### ISSUE TITLE
Unable to sync mail after installing it on Ubuntu 18.04

### ISSUE THREAD

**Issue by landiatico** [Foundry376/Mailspring#1002] opened 2018-07-31 05:21 UTC
##### Are there any related issues?

...

##### What operating system are you using?

Ubuntu 18.04 

##### What version of Mailspring are you using?
mailspring-1.3.0-amd64

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?

None

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

IBM SmartCloud

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...
Installed mailspring, run the wizard, and it stays in sync in progress, no emails are shown whatsoever and no network activity is being recorded. Did a .cap and after it syncs the folders it does nothing.

Is there any log I can enable in order to attach them to this issue?

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?

**Comment by vincentbeland** [comment] 2018-08-07 10:17
Same here. It just doesn't sync anymore. It says `Looking for more messages...` .

Thunderbird is fine with the same account settings.

**Comment by unnir** [comment] 2019-04-10 07:49
the same issue.

**Comment by CodeMouse92** [comment] 2021-02-02 03:15
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one of the ones we've already migrated to Discourse:

https://community.getmailspring.com/t/the-eternal-sync-bug/334/1

https://community.getmailspring.com/t/crash-on-sync-no-stack-trace/419

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-02 03:15 UTC
Labels: audit
