### ISSUE TITLE
Bug: Composer windows UI slow

### ISSUE THREAD

**Issue by howdev** [Foundry376/Mailspring#2215] opened 2020-11-30 09:28 UTC
**Describe the bug**
The controls and buttons appear slowly when you open composer, especially the controls at the bottom.  Even the signature slowly appear.  Also the change signature functions is slow to appear. 

**To Reproduce**
1. Go to 'top bar left hand corner'
2. Click on 'compose icon'
3. See everything loading slow

**Expected behavior**
all controls and buttons appear in a instant, not loading individual items.

**Setup: (please complete the following information):**
 - OS: Linux Mint 20
 - Mailspring Version: 1.7.8

**Comment by CodeMouse92** [comment] 2021-03-03 03:50
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/composer-windows-ui-slow/970

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@howdev: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-03 03:50 UTC
Labels: audit, bug
