### ISSUE TITLE
Closing Mailspring in Windows does not actually end its processes

### ISSUE THREAD

**Issue by palefire19** [Foundry376/Mailspring#1059] opened 2018-09-02 15:29 UTC
##### Are there any related issues?

This seems maybe related to general memory management issues like #566 that I also submitted. I would say in general the memory handling continues to be problematic. On Windows I've seen it get to up to about 1GB in memory usage and then not relinquish the memory when closed.

##### What operating system are you using?
Windows Version	10.0.17134 Build 17134

##### What version of Mailspring are you using?
Mailspring 1.4.2

--

**Bug?**

##### Is this an email sync or connection issue?

1. Run Mailspring for a while to spawn a variety of processes
2. Close Mailspring
3. 10 minutes later, open Task Manager and see that Mailspring is still there, using memory (see screenshot)
![capture](https://user-images.githubusercontent.com/4412269/44957752-6d36a480-aea3-11e8-9a23-3ca7fc56ec0c.PNG)

**Comment by bengotow** [comment] 2018-09-17 18:58
Hey! Can you try quitting Mailspring from it's menu or the shortcut in the system tray? By default closing the main window leaves it running and syncing your mail in the background - you'll still get new mail notifications, etc.

**Comment by palefire19** [comment] 2018-09-19 19:20
Hey, okay that seems to solve it. Not urgent but maybe we add an option in Windows for "Closing window quits application processes?"

**Comment by SrTobi** [comment] 2018-10-05 10:29
Yes, I was looking for that option as well. Normally these kind of application have an option "Stay open in background". Or you can bind it to the option "Show icon in menu bar / system tray" and quit the application if the tray icon is disabled.

I could try to make a PR, but not before someone of the dev team (@bengotow ?) has stated that such a behavior is wanted in some way.

**Comment by mbenoukaiss** [comment] 2019-12-22 21:49
Will an option like the one SrTobi mentioned ever be implemented?

**Comment by CodeMouse92** [comment] 2021-01-28 04:16
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/exit-on-x-button-with-no-minimize-to-tray/207/6

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 04:16 UTC
Labels: audit, windows
