### ISSUE TITLE
Mailspring does not add more than one email account

### ISSUE THREAD

**Issue by anacvignola** [Foundry376/Mailspring#1857] opened 2020-03-11 14:25 UTC
Mailspring does not add any other email account besides Gmail in this latest version(1.7.4) on Debian OS, but in Mailspring version 1.7.2 it works perfectly.
Outlook, riseup, Gmail accounts were tested.

**Comment by sarovin** [comment] 2020-03-11 18:50
Duplicate #1841

**Comment by allexlima** [comment] 2020-03-12 13:43
Same in Ubuntu 19.04 =(

**Comment by fitiavamamonjy** [comment] 2020-03-18 11:26
I have the same issue in ubuntu 18.04

**Comment by ElSenor64** [comment] 2020-03-20 18:42
I having the same issue trying to add my school Office 365 account on Ubuntu 19.10. I have done it before, so I know it works with this account. I tried it from the snap and from the .deb file, but to no avail. It says that it connected to the server successfully and that it is adding the account, but then it never actually does. I will be using Hiri in the meantime until the trial runs out.

**Comment by CarlosRebolledoA** [comment] 2020-03-20 22:00
Tengo versión Pro y 4 cuentas de correo, incluso una Outlook, pero no me deja agregar una nueva cuenta Outlook 

Extraño error y silencio absoluto de Ben 

Windows 10
1.7.4.

**Comment by ElSenor64** [comment] 2020-03-21 16:28
I just discovered that a fresh install of Mailspring from snap without Gmail account renders the same result as the issue @sarovin posted above. I tried to install 1.7.2, but Ubuntu 20.04 still has package problems about the python2 stack, so I'll have to wait to _really_ try it.

**Comment by Lubell** [comment] 2020-03-24 09:05
Same issue here for (1.7.4) on a fresh install.  I first tried to setup my Microsoft Exchange (using DavMail), which previously worked (1.7.2).  Two-step verification went through and everything seemed to work, but then no account was added.  I then setup my gmail account, which did **work**.  Every subsequent attempt to add other accounts (including another type of IMAP account) did not work.  It seems that everything except the last step of adding the account works though (e.g. contacting the exchange server was succesful).

System:
Host: ******* Kernel: 5.3.0-40-generic x86_64 bits: 64 compiler: gcc v: 7.4.0 
           Desktop: Cinnamon 4.4.8 wm: muffin dm: LightDM Distro: Linux Mint 19.3 Tricia 
           base: Ubuntu 18.04 bionic 

Machine:
Type: Laptop System: HP product: HP EliteBook 840 G6

**Comment by namerci** [comment] 2020-03-25 06:12
I have the same issue. The problem exists when you install mailspring from SNAP. Also, when you add accounts on SNAP installation, and account doesn't show up, then you will see them when you install `.deb` from website. It looks like mailspring have hardcoded path during adding accounts and that's why SNAP version didn't work well.

**Comment by justin-lacroix** [comment] 2020-03-26 15:57
same issue here on Ubuntu 18.04 LTS :/

**Comment by marcvk** [comment] 2020-03-27 16:16
I can confirm the issue, I just download mailspring 1.7.4 on Pop!_OS 19.10 (basically Ubuntu 19.10), and added my gmail account. I then wanted to add my office365 account. I can enter the usercode/password just fine, it tells me it adds it and then nothing. No error message, and no account added.

I downgraded to 1.7.2 and now I can add both accounts.

I installed via the .deb packages.

**Comment by Meunsy** [comment] 2020-03-27 18:16
I used the same workaround as marcvk, on Manjaro 19.0.2. I removed the snap 1.7.4 version to get the AUR 1.7.2 version (mailspring-libre), and everything works fine.

But I hope this will be fixed soon, to be able to keep it up to date through snap.

**Comment by lipe1966** [comment] 2020-04-01 17:44
I can attest that this happens in Ubuntu Budgie 19.10 and 20.04, snap or deb. the work around function well in 19.10, if you upgrade to 20.04 mailspring will be removed because of python2 dependency.

**Comment by bangau1** [comment] 2020-04-13 05:40
>  added my gmail account. I then wanted to add my office365 account. I can enter the usercode/password just fine, it tells me it adds it and then nothing. No error message, and no account added.

This also happened to me. I can add GSuite/Gmail account just fine, but when adding Office365 account, it shows nothing

**Comment by CodeMouse92** [comment] 2021-02-02 01:38
It appears that this issue has been resolved in a later release, so we are closing it. If the problem occurs again, please create a new thread in the appropriate category on our Discourse.

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. Learn more about the changes here.

We hope to see you there soon!

-The Mailspring Team

**Comment by CodeMouse92** [comment] 2021-02-02 01:39
Duplicate of #1841

**Closed by CodeMouse92** 2021-02-02 01:38 UTC
Labels: audit, mailserver-incompatibility, needs-reproduction
