### ISSUE TITLE
[Feature Request] Automatic Dark theme

### ISSUE THREAD

**Issue by lsonnino** [Foundry376/Mailspring#1748] opened 2019-12-24 12:45 UTC
Could it be possible to add a new theme choosing between dark and light depending on the system's theme on macOS Mojave and later ?
For instance light theme is better at day but dark theme is better for reading at night. macOS Catalina already has a feature that changes the theme depending on the time of the day. Is it possible for Mailspring to adapt it's with Catalina's ?

Thanks

**Comment by CodeMouse92** [comment] 2021-02-08 18:31
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/automatic-dark-theme/488

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@lsonnino: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-08 18:31 UTC
Labels: audit, enhancement

**Comment by bengotow** [comment] 2026-04-19 21:25
Good news — Mailspring 1.20.0 (April 2026) added an "Automatic" theme (now the default) that follows your operating system's light/dark mode setting! It also adds system accent color support. You should no longer need to manually switch themes when your OS changes modes. Let us know if you still see any areas that don't respond correctly.
