### ISSUE TITLE
Allow signatures to be the default for new messages / replies only

### ISSUE THREAD

**Issue by rizwank23** [Foundry376/Mailspring#1312] opened 2019-01-09 07:48 UTC
Hello

I am using mailspring in Ubuntu. I want to use Signature option. 

I have created 2 signatures, one for a new message and other for Replies/Forward.  So how can I select this..

In outlook, we have an option to select one signature for new message and other signature for reply/forward. I dont see that option here..

So can you help on this issue.

**Comment by MasterPCUK** [comment] 2019-01-29 15:46
+1 this would be a great addition! Pro subscriber here

**Comment by bengotow** [comment] 2019-03-17 17:09
Hey @rizwank23 thanks for reporting this! This would definitely be cool - I wasn't aware of that feature in Outlook but I think it'd definitely make sense. Right now you can choose a signature as the default for an account, but there's no way to select it for replies / new messages only.

**Comment by raffykim89** [comment] 2019-10-24 02:05
+1 Please...

**Comment by CodeMouse92** [comment] 2021-02-17 23:17
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/allow-signatures-to-be-the-default-for-new-messages-replies-only/676

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@rizwank23: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-17 23:17 UTC
Labels: audit, composer, product-direction
