### ISSUE TITLE
Activity notifications appear again after reboot

### ISSUE THREAD

**Issue by 29axe** [Foundry376/Mailspring#373] opened 2017-11-28 22:54 UTC
##### What operating system are you using?
Ubuntu Gnome 17.04

##### What version of Mailspring are you using?
1.0.8-5a847d0e

--

When opening MailSpring after starting my computer the notification bubble on the "activity" button (left to the search bar) shows "2" notifications even if I have already viewed them on a previous session.

To reproduce:
- Open MailSpring
- A red bubble appears on "activity" button showing 'n' notifications 
- Read the notifications on "activity" feed
- Notification bubble disappears (as expected)
- Restart computer
- Open MailSpring
- Notification bubble appears again showing the exact same number of notifications

I'm using 4 gmail accounts.

**Comment by laracabrera** [comment] 2017-11-29 18:49
Confirmed in Windows 10

### What operating system are you using?
Windows 10

### What version of Mailspring are you using?
1.0.8-5a837d0e

### How to reproduce:

1. Open MailSpring
2. A red bubble appears on "activity" button showing 'n' notifications
3. Read the notifications on "activity" feed
4. Notification bubble disappears (as expected)
5. Restart computer
6. Open MailSpring
7. Notification bubble appears again showing the exact same number of notifications

I'm using an IMAP account.

**Comment by iainheng** [comment] 2018-01-13 07:18
Same issue on Windows 10. Activity icon is glowing everytime mailspring is started.

**Comment by isochonium** [comment] 2018-01-13 11:54
**What operating system are you using?**
Arch Linux

**What version of Mailspring are you using?**
1.0.12-cf081332

Same issue - icon indicates new activity after every ﻿logout / reboot.

**Comment by grg2rsr** [comment] 2018-02-06 08:52
In Mailspring 1.1.2 (snap) on Ubuntu 17.10 as well

**Comment by amiller27** [comment] 2018-03-02 17:35
Same issue here in both Ubuntu 17.10 and Windows 10.  Number of notifications is cleared if I quit the application (i.e. ctrl-q) and reopen, but if I reboot without quitting the application, number of notifications is preserved

**Comment by sathiz1993** [comment] 2018-03-03 06:41
+1
OS Version - Linux Mint 18.3 Sylvia
Mailspring Version - 1.1.4-22d9f20d

**Comment by fcastilloec** [comment] 2018-04-04 08:43
The latest version (`v1.2.0`) has fixed this issue. Can @29axe try updating and if the issue is solved, closed this?

**Comment by bengotow** [comment] 2018-04-04 08:52
Awesome—thanks for verifying @fcastilloec. This makes sense because I rewrote part of this code to handle the new "don't show notifications for repeated opens/clicks" option in Preferences > General.

Going to go ahead and close this and we can re-open it if it happens again.

**Closed by bengotow** 2018-04-04 08:52 UTC
