### ISSUE TITLE
Emails in Draft folder not deleting

### ISSUE THREAD

**Issue by dipakcg** [Foundry376/Mailspring#661] opened 2018-02-08 04:54 UTC
— Mac OS: High Sierra 10.13.4 Beta (17E139j)
 — Mailspring Version 1.1.3 (1.1.3)

I've just noticed that emails in the _Draft_ folder is not deleting and staying in-tact.

<img src="http://g.recordit.co/4h68hWygGA.gif" />

Already tried restarting Mailspring app several times but that didn't help.

**Comment by karlodz** [comment] 2018-12-05 08:34
Anybody solved that issue with drafts no deleting? Any solution until now? 
I also stuck - no chance to delete drafts, messages just keep staying as is, nevertheless what clicked... pretty annoying and not expected, especially I paid for "full", "professional" version (subscription). Running latest version - "Version 1.5.3 (1.5.3)"

**Comment by PlayingKarrde** [comment] 2019-01-02 23:42
Also have this issue. Very annoying. Almost ready to try a different mail program due to this.

**Comment by dipakcg** [comment] 2019-01-03 02:08
_Software may have bugs_ but not giving it a priority nor a single update about it, is something I don't accept _(my personal thought)_. Disappointed 😞

Already moved to another mail client few months ago.

@karlodz If you've paid for this then ask their support trying alternate contact method.

**Comment by karlodz** [comment] 2019-01-07 11:08
> @karlodz If you've paid for this then ask their support trying alternate contact method. <

Tried that for previous requests (signature formatting bug/problems) but never got serious, concrete answer. Support with real issues is really questionable wit AirMail I believe. Maybe I'll wait for a while for a next update here but if it doesn't come soon, maybe you'd suggest some alternative client that works for you?   Thank you.

**Comment by dipakcg** [comment] 2019-01-07 14:05
@karlodz, Give [**Spark**](https://sparkmailapp.com) a try. That works well on my Mac as well as on iPhone without any issues.

**Comment by SethMMorton** [comment] 2019-04-04 05:28
Is this going to be addressed?

**Comment by PlayingKarrde** [comment] 2019-04-04 06:30
I gave up. Moved to Postbox unfortunately. Mailspring was really good but this bug was a dealbreaker for me and it looks like it's being ignored.

**Comment by SethMMorton** [comment] 2019-04-04 15:34
So... all of the alternate suggestions on this thread are Mac or Windows only. There isn't really anything that comes close to Mailspring on Linux that I can see.

**Comment by MehdiCHEBBAH** [comment] 2020-12-29 10:09
I have fixed this issue by enabling IMAP of the trash folder. (It was disabled by default in Gmail).

**Comment by CodeMouse92** [comment] 2021-02-04 18:58
Please be advised, *nothing* is "ignored" with Mailspring, but the GitHub Issue tracker has certainly gotten out of hand, wherein the sole primary maintainer, Ben Gotow, could not keep on top of it with his limited development time. (He works on Mailspring in addition to his full time job.)

It *appears* that this issue has been resolved by @MehdiCHEBBAH, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-04 18:58 UTC
Labels: audit
