### ISSUE TITLE
Bug: Automatic hyperlinking regex in plaintext mail incomplete

### ISSUE THREAD

**Issue by moeffju** [Foundry376/Mailspring#1823] opened 2020-02-27 11:51 UTC
**Describe the bug**

I have a plain text email containing a URL of the form "http://example.com/path/stra:strb". Mailspring only automatically hyperlinks it up to and including the second colon ("stra:"), when it should link the entire URL.

I'm guessing this might be special case handling for when people forget spaces after posting URLs, but I doubt that including the :/. makes sense in those cases - the token separator for URLs should just be whitespace or EOF.

**To Reproduce**
1. Send yourself a plaintext email containing the string "http://localhost/foo:bar hello"

**Expected behavior**
The full URL is automatically hyperlinked.

**Setup: (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - Mailspring Version: 1.7.4

**Comment by CodeMouse92** [comment] 2021-02-23 22:38
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/automatic-hyperlinking-regex-in-plaintext-mail-incomplete/750

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@moeffju: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-23 22:38 UTC
Labels: audit, bug
