### ISSUE TITLE
Bug: Error: SQLite: database disk image is malformed

### ISSUE THREAD

**Issue by queglay** [Foundry376/Mailspring#1871] opened 2020-03-20 22:21 UTC
**Describe the bug**
Upon opening mailspring, the error presents -'Error: SQLite: database disk image is malformed'
then it will close, reopent after a few seconds, and repeat.
I've had this problem on 3 different RHEL7 and Centos 7 installations and given up a few times (in the past 18 months).  I decided to pay for a subscription 2 days ago though and see if we can fix this problem somehow, I'd like to see it work.

I used the support form to get help, but got a bot response with nothing relevant and no way to speak to a person. For feedback it would be great if a subscription provided some better means of getting through to paid support.

**To Reproduce**
1. after registering my icloud email account, a gmail account and a bluehost IMAP account, I open mailspring.

**Expected behavior**
Open and remain stable.

**Screenshots**
![Screenshot from 2020-03-21 08-41-40](https://user-images.githubusercontent.com/4046493/77210362-bebf8680-6b50-11ea-91ab-40d5cedf476d.png)
![Screenshot from 2020-03-21 08-42-03](https://user-images.githubusercontent.com/4046493/77210368-c1ba7700-6b50-11ea-8e85-c212414502b7.png)
![Screenshot from 2020-03-21 08-42-59](https://user-images.githubusercontent.com/4046493/77210371-c3843a80-6b50-11ea-88d6-eb9aafbccaa3.png)

**Setup: (please complete the following information):**
 - OS: CENTOS 7
 - OS Version: CentOS Linux release 7.7.1908 (Core)
 - Mailspring Version: 1.7.2

**Comment by CodeMouse92** [comment] 2021-02-16 18:47
> I used the support form to get help, but got a bot response with nothing relevant and no way to speak to a person. For feedback it would be great if a subscription provided some better means of getting through to paid support.

Mailspring Pro has *never* offered "premium support" as part of the package. Your subscription helps cover the costs of the servers and APIs that enable pro features, and to help cover the high costs of security audits that allow us to work with different email services. Mailspring is still an independent software project, rather than a big product backed by a large company (Foundry376 just provides the administrative framework to even offer the subscription). In fact, Mailspring is primarily developed by one person — Ben Gotow — in addition to his full-time job. Manning the Zendesk would negate literally all of his development time indefinitely.

On top of all that, 2020 pretty much stalled all progress on Mailspring from the summer onward. It's finally restarted, however, and we released 1.8.0 recently with some major bug fixes.

*That* understood, we are working on improving our bug reporting. We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/error-sqlite-database-disk-image-is-malformed/651

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@queglay: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-16 18:47 UTC
Labels: audit, bug
