### ISSUE TITLE
Bug: With version 1.7.4 after paying for subscription link/view tracking icons still did not appear

### ISSUE THREAD

**Issue by evaldsurtans** [Foundry376/Mailspring#1840] opened 2020-03-03 22:18 UTC
After running out of a trial, I paid for a subscription, but did not get buttons in messages anymore..
Only visible for new messages.

MacOS Catalina
<img width="772" alt="image" src="https://user-images.githubusercontent.com/1777062/75825262-acea8f00-5dad-11ea-8939-eb735a2afe90.png">

**Comment by evaldsurtans** [comment] 2020-03-03 22:36
For new emails they are appearing, but sad that I lost them for previous emails after I ran out of trial

**Comment by bengotow** [comment] 2020-04-16 05:30
Hey @evaldsurtans thanks for reporting this! I will look into this tomorrow and see if I can reproduce this issue. You definitely shouldn't have lost the tracking data for your previous emails.

One possibility—in order to see the opens / link clicks on your sent mail, you need to be looking at the copy you sent. If you CC yourself or BCC yourself, or have the email arriving in another email account you own, those versions of the email won't show the tracking status.

**Comment by CodeMouse92** [comment] 2021-02-26 20:52
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/after-paying-for-subscription-link-view-tracking-icons-still-did-not-appear/845

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@evaldsurtans: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-26 20:52 UTC
Labels: audit, bug
