### ISSUE TITLE
Feature Request: Mailspring icon for light-colored system trays

### ISSUE THREAD

**Issue by DigiOhhh** [Foundry376/Mailspring#2212] opened 2020-11-28 17:06 UTC
This is how my system tray looks on KDE Plasma:

![Screenshot_20201128_175647](https://user-images.githubusercontent.com/37815914/100521396-b1f53700-31a3-11eb-9d86-2e2fea2d2ebf.png)

Notice the Mailspring icon, which is barely visible against the white background.

Can you add an option for light-colored panels such as mine? By selecting this option you would be able to toggle the icon color, which would go from white to black.

**Comment by CodeMouse92** [comment] 2021-02-20 03:48
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue is related to one we already migrated to Discourse:

https://community.getmailspring.com/t/implement-a-dark-tray-icon-for-light-themes/700/9

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@DigiOhhh: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-20 03:48 UTC
Labels: audit, enhancement
