### ISSUE TITLE
Can't configure archive folder for Gmail account?

### ISSUE THREAD

**Issue by doronbehar** [Foundry376/Mailspring#2151] opened 2020-09-22 17:19 UTC
##### What is the behavior you're seeing?

New mailspring user here. I setup my gmail account and I was surprised to note that I can't configure the "Archive" mailbox for gmail:

![Screenshot from 2020-09-22 20-05-40](https://user-images.githubusercontent.com/10998835/93915330-65026980-fcf7-11ea-8e7c-5ca5f1ebba3e.png)

I am able to configure this mailbox for the other accounts I've setup. This is particularly important to me as I have all of my unattended mailing lists messages in the default archive mailbox "[Gmail]/All Mail" and I want to use a different archive mailbox, just like my other mail clients (K9).

##### What email provider (Gmail, Exchange, etc.) are you trying to use?

Gmail

##### What operating system are you using?

NixOS

##### What version of Mailspring are you using?

1.7.8

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Irrelevant.

##### Other comments

Damn this application is beautiful! :heart_eyes:

**Comment by CarlosRebolledo** [comment] 2020-10-04 11:57
Only responses from Bot and where is the Mailspring manager and team?

Who knows what really happens with the development and continuity of Mailspring?

**Comment by CodeMouse92** [comment] 2021-02-12 21:49
2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/cant-configure-archive-folder-for-gmail-account/594

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@doronbehar: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-12 21:49 UTC
Labels: audit, bug, mailserver-incompatibility, needs-reproduction
