### ISSUE TITLE
Feature Request: Add app password instructions to Outlook

### ISSUE THREAD

**Issue by aidenmitchell** [Foundry376/Mailspring#1949] opened 2020-04-28 20:18 UTC
**Is your feature request related to a problem? Please describe.**
I tried to login with my Outlook account and it wasn't working, then I realized that I needed an app password.

**Describe the solution you'd like**
Similar to the instructions on the iCloud connection page, where it mentions the app password in case someone doesn't realize.

**Describe alternatives you've considered**
N/A

**Additional context**
Similar to this:
![image](https://user-images.githubusercontent.com/30846409/80533627-c8f45200-8952-11ea-9781-4517d2a8803b.png)

**Comment by CodeMouse92** [comment] 2021-03-01 22:38
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/add-app-password-instructions-to-outlook/889

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@aidenmitchell: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-01 22:38 UTC
Labels: audit, enhancement
