### ISSUE TITLE
Mailspring should store mail data in XDG_DATA_HOME, in accordance with the XDG Base Directory specification

### ISSUE THREAD

**Issue by jsbhat** [Foundry376/Mailspring#1755] opened 2020-01-03 18:35 UTC
##### Are there any related issues?

No

##### What operating system are you using?

Manjaro Linux 18.1.5

##### What version of Mailspring are you using?
(eg: 1.6.3 or 1.7.0 - this is shown in Mailspring's main menu.)

1.7.2-4522b259

**Bug?**

No 

##### Is this an email sync or connection issue?

No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

N.A

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

N.A

Mailspring doesn't seem to fully conform to the [XDG Base Directory specification ](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)because it puts user-generated data files like email attachments in that directory. Is it possible for Mailspring to make sure of `$XDG_DATA_HOME` for the data files? 

For now I have just [symlinked](https://foundry376.zendesk.com/hc/en-us/articles/115002016431-Can-I-change-where-Mailspring-stores-my-mail-) `$XDG_CONFIG_HOME/Mailspring` to `$HOME/.mailspring`

**Comment by bengotow** [comment] 2020-04-16 05:54
Hey! Ahh this would be really cool, but Mailspring's single "home" directory is a pretty baked in concept throughout the codebase. I'll keep this in mind though, I didn't realize there was an $XDG_DATA_HOME env var, actually!

**Comment by CodeMouse92** [comment] 2021-02-26 18:37
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mailspring-should-store-mail-data-in-xdg-data-home-in-accordance-with-the-xdg-base-directory-specification/833

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@jsbhat: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-26 18:37 UTC
Labels: audit, enhancement, linux
