### ISSUE TITLE
Exclude IMAP folders from syncing?

### ISSUE THREAD

**Issue by lkraav** [Foundry376/Mailspring#421] opened 2017-12-10 21:00 UTC
I'd like to configure a list of folders for Mailspring to ignore. Not seeing any IMAP folder subscription management ability in the UI at the moment.

##### Are there any related issues?

Searched "exclude", no match. Same for zendesk support kb db.

##### What operating system are you using?
Linux

##### What version of Mailspring are you using?
1.0.10

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Probably.

**Comment by bengotow** [comment] 2017-12-11 20:24
Hey! Thanks for filing this and checking the other support site - right now there isn't a way to exclude certain folders from sync. I'll see if we can add this soon. I'm overhauling the "Accounts" preferences tab and this really belongs there.

**Comment by gwelr** [comment] 2018-10-18 10:33
when can we expect  something here ? I have lots of emails in folders I don't want to have in my email client.

**Comment by Tomschi** [comment] 2019-02-13 19:07
I also think this is an useful feature. So it would be possible to exclude the office365 folders e.g. journal, contacts, ...

**Comment by NHRedAnt** [comment] 2019-02-14 15:38
I too really need this in order to use MailSpring.  

I have far too much email for it to be scanning all my folders.  The "main" process consumes 100% CPU on  a thread trying.  Nice mailer, but it's trying to do too much for me.

Thanks.

**Comment by superjacktr** [comment] 2019-06-27 19:17
So what's the progress with this? Scanning messages almost never stops for me and I need to exclude some big folders. Please up the priority on this!

**Comment by pnmcosta** [comment] 2019-07-23 09:27
This would be neat for me too! Especially cause of Office365!

**Comment by lkraav** [comment] 2019-07-23 10:53
Yeah, for me it's impossible to even trial Mailspring if I can't opt-out some mailboxes.

Unless the forever-indexing situation has somehow been resolved in the meanwhile.

**Comment by BrunoSpy** [comment] 2020-10-27 14:45
I too need this option : I do not need to sync old folders with thousands of emails (but I need to keep them on the server for other reasons).

**Comment by CodeMouse92** [comment] 2021-02-05 01:07
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/per-account-per-folder-sync-scan-cache-settings/474

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@lkraav: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-05 01:07 UTC
Labels: audit, enhancement
