### ISSUE TITLE
Add ability to delete a single message in a thread

### ISSUE THREAD

**Issue by 3v1n0** [Foundry376/Mailspring#426] opened 2017-12-11 15:50 UTC
##### What operating system are you using?
Ubuntu 16.04

##### What version of Mailspring are you using?
1.0.10

--

It's not possible to delete a single message from a thread, gmail has it, it would be nice to have the ability to delete a single message using the dropdown menu:

![immagine](https://user-images.githubusercontent.com/345675/33839712-fef3b7b4-de60-11e7-996f-b82dc7baccb0.png)

**Comment by readsquirrel** [comment] 2018-03-02 20:21
A definite +1 on this. It's odd to not be able delete an out of office response or other non-needed email from a thread. Thanks!

**Comment by dibley1973** [comment] 2018-11-07 09:20
Likewise I'd like to see this feature, as a couple of times I have had an email open in a thread and hit delete expecting it to delete _just_ the individual message and it has taken the whole thread with it! **_Arg!_**

**Comment by ilovecats516** [comment] 2019-01-16 02:59
This feature would be great!

**Comment by keithbaddeley** [comment] 2019-01-23 06:13
I agree too, this feature would be great. I use it to delete those out-of-office or automated replies from a thread and am really missing it in Mailspring.

**Comment by GrangeBeach** [comment] 2019-02-10 21:37
Please implement this - it has increasing become an issue in many long threads you get nowadays.

**Comment by oDevArc** [comment] 2019-02-26 08:56
yes nice feature to "clean" a conversation :-)

**Comment by castiboy** [comment] 2019-05-22 13:39
This feature is **essential** 🙄
I have a ton of "out of work on tuesdays" and "on holiday until next week" emails cluttering threads constantly.
Please add it 🙏

**Comment by jonathanmichel** [comment] 2019-05-31 13:10
Please add this feature 🙏. It is really frustrating to have all kind of useless mails in a thread, for example when a mail is just transferred or has an automatic reply.

Or at least an option to disable threads and sort the emails one by one.

**Comment by shchukax** [comment] 2019-10-11 13:21
In the linked (duplicate) issue #770 @bengotow wrote:

> ... the biggest blocker is that Mailspring's "conversation" UI doesn't have a selected message concept yet.

You don't need this concept.  There's already an ability to reply to a specific message in a thread.  On each message in a conversation, there's a dropdown with actions "Reply", "Reply All" and "Forward".  It's totally natural to have another action "Delete".

**Comment by rfparedes** [comment] 2020-05-27 20:25
+1.  I've just started using and paying for this and this is the first thing that's bugging me about the product.

**Comment by CodeMouse92** [comment] 2021-01-28 01:19
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/delete-a-single-message-in-a-thread/320/1

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@3v1n0: if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 01:19 UTC
Labels: audit, enhancement
