### ISSUE TITLE
Sync settings and bring Mailspring to other devices

### ISSUE THREAD

**Issue by fgadaleta** [Foundry376/Mailspring#2132] opened 2020-08-29 05:58 UTC
**Is your feature request related to a problem? Please describe.**
I want to bring all settings (accounts, signatures, etc.) with me to other devices.

**Describe the solution you'd like**
A sync-settings button to export settings to github gist or similar and sync back. Even export settings to file and manually import from another device, would be great.

**Comment by CodeMouse92** [comment] 2021-01-28 03:27
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/sync-templates-signatures-accounts-etc-accross-multiple-devices/265/1

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 03:27 UTC
Labels: audit, enhancement
