### ISSUE TITLE
Move from 32 Bit Windows binaries to 64 Bit

### ISSUE THREAD

**Issue by AluminiumTech** [Foundry376/Mailspring#797] opened 2018-04-03 22:42 UTC
##### Are there any related issues?

...

##### What operating system are you using?
Windows 10 Build 16299 64 Bit

##### What version of Mailspring are you using?
1.2.0

--
**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

I'm proposing that the Windows binaries for Mailspring should be 64 Bit by default with 32 Bit as an option for those who need it.

![mail](https://user-images.githubusercontent.com/14107316/38279487-7240b024-3798-11e8-92ce-8e02465d7292.PNG)

**Comment by bengotow** [comment] 2018-04-04 01:33
Hey! Mailspring doesn't use enough memory for 64 vs 32 bit to really matter (the 32-bit compatibility built in to Windows is really great - there isn't really any performance impact to running 32-bit apps) but I'm definitely looking to do this once the majority of machines are 64-bit. Stay tuned!

**Comment by CodeMouse92** [comment] 2021-02-15 20:58
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this discussion to the Development section of Discourse:

https://community.getmailspring.com/t/64-bit-windows-binary/628

Please consider joining that community and continuing the discussion there!

@AluminiumTech: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-15 20:58 UTC
Labels: audit, product-direction
