### ISSUE TITLE
Bug:  Error during the syncing with yandex

### ISSUE THREAD

**Issue by ovgeorge** [Foundry376/Mailspring#2052] opened 2020-06-10 22:47 UTC
**Describe the bug**
Happens in the middle or work, initially mail is working fine

**To Reproduce**
1. Just work some time
2. Try any action
3. Ger error about syncing -- synchronization error with yandex.ru
4. See error. Close app, start again and you can work with it for some time

**Expected behavior**
Just syncing mail

**Setup: (please complete the following information):**
 - OS: macOS
 - OS Version 10.15.4 (19E287)
 - Mailspring Version: 1.7.8 (1.7.8)

**Additional context** 
Mailspring Version: 1.7.8-13635bcf
Platform: darwin
Account State: sync_error
Account Provider: yandex
IMAP Server: imap.yandex.com
SMTP Server: smtp.yandex.com
--------------------------------------------
*** in mailsync  exceptions::logCurrentExceptionWithStackTrace()
*** in mailsync  runBackgroundSyncWorker()
*** in mailsync  main::$_6::operator()() const
*** in mailsync  void* __thread_proxy(void*)
*** in mailsync  thread_start()
***

7266 [2020-06-11 01:40:28.909] [main] [info] Identity created at 1579206750 - using ID Schema 1
7266 [2020-06-11 01:40:28.910] [main] [info] ------------- Starting Sync (ovgeorge@yandex.ru) ---------------
7266 [2020-06-11 01:40:28.915] [metadata] [info] Metadata delta stream starting...
7266 [2020-06-11 01:40:32.916] [background] [info] Marking all folders as `busy`
7266 [2020-06-11 01:40:32.917] [background] [info] Syncing folder list...
7266 [2020-06-11 01:40:33.124] [background] [info] Syncing folder list...
7266 [2020-06-11 01:40:33.374] [foreground] [info] syncFolderUIDRange for INBOX, UIDs: 23201 - 23341, Heavy: false
7266 [2020-06-11 01:40:33.405] [background] [info] syncFolderUIDRange for &BBAEQARFBDgEMg-, UIDs: 9535 - 10285, Heavy: true
7266 [2020-06-11 01:40:33.446] [foreground] [info] - remote=101, local=101
7266 [2020-06-11 01:40:33.449] [foreground] [info] Idling on folder INBOX
7266 [2020-06-11 01:40:43.912] [metadataExpiration] [info] Scanning for expired metadata
7266 [2020-06-11 01:40:43.912] [metadataExpiration] [info] -- Will wake for next expiration in 7200sec
7266 [2020-06-11 01:40:48.715] [calContacts] [critical] 
***
*** Mailspring Sync 
*** An exception occurred during program execution: 
*** {"debuginfo":"https://yandex.ru/","key":"Stream error in the HTTP/2 framing layer","retryable":false,"what":"std::exception"}
***

7266 [2020-06-11 01:40:48.715] [calContacts] [critical] *** Stack trace (line numbers are approximate):
*** in mailsync  ValidateRequestResp(CURLcode, void*, string)
*** in mailsync  PerformRequest(void*)
*** in mailsync  DAVWorker::performXMLRequest(string, string, string)
*** in mailsync  DAVWorker::resolveAddressBook()
*** in mailsync  DAVWorker::runContacts()
*** in mailsync  DAVWorker::run()
*** in mailsync  runCalContactsSyncWorker()
*** in mailsync  main::$_7::operator()() const
*** in mailsync  void* __thread_proxy(void*)
*** in mailsync  thread_start()
***

7266 [2020-06-11 01:40:48.715] [calContacts] [error] Suspending sync for 90min - unlikely a retry would resolve this error.
7266 [2020-06-11 01:41:16.793] [background] [info] - remote=748, local=137
7266 [2020-06-11 01:41:16.814] [background] [critical] 
***
*** Mailspring Sync 
*** A JSON exception occurred during program execution: 
*** [json.exception.type_error.316] invalid UTF-8 byte at index 1: 0xA3
***

7266 [2020-06-11 01:41:16.855] [background] [critical] *** Stack trace (line numbers are approximate):
*** in mailsync  exceptions::logCurrentExceptionWithStackTrace()
*** in mailsync  runBackgroundSyncWorker()
*** in mailsync  main::$_6::operator()() const
*** in mailsync  void* __thread_proxy(void*)
*** in mailsync  thread_start()
***

**Comment by CodeMouse92** [comment] 2021-02-11 22:11
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/error-during-the-syncing-with-yandex/572

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@ovgeorge: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-11 22:11 UTC
Labels: audit, bug
