### ISSUE TITLE
[Feature request] Use Thunderbird's autoconfig algorithm

### ISSUE THREAD

**Issue by notpushkin** [Foundry376/Mailspring#1483] opened 2019-05-03 14:32 UTC
First of all, thanks for the best email client out there :) Here's an idea for your consideration:

When setting up an account in Thunderbird, a fairly simple [autoconfig algorithm][1] is used, tldr:

1. Check `https://autoconfig.<domain>/mail/config-v1.1.xml?emailaddress=<address>`
2. Check Mozilla's own ISPDB at `https://autoconfig.thunderbird.net/v1.1/<domain>` (also look up domain's MX records)
3. Try some common names like `imap.<domain>` or `mail.<domain>`

This makes setting up IMAP/SMTP a lot easier – you just have to write your email and password and you're done. Definitely not something you need every day but it still would be nice to have it implemented in Mailspring as well.

[1]: https://developer.mozilla.org/en-US/docs/Mozilla/Thunderbird/Autoconfiguration

##### Are there any related issues?

None AFAIK

##### What operating system are you using?

Linux

##### What version of Mailspring are you using?

1.6.1

##### Does this feature exist in another mail client or tool you use?

Thunderbird, obviously :)

**Comment by bengotow** [comment] 2019-05-26 19:21
Hey! This would be great - we actually pulled down Thunderbird's database (which is also used by Mailcore) and put it into the app here: https://github.com/Foundry376/Mailspring/blob/master/app/internal_packages/onboarding/lib/mailcore-provider-settings.json#L1. Right now the app makes a DNS request for MX records of your email accocunt's domain, and then tries to match the MX record to one of those known providers. It works /most/ of the time, but I think we could definitely do better by implementing a realtime lookup to their ISPDB! Will see if we can do this sometime soon!

**Comment by CodeMouse92** [comment] 2021-02-25 23:39
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/use-thunderbirds-autoconfig-algorithm/805

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-25 23:39 UTC
Labels: audit, enhancement
