### ISSUE TITLE
Bug: Two factor Authentication 

### ISSUE THREAD

**Issue by fx11111** [Foundry376/Mailspring#2146] opened 2020-09-17 18:12 UTC
I'm having issues adding office 365 University account that has two-factor authentication on. On Thunderbird, I was able to login using oauth2 however I don't like the UI of Thunderbird which is why I keep going back to MailSpring hoping to see oauth2 on MailSpring

**Comment by CodeMouse92** [comment] 2021-02-23 22:58
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/o365-oauth-an-unknown-error-has-occurred-mailsync-3765269347/698

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@fx11111: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-23 22:58 UTC
Labels: audit, bug
