### ISSUE TITLE
[Feature Request] Ability to save Reading Panel layout dimensions

### ISSUE THREAD

**Issue by mscott5861** [Foundry376/Mailspring#1449] opened 2019-04-02 20:27 UTC
Similar to [Feature Request #1350](https://github.com/Foundry376/Mailspring/issues/1350), I'd like the ability to save my two-panel layout dimensions. Unlike the previous request, I prefer a less dense email list panel, so I have to drag my reading panel over to the left every time I open Mailspring.

Maybe auto-saving the dimensions of the layout every time it's adjusted would handle this?

And also, thanks to everyone involved for the most gorgeous and best email client out there. I've got it installed on every system I have.

**Comment by CodeMouse92** [comment] 2021-02-10 23:50
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/ability-to-save-reading-panel-layout-dimensions/563

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@mscott5861 if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-10 23:50 UTC
Labels: audit
