### ISSUE TITLE
can't install on debian testing, mailspring : Depends: gir1.2-gnomekeyring-1.0 but it is not installable

### ISSUE THREAD

**Issue by duriantang** [Foundry376/Mailspring#998] opened 2018-07-27 18:42 UTC
```console
$ sudo apt install ./mailspring-1.3.0-amd64.deb                     
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'mailspring' instead of './mailspring-1.3.0-amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mailspring : Depends: gir1.2-gnomekeyring-1.0 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

```
$ neofetch                                                         
       _,met$$$$$gg.         
    ,g$$$$$$$$$$$$$$$P.       ----------------------- 
  ,g$$P"     """Y$$.".        OS: Debian GNU/Linux testing (buster) x86_64 
 ,$$P'              `$$$.     Host: Inspiron 7370 
',$$P       ,ggs.     `$$b:   Kernel: 4.17.0-1-amd64 
`d$$'     ,$P"'   .    $$$    Uptime: 52 mins 
 $$P      d$'     ,    $$P    Packages: 2733 (dpkg) 
 $$:      $$.   -    ,d$$'    Shell: zsh 5.5.1 
 $$;      Y$b._   _,d$P'      Resolution: 1920x1080 
 Y$$.    `.`"Y$$$$P"'         DE: GNOME 3.28.3 
 `$$b      "-.__              WM: GNOME Shell 
  `Y$$                        WM Theme: Adapta-Eta 
   `Y$$.                      Theme: Adapta-Eta [GTK2/3] 
     `$$b.                    Icons: Papirus [GTK2/3] 
       `Y$$b.                 Terminal: tilix 
          `"Y$b._             CPU: Intel i7-8550U (8) @ 4.000GHz 
              `"""            GPU: Intel UHD Graphics 620 
                              Memory: 3342MiB / 15784MiB 
```

**Comment by duriantang** [comment] 2018-07-27 18:46
`gir1.2-gnomekeyring-1.0` removed from testing.

https://tracker.debian.org/pkg/libgnome-keyring

**Comment by stefaca** [comment] 2018-09-16 17:35
gir1.2-gnomekeyring-1.0 can be found in SID but please, do not make us to use SID packages :( Is there any chance that you can fix dependency issue?

**Comment by zeph** [comment] 2019-02-07 09:24
yeah, would love to get back using MailSpring

guys, you seem overwhelmed with tickets... make it a PRO pay software, and fix the bugs... we (I at least) love it... and I need Exchange, Calendar, GPG to work. You have the best indexing/search solution ever. Please, get money and hire some more workforce

**Comment by luqasz** [comment] 2019-03-25 16:56
Debian `buster` is in freeze and will become stable release.

**Comment by stefaca** [comment] 2019-05-15 19:22
> Debian `buster` is in freeze and will become stable release.

Which is not going to solve problem.

**Comment by bengotow** [comment] 2019-07-04 13:26
Hey folks—it looks like they deprecated gnome-keyring in favor of libsecret, and we actually already use libsecret. Libsecret just maps to your underlying keyring, and I think that Mailspring installs gnome-keyring to ensure that you have at least /some/ keyring installed on your system.

Could you try installing the dpkg manually and force-ignoring that dependency? The app may just work, and we need to update the package config to mark that the dependency is optional.

Actually, it looks like we may install gnome-keyring to ensure that you have /some/ keyring on your system. Could you try to download the deb and run:

```
wget https://github.com/Foundry376/Mailspring/releases/download/1.6.3/mailspring-1.6.3-amd64.deb
sudo dpkg -i --ignore-depends=gir1.2-gnomekeyring-1.0 mailspring-1.6.3-amd64.deb
```

**Comment by geonnave** [comment] 2019-07-06 17:31
@bengotow thanks, your solution worked on my Debian 10!

I also had to install the following packages that mailspring depends on:

```
sudo apt install libsecret-1-dev gvfs gvfs-bin gconf2
```

**Comment by geonnave** [comment] 2019-07-07 14:26
Ooops, I just noticed, now debian complains about unmet dependencies:

```
$ sudo apt install httpie
Reading package lists... Done
Building dependency tree       
Reading state information... Done
httpie is already the newest version (0.9.8-2).
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 mailspring : Depends: gir1.2-gnomekeyring-1.0 but it is not installable
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

Any suggestions to ignore that too? (if I run `apt --fix-broken install`, mailspring gets removed :disappointed:)

**Comment by jimblue** [comment] 2019-07-31 11:35
Please add Debian Buster support :)

**Comment by wop** [comment] 2019-09-04 18:47
You can ignore the dependency this way:
dpkg --ignore-depends=gir1.2-gnomekeyring-1.0 -i mailspring-x.x.x-amd64.deb

That works for me in Debian Buster

**Comment by zeph** [comment] 2019-10-09 13:56
Il giorno mer, 04/09/2019 alle 11.48 -0700, wop ha scritto:
> You can ignore the dependency this way:
> dpkg --ignore-depends=gir1.2-gnomekeyring-1.0 -i mailspring-x.x.x-
> amd64.deb
> That works for me in Debian Buster

$ sudo dpkg --ignore-depends=gir1.2-gnomekeyring-1.0 -i
~/Downloads/mailspring-1.6.3-amd64.deb

worked as well for me on Devuan Beowulf, thanks for the heads up wop!

best,
GMS

**Comment by Labohkip81** [comment] 2020-02-21 11:47
This works for me.

**Comment by CodeMouse92** [comment] 2021-02-09 21:48
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/cant-install-on-debian-testing-mailspring-depends-gir1-2-gnomekeyring-1-0-but-it-is-not-installable/527

Please consider joining that community and continuing the discussion there! (It's marked resolved, as the above appears to be for an old version of Mailspring, and subsequently resolved.)

@duriantang @geonnave @wop: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-09 21:48 UTC
Labels: audit, linux
