### ISSUE TITLE
cannot setup IMAP account - Authentication error for SMTP

### ISSUE THREAD

**Issue by sedghi** [Foundry376/Mailspring#811] opened 2018-04-06 17:28 UTC
Hi all, 
I'm getting authentication error for setting up my school's email on my Ubuntu machine. I tried Thunderbird and I could successfully setup my account but in mailspring it gives authentication error. I have put the log file at the end of this message

##### What operating system are you using?
Ubuntu 16.04 LTS
##### What version of Mailspring are you using?
mailspring 1.2.1-7e7447b6

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

----------SMTP----------
220 *** ESMTP Sendmail 8.14.8/8.14.8; Fri, 6 Apr 2018 13:19:11 -0400 (EDT)
EHLO ****
250-**** Hello ****** pleased to meet you
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-8BITMIME
250-SIZE
250-DSN
250-STARTTLS
250-DELIVERBY
250 HELP
STARTTLS
220 2.0.0 Ready to start TLS
EHLO *****
250****** Hello *******, pleased to meet you
250-ENHANCEDSTATUSCODES
250-PIPELINING
250-8BITMIME
250-SIZE
250-DSN
250-DELIVERBY
250 HELP
AUTH PLAIN c2VkZ2hpAHNXXXXXQBzYWRvaGFzaHRhZG84QA==
500 5.5.1 Command unrecognized: "AUTH PLAIN c2VkZ2hpAHNXXXXXQBzYWRvaGFzaHRhZG84QA=="

SMTP Last Response Code: 500

SMTP Last Response: 5.5.1 Command unrecognized: "AUTH PLAIN c2VkZ2hpAHNXXXXXQBzYWRvaGFzaHRhZG84QA=="

mailsmtp Last Error Code: 1

mailsmtp Last Error Location: 10

**Comment by DavidIRoitman** [comment] 2018-04-29 10:28
I have the same problem.

**Comment by ulriknyman** [comment] 2018-06-06 13:08
I have the same problem. 
Mailspring version: 1.2.2
Ubuntu 18.04
I have for a long time used Thunderbird with the same account and cannot authenticate to the SMTP server with Mailspring.

**Comment by WCSLoschy** [comment] 2018-06-08 12:42
Same issue Ubuntu 16.04 -- Has there been any update from the team as to whether they will address this soon? This is a pretty big show-stopping issue.

**Comment by WCSLoschy** [comment] 2018-06-08 12:59
I just checked - also occurs on windows build

**Comment by leebostock** [comment] 2018-06-21 08:52
I have the same problem. Mailspring 1.2.2, an older version of Ubuntu 14.04. Since you (or at least I) can't get past the setup screen without having it all completed there's no way of using the software at all.

**Comment by bengotow** [comment] 2018-08-06 07:51
Hey folks—thanks for reporting this. @sedghi , do you know if your university network doesn't require authentication at all to send email? It seems like the SMTP server is responding without the "AUTH" capability, which I don't think I've ever seen. Mailspring is essentially trying to log in and the server doesn't know what that command means.

I'll see if I can reproduce this with

**Comment by sedghi** [comment] 2018-08-07 13:40
@bengotow 
Thanks for responding
I checked my SMTP settings in the Thunderbird (which works with my university email) and got the following for the SMTP settings:
Authentication method: normal password
Connection Security: STARTTLS

**Comment by sansense** [comment] 2019-02-18 11:47
Any update on this as I am having the same issue.

**Comment by lhoggatt17** [comment] 2019-10-29 04:48
Having same issue, getting a `SMTP Last Response Code: 535` error when trying to authenticate.

**Comment by tlearyus** [comment] 2020-03-01 02:55
I am having the same issue with the Windows App. 

100% sure my IMAP server and account details are correct.

**Comment by Zalext** [comment] 2020-11-01 19:49
Hi,

One more here, SMTP Access Error.

Tested on 1.78 | 1.61 | 1.53
All the same on every version.


OS: W7 SP1
Opera Mail works fine for many accounts and all SMTP Ports.



Thank you.

**Comment by CodeMouse92** [comment] 2021-02-09 22:59
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/cannot-setup-imap-account-authentication-error-for-smtp/534

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@sedghi @Zalext: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-09 22:59 UTC
Labels: audit
