### ISSUE TITLE
[Feature Request] Avatar and/or Profile Icon

### ISSUE THREAD

**Issue by christophlandon** [Foundry376/Mailspring#213] opened 2017-10-20 00:35 UTC
Are there any related issues?

N/A

...

What operating system are you using?

MacOS 10.12.6

...

What version of Mailspring are you using?

1.0.5

...

Bug?

Do you have any third-party plugins installed? If so, which ones?

N/A

...

Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

N/A

...

Is the issue reproducible with a particular attachment, message, signature, etc?

N/A

...

Feature Request?
Does this feature exist in another mail client or tool you use?

Please add an avatar and/or profile icon next to each senders email addy. This has become an industry standard, it seems to slow me down without it. Visually, it's a good thing and speeds up the work flow. An enable/disable feature can be added to the Preferences.

Thanks!

**Comment by Chinney** [comment] 2018-02-24 12:11
Try this:
https://github.com/emadow/mailspring-avatars

But consider this:
https://github.com/emadow/mailspring-avatars/issues/3

I would like hitchhike this feature request: I have hacked the plugin above so it works like a charm in the email list. However I havn't found a way to replace the `default-profile-image` in the sidebar. Is there a way, a registry I could make to use the list icon in the sidebar?

I am browsing your code for 2 hours now and a little insight would be highly appreciated.

**Comment by CodeMouse92** [comment] 2021-02-08 19:08
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/avatar-profile-icon-on-inbox/494/2

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@christophlandon @Chinney: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-08 19:08 UTC
Labels: audit, enhancement
