### ISSUE TITLE
[Feature request] More distinction in notification icon

### ISSUE THREAD

**Issue by raqua** [Foundry376/Mailspring#665] opened 2018-02-08 13:44 UTC
I would like to make it more obvious that there are some new emails in my mailbox. Right now, the icons are just too similar, it is hard to tell the difference. 
My preferred solution would be to keep the empty mailbox icon as it is and if there is a new message, add a big red number on unread messages instead of the icon. Different color would certainly help.
Thanks for considering.

**Comment by bengotow** [comment] 2018-02-09 21:44
I think this sounds great - on macOS the icon turns blue when there are new messages, but we don't do that on Linux or Windows. I'll see if we can improve this in the future.

**Comment by fcastilloec** [comment] 2018-02-14 20:39
I'm using Ubuntu 16.04 and installing the deb packages. This is the only thing that's preventing me from using Mailspring as my main email client. Currently, I have to run two clients, Geary and Mailspring. Geary is running only so I can get notifications from my emails.

The problem with Linux is that we don't get any notification icon difference at all. The problem was reported before on issue #411 
You could even see on [this comment ](https://github.com/Foundry376/Mailspring/issues/411#issuecomment-352596511) that previous version attempted to load a notification icon unsuccessfully, the latest versions don't even try.

I tried installing Mailspring from snap and deb on Ubuntu 17.10 and still no notification badge. You can see this screenshot showing a new email but no badge 
![screenshot from 2018-02-14 12-09-12](https://user-images.githubusercontent.com/1280530/36226901-3f6b0800-119d-11e8-874b-7c65602f57c3.png)

**Comment by murakami-marco** [comment] 2018-08-01 18:12
Hi team!! Any news on this issue??? I have the latest version and still have this not fix.

Using KDE Neon 15.3.2

**Comment by mickaellecolazet** [comment] 2019-06-27 11:39
Same here.
An icon on system tray with the number of unread mail could be great.

**Comment by CodeMouse92** [comment] 2021-02-20 03:54
It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-20 03:54 UTC
Labels: audit, enhancement
