### ISSUE TITLE
Provide VIP feature

### ISSUE THREAD

**Issue by Ads20000** [Foundry376/Mailspring#970] opened 2018-07-07 09:21 UTC
There's no way of creating VIP contacts to get to their emails more easily, at the moment. See [here](https://www.techlicious.com/how-to/never-miss-an-important-email-on-your-smartphone/) for how this could work.

##### Are there any related issues?

Not as far as I'm aware.

##### What operating system are you using?
```
$ snap version
snap    2.34
snapd   2.34
series  16
ubuntu  18.04
kernel  4.15.0-25-generic
$ snap info core
tracking:     beta
refresh-date: yesterday at 18:45 BST
installed:   16-2.34   (5001) 91MB core
```

##### What version of Mailspring are you using?
```
$ snap info mailspring
tracking:     stable
refresh-date: 31 days ago, at 14:24 BST
installed:   1.2.2 (216) 164MB -
```

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Not one I use personally, but [apparently it does exist in other mail clients](https://www.techlicious.com/how-to/never-miss-an-important-email-on-your-smartphone/).

**Comment by bengotow** [comment] 2018-07-08 07:00
This is definitely a cool idea—the only mail client I'm aware of that does this is Apple Mail, where you can add people to a "VIP" list on mobile and then... I think you get email notifications from them even when the phone is in do-not-disturb? Would be cool to have a separate "priority" inbox for these folks.

**Comment by mabras** [comment] 2020-12-04 23:44
> the only mail client I'm aware of that does this is Apple Mail, where you can add people to a "VIP" list on mobile and then... I think you get email notifications

Is there any alternative to this right now?

**Comment by CodeMouse92** [comment] 2021-02-25 00:55
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/vip-contacts-feature/775

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@Ads20000: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-25 00:55 UTC
Labels: audit, enhancement, product-direction
