### ISSUE TITLE
Bug: header-toggle-control in wrong place for reminders

### ISSUE THREAD

**Issue by asparc** [Foundry376/Mailspring#2019] opened 2020-05-25 15:19 UTC
**Describe the bug**
When a reminder of a message is triggered, that message appears in the inbox with an additional header, the `send-reminders-header`. This header causes the `header-toggle-control` element to appear in the wrong place, i.e., it appears in the header, while it should be in front of the sender's name. 

This can be solved in css with:

    .send-reminders-header ~ .header-toggle-control {
        top: 57px !important;
    }

**Comment by CodeMouse92** [comment] 2021-03-02 00:37
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/header-toggle-control-in-wrong-place-for-reminders/903

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 00:37 UTC
Labels: audit, bug
