### ISSUE TITLE
Show labels of individual Gmail emails

### ISSUE THREAD

**Issue by jpbaril** [Foundry376/Mailspring#729] opened 2018-02-26 21:58 UTC
##### Are there any related issues?

Did not find

##### What operating system are you using?
Ubuntu Linux 17.10

##### What version of Mailspring are you using?
1.1.4

**Bug?**
No, it's an enhancement.

##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Yes, Gmail

**Feature Request?**
Yes

##### Does this feature exist in another mail client or tool you use?
Yes

----------------------------------------------------

For an individual Gmail email from a thread, If we click the arrow to expand the from header it shows for most emails that it is in the "All messages" folder. That's not really useful.

It would be more useful to see the labels that apply to that individual email. Use case: Not all my emails from a thread have the same labels applied to them. So for now it's impossible to see which individual email has of one or many of the labels Mailspring shows at the top of the thread.

Related to other issue I created: https://github.com/Foundry376/Mailspring/issues/730

**Comment by bengotow** [comment] 2018-03-06 23:44
Hey! The Gmail IMAP interface exposes labels as a per-message attribute but Gmail's official apps / UI don't show per-message labels since they're a concept intended for thread organization. We could display the raw X-GM-Labels attribute from IMAP on each message, but it might just be confusing. Gonna leave this open and see if anyone else has thoughts about this.

**Comment by CodeMouse92** [comment] 2021-02-17 23:33
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/show-labels-of-individual-gmail-emails/680

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@jpbaril: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-17 23:33 UTC
Labels: audit, product-direction
