### ISSUE TITLE
Bug: Attachment Name not correct

### ISSUE THREAD

**Issue by MartinHengstberger** [Foundry376/Mailspring#2023] opened 2020-05-26 14:39 UTC
**Describe the bug**
The name of the attachment isnt decoded correctly.  

I got a mail with an attachment "Übersicht.png" but it is shown as "Ãœbersicht.png". 

The sourcecode of the mail is:

> Content-Type: image/png;
> name="=?UTF-8?Q?=c3=9cbersicht=2epng?="
> Content-Transfer-Encoding: base64
> Content-Disposition: attachment;
> filename*=UTF-8''%C3%9C%62%65%72%73%69%63%68%74%2E%70%6E%67  

**Expected behavior**
The attachment should be shown as "Übersicht.png" but instead the name is "Ãœbersicht.png"

**Setup: (please complete the following information):**
 - OS: Windows 10 and Manjaro
 - Mailspring Version: ex: 1.7.8

**Comment by CodeMouse92** [comment] 2021-02-23 22:09
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/attachment-name-not-correct/746

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@MartinHengstberger: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-23 22:09 UTC
Labels: audit, bug
