### ISSUE TITLE
Takes too long to sync all emails (been 3 days). And while it sync, it slow down the other processes.

### ISSUE THREAD

**Issue by patelom** [Foundry376/Mailspring#1007] opened 2018-08-06 05:32 UTC
##### Are there any related issues?

[Feature Request] Don't Sync All of All Mail: https://github.com/Foundry376/Mailspring/issues/222

##### What operating system are you using?
Windows 10

##### What version of Mailspring are you using?
1.3.0

**Bug?**

##### Description

In Mailspring, email sync takes a lot of time to complete (thought we have lots of emails on the server and we use IMAP. **On one machine, its syncing since last 3 days**). The main problem is related to the system slowdown. **While the syncing process is going on, everything starts to operate slow.** Its very difficult to work on other heavy applications like Excel and Chrome, as majority of resources are consumed by Mailspring. 

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

**Feature Request?**

Allow user to selectively sync the emails. For instance, when I first add my account to the Mailspring,  I should be able to just sync emails of last week.

**Comment by CodeMouse92** [comment] 2021-01-28 03:31
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/the-eternal-sync-bug/334

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 03:31 UTC
Labels: audit
