### ISSUE TITLE
Bug: Can't add icloud on Windows

### ISSUE THREAD

**Issue by kyrstannie** [Foundry376/Mailspring#2114] opened 2020-08-06 02:48 UTC
When trying to add an iCloud account on Windows, I get an error message:
An unknown error has occurred (mailsync: 1)View Log

Waiting for Account JSON:

Waiting for Identity JSON:
info: Identity created at 1577226352 - using ID Schema 1

OPENSSL_Uplink(51FAD878,08): no OPENSSL_Applink

**Setup: (please complete the following information):**
-  Windows 10
 - Mailspring Version 1.7.8

![Error](https://user-images.githubusercontent.com/39582715/89485019-3562c680-d776-11ea-9266-3b580ff0f3ab.png)

**Comment by hacker1024** [comment] 2020-10-05 11:55
Duplicate of #2049

**Comment by CodeMouse92** [comment] 2021-02-08 19:27
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/cant-add-icloud-no-openssl-applink/497

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-08 19:27 UTC
Labels: audit, bug
