### ISSUE TITLE
Feature Request: Run as minimized on startup

### ISSUE THREAD

**Issue by tilda** [Foundry376/Mailspring#1953] opened 2020-04-29 11:32 UTC
**Is your feature request related to a problem? Please describe.**
Whenever I restart my PC I usually don't like having applications start up and be in my face so suddenly.

**Describe the solution you'd like**
I would like to have Mailspring just run on startup without opening a window.

**Describe alternatives you've considered**
None, I'm pretty sure this is not in the settings. I don't want to disable the open on startup feature.

**Additional context**
*N/A*

**Comment by ukrsup** [comment] 2020-05-02 08:30
In my Linux Mint 19.3 (LDME4) it runs in minimized mode on system startup

**Comment by tilda** [comment] 2020-05-02 10:34
Interesting, I'm on Windows 10 build 2004 and I see the window every time I start up my PC. Is there already a setting for this?

**Comment by Sov3rain** [comment] 2020-07-05 13:00
Windows 1909 here. Mailspring starts full screen, which is VERY annoying. I didn't found any setting outside "launch on system start".

**Comment by haimn** [comment] 2020-07-22 12:43
I changed the startup script from `/usr/bin/mailspring --background %U` to `/usr/bin/mailspring -b %U` and now it starts minimized (Ubuntu linux 20.04)

**Comment by ecavicc** [comment] 2021-01-15 19:35
It still doesn't work for me. Manjaro linux, installed from AUR.

**Comment by CodeMouse92** [comment] 2021-01-17 02:50
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/run-as-minimized-on-startup/57/1

Please consider joining that community and continuing the discussion there! Bonus: if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-17 02:50 UTC
Labels: audit, enhancement
