### ISSUE TITLE
No visible window frame on linux

### ISSUE THREAD

**Issue by buekera** [Foundry376/Mailspring#1507] opened 2019-05-21 18:36 UTC
##### What operating system are you using?
Arch Linux
Kernel 5.1.3
Gnome 

##### What version of Mailspring are you using?
1.6.1-aceed8e5

After starting Mailspring from dektop entry or shell there is no window coming up. I can see that it is running when looking at running processes.

I also read about some similar issues already reported over a year ago but could not find any current unsolved issues here on github.

**Update:**
I installed mailspring from different sources (snap, yaourt) and I still have the same issue.

**Update 2:**
I noticed the following message when running from commandline after installing Mailspring with snap:
```
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Running database migrations
App load time: 135ms

{"error":null}
```
I checked if `canberra-gtk` is installed on my system - it is:
```
~  sudo pacman -Qi libcanberra                                                                                                                                                                             Wed 22 May 2019 10:01:30 PM CEST
Name            : libcanberra
Version         : 0.30+2+gc0620e4-2
Description     : A small and lightweight implementation of the XDG Sound Theme Specification
Architecture    : x86_64
URL             : http://0pointer.de/lennart/projects/libcanberra
Licenses        : LGPL
Groups          : None
Provides        : None
Depends On      : libvorbis  libltdl  alsa-lib  tdb  sound-theme-freedesktop
Optional Deps   : libcanberra-pulse: PulseAudio driver [installed]
                  libcanberra-gstreamer: GStreamer driver
Required By     : brasero  cheese  evolution  gnome-bluetooth  gnome-color-manager  gnome-disk-utility  gnome-screenshot  gsound  gtk3  knotifications  lib32-libcanberra  libcanberra-pulse  mutter  steam-native-runtime
Optional For    : thunderbird
Conflicts With  : None
Replaces        : None
Installed Size  : 404.00 KiB
Packager        : Evangelos Foutras <evangelos@foutrelis.com>
Build Date      : Fri 09 Nov 2018 10:18:18 PM CET
Install Date    : Sat 17 Nov 2018 12:36:50 PM CET
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature
```

**Comment by bengotow** [comment] 2019-05-26 20:44
Hey! This is super interesting–we haven't seen any reports of this in a while and it looks like Mailspring is launching happily in the background (no exceptions or anything beneath the `{error: null}` line when you launch it).

Could you try running the app with Chromium's GPU support disabled and extra logging by launching it like this? Maybe that will give a bit more info.

```ELECTRON_ENABLE_LOGGING=true mailspring --disable-gpu```

**Comment by buekera** [comment] 2019-05-27 15:28
I will try when I get home tonight.

**Comment by buekera** [comment] 2019-05-27 20:46
I executed mailspring as adviced but still have no visible window.
Output:
```
[5421:0527/224423.815546:ERROR:gpu_process_transport_factory.cc(1017)] Lost UI shared context.
Running database migrations
App load time: 624ms

{"error":null}
[5421:0527/224426.056639:INFO:CONSOLE(16)] "Window load time: 736ms", source: file:///snap/mailspring/346/usr/share/mailspring/resources/app.asar/static/index.js (16)
[5421:0527/224426.056696:INFO:CONSOLE(16)] "Window load time: 736ms", source: file:///snap/mailspring/346/usr/share/mailspring/resources/app.asar/static/index.js (16)
```

**Comment by buekera** [comment] 2019-05-30 09:14
@bengotow Can you have another look at this?

**Comment by buekera** [comment] 2019-06-11 08:40
I noticed that when looging in with a different, newly created, user mailspring suddenly displays correctly.
I reset my gnome for the user where the issue occurs but had no luck so far. The window still is invisible.

**Comment by LongLiveCHIEF** [comment] 2019-06-28 15:07
Just reproduced today. I had some problems with snapd systemd service running (mask errors) when I tried to install mailspring, and I had to reboot to get snapd systemd service running. 

The first thing I did after rebooting and verifying snapd was running, was install the mailspring snap.  I used the launcher to launch it, and got no visible window frame.  I killed it, and then used the command line to launch it, and got the same errors reported above:

```
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Running database migrations
App load time: 172ms

{"error":null}
```

I'm running Ubuntu 19.04.  Hopefully some pertinent info to help: 

```
GJS_DEBUG_TOPICS=JS ERROR;JS LOG
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
SESSION_MANAGER=local/chief-spectre:@/tmp/.ICE-unix/1843,unix/chief-spectre:/tmp/.ICE-unix/1843
GNOME_TERMINAL_SCREEN=/org/gnome/Terminal/screen/da2a83ab_ec89_478c_9f57_442da1519170
SSH_AGENT_PID=1955
XDG_CURRENT_DESKTOP=ubuntu:GNOME
LANG=en_US.UTF-8
DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
IM_CONFIG_PHASE=2
PWD=/home/chief
QT_IM_MODULE=ibus
GPG_AGENT_INFO=/run/user/1000/gnupg/S.gpg-agent:0:1
USER=chief
GJS_DEBUG_OUTPUT=stderr
XDG_MENU_PREFIX=gnome-
DESKTOP_SESSION=ubuntu
HOME=/home/chief
QT4_IM_MODULE=xim
VTE_VERSION=5601
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
XDG_VTNR=2
XDG_SEAT=seat0
GTK_MODULES=gail:atk-bridge
XDG_DATA_DIRS=/usr/share/ubuntu:/home/chief/.local/share/flatpak/exports/share/:/var/lib/flatpak/exports/share/:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop
GTK_IM_MODULE=ibus
XDG_SESSION_DESKTOP=ubuntu
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/etc/xdg
WINDOWPATH=2
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
CLUTTER_IM_MODULE=xim
QT_ACCESSIBILITY=1
GNOME_TERMINAL_SERVICE=:1.75
PATH=/home/chief/.local/bin:/home/chief/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
XDG_RUNTIME_DIR=/run/user/1000
XMODIFIERS=@im=ibus
XDG_SESSION_ID=2
XDG_SESSION_TYPE=x11
SHELL=/usr/bin/zsh
USERNAME=chief
GNOME_SHELL_SESSION_MODE=ubuntu
SHLVL=1
XAUTHORITY=/run/user/1000/gdm/Xauthority
COLORTERM=truecolor
XDG_SESSION_CLASS=user
TERM=xterm-256color
GDMSESSION=ubuntu
DISPLAY=:0
OLDPWD=/home/chief
ZSH=/home/chief/.oh-my-zsh
PAGER=less
LESS=-R
LSCOLORS=Gxfxcxdxbxegedabagacad
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
LC_CTYPE=en_US.UTF-8
```

**Comment by rhythmhq** [comment] 2019-09-19 10:32
I cannot use Snap as I get this issue.
Ubuntu 18.04.3 LTS

**Comment by damiankoper** [comment] 2020-09-27 11:31
I had the same issue. It failed to display welcome window.
I had to disconnect second screen for the window to be displayed. After initial config everything seems to work fine with second screen.
Ubuntu 20.04.1 LTS. Mailspring installed from snap.

**Comment by CodeMouse92** [comment] 2021-02-18 00:34
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/no-visible-window-frame-on-linux/683

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@buekera @LongLiveCHIEF @rhythmhq @damiankoper: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-18 00:34 UTC
Labels: audit, linux, needs-reproduction
