### ISSUE TITLE
Bug/Enhancement: Go to label not working

### ISSUE THREAD

**Issue by gvteja** [Foundry376/Mailspring#2015] opened 2020-05-25 11:58 UTC
I use the Gmail shortcuts and within Gmail, g and then l goes to the label search. It looks like that does not work out in Mailspring. Based on the [Gmail template json](https://github.com/Foundry376/Mailspring/blob/ea37c75596f4cc6842ff01fdd576d185fbdd2e96/app/keymaps/templates/Gmail.json#L9), I think it's supposed to work. 

**To Reproduce**
Within any inbox, type g and then l.

**Expected behavior**
A search box that lists only labels

**Setup: (please complete the following information):**
 - OS: macOS
 - OS Version 10.15.4
 - Mailspring Version: 1.7.8. But has been this way since at least February 2020.

**Additional context** 
I would also appreciate any workaround where I could navigate to a particular label using only the keyboard.

**Comment by CodeMouse92** [comment] 2021-02-23 22:17
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/allow-jumping-to-labels-like-gmail-does-using-g-l-then-type-the-label-name/714

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-23 22:17 UTC
Labels: audit, bug
