### ISSUE TITLE
Moving thread removes sent items from Sent folder

### ISSUE THREAD

**Issue by fracsi** [Foundry376/Mailspring#1081] opened 2018-09-19 12:49 UTC
##### Are there any related issues?
Maybe: #774 

##### What operating system are you using?
Ubuntu 18.04

##### What version of Mailspring are you using?
1.4.2

--

**Bug**
 
##### Do you have any third-party plugins installed? If so, which ones?
No.
 
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
For any email thread for which there is a reply, moving the thread from the inbox to another IMAP folder will remove the sent messages from the Sent Items folder.
There's then no way to put the sent mails back to "Sent items"

**Comment by kmancobhc** [comment] 2019-02-26 21:47
I have the same question. Anyone have a workaround?

**Comment by CodeMouse92** [comment] 2021-02-11 18:39
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've migrated to Discourse:

https://community.getmailspring.com/t/improve-threading-behavior-when-moving-messages/569

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-11 18:39 UTC
Labels: audit
