### ISSUE TITLE
GPG and S/MIME Plugin

### ISSUE THREAD

**Issue by namnamir** [Foundry376/Mailspring#940] opened 2018-06-18 07:36 UTC
Dear folks,
I use Ubuntu 18 and like to have GPG - S/MIME or even PGP on it. I have read #25 but it doesn't work for me. It says that it needs a .json file.

What I have done so far:

1. download the introduced plugin from https://keybase.io/kbpgp_public/releases/kbpgp-2.0.8-signed-release.zip
2. unpack it and try to import it in Mainspring menu (Developer > Install Plugin). I get this error:

> The plugin or theme folder you selected doesn't contain a package.json file, or it was invalid JSON. Error: Cannot find module '/home/xxxxxx/Downloads/kbpgp-2.0.8-signed-release/kbpgp/package.json'

3. try to create a plugin through the menu but don't know where to put the single .js file I have.

Any idea?

**Comment by Gamebase32** [comment] 2018-06-30 13:00
I tried to use the old plugin for nylas in mailspring. It says the plugin is not been upgraded. So i Followed the guidelines from the article [http://support.getmailspring.com/hc/en-us/articles/115001918391](url). But still after that the same error appears that the plugin is not compatible.
`Could not install plugin
The plugin or theme you selected has not been upgraded to support Mailspring. If you're the developer, update the package.json's engines field to include "mailspring".`

**Comment by TKaluza** [comment] 2018-12-12 11:39
Any news about this? 

I need to sign my mails and it does not seems to be possible right now, or is it? (KDE Neon 18.04 and WIN 10)

**Comment by danieltpye** [comment] 2018-12-14 15:06
+ 1

**Comment by danieltpye** [comment] 2018-12-14 15:07
Seconded. I've tried a number of possible work around in previous issues but not had any luck. Devs is there any sign of light at the end of the tunnel here?

**Comment by cjpabloL** [comment] 2019-02-06 13:07
Any news about this? I need to sign my emails to switch to use Mailspring.

**Comment by fbruetting** [comment] 2019-02-06 20:14
So with using ProtonMail and the new Linux encryption bridge (beta!), encryption should work without having Mailspring needing to implement anything. I’ll see if I can check this tomorrow or so… 😄

**Comment by entepe85** [comment] 2019-03-04 11:51
I'd second the request for S/MIME signing and encryption as well as my employer uses S/MIME certificates and I need to be able to at least sign my emails.

**Comment by tristanlins** [comment] 2019-04-18 10:39
The European Directive 2016/943 on the protection of trade secrets requires indirect e-mail encryption. Especially S/MIME is required in this context as an industry standard and is indeed supported by almost all e-mail clients, including the mobile variants.

In our company, the use of S/MIME is currently being discussed and is expected to become mandatory for all employees in the coming weeks. Which will eventually lead to my being unable to use Mailspring any longer. :-(

**Comment by WalterMccan** [comment] 2019-04-22 12:05
I can't believe that you sell this as a product without such basic yet important feature.

**Comment by cpot** [comment] 2019-10-09 19:40
I just discovered mailspring and yes this software is a killer app but lack of s/mime avoid me to use it for work. I saw it is on the roadmap, i hope it will be released because mailspring is so really better than Outlook (easy) but also Thunderbird and all others IMHO

**Comment by fenris** [comment] 2019-12-22 17:43
hi .. any update on this plugin ?

**Comment by bengotow** [comment] 2020-02-17 17:10
Merging into #25 so we can track development of this in one place!

**Closed by bengotow** 2020-02-17 17:10 UTC

**Comment by michal-karpinski** [comment] 2020-03-16 09:35
I agree, mailspring looks very promising. Unfortunately without PGP I have to get back to Thunderbird :(

**Comment by CodeMouse92** [comment] 2021-01-18 21:39
Hey everyone,

This is something both @bengotow and I would love to see, but **we really need some members of the community to step up and help us implement this!**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/pgp-encryption-gpg-support-keybase/83

Please consider joining that community and continuing the discussion there! Bonus: if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Comment by zparihar** [comment] 2021-04-01 23:18
Looking forward to PGP support in Mailspring!
