### ISSUE TITLE
[BUG] Incorrect number of unread emails in folders

### ISSUE THREAD

**Issue by Andrewsudarikov** [Foundry376/Mailspring#416] opened 2017-12-08 07:45 UTC
##### Are there any related issues?

Couldn't find any

##### What operating system are you using?
Elementary OS 0.4.1

##### What version of Mailspring are you using?
1.0.10

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
None

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?

![screenshot from 2017-12-08 10 35 55](https://user-images.githubusercontent.com/18544958/33755869-e12f29d4-dc03-11e7-98f2-4fd6356fab65.png)

As you can see, all the messages in the folder were read, yet the badge still shows 5 unread messages. There is also a "DRIVE2" folder above, it shows 2 unread messages but it is also wrong - all were read. And this goes on with almost every folder except those that were not updated for a long time.  
--
I'm thinking - does it still count unread messages in the "Trash" folder? If so, exclude it from the counter poll?

**Comment by blizzardengle** [comment] 2017-12-20 20:30
I've noticed the same bug and I find it annoying too! What I think is causing this is Mailspring is having trouble recognizing that you have already read the email. Gmail has marked it differently with a label or as important for example so when your read the email itself Mailspring records this but the other labels/ storage architecture of Gmail does not get notified leaving Mailspring to think its all different emails you still haven't opened.

Just my thoughts, hopefully it helps people reproduce this issue and find a solution to it.

**Comment by gnunn1** [comment] 2018-02-15 05:12
I've been having this issue for awhile now and it's quite annoying as I can no longer tell at a glance when new e-mails have arrived. if there is anything I can do to help track this down let me know.

**Comment by MaxTurcHot** [comment] 2018-04-15 21:44
Deleting the account and setting it back is fixing the issue (short term).

**Comment by jurosh** [comment] 2018-05-05 11:35
Just installed Mailspring, but got similar issue. I have UNREAD emails in many folders but app is not showing any of those as unread. (ps. in gmail, I have configured filter to skip Inbox and those messages are going directly to folders)

**Comment by legendary-jld** [comment] 2018-05-15 21:12
Created a new folder, and received emails that get filtered directly into this folder. These emails don't show an unread account on the folder itself, nor does Mailspring notify me that an email has come in.

**Comment by jonesrussell** [comment] 2018-06-21 19:35
Same issue as @legendary-jld.  I'm using my ISP's IMAP server.  The ISP's webmail shows correct unread in folders other than inbox.

**Comment by 120dev** [comment] 2020-04-09 11:44
same issue for me 1.7.4 / Fedora 31

**Comment by CodeMouse92** [comment] 2021-01-28 18:38
Thank you for reporting this. 2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/unread-count-still-on-without-unread-messages/350

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 18:38 UTC
Labels: audit
