### ISSUE TITLE
Uninstaller doesn't clean up Windows registry entries

### ISSUE THREAD

**Issue by frodri** [Foundry376/Mailspring#1774] opened 2020-01-19 01:23 UTC
Title says it all.

Tested with mailspring 1.7.2 and Windows 10 (1909 update).

**Comment by bengotow** [comment] 2020-02-15 18:49
Thanks for reporting this! I think that this is happening because this method here (https://github.com/Foundry376/Mailspring/blob/master/app/src/browser/main.js#L227) isn't a full inverse of the `--squirrel-install` path above it.  Someone with a Windows machine might be able to knock this out fast!

**Comment by CodeMouse92** [comment] 2021-02-23 21:42
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/uninstaller-doesnt-clean-up-windows-registry-entries/742

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@frodri: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-23 21:42 UTC
Labels: audit, bug, windows
