### ISSUE TITLE
Typing Korean, not matched what I typed in composer

### ISSUE THREAD

**Issue by kocne** [Foundry376/Mailspring#1299] opened 2019-01-04 02:24 UTC
##### Are there any related issues?

...

##### What operating system are you using?

... win 10

##### What version of Mailspring are you using?

...1.5.5 b7939d38

--

**Bug?**

##### Is this an email sync or connection issue?

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...  try type in To: is working well but in contents, it is not what I typed in.
![korean](https://user-images.githubusercontent.com/46362748/50671114-35876700-1013-11e9-89ea-fb20f52d3aa3.png)

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

...

**Comment by davidsuh79** [comment] 2019-01-06 05:06
I am experiencing the same issue: macOS 10.13.6, Mainspring 1.5.5-b7939d38.

**Comment by luvix** [comment] 2019-01-13 15:48
I'm use mailspring on Windows 10 build 1803. I was downgraded to version 1.5.3-420ce003.

Korean input was better in 1.5.3 but not perfect. Here is a sample:

```
동해물과 백두산이 aㅏ르고 닳도록 하느님이 보우하사 우리나라 만세무궁화 삼천리 화려강산 대한사랑 대한으로 길이보전하세
```

This sentence has two problem: 
- 'aㅏ르고' is wrong input of '마르고'. 'ㅁ' and 'a' is same key on korean keyboard layout.
  - This problem occurred in sometimes, but too frequently in version 1.5.5. One of two/three Korean character has this problem in my case.
- '만세무궁화' is wrong input of '만세{enter}무궁화'. If i want to new line, i should input the enter again.

**Comment by bengotow** [comment] 2019-02-23 01:08
Hi folks—thanks for reporting this. It's interesting that this was working better in 1.5.3. I think that this must have been degraded when we upgraded to Electron 4 in the most recent release.

It doesn't look like any Korean input problems have been reported over at https://github.com/electron/electron/issues so we may need to dig in to this further.

**Comment by trustin** [comment] 2019-04-16 00:34
Still a problem with 1.6.1. Other Electron-based apps such as VSCode and YakYak does not show this problem, so I believe this is specific to Mailspring.

**Comment by trustin** [comment] 2019-04-16 00:35
May or may not be useful, but I'm on Arch Linux, which may mean this problem is platform independent?

**Comment by awesometic** [comment] 2019-06-04 09:17
Hi Mailspring team,
I found a perfect mail client for my multi-platform environment, but I'm not using it yet because it is a very critical problem for daily use.

Plus information: Searching in all mailboxes is fine. The problem occurs when I write an email, in the new window.
Please look into this bug. Thanks.

**Comment by luvix** [comment] 2019-06-19 15:21
I updated the client to version 1.6.1-278bf219, and this problem is almost solved. Typing is good but newline needs typing enter twice. My env is Win 10 1809. Thank you!

**Comment by awesometic** [comment] 2019-06-20 05:48
It seems to be almost solved! I'm using Ubuntu 19.04 and installed Mailspring 1.6.2 using snap. Thanks for this great program.

**Comment by trustin** [comment] 2019-06-20 07:22
1.6.2 fixes the problem mostly (Arch Linux). The only problem I see is that the enter key does not insert a newline when the current CJK character is not complete yet.

**Comment by kocne** [comment] 2019-06-20 09:02
@luvix Big Thanks to you. it is very good now. I tested in Linux Mint.

**Comment by CodeMouse92** [comment] 2021-02-09 23:10
It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-09 23:10 UTC
Labels: audit, bug
