### ISSUE TITLE
Bug: Crash and freeze in registration form ( linux, snap, version 1.7.8 )

### ISSUE THREAD

**Issue by mickare** [Foundry376/Mailspring#2136] opened 2020-09-04 15:38 UTC
**Describe the bug**
On a fresh installed `5.7.17-2-MANJARO` and snap-installed Mailspring 1.7.8, the application crashes when it receives any text input.

**To Reproduce**
1. Install Mailspring via Snap
2. Start Mailspring
3. Click Get Started and Next until you reach the registration form
4. Select any text field
5. Press any key
6. Freeze and crash

**Expected behavior**
Not freezing and crashing.

**Screenshots**

**Setup: (please complete the following information):**
 - OS: Linux MANJARO
 - OS Version 5.7.17-2
 - Mailspring Version: 1.7.8 latest/stable (snap)

**Additional context** 
No other context, I just wanted to try another mail-client than Thunderbird on my fresh-installed linux.

**Comment by EZ4ZZW** [comment] 2020-10-16 04:09
Hello! I have the same problem too. I also used the mailspring installed form snap, but i found that it have package in AUR, so I try to reinstall by pacman and I solved this problem. My mailspring have not crash and freeze now.
My English is not very good, I hope you can understand.
Have an Octotastic day!

**Comment by CodeMouse92** [comment] 2021-02-15 21:39
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

@mickare @EZ4ZZW: Can you please confirm that this is still broken with 1.8.0, and if so, open a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-15 21:39 UTC
Labels: audit, bug
