### ISSUE TITLE
Bug: Adding a new account with same 'email'/from name results in 1 confused inbox

### ISSUE THREAD

**Issue by samtuke** [Foundry376/Mailspring#1855] opened 2020-03-11 13:13 UTC
**Describe the bug**
Adding a new account with the same email / from addr as an existing account results in no new account being added, but the config options (server settings) of the preexisting account updated to the newly added account, but the mail within that inbox still belonging to the previous account.

I added the new account with the same email because on the first round I was confused by what was being requested and added my mailspring login email address instead of the account login (which must in any case be entered in manual imap config).

After adding the two accounts (different accounts, servers, logins) with the same 'from' email, I couldnt use either of the accounts, and had to remove the single listed account and start again. I'm fearful that mail from one or other account may be mistakenly deleted if mailspring is listing mail from the 1st account added and then polling mail into the same inbox from the 2nd account added.

**Setup: (please complete the following information):**
 - OS: Fedora 31
 - OS Version [e.g. 14]
 - Mailspring Version: ex: 1.7.2 (using that due to https://github.com/Foundry376/Mailspring/issues/1841)

**Comment by CodeMouse92** [comment] 2021-02-12 19:40
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/adding-a-new-account-with-same-email-from-name-results-in-1-confused-inbox/586

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@samtuke: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-12 19:40 UTC
Labels: audit, bug
