### ISSUE TITLE
Main window should be focused after sending an email

### ISSUE THREAD

**Issue by shroudedcode** [Foundry376/Mailspring#1362] opened 2019-02-09 12:21 UTC
I really love the *After sending, enable undo for: X seconds* feature but I found a small problem with it:

When I minimize or close the main Mailspring window, compose an email in the composer window, and send it, the composer window is closed and the main window which contains the undo button stays hidden, so I can't click *Undo* unless I manually open the window. This removes the kind of confidence this feature gives to users and thus makes it pointless.

My suggestion is to `.show()` the window if closed and `.focus()` it otherwise.

**Comment by bengotow** [comment] 2019-02-11 00:27
Hmm—this seems like a good idea. If you typically close / hide the main window while composing, you're definitely a little out of luck. I'll see if we can do this in an upcoming release. Would also accept a PR for this!

**Comment by CodeMouse92** [comment] 2021-02-25 23:26
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/main-window-should-be-focused-after-sending-an-email/801

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@shroudedcode: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-25 23:26 UTC
Labels: audit, enhancement
