### ISSUE TITLE
Feature Request: Missing invite.ics support

### ISSUE THREAD

**Issue by francesco-cmcc** [Foundry376/Mailspring#2070] opened 2020-06-25 14:44 UTC
Hi all,
When you receive an invitation via email to an event (for instance sent from outlook client), it can contain a description of the event. 
Currently MailSpring visualize only the event's name, the date and three acceptance buttons, but it doesn't show the description.
Is it possible to include this feature? or does it already exist ?  

kind regards

Francesco

**Comment by CodeMouse92** [comment] 2021-03-02 03:25
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/accepting-calendar-invite-should-change-event-status/43

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 03:25 UTC
Labels: audit, enhancement
