### ISSUE TITLE
database is locked

### ISSUE THREAD

**Issue by WladyX** [Foundry376/Mailspring#595] opened 2018-01-30 13:06 UTC
I get the following in the logs about my office365 account:

22159 [2018-01-30 10:25:17.142] [background] [critical] 
 ***
 *** A C++ exception occurred during program execution: 
 *** database is locked
 ***

22159 [2018-01-30 10:25:17.323] [background] [critical]  *** Stack trace (line numbers are approximate):
 *** (unknown)  clone
 ***

==> .config/Mailspring/mailsync-e453a4b0.log <==
22087 [2018-01-30 10:25:03.168] [background] [critical] 
 ***
 *** A C++ exception occurred during program execution: 
 *** database is locked
 ***

22087 [2018-01-30 10:25:03.223] [background] [critical]  *** Stack trace (line numbers are approximate):
 *** (unknown)  clone
 ***

**Comment by WladyX** [comment] 2018-02-07 07:29
I also get this for the IMAP account:
599 [2018-02-07 09:29:33.420] [foreground] [info] -- 0 matches.
599 [2018-02-07 09:29:33.420] [foreground] [info] Unlinking messages  WHERE remoteFolderId = ? AND remoteUID < ? no longer present in remote range.
599 [2018-02-07 09:29:33.598] [background] [critical] 
 ***
 *** A C++ exception occurred during program execution: 
 *** database is locked
 ***

599 [2018-02-07 09:29:33.661] [background] [critical]  *** Stack trace (line numbers are approximate):
 *** (unknown)  clone
 ***

**Comment by EvilJimJafar** [comment] 2018-11-15 02:15
I'm getting this too. Any ideas @bengotow ?

**Comment by tristanlins** [comment] 2019-04-07 16:26
This workaround works for me:
Close Mailspring, moved `~/.config/Mailspring/Cache` away (or delete it) and restart Mailspring.

**Comment by rsalevsky** [comment] 2019-04-16 09:23
I run at least once a week into this issue especially when my internet connection is not very good during travels. The result of this is that I have to rebuild the cache once a week which takes due to the size of my inbox at least 8 hrs with a high CPU load. This is not very sustainable.

**Comment by omega** [comment] 2019-04-26 08:14
I get the same exception, but removing the Cache folder didn't help for me :/

**Comment by tristanlins** [comment] 2019-05-10 11:09
For about two weeks, the error occurs daily. Usually when I get the laptop out of standby in the morning. At this moment, all old emails (whether read or unread) disappear from the Inbox. Only new emails arriving after the lock error are displayed. Therefore I have to go into the settings daily and press the "Clear cache" button.

Apparently this is primarily related to when the network connection changes. For example, after the standby mode, but apparently the error occurs even if the wireless connection is gone for a short time.

Mailspring: Version 1.6.1
Distributor ID: neon
Description:KDE neon User Edition 5.15
Release: 18.04
Codename: bionic

**Comment by tristanlins** [comment] 2019-05-11 08:49
Update: yesterday I downgraded Mailspring to version 1.6.0. The problem with the "Database Locked" seems since then no longer occur. I'll watch it for a few more days, but it looks like it's currently a problem with version 1.6.1.

**Comment by tristanlins** [comment] 2019-05-13 07:08
I can confirm that the bug only occurs in version 1.6.1, but not in version 1.6.0.

**Comment by CodeMouse92** [comment] 2021-02-01 19:23
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/database-is-locked/420

Please consider joining that community and continuing the discussion there!

@tristanlins: I've migrated your comments particularly, as they point to the version where this first appears. If you join and reply to the issue, the moderators can make an effort to reassign that post to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-01 19:23 UTC
Labels: audit
