### ISSUE TITLE
Mail keeps returning as unread after reading every time I open mailspring

### ISSUE THREAD

**Issue by NeroVanbiervliet** [Foundry376/Mailspring#544] opened 2018-01-19 11:26 UTC
##### Are there any related issues?
No.

##### What operating system are you using?
Ubuntu 17.10

##### What version of Mailspring are you using?
1.0.12-cf081332

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I only use exchange, so no idea. 

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Not that I know of

**Comment by DaddyWarlock** [comment] 2018-01-26 02:04
I'm having a similar issue.  Read emails are coming back unread during the same Mailspring session.  I'm also using Ubuntu 17.10, but my Mailspring version is 1.1.0-7563b09d.  The problem has been happening since Version 1.0.12 though.

**Comment by kevprice83** [comment] 2018-02-16 11:46
I also have a similar problem. I cannot seem to remove the unread mails from that folder unless I mark as `unread` and then as `read` again.

**Comment by sathiz1993** [comment] 2018-02-16 14:08
+1

**Comment by jonholdship** [comment] 2018-02-21 11:28
The same two emails in my inbox keeping doing this too. I am also using exchange.

**Comment by peterpalace** [comment] 2019-11-27 05:40
same. On Ubuntu 19.10.

**Comment by personalnadir** [comment] 2020-01-11 11:35
Likewise on MacOS 10.14.6 with Mailspring Version 1.7.2. Only occurs with the IMAP Exchange account, not my Gmail account.

**Comment by FoamyGuy** [comment] 2021-01-21 14:37
This occurs for me as well Linux Pop OS, `Mail Spring v 1.8.0-8983dca2`

IMAP connection to office 365 mail

**Comment by CodeMouse92** [comment] 2021-01-21 15:23
Hi all,

2020 prevented much development work on Mailspring, but rest assured, development has resumed! We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. Learn more about the changes here.

@FoamyGuy: Because the original issue does not describe the problem very well, can you please help us fix this by opening a new Bug Report on our Discourse, following the template? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

**Closed by CodeMouse92** 2021-01-21 15:23 UTC
Labels: audit
