### ISSUE TITLE
[Feature Request] Markdown Support for composing emails

### ISSUE THREAD

**Issue by ldartez** [Foundry376/Mailspring#19] opened 2017-10-04 16:33 UTC
**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
YES! Currently I have to use Thunderbird because I am a heavy user of Markdown formatting in emails. Thunderbird has a plugin called [markdown here](http://markdown-here.com/) that allows me to write emails in markdown formatting and converts the message (using html?) to render the formatting in the final message.

##### What operating system are you using?
```
(main) louis@xi:~$ neofetch
            .-/+oossssoo+/-.               louis@xi 
        `:+ssssssssssssssssss+:`           -------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 17.04 x86_64 
    .ossssssssssssssssssdMMMNysssso.       Model: Blade 6.06 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 4.10.0-35-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 8 hours, 41 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 2212 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 4.4.7 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1920x1080 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   DE: Unity:Unity7 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Compiz 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   WM Theme: Ambiance 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Theme: Ambiance [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Icons: Ubuntu-mono-dark [GTK2/3] 
  +sssssssssdmydMMMMMMMMddddyssssssss+     CPU: Intel i7-7700HQ (8) @ 3.8GHz 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      GPU: Intel Kabylake GT2 
    .ossssssssssssssssssdMMMNysssso.       GPU: NVIDIA GeForce GTX 1060 Mobile 
      -+sssssssssssssssssyyyssss+-         Memory: 2061MiB / 15932MiB 
        `:+ssssssssssssssssss+:` 
            .-/+oossssoo+/-.                                       


```

##### What version of Mailspring are you using?
none.
--

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No!

--

**Comment by buildersbrewery** [comment] 2017-10-05 23:14
It should be built-in? Mailspring keeps adding these lines to the `config.json` anytime there's a change, though:

```json
    "disabledPackages": [
        "message-view-on-github",
        "personal-level-indicators",
        "phishing-detection",
        "nylas-private-salesforce",
        "github-contact-card",
        "keybase",
        "composer-markdown",
        "composer-scheduler",
        "composer-mail-merge",
        "send-and-archive",
        "main-calendar"
      ]
```

**Comment by jbrooksuk** [comment] 2017-10-06 10:55
Can confirm that it keeps disabling Markdown.

**Comment by toddleo** [comment] 2018-01-03 02:59
Hi,

I'm accustomed to write email in markdown, and render with a Chrome extension [Markdown Here](https://chrome.google.com/webstore/detail/markdown-here/elifhakcjgalahccnjkneoccemfahfoa?hl=en).

With Mailspring, I have to cut out my content to chrome and paste back after rendering. It's not a "must have" feature but, every I do the pasting I wonder it would be great to have native markdown support!

That said, it doesn't stop Mailspring to be a great mail app! Loved it!

**Comment by bengotow** [comment] 2018-01-23 01:39
Hey folks—thanks for reporting this! Version 1.1.0 shipped today which includes an overhauled composer with support for RTL text, font colors, sizes and styles, improved markdown formatting tag support (`__`, `*`, `**`, `- ` for lists, single and triple \` for code blocks) and a lot of other small improvements. It also supports pasting HTML from other programs and preserves a wider range of basic styles. I'll be expanding the markdown support in the editor to include the link syntax and the header syntax soon, and I think that'll pretty much close this out. (Though there are some other great ideas here I think we could tackle separately in the future!)

Going to go ahead and close this since I think we're pretty close, but watch out for the few remaining markdown shortcuts in the next few minor releases.

You can grab the latest version from https://getmailspring.com/download.

**Closed by bengotow** 2018-01-23 01:39 UTC
Labels: composer, done-pending-release, enhancement

**Comment by ldartez** [comment] 2018-02-01 17:38
sorry but it's difficult to consider the current markdown implementation as complete. far from it. my installation (downloaded and installed today on ubuntu 17.10) only recognizes the single & double asterisks for italicized and bold characters. the single back-tick doesn't work at all. the triple back tick for code blocks is broken; if i start by typing the first three back ticks (```) then it puts me in block mode seamlessly but it's then impossible to get out of block mode!! The block mode shouldn't be interpreted until the closing triple-backticks are typed! Other features that I would need to see before coming back to mailspring are #, ##, ### for headers, []() for inline hyperlinks, and table support.

**Comment by claudiodsf** [comment] 2018-03-24 16:13
@bengotow I'm running v1.1.5, but I could not manage to use single and triple ` for code blocks.
Am I doing something wrong?

**Comment by bnvt** [comment] 2018-05-23 11:03
Hmmm… I think I'm missing something here, I cannot seem to use the markdown feature at all, all tags I write just get sent as plain text.
Am I supposed to do something to render the markdown into html? Or maybe I need to enable the feature in some settings option?

Thanks!

**Comment by mclang** [comment] 2018-05-24 12:11
For me the single back-tick usually works if there is space before but not e.g like so:
(`does not render fixed space`)
Furthermore
```
Coding blocks do not work because MailSpring seems to recognise
the two back-ticks immediately and does not re-render text after third is added.
```
These two markdown things are the ones I use the most.

**Comment by bergmul** [comment] 2018-10-12 11:52
Any update on the extended markdown support, i.e. links and headers?

**Comment by ditolesto** [comment] 2018-12-07 11:03
Hi,

Although the current implementation allows for the ``` code block, i find that pasting in the block doesn't support carriage returns. It all sticks in one line, without word wrap.

What I miss the most is the # octothorpe heading style and --- for line separator, maybe most importantly the table syntax i found in Markdown Here... that allowed for nicely styled tables within email...

|head|head1|head2|
|:----|:----|:----|
|content|content1|content2|

Loved it

**Comment by NicTanghe** [comment] 2020-08-26 20:36
its verry inclear how markdown works and am unable to use it

**Comment by ochen1** [comment] 2020-11-28 01:42
Yes, I agree that the instruction could be more clear.

Anyone with updates on this issue?

**Comment by msoutopico** [comment] 2021-02-05 12:15
As far as I can see, only code blocks (embedded by single or triple backticks) are recognized and rendered as expected markdown text. Neither headers nor tables do, so I don't think I can say Mailspring supports Markdown for composing. I don't understand why this ticket is closed.

**Comment by ochen1** [comment] 2021-02-05 14:54
> I don't understand why this ticket is closed.

Same. I know right?

**Comment by CodeMouse92** [comment] 2021-02-05 16:22
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/markdown-support-in-composer/322

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team
