### ISSUE TITLE
Lost my draft

### ISSUE THREAD

**Issue by AlexDunmow** [Foundry376/Mailspring#1174] opened 2018-10-26 07:59 UTC
##### What operating system are you using?

Ubuntu 18.04

...

##### What version of Mailspring are you using?
1.5.0-92ed66b8
...

**Bug**

I was typing out a very long email. I accidentally pressed shift + backspace. Which caused the email to revert to an old version with a tenth of the email contents. I could not get this old draft back. 

This was a pretty enraging moment as you can imagine. 

I am a paid user.

**Comment by CodeMouse92** [comment] 2021-01-22 00:30
So sorry to hear of this! It's always annoying to lose an email.

2020 prevented much development work on Mailspring, but rest assured, development has resumed! We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. Learn more about the changes here.

@AlexDunmow: Can you please confirm that this is still broken with 1.8.0, and if so, open a new Bug Report on our Discourse? We want to be able to address this, but we need up-to-date diagnostic information to do it. We've had quite a few releases since 1.5.0. :wink:

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-22 00:30 UTC
Labels: audit
