### ISSUE TITLE
Not able to sync IMAP inbox

### ISSUE THREAD

**Issue by jeffwillette** [Foundry376/Mailspring#1735] opened 2019-12-13 02:43 UTC
##### Are there any related issues?

Yes, but no clear solution

##### What operating system are you using?

Ubuntu 18.04

##### What version of Mailspring are you using?

1.7.2

**Bug?**

##### Is this an email sync or connection issue?

sync

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

yes, custom email server

##### Is the issue reproducible with a particular attachment, message, signature, etc?

![image](https://user-images.githubusercontent.com/9424192/70765130-240b1b00-1d9d-11ea-8245-1de0259536c8.png)

The inbox just shows syncing forever with no progress and the process is actually taking a lot of CPU power.

[mailspring-log.zip](https://github.com/Foundry376/Mailspring/files/3958765/mailspring-log.zip)

**Comment by CodeMouse92** [comment] 2021-01-28 03:54
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/the-eternal-sync-bug/334

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 03:54 UTC
Labels: audit
