### ISSUE TITLE
I have to sign into most of my emails again every day

### ISSUE THREAD

**Issue by ITCMD** [Foundry376/Mailspring#1593] opened 2019-07-28 11:14 UTC
I'm running KDE Plasma 5.16.3
Mailspring Version 1.6.3 (this has hapened since I updated from 1.6.2).
Every day I have to sign into my gmail acount through the web portal again, and every day, for my mail.com account, it says it cant sync, and I have to press `try again` and without changing anything, I can press `Connect Account` and it works.

**Comment by inDeev** [comment] 2019-08-02 10:03
Same here. Gmail each day, custom domain IMAP less often.

**Comment by al2me6** [comment] 2019-08-04 21:08
This has been an issue forever:

https://github.com/Foundry376/Mailspring/issues/1571

https://github.com/Foundry376/Mailspring/issues/1583

https://github.com/Foundry376/Mailspring/issues/1407

And probably more.

**Comment by CodeMouse92** [comment] 2021-02-15 21:16
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

Based on the comments above, this issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/database-is-locked/420

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-15 21:16 UTC
Labels: audit
