### ISSUE TITLE
Bug: Retrieval using the IMAP4 protocol failed for the following message: XXX

### ISSUE THREAD

**Issue by mp1994** [Foundry376/Mailspring#2038] opened 2020-06-01 09:35 UTC
**Describe the bug**
The search box for a Microsoft 365 account appears to work only with the most recent (probably locally-cached) messages. If I use the `since` and `before` keywords, I get a list of messages that say `Retrieval using the IMAP4 protocol failed for the following message: XXX`, where XXX is the number of the message (see screenshot below)

**To Reproduce**
1. Go to the search box and type a custom date range, i.e. `since: "2020/02/05" before: "2020/02/07"`
2. Click on any message found, they should be all the same. In particular,
> Sender: Microsoft Exchange Server
  Object: Retrieval using the IMAP4 protocol failed for the following message: 205
  No body (spinning wheel implying that the message is loading)

**Expected behavior**
I guess the messages, that are correctly found in the sever, should load kind of quickly (within a minute or so). They are found very quickly and they are mostly text-only, so I would expect fast loading.

**Screenshots**
![image](https://user-images.githubusercontent.com/23299360/83396114-c1b1df80-a3fb-11ea-93ac-b2fc1e83bae0.png)

**Setup: (please complete the following information):**
 - OS: Ubuntu 18.04 LTS, Linux kernel version 4.15.0-1081-oem
 - Mailspring Version: 1.7.8-13635bcf

**Additional context** 
I have set up only the Microsoft 365 account of my organization. I also get the "One or more account are having connection issues..." message quite often (it is also visible in the screenshot), but the syncing of messages works well...

**Comment by CodeMouse92** [comment] 2021-03-02 02:10
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/retrieval-using-the-imap4-protocol-failed-for-the-following-message/911

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@mp1994: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 02:10 UTC
Labels: audit, bug
