### ISSUE TITLE
Cannot attach files stored in NTFS partition with snap version

### ISSUE THREAD

**Issue by nihil21** [Foundry376/Mailspring#749] opened 2018-03-09 00:14 UTC
Hi,
I'm running Mailspring snap in Manjaro 17.1.6.
I have a second NTFS partition, and when I try to attach files stored there Mailspring returns an error message:
![screenshot_20180308_222736](https://user-images.githubusercontent.com/15859553/37183549-e0b3e632-2336-11e8-942e-6af4e79b9986.png)

The icon-less folders are links to folders on NTFS partition:
![screenshot_20180308_222630](https://user-images.githubusercontent.com/15859553/37183547-dce36fbe-2336-11e8-9aec-83f08d1d261e.png)

I've already connected mailspring to removable-media interface with `sudo snap connect mailspring:removable-media`, and I have also checked owner and permissions of the NTFS partition through `/etc/fstab`, but none of that worked.
I'm not sure if it's due to snap confinement or its a Mailspring problem at this point.
What do you think?

**Comment by Mikerr1111** [comment] 2018-03-11 02:20
@Void97, The issue your experiencing is likely due to the NTFS partition being in Read-Only mode. It's a common issue in Linux. These forums should put you in the right direction. 
https://wiki.archlinux.org/index.php/NTFS-3G
https://forum.manjaro.org/t/cant-modify-contents-on-ntfs-drives/33014. 
https://forum.manjaro.org/t/formatting-flash-drive-with-ext4-or-ntfs-gives-issues/3957/45

**Comment by Void97** [comment] 2018-03-11 13:01
It's not Read-Only, in fact I can create and delete file normally; the problem is that I cannot access it with Mailspring snap to attach files.

**Comment by Void97** [comment] 2018-03-11 17:29
I noticed that skype snap, installed with classic confinement, can read the files stored in NTFS partition. So maybe the problem is that Mailspring snap doesn't support classic confinement, I suppose.

**Comment by Void97** [comment] 2018-03-11 18:34
After a little of research, I've found that binding directories from NTFS partition to /home makes them browsable from snap apps with no classic confinement, and now I can attach files.
Not sure if mark this as solved though, since I cannot really browse NTFS files without this workaround.

**Comment by bengotow** [comment] 2018-03-19 20:56
Hey! Thanks for digging in to this—I think you're right that this is most likely an issue with snap confinement. It might be a good idea to bring it up in the snapcraft forums (https://forum.snapcraft.io) and see if it could be fixed in snapd. In the meantime I'll leave this open so it's easier for folks to find!

**Comment by davenorthcreek** [comment] 2020-04-07 03:06
I was told to type:
`sudo snap connect mailspring:removable-media
`
and that would allow mailspring to access other drives mounted on my system.  It had no effect (and no error message was raised either).

**Comment by ncounter** [comment] 2020-05-13 14:38
@davenorthcreek did it work for you? I tried `sudo snap connect mailspring:removable-media` but with no luck. But I may have a slightly different scenario I am not sure if it fits in the current issue or it is for another (or maybe even against snap).

I am on an openSUSE Leap 15.1 machine, and partitions and volumes everything is managed by LVM. I installed `Mailspring` via `snap`. The issue is that I cannot attach a file from a different Volume: I am on `/dev/system/home/` and I want to attach a file from `/dev/storage/`

### LVM
![lvm](https://user-images.githubusercontent.com/7080830/81825156-92176200-9536-11ea-8e33-85c6c205b623.png)

### OS files
![files](https://user-images.githubusercontent.com/7080830/81826011-955f1d80-9537-11ea-9ccd-5270f7de38ee.png)

### Mailspring
![mailspring](https://user-images.githubusercontent.com/7080830/81826028-9b54fe80-9537-11ea-94c3-d682d7f7e951.png)

As you can see there is not `/storage` in the `Mailspring` attachment list option, and if I even click on the location shortcut on the left, it still shows me the content of `/`.

Any idea? Thank you

**Comment by davenorthcreek** [comment] 2020-05-13 16:49
One hack that worked - create a symlink to your /storage partition from your home directory and connect that way.

**Comment by davenorthcreek** [comment] 2020-05-13 16:54
If that doesn't work, what I ended up doing was mounting my /data partition in /media/data as well as at /data.  I updated a bunch of shortcuts in my file browser and now the problem is gone.  Mailspring with the `sudo snap connect mailspring:removable-media` addition looks for partitions mounted in /media, not partitions mounted from the root (because it thinks it's looking for usb sticks I guess).

**Comment by davenorthcreek** [comment] 2020-05-13 17:07
If that doesn't work, just switch to the non-snap version.

**Comment by ncounter** [comment] 2020-05-13 18:53
Unfortunately, none of the hacking options worked. I am not willing to uninstall and reinstall actually, so I will just live with it as it is: I can always `copy` the attachment under a temp dir for a while of sending an e-mail, it's not a big deal. If it turns out I will figure out the right hack to make it work I'll also update you here. Thanks for your support.

**Comment by CodeMouse92** [comment] 2021-02-10 20:47
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/cannot-attach-files-stored-in-ntfs-partition-with-snap-version/557

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

OP: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-10 20:47 UTC
Labels: audit, linux, snapcraft
