### ISSUE TITLE
“Syncing your mailbox" forever again: "Applying tasks"

### ISSUE THREAD

**Issue by JunnanZ** [Foundry376/Mailspring#245] opened 2017-10-25 00:48 UTC
##### Are there any related issues?

No

##### What operating system are you using?
Arch

##### What version of Mailspring are you using?
1.0.6

**Bug?**
I sent a delayed email today to test the function, and after that mailspring is stuck in "syncing your mailbox". After I click that, it says "applying tasks". CPU usage is high and I can't find anything related to this in mailsync logs.

##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

**Comment by pat-s** [comment] 2017-11-30 12:55
Same problem on Arch/KDE with v1.0.8

**Comment by DakshMiglani** [comment] 2019-02-02 14:16
still happening.

**Comment by cpacchierotti** [comment] 2019-02-11 08:00
This may be the same as #435.

**Comment by CodeMouse92** [comment] 2021-01-28 03:30
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/the-eternal-sync-bug/334

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 03:30 UTC
Labels: audit
