### ISSUE TITLE
Bug: Overflow Show in clean inbox image

### ISSUE THREAD

**Issue by DevBacega** [Foundry376/Mailspring#2131] opened 2020-08-28 03:27 UTC
**Describe the bug**
When the box is empty, it shows a picture "Long life!   You're ready" but the overflow is showing

**To Reproduce**
1. Go to Inbox
2. Empty it
3. You'll see the "checked" picture and the message
4. See error, the overflow is appear

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/54642509/91517816-1cf15200-e8c5-11ea-8bbc-09472cddd5ef.png)

**Setup: (please complete the following information):**
 - OS: Windows 10
 - OS Version: 2004
 - Mailspring Version: 1.7.8

**Comment by CodeMouse92** [comment] 2021-03-02 18:20
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/overflow-show-in-clean-inbox-image/927

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@DevBacega: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 18:20 UTC
Labels: audit, bug
