### ISSUE TITLE
Bug: Failed to send email by gmail

### ISSUE THREAD

**Issue by hechengjin** [Foundry376/Mailspring#2107] opened 2020-07-30 01:30 UTC
**Describe the bug**
I use xxxx@gmail.com sent to myselft, but I can't get the email.

Setup: (please complete the following information):
OS: Windows 10 edu 64bit
OS Version 17763
Mailspring Version: 1.7.8

**Comment by CodeMouse92** [comment] 2021-03-02 21:38
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/emails-with-same-to-from-address-disappear-from-inbox/597

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 21:38 UTC
Labels: audit, bug
