### ISSUE TITLE
Feature request: dark tray icon for light desktop themes

### ISSUE THREAD

**Issue by justindoran** [Foundry376/Mailspring#209] opened 2017-10-19 19:01 UTC
##### What operating system are you using?
ArchLinux

##### What version of Mailspring are you using?
1.0.5

**Feature Request?**
Could you make a dark version of the tray icon for light desktop color schemes and put it on a switch in the preferences? It's currently invisible with my light color scheme on Xfce.

##### Does this feature exist in another mail client or tool you use?
Yes, notably qBittorrent.

**Comment by mahmadmujtaba** [comment] 2019-01-26 10:55
I am still looking towards this feature. 2019 it is now.

**Comment by sergey-s-moiseev** [comment] 2019-03-14 15:01
#225 is closed, but icon still ugly for light themes... So sad...

**Comment by IgnusG** [comment] 2019-03-14 16:01
@sergey-s-moiseev try out https://github.com/bilelmoussaoui/Hardcode-Tray with the Papirus-Light theme. Worked pretty well for me, even if it is a hack.

![DeepinScreenshot_select-area_20190314170022](https://user-images.githubusercontent.com/6438760/54371995-b8174d00-467a-11e9-998f-500b531d81c0.png)

**Comment by CodeMouse92** [comment] 2021-02-20 03:47
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue is related to one we already migrated to Discourse:

https://community.getmailspring.com/t/implement-a-dark-tray-icon-for-light-themes/700/9

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@justindoran: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-20 03:47 UTC
Labels: audit, enhancement
