### ISSUE TITLE
Feature Request: Keyboard shortcuts/menubar buttons for Contacts and Calendar

### ISSUE THREAD

**Issue by Darthagnon** [Foundry376/Mailspring#1980] opened 2020-05-12 21:08 UTC
Could we please have keyboard shortcuts and menubar items for Calendar and Contacts? It would also be convenient to have a CLI option to launch just Contacts or just Calendar views, without the mail client. (making it possible to make "Calendar App" and "Contacts App" shortcuts for Windows, so it looks and works like Mac OS

**Comment by CodeMouse92** [comment] 2021-03-01 23:36
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/keyboard-shortcuts-menubar-buttons-for-contacts-and-calendar/893

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@Darthagnon: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-01 23:36 UTC
Labels: audit, enhancement
