### ISSUE TITLE
[Feature Request] Automatically retrieve Gmail aliases / signatures

### ISSUE THREAD

**Issue by kanocz** [Foundry376/Mailspring#489] opened 2017-12-29 13:24 UTC
In GSuite account I have more email aliases and domains and on generic gmail web client I'm able to select sender address, in Mailspring I can select only primary sender email from each account even in case if some of accounts has email aliases on many domains

##### What operating system are you using?
Linux, OSX

##### What version of Mailspring are you using?
1.0.12

**Comment by bengotow** [comment] 2017-12-29 17:24
Hey! To use your aliases, you need to configure them from Preferences > Accounts. Hope that helps—

**Comment by bengotow** [comment] 2017-12-29 17:40
Edit: It actually looks like there's a new Gmail API for accessing alias configuration automatically. I'll see if we can automate this so you don't have to configure it in Mailspring:
https://developers.google.com/gmail/api/v1/reference/users/settings/sendAs

**Comment by DennisLypovetsky** [comment] 2018-10-21 10:49
The feature is still missing :(

**Comment by CodeMouse92** [comment] 2021-02-24 18:31
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/automatically-retrieve-gmail-aliases-signatures/760

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@kanocz: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-24 18:31 UTC
Labels: audit, enhancement
