### ISSUE TITLE
Bug: Mailspring was unable to create or delete the LaunchAgent file

### ISSUE THREAD

**Issue by squintgit** [Foundry376/Mailspring#1960] opened 2020-05-02 15:32 UTC
**Describe the bug**
When I try to disable "Launch on system start", I get this error:

<img width="636" alt="Screen Shot 2020-05-02 at 9 50 17 AM" src="https://user-images.githubusercontent.com/11663794/80868370-bb471100-8c5f-11ea-99d8-944c05a32567.png">

I wanted to use the "Login Items" feature of macOS so I could hide Mailspring on start, which doesn't seem achievable just using the "Launch on system start" feature in Mailspring.

**To Reproduce**
1. Go to Preferences
2. Try to untick "Launch on system start"

Error above received.

**Expected behavior**
I expected no error to appear and for the box to get unticked.

**Screenshots**
See above.

**Setup: (please complete the following information):**
 - OS: macOS
 - OS Version 10.14.6
 - Mailspring Version: 1.7.6

**Additional context** 
I only recently installed Mailspring.

**Comment by bengotow** [comment] 2020-05-03 21:36
Hey thanks for reporting this! I'll see if I can reproduce this - I wonder if something changed in macOS 10.14.

**Comment by RavHilton** [comment] 2020-08-08 01:51
I just installed Mailspring (through Homebrew) and am seeing the exact same error message on Catalina 10.15.6.

**Comment by designlabmx** [comment] 2020-11-22 13:35
Same On High Sierra 10.13.6

__Mailspring was unable to create or delete the LaunchAgent file at /Users/designlab/Library/LaunchAgents/com.mailspring.plist.__

Error: ENOENT: no such file or directory, open '/Users/designlab/Library/LaunchAgents/com.mailspring.plist'

came wile swishing to debug flags

**Comment by cabbage** [comment] 2021-02-19 08:30
I get the same message after installing via homebrew `brew install --cask mailspring`

![Screenshot 2021-02-19 at 09 25 16](https://user-images.githubusercontent.com/820175/108478317-a130fa80-7294-11eb-906f-fa6fa2c88b29.png)

**Comment by CodeMouse92** [comment] 2021-02-19 19:20
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mailspring-was-unable-to-create-or-delete-the-launchagent-file/708

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@squintgit @RavHilton @designlabmx @cabbage: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-19 19:20 UTC
Labels: audit, bug, macos
