### ISSUE TITLE
Forwarding a message removes pasted images

### ISSUE THREAD

**Issue by gdepourtales** [Foundry376/Mailspring#1380] opened 2019-02-21 14:55 UTC
To reproduce

- Create a new message
- Paste a screenshot in the message
- Send it
- Forward the message. The image is removed. See screenshot

![image](https://user-images.githubusercontent.com/810628/53177785-ec09d000-35f0-11e9-9057-d5c748254f63.png)

##### Are there any related issues?

Didn't find any

##### What operating system are you using?

Linux on i3wm
Linux 4.20.8-arch1-1-ARCH #1 SMP PREEMPT Wed Feb 13 00:06:58 UTC 2019 x86_64 GNU/Linux

##### What version of Mailspring are you using?
1.5.6-4cb1851b

--

**Bug?**

##### Is this an email sync or connection issue?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No. It is the same with all providers

##### Is the issue reproducible with a particular attachment, message, signature, etc?
It is reproducible with any image

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?
Yes. All emails clients keep the image in the forwarded email

**Comment by mib888** [comment] 2019-02-22 16:24
I also have the problem with images in forwarded messages and join to the issue.

**Comment by Galvanize87** [comment] 2019-07-25 08:48
Having the same problem, by the way the images are the signatures and forwarding signatures are lost.

**Comment by followthekoden** [comment] 2019-07-30 19:18
I have the same issue

**Comment by sid-dob** [comment] 2019-09-04 06:36
Same Issue

**Comment by jaskipper** [comment] 2019-09-24 14:17
This issue seems to be for everyone. It's happening to me on two different computers, and to a business partner who is also now using MailSpring. When forwarding a message that has inline images, those images are not included in the forward. This is a dealbreaker for us. Is there any type of work around for this issue?

**Comment by hantms2** [comment] 2019-11-14 08:41
Happening to me too. Can't really use it for anything real if I can't forward an image..

**Comment by hantms2** [comment] 2019-11-15 01:46
Only workaround I found:  Before forwarding, right click the image and copy it to the clipboard.  Then forward and paste it back in the right place in the forwarded message.   Really not ideal and downright impossible when there are multiple images.

**Comment by KorbinianMossandl** [comment] 2020-03-30 17:44
BUMP
this is SUPER important

**Comment by jvik** [comment] 2020-09-07 11:32
Same issue here as well

**Comment by hardeep** [comment] 2020-10-21 18:12
Happening here as well.

**Comment by CodeMouse92** [comment] 2021-02-10 21:10
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/forwarding-a-message-removes-pasted-images/558

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@gdepourtales @hardeep: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-10 21:10 UTC
Labels: audit

**Comment by CodeMouse92** [comment] 2021-02-10 21:20
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/forwarding-a-message-removes-pasted-images/558

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@gdepourtales @hardeep: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team
