### ISSUE TITLE
On Linux, exiting the application doesn't truly exit

### ISSUE THREAD

**Issue by pascalwhoop** [Foundry376/Mailspring#1563] opened 2019-07-05 17:47 UTC
When closing the application with the right click context menu of the tray icon, processes remain open 

```
21375 ?        Sl     0:00 /usr/share/mailspring/resources/app.asar.unpacked/mailsync.bin --mode sync --info mail@...
```

A "close" should _close_ the application. We're on linux guys, please no funny business!

**Comment by lucas-gautier** [comment] 2019-07-06 19:06
Can confirm - rogue mailspring processes found after a standard "close". Have to kill the stragglers... 

`S+   13:02   0:00 /bin/bash /usr/share/mailspring/resources/app.asar.unpacked/mailsync --mode sync --info`                              
`Sl+  13:02   0:03 /usr/share/mailspring/resources/app.asar.unpacked/mailsync.bin --mode sync --info`
`Sl+  01:39   2:23 /usr/share/mailspring/mailspring`
`S+   01:39   0:00 /usr/share/mailspring/mailspring --type=zygote --no-sandbox`
`Sl+  01:39   2:23 /usr/share/mailspring/mailspring --type=gpu-process --enable-features=SharedArrayBuffer --no-sandbox`

**Comment by Tomschi** [comment] 2019-08-05 05:51
Can also confirm the issue.
Mostly, the following dialog is shown in KDE, when i closing the application:

![mailspring](https://user-images.githubusercontent.com/1133900/62441408-47212080-b754-11e9-98e8-eff664e57083.png)

Apport reports that the following command produces the issue:
```usr/share/mailspring/resources/app.asar.unpacked/mailsync.bin --mode sync --info <email>```

**Comment by bengotow** [comment] 2019-10-22 05:29
Hey folks! Can you confirm that these processes don't exit on their own <15 seconds after the app is quit? There are some odd scenarios in which the app can exit without having a chance to clean up it's child processes, but they're actually designed to exit on their own if the socket to the app is closed. If they hang around past that they must be really stuck.

**Comment by Tomschi** [comment] 2019-10-23 19:08
Since version 1.7.x the KDE dialog is gone, but the child processes need 1 - 2 minutes to exit after the app is quit.

**Comment by Tomschi** [comment] 2020-01-07 07:23
The KDE Dialog above is shown every time i quit the application, now. So the behavior has worsened.

**Comment by mhadidg** [comment] 2020-03-02 11:26
Also experiencing this issue on Ubuntu 19.10. A crash report, like the example below, often pops up after closing the application from the context menu.

![Screenshot from 2020-03-02 14-16-28](https://user-images.githubusercontent.com/11995027/75671785-6fdcaa80-5c90-11ea-97c9-7954cae0401a.png)

**Comment by SteveSte** [comment] 2020-11-01 18:14
the bug is still present, even after 15 minutes the mailspring, mailsync, main processes are still there (one for each of my three email accounts)

**Comment by CodeMouse92** [comment] 2021-01-28 03:36
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/exit-on-x-button-with-no-minimize-to-tray/207/4

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 03:36 UTC
Labels: audit, linux
