### ISSUE TITLE
Automatic CC doesn't respect which account is selected

### ISSUE THREAD

**Issue by hellopablo** [Foundry376/Mailspring#1354] opened 2019-02-06 15:19 UTC
##### Are there any related issues?

No related issues that I could see.

##### What operating system are you using?

Mac OS Mojave 10.14.2

##### What version of Mailspring are you using?

1.5.5-b7939d38

--

**Bug?**

##### Is this an email sync or connection issue?

N/A

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

N/A (I don't think, but both accounts are Gmail)

##### Is the issue reproducible with a particular attachment, message, signature, etc?

I have two Gmail accounts, work and personal. For my work one I have specified two email addresses to automatically CC (my colleagues).

When I compose a new email, or reply they are added as expected. However, when I switch the email, or respond to an email from the _other_ account they are still there (either added when the compose window opens, or not removed when I switch to the other account).

This seems like a small issue, until I'm sending a personal email (to say my partner, doctor, lawyer, therapist, etc) and all of a sudden accidental leaking of personal information is extremely easy!

**Comment by CodeMouse92** [comment] 2021-02-10 21:53
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/automatic-cc-doesnt-respect-which-account-is-selected/561

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@hellopablo: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-10 21:53 UTC
Labels: audit
