### ISSUE TITLE
Problem setting up IMAP/SMTP account

### ISSUE THREAD

**Issue by Sytred** [Foundry376/Mailspring#1322] opened 2019-01-12 16:54 UTC
##### Are there any related issues?

Apparently yes though my log is different.

##### What operating system are you using?

Ubuntu 18.04 LTS

##### What version of Mailspring are you using?

1.5.5-b7939d38 (snap package)

**Bug?**

##### Is this an email sync or connection issue?

Yes. After adding my account which is done without error, it tries syncing and shows "une erreur s'est produite lors de la synchronisation xxx@y.com ; réessayer" ("An error occured while synchronizing xxx@y.com ; try again")

Here is the log :

```6207 [2019-01-12 17:43:17.608] [main] [info] Identity created at 1547300119 - using ID Schema 1
6207 [2019-01-12 17:43:17.610] [main] [info] ------------- Starting Sync (d.banuls_16@envt.fr) ---------------
6207 [2019-01-12 17:43:17.612] [background] [info] Marking all folders as `busy`
6207 [2019-01-12 17:43:17.612] [background] [info] Syncing folder list...
6207 [2019-01-12 17:43:17.613] [metadata] [info] Metadata delta stream starting...
6207 [2019-01-12 17:43:18.299] [background] [critical] 
 ***
 *** A C++ exception occurred during program execution: 
 *** UNIQUE constraint failed: Folder.id
 ***

6207 [2019-01-12 17:43:18.302] [background] [critical]  *** Stack trace:
 ***   clone
 ***
```

(It writes this many times as if it tries to sync like three or four times in a row but it is always the exact same message.)

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

I get this issue with my uni mail.

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

I had successfully set up this mail account on my mobile phone (both integrated and gmail apps) and on my laptop with Thunderbird and Evolution.

**More information**

My email support asks setting connection mode as LOGIN or PLAIN with SSL/TLS security, but I can't find LOGIN or PLAIN in Mailspring. Could it be related ?

The problem remains when using the deb package instead of the snap

Mailspring does have access to my mailbox since it successfully creates the Mailspring and Mailspring/snooze folders (log :)

```10103 [2019-01-12 18:11:25.580] [main] [info] Identity created at 1547300119 - using ID Schema 1
10103 [2019-01-12 18:11:25.582] [main] [info] ------------- Starting Sync (d.banuls_16@envt.fr) ---------------
10103 [2019-01-12 18:11:25.583] [background] [info] Marking all folders as `busy`
10103 [2019-01-12 18:11:25.583] [background] [info] Syncing folder list...
10103 [2019-01-12 18:11:25.584] [metadata] [info] Metadata delta stream starting...
10103 [2019-01-12 18:11:26.483] [background] [error] Created Mailspring container folder: Mailspring.
10103 [2019-01-12 18:11:26.625] [background] [error] Created required Mailspring folder: Mailspring/Snoozed.
10103 [2019-01-12 18:11:26.628] [background] [critical] 
 ***
 *** A C++ exception occurred during program execution: 
 *** UNIQUE constraint failed: Folder.id
 ***

10103 [2019-01-12 18:11:26.644] [background] [critical]  *** Stack trace (line numbers are approximate):
 *** (unknown)  clone
 ***
```

**Comment by harshadgavali** [comment] 2019-01-13 08:51
I'd exactly same problem on Ubuntu 18.04 and 18.10 as well, while using LAN(proxy-configured).
But I was able to set it up using WIFI(No proxy).

While using LAN, I was able to login into mailspring account.

**Comment by Sytred** [comment] 2019-01-13 11:42
Unless there's something I've not understood, I don't think I'm using any kind of proxy. (In Network settings --> Proxy, it says "Disabled"). Thanks anyway :)

**Comment by Sytred** [comment] 2019-01-13 16:33
**SOLVED :** I foolishly did several things at once so I don't know which one actually worked. In order from (in my opinion) least to more likely to be the solution : 
**-->** Emptied trash and several other folders
**-->** Deleted several subfolders (folders inside folders)
**-->** Deleted a "Sent Items" folder which had been created by another mail client
**-->** Deleted tags

Thanks for your help :)

**Comment by Sytred** [comment] 2019-01-14 00:32
**LAST UPDATE : (Promise ^^)**

Looks like it was the "Sent Items" folder : I recreated it and instantly the problem appeared again (with similar logs). I had to delete the folder and empty the bin, remove the account, delete the _whole_ cache and add the account again.

Apparently it's a tongue problem : I'm French so my _true_ Sent Items folder is called "Envoyés" (and Mailspring does recognise it as such but calls it Sent Items), but creating a folder with the name "Sent Items" (in English) seems to confuse it as to which one is the real folder it should use for sent mail.

Hope this will help you fix this bug !

**Comment by rigg77** [comment] 2020-08-12 16:24
I had a similar issue on Win10 

Fixed via 'Preferences>Accounts>Rebuild Cache' then 'Reconnect' solved the issue. I believe its a caching issue with folders. Reconnect could have a function that rebuilds cache automatically for persistent issues.

**Comment by andrelug** [comment] 2020-08-27 18:09
Just to confim if anyone is having issues with this sync problem, it's indeed the language of the imap/smtp provider. Changing the language to English worked.

**Comment by CodeMouse92** [comment] 2021-02-02 03:04
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/syncfolderuidrange-errorconnection-on-one-of-the-folders/412/2

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-02 03:04 UTC
Labels: audit
