### ISSUE TITLE
Mailspring syncFolderUIDRange problem

### ISSUE THREAD

**Issue by carlospg79** [Foundry376/Mailspring#717] opened 2018-02-22 13:19 UTC
##### Are there any related issues?

i don't know

##### What operating system are you using?
Ubuntu 17.10 and Windows 10

##### What version of Mailspring are you using?
Latest 1.1.4

--

**Bug?**
when i use mailspring to connect to my work account, it doesn't sync all the folders

the output in the log file is
`12824 [2018-02-22 13:31:57.628] [background] [info] syncFolderUIDRange for INBOX/Proyectos/ID/Stardust/Iot, UIDs: 1 - 49, Heavy: true`

`12824 [2018-02-22 13:32:08.219] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID","key":"ErrorParse","retryable":true,"what":"std::exception"}`

The difference i see with previous succesfull folders is that heavy option is marked as true.

##### Do you have any third-party plugins installed? If so, which ones?
None

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
davmail usage to connect an exchange account without imap support

##### Is the issue reproducible with a particular attachment, message, signature, etc?

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
no, if i use thunderbird to connect to davmail, it works without problem
update: with nylas-mail-live, the sync finish succesfully

**Comment by jasonfrowe** [comment] 2018-05-06 17:11
I'm having a similar problem.  Scanning is stuck at 0% for all folders. 
Here are the log entries

5984 [2018-05-06 12:35:43.942] [metadata] [info] Metadata delta stream starting...
5984 [2018-05-06 12:35:43.944] [background] [info] Marking all folders as `busy`
5984 [2018-05-06 12:35:43.945] [background] [info] Syncing folder list...
5984 [2018-05-06 12:35:44.267] [background] [info] Syncing folder list...
5984 [2018-05-06 12:35:44.538] [foreground] [info] Connection does not support idling. Locking until more to do...
5984 [2018-05-06 12:35:44.569] [background] [info] syncFolderUIDRange for INBOX, UIDs: 1 - 8211, Heavy: true
5984 [2018-05-06 12:35:45.702] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID","key":"ErrorParse","retryable":true,"what":"std::exception"}
5984 [2018-05-06 12:35:58.940] [metadataExpiration] [info] Scanning for expired metadata
5984 [2018-05-06 12:35:58.940] [metadataExpiration] [info] -- Will wake for next expiration in 7200sec

**Comment by antoine-duchenet** [comment] 2018-05-07 06:56
Hi,
I'm getting a similar problem too, the main difference is that I raise an "ErrorConnection", not an "ErrorParse" ;

```
704 [2018-05-07 08:54:33.635] [background] [info] Syncing folder list...
704 [2018-05-07 08:54:33.948] [background] [info] syncFolderUIDRange for INBOX, UIDs: 1 - 165728, Heavy: false
704 [2018-05-07 08:54:34.101] [background] [info] - remote=3373, local=0
704 [2018-05-07 08:54:34.136] [background] [info] - Fetching full headers for 3373 (of 3373 needed)
704 [2018-05-07 08:55:04.227] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID (heavy)","key":"ErrorConnection","retryable":true,"what":"std::exception"}
```

**Comment by sjjf** [comment] 2018-05-24 23:27
I'm seeing something similar as well, with version 1.2.1, running against an office365.com email account:

```
3586 [2018-05-25 09:13:09.275] [background] [info] Syncing folder list...
3586 [2018-05-25 09:13:11.018] [background] [info] syncFolderUIDRange for INBOX, UIDs: 1 - 75497, Heavy: false
3586 [2018-05-25 09:13:11.429] [background] [info] - remote=3152, local=0
3586 [2018-05-25 09:13:11.454] [background] [info] - Fetching full headers for 3152 (of 3152 needed)
3586 [2018-05-25 09:13:11.855] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID (heavy)","key":"ErrorFetch","retryable":true,"what":"std::exception"}
3586 [2018-05-25 09:15:11.855] [background] [info] Syncing folder list...
3586 [2018-05-25 09:15:11.874] [background] [info] Sleeping after exception: {"debuginfo":"syncFoldersAndLabels - fetchAllFolders","key":"ErrorConnection","retryable":true,"what":"std::exception"}
3586 [2018-05-25 09:17:11.875] [background] [info] Syncing folder list...
3586 [2018-05-25 09:17:13.508] [background] [info] syncFolderUIDRange for INBOX, UIDs: 1 - 75497, Heavy: false
3586 [2018-05-25 09:17:14.102] [background] [info] - remote=3152, local=0
3586 [2018-05-25 09:17:14.134] [background] [info] - Fetching full headers for 3152 (of 3152 needed)
3586 [2018-05-25 09:17:14.370] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID (heavy)","key":"ErrorFetch","retryable":true,"what":"std::exception"}`
```
That's the last couple of instances of the same error message, with the same message count every time - it doesn't look like it's making any progress.

The same account works fine with sylpheed.

>

**Comment by s881628** [comment] 2018-05-30 00:47
Same here.  Scanning never completes.
Version 1.2.1 For Mac OS 10.13.4

> 10600 [2018-05-30 10:40:58.917] [background] [info] Syncing folder list...
> 10600 [2018-05-30 10:41:32.104] [background] [info] syncFolderUIDRange for [Gmail]/All Mail, UIDs: 1 - 0, Heavy: false
> 10600 [2018-05-30 10:42:18.208] [background] [info] - remote=88562, local=87532
> 10600 [2018-05-30 10:42:18.423] [background] [info] - Fetching full headers for 1033 (of 1033 needed)
> 10600 [2018-05-30 10:42:47.358] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID (heavy)","key":"ErrorConnection","retryable":true,"what":"std::exception"}

**Comment by s881628** [comment] 2018-05-30 21:59
Just upgraded to version 1.2.2 and the exact same thing is still happening.  I love this app but whilst this issue exists, it's hard to justify a monthly subscription, especially when Airmail offers all mailspring does and more for a once off fee...

**Comment by ShiveshM** [comment] 2018-05-30 23:32
Also seeing the same issue, Version 1.2.1 for Ubuntu 18.04 LTS
```
29548 [2018-05-30 18:23:09.453] [background] [info] Syncing folder list...
29548 [2018-05-30 18:23:12.189] [background] [info] syncFolderUIDRange for INBOX, UIDs: 1 - 54057, Heavy: false
29548 [2018-05-30 18:23:12.855] [background] [info] - remote=4591, local=0
29548 [2018-05-30 18:23:12.899] [background] [info] - Fetching full headers for 4591 (of 4591 needed)
29548 [2018-05-30 18:23:12.955] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID (heavy)","key":"ErrorFetch","retryable":true,"what":"std::exception"}
29548 [2018-05-30 18:25:12.956] [background] [info] Syncing folder list...
29548 [2018-05-30 18:25:12.970] [background] [info] Sleeping after exception: {"debuginfo":"syncFoldersAndLabels - fetchAllFolders","key":"ErrorConnection","retryable":true,"what":"std::exception"}
29548 [2018-05-30 18:27:12.970] [background] [info] Syncing folder list...
29548 [2018-05-30 18:27:16.005] [background] [info] syncFolderUIDRange for INBOX, UIDs: 1 - 54057, Heavy: false
29548 [2018-05-30 18:27:16.677] [background] [info] - remote=4591, local=0
29548 [2018-05-30 18:27:16.717] [background] [info] - Fetching full headers for 4591 (of 4591 needed)
29548 [2018-05-30 18:27:16.794] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID (heavy)","key":"ErrorFetch","retryable":true,"what":"std::exception"}
29548 [2018-05-30 18:29:16.794] [background] [info] Syncing folder list...
29548 [2018-05-30 18:29:16.810] [background] [info] Sleeping after exception: {"debuginfo":"syncFoldersAndLabels - fetchAllFolders","key":"ErrorConnection","retryable":true,"what":"std::exception"}
```
Not all of the message headers have synced for my inbox, so a lot of the emails in there are just plain missing. Is there some workaround available?

**Comment by ShiveshM** [comment] 2018-06-01 21:42
Figured out a workaround. It gives this error if the folder is too large (has a couple thousand emails in it), so I split the folder into multiple folders in my mail client and after this everything synced OK.

**Comment by martinfejes** [comment] 2018-07-14 22:09
Works fine with version 1.10, every newer version throws this exception

**Comment by emallson** [comment] 2018-08-23 14:46
Having this same issue.

```
2384 [2018-08-23 10:30:39.579] [background] [info] Syncing folder list...
2384 [2018-08-23 10:30:40.033] [background] [info] syncFolderUIDRange for INBOX, UIDs: 1 - 37100, Heavy: false
2384 [2018-08-23 10:30:40.227] [background] [info] - remote=4270, local=0
2384 [2018-08-23 10:30:40.251] [background] [info] - Fetching full headers for 4270 (of 4270 needed)
2384 [2018-08-23 10:30:40.320] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID (heavy)","key":"ErrorFetch","retryable":true,"what":"std::exception"}
2384 [2018-08-23 10:32:40.320] [background] [info] Syncing folder list...
2384 [2018-08-23 10:32:40.369] [background] [info] Sleeping after exception: {"debuginfo":"syncFoldersAndLabels - fetchAllFolders","key":"ErrorConnection","retryable":true,"what":"std::exception"}
2384 [2018-08-23 10:34:40.369] [background] [info] Syncing folder list...
2384 [2018-08-23 10:34:40.828] [background] [info] syncFolderUIDRange for INBOX, UIDs: 1 - 37100, Heavy: false
2384 [2018-08-23 10:34:41.022] [background] [info] - remote=4270, local=0
2384 [2018-08-23 10:34:41.050] [background] [info] - Fetching full headers for 4270 (of 4270 needed)
2384 [2018-08-23 10:34:41.114] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID (heavy)","key":"ErrorFetch","retryable":true,"what":"std::exception"}
```

**Comment by ogkita** [comment] 2018-11-07 09:37
This bug exist jet in version 1.5.2.31660462. Please could you check it.

Sorry, we can not use this splendid application with this issue.

**Comment by robsilvia** [comment] 2018-11-12 19:00
I was able to resolve this issue by moving the mail in the problem folder into another, then moving it back.

**Comment by ogkita** [comment] 2018-11-13 11:06
Yes!

This workaround worked correctly.

Thank you very much.

**Comment by robsilvia** [comment] 2018-11-23 15:53
I just executed the command directly on the server, and maybe I do not have the volume of messages you have. I actually think the you can fix the issue without completely moving all the messages. If you look at the logs you'll see that total remote messages mailspring is calculating does not match the number actually on the server. You might be able to resolve the issue if you can identify the message indexed at where the count stops and move it along with some messages around it. I think the actual root cause is coming from either a malformed message header or a corrupted index on the mail server. Moving the messages is just a way to force the server to rebuild the metadata that mailspring is aborting at.

**Comment by alexandrutrifan** [comment] 2018-11-23 15:54
Hmm that’s legit. Thanks, I’ll try it.

**Comment by alexandrutrifan** [comment] 2018-11-23 17:46
Hmm that’s legit. Thanks, I’ll try it. Thanks @robsilvia .

Later edit:
It's not clear to me if a particular message triggers the issue, since the log states:
```
6149 [2018-11-23 19:35:18.236] [main] [info] ------------- Starting Sync ---------------
6149 [2018-11-23 19:35:18.243] [background] [info] Marking all folders as `busy`
6149 [2018-11-23 19:35:18.243] [metadata] [info] Metadata delta stream starting...
6149 [2018-11-23 19:35:18.249] [background] [info] Syncing folder list...
6149 [2018-11-23 19:35:19.239] [background] [info] Syncing folder list...
6149 [2018-11-23 19:35:19.346] [background] [info] syncFolderUIDRange for INBOX, UIDs: 1 - 151565, Heavy: false
6149 [2018-11-23 19:35:19.443] [background] [info] - remote=56, local=56
6149 [2018-11-23 19:35:19.582] [background] [info] syncFolderUIDRange for Sent Items, UIDs: 1 - 38215, Heavy: false
6149 [2018-11-23 19:35:19.832] [background] [info] - remote=4340, local=1
6149 [2018-11-23 19:35:19.844] [background] [info] - Fetching full headers for 4339 (of 4339 needed)
6149 [2018-11-23 19:35:20.139] [foreground] [info] syncFolderUIDRange for INBOX, UIDs: 1 - 151565, Heavy: false
6149 [2018-11-23 19:35:20.166] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID (heavy)","key":"ErrorFetch","retryable":true,"what":"std::exception"}
6149 [2018-11-23 19:35:20.251] [foreground] [info] - remote=56, local=56
6149 [2018-11-23 19:35:20.260] [foreground] [info] Idling on folder INBOX
```
It's not clear whether or not it gets stuck in the "Sent Items" folder, which, indeed, has a lot of emails.

(Maybe important, both Outlook and Apple Mail show that it has 4.539 emails, only this log shows 4.339 emails)

**Comment by robsilvia** [comment] 2018-11-23 18:09
Move the difference between the two plus a few extras. Assuming it's retrieving oldest first, move the oldest 210 messages out of the sent folder into a temporary folder and back in. Or if you feel that's too much count up from the oldest message to 200 and move it plus 5 above and below it; though you're much more likely to fix the issue if you do the first suggestion.

**Comment by martinfejes** [comment] 2019-04-11 10:45
It's really annoying, because this problem wasn't resolved for more than one year. I think there is problem with only one email in our Outlook365 account (but we don't know, which email, attachment, whatever is causing problem, log contains only exception {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID (heavy)","key":"ErrorFetch","retryable":true,"what":"std::exception"}). Everything works fine in version 1.1.0, but who can use it, when it always shows that message about new version of Mailspring and it's full of bugs. I think this issue deserves some attention, workaround above is not working for me.

**Comment by XGhozt** [comment] 2020-01-24 18:55
Every time I give Mailspring a try again, I run into this issue. Seems this one has existed for a years now. If the logs could just tell us which message or more information about the "exception" that would be great. Seems like there's one specific email that might be causing the issue. Perhaps a weird character or something other corruption?

**Comment by XGhozt** [comment] 2020-01-24 21:12
I think I might have figured out what was causing it, at least on my end. I went through around 50k messages and moved 500 or at a time into new folders until it got to that folder and triggered the error again. I kept doing this until I had enough small batches to see which email looked a little weird.

Eventually I ran into an email where (somehow) the "to" email address in the header had this in it (I've changed the actual name but you can see the characters):

`samuel;jackson"`

That's all it had for the "to". So somehow some text in the header became corrupt over the years and there was a semicolon and a quote character in there where they shouldn't have been.

I found 3 messages with the same thing. In my case they were from a Microsoft support ticket from 2013. I deleted all 3 messages (from server / webmail) and restarted Mailspring and it worked.

So this issue must have something to do with malformed headers containing unexpected characters. I can't tell if it's always been like this or just happened (my inbox has moved to several servers over the years).

**Comment by CodeMouse92** [comment] 2021-02-01 18:16
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/syncfolderuidrange-errorconnection-on-one-of-the-folders/412

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-01 18:16 UTC
Labels: audit
