### ISSUE TITLE
Clicking attachment on Linux doesn't open the document

### ISSUE THREAD

**Issue by monotasker** [Foundry376/Mailspring#540] opened 2018-01-17 19:30 UTC
##### What operating system are you using?
Ubuntu 17.10

##### What version of Mailspring are you using?
1.0.12-cf031332 (snap package)

##### Problematic behaviour

When I double-click on an attachment button at the bottom of a message, nothing happens. The attachment is not opened. 

This is the same for attachments in both my gmail and microsoft exchange accounts.

**Comment by oserban** [comment] 2018-01-23 13:25
This is a weird one actually. I have two Ubuntu installs:
1. 16.04 LTS and the double click in mailspring works as expected (opens the attachment)
2. 17.10 where the double click does not work anymore. 

Maybe this is an electron bug?

**Comment by harm0nic** [comment] 2018-01-23 16:43
I too have the same issue. Ubuntu 17.10

**Comment by bengotow** [comment] 2018-02-06 20:03
Hey folks thanks for reporting this - I think this is a bug in the snap package permissions or snap daemon, but haven't had time to take a look yet. It looks like it's related to #572

**Comment by CodeMouse92** [comment] 2021-02-18 23:34
It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-18 23:34 UTC
Labels: audit, bug, linux, snapcraft
