### ISSUE TITLE
Bug: Connectivity issue after suspend or change of network

### ISSUE THREAD

**Issue by pendula95** [Foundry376/Mailspring#1424] opened 2019-03-19 09:54 UTC
##### Are there any related issues?
Yes this issue partly covers it, alongside the issue described here I have issue same as here #468

##### What operating system are you using?
Fedora release 29 (Twenty Nine) x86_6
Kernel: 4.20.15-200.fc29.x86_64

##### What version of Mailspring are you using?
mailspring-1.6.0-0.1.x86_64

**Bug?**
When mailspring is in tray/background when network is changed or when my laptop wakes from sleep I get error `Several of your accounts are having issues` with options Check Again and Manage. If I click Check Again everything works. 

##### Is this an email sync or connection issue?
[mailsync-c67d0374.log](https://github.com/Foundry376/Mailspring/files/2982623/mailsync-c67d0374.log)
[mailsync-a182035f.log](https://github.com/Foundry376/Mailspring/files/2982625/mailsync-a182035f.log)
[mailsync-7f167e86.log](https://github.com/Foundry376/Mailspring/files/2982626/mailsync-7f167e86.log)

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No, all accounts fail.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
![image](https://user-images.githubusercontent.com/1239791/54596579-3ab25a80-4a35-11e9-8f91-10062ec33854.png)

**Comment by aia832003** [comment] 2019-03-20 22:32
Confirmed to see the same on kernel 4.20.15-200
fc29.x86_64 Fedora 29.

All accounts.

**Comment by MuTaTeD** [comment] 2019-04-05 07:12
Happens when network is changed or laptop is resumed from sleep or network dies and then reconnects.

**Comment by mamantoha** [comment] 2019-07-02 12:15
I have the same issue. Are there any updates?

**Comment by snqlby** [comment] 2019-07-19 06:48
This is really the main problem for me. We must trust our software, but I cannot be sure that the mail will be delivered on time.
I have to constantly check whether this error has appeared because I can miss an important letter and not react as I should.
@bengotow Does it have some architecture limitations to work it properly?

**Comment by CodeMouse92** [comment] 2021-02-16 01:36
It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-16 01:36 UTC
Labels: audit
