### ISSUE TITLE
Add "Mark as unread from this message"

### ISSUE THREAD

**Issue by ItachiSan** [Foundry376/Mailspring#1453] opened 2019-04-04 19:58 UTC
**Description**

Add the possibility in Mailspring to mark as unread all the messages of a thread from a starting message.

--

##### Are there any related issues?

The only somehow related issue is #486, which request something somehow different.

##### What operating system are you using?

Both ArchLinux and Windows.

##### What version of Mailspring are you using?

1.6.0

--

**Bug?**

##### Is this an email sync or connection issue?

Nope.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Nope.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Yes, any thread (it's a feature request)

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

GMail offers such option and I am quite sure other online e-mail services do that too.

**Comment by bengotow** [comment] 2019-05-27 00:08
Hey! Ahh man this would be really nice. I never noticed that feature in Gmail but I can see how it'd fit into a nice workflow.

Right now, Mailspring doesn't really have a concept of message "selection", which is becoming a problem. You can select a conversation and all the messages are shown, but in the message panel there's not really a "focused" one, so we can't reference a message in the app's menus. I think we need to change this soon and they we can add features like this more easily.

Stay tuned!

**Comment by ItachiSan** [comment] 2020-06-16 10:07
Well, hello again!
Got finally a more performant laptop and thus re-installed Mailspring.
This feature is still missing; any idea about this happening?

**Comment by CodeMouse92** [comment] 2021-02-25 23:37
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/add-mark-as-unread-from-this-message/804

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@ItachiSan: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-25 23:37 UTC
Labels: audit, enhancement
