### ISSUE TITLE
Yahoo mail

### ISSUE THREAD

**Issue by aliazani** [Foundry376/Mailspring#1974] opened 2020-05-08 12:57 UTC
Mailspring not syncing with yahoo account today I think yahoo changed something and MailSpring should update and change some options to fix this issue.
After that, I tried to logout and re-login to my yahoo account but I've got a Connection error.
I'm using Mailspring on ubuntu.
Mailspring version 1.7.6

**Comment by nightwatch75** [comment] 2020-05-08 14:11
Same problem here. I have 2 accounts (Gmail and Yahoo) configured on Mailspring, only Gmail is working. It seems an issue with the yahoo "app password" feature or Yahoo IMAP servers down.

**Comment by stivo85** [comment] 2020-05-08 23:38
Same here.
Generating new password for application nothing changes.

**Comment by aliazani** [comment] 2020-05-09 07:09
I think there is an issue in Imap servers or configuration so, I hope Mailspring fix the issue as fast as possible.

**Comment by ekawahyu** [comment] 2020-05-09 07:29
Same issue here, re-generating app password does not solve the issue. I went even further by completely reinstalled Mailspring and deleted ~/.config/Mailspring. Nothing works.

**Comment by endmarsfr** [comment] 2020-05-09 08:57
+1,
Same issue, nothing work, even after deleting account and re-generating new app password :(

**Comment by aliazani** [comment] 2020-05-09 17:45
@ekawahyu I think It's bug or incompatibality of Mailspring with IMAP because I test outlook too and same issue appeared.

**Comment by ekawahyu** [comment] 2020-05-09 18:52
@aliazani I had the same issue on Mac Mail. But once I re-generated the app password, it works just fine.

**Comment by aliazani** [comment] 2020-05-10 06:10
I checked re-generate the app password but nothing works , I'm still waiting for mailspring to answer.

**Comment by 2disbetter** [comment] 2020-05-10 11:02
I am having this issue as well on Ubuntu. I believe it is becuase yahoo started to use app passwords. I don't believe the issue is really so much Mailspring as it is the way Yahoo implemented their app passwords. I think yahoo's servers are expecting a specific application to access the account via the app password, and because Mailspring doesn't show up on that list, it is blocking Mailsprings attempts at using the app password. 

Or Yahoo changed their IMAP settings.

**Comment by nightwatch75** [comment] 2020-05-10 11:39
> I am having this issue as well on Ubuntu. I believe it is because yahoo started to use app passwords. I don't believe the issue is really so much Mailspring as it is the way Yahoo implemented their app passwords. I think yahoo's servers are expecting a specific application to access the account via the app password, and because Mailspring doesn't show up on that list, it is blocking Mailsprings attempts at using the app password.
> 
> Or Yahoo changed their IMAP settings. But now whether entering the IMAP settings manually or automatically, the connection does not ever seem to be even established.

actually mailspring support this kind of authentication method and give you the advice as well during the account setup. Running Mailspring in debug mode didn't help...

**Comment by aliazani** [comment] 2020-05-10 12:45
@2disbetter I don't think so because Geary works fine with yahoo mail and this kind of authentication
so, I think Mailspring have some trouble

**Comment by aliazani** [comment] 2020-05-10 12:46
@bengotow Could you please check this issue, please?

**Comment by olikugel** [comment] 2020-05-10 20:01
I'm having the same issue. Unable to add my Yahoo account... any update on this?

**Comment by bengotow** [comment] 2020-05-11 04:49
Hey folks! Thanks for reporting this, I have a test yahoo account and will see if I can reproduce the problems here 🙏  stay tuned.

**Comment by bengotow** [comment] 2020-05-11 04:57
Hmm, so I'm still able to connect Mailspring 1.7.6 to my Yahoo account. I tested first with my main yahoo password, and that actually worked, but it also works when I create an app password and use that.

Could you try opening this page on Yahoo's site, which shows recent login attempts to your account?
https://login.yahoo.com/account/activity

For me it looks like this. The top login is Mailspring with an app password I just named "Mailspring", and the one below that is the app logging in with my primary account password.
<img width="1310" alt="image" src="https://user-images.githubusercontent.com/1037212/81525266-bba77200-9319-11ea-99f2-91a9cab51f7f.png">

Under Yahoo's account security page (https://login.yahoo.com/account/security), I have these Two Step Verification turned off and "Yahoo Account Key" turned off. Any chance this is tied to having one of those features on?

![image](https://user-images.githubusercontent.com/1037212/81525326-f01b2e00-9319-11ea-8a19-0d0f13798754.png)

**Comment by ekawahyu** [comment] 2020-05-11 07:10
@bengotow I had the Two-step verification turned off, just like yours, but it does not work on my machine. Ubuntu 18.04.3 LTS, Mailspring 1.7.6 from Snap Store.

**Comment by stivo85** [comment] 2020-05-11 07:22
My settings looks just like yours @bengotow 
![image](https://user-images.githubusercontent.com/64167026/81534648-b1609480-9368-11ea-9798-f8a695a4bf06.png)
But **Mailspring doesn't connect** with main password or generated app password. And it doesn't show in last activity
![image](https://user-images.githubusercontent.com/64167026/81534797-eb319b00-9368-11ea-9233-116e217acfea.png)

**Comment by nightwatch75** [comment] 2020-05-11 07:53
Same here. I have the exact configurations in security and activity pages, I've tried again to generate many passwords app and recreate account on Mailspring using them and real password.... doesn't work

**Comment by aliazani** [comment] 2020-05-11 09:06
@bengotow Thanks for checking but I don't think the issue was about security settings.
The error I got when I set the same settings was this:
Connection Error - unable to connect to the server/port you provided(IMAP)
After this, I check the firewall and open port 993 and I found the problem wasn't the firewall.
And I should say a few days ago everything works fine, I think yahoo changes something that's not compatible with Mailspring

**Comment by aliazani** [comment] 2020-05-11 09:54
And I test geary now it works fine so , this is mailspring problem

**Comment by StevenMapes** [comment] 2020-05-11 11:41
I've been using an app password for Yahoo since the introduced them and it was working fine with Mailspring until a few days ago. If you remove the account and re-add it even with a fresh password its no longer using the correct settings to connect to Yahoo! mail

**Comment by rlai000** [comment] 2020-05-11 16:55
Mailspring certainly this issue. My Yahoo and Rogers accounts have this same issue. I did deliberately typed a wrong password but the error message was the same (app password). Moreover, checking the activities on both account, Mailspring seemed not even communicating as no warning.

**Comment by itsthisjustin** [comment] 2020-05-12 22:43
Seems a number of email clients are having this issue. https://github.com/golang/go/issues/36234

**Comment by 233mhz** [comment] 2020-05-13 07:31
Same problem.

**Comment by spike850** [comment] 2020-05-13 14:48
I am having the same issue with Yahoo not connecting.
The problem does not replicate in the Mac version. Macs are working fine, connecting, sending and receiving all mail. Windows is broken, don't have mailspring installed on Linux.

**Comment by nightwatch75** [comment] 2020-05-13 15:51
> 
> 
> I am having the same issue with Yahoo not connecting.
> The problem does not replicate in the Mac version. Macs are working fine, connecting, sending and receiving all mail. Windows is broken, don't have mailspring installed on Linux.

Tried on a Centos 7 Desktop, same problem (real password and app password)

**Comment by 2disbetter** [comment] 2020-05-13 16:58
I've been using it on Ubuntu 18.04, 19.10, and 20.04 and all have the same problem.

**Comment by bengotow** [comment] 2020-05-15 15:05
Hey folks - thanks for all the replies. Will continue investigating this today. 

It looks like most of you are reporting this issue on Linux variants, I think one more possibility is that Yahoo has upgraded their SSL certificate to one that (for whatever reason) your system does not trust as authentic. Could you try updating your root certificate chain and see if that resolves the problem? (Good overview of how to upgrade them on different linux distros here: https://manuals.gfi.com/en/kerio/connect/content/server-configuration/ssl-certificates/adding-trusted-root-certificates-to-the-server-1605.html)

Unlike a lot of mail clients, when Mailspring connects via SSL or STARTTLS it checks to make sure that the remote server's certificate is trusted by your machine. This is kind of annoying in some cases, but it prevents someone from MITM attacking your connection and serving a random certificate advertising itself as the mailserver.

**Comment by bengotow** [comment] 2020-05-15 15:09
One small update, to see if the IMAP server's SSL certificate is what is causing problems on your computer, you can open a Terminal and run this command:

```
openssl s_client -showcerts -connect imap.mail.yahoo.com:993 -servername imap.mail.yahoo.com
```

That will print the certificate chain advertised by the server, and at the bottom you'll see if accept the SSL handshake and connect (ending with `OK [CAPABILITY IMAP4rev1...`) or see it fail with an error message.

**Comment by nightwatch75** [comment] 2020-05-15 15:42
> 
> 
> One small update, to see if the IMAP server's SSL certificate is what is causing problems on your computer, you can open a Terminal and run this command:
> 
> ```
> openssl s_client -showcerts -connect imap.mail.yahoo.com:993 -servername imap.mail.yahoo.com
> ```
> 
> That will print the certificate chain advertised by the server, and at the bottom you'll see if accept the SSL handshake and connect (ending with `OK [CAPABILITY IMAP4rev1...`) or see it fail with an error message.

Seems ok here: 

`---
read R BLOCK
* OK [CAPABILITY IMAP4rev1 SASL-IR AUTH=PLAIN AUTH=XOAUTH2 AUTH=OAUTHBEARER ID MOVE NAMESPACE XYMHIGHESTMODSEQ UIDPLUS LITERAL+ CHILDREN X-MSG-EXT OBJECTID] IMAP4rev1 Hello`

Tested on Windows 10 Enterprise 1009

**Comment by 2disbetter** [comment] 2020-05-15 16:05
Same response for me with that command, but on Ubuntu 20.04.

**Comment by ekawahyu** [comment] 2020-05-15 17:18
Same response for me, no error reported, Ubuntu 18.04.3 LTS

**Comment by stivo85** [comment] 2020-05-15 17:34
`* OK [CAPABILITY IMAP4rev1 SASL-IR AUTH=PLAIN AUTH=XOAUTH2 AUTH=OAUTHBEARER ID MOVE NAMESPACE XYMHIGHESTMODSEQ UIDPLUS LITERAL+ CHILDREN X-MSG-EXT OBJECTID] IMAP4rev1 Hello`

Windows 10 Pro x64

**Comment by olikugel** [comment] 2020-05-15 17:43
OK [CAPABILITY IMAP4rev1 SASL-IR AUTH=PLAIN AUTH=XOAUTH2 AUTH=OAUTHBEARER ID MOVE NAMESPACE XYMHIGHESTMODSEQ UIDPLUS LITERAL+ CHILDREN X-MSG-EXT OBJECTID] IMAP4rev1 Hello

with ZorinOS (Ubuntu-based)

However, still not able to reconnect my Yahoo account to Mailspring :(

**Comment by moray33** [comment] 2020-05-15 17:52
I've formatted my SSD today, reinstalled the system and programs... I had Mailspring running with no problems but now I can't connect it with my Yahoo account.

I use Windows 10.

**Comment by Lisaa5** [comment] 2020-05-15 18:06
I've been experiencing the same issue for the past week. I'm on Windows 10.

**Comment by aliazani** [comment] 2020-05-15 21:52
@bengotow  Hey I'm really glad to see you are trying to slove the issue 
I run openssl test and the final result is :
* OK [CAPABILITY IMAP4rev1 SASL-IR AUTH=PLAIN AUTH=XOAUTH2 AUTH=OAUTHBEARER ID MOVE NAMESPACE XYMHIGHESTMODSEQ UIDPLUS LITERAL+ CHILDREN X-MSG-EXT OBJECTID] IMAP4rev1 Hello

**Comment by maneandrea** [comment] 2020-05-16 19:47
I have the same problem. With the command suggested by Ben I get
```
* OK [CAPABILITY IMAP4rev1 SASL-IR AUTH=PLAIN AUTH=XOAUTH2 AUTH=OAUTHBEARER ID MOVE NAMESPACE XYMHIGHESTMODSEQ UIDPLUS LITERAL+ CHILDREN X-MSG-EXT OBJECTID] IMAP4rev1 Hello
```
On Ubuntu 18.04.3 LTS

Furthermore, the latest comments on [this other issue](https://github.com/Foundry376/Mailspring/issues/1193) seem to be related to the same problem. It could be appropriate to notify the people to comment here and close that one.

**Comment by BiNh0X** [comment] 2020-05-18 01:15
> * OK [CAPABILITY IMAP4rev1 SASL-IR AUTH=PLAIN AUTH=XOAUTH2 AUTH=OAUTHBEARER ID MOVE NAMESPACE XYMHIGHESTMODSEQ UIDPLUS LITERAL+ CHILDREN X-MSG-EXT OBJECTID] IMAP4rev1 Hello
Linux Mint 19.3

**Comment by cssistoughestthingihaveeverdone** [comment] 2020-05-18 07:35
Did you guys contact yahoo customer care? If yes, with what subject? "Mailspring issues?". I will also use same subject line so that they see a pattern and escalate it to the devs.

**Comment by rlai000** [comment] 2020-05-18 20:31
It's not Yahoo issue; at least the issue is the way Mailspring on accessing Yahoo IMAP server

**Comment by itsthisjustin** [comment] 2020-05-18 20:39
FYI, looks like we resolved this same issue on Newton. @bengotow check your Twitter DMs if you want to chat about it.

**Comment by cssistoughestthingihaveeverdone** [comment] 2020-05-18 20:52
Just FYI for folks. Following line just shows that SSL is working fine and we are able to connect to Yahoo Servers. I guess we need login or auth command result after this. 
```
OK [CAPABILITY IMAP4rev1 SASL-IR AUTH=PLAIN AUTH=XOAUTH2 AUTH=OAUTHBEARER ID MOVE NAMESPACE XYMHIGHESTMODSEQ UIDPLUS LITERAL+ CHILDREN X-MSG-EXT OBJECTID] IMAP4rev1 Hello
Linux Mint 19.3
```

**Comment by itsthisjustin** [comment] 2020-05-18 20:55
> Just FYI for folks. Following line just shows that SSL is working fine and we are able to connect to Yahoo Servers. I guess we need login or auth command result after this.
> 
> ```
> OK [CAPABILITY IMAP4rev1 SASL-IR AUTH=PLAIN AUTH=XOAUTH2 AUTH=OAUTHBEARER ID MOVE NAMESPACE XYMHIGHESTMODSEQ UIDPLUS LITERAL+ CHILDREN X-MSG-EXT OBJECTID] IMAP4rev1 Hello
> Linux Mint 19.3
> ```

We were able to do this too...the problem was that it was dropping the connection immediately afterwards. I don't know enough about how Mailcore works here to give direct feedback but I'll chat with Ben if he'll have me :)

**Comment by olikugel** [comment] 2020-05-18 20:56
Please do chat, Ben and Justin, you are our only hope! :D

**Comment by bengotow** [comment] 2020-05-18 21:14
Hey folks, thanks for the feedback—will follow up separately @itsthisjustin! I made a few changes to the IMAP authentication test that Mailspring performs and enabled another layer of mailcore / libSSL logging that we previously had turned off (by redirecting MCLog to our logger), and I'm able to reproduce this on one of my Windows VMs. It still exits immediately after opening the connection, and now we get a bit more information about why the connection was dropped:

```
Important: Yahoo requires that you create a unique app password for email apps like Mailspring. Follow these instructions to create one and then paste it below.
https://help.yahoo.com/kb/SLN15241.html?guccounter=1
----------IMAP----------
connect <mailcore::IMAPSession:00DDF550>
ssl connect imap.mail.yahoo.com 993 43
connect error 43
```

Digging deeper into this, it looks like Mailspring is actually bundling it's own copy of OpenSSL on Windows and Linux. Circa 2014, this copy was better than what was available on those platforms, and we updated them in 2017 to address SSL security improvements / patches, but I think they're still too old. (Other clients might have this issue too if they followed the instructions here to use the mailcore2 binaries from 2014: ).

I think we may need to recompile the latest version of OpenSSL for windows and ship that version instead, going to see if I can do that and re-test. Thankfully now that I have this happening in one of my windows virtual machines I think we can get this fixed!

**Comment by itsthisjustin** [comment] 2020-05-18 21:41
> I think we may need to recompile the latest version of OpenSSL for windows and ship that version instead, going to see if I can do that and re-test. Thankfully now that I have this happening in one of my windows virtual machines I think we can get this fixed!

This definitely mirrors what we did, but I have specifics that might help save you some time and hassle

**Comment by hodsonus** [comment] 2020-05-20 03:39
@bengotow If these commits resolve the issue is there any way that we could get a 1.7.7? Would love to get this up and running on my machine. Cheers :)

**Comment by bengotow** [comment] 2020-05-20 06:21
Hey folks! Sorry for the delay, this has been quite an adventure.

I've now been able to reproduce this on Ubuntu 18 and on Windows 10, and the current builds on `master` solve the problem by building Mailspring's sync engine (and the supporting mailcore2 and libetpan libraries) against a much newer version of OpenSSL (1.1.0f) and statically linking against it rather than depending on your installed version of OpenSSL. (I will try to move things to latest 1.1.1 release for even more security goodness soon, but ran into a couple issues).

I'm still seeing a related issue (I think) on Ubuntu 14, where the Yahoo IMAP connection works just fine but setup fails because the SMTP server disconnects during authentication with a libsasl2 error. It looks like that will take another day to work out, but I'd love if you could try out the new builds and see if it resolves the issue. 

I think that this will get the majority of you back to your inboxes! I'm sorry for the delay and I appreciate all the help triaging this issue. If things look good I'll ship this very soon.

Windows:  
https://mailspring-builds.s3.amazonaws.com/client/5b438be9/win-ia32/MailspringSetup.exe

Linux:
https://mailspring-builds.s3.amazonaws.com/client/5b438be9/linux/mailspring-1.7.7-amd64.deb
https://mailspring-builds.s3.amazonaws.com/client/5b438be9/linux/mailspring-1.7.7-0.1.x86_64.rpm

Linux Snap:
`snap install mailspring --beta` (Note I don't recommend sitting on the edge channel long-term, these builds can be pretty unstable and snap updates automatically!)

**Comment by rlai000** [comment] 2020-05-20 06:35
Yes, Just installed this latest version on Windows 10 and Yahoo / Rogers working again. Thanks

**Comment by nightwatch75** [comment] 2020-05-20 06:38
I can confirm. Installed 1.7.7 on Windows 10 Enterprise and Yahoo is working again using real password (not password app). Thanks!

**Comment by BiNh0X** [comment] 2020-05-20 07:02
Now it's working for Yahoo! The 1.7.7 version in Linux Mint 19.3 Thks @bengotow

**Comment by 2disbetter** [comment] 2020-05-20 09:14
Got it working on Ubuntu 20.04 (via snap refresh --beta).

**Comment by martseba** [comment] 2020-05-20 09:35
> 
> 
> I can confirm. Installed 1.7.7 on Windows 10 Enterprise and Yahoo is working again using real password (not password app). Thanks!

Working also on Win10 Pro, but for me I had to use the generated password app.

**Comment by maneandrea** [comment] 2020-05-20 09:37
I confirm that on my Ubuntu 18.04.3 LTS the new version works like a charm!

**Comment by olikugel** [comment] 2020-05-20 13:04
New version works with ZorinOS, thanks a ton Ben!!

**Comment by 2disbetter** [comment] 2020-05-20 13:17
On Windows 10 Pro (1909) it does not seem to work if you need to add the account. I believe previous answers here are from accounts already configured in Mailspring.

**Comment by Asmilex** [comment] 2020-05-20 13:36
Last update 1.7.7 does seem to fix IMAP. Although, trying to add a new account throws error code 196 for SMTP.

**Comment by BiNh0X** [comment] 2020-05-20 13:44
> On Windows 10 Pro (1909) it does not seem to work if you need to add the account. I believe previous answers here are from accounts already configured in Mailspring.



> Last update 1.7.7 does seem to fix IMAP. Although, trying to add a new account throws error code 196 for SMTP.

In Linux, the function of adding new accounts is working.

**Comment by aliazani** [comment] 2020-05-20 14:07
I've tested MailSpring for 2 of my yahoo account with password generated and every things works fine,
`Thanks @bengotow `

**Comment by bengotow** [comment] 2020-05-20 14:42
Hey folks, thanks for the quick feedback I appreciate it! Really glad that resolves the problem. It's interesting that not everyone needs to use an app password for Yahoo. My test account works without one, but I'll leave that messaging in place since it sounds like it's necessary for some accounts.

I was able to track down the problem with SMTP authentication on Ubuntu 14 (and I believe other older distros as well). Before it starts, Mailspring locates it's own libsasl2 plugins using `realpath`, and that's actually not a stock linux command. Doing `apt-get install realpath` or the equivalent on your linux distro and re-launching Mailspring will allow it to find the SASL library and should fix the problem. The next release will use a more portable solution (all it's trying to do is say "find the libraries in the same folder I'm running from", and that's harder than you'd imagine...)

Thanks, relieved to have gotten to the bottom of this!

**Comment by Henryh123** [comment] 2021-01-01 11:09
Often, there are several cases, when you might get Canon TR8520 printer wireless setup issue, especially on the Operating system, that indicates, every time when we print something, due to some issues, we are unable to connect canon TR8520 printer to WiFi. Hence, if you’re useless to tackle such a technical issue and looking for the right solutions explaining how to resolve canon TR8520 printer setup problems, you’re on the right path. You will know the possible reasons and troubleshooting guidelines to fix the issue. Read More- https://contactemail.us/yahoo-mail-recovery/
--

**Comment by Henryh123** [comment] 2021-01-01 11:10
Yahoo is one of the popularly known web platforms providing many services. You can do yahoo account recovery by following couple of steps. If you want to do Yahoo mail account recovery you can do it by sending the code to the phone number or by email. You can choose any option and can get your account recovered. However, if you are having any query regarding how to recover Yahoo mail account, you can reach our professionals and they will let you know the troubleshooting steps to fix the issue instantly. Read More - https://contactemail.us/yahoo-mail-recovery/

https://contactemail.us/yahoo-mail-recovery/
--

**Comment by CodeMouse92** [comment] 2021-01-22 18:41
It appears that this issue has been resolved, so we are closing it. If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-22 18:41 UTC
Labels: audit, mailserver-incompatibility, needs-reproduction
