### ISSUE TITLE
Failed to execute 'setStart' on 'Range

### ISSUE THREAD

**Issue by D4V3M0NK** [Foundry376/Mailspring#1458] opened 2019-04-08 01:37 UTC
Just spent about 30mins writing an intricate email, with a ton of detail, only to have the following completely blow the email away. So frustrating.

Running Mailspring 1.6.1-aceede8e5 on Ubuntu 16 desktop.

Error: Failed to execute 'setStart' on 'Range': The offset 4294967295 is larger than the node's length (1).
    at findDOMRange (/snap/mailspring/346/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/utils/find-dom-range.js:37:5)
    at Content._this.updateSelection (/snap/mailspring/346/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/content.js:154:46)
    at Content._this.componentDidMount (/snap/mailspring/346/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/content.js:113:13)
    at Hi (/snap/mailspring/346/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:227:261)
    at Fi (/snap/mailspring/346/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:218:212)
    at Gi (/snap/mailspring/346/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:217:174)
    at ii (/snap/mailspring/346/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:214:252)
    at xg (/snap/mailspring/346/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:212:94)
    at Object.enqueueSetState (/snap/mailspring/346/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:133:223)
    at _a.Component.setState (/snap/mailspring/346/usr/share/mailspring/resources/app.asar/node_modules/react/cjs/react.development.js:373:16)
    at draft_store_1.default.sessionForClientId.then.session (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/decorators/inflates-draft-client-id.tsx:77:14)

**Comment by D4V3M0NK** [comment] 2019-04-08 01:40
Fortunately the version in the draft folder was recoverable and I was able to send the email. In previous versions that wasn't possible, so glad that the draft version is working as expected now :O)

**Comment by tiguchi** [comment] 2019-04-10 15:09
Same issue. It's 100% reproducible and shockingly easy to trigger every day. And once Mailspring gets into that error state it needs to be restarted since that error message doesn't want to go away from the center pane.

Here's a demonstration GIF. For context: I only type the colon character in the following demo once. The editor tends to treat it in a special way (maybe emoticon parser?) and gets sticky around it. I can not use the cursor up / down keys to move past it. I can use the delete and enter keys though, which bizarrely duplicate the character until the editor gives up and crashes in the end

![mailspring crash](https://user-images.githubusercontent.com/6569525/55890258-3de9c380-5b67-11e9-8fba-f45cc596e586.gif)

It's not just the colon character that glitches out the app. I experienced the same issue also with embedded images or pasted HTML-formatted snippets. The cursor gets sticky around these "special" elements and a few enter key presses can trigger the crash.

**Comment by MikoMagni** [comment] 2019-05-15 03:58
Here to bump the same issue still occurng on Version 1.6.1 on MacOS. 

<img width="583" alt="Screen Shot 2019-05-15 at 1 26 35 pm" src="https://user-images.githubusercontent.com/2527231/57747541-7bd98a80-76c5-11e9-862c-16c3c628c846.png">

**Comment by bengotow** [comment] 2019-05-26 21:48
Hey folks, this should be fixed in the next release—we just need to upgrade to the new SlateJS text editor and there are a few blockers. Stay tuned!

**Closed** 2020-04-15 18:53 UTC
