### ISSUE TITLE
Option for keeping notifications at Notification Center (Windows 10)

### ISSUE THREAD

**Issue by Javinator9889** [Foundry376/Mailspring#1343] opened 2019-01-29 15:39 UTC
##### Are there any related issues?

Not exactly, this is an enhancement (similar one #221)

##### What operating system are you using?

Windows 10 *Education* 1809 (`17763.22`)

##### What version of Mailspring are you using?

`1.5.5-b7939d38`

------------------

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

Yes, it exists both **Microsoft Outlook** and **native mail app** - what I want is the possibility to keep the notification on Action Center (Notification center) of Windows 10, as if you did not read the proper pop-up, it is lost. I tried also changing the *notifications settings* for keeping *Mailspring* notifications on Notification Center but it is not working.

**Comment by bengotow** [comment] 2019-02-05 05:09
Hey! Thanks for filing this - this definitely seems like a good improvement. I'll study how the native mail app's notifications work a bit and see if that's something we can do.

**Comment by bengotow** [comment] 2019-02-05 05:11
Tagging this one as a good first issue. If someone has a Windows machine and wants to dig in to Mailspring, the notifications are currently posted via the standard HTML5 API here: https://github.com/Foundry376/Mailspring/blob/master/app/src/native-notifications.es6#L66, and we may be able to change our use of `tag` IDs to get the behavior we want.

**Comment by Venryx** [comment] 2019-12-20 21:32
It might have something to do with this: https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/send-local-toast-desktop-cpp-wrl#step-4-implement-the-activator
> You must implement a handler for toast activation, so that when the user clicks on your toast, your app can do something. **This is required for your toast to persist in Action Center** (since the toast could be clicked days later when your app is closed). This class can be placed anywhere in your project.

**Comment by CodeMouse92** [comment] 2021-02-25 23:24
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/option-for-keeping-notifications-at-notification-center-windows-10/800

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@Javinator9889 @Venryx: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-25 23:24 UTC
Labels: audit, enhancement, good first issue
