### ISSUE TITLE
Bug: Archiving conversations leaves unread emails in the inbox but does not display them

### ISSUE THREAD

**Issue by FriesischScott** [Foundry376/Mailspring#1991] opened 2020-05-18 14:08 UTC
**Describe the bug**
When I archive conversations with multiple emails without explicitly reading all of them, Mailspring leaves the unread emails in the inbox and I can see them when I directly log into my email account. However, inside Mailspring these emails are not shown in either *Inbox* or *Unread*. I assume because Mailspring connects them to the archived conversation.

This way, Mailspring reports my Inbox as empty when it is in fact filling up with unread, hidden emails.

**Expected behavior**
I expect Mailspring to move the unread emails to the *Archive*. Personally, I would also like Mailspring to mark the emails in a conversation as read when archiving.

**Setup: (please complete the following information):**
 - OS: Solus
 - OS Version: 4.1
 - Mailspring Version: 1.7.6
 - Account type: IMAP

**Comment by CodeMouse92** [comment] 2021-03-01 23:51
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/archiving-conversations-leaves-unread-emails-in-the-inbox-but-does-not-display-them/897

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@FriesischScott: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-01 23:51 UTC
Labels: audit, bug
