### ISSUE TITLE
[question] color line quotes

### ISSUE THREAD

**Issue by darwin67** [Foundry376/Mailspring#1554] opened 2019-07-01 22:02 UTC
##### Are there any related issues?

Is there a way to make the line of quoted text of different colors?
Below is the same email opened in Mailspring and Thunderbird.

#### Mailsping
![mailspring](https://user-images.githubusercontent.com/5746693/60469199-bdd87480-9c10-11e9-8da1-7360f76a8a02.png)

#### Thunderbird
![thunderbird](https://user-images.githubusercontent.com/5746693/60469232-dc3e7000-9c10-11e9-9a33-54616235045f.png)

Having the colors would be pretty helpful when looking at emails in mailing lists, since there are so many levels of nesting.

...

##### What operating system are you using?

Ubuntu 18.04

...

##### What version of Mailspring are you using?
1.6.2-278bf219
...

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

Thunderbird
...

**Comment by bengotow** [comment] 2019-07-04 13:48
Hey! I think we can definitely do this—do you know offhand if this is an option in Thunderbird or if it does this all the time? I think we copied Gmail's behavior for Mailspring but some CSS rules would probably allow us to do this.

**Comment by darwin67** [comment] 2019-07-04 21:21
I think it does it all the time.
Can't find the settings to tune the behavior.

**Comment by CodeMouse92** [comment] 2021-02-26 16:58
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/color-line-quotes/822

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@darwin67: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-26 16:58 UTC
Labels: audit, enhancement
