### ISSUE TITLE
Bug: Yandex refuses to connect

### ISSUE THREAD

**Issue by InterstellarDragon** [Foundry376/Mailspring#2153] opened 2020-09-25 16:41 UTC
**Describe the bug**
I cannot connect my Yandex.Mail account, neither with an app password nor directly as an IMAP/SMTP account, I always get "Authentication Error - Check your username and password. (IMAP)".

**To Reproduce**
Attempt to connect a Yandex mailbox.

**Expected behavior**
Successful connection.

**Setup: (please complete the following information):**
 - OS: openSUSE
 - OS Version: Leap 15.1
 - Mailspring Version: 1.7.8

**Additional context** 
GMail connected just fine, so it's specifically an issue with Yandex.

**Comment by Minashraf** [comment] 2020-10-14 16:14
Same version but on Arch linux

**Comment by wolfw3** [comment] 2021-02-11 19:54
Same here, I assume this would be fixed by moving Yandex's authentication method to OAuth

**Comment by CodeMouse92** [comment] 2021-02-11 22:03
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/yandex-refuses-to-connect/571

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@wolfw3: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-11 22:03 UTC
Labels: audit, bug
