### ISSUE TITLE
Connection Error with University's Office365 account

### ISSUE THREAD

**Issue by shpotes** [Foundry376/Mailspring#832] opened 2018-04-18 07:27 UTC
When I try to add my univetsity Office365 account, I get the following Error
![2018-04-18-02-10-12](https://user-images.githubusercontent.com/12214323/38917064-2e22ca72-42af-11e8-9bd6-1ebf4867861a.png)

##### Are there any related issues?

I thing that #207 have the same issue. 

##### What operating system are you using?
Linux version 4.13.0-38-generic
Ubuntu 16.04

##### What version of Mailspring are you using?
1.2.1-7e7447b6

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Exchange

##### Is the issue reproducible with a particular attachment, message, signature, etc?

I know that my university choose a particular setup for his mail server, previously when I setup the account in other clients (like thunderbird) i have similar issues, but I solve it when changed the server name and port. 

![2018-04-18-02-19-56](https://user-images.githubusercontent.com/12214323/38917078-385b34de-42af-11e8-9d77-2ec9c03396e0.png)

--

##### Log file
[View log](https://gist.githubusercontent.com/shpotes/8191e3b409e3890e38da5f8ef677f775/raw/5934eb2887b0c552f1311fad273f717527845cd3/118330-8443-19xl2e.ampt1.log)

**Comment by dtbray** [comment] 2018-04-19 10:09
Have you checked with your university to see if their O365 allows Mailspring as a third-party email client?  My university uses G Suite, and I'm in the process of petitioning the admins to let me authenticate it against our email.

**Comment by shpotes** [comment] 2018-04-30 16:51
sure, I setup without any problem in my office PC (HP Z840 with Ubuntu Gnome 16.04), but I cant do it in my laptop

**Comment by aeismail** [comment] 2018-05-15 17:25
My university just announced it's dropping support for IMAP-based O365 access. Without support for the Exchange server (Endpoint URLs), I can't use Mailspring after August 1. It's a shame—I finally find a client for which I can make a theme that doesn't hurt my eyes, and has pretty much everything I want, and then I can't use it anymore because of the lack of native Exchange support.

**Comment by CodeMouse92** [comment] 2021-01-18 18:57
Thank you for your patience on this issue! I know it's frustrating when you cannot connect to your email with Mailspring.

2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be a duplicate of one we've already migrated to Discourse:

https://community.getmailspring.com/t/institutional-office365-not-working/48/2

Please consider joining that community and continuing the discussion there.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-18 18:57 UTC
Labels: audit
