### ISSUE TITLE
Can't Launch Mailspring Offline

### ISSUE THREAD

**Issue by ZakharH** [Foundry376/Mailspring#140] opened 2017-10-12 14:00 UTC
Here is my backtrace when running `mailspring`

```
Streaming log data to /tmp/Nylas-Mail-3660.log
App load time: 223ms
{ Error: getaddrinfo ENOTFOUND updates.getmailspring.com updates.getmailspring.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'updates.getmailspring.com',
  host: 'updates.getmailspring.com',
  port: 443 } {}
undefined
undefined
undefined
undefined
undefined
undefined
Error: getaddrinfo ENOTFOUND updates.getmailspring.com updates.getmailspring.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)

```

##### Are there any related issues?

No.

##### What operating system are you using?

Arch Linux and AUR package

##### What version of Mailspring are you using?

1.0.3

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
None

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

I would assume not, but for the record I use Gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?

Yes, offline capability is kind of the point of an email client

**Comment by kc9jud** [comment] 2017-10-12 19:15
Duplicate of #90.

**Closed** 2017-10-16 16:58 UTC
