### ISSUE TITLE
Mail get lost from inbox after undoing a remove in Gmail

### ISSUE THREAD

**Issue by ngnmhieu** [Foundry376/Mailspring#1214] opened 2018-11-04 22:50 UTC
##### Description

After I delete an email from inbox and undo the action (either with shortcut and by clicking 'undo'), the email disappears from inbox list. Though it still appears if I search the for the title of the email and is not in Trash or Spam. This only happens for gmail.

##### What operating system are you using?

macOS Mojave 10.14

##### What version of Mailspring are you using?

Version 1.5.1 (1.5.1)

**Bug?**

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

The bug happens for emails in Gmail.

**Comment by chemicalkosek** [comment] 2019-01-14 08:52
I can confirm this bug. They are visible in "All emails" tho. The same happens when "unspamming" an email from the Spam folder. Ubuntu 16.04. Mailspring 1.5.5

**Comment by amadrzyk** [comment] 2020-01-27 19:52
Duplicate from [issue #491](https://github.com/Foundry376/Mailspring/issues/491)

**Comment by kpalczewski** [comment] 2020-06-18 14:36
I seem to have this issue too.
Undo doesn't seem to work at all (the command is executed anyway).

**Comment by CodeMouse92** [comment] 2021-02-02 02:44
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/disappearing-emails-desync/428

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-02 02:44 UTC
Labels: audit
