### ISSUE TITLE
Mail send with Mailspring is defined as 'potential threat - phishing'

### ISSUE THREAD

**Issue by knireis** [Foundry376/Mailspring#294] opened 2017-11-02 09:15 UTC
When i send a mail with mailspring to a mailaddress hosted at siteground, this mail is defined as a potential threat- phishing. Because of that the receiver of the mail is not able to reply to this mail.

**Comment by oserban** [comment] 2017-11-02 09:40
I think this is a duplicate of #284

**Comment by bengotow** [comment] 2017-11-02 18:05
Thanks—merging this into #284

**Closed by bengotow** 2017-11-02 18:05 UTC
