### ISSUE TITLE
problem to add a Yahoo account

### ISSUE THREAD

**Issue by franco27** [Foundry376/Mailspring#1193] opened 2018-10-29 15:55 UTC
Windows 10 x64 + Mailspring 151

1/ I click on add a account, main interface menu
2/ I click on the Yahoo logo
3/ an error message is displayed

![mailspring 2018-10-29 16 26 55](https://user-images.githubusercontent.com/31793920/47662295-eea46d80-db9a-11e8-947e-a366da4d5dd3.png)

it's a new installation with the latest version. There were no previous versions installed

**Comment by franco27** [comment] 2018-10-29 15:59
the error message displays a connection error. impossible to connect to the server.

**Comment by bengotow** [comment] 2018-11-03 16:17
Hey! Thanks for reporting this—could you try enabling "Less Secure Apps" in Yahoo's settings (which allows you to sign in with your email / password via IMAP), or create an app password for Mailspring? Here's a bit more info: https://blog.context.io/yahoos-less-secure-app-setting-2203fcef54f.

I'll see if I can get these tips in to the actual log as well!

**Comment by franco27** [comment] 2018-11-03 21:44
I solved this problem:
1 / I uninstalled version 1.5.1
2/ I installed version 1.4.2 and added my mail account laposte and yahoo #1193
3/I upgraded to 1.5.0 and then version 1.5.1

**Comment by franco27** [comment] 2018-11-03 21:51
There is this parameter in my Yahoo account. On another computer, Mailspring is installed with the same Yahoo account.

**Comment by josiasmat** [comment] 2019-08-07 17:39
I'm too experiencing the same problem. Mailspring version 1.6.3. Cannot add a new Yahoo account on a new Mailspring installation. The log file says:

> 13780 [2019-08-07 14:04:29.924] [main] [info] Identity created at 1565207027 - using ID Schema 1
> 13780 [2019-08-07 14:04:29.925] [main] [info] ------------- Starting Sync (*********@yahoo.com.br) ---------------
> 13780 [2019-08-07 14:04:29.928] [metadata] [info] Metadata delta stream starting...
> 13780 [2019-08-07 14:04:29.929] [background] [info] Marking all folders as `busy`
> 13780 [2019-08-07 14:04:29.929] [background] [info] Syncing folder list...
> 13780 [2019-08-07 14:04:32.487] [background] [critical]  *** Stack trace:
>  ***   raise
>  ***   abort
>  ***   terminate
>  ***   wcsstr
>  ***   wcsstr
>  ***   RtlInterlockedCompareExchange64
>  ***   RtlInterlockedCompareExchange64
>  ***   KiUserExceptionDispatcher
>  ***   _CxxThrowException
>  ***   _o_iswdigit
>  ***

**Comment by Dahouo** [comment] 2019-09-20 23:55
I have the same problem. 
A first installation (version 1.6.3) works well and then failed when I tried to configure my account in a second installation (same version) in another pc

`Erreur d'authentification - Vérifiez votre nom d'utilisateur et votre mot de passe. (IMAP)View Log`

**Comment by TheDechev** [comment] 2019-10-13 07:23
The issue still remains in version 1.6.3.

**Comment by TheDechev** [comment] 2019-10-13 07:25
The issue still remains in version 1.6.3.

Tried the previous solution with the downgrade to 1.4.2 but no luck.

**Comment by josiasmat** [comment] 2019-10-15 01:14
The issue persists in version 1.7.1.

**Comment by AlexmograineThird** [comment] 2019-12-08 01:45
Just making a comment that under the latest version as of today ( 8/12/2019) I also faced the same issue. Solved it by changing the outgoing port in the IMAP configuration to 587.

**Comment by josiasmat** [comment] 2019-12-08 12:51
Tried the solution suggested by AlexmograineThird (change IMAP port to 587), but it didn't work for me.

**Comment by AlexmograineThird** [comment] 2019-12-09 18:53
> Tried the solution suggested by AlexmograineThird (change IMAP port to 587), but it didn't work for me.
> 
> Using version 1.7.2, and the problem persists. This issue is preventing me from installing MailSpring in a new computer. But it appears that no one in the MailSpring team cares about it.

Sorry to hear it didnt work. I tried once more today. So those were the steps that got me to make it work.
When adding a yahoo account you first have to generate a password for third party apps, this can be done using the following link: https://help.yahoo.com/kb/SLN15241.html?guccounter=1
( It is provided under the instructions to add you a yahoo account on the springmail program)
After having generated that password, on the "connect an email account" page of springmail, you select IMAP/SMTP you enter your informations, and change ports for the " Outgoing mail" part to 587 and secutiry should switch to STARTTLS on its own.
That's how I got it to work, hope it helps you in the end.
Regards Steven.

**Comment by lukasdeveloper** [comment] 2019-12-10 17:06
Hello, i am also not able to login using Yahoo, i tried everything and yes i did a app password.

**Comment by josiasmat** [comment] 2019-12-10 20:33
Just to be clear here: the issue is that it is not possible to add a new Yahoo Mail account to MailSpring. I have a Yahoo Mail account working in MailSpring which I added some time ago, probably when MailSpring was at version 1.2 or 1.3. Even though I have this account working, when I try to add another Yahoo Mail account, be it in this same installation or in another computer, it doesn't work, failing in fetching folders and emails. It doesn't even show under Inbox. Tried adding a "Yahoo Mail" account and a custom IMAP/SMTP account; both fail. Changing port as suggested by AlexmograineThird doesn't work either. And yes, I also did an app password...

**Comment by lukasdeveloper** [comment] 2019-12-11 04:17
^

**Comment by mystinen** [comment] 2020-02-29 06:46
Issue still there on Mailspring version downloaded today. In fact, the client says that authentication was successful (using app-specific password from Yahoo, and the default Yahoo IMAP settings in Mailspring), but the "new account" window then simply disappears without the Yahoo account being added to the list of accounts.

The same issue reported in #1672 is sadly closed without comment - pity, as it's a show-stopper for anyone with a Yahoo account who might like to make the switch to Mailspring!

Any comment (even if not a fix!) from the developers as to why Yahoo's IMAP is breaking Mailspring... ?

**Comment by josiasmat** [comment] 2020-04-22 22:18
Version 1.7.6: this issue persists.
Come on devs... don't you want users of Yahoo Mail to use your app?

**Comment by GeorgeB5555** [comment] 2020-05-08 05:31
Hi All

This issue is still occurring in 1.7.6 as I have encountered it today

Some other details
01. I used 1.7.2 to install mailspring in March 2020
02. I found I had issues with white screen with 1.7.4 (Getting 1.7.2 fixed this and then I could upgrade)
03. Over the week starting 1 May I had constant connection issues to my yahoo mail
04. There was a significant crash that created error reports 6 May 2020 that was sent to dev's
05. 8 May 2020 the mailspring application stopped updating/sync-ing altogether
06. I have uninstalled and re-installed 1.72, 1.74 and 1.76 and all have the same IMAP error in the set up screens
07, changing any of the ports to the available options DO NOT resolve the issues with the IMAP error
08. all of the installs have the yahoo app password set up as part of the configuration
09. Yahoo has published a notice about IMAP security and preventing older apps from connecting but I do not know the date of the post - linked: https://nz.help.yahoo.com/kb/SLN27791.html
10. Issue has been submitted today 8 May as part of the issue reported

****I wonder if the issue is at the Yahoo end and dev's have a bigger issue to address??****

**Comment by BiNh0X** [comment] 2020-05-08 14:05
Same problem here, version 1.7.6. Since yesterday Yahoo! Mail doesn't connect, so I removed the account and added it again and now it gives this same error message, since I use a unique password for apps. Until yesterday it worked perfectly.

**Comment by ZhirenXu** [comment] 2020-05-08 16:34
Same issue in ver. 1.7.6, The error message says "Connection Error - Unable to connect to the server / port you provided. (IMAP)". I tried manually setup IMAP ports according to Yahoo's doc but didn't work.

**Comment by gordynorth** [comment] 2020-05-08 18:43
I also have version 1.7.6 and since yesterday 2020-05-08 Yahoo no longer works. I created a new app password in Yahoo and it did not work, I also tried setting up IMAP email using Yahoo specs and that doesn't work either. Why only Yahoo???

**Comment by BiNh0X** [comment] 2020-05-08 18:49
This problem only occurs in Mailspring, as I also use Thunderbird and there is no problem logging in to Yahoo.

**Comment by GeorgeB5555** [comment] 2020-05-08 20:42
Hi All

I have been in touch with Yahoo and all the IMAP settings in Mailspring , either 465/587 for the outgoing mail, are correct 

Yahoo provided the below re settings as confirmation after setting up your app password

After finishing generate your third-party app passwords, follow the instructions below for the IMAP server setting:

Your login info

    Email address - Your full email address (name@domain.com)
    Password - The generate third-party app passwords (16 characters without space)
    Requires authentication - Yes

Incoming Mail (IMAP) Server

    Server - imap.mail.yahoo.com
    Port - 993
    Requires SSL - Yes

Outgoing Mail (SMTP) Server

    Server - smtp.mail.yahoo.com
    Port - 465 or 587
    Requires SSL - Yes
    Requires authentication - Yes

If you need specific instructions for your mail client or app, reach out to its manufacturer.

**Comment by GeorgeB5555** [comment] 2020-05-08 20:47
further update - could the issue be that the outgoing mail "requires authentication" configuration has been removed in mailspring?

Would be good for feedback on this from developers and the most recent changes to Mailspring

**Comment by GeorgeB5555** [comment] 2020-05-08 22:11
final note from me until devs look into this - 1.7.6 had a change in the preferences and authentication settings, I believe this to be the cause of the issue but need one of the 12 contributors to look into that ... hopefully soon as the app is great when it is working

**Comment by jrbastien** [comment] 2020-05-09 13:15
I'm in the same boat here.  I know that does not help but reporting so Mailspring support understands that it is not limited to only a few people.

**Comment by josiasmat** [comment] 2020-05-10 15:52
Well, after months not being able to create a new Yahoo account, and now unable to use the Yahoo account which I was already using, and for all this time being simply ignored by the Mailspring devs, as if it wasn't a serious bug that their MAIL APP doesn't work with a MAJOR MAIL PROVIDER, I'm going back to Thunderbird.

**Comment by HaoZeke** [comment] 2020-05-10 18:57
Yeah this is annoying. I can't understand what the team is up to. I only realized I was losing mail because other clients are still working correctly.

**Comment by olikugel** [comment] 2020-05-10 19:59
I'm having the same problem... if this isn't resolved soon I will have to switch to Thunderbird.. would be a pitty since I love Mailspring, it's much prettier than Thunderbird;  but without connection to my Yahoo account it loses all its value :/.

**Comment by BiNh0X** [comment] 2020-05-10 21:34
I am also returning to Thunderbird until they resolve this issue, as my primary email account is Yahoo ...

**Comment by pete00** [comment] 2020-05-14 18:11
Same issue in version 1.7.6, The error message says "Connection Error - Unable to connect to the server / port you provided. (IMAP)". I tried manually setup IMAP ports according to Yahoo's doc but didn't work.

**Comment by vik-tor** [comment] 2020-05-16 16:19
Having the same issue. I'm using version 1.7.6 on Manjaro. I have tried all workarounds without success.

**Comment by maneandrea** [comment] 2020-05-20 09:39
This problem should be resolved by installing the new version 1.7.7

Windows:
https://mailspring-builds.s3.amazonaws.com/client/5b438be9/win-ia32/MailspringSetup.exe

Linux:
https://mailspring-builds.s3.amazonaws.com/client/5b438be9/linux/mailspring-1.7.7-amd64.deb
https://mailspring-builds.s3.amazonaws.com/client/5b438be9/linux/mailspring-1.7.7-0.1.x86_64.rpm

Linux Snap:
`snap install mailspring --beta`

(See issue #1974)

**Comment by josiasmat** [comment] 2020-05-21 12:54
Yes, it works finally!

**Comment by josiasmat** [comment] 2020-05-21 13:18
> Yes, it works finally!

Wrong... Existing accounts do work normally now, but I am unable to add a new Yahoo account yet.

**Comment by gordynorth** [comment] 2020-05-21 13:37
Refreshed Mailspring using --beta on Linux and I was able to add my Yahoo account and it seems to be refreshing. 
So far all is good

**Comment by HaoZeke** [comment] 2020-05-21 13:40
Works for me now.

**Comment by josiasmat** [comment] 2020-05-21 14:04
For me, the existing account works. But tried to add a Yahoo Mail account in a refreshed MailSpring installation and it does not work. Log:

```
16408 [2020-05-21 10:58:50.838] [main] [info] Identity created at 1565207027 - using ID Schema 1
16408 [2020-05-21 10:58:50.840] [main] [info] ------------- Starting Sync (******@yahoo.com.br) ---------------
16408 [2020-05-21 10:58:50.848] [background] [info] Marking all folders as busy
16408 [2020-05-21 10:58:50.848] [background] [info] Syncing folder list...
16408 [2020-05-21 10:58:52.286] [metadata] [info] Metadata delta stream starting...
16408 [2020-05-21 10:58:53.409] [background] [critical] 
***
*** Mailspring Sync 
*** A C++ exception occurred during program execution: 
*** UNIQUE constraint failed: Folder.id
***
```

Note that the mail domain is yahoo.com.br.

**Comment by mystinen** [comment] 2020-05-25 05:53
I am now able to add a new Yahoo account, and mail operations are working normally. Had downloaded version 1.7.7-71504f2c from the website, running on Windows 10.

Thank you!

**Comment by jambocurious** [comment] 2020-05-25 08:07
Can confirm successful login and operations with the Yahoo account with Mailspring v1.7.8 under Ubuntu 20.04.

**Comment by josiasmat** [comment] 2020-05-25 13:10
For me it still doesn't work. Tried to add another yahoo mail account to a clean install (v. 1.7.8). But now the log has different info:

```
Important: Yahoo requires that you create a unique app password for email apps like Mailspring. Follow these instructions to create one and then paste it below.
https://help.yahoo.com/kb/SLN15241.html?guccounter=1

----------IMAP----------
connect <mailcore::IMAPSession:010FF9CC>
* OK [CAPABILITY IMAP4rev1 SASL-IR AUTH=PLAIN AUTH=XOAUTH2 AUTH=OAUTHBEARER ID MOVE NAMESPACE XYMHIGHESTMODSEQ UIDPLUS LITERAL+ CHILDREN X-MSG-EXT OBJECTID] IMAP4rev1 Hello
ssl connect imap.mail.yahoo.com 993 2
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
connect ok
login
1 LOGIN "*********@yahoo.com.br" *********
1 OK LOGIN completed
2 CAPABILITY
* CAPABILITY IMAP4rev1 ID MOVE NAMESPACE XYMHIGHESTMODSEQ UIDPLUS LITERAL+ CHILDREN X-MSG-EXT UNSELECT OBJECTID
2 OK CAPABILITY completed
3 NAMESPACE
* NAMESPACE (("" "/")) NIL NIL
3 OK NAMESPACE completed
login ok
4 LIST "" "*"
* LIST (\Archive \HasChildren) "/" "Archive"
* LIST (\HasNoChildren) "/" "************"
* LIST (\HasNoChildren) "/" "************"
* LIST (\HasNoChildren) "/" "************"
* LIST (\HasNoChildren) "/" "************"
* LIST (\HasNoChildren) "/" "************"
* LIST (\HasNoChildren) "/" "************"
* LIST (\Junk \HasNoChildren) "/" "Bulk Mail"
* LIST (\Drafts \HasNoChildren) "/" "Draft"
* LIST (\HasChildren) "/" "Inbox"
* LIST (\HasNoChildren) "/" "Inbox/*****************"
* LIST (\HasNoChildren) "/" "Inbox/***********"
* LIST (\HasNoChildren) "/" "Inbox/*********"
* LIST (\HasNoChildren) "/" "Inbox/*******"
* LIST (\HasNoChildren) "/" "Inbox/********************"
* LIST (\HasNoChildren) "/" "Inbox/*********************"
* LIST (\HasNoChildren) "/" "Inbox/********************"
* LIST (\HasChildren) "/" "Mailspring"
* LIST (\HasNoChildren) "/" "Mailspring/Snoozed"
* LIST (\Sent \HasNoChildren) "/" "Sent"
* LIST (\Trash \HasNoChildren) "/" "Trash"
4 OK LIST completed


----------SMTP----------


SASL_PATH: 

SMTP Last Response Code: 0
SMTP Last Response: 


mailsmtp Last Error Code: 3
mailsmtp Last Error Explanation: MAILSMTP_ERROR_STREAM
mailsmtp Last Error Location: 5
mailsmtp Last Auth Type: 0
```

Note that I do created an "unique app password", so this isn't the problem.

Could it be an issue related to addresses that contain country-specific domains (as mine which is yahoo.com.**br**)?

![mailspring_error_capture](https://user-images.githubusercontent.com/4457615/82815602-dc221100-9e6f-11ea-853d-eb6870d90bab.png)

**Comment by mystinen** [comment] 2020-05-25 17:17
@josiasmat Sorry you're still having issues... if it's any help, the Yahoo account I tested with is also on a country-specific domain (i.e. it is not @yahoo.com) - so unless this issue is specific to yahoo.com.br, I don't think that's the cause.

Thanks for confirming you used an 'app password' - I forgot to mention that I had done so as well.

**Comment by CodeMouse92** [comment] 2021-01-28 18:29
Hi all,

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears partially resolved, but clearly there are still some problems. We need to untangle the resolved and unresolved issues.

@josiasmat: Can you please confirm that this is still broken with 1.8.0, and if so, open a new Sync Issue on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 18:29 UTC
Labels: audit, support
