### ISSUE TITLE
[Feature Request] Option to disable *italics* which make it hard to write math

### ISSUE THREAD

**Issue by psivesely** [Foundry376/Mailspring#1592] opened 2019-07-27 15:48 UTC
**Feature Request?**

When I'm trying to type out math equations in emails, I will most often need to use a couple *s. When I do this, it removes the *s and makes the text between them italic. I'd love if I could disable this behavior as it much harder to do my work.

**Comment by bengotow** [comment] 2019-10-09 02:00
Hey @nvesely — thanks for reporting this! I actually had never thought about the math use case. I'll see if we can add an option for this in a release later this year!

**Comment by tdewolff** [comment] 2020-10-01 00:31
Any advances on this? I'd like to see this as I have the same use-case.

**Comment by AndrewCarvalho** [comment] 2020-10-30 03:25
I'm writing some technical emails at the moment and am hitting a similar issue when trying to write out some wildcards.

**Comment by CharlesCossette** [comment] 2021-01-08 00:49
I also support this feature request. It is quite cumbersome to write technical emails or code snippets which contain math. Given that we also have the ctrl + I ability for italics, it isnt a big loss (for me at least) to not have *italics*

**Comment by CodeMouse92** [comment] 2021-02-26 17:13
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/option-to-disable-italics-which-make-it-hard-to-write-math/827

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@psivesely @AndrewCarvalho @CharlesCossette: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-26 17:13 UTC
Labels: audit, composer, enhancement, good first issue
