### ISSUE TITLE
Bug: correction in cs.json

### ISSUE THREAD

**Issue by DemonioCZ** [Foundry376/Mailspring#1801] opened 2020-02-18 14:10 UTC
Hi, I found mistake in translation to czech, but I dont see it in this file. By every mail content, there is a number of "opens" (how many times it was open). Wrong czech translation is "otevřít"... it should be "otevřeno"

**Comment by bengotow** [comment] 2020-04-16 05:22
Hey @DemonioCZ thanks for reporting this, sorry for the delay. It looks like this is a flaw in our current localization strings - we use the same string key for "Open" (as in "email opens") and "Open" (as in "Open attachment").  I think we'll need to create a separate string entry (with another key like "OpenTrackingOpen" and then translate it in English as well as Czech!

**Comment by CodeMouse92** [comment] 2021-02-23 21:51
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/correction-in-cs-json/743

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@DemonioCZ: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-23 21:51 UTC
Labels: audit, bug, good first issue
