### ISSUE TITLE
Bug: "remove and show previous" shortcut fails on last email

### ISSUE THREAD

**Issue by awmottaz** [Foundry376/Mailspring#2033] opened 2020-05-28 19:28 UTC
**Describe the bug**
Nothing happens when I use the "Remove and show previous" shortcut on the last email in my Inbox.

**To Reproduce**
1. Open oldest email in Inbox
2. Use the "Remove and show previous" shortcut to archive current email and move to the next oldest email in the Inbox (for me, this is the `]` key).
3. Notice that nothing happens once you've reached the last email in the Inbox

**Expected behavior**
Archive the email and show me an empty Inbox.

**Screenshots**
N/A

**Setup: (please complete the following information):**
 - OS: Linux Pop!_OS
 - OS Version 20.04 LTS
 - Mailspring Version: 1.7.8

**Additional context** 
N/A

**Comment by CodeMouse92** [comment] 2021-03-02 18:36
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/remove-and-show-previous-shortcut-fails-on-last-email/930

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@awmottaz: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 18:36 UTC
Labels: audit, bug
