### ISSUE TITLE
Minimize to tray and then restore unresponsive interface

### ISSUE THREAD

**Issue by grandixximo** [Foundry376/Mailspring#1627] opened 2019-09-05 07:33 UTC
#### What operating system are you using?

Windows 10

##### What version of Mailspring are you using?

1.6.3

##### Desription

In windows if mailspring is minimized from the minimize button to the taskbar, then hidden in tray by clicking on the tray icon, and then restored to taskbar by click on tray icon again, then click on the mailspring in the task bar to maximize it, now if you try to click inside mailsrping nothing is responsive.

**Comment by netmajor** [comment] 2020-01-02 20:00
The bug still occurs in 1.7.2

**Comment by gunters63** [comment] 2020-10-22 07:04
I have the same problem with 1.7.8.

If I use close (Taskbar icon gone) and open Mailspring again through the tray icon the interface works normal.

Also, when you minimized, one way to get it open responsive again is to right-click the tray icon and select preferences. After Mailspring opened the preference page just go back to the inbox, user interface is responsive.

The issue is quite annoying, happens several times a day.

**Comment by gunters63** [comment] 2020-10-29 21:41
Is there any support on this product? 
I see many posted bugs the last 4 weeks with only automated responses.
I think it was a mistake to go for the Pro version.

**Comment by gunters63** [comment] 2020-11-03 09:26
Canceled Pro subscription, 
Its a pity, I really like the concept.

**Comment by CodeMouse92** [comment] 2021-02-18 01:11
Hi all,

Unfortunately, this got buried in the 1.1K issue backlog — most of which was actually just duplicate issues and wishlist feature requests. Mailspring is primarily maintained by one person, Ben Gotow, in addition to a full time job. The Mailspring Pro subscriptions cover the costs of the servers and APIs that enable Pro features, and help cover the security audits necessary to work with some email providers. In short, 2020 stalled development for a bit, that year being what it is, but we're getting back to work!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/minimize-to-tray-and-then-restore-unresponsive-interface/685

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@grandixximo @netmajor @gunters63: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them. (Furthermore, @netmajor and @gunters63, can you confirm on that thread what OS you were using? Is this bug specific to Windows?)

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-18 01:11 UTC
Labels: audit
