### ISSUE TITLE
Badge doesn't always appear on app indicator when receiving new mail

### ISSUE THREAD

**Issue by goransimic** [Foundry376/Mailspring#411] opened 2017-12-07 19:12 UTC
When you receive new mail and Mailspring is opened or minimized badge appears on app indicator in system tray, but if you close Mailspring while still active in background there is no badge on new mail.

Also badge could be larger or something because it's barely visible anyway.

Using TopIcons Plus gnome extension to display Mailspring in system tray.

##### Are there any related issues?

No

##### What operating system are you using?
Ubuntu 17.10

##### What version of Mailspring are you using?
1.0.10

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No

**Comment by fcastilloec** [comment] 2017-12-08 06:34
I also have this same problem on Ubuntu 16.04, using v1.0.10.
I think I saw a badge the first two/three emails I received. Since then, I don't see a badge on the icon anymore, it's annoying. I have to keep Mailspring always open to see if an email arrives.

**Comment by fcastilloec** [comment] 2017-12-19 00:00
I've noticed that none of the collaborators have addressed this issue, so I'm attaching a GIF showing what happens when I mark some emails as **Unread**. You can see that the icon flashes and probably tries to find the appropriate icon that includes a badge but it can't. You can even see for a second when it flashes, that an error icon is shown ![mailspring](https://user-images.githubusercontent.com/1280530/34133691-34a2e2b8-e424-11e7-9308-425064943ea2.png) before it goes back to the Mailspring icon.
Here's the GIF
![mailspring](https://user-images.githubusercontent.com/1280530/34133821-eb9dab24-e424-11e7-825c-f05b8d105249.gif)
This is happening with Mailspring v1.0.11 which was released today. I'm using Ubuntu 16.04 with the latest updates and also using a single IMAP account.
Again, the GIF is demonstrating when I mark messages as unread but the same behavior is seen when receiving new messages.

**Comment by n-osennij** [comment] 2018-01-12 23:20
I'm too do not have indicator in tray, when have new mail. The icon in tray just white. There are no any additional marks. And if a delete all inbox messages, tray icon do not changed.

**Comment by j130792** [comment] 2018-08-31 19:35
I too have this issue on Ubuntu 16.04 with mailspring v1.4.2.

**Comment by dolpa** [comment] 2019-02-15 21:04
Have the same problm on ElementtaryOS Juno

**Comment by tauinger-de** [comment] 2019-05-21 11:51
Same here, Ubuntu 18.04, Mailspring installed via snap, Zenity is installed

**Comment by niraami** [comment] 2020-12-18 21:08
FYI still an issue - there is absolutely no distinction. Telegram, Discord, Syncthing, everything else works great. It currently looks like this, and I don't even know what it means:
![image](https://user-images.githubusercontent.com/24532624/102661113-818a3280-417c-11eb-9425-729c8a034dd4.png)
Arch, Polybar, Mailspring from AUR.

**Comment by CodeMouse92** [comment] 2021-01-29 23:50
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/badge-doesnt-always-appear-on-app-indicator-when-receiving-new-mail/392

Please consider joining that community and continuing the discussion there!

@goransimic and @niraami: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-29 23:50 UTC
Labels: audit
