### ISSUE TITLE
Bug: Blank Thread

### ISSUE THREAD

**Issue by johnyradio** [Foundry376/Mailspring#1433] opened 2019-03-23 22:36 UTC
Happens all the time. 
Fix: click on a different thread, then click on the problem thread. Then messages become visible. 

![image](https://user-images.githubusercontent.com/6564280/54872445-66a94500-4d81-11e9-9281-7ee928604af5.png)

**Comment by johnyradio** [comment] 2019-03-23 22:48
Sometimes, only one message in the thread is blank. Happens all the time. 

![image](https://user-images.githubusercontent.com/6564280/54872566-103d0600-4d83-11e9-9518-734d12c8d649.png)

**Comment by CodeMouse92** [comment] 2021-02-02 01:48
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/many-emails-appear-white-empty/426/2

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-02 01:48 UTC
Labels: audit
