### ISSUE TITLE
icon in the notification area: problem with the blue dot

### ISSUE THREAD

**Issue by franco27** [Foundry376/Mailspring#483] opened 2017-12-28 22:45 UTC
with Windows 10 x64 , Mailspring 1.0.11

I have not received any new messages and I have a blue dot on the Mailspring icon in the notification area

1 / when I open Mailspring, the blue dot disappears
2/I have no sound notification
3 / when Mailspring is minimized, it is not immediate and the blue dot is displayed again and no new messages
4 / I checked with another email software, I do not have new messages

![2017-12-28_23-07-52](https://user-images.githubusercontent.com/31793920/34425075-2c1647a4-ec29-11e7-91c5-899480aa94f6.png)
![2017-12-28_23-54-36](https://user-images.githubusercontent.com/31793920/34425238-88120c04-ec2a-11e7-97c8-36147dfb01c4.png)

**Comment by franco27** [comment] 2017-12-28 22:46
Normally when there are no new messages, the icon should be:
![2017-12-28_23-07-00](https://user-images.githubusercontent.com/31793920/34425104-62d0b69e-ec29-11e7-9aec-35fd3ab38414.png)

**Comment by bengotow** [comment] 2017-12-29 03:30
Hey! This should also be fixed in 1.0.12 as well—try it out and let me know if you still see this happening.

**Comment by chadidi** [comment] 2017-12-29 13:55
There is also these error in Gmail accounts where I have read all message but still showing that 1 message is not and I can't find it anywhere
![Unread error](https://image.ibb.co/jUfR2G/Capture.png)

- Windows 10 x64
- 1.0.12

**Comment by franco27** [comment] 2018-01-12 12:15
For me, you solved this problem with the version 1.0.12

**Comment by pmgrr** [comment] 2018-01-23 14:51
I have the blue dot issue. Running 1.1.0. - It shows when there is no new mail.

Mind you, the dot is very small, might be nicer to have the complete icon change colour.

**Comment by franco27** [comment] 2018-01-29 14:05
I have this problem again with version 1.1.1.
1/ when Mailspring is minimized
2/ I have a blue dot on the Mailspring icon in the notification area
3/ I open Mailspring, and there are no unread messages (no new messages)

**Comment by vfreitas54** [comment] 2018-03-23 10:59
I am in version 1.1.5 and still have the blue dot problem

**Comment by nfaivre** [comment] 2018-10-01 12:27
same here on the ubuntu snap version 1.4.2

**Comment by mickaellecolazet** [comment] 2019-06-27 13:04
https://github.com/Foundry376/Mailspring/issues/1017#issuecomment-506336191

**Comment by techtickcn** [comment] 2019-09-06 08:28
same here on the ubuntu18.04 , version 1.6.3

**Comment by CodeMouse92** [comment] 2021-01-30 00:25
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

There appear to be multiple issues being reported in the comments here. As far as I can tell, they've all been migrated to Discourse. We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

**Closed by CodeMouse92** 2021-01-30 00:25 UTC
Labels: audit
