### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by ohepworthbell** [Foundry376/Mailspring#2087] opened 2020-07-10 13:42 UTC
**Is your feature request related to a problem? Please describe.**
As per issue #1579 (apologies if this is a duplicate of other issues that I have missed) it can be awkward when scrolling through lengthy email chains and quickly sending an email (or even composing one - the same issue occurs with the 'reply' textbox). Whilst the resolution previously was to use the hotkey shortcut of `ctrl+enter`, I think having a fixed toolbar would still make sense for the following cases:

* Someone using a touchscreen laptop/device
* Someone who has clicked out of the email conversation, so they are no longer focused (e.g. if they have another app/program open to cross-reference something, and want to use the mouse to quickly click 'send' without having to click on the Mailspring window; move their hand from their mouse to their keyboard; and then press `ctrl+enter`)
* Some users may not be aware of the hotkey shortcut. Hotkeys are great for those who use them, but some users may not be aware of such features (or struggle to remember to use them/what they are). IMO, hotkeys should supplement a UX, not replace it
* The toolbar with 'send' has other options, too, which may also be applicable. Therefore, having it fixed massively increases usability

**Describe the solution you'd like**
A fixed bar at the bottom of the 'reading' pane, showing the 'Write a reply' textbox, which - when selected - is replaced with a fixed toolbar showing the 'send' button, and other related buttons

**Comment by CodeMouse92** [comment] 2021-02-11 23:01
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/style-send-button-tool-bar-with-fixed-positioning/577

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@ohepworthbell: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-11 23:01 UTC
Labels: audit, enhancement
