### ISSUE TITLE
Archiving an email also archives the email at the top of the inbox if it has not been read yet

### ISSUE THREAD

**Issue by palefire19** [Foundry376/Mailspring#552] opened 2018-01-22 15:51 UTC
##### What operating system are you using?
MacOS 10.13.2

##### What version of Mailspring are you using?
1.0.12

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I'm using Mailspring with Gmail, so possibly Gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?

I think I can reproduce this consistently:

1. Wait until you have a brand new unread email at the top of the inbox
2. Do not open it or mark it unread
3. Open up any other email in the inbox and archive it
4. In addition to the one you wanted to archive, that brand new unread email at the top of the inbox also gets archived

**Comment by palefire19** [comment] 2018-02-27 19:42
@bengotow Not a big rush, but I'm curious if you can reproduce this. It's risen to the top of my list of things I'd love to see fixed! Thank you.

**Comment by wdullaer** [comment] 2018-06-05 07:49
I have similar issues, where if I archive a mail, the selection will jump to the mail above and then after a second it'll also archive that one.
It doesn't happen all the time, but in 1/5 cases. This is super annoying, especially because there's a slight delay when it archives the second mail, which I sometimes miss.

**Comment by gus** [comment] 2018-08-14 14:28
I noticed a similar issue this morning: in my Inbox -- grandfathered gsuite account (whatever they call it these days) -- I archive the second email from the top of the inbox and Mailspring is archiving the email above it as well. Both emails have been read. This is happening regardless of which email in the list I am archiving; 2nd, 3rd, 4th from the top. All of the emails have been read and the top email is getting archived as well.

**Comment by palefire19** [comment] 2018-08-15 11:04
@bengotow Ben, any way this could be maybe elevated for the next round of bug fixes? As you chip away at most everything else, this is now the top thing hurting my daily usage. Thanks so much!

**Comment by tobias-kuendig** [comment] 2018-11-06 06:53
This bug is very dangerous. I have lost multiple mails this way.

Does the archive button archive the currently selected mail? 

I can reproduce the issue most of the time:

1. Reply to a message
1. Hit send
1. While sending, archive the open mail
1. While archiving, select another mail from the list pane
1. When the old mail is finnaly sent and archived the newly selected and the old mail dissappear both together

The actions have to be done pretty fast so the previous action is still executing.

**Comment by palefire19** [comment] 2018-11-08 15:28
@bengotow Hi Ben - Just wanted to check in with you on this. I know you're not our "fix bug on demand" helper but I think this has risen to the top of the list of "prevents Mailspring from being top client" for a lot of users and I think @tobias-kuendig has also helped to make it slightly more reproducible. Thanks!

**Comment by tobias-kuendig** [comment] 2019-03-22 08:33
Are there any news on this issue? I'm still scared to archive a mail after sending it. In fact, I just noticed I lost another mail this week because of this bug :sweat:

**Comment by stevenrombauts** [comment] 2019-12-23 09:08
I've been having the same problem, happening exactly as described. Archiving some emails seems to result in newer ones mysteriously disappearing in the archive folder as well. I've missed quite a few messages this way :)

**Comment by jprm** [comment] 2020-04-02 08:41
Same problem here (not everytime)
Windows 10
Version: 1.7.4

**Comment by CodeMouse92** [comment] 2021-02-18 22:43
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/archiving-an-email-also-archives-the-email-at-the-top-of-the-inbox-if-it-has-not-been-read-yet/699

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@palefire19 @wdullaer @gus @tobias-kuendig @stevenrombauts @jprm: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-18 22:43 UTC
Labels: audit
