### ISSUE TITLE
Mail indexing produces very much traffic

### ISSUE THREAD

**Issue by intradesign** [Foundry376/Mailspring#662] opened 2018-02-08 05:59 UTC
Living on the landside I am connect to the internet with LTE only which has a traffic limit and exceeding the limit is expensive. After connecting my Gmail (G Suite) account containing about 6GB of mails mailspring used about 30 GB to index all the mails. I think this is because of multiple labels.
Is this necessary?
A good thing would be the option to exclude folders from syncing, especially the all mail folder.

**Comment by bengotow** [comment] 2018-02-09 21:18
Hey! Thanks for reporting this - this is pretty interesting actually. I think the reason this happens is because Mailspring does a two-part scan of your mailbox. It grabs all the HEADERS for all the messages rapidly, and then goes back through fetching the bodies + attachments for messages in the last three months. I'm surprised it'd be 5x the size of the emails, though.

I'll see if I can take this into consideration next time I clean up the sync code - definitely hadn't thought much about the overall bandwidth use! Cheers—

**Comment by jerm** [comment] 2018-03-18 19:21
I wonder if external the IP hopping and/or variable reliability nature of cell networks could be contributing to this... possibly lots of re-tried large message downloads?

**Comment by intradesign** [comment] 2018-03-19 09:24
No, I don't think so. The connection is not mobile but at a fixed location
and therefore always within the same radio cell.
The connection is stable and is reconnected only once every 24 hours.

---

INTRADESIGN | Timo Mackowiak | Husstäenweg 4 | 26629 Großefehn | Tel
0441-55979455 | Mobil 0173-5237884 | timo@intradesign.xyz | USt-IdNr.
DE259414283

Diese E-Mail könnte vertrauliche und/oder rechtlich geschützte
Informationen enthalten. Wenn Sie nicht der richtige Adressat sind oder
diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den
Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die
unbefugte Weitergabe dieser Mail sind nicht gestattet.

THINK before printing!

2018-03-18 20:21 GMT+01:00 Jeremy Price <notifications@github.com>:

**Comment by qlfwyyd** [comment] 2018-05-21 12:19
Odd. My version of Mailspring doesn't download all the headers – just the email from the last three months. Any way to force this? I've tried re-caching but it doesn't seem to change anything.

**Comment by CodeMouse92** [comment] 2021-02-17 23:28
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mail-indexing-produces-very-much-traffic/678

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@intradesign @jerm @qlfwyyd: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-17 23:28 UTC
Labels: audit, product-direction
