### ISSUE TITLE
Bug: Activity sub-menu Blurry on OSX

### ISSUE THREAD

**Issue by b7s9** [Foundry376/Mailspring#2235] opened 2020-12-19 02:47 UTC
**Describe the bug**
This is the same as #1931 except I'm seeing it on Mac. Supposedly this has been fixed on Linux.

**To Reproduce**
1. Click Activity Icon next to Compose Icon up top

**Expected behavior**
Activity sub-menu text should be sharp.

**Screenshots**
![broken](https://user-images.githubusercontent.com/19176695/102678943-c3fe4000-4179-11eb-9718-fb72cab33bc6.png)

**Setup: (please complete the following information):**
 - OS: macOS
 - OS Version 10.14.6
 - Mailspring Version: ex: 1.7.8

**Additional context** 
Oddly, this is working on one of my machines with the exact same setup as above, but not the other. I could try re-installing, but since I have several email accounts logged in, that would take awhile to setup again, so I wanted to check here before I do that.

**Comment by CodeMouse92** [comment] 2021-01-18 23:44
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be connected to this:

https://community.getmailspring.com/t/interface-gets-blurry/89

Please consider joining that community and continuing the discussion there. **We need users to confirm the existence of this bug on Mailspring 1.7.8 or later, by commenting on that thread, for us to address this issue properly.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-18 23:44 UTC
Labels: audit, bug
