### ISSUE TITLE
Unable to deliver message

### ISSUE THREAD

**Issue by n00d1e5** [Foundry376/Mailspring#1476] opened 2019-04-24 18:04 UTC
##### Error message:
Sorry, Mailspring was unable to deliver this message: Sending is not enabled for this account.

And then, it crashes...

##### Are there any related issues?

https://github.com/Foundry376/Mailspring/issues/477
https://github.com/Foundry376/Mailspring/issues/352
But not same case

##### What operating system are you using?
Windows 10 1806

##### What version of Mailspring are you using?
1.6.1-aceed8e5

--

**Bug?**

##### Is this an email sync or connection issue?

Your software does a great job.
By using software "Mail" of Win 10, the outgoing box is empty.
But with your Mailspring, all goes prefect during sync and connection.
It happens ONLY when I want to send an e-mail. 

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Yes, it is a Outlook based mail (we use Outlook Web App as the web client).

##### Is the issue reproducible with a particular attachment, message, signature, etc?

In the setting up manual, SMTP does not request SSL but request authentication.
I think that the bug / issue comes from this point.
With Mail of Win 10, I can send e-mail without any problem.

**Comment by jmoran2611** [comment] 2019-12-09 12:35
I am facing exactly the same issue. With my Outlook Web App email account I cannot send emails on ubuntu 18.04

**Comment by unnir** [comment] 2020-03-09 10:38
same here, ubuntu, it works before.

**Comment by franapoli** [comment] 2020-06-19 09:43
I have a dual boot system, both with **Mailspring 1.7.8-13635bcf** installed: **elementary OS 5.1.5 Hera** and **Ubuntu 20.04**.

In both cases I configured 3 mail accounts, 2 Google, 1 IMAP. The 2 Google accounts work in both systems, **the IMAP account works on eOS but not on Ubuntu**, where it shows the "Sorry, Mailspring was unable to deliver this message: Sending is not enabled for this account" message every time.

**Comment by CodeMouse92** [comment] 2021-01-30 00:23
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

<<USER>>: Can you please confirm that this is still broken with 1.8.0, and if so, open a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-30 00:23 UTC
Labels: audit
