### ISSUE TITLE
An unexpected mailsync error occurred (3765269347)

### ISSUE THREAD

**Issue by madf78** [Foundry376/Mailspring#397] opened 2017-12-04 19:51 UTC
Impossible to start mailspring.
Each time I try to connect to my gmail account I receive the following error:
An unexpected mailsync error occurred (3765269347)

OS: Win 10

**Comment by mickaelicoptere** [comment] 2017-12-07 11:16
Same...

**Comment by spartaequip** [comment] 2018-02-15 14:01
Hello! I've got the same:
An unexpected mailsync error occurred (3765269347) View Log...

Waiting for Account JSON:

Waiting for Identity JSON:
info: Identity created at 1518691439 - using ID Schema 1


 ***
 *** A fatal error occurred during program execution.
 *** No details were provided about the error.
 ***
CREATE PROCESS FAIL: 
addr2line.exe -f -i -C -s -p -e "C:\Users\678676876\AppData\Local\Mailspring\app-1.1.4\resources\app.asar.unpacked\mailsync" 75C408C2 6F6345A5 0086FC83 0086BEC0 008AA24C 0088ECFB 008991CE 0089BACA 009B0B3C 74438654 773B4A77 773B4A47
critical:  *** Stack trace:
 ***   RaiseException
 ***   CxxThrowException
 ***   RtlGetAppContainerNamedObjectPath
 ***   RtlGetAppContainerNamedObjectPath
 ***


critical:  *** Stack trace:
 ***   RaiseException
 ***   CxxThrowException
 ***   RtlGetAppContainerNamedObjectPath
 ***   RtlGetAppContainerNamedObjectPath
 ***

**Comment by mihirpathak97** [comment] 2018-02-16 01:45
Hey! I've got the same issue.
Gmail works fine. I only get this error when I try to add my IMAP account.

**Comment by YuukiMinoru** [comment] 2018-02-16 02:07
I get this issue with any IMAP accounts I attempt to add. Gmail and Outlook accounts work fine.

**Comment by Chritzel** [comment] 2018-02-24 11:33
I'm experiencing the same issue, on both Mailspring 1.1.3 and 1.1.4. Win 10.
Adding my Gmail-account worked without any issues, but when I try to add a IMAP/SMTP-Account, I get the error mentioned above.

Here's my log that appears when I click "View Log":
```
Waiting for Account JSON:

Waiting for Identity JSON:
info: Identity created at 1519225729 - using ID Schema 1


 ***
 *** A fatal error occurred during program execution.
 *** No details were provided about the error.
 ***
CREATE PROCESS FAIL: 
addr2line.exe -f -i -C -s -p -e "C:\Users\cjuet\AppData\Local\Mailspring\app-1.1.4\resources\app.asar.unpacked\mailsync" 75AB08C2 6E6145A5 00A3FC83 00A3BEC0 00A7A01C 00A5E99B 00A68E8C 00A6BACA 00B80B3C 74D18654 777E4A77 777E4A47
critical:  *** Stack trace:
 ***   RaiseException
 ***   CxxThrowException
 ***   RtlGetAppContainerNamedObjectPath
 ***   RtlGetAppContainerNamedObjectPath
 ***


critical:  *** Stack trace:
 ***   RaiseException
 ***   CxxThrowException
 ***   RtlGetAppContainerNamedObjectPath
 ***   RtlGetAppContainerNamedObjectPath
 ***
```

**Comment by Hanchor** [comment] 2018-05-11 02:31
I'm facing the same issue here even with Gmail. 
Win10 with version 1.2.1.

Since I didn't successfully login in any email accounts, I did no see any logs.

possibly because proxy settings, since I'm currently adding gmail with a system proxy helping me cross through the GFW

**Comment by Lomacar** [comment] 2018-09-27 08:19
Same issue. Unable to add Gmail account in Windows 10. I am not using any proxy, but maybe the accountability software I use is interfering?

**Comment by yangyangoceanographer** [comment] 2020-03-12 02:42
Same issue.

**Comment by bengotow** [comment] 2020-04-16 02:50
Hey folks, thanks for reporting this—it looks like Mailspring's sync engine is crashing abruptly on your machine, and it's not even able to get a stack trace.

It looks like at least 2 of the cases above mention that the system is connected through a VPN, and another mentions a proxy - any chance that's a common theme? Mailspring doesn't support proxy configuration but it /should/ use the settings from your system if they're set up in a transparent way.

If anyone is able to test with the VPN connected vs. disconnected, that'd help a lot in narrowing this one down.

**Comment by yl-miao** [comment] 2020-08-04 12:45
> Hey folks, thanks for reporting this—it looks like Mailspring's sync engine is crashing abruptly on your machine, and it's not even able to get a stack trace.
> 
> It looks like at least 2 of the cases above mention that the system is connected through a VPN, and another mentions a proxy - any chance that's a common theme? Mailspring doesn't support proxy configuration but it /should/ use the settings from your system if they're set up in a transparent way.
> 
> If anyone is able to test with the VPN connected vs. disconnected, that'd help a lot in narrowing this one down.

Is there any chance you can add proxy feature in mailspring?

China blocks all google domains and it's impossible for us to use gmail without using proxy here. 😭

**Comment by CodeMouse92** [comment] 2021-01-29 23:37
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

Can anyone confirm that this is still broken with 1.8.0, and if so, open a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-29 23:37 UTC
Labels: audit
