### ISSUE TITLE
Encountered an error while syncing (Windows10)

### ISSUE THREAD

**Issue by MaluPL** [Foundry376/Mailspring#1628] opened 2019-09-05 08:37 UTC
Mailspring start to fail synchronization at random moments. Someday it works for half of day, somedays it fail in few minutes from start.
I've same problems on two computers with mailspring. 

##### Are there any related issues?
I found this as similiar: https://github.com/Foundry376/Mailspring/issues/238

##### What operating system are you using?

Windows 10 Pro 1809

##### What version of Mailspring are you using?

1.6.3-134a0e55

--

**Bug?**

##### Is this an email sync or connection issue?

I've normal internet connection, when this error encountered. I can login to webmails and mail on my phone works correctly. Problem only exists with mailspring.

6720 [2019-09-05 10:17:00.287] [main] [info] Identity created at 1567326375 - using ID Schema 1
6720 [2019-09-05 10:17:00.289] [main] [info] ------------- Starting Sync (XYZ@gmail.com) ---------------
6720 [2019-09-05 10:17:00.299] [background] [info] Fetching XOAuth2 access token from Gmail for 9147e6e9
6720 [2019-09-05 10:17:00.346] [metadata] [info] Metadata delta stream starting...
6720 [2019-09-05 10:17:00.620] [background] [info] Marking all folders as `busy`
6720 [2019-09-05 10:17:00.644] [background] [info] Syncing folder list...
6720 [2019-09-05 10:17:01.572] [background] [info] Syncing folder list...
6720 [2019-09-05 10:17:01.950] [background] [info] Sync loop deleting unlinked messages with phase 2.
6720 [2019-09-05 10:17:01.963] [background] [info] Sync loop complete.
6720 [2019-09-05 10:17:02.101] [foreground] [info] syncFolderChangesViaCondstore - [Gmail]/Wszystkie: modseq 6285364 to 6285364, uidnext 97054 to 97054
6720 [2019-09-05 10:17:02.225] [foreground] [info] Idling on folder [Gmail]/Wszystkie
6720 [2019-09-05 10:17:15.369] [metadataExpiration] [info] Scanning for expired metadata
6720 [2019-09-05 10:17:15.369] [metadataExpiration] [info] -- Will wake for next expiration in 7200sec
6720 [2019-09-05 10:19:01.963] [background] [info] Syncing folder list...
6720 [2019-09-05 10:19:12.297] [background] [critical]  *** Stack trace:
 ***   raise
 ***   abort
 ***   terminate
 ***   wcsstr
 ***   wcsstr
 ***   RtlInterlockedCompareExchange64
 ***   RtlInterlockedCompareExchange64
 ***   KiUserExceptionDispatcher
 ***   _CxxThrowException
 ***

10652 [2019-09-05 10:19:12.431] [main] [info] Identity created at 1567326375 - using ID Schema 1
10652 [2019-09-05 10:19:12.433] [main] [info] ------------- Starting Sync (XYZ@gmail.com) ---------------
10652 [2019-09-05 10:19:12.436] [background] [info] Fetching XOAuth2 access token from Gmail for 9147e6e9
10652 [2019-09-05 10:19:12.437] [metadata] [info] Metadata delta stream starting...
10652 [2019-09-05 10:19:12.647] [background] [info] Marking all folders as `busy`
10652 [2019-09-05 10:19:22.778] [background] [critical]  *** Stack trace:
 ***   raise
 ***   abort
 ***   terminate
 ***   wcsstr
 ***   wcsstr
 ***   RtlInterlockedCompareExchange64
 ***   RtlInterlockedCompareExchange64
 ***   KiUserExceptionDispatcher
 ***   _CxxThrowException
 ***   _o_iswdigit
 ***

13752 [2019-09-05 10:19:22.910] [main] [info] Identity created at 1567326375 - using ID Schema 1
13752 [2019-09-05 10:19:22.912] [main] [info] ------------- Starting Sync (XYZ@gmail.com) ---------------
13752 [2019-09-05 10:19:22.915] [background] [info] Fetching XOAuth2 access token from Gmail for 9147e6e9
13752 [2019-09-05 10:19:22.916] [metadata] [info] Metadata delta stream starting...
13752 [2019-09-05 10:19:23.127] [background] [info] Marking all folders as `busy`
13752 [2019-09-05 10:19:33.245] [background] [critical]  *** Stack trace:
 ***   raise
 ***   abort
 ***   terminate
 ***   wcsstr
 ***   wcsstr
 ***   RtlInterlockedCompareExchange64
 ***   RtlInterlockedCompareExchange64
 ***   KiUserExceptionDispatcher
 ***   _CxxThrowException
 ***   _o_iswdigit
 ***

10012 [2019-09-05 10:19:42.774] [main] [info] Identity created at 1567326375 - using ID Schema 1
10012 [2019-09-05 10:19:42.776] [main] [info] ------------- Starting Sync (XYZ@gmail.com) ---------------
10012 [2019-09-05 10:19:42.779] [metadata] [info] Metadata delta stream starting...
10012 [2019-09-05 10:19:42.780] [background] [info] Fetching XOAuth2 access token from Gmail for 9147e6e9
10012 [2019-09-05 10:19:42.975] [background] [info] Marking all folders as `busy`
10012 [2019-09-05 10:19:53.133] [background] [critical]  *** Stack trace:
 ***   raise
 ***   abort
 ***   terminate
 ***   wcsstr
 ***   wcsstr
 ***   RtlInterlockedCompareExchange64
 ***   RtlInterlockedCompareExchange64
 ***   KiUserExceptionDispatcher
 ***   _CxxThrowException
 ***   _o_iswdigit
 ***

7192 [2019-09-05 10:19:53.311] [main] [info] Identity created at 1567326375 - using ID Schema 1
7192 [2019-09-05 10:19:53.313] [main] [info] ------------- Starting Sync (XYZ@gmail.com) ---------------
7192 [2019-09-05 10:19:53.316] [background] [info] Fetching XOAuth2 access token from Gmail for 9147e6e9
7192 [2019-09-05 10:19:53.316] [metadata] [info] Metadata delta stream starting...
7192 [2019-09-05 10:19:53.537] [background] [info] Marking all folders as `busy`
7192 [2019-09-05 10:20:03.650] [background] [critical]  *** Stack trace:
 ***   raise
 ***   abort
 ***   terminate
 ***   wcsstr
 ***   wcsstr
 ***   RtlInterlockedCompareExchange64
 ***   RtlInterlockedCompareExchange64
 ***   KiUserExceptionDispatcher
 ***   _CxxThrowException
 ***   _o_iswdigit
 ***

14148 [2019-09-05 10:21:28.337] [main] [info] Identity created at 1567326375 - using ID Schema 1
14148 [2019-09-05 10:21:28.339] [main] [info] ------------- Starting Sync (XYZ@gmail.com) ---------------
14148 [2019-09-05 10:21:28.343] [background] [info] Fetching XOAuth2 access token from Gmail for 9147e6e9
14148 [2019-09-05 10:21:28.344] [metadata] [info] Metadata delta stream starting...
14148 [2019-09-05 10:21:28.556] [background] [info] Marking all folders as `busy`
14148 [2019-09-05 10:21:38.678] [background] [critical]  *** Stack trace:
 ***   raise
 ***   abort
 ***   terminate
 ***   wcsstr
 ***   wcsstr
 ***   RtlInterlockedCompareExchange64
 ***   RtlInterlockedCompareExchange64
 ***   KiUserExceptionDispatcher
 ***   _CxxThrowException
 ***   _o_iswdigit
 ***

13428 [2019-09-05 10:21:38.817] [main] [info] Identity created at 1567326375 - using ID Schema 1
13428 [2019-09-05 10:21:38.819] [main] [info] ------------- Starting Sync (XYZ@gmail.com) ---------------
13428 [2019-09-05 10:21:38.823] [background] [info] Fetching XOAuth2 access token from Gmail for 9147e6e9
13428 [2019-09-05 10:21:38.825] [metadata] [info] Metadata delta stream starting...
13428 [2019-09-05 10:21:39.015] [background] [info] Marking all folders as `busy`
13428 [2019-09-05 10:21:49.120] [background] [critical]  *** Stack trace:
 ***   raise
 ***   abort
 ***   terminate
 ***   wcsstr
 ***   wcsstr
 ***   RtlInterlockedCompareExchange64
 ***   RtlInterlockedCompareExchange64
 ***   KiUserExceptionDispatcher
 ***   _CxxThrowException
 ***   _o_iswdigit
 ***

10320 [2019-09-05 10:21:49.243] [main] [info] Identity created at 1567326375 - using ID Schema 1
10320 [2019-09-05 10:21:49.245] [main] [info] ------------- Starting Sync (XYZ@gmail.com) ---------------
10320 [2019-09-05 10:21:49.249] [background] [info] Fetching XOAuth2 access token from Gmail for 9147e6e9
10320 [2019-09-05 10:21:49.249] [metadata] [info] Metadata delta stream starting...
10320 [2019-09-05 10:21:49.436] [background] [info] Marking all folders as `busy`
10320 [2019-09-05 10:21:52.622] [background] [info] Syncing folder list...
10320 [2019-09-05 10:21:53.413] [background] [info] Syncing folder list...
10320 [2019-09-05 10:21:53.514] [background] [info] syncFolderUIDRange for [Gmail]/Wszystkie, UIDs: 94863 - 97054, Heavy: false
10320 [2019-09-05 10:21:54.491] [foreground] [info] syncFolderChangesViaCondstore - [Gmail]/Wszystkie: modseq 6285364 to 6285364, uidnext 97054 to 97054
10320 [2019-09-05 10:21:54.517] [background] [info] - remote=400, local=400
10320 [2019-09-05 10:21:54.640] [foreground] [info] Idling on folder [Gmail]/Wszystkie
10320 [2019-09-05 10:21:54.836] [background] [info] syncFolderUIDRange for [Gmail]/Kosz, UIDs: 1 - 21621, Heavy: false
10320 [2019-09-05 10:21:54.961] [background] [info] - remote=6, local=6
10320 [2019-09-05 10:21:55.021] [background] [info] syncFolderUIDRange for [Gmail]/Spam, UIDs: 48530 - 48931, Heavy: false
10320 [2019-09-05 10:21:55.266] [background] [info] - remote=400, local=400
10320 [2019-09-05 10:21:55.269] [background] [info] Sync loop deleting unlinked messages with phase 2.
10320 [2019-09-05 10:21:55.280] [background] [info] Sync loop complete.
10320 [2019-09-05 10:22:04.251] [metadataExpiration] [info] Scanning for expired metadata
10320 [2019-09-05 10:22:04.252] [metadataExpiration] [info] -- Will wake for next expiration in 7200sec
10320 [2019-09-05 10:23:55.280] [background] [info] Syncing folder list...
10320 [2019-09-05 10:24:05.445] [background] [critical]  *** Stack trace:
 ***   raise
 ***   abort
 ***   terminate
 ***   wcsstr
 ***   wcsstr
 ***   RtlInterlockedCompareExchange64
 ***   RtlInterlockedCompareExchange64
 ***   KiUserExceptionDispatcher
 ***   _CxxThrowException
 ***

10040 [2019-09-05 10:24:05.696] [main] [info] Identity created at 1567326375 - using ID Schema 1
10040 [2019-09-05 10:24:05.699] [main] [info] ------------- Starting Sync (XYZ@gmail.com) ---------------
10040 [2019-09-05 10:24:05.704] [background] [info] Fetching XOAuth2 access token from Gmail for 9147e6e9
10040 [2019-09-05 10:24:05.705] [metadata] [info] Metadata delta stream starting...
10040 [2019-09-05 10:24:05.950] [background] [info] Marking all folders as `busy`

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No, i have yandex, gmail and my own dovecot server, and everywhere problem exists.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No

**Comment by bengotow** [comment] 2019-10-22 03:22
Hey folks! Well, the good news is I've finally gotten this to happen on my machine (or at least, something mostly similar.) The bad news is that even with the app attached to Visual Studio the output is still mostly garbage - hopefully will get to the bottom of this. Definitely seems arbitrary and probably caused by some characters / data sent by the IMAP server, but it's unclear why it'd be a windows-specific issue.

**Comment by CodeMouse92** [comment] 2021-02-02 02:33
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/the-eternal-sync-bug/334

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-02 02:33 UTC
Labels: audit, bug, needs-reproduction, windows
