### ISSUE TITLE
Bug: Can't add icloud on Windows

### ISSUE THREAD

**Issue by paulomanrique** [Foundry376/Mailspring#2049] opened 2020-06-09 09:57 UTC
When trying to add an iCloud account on Windows, I get an error message: 

Waiting for Account JSON:

Waiting for Identity JSON:
info: Identity created at 1507252051 - using ID Schema 0

OPENSSL_Uplink(7A45D878,08): no OPENSSL_Applink

**Comment by edwinosky** [comment] 2020-06-14 20:05
same problem here, when trying to add icloud account or any other server that uses ssl

**Comment by thejustinwalsh** [comment] 2020-06-19 01:55
Setting up a new machine and experiencing the same failure.

**Comment by thejustinwalsh** [comment] 2020-06-23 22:31
Looks like version 1.76 is working for iCloud on Windows. The release notes indicate that an OpenSSL upgrade was done to resolve some changes to Yahoo and potentially other SMTP mail servers, and it appears this change has caused an SSL problem in iCloud now.

**Comment by irrenhaus** [comment] 2020-08-23 19:18
Not working for mailbox.org even in 1.76.

**Comment by arturluizbr** [comment] 2020-10-09 15:18
This started to happen with me when I upgraded my server from Ubuntu 18.04 to 20.04 yesterday, maybe its related somehow to Dovecot version upgrade, I'm using at the moment Dovecot 2.3.7.2

**Comment by moritzruth** [comment] 2021-02-05 13:02
I have the same issue when adding an IMAP account. It doesn't matter whether I choose STARTTLS or TLS.

**Comment by CodeMouse92** [comment] 2021-02-08 19:25
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/cant-add-icloud-no-openssl-applink/497

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@paulomanrique @arturluizbr: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-08 19:25 UTC
Labels: audit, bug
