### ISSUE TITLE
Bug: Mailspring stops responding for email chains - v1.7.6 

### ISSUE THREAD

**Issue by StevenMapes** [Foundry376/Mailspring#1979] opened 2020-05-12 08:24 UTC
**Describe the bug**
Since the update to 1.7.6 (Kubuntu 18.04 - MS installed via snapd) I find that mailspring stops responding 9/10th of the time.

**update** This appears to be linked to having a large email chain. One of the messages I have has 55 responses (gmail) and as soon as that is selected the app stops responsding

**To Reproduce**
1. Launch mailspring
2. click on or cursor over the large email

**Expected behavior**

**Screenshots**

**Setup: (please complete the following information):**
 - OS: Linux Kubuntu
 - OS Version 18.04 - Plasma 5.12.9, KDE Framework 5.44.0, Qt 5.9.5
 - Mailspring Version: ex: 1.7.6
**Additional context** 

I have several Gmail accounts connected. I use to have a Yahoo! mail account connected but removed it due to the bug in 1974 - https://github.com/Foundry376/Mailspring/issues/1974

**Comment by CodeMouse92** [comment] 2021-02-23 17:55
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/significant-lag-on-large-threads/183

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-23 17:55 UTC
Labels: audit, bug
