### ISSUE TITLE
[Feature Request] Exclude a specific email account from unified Inbox

### ISSUE THREAD

**Issue by MurzNN** [Foundry376/Mailspring#1272] opened 2018-12-17 08:28 UTC
At now unified Inbox folder contain mail from all configured accounts. Will be good to have option for exclude some accounts from unified Inbox and show them only in separate group.

**Comment by CodeMouse92** [comment] 2021-01-29 21:42
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/disable-selective-unified-inbox/136

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

**Closed by CodeMouse92** 2021-01-29 21:42 UTC
Labels: audit, enhancement
