### ISSUE TITLE
Feature Request: Seamless title bar like VSCode or ability to hide frame

### ISSUE THREAD

**Issue by k4rli** [Foundry376/Mailspring#2084] opened 2020-07-08 20:56 UTC
Seamless titlebar would improve the overall look of main window, especially in Windows. This is less of an issue on light themes, but the white title bar does not look good with dark themes.

![Windows 10 reference](https://supa.ee/i/HungryLeopardseal.png)

An easier solution to improve appearance would be to provide a way to hide it. This should not reduce user experience if it's only opt-in.

**Comment by NicTanghe** [comment] 2020-08-27 21:48
The only reason i installed the app is to have a Dracula themed mail app.
It is very annoying that there is a white titlebar at the top of my Dracula theme.

**Comment by NicTanghe** [comment] 2020-09-16 10:03
if someone is having dificulity with inplementing this in windows 10 it should be quite eazy when [Winui](https://docs.microsoft.com/en-us/windows/apps/winui/winui3)/

**Comment by amrbashir** [comment] 2021-01-15 15:12
Since Mailspring is built using Electron, it should be easy to implement without using WinUI 3 (pretty sure WinUI 3 is aimed towards wpf, uwp, and windows forms so you can't use it in electron apps).

**Comment by CodeMouse92** [comment] 2021-01-17 02:57
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/seamless-title-bar-or-hide-frame/58/1

Please consider joining that community and continuing the discussion there! Bonus: if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-17 02:57 UTC
Labels: audit, enhancement
