### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by AlejoJauregui** [Foundry376/Mailspring#1998] opened 2020-05-21 13:23 UTC
**Describe the bug**
I have the same problem that we have in other mailspring versions. I can't connect to my O365 account.

**To Reproduce**
1. Go to 'PREFERENCES'
2. Click on 'Update Connection settings'
3. I tried to re-authenticate, but has an authenticaton error. 
4. 
![image](https://user-images.githubusercontent.com/12925866/82563177-2dfb2c00-9b3c-11ea-89be-61365c2b6bc6.png)

And the error that is reported in the login is:

mailsmtp Last Error Code: 296
mailsmtp Last Error Explanation: Unknown
mailsmtp Last Error Location: 10
mailsmtp Last Auth Type: 16

Windows 10 version.

**Comment by kzadora** [comment] 2020-05-21 20:04
dupe of https://github.com/Foundry376/Mailspring/issues/1996 ?

**Comment by bengotow** [comment] 2020-05-24 22:11
Hey folks, thanks for reporting this - going to merge this into #1996. The fix has landed in master and I'll be shipping it soon!

**Closed by bengotow** 2020-05-24 22:11 UTC
Labels: bug
