### ISSUE TITLE
Bug: Privacy issue - Mailspring leaking image data in email replies

### ISSUE THREAD

**Issue by paksj** [Foundry376/Mailspring#2134] opened 2020-09-02 14:24 UTC
I use www.emailprivacytester.com to check on data being leaked by email providers & clients. Mailspring doesn't leak anything while reading (only if loading remote images, but that all email clients seem to). But mailspring does leak image data as soon as you click on reply (see screenshot) - even if you haven't sent the email. It happens with all email accounts & does not happen in Apple Mail or Thunderbird. 

![Screenshot 2020-09-02 at 12 42 25 PM](https://user-images.githubusercontent.com/27799808/91995791-c1d9b800-ed27-11ea-9f51-3fcaca9e7710.jpg)

Mac OS 10.15.6
Mailspring 1.7.8

**Comment by CodeMouse92** [comment] 2021-03-03 02:36
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/privacy-issue-mailspring-leaking-image-data-in-email-replies/950

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@paksj: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-03 02:36 UTC
Labels: audit, bug
