### ISSUE TITLE
Sent mail saved with wrong date - Dec 31, 1969

### ISSUE THREAD

**Issue by deverill** [Foundry376/Mailspring#508] opened 2018-01-05 15:07 UTC
I just downloaded Mailspring 1.0.12-cf081332.  When I sent an email it was _seemingly_ not added to the sent folder.  I searched for a term I knew was in there and on the list it shows as Dec 31, 1969 but when I open it the date is correct.  I am using Gmail and sent emails are set to go to [Gmail]/Sent Mail and it does appear there correctly in the web interface to Gmail.

![image](https://user-images.githubusercontent.com/496420/34614501-adffb1ac-f1ff-11e7-9b82-1a66e2413b32.png)

Hope it helps.
This is similar to issue #457 but is not exactly the same.

**Comment by PixelPoetix** [comment] 2018-01-05 19:03
I've had a similar issue as yours related to the **exact same date** showing up on a zombie message - no matter what I tried, I couldn't get rid of the damn thing! I'd delete it, then it would return to my inbox moments later. A couple times I thought I'd finally killed it off for good only to have it randomly come back later that day. It seems to randomly come and go as it pleases. Super annoying.

**Comment by bengotow** [comment] 2018-01-30 00:30
Hey folks - thanks for the updates, thanks for tracking this down - looks like you're right: if the only message(s) in the conversation were sent by you, the conversation displays correctly in your account's `Sent Mail` folder, but as "1969" when viewing search results, labels, and other places where threads are typically sorted by "last received message". I'm testing the fix now and it should land in the next release.

**Comment by gombosg** [comment] 2018-02-05 22:41
Oh yes, I can confirm this. All the messages in the 'Sent Mail' folder show up with the date "1 Jan 1970" - although if I open them, they show the correct date & time.

I hope that the fix comes out soon, this could have been a show-stopper for me, unable to properly browse my sent folder.

**Comment by bengotow** [comment] 2018-02-09 20:22
Hey folks—version `1.1.3` shipped a few days ago and included the fix for this issue. You should have received the update automatically, but if not you can download it directly from getmailspring.com/download. Enjoy! Gonna go ahead and close this.

**Closed by bengotow** 2018-02-09 20:22 UTC
Labels: done-pending-release

**Comment by gombosg** [comment] 2018-02-12 20:18
I have checked with version 1.1.3-27dcee2f.
See the attached screen. Mail shows up with "no date" but as I scroll, the scroller shows some date, and of course date shows up in the emails.
Let me know if you need some more info.
[http://oi67.tinypic.com/2mqw2gx.jpg](http://oi67.tinypic.com/2mqw2gx.jpg)
