### ISSUE TITLE
[Feature Request] Handle notifications for separate mail accounts separately

### ISSUE THREAD

**Issue by gathurian** [Foundry376/Mailspring#1039] opened 2018-08-22 18:31 UTC
It would be great if you could handle the notification settings for each account (like e.g. in the Windows Mail App).
I, for example, have a couple of 'trash accounts', where I don't want to be notified if I get a new mail. But it's still convenient to have them synced with Mailspring to check every once in a while. So it would be great if one could mute single mail accounts while still getting notifications for other accounts.

**Comment by VannevarB2** [comment] 2018-08-30 16:07
To make this even more useful, I'd like to see notifications set based on folders/labels as well.
For instance, I'd like to set a notification for payment reminder emails that are tagged Important but maybe not so for a coupon that is delivered to my Promotions folder/label.

**Comment by rbbernardino** [comment] 2019-07-21 23:41
Hello there! It's been almost one year since this post. I believe having a finer control of which labels/folders should generate notifications on new e-mail is really important.
We don't need to be notified for Promotions e-mails etc. It can be really annoying...

@Foundry376, any chances that this might get implemented in the future?

**Comment by CodeMouse92** [comment] 2021-02-24 18:54
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/per-account-mailbox-notification-settings/133

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-24 18:54 UTC
Labels: audit, enhancement
