### ISSUE TITLE
Error when sending new emails

### ISSUE THREAD

**Issue by EtoileFilante** [Foundry376/Mailspring#1200] opened 2018-10-30 13:29 UTC
Hello,

I've been having a very annoying problem since I started using mailspring a few months ago.

I'm currently using Mailspring v1.5.1-da141eaf (in french) on Ubuntu 18.04 LTS

Sometimes, after I click on send a new email (no problem when replying), I get the following message a few seconds after: "Désolé, Mailspring n'a pas pu transmettre ce message: undefined"

It gets worse. When I go to drafts, the email is there, I can see the beginning of the content, but when I double click to open the email, it opens a new email(well at least the content and subject disappear). From there on everything is lost and I have to start again.

I've lost enough emails so that I systematically save their content on the side before sending new ones, but it's not that fun.

It happens about 1 time out of 2 or 3, and usually if I have saved their content and try to send it again, it works.

Thanks
Nathanaël

**Comment by SimonVanacco** [comment] 2018-10-30 22:16
What email provider do you use? Gmail, outlook or something else? 
Did you have this issue before updating to the latest version? 

Simon

**Comment by EtoileFilante** [comment] 2018-10-31 09:47
Yes I did have this issue before updating to the latest version.

I have 4 accounts connected, 1 is gmail the others are from other providers (from 3 different providers for which I add the smtp and imap). I have had problems with all 3 other providers. I don't recall having it with my gmail provider.

Nathanaël

**Comment by CodeMouse92** [comment] 2021-01-22 00:20
Duplicate of #1107

**Comment by CodeMouse92** [comment] 2021-01-22 00:21
Thank you for reporting this. 2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/mail-lost-when-sending/169

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-22 00:21 UTC
Labels: audit
