### ISSUE TITLE
Feature Request: Live Tile

### ISSUE THREAD

**Issue by PowerSnail** [Foundry376/Mailspring#202] opened 2017-10-18 20:37 UTC
Live Tile is a feature that many Windows App uses to display information on the Start Menu. The built-in Mail and Calendar app of Windows 10 uses Live Tile to display summaries of new, unread emails. 

This is actually a greatly convenient feature, especially when many other apps supports its. Opening start menu is like opening a notification center.

Sorry I could not provide any information on the implementation. I have absolutely no knowledge how electron app could implement that. Only suggesting from the perspective of a user.

Thank you very much.

**Comment by bengotow** [comment] 2017-10-19 01:09
Ahh man I love live tiles on Windows, they're great. I'm not sure how we'd go about doing this - if anyone wants to contribute and has some windows development experience, we basically need an Electron app to get a live tile. Hopefully other Electron apps have figured this out already!

**Comment by dbhowell** [comment] 2017-10-19 02:25
Here is an example from Felix: https://github.com/felixrieseberg/electron-uwp-background

**Comment by saravanabalagi** [comment] 2019-10-06 18:41
I would love to see live tiles for Mailspring so I can happily unpin my Windows 10 mail app!!!

**Comment by CodeMouse92** [comment] 2021-01-29 22:20
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

<<LINK>>

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@PowerSnail @dbhowell @saravanabalagi: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-29 22:20 UTC
Labels: audit, enhancement, good first issue
