### ISSUE TITLE
[Feature Request] Line wrapping, plaintext support for Linux Kernel community

### ISSUE THREAD

**Issue by robertfoss** [Foundry376/Mailspring#46] opened 2017-10-06 07:45 UTC
Nearly all Linux related mailing list development is currently done using mutt/thunderbird/evolution.
And those email clients are all flawed in serious ways.

 - Mutt has the 1960ies UI going for it.
 - Thunderbird just permanently pegs a CPU core at 100% due to not coping with higher than normal mail volume.
 - Evolution does not filter email properly, it will just dump _all_ incoming email into 'Inbox' if connection issues are had, like when moving around your laptop between WiFis.

So adding support for a few features could be a cheap and fast PR and adoption win.

- [ ] Line wrapping support at 80-chars
- [ ] Plain text email support
- [ ] The general ability to cope with >100k emails

**Does this feature exist in another mail client or tool you use?**
Mutt, Evolution and Thunderbird

**Comment by robertfoss** [comment] 2017-10-07 15:50
- Subscribe to: linux-kernel @ http://vger.kernel.org/vger-lists.html
 - Subscribe to: dri-devel @ https://lists.freedesktop.org/mailman/listinfo/dri-devel
 - Subscribe to: mesa-dev @ https://lists.freedesktop.org/mailman/listinfo/mesa-dev
 - Subscribe to: intel-gfx @ https://lists.freedesktop.org/mailman/listinfo/intel-gfx

The way I typically use there lists is by filtering them all into their own folder, except for any email that is explicitly To/CC/BCC-ing me. Those emails get to stay in the inbox.

After a few months you'll have 100-200k emails. And having them around is kind of useful for doing searches of patches that have been submitted.

**Comment by bengotow** [comment] 2017-10-11 00:41
Thanks @robertfoss — I've signed one of my test accounts up for these emails. It's actually pretty difficult to sign up for the linux-kernel one without a client that sends plaintext. Hah :-) Will keep you posted on further improvements for this use case.

**Comment by bayang** [comment] 2017-11-27 15:05
Hi,
plain text mail composing and sending would be a huge improvement for me as well.

**Comment by simotek** [comment] 2018-02-07 00:27
I also use a number of mailing lists that are fussy about plain text, in addition it would also be nice if you could set up plain text email signatures.

**Comment by kevinherron** [comment] 2018-07-13 13:43
It looks like line wrapping is possible to implement via plugin, but even then, it's going to be sending <br> elements once Mailspring HTML-ifies the message.

Is there any movement on plaintext support @bengotow ?

**Comment by soleen** [comment] 2018-08-29 19:17
kernel developers would need: messages in plain text, enabled/disable line wrapping via a button/hotkey, exclusive threading by message-id, download all messages in a thread (to be able to apply patches).

**Comment by fragkp** [comment] 2018-08-30 22:55
This is the only reason, why i cant currently use mailspring 🤒 

Can we get a status update @bengotow?

**Comment by bengotow** [comment] 2018-12-18 04:35
Hey folks—linking this to #52. Mail merge is coming in an upcoming release, and I think that feature would also benefit a lot from a plaintext mode. I'll take a look and see what it'd take to get this in.

**Comment by fragkp** [comment] 2018-12-18 06:06
Realy cool, cant wait for it! Thx

**Comment by CodeMouse92** [comment] 2021-01-21 01:20
Since this is in progress, I am locking this, but not closing or migrating it to Discourse.

**Comment by CodeMouse92** [comment] 2021-02-25 01:50
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/line-wrapping-plaintext-support-for-linux-kernel-community/785

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@robertfoss @kevinherron @soleen : if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-25 01:50 UTC
Labels: composer, product-direction
