### ISSUE TITLE
Suggestion: Mute notifications

### ISSUE THREAD

**Issue by brunofin** [Foundry376/Mailspring#966] opened 2018-07-05 07:24 UTC
Quick suggestion:

On right clicking the tray icon, there could be an option Mute notifications for -> 10 minutes | 15 minutes | 30 minutes | 1 hour | etc...

This is super useful when for example trying to focus on something, or sharing your screen with your boss and avoid weird situations when receiving job interview follow up emails (:laughing: just an example!)

**Comment by bengotow** [comment] 2018-07-08 06:01
Hey! This would definitely be cool—I think this would be a good starter project for someone looking to contribute, too. (If you search the project for `new Notification(` you can find where they're created.) Thanks!

**Comment by brunofin** [comment] 2018-07-08 09:38
What would be the best way to deal with queued notifications when the mute period expires? Fire all of them at once? Or show something like "you have 3 new mails"?

**Comment by VannevarB2** [comment] 2018-08-30 16:09
Can we make sure this integrates with/respects the "Focus assist"/do not disturb feature in Windows 10?

**Comment by muravjov** [comment] 2018-09-05 09:53
> What would be the best way to deal with queued notifications when the mute period expires? Fire all of them at once? Or show something like "you have 3 new mails"?

I would prefer behaviour as in Slack: "you have 3 new mails", that is all

**Comment by CodeMouse92** [comment] 2021-02-25 01:00
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mute-notifications/777

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@brunofin @VannevarB2 @muravjov: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-25 01:00 UTC
Labels: audit, enhancement, good first issue
