### ISSUE TITLE
Mailspring sometimes don't attach files

### ISSUE THREAD

**Issue by PrzemekSkw** [Foundry376/Mailspring#822] opened 2018-04-10 08:10 UTC
Are there any related issues?
NO

What operating system are you using?
Manjaro Deepin (archlinux based)

What version of Mailspring are you using?
1.2.1

Sometimes when I attach files in Mailspring it send blank emails. I don't know what is related. I try sending with many configurations (one recipient, many recipients, with topic or without etc.). 

Regards,
Przemek

**Comment by palefire19** [comment] 2018-04-11 13:17
I can confirm this is happening on Mac too. I haven't been able to reproduce when the attachments don't attach - unfortunately so far it seems random.

**Comment by awemerson** [comment] 2018-05-01 15:54
This also happens on Windows 10 (Mailspring 1.2.1) in various email accounts/providers - it seems random here too, but needs to be fixed!

**Comment by hnkumar** [comment] 2018-05-09 12:05
I'm also facing the same issue. Hope it is going to be fixed soon. If this situation occurs, I have to close mailspring for 10min and start again then it will work fine. It's a random behavior.  Majorly this issue occurs when you write new mail, if you are going to reply existing mail then it will work most of the time.

I'm on Ubuntu and MailSpring version 1.2.1

**Comment by WesHildebrandt** [comment] 2018-05-11 15:19
I'm on Ubuntu 17.10 and Mailspring v1.2.1 and am seeing this problem as well.  I haven't fully diagnosed it, but when I compose new mail and attach a file it seems to never actually get attached to the send email.  Could someone from Mailspring let us know if you've seen these comments or this issue and know how to fix it?

**Comment by neamtua** [comment] 2018-05-30 21:02
I'm on High Sierra and I attach a file but the email sends without it. It's a PDF of 108kb. It happens all the time.

**Comment by neamtua** [comment] 2018-06-01 04:40
I have come back to this, I've tried attaching multiple types of files, the account is a gmail account. It just doesn't work. It either doesn't show a file attached and I need to try again, or it shows but there's no preview, just the name and an "x" button which sometimes gives an error when pressed after a while. Unfortunately, this is a deal breaker for me, it's a basic functionality that doesn't work at all.
<img width="425" alt="screen shot 2018-06-01 at 07 40 15" src="https://user-images.githubusercontent.com/1029457/40821362-195cf7e2-656f-11e8-938e-5b3c6c4da172.png">
<img width="431" alt="screen shot 2018-06-01 at 07 39 44" src="https://user-images.githubusercontent.com/1029457/40821363-197a0a8a-656f-11e8-98d3-61ccdeeb415e.png">

**Comment by lyhongpon** [comment] 2018-06-14 07:10
Seems like no one is listening to this. ):

**Comment by oritsemisan** [comment] 2018-06-21 08:47
same here

**Comment by franciscaconcha** [comment] 2018-06-28 15:54
I am having the same problem on Ubuntu 18.04 with Mailspring v1.2.2. So far it seems to be random which files get attached and which don't.

**Comment by franciscaconcha** [comment] 2018-06-28 15:54
I am having the same problem on Ubuntu 18.04 with Mailspring v1.2.2. So far it seems to be random which files get attached and which don't.

**Comment by bengotow** [comment] 2018-07-08 17:47
Hey folks thanks for reporting this—I thought this might be related to handling of Windows special characters (#810) but if it's happening on Mac and Windows too that can't be it. If anyone can identify whether this happens with a specific type of attachment, that'd be super helpful. In the meantime I'll try to track down exactly where the file data is getting lost.

(Not seeing a preview in the composer window is expected behavior for everything but images, unfortunately. On the Mac, Mailspring generates quicklook previews for attachments but only in messages you receive. I'll see if I can address that separately.)

**Comment by DKimballl7** [comment] 2018-07-09 02:57
I try to attach an excel spreadsheet and it seems to attach, but its muted and the icon is blank, instead of showing an excel icon.

**Comment by franciscaconcha** [comment] 2018-07-09 08:21
To me it has happened with pdf, jpg and png files.

**Comment by DKimballl7** [comment] 2018-07-09 13:09
I love this application and would possibly consider paying for the pro version, but if it can't send attachments, I can't continue to use it.

**Comment by JunnanZ** [comment] 2018-07-17 05:32
Can confirm this (Arch Linux). The worst thing about this is that it's so random and usually I didn't realize it until the receiver told me.

**Comment by DKimballl7** [comment] 2018-07-17 13:58
I’m not sure what you mean by (Arch Linux).  I am running a native Windows 10 OS and I do know that there are others that are experiencing the same issue as I have run into a blog on Github that has many individuals that are having the same issue.  

Here is the link to the Github I found with multiple people having the same issue on different platforms:

https://github.com/Foundry376/Mailspring/issues/822



Sent from Mail for Windows 10

**Comment by dale76uk** [comment] 2018-07-23 14:08
I'm running Ubuntu 18.04, i had the same issue using Mailspring on Ubuntu 16 also.  I'm current using Version 1.3 and still have the issue of attachments not sending 95% of the time. It doesnt seem to matter what the attachment type is, it rarely sends.

One work around to guarantee the email sends with the attachment is to CC or Bcc yourself into the mail.  This produces a 100% working fix.

Please would some address this annoying bug, I'm so close to paying for the PRO version but cant justify it with this annoying bug.

**Comment by awemerson** [comment] 2018-08-05 16:52
Still facing this issue regularly with all sorts of file types. (Running Mailspring 1.3.0 on Windows 10) 

I think it is related to whether or not the attachment uploads before I click send. On slower internet connections, the file fails to attach almost every time, whereas on a faster internet connection it happens less frequently. 

I would seriously consider paying for the pro version if it weren't for this bug.

**Comment by DKimballl7** [comment] 2018-08-05 22:28
I have 100 Mb connection and my file never upload.  I too would consider paying for the Pro service, but not if I cannot send attachments. 



Sent from Mail for Windows 10

**Comment by CodeMouse92** [comment] 2021-02-04 23:09
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/attached-files-not-sent/468

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-04 23:09 UTC
Labels: audit
