### ISSUE TITLE
Emails Not Marked as Read if a New Email Comes into the Thread While Reading Thread

### ISSUE THREAD

**Issue by seesemichaelj** [Foundry376/Mailspring#617] opened 2018-02-01 22:28 UTC
**Reproduction Steps:**
1. Open thread
2. Receive email on that thread while thread is open
3. Go back to Inbox, see thread has unread emails
4. Open thread
5. Go to Inbox; the thread should be marked read by now but it isn't
6. You can Right Click->Mark as Read to mark it as read (or if you get in the state of #616 or #247, you can Mark Unread then Mark Read)

##### Are there any related issues?
#616 and #247 may be related. It seems if I read the email on another client, then I had similar "ghost" unread as #616. #247 seems to describe the same issue as #616

##### What operating system are you using?
Elementary OS 0.4.1 Loki

##### What version of Mailspring are you using?
1.1.1

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Currently Gmail has only been tested, but I have a feeling this has happened under other providers; I'll have to test later to verify.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Not applicable

**Comment by bengotow** [comment] 2018-02-03 17:03
Hey! So I think this is actually one of the most long standing issues in the app. (I think there's a Nylas Mail ticket going back years!) Basically, if use the Gmail style UI where you slide in and out of a thread, sliding in to the same thread repeatedly won't remark the thread as read again. I'll see if I can get this fixed today.

**Comment by bengotow** [comment] 2018-02-03 17:35
Hmm - so the code in MessageStore really needs to be refactored one of these days, but it looks like a state variable in there that was added to prevent it from "marking as read" to aggressively as new messages arrived was preventing it from re-marking the thread as read at Step 4 of your flow above.  I've confirmed this patch (5cae7f4fe75e5486334dbe6efd3147c2a5585125) fixes it, but I think we really need to add some sort of "2 New Messages" notification that appears and would allow you to mark the new messages as read without leaving and drilling back in.

**Comment by bengotow** [comment] 2018-02-09 20:25
Hey folks—version `1.1.3` shipped a few days ago and included the fix for this issue. You should have received the update automatically, but if not you can download it directly from getmailspring.com/download. Enjoy! Gonna go ahead and close this.

**Closed by bengotow** 2018-02-09 20:25 UTC
Labels: bug, done-pending-release

**Comment by cursorme** [comment] 2018-06-15 14:21
Hi,

I'm using latest version 1.2.2 on Manjaro Linux and I've been experience this issue. When I receive several emails on an existing conversation most of the new emails don't get as read after I click them. Does not seem to affect emails that are not on conversations.

Thanks
Eduardo

**Comment by Draghmar** [comment] 2018-07-11 11:57
I can confirm that 1.2.2 does have this issue on Windows 10. When conversation is selected and a new e-mail arrives it shows as unread. The only way to mark is as read is to click on other conversation and then click it again (or use Mark as read option from the menu).
