### ISSUE TITLE
Sync issues with university's Outlook (Office 365) service

### ISSUE THREAD

**Issue by Kataera** [Foundry376/Mailspring#1749] opened 2019-12-26 13:30 UTC
##### Are there any related issues?

Possibly related: https://github.com/Foundry376/Mailspring/issues/1660, https://github.com/Foundry376/Mailspring/issues/1664

##### What operating system are you using?

Windows 10

##### What version of Mailspring are you using?
(eg: 1.6.3 or 1.7.0 - this is shown in Mailspring's main menu.)

1.7.2, however the same issue exists on 1.6.3 as well.

**Bug?**

##### Is this an email sync or connection issue?

Sync issue.

Log excerpt that seems to be highlighting the issue:

> 6624 [2019-12-26 13:12:29.309] [main] [info] Identity created at 1573478833 - using ID Schema 1
> 6624 [2019-12-26 13:12:29.311] [main] [info] ------------- Starting Sync (sccmho@leeds.ac.uk) ---------------
> 6624 [2019-12-26 13:12:29.317] [metadata] [info] Metadata delta stream starting...
> 6624 [2019-12-26 13:12:30.317] [background] [info] Marking all folders as `busy`
> 6624 [2019-12-26 13:12:30.320] [background] [info] Syncing folder list...
> 6624 [2019-12-26 13:12:31.241] [background] [info] Syncing folder list...
> 6624 [2019-12-26 13:12:31.915] [foreground] [info] syncFolderUIDRange for INBOX, UIDs: 8420 - 8715, Heavy: false
> 6624 [2019-12-26 13:12:32.143] [foreground] [info] - remote=101, local=101
> 6624 [2019-12-26 13:12:32.156] [foreground] [info] Idling on folder INBOX
> 6624 [2019-12-26 13:12:32.453] [background] [info] Sync loop deleting unlinked messages with phase 2.
> 6624 [2019-12-26 13:12:32.454] [background] [info] Sync loop complete.
> 6624 [2019-12-26 13:12:44.319] [metadataExpiration] [info] Scanning for expired metadata
> 6624 [2019-12-26 13:12:44.319] [metadataExpiration] [info] -- Sending expiration event for Message UXEpWD2qzq8eYiUAoUAasVLrRnmpx7Cuo49gYsxtp
> 6624 [2019-12-26 13:12:44.320] [metadataExpiration] [info] -- Will wake for next expiration in 7200sec
> 6624 [2019-12-26 13:12:47.263] [calContacts] [critical]  *** Stack trace:
>  ***   raise
>  ***   abort
>  ***   terminate
>  ***   _is_exception_typeof
>  ***   _is_exception_typeof
>  ***   RtlInterlockedCompareExchange64
>  ***   RtlInterlockedCompareExchange64
>  ***   KiUserExceptionDispatcher
>  ***   _CxxThrowException
>  ***

The full log can be found [here](https://github.com/Foundry376/Mailspring/files/4002596/logs.zip).

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

It only occurs with my university's email service, which uses Outlook (Office 365). Given the exception occurs with calContacts, it may be to do with the global address list?

##### Is the issue reproducible with a particular attachment, message, signature, etc?

It doesn't seem so, but this issue exists across different operating systems and seems related to the configuration of my university's email service.

**Comment by Kataera** [comment] 2020-01-15 11:05
Bumping this, still having problems.

**Comment by dragosnec** [comment] 2020-01-15 17:01
I have the same issue with a couple of email accounts hosted on a2hosting. Here's the log excerpt

> 10688 [2020-01-16 00:16:47.285] [background] [warning] [SLOW] Transaction=insertMessage > 60ms (65236 microseconds, 11 waiting to aquire)
10688 [2020-01-16 00:16:47.345] [background] [warning] [SLOW] Transaction=insertMessage > 60ms (60088 microseconds, 13 waiting to aquire)
10688 [2020-01-16 00:16:47.765] [background] [warning] [SLOW] Transaction=insertMessage > 60ms (318639 microseconds, 35 waiting to aquire)
10688 [2020-01-16 00:16:47.924] [calContacts] [critical]  *** Stack trace:
 ***   raise
 ***   abort
 ***   terminate
 ***   _is_exception_typeof
 ***   _is_exception_typeof
 ***   RtlInterlockedCompareExchange64
 ***   RtlInterlockedCompareExchange64
 ***   KiUserExceptionDispatcher
 ***   _CxxThrowException
 ***

The server has SRV entries for caldav

> _caldav._tcp.uwconepeace.net. | 14400 | IN | SRV | Priority: 0 Weight: 0 Port: 2079 Target: sg1-lr2.supercp.com
_caldavs._tcp.uwconepeace.net. | 14400 | IN | SRV | Priority: 0 Weight: 0 Port: 2080 Target: sg1-lr2.supercp.com 
_carddav._tcp.uwconepeace.net. | 14400 | IN | SRV | Priority: 0 Weight: 0 Port: 2079 Target: sg1-lr2.supercp.com
_carddavs._tcp.uwconepeace.net. | 14400 | IN | SRV | Priority: 0 Weight: 0 Port: 2080 Target: sg1-lr2.supercp.com

As impressed as I am with the way Mailspring is put together this is a show stopper for me. Will wait for this to get addressed and give it another shot.

**Comment by Kataera** [comment] 2020-05-13 15:55
Hi, it's been several months since I opened this issue. I still have the same problem on version 1.7.6. Any insights would be appreciated; the log from the issue occuring in 1.7.6 can be seen below:

> Mailspring Version: 1.7.6-e94bb759
> Platform: win32
> Account State: sync_error
> Account Provider: office365
> IMAP Server: outlook.office365.com
> SMTP Server: smtp.office365.com
> --------------------------------------------
> 15792 [2020-05-13 16:48:56.181] [background] [info] syncFolderUIDRange for Outbox, UIDs: 1 - 414, Heavy: false
> 15792 [2020-05-13 16:48:56.254] [background] [info] - remote=0, local=0
> 15792 [2020-05-13 16:48:56.291] [background] [info] syncFolderUIDRange for RSS Feeds, UIDs: 1 - 1, Heavy: false
> 15792 [2020-05-13 16:48:56.362] [background] [info] - remote=0, local=0
> 15792 [2020-05-13 16:48:56.398] [background] [info] syncFolderUIDRange for Sync Issues, UIDs: 1 - 1, Heavy: false
> 15792 [2020-05-13 16:48:56.471] [background] [info] - remote=0, local=0
> 15792 [2020-05-13 16:48:56.506] [background] [info] syncFolderUIDRange for Sync Issues/Conflicts, UIDs: 1 - 2, Heavy: false
> 15792 [2020-05-13 16:48:56.577] [background] [info] - remote=0, local=0
> 15792 [2020-05-13 16:48:56.612] [background] [info] syncFolderUIDRange for Sync Issues/Local Failures, UIDs: 1 - 1, Heavy: false
> 15792 [2020-05-13 16:48:56.689] [background] [info] - remote=0, local=0
> 15792 [2020-05-13 16:48:56.725] [background] [info] syncFolderUIDRange for Sync Issues/Server Failures, UIDs: 1 - 1, Heavy: false
> 15792 [2020-05-13 16:48:56.798] [background] [info] - remote=0, local=0
> 15792 [2020-05-13 16:48:56.837] [background] [info] syncFolderUIDRange for Tasks, UIDs: 1 - 69, Heavy: false
> 15792 [2020-05-13 16:48:56.971] [background] [info] - remote=1, local=1
> 15792 [2020-05-13 16:48:56.972] [background] [info] Sync loop deleting unlinked messages with phase 2.
> 15792 [2020-05-13 16:48:56.973] [background] [info] Sync loop complete.
> 15792 [2020-05-13 16:49:04.365] [main] [info] [local-fd8d036e-a357] Running ChangeUnreadTask performLocal:
> 15792 [2020-05-13 16:49:04.369] [main] [info] [local-fd8d036e-a357] -- Succeeded. Changing status to `remote`
> 15792 [2020-05-13 16:49:04.706] [foreground] [info] Idle exited with code 0
> 15792 [2020-05-13 16:49:04.708] [foreground] [info] [local-fd8d036e-a357] Running ChangeUnreadTask performRemote:
> 15792 [2020-05-13 16:49:04.811] [foreground] [info] [local-fd8d036e-a357] -- Succeeded. Changing status to `complete`
> 15792 [2020-05-13 16:49:04.845] [foreground] [info] syncFolderUIDRange for INBOX, UIDs: 10851 - 11161, Heavy: false
> 15792 [2020-05-13 16:49:04.907] [foreground] [info] - remote=101, local=101
> 15792 [2020-05-13 16:49:04.924] [foreground] [info] Idling on folder INBOX
> 15792 [2020-05-13 16:49:05.116] [metadataExpiration] [info] Scanning for expired metadata
> 15792 [2020-05-13 16:49:05.116] [metadataExpiration] [info] -- Sending expiration event for Message UXEpWD2qzq8eYiUAoUAasVLrRnmpx7Cuo49gYsxtp
> 15792 [2020-05-13 16:49:05.117] [metadataExpiration] [info] -- Will wake for next expiration in 7200sec
> 15792 [2020-05-13 16:49:08.644] [calContacts] [critical]  *** Stack trace:
>  ***   raise
>  ***   abort
>  ***   terminate
>  ***   _is_exception_typeof
>  ***   _is_exception_typeof
>  ***   RtlInterlockedCompareExchange64
>  ***   RtlInterlockedCompareExchange64
>  ***   KiUserExceptionDispatcher
>  ***   _CxxThrowException
>  ***

**Comment by CodeMouse92** [comment] 2021-01-18 19:25
Thank you for your patience on this issue! I know it's frustrating when you cannot connect to your email with Mailspring.

2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be a duplicate of one we've already migrated to Discourse:

https://community.getmailspring.com/t/institutional-office365-not-working/48

Please consider joining that community and continuing the discussion there.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-18 19:25 UTC
Labels: audit
