### ISSUE TITLE
Feature Request: Go to the next unread message through all folders

### ISSUE THREAD

**Issue by panter-dsd** [Foundry376/Mailspring#2026] opened 2020-05-27 04:35 UTC
**Is your feature request related to a problem? Please describe.**
I have a lot of folders and as the Mailspring doesn't support saving filters or smart folders I have to manually go through all subfolders with unread items. It's very uncomfortable.

**Describe the solution you'd like**
I propose to add the button (with hotkey of course) "Next unread" which should open the next unread item even it is in another folder.

**Describe alternatives you've considered**
I didn't find any alternative.

**Comment by CodeMouse92** [comment] 2021-03-02 00:44
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/go-to-the-next-unread-message-through-all-folders/906

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@panter-dsd: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 00:44 UTC
Labels: audit, enhancement
