### ISSUE TITLE
Line quoting doesn't work in Thunderbird on emails sent by Mailspring

### ISSUE THREAD

**Issue by rykr** [Foundry376/Mailspring#831] opened 2018-04-17 14:30 UTC
When I reply emails and do inline replies, then the line quoting that Thunderbird  does doesn't work.  I'm not sure if it's using a different character set or what.

**Comment by essafik** [comment] 2019-10-14 09:21
This might be related to the issue I am having with inline replies. When I reply to the first email then the inline reply quoting works but as soon as I get a reply to that same email and try to reply to it then the inline reply doesn't work as expected. What I mean by this is that nested inline replies don't work at all. I have this issue both on Windows 10 and Ubuntu. I tried using Thunderbird and it doesn't have this issue.

**Comment by CodeMouse92** [comment] 2021-02-11 19:15
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/quoted-text-not-folded/570

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@essafik: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-11 19:15 UTC
Labels: audit
