### ISSUE TITLE
[Feature Request] View & Disable Plugins

### ISSUE THREAD

**Issue by patrickheeney** [Foundry376/Mailspring#42] opened 2017-10-06 02:33 UTC
##### What operating system are you using?
Mac OSX

##### What version of Mailspring are you using?
1.0.1

--

**Bug?**
##### Is the issue reproducible with a particular attachment, message, signature, etc?

The ability to disable plugins is missing that previously existed in Nylas. I don't need the translations, quick replies, tracking features, etc. 

Code found here: https://github.com/nylas/nylas-mail/tree/master/packages/client-app/internal_packages/plugins

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment] 2017-10-06 05:19
Hey! Great to hear from you @patrickheeney — yep, the code is definitely still in there, just needs to be cleaned up and turned back on. The plan is to drastically revamp the old "plugins" page so you can browse and install themes and plugins within the app. Stay tuned!

**Comment by CodeMouse92** [comment] 2021-01-29 21:09
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/plugin-theme-catalog/318

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-29 21:09 UTC
Labels: audit, enhancement
