### ISSUE TITLE
Mails in the trash with message "There is one more message in this thread that is not in spam or trash."

### ISSUE THREAD

**Issue by rafrsr** [Foundry376/Mailspring#820] opened 2018-04-09 20:01 UTC
##### What operating system are you using?
Ubuntu 17.10

##### What version of Mailspring are you using?
v1.2.1

**Bug?**
##### Is the issue reproducible with a particular attachment, message, signature, etc?

Get any message in the inbox and click on "reply" ![image](https://user-images.githubusercontent.com/7094012/38519672-9e5fc13e-3c0e-11e8-9fb5-8cb4ef5395ae.png), now leave the reply as is, don`t delete. Move to the folder "Draft" and delete the last draft, should be the empty reply. Now you can view a message in the trash with the subject of the original inbox email but with the following message.
> There is one more message in this thread that is not in spam or trash.

**Comment by rafrsr** [comment] 2019-01-09 16:33
@bengotow in the latest version (1.5.5) I still have this problem. Each time I delete an answer to another email that I will never send; I can see the original message in the trash folder. Right now I have hundreds of emails in the trash folder, however empty the trash does not remove these messages

All messages in the trash say:

> There is one more message in this thread that is not in spam or trash.

**Comment by CodeMouse92** [comment] 2021-02-03 18:52
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/mails-persist-in-the-trash-after-emptying-the-trash-or-the-junk/447

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-03 18:52 UTC
Labels: audit
