### ISSUE TITLE
Mailspring is spawning extra [Gmail]/Sent Mail folder on Gmail

### ISSUE THREAD

**Issue by palefire19** [Foundry376/Mailspring#355] opened 2017-11-20 17:48 UTC
##### Are there any related issues?

...

##### What operating system are you using?
10.13.1

##### What version of Mailspring are you using?
1.0.8

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?

See screenshot from Gmail web app

<img width="196" alt="screen shot 2017-11-20 at 7 15 45 pm" src="https://user-images.githubusercontent.com/4412269/33032969-e77ed920-ce33-11e7-867b-0e706f847279.png">

**Comment by jaydub200** [comment] 2017-11-21 00:09
Replicated here as well.

**Comment by bengotow** [comment] 2017-11-25 20:40
Hey—thanks for reporting this. Can you go to the Preferences > Folders screen and see if both Sent Mail folders appear in this dropdown? Mailspring /shouldn't/ create a second sent mail folder (it only explicitly creates that `Mailspring/Snoozed` label—I'm wondering if Gmail isn't exposing your existing one via IMAP maybe?

<img width="598" alt="image" src="https://user-images.githubusercontent.com/1037212/33234555-37cbb0d0-d229-11e7-99d0-d9d0c57d151c.png">

**Comment by palefire19** [comment] 2017-11-26 07:22
Ben, followed your instructions. Here's the screenshot of what I see.
<img width="631" alt="screen shot 2017-11-26 at 10 19 58 am" src="https://user-images.githubusercontent.com/4412269/33237973-af92ad2a-d293-11e7-9465-003388ad0f6f.png">

**Comment by bengotow** [comment] 2017-11-27 10:31
Hmm that's really interesting–it looks like Gmail isn't reporting two Sent Mail folders, only one... could you try going to Gmail's preferences / settings and under Folders see if your second sent folder has "Enable in IMAP" checked?

**Comment by jaydub200** [comment] 2017-11-27 11:03
Hi Ben,

Unfortunately, I deleted the additional folder, so am unable to check why it was created.

I can confirm that it hasn't happened since, although to be honest I haven't used Mailspring very much as I downloaded it to see how it compared to my preferred mail app, Postbox.

From my perspective, it just appears to have been a one off incident.

Like Palefire I only see one sent folder in my folder preferences, but that is expected as I have already deleted the second sent folder.

I can also confirm that my Gmail sent folder is definitely set to "enable in IMAP". I'd spot it pretty quickly in Postbox, if it wasn't.

Thanks,
Jon

**Comment by palefire19** [comment] 2017-11-27 12:01
Hi Ben - Here's what my Gmail settings looks like:

<img width="1326" alt="screen shot 2017-11-27 at 2 59 12 pm" src="https://user-images.githubusercontent.com/4412269/33265693-afd67956-d383-11e7-83c9-4893e17a6066.png">

**Comment by jaydub200** [comment] 2017-11-28 01:02
Hi Ben,

I have just used Mailspring to send a message this evening and it has created a {Gmail}/sent folder (see screenshot) of view seen in Gmail

![screen shot 2017-11-28 at 00 54 36](https://user-images.githubusercontent.com/33849107/33297205-aca06e46-d3d7-11e7-914c-8dcd07de6cc9.png)

Thanks,

Jon

**Comment by jaydub200** [comment] 2017-11-28 11:55
Having sent a few more mails from Mailspring this morning, it appears that Mailspring is labelling replies to emails with [Gmail]/Sent Mail, but new emails are not labelled in this way.  All sent emails in [Gmail]/Sent are in the normal Sent folder as well.

At the risk of going off topic, where does Mailspring store its draft mails?  Although the mapping says [Gmail]/Drafts, the drafts are not visible there in the Drafts folder from within Gmail itself.

**Comment by sprakash81** [comment] 2018-01-03 01:57
I'm having same issue, seeing [gmail]/Sent Mail.

**Comment by nelas** [comment] 2018-01-03 10:05
I'm also experiencing this in `Version 1.0.12-cf081332`. Mailspring creates an extra label `[GMail]/Sent Mail` for sent messages, as well as `[Gmail]/Starred` for starred messages. All my system labels are marked as `Show in IMAP` in GMail. They appear like this in Mailspring Folders settings:

![mailspringfolders](https://user-images.githubusercontent.com/361179/34516050-710fad32-f075-11e7-899c-266f4f332825.png)

Any suggestions on how to debug?

**Comment by pateljj04** [comment] 2018-01-24 19:05
I am having the same issue, I have Send to show in imap, and it doesn't show up under sent. It creates a new [Gmail]/Send Mail label.

**Comment by l00kanio** [comment] 2018-02-20 23:18
Are using more than 1 gmail account and set up with different display languages? I had one in English (US) and  second one in Polish. Unified then (switched both to US), deleted needles labels ([Gmail]/...) and now it works as exacted.

**Comment by pateljj04** [comment] 2018-02-21 00:43
Nope, just one account with English US. Although I did notice today that if I create the email from Mailspring it adds the [Gmail]/Send label, at the same time also shows up under Send Items. Very odd...

**Comment by jaydub200** [comment] 2018-02-21 08:53
I have two gmail accounts connected to Mailspring, both English (UK).

Mine was behaving exactly as Jigar describes.  If you send an email from
Mailspring it adds the[Gmail]/Sent label, but also shows up under Sent
Items.

However I have just retested this and it has sent an email without creating
the [Gmail]/Sent folder/label.


On 21 February 2018 at 00:43:37, Jigar Patel (notifications@github.com)
wrote:

Nope, just one account with English US. Although I did notice today that if
I create the email from Mailspring it adds the [Gmail]/Send label, at the
same time also shows up under Send Items. Very odd...

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Foundry376/Mailspring/issues/355#issuecomment-367173601>,
or mute the thread

**Comment by Chrismarsh** [comment] 2019-05-29 21:52
@bengotow I'm seeing this with 1.6.1 across all platforms

**Comment by bengotow** [comment] 2019-06-17 05:39
hey folks—thanks for reporting this. It looks as though Gmail's behavior changed slightly, and a workaround I added to prevent thread labels from being lost when replies were sent was causing EXTRA [Gmail]/Sent and Gmail/[Drafts] labels to be applied. It's fixed by a4676d730d01ac132accf2463e94fdb78eebe10c. Stay tuned!

**Comment by bengotow** [comment] 2019-07-04 13:59
Hey folks! This should be addressed in the latest release (1.6.3) that shipped earlier this week. The app should auto-update on it's own, or you can grab the new version from the releases page: https://github.com/Foundry376/Mailspring/releases/. Thanks for filing this - enjoy the update!

**Closed by bengotow** 2019-07-04 13:59 UTC
Labels: bug, done-pending-release, needs-reproduction
