### ISSUE TITLE
Feature Request: Use popout composer for all emails

### ISSUE THREAD

**Issue by katonash** [Foundry376/Mailspring#608] opened 2018-01-31 16:14 UTC
Allow me to set a default so all new drafts and replies use the "pop out compose" style window instead of inline.

Does this feature exist in another mail client or tool you use?

None that I've used, but some (gmail web, mailbird) allow you to popout by using shift+r, shift+a, shift+c

**Comment by ngurney** [comment] 2018-02-01 16:52
I second this! I used to use Spark which did this. 

It would also love to have an option like the latest version of Apple Mail that will open the new message in split screen when in fullscreen view

**Comment by svleeuwen** [comment] 2018-11-20 17:40
This would be really useful. Currently with a long thread in the inline composer, when you click the show more (three dots) button, the 'Send' button (and other controls) move all the way down. This results in a lot of scrolling. 

The popout composer has these controls fixed to the bottom, so they're always visible.

**Comment by lonewolf1870** [comment] 2019-07-02 08:39
> I second this! I used to use Spark which did this.
> 
> It would also love to have an option like the latest version of Apple Mail that will open the new message in split screen when in fullscreen view

I also would love to a solution similar to the Apple Mail one

**Comment by CodeMouse92** [comment] 2021-02-24 22:06
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/use-popout-composer-for-all-emails/771

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@katonash @ngurney @sverhagen: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-24 22:06 UTC
Labels: audit, composer, enhancement
