### ISSUE TITLE
[Feature Request] "Edit as new" next to "Reply" and "Forward"

### ISSUE THREAD

**Issue by gmagic** [Foundry376/Mailspring#622] opened 2018-02-02 14:42 UTC
##### Feature request

I liked such feature in Thunderbird where i could make a copy of mail content instead of replying or forwarding it and send it as new mail.

Thanks in advance!

**Comment by gmagic** [comment] 2019-10-15 06:26
Hey, guys! Will this feature be included in the future releases?
Easy one but useful. Still need sometimes use Thunderbird or Evolution to send income email as new one.

**Comment by bflorat** [comment] 2020-06-11 21:23
This is very important to me as well...

**Comment by samtuke** [comment] 2020-07-20 14:56
Still missing this feature every other day

**Comment by CodeMouse92** [comment] 2021-02-04 18:37
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/edit-as-new-message-resend-email-to-another-recipient/456

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@gmagic: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-04 18:37 UTC
Labels: audit, enhancement
