### ISSUE TITLE
"Scanning Messages" (Syncing) Never Completes

### ISSUE THREAD

**Issue by lots0logs** [Foundry376/Mailspring#1335] opened 2019-01-25 03:50 UTC
I already reached out via your support form but haven't received a response so I'm trying my luck here. I added two accounts to Mailspring. My main account never finishes scanning messages and it doesn't appear to be making any progress no matter how much time goes by. The secondary account I added finished scanning without any issue. I've attached the log file. I hope you can help me to resolve the issue.

##### Are there any related issues?
#1327 (possibly, but it's a different error message in the logs)

##### What operating system are you using?
Linux (Arch)

##### What version of Mailspring are you using?
1.5.5 --Side Note: would be great if it was possible to copy the version from the app's UI

--

**Bug?**

##### Is this an email sync or connection issue?
Yes and I have to say the error message in the log is quite useless. Need more context to know how to resolve whatever the problem is. 

* [mailsync-30b67434.log.zip](https://github.com/Foundry376/Mailspring/files/2794567/mailsync-30b67434.log.zip)

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Outlook.com

##### Is the issue reproducible with a particular attachment, message, signature, etc?
N/A

**Comment by bengotow** [comment] 2019-03-29 22:16
Hey! Thanks for reporting this - sorry for the delay. It looks like Mailspring is asking for detailed headers of 3042 messages and the server is returning an unexpected error. It's possible that Outlook is rejecting this request because that's too large a set of messages, but I don't think I've seen this before. I'm going to try to recreate this and I'll keep you posted.

**Comment by csi-lk** [comment] 2019-04-17 09:58
Am having the same issue, seems to be random, also can't seem to open the logs to see what the issue is :/

**Comment by ivnilv** [comment] 2019-04-22 15:06
Same here... also experiencing this and need to often Rebuild Caches in order for the app to see new mail and start working properly.

But the "Scanning messages" message never disappears..

**Comment by rsankuratri** [comment] 2019-05-22 10:00
I am also having to rebuild the cache for my iCloud, Outlook and Gmail accounts everytime for the messages to show up correctly in the inbox.

**Comment by erodriguezv** [comment] 2019-06-14 16:11
I have the same zero percent issue as @ahoodnick (only for my icloud account). 
I am using an app speific password and I tried configuring from both icloud and manual imap/smtp. same result.

**Comment by SamTebbs33** [comment] 2019-08-06 08:11
Is there any word on this? I'm also facing this. @bengotow

**Comment by montowniastron** [comment] 2019-10-06 10:19
I have the same problem... unistall program...

**Comment by silkyclouds** [comment] 2019-10-18 12:15
same problem here using latest version of mailspring, mac os catalina. 

![image](https://user-images.githubusercontent.com/23377067/67093316-a3230f00-f1b1-11e9-81f1-eabaa59fc9b4.png)

![image](https://user-images.githubusercontent.com/23377067/67093345-b3d38500-f1b1-11e9-9d60-b4728cc3ad1e.png)


it's in this state for like 6 hours now. I cannot use it in this state...uninstalling as well. 

Please let us know when this will be fixed.

**Comment by espenfl** [comment] 2019-10-25 18:11
I also see the same issue. Using DavMail as a backend and IMAP.

**Comment by vagrod** [comment] 2019-11-06 13:06
Same on Ubuntu 19.10 with DavMail. DavMail logs say that everything is OK (OK UID FETCH COMPLETED), tons of (Downloaded full message content for IMAP) messages in log, but Mailspring is still "Scanning" and seems like it is repeating same requests to DavMail over and over again. No errors or even warnings anywhere.

**Comment by vagrod** [comment] 2019-11-06 14:00
Here is my Mailspring log for this DavMail account: [https://pastebin.com/WJKZib8E](url)
DavMail log: [https://pastebin.com/wmHGd7Kn](url)

**Comment by k4ch0** [comment] 2019-11-06 21:18
Same issue here, how I can get some logs to upload them here??

**Comment by vagrod** [comment] 2019-11-06 21:23
In Mailspring I went to Developer -> Open Mailspring Logs.
In DavMail it is Show Logs (or Open Logs) in the only menu on an main window.
Be careful and not leak any sensitive information which can be contained in these logs.

**Comment by k4ch0** [comment] 2019-11-06 22:24
I put some logs on https://pastebin.com/QCdvVNqA, but I noticed a recurrent error:

451 [2019-11-06 15:42:44.993] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID (heavy)","key":"ErrorFetch","retryable":true,"what":"std::exception"}

**Comment by kurisu-gh** [comment] 2019-12-28 02:55
Argh... this is frustrating. I stopped using Mailspring for a while but I have been following the thread in https://github.com/Foundry376/Mailspring/issues/304 and saw that people had success fixing the disappearing mail problem by rebuilding the cache. Thought to give Mailspring another try and I now I have this forever "scanning messages..." problem.

My recent logs while experiencing the problem are here: https://pastebin.com/UgFR49jn

Similar to @k4ch0, I also have a similar recurrent error:
```
[background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID (heavy)","key":"ErrorFetch","retryable":true,"what":"Unknown exception"}
```
```
[background] [info] Sleeping after exception: {"debuginfo":"syncFoldersAndLabels - fetchAllFolders","key":"ErrorConnection","retryable":true,"what":"Unknown exception"}
```

**Comment by comisso** [comment] 2020-02-04 09:22
Same problem here, Office365 and MacOS.

**Comment by nickhenshall** [comment] 2020-04-06 11:21
Same here, G Suite and Windows 10.

**Comment by BinaryPaean** [comment] 2020-04-21 23:25
Happening on 1.7.5, running on Ubuntu, connecting to Office365

```log
170561 [2020-04-21 16:24:50.259] [background] [info] Sync loop deleting unlinked messages with phase 2.
170561 [2020-04-21 16:24:50.269] [background] [info] Sync loop complete.
170561 [2020-04-21 16:24:50.270] [background] [info] Syncing folder list...
170561 [2020-04-21 16:24:50.865] [background] [info] syncFolderUIDRange for Sent Items, UIDs: 1 - 0, Heavy: false
170561 [2020-04-21 16:24:51.546] [background] [info] - remote=9419, local=5904
170561 [2020-04-21 16:24:51.580] [background] [info] - Fetching full headers for 3515 (of 3515 needed)
170561 [2020-04-21 16:24:51.618] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID (heavy)","key":"ErrorFetch","retryable":true,"what":"std::exception"}

**Comment by BinaryPaean** [comment] 2020-04-25 06:39
Still occurring with 1.7.6; same log as above.

**Comment by kurisu-gh** [comment] 2020-04-25 06:43
> Hey! Thanks for reporting this - sorry for the delay. It looks like Mailspring is asking for detailed headers of 3042 messages and the server is returning an unexpected error. It's possible that Outlook is rejecting this request because that's too large a set of messages, but I don't think I've seen this before. I'm going to try to recreate this and I'll keep you posted.

@bengotow has there been any update on this?

**Comment by mp1994** [comment] 2020-05-21 10:38
Same here on Ubuntu 18.04 LTS and Office365. I am running the newest version (1.7.7) released today. I have to say that I get most of my e-mail but sometimes I have to quit and re-launch the app because it won't sync, no matter what I do.
In the log message, I often get these lines:

> *** Mailspring Sync 
*** An exception occurred during program execution: 
*** {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID (heavy)","key":"ErrorFetch","retryable":true,"what":"std::exception"}

I hope this can be solved!

**Comment by david-sitsky** [comment] 2020-06-04 00:21
I see the same issue on Ubuntu 18.04 and Office365.  I reset my cache, restarted and still see this:
```
8182 [2020-06-04 10:19:58.032] [metadata] [info] Metadata delta stream starting...
8182 [2020-06-04 10:20:00.031] [background] [info] Marking all folders as `busy`
8182 [2020-06-04 10:20:00.032] [background] [info] Syncing folder list...
8182 [2020-06-04 10:20:13.028] [metadataExpiration] [info] Scanning for expired metadata
8182 [2020-06-04 10:20:13.028] [metadataExpiration] [info] -- Will wake for next expiration in 7200sec
8182 [2020-06-04 10:20:14.209] [background] [critical] 
***
*** Mailspring Sync 
*** An exception occurred during program execution: 
*** {"debuginfo":"syncFoldersAndLabels - fetchAllFolders","key":"ErrorNamespace","retryable":false,"what":"std::exception"}
***
```
I like the program and would donate, but this is pretty much a non-starter until this is fixed.

**Comment by alphonse** [comment] 2020-06-16 23:26
I had similar issues syncing my Office365 account in Mailspring via DavMail (IMAP) on OSX 10.14 and 10.15 and Pop!_OS 20.04.  I was always able to sync some folders, but eventually the process would fail.  Example from the log file:

       Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID (heavy)","key":"ErrorParse","retryable":true,"what":"std::exception"}

It's only Office365 that has this problem  -- syncing has always worked great with my Gmail account.

I tried various solutions I'd seen online with no luck.  Finally I turned on the "Enable KeepAlive" option in DavMail and it fixed the issue.  Syncing works fine on all my machines now.

@bengotow: For what it's worth, I've tried a number of other email clients (Thunderbird, Postbox, Airmail) for the same account going through DavMail on the same machines and Mailspring is the only one that's ever had this issue.  Hoping this helps find the cause.

**Comment by brianabouchard** [comment] 2020-06-17 21:09
Same issue on MacOS 10.14.6 trying to sync Office 365 account. Exception appears to occur after attempting to sync "Calendar" folder.

**Comment by EugenMayer** [comment] 2020-06-18 18:45
Got the same issue against our Zimbra (latest version) server using (obv.) IMAP.

Evolution, KMail, Mail(OSX) and Spark (OSX) as well as Gmail (Android) are working just fine.

Running Mailspring 1.7.8-13 under latest Majaro KDE 20

**Comment by jackchealdang** [comment] 2020-06-25 21:28
Can confirm I have the same issue with my Office365 email using DavMail. I'm running Arch Linux and Mailspring 1.7.8-13635bcf.

**Comment by j-applese3d** [comment] 2020-06-30 17:12
Same issue here. I tried setting `davmail.enableKeepAlive=true` as @alphonse mentions, but I still have the same issue.
I'm using EWS via davmail on Ubuntu 20.04.

Log:
```
10356 [2020-06-30 09:55:10.586] [foreground] [info] syncFolderUIDRange for INBOX, UIDs: 34422 - 34665, Heavy: false
10356 [2020-06-30 09:55:10.638] [foreground] [info] - remote=101, local=101
10356 [2020-06-30 09:55:10.684] [foreground] [info] Connection does not support idling. Locking until more to do...
10356 [2020-06-30 09:56:07.066] [background] [critical] 
***
*** Mailspring Sync 
*** An exception occurred during program execution: 
*** {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID","key":"ErrorParse","retryable":true,"what":"std::exception"}
***

10356 [2020-06-30 09:56:07.066] [background] [info] --sleeping
10356 [2020-06-30 09:58:07.067] [background] [info] Marking all folders as `busy`
10356 [2020-06-30 09:58:07.095] [background] [info] Syncing folder list...
10356 [2020-06-30 09:58:19.171] [background] [info] syncFolderUIDRange for INBOX, UIDs: 1 - 3885, Heavy: true
10356 [2020-06-30 10:00:06.577] [background] [critical] 
***
*** Mailspring Sync 
*** An exception occurred during program execution: 
*** {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID","key":"ErrorParse","retryable":true,"what":"std::exception"}
***
```

**Comment by TristanK27** [comment] 2020-07-06 11:06
I have the same problem, this time I waited a little longer and this resulted in another error with a stack trace:
I am using an office365 account through manually setting the imap settings in combination with davmail.
![image](https://user-images.githubusercontent.com/20356336/86587137-65f1ed80-bf89-11ea-80a1-05bde2e460d8.png)

**Comment by CodeMouse92** [comment] 2021-01-28 03:29
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/the-eternal-sync-bug/334

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 03:29 UTC
Labels: audit
