### ISSUE TITLE
Pre 1.6 tray icon looked better on KDE

### ISSUE THREAD

**Issue by tobias-kuendig** [Foundry376/Mailspring#1422] opened 2019-03-18 16:35 UTC
I'm running KDE Neon. The new tray icon looks too big and out of place. The old icon looked fine on KDE.

![image](https://user-images.githubusercontent.com/8600029/54546533-325e0f00-49a4-11e9-808e-5356f183aa2d.png)

**Comment by bengotow** [comment] 2019-03-18 18:17
Hey! Ahh man here we go - it seems that there is no good solution to this. On Ubuntu the old icon (16x16) was pixelated and blurry, and it appears that some platforms like KDE Neon can't scale down the image (?!) so now it appears too large.

@arkraft do you have any thoughts on how we could handle this? I honestly don't know too much about the Linux ecosystem except what I've learned maintaining Mailspring. Can we detect which distro the user is on and just start using different icon sizes?

**Comment by harm0nic** [comment] 2019-03-18 18:27
For whatever it's worth, it looks better for me now on Ubuntu 18.10 gnome.

Also, perhaps `os.release()` [https://nodejs.org/api/os.html](https://nodejs.org/api/os.html) might help narrow down specific linux distros? Never used before so cannot confirm, though.

**Comment by shrestaz** [comment] 2019-03-18 22:34
+1 here. Tray icon before upgrading to 1.6.0 was fine. Looks very same to @tobias-kuendig's issue.

@harm0nic It's got to do with Desktop Environment, more than Linux distro. I'm running Antergos with KDE.

Before:
![screenshot_20190227_220313](https://user-images.githubusercontent.com/9460504/53522812-7ebbda80-3adb-11e9-97f2-dcdbe82d885f.png)

After:
![Screenshot_20190318_233415](https://user-images.githubusercontent.com/9460504/54568121-59353900-49d6-11e9-84fd-de1cb5e471ee.png)

**Comment by vtruong68** [comment] 2019-03-19 05:00
Exact same issue on Manjaro KDE. Seems like a problem for KDE users.

**Comment by habl** [comment] 2019-03-19 09:29
With default KDE plasma theme even worse, white on white ;)

![Screenshot_20190319_102758](https://user-images.githubusercontent.com/2447111/54594848-c5915600-4a31-11e9-97df-4e44b5dc1533.png)

**Comment by arkraft** [comment] 2019-03-19 09:40
@bengotow We could detect the current DE by using the `DESKTOP_SESSION` environment variable. There is also the `XDG_CURRENT_DESKTOP` environment variable, but this is only for X11 i believe and with Wayland coming up it would be safe to use the first one. 

I thought the icon size is managed by electron itself, but it seems to only work on OSX as there are also HiDPI versions of the icon in the directory.

@habl It was also white on the pre 1.6 release, there is also an issue for that (#884)  The problem here is to detect the color of the panel because there is no gloabl setting for a theme variant and there are light themes using a dark tray.

**Comment by Funeoz** [comment] 2019-03-19 17:02
@arkraft This is a good solution. And for now, this workaround is good for X11 because Wayland and KDE aren't two things that play very well together so this isn't a problem.

**Comment by arkraft** [comment] 2019-03-20 06:23
Could someone using KDE tell me what the output of `echo $DESKTOP_SESSION` and `echo $XDG_CURRENT_DESKTOP`is? I am not sure if its "plasma" or "kde".

**Comment by tobias-kuendig** [comment] 2019-03-20 06:52
@arkraft 

```
$ echo $DESKTOP_SESSION
/usr/share/xsessions/plasma

$ echo $XDG_CURRENT_DESKTOP
KDE

$ lsb_release -a
No LSB modules are available.
Distributor ID: neon
Description:    KDE neon User Edition 5.15
Release:        18.04
Codename:       bionic
```

**Comment by arkraft** [comment] 2019-03-20 07:21
Thanks! Will try to get it ready this week

**Comment by Bugsbane** [comment] 2019-03-26 02:29
This might have to do with screen resolution as well or something. I'm running KDE on Kubuntu, and while it still looks a bit large for my tastes, it looks a lot better on mine than on thjose screenshots above:

![Screenshot_20190325_222815](https://user-images.githubusercontent.com/401733/54967242-4928d680-4f4d-11e9-93d9-071c50bf2a4c.png)

```
echo $DESKTOP_SESSION
plasma

echo $XDG_CURRENT_DESKTOP
KDE

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.10
Release:        18.10
Codename:       cosmic

```

**Comment by tobias-kuendig** [comment] 2019-03-26 07:06
Good thinking! Unfortunately, I'm seeing the same (too large) icon when running on 1920x1080 and 3840x2160 (I did not reboot, just changed the resolution on-the-fly).

**Comment by Bugsbane** [comment] 2019-03-27 13:19
@tobias-kuendig Interesting... I'm on 1920x1080, too, so it's not screen resolution, and it's not all KDE installations... I wonder if it could be down to the version of KDE libs (libplasma)?

**Comment by IevgenSobko** [comment] 2019-04-04 12:07
As a workaround, you can set `/usr/bin/env XDG_CURRENT_DESKTOP=Unity` in the desktop file.
If you have mailspring in autostart applications you will also need to add the same to autostart line.
![2019-04-04_15-04](https://user-images.githubusercontent.com/14232100/55554228-f12b6600-56ea-11e9-9961-e72a2993bfef.png)

**Comment by Funeoz** [comment] 2019-04-04 15:49
> As a workaround, you can set `/usr/bin/env XDG_CURRENT_DESKTOP=Unity` in the desktop file.
> If you have mailspring in autostart applications you will also need to add the same to autostart line.
> ![2019-04-04_15-04](https://user-images.githubusercontent.com/14232100/55554228-f12b6600-56ea-11e9-9961-e72a2993bfef.png)

Where did you put this line? I can't figure out how to do that.

**Comment by IevgenSobko** [comment] 2019-04-04 15:57
For autostart:
![2019-04-04__18-50-44](https://user-images.githubusercontent.com/14232100/55569883-03b59780-570b-11e9-8588-0819437898cd.png)
![2019-04-04__18-51-20](https://user-images.githubusercontent.com/14232100/55569884-044e2e00-570b-11e9-86d6-9eaf7d774185.png)
For general system if you are using installers edit desktop file
`sudo vim /usr/share/applications/mailspring.desktop`
![2019-04-04__18-53-17](https://user-images.githubusercontent.com/14232100/55569948-23e55680-570b-11e9-998e-93a9c28b5f5b.png)

**Comment by Funeoz** [comment] 2019-04-04 16:01
Thanks ! It worked.

**Comment by tobias-kuendig** [comment] 2019-04-05 05:25
Can confirm this bug as fixed in 1.6.1 :+1:

**Comment by arkraft** [comment] 2019-04-05 05:57
There is something about the try icon in KDE in the electron change log: https://electronjs.org/releases/stable#release-notes-for-v412

> Fixed issue on KDE where tray icons would be displayed incorrectly as a 22x22 version of the provided tray image but cropped from the center. #17497

Could it be that this solved the problem?

**Comment by omerfarukdogan** [comment] 2020-05-24 14:19
This issue seems to be solved, you may want to close it @bengotow.

**Comment by theGeekyLad** [comment] 2021-01-01 13:13
This is how it looks on my updated Arch machine. :crying_cat_face: Anything specific package that I maybe missing out on?

![image](https://user-images.githubusercontent.com/15625446/103439216-00916780-4c61-11eb-8d93-d1a80ff84946.png)

**Comment by CodeMouse92** [comment] 2021-01-28 18:56
It appears that this issue has been resolved, so we are closing it. If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).

@theGeekyLad That looks like a separate issue. Mind reporting it on [Discourse](https://community.getmailspring.com) under Bug Reports?

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 18:56 UTC
Labels: audit, linux
