### ISSUE TITLE
Copy & Paste destroys the sentence pattern

### ISSUE THREAD

**Issue by PrzemekSkw** [Foundry376/Mailspring#545] opened 2018-01-19 11:50 UTC
When I copy messege from one recived email and paste it to new email (or to empty file) everything is spread into additional rows. For example sentence in recived email looks that:
"Witam uprzejmie,
poniżej oferta na 2 transformatory energetyczne olejowe, jakie posiadamy w sprzedaży"

when paste looks like that:
"Witam uprzejmie,
          
          poniżej
            oferta na 2 transformatory energetyczne olejowe, jakie
            posiadamy w sprzedaży:"

**Comment by dialed** [comment] 2018-05-16 02:39
Love Mailspring but this is true for me as well. 

As a result of email bodies disappearing and questionable spellcheck, I often compose an email in another application like Microsoft Word or TextEdit using rich text. When pasting back to mailspring the structure gets totally blown away. 

Also when pasting to mailspring the structure of of bullets and outlines doesn't stick and have to be entirely recreated within the app.

Thanks for all the hard work.

**Comment by b00f** [comment] 2018-08-16 05:14
The Ctrl+x/Ctrl+c/Ctrl+v shortcuts for cut/copy and paste don't work for me. I have ubuntu 18.04

**Comment by gmagic** [comment] 2019-10-15 06:30
Yeap. Need to solve copy-paste formatting issue.

**Comment by CodeMouse92** [comment] 2021-01-30 01:51
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/copy-paste-destroys-the-sentence-pattern/396

Please consider joining that community and continuing the discussion there!

@PrzemekSkw @dialed: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-30 01:51 UTC
Labels: audit
