### ISSUE TITLE
Copy and paste out of composer loses all formatting, for certain destinations

### ISSUE THREAD

**Issue by jerm** [Foundry376/Mailspring#1183] opened 2018-10-27 17:24 UTC
##### Are there any related issues?
Possibly related: https://github.com/Foundry376/Mailspring/issues/545

They mention pasting into composer, my issue concerns copying out of composer.

##### What operating system are you using?

OSX High Sierra

##### What version of Mailspring are you using?

1.5.1-da141eaf, but this has been present for a while

**Bug?**

I'll sometimes compose something in mailspring and then decide to save/send it elsewhere, ie: slack, vim. 

When doing so, all formatting, including line breaks, disappears. Interestingly, this works fine for some destinations: ie:  gmail, Paper, but other destinations, like this form, vim, slack, etc., this text:

```
This is a test

foo


goo

loo
```

ends up as:

`This is a testfoogooloo`

Pasting into ie: gmail, which works, and then re-selecting it from there, yields the desired results when going into vim, slack, etc.

I totally understand fancier formatting not always translating well, but I feel like basic paragraph structure should translate/transfer well.

**Comment by remokon** [comment] 2019-02-04 11:43
I second this on my Ubuntu 18.04 laptop.
Copy pasting loses all formatting and squeezes every `\n` to `''`.
I also support the idea of working on the structure first as it's much more important than bold or italic.

Thanks :+1:

**Comment by cake808** [comment] 2019-06-14 12:04
I have the same Issues on Arch Linux, it's quite inconvenient :/

`Version 1.6.1-aceed8e5`

**Comment by gmagic** [comment] 2019-10-15 06:28
The same issue.
Copy-paste formatted text makes lose formatting in mailspring composer!

**Comment by imperator-maximus** [comment] 2020-09-12 13:19
Copy & paste is a big mess in Mailspring (Ubuntu 20.04, Mailspring 1.7.8.05) and I encouter is several times a day:
- loosing line breaks (workaround copy & paste via keyboard shortcuts)
- does not work at all

a show stopper.

I am close to move to Windows now (coming from MacOS) because all mail clients are terrible on Linux and this was the most promising one.

**Comment by torqueing** [comment] 2020-09-16 11:43
This is still a MASSIVE problem. Is there a fix?

**Comment by CodeMouse92** [comment] 2021-02-18 23:32
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/copy-and-paste-out-of-composer-loses-all-formatting-for-certain-destinations/701

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@jerm @remokon @cake808 @imperator-maximus: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-18 23:32 UTC
Labels: audit
