### ISSUE TITLE
Bug: Copy HTML with color blackground changes to a light color

### ISSUE THREAD

**Issue by brandon-mosqueda** [Foundry376/Mailspring#2175] opened 2020-10-21 17:33 UTC
I usually compose emails with programming code that I copy from Visual Studio Code as HTML but no matter what the background color is it always is changed to the same color of mailspring background code utility, and depending the font color It is hard to read. In other applications when I paste code copied from Visual Studio Code in HTML format they also respects the indentation levels, in mailspring composer all tabs or spaces at the beginning of the lines are trimed.

**To Reproduce**
1. Copy as HTML text with background color from somewhere (Visual Studio Code for example)
2. Compose a message
3. Paste it

**Screenshots**
For example, this is the original code that I copy from Visual Studio Code:
![Screenshot from 2020-10-21 12-23-32](https://user-images.githubusercontent.com/45582024/96756083-2b298f00-1399-11eb-8cab-703c62ab7eb7.png)

This is how it looks like in Mailspring when it's copied:
![Screenshot from 2020-10-21 12-23-18](https://user-images.githubusercontent.com/45582024/96756132-3ed4f580-1399-11eb-9e6f-748d513d55fa.png)

And this is how it looks like when copied in Thunderbird:
![Screenshot from 2020-10-21 12-28-49](https://user-images.githubusercontent.com/45582024/96756180-53b18900-1399-11eb-8fab-003350f51a78.png)

**Setup: (please complete the following information):**
 - OS: Solus OS (Linux)
 - OS Version 4.1 Fortitude
 - Mailspring Version: ex: 1.7.8

**Comment by CodeMouse92** [comment] 2021-03-03 03:30
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/copy-html-with-color-background-changes-to-a-light-color/961

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@brandon-mosqueda: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-03 03:30 UTC
Labels: audit, bug
