### ISSUE TITLE
Failed to load config.json

### ISSUE THREAD

**Issue by GiacomoSilli** [Foundry376/Mailspring#1752] opened 2020-01-01 21:56 UTC
I can no longer open the client.
I use windows 10
<img width="273" alt="mailspring" src="https://user-images.githubusercontent.com/22368271/71646492-e2112d00-2ce9-11ea-87ba-b78470ac3f28.png">

**Comment by paulocoghi** [comment] 2020-02-11 16:36
Hello (Ciao!) Giacomo!

Other users already reported this issue [here](https://github.com/Foundry376/Mailspring/issues/463), and we are waiting to some of the community's devs to look into it.

**Comment by CodeMouse92** [comment] 2021-01-29 21:51
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/regression-avoid-corruption-of-config-json-on-unexpected-shutdown/386

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-29 21:51 UTC
Labels: audit
