### ISSUE TITLE
Bug: Editing drafts in popout composer causes thread view to scroll

### ISSUE THREAD

**Issue by jmanuel1** [Foundry376/Mailspring#2158] opened 2020-10-02 08:02 UTC
**Describe the bug**
When editing a draft in the pop-out composer, pausing any edits for a few seconds causes the thread view in the main window to scroll down to the draft. Same behavior occurs even when the entire thread is popped out.

This bug happens when my edits to a draft are synced to the view of the draft in the other window.

**To Reproduce**
1. Select any single thread.
2. Start a reply to a message in that thread.
3. Switch to the pop-out composer for your reply.
4. Scroll to elsewhere in the thread where you can't see the thread in the main window.
5. Type some text in the message area of the pop-out composer.
6. Wait a few seconds.
7. _View of thread in main window scrolls to where the draft is._

Reproduction steps for the case where the pop-out thread view is scrolled are similar. Just pop-out the thread, then edit your draft and wait, and similar behavior will occur.

**Expected behavior**
Edits to the draft do not cause the scroll position to change drastically in other windows. Sometimes I want to consult previous emails in a thread while writing a reply, and having to repeatedly scroll to past messages feels so inefficient.

**Screenshots**
Here's a [screencast](https://recordit.co/c992Up5wsW) of me using the pop-out composer and pop-out thread window to reproduce the bug.

**Setup: (please complete the following information):**
 - OS: Windows
 - OS Version: Windows 10 Education Version 2004, build 19041.388, Windows Feature Experience Pack 120.2202.130.0
 - Mailspring Version: `1.7.8-13635bcf`

**Additional context** 

This not particular to any of the accounts of email services that I use, as far as I can tell.

**Comment by jylertones** [comment] 2020-11-12 16:59
I see the same behavior in Linux, mailspring 1.7.8

**Comment by CodeMouse92** [comment] 2021-03-03 03:12
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/editing-drafts-in-popout-composer-causes-thread-view-to-scroll/955

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@jmanuel1 @jylertones: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-03 03:12 UTC
Labels: audit, bug
