### ISSUE TITLE
wsod with disroot.org

### ISSUE THREAD

**Issue by schapira** [Foundry376/Mailspring#1859] opened 2020-03-12 06:37 UTC
can't connect to [disroot.org mail](https://disroot.org/en/services/email), 
![image](https://user-images.githubusercontent.com/203137/76493975-917e2480-643c-11ea-91b4-bce1ff1a9185.png)
after entering details got just WSOD.

**Comment by CodeMouse92** [comment] 2021-01-30 02:21
Thank you for your patience on this issue! I know it's frustrating when you cannot connect to your email with Mailspring. 2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

@schapira: Can you please confirm that this is still broken with 1.8.0, and if so, open a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

Understand, I'm asking you rather than migrating it myself, because we will need your help to diagnose this and test the fix.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-30 02:21 UTC
Labels: audit
