### ISSUE TITLE
RTL problem in the subject section. Version 1.7.2

### ISSUE THREAD

**Issue by imanmoghimiq30** [Foundry376/Mailspring#1761] opened 2020-01-09 10:01 UTC
Hello
I have a problem with Mailspring and I think it can be a bug. In the subject section, Mailspring doesn't support RTL but in the compose area, it's ok and doesn't have any problem. 
Thank for your attention
![mailspring bug](https://user-images.githubusercontent.com/33248902/72056833-96aae000-32e2-11ea-81f2-0c59ca92c843.jpg)

**Comment by CodeMouse92** [comment] 2021-02-23 21:36
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/rtl-problem-in-the-subject-section/741

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@imanmoghimiq30: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-23 21:36 UTC
Labels: audit, bug, intl
