### ISSUE TITLE
Feature Request: Mailspring takes a lot of time to open in Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by jrmejiaa** [Foundry376/Mailspring#1940] opened 2020-04-26 01:10 UTC
I have been a Mailspring user for a while and I was working with Mailspring in Linux Mint 18.0 for a long time. I had a problem with this system but it was related to the graphical environment (Cinnamon), but because of the sooner unsupported version, I decide to try again Ubuntu with their last LTS version. I have made some test of performance (time tracker) of how much time requires Mailspring to open up for the first time and I am sure that it takes more than the double of time compare with the Linux Mint 18.0 version. Besides Mailspring app does not recognize the theme of my pointer and takes a default (ugly) pointer theme. 

I know that those problems are not so heavy compare with some other issues. However, if you can improve the performance for the new Ubuntu LTS version, I believe that you are going to improve a lot of distributions as well. 

I am working with the last stable version available in SNAP. I give you also some details about the RAM/CPU performance of my machine, if you want to work in this feature and you need data from my machine, I will help you with whatever you want. 

[Performance RAM/CPU in a Ubuntu 20.04 machine](https://i.imgur.com/Oz1gbPY.png)

Thanks for your time

**Comment by castrojo** [comment] 2021-01-24 01:15
Using lzo compression in the snap instead of xz will probably help this a bunch: 

- https://snapcraft.io/blog/snap-speed-improvements-with-new-compression-algorithm
- https://forum.snapcraft.io/t/how-to-switch-your-snap-to-use-lzo-compression/21714

**Comment by CodeMouse92** [comment] 2021-01-26 20:41
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mailspring-takes-a-lot-of-time-to-open-in-ubuntu-20-04-lts/273

Please consider joining that community and continuing the discussion there!

@jrmejiaa and @castrojo : if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-26 20:41 UTC
Labels: audit, enhancement
