### ISSUE TITLE
Feature Request: Navigate back and forth through history using cmd + [/]

### ISSUE THREAD

**Issue by gvteja** [Foundry376/Mailspring#2029] opened 2020-05-28 13:17 UTC
**Is your feature request related to a problem? Please describe.**
I frequently switch between inbox view and a label view. Everytime I want to switch, I'm forced to use a mouse since navigation to labels is not possible with a keyboard. Within Gmail, I could have accomplished the same thing in two ways:
1. Use the browser back and forth using cmd + [ or cmd + ]
2. Use `g l` keyboard shortcut to type my label and `g i` to go to inbox.

**Describe the solution you'd like**
Typing cmd + [ should go back to the previous view pane.

**Describe alternatives you've considered**
Switching to a new label seems to be impossible without a mouse

**Comment by CodeMouse92** [comment] 2021-03-02 00:48
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/navigate-back-and-forth-through-history-using-cmd/908

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@gvteja: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 00:48 UTC
Labels: audit, enhancement
