### ISSUE TITLE
Bug: Translations never do anything with the API always returning an empty string

### ISSUE THREAD

**Issue by robclancy** [Foundry376/Mailspring#2161] opened 2020-10-06 20:41 UTC
**Describe the bug**
Whenever I click translate email it just does nothing. I opened dev tools and the result is always empty. Using manjaro linux through a snap, which I thought might be missing something, so moved to using a package compiled using the AUR and it still has the same issue.

**To Reproduce**
1. Go to any Spanish written email
2. Click translate to English
3. No result

**Expected behavior**
It translates and replaces text.

**Setup: (please complete the following information):**
 - OS: Linux 5.8.11-1-MANJARO x86_64 20.1 Mikah
 - Mailspring Version: AUR and Snap both 1.7.8

**Additional context** 
This hasn't worked since installing weeks ago. I have searched issues and not seen this come up for anyone else. But since I can inspect the network request and see that it just returns an empty result it must be an issue for everyone.

### Here is a full request from devtools

**Request URL:** https://id.getmailspring.com/api/translate
**Request Method:** POST
**Status Code:** 200 OK
**Remote Address:** 107.20.76.229:443

**Response Headers**
```
HTTP/1.1 200 OK
cache-control: no-cache
content-encoding: gzip
content-type: application/json; charset=utf-8
Date: Tue, 06 Oct 2020 20:37:35 GMT
vary: accept-encoding
transfer-encoding: chunked
Connection: keep-alive
```

**Request Headers**
```
POST /api/translate HTTP/1.1
Host: id.getmailspring.com
Connection: keep-alive
Content-Length: 80
accept: application/json
Origin: null
authorization: Basic [secret]
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Mailspring/1.7.8 Chrome/69.0.3497.128 Electron/4.2.2 Safari/537.36
content-type: application/json
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US
```

**Request Payload**
```json
{
  "lang":"en",
  "text":"<b>Gracias Rodrigo, </b><b>Cuidensee </b>",
  "format":"html"
}
```

**Response**
```json
{"result":""}
```

**Comment by robclancy** [comment] 2020-10-06 20:42
Actually is related to this issue, I thought it was talking about the automatic translations (since it says pro) when I first read it.
https://github.com/Foundry376/Mailspring/issues/2157

**Comment by robclancy** [comment] 2020-10-26 20:02
So I guess this project isn't actively maintained. Thank god I was trying it out before paying.

**Comment by maneandrea** [comment] 2020-11-18 11:01
I have the same issue. However, as per [this question](https://github.com/Foundry376/Mailspring/issues/2200) it seems that the development team is indeed taking a break from this project. That's unfortunate.

**Comment by CodeMouse92** [comment] 2021-01-25 22:04
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. Learn more about the changes here.

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/translations-never-do-anything-with-the-api-always-returning-an-empty-string/255/3

Please consider joining that community and continuing the discussion there!

@robclancy: if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

We're locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. In fact, I'm leaving the task open because it should be addressed in an upcoming release.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed** 2021-02-04 23:54 UTC
Labels: bug, migrated
