### ISSUE TITLE
Bug: backspace not functioning when composing email

### ISSUE THREAD

**Issue by ivarsauce** [Foundry376/Mailspring#1911] opened 2020-04-17 09:27 UTC
**Describe the bug**
When composing email, the backspace stops functioning and can't delete any characters. After that can't select any text, any clicks will jump the text cursor to the beginning of the text and type from there.
Persists until app restart.

**To Reproduce**
No clear idea. Sometimes doesn't happen for two days, sometimes happens twice in two minutes.
I have a suspicion that it triggers on using diacritical signs (ī, ā, ū and such), but can't really test it.
Edit: it just happened five times in a row and now I'm pretty certain that it happens when trying to type a diacritical signs, it fails, types a regular letter (e instead of expected ē, for example) and then the backspace is disabled.

**Setup:**
 - OS: macOS
 - OS Version 10.15.4
 - Mailspring Version: ex: 1.7..4

**Additional context** 
A real deal-breaker of a bug.

**Comment by bengotow** [comment] 2020-04-22 15:23
Hey thanks for reporting this—really crazy this is happening on macOS. I think you're probably right that this has to do with the input method for diatrics, I'll see if I can reproduce this soon.

**Comment by multivac61** [comment] 2020-04-26 12:17
I am experiencing the same exact issue when composing mail using diacritical signs (I'm writing in Icelandic). More specifically the compose window hangs if the diacritical sign is not followed by a letter that can have a diacritical sign, e.g., q.

I am able to keep composing If I close the compose window and open a new one. That is I am not forced to restart the app, but this is nonetheless really annoying.

**Comment by ivarsauce** [comment] 2020-12-09 17:11
Update on this:  it seems to be happening way less frequently. Also, an app restart is no longer neccessary - just trying to type another diacritical removes the problem.
No longer a deal-breaker problem, but unpleasant nonetheless.

**Comment by CodeMouse92** [comment] 2021-02-27 03:19
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/backspace-not-functioning-when-composing-email/855

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@ivarsauce @multivac61: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-27 03:19 UTC
Labels: audit, bug
