### ISSUE TITLE
Fastmail: App passwords are always rejected.

### ISSUE THREAD

**Issue by WhyNotHugo** [Foundry376/Mailspring#2217] opened 2020-12-03 19:18 UTC
**Describe the bug**

After hitting #2216, I generated an IMAP password for fastmail, but my credentials are always rejected.

**To Reproduce**
1. Open mailspring.
2. Log into a mailspring account.
3. Select fastmail as a provider.
4. Visit Fastmail.
5. Generate an app password (IMAP, read-only: false).
6. Provide that password to mailspring.

** Actual behaviour **

The password is rejected. I've generated it a few times, and both copy-pasted and manually typed, just to make sure there's not dumb issues like that.

The log file provided says (there's some weird encoding issues in the file, but I don't think that's relevant):

```
----------IMAP----------
connect <mailcore::IMAPSession:0x7fff2cf29e10>
* OK IMAP4 ready
ssl connect imap.fastmail.com 993 2
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
1 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 LITERAL+ ENABLE UIDPLUS SASL-IR NAMESPACE CONDSTORE SORT LIST-EXTENDED QRESYNC MOVE SPECIAL-USE CREATE-SPECIAL-USE IDLE AUTH=PLAIN
1 OK completed
connect ok
login
2 LOGIN "hugo@barrera.io" *********
2 NO Incorrect username or password.
```

**Expected behavior**

App password should work

**Screenshots**

![2020-12-03T20:17:14,921244986+01:00](https://user-images.githubusercontent.com/730811/101077067-2f51ea80-359c-11eb-946f-deda46cd1f1d.png)
![2020-12-03T20:17:20,450193690+01:00](https://user-images.githubusercontent.com/730811/101077071-2fea8100-359c-11eb-8ba9-eb77df844bd0.png)

**Setup: (please complete the following information):**
 - OS: ArchLinux
 - Mailspring Version: 1.7.8-13635bcf

**Comment by robclancy** [comment] 2020-12-04 00:22
All my existing accounts are now failing. Pretty sure this company is just dead.

**Comment by WhyNotHugo** [comment] 2020-12-04 07:56
By "this company", do you mean Fastmail or Mailspring?

**Comment by robclancy** [comment] 2020-12-04 07:58
Mailspring. I use gmail through it. However it seems to be working again. Either way if it doesn't work for you still then you're out of luck because this client appears to be dead. https://github.com/Foundry376/Mailspring/issues/2200

**Comment by WhyNotHugo** [comment] 2020-12-04 09:55
Gee, that's very sad. Thanks for the news.

**Comment by valentt** [comment] 2020-12-16 11:09
Check my bug: https://github.com/Foundry376/Mailspring/issues/2231

This is a dead project and dead product unfortunately, and we need to find an alternative. Any suggestions?

**Comment by WhyNotHugo** [comment] 2020-12-16 12:06
I'm using Thunderbird. It's not perfect, but it's the best there is.

**Comment by CodeMouse92** [comment] 2020-12-18 15:56
@WhyNotHugo Unfortunately, @valentt spoke out of turn. The project and product are NOT dead. The maintainer responded to his issue. There was a server issue.

Mailspring is alive and well!

**Comment by WhyNotHugo** [comment] 2020-12-18 16:22
@CodeMouse92 Thanks for the heads up.

The UX comments are still relevant, and the bug is still persistent.

**Comment by CodeMouse92** [comment] 2021-01-17 05:27
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/fastmail-app-passwords-are-always-rejected/65/1

Please consider joining that community and continuing the discussion there! Bonus: if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

Also, rest assured that Mailspring development is once again active and underway.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-17 05:27 UTC
Labels: audit, bug
