### ISSUE TITLE
Bug: Mailspring will no longer open

### ISSUE THREAD

**Issue by Mycheze** [Foundry376/Mailspring#2242] opened 2020-12-28 20:22 UTC
**Describe the bug**
A clear and concise description of what the bug is. Does it happen with all email accounts, or only a particular account and/or email message?

Not sure why, but I can no longer open Mailspring. It just never launches. I also couldn't install from the .deb file from the website.

**To Reproduce**
1. Open Mailspring as usual
2. Doesn't work

**Expected behavior**
I expected the app to open and let me view my emails.

**Screenshots**

**Setup: (please complete the following information):**

 - OS: Pop OS
 - OS Version: 20.10
 - Mailspring Version: Everything is up to date (according to snap), but I can't see the exact version because I can't open the menu

**Additional context** 

This is what I get when I try to launch Mailspring from the terminal:
/snap/mailspring/488/bin/desktop-launch: line 51: /home/user/.config/user-dirs.dirs: Permission denied
Gtk-Message: Failed to load module "appmenu-gtk-module"

I also tried (sudo apt-get install appmenu-gtk2-module appmenu-gtk3-module) and everything there is also up to date.

Non of my googling was effective or showed me anything that actually helped.

**Comment by fcastilloec** [comment] 2020-12-28 22:31
I think that your problem has nothing to do with the Gtk message you see. Many of us also see that message and there's no problem. The real problem is that you can't access your configuration directory.
Because you installed Mailspring using a snap package, the permission of that package might be wrong, or you need to install Mailspring using the `--classic` flag (which might not helped).

I think your best bet would be to install Mailspring using the `.deb` file rather than `snap`. Nonetheless, this bug should be looked at, especially if other people are having the same problem.

**Comment by Mycheze** [comment] 2020-12-29 17:29
I didn't think the Gtk thing was an issue, but I decided to include it anyway.

Using --classic didn't seem to do anything either.

I already tried to use the .deb file, but it said the "Installation Failed" (The following packages have unmet dependencies:
  mailspring: Depends: gvfs-bin but it is not installable).
  
  I tried googling those issues too but didn't find anything useful.
  
  Should I maybe purge the snap version or something?

**Comment by CodeMouse92** [comment] 2021-01-17 04:37
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this conversation to Discourse:

https://community.getmailspring.com/t/mailspring-will-no-longer-open/62

Please consider joining that community and continuing the discussion there! Bonus: if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

@Mycheze and @fcastilloec, I've taken special effort to preserve your posts separately in the thread, so they can be reassigned to you. Please continue the conversation there.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

**Closed by CodeMouse92** 2021-01-17 04:37 UTC
Labels: audit, bug
