### ISSUE TITLE
Unable to file sent mail automatically to my archive

### ISSUE THREAD

**Issue by couling** [Foundry376/Mailspring#1706] opened 2019-11-12 10:02 UTC
Operating system: Ubuntu
Bug

Not sure whether to class this is as a bug or feature request.  It appears to be a problem with an existing feature so I'll say "bug".

I want to archive all emails to the same place.  Specifically I want my "sent mail" to be archived in the "Archive".  This is simple enough in other mail clients.  There's even a tick box option for it in evolution.

However in mailspring, it seems the drop downs for Inbox/Sent/Drafts/Spam/Archive/Trash are all mutually exclusive.  You can't have the same send folder as Archive.  When I set my sent mail to my archive directory the "Archive" drop down is set blank.

**Comment by CodeMouse92** [comment] 2021-02-08 19:32
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/allow-same-folder-for-sent-and-archive/499

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@couling: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-08 19:32 UTC
Labels: audit
