### ISSUE TITLE
Windows Live Mail Not Able To Send After Update

### ISSUE THREAD

**Issue by vb543** [Foundry376/Mailspring#2008] opened 2020-05-22 15:43 UTC
Hello,

Since updating to the latest version of Mailspring, I am unable to send mail via my @live.com address. I get a 'Authentication error' when sending. Incoming works just fine and I've already re-connected my account with no luck. 

##### What operating system are you using?

Windows 10

##### What version of Mailspring are you using?

1.7.7

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Happens every time I try to send email.

**Comment by karolz-ms** [comment] 2020-05-22 18:19
Probably a dupe of https://github.com/Foundry376/Mailspring/issues/1996

**Comment by bengotow** [comment] 2020-05-24 22:11
Hey folks, thanks for reporting this - going to merge this into #1996. The fix has landed in master and I'll be shipping it soon!

**Closed by bengotow** 2020-05-24 22:11 UTC
Labels: mailserver-incompatibility, needs-reproduction
