### ISSUE TITLE
IMAP Syncing Issues.

### ISSUE THREAD

**Issue by hickscorp** [Foundry376/Mailspring#1693] opened 2019-10-30 16:50 UTC
Note that before opening this one I found similar issues but they were all closed.

I added an IMAP account to MailSpring a long time ago and everything was working great. Recently, I've been experiencing problems syncing:

![image](https://user-images.githubusercontent.com/822933/67879476-f774aa00-fb34-11e9-8c22-89a590544f4c.png)

What is very odd is the fact that I seem to receive emails, but sending them don't work (The SMTP settings seem to be fine).

Our email provider is Gandi and their setup instructions can be [found here](https://docs.gandi.net/en/gandimail/standard_email_settings/).

I've tried toggling the dev tools but appart from several `Sync worker sent non-JSON formatted message` logs, I don't see any warning nor errors. I've also tried to ignore insecure SSL in case the certs were expired but it didn't help.

Note that on my using GMail as my client it works fine - and my coworkers using Mac / Windows and their own choice of clients don't have the problem on mailboxes also provided by Gandi.

Also, when trying to change the settings, this is what I see:

![image](https://user-images.githubusercontent.com/822933/67880024-db253d00-fb35-11e9-824f-4b2ba9348c66.png)

**Comment by CodeMouse92** [comment] 2021-02-01 19:17
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/crash-on-sync-no-stack-trace/419

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-01 19:17 UTC
Labels: audit
