### ISSUE TITLE
long messages - "popout" option - links open in "popout" not browser

### ISSUE THREAD

**Issue by xplreitr** [Foundry376/Mailspring#1326] opened 2019-01-17 19:33 UTC
Based on an improvement in 1.5.4, long emails are clipped. You can open them in their entirity in a popout window. However, if you click on any links in the 'popout' window it open the links in the 'popout' rather than in a browser. Without any navigation abilities in the popout window, you just have to close the window and reopen the long message again. 

##### Are there any related issues?

version 1.5.4 had the following improvement 

"Extremely long messages now clip in the message panel and a "popout" option allows you to view their entire text in a separate window, similar to Gmail. This allows Mailspring to more reliably maintain good performance as you browse your email." 

##### What operating system are you using?

Ubuntu 18.04

##### What version of Mailspring are you using?

v 1.5.5-b7939d38

--

**Bug?**

##### Is this an email sync or connection issue?

no

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

no

##### Is the issue reproducible with a particular attachment, message, signature, etc?

The specific long email holds too much private information to post, but the issue should be replicated by any email sufficiently long that holds a link 

Email is too long and truncated.
![s1](https://user-images.githubusercontent.com/32180339/51336846-d24df980-1a42-11e9-8ad1-91dd3300136e.png)

Popout window opens complete window. 
![s2](https://user-images.githubusercontent.com/32180339/51336845-d24df980-1a42-11e9-863d-2d1a2e2bf1c8.png)

Selecting a link opens the link in the popout window rather than a browser window
![s3](https://user-images.githubusercontent.com/32180339/51336844-d24df980-1a42-11e9-8c16-0864a14ca110.png)

...

--

**Feature Request?**
N/A

...

**Comment by CodeMouse92** [comment] 2021-02-10 21:36
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://github.com/Foundry376/Mailspring/issues/1326

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-10 21:36 UTC
Labels: audit
