### ISSUE TITLE
Bug: Mailspring becomes unresponsive when installing a plugin

### ISSUE THREAD

**Issue by jmanuel1** [Foundry376/Mailspring#2170] opened 2020-10-18 20:56 UTC
**Describe the bug**

When I install a plugin through the Developer menu, Mailspring becomes unresponsive to typing and clicks until the "Plugin installed! 🎉" dialog appears. At that point, I can dismiss the dialog, and Mailspring is responsive again.

**To Reproduce**

1. Go to the hamburger menu
2. Click on "Developer"
3. Click on "Install a Plugin..."
4. Choose a directory with a plugin in it
5. _Mailspring freezes until plugin is installed_

**Expected behavior**

I should be able to use Mailspring while a plugin is installing.

**Screenshots**

Here's a sequence of screenshots demonstrating the issue.

* Installing a plugin
![image](https://user-images.githubusercontent.com/7255867/96385510-4605c480-1149-11eb-98fd-25467d6f447d.png)
![image](https://user-images.githubusercontent.com/7255867/96385522-54ec7700-1149-11eb-80a1-b1ba567b534b.png)
![image](https://user-images.githubusercontent.com/7255867/96385525-5c138500-1149-11eb-9ad9-55505f4ee4a5.png)
* Mailspring stops responding
![image](https://user-images.githubusercontent.com/7255867/96385535-6766b080-1149-11eb-874c-4c950c7bfdeb.png)
* Plugin installation finishes
![image](https://user-images.githubusercontent.com/7255867/96385538-7188af00-1149-11eb-83da-708e13d1de1f.png)
* Mailspring is responsive (I can select text)
![image](https://user-images.githubusercontent.com/7255867/96385550-7d747100-1149-11eb-902f-dbba502c1cae.png)

**Setup: (please complete the following information):**
 - OS: Windows
 - OS Version Windows 10 Education Version 2004, build 19041.388, Windows Feature Experience Pack 120.2202.130.0
 - Mailspring Version: 1.7.8-13635bcf

**Additional context** 

This is not related to a particular email provider.

I am unsure of the cause of the issue, but it would seem that plugin directories are copied *synchronously* during plugin installation. I imagine this might cause problems when there's a large `node_modules/` folder inside a plugin. Relevant code: https://github.com/Foundry376/Mailspring/blob/052f6dd5fe51a0ebddc19d3f8afc54237440dff9/app/src/package-manager.ts#L186

**Comment by CodeMouse92** [comment] 2021-03-03 03:19
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mailspring-becomes-unresponsive-when-installing-a-plugin/957

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@jmanuel1: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-03 03:19 UTC
Labels: audit, bug
