### ISSUE TITLE
Bug: contact birthdays without a year appears as invalid

### ISSUE THREAD

**Issue by asparc** [Foundry376/Mailspring#2018] opened 2020-05-25 15:14 UTC
**Describe the bug**
In the contacts window, the birthday of contacts is shown. Google Contacts allows to specify a birthday without a year. Mailspring displays such birthday as `Invalid Date`, which is undesirable. It should just display the birthday without the year.

**Setup:**
 - OS: Ubuntu 20.04
 - Mailspring Version: 1.7.8

**Comment by CodeMouse92** [comment] 2021-03-02 00:35
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/contact-birthdays-without-a-year-appears-as-invalid/902

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 00:35 UTC
Labels: audit, bug
