### ISSUE TITLE
Bug: poczta.onet.pl mailbox does not sync

### ISSUE THREAD

**Issue by Herbata-Sys** [Foundry376/Mailspring#1849] opened 2020-03-08 15:44 UTC
##### What is the behavior you're seeing?
Accounts from poczta.onet.pl mailbox does correct sync only for the first time. After first time sync it scanning forever and nothing happens.
##### What email provider (Gmail, Exchange, etc.) are you trying to use?
poczta.onet.pl
##### What operating system are you using?
Arch linux
##### What version of Mailspring are you using?
1.7.2
#### IMAP
- Server: imap.poczta.onet.pl
- Port: 993
- Security: SSL/TSL
#### SMTP
- Server: smtp.poczta.onet.pl
- Port: 465
- Security: SSL/TSL

**Comment by CodeMouse92** [comment] 2021-02-12 22:30
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/the-eternal-sync-bug/334

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-12 22:30 UTC
Labels: audit, mailserver-incompatibility, needs-reproduction
