### ISSUE TITLE
Copy-pasting out of the composer into plaintext editor does not preserve formatting (line-feed characters, indentation, etc.)

### ISSUE THREAD

**Issue by johnyradio** [Foundry376/Mailspring#1457] opened 2019-04-06 22:52 UTC
hi, these are major defects, which damage productivity and make this mail client unusable for serious business. To me, these pervasive text issues in Mailspring indicate a core flaw in your text-handling model. Until that core flaw is fixed, Mailspring will continue to suffer unacceptable bugs. 

Simply copying and pasting text from emails to or from Mailspring reveals the defects. Affects both received mails, and outgoing mails in compose-mode. 

Here, a line-feed is hidden in the text, revealed by copying from mailspring compose window into notepad. 

Highlight text in composer:
![mailsp-hidden-1](https://user-images.githubusercontent.com/6564280/55676184-f40d8e80-5883-11e9-86b3-cffbf6a0db0c.png)

Copy:
![mailsp-hidden-2](https://user-images.githubusercontent.com/6564280/55676185-f40d8e80-5883-11e9-8639-a3f76ab73513.png)

Paste in plain-text editor:
![mailsp-hidden-3](https://user-images.githubusercontent.com/6564280/55676186-f40d8e80-5883-11e9-81d4-a841d3c8fca1.png)

Hidden line-feed revealed:
![mailsp-hidden-4](https://user-images.githubusercontent.com/6564280/55676187-f40d8e80-5883-11e9-90a8-61d3235212f2.png)

**Comment by bengotow** [comment] 2019-05-26 21:46
Hey! Hmm, this is an interesting one - do you remember if you pasted that text into the composer to create the line-feed in the first place?

I think that there are probably quite a few of these type of issues because Mailspring composes and sends HTML email, not plaintext email. The plaintext appearance of it (when you paste it into notepad and it's rendered as text and not as HTML) may or may not be the same, but the recipient of the email should see exactly what you see in Mailspring as long as their email app supports HTML (basically everyone except the "BATS" client on Linux).

I think that this particular one is caused by line feed characters not being converted to paragraph blocks by the SlateJS editor we use, but it seems low priority? I don't think copy-pasting from Mailspring's text editor into notepad and having formatting be preserved is a behavior we care about much and I'm fairly certain indentation, nested lists, etc. will all look different.

**Comment by bengotow** [comment] 2019-05-26 21:48
Going to rename this and we can see if we can collect similar issues here.

**Comment by johnyradio** [comment] 2019-05-27 00:08
I don't recall the details. As I recall, linefeed breaks.

I don't want formatting to be preserved, cuz there is no formatting. Trying
to paste plain text from notepad.

I don't consider linefeed to be "formatting".

For me, this sort of thing is a top priority.


Thx!

**Comment by bengotow** [comment] 2019-06-11 00:39
Hey! Just a heads up, I took a look at this today and it turns out the text editing library Mailspring uses now has a plaintext exporter! (I just finished upgrading it for the next release and it's also gotten considerably faster, which is great.) This should be fixed in the next release - stay tuned!

**Comment by bengotow** [comment] 2019-07-04 13:57
Hey folks! This should be addressed in the latest release (1.6.3) that shipped earlier this week. The app should auto-update on it's own, or you can grab the new version from the releases page: https://github.com/Foundry376/Mailspring/releases/. Thanks for filing this - enjoy the update!

**Closed by bengotow** 2019-07-04 13:57 UTC
Labels: composer, done-pending-release
