### ISSUE TITLE
[Feature Request] Ability to compact message list while using Two Panel layout

### ISSUE THREAD

**Issue by mph-code** [Foundry376/Mailspring#1350] opened 2019-02-02 21:53 UTC
In the message list/pane, there is quite a bit of excess space (when using Reading Pane mode). I would like the ability to compact the message list while in reading pane mode. Essentially, I would just like to be able to see more emails at once while in reading panel mode (the way you are able to in single panel mode). This could be accomplished either via sacrificing the message contents completely or just reducing the height of each email (or both). I believe this would be the view to use for ultimate productivity. 

Also, is this something that could be accomplished with a custom theme? Any assistance is appreciated. Thanks!

Cheers!

**Comment by bengotow** [comment] 2019-03-17 16:57
Hey @IAmMateo! You should be able to do this actually if you move the divider so that the left panel is wider, like this. I think right now it switches at 550px, and we should probably just make this a preference instead.

<img width="1769" alt="image" src="https://user-images.githubusercontent.com/1037212/54494764-fee38d80-489a-11e9-9a4c-81e83e30f744.png">

**Comment by CodeMouse92** [comment] 2021-02-18 01:24
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/hide-show-compact-left-panel-account-folders-pane/688

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@mph-code: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-18 01:24 UTC
Labels: audit, enhancement, product-direction
