### ISSUE TITLE
Bug: Sent date always showing Dec 31, 1969

### ISSUE THREAD

**Issue by akanarsky** [Foundry376/Mailspring#2036] opened 2020-05-31 07:57 UTC
The date for sent message is always shown (and sorted as) Dec 31, 1969. It that happens only when GoDaddy IMAP server is used.

**Comment by pagsball** [comment] 2020-07-27 18:37
This bug seems related to the others: https://github.com/Foundry376/Mailspring/issues?q=is%3Aissue+is%3Aopen+1969

I can temporarily resolve this by going to accounts and using "Rebuid Cache", but the issue seems to happen every time I send a new message.

**Comment by CodeMouse92** [comment] 2021-02-05 00:03
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/sent-date-always-showing-1969-or-1970/471

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-05 00:03 UTC
Labels: audit, bug
