### ISSUE TITLE
Quoting causes selected text to disappear

### ISSUE THREAD

**Issue by MRSalomao** [Foundry376/Mailspring#845] opened 2018-05-01 18:04 UTC
##### What operating system are you using?
MacOS 10.12.6

##### What version of Mailspring are you using?
1.2.1

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No, just installed Mailspring to test it out.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
No.

Bug description: pressing quote causes the selected text to disappear. 

http://www.giphy.com/gifs/1rN0asXb9DoRg8Hztl

**Comment by b00f** [comment] 2020-07-07 02:08
I can confirm this bug. ArchLinux

**Comment by CodeMouse92** [comment] 2021-02-11 19:06
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

@b00f: Can you please confirm that this is still broken with 1.8.0, and if so, open a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-11 19:06 UTC
Labels: audit
