### ISSUE TITLE
Email composing: `code` appends a space

### ISSUE THREAD

**Issue by tukusejssirs** [Foundry376/Mailspring#1794] opened 2020-02-13 10:23 UTC
##### Are there any related issues?

...

##### What operating system are you using?
CentOS 8 x86_64
...

##### What version of Mailspring are you using?
(eg: 1.6.3 or 1.7.0 - this is shown in Mailspring's main menu.)
1.7.2-4522b259
--

**Bug?**

##### Is this an email sync or connection issue?

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

---

When I use backticks to format a string as code (to use fixed width font), Mailspring does format the string as expected, but it appends a space after it. I think this is because you wanted to address the fact that when the space is not there (either not appended or removed by <kbd>Backspace</kbd>), the following characters will be also formatted as code.

Now I think that Mailspring (1) should not append that space (or insert anything else) and (2) the character that following the string formatted as code, should be in the format used just before code format (e.g. font: `Sans Serif`; font size: `Normal`).

I think a connected issue is the codeblock (using triple backticks): when I insert triple backticks at the beginning of a line, that line is formatted as codeblock (as expected). But when I paste in that line a multiline text copied from somewhere else, it create _separate_ codeblocks for each and every line. Should be: one codeblock for the whole pasted text.

**Comment by bengotow** [comment] 2020-02-15 20:19
Hey! Thanks for reporting this @tukusejssirs, you're definitely right about why this happens :-) We made it append a space after the closing tick mark so that subsequent characters weren't joined into the code block. I think you're totally right that it should go back to the format that you were using previous to opening the code block.

I'll see if we can fix this - I think that originally this was done to workaround a bug in the text editor, but that may be fixed now!

**Comment by tukusejssirs** [comment] 2020-02-15 20:23
Thanks, @bengotow! Hope you find a fix for both (sub)issues. Both are bugging me equally, although I use the inline code formatting much more frequently. :smiley:

**Comment by CodeMouse92** [comment] 2021-02-26 18:57
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/email-composing-code-appends-a-space/838

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-26 18:57 UTC
Labels: audit, composer, enhancement
