### ISSUE TITLE
Bug: Unable to download calendar files

### ISSUE THREAD

**Issue by chaitunya** [Foundry376/Mailspring#2047] opened 2020-06-09 04:58 UTC
**Describe the bug**
When I receive calendar invites, I get the box shown below, which is very useful for responding to invites. However, I would like to export the invite to an external calendar application, but the download button is grayed out and I can't click it.

**To Reproduce**
Open an email containing a calendar invite.

**Expected behavior**
When I click the download button, it should save the calendar file to the system.

**Screenshots**
![mailspring_calendar](https://user-images.githubusercontent.com/13303232/84107508-aaae5700-a9d2-11ea-9e80-0b9ef524bca9.png)

**Setup:**
 - OS: [Ubuntu Linux (Pop!_OS)]
 - OS Version [20.04]
 - Mailspring Version: 1.7.8-13635bcf

**Comment by chaitunya** [comment] 2020-06-09 04:59
👍

**Comment by CodeMouse92** [comment] 2021-03-02 02:29
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/accepting-calendar-invite-should-change-event-status/43

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 02:29 UTC
Labels: audit, bug
