### ISSUE TITLE
Label/tag colors should match colors in Gmail

### ISSUE THREAD

**Issue by curtisgibby** [Foundry376/Mailspring#753] opened 2018-03-09 21:58 UTC
##### Are there any related issues?

No.

##### What operating system are you using?

Linux Mint 18.3. 

##### What version of Mailspring are you using?

1.1.5-5834c99f

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?

mail.google.com itself allows you to specify colors for different labels/tags.

![gmail-labels](https://user-images.githubusercontent.com/1086964/37231910-2e978296-23aa-11e8-9634-3743ec3f8616.png)

After years of using the same colors, it's a little odd to see the same emails with different colors in Mailspring.

![mailspring-labels](https://user-images.githubusercontent.com/1086964/37231916-34563fba-23aa-11e8-9c33-93f84f64b360.png)

How are you generating these folder/label colors? Is there any way to pull the colors directly from Gmail? I understand if this information simply is not available, but I'm interested to understand the current process either way.

**Comment by bengotow** [comment] 2018-03-19 21:29
Hey—thanks for filing this! Right now, the colors are pseudo-randomly generated here: https://github.com/Foundry376/Mailspring/blob/master/app/src/flux/models/category.es6#L127 Right now Mailspring uses the Gmail IMAP interface, which doesn't expose the colors selected in Gmail, but there might be a way we could do this with the Gmail first-party API?

**Comment by DanKrue80** [comment] 2018-08-19 10:44
Hey there,

would be a really helpful enhancement seeing same labelcolors in Mailspring. We also use the same colorcode for a while now and every teammember is used to them. Seeing different colors in Mailspring is  really a little weird.

Cant wait to see this enhancement soon.

**Comment by evoxxgithub** [comment] 2018-09-16 22:05
Hey there,

If it's not possible to pull the colors from gmail, why not make a Settings option where you can choose a color? This way, you can at least match it on your own.
But this is probably another thing, so should I open a new issue for this?

**Comment by ipolevoy** [comment] 2018-12-10 18:59
I agree with @evoxxgithub , why not add a simple color picker?

**Comment by bradleyreid** [comment] 2020-03-21 22:38
Two years later this seems like a huge benefit for a mail client that does care about aesthetics. For some of us, colour is a key part of organization. Is the not-yet-possible tag added because the feature was not added or because it is not yet possible to add a color-picker feature?

**Comment by gatiba** [comment] 2020-03-22 15:08
This for me is a killer feature and the reason why I can't swich from thunderbird... :(

**Comment by moatus** [comment] 2020-10-05 15:54
Being able to add colors to labels is a fundamentally feature for mail organization. I just started using Mailspring and not being able to change the colors of labels is a big problem. My whole workflow is being thrown off. Please consider a feature to change the color of labels!!

**Comment by CodeMouse92** [comment] 2021-02-17 02:13
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/customize-label-tag-colors/658

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@curtisgibby @DanKrue80 @evoxxgithub @ipolevoy @bradleyreid @gatiba @moatus: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

Also, @moatus, I think we could accept a PR for this (depending on how the settings were implemented in the interface), if you're proposing taking a crack at it. There's a lot of high priority features and bugs currently taking development attention, but a PR would probably be well received...or at least a plugin. You'd kinda implement it the same either way. ;)

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-17 02:13 UTC
Labels: audit, enhancement, not-yet-possible
