### ISSUE TITLE
Don't remove whitespaces from plaintext messages

### ISSUE THREAD

**Issue by josiasmat** [Foundry376/Mailspring#2225] opened 2020-12-13 13:40 UTC
**Description of the bug:**
When one receives a plaintext message in Mailspring, the program trims all lines (i.e. removes whitespaces from both sides of the line), and removes duplicated whitespaces from the middle of every line too.

**Why I think this is a bug:**
In many cases, plaintext messages have whitespaces that serves to format the way the text is shown. For example: I manage a Linux server which sends me messages about various status changes, and many shell commands use whitespaces in their outputs to align items in rows and columns. Mailspring messes up everything. As an example, this:

```
               total       used       free     shared    buffers     cached
  Mem:          7964       5581       2382          0         80       2309
  -/+ buffers/cache:       3192       4772
  Swap:        32767          0      32767
```

becomes:

```
total used free shared buffers cached
Mem: 7964 5344 2619 0 43 2214
-/+ buffers/cache: 3086 4878
Swap: 32767 0 32767
```

which is not suitable.

**Steps to reproduce the behavior:**
1. Send a plaintext message to yourself with whitespaces at the beginning and at the end of lines, and double whitespaces at the middle of lines (you can simply copy my example above.)
2. Receive the message in Mailspring.

**Expected behaviour:**
Mailspring shouldn't remove whitespaces, or should at least offer an option to set the desired behaviour.

(If there is already an option to change this, please tell me because I didn't find it.)

**Setup:**
 - OS: Windows 10 Pro
 - OS Version 20H2
 - Mailspring Version: 1.7.8

Thanks in advance.

**Comment by CodeMouse92** [comment] 2021-02-23 22:52
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/dont-remove-whitespaces-from-plaintext-messages/753

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-23 22:52 UTC
Labels: audit, bug
