### ISSUE TITLE
Appplication get stuck on initial sync

### ISSUE THREAD

**Issue by Werseter** [Foundry376/Mailspring#1090] opened 2018-09-21 20:33 UTC
##### Are there any related issues?

Not recent ones, the only ones found say the issue has been solved in some kind of update

##### What operating system are you using?

Windows 8.1

##### What version of Mailspring are you using?

1.4.2-f587b7b7

**Bug?**

##### Is this an email sync or connection issue?

A sync issue, very early on, just started using, forever 0%

```
14632 [2018-09-21 22:20:01.957] [background] [info] Marking all folders as `busy`
14632 [2018-09-21 22:20:01.957] [background] [info] Syncing folder list...
14632 [2018-09-21 22:20:01.957] [metadata] [info] Metadata delta stream starting...
14632 [2018-09-21 22:20:02.706] [background] [info] Syncing folder list...
14632 [2018-09-21 22:20:02.770] [background] [info] syncFolderUIDRange for INBOX, UIDs: 1 - 0, Heavy: false
14632 [2018-09-21 22:20:03.039] [foreground] [info] Idling on folder INBOX
14632 [2018-09-21 22:20:03.437] [background] [info] - remote=13121, local=0
14632 [2018-09-21 22:20:03.507] [background] [info] - Fetching full headers for 13121 (of 13121 needed)
14632 [2018-09-21 22:20:03.668] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID (heavy)","key":"ErrorConnection","retryable":true,"what":"Unknown exception"}
14632 [2018-09-21 22:20:16.955] [metadataExpiration] [info] Scanning for expired metadata
14632 [2018-09-21 22:20:16.955] [metadataExpiration] [info] -- Will wake for next expiration in 7200sec
```

Will loop like this indefinitely

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

The only one I've been using has been `interia.pl` through IMAP

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Well, _can't do much else_ given the mails fail to sync. Tried rebuilding cache, resetting-up the account and reinstalling the app taking mind in deleting the cache in %APPDATA%

**Comment by iyumzit** [comment] 2018-09-27 00:45
hi, 
i have the same version and using it on windows 10. i love mailspring and it's features but the freezing is really an issue. i have to restart it throughout the day. i have uninstalled and deleted it's app folder then installed it again like i read in another thread but the issue remains. i wish there's a solution for a basic user like me as i really want to keep using the app.

**Comment by CodeMouse92** [comment] 2021-01-28 03:28
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/the-eternal-sync-bug/334

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 03:28 UTC
Labels: audit
