### ISSUE TITLE
Shows wrong recipient mail address

### ISSUE THREAD

**Issue by SpineEyE** [Foundry376/Mailspring#874] opened 2018-05-16 12:33 UTC
##### Are there any related issues?

 None found

##### What operating system are you using?

Unrelated

##### What version of Mailspring are you using?

1.2.1-7e7447b6

**Bug**
##### Do you have any third-party plugins installed? If so, which ones?
None

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
...

Mailspring displays as recipient: `To: You (identity1@host.com)` while actually the email was sent to `identity2@host.com`. Only when I click on the small triangle in front of the sender name, it shows the correct recipient name and email. Why don't you show this right away?

**Comment by SpineEyE** [comment] 2018-05-22 21:15
Hey, thanks for reaching out. Yes that's actually the case.

**Comment by CodeMouse92** [comment] 2021-02-08 21:45
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/reply-to-headers/507

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-08 21:45 UTC
Labels: audit, bug, needs-reproduction
