### ISSUE TITLE
Unwritable content field on account switch

### ISSUE THREAD

**Issue by AdamGold** [Foundry376/Mailspring#1661] opened 2019-10-14 18:55 UTC
##### What operating system are you using?
Mac OS Catalina

##### What version of Mailspring are you using?

1.7.0

--

**Bug?**

When composing a new message, switching accounts makes the "Content" field Unwritable. If I write something in it before the switch, the bug doesn't occur - Only when the first thing I do is switching accounts.

**Comment by bengotow** [comment] 2019-10-14 19:56
Hey thanks for filing this! I tried to reproduce this but I actually couldn't get it to happen. There's a small chance that this is actually related to the sync workers crashing in #1660, let's fix that and see if it's still reproducible. Also curious whether this has anything to do with having a signature enabled / disabled.

**Comment by AdamGold** [comment] 2019-10-15 05:31
> Hey thanks for filing this! I tried to reproduce this but I actually couldn't get it to happen. There's a small chance that this is actually related to the sync workers crashing in #1660, let's fix that and see if it's still reproducible. Also curious whether this has anything to do with having a signature enabled / disabled.

Interesting thought - I enabled the signature for the 2nd account, and everything works flawlessly.

**Comment by CodeMouse92** [comment] 2021-02-19 00:28
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://github.com/Foundry376/Mailspring/issues/1661

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@AdamGold: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-19 00:28 UTC
Labels: audit, bug, needs-reproduction
