### ISSUE TITLE
Bug: Notifications aren't working on Ubuntu 20.04 with only 1 account

### ISSUE THREAD

**Issue by HarunOr** [Foundry376/Mailspring#2060] opened 2020-06-20 02:30 UTC
**Describe the bug**
Notifications aren't working on Ubuntu 20.04 (fresh install).
I made sure that the notifications are enabled in the app settings.
Zenity is also installed.

![Screenshot from 2020-06-20 04-25-56](https://user-images.githubusercontent.com/12257110/85189615-d671ec80-b2b0-11ea-97d1-9be93abb85b8.png)

**Expected behavior**
A notification should notify me of new unread emails.

**Setup: **
 - OS: Ubuntu Linux
 - OS Version 20.04
 - Mailspring Version: 1.7.8-13635bcf

------------------------------------------------------------------------------

I just added another account, and the notifications suddenly started working, even though I didn't change any of the Mailspring settings. Weird. 

Probably related #1632

**Comment by CodeMouse92** [comment] 2021-03-02 02:57
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/notifications-arent-working-on-ubuntu-20-04-with-only-1-account/918

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@HarunOr: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 02:57 UTC
Labels: audit, bug
