### ISSUE TITLE
Sync Issue

### ISSUE THREAD

**Issue by canmenzo** [Foundry376/Mailspring#1882] opened 2020-03-31 17:10 UTC
"Mailspring encountered errors in syncing this account. Crash reports have been sent to the Mailspring team and we'll work to fix these errors in the next release. Try Reconnecting."

Tried downgrading the software and readding accounts. Could also provide more if requested.
![image](https://user-images.githubusercontent.com/21162557/78055050-a428b100-738b-11ea-9107-133a54a9815b.png)

**Comment by canmenzo** [comment] 2020-03-31 17:11
New to github so I am not really sure what else I need to include in my issue. feel free to ask and I'll respond asap

**Comment by CodeMouse92** [comment] 2021-01-28 03:23
Hi @canmenzo,

2020 prevented much development work on Mailspring, but rest assured, development has resumed! We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

Can you please confirm that this is still broken with 1.8.0, and if so, open a new Sync Issue on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 03:23 UTC
Labels: audit
