### ISSUE TITLE
Bug: Autoloading with the system is always marked

### ISSUE THREAD

**Issue by MrMyth** [Foundry376/Mailspring#1915] opened 2020-04-17 15:37 UTC
1) Remove the tick of the auto-loading program.
2) Move to any other section of settings.
3) Return to the first tab. We see that the autoload tick is marked, but the program does not start when the Windows system starts.

**Comment by CodeMouse92** [comment] 2021-02-27 03:20
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse (which happily has also been resolved in an upcoming release!):

https://community.getmailspring.com/t/i-cant-uncheck-run-on-startup/208

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-27 03:20 UTC
Labels: audit, bug
