### ISSUE TITLE
Being able to mute threads. 

### ISSUE THREAD

**Issue by krasi-georgiev** [Foundry376/Mailspring#1988] opened 2020-05-16 09:53 UTC
I am subscribed to a few google groups, but often I am not interested in a thread and would like to mute only a given thread. Gmail has a `mute` button for a thread so I would like to propose the same feature for Mailspring.

Just to be clear I don't want to mute an account, but a given thread in an account.

**Comment by CodeMouse92** [comment] 2021-03-01 23:43
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/being-able-to-mute-threads/895

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@krasi-georgiev: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-01 23:43 UTC
Labels: audit, enhancement
