### ISSUE TITLE
Feature Request: Translation of mail content with DeepL

### ISSUE THREAD

**Issue by playforvoices1** [Foundry376/Mailspring#1907] opened 2020-04-16 13:29 UTC
It is a very good feature that you can translate the content of a mail. But the translation in Mailspring is not really good. 

I would like to suggest a translation with DeepL. There are also API's offered to include them. 

https://www.deepl.com/home

**Comment by bengotow** [comment] 2020-04-16 15:21
Hey! Thanks for reporting this—a few folks have asked for DeepL specifically in the past. I agree it's really much better than what we're using now. Using it the way we're supposed to (as an API customer) is one cent per 500 words, which could be too expensive for folks that have automatic translation enabled for most of their emails. 

I'll see if we can add this as an option of some sort though—we have enough of a system in place we could forward costs along if they became too high or degrade the translation quality after you hit 250,000 characters / mo ($5) or something like that.

<img width="312" alt="image" src="https://user-images.githubusercontent.com/1037212/79473903-63f04200-7fcb-11ea-8ee5-b00a2bfd2840.png">

**Comment by playforvoices1** [comment] 2020-04-16 16:07
Sounds very good. It would be very nice to have these option.

**Comment by CodeMouse92** [comment] 2021-02-27 03:08
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/translation-of-mail-content-with-deepl/854

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@playforvoices1: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-27 03:08 UTC
Labels: audit, enhancement
