### ISSUE TITLE
Bug: Attachments not showing up in the discussion panel

### ISSUE THREAD

**Issue by MacDumi** [Foundry376/Mailspring#1872] opened 2020-03-23 11:41 UTC
**Describe the bug**
In the discussion panel, previous emails do not contain any attachments or only some of them. When searched for the original email, attachments show up.

**To Reproduce**
1. Open any discussion with several emails that had attachments.
2. Open a previous email
3. Check for attachments - they are either missing or only a part of them are present

**Expected behavior**
The attached files to a previous email are either missing or not all are shown.

**Setup: (please complete the following information):**
 - OS: Manjaro Linux (also verified on Windows 10)
 - Mailspring Version: 1.7.4-d54ff730

**Additional context** 
If the original email is opened then the attachments show up.

**Comment by bengotow** [comment] 2020-04-15 23:44
Hey! Thanks for reporting this, it definitely sounds like there could be a bug here.

Could you clarify how you're viewing the discussion though? Are you expanding the previous emails in the conversation by clicking on the folding UI that looks like this:

**Comment by MacDumi** [comment] 2020-04-16 00:03
Hi,
I am expanding the previous mails by clicking on the folding UI (the first image you showed). The emails show the "attachments" icon on the right but when selecting the email no attachments show up. 
I have to say that lately I'm experiencing this issue not as frequently as before, approximately one in 5-7 emails will show up without their attachments. 
Let me know if you need any additional information.
Thanks!

**Comment by CodeMouse92** [comment] 2021-02-27 02:45
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/attachments-not-showing-up-in-the-discussion-panel/848

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@MacDumi: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-27 02:45 UTC
Labels: audit, bug, needs-reproduction
