### ISSUE TITLE
Blue notification for unread e-mails in custom created folders

### ISSUE THREAD

**Issue by MattiaCostamagna** [Foundry376/Mailspring#1231] opened 2018-11-12 11:44 UTC
##### What operating system are you using?
Ubuntu 18.10

##### What version of Mailspring are you using?
1.5.2-31660462

**Feature Request?**
It would be nice to have the blue notification that tells you the number of unread mails you have also when e-mails are moved (for example by filters) in another folder that is not the Inbox. I have a lot of filters related to automatic notifications that move e-mails into custom created folders, and every time I have to check into every directory to see if there is an e-mail I haven't still read.

##### Does this feature exist in another mail client or tool you use?
Yes, Outlook or Thunderbird for example

**Comment by jesusvpct** [comment] 2019-03-22 06:51
I want this too. I have to switch back to Thunderbird because of this.

**Comment by CodeMouse92** [comment] 2021-02-25 22:48
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://github.com/Foundry376/Mailspring/issues/1231

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-25 22:48 UTC
Labels: audit, enhancement
