### ISSUE TITLE
Lost last unsaved changes when pressing up arrow key at the top of input box

### ISSUE THREAD

**Issue by IamGianluca** [Foundry376/Mailspring#1411] opened 2019-03-07 16:28 UTC
I'm using Mailspring 1.5.7 on Ubuntu 18.04.2 LTS. 

I constantly incur on a very annoying bug. When composing an email, if a go all the way up to the very first line of the email I'm composing and press the up arrow key, I lose the most recent part of the text I wrote. What I think is happening is that I go back to the last saved checkpoint. Undo doesn't help since it doesn't do anything in this case. I can't find a way to restore the text which was just removed.

This is happening to me VERY frequently and makes the whole experience quite annoying since it affects productivity.

Anyway, I really love the product and want to thank all the contributors to the project! I just hope this bug could be fixed sooner than later :-)

**Comment by M-Pixel** [comment] 2019-03-25 15:53
Duplicate of #851

**Closed** 2021-02-10 23:57 UTC
Labels: audit

**Comment by CodeMouse92** [comment] 2021-02-11 00:01
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/more-than-half-of-a-message-being-composed-got-suddenly-deleted-and-cannot-be-restored/564

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@IamGianluca: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team
