### ISSUE TITLE
Keyboard shortcut to move between labels on the left

### ISSUE THREAD

**Issue by oxysoft** [Foundry376/Mailspring#767] opened 2018-03-18 21:14 UTC
There doesn't seem to be any keyboard shortcut for moving around in the left-hand labels, forcing me to downgrade to mouse inputs when I am working with my keyboard in order to view emails in other categories/labels. I suggest something like ctrl-alt-up/ctrl-alt-down which is the same shortcut as Discord for changing between channels. In the same spirit as Discord again, we could also have ctrl-shift-up/ctrl-shift-down to navigate only between labels that have new emails (that is, an unread count is displayed next to them)

**Comment by tukusejssirs** [comment] 2019-06-11 12:23
+1, because I do 99 % of the computer work via keyboard :)

I would add the traditional Alt+[letter] to open the menu (like Alt+F to open the File manu) – it does not work on CentOS 7 installed from the official `.rpm` package.

**Comment by CodeMouse92** [comment] 2021-02-11 23:28
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/keyboard-shortcut-to-move-between-labels-on-the-left/580

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@oxysoft: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-11 23:28 UTC
Labels: audit
