### ISSUE TITLE
Feature Request: thumbnail preview of image attachment similar to thumbnail preview of pdf attachment

### ISSUE THREAD

**Issue by asparc** [Foundry376/Mailspring#2088] opened 2020-07-10 14:16 UTC
Currently, attached images are displayed in the email. The way they are display can hardly be called a thumbnail preview. They look as if they were added inline. Moreover, these previews are very large, so they obfuscate the layout of the email, while composing or reading. 

It would be nicer and less confusing if attached images could get a preview option similar to the way pdf attachments are currently previewed: in a small box that shows the name of the attachment + a sample of its content.

**Comment by CodeMouse92** [comment] 2021-03-02 18:48
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/thumbnail-preview-of-image-attachment-similar-to-thumbnail-preview-of-pdf-attachment/934

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@asparc: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 18:48 UTC
Labels: audit, enhancement
