### ISSUE TITLE
Backspace not working in compose when Text is already selected.

### ISSUE THREAD

**Issue by karan199** [Foundry376/Mailspring#863] opened 2018-05-10 15:27 UTC
so this issue comes up when i am selecting some text in compose and not able to perform backspace key operation on that selected text.

**Comment by emadow** [comment] 2018-05-10 23:09
Also experiencing this

**Comment by bengotow** [comment] 2018-05-22 23:13
Hey folks—thanks for reporting this. I haven't been able to reproduce this one yet. Does it typically happen within quoted text, or when you're trying to edit text that was pasted in, etc? Anything to help narrow it down would be useful.

**Comment by karan199** [comment] 2018-05-25 11:33
so this issue always appear when i am selecting text in Composer body and try to remove whole selected text by pressing backspace key, it does not matter text was pasted and written down. 
Delete key is working properly in composer body when try to remove whole selected text.

**Comment by jerm** [comment] 2018-10-27 17:03
@bengotow I think i have reproducing this nailed down:

I have also been experiencing this for quite some time, including most recent version. Using OSX High Sierra, but was present in Sierra as well.

This works as it should, unless your cursor is in the 0,0 position in the message when hitting backspace.

So if you're at the beginning of the first line, and select outward, it works fine... 

If you're anywhere else in first line, and select back to the beginning of the line, backspace does nothing.

Same vertically... it works fine _until_ you select all the way up to the top of the message from below.  top-down works fine, because cursor is not at 0,0 when hitting backspace. 

Hope this helps :)

**Comment by hybridvision** [comment] 2018-12-03 15:42
I encountered this today and I can confirm @jerm's excellent analysis of the bug. Hopefully it's a pretty simple one to solve now...

**Comment by bengotow** [comment] 2019-06-11 01:06
Hey folks! Sorry for the delay on this one—I just finished upgrading Mailspring's composer to use a new version of the Slate text editor and it looks like they've fixed this upstream! (The performance is  quite a bit better too, which is exciting.) Stay tuned—

**Comment by bengotow** [comment] 2019-07-04 14:01
Hey folks! This should be addressed in the latest release (1.6.3) that shipped earlier this week. The app should auto-update on it's own, or you can grab the new version from the releases page: https://github.com/Foundry376/Mailspring/releases/. Thanks for filing this - enjoy the update!

**Closed by bengotow** 2019-07-04 14:01 UTC
Labels: bug, composer, done-pending-release

**Comment by hybridvision** [comment] 2019-07-04 14:56
Confirming that it's fixed for me 🎉  It's great to see Mailspring steadily improving.

Thanks @bengotow!
