### ISSUE TITLE
Feature Request: Stopping notification for a particular email account

### ISSUE THREAD

**Issue by anubhav4sachan** [Foundry376/Mailspring#2065] opened 2020-06-23 14:13 UTC
**Is your feature request related to a problem? Please describe.**
It is annoying to see notifications from a specific email account during work.

**Describe the solution you'd like**

I have 3 email accounts synced with Mailspring, and I really love the interface and all the functionalities.

The point which is bothering me, is that there is an account having a lot of newsletters (which I read in free time) being delivered. I want this particular account to be in a snooze mode, while I'm working, but from other emails, I want the notification during this period.

Is it possible to do so?

**Comment by CodeMouse92** [comment] 2021-01-30 00:38
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/per-account-mailbox-notification-settings/133/4

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-30 00:38 UTC
Labels: audit, enhancement
