### ISSUE TITLE
Can not reply to mails, if the email account server is with self-signed SSL certificate (allow insecure connection option)

### ISSUE THREAD

**Issue by KIvanow** [Foundry376/Mailspring#488] opened 2017-12-29 13:01 UTC
OS: Ubuntu 16.04 (64 bit)

Mailspring version 1.12 (it could be reproduced to the second to last version as well). Clean version with no added plugins. It can be reproduced on the .deb package, the snap package and installed from the Ubuntu software center.

I have tried mailspring with 2 gMails accounts, and 2 email accounts from my hosting, there is no issue with them.

I have tried the troublesome mail account, that doesn't work in mailspring and it works just fine in Thunderbird.

On the problematic email account I can read, delete and archive messages. Only the reply and writing new message doesn't seem to work.

From the dev tools, on click mailspring logs "type: "queue-task", task: SyncbackDraftTask" and just hangs on there.

If I can help in any way for this issues, just let me know :)

![image](https://user-images.githubusercontent.com/541999/34437691-1ff1f722-eca9-11e7-8bc1-ebf841c5486c.png)

**Comment by bengotow** [comment] 2017-12-29 17:44
Hey @KIvanow — when you configure the account, you should be able to check this box and enable insecure / self-signed SSL. Can you try changing this setting and see if it resolves the issue?

<img width="349" alt="image" src="https://user-images.githubusercontent.com/1037212/34443554-fb7f27f6-ec95-11e7-8200-93bafb1c97fd.png">

**Comment by KIvanow** [comment] 2017-12-29 17:57
Hey @bengotow If this setting isn't checked I can't connect the account. When it is checked, I can connect the account and I can read, delete and archive messages, but I can not send messages and reply to messages.

**Comment by chemicalkosek** [comment] 2018-02-06 14:41
I can confirm this bug. Can't reply or write new messages from a problematic account. Gmail not affected.

**Comment by shorawitz** [comment] 2018-02-23 20:15
I can confirm this issue as well.  Using KDE Neon (Ubuntu 16.04 base.)  Running Mailspring from cli I get:

{ TypeError: Cannot read property 'id' of null
    at MailsyncProcess.sendMessage (/src/mailsync-process.es6:277:40)
    at MailsyncBridge.sendMessageToAccount (/src/flux/mailsync-bridge.es6:200:30)
    at MailsyncBridge._onQueueTask (/src/flux/mailsync-bridge.es6:341:10)
    at EventEmitter.eventHandler (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:36:22)
    at EventEmitter.emit (/usr/share/mailspring/resources/app.asar/node_modules/eventemitter3/index.js:93:33)
    at Function.trigger (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:52:26)
    at Function.functor [as queueTask] (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/createAction.js:32:56)
    at DraftStore._finalizeAndPersistNewMessage (/src/flux/stores/draft-store.es6:267:13)
    at DraftStore._onPopoutBlankDraft (/src/flux/stores/draft-store.es6:289:44)
    at <anonymous> message: 'Cannot read property \'id\' of null' } { pluginIds: [] }
Raven: 429 - Creation of this event was denied due to rate limiting

**Comment by chemicalkosek** [comment] 2018-02-25 10:31
Actually it has been resolved for me in the latest version.

**Comment by shorawitz** [comment] 2018-02-25 16:42
@chemicalkosek what O/S are you using?  I'm using 1.1.4-22d9f20d.  Odd.  No matter what I do, I get the above error output.

**Comment by chemicalkosek** [comment] 2018-02-25 17:08
I double checked. Everything working fine now. Ubuntu 16.04.3. Ran Mailspring from command line. No errors. Also 1.1.4-22d9f20. I think it's even working since 1.1.3, not sure.

**Comment by shorawitz** [comment] 2018-02-25 20:07
Are you using deb package or snap?

**Comment by CodeMouse92** [comment] 2021-01-30 01:00
It appears that this issue has been resolved, so we are closing it. If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-30 01:00 UTC
Labels: audit, needs-reproduction
