### ISSUE TITLE
no emails sent from MailSpring in Sent Items

### ISSUE THREAD

**Issue by bayareacoder** [Foundry376/Mailspring#1018] opened 2018-08-13 07:13 UTC
##### Are there any related issues?

...

##### What operating system are you using?

OS X High Sierra 10.13.6

##### What version of Mailspring are you using?

1.4.0

--

**Bug?**

Yes. Emails not showing in Sent Items. I saw this reported before and also reported as fixed, but still present. Not an issue with wrongly set IMAP folders since when I send an email from Mac Mail it does appear in Sent Items. Only emails sent from MailSpring do not. However the email does show with a "1969" date in Inbox...

##### Is this an email sync or connection issue?

No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Probably yes: GoDaddy IMAP

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Yes.

**Comment by bksubhuti** [comment] 2019-02-16 22:59
I am having a similar problem using Mate-ubuntu 18.04
I am using gmail and did the gmail sign in thing.  However, there are definitely emails in my sent folder if I go live with gmail.com

![mailspring-sendmailfolder](https://user-images.githubusercontent.com/18184280/52906168-8382b380-31ea-11e9-9c0e-673a5a7d1c8c.png)

**Comment by CodeMouse92** [comment] 2021-02-05 00:02
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/sent-date-always-showing-1969-or-1970/471

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-05 00:02 UTC
Labels: audit
