### ISSUE TITLE
Composer feature request: "No formatting" button?

### ISSUE THREAD

**Issue by palefire19** [Foundry376/Mailspring#603] opened 2018-01-31 13:29 UTC
##### What operating system are you using?
10.13.2

##### What version of Mailspring are you using?
1.1.2

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Gmail

Basically I'm looking for a button where selected text could be restored to default size, black, sans-serif formatting. I'm finding that when I insert a link, it's hard to get the follow text back to "normal" - it likes to stay blue and underlined

**Comment by dailyherold** [comment] 2018-01-31 21:41
Would like to see this as well, or even a way to get the raw markup so I can edit out formatting I can't clear via editor buttons.

**Comment by saldaj** [comment] 2020-09-07 07:39
Hi, it is a two years and half, since this topic was opened. Any news? I cannot see this function in mailspring, yet. It is a key function for me.
Thanks for any response.

**Comment by CodeMouse92** [comment] 2021-02-09 22:44
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/composer-no-formatting-button/533

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@palefire19: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-09 22:44 UTC
Labels: composer, enhancement, migrated
