### ISSUE TITLE
'Archive' and 'Mark as Spam' buttons change locations unexpectedly

### ISSUE THREAD

**Issue by SarahBaghdadi** [Foundry376/Mailspring#1077] opened 2018-09-18 02:38 UTC
When I'm archiving a number of messages in a row, the location of icons in the icon bar changes depending on the message. Sometimes that means that where the 'archive' button is for one message, for another message it will be the 'mark as spam' button. So when I'm clicking 'archive' a bunch of times in a row, it's pretty easy to accidentally click 'mark as spam' since that button sometimes just happens to be under my cursor unexpectedly. Its due to the number of icons changing but also due to different icons having different widths.

I would suggest that either certain critical buttons have a fixed location or that the 'mark as spam' button has a confirmation dialogue since that's a relatively rare action (hopefully).

##### What operating system are you using?

OSX 10.13.6

##### What version of Mailspring are you using?
1.4.2

<img width="797" alt="screen shot 2018-09-17 at 10 33 35 pm" src="https://user-images.githubusercontent.com/8106569/45661036-c28ccb80-bac9-11e8-9dbe-948465745d18.png">

**Comment by manzwebdesigns** [comment] 2019-12-19 19:27
I like the option suggested by @PowerSnail of disabling the non-usable buttons... it is very frustrating to wonder why I all of a sudden stop getting notifications from my servers, etc simply because I inadvertently clicked send to spam instead of archiving an email!  Please fix this.

**Comment by CodeMouse92** [comment] 2021-02-16 00:58
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/archive-and-mark-as-spam-buttons-change-locations-unexpectedly/645

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@SarahBaghdadi @PowerSnail @manzwebdesigns: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-16 00:58 UTC
Labels: audit
