### ISSUE TITLE
Installing Issue

### ISSUE THREAD

**Issue by satishgupta4s** [Foundry376/Mailspring#598] opened 2018-01-31 05:54 UTC
After download mailspring. I can't open this project .Any one help me how to install and build this project.

**Comment by sverhagen** [comment] 2018-01-31 06:14
Could you please say more about what you were trying to do? Download: source, binary, which platform? Is this a duplicate of #599?

**Comment by satishgupta4s** [comment] 2018-01-31 06:32
please find the error in attached form.
![error](https://user-images.githubusercontent.com/34708585/35608314-9d676c52-067e-11e8-940d-0765aa4667c5.png)

**Comment by sverhagen** [comment] 2018-01-31 06:34
So... this _is_ a duplicate of #599. I suggest closing this issue then.

**Comment by bengotow** [comment] 2018-02-03 07:08
Hey! Thanks for flagging this @sverhagen — closing as a dup of #599. 👍

**Closed by bengotow** 2018-02-03 07:08 UTC
