### ISSUE TITLE
Highlight labels with new emails

### ISSUE THREAD

**Issue by 3v1n0** [Foundry376/Mailspring#444] opened 2017-12-15 22:28 UTC
When new emails are added to some labels bypassing the inbox folder, it would be nice to highlight them.

This is useful when you use labels as folders for mailing lists or such, in order to track new emails there that aren't shown in the inbox folder.

**Comment by bengotow** [comment] 2017-12-18 23:59
Hey! We don't support this yet, but in the meantime showing unread counts for all the labels might help—since no count appears when there are zero unread messages, it makes it easier to see which labels have unread messages:

![image](https://user-images.githubusercontent.com/1037212/34133914-b72a88fe-e414-11e7-97c4-68ce44bcdec2.png)


![image](https://user-images.githubusercontent.com/1037212/34133928-ce03e390-e414-11e7-961e-91143e945252.png)

**Comment by phamhung77** [comment] 2018-08-15 13:52
This only works with the first level of folders / labels. If I have a second level, for example, Receipts/vendor1, then the unread count is not appearing in the first level. It would be great that the first level can show total unread counts of all second levels.

**Comment by Yari27** [comment] 2019-05-16 07:34
It would be nice if even unread messages from folders / labels were visible as unread sums in Inbox.

Now in the Inbox and Unread folders, it shows that there are no messages even though the folders are full of unread messages.

![](https://i.ibb.co/7zWWzjV/Adnotacja-2019-05-16-092843.jpg)

**Comment by CodeMouse92** [comment] 2021-02-20 03:39
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This appears to be related to a feature suggestion we already migrated to Discourse:

https://community.getmailspring.com/t/notifications-on-non-inbox-folders/323

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@3v1n0: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-20 03:39 UTC
Labels: audit, enhancement
