### ISSUE TITLE
MailSpring Windows client fails on sending attachments to Novell Groupwise SMTP Server hosted on SLES

### ISSUE THREAD

**Issue by StewAlexander-com** [Foundry376/Mailspring#1689] opened 2019-10-25 13:17 UTC
Hi all,

I prefer using the capabilities of MailSpring client in a team where most people use an (antiquated) Groupwise Windows Client.

Yes, groupwise is still around

Anyway, our SMTP server is also a Novell GroupWise product running on SLES (Suse Linux)

I have few issues sending emails as long as there are no attachments, but sending an attachment bombs

We use IMAP, prt 143 / SMTP port 25, and like I said email works, but sadly not attachments.

Please let me know what you need from me, because I would love to get this working

**Comment by bengotow** [comment] 2019-10-26 17:05
Hey @StewAlexanderACC thanks for reaching out! Wow I haven't heard of Groupwise in a while - glad it's still kicking!

Could you open Mailspring and try to send a message with an attachment, and then go to Develper -> Show Mailsync Logs and post the file mailsync-****.log for that account?  (There's not much PII in there other than your email address, but you can just post the last few dozen lines if that's easier.)

Mailspring doesn't do anything terribly tricky - it just builds a multipart MIME Message and sends it to the SMTP server, so I'm not sure offhand if this is something we'll be able to fix. It's possible that your attachment is over a filesize limit or that your administrator needs to enable a setting to allow attachments via IMAP/SMTP (maybe it was turned off for third party clients somehow?)

**Comment by StewAlexanderACC** [comment] 2019-10-28 11:47
![image](https://user-images.githubusercontent.com/48565067/67675853-9b542f00-f956-11e9-881d-204ad647e3cb.png)

```
12628 [2019-10-28 07:43:35.811] [background] [info] - Updating message gbDz16FqrSUBaCd735N89TcTDXs5gMGyXfDLTCjMW
12628 [2019-10-28 07:43:35.811] [background] [info] -- UID (26 to 87)
12628 [2019-10-28 07:43:35.811] [background] [info] -- FolderID (n9i6ARbt6ejggXB2UYFVSpiihLgzhZ37YUaz829pk to DwD5AVZzfHTWeQXs86qBS5AZd6FLfPxbtg76JwmXg)
12628 [2019-10-28 07:43:35.885] [background] [info] syncFolderUIDRange for No Reply, UIDs: 1 - 24, Heavy: false
12628 [2019-10-28 07:43:35.961] [background] [info] - remote=14, local=14
12628 [2019-10-28 07:43:35.961] [background] [info] - Fetching full headers for 1 (of 1 needed)
12628 [2019-10-28 07:43:35.966] [background] [warning] Ignoring changes to New Ticket Alert, local data is newer 1572263015 < 1572292208
12628 [2019-10-28 07:43:35.967] [background] [info] Cleaning local cache and updating stats
12628 [2019-10-28 07:43:35.970] [background] [info] -- 0 message bodies deleted from local cache.
12628 [2019-10-28 07:43:36.051] [background] [info] syncFolderUIDRange for Brian Arnold, UIDs: 1 - 3, Heavy: false
12628 [2019-10-28 07:43:36.112] [background] [info] - remote=2, local=2
12628 [2019-10-28 07:43:36.112] [background] [info] Sync loop deleting unlinked messages with phase 2.
12628 [2019-10-28 07:43:36.113] [background] [info] Sync loop complete.
```

**Comment by StewAlexanderACC** [comment] 2019-10-28 11:48
Weirdly no message, no error, everything works fine when there's no attachments

**Comment by StewAlexanderACC** [comment] 2019-10-28 11:53
Here's the windows Novell Groupwise info:

![image](https://user-images.githubusercontent.com/48565067/67676381-b7a49b80-f957-11e9-81e4-faac343a5992.png)

'''
support@mail:~> cat /etc/*release
LSB_VERSION="core-2.0-noarch:core-3.2-noarch:core-4.0-noarch:core-2.0-x86_64:cor                              e-3.2-x86_64:core-4.0-x86_64"
SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 3
'''

**Comment by StewAlexanderACC** [comment] 2019-10-28 12:00
```
Mailspring doesn't do anything terribly tricky - it just builds a multipart MIME Message and sends it to the SMTP server, so I'm not sure offhand if this is something we'll be able to fix. It's possible that your attachment is over a filesize limit or that your administrator needs to enable a setting to allow attachments via IMAP/SMTP (maybe it was turned off for third party clients somehow?)
'''

I'm one of the admins, so no it's not a size limitation, however I wasn't the original person who set this up, so there could be some block somewhere, anyway I appreciate you looking into this @bengotow

**Comment by StewAlexanderACC** [comment] 2019-11-15 14:40
@bengotow any updates?

I tried to find any blocking of attachments and didn't come up with anything.

Is there any additional logs I can send your way?

**Comment by CodeMouse92** [comment] 2021-02-17 02:20
Sorry it got so quiet on this, @StewAlexander-com! As you can imagine, there's quite a large backlog of issues (most of them duplicates and wishlist feature requests, incidentally), and most things got buried. 2020 stalled development anyhow. The good news is, we're back to working on Mailspring!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mailspring-windows-client-fails-on-sending-attachments-to-novell-groupwise-smtp-server-hosted-on-sles/659

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@StewAlexander-com : if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-17 02:20 UTC
Labels: audit, mailserver-incompatibility, needs-reproduction
