### ISSUE TITLE
Scheduled email is never sent when client is closed at scheduled time.

### ISSUE THREAD

**Issue by iwangu** [Foundry376/Mailspring#847] opened 2018-05-06 17:07 UTC
If one has mailspring closed when an email is scheduled to be sent, and only opens it after the scheduled time, the message is never sent.

Example:  Email scheduled to be sent at 1 pm. At 1 pm the mailspring app is closed. One oppens the mailspring app only at 2 pm. The scheduled mail is never sent.

##### Are there any related issues?
no

##### What operating system are you using?
macOS

##### What version of Mailspring are you using?

Version 1.2.1 (1.2.1)

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
None

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Yes

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Yes.

**Comment by brendon-wong** [comment] 2018-11-13 07:07
Does send later not work if Mailspring is closed? That seems like a pretty serious problem.

**Comment by Xuan-Lim** [comment] 2020-02-06 09:44
So this happened to me in a very very unfortunate way today. I had an argument with a professor of mine where the entire argument rested on him not receiving the email. You would imagine that finding out what really happened would be quite embarrassing:/ It turned out that even though the message is shown to be in the sent box, it never gets sent. I had this confirmed with two other emails sent around the same time. 

Happening on Pop!_OS 18.04 LTS (based on Ubuntu of the same version)

There probably should be a check for send success before it gets put to the sent box if it comes to this

**Comment by jesi-rgb** [comment] 2020-07-19 08:22
As I was looking for an answer, I run into [this forum](https://foundry376.zendesk.com/hc/en-us/articles/360024261592-Does-Mailspring-need-to-be-running-to-send-scheduled-emails-) where they explain it:

> Why is this?

> When we launched Mailspring we conducted a survey and found that most of our users would prefer that the app never send email account credentials to the cloud for security and peace-of-mind. Mailspring syncs your email locally on your computer and does not transmit your passwords to our servers at any time. Unfortunately, this means that if your computer is offline, we can't deliver emails on your behalf from the cloud. We may change this in the future if there's enough interest!

In other services like Spark, this works like a charm. I don't know exactly what is going on in the background for this feature to work, but it is certainly something I, and many other people, would love to see in Mailspring.

**Comment by CodeMouse92** [comment] 2021-01-30 00:42
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/server-side-send-later/391

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-30 00:42 UTC
Labels: audit
