### ISSUE TITLE
Feature Request: Move emails between accounts

### ISSUE THREAD

**Issue by sounakban** [Foundry376/Mailspring#2247] opened 2021-01-05 02:23 UTC
I have two Gmail accounts and people often send emails to the wrong account, which makes it difficult for me to organize the emails. A lot of other email clients out there have the provision of dragging and dropping emails from one account to another (like Spark and eM Client). I would really love to see that feature in mailSpring.

**Comment by kaleidoscopique** [comment] 2021-01-25 20:28
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/move-emails-between-accounts/244

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

OP: if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed** 2021-01-26 21:49 UTC
Labels: migrated
