### ISSUE TITLE
同步时遇到错误— —deepin20 -version：1.7.6

### ISSUE THREAD

**Issue by Jungle7516** [Foundry376/Mailspring#1943] opened 2020-04-27 08:15 UTC
##### What is the behavior you're seeing?
![image](https://user-images.githubusercontent.com/48152482/80349567-f65fd380-885e-11ea-9ad6-4c218f1c66b7.png)
无法连接到邮箱
##### What email provider (Gmail, Exchange, etc.) are you trying to use?
163.com
##### What operating system are you using?
deepin20beta
##### What version of Mailspring are you using?
1.7.6
(eg: 1.6.3 or 1.7.0 - this is shown in Mailspring's main menu.)

**Comment by CodeMouse92** [comment] 2021-02-12 21:40
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/cannot-sync-126-163-mails-because-setting-up-snooze-subfolder-in-mail-folders-is-not-allowed/562

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-12 21:40 UTC
Labels: audit, mailserver-incompatibility, needs-reproduction
