### ISSUE TITLE
Sync fails for Exchange account via DavMail

### ISSUE THREAD

**Issue by kemsar** [Foundry376/Mailspring#1378] opened 2019-02-20 17:53 UTC
##### Are there any related issues?
Possibly #118 

##### What operating system are you using?
Ubuntu 18.04 LTS

##### What version of Mailspring are you using?
1.5.6-4cb1851b

**Bug?**
Yes

##### Is this an email sync or connection issue?
Sync [mailsync-86052b79.zip](https://github.com/Foundry376/Mailspring/files/2885866/mailsync-86052b79.zip)

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
IMAP, DavMail, Exchange

##### Is the issue reproducible with a particular attachment, message, signature, etc?
No

Excerpt from log:

```
28474 [2019-02-20 10:16:18.674] [main] [info] Identity created at 1549060724 - using ID Schema 1
28474 [2019-02-20 10:16:18.675] [main] [info] ------------- Starting Sync ([redacted]) ---------------
28474 [2019-02-20 10:16:18.678] [background] [info] Marking all folders as `busy`
28474 [2019-02-20 10:16:18.678] [background] [info] Syncing folder list...
28474 [2019-02-20 10:16:18.678] [metadata] [info] Metadata delta stream starting...
28474 [2019-02-20 10:16:19.104] [background] [critical] 
 ***
 *** A C++ exception occurred during program execution: 
 *** UNIQUE constraint failed: Folder.id
 ***

28474 [2019-02-20 10:16:19.125] [background] [critical]  *** Stack trace (line numbers are approximate):
 *** (unknown)  clone
 ***
```

**Comment by caputchinefrobles** [comment] 2019-04-24 18:43
Same here...

**Comment by mflu** [comment] 2019-04-28 07:12
same here, 1.6.1-aceed8e5

**Comment by nlzet** [comment] 2019-05-06 05:45
Same: 

DavMail gateway 5.2.0-2961
Mailspring: 1.6.1

    9207 [2019-05-06 07:44:28.706] [main] [info] Identity created at 1554188816 - using ID Schema 1
    9207 [2019-05-06 07:44:28.708] [main] [info] ------------- Starting Sync ([redacted]) ---------------
    9207 [2019-05-06 07:44:28.712] [metadata] [info] Metadata delta stream starting...
    9207 [2019-05-06 07:44:28.712] [background] [info] Marking all folders as `busy`
    9207 [2019-05-06 07:44:28.712] [background] [info] Syncing folder list...
    9207 [2019-05-06 07:44:28.972] [background] [critical] 
     ***
     *** A C++ exception occurred during program execution: 
     *** UNIQUE constraint failed: Folder.id
     ***

    9207 [2019-05-06 07:44:28.983] [background] [critical]  *** Stack trace:
     ***   clone
     ***

**Comment by nlzet** [comment] 2019-05-06 09:30
Some extra info:

I got it working by using WebDav instead of EWS in the DavMail gateway settings.
I believe this is a Exchange 2007 version that is giving trouble on EWS.

**Comment by revelous** [comment] 2019-08-23 14:38
Same. I'm using 0365Interactive protocol on davmail (version 5.3.1). Mailspring snap (version 1.6.3) on Ubuntu 18.04:

```
20845 [2019-08-23 09:32:29.983] [main] [info] Identity created at 1554150817 - using ID Schema 1
20845 [2019-08-23 09:32:29.985] [main] [info] ------------- Starting Sync (<redacted>) ---------------
20845 [2019-08-23 09:32:29.988] [background] [info] Marking all folders as `busy`
20845 [2019-08-23 09:32:29.988] [background] [info] Syncing folder list...
20845 [2019-08-23 09:32:29.988] [metadata] [info] Metadata delta stream starting...
20845 [2019-08-23 09:32:30.785] [background] [critical] 
 ***
 *** A C++ exception occurred during program execution: 
 *** UNIQUE constraint failed: Folder.id
 ***

20845 [2019-08-23 09:32:30.794] [background] [critical]  *** Stack trace:
 ***   clone
 ***
```

**Comment by gdyr** [comment] 2019-10-04 01:06
Same here - EWS on davmail (5.3.1-3079) + Mailspring (1.6.3-134a0e55).
Haven't found a viable alternative on Linux for O365 + GMail w/ unified inbox.
Current showstopper for making Linux a daily driver OS.

`16006 [2019-10-04 11:02:35.423] [main] [info] Identity created at 1549235868 - using ID Schema 1
16006 [2019-10-04 11:02:35.424] [main] [info] ------------- Starting Sync (michaelg@tag.com.au) ---------------
16006 [2019-10-04 11:02:35.427] [metadata] [info] Metadata delta stream starting...
16006 [2019-10-04 11:02:35.427] [background] [info] Marking all folders as `busy`
16006 [2019-10-04 11:02:35.427] [background] [info] Syncing folder list...
16006 [2019-10-04 11:02:36.220] [background] [critical] 
 ***
 *** A C++ exception occurred during program execution: 
 *** UNIQUE constraint failed: Folder.id
 ***

16006 [2019-10-04 11:02:36.243] [background] [critical]  *** Stack trace (line numbers are approximate):
 *** (unknown)  clone
 ***`

**Comment by gdyr** [comment] 2019-10-04 01:10
Same here - EWS on davmail (5.3.1-3079) + Mailspring (1.6.3-134a0e55).
Haven't found a viable alternative on Linux for O365 + GMail w/ unified inbox.
Current showstopper for making Linux a daily driver OS.

```16006 [2019-10-04 11:02:35.423] [main] [info] Identity created at 1549235868 - using ID Schema 1
16006 [2019-10-04 11:02:35.424] [main] [info] ------------- Starting Sync (<redacted>) ---------------
16006 [2019-10-04 11:02:35.427] [metadata] [info] Metadata delta stream starting...
16006 [2019-10-04 11:02:35.427] [background] [info] Marking all folders as `busy`
16006 [2019-10-04 11:02:35.427] [background] [info] Syncing folder list...
16006 [2019-10-04 11:02:36.220] [background] [critical] 
 ***
 *** A C++ exception occurred during program execution: 
 *** UNIQUE constraint failed: Folder.id
 ***

16006 [2019-10-04 11:02:36.243] [background] [critical]  *** Stack trace (line numbers are approximate):
 *** (unknown)  clone
 ***```

**Comment by wullli** [comment] 2019-10-29 19:30
For everyone experiencing this:

Looking at the mailsync log there seems to be a constraint on unique folder names in the underlying database. Try to delete all duplicate folders you might have in on your exchange account also look if there is any deleted folders in the trash/bin and remove them. 

This fixed it for me.

**Comment by michaelaye** [comment] 2020-06-16 01:42
i have a davmail daemon running and Thunderbird successfully synced with it to my Exchange account. But trying to use Mailspring for the same account it fails with same errors as @gdyr .

**Comment by atomtm** [comment] 2020-08-24 19:42
Same problem here! Thunderbirds works correctly with DavMail , however Mailspring is not able to sync

**Comment by HaNNiBaL80** [comment] 2020-10-09 20:53
Same here aswell, thunderbird is fine, but Mailspring 1.7.8 fails to sync, 
got the  "*** UNIQUE constraint failed: Folder.id" error to

**Comment by BrunoSpy** [comment] 2020-10-27 09:51
[mailsync-8b5d9f4d.log](https://github.com/Foundry376/Mailspring/files/5444342/mailsync-8b5d9f4d.log)

Same issue here. No problem with Thunderbird.

**Comment by Antiloop-git** [comment] 2020-11-24 07:28
> For everyone experiencing this:
> 
> Looking at the mailsync log there seems to be a constraint on unique folder names in the underlying database. Try to delete all duplicate folders you might have in on your exchange account also look if there is any deleted folders in the trash/bin and remove them.
> 
> This fixed it for me.

Many thanks.
One more clarify... you have to delete mailspring folder direct in your Echange account (it appears in your account after a failed synchronization attempt at the beginning of the settings)

**Comment by CodeMouse92** [comment] 2021-02-02 03:04
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/syncfolderuidrange-errorconnection-on-one-of-the-folders/412/2

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-02 03:04 UTC
Labels: bug, migrated
