### ISSUE TITLE
Bug: Mailspring auto-updates without user consent

### ISSUE THREAD

**Issue by kzadora** [Foundry376/Mailspring#2009] opened 2020-05-24 00:36 UTC
Dismissing the notification about new Mailspring version has no effect--Mailspring auto-updates itself upon restart without asking the user.

**To Reproduce**
1. Install Mailspring 1.7.6
2. Receive notification about new version (1.7.7)
3. Hit **Dismiss** (not Update)
4. Restart Mailspring

**Expected behavior**
Mailspring should just start 

**Actual behavior**
Mailspring silently auto-updates itself to 1.7.7.

**Setup: (please complete the following information):**
 - OS: Windows 10 Version 2004
 - Mailspring Version: 1.7.6

**Additional context** 
This is unacceptable behavior--if the user did not consent to auto-update, it should not happen. There might be valid reasons, e.g. work-stopping bugs [like this one](https://github.com/Foundry376/Mailspring/issues/1996) that would make the user want to stay with the older version till the bug is fixed.

I was looking for a setting to disable the auto-update behavior, but there does not seem to be any--did I miss something?

**Comment by kzadora** [comment] 2020-05-24 01:02
Found a workaround:

```shell
cd %LOCALAPPDATA%\Mailspring
del Update.exe
```

**Comment by bengotow** [comment] 2020-05-24 20:27
Hey! Thanks for reporting this—I'm taking a look at that bug you referenced today. 

I'll see if we can support unsubscribing from updates in the future, but in the past (for less showstopping bugs), this behavior has been super important. 

I'm the only maintainer of Mailspring and moving the entire user base to the latest version of the app lowers support / github issue volume tremendously because I don't have to deal with people emailing me about bugs that have already been fixed. I actually spent a few months integrating the app with Snapcraft on linux so that this same "auto-update within 24 hours" behavior works across major linux distros. It's been a lifesaver.

**Comment by kzadora** [comment] 2020-05-25 03:26
@bengotow thanks for quick reply! I totally see why auto-updating by default is better for pretty much everybody and I would not mind reasonably frequent nudge to update if running an old version (e.g. once a week?) My point is just that if I choose not to update, the program should respect my choice.

I love Mailspring BTW. Let me know if I can help with anything ☺️

**Comment by CodeMouse92** [comment] 2021-03-02 00:26
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mailspring-auto-updates-without-user-consent/899

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@kzadora: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 00:26 UTC
Labels: audit, bug
