### ISSUE TITLE
Horizontal scrollbars remain white in dark mode

### ISSUE THREAD

**Issue by khvorov45** [Foundry376/Mailspring#2137] opened 2020-09-06 20:52 UTC
**Describe the bug**

Horizontal scrollbars remain white in dark mode.

**To Reproduce**

1. Activate dark mode
2. Receive an email whose width is greater than panel width

**Expected behavior**

Expected horizontal scrollbars to be dark in dark mode.

**Screenshots**

![Screenshot from 2020-09-07 06-38-11](https://user-images.githubusercontent.com/44919476/92335049-8ac42780-f0d6-11ea-9b2e-8b925725fd51.png)

**Setup: (please complete the following information):**
 - OS: Linux Mint
 - OS Version 20
 - Mailspring Version: 1.7.8

**Comment by CodeMouse92** [comment] 2021-03-03 02:40
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/horizontal-scrollbars-remain-white-in-dark-mode/951

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@khvorov45: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-03 02:40 UTC
Labels: audit, bug
