### ISSUE TITLE
[Feature Request] Open eml and msg files

### ISSUE THREAD

**Issue by agurz** [Foundry376/Mailspring#264] opened 2017-10-27 15:13 UTC
**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Outlook

**Comment by bengotow** [comment] 2017-10-28 00:25
Hey! What is the purpose of these files? Why should Mailspring open them? Gonna close this until there's a reason provided.

**Closed by bengotow** 2017-10-28 00:25 UTC

**Comment by agurz** [comment] 2017-10-28 13:44
Hey @bengotow, sorry for the short description, I thought those email file formats were more popular. 

Both are file formats used by Microsoft Outlook to save an email. `eml` is the format to save an email message in MIME RFC 822 format, and it's also used in other mail client such as Apple Mail.

Here are some links that provide more info:

https://fileinfo.com/extension/eml
https://fileinfo.com/extension/msg

Cheers!

**Comment by carlosmichelin** [comment] 2017-10-31 03:35
Hi.

There are workspaces that use `.msg` and `.eml` files as attachments, like user requests, system request, bug evidence, etc. Would be very useful can open these formats in Mailspring.

Where I work today people love to use `.msg` files instead of a more universal format as `.pdf` :disappointed:. Although `.eml` would be great too, since is more acceptable by e-mail applications.

**Comment by adamkruszewski** [comment] 2018-03-19 08:09
The "eml" file format is actually the most common email file type, thunderbird saves them by default. And if one wants to archive a one particular e-mail to disk, there have to be an option to save the message to file. It is very common in enterprise use that one have to transfer email to at least some file format, for example to attach it into CRM or ERP software used.

The best thing it is you can just dump the output you get from IMAP/POP3 server and you'll get an eml file.

Hopefully Mailspring will get saving and opening functionality for eml files.

**Comment by rosefresh** [comment] 2019-04-10 06:35
<a href ="http://www.vooksoftware.com/eml-to-msg/">VOOK EML to MSG Converter</a> is one of the best converter by which user can easily export bulk EML file to MSG format without any error It does not require any installation of MS Outlook to convert the EML files to MSG format. It supports all versions of Windows to export EML file to MSG Format.

To know More Information,Click Here  https://writeapp.me/stevesmith27/note/batch-convert-eml-to-msg-with-attachments

**Comment by rosefresh** [comment] 2019-05-24 10:03
There are multiple third party tools available on the internet, you just need to find right solution. I have used <a href ="https://www.zooksoftware.com/eml-to-msg/">ZOOK EML to MSG Converter</a> tool when I required same issue and got accurate result. This is download link of software, download from here (https://www.zooksoftware.com/eml-to-msg/)

**Comment by CodeMouse92** [comment] 2021-01-28 02:00
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/export-copy-backup-emails/325

@carlosmichelin @adamkruszewski: if you reply to that thread, the moderators can make an effort to reassign your migrated posts to you.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team
