### ISSUE TITLE
Error Message on editing Mail Body

### ISSUE THREAD

**Issue by intradesign** [Foundry376/Mailspring#723] opened 2018-02-25 11:16 UTC
While editing the email body the following error message was displayed:
Error: Failed to execute 'setStart' on 'Range': The offset 4294967295 is larger than the node's length (15).
    at findDOMRange (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/slate-react/lib/utils/find-dom-range.js:37:5)
    at Content._this.updateSelection (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/slate-react/lib/components/content.js:154:46)
    at Content._this.componentDidUpdate (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/slate-react/lib/components/content.js:121:13)
    at commitLifeCycles (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:149:308)
    at b (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:158:229)
    at m (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:169:217)
    at w (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:168:413)
    at batchedUpdates (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:171:357)
    at tc (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:54:269)
    at vd (/Applications/Mailspring.app/Contents/Resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:71:249)

What I did was: Typing several pararaphs. Then I wanted to mark 4 line with Shift-Arrow-Down to apply a bold format. Instead of marking the lines below the current cursor position in the editing area the messages below the current message in the messages panel were marked and the error message appeared.

<img width="1140" alt="mailspring 2018-02-25 12-15-16" src="https://user-images.githubusercontent.com/21263208/36640783-aec5f54e-1a25-11e8-8d25-89ae60a5f714.png">

**Comment by bengotow** [comment] 2018-02-26 19:42
Hey! Thanks for reporting this - this is a pretty nasty issue. I'll see if we can get this fixed - there have been some updates to Slate since we released the new editor and we need to incorporate those fixes in.

**Comment by Tamriel** [comment] 2018-02-28 11:08
I got this, too:

Error: Failed to execute 'setStart' on 'Range': The offset 4294967293 is larger than the node's length (4).
    at findDOMRange (/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/utils/find-dom-range.js:37:5)
    at Content._this.updateSelection (/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/content.js:154:46)
    at Content._this.componentDidUpdate (/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/content.js:121:13)
    at commitLifeCycles (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:149:308)
    at b (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:158:229)
    at m (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:169:217)
    at w (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:168:413)
    at batchedUpdates (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:171:357)
    at tc (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:54:269)
    at vd (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:71:249)

**Comment by tzar** [comment] 2018-03-01 04:14
Happened to me too - on the first email I've ever tried to write with mailspring no less ☹ the only formatting I had used was a bullet point list..

**Comment by jnylen** [comment] 2018-03-01 14:13
Happens for me too.

**Comment by grolinux** [comment] 2018-03-12 04:07
Same here. Happens to me.

Error: Failed to execute 'setStart' on 'Range': The offset 4294967295 is larger than the node's length (9).
    at findDOMRange (/snap/mailspring/180/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/utils/find-dom-range.js:37:5)
    at Content._this.updateSelection (/snap/mailspring/180/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/content.js:154:46)
    at Content._this.componentDidUpdate (/snap/mailspring/180/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/content.js:121:13)
    at commitLifeCycles (/snap/mailspring/180/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:149:308)
    at b (/snap/mailspring/180/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:158:229)
    at m (/snap/mailspring/180/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:169:217)
    at w (/snap/mailspring/180/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:168:413)
    at batchedUpdates (/snap/mailspring/180/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:171:357)
    at tc (/snap/mailspring/180/usr/share/mailspring/reso

**Comment by jyboudreau** [comment] 2018-03-12 20:03
Happens to me as well. I noticed this always happens when I try to navigate the text with keyboard arrow keys.

**Comment by jyboudreau** [comment] 2018-03-12 20:07
Possibly related to https://github.com/ianstormtaylor/slate/issues/710 ?

**Comment by sonufrienko** [comment] 2018-04-16 09:51
I have this error too on edit
![bug](https://user-images.githubusercontent.com/16773498/38802349-e1c2c9e2-4174-11e8-8c13-b36bd19d1d4d.png)

**Comment by jmgiaever** [comment] 2018-05-24 12:48
Happend here too today. V 1.2.1-7e7747b6

**Comment by joaofar** [comment] 2018-06-11 02:36
happened to me just now... after having composed a whole email... can't seem to access it again.
Think it was the arrow keys as well.

This is a major no no.
It's basic functionality we're talking here, if there's a chance this could happen when composing an email...

**Comment by crazylive** [comment] 2018-11-15 08:19
i think you used table in html.
i get this bug as: https://gist.github.com/crazylive/911953db4ca90db3c47b3dfb6133e515

and i don't know as it works but simple solution is wrap ckeditor to table, sample:
https://gist.github.com/crazylive/040aa95f4d980230cd776a60ff00603a

**Comment by bengotow** [comment] 2019-03-17 17:04
Going to merge this in to #921 - I've been hoping we can upgrade to a new version of Slate for a while now, but there are a few performance regressions that still need to be fixed in Slate. Hopefully this can be fixed soon.

**Closed by bengotow** 2019-03-17 17:04 UTC
Labels: bug, composer
