### ISSUE TITLE
"Error: Cannot find module '../dialog'" when launching mailspring a second time

### ISSUE THREAD

**Issue by Bouska** [Foundry376/Mailspring#152] opened 2017-10-13 17:11 UTC
I'm running MailSpring 1.0.4 on Fedora 26. This is kind of a paper cut bug : if an mailspring instance is already running and I launch `mailspring` on a terminal, I get the following error: 
```
[pablo@beta ~]$ mailspring
Exiting because another instance of the app is already running.
module.js:472
    throw err;
    ^

Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/usr/share/mailspring/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as dialog] (/usr/share/mailspring/resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.<anonymous> (/usr/share/mailspring/resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:96:13)
    at process.emit (events.js:191:7)
    at process._fatalException (bootstrap_node.js:308:26)
```

**Comment by bengotow** [comment] 2017-10-17 01:54
Hey! Thanks for reporting this - I've been able to reproduce it on my Fedora VM. It actually seems like this is coming from Electron itself, which is pretty odd.

Edit: It looks like it's this issue, but they've closed it there: https://github.com/electron/electron/issues/2488.

**Comment by bengotow** [comment] 2017-10-20 18:40
This should be fixed in the next release!

**Closed** 2017-11-02 18:18 UTC
Labels: done-pending-release
