### ISSUE TITLE
OSX Text Replacement support

### ISSUE THREAD

**Issue by story1234** [Foundry376/Mailspring#1716] opened 2019-11-20 00:48 UTC
<img width="673" alt="Screen Shot 2019-11-19 at 4 42 03 PM" src="https://user-images.githubusercontent.com/34608268/69199265-51411200-0aec-11ea-8c8a-baedd6bdc7ce.png">

Hello.  Just started using your mail app.  I've always used Outlook or Mail and they support the Text Replacement.  It doesn't seem to work for MailSpring.  It's quite useful for iPhone texting, iPad email etc.

**Comment by bengotow** [comment] 2019-12-02 16:41
Hey! Oh this is cool—I haven't really seen anyone use this macOS feature like this before. I'll see if we can add support for these text expansions soon.

**Comment by CodeMouse92** [comment] 2021-02-13 00:03
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/osx-text-replacement-support/599

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@story1234: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-13 00:03 UTC
Labels: audit, enhancement
