### ISSUE TITLE
Bug: Scrollbar appears even when there is not enough content to scroll

### ISSUE THREAD

**Issue by squintgit** [Foundry376/Mailspring#1956] opened 2020-05-01 04:51 UTC
**Describe the bug**
Just find it not very attractive that when you hover your mouse over the sidebar, even if there's not enough text there to where you can scroll down, it still shows the scroll bar. I think it would look better if the scroll bar only appeared if you had enough text in your sidebar to make it scrollable.

**To Reproduce**
1. Using an account that doesn't have a lot of folders (not enough to make the sidebar "scrollable"), put your mouse over the sidebar
2. Scroll bar will briefly appear then disappear

I expected the scroll bar to not appear because there's not enough text there to make it scrollable.

Strangely, the scroll bar appears in different opacities/colors as well. This is depicted in the video. I am using the Dark theme as you can see.

**Screenshots**
Trying to attach video.
[folders.mov.zip](https://github.com/Foundry376/Mailspring/files/4562529/folders.mov.zip)

**Setup: (please complete the following information):**
 - OS: macOS
 - OS Version 10.14.6
 - Mailspring Version: Version 1.7.6 (1.7.6)

**Additional context** 
Mailspring is my favorite mail client and I've used them all...  Tempo, Canary Mail, Edison, Airmail, Outlook, Spark, Postbox, Apple Mail, Thunderbird, and so on...   I'm new to Linux and although I don't use my Linux computer for too much yet, I'm interested in it, and I like that Mailspring works there. I'm looking forward to the iOS app.

**Update!** : I just switched to this theme which is the best one I've found (forgot I was using this on Linux): https://github.com/jpminor/mailspring-isaac-dark-theme/blob/master/README.md

Same weird scroll bar behavior happens in that theme so I think it's an app thing. The scrollbar is less noticeable in this theme (which I usually don't like... I love wide scrollbars that are easy to grab!).

P.S. I wish this Isaac theme was the default Dark theme. It's great! Maybe ask the author if it can be included in Mailspring?

**Comment by CodeMouse92** [comment] 2021-02-23 22:24
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/scrollbar-appears-even-when-there-is-not-enough-content-to-scroll/748

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@squintgit: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-23 22:24 UTC
Labels: audit, bug
