### ISSUE TITLE
Using images for full signature

### ISSUE THREAD

**Issue by EnigmaZA** [Foundry376/Mailspring#538] opened 2018-01-16 18:08 UTC
hi all,

would be great if one could use a single jpeg to sign the emails we send out.

in my case i have a jpeg from the company i work with that includes all my details in the image, but when i import it as my signature it compresses the image to make space for all the text details you can input manually. example is inserted below, the first image is what i get in mailsring and the second is what it should look like.
![screenshot from 2018-01-16 20-05-36](https://user-images.githubusercontent.com/12070020/35004418-af0d6358-faf8-11e7-885a-8415b2e97214.png)
![screenshot from 2018-01-16 20-07-42](https://user-images.githubusercontent.com/12070020/35004508-faf17610-faf8-11e7-9c1b-1801942af0e7.png)

regards,
Daniele Finezzi

**Comment by jenguidanos** [comment] 2018-01-17 11:47
I'm in the same situation. You can edit the signature template to use Raw HTML and edit the format. The problem is that the image is uploaded to the Mailspring servers and included in the email with a link. I think it would be better to add the image to the body of the message and avoid the image blocking function of most email clients. Currently you can replace the Mailspring image url with one from your server.

**Comment by bengotow** [comment] 2018-01-18 01:30
Ahh nice! This is a good use case I hadn't thought of - I'll see if we can add another signature option that is just "full-size image" in the future. Right now the images are intentionally sampled way down when they're uploaded, so unless you host the image on your own it'll look a little blurry. Stay tuned—

**Comment by DewaldDeJager** [comment] 2018-06-28 08:20
I resolved this by encoding the signature image as base64 and embedding it in the raw HTML.

**Comment by davidsharp** [comment] 2020-01-02 11:21
@DewaldDeJager, did this actually work? From my poking around, it seems it shows in the preview, but it doesn't arrive in any emails. Maybe this behaviour is specific to Gmail?

**Comment by DewaldDeJager** [comment] 2020-01-02 12:55
> @DewaldDeJager, did this actually work? From my poking around, it seems it shows in the preview, but it doesn't arrive in any emails. Maybe this behaviour is specific to Gmail?

It's been a while but I'm fairly sure it worked. I ended up moving to Hiri not too long after starting to use Mailspring anyways.

**Comment by KayahanKahriman** [comment] 2020-04-16 10:33
> 
> 
> > @DewaldDeJager, did this actually work? From my poking around, it seems it shows in the preview, but it doesn't arrive in any emails. Maybe this behaviour is specific to Gmail?
> 
> It's been a while but I'm fairly sure it worked. I ended up moving to Hiri not too long after starting to use Mailspring anyways.

I moved out EmClient too since this issue isnt solved.

**Comment by CodeMouse92** [comment] 2021-02-24 21:52
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/using-images-for-full-signature/769

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@EnigmaZA @jenguidanos: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-24 21:52 UTC
Labels: audit, enhancement
