### ISSUE TITLE
Only <100 messages are displayed, older unread missing

### ISSUE THREAD

**Issue by p3k** [Foundry376/Mailspring#1634] opened 2019-09-16 21:12 UTC
##### Are there any related issues?

Yes, #806 and #1143 – but they are rather about inconsistent display of the number of unread messages and the actual displayed unread messages.

##### What operating system are you using?

Regolith Linux (Ubuntu 18.04.3 LTS)

##### What version of Mailspring are you using?

1.6.3-134a0e55

--

**Bug?**

##### Is this an email sync or connection issue?

No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

No

**Comment by p3k** [comment] 2019-09-16 21:23
Even if I scroll down to the very bottom of the message list, no more mails are loaded. I am missing unread messages which are older than the last one in this last and don’t know how to achieve this. In consequence, I am fooled to think I have less unread messages (= todos) than there actually are.

**Comment by aznwannabie** [comment] 2019-09-23 18:11
I have the same issue, but only for some email accounts.. A couple of accounts I can pull till the beginning of time, but some I only have 100 emails regardless of read/unread.

Is there a reason for this?

**Comment by nfaivre** [comment] 2019-09-24 07:05
Same here, this happens for a zimbra but not gmail account, on ubuntu 19.04, mailspring 1.6.3-134a0e55

**Comment by seasidepb** [comment] 2019-09-26 09:15
I have a similar issue (on the Windows version), but found I could solve it easily by refreshing the cache (in account settings). However I'm having to repeat this pretty well every day, which is irritating. I've raised the issue with Mailspring and I'm waiting for an answer.

**Comment by p3k** [comment] 2019-10-12 12:24
@aznwannabie @nfaivre @seasidepb could you please click on the thumbsup icon under my original post? this could make the developers more aware of the issue. thanks :smile_cat:

**Comment by 3mkay** [comment] 2020-07-24 10:37
#1948 seems to be the same issue. 

I get the error only on Zimbra accounts.

**Comment by CodeMouse92** [comment] 2021-02-18 01:05
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/only-100-messages-are-displayed-older-unread-missing/684

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@p3k @adriangrantdotorg @nfaivre @seasidepb @3mkay: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-18 01:05 UTC
Labels: bug, mailserver-incompatibility, migrated
