### ISSUE TITLE
Bug: Cant login on Fedora 32 & 33 (rpm file)

### ISSUE THREAD

**Issue by tosziro** [Foundry376/Mailspring#2188] opened 2020-10-30 06:59 UTC
When I launch app I got stack on Create Mailspring identificator. On that page I cant do anything, writing box and buttons are inactive and i cant login or create account. 

**To Reproduce**
1.  Install app from RPM file
2. Run application
3. Try to create account/login
4. See nothing happens

**Expected behavior**
Create account or login

**Setup: (please complete the following information):**
 - OS: Fedora Linux 33 GNOME
 - OS Version [e.g. 14]
 - Mailspring Version: various versions ( I tried some older builds and they act same)

**Comment by CodeMouse92** [comment] 2021-01-29 21:08
Hi all,

2020 prevented much development work on Mailspring, but rest assured, development has resumed! We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

@tosziro: Can you please confirm that this is still broken with 1.8.0, and if so, open a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-29 21:08 UTC
Labels: audit, bug
