### ISSUE TITLE
Add TNEF support

### ISSUE THREAD

**Issue by salaros** [Foundry376/Mailspring#807] opened 2018-04-05 16:59 UTC
Implement TNEF ([Transport Neutral Encapsulation Format](https://en.wikipedia.org/wiki/Transport_Neutral_Encapsulation_Format)) support in Mailspring

##### What operating system are you using?
Linux (Ubuntu 18.04 amd64)

##### What version of Mailspring are you using?
Any

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Please try sending an email containing event, images etc attached from Outlook 2016

--

**Feature Request?**
yeap

##### Does this feature exist in another mail client or tool you use?
Partially implemented in Thunderbird via [Lookout addon(s)](https://addons.mozilla.org/en-US/thunderbird/search/?q=Lookout)

**Comment by bengotow** [comment] 2018-07-08 08:12
Ahh this is an interesting one—it looks like we can essentially "unpack" the .dat file and it gives us the real file within it? If we can find a tool on that page that has an open / GNU license we could probably bundle it or it's code with Mailspring.

**Comment by CodeMouse92** [comment] 2021-02-20 03:10
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/add-tnef-support/712

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@salaros: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-20 03:10 UTC
Labels: audit, enhancement
