### ISSUE TITLE
Bug: can't download files or forward attachments.

### ISSUE THREAD

**Issue by greenisagoodcolor** [Foundry376/Mailspring#2253] opened 2021-01-13 00:04 UTC
Can't download files or forward attachments. How can i recreate those files?

![image](https://user-images.githubusercontent.com/7354163/104389151-c9487380-5508-11eb-9f60-34c0b63df170.png)

**Comment by greenisagoodcolor** [comment] 2021-01-13 00:11
if you fix this, i'll sign up for pro.

**Comment by greenisagoodcolor** [comment] 2021-01-13 20:37
I've tried reinstalling the package too using pacman and the AUR (archlinux/xfce).

**Comment by Phylu** [comment] 2021-01-14 11:08
Hi @greenisagoodcolor,
can you please try to rename the directory `/home/matt/.config/Mailspring` (e.g. to /home/matt/.config/Mailspring.bak)? Afterwards, you will need to recreate the e-mail accounts. You may also try going to Preferences > Accounts > Rebuild Cache and see if that helps.

**Comment by CodeMouse92** [comment] 2021-01-17 03:38
Hi @greenisagoodcolor,

In order to diagnose this bug, we're going to need the additional information requested in the bug report template, especially environment information.

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

**Please open a bug report there, and follow the provided template as best as you can.** You're welcome to copy/paste information from this issue. By doing that, you'll be helping us address this sooner.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

**Closed by CodeMouse92** 2021-01-17 03:38 UTC
Labels: audit, bug
