### ISSUE TITLE
Last update issue

### ISSUE THREAD

**Issue by elodienadreau** [Foundry376/Mailspring#1837] opened 2020-03-02 16:39 UTC
Hello, since the last update, Mailspring disconnect all the time, and most of the time, when I try to send an email I have an error message :

Error 
"Désolée, Mailspring n'a pas pu transmettre ce message: Erreur de connexion-impossible de se connecter au serveur port que vous avez fourni."

FYI I didn't change any settings and it used to run perfectly before the update. Please help me because I can't use my mailbox if I'm not able to send anything.

[](url)
![2020-03-02](https://user-images.githubusercontent.com/11644532/75697099-e5ef0a80-5cac-11ea-874e-2998c3ace2cd.png)

**Comment by elodienadreau** [comment] 2020-03-02 16:40
![2020-03-02](https://user-images.githubusercontent.com/11644532/75697055-d5d72b00-5cac-11ea-809b-4b2789d7d367.png)

**Comment by enteropositivo** [comment] 2020-03-04 07:47
I had to downgrade to previous version (1.7.3) because i have a lot of problems when i reply an email.

**To test:**

- Reply an email
- If i want to reply with other alias, change the from account or alias to other from the list

Then i can not write anything



**Other issue:**

I can not open new draft emails generated with last version

**Comment by CodeMouse92** [comment] 2021-01-29 23:16
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

@elodienadreau or @enteropositivo: Can you please confirm that this is still broken with 1.8.0, and if so, open a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-29 23:16 UTC
Labels: audit
