### ISSUE TITLE
Right-click->send via mail opens new email dialog but doesn't attach file KDE Neon (Dolphin File Explorer)

### ISSUE THREAD

**Issue by Furqan136** [Foundry376/Mailspring#1319] opened 2019-01-11 11:50 UTC
##### Operating system
KDE Neon 5.14(Latest)

##### Mailspring version
1.5.5-b7939d38

**Bug?**

##### Is this an email sync or connection issue?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Yes

##### Issue:
In Dolphin (KDE's File Explorer) When I right click a file and choose send via mail (I have KDE set as default mail) a new mail dialog box opens but that file is not attached. This is very trivial and handy feature and should work. Please release a fix.
Thanks.

**Comment by Sytred** [comment] 2019-01-16 14:50
Doesn't work either with Nautilus in Ubuntu 18.04 (Gnome).

**Comment by Furqan136** [comment] 2019-04-20 22:54
@boffbowsh @sleeper @adrianmester Please look into it. It has to be one of the most important parts of the program.

**Comment by CodeMouse92** [comment] 2021-02-16 00:55
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/right-click-send-via-mail-opens-new-email-dialog-but-doesnt-attach-file-kde-neon-dolphin-file-explorer/644

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@Furqan136 @Sytred: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-16 00:55 UTC
Labels: audit, linux
