### ISSUE TITLE
[Feature Request] Don't Sync All of All Mail

### ISSUE THREAD

**Issue by Modelmat** [Foundry376/Mailspring#222] opened 2017-10-20 21:01 UTC
##### Are there any related issues?
Possibly #158 
...

##### What operating system are you using?
Windows 10
...

##### What version of Mailspring are you using?
1.0.5
...

--

**Feature Request?**

Is it possible only to sync the last few days of "All Mail"?. I have like 5GB in there and it is slowly syncing it all?

##### Does this feature exist in another mail client or tool you use?
Yes, outlook (sortof, they only sync inbox)
...

**Comment by bengotow** [comment] 2017-10-21 07:19
Hey! Unfortunately with Gmail accounts, "All Mail" is necessary because all of your labels are actually subsets of All Mail. (So syncing only three days of All Mail would mean only three days of mail in your labels too.)

That said, there's a configuration option I haven't exposed yet that will let you limit sync to say "the last six months" or the last year of mail. The client won't download it, won't sync it, won't index it for search, etc. Right now it doesn't seem like it's a huge feature request, but if we get more upvotes here I'll prioritize getting the UI in place!

**Comment by Modelmat** [comment] 2017-10-21 09:33
That feature would work!

**Comment by dakira** [comment] 2017-10-23 12:42
@bengotow are the emails currently actually downloaded or just their headers?

**Comment by CodeMouse92** [comment] 2021-02-15 19:44
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/dont-sync-all-of-all-mail/626

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@Modelmat: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-15 19:44 UTC
Labels: audit, enhancement
