### ISSUE TITLE
cannot setup IMAP account 

### ISSUE THREAD

**Issue by vfeshenko** [Foundry376/Mailspring#2236] opened 2020-12-21 10:39 UTC
Hi, I would like to test Mailspring for my company. I can't create an imap account for my mail server, because my smtp check fails.
External forwarding is closed on my server, mail forwarding is possible only within the domain. Mailspring, apparently, when verifying an account, tries to send an email to email@invalid.com and naturally receives acces denied from the server. On this I get a softlock and I cannot skip this stage.

**OS:** Windows Server 2016
**Version:** 1.7.8-13635bcf

> ----------SMTP----------
> 220 mail.test.net ESMTP Postfix
> OpenSSL version: OpenSSL 1.1.0f  25 May 2017
> init
> EHLO RDS-2
> 250-mail.test.net
> 250-PIPELINING
> 250-SIZE 100000000
> 250-VRFY
> 250-ETRN
> 250-AUTH LOGIN PLAIN
> 250-AUTH=LOGIN PLAIN
> 250-ENHANCEDSTATUSCODES
> 250-8BITMIME
> 250 DSN
> AUTH PLAIN **************
> 235 2.7.0 Authentication successful
> MAIL FROM:<test@test.net>
> 250 2.1.0 Ok
> RCPT TO:<email@invalid.com>
> 554 5.7.1 <test@test.net>: Sender address rejected: Access denied
> 
> 
> SASL_PATH: 
> 
> SMTP Last Response Code: 554
> SMTP Last Response: 5.7.1 <test@test.net>: Sender address rejected: Access denied

**Comment by CodeMouse92** [comment] 2021-01-18 23:33
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse, and specifically to the community Help section:

https://community.getmailspring.com/t/cannot-setup-imap-account-smtp-check-fails/92

Please consider joining that community and continuing the discussion there! Bonus: if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-18 23:33 UTC
Labels: audit
