### ISSUE TITLE
Feature Request: support RFC 3676 (format=flowed)

### ISSUE THREAD

**Issue by jsamr** [Foundry376/Mailspring#2031] opened 2020-05-28 17:08 UTC
**Is your feature request related to a problem? Please describe.**

Mails formatted with `format=flowed` are not wrapped such as described in [RFC 3676](https://tools.ietf.org/html/rfc3676).

**Describe the solution you'd like**

- Soft-wrap text/plain mails as described in RFC 3676
- Offer an option to write plain text message with 'format=flowed' as described in RFC 3676

**Comment by CodeMouse92** [comment] 2021-02-12 20:41
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/support-rfc-3676-format-flowed/588

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@jsamr: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-12 20:41 UTC
Labels: audit, enhancement
