### ISSUE TITLE
Request: Sync Local Drafts to Remote Folder

### ISSUE THREAD

**Issue by johnyradio** [Foundry376/Mailspring#1417] opened 2019-03-13 05:33 UTC
steps:
- add imap account
- compose draft
- remove imap account
- re-add same imap account
- **drafts are gone**

Any way to get these drafts back??

:(

**Comment by johnyradio** [comment] 2019-03-13 05:44
**update,** after a few minutes, old drafts loaded into the Draft folder. 
However, Drafts created in Mailspring are missing. 

That really sucks. 
It means, even tho Mailspring Draft folder was pointing to remote Draft folder, locally-created drafts were not saved to remote Draft folder. 

MAJOR BUG, correct?

**Comment by johnyradio** [comment] 2019-03-21 22:47
Just lost an important Draft message, cuz i had to remove and re-add my IMAP account (due to other bugs). 

Since you don't sync Drafts bidirectionally. Plz sync Drafts bidirectionally!

**Comment by CodeMouse92** [comment] 2021-02-02 02:50
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/disappearing-emails-desync/428

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

P.S. Duplicate of #304

**Closed by CodeMouse92** 2021-02-02 02:50 UTC
Labels: audit
