### ISSUE TITLE
💡: Feature Request: Workspace like sidebar (e.g. Slack / Discord)

### ISSUE THREAD

**Issue by joe733** [Foundry376/Mailspring#1982] opened 2020-05-13 06:02 UTC
**Describe the solution you'd like**
For each account it would be good to have dedicated workspace like environment as seen in other apps like Slack / Discord.

**Describe alternatives you've considered**
The sidebar need not remain in side (lol) but like a workspace switcher.

**Additional context**

![image](https://user-images.githubusercontent.com/38415384/81776767-0b01c400-950d-11ea-8c20-989d7241eeca.png)

See that left-most sidebar...? It would be cool if those where given like GMail1, GMail2, Hotmail etc...

**Comment by CodeMouse92** [comment] 2021-03-01 23:38
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/workspace-like-sidebar-e-g-slack-discord/894

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@joe733: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-01 23:38 UTC
Labels: audit, enhancement
