### ISSUE TITLE
Bug: Line breaks and tabulators missing in "quoted printable" parts

### ISSUE THREAD

**Issue by MartinHengstberger** [Foundry376/Mailspring#1985] opened 2020-05-14 14:07 UTC
**Describe the bug**
When I receive mails with a text/plain part which is encoded with quoted printable, no linebreaks and tabulators are shown in the mail. The mails are shown as one long sentence.

e.g. I have received this Mail:

> ------=_Part_280271_608161497.1589201258354
> Content-Type: text/plain; charset=UTF-8
> Content-Transfer-Encoding: quoted-printable
> 
> Lieber Kunde,=20
> im Anhang =C3=BCbermitteln wir Ihnen Ihre aktuelle Rechnung.=20
> 
> Ihre Rechnungsdaten:=20
> Rechnungsnummer:	1231231234=20
> =46=C3=A4lligkeit:		22.05.2020=20
> Betrag:			xx.xx EUR=20
> 
> Ihre elektronische Rechnung ist f=C3=BCr Sie kostenlos in der Kundenzone au=
> f www.xxxx.at/rechnung archiviert und nach Eingabe Ihres Kundenkennworts je=
> derzeit abrufbar. Bei Bedarf finden Sie dort auch den Einzelverbindungsnach=
> weis.
> 
> Haben Sie Fragen zur Rechnung?=20
> =E2=80=A2	Eine Video-Erkl=C3=A4rung und weitere Infos zur Rechnung, insbeso=
> ndere der ersten Rechnung, finden Sie auf www.xxxx.at/rechnung1
> =E2=80=A2	Unter www.xxxx.at/service finden Sie alle unsere Kontaktm=C3=B6gl=
> ichkeiten.=20
> 
> =46reundliche Gr=C3=BC=C3=9Fe,=20
> Ihr xxxx Service-Team

**Expected behavior**
The line breaks and the tabulators should be shown even if they are not encoded in quoted printable. (Maybe you can choose also an monospaced font to align the message correctly)

**Setup: (please complete the following information):**
 - OS: Manjaro and Windows
 - Mailspring Version: 1.7.6

Best regards,
Martin

**Comment by MartinHengstberger** [comment] 2020-05-14 18:25
After some testing I think the problem only occurs when there is an attachment in the mail (text/plain inside a multipart/mixed)

**Comment by bengotow** [comment] 2020-05-24 23:00
Hey thanks for reporting this! I'm super glad to have narrowed this down actually - there are a few other threads here reporting random / infrequent issues with plaintext becoming one line, and I think that this is probably the root cause. Will dig in to this a bit!

**Comment by bengotow** [comment] 2020-05-24 23:03
Yep, was able to reproduce this using Yahoo's "mobile / low HTML mode" which sends plaintext:
<img width="722" alt="image" src="https://user-images.githubusercontent.com/1037212/82766941-e5b46600-9de8-11ea-83db-21e205ebfe47.png">

**Comment by MartinHengstberger** [comment] 2020-05-25 07:06
Thank you for fixing this issue. After erasing the cache every mail I got is rendered now with linebreaks. There is only a minor issue left:

Tabulators are missing in the plaintext mails. 

But maybe this is a desired behaviour. In Kmail Tabulators are shown but there is no monospaced font by default, so the tabulators arent helpful. In Thunderbird tabulators and monospaced font are available.

Best regards from Austria,
Martin

**Comment by CodeMouse92** [comment] 2021-02-02 23:23
It appears that this issue has been resolved, so we are closing it. If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-02 23:23 UTC
Labels: audit, bug, done-pending-release
