### ISSUE TITLE
An unexpected mailsync error occurred (134)

### ISSUE THREAD

**Issue by paulpolidoro** [Foundry376/Mailspring#808] opened 2018-04-05 18:13 UTC
System: Ubuntu 17.10
App version: Mailspring 1.2.1-7e7447b6

My SMTP server don't need authentication, so the user and password fields are empty and I get this error. 

![captura de tela de 2018-04-05 15-15-12](https://user-images.githubusercontent.com/19935973/38384176-d32ed940-38e4-11e8-9fdc-d1681f9361b4.png)

Log:

```
Waiting for Account JSON:

Waiting for Identity JSON:
info: Identity created at 1513892075 - using ID Schema 0
critical: 
 ***
 *** A JSON exception occurred during program execution: 
 *** [json.exception.type_error.302] type must be string, but is null
 ***

critical: 
 ***
 *** A JSON exception occurred during program execution: 
 *** [json.exception.type_error.302] type must be string, but is null
 ***

critical:  *** Stack trace:
 ***   void nlohmann::detail::from_json(nlohmann::basic_json const&, nlohmann::basic_json::string_t&)
 ***   decltype ((from_json({parm#1}, {parm#2})),((void)())) nlohmann::detail::from_json_fn::call(nlohmann::basic_json const&, string&, nlohmann::detail::priority_tag) const
 ***   void nlohmann::detail::from_json_fn::operator()(nlohmann::basic_json const&, string&) const
 ***   void nlohmann::adl_serializer::from_json(nlohmann::basic_json const&, string&)
 ***   string nlohmann::basic_json::get() const
 ***   Account::SMTPUsername()
 ***   MailUtils::configureSessionForAccount(mailcore::SMTPSession&, shared_ptr)
 ***   runTestAuth(shared_ptr)
 ***   main
 ***

critical:  *** Stack trace:
 ***   void nlohmann::detail::from_json(nlohmann::basic_json const&, nlohmann::basic_json::string_t&)
 ***   decltype ((from_json({parm#1}, {parm#2})),((void)())) nlohmann::detail::from_json_fn::call(nlohmann::basic_json const&, string&, nlohmann::detail::priority_tag) const
 ***   void nlohmann::detail::from_json_fn::operator()(nlohmann::basic_json const&, string&) const
 ***   void nlohmann::adl_serializer::from_json(nlohmann::basic_json const&, string&)
 ***   string nlohmann::basic_json::get() const
 ***   Account::SMTPUsername()
 ***   MailUtils::configureSessionForAccount(mailcore::SMTPSession&, shared_ptr)
 ***   runTestAuth(shared_ptr)
 ***   main
 ***

/snap/mailspring/209/usr/share/mailspring/resources/app.asar.unpacked/mailsync: line 4: 20375 Aborted                 (core dumped) SASL_PATH="$(dirname $(realpath $0))" LD_LIBRARY_PATH="$(dirname $(realpath $0));$LD_LIBRARY_PATH" "$(dirname $0)/mailsync.bin" "$@"
```

**Comment by CodeMouse92** [comment] 2021-02-02 01:22
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/gmail-mailsync-134/422

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-02 01:22 UTC
Labels: audit
