### ISSUE TITLE
attached files are not sent

### ISSUE THREAD

**Issue by franco27** [Foundry376/Mailspring#1438] opened 2019-03-25 16:23 UTC
on Windows 10 - Mailspring 1.6.0 (I already had this same problem several times with version 1.5.7)

1/ I am writing a new message or I am writing a reply
2/ I attach files.  (small files size: less than 1 MB)
I select several files at the same time, only 2 or 3 files.
the problem occurred with files .pdf or .png

3/ then in the "new message" window or when I answer, I can see the attached files

4/ when I click on the "Send" button, the message is sent without including the attached files
I can also see in the "Sent" folder, that this message has no attached file

The trouble is that this problem is not repeated (the other days), and I do not know why there is this problem.

when the problem occurs, I'm blocked. I tried to solve it:
1/ I restart Mailspring, but when I send again message with attached files. I have the same situation, the message is sent without the attached files.

I don't think it's related to a server problem, on the email side because that same day and same time, when I use another mail client with the same sending settings , I don't have this problem and the attached files (the same ones) are included in the sent message.

This problem is not regular or not every time.  This problem is with all my email accounts but irregularly.

**Comment by bengotow** [comment] 2019-03-26 15:46
Hey! Thanks for reporting this, this is really interesting. It sounds like this is happening with a specific couple attachments that you have? I think this might be due to the permissions on the files, or something about their filenames or paths. Could you post the full paths to the files you dropped on the composer here? Curious whether something about them is throwing off the app.

I agree it's definitely not a server problem - I think Mailspring should also be complaining if the files do not exist when it goes to send, so I think it might be a permissions issue of some sort.

**Comment by franco27** [comment] 2019-03-26 18:03
This time it was with 2 files .png small sizes (25 KB and 490 KB). these files are located in the "images" folder of Windows10.  (C:\Users\francois\Pictures\2019-03-25_14-12-26.png) 

or C:\Users\francois\Documents\ShareX\Screenshots\2019-03\2019-03-03_17-04-15.png

Last time with 2 PDF files that I couldn't send (still less 1MB)
(C:\Users\francois\Desktop\feuille_fevrier.pdf) scanned and created by printer CANON

What I don't understand is, when there is a problem, on the same day or at the same time, I can repeat the problem. (impossible to send attached files)

I even assumed that this problem only occurred when I selected several files at the same time in the file explorer. But no because I imported 1 file and then another file, and the problem was still there when sending.

And another day, I will be able to send attached files without this malfunction. Usually at the same locations.

**Comment by mikerisher** [comment] 2019-03-27 17:00
Hello,

I'm also seeing this on Ubuntu 18.04 with the Mailspring 1.6.0 Snap on a Google account. For me this is isolated to the "New Message" compose window. Adding attachments in an existing thread seems to work.

In the "New Message" window everything looks like it works, including showing a preview of the image, etc. However there is no attachment when the message is actually sent.

I'm happy to provide any additional details that might help.

Mailspring is a fantastic email client. Thank you for your effort!

- Mike

**Comment by CodeMouse92** [comment] 2021-02-04 23:08
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/attached-files-not-sent/468

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@franco27 @mikerisher: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-04 23:08 UTC
Labels: audit, bug, composer, needs-reproduction
