### ISSUE TITLE
Feature Request: Better Image Attachment 

### ISSUE THREAD

**Issue by Klarato** [Foundry376/Mailspring#2223] opened 2020-12-10 02:53 UTC
**Is your feature request related to a problem? Please describe.**
Just found Mailspring - I love it and subbed already. The only thing i have discovered i don't love about it, is when i try to attach images, if i drag and drop it only goes inline. Having an option to drag inline or as a file attachment would be great.

**Describe the solution you'd like**
Having a split screen window when you drag and drop would be perfect.
See photo below

**Describe alternatives you've considered**
Pressing attachment and selecting does work, but it feels clumsy these days.
Having it where i can drag it to the tool bar would also work.

**Additional context**
Mailbird has a great solution for this:
![Attachment](https://user-images.githubusercontent.com/75767699/101715130-01fec280-3aef-11eb-952e-48d685daae9e.png)

Thanks again for the great client.

**Comment by CodeMouse92** [comment] 2021-03-03 03:55
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/better-image-attachment-drag-and-drop-inline/971

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@Klarato: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-03 03:55 UTC
Labels: audit, enhancement
