### ISSUE TITLE
Sync of Archive folder never finishes

### ISSUE THREAD

**Issue by pimboli** [Foundry376/Mailspring#1327] opened 2019-01-20 20:12 UTC
##### What operating system are you using?

Mac OS
##### What version of Mailspring are you using?

1.5.5

--

Hi,

I have an exchange account which is configured as IMAP account and which has around 5 GB of emails in the "archive" folder.

My problem is that Mailspring never finishes the indexing/scanning process.

Can someone help me please?!

Here what I found in the log:

`tail -n 1000000 mailsync-0996469e.log | grep "syncFolderUIDRange for Archive, UIDs"
27306 [2019-01-15 09:08:50.889] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 59636, Heavy: true
27306 [2019-01-15 09:12:19.467] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 54635, Heavy: false
27306 [2019-01-15 09:17:14.952] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 59636, Heavy: true
27306 [2019-01-15 09:21:06.908] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 59636, Heavy: true
27306 [2019-01-15 09:24:19.602] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 59636, Heavy: true
27306 [2019-01-15 09:27:21.773] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 54635, Heavy: false
27306 [2019-01-15 09:32:08.028] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 59636, Heavy: true
27306 [2019-01-15 09:34:55.195] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 54635, Heavy: false
27306 [2019-01-15 09:39:49.292] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 59636, Heavy: true
27306 [2019-01-15 09:42:32.392] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 54635, Heavy: false
27306 [2019-01-15 09:47:20.013] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 59636, Heavy: true
27306 [2019-01-15 09:50:03.957] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 54635, Heavy: false
27306 [2019-01-15 09:54:59.792] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 59636, Heavy: true
27306 [2019-01-15 09:57:35.803] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 54635, Heavy: false
27306 [2019-01-15 10:02:22.462] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 59636, Heavy: true
27306 [2019-01-15 10:05:10.661] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 54635, Heavy: false
27306 [2019-01-15 10:10:07.374] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 59636, Heavy: true
27306 [2019-01-15 10:12:54.343] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 54635, Heavy: false
27306 [2019-01-15 10:17:43.366] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 59636, Heavy: true
27306 [2019-01-15 10:20:25.902] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 54635, Heavy: false
27306 [2019-01-15 10:25:22.327] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 59636, Heavy: true
27306 [2019-01-15 10:28:00.712] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 54635, Heavy: false
27306 [2019-01-15 10:32:46.544] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 59636, Heavy: true
27306 [2019-01-15 10:35:26.417] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 54635, Heavy: false
27306 [2019-01-15 10:39:51.239] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 59636, Heavy: true
27306 [2019-01-15 10:42:07.461] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 54635, Heavy: false
27306 [2019-01-15 10:46:53.814] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 59636, Heavy: true
27306 [2019-01-15 10:49:35.818] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 54635, Heavy: false
27306 [2019-01-15 10:54:02.255] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 59636, Heavy: true
27306 [2019-01-15 10:56:46.892] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 54635, Heavy: false
27306 [2019-01-15 20:31:07.828] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 59636, Heavy: true
27306 [2019-01-15 21:16:36.148] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 59636, Heavy: true
27306 [2019-01-15 21:24:31.855] [background] [info] syncFolderUIDRange for Archive, UIDs: 80394 - 80396, Heavy: true
27306 [2019-01-15 21:24:32.470] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 54635, Heavy: false
27306 [2019-01-15 21:30:14.437] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 59636, Heavy: true
27306 [2019-01-15 21:32:45.543] [background] [info] syncFolderUIDRange for Archive, UIDs: 80394 - 80396, Heavy: true
27306 [2019-01-15 21:32:46.128] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 54635, Heavy: false
27306 [2019-01-15 21:37:14.131] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 59636, Heavy: true
34617 [2019-01-16 16:21:00.111] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 59636, Heavy: true
35241 [2019-01-18 15:51:10.032] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 59636, Heavy: true
35241 [2019-01-18 16:03:38.173] [background] [info] syncFolderUIDRange for Archive, UIDs: 80394 - 80402, Heavy: true
35241 [2019-01-18 16:03:41.325] [background] [info] syncFolderUIDRange for Archive, UIDs: 79771 - 80402, Heavy: false
35241 [2019-01-18 16:06:48.673] [background] [info] syncFolderUIDRange for Archive, UIDs: 54636 - 59636, Heavy: true
35241 [2019-01-18 16:10:00.025] [background] [info] syncFolderUIDRange for Archive, UIDs: 80394 - 80402, Heavy: true
35241 [2019-01-18 16:10:03.205] [background] [info] syncFolderUIDRange for Archive, UIDs: 79771 - 80402, Heavy: false
35241 [2019-01-18 16:17:18.131] [background] [info] syncFolderUIDRange for Archive, UIDs: 49636 - 54636, Heavy: true
35241 [2019-01-18 16:33:40.388] [background] [info] syncFolderUIDRange for Archive, UIDs: 49636 - 49635, Heavy: false
39825 [2019-01-19 18:45:05.301] [background] [info] syncFolderUIDRange for Archive, UIDs: 49636 - 54636, Heavy: true
39903 [2019-01-19 18:50:30.345] [background] [info] syncFolderUIDRange for Archive, UIDs: 49636 - 54636, Heavy: true
39942 [2019-01-19 18:54:43.655] [background] [info] syncFolderUIDRange for Archive, UIDs: 49636 - 54636, Heavy: true
39942 [2019-01-19 18:58:03.445] [background] [info] syncFolderUIDRange for Archive, UIDs: 80402 - 80406, Heavy: true
39942 [2019-01-19 18:58:05.378] [background] [info] syncFolderUIDRange for Archive, UIDs: 79782 - 80406, Heavy: false
39990 [2019-01-19 19:07:26.916] [background] [info] syncFolderUIDRange for Archive, UIDs: 44636 - 49636, Heavy: true
39990 [2019-01-19 19:16:10.228] [background] [info] syncFolderUIDRange for Archive, UIDs: 79833 - 80406, Heavy: false
40258 [2019-01-19 19:18:30.904] [background] [info] syncFolderUIDRange for Archive, UIDs: 44636 - 49636, Heavy: true
40258 [2019-01-19 19:21:35.988] [background] [info] syncFolderUIDRange for Archive, UIDs: 80406 - 80409, Heavy: true
40258 [2019-01-19 19:21:37.012] [background] [info] syncFolderUIDRange for Archive, UIDs: 79833 - 80409, Heavy: false
40258 [2019-01-19 19:25:44.183] [background] [info] syncFolderUIDRange for Archive, UIDs: 39636 - 44636, Heavy: true
40258 [2019-01-19 19:32:10.535] [background] [info] syncFolderUIDRange for Archive, UIDs: 39636 - 44636, Heavy: true
40258 [2019-01-19 19:36:51.263] [background] [info] syncFolderUIDRange for Archive, UIDs: 39636 - 39635, Heavy: false
40258 [2019-01-19 19:42:58.641] [background] [info] syncFolderUIDRange for Archive, UIDs: 39636 - 44636, Heavy: true
40258 [2019-01-19 19:45:58.997] [background] [info] syncFolderUIDRange for Archive, UIDs: 39636 - 39635, Heavy: false
40462 [2019-01-20 09:45:08.962] [background] [info] syncFolderUIDRange for Archive, UIDs: 79659 - 80409, Heavy: true
40462 [2019-01-20 09:46:27.405] [background] [info] syncFolderUIDRange for Archive, UIDs: 79838 - 80409, Heavy: false
40462 [2019-01-20 10:02:14.646] [background] [info] syncFolderUIDRange for Archive, UIDs: 74659 - 79659, Heavy: true
40462 [2019-01-20 10:11:31.605] [background] [info] syncFolderUIDRange for Archive, UIDs: 74659 - 74658, Heavy: false
40462 [2019-01-20 10:25:14.350] [background] [info] syncFolderUIDRange for Archive, UIDs: 74659 - 79659, Heavy: true
40462 [2019-01-20 16:34:33.679] [background] [info] syncFolderUIDRange for Archive, UIDs: 74659 - 79659, Heavy: true
40462 [2019-01-20 16:43:40.789] [background] [info] syncFolderUIDRange for Archive, UIDs: 74659 - 74658, Heavy: false
40462 [2019-01-20 17:00:10.817] [background] [info] syncFolderUIDRange for Archive, UIDs: 69659 - 74659, Heavy: true
40462 [2019-01-20 17:20:12.847] [background] [info] syncFolderUIDRange for Archive, UIDs: 69659 - 74659, Heavy: true
40462 [2019-01-20 17:24:46.621] [background] [info] syncFolderUIDRange for Archive, UIDs: 69659 - 69658, Heavy: false
40462 [2019-01-20 19:35:43.160] [background] [info] syncFolderUIDRange for Archive, UIDs: 69659 - 74659, Heavy: true
40462 [2019-01-20 19:39:31.464] [background] [info] syncFolderUIDRange for Archive, UIDs: 69659 - 69658, Heavy: false
40462 [2019-01-20 19:43:51.575] [background] [info] syncFolderUIDRange for Archive, UIDs: 64659 - 69659, Heavy: true
40462 [2019-01-20 19:52:49.883] [background] [info] syncFolderUIDRange for Archive, UIDs: 80409 - 80410, Heavy: true
43929 [2019-01-20 21:01:05.051] [background] [info] syncFolderUIDRange for Archive, UIDs: 64659 - 69659, Heavy: true`

**Comment by CodeMouse92** [comment] 2021-01-28 03:31
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/the-eternal-sync-bug/334

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 03:31 UTC
Labels: audit
