### ISSUE TITLE
Feature Request: Support Labels / Tags on non-Gmail IMAP servers

### ISSUE THREAD

**Issue by sinnlosername** [Foundry376/Mailspring#1006] opened 2018-08-03 22:06 UTC
It would be nice to also use labels for all imap accounts (not just google). Even if they are only saved clientside it's still better than nothing

**Comment by katossky** [comment] 2018-11-15 09:59
I have the problem with Protonmail, which does have a label feature, but stores it internally as a specific "Labels" folder. I am afraid that labels are not part of the standard IMAP protocol, and that a lot of specific cases have to be handled, provider by provider.

I am up for trying for Protonmail, though ! 😃

**Comment by katossky** [comment] 2018-11-29 10:16
I wrote that while waiting for the e-mails to start syncing, after Mailspring had finished syncing the folders. It does not work for me either.

**Comment by MarcoAix** [comment] 2019-02-01 16:40
Hi, I've asked for the feature in another thread, so yes: much needed.

"Much" is because not being able to move an email to another account, we're stuck with no overall filing solution... and tags would be simpler to use.

**Comment by Dahaniel** [comment] 2020-05-06 09:59
Not an expert here but on Thunderbird I heavily use tags/labels that are store server-side and it was my understanding that these are standard IMAP?

**Comment by Dahaniel** [comment] 2020-05-06 10:03
also maybe a bit off-topic but: if using folders as labels (as i think Geary does) wouldn't that lead to a lot of duplicated mails?

**Comment by flindeberg** [comment] 2020-09-25 19:10
Its part of the IMAP standard, called "Flags Message Attribute" but usually referred to as IMAP tags or labels. See:
https://tools.ietf.org/html/rfc3501#section-2.3.2

For me, this is a killer feature and a requirement to start a switch to Mailspring. 

The best implementation I've seen is the one in Mailmate: 
https://manual.mailmate-app.com/organize
https://brettterpstra.com/2019/08/26/mailmate-and-tagging/

**Comment by CodeMouse92** [comment] 2021-02-10 21:25
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse (thanks @flindeberg!):

https://community.getmailspring.com/t/support-for-imap-flags-aka-labels/540/2

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-10 21:25 UTC
Labels: audit
