### ISSUE TITLE
Bug: iCloud email not getting added

### ISSUE THREAD

**Issue by Spl0itable** [Foundry376/Mailspring#1845] opened 2020-03-07 06:43 UTC
**Describe the bug**
Says it was successful but doesn't actually get added. Only Gmail seems to work. I have the 2fa, but the generated app password is how it gets bypassed. 

**Expected behavior**
iCloud should be able to be added.

**Screenshots**

**Setup: (please complete the following information):**
 - OS: PureOS
 - OS Version: Gnome 3.30.2
 - Mailspring Version: 1.7.4

**Additional context** 
Seems like a lot of bugs with being able to add accounts. I paid for annual sub to Pro thinking it would fix these issue. I seriously hope they get fixed quickly. Thanks

**Comment by WeiChihChern** [comment] 2020-03-07 12:03
same here

**Comment by greggslist** [comment] 2020-03-07 23:04
Yeah, I upgraded too (the annual plan) hoping that would do something, but it didn't. I can't get through to support via ticket either--I only get automated email responses. I've also provided video of the issue here #1847

**Comment by coinpathio** [comment] 2020-03-07 23:11
> Yeah, I upgraded too (the annual plan) hoping that would do something, but it didn't. I can't get through to support via ticket either--I only get automated email responses. I've also provided video of the issue here #1847

Yea @greggslist I am about to do a chargeback. Mailspring seems dead. Sad, because it looked to be the best mail client for Linux.

**Comment by greggslist** [comment] 2020-03-07 23:19
> Yea @greggslist I am about to do a chargeback. Mailspring seems dead. Sad, because it looked to be the best mail client for Linux.

Agreed! It's a beautiful/simple design and the read receipts/tracking is what attracted me to it. I may have to file a charge back as well unfortunately. I submitted my initial ticket 5 days ago.

Also, when attempting to add a second account after successfully adding a Gmail account it acts as if the second account was added. However, that doesn't show in the left side menu. If you exit out of Mailspring afterwards you can't open Mailspring back up--it'll prompt you with the **_Connect an email account_** screen.

**Comment by coinpathio** [comment] 2020-03-07 23:26
> > Yea @greggslist I am about to do a chargeback. Mailspring seems dead. Sad, because it looked to be the best mail client for Linux.
> 
> Agreed! It's a beautiful/simple design and the read receipts/tracking is what attracted me to it. I may have to file a charge back as well unfortunately. I submitted my initial ticket 5 days ago.
> 
> Also, when attempting to add a second account after successfully adding a Gmail account it acts as if the second account was added. However, that doesn't show in the left side menu. If you exit out of Mailspring afterwards you can't open Mailspring back up--it'll prompt you with the **_Connect an email account_** screen.

@greggslist I just went ahead and started a dispute claim with my card issuer. Maybe that will get the Mailspring dev's attention. I'd be more than willing to cancel the chargeback if they get the bugs sorted and, at the very least, have some professionalism and respond to my ticket. Nevertheless, I guess it'll have to be using Thunderbird instead lol

**Comment by kreela** [comment] 2020-03-12 19:06
My icloud and fastmail accounts successfully worked with an app-specific password before the latest update.  Now after I reinstalled it fresh on a new-to-me iMac, it goes to a blank screen after I plug in a new app-specific password.  It is a new bug, and tech support for Pro versions is still limited to email only.  
It is too bad the support is so awful.  I love the swipe, themes, and snooze functions. emClient has more layout options but no swipe or snooze yet on a mac.  However, Airmail is only $10 a year.  While I cannot change the font or add cool colors, I have dark mode, snooze, and swipe.  What a bargain compared to Mailspring.  Turned off the billing in Pro.

**Comment by pythonInRelay** [comment] 2020-03-14 17:50
Temp solution. Install an older version located [here](https://github.com/Foundry376/Mailspring/releases/tag/1.7.2).

**Comment by coinpathio** [comment] 2020-03-15 03:20
> Temp solution. Install an older version located [here](https://github.com/Foundry376/Mailspring/releases/tag/1.7.2).

The fact that the devs couldn't even suggest this here, nor reply to my support ticket, says all I need to know about the future of this project; it's dead. I've ended up just moving to Thunderbird. RIP Mailspring.

**Comment by pythonInRelay** [comment] 2020-03-15 08:17
> > Temp solution. Install an older version located [here](https://github.com/Foundry376/Mailspring/releases/tag/1.7.2).
> 
> The fact that the devs couldn't even suggest this here, nor reply to my support ticket, says all I need to know about the future of this project; it's dead. I've ended up just moving to Thunderbird. RIP Mailspring.

Fair enough mate. 900 issues is definitely a lot. I only use Mailspring for the email tracking, unfortunately Thunderbird doesn't have that, just regular read receipts.

**Comment by wreedheid** [comment] 2020-03-18 08:35
Same issue here, however: I got a reply from Ben that an update will come this month with bug fixes.

**Comment by CodeMouse92** [comment] 2021-02-01 19:45
Hi all,

2020 prevented much development work on Mailspring, but rest assured, development has resumed!

Also, please bear in mind that Mailspring Pro covers the costs of the APIs and server the pro features rely on. A Mailspring Pro subscription does *not* promise premium support. This is still an independent project which is primarily maintained by one person (Ben) in addition to his full time job.

It appears that this issue has been resolved, so we are closing it. If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

P.S. Duplicate of #1847

**Closed by CodeMouse92** 2021-02-01 19:45 UTC
Labels: audit, bug
