### ISSUE TITLE
Feature Request: 144/240fps scrolling and animations for 144/240Hz monitors

### ISSUE THREAD

**Issue by AdelKS** [Foundry376/Mailspring#2041] opened 2020-06-04 17:29 UTC
Hello!

First of all, thank you guys for your awesome work on this software. Keep up! I am opening this issue to ask for a small feature request.

**Is your feature request related to a problem? Please describe.**
I have a 240Hz monitor and I find very unfortunate that scrolling and animations seem to be capped at 60fps.

**Describe the solution you'd like**
Take into account the screen refresh rate and adapt animations and scrolling.

Cheers,

Adel

**Comment by CodeMouse92** [comment] 2021-03-02 02:25
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/144-240fps-scrolling-and-animations-for-144-240hz-monitors/913

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@AdelKS: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 02:25 UTC
Labels: audit, enhancement
