### ISSUE TITLE
Cannot sync 126 & 163 mails because setting up "Snooze" subfolder in mail folders is not allowed

### ISSUE THREAD

**Issue by NewtMa** [Foundry376/Mailspring#1576] opened 2019-07-13 08:51 UTC
##### Are there any related issues?

[#769](https://github.com/Foundry376/Mailspring/issues/769), [#994](https://github.com/Foundry376/Mailspring/issues/994), [#551](https://github.com/Foundry376/Mailspring/issues/551), [#158](https://github.com/Foundry376/Mailspring/issues/158), [#50](https://github.com/Foundry376/Mailspring/issues/50)

##### What operating system are you using?

Ubuntu 1804 LTS 

##### What version of Mailspring are you using?

 1.6.3

**Bug?**

##### Is this an email sync or connection issue?

-- email sync

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

-- imtp.163.com and imtp.126.com

##### Is the issue reproducible with a particular attachment, message, signature, etc?

it doesn't need a specific thing to reproduce this issue. **I have tried to mannualy create the ```MailSpring``` folder like you said in [#769](https://github.com/Foundry376/Mailspring/issues/769), but I think 126 & 163 mail server do not support adding a subfolder in the mail folders, and that's what's causing the sync process to crush.**

```
6942 [2019-07-13 16:25:22.036] [main] [info] Identity created at 1562964813 - using ID Schema 1
6942 [2019-07-13 16:25:22.038] [main] [info] ------------- Starting Sync (salamandernewt@126.com) ---------------
6942 [2019-07-13 16:25:22.043] [background] [info] Marking all folders as `busy`
6942 [2019-07-13 16:25:22.044] [metadata] [info] Metadata delta stream starting...
6942 [2019-07-13 16:25:22.045] [background] [info] Syncing folder list...
6942 [2019-07-13 16:25:22.346] [background] [error] Could not create Mailspring container folder: Mailspring. ErrorNonExistantFolder
6942 [2019-07-13 16:25:22.384] [background] [error] Could not create required Mailspring folder: Mailspring/Snoozed. ErrorNonExistantFolder
6942 [2019-07-13 16:25:22.386] [background] [info] Syncing folder list...
6942 [2019-07-13 16:25:22.457] [background] [error] Could not create Mailspring container folder: Mailspring. ErrorNonExistantFolder
6942 [2019-07-13 16:25:22.493] [background] [error] Could not create required Mailspring folder: Mailspring/Snoozed. ErrorNonExistantFolder
6942 [2019-07-13 16:25:22.538] [background] [info] syncFolderUIDRange for INBOX, UIDs: 1 - 4294967296, Heavy: false
6942 [2019-07-13 16:25:22.582] [background] [critical] 
 ***
 *** Mailspring GenericException occurred during program execution: 
 *** {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID","key":"ErrorNonExistantFolder","retryable":false,"what":"std::exception"}
 ***

6942 [2019-07-13 16:25:22.583] [background] [critical]  *** Stack trace:
 ***   SyncWorker::syncFolderUIDRange(Folder&, mailcore::Range, bool, vector*)
 ***   SyncWorker::syncNow()
 ***   runBackgroundSyncWorker()
 ***   clone
 ***
```

**Comment by CodeMouse92** [comment] 2021-02-10 22:11
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/cannot-sync-126-163-mails-because-setting-up-snooze-subfolder-in-mail-folders-is-not-allowed/562

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@NewtMa: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-10 22:11 UTC
Labels: audit
