### ISSUE TITLE
Error when viewing a certain thread: TypeError: el.remove is not a function

### ISSUE THREAD

**Issue by andreyuv** [Foundry376/Mailspring#589] opened 2018-01-29 13:17 UTC
##### What operating system are you using?
Windows 10

##### What version of Mailspring are you using?
1.1.1-c42b1842

##### Do you have any third-party plugins installed? If so, which ones?
I have not installed third-party plugins.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Not related to a provider. It seems to be related to a certain email.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

A certain mail thread causes this error to appear in the reading pane:

```
TypeError: el.remove is not a function
    at QuotedHTMLTransformer.removeQuotedHTML (/src\services\quoted-html-transformer.es6:51:12)
    at EmailFrame._emailContent (/internal_packages\message-list\lib\email-frame.jsx:59:34)
    at EmailFrame._writeContent (/internal_packages\message-list\lib\email-frame.jsx:83:72)
    at EmailFrame.componentDidMount (/internal_packages\message-list\lib\email-frame.jsx:27:10)
    at commitLifeCycles (C:\Users\andre\AppData\Local\Mailspring\app-1.1.1\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:149:193)
    at b (C:\Users\andre\AppData\Local\Mailspring\app-1.1.1\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:158:229)
    at m (C:\Users\andre\AppData\Local\Mailspring\app-1.1.1\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:169:217)
    at w (C:\Users\andre\AppData\Local\Mailspring\app-1.1.1\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:168:413)
    at z (C:\Users\andre\AppData\Local\Mailspring\app-1.1.1\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:167:32)
    at u (C:\Users\andre\AppData\Local\Mailspring\app-1.1.1\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:165:441)
    at Object.enqueueSetState (C:\Users\andre\AppData\Local\Mailspring\app-1.1.1\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:108:299)
    at MessageItemBody.A.setState (C:\Users\andre\AppData\Local\Mailspring\app-1.1.1\resources\app.asar\node_modules\react\cjs\react.production.min.js:12:357)
    at _unsub._mailspringExports.MessageBodyProcessor.subscribe.processedBody (/internal_packages\message-list\lib\message-item-body.jsx:62:29)
    at retrieve.then.output (/src\flux\stores\message-body-processor.es6:97:13)
    at <anonymous>
```

Here is a screenshot:
![mailspring_2018-01-29_14-43-19](https://user-images.githubusercontent.com/20476201/35510944-c6a85e64-0502-11e8-83c8-2f04eed6c9d9.png)

Before updating to this version of Mailspring there was no error. After updating the error appears when I select that particular thread. Afterwards I have to restart the app because the error persists even if I select a different thread.

GMail and Mailbird render the thread with no issues.

EDIT
In a previous version of this issue I had attached the source code of an email but it turns out I had incorrectly identified it. The actual thread has 9 emails in it, and I'm not sure which one is the original cause of the problem.

**Comment by bengotow** [comment] 2018-01-29 15:59
Hey thanks for reporting this—I'll get this fixed in the next release. We upgraded to React 16 which improves performance and will let us do some cool stuff in the future, but it makes these errors more severe.

**Comment by bengotow** [comment] 2018-01-29 20:20
Hey folks—the fix for this has been shipped in 1.1.2. The app will auto-update in the next few hours, or you can download the new version directly from https://getmailspring.com/download. Enjoy!

**Comment by andreyuv** [comment] 2018-01-29 20:33
I updated the app and now I have a different error:

`TypeError: Failed to execute 'evaluate' on 'Document': parameter 2 is not of type 'Node'.
    at QuotedHTMLTransformer._removeImagesStrippedByAnotherClient (/src\services\quoted-html-transformer.es6:62:24)
    at QuotedHTMLTransformer.removeQuotedHTML (/src\services\quoted-html-transformer.es6:55:10)
    at EmailFrame._emailContent (/internal_packages\message-list\lib\email-frame.jsx:59:34)
    at EmailFrame._writeContent (/internal_packages\message-list\lib\email-frame.jsx:83:72)
    at EmailFrame.componentDidMount (/internal_packages\message-list\lib\email-frame.jsx:27:10)
    at commitLifeCycles (C:\Users\andre\AppData\Local\Mailspring\app-1.1.2\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:149:193)
    at b (C:\Users\andre\AppData\Local\Mailspring\app-1.1.2\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:158:229)
    at m (C:\Users\andre\AppData\Local\Mailspring\app-1.1.2\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:169:217)
    at w (C:\Users\andre\AppData\Local\Mailspring\app-1.1.2\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:168:413)
    at z (C:\Users\andre\AppData\Local\Mailspring\app-1.1.2\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:167:32)
    at u (C:\Users\andre\AppData\Local\Mailspring\app-1.1.2\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:165:441)
    at Object.enqueueSetState (C:\Users\andre\AppData\Local\Mailspring\app-1.1.2\resources\app.asar\node_modules\react-dom\cjs\react-dom.production.min.js:108:299)
    at MessageItemBody.A.setState (C:\Users\andre\AppData\Local\Mailspring\app-1.1.2\resources\app.asar\node_modules\react\cjs\react.production.min.js:12:357)
    at _unsub._mailspringExports.MessageBodyProcessor.subscribe.processedBody (/internal_packages\message-list\lib\message-item-body.jsx:62:29)
    at retrieve.then.output (/src\flux\stores\message-body-processor.es6:97:13)
    at <anonymous>`

**Comment by bengotow** [comment] 2018-01-29 20:37
Ooof interesting—thanks for posting that, it looks like Mailspring is really upset about that particular draft. Will see if I can get this fixed.

**Comment by CodeMouse92** [comment] 2021-02-11 19:17
It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-11 19:17 UTC
Labels: audit, bug
