### ISSUE TITLE
Bug: Contact group only partially added

### ISSUE THREAD

**Issue by michaelaye** [Foundry376/Mailspring#2059] opened 2020-06-19 04:54 UTC
**Describe the bug**
Not all entries of a contact group are being added to the To: field (6 out of 8)

**To Reproduce**
Steps to reproduce the behavior (using an iCloud account):
1. Have a contact group with 8 entries
2. Create new mail
3. Use name of contact group
4. Only 6 entries are being filled.

**Expected behavior**
All members of contact group added to To: field

**Screenshots**
Not provided for data protection.

**Setup: (please complete the following information):**
 - OS: Kubuntu 
 - OS Version 20.04
 - Mailspring Version: 1.7.8

**Comment by FSB16** [comment] 2020-06-22 00:00
I have the same issue
Windows 10 Pro Build 18363.900
Mailspring - 1.7.8
Using Gmail account

**Comment by CodeMouse92** [comment] 2021-03-02 02:54
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/contact-group-only-partially-added/917

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@michaelaye @FSB16: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 02:54 UTC
Labels: audit, bug
