### ISSUE TITLE
Feature Request: Use Mailspring ID to import mailboxes across devices

### ISSUE THREAD

**Issue by aemmadi** [Foundry376/Mailspring#2090] opened 2020-07-12 15:18 UTC
**Is your feature request related to a problem? Please describe.**
I personally have a lot of emails added on mailspring. Everytime I reinstall or migrate to a new device, I am required to re-enter every single mailbox I synced originally. This is a painstaking process, and since users are already asked to setup a mailspring ID it would be easy to carry over mailbox info so anytime I login to my mailspring ID on a new device, I automatically am able to view all my mailboxes I added originally.

**Describe the solution you'd like**
Just like how read receipts and snoozes are stored under your mailspring id to sync that data across devices, start storing mailbox info (i.e. email account, and authorization if possible, if not user can re-authorize).

**Describe alternatives you've considered**
I have been manually adding multiple mailboxes regularly, and it is really time intensive and I would rather want mailbox to auto add all my previous mailboxes.

I have contributed to open source projects before, and am ready to work and implement this feature if you guys approve.

**Comment by CodeMouse92** [comment] 2021-01-28 03:45
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/sync-templates-signatures-accounts-etc-accross-multiple-devices/265/8

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 03:45 UTC
Labels: audit, enhancement
