### ISSUE TITLE
Authentication Error adding hotmail account

### ISSUE THREAD

**Issue by joselicht90** [Foundry376/Mailspring#2001] opened 2020-05-21 19:04 UTC
Hi! I download the latest version of mailspring for Windows 10 1909. When i try to add a hotmail account i get this: **Authentication Error - Check your username and password. (SMTP)View Log**

Here's the log:

----------IMAP----------
connect <mailcore::IMAPSession:00D3F400>
* OK The Microsoft Exchange IMAP4 service is ready. [QwBQADIAUABSADgAMABDAEEAMAAxADEANAAuAGwAYQBtAHAAcgBkADgAMAAuAHAAcgBvAGQALgBvAHUAdABsAG8AbwBrAC4AYwBvAG0A]
ssl connect imap-mail.outlook.com 993 2
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
1 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
1 OK CAPABILITY completed.
connect ok
login
2 LOGIN "jose.licht@hotmail.com" *********
2 OK LOGIN completed.
3 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CLIENTACCESSRULES CLIENTNETWORKPRESENCELOCATION BACKENDAUTHENTICATE CHILDREN IDLE NAMESPACE LITERAL+
3 OK CAPABILITY completed.
4 NAMESPACE
* NAMESPACE (("" "/")) NIL NIL
4 OK NAMESPACE completed.
login ok
5 LIST "" "*"
* LIST (\HasNoChildren) "/" Archive
* LIST (\HasNoChildren) "/" Archivo
* LIST (\Marked \HasNoChildren) "/" Inbox
* LIST (\HasNoChildren) "/" Outbox
* LIST (\HasNoChildren \Drafts) "/" Drafts
* LIST (\HasNoChildren) "/" Compras
* LIST (\HasNoChildren \Junk) "/" Junk
* LIST (\HasNoChildren \Trash) "/" Deleted
* LIST (\HasNoChildren \Sent) "/" Sent
* LIST (\HasNoChildren) "/" Facultad
* LIST (\HasNoChildren) "/" Inmobiliaria
* LIST (\HasNoChildren) "/" Laburo
* LIST (\HasChildren) "/" Mailspring
* LIST (\HasNoChildren) "/" Mailspring/Snoozed
* LIST (\HasNoChildren) "/" Notes
* LIST (\HasNoChildren) "/" POP
5 OK LIST completed.

----------SMTP----------
connect smtp-mail.outlook.com 587
220 CP2PR80CA0068.outlook.office365.com Microsoft ESMTP MAIL Service ready at Thu, 21 May 2020 18:59:40 +0000
init
EHLO DESKTOP-BU7CGU8
250-CP2PR80CA0068.outlook.office365.com Hello [190.188.213.75]
250-SIZE 157286400
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250 SMTPUTF8
start TLS
STARTTLS
220 2.0.0 SMTP server ready
done
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
init after starttls
EHLO DESKTOP-BU7CGU8
250-CP2PR80CA0068.outlook.office365.com Hello [190.188.213.75]
250-SIZE 157286400
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-AUTH LOGIN XOAUTH2
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250 SMTPUTF8

SASL_PATH: 

SMTP Last Response Code: 250
SMTP Last Response: CP2PR80CA0068.outlook.office365.com Hello [190.188.213.75]
SIZE 157286400
PIPELINING
DSN
ENHANCEDSTATUSCODES
AUTH LOGIN XOAUTH2
8BITMIME
BINARYMIME
CHUNKING
SMTPUTF8

mailsmtp Last Error Code: 296
mailsmtp Last Error Explanation: Unknown
mailsmtp Last Error Location: 10
mailsmtp Last Auth Type: 16

-----------------------------------------------------------------

The username and pasword are correct. Hope you can help me!

**Comment by AlejoJauregui** [comment] 2020-05-21 19:17
I have the same problem, but is with an Office365 account. I can recieve my mails, because I add it in the previous mailspring version. But I can't send Mails, in the log I have the same error.

**Comment by kzadora** [comment] 2020-05-21 20:03
dupe of https://github.com/Foundry376/Mailspring/issues/1996 maybe ?

**Comment by iceman3000** [comment] 2020-05-21 23:38
Roll back to version 1.7.6 as a workaround.

**Comment by CodeMouse92** [comment] 2021-02-12 22:27
It appears that this issue has been resolved (based on #1996 and the date of last activity here), so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-12 22:27 UTC
Labels: audit, mailserver-incompatibility, needs-reproduction
