### ISSUE TITLE
Adding new iCloud account does not pull any emails in (won't sync)

### ISSUE THREAD

**Issue by nmrdxt** [Foundry376/Mailspring#2138] opened 2020-09-07 14:08 UTC
##### What version of Mailspring are you using? 1.7.8

(eg: 1.6.3 or 1.7.0 - this is shown in Mailspring's main menu.)

##### Is the issue reproducible with a particular attachment, message, signature, etc? Yes, just add new iCloud account.
[mailsync-35f98ef1.log](https://github.com/Foundry376/Mailspring/files/5183446/mailsync-35f98ef1.log)

**Comment by CodeMouse92** [comment] 2021-02-12 22:24
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/syncfolderuidrange-errorconnection-on-one-of-the-folders/412

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-12 22:24 UTC
Labels: audit, bug, mailserver-incompatibility, needs-reproduction
