### ISSUE TITLE
Bug: frozen when organize folders

### ISSUE THREAD

**Issue by FuqiX** [Foundry376/Mailspring#2097] opened 2020-07-20 11:00 UTC
**Describe the bug**
My mailspring always freeze when I delete email folders two or three times in a short time.

**To Reproduce**
1. create several folders in one email account
2. try to remove them one by one
3. it always freezes

**Setup: (please complete the following information):**
Linux Robust-3 5.3.0-62-generic #56~18.04.1-Ubuntu SMP Wed Jun 24 16:17:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

mailspring v1.7.8-13635bcf

**Comment by CodeMouse92** [comment] 2021-03-02 18:56
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/frozen-when-organize-folders/936

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@FuqiX: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 18:56 UTC
Labels: audit, bug
