### ISSUE TITLE
Bug: Outgoing SMTP Email not saved in Sent when it has an attachment

### ISSUE THREAD

**Issue by heidekrueger** [Foundry376/Mailspring#2194] opened 2020-11-05 11:54 UTC
**Describe the bug**
I'm using Mailspring with an IMAP/SMTP account. For most emails, everything works fine. When I sent an email with an attachment, however, it seems to be delivered successfully (see below), but does not show up in the 'Sent' folder. Neither in Mailspring itself nor on other clients accessing the mail server. There seems to be no record of whether the email has been sent or not.

When using clients other than Mailspring with the same configuration, everything works as expected.

**To Reproduce**
1. Compose and sent an Email that has any attachment.
2. Wait for "sending message..." to finish and hear success-sound.
3. Check 'Sent' folder

**Expected behavior**
After sending, the email is shown in 'Sent' and synchronized to the mailbox's Sent folder on the mail server.

**Screenshots**
After sending 7 emails to another one of my email accounts
 * (with/without attachments)
  * from Mailspring / Thunderbird / my provider's webclient I get the following results:
(I accidentally called email 4 "email 1" again)

Note: the receiving mailbox is on a different mail-server and does not use Mailspring at all.

In the receiving account:
![image](https://user-images.githubusercontent.com/9562632/98235343-f7866180-1f61-11eb-884c-10788eaba95a.png)

In the sending account:
(Mailspring shown, but looks the same in thunderbird / web client):
![image](https://user-images.githubusercontent.com/9562632/98237341-0cb0bf80-1f65-11eb-81ad-cf16579c2895.png)

**Setup: (please complete the following information):**
 - OS: Windows 10 Pro 1909
 - Mailspring Version: 1.7.8-13635bcf

**Additional context** 
Happens with an IMAP/SMTP account. Not tested with other providers.

I started using Mailspring a few days ago and have been really loving it so far, but this is, unfortunately, a dealbreaker for me as I lose records of important messages.

**Comment by 233mhz** [comment] 2021-01-18 15:23
Same problem

**Comment by CodeMouse92** [comment] 2021-01-18 19:49
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/outgoing-smtp-email-not-saved-in-sent-when-it-has-an-attachment/80

Please consider joining that community and continuing the discussion there! Bonus: if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-18 19:49 UTC
Labels: audit, bug

**Comment by CodeMouse92** [comment] 2021-01-28 04:25
@233mhz This appears to be resolved in 1.8.0. If you're still having the problem, please post here: https://community.getmailspring.com/t/outgoing-smtp-email-not-saved-in-sent-when-it-has-an-attachment/80
