### ISSUE TITLE
Is it possible to integrate with Grammerly?

### ISSUE THREAD

**Issue by pSnehanshu** [Foundry376/Mailspring#1485] opened 2019-05-04 16:16 UTC
[Grammerly](https://app.grammarly.com/) is an awesome service that does spell-check as you write. I would really like to use it in mailspring. Is it possible?

**Comment by bengotow** [comment] 2019-05-26 19:25
Hey! Grammerly is great but we did an assessment a while back and it looks like we'd have to send everything you type to their servers in real-time to provide grammar correction, and it's unclear if / how Grammerly monetizes this data. I think it'd be great to provide grammar checking if we can find a service or library that would do it offline!

**Comment by bengotow** [comment] 2019-05-26 19:25
Related: #1402

**Comment by pSnehanshu** [comment] 2019-05-27 07:23
Yeah, that can be done too.

**Comment by CodeMouse92** [comment] 2021-01-28 02:51
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. Learn more about the changes here.

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/grammar-check-tool-integration/329

Please consider joining that community and continuing the discussion there! Votes on the feature suggestion on Discourse will increase the likelihood we implement this.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 02:51 UTC
Labels: audit, enhancement, product-direction
