### ISSUE TITLE
Mailspring don't work with google mail

### ISSUE THREAD

**Issue by rolandbreedveld** [Foundry376/Mailspring#614] opened 2018-02-01 15:02 UTC
Mailspring isn't working with my google account on my own at google hosted domain (roland@breedveld.net)after allowing mailsping in my webbrowser, mailspring is connecting, but after some while I get:Sorry, we had trouble logging you inan unexpected mailsync error occurred (134)when I use a gmail account, it works fine.
Using the latest version, on Ubuntu 17.10

**Comment by bengotow** [comment] 2018-02-02 19:14
Hmm! It sounds like Mailspring isn't able to refresh your access token to Gmail for some reason. If you click "Retry" it still isn't able to connect?

**Comment by petr-nehez** [comment] 2018-02-06 06:21
Same for me: ```An unexpected mailsync error occurred (134)```

**Comment by rolandbreedveld** [comment] 2018-02-14 11:15
@bengotow No, retry (multiple times) gives the same error

**Comment by rolandbreedveld** [comment] 2018-02-14 11:16
@bengotow : No multiple retry's, always the same error

**Comment by KINGSABRI** [comment] 2018-03-08 13:51
same here 
```
An unexpected mailsync error occurred (134)
```

- MailSprint version: mailspring-1.1.5-5834c99f
- OS: Ubuntu 17.10 amd64

**Comment by SebastianMunozMora** [comment] 2018-11-09 13:39
Same here An unknown error has occurred (mailsync: 134)

**Comment by PiedPieper** [comment] 2019-02-28 19:34
Same issue here... half of my email accounts disconnect from google and require me to re-authenticate through Google's web portal every day

**Comment by ITCMD** [comment] 2019-07-28 11:08
sme issue here since 1.6.3 update

**Comment by sikand** [comment] 2019-08-13 01:54
I'm struggling with this problem now. Please helpo

**Comment by sikand** [comment] 2019-08-13 01:55
{ Error: An unknown error has occurred (mailsync: 134)
    at ChildProcess._proc.on.code (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/mailsync-process.ts:226:25)
    at ChildProcess.emit (events.js:182:13)
    at ChildProcess.EventEmitter.emit (domain.js:442:20)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
    at Pipe._handle.close (net.js:606:12)
  message: 'An unknown error has occurred (mailsync: 134)',
  rawLog:
   '\nWaiting for Account JSON:\n\nWaiting for Identity JSON:\nmailsync.bin: /home/travis/build/Foundry376/Mailspring/mailsync/MailSync/Models/MailModel.cpp:39: MailModel::MailModel(nlohmann::json): Assertion `_data.is_object()\' failed.\n\n ***\n *** An abort error occurred during program execution.\n *** This error is thrown by system functions that detect corrupt state.\n ***\n *** Stack trace:\n ***   gsignal\n ***   abort\n ***   MailModel::MailModel(nlohmann::basic_json)\n ***   Identity::Identity(nlohmann::basic_json)\n ***   _ZN9__gnu_cxx13new_allocatorI8IdentityE9constructIS1_IN8nlohmann10basic_jsonISt3mapSt6vectorSsblmdSaNS4_14adl_serializerEEEEEEvPT_DpOT0_\n ***   void allocator_traits::construct(allocator&, Identity*, nlohmann::basic_json&&)\n ***   _Sp_counted_ptr_inplace::_Sp_counted_ptr_inplace(allocator, nlohmann::basic_json&&)\n ***   shared_ptr::shared_ptr(_Sp_make_shared_tag, allocator const&, nlohmann::basic_json&&)\n ***   shared_ptr allocate_shared(allocator const&, nlohmann::basic_json&&)\n ***   _ZSt11make_sharedI8IdentityIN8nlohmann10basic_jsonISt3mapSt6vectorSsblmdSaNS1_14adl_serializerEEEEESt10shared_ptrIT_EDpOT0_\n ***   main\n ***\n/snap/mailspring/374/usr/share/mailspring/resources/app.asar.unpacked/mailsync: line 4:  1851 Aborted                 (core dumped) SASL_PATH="$(dirname $(realpath $0))" LD_LIBRARY_PATH="$(dirname $(realpath $0));$LD_LIBRARY_PATH" "$(dirname $0)/mailsync.bin" "$@"\n' } { pluginIds: [] }

**Comment by csysl** [comment] 2019-10-09 09:14
same too

**Comment by Lokdal** [comment] 2019-10-29 14:17
I have this problem as well. I accept the permissions for Mailspring in my browser, but Mailspring keeps saying "Connecting". After a few seconds, it changes to this error message.
Sorry, we had trouble loging you in
An unknown error has occurred (mailsync: 134)
I retried to no avail. Permissions are set correctly when I check on my Google Account.

**Comment by 1beb** [comment] 2020-01-23 16:02
Have three accounts (gmail) all fail to sync when connected to VPN (Private Internet Access). Only works if I disconnect.

**Comment by exapsy** [comment] 2020-07-04 11:22
I have same issue, I use no VPN, and on my other device on the same network mailspring works perfectly.
Logs: 
```
// When pushing "Try now" button to resync accounts that have connection issues
mailsync-bridge.ts:194 Sending `wake` to all mailsync workers...
sendSyncMailNow @ mailsync-bridge.ts:194
fn @ offline-notification.tsx:21
_onClick @ notification.tsx:83
onClick @ notification.tsx:146
fa @ /snap/mailspring/488/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:14
ma @ /snap/mailspring/488/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:15
na @ /snap/mailspring/488/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:15
za @ /snap/mailspring/488/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:17
Da @ /snap/mailspring/488/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:18
Fa @ /snap/mailspring/488/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:18
Ba @ /snap/mailspring/488/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:18
Ia @ /snap/mailspring/488/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:21
be @ /snap/mailspring/488/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:84
Ii @ /snap/mailspring/488/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:231
bc @ /snap/mailspring/488/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:39
ee @ /snap/mailspring/488/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:86
Ki @ /snap/mailspring/488/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:232
de @ /snap/mailspring/488/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:85
mailsync-process.ts:312 Sending to mailsync 8f13bad0 {type: "wake-workers"}
mailsync-process.ts:312 Sending to mailsync f88121c8 {type: "wake-workers"}


// Attempting to sync - reauthenticate GMAIL account
Sync worker sent non-JSON formatted message: Waiting for Account JSON:
```

**Comment by CodeMouse92** [comment] 2021-02-01 21:05
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/cannot-connect-to-gmail-from-behind-vpn/421

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-01 21:05 UTC
Labels: audit, needs-reproduction
