### ISSUE TITLE
Critical Bug: Mail preview crashes

### ISSUE THREAD

**Issue by pendula95** [Foundry376/Mailspring#1437] opened 2019-03-25 08:15 UTC
##### What operating system are you using?

Fedora release 29 (Twenty Nine) x86_6
Kernel: 4.20.15-200.fc29.x86_64

##### What version of Mailspring are you using?

mailspring-1.6.0-0.1.x86_64

##### Is the issue reproducible with a particular attachment, message, signature, etc?

When trying to reply all button on this specific email I get this error that crashes all mail preview for all emails. The only way I can get recover is to restart mail string or do reload on development tab. But if I try to reply all again it will crash again.

![Selection_001](https://user-images.githubusercontent.com/1239791/54904266-5c508d80-4ede-11e9-9d91-36a9a277df89.jpg)

**Comment by InFaM0u5** [comment] 2019-03-25 08:56
**What operating system are you using?**

Manjaro 18.0.4 Illyria
Kernel: x86_64 Linux 5.0.3-1-MANJARO

**What version of Mailspring are you using?**

1.6.0-10f5c95c

**Is the issue reproducible with a particular attachment, message, signature, etc?**

Same as pendula95 above. When i try to reply or use the normal mail preview this error accures all the time. At this moment i can get around that by double click the Mail to read it in an extra window. I cant reover it atm by reload or restart.

![Mailspring Error](https://user-images.githubusercontent.com/48907159/54906652-0d0d5b80-4ee4-11e9-812f-ed7cce7f2634.png)

**Comment by bengotow** [comment] 2019-03-26 15:51
Whoa - I haven't seen this one before but this is not good at all. It looks like Mailspring's composer is totally failing to display for one of the drafts in the thread.

Honestly, about a year ago we switched to using the SlateJS text editor, and it's been a bit of a rough transition -  #921 has also been causing a huge amount of pain. I've been hoping to upgrade the version of the editor we're using to fix some of these issues, but there's a major memory usage issue I've been hoping they could merge a fix for first (https://github.com/ianstormtaylor/slate/issues/2456). I'll see what we can do about this in the next release. I think that we can take the new version of the Slate library, fork it and fix the memory issue for now.

**Comment by bengotow** [comment] 2019-07-04 13:56
Hey folks! This should be addressed in the latest release (1.6.3) that shipped earlier this week. The app should auto-update on it's own, or you can grab the new version from the releases page: https://github.com/Foundry376/Mailspring/releases/. Thanks for filing this - enjoy the update!

**Closed by bengotow** 2019-07-04 13:56 UTC
Labels: bug, composer, done-pending-release
