### ISSUE TITLE
v1.1.0 composer has very buggy cursor movement / selection

### ISSUE THREAD

**Issue by brandondube** [Foundry376/Mailspring#578] opened 2018-01-26 03:44 UTC
##### Are there any related issues?
None that I could fine.

##### What operating system are you using?
Windows 10

##### What version of Mailspring are you using?
1.1.0

**Bug?**

When right clicking misspelled text, there is an almost random chance that the spell check entries come up or the copy/paste functions come up.

Additionally, when clicking the beginning of a line, the cursor may not move.

At times, when clicking to move the cursor it may do nothing and then appear at a seemingly random position within the email body.

When highlighting text, at times individual words may be skipped.

##### Do you have any third-party plugins installed? If so, which ones?
No

**Comment by bengotow** [comment] 2018-01-27 20:30
Hmm this is an interesting one - I think this could have been due to performance issues that were fixed in fd6d88e6db2166e47104a3cc6be5250c52a17760, I'll see if I can reproduce these behaviors in the next release.

**Comment by rosslaird** [comment] 2018-01-28 18:50
I am also experiencing weird cursor and selection movements, primarily in the pop-out editor (on Arch). The cursor has a tendency to just re-position itself at the top of the text entry box, sometimes taking a couple of words of text (from the previous cursor position) with it and selecting them.

**Comment by franco27** [comment] 2018-01-29 09:10
(with 1.1.0)
I had problems removing a link on a text. 

and 
1 / when I select a text to put a link to the point of the sentence. The link is created on this text.
2 / Then when I resume writing the message, just after the point of the sentence or "with a return to the line", the new text is displayed with a link.

**Comment by chris968** [comment] 2018-02-13 11:47
Same kind of problem for me since version 1.1.0 (i'm currently using version 1.1.3) when i try to replace a misspelled word with the spell correction menu the corrected word appear on another location on the composer.

**Comment by bengotow** [comment] 2019-07-04 14:00
Hey folks! This should be addressed in the latest release (1.6.3) that shipped earlier this week. The app should auto-update on it's own, or you can grab the new version from the releases page: https://github.com/Foundry376/Mailspring/releases/. Thanks for filing this - enjoy the update!

**Closed by bengotow** 2019-07-04 14:00 UTC
Labels: composer, done-pending-release, needs-reproduction
