### ISSUE TITLE
Feature Request: Don't count mail as unread when its the same as received before

### ISSUE THREAD

**Issue by specter78** [Foundry376/Mailspring#2120] opened 2020-08-17 11:06 UTC
**Is your feature request related to a problem? Please describe.**
I am subscribed to a couple of Wordpress blogs. Anytime the articles are updated, I get a mail. If the same article is updated multiple times, I get multiple mails.

But the mails are same as received before. So if the first mail is not read, all unread mail counts as one. If the first mail is read, subsequent mails are counted as unread.

**Describe the solution you'd like**
If same mail is received again and if first is read, count subsequent emails also as read.

I know this may not be advisable for all emails. So one option is to restrict it to specific email addresses (to be specified by the user).

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by CodeMouse92** [comment] 2021-03-02 21:59
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/dont-count-mail-as-unread-when-its-the-same-as-received-before/942

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@specter78: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 21:59 UTC
Labels: audit, enhancement
