### ISSUE TITLE
Unread box shows read mails after they are marked as read or opened.

### ISSUE THREAD

**Issue by swastikmishra** [Foundry376/Mailspring#1770] opened 2020-01-17 06:20 UTC
##### Are there any related issues?
Didn't find any
...

##### What operating system are you using?
Ubuntu 18.04
...

##### What version of Mailspring are you using?
1.7.2

--

**Bug?**

##### Is this an email sync or connection issue?
No
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Not sure
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Yes
Select *Unread* box, open any unread mail, and when you comeback to the *Unread* box, it still shows the mail there, where as it should have been removed from *Unread* box.
The mails disappear from *Unread* after I reload Mailspring.
...

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?
Yes
...

**Comment by bengotow** [comment] 2020-02-15 18:28
Hey! I believe this is actually intentional - if you navigate away from Unread and go back to it, the unread messages should reload and the read ones will disappear. It was just jarring to have them disappear as soon as they were marked as read, because they become read 30s after you click them (depending on how you've configured Mailspring). Can you see if toggling away from Unread and going back does the trick?

**Comment by swastikmishra** [comment] 2020-02-15 18:37
Hey @bengotow 
Yeah, thats the case, if I switch between Unread and other boxes, it works. I didn't notice the 30s lag in marking mails read. 
Its kind of an UX issue.

**Comment by Phylu** [comment] 2021-01-14 10:59
@codebytere Please close the issue, as mentioned by the original creator.

**Comment by codebytere** [comment] 2021-01-14 22:11
I don't think this was intended for me, was it?

**Comment by Phylu** [comment] 2021-01-14 22:13
> I don't think this was intended for me, was it?

That's true. Sorry for that.

**Comment by CodeMouse92** [comment] 2021-01-17 03:34
@swastikmishra Since this seems to be resolved, I'll close this issue. Please check out our new community, https://community.getmailspring.com for bug reporting, help, and discussion about Mailspring.

**Closed by CodeMouse92** 2021-01-17 03:34 UTC
Labels: audit, product-direction, support
