### ISSUE TITLE
Bug: G-suite email looses authentication every week

### ISSUE THREAD

**Issue by chinovelasco** [Foundry376/Mailspring#2116] opened 2020-08-08 15:57 UTC
Hello,
I currently use Mailspring with 2 Google accounts: a Gmail one and a G-Suite, however the G-Suite one keeps loosing the authentication after a week or less.
Due to this, I have to reauthenticate it every 3 days. I thought the problem was caused by the fact that I have 2 Google accounts configured so I disabled the Gmail one, but the problem remains.

**Comment by bengotow** [comment] 2020-08-16 23:12
Hey @chinovelasco - this is pretty strange actually... do you know if your G-Suite organization has any policies in place against third party email clients, or has a really aggressive two factor auth / password rotation policy? We use Google apps for business and I don't think I've run in to this.

**Comment by CodeMouse92** [comment] 2021-03-02 21:55
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/g-suite-email-looses-authentication-every-week/941

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@chinovelasco: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 21:55 UTC
Labels: audit, bug, needs-reproduction
