### ISSUE TITLE
Arch Linux Email add error even after Update

### ISSUE THREAD

**Issue by fakeid30** [Foundry376/Mailspring#125] opened 2017-10-11 12:24 UTC
##### Are there any related issues?
No open issues ATM. 
...

##### What operating system are you using?
Arch Linux
...

##### What version of Mailspring are you using?
1.0.3
...

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
N/A
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
ALL
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?
- Open Mailpile on Arch Linux , install it from here : https://aur.archlinux.org/packages/mailspring/
- Try to add an email 
- See error 
![screenshot_20171011_181936](https://user-images.githubusercontent.com/26362832/31440323-0b5694e8-ae7f-11e7-9cd8-897bce37ff97.png)

##### Does this feature exist in another mail client or tool you use?
Yes, every email client out there can add email account.
...

**Comment by jGleitz** [comment] 2017-10-11 12:25
Looks like a duplicate of #123

**Comment by bengotow** [comment] 2017-10-11 17:22
Hey—if you previously had 1.0.2 or an earlier version installed, try deleting Mailspring's settings here : https://foundry376.zendesk.com/hc/en-us/articles/115001968632-How-do-I-manually-delete-cached-mail-data-and-settings-.

**Comment by fakeid30** [comment] 2017-10-12 12:46
@bengotow 
![screenshot_20171012_184558](https://user-images.githubusercontent.com/26362832/31496545-5c18afa2-af4b-11e7-80fd-9075cd83834c.png)

Still same

**Closed** 2017-10-14 07:31 UTC
Labels: done-pending-release
