### ISSUE TITLE
Carriage return and hyperlink at line's end of list item

### ISSUE THREAD

**Issue by jpbaril** [Foundry376/Mailspring#745] opened 2018-03-07 23:40 UTC
##### Are there any related issues?

Did not find.

##### What operating system are you using?
Ubuntu 17.10

##### What version of Mailspring are you using?
1.1.5 (Snap package)

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Screenshot attached
![capture du 2018-03-07 18-32-54](https://user-images.githubusercontent.com/5779633/37124622-1251e564-2237-11e8-9825-0c5e8d48b842.png)

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
NA

-------------------------------------------

If a link is the last thing on the line of a list item, when pressing return key, instead of creating a new list item, it just creates a regular carriage return as if I would have pressed shift+return.

**Comment by bengotow** [comment] 2018-04-04 10:24
Ahh good catch—this one might be a bit tricky to fix but I'll see what I can do.

**Comment by CodeMouse92** [comment] 2021-02-18 23:53
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/carriage-return-and-hyperlink-at-lines-end-of-list-item/702

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@jpbaril: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-18 23:53 UTC
Labels: audit, bug, composer
