### ISSUE TITLE
Wrong date for sent email. 

### ISSUE THREAD

**Issue by barra** [Foundry376/Mailspring#117] opened 2017-10-11 08:30 UTC
##### What operating system are you using?
Ubuntu 17.10

##### What version of Mailspring are you using?
1.03

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
no

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
gmail work so i think that it was imap related issue. 

##### Is the issue reproducible with a particular attachment, message, signature, etc?
no. Each mail send with my imap ISP was dated 1 gen 1970. 
![selezione_016](https://user-images.githubusercontent.com/1047619/31429740-1fc8f124-ae6f-11e7-9161-4af3e57619be.png)

**Comment by bengotow** [comment] 2017-10-11 17:59
Hey! Thanks for reporting this—is there a specific email provider you're seeing this behavior with? It seems like something we'll have to reproduce with a particular server.

**Comment by bengotow** [comment] 2017-10-11 18:05
From support: Installed Mailspring on an Ubuntu 16.04 and a 17.04 distribution. When sending email with Fastmail as my IMAP provider, the sent email has a missing date stamp and shows up sorted as Dec 31, 1969 in the Sent Mail column. When the email arrives, it has a proper datestamp, but the raw source of the email that was sent has none. Usually when I send email there is a Date entry at the top of the raw source. I am attaching a screen grab from Mailspring and a dump of the raw source of the test email.

**Comment by palefire19** [comment] 2017-10-11 18:45
+1 on this

I'm experiencing it with Gmail

**Comment by bengotow** [comment] 2017-10-11 19:02
Wow on Gmail? I think this might be happening because the timestamp Mailspring puts on the message is rejected by the server. Is there any chance your computer's local time is set ahead / in the future?

**Comment by palefire19** [comment] 2017-10-11 19:52
I live several time zones ahead of the US, but my computer's time is set to where I am.

One important note - mine is not just for sent mail - it's in my All Mail folder. Hundreds of emails at the very bottom read "Jan 1 1970" as the date. Some where I've participated in a thread, but a lot where I didn't do any sending. Happy to send any helpful info.

**Comment by justindoran** [comment] 2017-10-12 17:14
I'm having this same problem on MacOS with an Office365 account at my work. Date on sent messages reads Dec 31 1969, which screws up the conversation threads. Perhaps related, mailspring seems to have trouble accessing the sent mail folder on that sever. It can access a handful of older sent messages, but nothing recent.

**Comment by bengotow** [comment] 2017-10-12 23:17
Hey folks! Thanks for reporting this - this should be fixed in 1.0.4, which I shipped earlier today (getmailspring.com/download). Give that a shot and let me know if you're still seeing this!

It turned out we weren't formatting the date on the message properly when saving the message into the Sent folder. It wasn't easy to track down because most mail providers (including the Office365 account I tested, which is super odd) automatically put the message in the Sent folder when you deliver it through the SMTP gateway. Mailspring has fallback code to save the message to the sent folder manually if that doesn't happen, and that code wasn't using a correctly formatted timestamp.

Enjoy the update!

**Comment by justindoran** [comment] 2017-10-12 23:25
Update fixed the send date problem, no more Dec 31 1969; you the man Ben!

**Comment by palefire19** [comment] 2017-10-13 05:12
Unfortunately still a bunch of Jan 1 1970 for me, even after rebuilding the
inbox.

Ben - let me know how I can help! Happy to send SSs, etc.

**Comment by palefire19** [comment] 2017-10-13 05:26
Here's another potentially helpful clue. They say Jan 1 1970 in the inbox, but then when I actually click on any of those messages to read, they render the date correctly. Ben, happy to send you a screenshot personally but don't want to post one on Github.

**Comment by barra** [comment] 2017-10-13 07:22
update fixed, thanks!

**Closed** 2017-11-02 18:18 UTC
Labels: bug, done-pending-release

**Comment by slhck** [comment] 2017-11-07 13:42
I'm seeing this behavior in version 1.0.7 on one particular IMAP server (`imap.univie.ac.at`). The messages show the correct date when clicked, in the right pane, but in the list they all show Jan 1st 1970.

Let me know if I can help

I think it has to do with having changed my default "Sent Mail" folder after adding the account, so perhaps that particular part of the code still has some issues?

**Comment by dspaan** [comment] 2017-12-01 11:07
I'm having the same problem. I'm on the 1.08 latest client application. Using Windows 10 on a Macbook Air. I'm using an IMAP account that is running on Koozali SME server. When you search for the mail you see in the results 1 jan 1970 but when you open it you can see the correct sent dates.

**Comment by batizovce** [comment] 2017-12-05 07:23
Hi, 
I have the same issue with version 1.0.9. 

![screen](https://user-images.githubusercontent.com/34264084/33594677-2fad59da-d995-11e7-806d-d37476d7d031.png)

It is necessary to create new issue?
