### ISSUE TITLE
"Several of your accounts are having issues"

### ISSUE THREAD

**Issue by oohjhu** [Foundry376/Mailspring#1583] opened 2019-07-18 19:51 UTC
Hi, I have Mailspring v1.6.3 running on Linux Mint 19.1. I have a few accounts--Gmail, Hotmail and Yahoo--added to it. But almost as soon as I launch the app, I am given an error message saying "several of your accounts are having issues". When I click on the "Check Again" button below the message the message disappears but then reappears again after 10-20 seconds. It's gotten to the point that the application is unusable. BTW, I don't have syncing problems with either Thunderbird or Evolution, so I know it's not an issue with the mail servers. Can you please look into this? Thank you.

**Comment by jorgedferreira** [comment] 2019-07-19 14:38
Hey. Have the same Mailspring version on Xubuntu 18.04 and i'm also getting these errors. In the logs the error seems to state "Database Locked". Read somewhere of a bug from 2018 that the workaround was to delete the cache every week... that's not in my plans. 
Is there any update from the developers on this issue? I'd rather not go back to Thunderbird and i was planing to go to pro subscription, but not with these issues...
Best regards,

**Comment by jorgedferreira** [comment] 2019-07-19 18:24
Uninstalling. Unfortunately it's not stable enough for my usage.

Best of luck, looks promising but after 3 weeks with issues i'll go back to good old thunderbird :(

**Comment by oohjhu** [comment] 2019-07-19 22:07
> Uninstalling. Unfortunately it's not stable enough for my usage.
> 
> Best of luck, looks promising but after 3 weeks with issues i'll go back to good old thunderbird :(

Sorry to hear you're experiencing the same issues, but in a way I'm a little relieved too. At least I know now it's not something I'm doing that's causing the problems. I appreciate your hesitation with Thunderbird. It works without fail but that, man, that interface! I don't know how anyone can use it and not their mind. So basically I'm up the creek without a pedal...or a mail client in this case. Sucks bigtime.

**Comment by jorgedferreira** [comment] 2019-07-19 22:30
For what i could tell online people have complain about this Database Locked issue for some time. I too wanted to change to something with a nicer UI, but alas, Thunderbird works. I've removed Mailspring, setup the same accounts in TB and it's working as expected... with the same somewhat ugly face...

I'll try Mailsping in a year or so...

**Comment by oohjhu** [comment] 2019-07-20 16:35
> For what i could tell online people have complain about this Database Locked issue for some time. I too wanted to change to something with a nicer UI, but alas, Thunderbird works. I've removed Mailspring, setup the same accounts in TB and it's working as expected... with the same somewhat ugly face...
> 
> I'll try Mailsping in a year or so...

Try Evolution too while you're at it and let me know what you think. I'm giving it a go, and so far it looks like a decent alternative.

**Comment by simonv3** [comment] 2019-07-22 21:00
I think this is the same issue as here: https://github.com/Foundry376/Mailspring/issues/1571

This has only started happening the past month or so. It's huge drag on my use of Mailspring.

**Comment by tecosaur** [comment] 2019-10-04 02:11
I have this issue on **Solus**, and I have a friend on **Manjaro KDE** who just started using mailspring and is also running into the exact same issue :disappointed:

**Comment by CodeMouse92** [comment] 2021-02-01 19:24
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/database-is-locked/420

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-01 19:24 UTC
Labels: audit
