### ISSUE TITLE
Feature Request:  All done check mark customize

### ISSUE THREAD

**Issue by Lava3063** [Foundry376/Mailspring#1883] opened 2020-03-31 19:31 UTC
I would like to be able to select what check mark comes up when inbox is empty. I have a few favorites, and some that I dont like.

**Comment by CodeMouse92** [comment] 2021-02-27 02:47
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/all-done-check-mark-customize/849

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@Lava3063: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-27 02:47 UTC
Labels: audit, enhancement
