### ISSUE TITLE
The 15 counts of email message was moved to sent box, where as none was sent

### ISSUE THREAD

**Issue by prabhjeetd** [Foundry376/Mailspring#1598] opened 2019-08-01 17:07 UTC
##### Are there any related issues?

...Did not find any related issue.

##### What operating system are you using?

...Windows 10

##### What version of Mailspring are you using?

... latest version as on 1 Aug

--

**Bug?**

##### Is this an email sync or connection issue?

...I was replying to a bunch of people (may be more than 40 people in CC along with two DLs), I got an error saying can not deliver the message to some xyz people. It listed down about 10. 
I was not sure what has happened, I cross checked with couple of people and none of them received the email. I tried couple of other clients - outlook and spike and it was showing me 15 emails in my sent box to this list of people. 

interesting thing about the list of people was, there were duplicate contacts, the few contacts which were mentioned separately were part of the distribution list also. That might have also triggered the issue. 

if the client never sent the email why in the world would it put 15 copies of it in my sent box ??

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

...Not sure

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...Can not try doing it again.

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

...

**Comment by CodeMouse92** [comment] 2021-01-29 22:34
Apologies for the delay in responding! Mailspring development is kicking up again.

This looks like a combination of two bugs: a sync problem (message not sent) and the replication of sent mail, one per recipient.

As to the not-sent situation, it's best if that's addressed separately. Can you please confirm that this is still broken with 1.8.0, and if so, open a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

At to the duplicate sent mail issue, that's already covered by this topic on Discourse:

https://community.getmailspring.com/t/duplication-of-sent-mail/275

Please consider joining that community and continuing the discussion there!

---

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-29 22:34 UTC
Labels: audit
