### ISSUE TITLE
[Feature request] Proxy Support

### ISSUE THREAD

**Issue by luiscachog** [Foundry376/Mailspring#235] opened 2017-10-23 00:51 UTC
Hi team,

There is a possibility to add a proxy option?

Thanks in advance

Luis Cacho

**Comment by DaichiUeura** [comment] 2017-10-24 08:20
It would be very nice if proxy could be configured for (at least) Gmail.

**Comment by livc** [comment] 2017-11-11 09:47
We can solve it by `proxychains`.

https://github.com/nylas/nylas-mail/issues/104#issuecomment-272155834

**Comment by bengotow** [comment] 2017-11-28 22:40
Hey folks! Mailspring's sync engine doesn't currently pick up system proxy settings, but it definitely should. (To be honest, I was hoping it was one of those things that would "just work", but it appears that's not the case on at least Linux and Windows.) I'll see if we can get this going soon.

**Comment by mickaelicoptere** [comment] 2017-12-07 12:20
Yes, I face the same problem. i have the error : "An unexpected mailsync error occurred (3221225477)" on the network i have to use with a proxy but with another network everything works just fine as expected.

**Comment by Cris70** [comment] 2017-12-20 08:10
Yes please. I cannot even start using Mailspring because I get this:
![image](https://user-images.githubusercontent.com/5107224/34197114-4c406944-e565-11e7-9567-3b07a513d67b.png)

I tried with proxychains but had no luck: when proxychained, mailspring doesn't event show its main window :-(

I am on Linux, behind a corporate http proxy. Mailspring is v1.0.11.

Cris

**Comment by JunnanZ** [comment] 2017-12-28 06:54
+1

**Comment by Thundermare** [comment] 2018-01-16 06:47
+1

**Comment by JAlwine** [comment] 2018-01-18 15:24
+1

**Comment by Blak-Ish** [comment] 2018-01-23 10:20
+1 , please it would be wonderful if this feature can be made available asap

**Comment by ErikOsterud** [comment] 2018-02-02 21:53
+1

I really want to use Mailspring but I'm always connected to my VPN for work, so I'm not really able to use Mailspring until it can send while connected to VPN / Proxy.

Windows 10 / OpenVPN

**Comment by angelcorrales** [comment] 2018-03-05 12:32
@bengotow, there is preview date to do this enhacement?

**Comment by JulienNic0las** [comment] 2018-03-07 15:42
+1

**Comment by gonzalesraul** [comment] 2018-03-22 11:05
+1

**Comment by zlown3t** [comment] 2018-03-28 13:55
Hi guys thank you for all your work, recently I start to use Mailspring on my personal Ubuntu notebook and I loved all the features that it have. Now I would like to use Mailspring on work but I'm on Win10, behind a corporate http proxy. So, I make @Blak-Ish words mine  "It would be wonderful if this feature can be made available". 

Thank you.

**Comment by rafrsr** [comment] 2018-04-04 17:54
Same problem here with Ubuntu 😥

**Comment by jschwartzenberg** [comment] 2018-04-05 19:32
Having HTTP Connect (HTTPS proxy) support would be very useful. I am not aware of any mail client that has support for this.

**Comment by patrickgodinho** [comment] 2018-04-16 13:09
+1

**Comment by KH8** [comment] 2018-05-10 13:08
+1

**Comment by burtsevyg** [comment] 2018-05-11 10:49
+1

**Comment by Cris70** [comment] 2018-05-11 13:48
This bug is nearly seven months old... how many "+1"s do we need to have it closed?
Is there some stopper that makes this so hard? Or is it just a time shortage?
Some communication would definitely help here!
Thank you
Cris

**Comment by coffee2theorems** [comment] 2018-05-16 19:34
+1

**Comment by lalloni** [comment] 2018-05-19 13:53
+1

**Comment by fractalzombie** [comment] 2018-06-18 10:17
+1

**Comment by dcy10000** [comment] 2018-06-24 12:06
+1

**Comment by moosti** [comment] 2018-07-09 23:05
+2 :) :+1:

**Comment by SiqingYu** [comment] 2018-07-23 16:56
+1

**Comment by k-brooks** [comment] 2018-07-24 23:15
Definitely required for adoption in the corporate world... +1

**Comment by duriantang** [comment] 2018-07-28 18:17
+1

**Comment by AbaoFromCUG** [comment] 2018-08-27 06:17
+1

**Comment by franzvalo1** [comment] 2018-09-19 00:35
+1

**Comment by XuHenghenglumia** [comment] 2018-09-19 01:50
+10086

**Comment by luizlinux** [comment] 2018-10-10 10:32
+1

**Comment by mordrake** [comment] 2018-11-07 08:50
+1

**Comment by abinax** [comment] 2018-11-16 21:57
+1

**Comment by janie624** [comment] 2018-11-23 04:53
+1

**Comment by ajinkyamarathe** [comment] 2019-01-16 05:41
+1

**Comment by MauJFernandezUVR** [comment] 2019-01-23 17:21
Well, I was expecting to stop using Thunderbird but no proxy support for corporate world is stopping me from trying Mailspring, leaving my +1.

**Comment by nobody-65534** [comment] 2019-02-26 17:28
+1

**Comment by DGovender** [comment] 2019-02-28 11:10
+1

**Comment by loonydevil** [comment] 2019-02-28 12:53
+1

**Comment by reisal78** [comment] 2019-03-04 08:47
+1

**Comment by fliaping** [comment] 2019-03-16 07:42
socks5 proxy +1

**Comment by freehuoshan** [comment] 2019-03-29 08:23
socks5 or http proxy please +1

**Comment by iosmanthus** [comment] 2019-04-25 03:02
SOCKS5 or HTTP proxy please +1, It's really necessary for Chinese mainland users. @Foundry376

**Comment by gustavotrott** [comment] 2019-05-17 12:04
+1

**Comment by PascalBe07** [comment] 2019-06-05 04:34
+1

**Comment by HankelBao** [comment] 2019-06-09 04:35
+1 thanks

**Comment by Cediddi** [comment] 2019-06-20 12:49
This bug is almost 2 years old and it's a dealbreaker for me. Please pick this up Ben.

**Comment by luizlinux** [comment] 2019-06-20 13:06
I completely agree with Cediddi. This basic and yet missing feature is a deal breaker for me as well.
This feature request has been open forever and has a lot of +1s, what will it take for this to be implemented? I'm pretty sure most of the people who +1 here wouldn't mind pitching in some donations if that's what it takes.

**Comment by bengotow** [comment] 2019-06-20 23:49
Hey folks! Sorry for the delay here—the overall problem is that "proxy" means a lot of different things (SOCKS, proxies only for HTTP traffic, etc.) Chromium has a /ton/ of code for proxy autodiscovery across platforms (like tens of thousands of lines of code, which is wild...) and I've been hoping that Electron will expose an API for reading the auto-discovered proxy settings, which would allow us to apply them to the C++ sync engine easily. Unfortunately I asked about this again recently and the response wasn't too promising:

<img width="489" alt="image" src="https://user-images.githubusercontent.com/1037212/59888105-a933eb00-938b-11e9-920f-cb02fc3da07c.png">

Even the `curl` page about proxies talks about a whole bunch of different topics (https://ec.haxx.se/usingcurl-proxies.html). I think we could probably support SOCKS and HTTPS `CONNECT` proxies (where the certificates and SSL are not broken by the proxy), but it's a gonna be a lot of work 😬

**Comment by luizlinux** [comment] 2019-06-21 01:06
First of all, thank you for the feedback Ben. Better late than ever, right?

Like you said, proxies might mean a lot of different things to different people.
In that case, how about taking the [MVP](https://en.wikipedia.org/wiki/Minimum_viable_product) route and aim to provide http proxy support at first, then implement the other types of proxies later on?

Taking the MVP way, I would start out by implementing http proxy support at first, with all data required [proxy address, port, username and password] being manually inputed by the user.
Later on I would add support for discovery, environment methods, scripts and other authentication methods.

Thanks.

**Comment by ninadkochkar** [comment] 2019-07-14 08:39
I need this too

**Comment by Oldmoooon** [comment] 2019-07-14 09:36
I'm a gmail and mailspring user living in China, so socks5 proxy support is necessary, please!!!

**Comment by nevermoreluo** [comment] 2019-07-22 13:23
Urgently need this feature.

I know there are a lot proxy methods.

if auto-discovered proxy settings is difficult, is it possible to provide support  for setting it manually?

**Comment by mnnyang** [comment] 2019-08-04 14:05
Looking forward to this feature..

**Comment by hcodhsing** [comment] 2019-08-18 04:22
need it

**Comment by exislow** [comment] 2019-08-21 08:31
+1 soo bad!

**Comment by getabettersite** [comment] 2019-09-24 14:26
+1

**Comment by Dundant** [comment] 2019-09-30 07:05
+1

**Comment by execb5** [comment] 2019-11-11 13:19
+1

**Comment by iEricKoh** [comment] 2019-12-06 03:20
+1

**Comment by pmercatoris** [comment] 2020-02-07 07:08
+1

**Comment by DenshaDev** [comment] 2020-02-14 12:37
+1

**Comment by iosmanthus** [comment] 2020-03-10 16:02
Seems no need to add this feature. If users are using Linux, a few `iptables` rules will solve this problem. :laughing:

**Comment by free8011** [comment] 2020-03-17 12:06
+99999

**Comment by macmartine** [comment] 2020-05-11 04:06
+1

**Comment by AlienKevin** [comment] 2020-06-29 01:33
+1

**Comment by wyvernnet** [comment] 2020-12-06 12:22
+1

**Comment by CodeMouse92** [comment] 2021-01-22 19:29
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/add-proxy-support/185

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@luizlinux: I particularly ported your suggestion from above. If you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-22 19:29 UTC
Labels: audit, enhancement
