### ISSUE TITLE
The whole application freezes when email is syncing while trying to answer an email and then crashes the email view

### ISSUE THREAD

**Issue by Pajn** [Foundry376/Mailspring#1442] opened 2019-03-28 14:00 UTC
##### Are there any related issues?

...

##### What operating system are you using?
Ubuntu 18.10
...

##### What version of Mailspring are you using?
1.6.0
...

--

**Bug?**
When mailspring starts to sync email while I'm responding to an email, the whole app freezes until the sync is done and then the email view is replaced with this error:

```
Invariant Violation: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at ea (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:13:316)
    at r (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:14:166)
    at xg (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:212:130)
    at Object.enqueueSetState (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:133:223)
    at _a.Component.setState (/usr/share/mailspring/resources/app.asar/node_modules/react/cjs/react.development.js:373:16)
    at DraftEditingSession._sessionUnlisten.session.listen (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/decorators/inflates-draft-client-id.tsx:74:16)
    at EventEmitter.eventHandler (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/global/mailspring-store.ts:128:23)
    at EventEmitter.emit (events.js:182:13)
```

##### Is this an email sync or connection issue?
Not in an by itself, but I guess the sync causes UI updates that in combination with an in progress email creates some kind of infinitive update loop.

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I don't think so, but I do have both an Gmail and IMAP set up.
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?
It always freezes but I don't see the error  every time.

...

--

**Feature Request?**
Not freezing? :)
##### Does this feature exist in another mail client or tool you use?

...

**Comment by nickallevato** [comment] 2019-04-04 20:15
This also happens to me!

**Comment by personalnadir** [comment] 2019-04-05 13:23
I seem to have the same issue, however I think it is linked to long e-mail chains. I'm running 1.6.1 on MacOS 10.14.4

**Comment by jonesrussell** [comment] 2019-04-05 16:25
Same here, it's very frustrating and I can no longer rely on it.

**Comment by artsgirl** [comment] 2019-04-26 01:02
I am having this same issue, on a Windows machine. I have been completely unable to use the computer for email for days.

**Comment by Adhik** [comment] 2019-05-28 03:52
Happened here as well

**Comment by jschill** [comment] 2019-09-25 14:53
+1

**Comment by REMjn832** [comment] 2020-01-13 12:14
+1 for Arch and Mailspring v1.7.2-45..

**Comment by CodeMouse92** [comment] 2021-02-03 18:23
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/the-eternal-sync-bug/334

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-03 18:23 UTC
Labels: audit
