### ISSUE TITLE
Feature Request:  I don't see if there is an ability to make categories?

### ISSUE THREAD

**Issue by StewAlexander-com** [Foundry376/Mailspring#2064] opened 2020-06-22 19:45 UTC
Email organization is a big deal for me, I bet for others too....

I don't want to this to be a carbon copy of other email clients out there, but the concept of categories as a way to sort of group email within a folder is a nice idea.

Windows has rules that can dump things into categories, the rule setup process is kinda a pain

What if there were a couple of pre-made category rules (unread mail, mail with "do not reply" in the header, mail from known spammers or something?), and then the ability to make one's own categories?

Outlook puts a color over to the right (by default) that describes the category, but I believe there's room for some creativity to how email is flagged, or nestled, or whatever with the category

I typically have over 3,000 emails, so keeping them all organized by what's important or not is a big deal to me

**Comment by CodeMouse92** [comment] 2021-03-02 03:03
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/support-for-imap-flags-aka-labels/540/3

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 03:03 UTC
Labels: audit, enhancement
