### ISSUE TITLE
Feature Request: Quick display of main panel when minimized to tray

### ISSUE THREAD

**Issue by edmond-irani** [Foundry376/Mailspring#1869] opened 2020-03-19 11:17 UTC
First of all, thanks for developing this app!
I am using Ubuntu 18.04, version 1.7.4. 

**Problem:**
Currently, when I close the main panel, Mailspring minimized to tray. Whenever I want to open the panel again, I have to **(left or right) click** on the tray icon, and click **"Open Inbox"**. I would like to reduce the number of clicks to just one click.

**Proposed solution:**
Show up the panel when left-clicking/right-clicking the icon tray, or enable some sort of global shortcuts (currently available shortcuts are only valid when the window is focused).

Thanks for your attention
Edmond

**Comment by bengotow** [comment] 2020-04-16 05:10
Hey @edmond-irani — thanks for filing this! Mailspring is actually configured to open the inbox when you click the icon, but it looks like it's actually dependent on which tray manager you use on Linux:

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/1037212/79417003-94f25780-7f76-11ea-98be-39d536be9836.png">
(from the Electron framework we use documented here: https://www.electronjs.org/docs/api/tray)

I don't know much about Linux - anything we should do about this?

**Comment by ukrsup** [comment] 2020-05-02 08:54
The app is awesome.  Thank you guys.

The preferred behavior is implemented in several apps like Telegram and Hexchat (opensource).
Possibly you can take a look on code related to tray icon and move it to mailspring as well.

**Comment by CodeMouse92** [comment] 2021-02-27 02:37
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/double-single-click-on-tray-icon-doesnt-open-app/37

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-27 02:37 UTC
Labels: audit, enhancement
