### ISSUE TITLE
Complete and utter failure as a client

### ISSUE THREAD

**Issue by HaoZeke** [Foundry376/Mailspring#2189] opened 2020-10-30 20:54 UTC
##### What is the behavior you're seeing?
It JUST DOESN'T SYNC.
![image](https://user-images.githubusercontent.com/4336207/97755616-6d697380-1af1-11eb-9425-cfc2e15b3f8c.png)

##### What email provider (Gmail, Exchange, etc.) are you trying to use?
Anything. Gmail, AOL, Office
##### What operating system are you using?
ArchLinux
##### What version of Mailspring are you using?
1.7.8-1
(eg: 1.6.3 or 1.7.0 - this is shown in Mailspring's main menu.)

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Sure. Just add a bunch of accounts and test.

## Rant
Honestly I didn't want to open this issue. I'm a paying user (not that that matters) but it's been months since Mailspring was even vaguely functional. What's the point of all the bells and whistles when I can't even get my mail without reconnecting every single time? Plus AOL accounts never send emails, the list goes on. It's come to the point where I actively prefer using the browser or Newton for my email.

**Comment by CodeMouse92** [comment] 2021-01-28 16:18
Hi @HaoZeke,

I understand it's frustrating not to be able to get to your email! In any case, thank you for reporting this. 2020 prevented much development work on Mailspring, but rest assured, development has resumed!

There are a lot of people successfully using Mailspring on a daily basis, including myself (over a dozen email accounts from many providers), so *we know this problem has to have very specific causes*. We are working on resolving a number of long-standing issues with Mailspring.

1. Are you still having this problem with 1.8.0? ([Someone just created an Arch package](https://community.getmailspring.com/t/for-those-installing-on-an-arch-based-distribution/125), by the by.)
2. If so, then are you able to connect via another email client? (Just checking for outbound network connectivity issues relating to specific ports, which does happen from time to time.)

**If you are still having these problems, please start a new Thread in the appropriate category on our [Discourse](https://community.getmailspring.com) — or else reply to the related Thread if it's already created — so we can properly evaluate and discuss this issue.**

Meanwhile, I'm closing and locking the issue here as part of this migration. Rest assured, **this doesn't mean the issue is being discarded or ignored; this actually ensures that further conversation occurs where it can be discovered and acted on.** Please join the Discourse community and continuing the discussion there.

---

P.S. In case you're wondering how it got like this, Mailspring is largely the work of one person — Ben Gotow — who maintains this project in addition to his full time job. Most of Mailspring Pro's subscription revenues go into paying for the servers and APIs used in Mailspring Pro features. The GitHub Issues board has obviously gotten swamped in the last couple of years, and much of the issues are relatively minor things like duplicate issues, edge-case bugs, wishlist feature requests, and so on. You can imagine, if you only have one day a week to work on something, you can't very well spend that day going through the whole issue tracker to find things. (Not to mention to demotivational factor of the overloaded Notifications window!)

That's why I joined as the Volunteer Community Manager. I'm in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38).

Mailspring is very much alive, and right now it's just a matter of ironing out several major wrinkles.

**Closed by CodeMouse92** 2021-01-28 16:18 UTC
Labels: audit, bug, mailserver-incompatibility, needs-reproduction
