### ISSUE TITLE
has:attachment search not working

### ISSUE THREAD

**Issue by Chrismarsh** [Foundry376/Mailspring#1480] opened 2019-04-28 05:01 UTC
##### Are there any related issues?
Appears to be identical issue as that raised in #1260, however that issue is closed so I'm reopening.

##### What operating system are you using?
Windows 10, Fedora 29

##### What version of Mailspring are you using?
1.6.1-aceed8e5

**Bug?**
Same problem as #1260, searching with has:"attachment" when used with extra text causes an infinite search to occur. Other searches seem to work correctly

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Using gmail

**Comment by bengotow** [comment] 2019-05-26 23:33
Hey! Thanks for raising this issue! I was able to reproduce the crash you're talking about —I think I missed that it was caused by adding extra text to the query after has:attachment. Will see if I can get this fixed.

**Comment by bengotow** [comment] 2019-05-26 23:44
This should be fixed in the next release - it looks like there was just a method missing that needed to be implement for the `Has:attachment` query!  To be honest, this code was written a few years ago by a brilliant algorithms guy who was working on the project for a while, and it's been a bit tough to maintain because I don't understand abstract syntax trees and the query parsing / compilation process that was built to translate the text input into a WHERE clause. I really need to familiarize myself with this part of the app more...

**Comment by Chrismarsh** [comment] 2019-05-27 15:58
@bengotow good to hear, thanks!

**Comment by bengotow** [comment] 2019-07-04 13:57
Hey folks! This should be addressed in the latest release (1.6.3) that shipped earlier this week. The app should auto-update on it's own, or you can grab the new version from the releases page: https://github.com/Foundry376/Mailspring/releases/. Thanks for filing this - enjoy the update!

**Closed by bengotow** 2019-07-04 13:57 UTC
Labels: bug, done-pending-release
