### ISSUE TITLE
[Feature Request] Exchange Support

### ISSUE THREAD

**Issue by adambirds** [Foundry376/Mailspring#34] opened 2017-10-05 12:15 UTC
**Exchange Support**
##### Does this feature exist in another mail client or tool you use?
Yes it works in Outlook (But not Linux compatible)
It also works in Thunderbird, but not a fan of the interface compared to this one.

**Comment by leopck** [comment] 2017-10-05 15:16
Speaking about this, Evolution Mailer has a plugin called Evolution-EWS (Exchange Web Services)
https://github.com/GNOME/evolution-ews

I would really love to see Mailspring work with Exchange as well since it's greatly used in corporate environment.

**Comment by bengotow** [comment] 2017-10-05 17:57
Hey folks! Thanks for filing this - Exchange support is definitely high on the list of features to add, but it's also one of the biggest. Exchange uses an entirely different protocol to sync mail, and the documentation is pretty sparse. It's actually patented, so there aren't many open source Exchange implementations. That said, once IMAP + SMTP support is rock solid, I'll definitely see if we can get it in. That GNOME mailer plugin might be a good place to start.

**Comment by ldartez** [comment] 2017-10-05 18:15
i want to chime in and say thank you @leopck for beating me to the punch. Exchange support is literally THE reason I ever became interested in nylas and now mailspring. I need a usable clean client for exchange on ubuntu.

**Comment by casamanya** [comment] 2017-10-05 21:13
Hi!
I'm trying mailSpring and looks very promising. I'm a Linux (Ubuntu user). Although Exchange support is not done yet i've tried configure a imap account via DavMail (http://davmail.sourceforge.net/) which i'm using currently with Thunderbird. 

But the account settings for an IMAP account only permits standards ports (143, 993). DavMail uses custom ports (1143 for example) and I can't configure them. Any possibility to change the ports combo to other editable control?

Great work!

**Comment by etique57** [comment] 2017-10-06 21:59
There's also an evolution ActiveSync (AES) plugin:
https://github.com/GNOME/evolution-activesync

It would be nice if Mailspring could support both ;)

**Comment by gkjpettet** [comment] 2017-11-14 21:31
I've tried setting up Mailspring with Davmail to access Exchange mail but it just constantly says it's looking for messages and building the indexes. Occasionally DavMail pops up a notification saying folder '[Mailspring]' not found.

**Comment by jprrezende** [comment] 2017-12-08 10:52
Hi I want to use Mailspring but I dont do this because it dont have EWS support. In company that I work, we have EWS without IMAP support. Please improve support to EWS.

**Comment by ldartez** [comment] 2018-02-01 17:20
@bengotow , any updates on getting EWS implemented?

**Comment by siucdude** [comment] 2018-02-27 16:04
Just wanted to follow up on this, see if there is any movement on this or if there is a timeline of when this might happen?

**Comment by Mjolinir** [comment] 2018-03-20 16:17
Just another bump to say EWS support would be amazing.

**Comment by siucdude** [comment] 2018-08-23 20:04
Just wondering if anything is in the works... with Newton going away im looking for a good replacement..

**Comment by agottschling** [comment] 2018-10-27 00:43
I'd love to see this in Mailspring. Especially since a recent update to exchange server broke the web app in anything other than internet explorer, and for whatever reason, I can't update to the version that fixes that bug. It would be even more legendary if Mailspring could support both EAS and EWS.

**Comment by ovorobio** [comment] 2018-10-30 09:21
Hi, and another bump, this is really important feature to implement. Thank you.

**Comment by heldmar** [comment] 2018-11-02 22:00
I am wondering if this is still on the path, as last response saying it WAS one of the highest priorities items on the list of features to add was more than 1 year ago. I think this would make a LOT of users to not only download but also pay for this email client (including myself) as this is one thing is not available for Linux users easily. Yes, there is a connector for Evolution mail which has been referenced in this same thread but, have you even tried it? Not only Evolution is really old looking and ugly, but also this connector doesn't even work well.

I really would love this feature to still be on the list at that some day we can get it.

**Comment by jeroen7s** [comment] 2018-11-02 22:06
Yeah i wonder if they still actively develop this shit or it's just kinda a side project
I switched to evolution just to have exchange support, but it's just not as nice of a client as mailspring, especially UI wise
Though i found the exchange integration does work well, don't have any issues with it (though you need to install some extra packages not installed by default on ubuntu (adding exchange to gnome-accounts and expecting it to work is not enough)

**Comment by Mjolinir** [comment] 2018-11-04 16:30
I also switched to Evolution. The Exchange support there worked fine for
me, even the Calendaring, yet it was not perfect or without issues. I
eventually switched over to Thunderbird, it has Exchange support as well
and looks a bit nicer than Evolution due to themes. Meeting requests seem
flaky, though, and don't always work. To me it seems these features are
always added as a hack, plugin, or addon, and usually by some 3rd party. If
someone could just build support straight into their app, I'm sure it would
be much more reliable. On the QT side of things, I was able to get KMail to
work with Exchange, but KMail has some issues I dont care for, and the
Exchange support there was the least stable of all.  Hiri is the only app
that seems designed with EWS in mind, but it has no calendaring and is
pretty minimal at this point.

**Comment by pasmon** [comment] 2018-11-05 06:49
I'm using Hiri, and there is "calendaring". Of course it is not Outlook calendar but works fine for me. The ugliness of both Thunderbird and Evolution (also some weird connection issues from time to time) forced me to switch to Hiri at some point.

**Comment by jeroen7s** [comment] 2018-12-11 15:10
try this: http://davmail.sourceforge.net/
it basically creates a bridge from exchange to SMTP/IMAP, works fine with MailSpring

**Comment by heldmar** [comment] 2018-12-11 15:55
This works perfectly!

Thanks!


---
Helder Martins
UY: +598-93-770465
US: +1-786-766-0872

**Comment by gautamsi** [comment] 2019-03-28 17:18
have you guys looked at https://github.com/gautamsi/ews-javascript-api ?

**Comment by davidchalifoux** [comment] 2019-04-29 00:13
Still looking for this! I absolutely despise Outlook.

**Comment by hmartins-bt** [comment] 2019-04-29 13:26
> Still looking for this! I absolutely despise Outlook.

Hey, I recommend using Mailspring WITH DavMail as @jeroen7s recommended. I have written an article about how I did it here: https://itsfoss.com/microsoft-exchange-linux-desktop/. I hope it helps.

**Comment by mbrihed** [comment] 2019-08-02 10:20
Hi!
I would like to see support for EWS as well. As people commented Evolution and Thunderbird works fine but they are not good mail clients. I am looking at Hiri as well and it works fine (so does Evolution and Thunderbird) but I think Hiri is not that good.
Please update us if this is something on the roadmap. Would easy pay a Pro version if this came as native support.

**Comment by linuxiaobai** [comment] 2020-03-08 09:17
I also use davmail+mailspring. unfortunately, I have the problem: https://github.com/mguessan/davmail/issues/95. Does anyone have idea?

**Comment by luixal** [comment] 2020-03-16 12:36
Ouch, Been here in 2017, tried Mailspring again today thinking that in 2 years this would have been achieved.

Cant' image how many people is coming here and there going anywhere else due to the coronavirus remote working situation...

**Comment by playforvoices1** [comment] 2020-04-16 11:28
I would also very happy to see an EWS support in Mailspring.

**Comment by skobylite** [comment] 2020-05-09 21:47
Me three - 🤞️

**Comment by psychend** [comment] 2020-05-14 15:58
Definitely +1 here. Exchange support is the only piece missing for me really, and it's that one reason why I didn't uninstall Windows Mail yet. Apart from that, imo this is the best client around. Keep on rocking 🤟

**Comment by AndrewCarvalho** [comment] 2020-05-25 17:20
Another +1 👋

I'm planning on switching business email providers from Google to Microsoft. Google's email is excellent but the rest of their offerings (storage, communication, office tools) are lacking when compared to what Microsoft offers, and Microsoft is also cheaper overall. The only thing holding me back is lack of Exchange/ActiveSync support in Mailspring which has been my email client since Google killed Inbox.

I'm likely going to make the switch regardless and set up IMAP for now, but I am worried about managing my email past October, when Microsoft plans on disabling Basic Authentication and move entirely to OAuth 2.0.  Whether this means updating to support EWS/ActiveSync or simply supporting the new OAuth with IMAP (if possible), I hope I can continue to use Mailspring going forward.

**Comment by scottadair** [comment] 2020-07-06 20:26
Another +1 here. I'll happily buy the "Pro" subscription for this

**Comment by zloymalefic** [comment] 2020-08-05 09:49
Another +1 here. Totally impossible to use it for the working purpose without Exchange support

**Comment by CodeMouse92** [comment] 2021-01-21 00:27
Thank you for your patience on this issue! I know it's frustrating when you cannot connect to your email with Mailspring.

2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be a duplicate of one we've already migrated to Discourse:

https://community.getmailspring.com/t/institutional-office365-not-working/48

Please consider joining that community and continuing the discussion there.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-21 00:27 UTC
Labels: audit, enhancement
