### ISSUE TITLE
Feature Request: Seperate WM-class for pop-ups

### ISSUE THREAD

**Issue by soppelmann** [Foundry376/Mailspring#1970] opened 2020-05-06 09:40 UTC
**Is your feature request related to a problem? Please describe.**
Currently the WM class for the mailspring compose window and the calendar share the same WM class as the main client. Checked with xprop. 
They seem to be pop ups but are not marked as such.

**Describe the solution you'd like**
Seperate Classes for seperate windows. Allows me to make them float by rules rather than manually.
Or force them to be floating through the electron framework, I believe it allows for that.

**Describe alternatives you've considered**
Having the compose window take up half the screen and then manually setting it to float. Ugly and requires manual intervention

**Additional context**
Probably only affecting Linux but shouldn't be a hard fix.
This might be of use https://gist.github.com/geekeren/ac1e92ed7d0df4260f334522c5beee5c
and this https://www.electronjs.org/docs/api/browser-window

**Comment by CodeMouse92** [comment] 2021-03-01 23:32
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/seperate-wm-class-for-pop-ups/892

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@soppelmann: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-01 23:32 UTC
Labels: audit, enhancement
