### ISSUE TITLE
Bug: SMTP test at account setup is incorrectly using IMAP address as "FROM"

### ISSUE THREAD

**Issue by working-name** [Foundry376/Mailspring#1967] opened 2020-05-05 03:14 UTC
**Describe the bug**
When you first add an imap/smtp account to mailspring it *has* to successfully send an email through SMTP server to validate settings. Sure, fine. 

It proceeds to log in using the SMTP details I provided and then tries to send an email **as the email address in the IMAP details instead**. I'm not sure why that's a thing.

Mailspring should send `MAIL FROM: <smtp.configured.address@some.mail.server.com>` or simply quit it at `235 Authentication successful`. Instead it sends this:
```js
235 Authentication successful
MAIL FROM:<imap@address.com>
550 Unable to authenticate sender <imap@address.com>

SMTP Last Response Code: 550

SMTP Last Response: Unable to authenticate sender <imap@address.com>
```

**To Reproduce**
1. install mailspring
2. add an imap/smtp account with different authentication details – I also have different servers too because I'm trying to do what I outlined in #1575 )
3. It will fail to add the account and if you view the log it will be similar to what I have above

**Expected behavior**
mailspring should be satisfied by `235 Authentication successful`, or at least not mix up imap/smtp details provided.

**Screenshots**
not applicable.

**Setup: (please complete the following information):**
 - OS: Winblows
 - OS Version 10
 - Mailspring Version: 1.7.6

**Additional context** 
see #1575

**Comment by CodeMouse92** [comment] 2021-02-12 19:36
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/smtp-test-at-account-setup-is-incorrectly-using-imap-address-as-from/585

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@working-name: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-12 19:36 UTC
Labels: audit, bug
