### ISSUE TITLE
Bug: Mail connection issues

### ISSUE THREAD

**Issue by arpadgabor** [Foundry376/Mailspring#1888] opened 2020-04-05 19:25 UTC
**Describe the bug**
Mailspring keeps showing it has trouble syncing email. It would be really helpful if it showed more error messages, because this keeps happening for some time now. I've also sent an email today and only the first line was actually sent, good thing I saw that (after 50 mins).

I'm also always seeing those "Sending message..." and "Syncing your mailbox...", they never disappear.

**To Reproduce**
I have no idea. It just happens.

**Expected behavior**
No errors?

**Screenshots**
![image](https://user-images.githubusercontent.com/9270494/78507953-edae3d00-778b-11ea-8cf9-7a7be6cfbef6.png)

**Setup: (please complete the following information):**
 - OS: Windows 10 Pro
 - OS Version: 10.0.18363 Build 18363
 - Mailspring Version: ex: 1.7.4 d54ff730

**Additional context** 
I have 4 email synced, 3 gmail, 1 outlook.

This started happening a few months ago but I just ignored it. I also experienced mails not syncing at all, or not sending at all.

**Comment by RemyyB** [comment] 2020-04-05 20:53
When you click on "Syncing your mailbox" there is a list with all your email accounts and what's currently syncing, probably one of those accounts can't sync, find out which one and check on the service where you host the mail.

**Comment by arpadgabor** [comment] 2020-04-14 13:05
@RemyyB everything is green.

**Comment by tpaixao** [comment] 2020-04-17 13:43
I am having the same problem! Using 1.7.5. My IMAP account seems to always have trouble syncing, even though it sometimes manages to sync properly. Maybe some timeout issue?

**Comment by CodeMouse92** [comment] 2021-02-02 02:33
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/the-eternal-sync-bug/334

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-02 02:33 UTC
Labels: audit, bug
