### ISSUE TITLE
FEATURE: Local Storage Folders (feature or plugin idea??)

### ISSUE THREAD

**Issue by glenn2223** [Foundry376/Mailspring#1089] opened 2018-09-21 14:49 UTC
##### Are there any related issues?

NO

##### What operating system are you using?

Windows 10 64bit

##### What version of Mailspring are you using?

1.4.2

---

**Feature Request**

##### Does this feature exist in another mail client or tool you use?

Windows Live Mail

--

**Possibly a feature (or a plugin??)**

I think it would be great to have Local Storage Folders on the PC to store emails that you don't want clogging up your email space allowance. Some hosts can be really limited on space which is a problem when you have no way to store files locally.

I know it would be difficult as:

1. You would need to allow searches to include local folder
2. You would also need to allow Rules to move emails to those folders
3. Keep some kind of folder hierarchy that matches the folders in the mail client

I'd love to develop it myself (expand my portfolio and all that) but I don't even know where to begin.

p.s. Sorry, feel like I'm pushing loads of issues/features

**Comment by purefan** [comment] 2018-09-27 08:48
no worries glen :) every piece of feedback is valuable. I think the best place to start is the [Contrib guide](https://github.com/Foundry376/Mailspring/blob/master/CONTRIBUTING.md), there's also the Developer -> Create Plugin way but nothing beats reading code to get acquainted with a new system :) 

I am by no means an expert in Mailspring but feel free to open issues with the label `question` and I'll do my best to help out :)

**Comment by kentsor** [comment] 2021-01-09 19:59
I second this feature. OS X Mail has this and I use it extensively.

**Comment by CodeMouse92** [comment] 2021-02-25 01:39
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/local-storage-folders/784

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@glenn2223: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-25 01:39 UTC
Labels: audit, enhancement
