### ISSUE TITLE
Feature Request: Email Notification

### ISSUE THREAD

**Issue by santoshbb** [Foundry376/Mailspring#2011] opened 2020-05-24 11:28 UTC
In current mailspring, notifications for filtered folders will not show when new email has been received,
This feature is required for people using filters.

![image](https://user-images.githubusercontent.com/10789840/82752987-c7d80880-9dca-11ea-8f98-351ae0dbf28e.png)

In above picture 3 quantity show on notification folder

**Comment by CodeMouse92** [comment] 2021-03-02 00:30
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/notifications-on-non-inbox-folders/323

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 00:30 UTC
Labels: audit, enhancement
