### ISSUE TITLE
Request: Portable Windows Version

### ISSUE THREAD

**Issue by hl2guide** [Foundry376/Mailspring#922] opened 2018-06-08 02:41 UTC
Please consider creating a portable version of Mailspring.

Maybe a portableapps.com package?

**Comment by Labirent** [comment] 2019-02-22 22:50
Hi.
I made a portable. Maybe it will work for you and few other people that want it.
[https://drive.google.com/file/d/19MVVmP07w2geRV-hBvLrUyJOJu7D-oVz
](url)

**Comment by Labirent** [comment] 2019-02-22 22:57
> Please consider creating a portable version of Mailspring.
> 
> Maybe a portableapps.com package?

Hi.
I made a portable. Maybe it will work for you and few other people that want it.
[https://drive.google.com/file/d/19MVVmP07w2geRV-hBvLrUyJOJu7D-oVz ](url)
or
[https://yadi.sk/d/-httWTofFwsVwg](url)

**Comment by beppe9000** [comment] 2020-01-14 15:37
Is there any news on this for windows? Easiest way is to add a check during app startup: if there is a "portable" file within the working directory portable mode is enabled. All file writes (including data) should be redirected to subfolders of the Mailspring directory so that it could be moved to a new PC and still work flawlessly.

**Comment by bengotow** [comment] 2020-02-17 16:27
Hey folks—the autoupdater will probably never work in a portable mode but you should be able to install Mailspring on a thumbdrive by copying it's AppData/Roaming folder to the volume and then launching it using the `--config-dir-path E:\other\path` option to specify where all the data should be placed (also a path on the thumbdrive).

The only thing is that Mailspring stores your passwords in your system Credential Vault, and if you run the app on another machine you'd have to reconnect all your accounts. We'd need a different password storage mechanism that relied on a flat file for this to be completely solved I think.

**Comment by beppe9000** [comment] 2020-02-17 16:46
> The only thing is that Mailspring stores your passwords in your system Credential Vault, and if you run the app on another machine you'd have to reconnect all your accounts. We'd need a different password storage mechanism that relied on a flat file for this to be completely solved I think.

looks like it. some obfuscated json file should do the trick. for additional security a master password approach could be used: ask user for a password; use the hash to derive a cryptographic key to encrypt the json file. then prompt the user for the password at startup and offer to cache it in the system credential store (maybe creating a guid at first startup to uniquely identify mailspring instances for this purpose).

**Comment by CodeMouse92** [comment] 2021-01-28 02:08
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/portable-windows-version/326

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@hl2guide @beppe9000: if you join and reply to the issue, the moderators can make an effort to reassign your migrated posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 02:08 UTC
Labels: audit, enhancement, windows
