### ISSUE TITLE
Unable to start mailspring

### ISSUE THREAD

**Issue by pavkam** [Foundry376/Mailspring#1524] opened 2019-06-16 14:19 UTC
Installed the latest version from `Snap store` on `Linux Pop!_OS 19.04`. I am using Gnome on Wayland.

When invoking the `mailspring` command from the command line getting:

```
alex@florianopolis:~$ ELECTRON_ENABLE_LOGGING=true mailspring
/snap/mailspring/346/bin/desktop-launch: line 282: [: /home/alex/../../../.drive/Google: binary operator expected
[12426:0616/151828.452869:WARNING:browser_main_loop.cc(269)] Gtk: cannot open display: :0
alex@florianopolis:~$ 
```

I have a directory called `.drive` in my home that I created.

After waiting for about 5 seconds the command simply exists and the client doesn't appear.

**Comment by bengotow** [comment] 2019-06-24 18:46
Hmm this `/home/alex/../../../.drive/Google` is super interesting — my guess is that your path has a space in it or something that is confusing the launcher? It might be interesting to look inside that `desktop-launch` file and see what it's trying to do.

**Comment by WhyNotHugo** [comment] 2020-08-20 16:37
> I am using Gnome on Wayland.

Mailspring is an electron app. Electron does no support Wayland yet.

> cannot open display: :0

Mailspring tries to connect to Xorg,  but you're not running Xorg.

See #2013 and https://github.com/electron/electron/issues/10915.

Running Mailspring on a modern Linux installation isn't really deasable. You can use Xwayland, but the application will be very blurry if you have a hidpi display.

**Comment by CodeMouse92** [comment] 2021-02-18 00:16
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/unable-to-start-mailspring/681

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@pavkam @WhyNotHugo: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-18 00:16 UTC
Labels: audit, linux, snapcraft
