### ISSUE TITLE
Bug: Cannot edit mail after removing the signature

### ISSUE THREAD

**Issue by ForNeVeR** [Foundry376/Mailspring#1846] opened 2020-03-07 09:14 UTC
**Describe the bug**
After editing my signature from a newly created email body, I cannot edit the email (it looks like the editable block is getting deleted with the signature).

**To Reproduce**
1. Create a new message with signature:
   ![image](https://user-images.githubusercontent.com/92793/76140508-dd704880-608d-11ea-8f71-5d2d0b92d860.png)
2. Delete the first line of the message:
   ![image](https://user-images.githubusercontent.com/92793/76140526-098bc980-608e-11ea-9c1c-42094ab6ed1e.png)
3. Now, press the cross icon to delete the signature:
   ![image](https://user-images.githubusercontent.com/92793/76140555-5ff90800-608e-11ea-8950-3120b1f53238.png)

**Expected behavior**
Empty message should be left with a place for the cursor, like this:
![image](https://user-images.githubusercontent.com/92793/76140586-9d5d9580-608e-11ea-9fbd-d1717a68d76d.png)

**Actual behavior**
No cursor, I cannot enter any message text:
![image](https://user-images.githubusercontent.com/92793/76140573-7d2dd680-608e-11ea-920a-97d142afcf2d.png)

**Setup: (please complete the following information):**
 - OS: Windows 10
 - OS Version: 1903
 - Mailspring Version: 1.7.4

**Comment by CodeMouse92** [comment] 2021-02-23 22:35
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/unwritable-content-field-on-composer-when-switching-to-account-with-no-signature/703

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@ForNeVeR: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-23 22:35 UTC
Labels: audit, bug
