### ISSUE TITLE
Bug: Clicking notification does not focus mailspring

### ISSUE THREAD

**Issue by alexandradeas** [Foundry376/Mailspring#2172] opened 2020-10-20 15:27 UTC
**Describe the bug**
On Pop_OS! 20.04 when mailspring displays a notification, clicking on the notification will make the notification disappear but not focus the mailspring window nor display the page related to that notification

**To Reproduce**
1. Have mailspring open
2. Click on a notification stating a new email has been received
3. The notification disappears but nothing else happens

**Expected behavior**
The active window changes to mailspring and mailspring displays the email within the email pane

**Setup: (please complete the following information):**
 - OS: Pop_OS!
 - OS Version 20.04
 - Mailspring Version: 1.7.8-13635bcf

**Additional context** 
Gnome Version: 3.36.3

Notification settings:
![image](https://user-images.githubusercontent.com/12813479/96608343-2c06e600-12f1-11eb-8b32-b7b811c1ca72.png)

**Comment by CodeMouse92** [comment] 2021-03-03 03:22
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/clicking-notification-does-not-focus-mailspring/958

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@alexandradeas: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-03 03:22 UTC
Labels: audit, bug
