### ISSUE TITLE
[feature request] Place replies in the folder of the message being replied to

### ISSUE THREAD

**Issue by tvercaut** [Foundry376/Mailspring#1677] opened 2019-10-19 14:29 UTC
Currently, Mailspring allows to configure the folder in which sent emails are being stored but this is a fixed choice. It would be nice to be able to choose to store replies in the folder of the message being replied to.

##### Are there any related issues?

I couldn't find any related issue.

##### What operating system are you using?

Mac OS X Catalina

##### What version of Mailspring are you using?

1.7.1

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

Thunderbird allows for such customisation as shown in this screenshot
![image](https://user-images.githubusercontent.com/1614505/67146622-e9956e00-f284-11e9-8526-eaa935962cae.png)

**Comment by bengotow** [comment] 2019-10-21 21:24
Hey! Hmm - since Mailspring always displays "conversations", it essentially shows replies along with the message being replied to all the time. They're not placed in the same IMAP folder, though. 

I'm a little hesitant to implement this one because most SMTP gateways place the sent message into the Sent folder on their own (and Mailspring waits for them to do it and then puts it there itself if it's not done automatically.) I think that if we put sent messages in another folder, you'd probably also see them in the Sent folder sometimes. (At least on Gmail + iCloud, not sure about others offhand.)

I think for now we'll let Thunderbird have this one but I'll leave this open in case other folks want to chime in!

**Comment by CodeMouse92** [comment] 2021-02-26 17:29
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/place-replies-in-the-folder-of-the-message-being-replied-to/830

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@tvercaut: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-26 17:29 UTC
Labels: audit, enhancement, product-direction
