### ISSUE TITLE
Sending multiple / duplicates of the same email?

### ISSUE THREAD

**Issue by jshwvr** [Foundry376/Mailspring#1086] opened 2018-09-20 18:33 UTC
Hello,

I'm on the latest version of mailspring, and people are getting multiple copies of the same email from me. Typically 4 repeats per email. I tried disabling the 'undo sending' feature, rebuilding the cache, resetting all settings, uninstalling and reinstalling, nothing seems to work. I emailed support but haven't received an answer there, either. Really bummed--I love mailspring but I can't use it in a professional environment with a problem like this. Help?

Best,

JW

**Comment by karincalvinho** [comment] 2018-09-20 21:45
I am having the same issue! Following the thread because I really need a solution for this.

**Comment by DaveWalk1** [comment] 2018-09-21 15:05
Hello,
I'm also having the issues, today sending ~5 emails to a reply (with 4 people on this one email).
----------------
- What operating system are you using?
Windows 10
- What version of Mailspring are you using?
v1.4.2-f587b7b7
- Do you have any third-party plugins installed?
No
- Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Using Office 365, have not tried others
- Is the issue reproducible with a particular attachment, message, signature, etc?
Maybe something to do with open tracking?

**Comment by karincalvinho** [comment] 2018-09-21 16:03
Curiously, my details are the same as Dave's above.

**Comment by enocksson** [comment] 2018-09-24 14:18
I had a similar experience today. My email was sent together with about 10 duplicates. Similar information as above, but running Arch Linux.

**Comment by jshwvr** [comment] 2018-09-24 17:48
Still really hoping for an update. I'm a pro subscriber and haven't been able to use Mailspring all week because of this issue. :(

**Comment by NielsPeeters** [comment] 2018-09-25 19:32
Same issue on 1.4.2 Free, I'm sending duplicate (2) mails on Ubuntu 18.4.

**Comment by CarlosRebolledoA** [comment] 2018-09-26 11:43
Hello, the same thing happened to me some time ago. For your comments I am concerned about two things: That the incidence or error also affects me and that there is no response from Mailspring.

I have a Pro account, v 1.4.2, Windows 10 Pro and Gmail mail accounts from Google Suite and Outlook

I write in translated English, because my native language is Spanish.

From Talca, from Chile, with respect and appreciation.

A hug

En español: 

Hola, tiempo atrás me ocurrió lo mismo. Por vuestros comentarios me preocupan dos cosas: Que la incidencia o error tambien me afecte y que no exista respuesta de Mailspring. 

Tengo una cuenta Pro, v 1.4.2, Windows 10 Pro y cuentas de correo Gmail de Google Suite y Outlook

Escribo en Inglés traducido, porque mi idioma nativo es Español. 

Desde Talca, de Chile, con respeto y aprecio.

Un abrazo

**Comment by purefan** [comment] 2018-09-26 12:30
Hi!

Do you get this when writing a new email? when replying to a thread with multiple recipients? when replying to a thread with a single recipient? with delayed sending enabled? with delayed sending disabled?

For anyone troubleshooting this: I believe we always send an email from the draft (never from a live copy), I've had some issues debugging it from the UI because the popup closes as soon as the task is queued

**Comment by mhobbis** [comment] 2018-09-26 18:45
I get the problem when send or replying to an email where there are several recipients. I do have 15s delay and have not tried turning that off.

Mathew Hobbis
VP Global Accounts and Services Architecture

[X]
Email:
Mobile:
Address:
Web:
Developer:

mathew.hobbis@solace.com<https://link.getmailspring.com/link/1531998800.local-67de64f4-2444-v1.3.0-fd741eb7@getmailspring.com/0?redirect=mailto%3Amathew.hobbis%40solace.com&recipient=TWF0aGV3LkhvYmJpc0Bzb2xhY2UuY29t>
+44 7904 311 203<tel:+447904%20311%20203>
30 Crown Place, London,EC2A 4ES<https://link.getmailspring.com/link/1531998800.local-67de64f4-2444-v1.3.0-fd741eb7@getmailspring.com/1?redirect=https%3A%2F%2Fmaps.google.com%2F%3Fq%3D30%2520Crown%2520Place%252C%2520London%252C&recipient=TWF0aGV3LkhvYmJpc0Bzb2xhY2UuY29t>
http://www.solace.com<https://link.getmailspring.com/link/1531998800.local-67de64f4-2444-v1.3.0-fd741eb7@getmailspring.com/2?redirect=http%3A%2F%2Fwww.solace.com&recipient=TWF0aGV3LkhvYmJpc0Bzb2xhY2UuY29t>
http://dev.solace.com<https://link.getmailspring.com/link/1531998800.local-67de64f4-2444-v1.3.0-fd741eb7@getmailspring.com/3?redirect=http%3A%2F%2Fwww.solace.com&recipient=TWF0aGV3LkhvYmJpc0Bzb2xhY2UuY29t>


On 26 Sep 2018, at 14:34, Miguel Espinoza <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi!

Do you get this when writing a new email? when replying to a thread with multiple recipients? when replying to a thread with a single recipient? with delayed sending enabled? with delayed sending disabled?

For anyone troubleshooting this: I believe we always send an email from the draft (never from a live copy), I've had some issues debugging it from the UI because the popup closes as soon as the task is queued

**Comment by purefan** [comment] 2018-09-27 08:07
ok I got a little bit further debugging this and as far as I can see the actual sending of messages happens in mailsync, which we can't read. 

If anyone else can confirm that this happens when replying to multiple recipients that will help us pinpoint what's going on

**Comment by karincalvinho** [comment] 2018-09-27 11:44
Yes, It happens when replying to threads with multiple people, but not when
sending an email from scratch.

**Comment by Xezarior** [comment] 2018-10-01 21:31
I landed here just after sending in my request via the support on the website. I didn't knew there was an open issue list here on Github.
Copying the question-based problem-description from above:

- What operating system are you using?
  Windows 10 version 1709
- What version of Mailspring are you using?
  v1.4.2-f587b7b7, free subscription
- Do you have any third-party plugins installed?
  No
- Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
  Yes, outlook.live.com. But only on one account (@outlook.com) and it's alias, another (@live.de) is not affected. Other mail-providers are not affected.
- Is the issue reproducible with a particular attachment, message, signature, etc?
 No, it is independent of attachments (size or existence of), recipients (in particular or by number), the existence of previous threads or not.
- What couldn't you test?
  Delayed send happens with 5 seconds delay and I didn't test it without. I could not observe it behaving differently when sending from a draft, or from scratch (I don't remember which mails were sent form a draft and which weren't). None of the mails used tracking, nor had they signatures or templates.
- Since when did the issue appear?
  I don't know exactly. The oldest affected thread I could find is from March 20th.
- Additional Details:
  The problematic e-mails appear twice in the thread-overview, appear twice in the sent-folder (both in Mailspring and on outlook.live.com), and get received twice by the recipient.

I hope this helps, thank you very much.

**Comment by purefan** [comment] 2018-10-02 08:38
Ok I think I found an important semantic difference, we have 2 ways of delaying an email and I may have been testing "the other one":
- File -> Preferences -> General -> "After sending enable undo for <x> seconds"
- Compose -> icon to the right of "Send" is "Send later"

I understand it must be tedious to nitty gritty test all these scenarios (especially if you're spamming colleagues) but it would really help if you could confirm which method are you using that is causing this issue.

**Comment by Xezarior** [comment] 2018-10-02 08:47
Hello, I edited my comment, you noted a good point here. I did never use the "Send later" feature. Only the "enable undo fr X seconds".

**Comment by mhobbis** [comment] 2018-10-02 13:41
General settings

Mathew Hobbis
VP Global Accounts and Services Architecture

[X]
Email:
Mobile:
Address:
Web:
Developer:

mathew.hobbis@solace.com<https://link.getmailspring.com/link/1531998800.local-67de64f4-2444-v1.3.0-fd741eb7@getmailspring.com/0?redirect=mailto%3Amathew.hobbis%40solace.com&recipient=TWF0aGV3LkhvYmJpc0Bzb2xhY2UuY29t>
+44 7904 311 203<tel:+447904%20311%20203>
30 Crown Place, London,EC2A 4ES<https://link.getmailspring.com/link/1531998800.local-67de64f4-2444-v1.3.0-fd741eb7@getmailspring.com/1?redirect=https%3A%2F%2Fmaps.google.com%2F%3Fq%3D30%2520Crown%2520Place%252C%2520London%252C&recipient=TWF0aGV3LkhvYmJpc0Bzb2xhY2UuY29t>
http://www.solace.com<https://link.getmailspring.com/link/1531998800.local-67de64f4-2444-v1.3.0-fd741eb7@getmailspring.com/2?redirect=http%3A%2F%2Fwww.solace.com&recipient=TWF0aGV3LkhvYmJpc0Bzb2xhY2UuY29t>
http://dev.solace.com<https://link.getmailspring.com/link/1531998800.local-67de64f4-2444-v1.3.0-fd741eb7@getmailspring.com/3?redirect=http%3A%2F%2Fwww.solace.com&recipient=TWF0aGV3LkhvYmJpc0Bzb2xhY2UuY29t>


On 2 Oct 2018, at 03:39, Miguel Espinoza <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok I think I found an important semantic difference, we have 2 ways of delaying an email and I may have been testing "the other one":

  *   File -> Preferences -> General -> "After sending enable undo for seconds"
  *   Compose -> icon to the right of "Send" is "Send later"

I understand it must be tedious to nitty gritty test all these scenarios (especially if you're spamming colleagues) but it would really help if you could confirm which method are you using that is causing this issue.

**Comment by DaveWalk1** [comment] 2018-10-08 14:55
Hi @purefan, thanks for your help with troubleshooting. I wanted to say that I only ever used the **Email undo feature** (5 second delay). I never used the send later function.

**Comment by jonnyeom** [comment] 2018-10-12 15:11
Just another user with the same error here.

* What operating system are you using?
  * Linux Ubuntu 16.04
* What version of Mailspring are you using?
  * v1.4.2-f587b7b7
* Do you have any third-party plugins installed?
  * No
* Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
  * Using Office 365, have not tried others
* Is the issue reproducible with a particular attachment, message, signature, etc?
  * This is consistently happening when I reply all to an email chain.

I have the following configuration
*After sending, enable undo for `5 seconds`*
*I am not pressing `Send Later`*

**Comment by cbamberg77** [comment] 2018-10-17 09:28
another one here:

What operating system are you using?
MacOS Mojave

What version of Mailspring are you using?
Version 1.4.2 (1.4.2) (app store version)

Do you have any third-party plugins installed?
No

Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Office 365

Is the issue reproducible with a particular attachment, message, signature, etc?
This is consistently happening when I reply all to an email chain.

I have the following configuration
After sending, enable undo for 5 seconds

**Comment by mhobbis** [comment] 2018-10-17 09:57
I have recently made the upgrade to Mojave and the problem seems to have gone. At the time I noticed the problem I could not determine if a Mailspring upgrade of High Sierra patch was the likely cause.

I need to do more testing but I have reverted back to using Mailspring as my default client. I'll update again by the end of this week

Mathew Hobbis
VP Global Accounts and Services Architecture

Email:
Mobile:
Address:
Web:
Developer:

mathew.hobbis@solace.com (mailto:mathew.hobbis@solace.com)
+44 7904 311 203 (tel:+447904%20311%20203)
30 Crown Place, London,EC2A 4ES (https://maps.google.com/?q=30%20Crown%20Place%2C%20London%2C)
http://www.solace.com
http://dev.solace.com (http://www.solace.com)

**Comment by prazooo** [comment] 2019-04-11 07:04
Tried MailSpring 5 months back, this happened which forced me to move to Thunderbird. Decided to give it a try again today and I am experiencing the same thing. How could such a basic feature related bug gets ignored for so long?

**Comment by migalmoreno** [comment] 2019-05-21 07:22
As much as I love the initiative this project has, it should have addressed this kind of bugs a long way back. Still getting duplicates, the 'New message' window gets always overlayed by the main window when trying to write a new email, unread count badges don't go away at some times unless you delete them, no new incoming mail notifications...

**Comment by nlukovic** [comment] 2019-05-22 15:49
Same issue as well, will have to cancel my subscription and move back to thunderbird...

**Comment by nikolalukovic** [comment] 2019-05-22 15:52
Same issue, will have to cancel the subscription and move back to thunderbird.
It's unacceptable for an issue like this to persist for so long...

**Comment by isfttr** [comment] 2019-07-18 15:10
Ever since started using mailspring I have this issue. Doesn´t matter if its from scratch or replying.

**Comment by mohamednaser** [comment] 2019-08-09 13:58
I have the same issue and I can't use mailspring more than this until we have an update for this issue.

**Comment by MJFalahi** [comment] 2019-08-12 20:43
same issue
linux ubuntu 18.04 
version : 1.6.3

**Comment by Striffly** [comment] 2019-09-09 14:39
Same issue
Arch linux 5.2.9
Mailsprint 1.6.3

**Comment by AlecsisDuarte** [comment] 2019-09-19 18:59
Same issue.
Occurs when replying and forwarding to someone, it just happened with one recipient, but it isn't constant (sometimes happens and sometimes it doesn't).

**Versions**:
Xubuntu 19.04
Mailspring 1.6.3 (Installed using `snap`)

**Metadata**:
- Started Mailspring in the background with the command `mailspring --background`
- I have the 3 panel setup
- I am not pressing send later
- After sending, enable undo for: 5 seconds
- It just happened with Gmail

**Comment by ptutak** [comment] 2019-10-02 11:07
Same issue here.
It occurs when replying to a thread, even with only one recipient. Most often it's just 2 copies of an e-mail instead of one.
OS:
Lubuntu 18.04
Mailspring: 1.6.3

It happens only on **outlook.com**
Interestingly it's not about that Mailspring really **sends** those e-mails. The recipient receives only **one** email. The second e-mail appears only on Microsoft account as though it was sent to the recipient, but in fact it wasn't.

**Comment by hajeklu** [comment] 2019-12-09 15:40
Same issue.
Ubuntu 18.04 LTS
Mailspring 1.7.2

**Comment by CNOT** [comment] 2019-12-09 23:29
I was considering switching to MailSpring, but with such a bug still open, I'd rather wait and follow this thread to see when it's going to get resolved. I guess I'm sticking to good old Thunderbird for now.

**Comment by FrankWhoee** [comment] 2019-12-16 22:28
Same issue with Ubuntu 19.10, my Mailspring version is 1.7.2-4522b259

No third party plugins
Not an issue with email service
Sends twice when replying.

**Comment by yidingww** [comment] 2020-02-13 14:37
Same issue here with Ubuntu 18.04

**Comment by yidingww** [comment] 2020-02-13 15:03
> Same issue with Ubuntu 19.10, my Mailspring version is 1.7.2-4522b259
> 
> No third party plugins
> Not an issue with email service
> Sends twice when replying.

But when I tested it, I found that though the sender can see the sent email appear twice in the sent folder. HOWEVER, the receiver only receives a **single** one

**Comment by cherrot** [comment] 2020-02-23 15:22
I guess it's related to the "link tracking" feature. In my case 2 emails have been sent. I have inspected into the  content:
- There is one email in which all the web links are replaced in the form `https://link.getmailspring.com/link/{MY-USER-UUID}?redirect={MY-ORIGINAL-LINK}&recipient={ANOTHER-HASH}`
- The other one keeps the original web links.

I may give it a test, say, turn off link tracking and see how many email will be sent.

**Comment by yidingww** [comment] 2020-02-24 05:36
> I guess it's related to the [Link Tracking / Open Tracking](https://foundry376.zendesk.com/hc/en-us/articles/115001876351-How-does-Mailspring-perform-Open-Tracking-) feature. In my case 2 emails have been sent. I have inspected into the content:
> 
> * There is one email in which all the web links are replaced in the form `https://link.getmailspring.com/link/{MY-USER-UUID}?redirect={MY-ORIGINAL-LINK}&recipient={ANOTHER-HASH}`
> * The other one keeps the original web links.
> 
> I may give it a test, say, turn off Link Tracking and Open Tracking then see how many email will be sent.

I just tried disabling view tracking and link tracking both, but it still sent 2 emails. The receiver only receive 1 copy though

**Comment by cherrot** [comment] 2020-02-24 07:33
I have sent an email to multiple recipients, with on web link,  with neither `Open Tracking` nor `Link Tracking` being enabled. 

This time only 1 email has been sent.

**Comment by jscrodrigo** [comment] 2020-03-04 15:01
Hello guys!
I'm passing through the same issue. I think I'll have to come back to Thunderbird.
OS: Linux Mint
Version: 19.3 Tricia

**Comment by burakcank** [comment] 2020-05-04 09:58
> > I guess it's related to the [Link Tracking / Open Tracking](https://foundry376.zendesk.com/hc/en-us/articles/115001876351-How-does-Mailspring-perform-Open-Tracking-) feature. In my case 2 emails have been sent. I have inspected into the content:
> > 
> > * There is one email in which all the web links are replaced in the form `https://link.getmailspring.com/link/{MY-USER-UUID}?redirect={MY-ORIGINAL-LINK}&recipient={ANOTHER-HASH}`
> > * The other one keeps the original web links.
> > 
> > I may give it a test, say, turn off Link Tracking and Open Tracking then see how many email will be sent.
> 
> I just tried disabling view tracking and link tracking both, but it still sent 2 emails. The receiver only receive 1 copy though

I can confirm this, tried replying to an email from my outlook account, after the email is sent there were 2 copies of the same email in history. Recepient only received a singe email though.

**Comment by LazKot** [comment] 2020-06-30 00:50
Still same issue on Ubuntu 20.04. Considering that people pay for an account, this is such a fundamental flaw. Tracking turned off and problem persists. Has anyone figured this out yet ?

**Comment by DmitryAstafyev** [comment] 2020-07-08 07:44
Still there, Arch Linux

**Comment by DmitryAstafyev** [comment] 2020-07-11 12:42
No feedback. Sad. I've migrated to `thunderbird`. Looks ... well, `Mailspring` looks much better. But this bug makes it impossible to use it. Will try to back into 1 year. Really hope it will be resolved.

**Comment by MalachiMcintosh** [comment] 2020-08-31 22:25
Still have this issue. Windows 10. version 1.7.8

**Comment by ezebunandu** [comment] 2020-09-14 15:56
Have the same issue too. Ubuntu 20.04. Was hoping this would be resolved, but might be time to move to Thunderbird.

**Comment by milessavva** [comment] 2020-11-15 20:34
Still having this issue too for several years now. OS: Linux Mint 19, Mailspring v1.7.8. It's a shame since this is otherwise the best email client I've used.

**Comment by jalovisko** [comment] 2020-11-17 17:40
Same issue for years, running Windows 10, Mailspring 1.7.8.

**Comment by laisbasso** [comment] 2020-11-27 14:45
Same issue. Ubuntu 20.10, Mailspring 1.7.8.

**Comment by edwardzhxi** [comment] 2020-12-02 21:00
this bug exists for a long time, have to live by...

**Comment by ItsNewe** [comment] 2021-01-06 13:37
Still happening. Arch, Mailspring 1.7.8-13635bcf

**Comment by chberger** [comment] 2021-01-26 21:46
Same issue .. Ubuntu 20.10 , Mailspring 1.8.0-8983dca2

**Comment by CodeMouse92** [comment] 2021-01-26 22:03
> > > I guess it's related to the [Link Tracking / Open Tracking](https://foundry376.zendesk.com/hc/en-us/articles/115001876351-How-does-Mailspring-perform-Open-Tracking-) feature. In my case 2 emails have been sent. I have inspected into the content:
> > > 
> > > * There is one email in which all the web links are replaced in the form `https://link.getmailspring.com/link/{MY-USER-UUID}?redirect={MY-ORIGINAL-LINK}&recipient={ANOTHER-HASH}`
> > > * The other one keeps the original web links.
> > > 
> > > I may give it a test, say, turn off Link Tracking and Open Tracking then see how many email will be sent.
> > 
> > 
> > I just tried disabling view tracking and link tracking both, but it still sent 2 emails. The receiver only receive 1 copy though
> 
> I can confirm this, tried replying to an email from my outlook account, after the email is sent there were 2 copies of the same email in history. Recepient only received a singe email though.

@burakcank I can also confirm. Actually, I think this is *partially* a bug on Outlook/Gmail's end, as I had the same problem with Evolution. Those services automatically move sent messages into sent mail, and then Mailspring does *the same thing*. Multiple recipients would amplify the issue. In reality, only one gets sent.

That actually makes this not as much of a disaster as it might appear — **recipients only get one email**, but nonetheless it can be annoying.

I also know it's irritating that many bugs have gone unresolved for years. This is *not* because the Mailspring developers don't care! Mailspring is primarily the work of one person — Ben Gotow — who has a full time job besides this. The overwhelming 1K+ issues (and many more notifications thereof) has historically made it difficult to find high priority bugs amidst all the wishlist items, edge-case reports, questions, and whatnot. Thus, it has been hard to determine which bugs and features to focus his very limited development time on.

To mitigate this problem, I was brought on as the Volunteer Community Manager. We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery. This way, GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/duplication-of-sent-mail/275

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

**Closed by CodeMouse92** 2021-01-26 22:03 UTC
Labels: audit
