### ISSUE TITLE
Address Book never finishes caching locally - Always Scanning and stuck at 2% progress

### ISSUE THREAD

**Issue by knimer** [Foundry376/Mailspring#1742] opened 2019-12-16 12:51 UTC
### Are there any related issues?
Not aware and did not find.

...

##### What operating system are you using?
Clear Linux 31890

...

##### What version of Mailspring are you using?
1.7.2 - 4522b259

--

**Bug?**

##### Is this an email sync or connection issue?
Yes.
I am connecting to Office365 account. The MailSpring client simply asked for the username and password and auto-configured and worked 100% for the email part.

Address Book (Contacts) folder is not syncing more than 2%
Calnedar folder is not syncing at all.

The result is that the MailSpring always show scanning messages at all times, drains battery, and Contacts are not loaded actually.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Not sure if this is an Office365 issue only or visible in other account types.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Please note screen shot.

![MailSpringContactsSyncNotWorking](https://user-images.githubusercontent.com/32583831/70908257-2cc15280-2024-11ea-829f-0e523739acb5.png)

**Comment by knimer** [comment] 2020-04-13 06:15
Still the issue is there when tried 1.7.5 beta. Is there a solution for this? It is always using CPU and resources.

**Comment by CodeMouse92** [comment] 2021-02-02 23:33
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/the-eternal-sync-bug/334

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-02 23:33 UTC
Labels: audit, contacts
