### ISSUE TITLE
Feature Request: Quick text template

### ISSUE THREAD

**Issue by howdev** [Foundry376/Mailspring#2209] opened 2020-11-27 01:50 UTC
allow flexible templates: instead of replacing entire email with a template, have another option of insert template, so that you can combine different templates in an email, like the thunderbird quicktext plugin

**Comment by CodeMouse92** [comment] 2021-03-03 03:48
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/snippets-include-templates-in-others/434

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-03 03:48 UTC
Labels: audit, enhancement
