### ISSUE TITLE
tracking across desktops not working

### ISSUE THREAD

**Issue by Sailorbare** [Foundry376/Mailspring#1553] opened 2019-06-30 20:56 UTC
I'm running Mailspring version 1.6,1 aceed8e5 on Windows 10
I use it on my desktop and my ThinkPad

When I was using Win7, I could always see open and tracking notifications across both desktops, (desktop and laptop) but after I migrated to Win10, the open notifications only show up on the machine where the msg was sent from. 
I tried sending a msg from my Win7 and the open notification will not cross over from Win7 to Win10

Any ideas? Is anyone else experiencing this problem?
Is this a programming tweak that can be fixed so a user can track opens and clicks across multiple desktops?

**Comment by bengotow** [comment] 2019-07-01 00:40
Hey! Could you try upgrading the app to version 1.6.2 on both your machines? (The updates should install automatically). It might be that this wasn't working because one machine upgraded to the latest version and the other didn't?

**Comment by Sailorbare** [comment] 2019-07-01 15:50
I noticed the issue the first day I installed Mailspring, so on that date both machines were running the same latest version, I updated both and checked, all are running on the same version, same issue

**Comment by Sailorbare** [comment] 2019-07-12 22:49
I have had to continue using one of my Win7 machines to track replies, opens and link clicks to any emails I sent out using Mailspring that were sent from a Win7 desktop. 
On my Win10 desktops I can see the emails that were sent under Win7, but there is no tracking icon present, not even the dimmed one that shows that an email hasn't been opened yet. 
Do you have any suggestions as to what I can do to get indicators to show up in Win10?

And yes I have continued to update to the latest version

**Comment by CodeMouse92** [comment] 2021-02-03 00:10
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/sync-templates-signatures-accounts-etc-accross-multiple-devices/265

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-03 00:10 UTC
Labels: audit, support
