### ISSUE TITLE
Feature request: Select multiple folders with ctrl-click

### ISSUE THREAD

**Issue by paulr4** [Foundry376/Mailspring#481] opened 2017-12-28 16:51 UTC
##### Are there any related issues?

Haven't found any

##### What operating system are you using?
Windows

##### What version of Mailspring are you using?
1.0.11

--

**Feature Request?**
Gmail implements 'labels' to organise emails, and multiple labels can be applied to each message. When accessing Gmail through IMAP, these labels are accessible as IMAP folders. Mailspring calls them 'Labels' in the left-hand pane, and they can be accessed one at a time, like folders. I'd like to propose that ctrl-clicking multiple labels will apply an 'AND' filter to emails with the selected labels, so I can easily select emails labelled, for example, both 'Work' and 'To do'. I hope this wouldn't be too complicated to implement and would be hugely useful.

##### Does this feature exist in another mail client or tool you use?
I've searched high and low for a client that implements labels this way, and have not found a single one that does. However, Evernote uses labels (it calls them 'tags') for sorting notes, and the result is very powerful and user friendly.

**Comment by bengotow** [comment] 2017-12-29 03:25
Hey! You can actually do this now in Mailspring using search - if you type `in:A AND in:B`, it'll show only threads with both those labels. Doing it via multiple selection would be cool though.

**Comment by CodeMouse92** [comment] 2021-02-20 03:33
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/select-multiple-folders-with-ctrl-click/715

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@paulr4: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-20 03:33 UTC
Labels: audit, enhancement
