### ISSUE TITLE
Add feature Forward email as original 

### ISSUE THREAD

**Issue by annguyen209** [Foundry376/Mailspring#852] opened 2018-05-08 04:14 UTC
##### What operating system are you using?
Windows 10

##### What version of Mailspring are you using?
1.2.1

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Yes. EM client.

**Comment by CodeMouse92** [comment] 2021-02-05 00:27
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/edit-as-new-message-resend-email-to-another-recipient/456

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

**If you're wanting different functionality than what is described in that feature suggestion, please create a new Feature Suggestion on our Discourse: https://community.getmailspring.com**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-05 00:27 UTC
Labels: audit, enhancement
