### ISSUE TITLE
No notification if mail comes to any other folder beside inbox.

### ISSUE THREAD

**Issue by TrunovS** [Foundry376/Mailspring#667] opened 2018-02-08 15:26 UTC
No notification if mail comes to any other folder beside inbox.
On server side i have folders (inbox, bank, steam, tourism etc.) on the same hierarchy level, to which mail sorts by server expression rules as it comes. Some mails remains in inbox folder, others no. But if unread mail comes to any other folder beside inbox there is no notification about incoming mail. I checked option to "show unread counts near every folder" and it works, but it seems that all that mail is not beeing classificated as unread. Tried to move my folders as inbox subfolders, nothing changed too.

##### Are there any related issues?

Looks like no.

##### What operating system are you 
Linux, Debian 9.

##### What version of Mailspring are you using?
1.1.3-27dcee2f

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
IMAP server ( mail.ru )

**Comment by TrunovS** [comment] 2018-02-10 12:51
![image](https://user-images.githubusercontent.com/13647806/36062283-2a95e402-0e7a-11e8-814f-eecd73215a9e.png)

**Comment by JakeCowton** [comment] 2018-07-14 11:36
Just to add, this affects me on Ubuntu 16.04, 18.04 and Windows 10 (all 64 bit).

**Comment by wasiflaeeq** [comment] 2018-07-19 15:21
Same issue for me. No notifications and no mail counts on folders except inbox. Emails are marked unread inside the folders...

Using 3 emails on cPanel IMAP.

Using 1.3.0-fd741eb7 on ubuntu 18.04

**Comment by marvinlwenzel** [comment] 2018-08-09 12:01
Same here.
I automatically order all incoming mails into subfolders inside of the Inbox to order then by "severity". And I do not get notifications from those subfolders either.

I guess this would be a feature request? Given I have never seen this (by us) expected behavior would be the intended one.

**Comment by fallenagus** [comment] 2018-08-23 09:27
Same here, on windows 10 :(

**Comment by logan-dunbar** [comment] 2018-11-29 14:10
Also experiencing this, Ubuntu 18.04

**Comment by jesusvpct** [comment] 2019-03-24 15:22
Same here. I'm back to Thunderbird because of this.

**Comment by Kawsihen** [comment] 2019-04-05 00:54
I think this is a serious bug, please escalate. I missed several e-mails on my Red Hat machine until I noticed that the mails arriving in sub-folders would not display any notification.

**Comment by CthulhuDev** [comment] 2020-02-19 14:17
Still no news? I am also on the same train, I usually apply a filter so that every client of mine has a folder, I would to see notifications on each folder!

**Comment by tarantelklient** [comment] 2020-02-20 10:10
Seems like no.. I'm also waiting for this feature.. The client is cool, but I don't want to put all my mails in my inbox to get a notification..

Maybe it's possible to create a plugin for this? They provide a template for it.. https://github.com/Foundry376/Mailspring-Plugin-Starter

**Comment by CthulhuDev** [comment] 2020-02-20 10:56
> Seems like no.. I'm also waiting for this feature.. The client is cool, but I don't want to put all my mails in my inbox to get a notification..
> 
> Maybe it's possible to create a plugin for this? They provide a template for it.. https://github.com/Foundry376/Mailspring-Plugin-Starter

Plugin could be a solution if the APIs provide you enough freedom to apply badges on folders. I'll take a look at it and maybe give it a shot but don't count on it, I'll keep you updated

**Comment by tarantelklient** [comment] 2020-02-20 10:59
"Only" the notification is missing.

At the moment i'll take a look every half an hour and can see the badge with the correct number. So the client receives all mails, but isn't able to notify the user.

**Comment by CthulhuDev** [comment] 2020-02-20 12:10
![Screenshot from 2020-02-20 13-08-02](https://user-images.githubusercontent.com/1218730/74932509-4a26ea00-53e2-11ea-944f-ca1609105998.png)
On these folders on the sidebar I can't see any notification badge when a mail comes.

**Comment by tarantelklient** [comment] 2020-02-20 12:12
hmm, do you use the rules from Mailspring to sort your E-Mails? I use the sort rules from my mail provider and only display it in Mailspring.

**Comment by jacksonP51** [comment] 2020-02-27 11:18
Same, Ubuntu 19.10, ver 1.7.4-d54ff730

**Comment by canercanbaz** [comment] 2020-03-19 13:07
I am waiting for this feature.
It should not take too long.

**Comment by JakeCowton** [comment] 2020-03-19 13:53
Are you/is someone you know working on a pull request?

**Comment by canercanbaz** [comment] 2020-03-19 14:18
No, actually I would love to.
I wish this feature immediately arrived.

**Comment by 183amir** [comment] 2020-03-26 12:22
Ideally, we should be able to select the folders that we want to receive notifications from.

**Comment by velkom** [comment] 2020-05-07 09:17
Any updates? We need these feature guys.

**Comment by Rigo-m** [comment] 2020-05-07 10:06
I have downloaded the latest version and now I have a badge that tells me how many unread mails I have in folders

**Comment by howdoicomputer** [comment] 2020-06-02 20:18
There are also other issues open that are asking for the same feature: https://github.com/Foundry376/Mailspring/issues/1316

@bengotow Is this on the road map?

The lack of notifications really leaves this client dead in the water. A lot of people use folders to differentiate between important emails and noise. I am trying to wrestle with the incredibly high volume of emails I get for work and want to use folders to help manage that. High priority emails that I need to look at immediately would go into a high priority folder. Low priority emails go into a low priority folder. But what's the point of putting high priority emails in a folder via a rule if I lose out on notifications?

So I guess it's back to sorting through dozens of emails in my main inbox to find that one email that I needed to respond to quickly.

**Comment by CodeMouse92** [comment] 2021-01-28 01:39
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/notifications-on-non-inbox-folders/323

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@TrunovS: if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 01:39 UTC
Labels: audit, product-direction
