### ISSUE TITLE
Bug: ctrl+q closes program instead of marking mail as read with Outlook shortcuts

### ISSUE THREAD

**Issue by fionnan-r** [Foundry376/Mailspring#2098] opened 2020-07-21 08:02 UTC
Control+q causes Mailspring to close instead of mark mail as read with Outlook shortcuts. Other Outlook shortcuts work as expected (eg. ctrl+u marks as unread).

I have checked the logs (eg. "user\AppData\Roaming\Mailspring\mailsync-f50f4c66.log") and there seems to be no evidence of the program either closing gracefully or an exception.

I can try running it with debug flags but it requires me to log into my accounts again. Let me know if necessary

**To Reproduce**
1. Set keyboard shortcuts to Outlook
2. Mark message as unread with ctrl+q

**Expected behavior**
Mail should be marked as read

**Setup: (please complete the following information):**
 - OS: Windows 10
 - OS Version 2004
 - Mailspring Version: 1.7.8

**Comment by fionnan-r** [comment] 2020-10-01 07:22
Is it possibly to do with the Outlook template still using "ctrl" instead of "mod" in the keymap json here: https://github.com/Foundry376/Mailspring/blob/master/app/keymaps/templates/Outlook.json#L16?

```
 "core:focus-item": "ctrl+o",
  "core:mark-as-read": "ctrl+q",
  "core:mark-as-unread": "ctrl+u",
  "core:star-item": "ctrl+shift+g",
```
Should all be changed I think

**Comment by CodeMouse92** [comment] 2021-03-02 21:29
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/ctrl-q-closes-program-instead-of-marking-mail-as-read-with-outlook-shortcuts/940

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@fionnan-r: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 21:29 UTC
Labels: audit, bug
