### ISSUE TITLE
Bug: Msgs Marked as Read Reappeared as Unread

### ISSUE THREAD

**Issue by liamkit** [Foundry376/Mailspring#1908] opened 2020-04-16 17:47 UTC
**Describe the bug**
I generally go to the Unread box and marked msgs as read. Quite often, msgs that are marked as read this way turned back to Unread later.

This seems to happen if Unread is showing msgs for multiple accounts. I have 3 different gmail accounts under mailspring. When msgs turned back as Unread, all msgs in the same account turned back to Unread.

If I go to Unread for each account and mark the msgs as read, it seems to work all the time, i.e. if I mark the unread msgs as read, they stay read. Since I have 3 different accounts, I have to do it 3 times.

Similar behaviors happens on ubuntu 18 running same version of mailspring.

**To Reproduce**
1 Go to 'Unread'
2 enter '*a'
3 enter'^I'
4 all msgs marked as read
5 go back to 'Unread' after minutes (10 min?)
6 some msgs previous marked as read turned back to Unread.

**Expected behavior**
After msgs marked as read, they should stay as read.

**Setup: (please complete the following information):**
OS: macOS
OS Version 10.15.4
Mailspring Version: 1.7.4

**Comment by phhemberg** [comment] 2020-07-16 14:18
In addition to above mentioned:

When 
1. enter '*a'
2. select all as unread
3. enter '*a'
4. select all as read
Mailspring still shows that (in my case) 2 are unread:

![image](https://user-images.githubusercontent.com/30298982/87682230-e7166500-c77f-11ea-9f42-dfbf3c0a93df.png)

**Comment by CodeMouse92** [comment] 2021-02-27 03:15
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/disappearing-emails-desync/428

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-27 03:15 UTC
Labels: audit, bug
