### ISSUE TITLE
error while syncing

### ISSUE THREAD

**Issue by franco27** [Foundry376/Mailspring#357] opened 2017-11-20 19:10 UTC
Hello

For several days / several weeks, Mailspring is configured. There was no update.
I have not changed accounts or added a new email account
1/I closed and opened the software many times
2/ restarting the computer
3/ there was no error message (for several weeks or since the availability of this version 108)

Today I open Mailspring and an error message is displayed for a single mail account.
This error message is displayed permanently.

I tried to click on the button "Try again".I did not solve this problem.
I deleted this account and I wanted to add it again: error message.

I'm stuck or jammed.
I have another email address or other email account from the same provider that is working properly.
I do not understand !

##### What operating system are you using?
Windows10 x32bits

##### What version of Mailspring are you using?
1.0.8

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
no , none

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
GMX  (https://www.gmx.fr/)

##### Is the issue reproducible with a particular attachment, message, signature, etc?
The error is repeated after complete closure (without the icon in the notification area) and opening.

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
I tried with another mail software during this error with Mailspring. There is no problem !

[1171020-34296-zcck9h.v398.log](https://github.com/Foundry376/Mailspring/files/1488811/1171020-34296-zcck9h.v398.log)
![mailspring_2017-11-20_19-02-26](https://user-images.githubusercontent.com/31793920/33036511-df74c71c-ce2e-11e7-991b-6e4058f58e56.png)
![mailspring_2017-11-20_19-03-28](https://user-images.githubusercontent.com/31793920/33036512-dfa12bcc-ce2e-11e7-85b6-9005f9d91db4.png)

**Comment by franco27** [comment] 2017-11-21 11:18
On another computer, with Windows10 x64, this mail account still works perfectly.
(initially installed with version 1.0.7 of Mailspring + update 1.0.8 performed)

Before the account is deleted, this error message flashes continuously : "...error while syncing ". I can not stop it and even clicking "Try Again"
I had a lot of trouble removing this account because in account settings,and when this account is selected, the button for deleted an account: moves continuously, appears and disappears continuously. (with an error message on blinking red background too)

**Comment by franco27** [comment] 2017-11-21 11:24
Today, I can not add this account again because there is an error message. (---> view log)

**Comment by franco27** [comment] 2017-11-21 12:05
I had noticed with the original version of Nylas Mail, that after deletion of an account: the parameters are deleted but the messages of this account are always stored on the computer.

Example: previously with Nylas, ...
1/ I deleted an email account (in the settings and in the interface this account has been deleted)
2/ after I had again wanted to add this same account. The account was well added again (the same account mail : no problem for add)
3/ but I was surprised that there was no synchronization again for the same account that I had just deleted and added again.
The Nylas software has retrieved previously synchronized messages before deleting of this same account and has also recovered the errors. (because of an error, I could not use it)
4/I was able to solve this problem only by completely uninstalling Nylas and deleting Nylas folders in my user folder.
5 / after deleting Nylas folders, I was forced to add my email accounts again but this time with a synchronization of all my email accounts.
I had no more error messages for the mail account that previously had an error message and whose removal and creation of the account did not resolve the problem.

**Comment by franco27** [comment] 2017-11-21 12:26
I had thought to try to solve this problem. I wanted delete the folder of my account francois.m2@gmx.fr with all his messages. (in the user folder)
I can not find it .

**Comment by bengotow** [comment] 2017-11-25 20:56
Hey! Thanks for reporting this—It sounds like a message in your account is probably crashing the sync worker, so it'll run for some time but eventually hit that email and crash. This is definitely a bug. I'll see if I can get it fixed in an upcoming release - I'm working on additional crash reporting to make finding these edge cases a bit easier.

**Comment by IamKennedyKambo** [comment] 2019-03-02 20:23
I also have the same problem and thought it was related to a certain sender as it has happened to two of my accounts but only after I subscribed to a couple of channels.Don't know which one yet.

**Comment by Funeoz** [comment] 2019-03-06 09:44
Same error here with a Gmail account on Ubuntu 18.10.

**Comment by CodeMouse92** [comment] 2021-01-29 23:38
Hi all,

2020 prevented much development work on Mailspring, but rest assured, development has resumed! We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

@franco27, @IamKennedyKambo, or anyone else: Can you please confirm that this is still broken with 1.8.0, and if so, open a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-29 23:38 UTC
Labels: audit, mailserver-incompatibility, needs-reproduction
