### ISSUE TITLE
Feature Request: Hide message preview line

### ISSUE THREAD

**Issue by alteoxCOM** [Foundry376/Mailspring#2192] opened 2020-11-04 08:31 UTC
Hello,

is there any possibility to deactivate the preview line of the messages in the list view?
https://ibb.co/7pzsjtX

If not, can we pleas add this as feature? 🤓

Thank you!

**Comment by CodeMouse92** [comment] 2021-03-03 03:41
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/hide-message-preview-line/966

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@alteoxCOM: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-03 03:41 UTC
Labels: audit, enhancement
