### ISSUE TITLE
Couldn't resolve host name

### ISSUE THREAD

**Issue by diego1215** [Foundry376/Mailspring#1414] opened 2019-03-11 10:38 UTC
##### Are there any related issues?

No directly related with VPN

...

##### What operating system are you using?

... PopOS 18.10

##### What version of Mailspring are you using?
1.5.7-2057ca30
...

**Bug?**

After establishing a VPN through the Express **VPN** service; Mailspring is unable to resolve the DNS name. Then is offline during the VPN session.  The thing is it is the only application on my system who has this issue.

../../../../mailsync-XXXX.log

5264 [2019-03-11 11:05:35.893] [metadata] [info] Metadata delta stream starting...
5264 [2019-03-11 11:05:35.893] [metadata] [info] Metadata delta stream closed.
5264 [2019-03-11 11:05:35.902] [metadata] [info] Encountered error: {"debuginfo":"","key":"Couldn't resolve host name","retryable":true,"what":"std::exception"}. Will retry in 3 sec.
5264 [2019-03-11 11:05:38.903] [metadata] [info] Metadata delta stream starting...
5264 [2019-03-11 11:05:38.904] [metadata] [info] Metadata delta stream closed.
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

...
Gmail accounts.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

...

**Comment by bengotow** [comment] 2019-03-16 18:54
Hey! Thanks for reporting this - this is pretty interesting. That particular error is coming from the "metadata sync" part of the app that keeps your snooze dates, read receipts, etc. synced with our servers, so it's trying to reach https://id.getmailspring.com/. Could you double check and make sure that address is accessible from within your VPN? (It should be...)

Have you set up your VPN on a separate network interface by any chance? Internally, the sync engine uses libCURL to make HTTP requests (they have a C++ library as well as the well known command line tool), and it looks like curl doesn't autodetect that it should use the separate network interface if you've set up your VPN that way, but otherwise it should work.

**Comment by LeAcid** [comment] 2019-03-22 16:07
I am experiencing the same issue as well. Is there a way to start mailspring and require it to use a specific interface? I am also using ExpressVPN while experiencing these issues.

**Comment by diego1215** [comment] 2019-03-25 08:58
> I am experiencing the same issue as well. Is there a way to start mailspring and require it to use a specific interface? I am also using ExpressVPN while experiencing these issues.

I am not pretty sure but, Did  you use *snap* installation for Mailpring?   I changed my OS from Ubuntu 18.10 to Debian 9 but  I had the same issue, so I removed the snap version and then install the .deb version. For my, at least now it's working, maybe you should try this way.

**Comment by LeAcid** [comment] 2019-03-25 12:47
Diego, that fixed it for me. Thank you for the help. I guess that should help confirm that it is only the snap that has issues with using the VPN.

**Comment by ConstantinoGoo** [comment] 2019-06-10 14:38
Diego, that fixed it for me too. Thanks for the help!

**Comment by adilimudassir** [comment] 2019-06-23 09:04
Wow! Thanks, it worked for me too

**Comment by nelhu** [comment] 2019-08-19 03:18
I am experiencing the same issue and I just close the VPN then retry, for me, it's just worked! May be you can try this way

**Comment by gerroon** [comment] 2019-12-22 02:00
I have the same issue because I have a very strick firewall and network blocking. 

Does it mean that this app is not usable without some ID from getmailspring servers?

**Comment by CodeMouse92** [comment] 2021-01-30 00:40
@gerroon At this time, we do require a Mailspring ID. That may change in the future.

---

It appears that this issue has been resolved, so we are closing it. If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-30 00:40 UTC
Labels: audit, needs-reproduction
