### ISSUE TITLE
[Feature Request] Mentions

### ISSUE THREAD

**Issue by phileastv** [Foundry376/Mailspring#1711] opened 2019-11-17 15:07 UTC
Hello ! With features like Calendar and Contacts slowly coming, it seems like Mailspring is becoming a full productivity suite, targeted for people who has a lot of e-mails to process every day.

A feature which will be great for those people will be to be able **to mention user in the composer**.

## Does this feature exist in another mail client or tool you use?

[This feature exists in Microsoft Outlook](https://support.office.com/en-us/article/use-mentions-to-get-someone-s-attention-90701709-5dc1-41c7-aa48-b01d4a46e8c7?omkt=en-001&ui=en-US&rs=en-001&ad=US) desktop and web client. And [in the new Gmail web client](https://www.androidpolice.com/2018/05/18/tip-new-gmail-supports-mentions-adding-email-recipients-type-name/).

I will take an example of how Outlook does this, as it seems like a pretty standard way of doing mentions. The great news is that Gmail seems to do exactly the same thing, that's great for compatibility!

### When you are compositing a mail
When you are composing a mail, and writing a "@", a list shows up with an auto-completion of the contacts you have. Once selected contact is selected 

- The mention will appear as a highlighted text
- A link will be added on the text like this "mailto:myselectedcontact@example.com"
- The selected contact will be added in the "To" (or "Copy To") field

#### If there's a mention (a text with starting with a @ and a link starting by "mailto:")

- The text will be highlighted
- A mini contact-card will be showing when mouse hover

#### When you are mentioned (a text starting with a @ and a link starting by "mailto:youremail@example.com")

- A "@" badge shows up in the e-mail list

## The way it can be implemented in Mailspring

As I find the way that Outlook does this to be pretty complete and useful, all of these features are not necessary. In the first place, just autocomplete contacts in the composer can be enough, and save a lot of time.

Thanks again for all the contributors of Mailspring mail which is really becoming a great and fully featured email client !

**Comment by MM-coder** [comment] 2019-12-07 21:37
I'd love to see this!

**Comment by CodeMouse92** [comment] 2021-01-28 02:42
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mentions-in-composer/328

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@phileastv : if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 02:42 UTC
Labels: audit, enhancement
