### ISSUE TITLE
Mailspring does not preserve custom MIME headers when creating replies 

### ISSUE THREAD

**Issue by ribanez7** [Foundry376/Mailspring#776] opened 2018-03-21 10:46 UTC
##### Are there any related issues?

No

##### What operating system are you using?
Ubuntu 16.04

##### What version of Mailspring are you using?
1.1.5

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
No

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
No.

Mailspring is removing custom headers provided from the sender once I reply. I found it when replying to issues generated via Gitlab: we have gitlab configured to allow developers reply to emails and generate comments on issues. Gitlab controls the thread via two custom headers:

```yml
Thread-Topic: repo-name | issue title (#225)
Thread-Index: FOmNZclVgug6MVht1qPdoXk9XWrm4w==
```

As Mailspring destroys these headers on doing a reply, gitlab is not able to recognize the email sent.
I suppose this will happen with any header related logic regarding emails comunication.

Is there any option to prevent removing the headers?

Thanks!

**Comment by bengotow** [comment] 2018-03-24 17:31
Hmm this is interesting—AFAIK there's not any formal spec for maintaining headers when building a reply. You basically just take the MIME `Message-ID` of the previous message and place it in the `In-Reply-To` or `References` headers, and it's otherwise identical to a new message.

It seems like your client is probably detecting headers that begin with `Thread-` and preserving them. Will see if I can find a spec related to this and we can change the Mailspring behavior.

**Comment by bengotow** [comment] 2018-03-24 17:36
Hmm... so based on the information I've found on StackOverflow (can't seem to find a spec related to this...), it doesn't seem like this is really a correct way for GitLab to be implementing this feature. I know GitHub uses a custom reply-to address, and that seems to be the suggested approach. It looks like users of Outlook have also complained about not being able to reply to Gitlab emails.

That said, I think we should be able to fix this - it's just a matter of being careful and picking out only custom headers that should be copied. A lot of spam protection systems / antivirus tools, etc. add headers server-side, and re-applying those to new emails would be bad.

- https://stackoverflow.com/questions/7591557/persistence-of-custom-headers-within-an-email-thread

- https://stackoverflow.com/questions/9323116/which-headers-are-always-returned-in-a-reply-forward

**Comment by CodeMouse92** [comment] 2021-02-25 00:41
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mailspring-does-not-preserve-custom-mime-headers-when-creating-replies/774

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@ribanez7: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-25 00:41 UTC
Labels: enhancement, migrated, product-direction
