### ISSUE TITLE
shortcut for marking spam ?

### ISSUE THREAD

**Issue by davduf** [Foundry376/Mailspring#546] opened 2018-01-19 13:32 UTC
Hello !

Love your app !I thing a shortcut for marking spam the message should be very very helpful.

Any idea ?
My very best

David

**Comment by Pinchanzee** [comment] 2018-02-05 16:35
I was surprised this wasn't among the default shortcuts too, and would also appreciate this.

**Comment by slintes** [comment] 2018-05-09 08:14
I just found found out that this is possible with `!`. I found that in the gmail keymap (https://github.com/Foundry376/Mailspring/blob/master/app/keymaps/templates/Gmail.json#L42), but it works on my imap account, too. Not sure if that is the case because I had a gmail account configured earlier, too.

**Comment by arthurlogilab** [comment] 2020-06-10 07:50
I would be in favor of this appearing in the edit panel in the preferences.

**Comment by CodeMouse92** [comment] 2021-01-30 01:11
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mark-as-spam-keyboard-shortcut/395

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-30 01:11 UTC
Labels: audit
