### ISSUE TITLE
Bug: losing mail by moving other mail

### ISSUE THREAD

**Issue by WoutDebacker** [Foundry376/Mailspring#2080] opened 2020-07-02 12:20 UTC
**Describe the bug**
Sometimes, when I move a mail to a label (by using shortcut "V" on my keyboard and sending it to a given label) the mail above disappears too. If you're not paying attention you can lose a mail this way. This is very frustrating because we have had this problem multiple times and forgot to answer important mail.
 
**To Reproduce**
1. Go to 'inbox'
2. Move mail to label with shortkey "V"
3. Select label and press enter

**Expected behavior**
You would expect to move selected mail into label/folder.

**Setup: (please complete the following information):**
 - OS: Windows 10 Pro
 - OS Version 1903
 - Mailspring Version: 1.7.8-13635bcf

**Additional context** 
The problem seems to be random. I'm trying to find out why it happens, but at the moment I haven't found the reason why this problem comes up.

**Comment by rjbathgate** [comment] 2020-07-10 03:28
I get the same issue, but instead of using a keyboard shortcut, it's sometimes when archiving an open email.

**Describe the bug**
When archiving one email, it will sometimes also archive the email above it/at the top of the inbox. 
Ditto re: If you're not paying attention you can lose a mail this way. This is very frustrating because we have had this problem multiple times and forgot to answer important mail.
As a result, I have had to stop using Mailspring entirely until this is fixed.

**To Reproduce**
Steps to reproduce the behavior:

1. Go to 'inbox'
2. Open an email (so it opens in a new 'window') - possibly any email other than the top one.
3. Click archive

**Expected behavior**
You would expect to see that email archived, and then you are returned to the inbox.
This does happen, however the email at the top of the inbox (i.e. not the one you just archived), also gets archived.

**Setup:** 
OS: Ubuntu 20.04 LTS
Mailspring installed by Snap (self updating)
Mailspring Version: Latest Stable 1.7.8

**Comment by asparc** [comment] 2020-07-10 14:08
Can confirm. For me, this coupled behaviour sometimes (...) happens with archiving, deleting, starring, labelling... I have the impression that the coupled email isn't necessarily the email at the top of the inbox, but rather the email your most recently interacted with. I'm not entirely sure about this last statement though, as it is hard to reproduce this error (it only happens sometimes...).

This is a major issue, as it indeed results in unreliable behaviour or even lost emails! 
Please urgently fix!

**Comment by ReillyProcentive** [comment] 2020-07-21 21:31
I'm seeing this happen when I have send undo enabled and I reply to an email. If I then archive/move the email while the send timer is counting down the action gets applied to whatever email is selected after the first one is moved.

@bengotow Are you aware of this? It seems like this is a high-priority bug as this frequently happens without people noticing that extra emails have been moved/archived.

**Comment by rjbathgate** [comment] 2020-07-21 21:47
> I'm seeing this happen when I have send undo enabled and I reply to an email. If I then archive/move the email while the send timer is counting down the action gets applied to whatever email is selected after the first one is moved.
> 
@ReillyProcentive , I also have "send undo" enabled. I have since uninstalled MailSpring as it's unusable with this bug so can't test it with "send undo" disabled, but if anyone can confirm it doesn't happen if that's turned off, I may revisit.

**Comment by ReillyTevera** [comment] 2020-07-24 20:32
@rjbathgate I made the change to disable "send undo" a couple days ago and I haven't noticed any emails disappearing since. Not completely conclusive but for what it's worth I was losing 3-5 a day before that change.

**Comment by rjbathgate** [comment] 2020-07-26 22:04
I've been (re)using Mailspring for a few days now, with "send undo" disabled too, and so far, I haven't experienced the issue. So, it's not a solution (as send undo is handy), but moreso perhaps helpful to identify where the issue lies. But, based on the lack of action and huge amount of other un-actioned bugs, I'm not holding my breath for a fix...

**Comment by kaleidoscopique** [comment] 2020-09-17 10:44
Same here! Very frustrating :( I just moved to Spark because of that, this is a very dangerous bug when dealing with business emails. I hope it will be fixed. Good luck Mailspring's team! :)

**Comment by CodeMouse92** [comment] 2021-01-21 23:51
Thank you for reporting this, and for your patience. 2020 prevented much development work on Mailspring, but rest assured, development has resumed! **I am ensuring this is among the bugs to get top priority.**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/losing-mail-by-moving-other-mail-via-keyboard-shortcut/168

Please consider joining that community and continuing the discussion there! Because of all the insight, I chose to migrate the entire conversation above (I usually don't).

@WoutDebacker, @rjbathgate, @asparc, and @ReillyTevera: if you join and reply to the issue (or just PM me), the moderators can make an effort to reassign the post to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed** 2021-02-08 18:43 UTC
Labels: bug, migrated
