### ISSUE TITLE
Feature Request: keep the content area (where the email is displayed) black theme

### ISSUE THREAD

**Issue by avelino** [Foundry376/Mailspring#2109] opened 2020-07-31 11:55 UTC
I really like dark theme but I'm finding not everything should go dark. It would be nice if there was at least an option to keep the content area (where the email is displayed) white. I've found it very hard to read several emails because up till now, all email clients assume a white backdrop. I've attached a few examples below.

Today | Proposal
---|---
![Screen Shot 2020-07-31 at 08 47 27](https://user-images.githubusercontent.com/31996/89032460-1d6cec00-d30b-11ea-9efc-520f37061528.png) | ![Screen Shot 2020-07-31 at 08 53 33](https://user-images.githubusercontent.com/31996/89032574-5907b600-d30b-11ea-92d4-68cf81b34ac8.png)

**Comment by CodeMouse92** [comment] 2021-03-02 21:47
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/poor-text-rendering-in-dark-theme/886/7

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 21:47 UTC
Labels: audit, enhancement
