### ISSUE TITLE
Error 134 (SIGABRT) when connecting a Gmail account

### ISSUE THREAD

**Issue by DmitryLoki** [Foundry376/Mailspring#664] opened 2018-02-08 12:17 UTC
This bug is still here - https://github.com/Foundry376/Mailspring/issues/368, and it's the real block right now. 

Yesterday when you released 1.1.3 my Mailspring stucks in a state "Sending message... Checking mailbox...". Few restarts get the same behavior, and I've decided to clear ~/.config/Mailspring and start from scratches. 

And I got the same error when trying to login to my Gmail. 
![screenshot from 2018-02-08 15-01-06](https://user-images.githubusercontent.com/1115774/35972281-3a32135c-0ce2-11e8-839c-899922422621.png)

Using IMAP to get access to my emails is not an option because there are no Gmail labels which are crucial for me.

So, I feel so unhappy because the new release blocked my work with no option to revert.

**Comment by bengotow** [comment] 2018-02-09 21:24
Hey! Thanks for reporting this. I'll see if I can get to the bottom of this. Error 134 is `SIGABRT`, which means something pretty far down in the IMAP/SMTP library is crashing and I haven't been able to find another account this occurs with yet.

**Comment by DmitryLoki** [comment] 2018-02-11 18:02
@bengotow Is this any chance to add gmail account with this bug? maybe some kind of backdoor? I'm really stuck right now :((

many thanks in advance!

**Comment by DmitryLoki** [comment] 2018-02-14 10:19
wow! supercool!!!! thanks a lot! 

PS
In case of thinking about starting donation program (additionally to pro subscription) - I'm down :)

**Comment by DmitryLoki** [comment] 2018-02-14 22:15
@bengotow  Nooooo =(((
1.1.4, still there
![image](https://user-images.githubusercontent.com/1115774/36231067-c34caae8-11ed-11e8-945a-b2b13c82b11c.png)

**Comment by DmitryLoki** [comment] 2018-02-17 03:08
:(

**Comment by DmitryLoki** [comment] 2018-02-19 06:44
Hm.. It seems that this bug is relevant only for Ubuntu 16.10. I've tried live-USB with Ubuntu 17.10 and it works fine. It's also fine with macOS.

So, I've solved this just logged in macOS and then just copy the whole Mailspring user's folder to my Ubuntu 16.10 and it works.

**Comment by JulioAzcarate** [comment] 2018-04-04 14:39
Still the same error with gmail account: `An unexpected mailsync error occurred (134)`
I'm using:
> Mailspring-1.2.1
> Linux Ubuntu 17.10

**Comment by zhzy0077** [comment] 2018-05-06 08:45
Still facing the same problem "An unexpected mailsync error occurred (134)" when connecting to Gmail.
My environment: `Fedora 27`, `mailspring-1.2.1-7e7447b6`

**Comment by maobaoqi** [comment] 2018-07-07 07:05
Hi, I have the same error on Ubuntu 16.04.
Anybody solved it?

**Comment by DanielRios549** [comment] 2019-02-21 16:32
Same here, Linux Mint 19.1 and Mailspring 1.5.6

**Comment by wanecek** [comment] 2019-04-14 15:41
The same issue arose for me as well, on Mailspring 1.6.1 and Ubuntu 18.10, about one week ago.

**Comment by jonathanffon** [comment] 2019-04-21 14:41
Same issue+1 on Mailspring 1.6.1 and ArchLinux

**Comment by Al4han** [comment] 2020-02-16 16:18
Still got the same issue on version 1.7.2-4522b259 and Kubuntu 19.10.

**Comment by wowsonsun** [comment] 2020-03-12 02:53
Same issue+1 on Mailspring 1.7.4 and deepin 15.11

**Comment by rudrab** [comment] 2020-04-30 06:24
got same error on fedora 32
MainSpring 1.7.6 
error: mailsync:134

**Comment by alexandrepichon** [comment] 2020-04-30 14:05
Same error
Mailspring 1.7.6
MacOS 10.13.6

**Comment by JonatanE** [comment] 2020-05-27 11:10
Same error on Arch Linux
Mailspring 1.7.8

**Comment by Epicccal** [comment] 2020-10-10 01:01
Hello, Same Error On ParrotOS
I try to Connect Gmail with Proxy , But it returns Error

`# uname -a`
`Linux parrot 5.8.0-2parrot1-amd64 #1 SMP Debian 5.8.10-2parrot1 (2020-10-05) x86_64 GNU/Linux`

mailSpring 1.7.8-13635bcf

![2020-10-10_08-56](https://user-images.githubusercontent.com/34046030/95641813-11ee2c00-0ad7-11eb-8697-bae4f75612d9.png)

**Comment by akula22** [comment] 2020-11-13 13:52
такая же херня
mailspring -v
1.7.8-13635bcf
LMDE
Сначала норм работало, потом перестало, как пофиксить то?  другие ящики работают только с гуглом проблема

**Comment by CodeMouse92** [comment] 2021-02-02 01:23
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/gmail-mailsync-134/422

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-02 01:23 UTC
Labels: audit
