### ISSUE TITLE
[Feature request] Ability to set Send and Archive as default option

### ISSUE THREAD

**Issue by brianleejackson** [Foundry376/Mailspring#1249] opened 2018-11-27 19:49 UTC
Need the ability to set the "Send and Archive" as the default option. I archive 99% of my emails after replying, so it would be awesome to have an option to set this as default without having to click the little down arrow every single time.

Thanks!

**Comment by bengotow** [comment] 2018-12-18 20:10
Hey! We definitely need to add an option for this soon. It's actually already possible though, if you're willing to edit the app's preferences manually!

If you run Mailspring and go to Developer > Open Mailsync Logs in the menu, it'll reveal a folder in the Finder / Windows Explorer. In that folder, open the file `config.json` in a text editor.

If you scroll through the file you'll find a `sending` section - add a new row like the one highlighted here that sets the default send action to "send-and-archive":

<img width="620" alt="image" src="https://user-images.githubusercontent.com/1037212/50180170-c5ac7900-02bd-11e9-9b8a-9139467480b5.png">

If you re-launch Mailspring. send-and-archive will be the default for replies.

Hope that helps! Will see if we can get an actual dropdown into the app for this soon.

**Comment by brianleejackson** [comment] 2018-12-18 20:35
Awesome thanks, the config change does work. 😄

**Comment by itstheandre** [comment] 2020-01-17 08:32
Hello, is this only for pro users? I tried doing this and the app breaks... Did anything specific change since this implementation?

**Comment by brianleejackson** [comment] 2020-01-20 20:34
@itstheandre It worked for me on the free version. But I had to stop using Mailspring though a while back to this bug: https://github.com/Foundry376/Mailspring/issues/579 😢

**Comment by thomasjonas** [comment] 2020-03-24 13:01
@itstheandre works for me! Are you sure you didn't make any typo's? An extra comma or something like that? I've added `"defaultSendType": "send-and-archive",` on the line after `"sending": {`

**Comment by tknx** [comment] 2020-04-15 18:51
Not sure if this is the same issue - but I would like to see the send and archive option also have its own shortcut - so I could maybe use ctrl-enter for send and ctrl-shift-enter for send and archive.

**Comment by CodeMouse92** [comment] 2021-02-25 23:03
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/ability-to-set-send-and-archive-as-default-option/799

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@brianleejackson @tknx: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-25 23:03 UTC
Labels: audit, enhancement, product-direction
