### ISSUE TITLE
Text is black-on-black in dark theme, highlight color is wrong

### ISSUE THREAD

**Issue by OtterBrah** [Foundry376/Mailspring#1290] opened 2018-12-30 07:34 UTC
The text behavior changed in the most recent update. Before on the default dark themes, black text would automatically turn white to contrast the black background, but now the text is black and can't be seen against the dark background. 

The highlight text color is also now orange instead of the green it was before. Is there a way to to correct this or a guide/manual online to customize the theme colors to a file I can re-import in case the issue isn't fixed in the next update?

![image](https://user-images.githubusercontent.com/41702116/50545203-c350f580-0bc0-11e9-9ed8-2f8824a93e2b.png)

**Comment by eclipsed-ninja** [comment] 2018-12-31 07:50
I believe this must be due to this : https://github.com/Foundry376/Mailspring/commit/8a18d2eb4f0bb48293e979ce12722626db00ae3f

I was not able to find any other commit that might affect this, I'll dig around later

**Comment by ransagy** [comment] 2018-12-31 11:01
Anyone aware of a workaround? Ability to edit the theme to force a different font color for now?

**Comment by bengotow** [comment] 2019-01-01 00:57
Hey folks—thanks for reporting this. I think this is because we upgraded to Electron 4 (and with it, a newer version of Chromium) in the last release. Will see if I can track this down and we'll get a fix out ASAP

**Comment by bengotow** [comment] 2019-01-03 21:02
Hey! Just a heads up that the fix for this just shipped a few minutes ago—Mailspring will auto-update soon, and you can also download the new version directly here: https://github.com/Foundry376/Mailspring/releases/tag/1.5.5. Thanks!

**Comment by ransagy** [comment] 2019-01-03 21:09
Thanks Ben, much appreciated! Will verify on both my machines ASAP.

**Comment by dzek69** [comment] 2019-01-03 21:13
I can confirm it does work as expected now, thanks.

**Comment by kode54** [comment] 2019-01-04 00:51
Also confirmed.

**Closed** 2019-03-18 18:19 UTC
Labels: done-pending-release
