### ISSUE TITLE
Feature Request: Mute Individual Email Accounts

### ISSUE THREAD

**Issue by Radicitus** [Foundry376/Mailspring#1942] opened 2020-04-26 20:49 UTC
Hey!

I was just wondering if it is possible to implement muting notifications for specific email accounts. In my case, I have a school email, personal email, professional email, and spam email. I would like to be able to mute my spam email, so I don't get notifications for that account (as I would get *ahem*  spammed) but receive emails from my other accounts as before.

Thanks for looking!

**Comment by CodeMouse92** [comment] 2021-01-29 23:13
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/per-account-mailbox-notification-settings/133/4

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-29 23:13 UTC
Labels: audit, enhancement
