### ISSUE TITLE
Feature Request: Folder customization (left pane)

### ISSUE THREAD

**Issue by RustBeard** [Foundry376/Mailspring#2062] opened 2020-06-20 12:30 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I need to search for my folders in a long list. 
I work in such a way that I am sorting incoming emails to folders "to do next", "can do later" and "archive". Every time I check my e-mail I looking into these folders to see is there something important to do. 

**Describe the solution you'd like**
Possibility to customize the top section (to show or hide folders there) or add a new section e.g. "favorites" where I can do it. 
I am working on multiple e-mail accounts and it is very helpful to me that you joining folders from every account (e.g. I see in inbox e-mails from all accounts). It will be nice if you can do something similar to this "favorites" folders – but this is not necessary for me now. 

**Additional context**
![image](https://user-images.githubusercontent.com/13813117/85201748-1f9e5c80-b302-11ea-8697-89ce509f1b18.png)
![image](https://user-images.githubusercontent.com/13813117/85201762-2e850f00-b302-11ea-933a-7dc5405be083.png)

**Comment by CodeMouse92** [comment] 2021-02-04 23:14
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/left-pane-hide-show-folders/469

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@RustBeard: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-04 23:14 UTC
Labels: audit, enhancement
