### ISSUE TITLE
Bug: Icons blurry when Mailspring started on low-DPI screen and moved to high-DPI screen

### ISSUE THREAD

**Issue by excitedleigh** [Foundry376/Mailspring#2081] opened 2020-07-06 00:47 UTC
**Describe the bug**

When I first open Mailspring on a low-DPI screen, and then move it to a high-DPI screen, I still get the @1x icons.

**To Reproduce**
1. Move Mailspring to a display at 1x scaling
2. Choose 'Reload' from the developer menu
3. Move it to a display at 2x scaling

**Expected behavior**
The 2x icons are used on the 2x screen.

**Screenshots**

<img width="152" alt="image" src="https://user-images.githubusercontent.com/473960/86545997-96c62880-bf71-11ea-8596-2e6943d5d03a.png">

**Setup: (please complete the following information):**
 - OS: macOS
 - OS Version 10.15.5 (19F101)
 - Mailspring Version: 1.7.8

**Comment by excitedleigh** [comment] 2020-07-06 00:49
Based on some devtools poking-around, it looks like the icons are `<img>` tags that use either the 1x or 2x resource depending on the DPI when they're first added. As a potentially-useless suggestion, without having (yet) poked around at the codebase itself, I wonder if using a [srcset](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-srcset) instead would work?

**Comment by CodeMouse92** [comment] 2021-03-02 18:42
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/icons-blurry-when-mailspring-started-on-low-dpi-screen-and-moved-to-high-dpi-screen/931

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@excitedleigh: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 18:42 UTC
Labels: audit, bug
