### ISSUE TITLE
Include templates in others

### ISSUE THREAD

**Issue by multiwebinc** [Foundry376/Mailspring#931] opened 2018-06-13 05:07 UTC
This is a feature request. Maybe to better understand it, let me start with a use case: 

Let's say, for example, you have an online store that sells 50 different widgets. You like to provide your customers with a description of the widget they purchased, so you make a template for each widget. However, you also like to include your company's branding in the email (a table with background color, your logo, etc), a column down the right hand side with links to a few popular articles, and a footer with links to your website, privacy policy, etc. Now let's say you want to modify a side link, add a link in the footer, and change the background color of one of the table cells. This now requires meticulously going through each of the 50 templates and modifying each one and hoping you don't make a mistake.

There needs to be a way around this. I have a few ideas:

1. Allow templates to extend other templates. Maybe something similar to [Laravel's blade templating engine](https://laravel.com/docs/5.6/blade). You have a main layout template which says it contains a "content" section. Then in a template that extends the main template you add a content section and it will be inserted at the correct position in the main template.
2. A simpler version of the above where in a template you simply do "{{include otherTemplate}}" and it includes that one at that point.
3. Allow templates to be added to the email without deleting the current content. This way the user could define a main layout template, add it to a blank email, click on the desired position where they want another template to be inserted and insert it. This is how the Thunderbird [Quicktext extension](https://addons.mozilla.org/en-US/thunderbird/addon/quicktext/?src=cb-dl-users) handles it.
4. Hopefully this doesn't get confusing to users, but add something called "snippets". The user defines a template for the layout, and only one template can be used per email (exactly like now), but they can also define small snippets of text or HTML to be inserted anywhere they want in an email, whether a template has been used or not, and any number of snippets can be inserted into a single email. This would benefit from being able to separate your presentation layer (template) from your content layer (snippets).

**Comment by CodeMouse92** [comment] 2021-02-03 02:45
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/snippets-include-templates-in-others/434

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@multiwebinc: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-03 02:45 UTC
Labels: audit
