### ISSUE TITLE
Notification / system tray icon doesn't show "check mark" unless the inbox is completely empty

### ISSUE THREAD

**Issue by raqua** [Foundry376/Mailspring#666] opened 2018-02-08 13:52 UTC
##### What operating system are you using?
Linux Mint 18.3

##### What version of Mailspring are you using?
1.1.3

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

I would expect that icon shows that I do have unread email and when there is no unread email, it should show the "tick". See attached picture. Icon appears as if there was unread email. I believe previous version did not do this, so regression maybe? 
![screenshot from 2018-02-08 14-48-06](https://user-images.githubusercontent.com/1541886/35976221-bce2641c-0cdf-11e8-8748-82a00b1bef81.jpg)

**Comment by bengotow** [comment] 2018-02-09 22:02
Hey! Thanks for reporting this—right now Mailspring only shows the check mark / tick mark if your inbox is completely empty (it goes along with that "inbox zero" animation that plays in your inbox.) I do think this is a bit confusing though, I'll see if we can refine the way this works in the future!

**Comment by CodeMouse92** [comment] 2021-01-30 02:11
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/badge-doesnt-always-appear-on-app-indicator-when-receiving-new-mail/392

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-30 02:11 UTC
Labels: audit, product-direction
