### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by ziordia68** [Foundry376/Mailspring#2186] opened 2020-10-28 17:44 UTC
**Describe the bug**
A clear and concise description of what the bug is. Does it happen with all email accounts, or only a particular account and/or email message?

Just after starting the view of my IMAP Mail account, I can see most of e-mails with "no date" (some of them have). This e-mail account is hosted in OVH mail.

OS: Manjaro Linux (current)
Mailspring Version: 1.7.8

**Comment by CodeMouse92** [comment] 2021-02-09 23:31
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/no-date-on-some-e-mails/538

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@ziordia68: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-09 23:31 UTC
Labels: audit, bug
