### ISSUE TITLE
Emails randomly get deleted

### ISSUE THREAD

**Issue by mod323** [Foundry376/Mailspring#2205] opened 2020-11-19 13:12 UTC
Hello, 

I often randomly find emails in my trash (that I did not delete). I'm not able to identify what triggers it and it seems to happen to emails that I have not interacted with. I typically find out about them when I search for old emails and eventually find them in the trash. 

Version 1.7.8
OS: Ubuntu

**Comment by kaleidoscopique** [comment] 2020-11-19 21:44
Same here, for months! Version 1.7.8 (1.7.8) OS/X.

Question: is it related to a Google Suit mailbox? Or an imap mailbox?
Because I got 4 inbox (1 Google and 3 IMAP) and I just noticed that bug with the Google one.

**Comment by mod323** [comment] 2020-11-22 06:48
The problem I'm facing is with an imap mailbox.

**Comment by PCPNIELSEN** [comment] 2020-11-23 09:44
If I delete a draft, the whole conversation seems to be deleted. (Google Workspace accounts)

**Comment by mod323** [comment] 2020-11-23 13:26
I do remember some of the emails deleted having deleted drafts - this could be the reason. I will observe and confirm if its the case but either way I hope Mailspring addresses this issue.

**Comment by CodeMouse92** [comment] 2020-12-21 20:33
@kaleidoscopique It's not discontinued. The maintainer has been overwhelmed, but he's still around, and plans to continue.

**Comment by CodeMouse92** [comment] 2020-12-30 23:25
@mod323 Were you ever able to follow up on your theory about the emails having deleted drafts? That'll be important for debugging.

**Comment by mod323** [comment] 2020-12-30 23:28
@CodeMouse92 yes I can confirm that deleting a draft will delete the email. 
I tried to avoid doing that but it's too inconvenient. This along with not being able to easily setup a custom signature made me unfortunately switch to Thunderbird.

**Comment by CodeMouse92** [comment] 2021-01-10 23:54
@mod323 I've been brought on as the volunteer community manager, and I'll be prioritizing bugs and helping plan releases for 2021. Hopefully we can get this resolved soon and make Mailspring usable for you again!

**Comment by tomastan** [comment] 2021-01-21 08:24
To help with prioritization +1 to this issue. I'm facing this as well. And it's really a serious problem with valuable conversations disappearing randomly.

**Comment by CodeMouse92** [comment] 2021-01-21 15:20
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/emails-randomly-get-deleted/143

Please consider joining that community and continuing the discussion there!

@mod323: if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it. **We'd also appreciate knowing what email services you use.**

@tomastan: Can you confirm this is occurring on 1.8.0? If so, please comment on that thread, and include your operating system (and its version), Mailspring version, and what email services you use.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-21 15:20 UTC
Labels: audit
