### ISSUE TITLE
NEW BUG - Cant Register Office365 Email with app - https://imgur.com/a/S90bgDK

### ISSUE THREAD

**Issue by automatesmallbig** [Foundry376/Mailspring#2268] opened 2021-01-28 21:14 UTC

**Comment by CodeMouse92** [comment] 2021-01-28 21:32
As mentioned in the Issue creation screen, we no longer accept bug reports through GitHub. Please see https://community.getmailspring.com/

I believe your issue may also be a duplicate of: https://community.getmailspring.com/t/institutional-office365-not-working/48

**Closed by CodeMouse92** 2021-01-28 21:32 UTC
