### ISSUE TITLE
Macos sends Mailspring to "sleep" at random times

### ISSUE THREAD

**Issue by kanunnikau** [Foundry376/Mailspring#1729] opened 2019-12-03 13:07 UTC
Rather regularly (about once every 1-2 weeks, maybe during times of high system load or if I haven't restarted mac for a few days) I notice a very annoying issue, where Mailspring stops doing anything in background.

Here's how I usually notice there is a problem:
- converse with someone over email
- type a new email response
- hit send. Watch "Sending soon..." countdown disappear, "Sending..." spinner appear
- close Mailspring window, leaving it running in the dock
- few hours later realise that there has been no response from my contact
- open Mailspring and observe the same "Sending..." spinner
- see Mailspring actually send an email, hours later
Sometimes Mailspring wakes up, then checkes for emails and spams me with 5-10 notifications for all the emails that I missed while Mailspring was inactive.

I have no idea how to reproduce this issue. Maybe someone can explain me how to collect pertinent logs, so that I share them next time I encounter the problem?

##### Are there any related issues?
I haven't found anything in GitHub

##### What operating system are you using?
macOS 10.14.6 

##### What version of Mailspring are you using?
Mailspring Version 1.7.2 (1.7.2)

##### Is this an email sync or connection issue?
No, local app running issue

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
No

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?
No

**Comment by CodeMouse92** [comment] 2021-02-08 18:36
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/macos-sends-mailspring-to-sleep-at-random-times/489
Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@kanunnikau: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-08 18:36 UTC
Labels: audit, macos, needs-reproduction
