### ISSUE TITLE
Feature Request: Need send and attach button at the top when dealing with long threads

### ISSUE THREAD

**Issue by m5shiv** [Foundry376/Mailspring#1976] opened 2020-05-10 01:48 UTC
**Is your feature request related to a problem? Please describe.**

With very long support threads, and large number of emails, I often struggle to find the "send" button and the "attach" button. I have to scroll to find it and it's not easy because the scroll size is not a page. Really really frustrating. 

**Describe the solution you'd like**
Send and Attach button at the top. Massive productivity win. Really massive.

**Describe alternatives you've considered**
No easy solution

**Additional context**

**Comment by CodeMouse92** [comment] 2021-03-01 23:34
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/style-send-button-tool-bar-with-fixed-positioning/577

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-01 23:34 UTC
Labels: audit, enhancement
