### ISSUE TITLE
[Feature Request] Move to Trash button on emails

### ISSUE THREAD

**Issue by rafabr4** [Foundry376/Mailspring#1509] opened 2019-05-26 17:09 UTC
Hello community,

I'd like to request to have a Delete/Move to Trash button on top of each individual email in the list view. Currently, I have to either right click and delete it, or open the email and use the button on top-right.

The button could appear when hovering over the email, like the Star or Mark as Important buttons do. The position could be under the Mark as Important, or on the right as I show on the image.

![trash_overlay](https://user-images.githubusercontent.com/36771169/58384892-4a5a9c00-7fae-11e9-82d7-4dc6639fc852.png)

Thanks for the awesome app!

**Comment by bengotow** [comment] 2019-05-26 21:38
Hey!  This is a great idea—right now these buttons do actually exist, but you have to use the "list" display mode or make the column more than ~500px wide to see them:

<img width="356" alt="image" src="https://user-images.githubusercontent.com/1037212/58387493-b3eda100-7fd4-11e9-8af2-fb07d57e3eb7.png">

Seems like we could probably make them appear in the narrow mode as well!

**Comment by rafabr4** [comment] 2019-05-27 03:10
Oh awesome! Didn't know that, thanks. Having all options would be nice.

**Comment by CodeMouse92** [comment] 2021-02-25 23:47
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/action-buttons-on-inbox-in-narrow-mode/807

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@rafabr4: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-25 23:47 UTC
Labels: audit, enhancement
