### ISSUE TITLE
Feature Request - Default Send As for aliases?

### ISSUE THREAD

**Issue by ITCMD** [Foundry376/Mailspring#1552] opened 2019-06-30 19:56 UTC
Pretty self explanitory, when selecting the default _send as_ address in preferences, I am unable to select an alias. This is a much needed feature for me and would be very appreciated!

**Comment by bengotow** [comment] 2019-07-02 02:51
Hey! Thanks for reporting this, I think this should be doable. Will look and see what we can do!

**Comment by CodeMouse92** [comment] 2021-02-26 16:55
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/default-send-as-for-aliases/821

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@ITCMD: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-26 16:55 UTC
Labels: audit, enhancement
