### ISSUE TITLE
Cannot delete unread mails

### ISSUE THREAD

**Issue by Sharlaan** [Foundry376/Mailspring#1584] opened 2019-07-20 10:24 UTC
##### Issue description
I noticed when clearing spams, that if if there is one single unread mail, it prevents all others following it to be deleted.

##### Reproduction
For example, let's say i have in my inbox :
"mail1, mail2, mail3, ...., mailN"
then i read mail3 for example.
then i decide to mass-delete from mail3 to mailN (without reading them !)
==> only mail3 gets deleted, but mail4...N stay in inbox.

If i open mails 4 to N to read them one by one, then the mass-delete works as intended.
This is super annoying and very risky as content from those mails has high probability of malwares or even trojans.
...

##### Versions
Windows10 Home
Mailspring latest (v1.6.3)
...

**Comment by CodeMouse92** [comment] 2021-02-10 23:30
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/mails-persist-in-the-trash-after-emptying-the-trash-or-the-junk/447

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-10 23:30 UTC
Labels: audit
