### ISSUE TITLE
better_sqlite3.node is not a valid Win32 application.

### ISSUE THREAD

**Issue by hechengjin** [Foundry376/Mailspring#2099] opened 2020-07-24 04:40 UTC
**Describe the bug**
npm start is ok
then
 npm run-script build
is ok.
bug when run 
Mailspring-win32-ia32/Mailspring.exe

better_sqlite3.node is not a valid Win32 application.

`

**Setup: (please complete the following information):**
 - OS: Windows 10 edu 64bit
 - OS Version 17763
 - Mailspring Version:  1.7.8

**Comment by Drarig29** [comment] 2021-02-26 17:30
I got the same error, this is because the `mailsync.tar.gz` which was extracted contains Linux libraries (.so) instead of Windows libraries (.dll).

**Comment by CodeMouse92** [comment] 2021-03-02 21:33
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

@hechengjin: Can you please confirm that this is still broken with 1.8.0, and if so, open a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 21:33 UTC
Labels: audit, bug, building-and-themeing, windows
