### ISSUE TITLE
persistent "one or more accounts are having connection issues." error

### ISSUE THREAD

**Issue by Miyazono1** [Foundry376/Mailspring#1973] opened 2020-05-08 02:20 UTC
as the title of the issue says. it's a persistent error in the corner that says "one or more accounts are having connection issues.". and when i click "try now", nothing happens. i've tried restarting the client, and it didn't work. i also tried re-authenticating the account, but it wouldn't connect, even though i can login to the website just fine.

one AOL account, one GMail account, and a school account that i think is through office365/onedrive

windows 10

version 1.7.6-e94bb759

**Comment by HaoZeke** [comment] 2020-05-09 01:50
Yeah I'm getting this on a google account.

**Comment by Miyazono1** [comment] 2020-05-09 05:12
> Yeah I'm getting this on a google account.

my google account is actually fine. i'm still getting emails from my gmail and school accounts, it's just not connecting my IMAP account. and they just fixed an issue similar to this as well.

**Comment by alvaro-leite** [comment] 2020-05-09 07:56
I'm getting this on two outlook accounts.

**Comment by Anillegalgoat** [comment] 2020-05-09 09:20
I'm getting this on an Aol account

1.7.6 on win 10

**Comment by Ade611** [comment] 2020-05-09 12:40
Do we know what they are doing about this?

**Comment by StevenMapes** [comment] 2020-05-11 14:00
Same. Since the latest update I'm having issues with this, the Yahoo mail bug and the client generally crashing or locking after a few minutes and becoming unusable. This is on Linux using the snapd package

**Comment by ShahNewazKhan** [comment] 2020-05-12 19:45
Same issue since last update `1.7.6-e94bb795`

**Comment by DrVeeDDS** [comment] 2020-05-12 21:09
same with both my yahoo and gmail accounts. Now the inboxes don't display at all. Can't add them again, because app password is not working.

**Comment by 233mhz** [comment] 2020-05-13 07:34
> same with both my yahoo and gmail accounts. Now the inboxes don't display at all. Can't add them again, because app password is not working.

Same problem

**Comment by aanred** [comment] 2020-05-14 02:43
Same issue and when I tried to reconnect I always get this error:

> Connection Error - Unable to connect to the server / port you provided. (IMAP)

But when I view the log, it is empty only contains this text "----------IMAP----------".

**Comment by ShahNewazKhan** [comment] 2020-05-14 02:44
Yup same empty log file with only:
```
"----------IMAP----------"
```

**Comment by southhill773** [comment] 2020-05-14 11:22
Same problem. 1.7.6 on Snap on Linux.

**Comment by prats-GH-50924** [comment] 2020-05-15 19:43
One more getting this on 1.7.6 on Windows 10 on an AOL account. Same error, same empty log file with just "----------IMAP----------". Meanwhile two Gmail accounts are working just fine. Connecting the same AOL account works immediately on other IMAP clients. Clearing cache and reinstalling both ineffective. Tried to remove and re-add the account and am unable.

**Comment by wulfalpha** [comment] 2020-05-16 00:36
Also having this problem with snap version AND windows version

**Comment by brandons209** [comment] 2020-05-16 05:28
I am having this issue only with my Aol account. 1.7.6 on Arch Linux. It seems to affect any account that you have to manually add IMAP settings for.

**Comment by knireis** [comment] 2020-05-25 19:51
I updated to 1.7.8 but this issue is still present. I am using Mailspring on Linux Mint 19.3. I don't know which account causes the issue, i have a few Google accounts and an imap account connected. Selecting try again removes the warning.

**Comment by dewzor** [comment] 2020-06-23 11:04
Same here on Win 10 with office 365 emails.

**Comment by BenjaminLindeen** [comment] 2020-07-09 16:28
I've been having this issue persist on my Desktop PC running Win 10, but my laptop on the same version of Win 10 is having no issues what so ever. I am able to get new emails from this Office 365 account but I am not able to view my love 1700 previous email. Solution?

**Comment by shalashik** [comment] 2020-11-16 20:53
I've experiencing the same issue on Ubuntu 20.04 and mailspring version 1.7.8. Each time I use the "Try now" button the following message is added to a log file
```
211883 [2020-11-16 23:50:56.562] [background] [info] --sleeping
211883 [2020-11-16 23:50:56.662] [metadataExpiration] [info] Scanning for expired metadata
211883 [2020-11-16 23:50:56.663] [metadataExpiration] [info] -- Will wake for next expiration in 7200sec
211883 [2020-11-16 23:50:56.671] [foreground] [info] Idle exited with code 0
211883 [2020-11-16 23:50:56.726] [foreground] [info] syncFolderUIDRange for INBOX, UIDs: 47918 - 48408, Heavy: false
211883 [2020-11-16 23:50:56.775] [foreground] [info] - remote=101, local=101
211883 [2020-11-16 23:50:56.781] [foreground] [info] Idling on folder INBOX
211883 [2020-11-16 23:50:58.708] [main] [info] Waking all workers...
211883 [2020-11-16 23:50:58.708] [background] [info] Marking all folders as `busy`
211883 [2020-11-16 23:50:58.734] [background] [info] Syncing folder list...
211883 [2020-11-16 23:50:58.736] [foreground] [info] Idle exited with code 0
211883 [2020-11-16 23:50:58.786] [foreground] [info] syncFolderUIDRange for INBOX, UIDs: 47918 - 48408, Heavy: false
211883 [2020-11-16 23:50:58.839] [foreground] [info] - remote=101, local=101
211883 [2020-11-16 23:50:58.844] [foreground] [info] Idling on folder INBOX
211883 [2020-11-16 23:50:58.982] [background] [info] syncFolderUIDRange for INBOX, UIDs: 1 - 47658, Heavy: false
211883 [2020-11-16 23:50:59.184] [background] [info] - remote=4161, local=1
211883 [2020-11-16 23:50:59.246] [background] [info] - Fetching full headers for 4160 (of 4160 needed)
211883 [2020-11-16 23:50:59.277] [background] [critical] 
***
*** Mailspring Sync 
*** An exception occurred during program execution: 
*** {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID (heavy)","key":"ErrorConnection","retryable":true,"what":"std::exception"}
***
```

**Comment by CodeMouse92** [comment] 2021-01-18 19:18
Thank you for your patience on this issue! I know it's frustrating when you cannot connect to your email with Mailspring.

2020 prevented much development work on Mailspring, but rest assured, development has resumed! A new release is slated for this week.

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We know about the institutional Office365 issues:

https://community.getmailspring.com/t/institutional-office365-not-working/48

**If you are having sync issues with other email clients, please [open a Sync Issue on our Discourse](https://community.getmailspring.com/c/sync/22). Problems with different providers may be unrelated to one another, and need to be considered separately.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-18 19:18 UTC
Labels: audit, mailserver-incompatibility, needs-reproduction
