### ISSUE TITLE
Mail rule creation interface needs to be changed

### ISSUE THREAD

**Issue by quixoticraindrp** [Foundry376/Mailspring#1275] opened 2018-12-19 18:30 UTC
##### Are there any related issues?
Not that I could see.

...

##### What operating system are you using?
macOS 10.14.2 (18C54)

...

##### What version of Mailspring are you using?

1.5.3

...

--

**Bug?**

##### Is this an email sync or connection issue?
No.

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No.

...

##### Is the issue reproducible with a particular attachment, message, signature, etc?
No.

...

--

**Feature Request?**

Mail rule creation should be in a separate or floating window with the inbox visible and manipulable. It should not require needing to repeatedly open and close the mail rules (aka Preferences)—which is required for either a multi-criteria rule, or for creating more than one rule at a time—or switching back and forth between Mailspring and another app (such as TextEdit or BBEdit) to copy & paste criteria.

##### Does this feature exist in another mail client or tool you use?
Pretty much all of the mail clients that I've used, which offer rules a user can create and/or manipulate, make it possible to create rules while actually looking at (and selecting/copying from) the inbox.

...

**Comment by CodeMouse92** [comment] 2021-02-05 00:31
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/manage-rules-in-a-popout-window/75

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@quixoticraindrp: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-05 00:31 UTC
Labels: audit, enhancement, product-direction
