### ISSUE TITLE
Bug: Support Mailspring deb installation on Kubuntu 20.04

### ISSUE THREAD

**Issue by tiago-as** [Foundry376/Mailspring#1828] opened 2020-02-28 13:51 UTC
**Describe the bug**
Cannot install .deb in Kubuntu 20.04. Mailspring depends on the **python** package, which does not exist in 20.04 repositories.

**To Reproduce**
Try to install the package with: **dpkg -i <package_name>.deb**

**Setup:**
- OS Kubuntu 20.04

**Additional context** 
I already installed all the other dependencies so **python** is the one left.
I'm testing mail clients on Kubuntu 20.04 to implement in customers, I'd like to add Mailspring to the list of options that I'm presenting to them.

**Comment by usfbrian** [comment] 2020-03-31 11:21
Duplicate of #1880

**Comment by CodeMouse92** [comment] 2021-02-23 22:26
It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-23 22:26 UTC
Labels: audit, bug
