### ISSUE TITLE
[Feature] Compose new message in same window

### ISSUE THREAD

**Issue by superDuperCyberTechno** [Foundry376/Mailspring#1391] opened 2019-02-27 09:34 UTC
Would it be possible to have the compose message window simply appear in the main window similar to when you read email when the reading pane is off?

**Comment by bengotow** [comment] 2019-03-16 20:07
Hey! This would be pretty cool - I'm hoping to get a plugin distribution system in to the app this year and I think this would make a great plugin. Will see what we can do 👍

**Comment by CodeMouse92** [comment] 2021-02-25 23:33
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/compose-new-message-in-same-window/803

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@superDuperCyberTechno: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-25 23:33 UTC
Labels: audit, enhancement, product-direction
