### ISSUE TITLE
Inbox unread count incorrect—persistent "1 new message"

### ISSUE THREAD

**Issue by briansholis** [Foundry376/Mailspring#726] opened 2018-02-26 01:36 UTC
##### What operating system are you using?
MacOS 10.13.3

##### What version of Mailspring are you using?
1.1.4-22d9f20d

##### Do you have any third-party plugins installed? If so, which ones?
None

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Perhaps—I only use Gmail, but it is appearing in one of three Gmail accounts I have synced to Mailspring.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

As you can see in the attached Mailspring and webmail screenshots, the app is reporting an unread message that is not appearing in the Gmail web interface (nor my wife's web interface; we share this account). I tried removing and re-adding the account, to no avail. Just thought I'd share in case someone else is having the same problem (though I didn't see anything about unread accounts when I searched known issues).

Thanks for a great and improving product.

Brian

![screen shot 2018-02-25 at 8 30 10 pm](https://user-images.githubusercontent.com/21323860/36649481-7daf85ec-1a6b-11e8-9185-9983e02b9778.jpg)
![screen shot 2018-02-25 at 8 30 23 pm](https://user-images.githubusercontent.com/21323860/36649482-7dbcaa42-1a6b-11e8-92bb-1754c97f0067.jpg)

**Comment by sam-lucas** [comment] 2018-02-26 21:23
Same here on Ubuntu 16.04, only I have also had a larger number on occasion. I am able to temporarily resolve the issue by marking ALL my mail as unread and then re-marking it as read, but the issue will eventually return. If I perform this action on my mail in chunks the number will decrement gradually, which seems to imply it is particular messages causing this bug and not just a random number.

**Comment by louim** [comment] 2018-03-07 21:59
Hey! Is this like #616 (which was a dupe of https://github.com/Foundry376/Mailspring/issues/247)? 

Have you checked in the **Unread** section just under **Inbox** like in the video? If the messages are there, that should at least help you do the toggle trick on the specific messages instead of the whole inbox. But yeah, I agree this is annoying, as it keep happening daily to me at least.

**Comment by RedaBousbah** [comment] 2018-05-02 08:17
In my case that solved the issue:
I had a message in the "Unread" section (as suggested by @louim .
There was a message, that was a series of collapsed messages. I think one of them was unread. I simply opened them all and then the new message was gone.

Hope it helps.

**Comment by lehasb** [comment] 2018-06-22 10:32
I've got the same issue. It is a specific thread of messages that was causing it. They would show up in the unread folder, but would display in every other way as being read (text normal instead of bold, "Mark as unread" icon in toolbar).

Gallium OS, no plugins, Mailspring 1.2.2-96fb3a99

**Comment by shandoosheri** [comment] 2018-08-04 01:18
I have the same issue and i have noticed it happens to me when I read an email using another email client.

**Comment by etekinbas** [comment] 2018-08-07 15:14
I have the same issue. I'm using Mac mail and Mailspring in a same time. I don't know that it causes this issue but this is really annoying..

**Comment by morfie78** [comment] 2018-08-28 18:21
Same. I used the mac client.

**Comment by joho** [comment] 2018-11-15 23:23
I've been getting this issue more frequently the past week or so. v1.5.2 on ubuntu 18.04.

To fix I need to go to unread, mark the thread as unread (because it's inexplicably unread there too), then mark as read.

**Comment by gabroo** [comment] 2019-04-11 08:14
this issue is still happening, ubuntu 18.04

**Comment by paulcarroll** [comment] 2019-07-31 23:56
FWIW I'm getting the same thing on MacOS Mojave 10.14.6 and Ubuntu 18.04

**Comment by surfingtomchen** [comment] 2020-01-28 19:16
can we just add a "marked as read" menu item as a defensive function to this bug? the number highlighted as unread but actually no is quite annoying.

**Comment by gabroo** [comment] 2020-01-28 19:42
This would be great. Currently one has to mark as unread and then view the email to clear the alert

**Comment by relgies** [comment] 2020-07-01 22:08
It's definitely an issue that needs to be corrected, however for those curious as to a short term fix there is a solution.  Go into "Unread" and then click on whatever the thread of emails is that's causing the incorrect unread mark.  Then at the top click the "Mark as Unread" (because even though it's claiming to be read, it's not letting you "Mark as Read" because of this bug).  Once you've done that it will change to allow you to "Mark as Read".

For the developers, I found this solution from someone who I recommended the software to when I went through and noticed that even after expanding the emails it still claimed it was unread.  Unfortunately my inbox is almost never at 0 (and in fact is usually several thousand beyond that :'D) but syncing and refreshing both did not, nor did expanding each message.  Although, and I double clicked on it rather fast so I cannot confirm this, but it seemed to mark it as read, or at least removed the '1' the moment I clicked "Mark as Unread".  Perhaps I didn't see it properly or perhaps that is a point in the direction of the error, but again it's not something solved by expanding, syncing, or restarting the application.

I hope this helps.

**Comment by ahmad-elkomy** [comment] 2020-11-19 15:00
> It's definitely an issue that needs to be corrected, however for those curious as to a short term fix there is a solution. **Go into "Unread" and then click on whatever the thread of emails is that's causing the incorrect unread mark. Then at the top click the "Mark as Unread" (because even though it's claiming to be read, it's not letting you "Mark as Read" because of this bug). Once you've done that it will change to allow you to "Mark as Read".**
> 
> For the developers, I found this solution from someone who I recommended the software to when I went through and noticed that even after expanding the emails it still claimed it was unread. Unfortunately my inbox is almost never at 0 (and in fact is usually several thousand beyond that :'D) but syncing and refreshing both did not, nor did expanding each message. Although, and I double clicked on it rather fast so I cannot confirm this, but it seemed to mark it as read, or at least removed the '1' the moment I clicked "Mark as Unread". Perhaps I didn't see it properly or perhaps that is a point in the direction of the error, but again it's not something solved by expanding, syncing, or restarting the application.
> 
> I hope this helps.
> 
> (On a side note I love the product and you really should consider a lifetime license because while I wouldn't pay a subscription fee for it I definitely would pay a decent bit to support the project if there was a lifetime license available. Either way keep up the great work.)

Thanks mate, that worked for me.

**Comment by CodeMouse92** [comment] 2021-01-28 18:39
Thank you for reporting this. 2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/unread-count-still-on-without-unread-messages/350

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 18:39 UTC
Labels: audit
