### ISSUE TITLE
Multiple emails appearing after sending to multiple recipients

### ISSUE THREAD

**Issue by ahmadov** [Foundry376/Mailspring#200] opened 2017-10-18 14:50 UTC
it sends the same email N (number of people in "TO") times to everyone.

**Comment by bengotow** [comment] 2017-10-19 01:06
Hey! where are you seeing these "N" emails? If you have link tracking or read receipts enabled, Mailspring does send N messages through your SMTP gateway, but you should only see a single copy in your sent mail folder.

If you continue having this issue can you send one of these messages to multiple recipients and then send me the contents of the mailsync-***.log file in the config folder (find it here: https://foundry376.zendesk.com/hc/en-us/articles/115001968632-How-do-I-manually-delete-cached-mail-data-and-settings-)? I think there must be a problem happening during the send flow.

**Comment by madve2** [comment] 2018-05-07 12:25
This happened to me as well – it was so embarrassing that I didn't dare using read receipts since then. (And the fact that Mailspring has made me beleive it was sent only once made matter worse...)

If Mailspring really _does_ send the e-mail N times, I think the issue might be related to the CC field (altough this is just a theory I have, I haven't experimented with it). In long conversations involving multiple people, some of the recepients often end up in the CC field instead of _To_, and that easily goes unnoticed. People CC'ed still shouldn't receive the e-mail more than once. If that's unfeasible for technical reasons, Mailspring should at least give a warning so that I can move every address to the _To_ field before sending.

**Comment by coopertinoUK** [comment] 2018-05-27 18:28
Same problem, Ubuntu 18
    Sent 1 mail to multiple destinations (3).
    The receipients of the mail have it in their inbox 3 times.

**Comment by msaharia** [comment] 2018-08-05 05:58
Just had the same issue. Mine got sent 10 times. This is not at all acceptable.

**Comment by vsanchez** [comment] 2018-10-10 21:19
Hi, this is repeatable. It happens only when sending from an Office 365 account, regardless of who are the recipients. It happens regardless where are the 2 addresses (both in the TO section or 1 in the TO section and the other in the CC). 

The problem is not there when using Gmail accounts. 

The last attempt with the repeated message is at 13:59 in log addresed to my email address (used to log in to GitHub)

[mailsync-57dd35e4.log.bak.gz](https://github.com/Foundry376/Mailspring/files/2466535/mailsync-57dd35e4.log.bak.gz)

**Comment by d-fault** [comment] 2018-10-11 00:49
Assume also related to #377 and #151

**Comment by minitesh** [comment] 2018-10-15 14:49
I am also facing same problem all of a sudden from last week.
Was working fine before that.

**Comment by cbamberg77** [comment] 2018-10-17 10:10
same here:
MacOS Mojave
Mailspring: Version 1.4.2-f587b7b7
Send Later: 5 seconds
Office 365

happens from time to time using reply all

**Comment by comanteodormihai** [comment] 2018-10-18 05:58
It happens also to me, on MacOSx mojave, latest verion (installed yesterday), office 365 account, send later: 15sec, read receipts active

**Comment by seshangamage** [comment] 2018-10-18 06:48
Hi All,

I was using office 365 account and when i reply all . it sends multiple copies to the same email address.


Thank You
![screenshot from 2018-10-18 12-16-16](https://user-images.githubusercontent.com/13871178/47136001-f0834c80-d2cf-11e8-8946-1bd89cd29a9f.png)

**Comment by vsanchez** [comment] 2018-10-26 14:46
Hi, 
The problem is apparently gone... maybe some fixes in Ofice365? Is that the case with everybody?

**Comment by seshangamage** [comment] 2018-10-30 07:14
Hi All,

The issue has been resolved after the new release. Thank You for fixing that 

https://github.com/Foundry376/Mailspring/releases/tag/1.5.1

**Comment by ignispider** [comment] 2018-12-21 18:06
Hello, everyone

I'm using mailspring on Debian 9 and it isn't gone. Even when I send to a single address, it shows 2 msgs in my sent box.

**Comment by joshbmartin** [comment] 2019-02-20 15:43
Ubuntu 18.04 same issue. Sending from 0365 account to multiple email groups in the company. If a person is in multiple groups it sends them multiple emails.

**Comment by sckv** [comment] 2019-03-20 20:12
Same issue 0365 account.

**Comment by CodeMouse92** [comment] 2021-01-29 22:24
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/duplication-of-sent-mail/275

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-29 22:24 UTC
Labels: audit, bug, needs-reproduction
