### ISSUE TITLE
[Feature Request] Recent searches / search history on top search bar 

### ISSUE THREAD

**Issue by remokon** [Foundry376/Mailspring#1025] opened 2018-08-14 08:33 UTC
Hey guys, I've been using mailspring for about two months and I would really appreciate a simple search history on the top bar. Queries reminders, but once you master them it'd be really cool to just see a search history, as in Gmail.

Thanks for your time!

##### What operating system are you using?

Ubuntu 18.04

##### What version of Mailspring are you using?

1.4.0

**Feature Request**

##### Does this feature exist in another mail client or tool you use?

Gmail, many others

**Comment by bengotow** [comment] 2018-08-15 01:52
Hey! This is a great suggestion - thanks! I'll see if we can get some recent search UI in there soon.

**Comment by CodeMouse92** [comment] 2021-02-25 01:24
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/recent-searches-search-history-on-top-search-bar/780/1

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@remokon: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-25 01:24 UTC
Labels: audit, enhancement
