### ISSUE TITLE
Bug: Notifications of new message arrivals appear in blank

### ISSUE THREAD

**Issue by jmirap** [Foundry376/Mailspring#1862] opened 2020-03-14 18:11 UTC
**Describe the bug**
Notifications on new mail arrival appear in the top right of the screen in a blank, except for two mail icons

**To Reproduce**
Steps to reproduce the behaviour:
1. new mail arrival
2. A notification appears in top right screen but completely blank except for two email icons

**Expected behaviour**
A notification box with an excerpt of a new message arrived.

**Screenshots**
N/A

**Setup: (please complete the following information):**
 - OS: Windows
 - OS Version 8,1
 - Mailspring Version: 1.7.4-d54ff730

**Additional context** 
N/A

**Comment by CodeMouse92** [comment] 2021-02-26 20:54
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/notifications-of-new-message-arrivals-appear-in-blank/846

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@jmirap: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-26 20:54 UTC
Labels: audit, bug
