### ISSUE TITLE
Bug: Synchronisation fails (always)

### ISSUE THREAD

**Issue by oddjobz** [Foundry376/Mailspring#2187] opened 2020-10-30 03:06 UTC
**Describe the bug**

Client attempts to synchronise email, managed to accomplish quite a lot, but eventually stops and reports that the client is no longer connected to the server and prompts for a retry.

**To Reproduce**
1. Start mail client
2. Wait for .. up to 30 mins for red "disconnected" box appears

**Expected behavior**
All mails should sync leaving the client functional, rather than disconnected and non-functional.

**Screenshots**
n/a

**Setup: (please complete the following information):**
 - OS: Ubuntu 18.10
 - Mailspring Version: 1.7.8 (.deb)
 - Mail server is Zimbra, although I've seen the same problem against Dovecot in the past

**Additional context** 

The mailsync log shows this following a failure;

***
*** Mailspring Sync 
*** A C++ exception occurred during program execution: 
*** database is locked
***

21660 [2020-10-30 02:58:24.870] [foreground] [critical] *** Stack trace (line numbers are approximate):
*** ??:?        exceptions::logCurrentExceptionWithStackTrace()
*** ??:?        runForegroundSyncWorker()
*** main.cpp:?  runBackgroundSyncWorker()::{lambda()#1}::operator()() const
*** main.cpp:?  _Bind_simple::operator()()
*** main.cpp:?  thread::_Impl::_M_run()
*** thread.o:?  execute_native_thread_routine()
***

I have tried mailspring many times, I have always had this problem and given up. This time I looked in the logs and can clearly see an issue .. so ..  this is reproducible, every time.

**Comment by CodeMouse92** [comment] 2021-01-28 03:52
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/zimbra-mailspring-sync/307/2

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 03:52 UTC
Labels: audit, bug
