### ISSUE TITLE
High energy consumption on MacbookPro

### ISSUE THREAD

**Issue by neamtua** [Foundry376/Mailspring#89] opened 2017-10-08 16:13 UTC
##### What operating system are you using?
OSX High Sierra

##### What version of Mailspring are you using?
1.0.2

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
no

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
no

##### Is the issue reproducible with a particular attachment, message, signature, etc?

<img width="792" alt="screen shot 2017-10-08 at 19 10 00" src="https://user-images.githubusercontent.com/1029457/31318495-73a63f96-ac5c-11e7-81a3-7805503723df.png">

Check the screenshot above. It's a huge difference between Mailspring, Chrome and PHPStorm. The last one is a huge java app. I was on battery this morning and it drained it in about 30 minutes.
Don't know what exactly is happening but it's been stuck for the past 2 days indexing [Mailspring].Snoozed on a few months old account with under 100 emails and indexing Drafts folder for same account that has no drafts in it.
I have no idea what is happening but this one makes it unusable for me at the moment.

**Comment by valmar** [comment] 2017-10-08 17:32
Uhm could it be the same problem I have?

https://github.com/Foundry376/Mailspring/issues/87

See what happens to me when the pop-up does not show

**Comment by bengotow** [comment] 2017-11-08 20:31
Hey! Thanks for reporting this—I think this was likely a dupe of #94 and should be fixed now. Enjoy Mailspring!

**Closed by bengotow** 2017-11-08 20:31 UTC
