### ISSUE TITLE
"More" Certificate Errors - OpenSuse

### ISSUE THREAD

**Issue by faasie** [Foundry376/Mailspring#144] opened 2017-10-13 01:54 UTC
Certificate Error when configuring accounts. Both errors still refer to `Problem with the SSL CA cert` path.
##### Are there any related issues?

Possibly #63 (closed)

##### What operating system are you using?
OpenSuse 42.3

##### What version of Mailspring are you using?
1.0.4-e604c991

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
None.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Certificate errors occur trying to connect to Office 365 (imap) and Gmail.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Office 365:
![image](https://user-images.githubusercontent.com/4673577/31526833-4cb9af10-af97-11e7-878b-0d1e4d8094b1.png)

Clicking on View Log:
![image](https://user-images.githubusercontent.com/4673577/31526860-71654356-af97-11e7-80c4-d88f0fc680d7.png)

Gmail:
![image](https://user-images.githubusercontent.com/4673577/31526885-9d164c5c-af97-11e7-9479-3852c2d85bee.png)

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
N/A

**Comment by bengotow** [comment] 2017-10-13 01:56
Hey! Thanks for reporting this. Do you know where the SSL certificates are located in OpenSUSE? Right now, Mailspring checks these paths for trusted certificates. Can you see if any of them seem to be valid for you? There might be an additional path we need to search for OpenSUSE (the lack of standardization of this on Linux is actually completely bonkers...)

```
        // Debian, Ubuntu, Arch: maintained by update-ca-certificates
        "/etc/ssl/certs/ca-certificates.crt",
        // Red Hat 5+, Fedora, Centos
        "/etc/pki/tls/certs/ca-bundle.crt",
        // Red Hat 4
        "/usr/share/ssl/certs/ca-bundle.crt",
        // FreeBSD (security/ca-root-nss package)
        "/usr/local/share/certs/ca-root-nss.crt",
        // FreeBSD (deprecated security/ca-root package, removed 2008)
        "/usr/local/share/certs/ca-root.crt",
        // FreeBSD (optional symlink)
        // OpenBSD
        "/etc/ssl/cert.pem",
```

**Comment by faasie** [comment] 2017-10-13 01:59
Looks like it's a symbolic link in `/etc/ssl/ca-bundle.pem` that points to `/var/lib/ca-certificates/ca-bundle.pem` as well as `/etc/ssl/certs` -> `/var/lib/ca-certificates/pem`

![image](https://user-images.githubusercontent.com/4673577/31527020-96a6fa82-af98-11e7-9af7-15993a44b70b.png)

**Comment by bengotow** [comment] 2017-10-13 02:03
Wow - another one! I was really hoping I'd collected them all...

Can you open `/etc/ssl/ca-bundle.pem` or `/var/lib/ca-certificates/ca-bundle.pem` and confirm that it's not just a single cert but a series of certificates concatenated together into a single file?

I'll add this to list of search paths and send you a build to test.

**Comment by faasie** [comment] 2017-10-13 02:07
Well, digging a little deeper, there is this header at the top of the ca-bundle.pem:
```
[ /etc/ssl ] ➜ cat ca-bundle.pem | more
#
# automatically created by /usr/lib/ca-certificates/update.d/99certbundle.run. Do not edit!
#
# Use of this file is deprecated and should only be used as last
# resort by applications that do not support p11-kit or reading /etc/ssl/certs.
# You should avoid hardcoding any paths in applications anyways though. Use
# functions that know the operating system defaults instead:
#
# - openssl: SSL_CTX_set_default_verify_paths()
# - gnutls: gnutls_certificate_set_x509_system_trust(cred)
#
```
And it then does have a series of concatenated certs.

**Comment by bengotow** [comment] 2017-10-13 02:13
Ahh interesting—I'm glad they're putting things in /etc/ssl/certs too. Mailspring calls `SSL_CTX_set_default_verify_paths`, but OpenSSL is compiled separately for each linux distribution with the correct paths based in as preprocessor flags, so when we do automated builds on the Ubuntu-based Travis machines and statically link in OpenSSL (which I've been doing because there are also different versions on different Linux distros...), the paths are hardcoded incorrectly when the binary is run on other Linuxes.

I think the takeaway is that statically linking against OpenSSL is a bad idea, even if it means it's easier to build a portable binary for a bunch of distros... (On a totally separate note, if you have any tips for building portable linux binaries I'd love to buy you a beer.)

I've gone ahead and added the paths though—when this Travis build finishes (https://travis-ci.org/Foundry376/Mailspring/jobs/287350270), you'll be able to download a build from these links. Let me know if this does the trick for you:

- https://s3.amazonaws.com/mailspring-builds/client/168881d4/linux/mailspring-1.0.4-0.1.x86_64.rpm
- https://s3.amazonaws.com/mailspring-builds/client/168881d4/linux/mailspring-1.0.4-amd64.deb

**Comment by faasie** [comment] 2017-10-13 02:27
Same errors, unfortunately.

```
[ ~ ] ➜ mailspring
Streaming log data to /tmp/Mailspring-3216.log
App load time: 288ms
Manual update check (updates.getmailspring.com/check/linux/x64/1.0.4-168881d4/anonymous/stable) returned 204
{ Error: 
Waiting for Account JSON:

Waiting for Identity JSON:
3696 [2017-10-12 22:25:40.399] [main] [critical] 
 ***
 *** Mailspring GenericException occurred during program execution: 
 *** {"debuginfo":"/auth/token/refresh","key":"Problem with the SSL CA cert (path? access rights?)","retryable":false,"what":"std::exception"}
 ***

3696 [2017-10-12 22:25:40.399] [main] [critical]  *** Stack trace (line numbers are approximate):
 *** ??:?  ValidateRequestResp(CURLcode, void*, string)
 *** ??:?  MakeRequest(string, string, string, string, string, nlohmann::basic_json const&)
 *** ??:?  MakeIdentityRequest(string, string, nlohmann::basic_json const&)
 *** ??:?  XOAuth2TokenManager::partsForAccount(shared_ptr)
 *** ??:?  MailUtils::configureSessionForAccount(mailcore::IMAPSession&, shared_ptr)
 *** ??:?  runTestAuth(shared_ptr)
 *** ??:?  main
 ***

/usr/share/mailspring/resources/app.asar.unpacked/mailsync: line 4:  3696 Aborted                 (core dumped) SASL_PATH="$(dirname $(realpath $0))" LD_LIBRARY_PATH="$(dirname $(realpath $0));$LD_LIBRARY_PATH" "$(dirname $0)/mailsync.bin" "$@"

    at ChildProcess._proc.on.code (/src/mailsync-process.es6:118:18)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:510:12)
  message: '\nWaiting for Account JSON:\n\nWaiting for Identity JSON:\n3696 [2017-10-12 22:25:40.399] [main] [critical] \n ***\n *** Mailspring GenericException occurred during program execution: \n *** {"debuginfo":"/auth/token/refresh","key":"Problem with the SSL CA cert (path? access rights?)","retryable":false,"what":"std::exception"}\n ***\n\n3696 [2017-10-12 22:25:40.399] [main] [critical]  *** Stack trace (line numbers are approximate):\n *** ??:?  ValidateRequestResp(CURLcode, void*, string)\n *** ??:?  MakeRequest(string, string, string, string, string, nlohmann::basic_json const&)\n *** ??:?  MakeIdentityRequest(string, string, nlohmann::basic_json const&)\n *** ??:?  XOAuth2TokenManager::partsForAccount(shared_ptr)\n *** ??:?  MailUtils::configureSessionForAccount(mailcore::IMAPSession&, shared_ptr)\n *** ??:?  runTestAuth(shared_ptr)\n *** ??:?  main\n ***\n\n/usr/share/mailspring/resources/app.asar.unpacked/mailsync: line 4:  3696 Aborted                 (core dumped) SASL_PATH="$(dirname $(realpath $0))" LD_LIBRARY_PATH="$(dirname $(realpath $0));$LD_LIBRARY_PATH" "$(dirname $0)/mailsync.bin" "$@"\n' } { pluginIds: [] }
```

**Comment by walmsles** [comment] 2017-10-16 22:02
On opensuse (tumbleweed) I had to create a symlink for "cert.pem" in /etc/ssl pointing to ca-bundle.pem for Mailspring to work and hook up my gmail account.  Used mailspring-1.0.4-0.1.x86_64.rpm to install.

**Comment by bengotow** [comment] 2017-10-16 22:31
Thanks @walmsles — can you see if this is addressed in 1.0.5? (getmailspring.com/download). I think the build above actually failed on Travis so testing with that may not have shown that it was fixed.

**Comment by walmsles** [comment] 2017-10-16 22:56
@bengotow 1.0.5 build is good without the symlink on opensuse (tumbleweed) - confirmed.

**Comment by faasie** [comment] 2017-10-16 23:01
@bengotow It appears good on my 42.3 system as well. Thanks!

**Comment by bengotow** [comment] 2017-10-17 17:41
Great! Glad this worked - thanks folks. Will leave this open for a bit in case anyone on the old version stumbles across it.

**Closed** 2017-11-02 18:18 UTC
Labels: bug, done-pending-release, linux
