### ISSUE TITLE
Can't add office365 account 

### ISSUE THREAD

**Issue by jshwvr** [Foundry376/Mailspring#1208] opened 2018-10-31 19:50 UTC
I am 100% sure that the login information is correct. I've double checked and even reset to be certain.

Here's the error I get:

Authentication Error - Check your username and password. (IMAP)View Log

And here's the log I get:

----------IMAP----------
* OK The Microsoft Exchange IMAP4 service is ready. [UwBOADQAUABSADAAMgAwADEAQwBBADAAMAA2ADEALgBuAGEAbQBwAHIAZAAwADIALgBwAHIAbwBkAC4AbwB1AHQAbABvAG8AawAuAGMAbwBtAA==]
1 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
1 OK CAPABILITY completed.
2 LOGIN "myemail@mydomain.com" "************"
2 NO LOGIN failed.

I've also tried manually entering the info through the imap config and no dice.

Thanks!

**Comment by bengotow** [comment] 2018-11-03 17:01
Hey! Thanks for reporting this - could you try creating an Office365 app password (https://support.office.com/en-us/article/create-an-app-password-for-office-365-3e7c860f-bda4-4441-a618-b53953ee1183) for Mailspring? I think that App Passwords used to be optional in Office365, but something seems to have changed recently.

Let me know if that allows you to sign in and I'll see if I can get a warning into the app itself!

**Comment by nimish** [comment] 2018-11-12 21:18
Can you add OAuth2 support? https://blogs.msdn.microsoft.com/exchangedev/2014/03/25/using-oauth2-to-access-calendar-contact-and-mail-api-in-office-365-exchange-online/

**Comment by djsipe** [comment] 2018-11-26 14:53
+1 for OAuth2.  My company will not allow app-specific passwords due to security concerns.  Dead in the water here.  🥺

**Comment by erenoglu** [comment] 2018-12-05 09:32
Yes many companies dont allow app passwords anymore. We are also enforced to OAuth2

**Comment by sahil-rivigo** [comment] 2019-02-04 05:18
@jshwvr Hi, were you able to log in with app password? 
I've been trying to set it up and haven't been able to do it.
I've tried both, app password and normal password, but still can't login, it gives me same error message as you.
@bengotow can you help me? 

----------IMAP----------
* OK The Microsoft Exchange IMAP4 service is ready. [UwBHADIAUABSADAAMQBDAEEAMAAxADUANQAuAGEAcABjAHAAcgBkADAAMQAuAHAAcgBvAGQALgBlAHgAYwBoAGEAbgBnAGUAbABhAGIAcwAuAGMAbwBtAA==]
1 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
1 OK CAPABILITY completed.
2 LOGIN "my.work.email@my.company.com" *********
2 NO LOGIN failed.


I wonder why it says "AUTH=XAUTH2" in capability line

**Comment by duoi** [comment] 2019-07-11 23:46
@sahil-rivigo did you ever figure it out? I'm in the same boat.

**Comment by ImTheDeveloper** [comment] 2019-11-12 18:10
Same issue here App passwords arent working:

```
1 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
1 OK CAPABILITY completed.
2 LOGIN "xxx.xxx@xxx.co.uk" "*********"
2 NO LOGIN failed.
```

**Comment by sirusss** [comment] 2019-11-14 01:12
Same issue here.

**Comment by ImTheDeveloper** [comment] 2019-11-14 08:54
Just got around this.

Created app password and chose to go the IMAP route instead of using the office365 route:
https://getmailspring.com/setup/access-office365-via-imap-smtp

**Comment by djsipe** [comment] 2019-11-14 17:01
For the record... app passwords are disabled at my place of work to mitigate account hijacking.

**Comment by sirusss** [comment] 2019-11-14 17:17
App passwords are also disabled by my employer.

**Comment by 3v1lb1t** [comment] 2020-01-16 13:51
I am receiving this same error. I have created an app password as well as tried my domain password. We have 2FA enabled.

**Comment by manooll** [comment] 2020-02-10 23:02
Did anyone solve this? Cause I've been trying to use app passwords with no luck. Neither option for office 365 works and this really sux

**Comment by sirusss** [comment] 2020-02-10 23:11
Ended up using davmail as a workaround to get office 365 to work on linux.

**Comment by duoi** [comment] 2020-02-12 22:12
> Did anyone solve this? Cause I've been trying to use app passwords with no luck. Neither option for office 365 works and this really sux

The only solution is to set it up as a normal MS account.

**Comment by cihyboj** [comment] 2020-03-31 13:00
@duoi - what does it mean to set it as "normal MS"?

**Comment by CodeMouse92** [comment] 2021-01-18 18:57
Thank you for your patience on this issue! I know it's frustrating when you cannot connect to your email with Mailspring.

2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be a duplicate of one we've already migrated to Discourse:

https://community.getmailspring.com/t/institutional-office365-not-working/48/2

Please consider joining that community and continuing the discussion there.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-18 18:57 UTC
Labels: audit, support
