### ISSUE TITLE
Refine copywriting style in Chinese locale files

### ISSUE THREAD

**Issue by cschenio** [Foundry376/Mailspring#1885] opened 2020-04-03 10:24 UTC
Per [this thread](https://github.com/sparanoid/chinese-copywriting-guidelines/blob/master/README.en-US.md) suggested, there is still some room for improving the current Chinese locale files.

TL;DR for those not clicking the link. 
1. Add one space before and after English words, numbers, except between an English word and a punctuation.
E.g. 
**Good**
我的名字叫 Linus。 
**Bad**
我的名字叫Linus。
2. Use 「」『』 instead of ‘ ”

**Comment by CodeMouse92** [comment] 2021-02-27 02:50
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/refine-copywriting-style-in-chinese-locale-files/850

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@cschenio: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-27 02:50 UTC
Labels: audit, enhancement
