### ISSUE TITLE
Feature request: url of an existing e-mail: get it and open it 

### ISSUE THREAD

**Issue by vlcinsky** [Foundry376/Mailspring#1473] opened 2019-04-23 10:01 UTC
##### What operating system are you using?
Linux Debian 9 Stretch

##### What version of Mailspring are you using?
 v 1.6.1-aceed8e5

##### Does this feature exist in another mail client or tool you use?
In Thunderbird, I use [ThunderLink](https://addons.thunderbird.net/en-US/thunderbird/addon/thunderlink/) allowing to create url to an existing e-mail and later on open such e-mail by opening given url.

##### Motivation: Way to Zero Inbox
Recently I reached [Zero Inbox](https://whatis.techtarget.com/definition/inbox-zero), easily emptying my inbox on all my accounts.

My Zero Inbox approach does not store mails in dedicated folder (as this does not allow me to state the action required on the e-mail), instead it files a task in my task management system.

 Instead of using inbox as (rather poor) bucket of reminders I create link to an e-mail to process and use that url in task, which I create in my task manager (I am using e-macs with org-mode, but the same shall apply to any other task managers).

Having the task in my (trusted) system, I can safely archive the e-mail from my inbox.

At the time I come to resolving the task, I open my task, from here I open the e-mail and proceed.

##### Use case: Create url to an e-mail
Open some inbox, alternatively open the mail. This defines context "this e-mail".

Then do something (like Ctrl-T, or using another shortcut) and it creates url pointing to given e-mail and puts that in clipboard.

Optional: ThunderLink also allows defining up to 8 different templates using url, datetime, subject, sender to create resulting text. This allows nice texts formatted almost as some types of tasks. Anyway, this is not rally necessary.

#### Use case: Open URL from external application
Having some sort of task manager, one shall be able to open the url in MailSpring.

The e-mail shall be open within MailSpring, new window is not required, it is acceptable to open it in existing MailSpring window, replacing previous view.

As one e-mail (having the same id) can live in multiple folders, the question is, where to open it. Putting folder into url is not the way to go, as it is very likely to change. Opening the e-mail anywhere is fine, in Gmail it could be in "All" folder.

**Comment by bengotow** [comment] 2019-05-26 22:29
Hey! This seems like a great email workflow, and there's actually a /bit/ of a way to do this in Mailspring currently!

If you build a URL that uses the `mailspring://` URL scheme and encodes the `subject` of a message and the date it was received as a unix timestamp, you can link to a particular thread. (Or rather, you can link to the first search result). For example:

```
mailspring://?subject=Aloha,%20new%20Hawaiian%20shirts&lastDate=1558893649
```

I think that right now it'd be difficult to incorporate this into a workflow because there's not a great way of getting the value you need for "lastDate". I'll see if we can add a right click option or a menu option to get the URL from the email!

**Comment by bengotow** [comment] 2019-05-26 23:09
Hey! FYI that I've added a new menu item that is bound to Ctrl+L (Ctrl+T was taken on Windows with the Outlook keybindings unfortunately). You can also right click threads in the thread list now to access it as well. Enjoy!

<img width="368" alt="image" src="https://user-images.githubusercontent.com/1037212/58388204-6d527380-7fe1-11e9-921e-455c4987c32b.png">

**Comment by vlcinsky** [comment] 2019-05-26 23:46
@bengotow this looks very promising.

How do I get it on my notebook? Do I have to wait for next release or do some manual update?

**Comment by vlcinsky** [comment] 2019-06-24 19:09
@bengotow nice, I have found it in my current Mailspring version. Very good.

My tests with opening that url seems to be working also very well:

## Open from Firefox
pasting the url into address bar: it recognizes it and offers Mailspring as protocol handler and opens it (after my confirmation).

## From console
From console (command line) I tried to enter `$ mailsrping {url}`. It complains a bit but opens the e-mail. 

```bash
$ mailspring "mailspring://thread?subject=Re%3A%20FW%3A%20Open%20linked%20data%20support%20(was%20RE%3A%20Json%20mapping%20alternatives)&date=1561364694"
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Exiting because another instance of the app is already running.
```
## Open from emacs org-mode:
I had to add new link handler:

```lisp
    (org-add-link-type "mailspring" 'org-mailspring-open)

    (defun org-mailspring-open (path)
      "Opens an email in mailspring with mailspring link."
      (start-process "ms_name" nil "mailspring" (concat "mailspring:" path)))

    )
    (provide 'org-mailspring)
```
then pressing enter on give link brings me to that e-mail.

I like it. Now I will play with it for few days.

**Comment by CodeMouse92** [comment] 2021-01-26 20:01
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse, specifically as a *question*:

https://community.getmailspring.com/t/url-of-an-existing-e-mail-get-it-and-open-it/271/3

Please consider joining that community and continuing the discussion there!

@vlcinsky @otesuji : if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for your posts.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the topic is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-26 20:01 UTC
Labels: audit
