### ISSUE TITLE
[Bug] Archived mail keeps returning and re-archiving in inbox (Office 365)

### ISSUE THREAD

**Issue by chris-ayala** [Foundry376/Mailspring#1394] opened 2019-02-28 18:28 UTC
I just archived a lot of mail on my Office 365 account at work using OSX's Mail.app. I return home to open the same account in Mailspring under Windows 10. After the sync finishes, there are still a few mails remaining in my inbox that should have been archived. And it seems after every sync, I can see in real-time my inbox being filled again with **a ton** of previously archived mail and then slowly disappearing (re-archiving) from my inbox.

##### Are there any related issues?
Possibly related to the now closed issue here: https://github.com/Foundry376/Mailspring/issues/364

##### What operating system are you using?
Windows 10

##### What version of Mailspring are you using?
Mailspring 1.5.7-2057ca30

**Bug?**
I think so.

##### Is this an email sync or connection issue?
Seems like an email sync issue.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Possibly Office 365. I only use Office 365.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Not sure.

**Comment by zufanka** [comment] 2019-04-25 08:13
I have the same issue. Tried to trash the emails instead of archiving them but I still keep on finding them once I come back to work in the morning.

**What operating system are you using?**
Fedora linux

**What version of Mailspring are you using?**
Mailspring 1.6.0-10f5c95c

**Bug?**
yes

**Is this an email sync or connection issue?**
Seems like an email sync issue.

**Is the issue related to a specific email provider (Gmail, Exchange, etc.)?**
Possibly Office 365. I only use Office 365.

**Comment by antonpiatek-imanage** [comment] 2019-08-19 12:58
Also seeing this on Ubuntu 19.04 (and previously with 18.04), using mailspring from stable Snapcraft repository: 

    $ snap list mailspring
    Name        Version  Rev  Tracking  Publisher    Notes
    mailspring  1.6.3    374  stable    foundry376✓  -

**Comment by CodeMouse92** [comment] 2021-02-02 02:44
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/disappearing-emails-desync/428

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-02 02:44 UTC
Labels: audit
