### ISSUE TITLE
With Undo Send enabled, emails seem to be getting stuck in the outbox

### ISSUE THREAD

**Issue by palefire19** [Foundry376/Mailspring#336] opened 2017-11-13 04:47 UTC
##### Are there any related issues?

...

##### What operating system are you using?
Mac OS 10.12.6

##### What version of Mailspring are you using?
1.0.8

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Possibly Gmail?

##### Is the issue reproducible with a particular attachment, message, signature, etc?

See screenshot. Since 1.0.8, a lot of emails seem to be hanging in my drafts folder after I've hit send. I think Undo Send being enabled might be part of the problem. Will turn off Undo Send for a while and see what happens.
<img width="363" alt="screen shot 2017-11-13 at 7 46 25 am" src="https://user-images.githubusercontent.com/4412269/32710120-d898c562-c846-11e7-9261-ba6b8e62820f.png">

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by palefire19** [comment] 2017-11-13 06:41
Confirmed that this seems to be related to Undo Send, so changing the title of the issue

**Comment by gottlike** [comment] 2017-12-01 09:18
I noticed that it seems to be even more error prone when setting the undo time to 15+ seconds.

**Comment by palefire19** [comment] 2017-12-08 12:22
@bengotow I'm increasingly convinced that this and #366 are the same. I noticed that this seems pinpointed to when I've put my Mac to sleep and then come back to Mailspring to send emails (with Mailspring having been open the whole time).

**Comment by palefire19** [comment] 2018-03-07 13:49
@bengotow Not sure which release fixed this ... but just a note that I think this bug has stopped happening, so could close this.

**Comment by CodeMouse92** [comment] 2021-01-17 03:54
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mail-getting-stuck-in-outbox/60

Please consider joining that community and continuing the discussion there! Bonus: if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-17 03:54 UTC
Labels: audit
