### ISSUE TITLE
Different scrollbars around the app

### ISSUE THREAD

**Issue by mtxr** [Foundry376/Mailspring#1455] opened 2019-04-05 13:10 UTC
##### Are there any related issues?

There are some about not working scrolls, but not with this purpose.

##### What operating system are you using?

Fedora 29 x64

##### What version of Mailspring are you using?

1.6.1

**Bug?**

##### Is the issue reproducible with a particular attachment, message, signature, etc?

There are some different scrollbars around the app. See:

![image](https://user-images.githubusercontent.com/707561/55629927-d1e41580-578a-11e9-8502-786973caba2d.png)

![image](https://user-images.githubusercontent.com/707561/55629975-ea543000-578a-11e9-882c-3c930f69e591.png)

I'm not sure if this is related to this new update (I just updated to 1.6.1).

**Comment by mtxr** [comment] 2019-04-05 13:11
I can work on this one. Is it ok?

**Comment by bengotow** [comment] 2019-05-26 21:40
Hey @mtxr — thanks for reporting this! It looks like this is happening because we use `<ScrollRegion />` in most places in the app, which implements the app's custom / themeable scrollbar, but there are a few places where it's just a div with `overflow: scroll`, and in those places you get the standard browser scrollbars. I think it'd be super helpful if you could help find those and upgrade them to use `<ScrollRegion />`!

**Comment by tecosaur** [comment] 2019-10-04 02:15
@bengotow this has been done hasn't it? (I think the issue can be closed)

**Comment by CodeMouse92** [comment] 2021-02-19 00:16
It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-19 00:16 UTC
Labels: audit, bug, good first issue
