### ISSUE TITLE
Conflict of Chinese input when reply

### ISSUE THREAD

**Issue by chagel** [Foundry376/Mailspring#734] opened 2018-02-28 06:54 UTC
When reply msg in Chinese, it trims characters after what I input at once. 
Only happens when input in reply window, either in embedded or popup window.

It's fine when write a new message.

##### What operating system are you using?
macOS v10.13.3

##### What version of Mailspring are you using?
Version 1.1.4 (1.1.4)

##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Recorded this problem and uploaded here. Please take a look:
https://foundry376.zendesk.com/attachments/token/lrOZZVl7ep0VYag7wB71bTENY/?name=1.mov

**Comment by btstream** [comment] 2018-03-02 03:45
I have this problem too. It only happened on MacOS, my Linux Desktop is all ok.

**Comment by chagel** [comment] 2018-03-02 03:50
Too follow up this issue, I dig more. Plain text reply seems ok, only encounter with HTML format content.

I'm trying to debug, any idea which file and where I should look into?

**Comment by CodeMouse92** [comment] 2021-02-16 01:08
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/when-i-input-japanese-the-sentence-disappears-during-the-input/535

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@chagel: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-16 01:08 UTC
Labels: audit, composer, needs-reproduction
