### ISSUE TITLE
Messages Not Being Marked As Read

### ISSUE THREAD

**Issue by gracintosh** [Foundry376/Mailspring#1475] opened 2019-04-24 12:42 UTC
This doesn't seem similar to existing issues, apologies if there is a duplicate.

With the Linux version 1.6.1-aceed8e5, the messages are not being marked as read after the amount of time determine in preferences (0.5 seconds) or after "mark as read" is selected after right-clicking. In fact-- when right clicking the option is "mark as <u>un</u>read. Marking as un-read then read doesn't work.

Blue circular badge persists, as does email highlight. The message is included in the unread count next to inbox.

Restarting program does not resolve issue, but restarting PC consistently does.

##### Are there any related issues?

...

##### What operating system are you using?

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.10
DISTRIB_CODENAME=cosmic
DISTRIB_DESCRIPTION="Pop!_OS 18.10"

##### What version of Mailspring are you using?

1.6.1-aceed8e5

**Bug?**

##### Is this an email sync or connection issue?

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Difficult to tell, I connect via IMAP to a MDaemon mail server.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

...

**Comment by CodeMouse92** [comment] 2021-01-28 18:41
Thank you for reporting this. 2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/unread-count-still-on-without-unread-messages/350

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 18:41 UTC
Labels: audit
