### ISSUE TITLE
Split Accounts view in left panel

### ISSUE THREAD

**Issue by intradesign** [Foundry376/Mailspring#628] opened 2018-02-02 23:05 UTC
**Feature Request?**
##### Does this feature exist in another mail client or tool you use?

Split Accounts view in left panel to have only ONE Account at once but all folders belonging to that account nearby. Use "unified inbox" to show accounts like now.

In AirMail you can decide to only see one account at once or all accounts in a unified and in subfolders. Thats the one reason why airmail beats all other mail clients in my opinion. Having multiple folders otherwise pushes the folders of a second account out of visible area and makes it more complicated to distinguish which account is active. 

<img width="328" alt="airmail 2018-02-03 00-00-23" src="https://user-images.githubusercontent.com/21263208/35758673-7a5a8fde-0875-11e8-9edb-d16df5caeb13.png">

<img width="325" alt="airmail 2018-02-03 00-02-31" src="https://user-images.githubusercontent.com/21263208/35758737-b703d468-0875-11e8-8563-e7359be43886.png">

**Comment by CodeMouse92** [comment] 2021-01-29 21:42
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/disable-selective-unified-inbox/136

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

**Closed by CodeMouse92** 2021-01-29 21:42 UTC
Labels: audit, enhancement
