### ISSUE TITLE
Feature Request: Print selected messages from e-mail thread 

### ISSUE THREAD

**Issue by oxmynx** [Foundry376/Mailspring#1030] opened 2018-08-16 07:55 UTC
E-mails are nicely grouped in a thread. However, the print function only allows printing the first message (while the other e-mails are hidden) or all message of the thread. It will be very useful to be able to unhide only one older message and print it or have a print button for each message individually. Thanks.

**Comment by drogica** [comment] 2019-02-12 15:52
I would like that too

**Comment by mjoppich** [comment] 2019-04-03 09:15
That is a required feature!

**Comment by CodeMouse92** [comment] 2021-02-25 01:26
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/print-selected-messages-from-e-mail-thread/781

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@oxmynx: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-25 01:26 UTC
Labels: audit, enhancement
