### ISSUE TITLE
Saved Searches / Search Folders / Smart Folders

### ISSUE THREAD

**Issue by aksdb** [Foundry376/Mailspring#514] opened 2018-01-09 17:21 UTC
I would be nice to have a way to either create virtual folders combining selected other folders, or to be able to mark arbitrary folders as inboxes.

Use case:
I have one IMAP server where I collect mail from several other mail accounts. Each mail gets sorted by the mail server into appropriate sub folders. Therefore I have multiple "inbox" folders in my IMAP account. I would like to have one (virtual) folder to rule them all so I can have a quick overview over new email, independent from their source.

##### Does this feature exist in another mail client or tool you use?
Yes. For example in Evolution you can create so called "search folders" with criteria matching multiple source folders. Then that folder will show all mails from the selected folders combined.

**Comment by bengotow** [comment] 2018-01-18 02:00
Hey! Search folders are actually on the roadmap and I think it'd be the best way to handle this in the UI. Step 1 is a minor refresh of the search bar to make the advanced logic more obvious (you can do `in:inbox OR in:folderA` but it's unclear), and then I'll tackle this.

**Comment by mattkatz** [comment] 2019-02-25 21:11
👍 also would like this.

**Comment by narthur** [comment] 2019-07-23 15:18
@bengotow [The roadmap](https://github.com/Foundry376/Mailspring/blob/master/ROADMAP.md) seems to indicate you've shipped saved searches, but I can't figure out how to save a search to my sidebar. How do you do that?

**Comment by panter-dsd** [comment] 2020-05-23 05:55
I also need this feature. I use subfolders for splitting my subscriptions (like a `News/Global`, `News/Russia`, `Work/Important`, `Work/Support`, etc). Also I use this way for configuration of notifications: for instance I don't want to get notifications about any `News` subfolders but I really need to get the notification for the `Work` subfolders.

**Comment by flindeberg** [comment] 2020-09-25 19:20
Mailmate has a killer implementation of virtual or smart folders:
https://manual.mailmate-app.com/organize

Which is really useful if you handle lots of mail and need to organize accordingly. Very useful together with IMAP labels (#1006)

**Comment by CodeMouse92** [comment] 2021-02-09 21:59
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/saved-searches-search-folders-smart-folders/528

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@aksdb @panter-dsd: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-09 21:59 UTC
Labels: audit, enhancement
