### ISSUE TITLE
reply to message doesn't work right with multiple email accounts

### ISSUE THREAD

**Issue by randinovak18** [Foundry376/Mailspring#1550] opened 2019-06-28 04:23 UTC
##### Are there any related issues? This may be what destabilizes the application when multiple email account caches are synced simultaneously. When this happens, I have to close the app and re-open. But let's just focus on the bug that I am reporting.

...

##### What operating system are you using? It happens on two Macs running OS X 10.11.6 and OS X 10.13.6

...

##### What version of Mailspring are you using? 1.6.2

...

--

**Bug?** Definitely a bug... with multiple email accounts, sending email from one to another, sender (FROM "You") and receiver (TO "You") are both "You" ... bug is that when one selects the action "reply," the reply email is sent to the TO "You" instead of the FROM "You"

##### Is this an email sync or connection issue? no

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)? no, I have tried gmail, comcast and suddenlink accounts

...

##### Is the issue reproducible with a particular attachment, message, signature, etc? 

You don't need any attachment, a blank email works. This bug is 100% reproducible as follows:

1. Add two email accounts.
2. Send email from account 1 to account 2. Account 2 receives email FROM You(account 1) and TO You(account 2), although pull down does differentiate between the two "You's."
3. Reply to email received from account 1 ("You") as the account 2 user (also "You").
4. The reply email TO address is You(account 2) instead of You(account 1). In other words, "You" end up sending email to yourself instead of replying to the "other" "You."

Work-around: Click on the FROM "You" in the original email to see the email address then manually copy it. Then select FORWARD (instead of REPLY) and paste the email address into the TO field. BTW, I had over a dozen email accounts so this bug became CRAZY, because I had over a dozen YOU's!

Bug Fix: Don't even use "You" in FROM field, but instead use the account name that had been configured with the email account. If one has only one email account, then this issue of course does not happen because there is always just one "You" by definition.

...

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use? No. I went back to using Apple's Mail application. I will cancel my pro monthly subscription in a few weeks unless this bug gets fixed.

...

**Comment by CodeMouse92** [comment] 2021-02-08 21:22
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/reply-to-headers/507

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@randinovak18: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-08 21:22 UTC
Labels: audit
