### ISSUE TITLE
Bug: qq.com mail, theChinese title doesn't work well 

### ISSUE THREAD

**Issue by yanqingwang** [Foundry376/Mailspring#2199] opened 2020-11-10 12:26 UTC
**Describe the bug**
I added qq.com as the one account, and the email title doesn't work well.  

I am using arch linux as the OS, and Chinese as the locale.

**Comment by CodeMouse92** [comment] 2021-02-23 22:01
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/chinese-email-subject-is-displayed-abnormally/744

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@yanqingwang: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-23 22:01 UTC
Labels: audit, bug
