### ISSUE TITLE
Implement a dark tray icon for light themes

### ISSUE THREAD

**Issue by nihil21** [Foundry376/Mailspring#884] opened 2018-05-21 14:03 UTC
##### What operating system are you using?
KDE Neon Developer Edition Unstable

##### What version of Mailspring are you using?
1.2.1-7e7447b6 snap

--

**Feature Request?**
Hi, as you can see in the screenshot below, currently mailspring displays a white tray icon even in light themes:

![screenshot_20180521_154901](https://user-images.githubusercontent.com/15859553/40311210-7ee44916-5d0f-11e8-843f-c45dff721e38.png)

So I was wondering if it would be possible to make mailspring recognize the theme in use and display the correct tray icon (in this case, a dark one), though I think that snap confinement wouldn't allow that. Maybe implementing a switch from which you can manually set the correct tray icon is more feasible, what do you think?
Thanks in advance.

**Comment by bengotow** [comment] 2018-05-22 18:31
Hey! Ahh this would be super cool - do you know how KDE normally exposes the theme tint color / light vs dark setting? I know we get a few environment variables through the Snap daemon, so we might be able to do this if it's one of them.

**Comment by Void97** [comment] 2018-05-27 20:58
Unfortunately I don't know how KDE does that

**Comment by soee** [comment] 2019-10-18 19:56
I second this request. Would be great to have dark icon for light themes.

**Comment by Pointedstick** [comment] 2019-10-18 20:07
And if your icon is an SVG, you can even embed a stylesheet into it that allows it to conform to the active color scheme: https://cgit.kde.org/breeze-icons.git/tree/icons/status/16/battery-050.svg

For more information, see https://community.kde.org/Guidelines_and_HOWTOs/Icon_Workflow_Tips#Embedding_stylesheets_in_SVGs

**Comment by taprobane99** [comment] 2020-11-16 22:39
This still hasn't been fixed, I get a white icon on light background using KDE Plasma with Breeze theme. Perhaps a custom fix could be made when it detects "Breeze" (but not "Breeze Dark")  as the theme, as many users will be using it as its the default in Manjaro etc.

**Comment by CodeMouse92** [comment] 2021-02-18 22:52
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/implement-a-dark-tray-icon-for-light-themes/700

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@nihil21 @soee @pontaoski @Pointedstick @taprobane99 : if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-18 22:52 UTC
Labels: audit
