### ISSUE TITLE
Message body search is limited to Mailspring's offline cache of last N years / messages, but not documented

### ISSUE THREAD

**Issue by Luminarcy** [Foundry376/Mailspring#1784] opened 2020-01-23 11:53 UTC
I'm searching for specific keyword "u2412m". Both Gmail and Spark clients showing 3 search results but Mailspring can't find any.

##### Are there any related issues?

No

##### What operating system are you using?

Windows 10

##### What version of Mailspring are you using?
(eg: 1.6.3 or 1.7.0 - this is shown in Mailspring's main menu.)

1.7.2-4522b259

**Bug?**

##### Is this an email sync or connection issue?

No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No

![image](https://user-images.githubusercontent.com/42573485/72982200-9a188e00-3def-11ea-9f71-df5dd1cf3cee.png)

![image](https://user-images.githubusercontent.com/42573485/72982269-c3391e80-3def-11ea-8ce3-223f1c1e20be.png)

![image](https://user-images.githubusercontent.com/42573485/72982353-e82d9180-3def-11ea-8142-c5dae84c87a1.png)

![image](https://user-images.githubusercontent.com/42573485/72982358-f085cc80-3def-11ea-8642-6060d117efae.png)

**Comment by bengotow** [comment] 2020-02-15 19:10
Hey! Thanks for reporting this—based on the dates of the messages in the Gmail screenshot, my guess is that Mailspring didn't sync the bodies of these messages for search (it uses a few heuristics to avoid taking up too much disk space in large mailboxes). You can check and see if this is the case by searching for the `subject line / to / from` etc. to pull up these results in Mailspring, clicking them to load the message bodies, and then seeing if results appear for `u2412m`. (I think they'll show up).

If that's the not the case let me know! Either way, we should improve this behavior. I think that for Gmail accounts we can delegate more of search to Gmail's API, and for all accounts we can expose the options to limit your offline cache of the mailbox so you can easily see how far back it's indexed.

**Comment by amits1995** [comment] 2020-10-29 07:28
I can confirm that this is happening to me, too.  
It can happen when I search for emails from the last 3 months, not necessarily a few years back.  
  
The search is the most valuable feature I find using really often. This is kind of a deal-breaker.  
I found myself struggling to find emails using Mailspring search only to realize after weeks that it was the client's fault.

**Comment by CodeMouse92** [comment] 2021-02-12 20:55
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/message-body-search-is-limited-to-mailsprings-offline-cache-of-last-n-years-messages-but-not-documented/590

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@Luminarcy @amits1995: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-12 20:55 UTC
Labels: audit
