### ISSUE TITLE
Moving to Archieve doesnt move messages on server

### ISSUE THREAD

**Issue by orcunbaslak** [Foundry376/Mailspring#350] opened 2017-11-17 13:31 UTC
Hello,

I'm using 1.0.8-5a837 version. When I click archieve; the app doesnt move messages to Archieve folder. This used to work like a week ago.

Here's the log file.

7496 [2017-11-17 16:27:12.355] [background] [info] syncFolderUIDRange - (Trash, UIDs: 1 - 0, Heavy: false)
7496 [2017-11-17 16:27:13.554] [background] [info] syncFolderUIDRange - (Spam, UIDs: 1 - 0, Heavy: false)
7496 [2017-11-17 16:27:14.353] [background] [info] syncFolderUIDRange - (Outbox, UIDs: 1 - 0, Heavy: false)
7496 [2017-11-17 16:27:15.305] [main] [info] [local-06556e6f-4ac5] Running ChangeFolderTask performLocal:
7496 [2017-11-17 16:27:15.311] [main] [info] [local-06556e6f-4ac5] -- Succeeded. Changing status to `remote`
7496 [2017-11-17 16:27:15.454] [background] [info] syncFolderUIDRange - ([Mailspring], UIDs: 1 - 0, Heavy: false)
7496 [2017-11-17 16:27:15.889] [foreground] [info] Idle exited with code 0
7496 [2017-11-17 16:27:15.894] [foreground] [info] [local-06556e6f-4ac5] Running ChangeFolderTask performRemote:
7496 [2017-11-17 16:27:16.506] [background] [info] syncFolderUIDRange - ([Mailspring]|Snoozed, UIDs: 1 - 0, Heavy: false)
7496 [2017-11-17 16:27:17.083] [background] [info] Sync loop deleting unlinked messages with phase 1.
7496 [2017-11-17 16:27:17.084] [background] [info] Sync loop complete.
7496 [2017-11-17 16:27:17.354] [foreground] [info] [local-06556e6f-4ac5] -- Succeeded. Changing status to `complete`
7496 [2017-11-17 16:27:17.765] [foreground] [info] syncFolderUIDRange - (INBOX, UIDs: 1 - 1514, Heavy: false)
7496 [2017-11-17 16:27:18.364] [foreground] [info] Idling on folder INBOX
7496 [2017-11-17 16:27:21.311] [main] [info] [local-b7e5780c-3e55] Running ChangeFolderTask performLocal:
7496 [2017-11-17 16:27:21.331] [main] [info] [local-b7e5780c-3e55] -- Succeeded. Changing status to `remote`
7496 [2017-11-17 16:27:21.782] [foreground] [info] Idle exited with code 0
7496 [2017-11-17 16:27:21.785] [foreground] [info] [local-b7e5780c-3e55] Running ChangeFolderTask performRemote:
7496 [2017-11-17 16:27:22.319] [foreground] [error] [local-b7e5780c-3e55] -- Failed ({"debuginfo":"move did not return a uidmap - maybe the UIDs are no longer in the folder?","key":"generic","retryable":false,"what":"Unknown exception"}). Changing status to `complete`
7496 [2017-11-17 16:27:22.626] [foreground] [info] syncFolderUIDRange - (INBOX, UIDs: 1 - 1514, Heavy: false)
7496 [2017-11-17 16:27:23.176] [foreground] [info] Idling on folder INBOX
7496 [2017-11-17 16:27:23.500] [main] [info] [local-34eac488-b58a] Running ChangeFolderTask performLocal:
7496 [2017-11-17 16:27:23.510] [main] [info] [local-34eac488-b58a] -- Succeeded. Changing status to `remote`
7496 [2017-11-17 16:27:23.923] [foreground] [info] Idle exited with code 0
7496 [2017-11-17 16:27:23.927] [foreground] [info] [local-34eac488-b58a] Running ChangeFolderTask performRemote:
7496 [2017-11-17 16:27:24.347] [foreground] [error] [local-34eac488-b58a] -- Failed ({"debuginfo":"move did not return a uidmap - maybe the UIDs are no longer in the folder?","key":"generic","retryable":false,"what":"Unknown exception"}). Changing status to `complete`
7496 [2017-11-17 16:27:24.674] [foreground] [info] syncFolderUIDRange - (INBOX, UIDs: 1 - 1514, Heavy: false)
7496 [2017-11-17 16:27:25.246] [foreground] [info] Idling on folder INBOX
7496 [2017-11-17 16:28:11.001] [main] [info] [local-0f16bb28-d91c] Running SyncbackDraftTask performLocal:
7496 [2017-11-17 16:28:11.007] [main] [info] [local-0f16bb28-d91c] -- Succeeded. Changing status to `remote`
7496 [2017-11-17 16:28:11.423] [foreground] [info] Idle exited with code 0
7496 [2017-11-17 16:28:11.427] [foreground] [info] [local-0f16bb28-d91c] Running SyncbackDraftTask performRemote:
7496 [2017-11-17 16:28:11.427] [foreground] [info] [local-0f16bb28-d91c] -- Succeeded. Changing status to `complete`
7496 [2017-11-17 16:28:11.712] [foreground] [info] syncFolderUIDRange - (INBOX, UIDs: 1 - 1514, Heavy: false)
7496 [2017-11-17 16:28:11.988] [foreground] [info] Idling on folder INBOX

**Comment by bengotow** [comment] 2017-11-28 22:42
Hey! Thanks for reporting this - it looks like Mailspring is failing to move the messages because the server is reporting that those messages no longer exist in the folder Mailspring thinks they're in. I'll see if I can reproduce this.

**Comment by bengotow** [comment] 2017-12-12 02:16
Hey! This should be fixed in 1.0.11 - I rolled this fix in to the changes for #364.

**Comment by bengotow** [comment] 2017-12-18 23:16
Hey folks - this has shipped in 1.0.11. The app will download the update automatically, but you can get it directly here: https://www.getmailspring.com/download. Gonna go ahead and close this—if you continue to have trouble after the update, let me know and I'll re-open it!

**Closed by bengotow** 2017-12-18 23:16 UTC
Labels: done-pending-release, needs-reproduction
