### ISSUE TITLE
Emails with attachments are rejected by the SMTP server

### ISSUE THREAD

**Issue by Purplene** [Foundry376/Mailspring#947] opened 2018-06-22 07:10 UTC
Is there a reason why you don't respond to support requests over email?

Absolutely unbelievable for a paid subscription product. I sent multiple emails all the way back from May 11 and am still yet to receive a response.

**Comment by Purplene** [comment] 2018-06-22 07:14
This is the issue:

I cannot send emails with attachments, or included pasted images without seeing the below error:

![image](https://user-images.githubusercontent.com/39333692/41762807-561c3978-763f-11e8-9ef7-0c6a3f23f42d.png)

All of the mailboxes work otherwise and my host has confirmed that all are working correctly on webmail. I had no issue with the same settings on Gmail either, and can continue to send via Gmail.

##### What operating system are you using?
Windows 10

##### What version of Mailspring are you using?
1.2.2-96fb3a99

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Happens if any attachment is sent.

**Comment by Purplene** [comment] 2018-06-22 07:15
I've tried changing ports etc.

**Comment by bengotow** [comment] 2018-07-08 06:37
Hey! Thanks for reporting this - sorry I missed your support email. Did you send it to support@foundry376.com?

Could you let me know what email provider you're seeing this with? It might be easiest for me to get a test account and add it to the set I test with.

**Comment by Purplene** [comment] 2018-07-08 08:00
[https://tr.cloudmagic.com/h/v6/emailtag/tag/2.0/1531036816/cbebcf0aac45198feb14b030ee4e11b8/1/87f8e2765c1cbd2a2bf85b2ab9d4eec5/4ac4972d23f1afdd3e3693e98fa9435b/9723c13ccc0a2f3ea85c997e70d164a5/newton.gif]Hi Ben,

Thanks for responding, but I've longed moved on to one of your competitors. And I'm now no longer having this issue.

Yes, I sent multiple requests to that email.

Thanks
Dean
On Sun, Jul 08, 2018 at 4:37pm, Ben Gotow <notifications@github.com<mailto:notifications@github.com>> wrote:

Hey! Thanks for reporting this - sorry I missed your support email. Did you send it to support@foundry376.com<mailto:support@foundry376.com>?

Could you let me know what email provider you're seeing this with? It might be easiest for me to get a test account and add it to the set I test with.

**Comment by andreaci** [comment] 2018-07-10 06:57
I'm having the same problem, using Axigen Mail server

this is the server log
https://pastebin.com/5xK9yuwP

I'm now trying to debug the client application; I'm searching where the mail is actually sent from the queue :)
will be back

**Comment by coldpumpkin** [comment] 2019-07-30 16:56
I'm having this issue. @bengotow any developments?

**Comment by jasonmacer** [comment] 2020-03-15 17:18
Did anything ever get resolved here?  I know that we run ISPConfig, and actually really like mailspring, but if we cannot send attachments, it's pretty worthless.

**Comment by CodeMouse92** [comment] 2021-02-17 22:54
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/sending-e-mail-with-attachments-generates-error-sorry-mailspring-was-unable-to-deliver-this-message-connection-error-unable-to-connect-to-the-server-port-you-provided/673

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-17 22:54 UTC
Labels: bug, mailserver-incompatibility, migrated
