### ISSUE TITLE
Wrong To address when replying to an email coming from one of your own accounts

### ISSUE THREAD

**Issue by pirivan** [Foundry376/Mailspring#935] opened 2018-06-14 22:41 UTC
##### Are there any related issues?

No

##### What operating system are you using?
Linux

##### What version of Mailspring are you using?
1.2.2-96fb3a99

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

1. Configure access to two IMAP accounts on Mailspring, say `me@a.com` and `me@b.com`
2. Send a message from `me@a.com` to `me@b.com`
3. Read the message on the `me@b.com` account
4. While reading the message, click the `Write a reply...` button at the bottom
5. When the reply window opens, notice the **To** address: It reads `me@b.com` instead of `me@a.com`, which is the sender you want to reply to.

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by watgrad** [comment] 2018-08-01 01:49
I also have this issue using version 1.3.0 in Windows 10.
Mailspring does not use the full "from" address to populate the "to" address in a reply. 
In my case the IMAP accounts do not have the same user name, just the same server.
a@outlook.com and b@outlook.com.

This is very confusing.

**Comment by CodeMouse92** [comment] 2021-02-08 21:32
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/reply-to-headers/507

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-08 21:32 UTC
Labels: audit
