### ISSUE TITLE
Feature Request: Allow Imap only mail

### ISSUE THREAD

**Issue by matheusfillipe** [Foundry376/Mailspring#2032] opened 2020-05-28 19:11 UTC
**Is your feature request related to a problem? Please describe.**
Add a new mail account with IMAP only fails. Some services have paid SMTP (in my case) maybe others have paid IMAP but have SMTP. Would be nice to add new accounts that have any one of those but the creation process fails telling me that SMTP is invalid or should be added.

**Describe the solution you'd like**
I would like to fill the imap fields only and have the inbox of messages working, the write buttons could then maybe get greyed out or it just throws and error dialog if If I ever try to send from one of those accounts.

**Comment by CodeMouse92** [comment] 2021-02-23 21:46
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue is related to one already migrated to Discourse:

https://community.getmailspring.com/t/make-smtp-or-imap-optional-read-only-or-send-only-accounts/134

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@matheusfillipe: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-23 21:46 UTC
Labels: audit, enhancement
