### ISSUE TITLE
[Sync Issue] Starred/urgent mail not properly synced (Office 365)

### ISSUE THREAD

**Issue by chris-ayala** [Foundry376/Mailspring#1401] opened 2019-03-01 03:31 UTC
At work I use OSX Mail.app for Office 365 and I've recently unstarred/un-urgent-ed many mails. I should have about 9 messages starred. I returned home, fired up Mailspring (Windows 10) and I still see a ton of starred messages in my inbox (under All Accounts [which are two of my work accounts] -> Starred). Funny enough, if I go to a specific account's Starred folder, it is missing many starred emails.

##### Are there any related issues?
Perhaps https://github.com/Foundry376/Mailspring/issues/684 and https://github.com/Foundry376/Mailspring/issues/1394

##### What operating system are you using?
Windows 10

##### What version of Mailspring are you using?
Mailspring 1.5.7-2057ca30

**Bug?**
I think so.

##### Is this an email sync or connection issue?
Seems to be an email sync issue.
[mailspring-logs-2019-03-01.zip](https://github.com/Foundry376/Mailspring/files/2917816/mailspring-logs-2019-03-01.zip)

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Maybe, this if Office 365.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
It happens in general with my Office 365 account.

**Comment by CodeMouse92** [comment] 2021-02-02 02:50
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/disappearing-emails-desync/428

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

P.S. Duplicate of #304

**Closed by CodeMouse92** 2021-02-02 02:50 UTC
Labels: audit
