### ISSUE TITLE
Bug: Print preview shows GUI elements

### ISSUE THREAD

**Issue by asparc** [Foundry376/Mailspring#2016] opened 2020-05-25 14:36 UTC
**Description**
When clicking the button `Print Thread`, a print preview window pops up. This window displays some GUI elements that shouldn't be there. 

1. The `find-in-thread` bar shows in the print preview, i.e., the bar that appears when pressing CTRL+F in a message.
2. The `send-reminder-header` shows in the print preview. This is the case for messages that resurfaced in the inbox after the reminder triggered. The header for reminders that are yet to be triggered is different and does not show in a print preview. 

**Expected behavior**
These are GUI elements and shouldn't appear in the print preview.

**Setup: (please complete the following information):**
 - OS: Ubuntu 20.04
 - Mailspring Version: 1.7.8

**Comment by CodeMouse92** [comment] 2021-03-02 00:32
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/print-preview-shows-gui-elements/900

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 00:32 UTC
Labels: audit, bug
