### ISSUE TITLE
**Feature Request** Sync Signatures with Mailspring Account

### ISSUE THREAD

**Issue by RicardoEPRodrigues** [Foundry376/Mailspring#755] opened 2018-03-12 11:31 UTC
I work on different computers and have different emails. I would like that when I log into Mailspring it would sync my Signatures to the new computer.

**Comment by jfbourdeau** [comment] 2018-03-12 15:14
I would like this too

**Comment by abaybektursun** [comment] 2018-08-09 21:26
+1

**Comment by magnusja** [comment] 2019-01-23 14:42
+1

**Comment by tscholiadis** [comment] 2019-03-12 22:54
+1

Same here. We have a Mailspring account so it would be nice if it would sync the signatures with it.

**Comment by Risen-Solutions** [comment] 2019-03-24 03:54
+1

**Comment by stevereinhardt** [comment] 2019-04-08 19:21
+1
is this in the works? there's already a mailspring account I'm signed in to, can't you just authenticate with mailspring account and sync signatures that way? syncing email accounts would be amazing too.

**Comment by PsyKooGlitch** [comment] 2019-05-22 15:02
+1

**Comment by pupontech** [comment] 2020-05-11 11:53
I would like this as well

**Comment by edg78987** [comment] 2020-08-15 17:39
+1

**Comment by AlessandroFasse** [comment] 2020-09-05 07:38
+100

**Comment by CodeMouse92** [comment] 2021-01-28 03:19
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/sync-templates-signatures-accounts-etc-accross-multiple-devices/265/7

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@RicardoEPRodrigues : if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 03:19 UTC
Labels: audit, enhancement
