### ISSUE TITLE
Office365 / Outlook browser (Oauth) authentication

### ISSUE THREAD

**Issue by thymbahutymba** [Foundry376/Mailspring#1615] opened 2019-08-17 19:40 UTC
Hi guys, I'm tring to connect my university mail (outlook365) to mailspring, the problem is that for authenticate is required the browser redirection to university site for fill the student credentials.
For now is not possible to authenticate throught IMAP/SMTP address, so I'm asking for a feature: is it possible to add the option "authenticate with browser" for outlook 365 like gmail account?

**Comment by bengotow** [comment] 2019-10-09 02:49
Hey thanks for filing this! I'm actually talking to the O365 team this month about switching over to their OAuth flow (they just need to make their IMAP servers accept the XOAUTH2 token that you get after the Oauth flow completes.) Stay tuned!

**Comment by thymbahutymba** [comment] 2019-11-22 13:50
Any news about this?

**Comment by RavenTheDev** [comment] 2020-04-27 06:01
Hey @bengotow  - Any update on this? I'm wanting to move back to Mailspring but the O365 being unable to authenticate is an absolute show stopper

**Comment by iboware** [comment] 2020-05-26 09:53
I cannot use my company email with MailSpring on Linux. It was my best Outlook client alternative. Now I am using an Evolution plugin. I would like to return using Mailspring. Thanks for this awesome mail client.

**Comment by CodeMouse92** [comment] 2021-01-18 18:56
Thank you for your patience on this issue! I know it's frustrating when you cannot connect to your email with Mailspring.

2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be a duplicate of one we've already migrated to Discourse:

https://community.getmailspring.com/t/institutional-office365-not-working/48/2

Please consider joining that community and continuing the discussion there.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-18 18:56 UTC
Labels: audit, enhancement, not-yet-possible
