### ISSUE TITLE
Many emails appear  white - empty

### ISSUE THREAD

**Issue by krasi-georgiev** [Foundry376/Mailspring#880] opened 2018-05-18 18:41 UTC
##### What operating system are you using?
Fedora

##### What version of Mailspring are you using?
1.2.1

See attached image. It happens quite often. I think it happens every time when I receive a new email in a thread for the current view.
If I switch to another thread ans switch back it all goes back to normal.
![screenshot_20180518_213727](https://user-images.githubusercontent.com/8903888/40252165-2b31c500-5ae4-11e8-8842-d167cf69d3d5.png)

**Comment by emadow** [comment] 2018-05-21 05:34
Same with me. Also tracked here: https://github.com/Foundry376/Mailspring/issues/858

**Comment by patelom** [comment] 2018-05-26 15:57
@emadow #858 is different for the one discussed here.

@bengotow **How to reproduce?**

Reply (or forward) to an email. Keep the threaded view open until the email is sent. Once the email is sent (the loader on the email goes away), the all previous email to the recently sent email goes blank. Go to another email thread, and come back to the thread, you will be now able to see the emails.

**Comment by krasi-georgiev** [comment] 2018-11-28 13:45
ping to the maintainers.

**Comment by hailwood** [comment] 2020-03-01 21:11
This is still an issue.
Specifically it affects emails in the thread that have been expanded,
non-expanded emails are not affected and display fine once expanded.

**Comment by krasi-georgiev** [comment] 2020-08-31 18:11
yep still an issue, bump

**Comment by krasi-georgiev** [comment] 2020-10-27 09:42
bump

**Comment by CodeMouse92** [comment] 2021-02-02 01:44
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/many-emails-appear-white-empty/426/2

Please consider joining that community and continuing the discussion there!

@krasi-georgiev: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-02 01:44 UTC
Labels: audit
