### ISSUE TITLE
Bug: When archiving via keyboard shortcut, the most recent email is archived too

### ISSUE THREAD

**Issue by ferrellmichael84** [Foundry376/Mailspring#1936] opened 2020-04-24 16:26 UTC
**Describe the bug**
When I use the "e" keyboard shortcut to archive an email, I have noticed that sometimes (not always) it archives the email I've intended, but then it also archives the most recent email in my inbox too.

**To Reproduce**
1. Have at least 5 emails in the inbox
2. Click into the oldest email
3. Hit the "e" keyboard shortcut
4. When it takes you back to the inbox, sometimes the most recent email archives too

**Expected behavior**
I would expect that this would only apply the archive shortcut to the email I have open

**Screenshots**
I don't have any screenshots because it is happening very quickly

**Setup: (please complete the following information):**
 - OS: MacOS
 - OS Version 10.15.4
 - Mailspring Version: 1.7.6

**Comment by asparc** [comment] 2020-05-25 14:18
Can confirm. There is more to this in my experience. Somehow, active emails can get coupled to another recently used emails, but I can't pinpoint when or how this happens.  It's as if a selection somehow hangs, every now and then...  There's no link to keyboard shortcuts in my experience. It can also happen when the mouse is used.

In any case, for me this happened for:
- archiving
- moving to trash
- snoozing
- labelling
- starring
Each time, this action was applied to the active email, but also to one other recently used emails from the inbox (like the upper email in the inbox, or the last opened email).

I'm using Mailspring 1.7.8 on a Ubuntu 20.04.

**Comment by kaleidoscopique** [comment] 2021-01-21 17:33
Hey guys!

Same here! OS/X.

I think it happens ONLY during the "sending" countdown. When I archive a message AFTER it has been sent, the bug never occurs.

**Comment by kaleidoscopique** [comment] 2021-01-21 17:36
Same issue here @CodeMouse92 if it can help you to clean issues : https://github.com/Foundry376/Mailspring/issues/2080

**Comment by CodeMouse92** [comment] 2021-01-21 23:53
Thanks @kaleidoscopique, that does indeed help.

**Comment by CodeMouse92** [comment] 2021-01-21 23:53
Merge #2080

**Comment by CodeMouse92** [comment] 2021-01-21 23:54
Thank you for reporting this. 2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/losing-mail-by-moving-other-mail-via-keyboard-shortcut/168/1

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-21 23:54 UTC
Labels: audit, bug
