### ISSUE TITLE
Exchange: ErrorNamespace (IMAP)

### ISSUE THREAD

**Issue by diegoferigo** [Foundry376/Mailspring#708] opened 2018-02-19 12:27 UTC
##### What operating system are you using?
Ubuntu 16:04

##### What version of Mailspring are you using?
1.1.4

---
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Exchange

##### Description

Authentication failed with the message:

```
ErrorNamespace (IMAP)
```

I don't find any way to configure manually the authentication infos. Probably the problem is due to the fact that the email and the server domains are different (`name.surname@domain.com` vs `mail.domain.com`).

**Comment by MrObvious** [comment] 2018-02-22 23:10
What kind of username are you using? I use Office 365 IMAP and just use username@company.com (not first.last@company.com), despite the imap server being outlook.office365.com.

**Comment by diegoferigo** [comment] 2018-02-28 07:50
No luck even in this case. With other email clients I always had to manually edit the domain to from `domain.com` to `mail.domain.com`, and I think this is the same case. I wonder why mailspring does not yet have a simple tab for manually editing and reviewing the default configuration, this would be a very useful feature.

**Comment by diegoferigo** [comment] 2018-03-18 15:22
Some more details:

```
----------IMAP----------
* OK The Microsoft Exchange IMAP4 service is ready. [UABSADIAUAAyADYANABDAEEAMAAwADIAOQAuAEYAUgBBAFAAMgA2ADQALgBQAFIATwBEAC4ATwBVAFQATABPAE8ASwAuAEMATwBNAA==]
1 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
1 OK CAPABILITY completed.
2 LOGIN "username@domain.com" "*********"
2 OK LOGIN completed.
3 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CLIENTACCESSRULES CLIENTNETWORKPRESENCELOCATION BACKENDAUTHENTICATE CHILDREN IDLE NAMESPACE LITERAL+
3 OK CAPABILITY completed.
4 NAMESPACE
4 BAD User is authenticated but not connected.
```

**Comment by diegoferigo** [comment] 2018-06-19 19:10
Error still persists in `1.2.2`

cc @bengotow

**Comment by diegoferigo** [comment] 2018-06-19 19:15
Related to https://github.com/Foundry376/Mailspring/issues/130#issuecomment-353308484

**Comment by DewaldDeJager** [comment] 2018-06-26 06:30
I am having the same issue in `1.2.2-96fb3a99`

**Comment by DewaldDeJager** [comment] 2018-06-26 06:55
This is my log output:
```
----------IMAP----------
* OK The Microsoft Exchange IMAP4 service is ready. [TQBSADIAUAAyADYANABDAXXXA==]
1 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
1 OK CAPABILITY completed.
2 LOGIN "xxx.xxx@xxx.com" "*********"
2 OK LOGIN completed.
3 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CLIENTACCESSRULES CLIENTNETWORKPRESENCELOCATION BACKENDAUTHENTICATE CHILDREN IDLE NAMESPACE LITERAL+
3 OK CAPABILITY completed.
4 NAMESPACE
4 BAD User is authenticated but not connected.
```

I believe I need to change to `AUTH=LOGIN` but I'm not sure how to set this.

**Comment by diegoferigo** [comment] 2018-06-26 07:35
@DewaldDeJager What I think is missing in Mailspring is an advanced configuration options when you setup a new email account. Most of the clients have it, more or less hidden. Unfortunately some setup needs a manual tweak of the default configuration and in this case I don't know where to operate.

@bengotow Even if it is not exposed through the GUI, is there any configuration file I can play around with in order to configure Exchange accounts?

**Comment by diegoferigo** [comment] 2018-07-19 20:18
This issue is still present in the 1.3 version released few days ago @bengotow

**Comment by DewaldDeJager** [comment] 2018-08-02 06:11
@diegoferigo Yeah, I thought the same thing but couldn't find anything in the config files. I ended up buying Hiri instead.

**Comment by wazlecracker** [comment] 2020-06-24 02:33
This issue is still present with an hotmail.com account.

**Comment by BinaryPaean** [comment] 2021-01-20 01:46
I just ran into this in 1.8.0 while attempting to connect to an O365 account. My browser loads the intended OAuth URL and I can complete that process, yielding the "You're All Set!" success splash page at https://id.getmailspring.com/oauth/finished

However the actual Mailspring App "Add Account" modal just sits there, then eventually shows the ErrorNamespace (IMAP) error.

**Comment by CodeMouse92** [comment] 2021-01-20 23:54
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/exchange-errornamespace/132

Please consider joining that community and continuing the discussion there!

@diegoferigo @DewaldDeJager @wazlecracker @BinaryPaean If you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-20 23:54 UTC
Labels: audit, mailserver-incompatibility, needs-reproduction
