### ISSUE TITLE
Can't use Mailspring due to problem with Gmail-sync

### ISSUE THREAD

**Issue by DmitryLoki** [Foundry376/Mailspring#368] opened 2017-11-27 10:36 UTC
##### Are there any related issues?

https://github.com/Foundry376/Mailspring/issues/357 I think

##### What operating system are you using?
Ubuntu 16.10

##### What version of Mailspring are you using?
1.0.8

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
Nope

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail

Two weeks ago I got infinitive "rebuild inbox index" and lost all chances to work with my emails. I tried to re-connect my Gmail by deleting all Mailspring config, but I've got Gmail sync error...

So.. I can't use Mailspring for two weeks... I hope this issue will be fixed soon.

Sincerely yours, pro-subscriber.

**Comment by bengotow** [comment] 2017-11-28 22:31
Hey! Thanks for reporting this—can you elaborate on the messages you saw in Mailspring? What error is displayed in the app? This may be fixed by some recent improvements going into 1.0.9 tomorrow but it's hard to say without more detail. We're shipping some error reporting improvements that will make these things a lot easier to track down in 1.0.9 though.

**Comment by DmitryLoki** [comment] 2017-11-29 11:50
So. That's what I got when I've tried to add Gmail account.
![screenshot from 2017-11-29 14-34-29](https://user-images.githubusercontent.com/1115774/33373551-81e278c4-d513-11e7-8a84-94a0d490d32b.png)

![screenshot from 2017-11-29 14-35-20](https://user-images.githubusercontent.com/1115774/33373553-84669d6e-d513-11e7-9a49-913b24e1755d.png)

![screenshot from 2017-11-29 14-46-36](https://user-images.githubusercontent.com/1115774/33373766-74a7caaa-d514-11e7-8711-d70725f2dfda.png)

But it works perfectly when I add it via IMAP. If you need more info please ask.

**Comment by bengotow** [comment] 2017-12-02 06:49
Hmm interesting—an error code 134 popped up in #353 as well. Glad to hear it works via IMAP/SMTP but that's pretty strange. Will see if I can reproduce this locally.

Also a fix in 1.0.9 should prevent the infinite "indexing your mailbox" issue from happening again. Previously the app retried pretty aggressively when it couldn't fetch certain messages for the search index, and it could cause it to crash over and over.

**Comment by ronisbr** [comment] 2017-12-06 02:38
@DmitryLoki

Hi!

One question, by adding as IMAP, do you mean to configure the gmail account as a normal IMAP account?

**Comment by lewisamarshall** [comment] 2017-12-09 22:35
Also experiencing this issue.

**Comment by bengotow** [comment] 2017-12-11 20:59
Hey @DmitryLoki — are you still running up against this issue? The infinite re-indexing of mail should be fixed in 1.0.9 and 1.0.10.

@lewisamarshall  could you elaborate on which part of the problem you're seeing? I think Error 134 is the code for an assertion failure, and it may be that you need to resolve the Password Management issue described here: https://foundry376.zendesk.com/hc/en-us/articles/115001875571--I-m-getting-a-Password-Management-Error

**Comment by lewisamarshall** [comment] 2017-12-12 07:03
I'm seeing the same behavior from the console as well (see screenshot). I took a look at the password-management page; I have libsecret and gnome-keyring installed. Based on this, I think it's the same issue.

![screenshot from 2017-12-11 23-00-52](https://user-images.githubusercontent.com/3657774/33871429-54808a98-dec7-11e7-839a-d8c841db1b55.png)

**Comment by oserban** [comment] 2017-12-14 09:51
I started having this issue with gmail accounts in 1.0.10. Wasn't a problem for previous versions.

**Comment by SamuelMiller** [comment] 2017-12-31 02:57
I am  having the same issue with Linuxmint XFCE 18.3 (Ubuntu 16.04 core) with my gmail account.

**Comment by ziggy42** [comment] 2018-01-23 08:14
Same here, Fedora 27, just installed 1.1.0

**Comment by DmitryLoki** [comment] 2018-02-08 12:23
1.1.3 still has this bug

**Comment by gcraenen** [comment] 2018-06-09 14:41
1.2.2 also.

**Comment by tankgit** [comment] 2018-07-30 06:37
1.3.0 ubutnu 18.04, same

**Comment by lansscar** [comment] 2018-10-23 02:43
macOS Mojave, same

**Comment by AgentEric** [comment] 2018-10-27 21:17
OS: Linux Manjaro
1.5.1 
exactly alike
Whayt's the root cause? Gmail?

**Comment by victoru** [comment] 2019-01-03 18:46
I also ran into this issue and saw the error was because my hostname contained parentheses which caused smtp.gmail.com to reject the request due to invalid characters.

**Comment by leychan** [comment] 2019-02-14 08:58
manjaro18.0.2,same

**Comment by TomaszWaszczyk** [comment] 2019-05-02 21:20
The same

**Comment by EddieEldridge** [comment] 2019-06-13 14:17
Still getting the same error in 1.6.1, Syncs for a while, able to retrieve emails etc. but then throws an error stating 'Encounterd an error while syncing" and continues to do this repeatably. I set up my account by logging in with the browser.

**Comment by yitang** [comment] 2019-07-02 06:58
started to have this issue a couple of days ago.

**Comment by EddieEldridge** [comment] 2019-07-02 18:22
This issue was resolved for me after a couple of days of signing of resyncing repeatedly for a couple of days. Not sure what actually fixed it but just wanted to let people know there is hope :)

**Comment by anandkumar89** [comment] 2019-09-24 08:29
Similar issue - mailspring doesn't sync with gmail seamlessly. Sync is highly unpredictable. examples - 
- I send an email using google account and it stays in drafts folder for hours.
- open an old email and it'll keep loading the content forever
Sync is unreliable and frustrating which is the one thing it's supposed to do perfectly. Please release any fixes soon.

**Comment by YuRiTan** [comment] 2019-10-15 13:20
Also get this error with gmail using ubuntu 18.04 and mailspring version 1.7.1-45d4260b

**Comment by kngmat004** [comment] 2019-10-23 09:52
same issue still present on version 1.7.2

**Comment by lastch** [comment] 2020-02-07 02:37
me too

**Comment by BlueManCZ** [comment] 2020-02-24 10:05
I cannot add my gmail account. After successful authentication in browser I get this error message.

> Connection Error - Unable to connect to the server / port you provided. (SMTP)

![Snímek z 2020-02-24 10-56-02](https://user-images.githubusercontent.com/17854950/75143047-9a5cbf80-56f4-11ea-920f-e74545b22998.png)

Is there something wrong with the default gmail configuration that is used to establish a connection?

Mailspring 1.7.2 on Gentoo Linux

**Comment by BlueManCZ** [comment] 2020-02-24 10:29
You have to be kidding me. Building on my previous post, I tried connect to my Gmail account via Gmail IMAP instead of Google OAuth and I got a more detailed log file, what is actually happening here. There was a line in SMTP section:

> 501-5.5.4 HELO/EHLO argument "Z170-D3H Gentoo" invalid, closing connection.

"Z170-D3H Gentoo" is name of my host. **So I removed whitespace from my hostname** and voila, now both (Gmail IMAP and Google OAuth) works perfectly. I'm going to open new issue for this so that developers can look at it.

**Comment by Snopoff** [comment] 2020-04-12 13:27
Yup, got same problem. Everything was okay back then, now it doesn't sync with gmail and throws 134 error as well

**Comment by CodeMouse92** [comment] 2021-01-28 23:58
Hi all,

2020 prevented much development work on Mailspring, but rest assured, development has resumed! We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

@Snopoff (or anyone else): Can you please confirm that this is still broken with 1.8.0, and if so, open a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 23:58 UTC
Labels: audit, bug, needs-reproduction

**Comment by CodeMouse92** [comment] 2021-01-29 23:36
Duplicate of #397

**Comment by CodeMouse92** [comment] 2021-02-02 01:24
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/gmail-mailsync-134/422

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team
