### ISSUE TITLE
Debian 10

### ISSUE THREAD

**Issue by jprrezende** [Foundry376/Mailspring#1573] opened 2019-07-12 23:27 UTC
Is it compatible with Debian 10?

I can not install Mailspring on Debian 10.
How can I do that?

**Comment by kitingChris** [comment] 2019-07-31 12:31
Unfortunatelly looks like it is currently not compatible... 

Wanted to give it a try but got:

```
# apt install ./mailspring-1.6.3-amd64.deb 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'mailspring' instead of './mailspring-1.6.3-amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mailspring : Depends: gir1.2-gnomekeyring-1.0 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by CodeMouse92** [comment] 2021-02-02 23:42
Can anyone confirm that this is still broken with 1.8.0, and if so, open a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-02 23:42 UTC
Labels: audit, linux
