### ISSUE TITLE
When I relply a long history message mail, the CPU will be 100%

### ISSUE THREAD

**Issue by jerry79** [Foundry376/Mailspring#1291] opened 2018-12-30 08:34 UTC
This is a constant problem. When I reply to an email with a long history, the CPU rushes up to 100% in an instant, and then I have to wait for nearly a minute before the interface to respond to the email appears. V1.54 version update improves the reading experience of long mail, but the problem of replying to email remains unsolved. Please consider whether the same method can be used to solve this problem. thanks a lot

**Comment by nfaivre** [comment] 2019-03-20 18:23
I've got the same problem on v 1.6.0 running on ubuntu 18.10. The client becomes unusable if the history contains more than 30 messages.

**Comment by lil5** [comment] 2019-03-27 11:31
Looks like an promise or async function will be required. Possibly here or following this component;

https://github.com/Foundry376/Mailspring/blob/master/app/internal_packages/message-list/lib/message-list.tsx

**Comment by CodeMouse92** [comment] 2021-02-03 18:19
Duplicate of #927

**Closed by CodeMouse92** 2021-02-03 18:19 UTC
Labels: audit
