### ISSUE TITLE
Menu bar won't hide

### ISSUE THREAD

**Issue by lnx64** [Foundry376/Mailspring#791] opened 2018-03-29 00:54 UTC
I tried searching for this issue specifically but couldn't find anything as of right now, only that some people wanted the feature, and it was supposedly added.  The menu bar will not hide no matter what I try to do, so it looks rather ugly with it being present right now.  It says it would depend on what window manager I use, but it doesn't specify what window manager is problematic, but since Firefox can hide the menu bar on KWin, I didn't think Mailspring would have issues.

##### What operating system are you using?
Kubuntu 17.10

##### What version of Mailspring are you using?
1.1.5

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

**Comment by iuvbio** [comment] 2018-03-30 13:12
I have the same issue on elementary OS 0.4.1 Loki

**Comment by RicardoEPRodrigues** [comment] 2018-04-02 22:32
Same on Ubuntu 17.10 and Pop_OS!

I do believe this is a Electron theme issue. On windows the design guideline follows a trend that Electro implements (I believe) and on Linux there is no such design guidelines. Maybe we can follow the GTK Header Bar concept.

[![Nautilus Header Bar](https://wiki.gnome.org/Apps/Files?action=AttachFile&do=get&target=menus.png)](https://wiki.gnome.org/Design/)
[Gnome Design](https://wiki.gnome.org/Design/)

**Comment by axfelix** [comment] 2018-04-08 00:09
This is a duplicate of my bug https://github.com/Foundry376/Mailspring/issues/558

It was added and indeed doesn't work yet.

**Comment by axfelix** [comment] 2018-04-08 00:10
I don't think it's a design guideline issue per se though -- it could just automatically hide and then display on pressing Alt the way that Slack and Atom do.

**Comment by mr-islam** [comment] 2018-04-24 15:38
I have the same issue — it should be easy to do though since almost every other Electron app has this option (Standard Notes, VS Code, Atom, etc.)

**Comment by axfelix** [comment] 2018-04-24 15:40
Yeah, I think @Foundry376 just hasn't taken the time to mess with it on Linux yet which is understandable -- not unreasonable for Linux users to have to fend for themselves to some extent, I just don't know anything about Electron packaging

**Comment by bengotow** [comment] 2018-07-08 08:19
Hey folks—merging this in to #558 which we'll be shipping a fix for in the next release.

**Closed by bengotow** 2018-07-08 08:19 UTC
Labels: linux, needs-reproduction
