### ISSUE TITLE
Archived emails are automatically unarchived. [Exchange]

### ISSUE THREAD

**Issue by ploum** [Foundry376/Mailspring#364] opened 2017-11-25 12:13 UTC
Very often, archived emails just popup back into my inbox. It seems I have to archive a mail multiple times before it is finally counted as "archived". 

My intuition is that it is related to the fact that I also use Outlook for Android with the same account. The "archived" status doesn't seem to be synchronised to the server.

##### What operating system are you using?

OSX mailspring. Also using Outlook for Android.

##### What version of Mailspring are you using?
Latest

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Private exchange server accessed through IMAP

**Comment by bengotow** [comment] 2017-11-28 22:37
Hey! Thanks for reporting this - it's definitely possible that Exchange's "archive" concept isn't the same as "move this thread to the archive folder" when it's done via IMAP. Have you tried moving messages to the archive folder in another mail client? Would be super interested to know if we're doing this wrong for Exchange / Outlook accounts.

**Comment by ploum** [comment] 2017-12-04 13:26
I think that it's definitely Mailspring the problem.  When I use another IMAP client to move a mail to the archive folder, it is immediately reflected as Archived in Outlook.

It is not the case with Mailspring.  (tested with 1.0.9)

**Comment by dspaan** [comment] 2017-12-09 21:03
I have the same problem and i'm using Koozali SME IMAP. Archived e-mails sometimes come back, sometimes they don't. I use Mailspring on two computers.

**Comment by chris-hld** [comment] 2017-12-10 12:32
I guess this is because the mail never actually got moved to the archive folder.
Same here: https://github.com/Foundry376/Mailspring/issues/330

**Comment by bengotow** [comment] 2017-12-11 20:37
Hey folks—thanks for the follow-up reports. I've tried to reproduce this on my end but I haven't had any luck yet. It seems it may be specific to the Exchange-via-IMAP setup and works for me with hosted Office 365. If anyone has the ability to create a new user account I could test with on your server, I'd really appreciate it! I should be able to fix this if I can get it happening for an account I can test with. (If you can create a new account temporarily or have one without anything important in it, shoot me an email at ben@foundry376.com). Thanks!

**Comment by dspaan** [comment] 2017-12-11 21:05
I've just sent you an account you can test with. Not sure if you can reproduce it, i think i also had it with Gmail but not 100% sure.

**Comment by bengotow** [comment] 2017-12-11 22:40
Hey @dspaan — thanks for the test account. I've been able to reproduce the issue with that account. It looks like there are actually two separate things going on - the server is reporting that it supports the QRESYNC IMAP extension, but it doesn't seem to. It also doesn't support the UIDPLUS IMAP extension, which means Mailspring is unable to move mail between folders.

I should be able to fix this but it may take a bit of work. Stay tuned—

**Comment by dspaan** [comment] 2017-12-11 22:52
Awesome, let me know when you're done with the account. If you need to talk to the developers of the server we're using you can find the forums here: https://forums.contribs.org/index.php

**Comment by bengotow** [comment] 2017-12-12 01:59
Hey folks—this should be fixed in the next release. It looks like we didn't support this combination of supported features correctly, and also required the `IMAP MOVE` extension to move messages. I actually hadn't seen a server in the wild that didn't support it, but I think that's the cause of a bunch of recent issues. (As a fallback, clients can COPY, UPDATE FLAGS and then DELETE messages to move them, which is a bit slower but achieves the same effect. Mailspring will now do this.)

I was also able to reproduce a strange bug where the client wouldn't "see" new mail when it was sitting idle because the `QRESYNC` extension was supported but not returning quite what the app expected. 

Will ship this in a few days!

**Comment by bengotow** [comment] 2017-12-18 23:16
Hey folks - this has shipped in 1.0.11. The app will download the update automatically, but you can get it directly here: https://www.getmailspring.com/download. Gonna go ahead and close this—if you continue to have trouble after the update, let me know and I'll re-open it!

**Closed by bengotow** 2017-12-18 23:16 UTC
Labels: bug, done-pending-release

**Comment by ulriksf** [comment] 2020-08-21 07:29
I've been using Mailspring for a few months, and I have the same (or similar) issue. When I archive an e-mail in Mailspring it disappears from my inbox in Mailspring, but is still there when viewed in other programs. When restarting Mailspring, the "archived" e-mail sometimes (but not always) reappears in the Mailspring inbox.

I'm using the snap-distributed version (1.7.8-13635bcf) on Ubuntu 18.04.

**Comment by galgalesh** [comment] 2020-09-23 08:00
I have the same issue; archiving email only moves it when viewed from Mailspring. When I look at it with any other email client, the emails stay in my inbox.

@bengotow Should this issue be reopened or do we need to create a new issue for this?

**Comment by srikanthlavudia** [comment] 2024-10-23 09:00
Want to archive your enterprise emails: [SOLIXCloud Email Archiving](https://www.solix.com/products/email-archiving/)
