### ISSUE TITLE
Indexing emails only from last three months

### ISSUE THREAD

**Issue by giedriusStan** [Foundry376/Mailspring#386] opened 2017-12-02 15:26 UTC
I think it's a big issue, because older emails do not appear in search results. I cleared cache today (Dec 2) and left mailspring to index everything from scratch. As you can see it stopped indexing emails after September 2

![image](https://user-images.githubusercontent.com/1705190/33517046-73ba8efc-d785-11e7-92b6-3e9504d1f3d8.png)

##### What operating system are you using?

Arch Linux

##### What version of Mailspring are you using?

1.0.9

##### Do you have any third-party plugins installed? If so, which ones?

No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No

**Comment by bengotow** [comment] 2017-12-12 03:13
Hey! Thanks for reporting this - this will be an option soon. Three months seemed like a good default since the cache can take up a very large amount of space if it's infinite, but the plan is to make this selectable from preferences. Stay tuned!

**Comment by Bergg** [comment] 2017-12-15 19:53
currently (1.0.11-ea4b20af zimbra imap F27 box) after a few minutes the cache stops at today after a few minutes.

**Comment by qlfwyyd** [comment] 2018-05-02 15:40
I'm currently only able to sync three weeks' worth of email. I've tried rebuilding the cache, but it always syncs the same amount. Not sure what's going on there, but it's almost unusable as is.

**Comment by dtokarczyk** [comment] 2019-03-06 11:44
@bengotow Hello! When feature gonna release? 

Can you confirm that if I add account where I have 40gb emails Mailspring will download messages which I got through 3 month ago?

**Comment by egidijusz** [comment] 2020-07-02 12:09
This is the only feature I'm missing from Mailspring. Hence not switching to it and paying for pro version. 
Will it be implemented at some point in future? Like maybe allow users to set how far back in time emails should be indexed or something like that.

**Comment by CodeMouse92** [comment] 2021-02-24 18:38
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/mail-storage-settings-download-number-of-days-all-mail-etc/170

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-24 18:38 UTC
Labels: audit, enhancement
