### ISSUE TITLE
Subfolders don't nest in the left sidebar unless a parent folder or label with the base path is present

### ISSUE THREAD

**Issue by jGleitz** [Foundry376/Mailspring#250] opened 2017-10-25 07:58 UTC
##### Are there any related issues?
Not that I’d know of.

##### What operating system are you using?
Ubuntu 17.10

##### What version of Mailspring are you using?
1.0.6

##### Do you have any third-party plugins installed? If so, which ones?
none

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I don’t know, I use IMAP

##### Is the issue reproducible with a particular attachment, message, signature, etc?
n/a

**Feature Request?**

Subfolders of designated folders like Trash or Archive are not shown as subfolders in the first part of the folder list, but as usual folders in the second part, all having the prefix “[Parent Folder]/”.

![archives subfolders](https://user-images.githubusercontent.com/4305652/31986920-686e4d92-b96a-11e7-87a1-e0620eabab4c.png)

I would expect that those “special” folders can also be expanded to show their subfolders.

##### Does this feature exist in another mail client or tool you use?
Yes, Thunderbird:

![subfolders thunderbird](https://user-images.githubusercontent.com/4305652/31987117-146bbf58-b96b-11e7-9eb6-04eae6dd1471.png)

**Comment by bengotow** [comment] 2017-10-28 00:27
Hey! This should work in Mailspring if you create a folder just called "Archives". The problem is that right now it looks for a parent folder, and your mail provider isn't returning one.

We should definitely see if we can make the algorithm in the sidebar a little more flexible.

**Comment by bengotow** [comment] 2017-10-28 00:29
For anyone interested in taking a look at this, there's a function in the sidebar code that takes a flat array of Folder / Label objects and produces a hierarchical representation. Right now it puts the items in alphabetical order and nests items in a single pass. We probably need to do something more sophisticated, where an (unclickable) parent item can be inferred by the presence of a path prefix on a folder / label.

https://github.com/Foundry376/Mailspring/blob/master/app/internal_packages/account-sidebar/lib/sidebar-section.coffee#L133

**Comment by jGleitz** [comment] 2017-10-28 09:10
@bengotow thanks for replying! Unfortunately, I think you misunderstood my issue. I *do have* a folder called “Archives”.

In the default configuration, Mailspring shows the subfolders of it as expected:

![without special role](https://user-images.githubusercontent.com/4305652/32133035-1c545556-bbd0-11e7-98cc-cd5274e164f5.png)

But if I make the “Archives” folder the folder with the special role “Archive”, like this:

![select special role](https://user-images.githubusercontent.com/4305652/32133040-2b43e00e-bbd0-11e7-9b45-2af2cf2bf109.png)

The subfolders of the “Archives” folder are not displayed as subfolders of the special folder, but as a flat list:

![with special role](https://user-images.githubusercontent.com/4305652/32133047-439c862e-bbd0-11e7-934a-9bb2f47a0140.png)


I don’t know if what you are saying is also a valid work item (are there mail providers, that allow subfolders without having the parent folder as mail folder?), but for me, this issue is about something else.

**Comment by jGleitz** [comment] 2017-10-28 10:25
Excerpt from the IMAP `LIST` command to verify there is an “Archives” folder:

```
a LIST "" *
[…]
* LIST (\HasChildren) "/" Archives
* LIST (\HasNoChildren) "/" "Archives/JUnit KIT"
* LIST (\HasNoChildren) "/" Archives/Kursverwaltung
* LIST (\HasNoChildren) "/" Archives/come2.help
* LIST (\HasNoChildren) "/" Archives/2016
* LIST (\HasNoChildren) "/" Archives/2017
[…]
a OK List completed (0.000 + 0.000 secs).
```

**Comment by agurz** [comment] 2017-11-12 19:40
Hey folks!, one question, just to clarify: 

This:

<img width="325" alt="screen shot 2017-11-12 at 4 31 42 pm" src="https://user-images.githubusercontent.com/13837769/32702564-ce226086-c7c7-11e7-9c0d-2812d4f29293.png">

Should be shown as:

<img width="287" alt="screen shot 2017-11-12 at 4 37 04 pm" src="https://user-images.githubusercontent.com/13837769/32702568-d882f432-c7c7-11e7-8d5d-9c44e3f60526.png">

?

Are we nesting infinite levels of folders? As far as I can see the sidebar tree shows up to 2 levels of folders. E.g. If I have a folder `Archive/Test1/SubTest1`, the tree will become `Archive -> Test1/SubTest1` (Instead of `Archive -> Test1 -> SubTest1`).

**Comment by agurz** [comment] 2017-12-12 02:35
Hey @bengotow, just pinging

**Comment by a-sevin** [comment] 2019-04-22 06:19
I'm also interested by this feature

**Comment by CodeMouse92** [comment] 2021-02-24 18:50
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/subfolders-dont-nest-in-the-left-sidebar-unless-a-parent-folder-or-label-with-the-base-path-is-present/764

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@jGleitz @agurodriguez: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-24 18:50 UTC
Labels: audit, enhancement, good first issue
