### ISSUE TITLE
Feature Request: “Silent” email addresses

### ISSUE THREAD

**Issue by specter78** [Foundry376/Mailspring#1964] opened 2020-05-04 14:16 UTC
I have subscribed to a few Wordpress feeds which get updated several times a day. Several notifications for something that is not important for immediate consideration is annoying. 

So it would be nice to “silence” some email addresses so I wouldn’t get notification for these.

**Comment by CodeMouse92** [comment] 2021-02-12 20:43
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/per-account-mailbox-notification-settings/133

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-12 20:43 UTC
Labels: audit
