### ISSUE TITLE
Feature Request: Ability to choose install path

### ISSUE THREAD

**Issue by Arteneko** [Foundry376/Mailspring#865] opened 2018-05-12 15:44 UTC
##### Are there any related issues?

Couldn't find any

##### What operating system are you using?

Windows 7, Arch Linux and MacOS 10.12

##### What version of Mailspring are you using?

1.2.1

----

**Feature Request**

I'd like to choose the installation path.

I have multiple disks, some being low-available-space SSDs.

Not being able to choose the installation path is a real pain

##### Does this feature exist in another mail client or tool you use?

Every other software ?

**Comment by bengotow** [comment] 2018-05-22 20:42
Hey! Thanks for reporting this - the easiest solution right now is to symlink your Mailspring preferences / data folder (where most of the file size is once you sync your mail) to another location. I'll see if we can make this a preference soon, though we'll probably start by adding new sync features that allow you to limit how much is stored on disk for a lighter setup.

**Comment by Wang1337** [comment] 2020-04-30 02:49
Not sure if this is the place to up-vote but I'd like this feature as well.

**Comment by CodeMouse92** [comment] 2021-02-25 00:51
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/ability-to-choose-install-path/776

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@Arteneko: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-25 00:51 UTC
Labels: audit, enhancement
