### ISSUE TITLE
Zimbra IMAP synch problem 

### ISSUE THREAD

**Issue by silvojakob** [Foundry376/Mailspring#238] opened 2017-10-23 17:06 UTC
##### Are there any related issues?

No!

##### What operating system are you using?
window 10 
##### What version of Mailspring are you using?
1.0.6-9448c884

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No!

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
 Zimbra IMAP

##### Is the issue reproducible with a particular attachment, message, signature, etc?

from log:
14584 [2017-10-23 18:49:19.378] [background] [info] Marking all folders as `busy`
14584 [2017-10-23 18:49:19.382] [background] [info] Syncing folder list...
14584 [2017-10-23 18:49:19.384] [metadata] [info] Metadata delta stream starting...
14584 [2017-10-23 18:49:20.035] [background] [info] Syncing folder list...
14584 [2017-10-23 18:49:20.048] [background] [info] syncFolderChangesViaCondstore - INBOX: highestmodseq changed, requesting changes...
14584 [2017-10-23 18:49:20.065] [background] [info] 🔸 Updating message 686=686 with subject: You’ll Love These Stunning Templates
14584 [2017-10-23 18:49:20.069] [background] [info] 🔸 Updating message 689=689 with subject: Logo
14584 [2017-10-23 18:49:20.070] [background] [info] 🔸 Updating message 690=690 with subject: ABBYY FlexiCapture Cloud | Welcome!
14584 [2017-10-23 18:49:20.072] [background] [info] 🔸 Updating message 691=691 with subject: [Request received] Zimbra IMAP synch error
14584 [2017-10-23 18:49:20.290] [foreground] [info] Idling on folder INBOX
14584 [2017-10-23 18:49:21.494] [background] [critical]  *** Stack trace:
 ***   raise
 ***   abort
 ***   terminate
 ***   wcsstr
 ***   wcsstr
 ***   NtContinueCHPE
 ***   NtContinueCHPE
 ***   KiUserExceptionDispatcher
 ***   _CxxThrowException
 ***
**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
No

**Comment by bengotow** [comment] 2017-10-23 18:05
Hey! Thanks for reporting this. Really strange that when this happens on Windows it's not able to capture the stack trace. I'll see if I can get some additional logging in here in the next version that will make it easier to track this down.

**Comment by ohynek96** [comment] 2017-10-24 06:45
I have this exact problem too. Also using custom IMAP.
My log:
14364 [2017-10-24 08:40:05.130] [main] [info] ------------- Starting Sync (xxx@yyy.zz) ---------------
14364 [2017-10-24 08:40:05.140] [background] [info] Marking all folders as `busy`
14364 [2017-10-24 08:40:05.146] [metadata] [info] Metadata delta stream starting...
14364 [2017-10-24 08:40:05.150] [background] [info] Syncing folder list...
14364 [2017-10-24 08:40:05.556] [background] [info] Syncing folder list...
14364 [2017-10-24 08:40:05.591] [background] [info] syncFolderChangesViaCondstore - INBOX: highestmodseq changed, requesting changes...
14364 [2017-10-24 08:40:05.636] [background] [info] 🔸 Updating message 24576=24576 with subject: xxx
14364 [2017-10-24 08:40:05.722] [foreground] [info] Idling on folder INBOX
14364 [2017-10-24 08:40:06.893] [background] [critical]  *** Stack trace:
 ***   raise
 ***   abort
 ***   terminate
 ***   wcsstr
 ***   wcsstr
 ***   RtlInterlockedCompareExchange64
 ***   RtlInterlockedCompareExchange64
 ***   KiUserExceptionDispatcher
 ***   _CxxThrowException
 ***

**Comment by ohynek96** [comment] 2017-10-30 07:30
For me this was fixed with the version 1.0.7.

**Comment by silvojakob** [comment] 2017-11-03 13:36
With 1.0.7 new problem raise it. Sinh begin "normaly" but after while.....most of emails are "removed" after while... 

[mailsync-2e7c2e1a.log](https://github.com/Foundry376/Mailspring/files/1441188/mailsync-2e7c2e1a.log)
[mailsync-3a617cd0.log](https://github.com/Foundry376/Mailspring/files/1441189/mailsync-3a617cd0.log)

**Comment by Viniter** [comment] 2018-02-28 14:01
Same problem, version 1.1.4. Zimbra IMAP, Ubuntu 17.10. I can't get to mailsync logs - option "Open Mailsync Logs" in Developer menu doesn't do anything.

**Comment by CodeMouse92** [comment] 2021-01-28 03:51
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/zimbra-mailspring-sync/307/2

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 03:51 UTC
Labels: audit, bug
