### ISSUE TITLE
Mailspring omits long / randomized email addresses from autocompletion

### ISSUE THREAD

**Issue by mimavox** [Foundry376/Mailspring#1919] opened 2020-04-19 09:22 UTC
When using task managers like Trello and MeisterTask, you get private email adresses that are used for importing new task items via email. I often use this feature by forwarding important emails that i want to import as tasks in these systems. However, Mailspring refuses to find these private adresses automatically when typing in the To-field, even though they been used before and are added to my Gmail contacts (Gmail finds them just fine when using their webmail). I suspect that Mailspring somehow flags them as spam addresses because they are long and randomized in nature. (I cannot find them in Mailsprings contact manger either.)

I would like to be able to manually whitelist these addresses since they are a very important part of my workflow. I want them to appear automatically when typing in the To-field.

**Comment by bengotow** [comment] 2020-04-22 15:21
Hey thanks for reporting this! We do currently omit "machine-generated" email addresses from autocompletion but I think we could change that! Will look in to this soon 👍

**Comment by CodeMouse92** [comment] 2021-02-27 03:23
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mailspring-omits-long-randomized-email-addresses-from-autocompletion/856

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@mimavox: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-27 03:23 UTC
Labels: audit, bug
