### ISSUE TITLE
[Feature Request] Conditionally download messages, display the message size (KB, MB ..) in some place

### ISSUE THREAD

**Issue by rafrsr** [Foundry376/Mailspring#211] opened 2017-10-19 22:57 UTC
##### Are there any related issues?
No

##### What operating system are you using?
Linux

##### What version of Mailspring are you using?
1.05

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
yes, most, if not all

The size is a helpful information to some people (like me)with a modest Internet speed, and should be displayed in some part, for example the header before sync the entire mail.

Suggestions:

> Display the message size in expanded messages headers:
![image](https://user-images.githubusercontent.com/7094012/31797730-dd8fd01c-b4fd-11e7-9342-93d4f5389636.png)

> Display the message size when the mouse hover the message, to keep the interface clean:
![image](https://user-images.githubusercontent.com/7094012/31797571-dfdfd02a-b4fc-11e7-834e-38c235988aa6.png)
This option can be configurable for people that need to be taken into account the message size.

I currently have no way of knowing if someone is sending me too big an email to take a action before download.

**Comment by bengotow** [comment] 2017-10-20 06:39
Hey! For the most part Mailspring automatically downloads message bodies and attachments (the only exception is mail more than three months old.). In order for this to be useful, we'd first need to give you finer-grain control over whether it downloads the message.

**Comment by CodeMouse92** [comment] 2021-02-20 03:21
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/conditionally-download-messages-display-the-message-size-kb-mb-in-some-place/713

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@rafrsr: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-20 03:21 UTC
Labels: audit, enhancement
