### ISSUE TITLE
Sync with Office 365 - One or more accounts are having connection issues

### ISSUE THREAD

**Issue by intheravine** [Foundry376/Mailspring#1815] opened 2020-02-25 18:08 UTC
##### What is the behavior you're seeing?

Intermittent messages:
"One or more accounts are having connection issues. Retrying..."

##### What email provider (Gmail, Exchange, etc.) are you trying to use?

Office 365

##### What operating system are you using?

Mac OS Catalina 10.15.3

##### What version of Mailspring are you using?

1.7.4

(eg: 1.6.3 or 1.7.0 - this is shown in Mailspring's main menu.)

##### Is the issue reproducible with a particular attachment, message, signature, etc?

The message comes and goes. It does not prevent me from receiving and sending mail or searching for messages.

Here's snippet from the log:

```
12962 [2020-02-25 10:01:04.573] [metadataExpiration] [info] Scanning for expired metadata
12962 [2020-02-25 10:01:04.573] [metadataExpiration] [info] -- Will wake for next expiration in 7200sec
12962 [2020-02-25 10:01:04.747] [foreground] [info] Idling on folder INBOX
12962 [2020-02-25 10:01:33.912] [background] [info] Sleeping after exception: {"debuginfo":"syncFoldersAndLabels - fetchAllFolders","key":"ErrorConnection","retryable":true,"what":"std::exception"}
12962 [2020-02-25 10:03:33.917] [background] [info] Syncing folder list...
12962 [2020-02-25 10:03:35.176] [background] [info] syncFolderUIDRange for INBOX, UIDs: 644955 - 649955, Heavy: true
12962 [2020-02-25 10:03:36.634] [background] [info] - remote=1, local=0
12962 [2020-02-25 10:03:36.650] [background] [info] syncFolderUIDRange for INBOX, UIDs: 1005764 - 1005766, Heavy: true
12962 [2020-02-25 10:03:36.868] [background] [info] - remote=1, local=1
12962 [2020-02-25 10:03:36.869] [background] [info] syncFolderUIDRange for INBOX, UIDs: 1004531 - 1005766, Heavy: false
12962 [2020-02-25 10:03:37.032] [background] [info] - remote=402, local=401
12962 [2020-02-25 10:03:37.033] [background] [info] - Fetching full headers for 1 (of 1 needed)
12962 [2020-02-25 10:03:37.259] [background] [info] - Updating message 6LVBTzmEUGMpDJe8cWpFE92iMwS3dH28AXsTNRHwF
12962 [2020-02-25 10:03:37.259] [background] [info] -- UID (287021 to 1004852)
12962 [2020-02-25 10:03:37.259] [background] [info] -- FolderID (M8u12E5EYnZk4WsowQb76N7T822VwheRuprizNNxt to PjuDyt4opZ5sZm1ctFfjdXTKw8nuC6CZHYRU2zNW4)
12962 [2020-02-25 10:03:37.380] [background] [info] syncFolderUIDRange for Sent Items, UIDs: 284559 - 287301, Heavy: false
12962 [2020-02-25 10:03:37.777] [background] [info] - remote=421, local=400
12962 [2020-02-25 10:03:37.778] [background] [info] - Fetching full headers for 21 (of 21 needed)
12962 [2020-02-25 10:03:38.015] [background] [info] - Updating message kFtLGxcqcgX1yZqHD4TMr7KytcN4wg8EUsnhHwceD
12962 [2020-02-25 10:03:38.015] [background] [info] -- UID (287290 to 287286)
12962 [2020-02-25 10:03:38.028] [background] [info] - Updating message MRP5ZEoeMqiLFztMyQgpdNYGU5oECmqjaah2jPZey
12962 [2020-02-25 10:03:38.028] [background] [info] -- UID (287264 to 287268)
12962 [2020-02-25 10:03:38.035] [background] [info] - Updating message PjBAufJDoz4LWLDnzfsjTzifBqNHbNLUKR44TWVVV
12962 [2020-02-25 10:03:38.035] [background] [info] -- UID (287226 to 287230)
12962 [2020-02-25 10:03:38.042] [background] [info] - Updating message f3g4D6w3xhEzNASjJe9e3ZZkeYo3AHD6XUD5EyGFq
12962 [2020-02-25 10:03:38.042] [background] [info] -- UID (1005633 to 287222)
12962 [2020-02-25 10:03:38.042] [background] [info] -- FolderID (PjuDyt4opZ5sZm1ctFfjdXTKw8nuC6CZHYRU2zNW4 to M8u12E5EYnZk4WsowQb76N7T822VwheRuprizNNxt)
12962 [2020-02-25 10:03:38.048] [background] [info] - Updating message FB1gJ1t7M8XGgxMsDyqAEiQbQqC8Ph3wRLx6sAjJg
12962 [2020-02-25 10:03:38.048] [background] [info] -- UID (287216 to 287220)
12962 [2020-02-25 10:03:38.055] [background] [info] - Updating message UFMvHXjZTAkeF3QVZ6nqv1HTe2BsPwkeQuB9944Eb
12962 [2020-02-25 10:03:38.055] [background] [info] -- UID (287209 to 287213)
12962 [2020-02-25 10:03:38.061] [background] [info] - Updating message iobtJnzTKUw4eXtDS8uny9NdTfwQE3Nw6vDjBfSQ2
12962 [2020-02-25 10:03:38.061] [background] [info] -- UID (287193 to 287197)
12962 [2020-02-25 10:03:38.067] [background] [info] - Updating message ihFFpEmVshT27pmUpQV6rECc3VH5KhihsQa8iS9XT
12962 [2020-02-25 10:03:38.067] [background] [info] -- UID (287188 to 287192)
12962 [2020-02-25 10:03:38.074] [background] [info] - Updating message pkoCtStAFYRDMN56s5czG3pRFggfJ6283ws1n6Xzk
12962 [2020-02-25 10:03:38.074] [background] [info] -- UID (287178 to 287182)
12962 [2020-02-25 10:03:38.080] [background] [info] - Updating message cwXv4C36DeYxbqUYet2YxwwuYGpdE9zEFezfgWUrs
12962 [2020-02-25 10:03:38.080] [background] [info] -- UID (287149 to 287151)
12962 [2020-02-25 10:03:38.087] [background] [info] - Updating message gaG9yRRtKfgT3RJkNQUZeWuikMH6fi3eiwpdqqnKd
12962 [2020-02-25 10:03:38.087] [background] [info] -- UID (287143 to 287145)
12962 [2020-02-25 10:03:38.094] [background] [info] - Updating message GBP49sY3Q9Sz2Y7qN7srjkVKVNgMFmTiYLkxwChvz
12962 [2020-02-25 10:03:38.094] [background] [info] -- UID (287137 to 287142)
12962 [2020-02-25 10:03:38.101] [background] [info] - Updating message kuEr6q4r36BggVXAqJTWMpRDKwzb4DF4oYaLZuQq3
12962 [2020-02-25 10:03:38.101] [background] [info] -- UID (287130 to 287135)
12962 [2020-02-25 10:03:38.109] [background] [info] - Updating message Gh6yJmDuKN4PejZYb6ULxW2H6j8Xjp1hJyqWqj4cK
12962 [2020-02-25 10:03:38.109] [background] [info] -- UID (287124 to 287127)
12962 [2020-02-25 10:03:38.117] [background] [info] - Updating message eDSeqRUEaAZcQipY173xhQzDBnrq3y1VK5Mmqjy2b
12962 [2020-02-25 10:03:38.117] [background] [info] -- UID (287119 to 287123)
12962 [2020-02-25 10:03:38.124] [background] [info] - Updating message Ztdy6sqyrGERwpqhCjYa5kypnXtzaqCk5dKoy6rAX
12962 [2020-02-25 10:03:38.124] [background] [info] -- UID (287114 to 287118)
12962 [2020-02-25 10:03:38.132] [background] [info] - Updating message YVTMnVMbQiyKFuv5Z17yRsLetZUrjxghQeV661HCt
12962 [2020-02-25 10:03:38.132] [background] [info] -- UID (287108 to 287110)
12962 [2020-02-25 10:03:38.139] [background] [info] - Updating message YQM5BVe2cUBy6yq8cEB7jvuJ494QHNnL2sjo6AQgC
12962 [2020-02-25 10:03:38.139] [background] [info] -- UID (287103 to 287105)
12962 [2020-02-25 10:03:38.174] [background] [info] - Updating message jQGGyxCzND4VygK3iwTQVnH7T94abSpfp2vNEBz3w
12962 [2020-02-25 10:03:38.174] [background] [info] -- UID (287095 to 287096)
12962 [2020-02-25 10:03:38.182] [background] [info] - Updating message aCosHGMWka3Pj6ZFtWGxVTtNbmofG5ZcK5GYEUBfC
12962 [2020-02-25 10:03:38
.182] [background] [info] -- UID (287090 to 287091)
12962 [2020-02-25 10:03:38.189] [background] [info] - Updating message 6LVBTzmEUGMpDJe8cWpFE92iMwS3dH28AXsTNRHwF
12962 [2020-02-25 10:03:38.189] [background] [info] -- UID (1004852 to 287021)
12962 [2020-02-25 10:03:38.189] [background] [info] -- FolderID (PjuDyt4opZ5sZm1ctFfjdXTKw8nuC6CZHYRU2zNW4 to M8u12E5EYnZk4WsowQb76N7T822VwheRuprizNNxt)
12962 [2020-02-25 10:03:38.288] [background] [info] syncFolderUIDRange for Drafts, UIDs: 1 - 63864, Heavy: false
12962 [2020-02-25 10:03:38.585] [background] [info] - remote=2, local=2
12962 [2020-02-25 10:03:38.682] [background] [info] syncFolderUIDRange for Deleted Items, UIDs: 1 - 39936, Heavy: false
12962 [2020-02-25 10:03:38.941] [background] [info] - remote=115, local=113
12962 [2020-02-25 10:03:38.941] [background] [info] - Fetching full headers for 2 (of 2 needed)
12962 [2020-02-25 10:03:39.162] [background] [info] - Updating message 6fnmFWri9T22LpGHPZ7ndkwoRuyczMB2h9t7DofBn
12962 [2020-02-25 10:03:39.162] [background] [info] -- UID (39931 to 39932)
12962 [2020-02-25 10:03:39.169] [background] [info] - Updating message F22nw5jpt8sSB1a5HNC8VZM3QtRUBa7DVzigZD5hU
12962 [2020-02-25 10:03:39.169] [background] [info] -- UID (39819 to 39820)
12962 [2020-02-25 10:03:39.264] [background] [info] syncFolderUIDRange for Junk Email, UIDs: 1 - 20848, Heavy: false
12962 [2020-02-25 10:03:39.555] [background] [info] - remote=7, local=7
12962 [2020-02-25 10:03:39.653] [background] [info] syncFolderUIDRange for [Airmail]/To Do, UIDs: 1 - 10, Heavy: false
12962 [2020-02-25 10:03:39.839] [background] [info] - remote=0, local=0
12962 [2020-02-25 10:03:39.938] [background] [info] syncFolderUIDRange for Archive1, UIDs: 612 - 1012, Heavy: false
12962 [2020-02-25 10:03:40.211] [background] [info] - remote=400, local=400
12962 [2020-02-25 10:03:40.306] [background] [info] syncFolderUIDRange for Calendar, UIDs: 1 - 43390, Heavy: false
12962 [2020-02-25 10:03:40.627] [background] [info] - remote=2897, local=0
12962 [2020-02-25 10:03:40.633] [background] [info] - Fetching full headers for 2897 (of 2897 needed)
12962 [2020-02-25 10:03:41.021] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID (heavy)","key":"ErrorFetch","retryable":true,"what":"std::exception"}
```

**Comment by AlexDunmow** [comment] 2020-02-26 00:35
Potential dupe of my bug? #1811

**Comment by intheravine** [comment] 2020-02-26 00:53
#1811 looks like the login is unsuccessful. I can login and Mailspring is able to send and receive Office 365 emails - I just get messages that there are connection issues - even though everything appears to be working as you'd expect.

**Comment by westr029** [comment] 2020-04-29 09:30
Having the same issue here with Office 365 on Mailspring 1.7.6 with OS Ubuntu 20.04.

**Comment by marastino** [comment] 2020-05-15 03:34
I'm also getting this with 1.7.6 on Ubuntu 20.04
1.7.6-e94bb759 to be exact.

**Comment by mrturcot** [comment] 2020-07-11 00:36
Same issue on Manjaro 20.0.3 using Mailspring 1.7.8-13635bcf. Mailspring reports connection issues however I am able to send and receive emails without issue.

**Comment by Kamiware** [comment] 2020-08-10 10:04
I have the same issue.

I think mailsping is 'to much' checking for mail, and is hitting some rate limit (max connections/whatever) at the office365 server side, and is so banning itselves.
Is there a way to have mailspring less agressive check for email? (like force it for subfolders to only check by default every 15 minutes or so?)

**Comment by CodeMouse92** [comment] 2021-01-18 19:30
Thank you for your patience on this issue! I know it's frustrating when you cannot connect to your email with Mailspring.

2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be a duplicate of one we've already migrated to Discourse:

https://community.getmailspring.com/t/institutional-office365-not-working/48

Please consider joining that community and continuing the discussion there.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-18 19:30 UTC
Labels: audit, mailserver-incompatibility, needs-reproduction
