### ISSUE TITLE
Request: ability to close the "New update available" window

### ISSUE THREAD

**Issue by mpetitjean** [Foundry376/Mailspring#1387] opened 2019-02-26 13:14 UTC
When a new update is available for Mailspring, a window open on the bottom left of the screen saying "An update to Mailspring is available (_version_)".  As far as I can see there is no option to close/discard the pop-up.

As an Arch Linux user, I rely on the AUR package to update Mailspring but there could be a bit of latency with respect to the actual new release. It would be interesting to add another button in the window saying "Discard" or "later".

**Comment by CodeMouse92** [comment] 2021-02-10 21:27
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue is similar to one already migrated to Discourse:

https://community.getmailspring.com/t/check-for-updates-banner-is-annoying-when-using-a-third-party-distribution-that-lags-behind-releases/542

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@mpetitjean: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-10 21:27 UTC
Labels: audit
