### ISSUE TITLE
Bug: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID (heavy)","key":"ErrorConnection","retryable":true,"what":"std::exception"} during message scanning

### ISSUE THREAD

**Issue by droggo** [Foundry376/Mailspring#2119] opened 2020-08-11 21:56 UTC
**Describe the bug**
After adding my IMAP account to mailspring, "Scanning Messages" is never finished. "One or more accounts are having connection issues" shows up frequently.

Log is showing following messages:
`68447 [2020-08-11 23:43:10.956] [background] [critical] 
***
*** Mailspring Sync 
*** An exception occurred during program execution: 
*** {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID (heavy)","key":"ErrorConnection","retryable":true,"what":"std::exception"}
***

68447 [2020-08-11 23:43:10.956] [background] [info] --sleeping
68447 [2020-08-11 23:45:10.956] [background] [info] Marking all folders as `busy`
68447 [2020-08-11 23:45:10.974] [background] [info] Syncing folder list...
68447 [2020-08-11 23:45:11.210] [background] [info] syncFolderUIDRange for INBOX, UIDs: 1 - 126114, Heavy: false
68447 [2020-08-11 23:45:11.306] [background] [info] - remote=1938, local=0
68447 [2020-08-11 23:45:11.314] [background] [info] - Fetching full headers for 1938 (of 1938 needed)
68447 [2020-08-11 23:45:41.395] [background] [critical] 
***
*** Mailspring Sync 
*** An exception occurred during program execution: 
*** {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID (heavy)","key":"ErrorConnection","retryable":true,"what":"std::exception"}
***`

**To Reproduce**
1. Add IMAP account

**Expected behavior**
all messages are scanned and cache is built

**Screenshots**
i can upload screenshots if this will help

**Setup: (please complete the following information):**
 - OS: Mint
 - OS Version 20
 - Mailspring Version: ex: 1.7.8 (found in the app's menu)

**Additional context** 
The issue does not occur on Gmail accounts, but it happens for both IMAP accounts I tested. Both of those accounts have quite a lot of existing messages (in thousands)

**Comment by Raka74** [comment] 2020-08-17 08:51
I'm seeing the same:

An exception occurred during program execution: 
*** {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID","key":"ErrorParse","retryable":true,"what":"std::exception"}

Running Elementary OS 5.1.7 / Mailspring 1.7.8

Added my Icloud mail account.
The error occurs for me after the Inbox is Synced, other folders stay empty

**Comment by droggo** [comment] 2020-08-17 10:01
I suspect this is problem in https://github.com/MailCore/mailcore2 or how this library is used (fetching all headers at once), but unfortunately I was not able to workaround it and had to resign from mailspring for now. It actually may be a duplicate of #1335 . Similar to #1815 #717 #1090

**Comment by CodeMouse92** [comment] 2021-02-01 18:25
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one already on Discourse:

https://community.getmailspring.com/t/syncfolderuidrange-errorconnection-on-one-of-the-folders/412

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-01 18:25 UTC
Labels: audit, bug
