### ISSUE TITLE
Toolbar buttons move around

### ISSUE THREAD

**Issue by sithu-win** [Foundry376/Mailspring#1031] opened 2018-08-16 20:32 UTC
Sometimes when clicking on the Archive button in the toolbar, the buttons slide over to the left causing the mouse to be over the Junk button on the next message. This results in accidentally marking messages as junk.

Unable to reliably reproduce this, but it happens regularly and may be related to the sidebar.

Version 1.4.1 (1.4.1) on OS X 10.12.6 Sierra

**Comment by heliostatic** [comment] 2018-08-25 00:35
I've noticed this behavior when moving between emails on Gmail accounts and non-gmail accounts:
![2018-08-16 15 30 35](https://user-images.githubusercontent.com/70898/44613115-490d0080-a7dd-11e8-92e7-ed5b9b5b66a7.gif)

**Comment by sithu-win** [comment] 2018-08-25 02:47
I've also noticed the reminder Bell icon also disappears between some messages with a similar result. Would be better if the toolbar was more static.

<img width="424" alt="screen shot 2018-08-24 at 7 44 39 pm" src="https://user-images.githubusercontent.com/6029039/44614285-71453100-a7d6-11e8-9a32-2bdcfc0cc0c4.png">

**Comment by CodeMouse92** [comment] 2021-02-24 22:25
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/archive-and-mark-as-spam-buttons-change-locations-unexpectedly/645

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-24 22:25 UTC
Labels: audit, enhancement
