### ISSUE TITLE
This account is invalid or Mailspring could not find the Inbox or All Mail folder. 

### ISSUE THREAD

**Issue by qodehub-victor** [Foundry376/Mailspring#780] opened 2018-03-21 21:07 UTC
<img width="641" alt="screen shot 2018-03-21 at 9 03 19 pm" src="https://user-images.githubusercontent.com/37292577/37737378-78617328-2d4b-11e8-8ea4-06e1af7c6eee.png">

Here's an issue I keep getting each time I try to add my email account. 
This account is invalid or Mailspring could not find the Inbox or All Mail folder. 

There's nothing wrong with the email account.

**Comment by Conspir3D** [comment] 2018-03-22 09:22
This loks like it is related to #768 

Are there any changes to get this issue solved as i have this problem too with ALL of my main accounts, hosted on the same provider. Other accounts e.g. strat mail works fine.

Please help as Mailspring is a quite nice Mailapp wich pro features are needed by us, but the app is useless with this issue for us.

**Comment by ovac** [comment] 2018-03-23 15:51
This same problem is not letting me add most of my emails.

**Comment by TomaszWaszczyk** [comment] 2019-05-02 21:02
The same.

**Comment by vislonery** [comment] 2019-07-17 06:44
same problem

**Comment by sprewell20051116** [comment] 2020-02-24 05:12
Same problem. Only seen in Windows version nut linux/macOS version.

**Comment by CodeMouse92** [comment] 2021-02-03 19:28
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/cannot-setup-imap-account-smtp-check-fails/92

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-03 19:28 UTC
Labels: audit

**Comment by CodeMouse92** [comment] 2021-02-03 19:29
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/cannot-setup-imap-account-smtp-check-fails/92

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

P.S. Duplicate of #768
