### ISSUE TITLE
Enhancement: Move Activity Window to rightmost panel

### ISSUE THREAD

**Issue by bayareacoder** [Foundry376/Mailspring#1020] opened 2018-08-13 15:47 UTC
##### Are there any related issues?

...

##### What operating system are you using?

OS X High Sierra 10.13.6

##### What version of Mailspring are you using?

1.4.0

--

**Bug?**
No

##### Is this an email sync or connection issue?

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**

Yes. Activity Window top left is too small. Also it would be better to show this as an 'Activity Feed' as a permanent right panel, similar to how you show the Profile, that updates with new activity tracking. This is how it is done in Polymail: you can select which tab to see in the right most panel, eg between Social Profile view and Activity Tracking.

##### Does this feature exist in another mail client or tool you use?
Yes, Polymail, per above.

**Comment by bengotow** [comment] 2018-09-17 19:29
I think this would be really cool - I'll see if we can make this an option in an upcoming release!

**Comment by CodeMouse92** [comment] 2021-02-25 01:22
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/option-to-move-activity-feed-to-right-panel/779

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

OP: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-25 01:22 UTC
Labels: audit, enhancement
