### ISSUE TITLE
Remove Mailspring/Snoozed

### ISSUE THREAD

**Issue by fouyos** [Foundry376/Mailspring#1262] opened 2018-12-10 12:57 UTC
##### Are there any related issues?

...

##### What operating system are you using?
Deepin Linux 15.8
...

##### What version of Mailspring are you using?
1.5.0
...

--

**Bug?**
I dont want Mailspring/Snoozed folder on my mail account. How to properly remove or opt-out or disable snoozed function?
##### Is this an email sync or connection issue?

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

...

**Comment by bengotow** [comment] 2018-12-19 07:34
Hey! Unfortunately there's currently not a way to remove Mailspring's Snoozed folder. We are looking at making it possible to move it to another location and I'll see if we can make it optional (or at least make it so that if you delete it, it doesn't come back.)

**Comment by bengotow** [comment] 2018-12-19 07:34
Hey! Unfortunately there's currently not a way to remove Mailspring's Snoozed folder. We are looking at making it possible to move it to another location and I'll see if we can make it optional (or at least make it so that if you delete it, it doesn't come back.)

**Comment by fuzuyx** [comment] 2018-12-19 10:02
looking forward to it

**Comment by CarlosRebolledoA** [comment] 2018-12-19 11:56
No hay que removerlo.

Distinto sería la opción ocultarlo / visible para que cada usuario elija

**Comment by cpl183** [comment] 2019-03-03 15:19
I'm not even using Mailspring anymore and this folder still recreates itself immediately after deletion in my Hotmail account, EVEN AFTER I DELETED MY MAILSPRING ID ON YOUR SITE!

How can i stop this, that is a really annoying and dubious behaviour.

**Comment by Raymo111** [comment] 2020-04-20 01:04
Any updates? @bengotow

**Comment by ikuranoff** [comment] 2020-10-19 07:41
This application is the worst I've ever used, I swear! It places my email in the Deleted folder without any rules, it created this Mailspring folder I cannot delete even after I deleted Mailspring app, and it does not show new emails if I open up a minimized window! I see there are new messages arrived (tray icon shows me that) but to see them I have to CLOSE the window and OPEN IT AGAIN! What a hell?! And they take money for this piece of garbage? Seriously?

**Comment by CodeMouse92** [comment] 2021-02-17 23:20
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/remove-mailspring-snoozed/677

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@fouyos: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-17 23:20 UTC
Labels: audit, product-direction, support
