### ISSUE TITLE
Bug: Activity sub-window is blurry/low-resolution (.deb package - not SNAP)

### ISSUE THREAD

**Issue by TimJCooper** [Foundry376/Mailspring#1931] opened 2020-04-23 08:31 UTC
Ubuntu 19.10
MailSpring: 1.7.6 (however, same issue with previous versions)

The activity sub-menu, located on the top-left, is particularly low-resolution and blurry (see screenshot). 

![Screenshot from 2020-04-23 11-28-49](https://user-images.githubusercontent.com/32513989/80077228-e17cfa80-8555-11ea-9c35-615ccc2021c9.png)

**Comment by bengotow** [comment] 2020-04-26 06:45
Hey thanks for reporting this! That's pretty wild - It looks like it might be rendering on a half-pixel. I think we may be able to fix this.

**Comment by fcastilloec** [comment] 2020-05-21 22:33
FYI, I can't reproduce this on Ubuntu 20.04. @TimJCooper have you updated your Ubuntu? and if so, do you still see this?

**Comment by TJCooperIL** [comment] 2020-05-22 06:49
I saw this on 19.10 + 20.04, however, as of v1.7.7 - it's fixed.

**Comment by CodeMouse92** [comment] 2021-01-18 23:22
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be connected to this:

https://community.getmailspring.com/t/interface-gets-blurry/89

Please consider joining that community and continuing the discussion there. **We need users to confirm the existence of this bug on Mailspring 1.7.8 or later, by commenting on that thread, for us to address this issue properly.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-18 23:22 UTC
Labels: audit, bug, linux
