### ISSUE TITLE
Deleting a message while viewing a search query does not remove it from view

### ISSUE THREAD

**Issue by jgardiner68** [Foundry376/Mailspring#1462] opened 2019-04-09 20:45 UTC
##### Are there any related issues?

Saw old messages from years ago which haven't been marked as resolved.

##### What operating system are you using?

MacOS latest

##### What version of Mailspring are you using?

Version 1.6.1 (1.6.1) using Gsuite.

**Bug?**

If I filter the messages by putting "is:unread" in the search box, then when I delete messages they do not disappear from the listing but they are being deleted.

I have Backspace set as Trash in the shortcuts, Mark as read is set to Manual and Swipe gesture and backspace / delete move message to trash is enabled.

Occasionally the same behaviour happens when viewing the inbox with no filtering.  Viewing a different folder and then coming back to the Inbox resolves this.

**Comment by athelas64** [comment] 2020-03-03 05:48
I will just briefly second that:
also on Windows, deleting a message in any search or filtered view will give no feedback to user something has happened. In this case, the expected behavior would be that the message disappears or that it is marked with a proper label (e,g. Trash). While the message, in fact, does get deleted, the UX is confusing. I hope this will get fixed soon. Thank you

**Comment by CodeMouse92** [comment] 2021-02-11 22:52
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/deleting-a-message-while-viewing-a-search-query-does-not-remove-it-from-view/576

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@jgardiner68 @athelas64: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-11 22:52 UTC
Labels: audit
