### ISSUE TITLE
Bug: automatic translation not working (Pro)

### ISSUE THREAD

**Issue by phylophyl** [Foundry376/Mailspring#2157] opened 2020-10-01 06:22 UTC
**Describe the bug**
Messages are not translated despite the blue box showing "Mailspring has translated your message into English", whether it is after clicking translate button or whether it is set on "always"

**To Reproduce**
1. Go to a message
2. Click on 'Translate'
3. You see "Mailspring has translated your message into English"
4. But the text is not translated

**Expected behavior**
Text translated with  Translation button has been clicked or when Always translate has been activated.

**Setup: (please complete the following information):**
 - OS: Debian 
 - OS Version [stable]
 - Mailspring Version: ex: 1.7.8

**Comment by Nate23** [comment] 2020-10-07 09:01
I am encountering the same issue.  Running version 1.7.8-13635bcf on Windows 10.

**Comment by tezer** [comment] 2020-10-27 10:49
Same issue on Linux (Pop_os)

**Comment by sj64** [comment] 2020-11-05 11:16
Exactly same issue:
ElementaryOS: 5.1.7 (based on Ubuntu 18.04.4LTS)
Mailspring: 1.7.8-13635bcf

**Comment by awaismirza92** [comment] 2020-11-26 10:09
Like sj64, I am also facing this issue on:
Elementary OS: 5.1.7 (based on Ubuntu 18.04.4 LTS)
Mailspring: 1.7.8-13635bcf

**Comment by CodeMouse92** [comment] 2021-01-25 22:04
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/translations-never-do-anything-with-the-api-always-returning-an-empty-string/255/3

Please consider joining that community and continuing the discussion there!

OP: if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

We're locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. In fact, I'm leaving the task open because it should be addressed in an upcoming release.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed** 2021-02-25 00:44 UTC
Labels: bug, migrated
