### ISSUE TITLE
Composer question / bug: Clicking in the padding of a composed email takes the focus away - easy to mess up

### ISSUE THREAD

**Issue by palefire19** [Foundry376/Mailspring#741] opened 2018-03-07 14:09 UTC
##### What operating system are you using?
MacOS 10.13.3

##### What version of Mailspring are you using?
1.1.4

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No - composer

##### Is the issue reproducible with a particular attachment, message, signature, etc?

My composer window has padding between its borders and where the text actually starts - see screenshot.

It's very easy to accidentally click in that padding - this happens a lot for example when trying to place the cursor on the first letter of a line.

If you "miss" and accidentally click in the padding itself, the composer loses the focus, and thus keystrokes begin to act as shortcuts on the thread, rather than text in the composer.

Would it be possible instead to just have those clicks default to placing the cursor in the first character on the line, or alternatively just do nothing?

<img width="802" alt="screen shot 2018-03-07 at 5 07 14 pm" src="https://user-images.githubusercontent.com/4412269/37096625-46751616-222a-11e8-9432-c3d86627d57f.png">

**Comment by CodeMouse92** [comment] 2021-02-03 18:36
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/clicking-in-the-padding-of-a-composed-email-takes-the-focus-away/445

Please consider joining that community and continuing the discussion there!

@palefire19: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-03 18:36 UTC
Labels: audit
