### ISSUE TITLE
Feature Request: Choose plain text font

### ISSUE THREAD

**Issue by sampotts** [Foundry376/Mailspring#1816] opened 2020-02-26 01:29 UTC
**Is your feature request related to a problem? Please describe.**
It'd just be nice to be able to choose the font + size used for the plain text messages. It looked better in 1.7.2 I think? 

**Describe the solution you'd like**
In the appearance settings (or wherever appropriate), add an option for plain-text font family and size.

**Describe alternatives you've considered**
I'm not sure there's an alternative? 

**Additional context**
N/A

**Comment by GNHua** [comment] 2020-04-26 16:49
I have tried MailSpring on both Windows 10 and Linux (Manjaro). The plain text emails look different for both systems. 
The emails are displayed in San Serif, but on Windows 10 the text looks bold, although it isn't. On linux it looks normal, i.e. font is skinnier.

**Comment by CodeMouse92** [comment] 2021-02-26 20:45
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/choose-plain-text-font/843

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@GNHua: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-26 20:45 UTC
Labels: audit, enhancement
