### ISSUE TITLE
Error encounter while sync after system restart

### ISSUE THREAD

**Issue by shadowwarrior29** [Foundry376/Mailspring#2211] opened 2020-11-27 17:22 UTC
Every time I restart my system, mail spring autostarts but doesn't sync. Instead, I get a message which says error encountered while syncing. I need to close the process and restart again to make it work which is kind of annoying.

I thought this was just an issue on my personal laptop but once I installed it on another system, I get the same issue

![image](https://user-images.githubusercontent.com/12261224/100472934-2f1c9f80-3103-11eb-9777-f23bf76a391e.png)

**Comment by CodeMouse92** [comment] 2021-02-02 02:33
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/the-eternal-sync-bug/334

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-02 02:33 UTC
Labels: audit
