### ISSUE TITLE
Problems with Icloud

### ISSUE THREAD

**Issue by Berkov99** [Foundry376/Mailspring#1586] opened 2019-07-22 16:25 UTC
Messages in the inbox disappear. This is not a workable situation and should not be allowed for an app such as mailspring. Just taken a Pro account, a waste of money. Does anyone have a solution????

##### Are there any related issues?
NO

...

##### What operating system are you using?
macOS Sierra 10.12.6
...

##### What version of Mailspring are you using?
1.6.3
...

--

**Bug?**

##### Is this an email sync or connection issue?
Sync

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Icloud
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

...

**Comment by CodeMouse92** [comment] 2021-02-02 02:37
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/disappearing-emails-desync/428

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-02 02:37 UTC
Labels: audit
