### ISSUE TITLE
Bug: Stuttering on Linux

### ISSUE THREAD

**Issue by hmnd** [Foundry376/Mailspring#2101] opened 2020-07-25 09:23 UTC
**Describe the bug**
Mailspring on Linux appears to cause system-wide slowness and stuttering. I keep noticing this issue on and off while using my computer and closing Mailspring almost always fixes it. This stuttering is noticeable in mouse movements and often while typing, as well (wherein the typing on screen pauses for a few seconds and then catches up). 

**To Reproduce**
1. Open Mailspring
2. Use device as normal
3. Experience random system-wide stuttering

**Expected behavior**
No stuttering.

**Setup: (please complete the following information):**
 - OS: Solus
 - OS Version: 4.1
 - Mailspring Version: 1.7.8

**Additional context** 
To be clear, this issue affects applications outside of Mailspring, too; not just an issue within Mailspring. This issue appears to have existed since as early as Oct. 2017 [in this report on the Linux Mint forum](https://forums.linuxmint.com/viewtopic.php?t=255280).

**Comment by StanAngeloff** [comment] 2020-07-27 09:59
This has started happening to me as well, I thought I was going mad. It usually is accompanied by a yellow banner inside the app complaining about not being able to sync. May be related to #1344 and #435, however the serious slowness has only started manifesting itself in the last month or so.

**Comment by sudoman281** [comment] 2020-08-13 15:33
I'm experiencing the same problem. I use the computer normally and suddenly I notice almost all of my CPU is used. Restarting the Mailspring app always helps.

**Comment by bengotow** [comment] 2020-08-17 13:34
Wow this is pretty wild—when you see the mouse stuttering the CPU is being used heavily? I'm really curious if it's unable to sleep threads for some reason and is running the retry logic in a hard loop instead of every 30s, etc. 

If you get a chance, could you pull the sync logs from Mailspring's config directory? You can reveal the log files by going to `Mailspring > Developer > Open Mailsync Logs` in the app's menu (it'll show a directory with a bunch of mailsync-***.log files)

**Comment by CodeMouse92** [comment] 2021-02-11 18:44
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/mailspring-has-high-cpu-usage/87

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-11 18:44 UTC
Labels: audit, bug, linux, needs-reproduction
