### ISSUE TITLE
FEATURE: Choosing A Default Composing Font

### ISSUE THREAD

**Issue by glenn2223** [Foundry376/Mailspring#1088] opened 2018-09-21 11:07 UTC
##### Are there any related issues?

NO

##### What operating system are you using?

Windows 10 64bit

##### What version of Mailspring are you using?

1.4.2

---

**Feature Request**

Can we specify the default font for when composing emails

**Comment by nikpmr** [comment] 2019-09-23 21:23
On the same topic, why is the default display font for sans-serif "Nylas Pro"? It looks somewhat large and bold next to the reading list. My guess is that it should be a similar font to the rest of the app (Segoe UI on Windows for instance). What is the opinion on that?

**Comment by CodeMouse92** [comment] 2021-02-20 03:02
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/choosing-a-default-composing-font/711

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@glenn2223: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-20 03:02 UTC
Labels: audit, enhancement
