### ISSUE TITLE
[Feature Request] Set message `Importance` when composing

### ISSUE THREAD

**Issue by pablorq** [Foundry376/Mailspring#1648] opened 2019-10-01 07:44 UTC
##### Are there any related issues?

No

##### What operating system are you using?

Windows 7/10

##### What version of Mailspring are you using?

1.6.3-134a0e55

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

Yes

When composing an email, it could be nice to mark it as urgent in order to be received in a different way (different color or highlighted) according to each email client.

In Outlook you have the following options:
- Importance
  - Low
  - Normal
  - High

- Sensitivity
   - Normal
   - Personal
   - Private
   - Confidential

There are some other interesting options, like voting and others, but this could be other feature request.

**Comment by bengotow** [comment] 2019-10-08 21:49
Hey! There's actually an email standard for this (https://tools.ietf.org/html/rfc4021#section-2.1.52) but Mailspring doesn't allow you to choose message importance because many clients don't display the value. I'll see if we can add this as an advanced option sometime soon.

**Comment by pablorq** [comment] 2019-10-09 06:37
Maybe this can be a way to differentiate Mailspring form other email clients: to accomplish the RFCs!

:)

**Comment by fazla86** [comment] 2020-04-28 11:12
I need this feature very much. I hope the status of received message importance will be present as well. I use Mailspring on Linux with Outlook 365 account and need to see if the message was tagged with high importance.

I hope this feature will be developed soon.

**Comment by habl** [comment] 2020-07-01 10:00
Would like to use it as well!

**Comment by mathewgrabau** [comment] 2020-07-10 04:06
The high importance would be very useful.

**Comment by CodeMouse92** [comment] 2021-02-26 17:21
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/message-importance/829/1

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@pablorq @fazla86: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-26 17:21 UTC
Labels: audit, enhancement, product-direction
