### ISSUE TITLE
Bug: RAW HTML signature, extra new line break added between sequential paragraphs

### ISSUE THREAD

**Issue by colinbes** [Foundry376/Mailspring#1925] opened 2020-04-21 19:12 UTC
**Describe the bug**
When adding signature using raw HTML a <br> element is inserted between repeating paragraphs <p>

**To Reproduce**
Add RAW HTML signature

```
<u style="color:blue;">Internet Disclaimer</u>
<p>This message (including any attachments) contains confidential information intended for a specific individual and purpose, and may be protected by law.</p>
<p>If you are not the intended recipient, you should delete this message and are hereby notified that any disclosure, copying, or distribution of this message, or the taking of any action based on it, is strictly prohibited.</p>
```
Compose email and view in debug

**Expected behavior**
Signature inserted into email should have following format:
```
<signature id="...">
<u style="color:blue;">Internet Disclaimer</u>
<p>This message (including any attachments) contains confidential information intended for a specific individual and purpose, and may be protected by law.</p>
<p>If you are not the intended recipient, you should delete this message and are hereby notified that any disclosure, copying, or distribution of this message, or the taking of any action based on it, is strictly prohibited.</p>
</signature>
```

**Noticed output**
```
<signature id="...">
<u style="color:blue;">Internet Disclaimer</u><p>This message (including any attachments) contains confidential information intended for a specific individual and purpose, and may be protected by law.</p>
<br>
<p>If you are not the intended recipient, you should delete this message and are hereby notified that any disclosure, copying, or distribution of this message, or the taking of any action based on it, is strictly prohibited.</p></signature>
```
**Setup: (please complete the following information):**
 - OS: Pop OS Ubuntu 
 - OS Version : 18.04
 - Mailspring Version: ex: 1.7.5.a976d710

**Comment by CodeMouse92** [comment] 2021-02-27 03:36
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/raw-html-signature-extra-new-line-break-added-between-sequential-paragraphs/858

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@colinbes: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-27 03:36 UTC
Labels: audit, bug
