### ISSUE TITLE
Add support for Gmail accounts without All Mails folder

### ISSUE THREAD

**Issue by ronisbr** [Foundry376/Mailspring#277] opened 2017-10-30 16:29 UTC
##### What operating system are you using?
openSUSE Tumbleweed
...

##### What version of Mailspring are you using?
1.0.7
...

**Feature Request?**

I would like to ask to remove the requirement that the Gmail account must expose "All Mail" folder. In default iOS Mail client and in the Mail.app client of macOS, if "All Mail" is exposed to IMAP, then all my mails will be downloaded twice, which is not acceptable. Hence, it will be very good if I can use Mailspring without needing to expose my "All Mail" folder to IMAP.

##### Does this feature exist in another mail client or tool you use?
Yes. All mail clients I use (Thunderbird, Mail.app, Outlook, etc) can connect to Gmail without requiring "All Mails" folder to be exposed to IMAP.
...

**Comment by bengotow** [comment] 2017-10-30 18:40
Hey! Thanks for filing this—unfortunately this was a pretty core design decision when we built the new sync engine. Supporting Gmail Labels properly (and showing them as real labels and not as folders like Apple Mail does) requires syncing the All Mail folder. (Mailspring avoids the "downloading twice" issue by /only/ scanning All Mail and ignoring the fake folders that Gmail creates for your labels.)

I'll see if we can make it possible to link a Gmail account as a standard IMAP account in the future. That'd make it work just like Mail.app (where you need to disable All Mail to avoid double-syncing your email, and labels appear as folders.)

**Comment by ronisbr** [comment] 2017-10-31 16:37
Hi @bengotow !

Thanks for the answer. I understand the problem and I think that it will work for my use case if I can connect to gmail as a standard IMAP. Is there any problem if I enable the "less-secure" option in Gmail and configure the account in Mailspring as a default IMAP? Would be that a workaround for this issue?

**Comment by redhatjobin** [comment] 2018-01-16 11:43
@bengotow here is the issue I'm facing.
- I have thousands of notification email with a label "notification", these emails are skip-inbox when it is received, also I have excluded this folder from IMAP via Gmail settings.
- I have 2000 emails limited for IMAP.

Now, since mailspring needs to enable "All Mail", all the notifications are syncing to the "All mail" folder, and the worst thing is I have only 5 or 10 emails maximum showing up in the inbox (because of the 2000 IMAP limit set).

I was using mac mail earlier and resolved this issue by disabling the "All Mail" from Gmail IMAP setting.

It would be great if you could give me the option to disable "All mail" form Gmail IMAP settings.

**Comment by lhorstm** [comment] 2020-08-11 22:18
Has there been any work on this or a workaround? I too need to use mailspring with the 'All Mails' label turned off in gmail.

**Comment by CodeMouse92** [comment] 2021-02-15 19:48
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/dont-sync-all-of-all-mail/626

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@Modelmat: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-15 19:48 UTC
Labels: audit, enhancement, product-direction
