### ISSUE TITLE
Feature Request: Choose IMAP Folders and time window to sync / scan / cache

### ISSUE THREAD

**Issue by sommarnatt** [Foundry376/Mailspring#888] opened 2018-05-23 13:38 UTC
Hi!

I'm one of those email users with a HUGE amount of emails.
It took a few days time for Mailspring to scan my mail history and then to cache my main inbox.

I've seen that you're developing an option to cache longer / shorter time than 3 months, however I'd like to be able to disable scanning/caching per IMAP account folder.

Would that be doable?

**Comment by CodeMouse92** [comment] 2021-02-05 01:03
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/per-account-per-folder-sync-scan-cache-settings/474

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@sommarnatt: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-05 01:03 UTC
Labels: audit
