### ISSUE TITLE
Feature Request: Integrate Mailspring with OS search indexing

### ISSUE THREAD

**Issue by 20zinnm** [Foundry376/Mailspring#2042] opened 2020-06-05 18:21 UTC
Microsoft Outlook provides a tight integration between your mailbox and the Windows Search bar, as does Apple Mail with Spotlight.

It would be very useful if Mailspring could provide such an integration, allowing the user to search for emails from Windows Search or Spotlight.

https://docs.microsoft.com/en-us/windows/win32/search/-search-3x-wds-extidx-overview
https://developer.apple.com/documentation/corespotlight

**Comment by CodeMouse92** [comment] 2021-03-02 02:26
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/integrate-mailspring-with-os-search-indexing/914

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@20zinnm: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 02:26 UTC
Labels: audit, enhancement
