### ISSUE TITLE
Bug:  Calender Preview - Black Theme + Black Text = unreadable

### ISSUE THREAD

**Issue by famewolf** [Foundry376/Mailspring#2173] opened 2020-10-21 17:18 UTC
When using the black theme and viewing the calendar preview appointments are unreadable because the text is still black instead of switching to white.

**Screenshots**
![image](https://user-images.githubusercontent.com/4558832/96754590-82caf900-139f-11eb-90cf-99009e11315a.png)

**Setup: (please complete the following information):**
 - OS: Linux
-  Kde Neon 20.02
 - Mailspring Version: ex: 1.7.8 (Snap)

I'll also mention the text is more viewable (because it's zoomed)  in the screenshot than it was on the actual screen.

**Comment by CodeMouse92** [comment] 2021-02-03 18:47
Duplicate of #1928

**Comment by CodeMouse92** [comment] 2021-03-03 03:25
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/calender-preview-black-theme-black-text-unreadable/959

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@famewolf: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-03 03:25 UTC
Labels: audit, bug
