### ISSUE TITLE
Mails appears, disappears and reappears suddenly in inbox

### ISSUE THREAD

**Issue by pablosolar** [Foundry376/Mailspring#1315] opened 2019-01-10 08:45 UTC
Hello all!

I just installed Mailsping somedays ago and mails loaded in inbox (even in other folders) suddenly disappear to reappear some seconds or minutes after. Then, other mails disappears and so on.

Is there any other reported similar bug or something? Are you working on this?

Thank you in advance so much!

**Comment by chemicalkosek** [comment] 2019-01-11 09:34
I thought I was going insane. But I have definitely seen emails disappearing from the list. I think it was in 'Sent'. No clue how to reproduce this... ;)

**Comment by pablosolar** [comment] 2019-01-11 09:37
@chemicalkosek this happens to me in Send folder, Inbox folder, Deleted folder, etc.!

**Comment by pdaniell** [comment] 2019-01-12 22:36
@pablosolar @chemicalkosek Are you using Gmail accounts? I am seeing this too. I reported it as #1244 -- I thought that it was because Mailspring is using a custom "Sent Items" Label rather than the system "Sent" Label. However, now I observe actually the same "flashing" of messages -- some messages, like preciously sent messages, appear rather quickly and then disappear. I've only seen it in Sent messages.  My sync logs look like this:

```
26052 [2019-01-12 22:33:10.310] [background] [error] Could not create Mailspring container folder: Mailspring. ErrorCreate
26052 [2019-01-12 22:33:10.426] [background] [error] Could not create required Mailspring folder: Mailspring/Snoozed. ErrorCreate
26052 [2019-01-12 22:33:10.550] [background] [info] syncFolderUIDRange for [Gmail]/All Mail, UIDs: 24636 - 25312, Heavy: false
26052 [2019-01-12 22:33:11.081] [background] [info] - remote=432, local=400
26052 [2019-01-12 22:33:11.082] [background] [info] - Fetching full headers for 32 (of 32 needed)
26052 [2019-01-12 22:33:11.251] [background] [info] - Updating message Hryn9sNdtTzxawUYDj5KkRU8hqF4RUpQKgVEcW63C
26052 [2019-01-12 22:33:11.251] [background] [info] -- UID (6470 to 25308)
26052 [2019-01-12 22:33:11.251] [background] [info] -- FolderID (jAkk9NR5AKbmZU7G6QeqdTSTHnmrBaz1thhQptjRN to apFW7hDmkvXHj86CafsEjt3EbJQUjJ4Pu4ftTY7zb)
26052 [2019-01-12 22:33:11.251] [background] [info] -- XGMLabels ([] to ["\\Sent"])
26052 [2019-01-12 22:33:11.255] [background] [info] - Updating message q6UVc5dSKD985mED6xhy3Xgp3YxZmbi2CjonRvzN8
26052 [2019-01-12 22:33:11.255] [background] [info] -- UID (6466 to 25269)
26052 [2019-01-12 22:33:11.255] [background] [info] -- FolderID (jAkk9NR5AKbmZU7G6QeqdTSTHnmrBaz1thhQptjRN to apFW7hDmkvXHj86CafsEjt3EbJQUjJ4Pu4ftTY7zb)
26052 [2019-01-12 22:33:11.255] [background] [info] -- XGMLabels ([] to ["\\Sent"])
26052 [2019-01-12 22:33:11.258] [background] [info] - Updating message g6aosyNCWaXCenCn9g7PZqDvBNnn2tPwnxwtsPQP3
26052 [2019-01-12 22:33:11.258] [background] [info] -- UID (6465 to 25267)
26052 [2019-01-12 22:33:11.258] [background] [info] -- FolderID (jAkk9NR5AKbmZU7G6QeqdTSTHnmrBaz1thhQptjRN to apFW7hDmkvXHj86CafsEjt3EbJQUjJ4Pu4ftTY7zb)
26052 [2019-01-12 22:33:11.258] [background] [info] -- XGMLabels ([] to ["\\Sent"])
26052 [2019-01-12 22:33:11.261] [background] [info] - Updating message QXNiDB3JHQaxutxSN1bqvong7LVdEdSzTgbMVRTfD
26052 [2019-01-12 22:33:11.261] [background] [info] -- UID (6452 to 25239)
26052 [2019-01-12 22:33:11.261] [background] [info] -- FolderID (jAkk9NR5AKbmZU7G6QeqdTSTHnmrBaz1thhQptjRN to apFW7hDmkvXHj86CafsEjt3EbJQUjJ4Pu4ftTY7zb)
26052 [2019-01-12 22:33:11.261] [background] [info] -- XGMLabels ([] to ["\\Sent"])
26052 [2019-01-12 22:33:11.265] [background] [info] - Updating message jri7qV8HmP9UPhkhEsSDWyaMfMqTBuHGPaHH216RT
26052 [2019-01-12 22:33:11.265] [background] [info] -- UID (6445 to 25216)
26052 [2019-01-12 22:33:11.265] [background] [info] -- FolderID (jAkk9NR5AKbmZU7G6QeqdTSTHnmrBaz1thhQptjRN to apFW7hDmkvXHj86CafsEjt3EbJQUjJ4Pu4ftTY7zb)
26052 [2019-01-12 22:33:11.265] [background] [info] -- XGMLabels ([] to ["\\Sent"])
26052 [2019-01-12 22:33:11.268] [background] [info] - Updating message qHw7ZEEASTRxUXZ9bpfVCCxyQTLukbFw6jmmTVJNQ
26052 [2019-01-12 22:33:11.268] [background] [info] -- UID (6444 to 25209)
26052 [2019-01-12 22:33:11.268] [background] [info] -- FolderID (jAkk9NR5AKbmZU7G6QeqdTSTHnmrBaz1thhQptjRN to apFW7hDmkvXHj86CafsEjt3EbJQUjJ4Pu4ftTY7zb)
26052 [2019-01-12 22:33:11.268] [background] [info] -- XGMLabels ([] to ["\\Sent"])
26052 [2019-01-12 22:33:11.271] [background] [info] - Updating message MnMAXTQv3v1rfqfahKp4gMf6xwyV6Bjpsvv1uaotE
26052 [2019-01-12 22:33:11.271] [background] [info] -- UID (6432 to 25169)
26052 [2019-01-12 22:33:11.271] [background] [info] -- FolderID (jAkk9NR5AKbmZU7G6QeqdTSTHnmrBaz1thhQptjRN to apFW7hDmkvXHj86CafsEjt3EbJQUjJ4Pu4ftTY7zb)
26052 [2019-01-12 22:33:11.271] [background] [info] -- XGMLabels ([] to ["\\Sent"])
26052 [2019-01-12 22:33:11.275] [background] [info] - Updating message 5mkbJsRQBK5N4CnvnLmdPqotPhFqzejxXzCoZoUAr
26052 [2019-01-12 22:33:11.275] [background] [info] -- UID (24866 to 24922)
26052 [2019-01-12 22:33:11.275] [background] [info] -- XGMLabels (["\\Sent"] to ["\\Inbox"])
26052 [2019-01-12 22:33:11.278] [background] [info] - Updating message b5kWTiqwq6oMWJSFGD4G3jbeYvdbEz7r8cEZNHqqr
26052 [2019-01-12 22:33:11.278] [background] [info] -- UID (24736 to 24737)
26052 [2019-01-12 22:33:11.278] [background] [info] -- XGMLabels ([] to ["\\Sent"])
26052 [2019-01-12 22:33:11.281] [background] [info] - Updating message EcnuyK6GetT5u2C4sVf8o5PyDjB4AQ6cEJ3hXKaAQ
26052 [2019-01-12 22:33:11.281] [background] [info] -- UID (24734 to 24735)
26052 [2019-01-12 22:33:11.281] [background] [info] -- XGMLabels ([] to ["\\Sent"])
26052 [2019-01-12 22:33:11.284] [background] [info] - Updating message R1NGhheEiy6LBcx3cQFUriFvQmF6de4ETDRJG6L3N
26052 [2019-01-12 22:33:11.284] [background] [info] -- UID (24732 to 24733)
26052 [2019-01-12 22:33:11.284] [background] [info] -- XGMLabels ([] to ["\\Sent"])
26052 [2019-01-12 22:33:11.287] [background] [info] - Updating message GeA8keJFCDNCr5pySbBA6xfckc2FpaUER8YUQB8Q
26052 [2019-01-12 22:33:11.287] [background] [info] -- UID (24730 to 24731)
26052 [2019-01-12 22:33:11.287] [background] [info] -- XGMLabels ([] to ["\\Sent"])
26052 [2019-01-12 22:33:11.291] [background] [info] - Updating message nqgukanKiGdhNNDtdqxQ9ACLE4X4naHRBRPi1WiDr
26052 [2019-01-12 22:33:11.291] [background] [info] -- UID (24728 to 24729)
26052 [2019-01-12 22:33:11.291] [background] [info] -- XGMLabels ([] to ["\\Sent"])
26052 [2019-01-12 22:33:11.294] [background] [info] - Updating message 9sTxKtGKh23gepFffEZx94r5JVXkTZYApuPWCWDwn
26052 [2019-01-12 22:33:11.294] [background] [info] -- UID (24726 to 24727)
26052 [2019-01-12 22:33:11.294] [background] [info] -- XGMLabels ([] to ["\\Sent"])
26052 [2019-01-12 22:33:11.297] [background] [info] - Updating message CiHgK9PU1p1AL7uuaioC2bjWDWcrzd74y9vBiG4Xh
26052 [2019-01-12 22:33:11.297] [background] [info] -- UID (24724 to 24725)
26052 [2019-01-12 22:33:11.297] [background] [info] -- XGMLabels ([] to ["\\Sent"])
26052 [2019-01-12 22:33:11.300] [background] [info] - Updating message EwQqcqDq4PVPpKUPqopZxgj4yLePKq1dcvcGk9Lr7
26052 [2019-01-12 22:33:11.300] [background] [info] -- UID (24722 to 24723)
26052 [2019-01-12 22:33:11.300] [background] [info] -- XGMLabels ([] to ["\\Sent"])
26052 [2019-01-12 22:33:11.303] [background] [info] - Updating message 5BvXNa4Pc7uwGQLJ7ud8sapdDJyKzCg234pWEGHnN
26052 [2019-01-12 22:33:11.303] [background] [info] -- UID (24720 to 24721)
26052 [2019-01-12 22:33:11.304] [background] [info] -- XGMLabels ([] to ["\\Sent"])
26052 [2019-01-12 22:33:11.307] [background] [info] - Updating message 5tWc9BU1SH8FZKss1nybwCaz3RBvXfLwB91ohGrvo
26052 [2019-01-12 22:33:11.307] [background] [info] -- UID (24718 to 24719)
26052 [2019-01-12 22:33:11.307] [background] [info] -- XGMLabels ([] to ["\\Sent"])
26052 [2019-01-12 22:33:11.310] [background] [info] - Updating message iKSxMxV4opiLpnWR6QwPiS8cqLu6JA7ZYy2EEvacv
26052 [2019-01-12 22:33:11.310] [background] [info] -- UID (24716 to 24717)
26052 [2019-01-12 22:33:11.310] [background] [info] -- XGMLabels ([] to ["\\Sent"])
26052 [2019-01-12 22:33:11.333] [background] [info] - Updating message sp7nVePZfVRt1gNBzMC6HwmUCZmTAYLUnWNcXYsVm
26052 [2019-01-12 22:33:11.333] [background] [info] -- UID (24714 to 24715)
26052 [2019-01-12 22:33:11.333] [background] [info] -- XGMLabels ([] to ["\\Sent"])
26052 [2019-01-12 22:33:11.342] [background] [info] - Updating message eHoUDeUSXvxmwaX4Lph5SsYo6iFMrmXU3aFH76wSA
26052 [2019-01-12 22:33:11.342] [background] [info] -- UID (24712 to 24713)
26052 [2019-01-12 22:33:11.342] [background] [info] -- XGMLabels ([] to ["\\Sent"])
26052 [2019-01-12 22:33:11.347] [background] [info] - Updating message Kn9Rq8MgD2rUMRgSuKfyvjaaa3BZ7nbby4aXDqh5C
26052 [2019-01-12 22:33:11.347] [background] [info] -- UID (24710 to 24711)
26052 [2019-01-12 22:33:11.347] [background] [info] -- XGMLabels ([] to ["\\Sent"])
26052 [2019-01-12 22:33:11.350] [background] [info] - Updating message QGEswgT2ssrBCx6vGr7bauszpKReeQ2o1PR7s1pSu
26052 [2019-01-12 22:33:11.350] [background] [info] -- UID (24708 to 24709)
26052 [2019-01-12 22:33:11.350] [background] [info] -- XGMLabels ([] to ["\\Sent"])
26052 [2019-01-12 22:33:11.354] [background] [info] - Updating message 85wdaEDZVzZgiPbT2hy4KqLRYHFzSWyR82hpNQvTd
26052 [2019-01-12 22:33:11.354] [background] [info] -- UID (24706 to 24707)
26052 [2019-01-12 22:33:11.354] [background] [info] -- XGMLabels ([] to ["\\Sent"])
26052 [2019-01-12 22:33:11.356] [background] [info] - Updating message 8igDJHQy1w3bXM6oDstDGy4VZNHoGLpxm9iaGPK4X
26052 [2019-01-12 22:33:11.357] [background] [info] -- UID (24704 to 24705)
26052 [2019-01-12 22:33:11.357] [background] [info] -- XGMLabels ([] to ["\\Sent"])
26052 [2019-01-12 22:33:11.359] [background] [info] - Updating message NJmhMg3BeYJ9Hzmx4ZcJruvUiFakKEiNiiXcyGacv
26052 [2019-01-12 22:33:11.359] [background] [info] -- UID (24702 to 24703)
26052 [2019-01-12 22:33:11.360] [background] [info] -- XGMLabels ([] to ["\\Sent"])
26052 [2019-01-12 22:33:11.362] [background] [info] - Updating message NuPGxeDHgqzTzK8bREKot3BP3rgw7XEKStUHMV3p7
26052 [2019-01-12 22:33:11.363] [background] [info] -- UID (24700 to 24701)
26052 [2019-01-12 22:33:11.363] [background] [info] -- XGMLabels ([] to ["\\Sent"])
26052 [2019-01-12 22:33:11.366] [background] [info] - Updating message ZovVQVrwfmq6fvy69KcCZX2avfAxRyvfdpe1oQL3e
26052 [2019-01-12 22:33:11.366] [background] [info] -- UID (24698 to 24699)
26052 [2019-01-12 22:33:11.366] [background] [info] -- XGMLabels ([] to ["\\Sent"])
26052 [2019-01-12 22:33:11.369] [background] [info] - Updating message bRPqe7CzJyZ21BRLWKcn1HicbMrnSMKKcAL1RogPe
26052 [2019-01-12 22:33:11.369] [background] [info] -- UID (24696 to 24697)
26052 [2019-01-12 22:33:11.369] [background] [info] -- XGMLabels ([] to ["\\Sent"])
26052 [2019-01-12 22:33:11.372] [background] [info] - Updating message fPoj2m4fGyTSY14564vj199WiuyxEcAQ9J4wgaXdk
26052 [2019-01-12 22:33:11.372] [background] [info] -- UID (24694 to 24695)
26052 [2019-01-12 22:33:11.372] [background] [info] -- XGMLabels ([] to ["\\Sent"])
26052 [2019-01-12 22:33:11.375] [background] [info] - Updating message nyfxaQTfyRbkWVUYw11tMsRccNGW8hMTDHUAGFYFL
26052 [2019-01-12 22:33:11.375] [background] [info] -- UID (24692 to 24693)
26052 [2019-01-12 22:33:11.375] [background] [info] -- XGMLabels ([] to ["\\Sent"])
26052 [2019-01-12 22:33:11.378] [background] [info] - Updating message AXpdwXnNFu94rdUKNU8GVfon32NmTBmmWWsdSxQwx
26052 [2019-01-12 22:33:11.378] [background] [info] -- UID (24690 to 24691)
26052 [2019-01-12 22:33:11.378] [background] [info] -- XGMLabels ([] to ["\\Sent"])
26052 [2019-01-12 22:33:11.542] [background] [info] syncFolderUIDRange for [Gmail]/Trash, UIDs: 1 - 6471, Heavy: false
26052 [2019-01-12 22:33:11.799] [background] [info] - remote=7, local=0
26052 [2019-01-12 22:33:11.799] [background] [info] - Fetching full headers for 7 (of 7 needed)
26052 [2019-01-12 22:33:11.945] [background] [info] - Updating message Hryn9sNdtTzxawUYDj5KkRU8hqF4RUpQKgVEcW63C
26052 [2019-01-12 22:33:11.945] [background] [info] -- UID (25308 to 6470)
26052 [2019-01-12 22:33:11.945] [background] [info] -- FolderID (apFW7hDmkvXHj86CafsEjt3EbJQUjJ4Pu4ftTY7zb to jAkk9NR5AKbmZU7G6QeqdTSTHnmrBaz1thhQptjRN)
26052 [2019-01-12 22:33:11.945] [background] [info] -- XGMLabels (["\\Sent"] to [])
26052 [2019-01-12 22:33:11.951] [background] [info] - Updating message q6UVc5dSKD985mED6xhy3Xgp3YxZmbi2CjonRvzN8
26052 [2019-01-12 22:33:11.951] [background] [info] -- UID (25269 to 6466)
26052 [2019-01-12 22:33:11.951] [background] [info] -- FolderID (apFW7hDmkvXHj86CafsEjt3EbJQUjJ4Pu4ftTY7zb to jAkk9NR5AKbmZU7G6QeqdTSTHnmrBaz1thhQptjRN)
26052 [2019-01-12 22:33:11.951] [background] [info] -- XGMLabels (["\\Sent"] to [])
26052 [2019-01-12 22:33:11.956] [background] [info] - Updating message g6aosyNCWaXCenCn9g7PZqDvBNnn2tPwnxwtsPQP3
26052 [2019-01-12 22:33:11.956] [background] [info] -- UID (25267 to 6465)
26052 [2019-01-12 22:33:11.956] [background] [info] -- FolderID (apFW7hDmkvXHj86CafsEjt3EbJQUjJ4Pu4ftTY7zb to jAkk9NR5AKbmZU7G6QeqdTSTHnmrBaz1thhQptjRN)
26052 [2019-01-12 22:33:11.956] [background] [info] -- XGMLabels (["\\Sent"] to [])
26052 [2019-01-12 22:33:11.959] [background] [info] - Updating message QXNiDB3JHQaxutxSN1bqvong7LVdEdSzTgbMVRTfD
26052 [2019-01-12 22:33:11.959] [background] [info] -- UID (25239 to 6452)
26052 [2019-01-12 22:33:11.959] [background] [info] -- FolderID (apFW7hDmkvXHj86CafsEjt3EbJQUjJ4Pu4ftTY7zb to jAkk9NR5AKbmZU7G6QeqdTSTHnmrBaz1thhQptjRN)
26052 [2019-01-12 22:33:11.959] [background] [info] -- XGMLabels (["\\Sent"] to [])
26052 [2019-01-12 22:33:11.962] [background] [info] - Updating message jri7qV8HmP9UPhkhEsSDWyaMfMqTBuHGPaHH216RT
26052 [2019-01-12 22:33:11.962] [background] [info] -- UID (25216 to 6445)
26052 [2019-01-12 22:33:11.962] [background] [info] -- FolderID (apFW7hDmkvXHj86CafsEjt3EbJQUjJ4Pu4ftTY7zb to jAkk9NR5AKbmZU7G6QeqdTSTHnmrBaz1thhQptjRN)
26052 [2019-01-12 22:33:11.962] [background] [info] -- XGMLabels (["\\Sent"] to [])
26052 [2019-01-12 22:33:11.965] [background] [info] - Updating message qHw7ZEEASTRxUXZ9bpfVCCxyQTLukbFw6jmmTVJNQ
26052 [2019-01-12 22:33:11.965] [background] [info] -- UID (25209 to 6444)
26052 [2019-01-12 22:33:11.965] [background] [info] -- FolderID (apFW7hDmkvXHj86CafsEjt3EbJQUjJ4Pu4ftTY7zb to jAkk9NR5AKbmZU7G6QeqdTSTHnmrBaz1thhQptjRN)
26052 [2019-01-12 22:33:11.965] [background] [info] -- XGMLabels (["\\Sent"] to [])
26052 [2019-01-12 22:33:11.968] [background] [info] - Updating message MnMAXTQv3v1rfqfahKp4gMf6xwyV6Bjpsvv1uaotE
26052 [2019-01-12 22:33:11.968] [background] [info] -- UID (25169 to 6432)
26052 [2019-01-12 22:33:11.968] [background] [info] -- FolderID (apFW7hDmkvXHj86CafsEjt3EbJQUjJ4Pu4ftTY7zb to jAkk9NR5AKbmZU7G6QeqdTSTHnmrBaz1thhQptjRN)
26052 [2019-01-12 22:33:11.968] [background] [info] -- XGMLabels (["\\Sent"] to [])
26052 [2019-01-12 22:33:11.970] [background] [info] Sync loop deleting unlinked messages with phase 1.
26052 [2019-01-12 22:33:11.975] [background] [info] Sync loop complete.

```

**Comment by pablosolar** [comment] 2019-01-14 08:20
@pdaniell Hello Paul, 

In my case, I am using office 365 account!

**Comment by chemicalkosek** [comment] 2019-01-14 08:45
I'm using Gmail but also 2 other custom domain IMAP accounts. So can't really say what messages from which account are flashing there in the view.

**Comment by M-Pixel** [comment] 2019-01-14 19:45
Using Fastmail, as soon as I updated to the latest version of Mailspring, I also noticed several emails disappear.  I've experienced this on all of my computers, and only once upgrading to the latest version.  Using the webmail interface, I see that these emails exist.  It gets worse as time goes on - some folders now appear completely empty.

**Comment by cpacchierotti** [comment] 2019-02-07 15:08
Maybe related to #304 .

**Comment by M-Pixel** [comment] 2019-02-07 18:37
You're right.  This issue should have been marked duplicate and closed by the maintainer weeks ago.

**Comment by CodeMouse92** [comment] 2021-02-02 02:45
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/disappearing-emails-desync/428

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-02 02:45 UTC
Labels: audit
