### ISSUE TITLE
Bug: Mailspring menus, file browsers etc. not dark when using system-wide dark mode

### ISSUE THREAD

**Issue by squintgit** [Foundry376/Mailspring#1937] opened 2020-04-25 05:18 UTC
**Describe the bug**
In Linux, the regular Mailspring menus and other things like file selector windows appear light even when the user is using dark mode system-wide. Choosing a dark theme such as the Isaac Dark Theme or Minimal Dark Theme does not yield dark menus or file selector windows either.

**To Reproduce**
1. Set your Linux system to dark mode
2. Go to any of the menus or choose to attach a file to an email
3. Notice the menus and file selector windows are all light still

**Expected behavior**
The menus and windows should be dark along with the rest of the interface

**Screenshots**
![Screenshot from 2020-04-25 00-16-11](https://user-images.githubusercontent.com/11663794/80271858-07a3b700-868a-11ea-8253-b0332d3b02f2.png)

**Setup: (please complete the following information):**
 - OS: Pop! OS (Ubuntu-based)
 - OS Version 19.10
 - Mailspring Version: ex: 1.7.6

**Additional context** 
n/a

**Comment by bengotow** [comment] 2020-04-26 06:41
Hey! I /think/ this will be resolved soon(ish) when we launch an update based on Electron 8. Stay tuned!

**Comment by squintgit** [comment] 2020-04-26 06:44
cool thanks!

**Comment by CodeMouse92** [comment] 2021-02-08 20:15
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue is related to our goal to migrate to Electron 8:

https://community.getmailspring.com/t/upgrade-to-electron-8/501

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-08 20:15 UTC
Labels: audit, bug, electron-soon
