### ISSUE TITLE
Feature Request: Sync contacts with Global Address List/Directory Server / LDAP

### ISSUE THREAD

**Issue by salikhov** [Foundry376/Mailspring#864] opened 2018-05-11 04:21 UTC
**Feature Request**
##### Does this feature exist in another mail client or tool you use?
This feature exists in Mozilla Thunderbird, which I have used in the past. Essentially, it is the ability to connect to an online GAL (Global Address List) which contains emails of every individual in the organization that I am a part of. These are stored on a server and accessed through a URL by the mail client. This is a guide I found on said feature for Thunderbird if it is of any help in describing it: https://kb.intermedia.net/article/34419

I use Mailspring with my university email, and it is helpful to be able to simply type in someone's name to get their email address immediately in my mail client, rather than having to go look at the online directory myself to find the correct one.

**Comment by bengotow** [comment] 2018-05-22 23:20
This would be great—I'll see if we can get this added soon.

**Comment by ccsw1** [comment] 2019-05-04 11:56
Hello,
Is a contacts plugin available for Mailspring?

**Comment by HairBear22** [comment] 2020-01-22 04:58
I'd love to bump this/check status... this would be really handy for those of us in large organizations

**Comment by CodeMouse92** [comment] 2021-01-28 02:55
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/sync-contacts-with-global-address-list-directory-server-ldap/330

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@salikhov: if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 02:55 UTC
Labels: audit, enhancement
