### ISSUE TITLE
Lost two drafts in two days, keeps on over-writing my new draft

### ISSUE THREAD

**Issue by clockworkpc** [Foundry376/Mailspring#679] opened 2018-02-10 13:21 UTC
##### Are there any related issues?

...

##### What operating system are you using?
Ubuntu 16.04

##### What version of Mailspring are you using?
1.1.3-27dcee2f

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
None.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Kolab mail, maybe.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

```
Error: Failed to execute 'setStart' on 'Range': The offset 4294967295 is larger than the node's length (37).
    at findDOMRange (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/utils/find-dom-range.js:37:5)
    at Content._this.updateSelection (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/content.js:154:46)
    at Content._this.componentDidMount (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/content.js:113:13)
    at commitLifeCycles (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:149:193)
    at b (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:158:229)
    at m (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:169:217)
    at w (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:168:413)
    at z (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:167:32)
    at u (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:165:441)
    at Object.enqueueSetState (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:108:299)
    at _class.A.setState (/snap/mailspring/167/usr/share/mailspring/resources/app.asar/node_modules/react/cjs/react.production.min.js:12:357)
    at _draftStore2.default.sessionForClientId.then.session (/src/decorators/inflates-draft-client-id.jsx:66:14)
    at <anonymous>

**Comment by clockworkpc** [comment] 2018-02-28 21:36
Any luck replicating this?

**Comment by CodeMouse92** [comment] 2021-01-22 00:33
2020 prevented much development work on Mailspring, but rest assured, development has resumed! We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. Learn more about the changes here.

@clockworkpc: Can you please confirm that this is still broken with 1.8.0, and if so, open a new Bug Report on our Discourse ? We want to be able to address this, but we need up-to-date diagnostic information to do it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-22 00:33 UTC
Labels: audit, bug, composer
