### ISSUE TITLE
Make password storage optional

### ISSUE THREAD

**Issue by outfrost** [Foundry376/Mailspring#1512] opened 2019-06-05 16:27 UTC
Continuing the problem and discussion from #681, it seems that development in Mailspring's dependencies regarding that issue has mostly stalled. I reckon something can still be done here, though.

Could you make it an option to _not_ store passwords on disk at all?

It seems that `node-keytar` relies on `libsecret` on Linux, and `libsecret` in turn relies on `gnome-keyring`, as the only full/viable existing implementation of the `org.freedesktop.secrets` DBus functionality.

For me, as a KDE Plasma user, installing `gnome-keyring`, or using any of the few workarounds that I've found for this problem, is undesirable. I would simply prefer Mailspring to _not_ store my password offline, and to only hold it in RAM while I'm logged in, for the purpose of continuous sync. FWIW, it is an option in Thunderbird.

_Originally posted by @outfrost in https://github.com/Foundry376/Mailspring/issues/681#issuecomment-497740495_

**Comment by bengotow** [comment] 2019-06-17 05:34
Hey! Hmm, technically this wouldn't be too hard really... the app essentially just reads your passwords from the keychain and hands them off to the sync workers that open the IMAP connections. I'll take a closer look and see. I think the trickiest part is that it essentially means inserting a delay where the sync process hasn't been started / given a password yet, and the app might be a little unstable in that state. Will take a look...

**Comment by CodeMouse92** [comment] 2021-02-17 23:15
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/make-password-storage-optional/675

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@outfrost: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-17 23:15 UTC
Labels: migrated, product-direction
