### ISSUE TITLE
[Enhancement] Give the focus to one email in a thread, so that [r], [a], or [f] shortcut applies to that email rather than the most recent one in the thread

### ISSUE THREAD

**Issue by palefire19** [Foundry376/Mailspring#217] opened 2017-10-20 09:57 UTC
##### Are there any related issues?

...

##### What operating system are you using?
Mac OS 10.12.6

##### What version of Mailspring are you using?
1.0.5

--

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Yes, Gmail's web interface is the one to mimic here. It has the concept of giving the focus to existing emails in a thread, so that when one of the shortcuts [r], [a], or [f] is used, it applies to that email rather than to the bottom one of the thread.

**Comment by bengotow** [comment] 2017-10-20 18:43
Yeah this would be great - right now there isn't a concept of a "focused" message in the thread but we should definitely add one!

**Comment by CodeMouse92** [comment] 2021-02-20 02:59
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/focused-message/710

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@palefire19: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-20 02:59 UTC
Labels: audit, enhancement
