### ISSUE TITLE
Move messages marked as "not spam" to Inbox instead of "All Mail"

### ISSUE THREAD

**Issue by markojurkovic** [Foundry376/Mailspring#985] opened 2018-07-19 11:26 UTC
When marking selected Gmail message(s) in the Spam folder as "not spam" by clicking the "like" button (![Like button](http://i66.tinypic.com/6ym7ew.jpg)), they should be moved to the Inbox folder instead of the All Mail folder. With the current behavior, when marking a message as "not spam", it effectively disappears from Mailspring.

##### What operating system are you using?

Ubuntu 18.04

##### What version of Mailspring are you using?

1.3.0

##### Do you have any third-party plugins installed? If so, which ones?

No third-party plugins.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Haven't had a chance to test with other email providers.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

The issue is reproducible with any message in the Spam folder of any Gmail account.

**Comment by bengotow** [comment] 2018-08-02 20:09
Good catch—I'll see if I can get this fixed in an upcoming release.

**Comment by IevgenSobko** [comment] 2019-01-11 12:17
@bengotow would it be possible to include this in one of the closest releases?
This is the really annoying issue since inception.

**Comment by CodeMouse92** [comment] 2021-02-18 23:39
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

@levgenSobko (or anyone else): Can you please confirm that this is still broken with 1.8.0, and if so, open a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-18 23:39 UTC
Labels: audit, bug
