### ISSUE TITLE
[Feature Request] Make composer recipient name warnings optional / add "don't warn me again" option

### ISSUE THREAD

**Issue by intradesign** [Foundry376/Mailspring#1201] opened 2018-10-30 13:44 UTC
I want to send mails to many different people. Sometime when I am writing mails to Christoph or Julia oder info@ starting with Hello Chris or Hi Julie oder dear Doris I am asked if I am really sure and want to send anyway.

Asking once is a nice (but unnecessary) feature. Asking once per name is too much. And asking every single time I write an email to Chris oder Julie is absolutely annoying.

Please provide an option to disable this (and other) warnings (in settings and in the warning itself like "Never warn me again for Chris" and "Never warn me againg"

**Comment by bengotow** [comment] 2018-11-03 16:35
Hey! Ahh this is a great idea. I think we should definitely make it so you can disable the warning for a particular recipient email address using a "Never again for Chris" option.

This would be a great first patch for someone interested in contributing! Right now, these warnings are built in `DraftSession::validateDraftForSending` and the code looks for common English salutations (eg: `Hey (name),`) and then checks that the name is one of the recipients. Right now, the warnings are all bundled together and displayed as a single string. So it might say "Are you sure you want to send to Ben who does not appear to be a recipient, and without a subject line?"

I think we might need to break the naming warnings out into a separate `validateDraftRecipients` step which gets to display it's own separate dialog box. Then we could add the buttons to ignore / disable the warning for that email. We could keep the blacklist in localstorage.

Happy to help if someone wants to try tackling this!

**Comment by CodeMouse92** [comment] 2021-02-15 21:07
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/make-composer-recipient-name-warnings-optional-add-dont-warn-me-again-option/630

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@intradesign: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-15 21:07 UTC
Labels: audit, enhancement, good first issue
