### ISSUE TITLE
Emails with same To/From address disappear from Inbox

### ISSUE THREAD

**Issue by Rakantor** [Foundry376/Mailspring#1730] opened 2019-12-03 16:47 UTC
All contact form entries on my WP website are forwarded to my mail account. The address for sending and receiving the emails is identical in this case. 
After receiving a new mail, it is visible in the Inbox for a few moments and then disappears. 
The email sporadically pops up in the list for a second and then vanishes again. 
It is still in the Inbox on the server and is correctly shown by other clients, but not displayed by Mailspring.

##### What operating system are you using?
Linux Mint 19.2 Cinnamon

##### What version of Mailspring are you using?
1.7.2

--

**Bug?**

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No.

**Comment by thosgood** [comment] 2020-04-22 23:46
I've also been having this problem with email reminders I send to myself, but hadn't realised that it might be specifically because the send/receive addresses are the same. But this seems to explain why these ones in particular never seem to show up.

**Comment by wadih** [comment] 2020-05-17 22:57
I just came across this same case. In my case, it was an email I sent to myself and to another mailbox which forwards to myself. I received it, and a few seconds later, it disappeared. I have the same mailbox connected with Outlook, it was appearing in Outlook on another computer, but not in Mailspring. I'm using Mailspring on Ubuntu 20.04.

**Comment by CodeMouse92** [comment] 2021-02-12 23:32
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/emails-with-same-to-from-address-disappear-from-inbox/597

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@Rakantor @thosgood @wadih: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-12 23:32 UTC
Labels: audit
