### ISSUE TITLE
Feature Request: Combining messages action into one

### ISSUE THREAD

**Issue by b00f** [Foundry376/Mailspring#1999] opened 2020-05-21 15:52 UTC
**Is your feature request related to a problem? Please describe.**
No. It can be a problem if a message has more actions like stared/mark as important, etc. It takes more space in left area. like here:
![Screenshot from 2020-05-21 23-33-15](https://user-images.githubusercontent.com/8073510/82577517-a8b85b80-9bbd-11ea-93f5-425c72e49935.png)

**Describe the solution you'd like**
Combining all action into one. `Hover` event (when user holds mouse over it), opens a small popup dialog to apply actions for a message. like:
![1](https://user-images.githubusercontent.com/8073510/82577603-cdacce80-9bbd-11ea-9265-cc8e5fd82efe.png)
![2](https://user-images.githubusercontent.com/8073510/82577601-cd143800-9bbd-11ea-8fd2-08b0b6f96997.png)
The black box is a popup dialog with actions like star/ /mark as important, etc.
sorry for my bad Photoshop!

**Comment by CodeMouse92** [comment] 2021-02-03 18:14
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We're going to incorporate this idea into a larger feature request already migrated to Discourse:

https://community.getmailspring.com/t/customizable-swipe-button-actions/444

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-03 18:14 UTC
Labels: audit, enhancement
