### ISSUE TITLE
Bug: config.json easily gets corrupted on system crash

### ISSUE THREAD

**Issue by chakflying** [Foundry376/Mailspring#1993] opened 2020-05-20 08:27 UTC
**Describe the bug**
My system is not stable and sometimes would crash and reboot. I noticed that Mailspring easily gets broken, saying that it failed to load config.json. The file when opened by a text editor shows a bunch of unknown characters, obviously corrupted.

**To Reproduce**
1. Have mailspring running in the background
2. Trigger system crash, e.g. by cutting power
3. See config.json unable to load message

![image](https://user-images.githubusercontent.com/3271800/82423226-18432380-9ab6-11ea-8dbc-36dfeb150c25.png)

**Expected behavior**
Maybe the app should write to config.json less often?

**Setup: (please complete the following information):**
 - OS: Windows 10 1909
 - Mailspring Version: 1.7.6 

**Additional context** 
Having to setup mailspring again is quite annoyiong as all the accounts need to be linked again.

**Comment by linasdev** [comment] 2020-11-25 18:59
This happens to me also. My laptop's battery is dead and when external power gets cut it immediately powers off. The config file is completely empty on reboot in my case. This happens every time.

**Comment by CodeMouse92** [comment] 2021-01-29 21:52
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/regression-avoid-corruption-of-config-json-on-unexpected-shutdown/386

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-29 21:52 UTC
Labels: audit, bug
