### ISSUE TITLE
[Feature Request] Read-only accounts / Make SMTP optional

### ISSUE THREAD

**Issue by m0n1s** [Foundry376/Mailspring#23] opened 2017-10-04 19:22 UTC
Would it be possible to make the SMTP account details optional. 
So we can create a receive-only account ?

**Comment by bengotow** [comment] 2017-10-04 19:54
Hey @m0n1s  - there aren't currently plans to support this — could you elaborate on your email setup? Are there mail providers that offer read-only IMAP accounts without SMTP? Are you using an IMAP server you deployed yourself?

**Comment by nmindz** [comment] 2017-10-04 20:06
Well I have an specific use case where that would fit, @bengotow. My university IT department decided, instead of improving availability of our email service, they chose to block every and all SMTP auth attempts that do not come from _localhost_ (on their end.).

They did so in an attempt to block spam abuse in only letting their own webmail client authenticate and send emails. While effective, that's a horribly handicapped solution IMHO. However, that's how they work. That has also been a stepping stone in using email clients since every client will try/force to SMTP auth and others even won't add/work with a read only account.

While somewhat uncommon (public/free providers don't work in such way, only private/paid ones with specific scenarios.) it is a valid point and it should probably be considered a feature in Mailspring. That would make it awesome for **all** my email.

**Comment by m0n1s** [comment] 2017-10-05 08:53
Hello @bengotow,
I would like to use mailspring as my all-in-one mailclient but my company's  *info@....* account is, just like @nmindz 's account, restricted to receiving-only. 
For now it is totally ok if there would be a "Just ignore the not working SMTP-Settings"-Checkbox even if mailspring will throw some error-modals :sweat_smile:

**Comment by zeph** [comment] 2020-03-03 10:39
@bengotow in my case I just wanna have an imap archive... 
  no SMTP for such account... as Evolution provides

**Comment by Markeli** [comment] 2020-09-18 11:53
I'm also intersted in this feature. We have an EMail account for alert messages from our production environment. And it's a receive-only.

**Comment by CodeMouse92** [comment] 2021-01-21 00:21
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/read-only-accounts-make-smtp-optional/134

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

OP: if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-21 00:21 UTC
Labels: audit, enhancement
