### ISSUE TITLE
Image resizing **Feature Request**

### ISSUE THREAD

**Issue by grandixximo** [Foundry376/Mailspring#1626] opened 2019-09-02 08:48 UTC
**Feature Request**

##### Does this feature exist in another mail client or tool you use?

Most e-mail clients i have seen have a way to resize the images you import inside your composing window, you should be able to grab the corners of a picture and drag it to make the picture smaller while composing an email.
I sometimes make step by step emails with lots of images for visual reference, and it would be nice to just be able to resize the picture I import inside Mailspring without relying on other applications to do it.

**Comment by bengotow** [comment] 2019-10-08 21:29
Hey @grandixximo this is a great idea! I'll see if we can get this implemented sometime soon.

**Comment by grandixximo** [comment] 2019-10-09 03:18
Awesome, thank you!
If you could have a look at the bug with windows minimize to tray where everything becomes unresponsive, thanks!

**Comment by iamscott** [comment] 2020-05-07 13:39
+1

**Comment by mokafolio** [comment] 2020-10-04 20:08
+1

**Comment by woodsadrian** [comment] 2020-10-26 14:06
YES! Would love this function. Essential for everyday mails.
Any update since @bengotow message last year? Thanks!

**Comment by MyDimeIsUp** [comment] 2020-11-25 01:24
bump I would really like this

**Comment by aalonsobar** [comment] 2021-02-20 18:15
> Hey @grandixximo this is a great idea! I'll see if we can get this implemented sometime soon.

Hello. How is the resizing images feacture?

**Comment by CodeMouse92** [comment] 2021-02-22 21:39
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/resizing-image-in-composer/729

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@grandixximo: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-22 21:39 UTC
Labels: audit, enhancement
