### ISSUE TITLE
[Feature Request] Mail merge

### ISSUE THREAD

**Issue by heliostatic** [Foundry376/Mailspring#174] opened 2017-10-16 14:35 UTC
##### What operating system are you using?
Mac OS 10.12.6

##### What version of Mailspring are you using?
1.0.4

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Yes, it existed in Nylas N1 and exists in Polymail as "Campaigns", as well as Gmail via extensions like MixMax.

**Comment by smacking** [comment] 2018-02-06 12:55
Yes please! @bengotow this is a winner!

**Comment by simonv3** [comment] 2018-08-28 17:00
What would be required to make this work?

**Comment by AbdulHannanS** [comment] 2019-02-13 04:14
Has this feature been added?
Please let me know.

**Comment by kensheldon** [comment] 2019-12-04 23:34
any news?

**Comment by Mike97M** [comment] 2020-09-04 11:06
Any updates about this?

**Comment by CodeMouse92** [comment] 2021-01-29 22:16
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mail-merge-with-templates/387

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-29 22:16 UTC
Labels: audit
