### ISSUE TITLE
Bug: Chinese email subject is displayed abnormally

### ISSUE THREAD

**Issue by qiujiangkun** [Foundry376/Mailspring#2166] opened 2020-10-12 10:12 UTC
**Describe the bug**
Chinese email subject is displayed abnormally

**To Reproduce**
1. login QQ email
2. See the error: Chinese email subject is displayed abnormally

**Expected behavior**
Display normally
**Screenshots**
![image](https://user-images.githubusercontent.com/33482468/95734523-25a3b900-0cb6-11eb-96c9-4d29dc021944.png)

**Setup: (please complete the following information):**
```text

 ██████████████████  ████████     jack@jack-pc
 ██████████████████  ████████     OS: Manjaro 20.1.1 Mikah
 ██████████████████  ████████     Kernel: x86_64 Linux 5.8.11-1-MANJARO
 ██████████████████  ████████     Uptime: 3d 19h 10m
 ████████            ████████     Packages: 1738
 ████████  ████████  ████████     Shell: zsh 5.8
 ████████  ████████  ████████     Resolution: 3840x2160
 ████████  ████████  ████████     DE: Xfce4
 ████████  ████████  ████████     WM: Xfwm4
 ████████  ████████  ████████     WM Theme: Matcha-sea
 ████████  ████████  ████████     GTK Theme: Matcha-sea [GTK2]
 ████████  ████████  ████████     Icon Theme: Papirus-Maia
 ████████  ████████  ████████     Font: Noto Sans 12
 ████████  ████████  ████████     Disk: 565G / 2.1T (29%)
                                  CPU: AMD Ryzen 7 3700X 8-Core @ 16x 3.6GHz
                                  GPU: GeForce GTX 1660
                                  RAM: 8039MiB / 16019MiB
```
 - Mailspring Version: ex: 1.7.8 (found in the app's menu)

**Additional context** 
My locale is `C`

**Comment by ikelvinwoo** [comment] 2020-10-16 09:08
I am experiencing the same issue :(

**Comment by wusy1209** [comment] 2020-10-31 12:00
I am experiencing the same issue :(

**Comment by CodeMouse92** [comment] 2021-02-23 22:01
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/chinese-email-subject-is-displayed-abnormally/744

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@qiujiangkun: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

@qiujiangkun @ikelvinwoo @danger812 Also, could someone respond to the Discourse thread with the additional requested info? We don't have enough information to diagnose or fix this yet.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-23 22:01 UTC
Labels: audit, bug
