### ISSUE TITLE
duplicate in sent folder - outlook.com

### ISSUE THREAD

**Issue by weissi29** [Foundry376/Mailspring#937] opened 2018-06-15 13:30 UTC
##### Are there any related issues?
No

##### What operating system are you using?
MacOS 10.13.5

##### What version of Mailspring are you using?
Version 1.2.2 (1.2.2) 96fb3a99

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Outlook.com

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Everytime I send a mail via outlook.com, i have this email twice in my send folder.
In other apps you can set the option - not to save a sent email in sent folder. This would be necessary here.

![bildschirmfoto 2018-06-15 um 15 28 46](https://user-images.githubusercontent.com/22611162/41470426-d3dbbc38-70b0-11e8-8b0c-d47da10d0166.png)
![bildschirmfoto 2018-06-15 um 15 30 10](https://user-images.githubusercontent.com/22611162/41470488-03b00a68-70b1-11e8-9e42-5f71b7649a66.png)

**Comment by conlaoch1** [comment] 2018-06-15 14:20
Having the same error here. Fix would be appreciated. Thanks!

**Comment by qlfwyyd** [comment] 2018-06-20 05:00
I seem to also be sending double emails on some occasions, though not on others. I'm on Gmail though. Not sure what's going on here.

**Comment by Kiailandi** [comment] 2018-07-31 21:30
Same issue here, this makes mailspring useless because it will spam double emails each time.
I would suggest an option, as Thunderbird offers, to disable the duplication of sent emails.

**Comment by weissi29** [comment] 2018-08-21 10:45
Any news on this??? That reaaaaaaalllllyy sucks...

**Comment by conlaoch1** [comment] 2018-08-21 10:50
Still waiting for this fix.. :(

**Comment by TizeN85** [comment] 2018-09-11 10:38
Same here... Any news on this issue? It's really anoying, I would'nt buy a subscription if this is not corrected :/

**Comment by Emonadeo** [comment] 2018-09-24 12:06
This is a major bug and prevents me from using it until it's fixed.

**Comment by berkaydedeoglu** [comment] 2018-10-14 11:06
Is fixing it really hard?

**Comment by ChengweiWang0** [comment] 2018-10-15 16:41
same here, please fix...

**Comment by ChuangTseu** [comment] 2018-10-18 11:28
For those worried that it might actually spam a double email to the receiver, I've been testing this with a friend, and the duplicate seems to be strictly _sender-side_.

I'd still like to see this fixed of course, but at least we can stay assured that it won't really double spam the receiver each time we reply through Mailspring :)

**Comment by nd983zhn** [comment] 2018-10-19 13:57
could this be related to #1086?
using office365 the issue is recipient-side (in fact I do not have multiple copies in sent folders), reply-all results in 2 or more copies of the same email to one or more recipients.
happens only with office365 accounts and reply-all. 
My tests showed independence on send later feature, happens with or without it.
Happens on multiple different OS.

version v1.4.2-f587b7b7, no plugins installed

this issue prevents all office365 users from using Mailspring as nobody wants to spam his recipients, right?

**Comment by mnylen** [comment] 2018-11-15 13:59
Can confirm that the emails seem to be sent only once, even though there are duplicate emails in the sent folder. Tested by sending from Gsuite to another Gsuite account. Annoying nevertheless.

**Comment by m7rcelo** [comment] 2018-12-14 12:00
Still waiting for it to be fixed.

**Comment by watgrad** [comment] 2019-01-03 00:43
This has been frustrating me as well. (Win 10, ver 1.5.4 of MailSpring).
I was also getting duplicate emails in the sent folder for outlook accounts (sending to multiple addressees).  
When I disabled the "After sending enable undo for: ___ sec" this problem went away- no more duplicates - (at least for now).

**Comment by UnixMonky** [comment] 2019-03-14 13:52
This is still an issue as of March 14th 2019. I'm seeing this on my Office365 email account.

**Comment by phnx47** [comment] 2019-03-14 23:19
I have some problem:
First email has: ```Message-ID: <HE1PR06MB3865B5C499DB0DA1D549B62B8F4B0@HE1PR06MB3865.eurprd06.prod.outlook.com>```
Second email has: ```Message-ID: <03B19327-0827-46F1-BDA9-F738F13A5A2E@getmailspring.com>```

Duplicated in Mailspring server

**Comment by bengotow** [comment] 2019-03-22 00:25
Hey folks—this should fixed in the latest release. Let me know if you still see this in 1.6.0.

**Comment by TizeN85** [comment] 2019-03-24 13:01
Yes it seems ok now for me :) Thanks !

**Comment by giswqs** [comment] 2019-04-12 23:16
Hello, I am using Mailspring 1.6.1 on Manjaro Linux. I have an issue with my Office 365 account. If I send emails using Mailspring, I can see duplicates in the Send Folder when I log into https://outlook.office365.com. However, the Sent Mail folder in Mailspring is working properly without duplicates. Please help. Thanks.

**Comment by bullsei** [comment] 2019-06-03 23:59
Same Problem here. I actually switched today from Thunderbird to Mailspring because this was annoying me and i thought this problem is specifig to Thunderbird since i did some testing and when sending mails using the outlook website i didn't get duplicates in sent folder. But apparently now with Mailspring i have the same problem. Maybe this problem is caused by some piece of software thats used by both Thunderbird and Mailspring?  I am using latest Manjaro 18.0.4 (Illyria) with a normal outlook account with Mailspring 1.6.1

**Comment by Kiailandi** [comment] 2019-06-08 09:50
@bullsei in thunderbird you have the option to disable it, just go to the account settings, "copies & folders" and disable the "place a copy in" "sent folder" option.

**Comment by UnixMonky** [comment] 2019-06-10 11:28
I've noticed in further use that this happens when I'm replying to a distro that I'm a member of. Normal replies to people/groups I'm not a member of don't seem to have the duplication, it's only when I'm in a group on the to/cc fields that I get the duplicate email.

Logically I understand why this occurs, but it doesn't happen with O365 web client, so they may be doing some fancy checking for deduplication.

**Comment by linean** [comment] 2019-10-21 06:01
This is still an issue on 1.7.1 - only happens for outlook. I hope there will be a fix soon.

**Comment by kmancobhc** [comment] 2019-10-22 19:17
Happens with Outlook on 1.7.2. Can't use until this is fixed.

**Comment by toboko** [comment] 2019-10-24 09:11
It looks like isn't a problem about Hotmail or other providers but is about IMAP.
The mail app logs the sent item, the IMAP service shows it sent and you get 2 mail.

**To fix it**, it should be necessary to have check box where we can set to save/un-save a copy of sent items in the sent folder.

**Comment by vb543** [comment] 2020-01-27 18:28
Any updates here? Just trying Mailspring out for the first time and came across this same issue with my Outlook.com email address.

**Comment by yidingww** [comment] 2020-02-14 02:50
Awaiting to be fixed!! Same issue here for **Ubuntu 18.04 Mailspring 1.7.2-4522b259**

**Comment by OctopusProteins** [comment] 2020-03-25 14:32
@bengotow This is still an issue in 1.7.4-d54ff730. Mailspring should have a toggle to either save or not save a copy of sent emails to the sent folder, similar to outlook.

**Comment by DevZky** [comment] 2020-05-28 15:02
Same Problem still remains.
**Mailspring: 1.7.8 / OS: Ubuntu 20.04 / Mail provider: outlook.com**
Please fix. I think a checkbox to decide wether mails are saved in sent folder or not would be the best solution.

**Comment by WoutDebacker** [comment] 2020-07-10 06:36
I'm also having the same problem
**Mailspring: 1.7. 8/ OS: Windows 10 Pro / Mail provider: outlook.com**

**Comment by ianpan870102** [comment] 2020-08-10 14:37
I'm having the **exact same** problem. I'm on **Windows 10** with and **Outlook** account using **Mailspring**.
This does not happen when I'm using my Gmail account in Mailspring to send email -- it only happens when I switch to my Outlook account for sending.
As others have mentioned, the duplicate email issue seems to happen only on the sender's side! That is, the receiver will still receive one and only one email from you the whole time.

**Comment by darthvinyll** [comment] 2020-09-09 17:24
As per above, latest ubuntu & current mailspring app version...

@bengotow Please have a look at the suggestion from @OctopusProteins above

**Comment by Haini** [comment] 2020-09-16 08:36
Same Problem, Mailspring 1.7.8, Ubuntu 20.04.1 LTS, Outlook Mail Account.

**Comment by Vicvitoria** [comment] 2020-11-11 09:51
same problem in windows 10 and manjaro KDE, mailspring 1.7.8-1. Outlook mail accounts

**Comment by CodeMouse92** [comment] 2021-01-28 02:35
Thank you for reporting this. 2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/duplication-of-sent-mail/275

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 02:35 UTC
Labels: audit
