### ISSUE TITLE
When Opened in Gmail registers as opened in mailspring

### ISSUE THREAD

**Issue by joreb** [Foundry376/Mailspring#812] opened 2018-04-06 18:33 UTC
##### Are there any related issues?

...

##### What operating system are you using?
Ubuntu 16.04

##### What version of Mailspring are you using?
...
1.2.1-7e7447b6
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...
none
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...
If i open the mail in my gmail account via browser it registers as opened in mailspring
--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by CodeMouse92** [comment] 2021-02-03 02:53
This is the intended behavior, and is standard for all email clients. When a message is marked as read in one client, it is marked as read on the email server, and thereby seen as read by all other clients.

---

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-03 02:53 UTC
Labels: rejected
