### ISSUE TITLE
New mail not notified when rule is applied

### ISSUE THREAD

**Issue by pablosolar** [Foundry376/Mailspring#1316] opened 2019-01-10 11:30 UTC
Hi all!

I've got a rule defined that moves a mail to one subfolder based on _Subject_ name and _From_ name. When this rule is applied, the new mail is moved correctly to the subfolder but no notification (neither sound) is shown so I cannot know if I received the email or not. Why is this happening?

Thanks in advance!

**Comment by bengotow** [comment] 2019-03-25 00:50
Hey! Right now, Mailspring only plays notifications / sounds, etc. for new emails that arrive in your inbox. If a message arrives and goes straight to a folder (either via an external mail rule or one in Mailspring) there isn't a notification. I think this is consistent with other apps like Mail.app, but it might be worth revisiting?

**Comment by SarkasticnaCufta** [comment] 2019-07-03 09:42
The same issue was reported here: #667

Is there any chance to add notifications when rules are in use which move mails to other labels/folders? It's really bad that I have to have rules set to only apply labels to mails and then manually sort them into labels/folders. For 100+ mails daily that is a chore, and I can assume that someone who is getting more is having really bad time with that practice.

Simply leaving everything in inbox is in my opinion not an option.

**Comment by CodeMouse92** [comment] 2021-01-28 01:45
Thank you for reporting this. 2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/notifications-on-non-inbox-folders/323

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 01:45 UTC
Labels: audit, product-direction
