### ISSUE TITLE
Feature Request - Image Viewing improvements

### ISSUE THREAD

**Issue by Morgul** [Foundry376/Mailspring#923] opened 2018-06-08 14:05 UTC
##### Are there any related issues?

- #234 Feature Request - Built in attachment viewer
- #853 Mailspring open images in Web Browser

##### What operating system are you using?

Linux Mint 18.3

##### What version of Mailspring are you using?

I'm using the snap, which currently is updated to `1.2.2-96fb3a99`.

---

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?

Yes, Slack has an amazing way of handling inline imaged: Every image can be opened in it's own window (which is good enough for my needs), but also has an overlay with zoom controls on it.

---

What I'm looking for is an improvement to how inline images are handled. I am using Mailspring at work (beats Outlook under wine, let me tell you) and I get dozens of screenshots as bug reports for our internal applications. They say a picture's worth a thousand words, so here's an example of my problem:

![mailspring-image-issue](https://user-images.githubusercontent.com/770655/41161901-de0cc04c-6af9-11e8-9995-257ddd8bd537.png)

Those screenshots are proper size... if I right click on them, save them. Even GitHub lets you click on the images to open them in another window, and that's more than good enough. I'd love to see something like Slack's image viewer build in, but that might fall more under #234. If nothing else, a context menu option to open in the default image viewer would work, too... but at this point I'll take anything.

I adore Mailspring; it's the best email client for linux, period. While it's tedious to rightclick and save images just to be able to read the text in them, Mailspring is better in every other way enough that I'll suffer through. ;)

**Comment by CodeMouse92** [comment] 2021-02-04 20:42
It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

P.S. Duplicate of #234

**Closed by CodeMouse92** 2021-02-04 20:42 UTC
Labels: audit
