### ISSUE TITLE
Bug: "Write a plain text reply"

### ISSUE THREAD

**Issue by pszucs** [Foundry376/Mailspring#1827] opened 2020-02-28 10:44 UTC
**Describe the bug**
Since version 1.7.4 when I'm about to respond to an email or compose a new one, sometimes I'm only able to do that in plain text mode. The messages I'm trying to respond to are html emails. This worked fine in version 1.7.4.

**To Reproduce**
1. Go to Inbox
2. Click on one of the emails
3. Scroll down to the "Reply" box at the bottom of the email
4. It says "Write a plain text reply"

**Expected behavior**
It should say "Write a reply" and the editor (bold, italic, etc) should appear.

**Screenshots**
![Screenshot from 2020-02-28 10-35-23](https://user-images.githubusercontent.com/2471046/75541689-457fb880-5a16-11ea-8cbf-81fdddde7d18.png)

**Setup: (please complete the following information):**
 - OS: Elementary OS
 - OS Version: 5.1.2. Hera
 - Mailspring Version: 1.7.4.

**Additional context** 
This doesn't seem to be a permanent issue. Sometimes it says "Write a reply" and the html editor (bold, italic, etc.) appears, sometimes it says "Write a plain text reply" for no apparent reason.

Sometimes when I restart the app it starts working again. For the same email, before restarting the app it said "Write a plain text reply", after restart it says "Write a reply" and the html editor appears. Restarting the app doesn't always help. Sometimes I leave the app open, come back after 10 minutes and the text changes to "Write a reply".

**Comment by nolteb** [comment] 2020-03-01 01:58
I can confirm that I have this same issue.

**Comment by angusscown** [comment] 2020-03-01 22:59
Agree, this has started occurring since 1.7.4.  I haven't changed my process, when I hit reply it often seams to default to txt, not html.

**Comment by Rendse** [comment] 2020-03-02 09:55
Also having the issue. It's unclear what causes this, I close/open the application and sometimes it replies as html.
@angusscown Double clicking the message and clicking reply seems to work more realiably. Thank you.

**Comment by pszucs** [comment] 2020-03-02 11:02
I've looked at the source code and it seems to me it's something to do with the "Alt" key.

By default, if you press the "Alt" key and click on the reply box, it will load the plain text reply functionality.

I've just tried pressing the "Alt" key twice, and it switched back to "Write a reply".

**Comment by palefire19** [comment] 2020-03-02 11:27
+1 on this.

In general, the plain text implementation is pretty clunky and in many cases has forced me into a plain text compose that I didn't want. Suggested improvement could be to ad a preference item to "never compose in plain text"

**Comment by chemicalkosek** [comment] 2020-03-02 11:59
I can confirm this issue also

**Comment by artsgirl** [comment] 2020-03-03 19:35
+1 here

This is incredibly frustrating, as my annual renewal payment for Mailspring was just processed and then this upgrade and bug began. It might seem like a small thing, but it happens dozens of times a day and every time I have to close the app and re-open it (sometimes several times), and sometimes I must rebuild the cache as well before it will work properly.

**Comment by jrmejiaa** [comment] 2020-03-05 02:08
:+1: In this issue

It is constant when this happens, however, I have found some specific cases when that happens and it is when it is trying to connect again with the account. I don't know why, but when my machine has made this process I have the "Write a plain text replay" message. When this happens I have to close the app and re-open (sometimes several times) but most of the time it fix when I press `F5` to synchronize my email accounts again.

I hope you can fix, it is small but it is true that it is really annoying when you are pretty happy with the option that gives Mailspring to decorate your messages (Loves the signature and code feature btw :heart:)

**Comment by Rendse** [comment] 2020-03-05 12:45
As @pszucs wrote, there is a pretty simple workaround.

"HTML <--> Plain text" is toggled with the Alt key. Once you press Alt + tab, Mailspring receives the keyDown event, but not the keyUp event. So it is stuck in Plain text reply mode.

**Clicking Alt** with Mailspring in focus should perform the keyUp event, and the text will change back from "Write a plain text reply..." to "Write a text reply...".

**Comment by artsgirl** [comment] 2020-03-05 13:04
Unfortunately @Rendse, that is not exactly true. Sometimes I am able to toggle it with alt, but more often I have to hold down the alt key while I click reply (which is still in plain text), close and delete that reply, and **then** when I get back to the main window I have the "Write a reply" option available instead of the plain text option. Doing it this way also introduces the [mail persists in emptied trash bug](https://github.com/Foundry376/Mailspring/issues/220), which is only resolved through a cache reset, so there's a whole cascade of tiny issues here and it becomes death by a thousand cuts to productivity.

**Comment by nolteb** [comment] 2020-03-05 15:15
I've switched to thunderbird until this and the performance issues are sorted out. I had to create a command that would kill mailspring's pid if I am running on battery and haven't used it in a few minutes, because of CPU utilization killing my battery. This reply being in plaintext thing is the last straw.

**Comment by macrophone** [comment] 2020-03-06 12:48
Same problem. 
Going into Preferences > Clear cache exits from the plain text mode. 
Opening a reply box by clicking on an email in chromium puts again mailspring in plain text reply mode.

**Comment by hariscodes** [comment] 2020-03-14 01:44
I'm also having this issue on Ubuntu 18.04. When I hit ctrl-alt up to move between workspaces It gets stuck on plain text reply. When I move back to that workspace I can to hit either ctrl or alt and it fixes the issue. Kinda annoying.

**Comment by ipa1981** [comment] 2020-03-21 09:00
If you have set Mailspring as a default email composer, it makes things even more problematic. The composer opens in a random state, and I need to be lucky to get default HTML editor. There is even not switch between HTML <> Plain text, so I have to close the composer, go back to Mailspring, play with Alt key, then go back and click on an email link in another app.

My suggestion:
1. Make a Setting to enable/disable global support for plain text at all. I don't believe there is a huge share of plain text users nowadays. It's just a share of specific users who can enable this if they want.
2. Create a switch in Composer (HTML <> Plain), if the setting mentioned above is enabled.
3. Unbind this from Alt key. It's too frequently used key.

**Comment by bengotow** [comment] 2020-04-26 06:49
Hey folks! Sorry for the delay—I'm not sure how I missed this but it's a dup of 1894 and was fixed in the 1.7.6 release last week. I think we'll switch this to an in-editor option fairly soon, the "hold alt for plaintext" was sort of a stopgap to get us there and caused more problems than expected because 1) the alt key state is difficult to track accurately due to the app being backgrounded, etc. and 2) the alt key is used a lot more on Windows / Linux than it is on macOS (where I personally use Mailspring). 

Thanks for all the constructive feedback, I appreciate it! Stay tuned for more improvements on this front—

**Closed by bengotow** 2020-04-26 06:49 UTC
Labels: bug
