### ISSUE TITLE
Feature Request: Match Window Controls side to OS settings when using Custom Window Frame on Linux

### ISSUE THREAD

**Issue by fcastilloec** [Foundry376/Mailspring#983] opened 2018-07-18 19:37 UTC
##### Are there any related issues?
The closest I found is issue #142 
##### What operating system are you using?
Ubuntu 18.04
##### What version of Mailspring are you using?
1.3.0

There was some discussion regarding the Window Controls on issue #142 but the end focus was the implementation of the Right-hand hamburger menu. I would like to see a way to match my OS's settings regarding where the window controls buttons should be placed when using the Custom Window Frame. At the very least, I'd like to see a setting where I can move those buttons to either side.
Some alternatives/solutions could be:
- New setting `Default Window Controls and Right-hand Menu`.
- When selecting `Custom Window Frame and Right-hand Menu` have a greyed/invisible setting become available that lets me choose the side where the window controls should be placed.
- Automatically match the side where the window controls should be based on my OS settings when `Custom Window Frame and Right-hand Menu`  is used

**Comment by bengotow** [comment] 2018-08-02 20:13
Hey! This seems like a good enhancement - do you know if there's an API / shell command for reading the relevant OS setting?

**Comment by fcastilloec** [comment] 2018-08-03 01:48
@bengotow Yes, there is, using `dconf` https://developer.gnome.org/dconf/unstable/dconf-tool.html
By using the following command `dconf read /org/gnome/desktop/wm/preferences/button-layout` you will get the user preferences which can be something likes this:
```
:minimize,maximize,close
```
where the `:` specifies if the buttons are placed to the left or to the right of the window. In the previous example, they're on the right side of the window. The rest is pretty self-explanatory.
The only caveat is that the `dconf read` command will not output anything if the default setting is in place (the default setting for Ubuntu 18.04 is the above example), only if the user has modified them. The command `dconf read -d` should display the deafult but on my system that's not working and I found this issue https://github.com/ansible/ansible/issues/35659#issuecomment-363458012 that says the `-d` option doesn't work either.

You can also use the variable `$XDG_CURRENT_DESKTOP` which will tell you if you're using Gnome (or any other one) and then use the defaults for that, and just compile a list of the defaults for other (i.e. KDE, XFCE, LXQT, GNOME, Unity, etc.)

Hopefully this info was helpful and it was an starting point. I'll see if I can check how other software handle this, and if I find anything interesting I'll report back.

**Comment by ferlanero** [comment] 2018-09-18 22:54
Is there any news regarding this topic? It will be very useful to integrate my [Material Adapted theme for Mailspring email client](https://github.com/ferlanero/mailspring-material-adapted) into Adapta GTK Theme for Gnome 3.x

Thanks!

**Comment by fbruetting** [comment] 2019-02-17 22:20
With Webview there exists an abstraction layer which not only lets Mailspring get rid of Electron but seems to also handle CSD. Here’s some information:

https://www.phoronix.com/scan.php?page=news_item&px=HTML5-Golang-Desktop-Apps&utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+Phoronix+%28Phoronix%29

**Comment by fcastilloec** [comment] 2019-03-21 00:15
@bengotow It's been a while since I posted here but there's a better way to reliably get the button layout for any Linux OS: `gsettings get org.gnome.desktop.wm.preferences button-layout`
I've tested it on many different distros and it works in all.

These are the strings that are displayed: `minimize`, `maximize`, `close` and `appmenu`; also `:` for separating left and right. Not all of them are used by all distros, except for `close` which from my experience it's always shown. The only rule I know is that if `appmenu` is not shown, it should be displayed opposite to `close`, but I'm not 100% sure about that.

I'll try to see if I can submit a PR for this, but if anybody else can take a look at this, that'll be great

**Comment by fcastilloec** [comment] 2019-03-21 04:35
I started to look at the code, but I'm way over my head here. Here's what's I've found out so other people can take a look and try to implement this:
I did find that [app/src/sheet-toolbar.tsx](https://github.com/Foundry376/Mailspring/blob/master/app/src/sheet-toolbar.tsx) is responsible for deciding where to place the buttons. I think an additional variable could be added to decide for Linux and its button placement. I just don't know how/where the config options are read/written so that the `gsettings` command can be executed and then pass this variable to [app/src/sheet-toolbar.tsx](https://github.com/Foundry376/Mailspring/blob/master/app/src/sheet-toolbar.tsx), telling it where to put the buttons.
Also, [#L157-159](https://github.com/Foundry376/Mailspring/blob/master/app/src/sheet-toolbar.tsx#L157-L159) can take into consideration the order of the buttons passed by`gsettings` if wanted, and even render only the buttons specified by the distro outputted by the same `gsettings` command. Some distros only like to have a `close` button and nothing else.

**Comment by CodeMouse92** [comment] 2021-02-13 23:43
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/match-window-controls-side-to-os-settings-when-using-custom-window-frame-on-linux/611

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@ferlanero: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-13 23:43 UTC
Labels: audit, enhancement, good first issue
