### ISSUE TITLE
badge only shows unread count for 1 email account

### ISSUE THREAD

**Issue by tmmttm** [Foundry376/Mailspring#1736] opened 2019-12-13 02:51 UTC
##### What operating system are you using?

MacOS 10.15.1

##### What version of Mailspring are you using?
(eg: 1.6.3 or 1.7.0 - this is shown in Mailspring's main menu.)

1.7.2

**Bug?**
I have both my exchange and gmail accounts on mailspring, but only exchange unread emails will show up on the badge on dock. 

##### Is this an email sync or connection issue?
no
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
gmail
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

no

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

no

**Comment by bengotow** [comment] 2020-02-17 15:55
Hey! This is a super old behavior of Mailspring that I think we need to change - it only shows the unread count on the badge icon of the account you're currently viewing. To see the badge count for all your mailboxes, you need to be using Mailspring in the unified inbox view.

I'll see if we can improve this behavior soon, I think there was a reason it worked this way back when the app was Nylas Mail, but there's no reason for it now.

**Comment by mohegan** [comment] 2020-05-06 19:11
Same things with Ubuntu 20.04.

**Comment by krasi-georgiev** [comment] 2020-06-22 12:42
same think on Kubuntu 20.04 and the "Icons only task manager" it shows the unread count only for the currently selected account.

**Comment by CodeMouse92** [comment] 2021-02-26 17:37
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/badge-only-shows-unread-count-for-1-email-account/831

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@tmmttm: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-26 17:37 UTC
Labels: audit, enhancement, product-direction
