### ISSUE TITLE
Calendar event crashes mailspring

### ISSUE THREAD

**Issue by patrickheeney** [Foundry376/Mailspring#402] opened 2017-12-05 16:23 UTC
##### Are there any related issues?
...

##### What operating system are you using?
Mac OS 10.13.1

##### What version of Mailspring are you using?
1.0.9

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail?

##### Is the issue reproducible with a particular attachment, message, signature, etc?

I received a calendar event (ics file) via email. Gmail doesn't allow you to download the file since it inlines it. However in mailspring I see this, and this is what happens:

![screen shot 2017-12-05 at 9 16 38 am](https://user-images.githubusercontent.com/1407228/33617766-de29abbe-d99d-11e7-829d-36de72fd6331.png)

![screen shot 2017-12-05 at 9 14 57 am](https://user-images.githubusercontent.com/1407228/33617768-dff16f86-d99d-11e7-99d8-21856b3841d4.png)

![screen shot 2017-12-05 at 9 14 50 am](https://user-images.githubusercontent.com/1407228/33617771-e1cccdc8-d99d-11e7-89f0-b7f7f97480d3.png)

**Comment by bengotow** [comment] 2017-12-11 19:02
Hey! Thanks for reporting this - will investigate and see what's going on. Looks like we need to write the attachment to disk and it's not working for some reason.

I have a hunch that that "Mailspring Not Responding" dialog appears because the "Download Failed" modal is open and blocking the app for a while - it might be a red herring, but I'm not sure.

**Comment by asim-vax** [comment] 2017-12-20 12:35
On ubuntu deb latest version i get the same error - minus the crash
![image](https://user-images.githubusercontent.com/4798940/34207376-1d05bd88-e582-11e7-9892-8c5dabde977f.png)

It actually creates the file in downloads folder, with 0 bytes - i.e no content

**Comment by asim-vax** [comment] 2018-01-23 10:59
This doesn't seem to be a problem in 1.1.0 - using the snap version atleast, it downloads correctly.

**Comment by berliner** [comment] 2018-02-01 16:56
On Manjaro 17.1 with all updates I see the same as asim-vax on Ubuntu. I'm not using the snap version.

**Comment by CodeMouse92** [comment] 2021-01-29 23:45
It appears that this issue has been resolved, so we are closing it. If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-29 23:45 UTC
Labels: audit, calendar, needs-reproduction
