### ISSUE TITLE
Blue tray icon badge appears after every mail sync regardless of new unread email

### ISSUE THREAD

**Issue by mko-mx** [Foundry376/Mailspring#1017] opened 2018-08-12 16:32 UTC
##### Are there any related issues?

- Possibly #692 

##### What operating system are you using?

Windows 10 x64

##### What version of Mailspring are you using?

1.4.0-549b7968

--

**Bug?**

Every time the client syncs new email, regardless of whether or not there is new email a tiny blue badge appears on the tray icon.

I believe this indicator should only appear when there is new unread email since, when you click and open the window, the badge disappears until the next sync.

**Badge after mail sync:**
![captura de pantalla 2018-08-12 11 07 03](https://user-images.githubusercontent.com/8079447/44004117-7b3b2614-9e22-11e8-9dd6-ce2560fdca80.png)

**Regular state:**
![image](https://user-images.githubusercontent.com/8079447/44004141-070b1a00-9e23-11e8-9c94-e85bba619a18.png)

##### Is this an email sync or connection issue?

No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No

**Comment by JackDinn** [comment] 2018-08-24 15:00
me too (blue dot on every sync) and it only works if mailspring is minimised NOT closed to tray, Also the actual blue dot is so small i cant even see it without Kmag

**Comment by D4V3M0NK** [comment] 2018-09-04 19:49
I've installed Mailspring on Ubuntu 14 and this happens on Linux too. It was driving me mad seeing a blue dot on the notification icon but then (after spending a few minutes hunting around the 4 IMAP accounts that I connect to) came across this thread and it's related bug in Mailspring.

However, I'm hanging in with Mailspring as I think it's the neatest and easiest to use across the board. I do like their (monthly subscription based) option of tracking emails that are sent / opened, although I'm not using it presently.

**Comment by HarveyWilliams** [comment] 2018-10-31 14:34
I think I see the issue: https://github.com/Foundry376/Mailspring/blob/master/app/internal_packages/system-tray/lib/system-tray-icon-store.es6#L54

```
return isWindowBlurred
      ? { iconPath: INBOX_UNREAD_ALT_ICON, isTemplateImg: false }
      : { iconPath: INBOX_UNREAD_ICON, isTemplateImg: true };
```

I assume `isWindowBlurred` is true, and so it always sets the `iconPath` to be `INBOX_UNREAD_ALT_ICON` which is set on line 15.

However this goes against what @JackDinn said: 

> it only works if mailspring is minimized NOT closed to tray

If it's minimized, it will also probably say that the window is blurred.

**Comment by JackDinn** [comment] 2018-10-31 15:00
when i said "it only works if mailspring is minimized NOT closed to tray" i meant that the unread mail icon (blue badge) only works when mailspring is minimized although it has this error of showing with every sync. However the blue unread badge does not show at all if i have mailspring closed to tray.

**Comment by memboc** [comment] 2019-02-07 06:56
I have inverse case 
![02c905f3-2048-4629-b54f-8c20cca40b86 png](https://user-images.githubusercontent.com/7403119/52395307-ac09ff80-2abe-11e9-8c2f-039a8cbcff28.jpg)

**Comment by xclabit** [comment] 2019-02-13 12:00
Can confirm on Windows x64. I always get a blue dot after a sync, even with 0 unread messages.

**Comment by Ax3man** [comment] 2019-06-17 21:22
Can confirm on Linux Mint 19.1 Cinnamon. Icon keeps turning blue, no new mail.

**Comment by mickaellecolazet** [comment] 2019-06-27 13:01
Same here. Blue dot while there is no new mail.
It could be great to disable this, and have a email counter badge instead.
![Annotation 2019-06-27 145203-edit](https://user-images.githubusercontent.com/25107307/60268146-0a0f7600-98ec-11e9-93ce-c76bf4039614.jpg)

**Comment by mkhazov** [comment] 2019-07-03 08:50
This issue is supposed to be fixed by #1206

**Comment by JDecunha** [comment] 2019-11-01 17:27
Any progress on this? Have been having this issue in Ubuntu 19.10. I think a solution was given in #1206 but hasn't been committed to master.

**Comment by saber7165** [comment] 2019-11-04 01:36
I have Mailspring 1.7.2 with Ubuntu 18.04. I do not see a blue dot on the tray icon, but the whole tray icon which is white randomly turns into blue.

**Comment by popovas** [comment] 2020-03-20 09:15
Mailspring version 1.7.4-d54ff730 on ubuntu 19.10 has the same issue.

**Comment by CodeMouse92** [comment] 2021-01-30 02:10
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/badge-doesnt-always-appear-on-app-indicator-when-receiving-new-mail/392

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-30 02:10 UTC
Labels: audit
