### ISSUE TITLE
Feature Request: Dark theme menus are still white - make them dark, too.

### ISSUE THREAD

**Issue by IngwiePhoenix** [Foundry376/Mailspring#2227] opened 2020-12-14 13:39 UTC
**Is your feature request related to a problem? Please describe.**
I just installed Mailspring on Windows. So far, I like it. But due to my visual impairment, the first thing I always do is activate dark mode wherever possible so I do not have to rely on the system magnifier's "Invert Colors" feature. After doing so in Mailspring, the menu - mainly the top-right hamburger-menu - is still white.
![image](https://user-images.githubusercontent.com/2893716/102087618-1a861a00-3e1a-11eb-8333-25c039cfeff0.png)

**Describe the solution you'd like**
Apply the dark theme to all menus - including this menu, too.

**Describe alternatives you've considered**
Dunno what an alternative would be. If this menu can not be themed, then make it theme-able, I guess?

**Additional context**
None needed.

**Comment by valentt** [comment] 2020-12-16 11:09
Check my bug: https://github.com/Foundry376/Mailspring/issues/2231

This is a dead project and dead product unfortunately, and we need to find an alternative. Any suggestions?

**Comment by CodeMouse92** [comment] 2021-01-18 20:52
Contrary to rumors, **Mailspring is not abandoned.** 2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be a duplicate of one we've already migrated to Discourse:

https://community.getmailspring.com/t/consistent-theming-on-windows/58

@IngwiePhoenix I've migrated your post to that thread. If you comment on that thread or private message me on Discourse, I'll reassign that post to you.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-18 20:52 UTC
Labels: audit, enhancement
