### ISSUE TITLE
Arrow keys move to the opposite direction when vomposing RTL

### ISSUE THREAD

**Issue by Galgalon** [Foundry376/Mailspring#1637] opened 2019-09-19 08:27 UTC
Hello,

When I compose a message in an RTL language (Hebrew in my case), the arrow keys move the cursor to the opposite direction, i.e. Left arrow moves the cursor to the right, and right arrow moves the cursor to the left. The Backspace and Delete keys work fine.

Thanks

**Comment by bengotow** [comment] 2019-10-08 21:41
Oh wow this is no good! Sorry for the hassle. It sounds like we've inherited this from this issue upstream: https://github.com/ianstormtaylor/slate/issues/2963. Will see if we can contribute a patch back!

**Comment by k-caps** [comment] 2020-04-27 16:20
> Oh wow this is no good! Sorry for the hassle. It sounds like we've inherited this from this issue upstream: [ianstormtaylor/slate#2963](https://github.com/ianstormtaylor/slate/issues/2963). Will see if we can contribute a patch back!

Has this been addressed? I am currently experiencing the same issue.

**Comment by CodeMouse92** [comment] 2021-02-19 00:35
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/arrow-keys-move-to-the-opposite-direction-when-composing-rtl/704

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@Galgalon @k-caps: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-19 00:35 UTC
Labels: audit, bug, composer
