### ISSUE TITLE
Office 365 Account Sync Failed

### ISSUE THREAD

**Issue by nemeroth** [Foundry376/Mailspring#1753] opened 2020-01-03 10:59 UTC
Hello,

 Office 365 Sync Failed,
 MailSpring Version : 1.7.2.4522b259

```
4928 [2020-01-02 17:53:23.583] [foreground] [info] - remote=63, local=63
4928 [2020-01-02 17:53:23.584] [foreground] [info] Idling on folder INBOX
4928 [2020-01-02 17:53:32.250] [metadataExpiration] [info] Scanning for expired metadata
4928 [2020-01-02 17:53:32.250] [metadataExpiration] [info] -- Will wake for next expiration in 7200sec
4928 [2020-01-02 17:53:38.241] [calContacts] [critical] 
 ***
 *** An exception occurred during program execution: 
 *** (unknown exception details)
 ***

4928 [2020-01-02 17:53:38.247] [calContacts] [critical]  *** Stack trace:
 ***   clone
 ***
```

**Comment by CodeMouse92** [comment] 2021-02-01 19:17
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/crash-on-sync-no-stack-trace/419

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-01 19:17 UTC
Labels: audit
