### ISSUE TITLE
Bug: opting out of auto-start at system startup is not persistent across version upgrades

### ISSUE THREAD

**Issue by kzadora** [Foundry376/Mailspring#2010] opened 2020-05-24 00:43 UTC
**Describe the bug**
If the user disables "Launch at system start" setting, and then upgrades to new Mailspring version, the setting is re-enabled. 

**To Reproduce**
1. Go to Preferences, disable "Launch at system start" setting
2. Upgrade Mailspring to newer version
3. Check the "Launch at system start" setting

**Expected behavior**
The setting should be still disabled, honoring user preference

**Actual behavior**
The setting is enabled

**Setup: (please complete the following information):**
 - OS: Windows 10 Version 2004
 - Mailspring Version: ex: 1.7.6

**Comment by Darthagnon** [comment] 2020-05-25 12:24
#1493 - The checkbox has been resetting itself to "launch on system startup" for a while. It doesn't autostart, anyway, for me (I must have disabled it somewhere)

**Comment by doman18** [comment] 2020-06-05 17:32
Can someone at least provide temporary workaround by telling how Mailspring adds itself to autostart on each system? Im using Kubuntu and tried to look for some .desktop file on all autostart directories but didnt found any 

~/.kde/Autostart
~/.kde/share/autostart
~/.config/autostart
~/.local/share/autostart
/etc/xdg/autostart
/usr/share/autostart

**Comment by CodeMouse92** [comment] 2021-01-29 21:53
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/i-cant-uncheck-run-on-startup/208

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-29 21:53 UTC
Labels: audit, bug
