### ISSUE TITLE
Existing contact will not show in compose

### ISSUE THREAD

**Issue by harm0nic** [Foundry376/Mailspring#1464] opened 2019-04-11 14:25 UTC
Long time user of MailSpring, and have had this issue since day one. One of my client's email and contact info never appears in the composer. I have not noticed this issue with any other users. His email and contact info appears in my Google Contacts account as well as in Gmail with no issue.

This issue has persisted across different computers (all running linux from ubuntu 16.04 to 18.10) and several clean and fresh syncs. The worst is that this client is the one I send the most email too, so super annoying to have to type his name and email each time I want to start a new thread or copy him on something.

##### What operating system are you using?
Ubuntu 18.10
...

##### What version of Mailspring are you using?
Affected mailspring since launch. Currently using latest 1.6.1

##### Is this an email sync or connection issue?

Guessing a contact sync issue

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Gmail

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

Perhaps allow for a basic contact manager so anyone else with a similar issue can manually edit.

**Comment by bengotow** [comment] 2019-05-26 21:59
Hey! Hmm, this one is pretty interesting. We definitely need to add a full address book solution soon, but do you know offhand if your client's email address looks autogenerated in some way? I think that to prevent the address book from becoming a mess, we filter out email addresses that are more than 40 characters long or include "notifications" or "no-reply", or start with "updates" or "news" or "info", etc. Maybe he's getting caught in one of those rules. Will definitely be better when we've got an address book built in!

**Comment by harm0nic** [comment] 2019-05-26 22:03
Hi bengotow,
You are correct in that the email begins with info@

Perhaps it would be a good idea to remove "info" from the filter as I happen to know a lot of small business' that use info@ as their primary contact addresses.

**Comment by mimavox** [comment] 2019-10-30 17:16
I know this issue is merged, but as a side note I want to point out a serious drawback of having a automatic long-address-ban on new contacts: I use Trello as my task manager, and I frequently need to forward mails to Trello in order for them to appear on my TODO Trello board (as in: https://help.trello.com/article/809-creating-cards-by-email) Unfortunately, my Trello-generated address is quite long, and will therefore not be remembered in Mailspring's contact list. It would be very convinient with some kind of work-around for this use case.

**Comment by harm0nic** [comment] 2019-10-30 17:20
@mimavox Just curious; have you tried manually adding the email to the new contact manager? settings -> window -> accounts?

This doesn't work for Google accounts yet "Coming Soon for Google Accounts", but it looks like it will be added as soon as Google approves their API access.

**Comment by mimavox** [comment] 2019-10-31 07:00
I can add it for my work account, but not for my Google account (as you point out). However, it doesn't matter; the added address still doesn't show up when I try to type it's name in the To-field.

**Comment by valentt** [comment] 2020-12-16 11:12
Check my bug: https://github.com/Foundry376/Mailspring/issues/2231

This is a dead project and dead product unfortunately, and we need to find an alternative. Any suggestions?

**Comment by CodeMouse92** [comment] 2021-01-18 22:13
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/gh-issue-migration-canned-message/39

Please consider joining that community and continuing the discussion there!

Bonus: @harm0nic @mimavox if you join and reply to the issue, the moderators can make an effort to reassign your migrated posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-18 22:13 UTC
Labels: audit, composer, needs-reproduction
