### ISSUE TITLE
Bug: Mailspring eats whole CPU

### ISSUE THREAD

**Issue by skijsche** [Foundry376/Mailspring#2218] opened 2020-12-05 01:49 UTC
When i have mailspring running in the background, after a while it starts eating whole cpu. I tried to reinstall but to no help. Mailspring is the best client i encountered but this thing is really weird. IDK what to do.
![image](https://user-images.githubusercontent.com/60545090/101230245-804d0600-36a4-11eb-9b48-4a37fc97b01d.png)

**Comment by matheusfillipe** [comment] 2020-12-06 19:13
I have the same problem on linux! 


![image](https://user-images.githubusercontent.com/24435787/101289428-1daa5600-37db-11eb-995e-10aa492a206e.png)


Everytime I start mailspring those processes start burning cpu one thread for each of my mails and they won't stop. I already let it for hours and that never finishes. If I kill each of them mailspring is still usable.

OS: Arch Linux x86_64, DE: KDE Plasma 5.20.2, CPU: Intel i7-7700HQ (8) @ 3.800GHz, GPU: NVIDIA GeForce GTX 1050 Ti Mobile, GPU: Intel HD Graphics 630, Memory: 15.5 GiB

**Comment by mikaelmello** [comment] 2020-12-08 15:57
I am constantly seeing the same behavior, specially on startup, where the CPU usage becomes really high and even after hours it does not stop.

With only mailspring open, my CPU usage is at around 20% (i7-9750h). I usually restart and it fixes the problem for a while before the CPU usage starts to get really high again.

I have just restarted and do not have any screenshots, but I will take them and comeback here next time.

![image](https://user-images.githubusercontent.com/17488630/101507016-db0c8900-3954-11eb-8b4e-53de493a373e.png)

**Comment by mikaelmello** [comment] 2020-12-12 23:46
![image](https://user-images.githubusercontent.com/17488630/101999373-198aa680-3cbb-11eb-83c3-9d58ec536a35.png)

**Comment by valentt** [comment] 2020-12-16 11:09
Check my bug: https://github.com/Foundry376/Mailspring/issues/2231

This is a dead project and dead product unfortunately, and we need to find an alternative. Any suggestions?

**Comment by CodeMouse92** [comment] 2020-12-18 15:56
@shijsche Unfortunately, @valentt spoke out of turn. The project and product are NOT dead. The maintainer responded to his issue. There was a server issue.

Mailspring is alive and well!

**Comment by CodeMouse92** [comment] 2021-01-18 20:59
Thank you for reporting this. 2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

**In order to properly address this issue, we require the additional information requested by the issue template. Please start a new Thread in the appropriate category on our [Discourse](https://community.getmailspring.com) — or else reply to the related Thread if it's already created — so we can properly evaluate and discuss this issue.**

Meanwhile, we're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-18 20:59 UTC
Labels: audit, bug
