### ISSUE TITLE
Bug: smtp auth / ubuntu 20.04 / snap and deb 1.7.8

### ISSUE THREAD

**Issue by netfxtech** [Foundry376/Mailspring#2072] opened 2020-06-26 04:06 UTC
**Cannot connect to Office365 --- Log below:**

_"----------IMAP----------
connect <mailcore::IMAPSession:>
* OK The Microsoft Exchange IMAP4 service is ready.
ssl connect outlook.office365.com 993 2
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
1 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
1 OK CAPABILITY completed.
connect ok
login
2 LOGIN "MY EMAIL ADDRESS" "*********"
2 OK LOGIN completed.
3 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS MOVE ID UNSELECT CLIENTACCESSRULES CLIENTNETWORKPRESENCELOCATION BACKENDAUTHENTICATE CHILDREN IDLE NAMESPACE LITERAL+
3 OK CAPABILITY completed.
4 NAMESPACE
* NAMESPACE (("" "/")) NIL NIL
4 OK NAMESPACE completed.
login ok
5 LIST "" "*"
* LIST (\HasNoChildren) "/" Archive
* LIST (\Marked \HasChildren) "/" Calendar
* LIST (\HasNoChildren) "/" Calendar/Birthdays
* LIST (\HasNoChildren) "/" "Calendar/United States holidays"
* LIST (\Marked \HasChildren) "/" Contacts
* LIST (\HasChildren) "/" "Conversation History"
* LIST (\Marked \HasNoChildren \Trash) "/" "Deleted Items"
* LIST (\Marked \HasNoChildren \Drafts) "/" Drafts
* LIST (\Marked \HasChildren) "/" INBOX
* LIST (\HasChildren) "/" INBOX/Clients
* LIST (\HasNoChildren) "/" "INBOX/Clients/RANDOM FOLDER"
* LIST (\HasNoChildren) "/" "INBOX/Clients/RANDOM FOLDER"
* LIST (\HasChildren) "/" "INBOX/Clients/RANDOM FOLDER"
* LIST (\HasNoChildren) "/" "INBOX/Clients/RANDOM FOLDER"
* LIST (\HasNoChildren) "/" "INBOX/Clients/RANDOM FOLDER"
* LIST (\HasNoChildren) "/" "INBOX/Clients/RANDOM FOLDER"
* LIST (\HasNoChildren) "/" "INBOX/Clients/RANDOM FOLDER"
* LIST (\HasNoChildren) "/" "INBOX/Clients/RANDOM FOLDER"
* LIST (\HasChildren) "/" INBOX/Family
* LIST (\HasNoChildren) "/" INBOX/Family/RANDOM_FOLDER
* LIST (\Marked \HasChildren) "/" INBOX/Personal
* LIST (\HasNoChildren) "/" INBOX/Personal/Receipts
* LIST (\HasNoChildren) "/" "INBOX/Scanned Items"
* LIST (\HasNoChildren) "/" "INBOX/To be sorted"
* LIST (\HasNoChildren) "/" "INBOX/To be sorted - Other"
* LIST (\HasNoChildren) "/" INBOX/Vendors
* LIST (\HasNoChildren) "/" Journal
* LIST (\HasNoChildren \Junk) "/" "Junk Email"
* LIST (\HasNoChildren) "/" Notes
* LIST (\Marked \HasNoChildren) "/" Outbox
* LIST (\HasNoChildren) "/" "RSS Feeds"
* LIST (\Marked \HasNoChildren \Sent) "/" "Sent Items"
* LIST (\HasChildren) "/" "Sync Issues"
* LIST (\HasNoChildren) "/" "Sync Issues/Conflicts"
* LIST (\HasNoChildren) "/" "Sync Issues/Local Failures"
* LIST (\HasNoChildren) "/" "Sync Issues/Server Failures"
* LIST (\HasNoChildren) "/" Tasks
5 OK LIST completed.

----------SMTP----------
connect smtp.office365.com 587
220 SERVER.outlook.office365.com Microsoft ESMTP MAIL Service ready at Fri, 26 Jun 2020 03:57:03 +0000
init
EHLO PC-NAME
250-SERVER.outlook.office365.com Hello [IPV6 Address]
250-SIZE 157286400
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-STARTTLS
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250 SMTPUTF8
start TLS
STARTTLS
220 2.0.0 SMTP server ready
done
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
init after starttls
EHLO PC-NAME
250-SERVER.outlook.office365.com Hello [IPV6 Address]
250-SIZE 157286400
250-PIPELINING
250-DSN
250-ENHANCEDSTATUSCODES
250-AUTH LOGIN XOAUTH2
250-8BITMIME
250-BINARYMIME
250-CHUNKING
250 SMTPUTF8
AUTH LOGIN
334 VXNlcm5hbWU6
c2JvdWlsbG9uQG5ldGZ4dGVjaC5jb20=
334 UGFzc3dvcmQ6
QU1QbmV0QDk5
535 5.7.3 Authentication unsuccessful

SASL_PATH: /snap/mailspring/488/usr/share/mailspring/resources/app.asar.unpacked

SMTP Last Response Code: 535
SMTP Last Response: 5.7.3 Authentication unsuccessful

mailsmtp Last Error Code: 17
mailsmtp Last Error Explanation: MAILSMTP_ERROR_AUTH_LOGIN
mailsmtp Last Error Location: 10
mailsmtp Last Auth Type: 16_

**To Reproduce**
Easy - fresh install - try adding Office365 account, will receive this error
Tried adding Gmail first which was accepted and then adding Office365 email but it still didn't work

**Setup: (please complete the following information):**
 - OS: Ubuntu Desktop
 - OS Version 20.04
 - Mailspring Version: 1.7.8

**Additional context** 
Kind of annoying I keep forgetting to cancel my subscription but continue paying even though I haven't been able to use it in the past year.

**Comment by c-goosen** [comment] 2020-07-20 18:11
Have the same issue. Thunderbird mail is working, same settings.

**Comment by pramodbutte** [comment] 2020-08-20 21:31
I just downloaded the latest version and having same problem. Any update?

**Comment by teezeit** [comment] 2020-09-22 07:42
same here.

**Comment by dakorpar** [comment] 2020-10-08 12:18
also having problem for one of my office365 accounts, one works fine other one doesn't... They said I should try to connect to smtp port 25 instead of 587, that that could work, but that's not possible to change in mailspring for offi365 account

**Comment by CarlosRebolledo** [comment] 2020-10-09 03:11
Oh my God!!!! How is it possible that Ben does not show signs of life and interest in responding? Unusual

**Comment by pahofmann** [comment] 2020-10-21 17:52
Have the same issue on Pop_OS! 20.04.

**Comment by netfxtech** [comment] 2020-10-29 21:23
I've given up on this application. The developer obviously doesn't care about users who use O365.... you know, the market share leader in business email. Cancelled membership... tool frustrating. I'll leave this issue open though. I hope you receive the assistance I requested almost 5 months ago.

Cheers!

**Comment by sichkarmg** [comment] 2020-11-05 12:33
Microsoft is a piece of shit that constantly changes the specification! It seems they do it on purpose so that only their soft is used.

**Comment by CodeMouse92** [comment] 2021-01-18 19:14
Thank you for your patience on this issue! I know it's frustrating when you cannot connect to your email with Mailspring.

2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be a duplicate of one we've already migrated to Discourse:

https://community.getmailspring.com/t/institutional-office365-not-working/48/2

Please consider joining that community and continuing the discussion there.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-18 19:14 UTC
Labels: audit, bug
