### ISSUE TITLE
Cannot receive message sent to myself

### ISSUE THREAD

**Issue by oserban** [Foundry376/Mailspring#149] opened 2017-10-13 10:16 UTC
##### What operating system are you using?
Ubuntu 16.04

##### What version of Mailspring are you using?
1.0.4
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No (reproduced this issue with  both Gmail and Exchange)

Sometimes, I CC myself in some e-mails I send. I can see these e-mail in sent, but in the inbox it behaves a bit weird. 

The message appears for 1 second in inbox while the sync is still running but disappears straight after. I think this is a UI problem, but I don't know where to investigate. If I login to the webmail interface, the e-mail appears in the inbox so it is definitely a mailspring issue.

**Comment by oserban** [comment] 2017-10-13 10:23
If I move the message to another folder (using the web interface), the issue does not reproduce anymore. So it is an inbox problem.

**Comment by Bouska** [comment] 2017-10-14 17:41
I'm running MailSpring 1.0.4 on Fedora 26. I've tried to send myself a email either a TO or a CC with my gmail account, and each time I got my mail in my inbox (I'm even detected as "You").

**Comment by bengotow** [comment] 2017-10-15 07:48
Hmm so this is an interesting one—Mailspring generates unique IDs for messages that are based on their RFC822 headers and the message date. (Which isn't ideal for several reasons, but it needs to be able to track messages as they move between folders and associate metadata with them in a stable way...) When you send mail, Mailspring sometimes needs to place the message into your sent folder by itself, and sometimes the mail provider does it automatically. If it does it itself or the mail provider doesn't change the message headers at all, it's very likely that when it sees the message arrive in the Inbox, it processes it and assigns it the same ID it gave to the message it put in the sent folder. It's actually possible that this message will jump back and forth between the two folders, which would be pretty whacky...

I'll see if we can fix this in the next release—I'm pretty sure I've seen this happen and just haven't investigated it.

**Comment by oserban** [comment] 2017-10-15 19:00
Maybe I should have pointed out that I have multiple accounts setup

**Comment by jarey** [comment] 2017-10-15 19:03
Hello,

It is happening to me using the nylas-mail-lives 2.2.0 release. Could be related to the codebase?
I'm opening an issue linked to this one on nylas-mail-lives repo so it could be helpful.

Just if it helps, i'm using an outlook account using IMAP.

Kind regards.

**Comment by jerm** [comment] 2017-10-26 06:18
@jarey Yeah, this was a known issue in Nylas Mail, re the messsage-id generation that Ben mentioned. Excited for a fix :)

**Comment by dinoboy197** [comment] 2018-09-24 17:33
Hi @bengotow ! I'm still seeing this issue in Mailspring 1.4.2. I send emails to myself regularly, so this turns out to be a big headache for me.

Would you mind giving us an update on the priority for a fix for this item? Thanks!

**Comment by smelco** [comment] 2019-04-07 14:26
Still an issue in Mailspring 1.6.1 (Mac). 

I was sending myself some messages when trying out the client's features and noticed that my messages would appear but be hidden seconds later. The messages are still in my imap account and they appear as expected with other email clients, but the Mailspring client is not showing them in my inbox.

**Comment by funkycram** [comment] 2019-10-06 20:39
Same problem here : Ubuntu 18.04, Mailspring 1.6.3

**Comment by bjorkeberget** [comment] 2020-06-04 17:37
+1. Fedora 32. mailspring-1.7.8-0.1.x86_64. 
Very annoying.

**Comment by CodeMouse92** [comment] 2021-01-21 01:24
Hi all,

2020 prevented much development work on Mailspring, but rest assured, development has resumed! We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. Learn more about the changes here.

@bjorkeberget: Can you please confirm that this is still broken with 1.8.0, and if so, open a new Bug Report on our Discourse ? We want to be able to address this, but we need up-to-date diagnostic information to do it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-21 01:24 UTC
Labels: audit
