### ISSUE TITLE
Specify Reply-To header when composing

### ISSUE THREAD

**Issue by LeonB** [Foundry376/Mailspring#519] opened 2018-01-11 09:16 UTC
It would be nice to have a posibility to specify a 'Reply-To' header when sending messages.

![Reply-To in Thunberbird](https://i.stack.imgur.com/iR0zf.png)

**Comment by pappfer** [comment] 2018-07-06 11:10
It seems like Mailspring doesn't respect the Reply-To headers on the incoming e-mails either.
When I click on the Reply button, it always replies to the sender of the email, even though the Reply-To header is set to a different email address.

**Comment by mb-karo** [comment] 2019-10-11 07:37
This would be very useful for me, too! :up: :+1:

**Comment by Darunada** [comment] 2019-10-13 00:04
+1

**Comment by GuillauG** [comment] 2020-02-05 12:33
+1

**Comment by sketet** [comment] 2020-06-12 17:42
this feature is scheduled to be added?

**Comment by CodeMouse92** [comment] 2021-02-24 21:47
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/specify-reply-to-header-when-composing/768

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@LeonB: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-24 21:47 UTC
Labels: audit, enhancement
