### ISSUE TITLE
ErrorCertificate, X509_verify_cert_error, unable to get local issuer certificate

### ISSUE THREAD

**Issue by remingtonc** [Foundry376/Mailspring#214] opened 2017-10-20 03:19 UTC
##### Are there any related issues?
Not obviously. Some errors look similar.

##### What operating system are you using?
Windows 10

##### What version of Mailspring are you using?
1.0.5

--

**Bug?**
```
Waiting for Account JSON:

Waiting for Identity JSON:
{"account":null,"error":"ErrorCertificate","error_service":"imap","log":"----------IMAP----------\n* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=LOGIN] Dovecot ready.\r\n��"}Verification failed:
X509_verify_cert_error_string:
unable to get local issuer certificateX509_get_subject_name:
countryName               = US
organizationName          = Let's Encrypt
commonName                = Let's Encrypt Authority X3
```
<img width="675" alt="mailspring_bug" src="https://user-images.githubusercontent.com/16908622/31803749-505cb2fc-b50a-11e7-8612-f483d6e3e17f.png">

##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
migadu.com

##### Is the issue reproducible with a particular attachment, message, signature, etc?
N/A

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Yes - Apple Mail and Outlook, and Mailbird.

**Comment by bengotow** [comment] 2017-10-20 06:38
Hey! So this looks /super/ ugly and we definitely need to fix it, but it sounds like your machine does not trust this SSL certificate. Can you try checking "Allow insecure SSL"? 

Also if you visit migadu.com in the Edge browser does it show it as insecure?

**Comment by josgompor** [comment] 2017-10-24 08:44
Another one with the same error:

Last Error Code: 0\n\nmailsmtp Last Error Location: 3"}Verification failed:
X509_verify_cert_error_string:
unable to get local issuer certificateX509_get_subject_name:
commonName                = MadMail09

**Comment by moeffju** [comment] 2020-02-12 16:35
I'm getting this on Windows 10 with a Let's Encrypt cert. It's not as ugly anymore, but after "View Log" the error message is the same: 
```
Verification failed:
X509_verify_cert_error_string:
unable to get local issuer certificate
```

**Comment by moeffju** [comment] 2020-02-12 16:37
By the way, I literally added the same server on my MacBook a few minutes earlier, and it worked just fine. What's different about the cert stores or handling between Mailspring Mac & Windows?

**Comment by CodeMouse92** [comment] 2021-02-03 00:36
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

@moeffju (or anyone else): Can you please confirm that this is still broken with 1.8.0, and if so, open a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-03 00:36 UTC
Labels: audit, bug
