### ISSUE TITLE
any way to export/import mail routes? even manual copy-paste?

### ISSUE THREAD

**Issue by adolson** [Foundry376/Mailspring#1109] opened 2018-10-03 16:04 UTC
Can I somehow copy all of my mail routes from one PC to another? I use Mailspring on multiple computers, and have a bunch of mail routes that I would rather not have to recreate on every system. I don't see any export/import feature built in. Is that in the works (hopefully soon) or is there ANY way for me to do it without having to re-enter everything from scratch? I don't mind copying files or copy-pasting/editing config files.

##### Are there any related issues?

I saw none.

##### What operating system are you using?

Debian Linux

##### What version of Mailspring are you using?

Latest via self-updating Snap

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

I don't use another mail client

**Comment by bengotow** [comment] 2018-10-08 06:30
Hey! I've been planning to move mail rules to the cloud (attached to your Mailspring ID) to fix this. In the meantime, I think @KristerV's suggestion will work. If you were to symlink your Mailspring config folder to Dropbox or another location that is shared between your machines, the mail rules / templates, etc. would stay in sync. Hope that helps!

**Comment by adolson** [comment] 2018-10-08 07:50
I will try that, but cloud sync would be perfect!
I think I did try copying my config once but left cache stuff in and I
remember having a problem, but chalked it up to my own fault for copying
the files.

**Comment by KristerV** [comment] 2018-10-08 12:16
cloud sync? Amazing. If you also end up accepting MX records with the catch-all feature I would love to pay for this service. I'm not satisfied with mailbox.org at all. I mean I can just switch them as it doesn't matter which provider I use - just saying.

**Comment by synsa** [comment] 2019-01-14 23:01
This would definitely be a great feature to have. I would like to be able to export my [100's] of mail-rules from one Mailspring installation (office) to another on my (home) machine. Would rather not have to re-add them all manually. Which appears to be currently the case-- and why i'm looking at the source-code to see if i can help in development with this piece.

It'd also be nice to have a filter scripting language like Dovecots ManageSieve.  If using a flat-file system of course.

**Comment by MartinMuzatko** [comment] 2019-01-15 11:17
I fear the cloud-based services are not part of the source code.

**Comment by CodeMouse92** [comment] 2021-01-28 01:51
Thank you for reporting this. 2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/sync-templates-signatures-accounts-etc-accross-multiple-devices/265

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 01:51 UTC
Labels: audit, enhancement
