### ISSUE TITLE
setting shortcut key has been translated into Japanese

### ISSUE THREAD

**Issue by kometchtech** [Foundry376/Mailspring#1539] opened 2019-06-23 03:49 UTC
##### What operating system are you using?
windows10 1903

##### What version of Mailspring are you using?
1.6.2

--
In Japanese, commas are automatically written in Japanese.
When I looked at the language file, I did not find the corresponding part, so is it processed on the electron side?

![mailspring](https://user-images.githubusercontent.com/5137077/59971332-05c61e80-95b5-11e9-9cd1-be212590dc16.png)

**Comment by bengotow** [comment] 2019-07-01 02:24
Ahh this one might be tricky, let me see what we can do @kometchtech!

**Comment by CodeMouse92** [comment] 2021-02-15 21:03
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/setting-shortcut-key-has-been-translated-into-japanese/629

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@kometchtech: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed** 2021-02-25 01:50 UTC
Labels: bug, migrated
