### ISSUE TITLE
Different SMTP server for alias

### ISSUE THREAD

**Issue by aksdb** [Foundry376/Mailspring#1133] opened 2018-10-13 17:04 UTC
I have an IMAP server where I aggregate mails from different other mail providers. When sending mail I want to have the "sender"/FROM set according to the identity the mail was sent to.
Unfortunately, the current aliases only get me so far ... if I simply set the FROM to an email address that does not belong to the SMTP server I send it from, the receiving party will mark the mail as spoofed (which usually gets my mail thrown into the spam folder).

The proper solution would be, to actually send from the SMTP server the email actually belongs to.

Therefore my request: allow (optionally, ofcourse) to associate an alias with different SMTP settings.

If that is completely out of scope, then please at least allow to pick *any* sender when replying to an email (currently I can only pick aliases for the mail account the mail I respond to resides in; Mailspring currently doesn't allow me to answer with a completely different mail account).

**Comment by dantefff** [comment] 2019-03-28 12:40
I have a similar use case.
I have several email accounts which share a lot of folders (each of our team member can access folders of the others).
But our email provider allows only to send mail from our mail address so when we want to reply a email from another user (because he cant do it at the moment, or something like that) the email is blocked.

**Comment by huangzonghao** [comment] 2020-03-29 07:57
Having a similar issue here. I am not an expert in the field but I believe this is doable, as I am enjoying this exact feature in Spark on Mac. Looking for a Spark alternative for Linux

**Comment by CodeMouse92** [comment] 2021-02-25 20:57
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/different-smtp-server-for-alias/793

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@aksdb @dantefff @huangzonghao: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-25 20:57 UTC
Labels: audit, enhancement
