### ISSUE TITLE
Message window (popup) always opens on the primary display

### ISSUE THREAD

**Issue by Draghmar** [Foundry376/Mailspring#986] opened 2018-07-19 11:55 UTC
##### Are there any related issues?
Coulnd't find any.

##### What operating system are you using?
Windows 10 64bit

##### What version of Mailspring are you using?
1.3.0

--

**Bug?**
I have setup with two displays and Mailspring is on the second. When trying to create new message or open some existing one it always ends up on the default display. Moving window to the secondary display and then closing doesn't help - it'll still open on the first one. It's a minor issue but I'd gladly see it addressed. :)
##### Do you have any third-party plugins installed? If so, which ones?
Nope.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Nope.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Nope.

**Comment by bengotow** [comment] 2018-08-02 20:14
I think this may be something we can fix - Electron BrowserWindow's don't indicate what screen they're currently on, but I imagine each screen has a separate coordinate space range, so we might be able to identify the screen and then center the new window on the same screen. (https://github.com/electron/electron/blob/master/docs/api/browser-window.md)

**Comment by KennethNielsen** [comment] 2020-03-05 13:19
This problem applies also to viewing attachments as well

**Comment by KennethNielsen** [comment] 2020-03-05 14:20
For anyone else that may stumble on this issue. If you are on Ubuntu you can use this rather hacky workaround using wmctrl and a python script that runs all the time: https://gist.github.com/KennethNielsen/098584c272f92fc70f190396cca21af0

**Comment by CodeMouse92** [comment] 2021-02-25 01:04
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/message-window-popup-always-opens-on-the-primary-display/778

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@Draghmar @KennethNielsen: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-25 01:04 UTC
Labels: audit, enhancement
