### ISSUE TITLE
Memory leak in composer

### ISSUE THREAD

**Issue by KristerV** [Foundry376/Mailspring#1211] opened 2018-11-02 12:29 UTC
What operating system are you using? **Arch Linux**
What version of Mailspring are you using? **1.5.1-da141eaf**
Is this an email sync or connection issue? **no**
Is the issue related to a specific email provider (Gmail, Exchange, etc.)? **Probably not**

##### Are there any related issues?

https://github.com/Foundry376/Mailspring/issues/91 but my mail syncs fine
https://github.com/Foundry376/Mailspring/issues/566 but they talk about "Mailspring default" program, mine is with composer

##### Is the issue reproducible with a particular attachment, message, signature, etc?

I was writing a long letter, but no attachments, signatures or even recipients. I did add links and lists, if that is of any help.

##### How to reproduce

I'm not sure. All I was doing was writing a letter until my 8gb ram was so full that I couldn't type anymore.

Just instructions on how to debug would be good, then I could debug this further the next time this issue arises.

![image](https://user-images.githubusercontent.com/2750622/47915494-b909c800-deab-11e8-8db2-429d258db220.png)

**Comment by bengotow** [comment] 2018-11-03 16:04
Wow this is crazy - thank you for posting this! Next time this happens, could you:
- Open the developer tools in the composer window from Developer > Toggle Developer Tools
- Go to the Memory Tab and click "Take heap snapshot".
- Right click the snapshot in the left sidebar and say "Save..."
- Send that file to me at ben@foundry376.com (You can also post it here but I'm 99% sure that it doesn't contain personal information but not 100% positive).

That should allow us to see where in the application all this memory is being allocated and left around. I have a hunch this is down in the text editor somewhere, but we'll need to see.

In the meantime, I'll also try to reproduce this on my own and see how it goes!

**Comment by KristerV** [comment] 2018-11-05 05:29
Thanks for the tips. I'll do that next time the issue arises.

**Comment by bengotow** [comment] 2019-07-04 13:55
Hey folks! This should be addressed in the latest release (1.6.3) that shipped earlier this week. The app should auto-update on it's own, or you can grab the new version from the releases page: https://github.com/Foundry376/Mailspring/releases/. Thanks for filing this - enjoy the update!

**Closed by bengotow** 2019-07-04 13:55 UTC
Labels: bug, composer, done-pending-release, needs-reproduction

**Comment by CodeMouse92** [comment] 2021-02-03 18:25
It appears that this issue has been resolved, so we are closing it. If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

P.S. Duplicate of #927
