### ISSUE TITLE
Mail disappears from view.

### ISSUE THREAD

**Issue by izznogooood** [Foundry376/Mailspring#991] opened 2018-07-22 09:06 UTC
##### Are there any related issues?

Ubuntu 18.04
1.3.0-fd741eb7

##### Do you have any third-party plugins installed? If so, which ones?

No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

getmail.no

Mail disappears from view, not from server. 

I have to recache my mail on a daily basis, only the last 10-20 mails shows up. This randomly happens within 10 minuts of using mailspring and is only affecting this account.

I'd be happy to make an account for you for testing purposes.

**Comment by Bergg** [comment] 2018-07-23 12:10
Looks like a duplicate of #304

**Comment by izznogooood** [comment] 2018-07-24 13:49
Yep, thats it.

Moving back to evolution.

**Comment by bengotow** [comment] 2018-08-02 19:57
merging into #304

**Closed** 2018-08-02 19:57 UTC
