### ISSUE TITLE
BCC'ing many recipients splits the message into one for each recipient

### ISSUE THREAD

**Issue by nmggithub** [Foundry376/Mailspring#1669] opened 2019-10-16 20:13 UTC
Hello, I am logged into my university's email system (connected as an Office 365 account), and am using Mailspring on Debain. I am an officer on a club on campus, so I sometimes send out mass emails to our members. I have a text file with a little over 100 email addresses, one per line. I copy and paste this into the BCC field, and then I put my fellow officers in the To field. When I send an email, my Sent folder get's populated with multiple emails each with only one recipient in the BCC field. This did not happen when I used Evolution (GNOME's default mail client).

I tried sending out a message, BCCing only three addresses (that I own) and only one message ended up in my Sent folder, with all three in the BCC field, which is what should happen. Is it possible my issue is an issue with the number of recipients?

**Comment by bengotow** [comment] 2019-10-16 22:07
Hey! This is super interesting—there's only one scenario where Mailspring would split your message and deliver it many times, and that's when "read receipts" or "link tracking" are enabled (so you'd see blue icons in the bottom of the composer window.) AND there are fewer than 8 recipients. In that case, we send a separate copy of the message through your SMTP server for each recipient with the links and read receipt modified so you can tell which recipients are viewing the email. But when those features are off or there are a lot of recipients, we do a hard bypass of that code and deliver the message with just one SMTP request.

It's possible that when you hit 100 BCC'd folks your mail server (Office 365) switches to a different delivery strategy, but I don't think I've heard of that before.

I'll think about this one a bit and see if I can think of anything else that might cause this!

**Comment by bengotow** [comment] 2019-10-16 22:33
Actually, I was just reviewing the code for this and I can't find where the 8-recipient limit is implemented for read receipts and link tracking. Could you try sending your next email with those blue icons disabled in the composer and see if you get a single entry in your sent mail?

**Comment by nmggithub** [comment] 2019-11-04 17:30
Hello! I am sending out another email today, and I will test it then. I will let you know what happens.

**Comment by nmggithub** [comment] 2019-11-04 17:41
That does appear to have been the issue. I am seeing a single entry now on the email where I turned off read receipts and link tracking.

**Comment by CodeMouse92** [comment] 2021-01-29 22:26
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/duplication-of-sent-mail/275

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-29 22:26 UTC
Labels: audit, needs-reproduction
