### ISSUE TITLE
Bug: Lag when "Syncing your mailbox..."

### ISSUE THREAD

**Issue by amadrzyk** [Foundry376/Mailspring#2163] opened 2020-10-07 22:27 UTC
**Describe the bug**
The entire app lags for me whenever the mailbox begins to sync. I'm unable to perform any actions like scroll or reply, until the mailbox stops syncing.

**To Reproduce**
Not sure what steps to write here, since it happens when I just open the app.

**Expected behavior**
I'd expect the app to work without lag & have the syncing job run in the background, while I'm using the app.

**Setup: (please complete the following information):**
 - OS: macOS
 - OS Version Catalina 10.15.6
 - Mailspring Version: 1.7.8

**Comment by CodeMouse92** [comment] 2021-01-28 03:30
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/the-eternal-sync-bug/334

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 03:30 UTC
Labels: audit, bug
