### ISSUE TITLE
Bug: Unread folder only checks Inbox

### ISSUE THREAD

**Issue by purefan** [Foundry376/Mailspring#1065] opened 2018-09-07 10:14 UTC
Clicking "Unread" only shows messages from the "Inbox" box in the connected accounts.

State 1: 
- In my "Inbox" folder (As defined in Edit -> Preferences -> Folders -> Inbox) I have 10 unread messages
- Clicking on "Unread" shows those 10 messages
- For the same account I have several folders

Action:
- Without opening an email, drag an Unread email from the Inbox folder to another folder

Result:
- The Unread folder on the side panel shows only 9 messages
- The folder where we moved the unread message does display the Unread mark
- Across the entire account there are still 10 unread messages

Expectation: 
- I expected that the Unread folder would count all the unread messages in every folder

**Comment by bengotow** [comment] 2018-09-17 18:29
Hey! This is correct currently - the unread item in the sidebar is the subset of your inbox which is unread. I actually can't remember why we built it this way—I think it's copying another mail client (Google Inbox maybe?)

I'll see if we can change this in the future - in the meantime, searching for `is:unread` should do what you're looking for.

**Comment by purefan** [comment] 2018-09-25 07:46
Gathering feedback: https://github.com/Foundry376/Mailspring/issues/70 Im not sure if by "badge" @neamtua means in the dock area or inside the app.

There is also a setting "Show unread counts for all folders / labels",  this seems to work fine in that it shows the count next to the folder name, perhaps re-wording it would avoid confusions ("Show unread count next to folder's name" ?)

**Comment by jplaverdure** [comment] 2019-04-30 18:58
While activating the setting "Show unread counts for all folders / labels" (which should be activated by default) alleviates part of the problem, It would be nice to have the desktop notifications also show up when new mail is received and sent to a folder by custom rules. I rely on such rules to manage my inbox as I am sure many people do.

**Comment by CodeMouse92** [comment] 2021-02-17 23:21
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/notifications-on-non-inbox-folders/323

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-17 23:21 UTC
Labels: audit, product-direction
