### ISSUE TITLE
Not all carddav address books are discovered

### ISSUE THREAD

**Issue by Dahaniel** [Foundry376/Mailspring#1972] opened 2020-05-07 11:11 UTC
##### What is the behavior you're seeing?
Mailspring only discovers the main carddav address book, misses all others. 

##### What email provider (Gmail, Exchange, etc.) are you trying to use?
mailbox.org with a custom domain. I created  `_carddavs._tcp.example.com` srv DNS entries to  `davs.mailbox.org`

##### What operating system are you using?
Ubuntu 18.04 

##### What version of Mailspring are you using?
1.7.6

**Comment by CodeMouse92** [comment] 2021-02-12 21:54
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/not-all-carddav-address-books-are-discovered/595

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@Dahaniel: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-12 21:54 UTC
Labels: audit, mailserver-incompatibility, needs-reproduction
