### ISSUE TITLE
Cannot create new label on GMAIL account

### ISSUE THREAD

**Issue by Andrewsudarikov** [Foundry376/Mailspring#101] opened 2017-10-10 04:16 UTC
When trying to add new label on Gmail literally nothing happens. I use Cyrillic characters but even if I try to name the label in English it doesn't work.

**Comment by neddy70** [comment] 2017-10-11 10:43
I had trouble with this too, sometimes I found the label would be created in Gmail, but would not appear in Mailspring, if I quit Mailspring and then opened it again the label would appear. However, sometimes it just wouldn't create a label.

**Comment by DmitryLoki** [comment] 2017-10-12 05:03
The same problem. This issue connects to mine - https://github.com/Foundry376/Mailspring/issues/100

**Comment by bengotow** [comment] 2017-10-12 22:43
Hey! This should be fixed in version 1.0.4 which was just released. Try grabbing the update at getmailspring.com/download and let me know if it's still an issue! Basically the client was creating the label / folder, but not properly updating the local cache. So you'd have to wait ~2 minutes for it to appear...

**Comment by neddy70** [comment] 2017-10-16 23:35
Hi Ben, I can confirm that this is fixed. However, it looks like the same thing is happening when I try to delete a label. If I delete a label, nothing happens initially, but if I click 'Sync New Mail Now' it disappears.

Cheers

**Closed** 2017-11-02 18:20 UTC
Labels: done-pending-release
