### ISSUE TITLE
Copy using CMD - C  Not Working

### ISSUE THREAD

**Issue by neddy** [Foundry376/Mailspring#799] opened 2018-04-04 04:56 UTC
CMD - C does not copy selected text from received emails. I can right click on the text and copy it, but using the shortcut no longer works.

CMD - C still works on text in emails that I am composing.

##### What operating system are you using?
macOS 10.12.6

##### What version of Mailspring are you using?
Malispring 1.2.0

**Comment by bengotow** [comment] 2018-04-04 07:14
Hey! Thanks for reporting this—it looks like this was a regression in 1.2.0 caused by https://github.com/Foundry376/Mailspring/issues/787, which was one of the last things I fixed. This is definitely a criticall issue—I'll ship a patch release (1.2.1) tonight to fix this.

**Comment by CodeMouse92** [comment] 2021-02-16 18:57
It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-16 18:57 UTC
Labels: audit, bug
