### ISSUE TITLE
Problems rendering on Linux and high DPI

### ISSUE THREAD

**Issue by scooby** [Foundry376/Mailspring#1213] opened 2018-11-04 20:59 UTC
#### Description

I've uploaded [a video on Youtube](https://youtu.be/NQ7WI5iFt58) illustrating the problem.

This appears to affect all views in Mailspring.

**Workaround**: reduce the size of the window.

Observed behavior: when a window exceeds certain dimensions (not sure exactly what they are) some "tiles" of the window will be cleared and not repainted.

##### Are there any related issues?

#359 may be related.

##### What operating system are you using?

Linux Mint 19

Possibly relevant: 
```
$ wmctrl -m
Name: Mutter (Muffin)
```

##### What version of Mailspring are you using?

```
$ mailspring --version
1.5.1-da141eaf
```

---

**Bug?**

##### Is the issue reproducible with a particular attachment, message, signature, etc?

It seems to affect all views within Mailspring.

**Comment by krupenja** [comment] 2018-11-06 09:16
I am also encountering this, though the symptoms are less severe on my system: it happens only occasionally and I was not yet able to record a video. Additionally, it only seems to happen when I have an external monitor attached to my laptop. I do not have this issue with other Electron/Chromium-based apps.
OS: Ubuntu 18.10, GNOME on Xorg
Mailspring: 1.5.2-31660462

**Comment by bengotow** [comment] 2018-11-25 07:39
Hey! Thanks for reporting this—It seems like Mailspring may be running out of video memory somehow. It might be worth trying to run it from the command line with the `--disable-gpu` argument. I know on some graphics cards that has improved performance.

We're planning to upgrade to Electron 4 as soon as they fix one last issue with the printing support, I'm also hopeful this will be fixed in the upgrade since it's probably relate to Chromium. Stay tuned!

**Comment by jstrieter** [comment] 2018-11-26 22:12
I've been having the same issue on Ubuntu 18.10 with KDE -- thought I also had it on GNOME. A comment in the above linked [#359](https://github.com/Foundry376/Mailspring/issues/359) mentions that issue only occurs with snap packages. Indeed I removed the snap and installed the .deb and the issue is gone.

**Comment by CodeMouse92** [comment] 2021-02-16 01:20
It appears that there has been no activity on this issue for some time, so we will close it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-16 01:20 UTC
Labels: audit, bug, linux
