### ISSUE TITLE
No messages in [Gmail]/Starred and missing other mails from random time periods

### ISSUE THREAD

**Issue by guygma** [Foundry376/Mailspring#719] opened 2018-02-22 18:55 UTC
##### Overview

The basic issue that I have comes when using Gmail as provider. Despite all of my 60k+ mails being visible when using webmail, a strange but repeatable subset of them is *not* synced by Mailspring. It is as if they do not exist. For one, there are no mails at all in [Gmail]/Starred. For another, I apparently only got 5 emails in 2015. If it were for 1915 I would believe it, but pretty sure that is not correct. There are also other blocks of time for which only of subset of my mails are fetched. 

Possible contributors to this I have consider are:
* I used to use Nylas for a time. I may even have been in the beta, I forget. 
* I have several external accounts whose mail I access by POP (old and current personal/school/work accounts), so many mails in my Gmail account do not have my accounts email in the `To` or `From` field. 
* I have used notmuch and [gmaileer](https://github.com/gauteh/gmailieer) to sync the X-Labels and X-GM-Labels in the past. Thus, a subset of my mails will have both but not all. 
* I recently gave a go at moving to FastMail (lots of good but also leaves much to be desired). Not sure how that may have impacted the internal message store.
* Recently, I had an issue wherein so much of my mail went into Spam even though it should not have. That one's on Google, [and it has happened before](https://plus.google.com/+LinusTorvalds/posts/DiG9qANf5PA). Again, thought it could potentially be relevant. 

Some logs:
[mailsync-red.log](https://github.com/Foundry376/Mailspring/files/1749160/mailsync-red.log)
[mspr.log](https://github.com/Foundry376/Mailspring/files/1749114/mspr.log)

##### Are there any related issues?

Not directly, but possibly tangentially.

[syncFolderUIDRange problem, #717](https://github.com/Foundry376/Mailspring/issues/717)
- I do not see similar output in my logs, but the nature of the problem seems similar. 

[high network bandwith from multiple labels, 662](https://github.com/Foundry376/Mailspring/issues/662)
- I have a lot of labels, and my interpretation of the logs indicates there is an excess of outbound requests at some point that causes the job to fail. I think this is pretty common when accessing a connection-limited SQL database.

[some mails not syncing, #525](https://github.com/Foundry376/Mailspring/issues/525)
- This is similar in that there are only some mails that I have a problem with. Since I have various outside accounts that are pulled into my Gmail I wonder if that is a factor as well. Also, given the generally sad state of email clients that Mailspring is here to fix, I have bounced between various ones from Thunderbird to Mailmate to notmuch/mutt and so on. This may not seem relevant at first, but the thought I had was that there are some conflicts between header values like X-Label and X-GM-Label or such. Perhaps there is one that Mailspring is reading in the API but it is actually the other that should be read to perform the proper logic for whether to download and sync.

[error while syncing, #357 ](https://github.com/Foundry376/Mailspring/issues/357)
- similar to above

[emails disappear from inbox, #304](https://github.com/Foundry376/Mailspring/issues/304)
- similar in concept to my case. I have Starred messages in my Inbox that appear on the Gmail web interface, but they DO NOT appear in my Inbox in the Mailspring interface. I have not seen them appear and then disappear, but that doesn't mean it isn't happening without ever appearing in the Inbox view. If there is a certain log that can clarify this I am happy to provide it. 

##### What operating system are you using?

Arch Linux (mainline kernel)

##### What version of Mailspring are you using?

1.1.4-22d9f20d

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?

No . 

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

I am using the built-in Gmail sync to setup my free (non-GSuite) Gmail account

##### Is the issue reproducible with a particular attachment, message, signature, etc?

I have tried on both my desktop machine (arch on a dell xps tower) and laptop (arch on 2012 macbook pro), both with the same result. I have rebuilt the AUR package three times, making sure to have rebooted to reload and changes to dkms modules. I have deleted and recreated my Mailspring ID. 

After each of these changes, the issue persists. 

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?

Yes, Gmail. But I would prefer to use it here!

**Comment by guygma** [comment] 2018-02-23 01:14
Another breadcrumb: in the Gmail client on Android, "Inbox" also does not show my starred messages. However, in this case there is a separate "Priority Inbox" that does show all messages with the "Inbox" label including those that are starred. It does not seem that Mailspring locates the Priority Inbox so perhaps that is the source of this problem?

**Comment by CodeMouse92** [comment] 2021-02-13 00:10
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/disappearing-emails-desync/428

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-13 00:10 UTC
Labels: audit
