### ISSUE TITLE
Bug: Visual glitch when editing keyboard shortcuts

### ISSUE THREAD

**Issue by paulomanrique** [Foundry376/Mailspring#1934] opened 2020-04-24 07:33 UTC
**Describe the bug**
When I try to edit a shortcut, it visually returns to the previous value. Whoever, if I restart the application, I see it saved the changes I made.

**To Reproduce**
Try to change any shortcut

**Expected behavior**
The new key to stay on screen

**Screenshots**
Video: https://imgur.com/a/4Gmn1vo

**Setup: (please complete the following information):**
 - OS: Deepin 20 Beta
 - Mailspring Version: 1.7.6

**Comment by CodeMouse92** [comment] 2021-02-27 03:46
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/visual-glitch-when-editing-keyboard-shortcuts/861

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@paulomanrique: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-27 03:46 UTC
Labels: audit, bug
