### ISSUE TITLE
Could not create required Mailspring folder: Mailspring/Snoozed.

### ISSUE THREAD

**Issue by mxdlzg** [Foundry376/Mailspring#1131] opened 2018-10-13 03:53 UTC
##### Are there any related issues?

...

##### What operating system are you using?
Deepin 15.7
...

##### What version of Mailspring are you using?
1.4.2
...

--

**Bug?**

##### Is this an email sync or connection issue?

[mailsync-0e1ae138.log.zip](https://github.com/Foundry376/Mailspring/files/2475044/mailsync-0e1ae138.log.zip)

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
mail.163.com
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?
Thunderbird works normally.
...

**Comment by CodeMouse92** [comment] 2021-01-30 00:31
Duplicate of #464

**Closed by CodeMouse92** 2021-01-30 00:31 UTC
Labels: audit
