### ISSUE TITLE
Bug: Cannot view / create contacts on IMAP account

### ISSUE THREAD

**Issue by cdancette** [Foundry376/Mailspring#2196] opened 2020-11-06 10:13 UTC
I use IMAP accounts on mailspring. I have two issues here: First, I cannot view the contacts I created on my webmail account, they are not synchronized. But I think that's due to IMAP.

Second, I cannot create new contacts: the Create Contact button is greyed. This issue is more annoying that the first one, as I would like to create groups to send mail to multiple people at once. 
It would be nice to be able to create contacts locally, even if they are not synchronized to the server.

![image](https://user-images.githubusercontent.com/10550327/98354667-55c64980-2021-11eb-8cf7-aef75c0ce0f5.png)

**To Reproduce**
1. Create IMAP account (I have two accounts, one on mailbox.org, and the other is a corporate mail)
2. Open contacts window
3. Try to create contact or view your contacts

**Setup: (please complete the following information):**
 - OS: Linux Solus
 - Mailspring Version: ex: 1.7.8

**Comment by CodeMouse92** [comment] 2021-03-03 03:43
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/editable-contacts-from-imap-email-addresses/752

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-03 03:43 UTC
Labels: audit, bug
