### ISSUE TITLE
Bug: All of the app gets blurry

### ISSUE THREAD

**Issue by ivarsauce** [Foundry376/Mailspring#2221] opened 2020-12-09 17:07 UTC
**Describe the bug**
Whole interface - all of it - gets a little blurry

**To Reproduce**
Can't really reproduce. I *think* it always happens after waking mac from sleep. Goes away only after restarting the app.

**Screenshots**
Screenshots with the problem and after restarting for comparison.
<img width="269" alt="Screenshot 2020-12-09 at 18 58 56" src="https://user-images.githubusercontent.com/63846954/101662090-ba762900-3a51-11eb-8b93-2e6d2bc6632f.png">
<img width="251" alt="Screenshot 2020-12-09 at 18 59 49" src="https://user-images.githubusercontent.com/63846954/101662096-bc3fec80-3a51-11eb-85e6-2649b5f02c33.png">

**Setup: (please complete the following information):**
 - OS: macOS
 - OS Version BigSur, but it happened on previous versions as well
 - Mailspring Version: 1.7.8., but again - it been a problem for a while

**Comment by CodeMouse92** [comment] 2021-01-18 23:22
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be connected to this:

https://community.getmailspring.com/t/interface-gets-blurry/89

Please consider joining that community and continuing the discussion there. **We need users to confirm the existence of this bug on Mailspring 1.7.8 or later, by commenting on that thread, for us to address this issue properly.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-18 23:22 UTC
Labels: audit, bug
