### ISSUE TITLE
Feature Request: Auto Complete for Organisation Emails

### ISSUE THREAD

**Issue by ckkibet** [Foundry376/Mailspring#1927] opened 2020-04-22 15:53 UTC
I use Mailspring for all my emails (and I really like it) including those from my organisation which is provided by Google's GSuite. When composing mails on the web or on just normal app, I just have to know the recipient's name and I get suggestions of possible email addresses within the organisation. 
![download (1)](https://user-images.githubusercontent.com/44083738/80003657-03c93680-84ca-11ea-8b84-71f050f5ac99.png)

When using Mailspring, this feature however is not there. I either have to ask for their emails or just compose the mail from Gmail which is tideous.

**Comment by CodeMouse92** [comment] 2021-02-27 03:39
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/auto-complete-for-organisation-emails/859

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@ckkibet: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-27 03:39 UTC
Labels: audit, enhancement
