### ISSUE TITLE
one or more accounts are having connection issues

### ISSUE THREAD

**Issue by anup-rayamajhi** [Foundry376/Mailspring#2246] opened 2020-12-31 07:15 UTC
I am using mailspring for IMAP email accounts in Windows 10 and i have been getting these error msgs "one or more accounts are having connection issue"

**Comment by xplreitr** [comment] 2021-01-04 23:56
I am having the same issue with a gmail account. I can re-link from the Preferences>Accounts section, but within a half-hour, the same problem crops up.

**Comment by CodeMouse92** [comment] 2021-01-17 05:37
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

**We need additional information from you to be able to evaluate and address this issue.** Please join the Mailspring Discourse community and create a new topic in the appropriate category. **Be sure to follow the provided template.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. **We will not be able to evaluate it until it has been reposted as requested above, by you or someone else.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-17 05:37 UTC
Labels: audit, mailserver-incompatibility, needs-reproduction
