### ISSUE TITLE
Yandex account causes a high CPU load and produces too many log records

### ISSUE THREAD

**Issue by h31** [Foundry376/Mailspring#1556] opened 2019-07-02 11:56 UTC
Hello.

I have noticed that a Yandex account causes a high CPU load in one of the syncing processes. When I've looked at logs I discovered that those related to the problematic account are much bigger and longer. The problem occurs both on Windows and on Linux. Please look at the logs attached.
[logs.zip](https://github.com/Foundry376/Mailspring/files/3349902/logs.zip)

##### Are there any related issues?

Haven't found anything.

##### What operating system are you using?

Linux (Ubuntu 18.04, snap) and Windows 10

##### What version of Mailspring are you using?

1.6.3

##### Is this an email sync or connection issue?

Sync issue.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Specific to one of email providers (Yandex Mail). Other email providers (Gmail and self-hosted one) works flawlessly.

**Comment by bengotow** [comment] 2019-10-29 13:15
Oh this is interesting - does Yandex support labels of some kind (or "virtual folders"?) It looks like Mailspring is discovering the same email message in more than one folder, and it's thinking that the items were "moved" between the folders. Then it syncs the other folder, finds them again, and moves them all back over and over. 

I'll see if I can fix this once and for all later this month—Mailspring was built on the assumption that folders hold messages, and a message won't appear in multiple folders, but it turns out there are several providers (maybe Yandex too) that implement "labels" or "tags" by just duplicating the message into several IMAP folders, and it really throws off Mailspring. Stay tuned—

**Comment by h31** [comment] 2019-10-29 20:59
Hello, Ben. Thank you for the reply!

There is something named labels in the web interface, but I only see two existing labels - "Important" and "Unread". There's an action to add custom labels, but looks like I haven't used this feature. And there is no IMAP folders for those labels. At least, I haven't found.

**Comment by CodeMouse92** [comment] 2021-02-17 22:40
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/yandex-account-causes-a-high-cpu-load-and-produces-too-many-log-records/671

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@h31: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-17 22:40 UTC
Labels: audit, mailserver-incompatibility, needs-reproduction
