### ISSUE TITLE
Frozen app when there are more than 15 messages in a thread

### ISSUE THREAD

**Issue by Dilliaglio** [Foundry376/Mailspring#951] opened 2018-06-25 10:29 UTC
Using macOS Sierra 10.12.6. and MailSpring Version 1.2.2.

When trying to reply to the latest email in a thread mailspring will either freeze for a while (only to be helped with a restart) or it will crash altogether.

**Comment by sbosque** [comment] 2018-09-10 14:29
Using Windows 10 and Mailspring 1.4.2-f587b7b7 also freezes. I am unsure about the real cause.

How could we help you to identify the root cause? 

How could I send you log files or evidences to help you diagnose this?

Thanks

**Comment by CodeMouse92** [comment] 2021-02-11 18:43
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/significant-lag-on-large-threads/183

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-11 18:43 UTC
Labels: audit
