### ISSUE TITLE
Gmail not syncing properly

### ISSUE THREAD

**Issue by purusharths** [Foundry376/Mailspring#1571] opened 2019-07-11 08:44 UTC
I recently switched from Thunderbird to Mailspring, but there's some problem with Gmail sync in mailspring. My college account is working properly, but Gmail is having sync issues. I have even disabled the secure app on the concerned Gmail account. 

##### Are there any related issues?

https://github.com/Foundry376/Mailspring/issues/1066
(It's same but not exactly, since I am able to log in properly, but not able to get new emails or send new emails).
...

##### What operating system are you using?
Fedora 30
...

##### What version of Mailspring are you using?
v1.6.3-134a0e55
...

--

**Bug?**

##### Is this an email sync or connection issue?

Yes, sync issue.
[mailsync-4dfafd6d.log](https://github.com/Foundry376/Mailspring/files/3381072/mailsync-4dfafd6d.log)

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?
![Screenshot from 2019-07-11 14-05-13](https://user-images.githubusercontent.com/5101224/61035614-211e8f80-a3e5-11e9-8730-cd9927ed12c6.png)

...

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?
Not a feature request per se, but I was not facing the sync problem with Thunderbird

.
...

**Comment by Ulver56** [comment] 2019-07-13 02:52
Same thing with Gmail.

**What operating system are you using?**
Arch Linux

**What version of Mailspring are you using?**
1.6.3-134a0e55

**Comment by 0msLaw** [comment] 2019-07-13 10:11
Same issue with Gmail

**What operating system are you using?**
Ubuntu 18.04 LTS

**What version of Mailspring are you using?**
1.6.3-134a0e55

**Comment by CodeMouse92** [comment] 2021-02-01 19:24
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/database-is-locked/420

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-01 19:24 UTC
Labels: audit
