### ISSUE TITLE
Sent date always showing Dec 31, 1969

### ISSUE THREAD

**Issue by RyanNerd** [Foundry376/Mailspring#893] opened 2018-05-25 16:58 UTC
##### What operating system are you using?
Linux Mint 18.2 (This issue is also present on the Mac)

##### What version of Mailspring are you using?
1.2.1-7e7447b6

--

Also see: #949 

--

**Bug**
##### Do you have any third-party plugins installed? If so, which ones?
None

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Yes: Godaddy
My test with gmail had the correct sent date.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
![image](https://user-images.githubusercontent.com/10543911/40556423-d004a118-6009-11e8-8e01-caf0f67d2244.png)

Apparently Mailspring is using the mail server's sent date (which in Godaddy's case is always Dec 31, 1969). Probably shouldn't use the mail server's date time stamp and use the local system date time instead.

**Comment by gzparker** [comment] 2018-11-16 22:04
I have this same issue, where are we with this bug?

**Comment by akanarsky** [comment] 2020-01-07 08:43
I have the same issue, Linux Mint 18.3, the account is hosted by GoDaddy. Is there a way to work around this bug?

**Comment by CodeMouse92** [comment] 2021-02-05 00:02
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/sent-date-always-showing-1969-or-1970/471

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@RyanNerd Thanks for the screenshot. We've migrated that as part of the bug report.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-05 00:02 UTC
Labels: audit
