### ISSUE TITLE
Feature request: "Mark as read on reply"

### ISSUE THREAD

**Issue by jotaf98** [Foundry376/Mailspring#956] opened 2018-06-27 19:06 UTC
I like to mark emails as read explicitly. However it would speed this up if there was an option to mark them automatically on reply (or other actions, although just on reply would be pretty good already!).

**Comment by bengotow** [comment] 2018-07-08 07:18
Ahh man that's a great idea - I haven't heard of "Mark as read on reply", but I could see that being a nice workflow. If anyone wants to take a stab at this, it'd actually be a great first contribution. Right now, the app has a setting called `markAsReadDelay` which is an integer, and we'll probably want to make it a string value so there can be a non-numeric delay (eg: "on-send").

**Comment by sNiXx** [comment] 2018-10-29 11:48
That is a great idea! In combination with higher values for mark as read (i.e. >"After 2 seconds") this would prove rather useful!

**Comment by MurzNN** [comment] 2018-12-20 09:59
> In combination with higher values for mark as read (i.e. >"After 2 seconds") this would prove rather useful!

Does the delay for mark as read already exists? I can't find it in settings.

**Comment by pocky** [comment] 2019-02-26 16:57
@bengotow +1 on this feature, I use Airmail on MacOS with "manually mark as read" and I think this feature should be on Mailspring because I need to read an email before reply to his sender :smile:.

**Comment by CodeMouse92** [comment] 2021-02-08 18:50
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/keep-the-next-email-unread-after-archiving/492

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@jotaf98: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-08 18:50 UTC
Labels: audit, composer, good first issue
