### ISSUE TITLE
Links not working

### ISSUE THREAD

**Issue by Galvanize87** [Foundry376/Mailspring#1471] opened 2019-04-22 03:21 UTC
Installing Mailspring in Deepin with snapd, the links inside the messages don't work by clicking on it. Mailspring doesn't open any browser. Recognizes the links and allows to copy but mailspring is not opening any browser when links inside mails are selected.

**Comment by bengotow** [comment] 2019-05-26 22:17
Hey! Thanks for reporting this - I tried reproducing this but I haven't had any luck so far. Might need to get a Deepin VM spun up and install Mailspring. Anyone else seeing this issue?

**Comment by mjlbach** [comment] 2019-10-01 15:15
I have this issue on Fedora 30/31 with Gnome 3.32/3.34 respectively

**Comment by PeetsB** [comment] 2019-11-23 13:51
same issue here
          /:-------------:\          XXX@localhost.localdomain 
       :-------------------::        ------------------------------------- 
     :-----------/shhOHbmp---:\      OS: Fedora release 31 (Thirty One) x86_64 
   /-----------omMMMNNNMMD  ---:     Host: HP EliteBook 745 G3 
  :-----------sMMMMNMNMP.    ---:    Kernel: 5.3.11-300.fc31.x86_64 
 :-----------:MMMdP-------    ---\   Uptime: 1 day, 5 hours, 37 mins 
,------------:MMMd--------    ---:   Packages: 2483 (rpm), 19 (flatpak) 
:------------:MMMd-------    .---:   Shell: bash 5.0.7 
:----    oNMMMMMMMMMNho     .----:   Resolution: 1366x768 
:--     .+shhhMMMmhhy++   .------/   DE: GNOME 3.34.1 
:-    -------:MMMd--------------:    Theme: Adwaita [GTK2/3] 
:-   --------/MMMd-------------;     Icons: Adwaita [GTK2/3] 
:-    ------/hMMMy------------:      Terminal: gnome-terminal 
:-- :dMNdhhdNMMNo------------;       CPU: AMD PRO A10-8700B R6 4C+6G (4) @ 1.80 
:---:sdNMMMMNds:------------:        GPU: AMD ATI Radeon R5/R6/R7 Graphics 
:------:://:-------------::          Memory: 5129MiB / 7436MiB 
:---------------------://

**Comment by holoGDM** [comment] 2020-01-24 15:31
Same issue here Sway, manjaro. Links are not opening in any browser.

**Comment by PeetsB** [comment] 2020-02-02 08:10
> same issue here
> /:-------------:\ [XXX@localhost.localdomain](mailto:XXX@localhost.localdomain)
> :-------------------:: -------------------------------------
> :-----------/shhOHbmp---:\ OS: Fedora release 31 (Thirty One) x86_64
> /-----------omMMMNNNMMD ---: Host: HP EliteBook 745 G3
> :-----------sMMMMNMNMP. ---: Kernel: 5.3.11-300.fc31.x86_64
> :-----------:MMMdP------- ---\ Uptime: 1 day, 5 hours, 37 mins
> ,------------:MMMd-------- ---: Packages: 2483 (rpm), 19 (flatpak)
> :------------:MMMd------- .---: Shell: bash 5.0.7
> :---- oNMMMMMMMMMNho .----: Resolution: 1366x768
> :-- .+shhhMMMmhhy++ .------/ DE: GNOME 3.34.1
> :- -------:MMMd--------------: Theme: Adwaita [GTK2/3]
> :- --------/MMMd-------------; Icons: Adwaita [GTK2/3]
> :- ------/hMMMy------------: Terminal: gnome-terminal
> :-- :dMNdhhdNMMNo------------; CPU: AMD PRO A10-8700B R6 4C+6G (4) @ 1.80
> :---:sdNMMMMNds:------------: GPU: AMD ATI Radeon R5/R6/R7 Graphics
> :------:://:-------------:: Memory: 5129MiB / 7436MiB
> :---------------------://

as of beginning of 2020 I stop using Mailspring -  thanks for sharing ...

**Comment by jeffrussell37** [comment] 2020-03-12 20:03
I also have this issue.  Fedora 31:
Linux <FQDN> 5.5.7-200.fc31.x86_64 #1 SMP Fri Feb 28 17:18:37 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
I see this has been open since May of 2019.  Will this be looked at, or should I go look for another email client?

**Comment by lilgreggy** [comment] 2020-05-27 01:03
I have this issue on Arch now as well.

**Comment by Galvanize87** [comment] 2020-05-27 08:47
One year after the report and this bug is still present...shame...thats why I stoped using mailspring on work. Thunderbird may be ugly but functional.

**Comment by zakk-h** [comment] 2020-06-03 20:24
I also have this issue on Solus.

**Comment by matthewejacob** [comment] 2020-06-24 15:28
This is still an issue, Fedora 32, gnome. Please fix this, aside from that its a great client, but having to copy and paste every link in an email is not exactly productive seeing this is basic functionality in every other client. Linux is my only daily driver so I have to put up with this all day long. It's been over a year since this was first reported, any updates on the status of this? It didn't behave this way in the previous version I had.

**Comment by codeloopy** [comment] 2020-10-14 21:14
The same issue on Min 19, except, works when it feels like it.
Beautiful client!

**Comment by matthewejacob** [comment] 2020-10-15 02:21
It's still an issue. It seems to be isolated to the snap version. just uninstall the snap version and download the standalone linux version for your distribution. I can't complain too much seeing how it's free. But it has been a bug for a long time. not sure why they won't address it. It does work correctly on the distro specific version. I've been using that way since 31. and i'm pretty sure it's been updated at least once in that time.

**Comment by CodeMouse92** [comment] 2021-01-30 00:53
Hi all,

2020 prevented much development work on Mailspring, but rest assured, development has resumed! We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

<<USER>>: Can you please confirm that this is still broken with 1.8.0, and if so, open a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-30 00:53 UTC
Labels: audit, linux, needs-reproduction
