### ISSUE TITLE
-2 new mail

### ISSUE THREAD

**Issue by duckness** [Foundry376/Mailspring#1450] opened 2019-04-03 13:12 UTC
![mailspring_2019-04-03_21-09-21](https://user-images.githubusercontent.com/6380270/55481382-df977f00-5654-11e9-8595-4d5ec7a70558.png)

##### Are there any related issues?

Don't think so.
...

##### What operating system are you using?

Windows 10
...

##### What version of Mailspring are you using?

1.6.0-10f5c95c
...

--

**Bug?**

##### Is this an email sync or connection issue?

Maybe? 
[mailsync.zip](https://github.com/Foundry376/Mailspring/files/3038799/mailsync.zip)

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Don't think so.
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Probably not.

**Comment by CodeMouse92** [comment] 2021-02-04 23:47
🤣 That's beautiful. You should consider -2 mail quite an accomplishment!

I can't find any other references to this bug occurring, and it's likely to be *really* hard to reproduce. Since this appears to be isolated, I will close it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-04 23:47 UTC
Labels: audit
