### ISSUE TITLE
Bug: Labels Issue with Gmail and moving to folder

### ISSUE THREAD

**Issue by simonfben** [Foundry376/Mailspring#2250] opened 2021-01-06 12:28 UTC
Hello,

This bug happens enough to be very annoying. When I move an email to a folder or if I delete an email from my inbox. The previous email in my inbox is doing the same action.
This causes to lose a lot of emails.
Could you please help me with that?

Setup:
 - OS: Mac OS Catalina
 - OS Version 10.15.7
 - Mailspring Version: 1.7.8

**Comment by CodeMouse92** [comment] 2021-01-17 04:24
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/labels-issue-with-gmail-and-moving-to-folder/61/1

Please consider joining that community and continuing the discussion there! Bonus: if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-17 04:24 UTC
Labels: audit, bug
