### ISSUE TITLE
Unable to add Office 365 account

### ISSUE THREAD

**Issue by muzammilLUMS** [Foundry376/Mailspring#1813] opened 2020-02-25 15:02 UTC
I have added my gmail account it is working fine. But I am unable to add my office 365 account on mailspring. I finish the authentication process and it says that it is adding the count but it does not.

**Comment by AlexDunmow** [comment] 2020-02-26 00:34
Dupe of my issue: #1811

**Comment by benbluegreen** [comment] 2020-03-05 00:00
Same as above.

**Comment by CodeMouse92** [comment] 2021-02-02 23:39
Thank you for your patience on this issue! I know it's frustrating when you cannot connect to your email with Mailspring.

2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be a duplicate of one we've already migrated to Discourse:

https://community.getmailspring.com/t/institutional-office365-not-working/48

Please consider joining that community and continuing the discussion there.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-02 23:39 UTC
Labels: audit
