### ISSUE TITLE
Calendar Release When?

### ISSUE THREAD

**Issue by RayParkerBassPlayer** [Foundry376/Mailspring#1790] opened 2020-01-30 19:46 UTC
Love the app.  I purchased based on futures, with the promise of the calendar integration coming late last year.  Is there a firmer ETA on this?

**Comment by bengotow** [comment] 2020-02-15 20:00
Hey @RayParkerBassPlayer! Sorry for the delay, thanks for upgrading to Mailspring Pro! I got bogged down last fall because Google wanted us to get a third party security audit for continued use of the Gmail APIs. We got that, and were approved for use of CalDav / Google Calendar APIs in the new calendar, so I can ship the calendar this summer! I'll sit down and lay out everything that is left to do and put firmer dates in the roadmap. Stay tuned!

**Comment by RayParkerBassPlayer** [comment] 2020-02-15 20:29
Awesome!  Thank you for getting back to me.

**Comment by Enkhiel** [comment] 2020-02-24 13:18
What about Exchange/Office365 Calendar? I wish I could use Mailsrping for my corporate notebook, but without calendar integration it is more or less a no go.

**Comment by Gaket** [comment] 2020-04-15 13:57
Looking forward to using the Google Calendar in the best email client for Mac! :)

**Comment by CodeMouse92** [comment] 2021-01-18 19:23
Just a heads up for everyone — 2020 prevented much development work on Mailspring, but rest assured, development has resumed! The Calendar features are still high on the priority list.

We are also in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

Please consider joining that community and continuing the discussion there.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-18 19:23 UTC
Labels: audit, product-direction
