### ISSUE TITLE
Bug: Mailspring breaks hyperlinks of proofpoint urldefense urls.

### ISSUE THREAD

**Issue by amorris28** [Foundry376/Mailspring#2150] opened 2020-09-19 16:04 UTC
Many listervs use urldefense to create hyperlinks in emails by appending "https://urldefense.com/v3/__" to before the url and "\__;!!" followed by a series of numbers and letters to the end of the url. Mailspring seems to disrupt these hyperlinks at the "http://" of the inner url so you cannot click the hyperlink, but instead have to highlight the whole line and copy and it into your browser. Occasionally, no hyperlink is generated and the entire url is just printed in plain text. I have examples of both of these in the screenshot below.

To reproduce, subscribe to any listserv that uses proofpoint urldefense and observe any links included in listserv emails. This seems to be becoming standard at universities and other organizations. 

The expected behavior is to create a hyperlink for the *whole* urldefense url starting from the "https://urldefense.com" prefix to the inner url to the "__;!!..." suffix. This is how it works in the web browser email clients that I have tried (Gmail, Webmail). 

![Screenshot from 2020-09-19 08-51-53](https://user-images.githubusercontent.com/16123635/93671300-aaecd280-fa56-11ea-868d-1c09bcce0d6e.png)

 - OS: Ubuntu
 - OS Version: 18.04.5 LTS
 - Mailspring Version: 1.7.8

**Comment by CodeMouse92** [comment] 2021-03-03 03:08
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mailspring-breaks-hyperlinks-of-proofpoint-urldefense-urls/954

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@amorris28: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-03 03:08 UTC
Labels: audit, bug
