### ISSUE TITLE
Sending e-mail with attachments generates error: "Sorry, Mailspring was unable to deliver this message. Connection error - unable to connect to the server / port you provided"

### ISSUE THREAD

**Issue by coldpumpkin** [Foundry376/Mailspring#1602] opened 2019-08-06 09:30 UTC
Currently using IMAP configuration without SSL. Sending and receiving e-mail is working fine except when I'm trying to send an e-mail with any attachment (no matter the format or size). I receive the following error: _"Sorry, Mailspring was unable to deliver this message. Connection error - unable to connect to the server / port you provided"_

##### Are there any related issues?

https://github.com/Foundry376/Mailspring/issues/757
https://github.com/Foundry376/Mailspring/issues/947

##### What operating system are you using?

Windows 10 Home

##### What version of Mailspring are you using?

1.6.3-134a0e55

##### Is this an email sync or connection issue?

Connection (it seems so)

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No. Using own domain's. Works fine on alternative software.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Any kind of attachment, as stated above.

**Comment by coldpumpkin** [comment] 2019-09-03 08:52
Hello?

**Comment by Fregaa** [comment] 2019-11-08 14:24
Same here!! Excellent email client but this problem is a huge turn down, I cant use a email client that can't send attachments.

**Comment by marianarita** [comment] 2020-10-07 09:47
I have the same issue!
Version 1.7.8-13635bcf

![image](https://user-images.githubusercontent.com/46107768/95315458-6cdf1380-088a-11eb-978b-78abbdc02e6d.png)

**Comment by PTSTUDIOS** [comment] 2020-11-12 16:18
I had the exact same problem.  I managed to fix it (fingers crossed) by going into Preferences, Accounts, Update Connection Settings, and trying different port numbers for the Outgoing (SMTP) port.  You may want to search online for all possible ports that your e-mail providers uses.  [This is the reference I used.](https://portal.smartertools.com/kb/a2838/commonly-used-ports-for-smartermail.aspx)  It was port 25 that worked for me in the end.  Strangely, I'm sure that was what I was trying to use to begin with.  Perhaps just the act of trying the alternative ports gave it the nudge it needed!

**Comment by CodeMouse92** [comment] 2021-02-17 22:53
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/sending-e-mail-with-attachments-generates-error-sorry-mailspring-was-unable-to-deliver-this-message-connection-error-unable-to-connect-to-the-server-port-you-provided/673

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@coldpumpkin @Fregaa @marianarita @PTSTUDIOS: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-17 22:53 UTC
Labels: audit
