### ISSUE TITLE
Bug: 126.com sync mail error

### ISSUE THREAD

**Issue by hechengjin** [Foundry376/Mailspring#2102] opened 2020-07-27 08:43 UTC
**Describe the bug**
can't get mails.

**Setup: (please complete the following information):**
OS: Windows 10 edu 64bit
OS Version 17763
Mailspring Version: 1.7.8

`Mailspring Version: 1.7.8-COMMIT_INSERTED_DURING_PACKAGING
Platform: win32
Account State: sync_error
Account Provider: imap
IMAP Server: imap.126.com
SMTP Server: smtp.126.com
--------------------------------------------
15304 [2020-07-27 16:26:22.729] [metadata] [info] Metadata delta stream starting...
15304 [2020-07-27 16:26:22.729] [background] [info] Marking all folders as `busy`
15304 [2020-07-27 16:26:22.730] [background] [info] Syncing folder list...
15304 [2020-07-27 16:26:23.227] [background] [error] Could not create Mailspring container folder: Mailspring. ErrorNonExistantFolder
15304 [2020-07-27 16:26:23.268] [background] [error] Could not create required Mailspring folder: Mailspring/Snoozed. ErrorNonExistantFolder
15304 [2020-07-27 16:26:23.269] [background] [info] Syncing folder list...
15304 [2020-07-27 16:26:23.350] [background] [error] Could not create Mailspring container folder: Mailspring. ErrorNonExistantFolder
15304 [2020-07-27 16:26:23.399] [background] [error] Could not create required Mailspring folder: Mailspring/Snoozed. ErrorNonExistantFolder
15304 [2020-07-27 16:26:23.459] [background] [info] syncFolderUIDRange for INBOX, UIDs: 1 - 4294967296, Heavy: false
15304 [2020-07-27 16:26:23.638] [foreground] [info] Connection does not support idling. Locking until more to do...
15304 [2020-07-27 16:26:23.741] [background] [critical] 
***
*** Mailspring Sync 
*** An exception occurred during program execution: 
*** {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID","key":"ErrorNonExistantFolder","retryable":false,"what":"Unknown exception"}
***`

**Comment by x93008** [comment] 2020-07-28 15:01
linux也出现了这个问题(Linux also has this problem)
Mailspring Version: 1.7.8-13635bcf
Platform: linux
Account State: sync_error
Account Provider: imap
IMAP Server: imap.163.com
SMTP Server: smtp.163.com
--------------------------------------------
391142 [2020-07-28 22:46:51.724] [background] [error] Could not create required Mailspring folder: Mailspring/Snoozed. ErrorNonExistantFolder
391142 [2020-07-28 22:46:51.797] [background] [info] syncFolderUIDRange for INBOX, UIDs: 1 - 4294967296, Heavy: false
391142 [2020-07-28 22:46:52.001] [background] [critical] 
***
*** Mailspring Sync 
*** An exception occurred during program execution: 
*** {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID","key":"ErrorNonExistantFolder","retryable":false,"what":"std::exception"}
***

391142 [2020-07-28 22:46:52.002] [background] [critical] *** Stack trace (line numbers are approximate):
*** ??:?        SyncWorker::syncFolderUIDRange(Folder&, mailcore::Range, bool, vector*)
*** ??:?        SyncWorker::syncNow()
*** ??:?        runBackgroundSyncWorker()
*** main.cpp:?  main::{lambda()#3}::operator()() const
*** main.cpp:?  _Bind_simple::operator()()
*** main.cpp:?  thread::_Impl::_M_run()
*** thread.o:?  execute_native_thread_routine()
***

391509 [2020-07-28 22:46:53.024] [main] [info] Identity created at 1595906869 - using ID Schema 1
391509 [2020-07-28 22:46:53.026] [main] [info] ------------- Starting Sync (x93008@163.com) ---------------
391509 [2020-07-28 22:46:53.036] [metadata] [info] Metadata delta stream starting...
391509 [2020-07-28 22:46:57.035] [background] [info] Marking all folders as `busy`
391509 [2020-07-28 22:46:57.041] [background] [info] Syncing folder list...
391509 [2020-07-28 22:46:57.564] [background] [error] Could not create Mailspring container folder: Mailspring. ErrorNonExistantFolder
391509 [2020-07-28 22:46:57.604] [background] [error] Could not create required Mailspring folder: Mailspring/Snoozed. ErrorNonExistantFolder
391509 [2020-07-28 22:46:57.609] [background] [info] Syncing folder list...
391509 [2020-07-28 22:46:57.690] [background] [error] Could not create Mailspring container folder: Mailspring. ErrorNonExistantFolder
391509 [2020-07-28 22:46:57.730] [background] [error] Could not create required Mailspring folder: Mailspring/Snoozed. ErrorNonExistantFolder
391509 [2020-07-28 22:46:57.779] [background] [info] syncFolderUIDRange for INBOX, UIDs: 1 - 4294967296, Heavy: false
391509 [2020-07-28 22:46:57.951] [background] [critical] 
***
*** Mailspring Sync 
*** An exception occurred during program execution: 
*** {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID","key":"ErrorNonExistantFolder","retryable":false,"what":"std::exception"}
***

391509 [2020-07-28 22:46:57.952] [background] [critical] *** Stack trace (line numbers are approximate):
*** ??:?        SyncWorker::syncFolderUIDRange(Folder&, mailcore::Range, bool, vector*)
*** ??:?        SyncWorker::syncNow()
*** ??:?        runBackgroundSyncWorker()
*** main.cpp:?  main::{lambda()#3}::operator()() const
*** main.cpp:?  _Bind_simple::operator()()
*** main.cpp:?  thread::_Impl::_M_run()
*** thread.o:?  execute_native_thread_routine()
***

**Comment by CodeMouse92** [comment] 2021-02-10 22:10
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/cannot-sync-126-163-mails-because-setting-up-snooze-subfolder-in-mail-folders-is-not-allowed/562

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@hechengjin @x93008: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

P.S. Duplicate of #1576

**Closed by CodeMouse92** 2021-02-10 22:10 UTC
Labels: audit, bug
