### ISSUE TITLE
buy an annual license or lifetime license for private use

### ISSUE THREAD

**Issue by franco27** [Foundry376/Mailspring#410] opened 2017-12-07 13:32 UTC
Hello 

I have set up 6 email accounts in Mailspring.
I often have this message: "You have set more than 4 accounts, please consider the purchase of the Pro version".
![mailspring_2017-12-07_14-19-45](https://user-images.githubusercontent.com/31793920/33717534-91769d04-db5a-11e7-90da-374445102908.png)

I do not have a professional use of Mailspring and I do not conceive to pay a subscription.

It's a pity that there is not an intermediate version with some Pro functions (Read receipts + creating unlimited email accounts) with a modest payment

When I compare Mailspring to other messaging software and for the moment, Mailspring's features are low.
and buying a license for these softwares is much less expensive but I really like your software!

**Comment by tenten8401** [comment] 2017-12-07 13:53
The thing with Mailspring is for the Pro versions, it uses their servers for link tracking, or it wouldn't work if your email client closed. The message you mention is not forcing you to pay for Pro, but rather reminding you that you should support the project if you find it useful.

**Comment by franco27** [comment] 2017-12-07 14:08
For Nylas N1, I knew that for its operation servers were used. But with the availability of Nylas Mail (initial version) I seemed to have read that it was not the case anymore ...

just to support Mailspring, a less expensive license or payment for private use would be appreciated

**Comment by tenten8401** [comment] 2017-12-07 14:10
Mailspring no longer uses their own servers for syncing, but they do still
do it for mail tracking and whatnot. I do agree that there should be a
cheaper option though.

**Comment by bengotow** [comment] 2017-12-08 02:24
Hey folks! Thanks for the feedback and support—I've heard this from a few other folks, and I think we'll definitely try to create a cheaper paid version in the future aimed at users that want to support development and use snoozing, etc., but don't need the other pro features or rich contact profiles (which is actually the biggest cost driver). Stay tuned!

**Comment by surajmandalcell** [comment] 2018-02-02 11:17
any updates on this yet?

**Comment by fcristel** [comment] 2018-07-11 22:02
Any private use licence yet?

**Comment by sNiXx** [comment] 2018-10-14 20:42
Bumping this once again - any updates? For personal use I find 8$ per month prohibitively expensive, especially if one only requires snoozing, send later and so on.

**Comment by coagmano** [comment] 2018-10-28 22:44
I'd be more willing to pay something like $50 USD once off for the features that don't have an ongoing cost for you

**Comment by pablitok** [comment] 2018-11-01 19:51
Same here, I'd love to have the pro version and support this awesome app, but it's really expensive here in Argentina. IMHO, the lifetime license sounds like a good idea

**Comment by coagmano** [comment] 2018-11-05 23:06
Actually, f-it. Since I said I don't care about the premium features, I've just put my money where my mouth is and subscribed. 
I can always stop it after 6 mo to make it end up at ~$50 total

It's a slow once-off, but it's a once-off haha

**Comment by franco27** [comment] 2018-12-29 21:51
So has a decision been made for a less expensive license for individuals?

**Comment by mjoppich** [comment] 2019-01-19 11:58
A lifetime version without the server-based pro-features would be great.

I don't need the tracking for whether an email was read or not, etc. - but I would like to include more than 4 mailboxes.

**Comment by washingtonphp** [comment] 2019-01-31 14:57
I'm using more than 4 account for a while. I got the message, but all accounts works fine. So, no issue here

**Comment by zenom** [comment] 2019-04-11 13:20
I too think $8 a month is high for some of the features that I would use.  $3-5 I would do.

**Comment by GitSomeSource** [comment] 2019-06-11 17:59
No one buys a brand new truck and says ... it's only going to cost me $400 per month ... but I won't do the math re how many months I plan to drive it and pay for it. Unless everyone else in this thread is geriatric ... you're all going to be using email for decades. I own licenses for many other mail clients ... most were between $15-$50 as a one-time cost. $8/month sounds cheap ... UNLESS YOU THINK ABOUT IT ... then it's an absurd amount. As you look back in 5 years at the $480 you spent on Mailspring and you're still stuck paying for it remember this post. There is no SAAS value here folks ... no millions of dollars in required hosting resources that need to be amortized ... there is no real value proposition that would justify the price disparity re other mail client options. C'mon! I like Mailspring ... and so I'll pay for it ...  but just charge us $50 ... once ... and move on. If you EVER come out with some amazing new features ... charge us to upgrade. The current pricing scheme is just giving MailSpring a poor reputation.

**Comment by franco27** [comment] 2019-06-11 21:29
I would like a decision to be made on that.  Either you maintain a subscription membership and in this case I uninstall your software. Or you allow us to buy a license without a subscription. and in that case, I'll wait for the price to make a decision. 
We are still waiting for an answer.

**Comment by TheSHEEEP** [comment] 2019-08-02 11:43
I'd also gladly pay a fixed price for software that I use regularly. 
But a monthly price of 8$ just to be able to link in more email accounts (I don't have a user for the other Pro options, really)? Which would rack up to hundreds of dollars over the years? Yeah... no.

**Comment by dharjai** [comment] 2019-08-19 05:46
Any update so far on one time license

**Comment by Rickeo** [comment] 2019-08-29 00:12
Yes, I also find the cost too high.

Thunderbird felt a little dated for me and was buggy in areas, been giving MailSpring a try and love it so far, I used to use MailBird on Windows but there was nothing similar on Linux until I came across MailSpring that was.

The issue was MailBird has a pay once, lifetime license, I understand that, that may not be ideal to continually support a project and pay for salaries but $8 is just too high. Paying monthly I'd want to pay between $2 and $3 at a PUSH the highest I MAY consider is $4 but $8 is just out of the range for me.

It's at a price where I'm willing to put up with the bugs of Thunderbird and if I was going to pay that price, I'd rather go the full hog, add a couple of dollars and get tons of additional features by switching to a webmail platform such as gsuite or office365 sure it doesn't come with desktop / linux support but I can do without that.

MailSpring really need to review their pricing as I feel they could be losing a lot of custom due to this.

**Comment by demogorgonz** [comment] 2019-12-05 08:28
I agree with other folks, $85 per year or $8/month is a lot for email client.

Another issue is that **i have 4 accounts** and i still see notification that says i am using **MORE than 4** accounts which is annoying.. 

Personal licence at cheaper price would be a win/win situation for client base and Mailspring business.

**Comment by juliankoehn** [comment] 2020-01-05 21:05
(Bump)

If i am not so wrong, i can get for 10 bucks / month 1 exchange mailbox from Microsoft PLUS Office 365? Compared to that the Price for Mailspring is insane. 

Looking at Mailbird: https://www.getmailbird.com/pricing/ their pricing for subscription based varies between 2-4 USD / month. I purchases a Pro (Old Licensing model) license for around 80 USD a year or 2 ago.

Rethink your Pricing -> get more customers. I am not willing to subscribe for 8$ / Month, but i would pay once up to 100$ for a good Mailclient and i would pay for Upgrades!

**Comment by pleone** [comment] 2020-05-13 15:48
Bump.
Totally agree with this thread 8 per month is too much and I'm not willing to subscribe, but something between 2/4$ per month to have some pro features (maybe not all of them or not the most expensive for you ) would totally be acceptable.
Also a one time payment would be cool; not sure about the 100$ @juliankoehn was suggesting.

At the moment i'm ok with the free tier, but i would pay to have some nice features like read receipts :smiley: 

To me mailspring is the best mail client on linux, so you really have good and profitable niche with a review of the pricings.

Besides that, keep on rocking guys! You are doing a great job and thanks for letting us (linux users) have a nice mail client! :smile:

**Comment by adfayed** [comment] 2020-07-09 14:20
Agreeing with this thread, a full one-time payment of $50-$100 (max) sounds still in the reasonable range. Please developers or whoever can reach someone with the right authorities to do this, have them give us their take on this. This issue has been opened 3 years ago since 2017 and is still an ongoing issue. If they wish to make this possible, then they are losing money waiting -if they don't let us know.

**Comment by Deichscheich** [comment] 2020-07-25 09:05
Yes please, 8$ / month is really pricey - can't pay that kind of money. I don't even use all that corporate stuff, yet I would like to support development. 50$ sounds reasonable.

**Comment by CodeMouse92** [comment] 2021-01-28 02:13
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

I'm actually migrating this to a staff conversation to be revisited in the upcoming development cycles.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. We *have* heard you!

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 02:13 UTC
Labels: audit, product-direction
