### ISSUE TITLE
Gmail signatures not showing in message view

### ISSUE THREAD

**Issue by isteptoe** [Foundry376/Mailspring#1717] opened 2019-11-20 22:51 UTC
##### What operating system are you using?

Windows 10

##### What version of Mailspring are you using?

--1.7.2-4522b259

**Bug?**

When opening emails with signatures from gmail, Mailspring seems to cut the signatures off and does not display them in the message view. The signatures are still there, however, and if I forward or reply to them, the signature is displayed again. 
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

... I have only seen this happen with gmail signatures

##### Is the issue reproducible with a particular attachment, message, signature, etc?

A message that the signature gets cut off in. "This is the message" is the message and "Testing" is the signature. It was sent from gmail online, the lower part of the picture shows the message displayed in Mailspring. You can see that the signature "Testing" is displayed in the preview, but not in the actual message. 

![image](https://user-images.githubusercontent.com/40774387/69283898-51f4a980-0bbb-11ea-8d23-843e30f47633.png)

This, however, doesn't happen all the time. Below is a picture that shows the same message in a different email, but this time, it does include the signature.
![image](https://user-images.githubusercontent.com/40774387/69284269-376f0000-0bbc-11ea-8174-703638c5e9db.png)

When viewing the original source of the two messages, there is only one thing that I could tell was different. 
This one is from the email that displayed the signature
```

--000000000000750d420597cde07b
Content-Type: text/plain; charset="UTF-8"

This is the message
Testing

--000000000000750d420597cde07b
Content-Type: text/html; charset="UTF-8"

<div dir="ltr">This is the message<br clear="all"><div><div dir="ltr" data-smartmail="gmail_signature"><div dir="ltr"><div><div dir="ltr">Testing</div></div></div></div></div></div>

--000000000000750d420597cde07b--
```
The second one is from the message that did not display the signature

```
--0000000000009d7fd10597cdedbb
Content-Type: text/plain; charset="UTF-8"

This is the message
Testing

--0000000000009d7fd10597cdedbb
Content-Type: text/html; charset="UTF-8"

<div dir="ltr">This is the message<br clear="all"><div><div dir="ltr" class="gmail_signature" data-smartmail="gmail_signature"><div dir="ltr"><div><div dir="ltr">Testing</div></div></div></div></div></div>

--0000000000009d7fd10597cdedbb--
```
The only difference that I could tell is that the second one has a class="gmail_signature" that the first one does not have.

After getting the email that displayed the signature properly, I could not reproduce it. All the test emails I sent cut off the signature in the display.

Is there any way to force the display of the signatures?

**Comment by vanquang9387** [comment] 2019-12-20 07:52
I got same problem.

**Comment by hnq90** [comment] 2019-12-20 07:54
I got same issue.

**Comment by HM-PAN** [comment] 2020-09-09 00:53
+1

**Comment by Sabrout** [comment] 2020-12-08 09:46
same here

**Comment by CodeMouse92** [comment] 2021-02-18 00:26
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/gmail-signatures-not-showing-in-message-view/682

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@isteptoe: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-18 00:26 UTC
Labels: audit
