### ISSUE TITLE
Read mail turning back into unread mail

### ISSUE THREAD

**Issue by 512DuncanL** [Foundry376/Mailspring#2118] opened 2020-08-09 03:37 UTC
**Describe the bug**
Mail from Gmail that I read earlier on turns into unread mail. Not sure if this only affects Gmail (my office 365 mail is not syncing at all)

**To Reproduce**
1. Go to Inbox
2. Click on unopened mail
3. Wait a day or so
4. See mail you previously read have the unread icon next to it

**Expected behavior**
Read mail should stay read

**Setup: (please complete the following information):**
 - OS: macOS
 - OS Version: 10.14.5
 - Mailspring Version: 1.7.8

**Comment by DanielAtwood** [comment] 2020-08-17 21:20
This affects my Gmail too on both the latest macOS and Pop!_OS.

**Comment by ekawahyu** [comment] 2020-10-11 17:43
I don't think this is provider specific, cause it affects my Yahoo. There is no pattern that I can see, it happens randomly to recent emails

**Comment by CodeMouse92** [comment] 2021-03-02 18:16
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/disappearing-emails-desync/428

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 18:16 UTC
Labels: audit, bug
