### ISSUE TITLE
support for single protocol accounts (IMAP or SMTP)

### ISSUE THREAD

**Issue by working-name** [Foundry376/Mailspring#1575] opened 2019-07-13 02:32 UTC
##### Are there any related issues?

Possibly: https://github.com/Foundry376/Mailspring/issues/1569

##### What operating system are you using?

MacOS, Windows, Arch

##### What version of Mailspring are you using?

Whatever the latest release is
--

**Feature Request?**

There are plenty of options out there for sending encrypted email which can be opened by the recipient via a web portal. That's commonly used in HIPAA compliant communication. eM Client has/had a feature where you could simply uncheck one of the protocols for the account in question - be it IMAP, or SMTP. That makes it usable. As it is right now your software refuses to send email from an account with an IMAP error although SMTP details are valid. 

There's no way to ignore an account when checking for new mail either, which is a feature I've seen in a few prominent clients.

It would be extremely awesome if you were able to implement single-protocol email accounts to be used as either storage/organization (IMAP vs local mailboxes for availability) or for encrypted email sending (you only send, you don't save sent mail to Sent folder, no IMAP needed).

Thanks!

##### Does this feature exist in another mail client or tool you use?

Yes, eM Client.

**Comment by CodeMouse92** [comment] 2021-02-03 00:07
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/make-smtp-or-imap-optional-read-only-or-send-only-accounts/134

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@working-name: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-03 00:07 UTC
Labels: audit
