### ISSUE TITLE
SMTP Error when Sending from an Alias

### ISSUE THREAD

**Issue by jGleitz** [Foundry376/Mailspring#307] opened 2017-11-05 18:36 UTC
If I send using an alias I have set up, I get the following error:

![message send error](https://user-images.githubusercontent.com/4305652/32417863-ec72cdf4-c25f-11e7-9243-628d4f19b7b5.png)

There is nothing of interest logged to the console. The mailsync log contains these lines:
```
2175 [2017-11-05 19:16:27.789] [main] [info] [local-c4749333-5a75] Running SyncbackDraftTask performLocal:
2175 [2017-11-05 19:16:27.790] [main] [info] [local-c4749333-5a75] -- Succeeded. Changing status to `remote`
2175 [2017-11-05 19:16:27.815] [foreground] [info] Idle exited with code 0
2175 [2017-11-05 19:16:27.816] [foreground] [info] [local-c4749333-5a75] Running SyncbackDraftTask performRemote:
2175 [2017-11-05 19:16:27.816] [foreground] [info] [local-c4749333-5a75] -- Succeeded. Changing status to `complete`
2175 [2017-11-05 19:16:27.816] [foreground] [info] Idling on folder INBOX
2175 [2017-11-05 19:16:32.760] [main] [info] [local-2b66ce49-53c8] Running DestroyDraftTask performLocal:
2175 [2017-11-05 19:16:32.761] [main] [info] -- Hiding / detatching drafts while they're deleted...
2175 [2017-11-05 19:16:32.769] [main] [info] -- Replacing local ID Krb5MktkTH3vV5bFXUNqJjrG8tuuoQcE2czFiZSTv with deleted-mN5A6XsuHLwk0xWyNLDLf2ECKAuXTXm6Bhwu3MOz
2175 [2017-11-05 19:16:32.773] [main] [info] [local-2b66ce49-53c8] -- Succeeded. Changing status to `remote`
2175 [2017-11-05 19:16:32.798] [foreground] [info] Idle exited with code 0
2175 [2017-11-05 19:16:32.798] [foreground] [info] [local-2b66ce49-53c8] Running DestroyDraftTask performRemote:
2175 [2017-11-05 19:16:32.799] [foreground] [info] -- Identified `trash` folder: Trash
2175 [2017-11-05 19:16:32.799] [foreground] [info] [local-2b66ce49-53c8] -- Succeeded. Changing status to `complete`
2175 [2017-11-05 19:16:32.799] [foreground] [info] Idling on folder INBOX
2175 [2017-11-05 19:16:53.356] [main] [info] [local-5ae3dd72-c0ba] Running SendDraftTask performLocal:
2175 [2017-11-05 19:16:53.357] [main] [info] [local-5ae3dd72-c0ba] -- Succeeded. Changing status to `remote`
2175 [2017-11-05 19:16:53.381] [foreground] [info] Idle exited with code 0
2175 [2017-11-05 19:16:53.382] [foreground] [info] [local-5ae3dd72-c0ba] Running SendDraftTask performRemote:
2175 [2017-11-05 19:16:53.383] [foreground] [info] - Sending draft local-a9627af6-2d21@Lovelace
2175 [2017-11-05 19:16:53.383] [foreground] [info] -- Identified `sent` folder: Sent
2175 [2017-11-05 19:16:53.384] [foreground] [info] -- Identified `trash` folder: Trash
2175 [2017-11-05 19:16:53.384] [foreground] [info] -- Sending a single message body to all recipients:
2175 [2017-11-05 19:16:53.686] [foreground] [info] -X An SMTP error occurred: ErrorSendMessage
2175 [2017-11-05 19:16:53.712] [foreground] [error] [local-5ae3dd72-c0ba] -- Failed ({"debuginfo":"ErrorSendMessage","key":"send-failed","retryable":false,"what":"std::exception"}). Changing status to `complete`
2175 [2017-11-05 19:16:53.713] [foreground] [info] Idling on folder INBOX
```

Sending the mail succeeds, however, if I use the address that I set the account up with instead of an alias.

Note that my server is configured to allow aliases, and sending the same E-Mail from Thunderbird succeeds.

##### Are there any related issues?
Could not find any.

##### What operating system are you using?
Ubuntu 17.10

##### What version of Mailspring are you using?
1.0.7

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
None

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I use IMAP

##### Is the issue reproducible with a particular attachment, message, signature, etc?
A message with an alias as from-address

**Comment by AramLoosman** [comment] 2019-06-26 15:26
Same here!

**Comment by CodeMouse92** [comment] 2021-01-29 23:14
Hi all,

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

@jGleitz or @AramLoosman: Can you please confirm that this is still broken with 1.8.0, and if so, open a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-29 23:14 UTC
Labels: audit
