### ISSUE TITLE
Sent email dissapearing afterwards

### ISSUE THREAD

**Issue by GAPP99** [Foundry376/Mailspring#1105] opened 2018-09-29 11:43 UTC
##### What operating system are you using?
Windows 10 x64
...

##### What version of Mailspring are you using?
1.4.2
...

--

**Bug?**

##### Is this an email sync or connection issue?
I'm not sure. It could be something about the sync.

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I'm not 100% sure, but it seems to be affecting the emails through Zoho mostly.
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?
So the issue is that whenever I send an email, the "Sent" folder will sometimes not be in there for hours and hours. If I close down Mailspring and re-open it, it may be there though, just to then disappear after 10-20 seconds, and this continuously happen with other emails too in the "Sent" folder. It kinda just seems to sync completely on random.

I've tried to "Sync New Emails", "Rebuild Cache" and "Update Connection Settings", but it just keeps happening.

I can send a small video clip of how it looks, if you give me an email address.

...

--

**Comment by purefan** [comment] 2018-10-02 08:51
Just to be sure, is the actual email that disappears from the Sent folder, or is the entire Sent folder that disappears from the sidebar? 

Also, do you have more than one mail account enabled?

**Comment by CodeMouse92** [comment] 2021-02-02 02:44
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/disappearing-emails-desync/428

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-02 02:44 UTC
Labels: audit
