### ISSUE TITLE
Feature Request: Add paypal as payment method for PRO version

### ISSUE THREAD

**Issue by skonsoft** [Foundry376/Mailspring#1906] opened 2020-04-16 13:21 UTC
Hello,

I want to buy the pro version but i dont want to insert my  credit card information.

Can you add paypal as payment method please ?

![Capture d’écran du 2020-04-16 15-10-03](https://user-images.githubusercontent.com/446939/79460275-de818780-7ff4-11ea-9de8-d3df07478cfd.png)

Reagrds

**Comment by bengotow** [comment] 2020-04-16 15:25
Hey @skonsoft — thanks for filing this, I appreciate your interest in purchasing Mailspring! I will see if we can do this in the future - there's quite a bit of overhead in implementing subscriptions for a new payment provider (since we also need to support cancelling / changing plans, etc.) but this comes up every month or two so it seems like it'd be worth the time. Stay tuned!

**Comment by CodeMouse92** [comment] 2021-02-27 03:03
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/add-paypal-as-payment-method-for-pro-version/853

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-27 03:03 UTC
Labels: audit, enhancement
