### ISSUE TITLE
BUG: SMTP Setup failed due to email@invalid.com

### ISSUE THREAD

**Issue by Conspir3D** [Foundry376/Mailspring#768] opened 2018-03-19 10:12 UTC
I just installed mailspring and wanted to setup an imap account.

but during setup it failed by trying to send a mail to email@invalid.com .... WTF? Why is it trying to send a testmail to an invalid mailaddress which obviousy will fail!

---------SMTP----------
220 mail.hostinprovider.com ESMTP Speedbone Mailservice
EHLO soldberg
250-mail.hostinprovider.com
250-PIPELINING
250-SIZE 71303168
250-VRFY
250-ETRN
250-AUTH PLAIN LOGIN CRAM-MD5
250-AUTH=PLAIN LOGIN CRAM-MD5
250-ENHANCEDSTATUSCODES
250 8BITMIME
AUTH CRAM-MD5
334 PDQ1OTUxMTI1MjQzMTIwOTguMTUyMTQ1NDI0OEBtYWlsMDE+
amFuQGdpZWJlbHMuYml6IGMzNzE2ZDcwMDc5ZjY0MTQzNzg1NDBhMDA1ODQyM2M5
235 2.7.0 Authentication successful
MAIL FROM:<xx@xxxxxx.com>
250 2.1.0 Ok
RCPT TO:<email@invalid.com>
577 5.1.1 <email@invalid.com>: Recipient address rejected: undeliverable address: host gw-mail4.jodoshared.com[173.0.129.9] said: 550 sorry, no mailbox here by that name (#5.1.1) (in reply to RCPT TO command)

SMTP Last Response Code: 577

SMTP Last Response: 5.1.1 <email@invalid.com>: Recipient address rejected: undeliverable address: host gw-mail4.jodoshared.com[173.0.129.9] said: 550 sorry, no mailbox here by that name (#5.1.1) (in reply to RCPT TO command)

Any solutions to this or am i just oing something completly wrong?

Thanks

Jan

**Comment by bengotow** [comment] 2018-03-19 20:54
Hey! So I actually hadn't looked in to how the libmailcore library we use "verifies" SMTP connections, but it looks like this behavior is expected:

<img width="758" alt="image" src="https://user-images.githubusercontent.com/1037212/37621594-baec157a-2b95-11e8-8ddd-735d15d190cd.png"> (https://github.com/MailCore/mailcore2/blob/260c91078bef3d04b6b5e0de65ad56d58a9ac4bc/src/core/smtp/MCSMTPSession.cpp#L660)

It seems that when we try to validate your SMTP credentials, a standard part of that is trying to issue a `rcpt` command and making sure you aren't blocked. This seems strange to me though... not sure what a good fix would be. Oddly it doesn't seem like there are any complaints on the mailcore2 repo...

**Comment by Conspir3D** [comment] 2018-03-20 09:56
A good fix would be to turn off SMTP verification with a checkbox as an option, as i can see in the log, the credentials are correct ;)

I just don't understand how someone could use a hardcoded mailaddress in a generic library!?

**Comment by Conspir3D** [comment] 2018-03-20 10:01
Maybe these threads can give further informations:
https://stackoverflow.com/questions/27825359/smtp-an-error-occurred-while-sending-the-message
https://github.com/MailCore/mailcore2/issues/1033

**Comment by peternormann** [comment] 2018-10-04 17:43
I just had the same issue, and this is how I fixed it:

1. Log in to your gmail account
2. Go to settings
3. Assuming IMAP is enabled, go to LABELS
4. Check the label 'All Mail' so that it is not hidden in IMAP
5. Profit

**Comment by Conspir3D** [comment] 2018-10-04 21:07
This maxy work with gmail account but "other" IMAP Accounts may not have this option. But it's a while ago, maybe i give it another try.

**Comment by Conspir3D** [comment] 2018-10-04 21:33
still problematic on some hosts, maybe it's also a misconfiguration on some mailproviders end

**Comment by serhattsnmz** [comment] 2018-11-19 14:35
Same issue here. Try to add Yandex account but get following error.

`This account is invalid or Mailspring could not find the Inbox or All Mail folder. `

> I just had the same issue, and this is how I fixed it:
> 
> 1. Log in to your gmail account
> 2. Go to settings
> 3. Assuming IMAP is enabled, go to LABELS
> 4. Check the label 'All Mail' so that it is not hidden in IMAP
> 5. Profit

Try to find it in Yandex but it looks like Yandex doesn't have this option.

**Comment by cr1st1p** [comment] 2018-11-21 18:00
I have the same issue in which I can not add an imap account because it thinks there is a problem with smtp authentication, when in fact it just gets an error for trying email to email@invalid.com.

That type of smtp check seems bogus (hey, server already said to you that authentication was successful!)  and the interpretation of the error code is even more strange.

If this does not get fixed quickly I'll be forced to dump mailspring.

**Comment by artemkaxboy** [comment] 2020-08-27 02:41
Hello!
It affects me as well. Is there any workaround to skip this SMTP checking or change recipient address?

**Comment by CodeMouse92** [comment] 2021-02-03 19:26
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/cannot-setup-imap-account-smtp-check-fails/92

Please consider joining that community and continuing the discussion there!

@Conspir3D: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-03 19:26 UTC
Labels: audit, mailserver-incompatibility

**Comment by CodeMouse92** [comment] 2021-02-03 19:31
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/cannot-setup-imap-account-smtp-check-fails/92

Please consider joining that community and continuing the discussion there!

@Conspir3D: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team
