### ISSUE TITLE
[Feature Request] auto-advance to next conversation upon archive/delete

### ISSUE THREAD

**Issue by leggomyinfo** [Foundry376/Mailspring#1719] opened 2019-11-22 05:41 UTC
This is a Gmail feature I'm discovering I sorely miss.

When you click into an email and archive it, instead of being returned to the inbox, it auto-advances you to the next conversation. You can also choose whether you want to auto-advance to the next newer or next older conversation.

**Comment by CodeMouse92** [comment] 2021-02-08 18:52
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/auto-advance-to-next-conversation-upon-archive-delete/493

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@leggomyinfo: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-08 18:52 UTC
Labels: audit, enhancement
