### ISSUE TITLE
[Feature Request] - Blocks email tracking attempts

### ISSUE THREAD

**Issue by MikoMagni** [Foundry376/Mailspring#1609] opened 2019-08-10 05:50 UTC
##### What operating system are you using?

macOS Mojave 10.14.6

##### What version of Mailspring are you using?

1.6.3

**Feature Request?**

I would love to see an option to block email tracking attempts while displaying standard images.

Canary Mail does this well by automatically blocking most tracking pixels. 

![canary](https://user-images.githubusercontent.com/2527231/62818154-4cca9c00-bb82-11e9-902d-36b12b455f59.png)

Airmail has recently started offering the same feature and so many extensions for Gmail. 

While blocking all remote images is an option, a built-in blocker would be great to have.  

##### Does this feature exist in another mail client or tool you use?

Canary Mail https://canarymail.io/
PixelBlock https://chrome.google.com/webstore/detail/pixelblock/jmpmfcjnflbcoidlgapblgpgbilinlem/

**Comment by bengotow** [comment] 2020-04-15 18:53
Hey! Ahh man this would be very cool. I started looking in to this, and it actually looks like we're blocking a bunch of tracking pixels by default and without really alerting the user. We should probably make the functionality in the existing `remove-tracking-pixels` package optional and present it better. If anyone wants to pick this up, I think it could be structured / communicated almost exactly the way the `messages-autoload-images` plugin is!

**Comment by jeriewang** [comment] 2020-10-04 21:40
Under the current implementation, what will happen if you open an email with mailspring tracking inside another mailspring client? Will the tracking be blocked?

**Comment by CodeMouse92** [comment] 2021-02-26 17:16
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/block-email-tracking-attempts/828

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@MikoMagni @jeriewang: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-26 17:16 UTC
Labels: audit, enhancement, good first issue
