### ISSUE TITLE
"Relay access denied" Issue with SMTP account and sending emails afterwards

### ISSUE THREAD

**Issue by awunder** [Foundry376/Mailspring#763] opened 2018-03-14 10:12 UTC
##### Are there any related issues?

...

##### What operating system are you using?
Windows 10

##### What version of Mailspring are you using?
1.1.5-5834c99f

--

##### Do you have any third-party plugins installed? If so, which ones?
no 3rd party plugins

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
nope, generic smtp

##### Is the issue reproducible with a particular attachment, message, signature, etc?

when creating an account i get an issue in Mailspring like this: https://www.screencast.com/t/tMh6PMef8

> This account is invalid or Mailspring could not find the Inbox or All Mail folder. http://support.getmailspring.com/hc/en-us/articles/115001881912 (SMTP)View Log

However, thats not correct.. after some digging through the smtp log files, i found out that it does try to send an email without actually logging in:

> Mar 14 10:26:00 hq postfix/smtpd[27061]: warning: hostname REDACTED.in-addr.arpa does not resolve to address REDACTED: Name or service not known
> Mar 14 10:26:00 hq postfix/smtpd[27061]: connect from unknown[REDACTED]
> Mar 14 10:26:00 hq postfix/smtpd[27061]: warning: REDACTED.zen.spamhaus.org: RBL lookup error: Host or domain name not found. Name service error for name=REDACTED.zen.spamhaus.org type=A: Host not found, try again
> Mar 14 10:26:00 hq postfix/smtpd[27061]: NOQUEUE: reject: RCPT from unknown[REDACTED]: 554 5.7.1 <email@invalid.com>: Relay access denied; from=<REDACTED@REDACTED> to=<email@invalid.com> proto=ESMTP helo=<DESKTOP-7N0FDKQ>
> Mar 14 10:26:00 hq postfix/smtpd[27061]: lost connection after RCPT from unknown[REDACTED]
> Mar 14 10:26:00 hq postfix/smtpd[27061]: disconnect from unknown[REDACTED] ehlo=1 auth=1 mail=1 rcpt=0/1 commands=3/4

so, just temporarily i disabled the postfix submission_sender_restrictions and was able to create the account.
However, after enabling them back again i wasnt able to actually send an email.. logs look like this (more or less the same):

> Mar 14 10:21:00 hq postfix/smtpd[26623]: warning: hostname REDACTED.in-addr.arpa does not resolve to address REDACTED: Name or service not known
> Mar 14 10:21:00 hq postfix/smtpd[26623]: connect from unknown[REDACTED]
> Mar 14 10:21:00 hq postfix/smtpd[26623]: warning: REDACTED.zen.spamhaus.org: RBL lookup error: Host or domain name not found. Name service error for name=REDACTED.zen.spamhaus.org type=A: Host not found, try again
> Mar 14 10:21:00 hq postfix/smtpd[26623]: NOQUEUE: reject: RCPT from unknown[REDACTED]: 554 5.7.1 <REDACTED@REDACTED.com>: Relay access denied; from=<REDACTED@REDACTED> to=<REDACTED@REDACTED.com> proto=ESMTP helo=<DESKTOP-7N0FDKQ>
> Mar 14 10:21:00 hq postfix/smtpd[26623]: lost connection after RCPT from unknown[REDACTED]
> Mar 14 10:21:00 hq postfix/smtpd[26623]: disconnect from unknown[REDACTED] ehlo=2 starttls=1 auth=1 mail=1 rcpt=0/1 commands=5/6

while sending it from another email client resulted in a "correct behavior":

> Mar 14 10:29:42 hq postfix/submission/smtpd[27254]: connect from localhost.localdomain[127.0.0.1]
> Mar 14 10:29:43 hq postfix/submission/smtpd[27254]: E4289D8152F: client=localhost.localdomain[127.0.0.1], sasl_method=LOGIN, sasl_username=REDACTED
> Mar 14 10:29:44 hq postfix/cleanup[27262]: E4289D8152F: message-id=<REDACTED@REDACTED>
> Mar 14 10:29:44 hq postfix/qmgr[27035]: E4289D8152F: from=<REDACTED@REDACTED>, size=1870, nrcpt=1 (queue active)
> Mar 14 10:29:44 hq postfix/submission/smtpd[27254]: disconnect from localhost.localdomain[127.0.0.1] ehlo=2 starttls=1 auth=1 mail=1 rcpt=1 data=1 quit=1 commands=8
> Mar 14 10:29:44 hq imaps[26578]: starttls: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits reused) no authentication
> Mar 14 10:29:44 hq postfix/smtpd[27265]: connect from localhost.localdomain[127.0.0.1]
> Mar 14 10:29:44 hq postfix/smtpd[27265]: 30BF0D81569: client=localhost.localdomain[127.0.0.1], orig_queue_id=E4289D8152F, orig_client=localhost.localdomain[127.0.0.1]
> ...<snip>

it does work from "remote" too, so dont be overly focused on the localhost vs other hosts

so, to me this looks like it does not login and postfix rejects the send request...

please let me know if you need additional infos, i am more than happy to provide.

thanks
Andreas

**Comment by CodeMouse92** [comment] 2021-02-03 19:28
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/cannot-setup-imap-account-smtp-check-fails/92

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-03 19:28 UTC
Labels: audit

**Comment by CodeMouse92** [comment] 2021-02-03 19:30
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/cannot-setup-imap-account-smtp-check-fails/92

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

P.S. Duplicate of #768
