### ISSUE TITLE
Style Send-Button-Tool-Bar with Fixed Positioning

### ISSUE THREAD

**Issue by Lonniebiz** [Foundry376/Mailspring#1579] opened 2019-07-18 10:45 UTC
When you reply to emails, you typically have to scroll down until the send-button is visible, before you can click it.

On this tool bar, where the send button is located, I'd like the option to make that whole bar **fixed position**, so that no matter where I'm at in the email-body, the send button is always visible and ready to be clicked without scrolling first.

**Comment by Lonniebiz** [comment] 2019-07-18 11:00
I just discovered that I can type `ctrl+enter` to send an email (no matter where I'm scrolled). Perhaps I should learn hot keys for all items on that tool bar . . .

**Comment by CodeMouse92** [comment] 2021-02-11 23:00
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/style-send-button-tool-bar-with-fixed-positioning/577

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@Lonniebiz: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-11 23:00 UTC
Labels: audit
