### ISSUE TITLE
connection error on IMAP - Certificate Error

### ISSUE THREAD

**Issue by didrip** [Foundry376/Mailspring#1505] opened 2019-05-21 06:32 UTC
I am on Mailspring 1.6.1-aceed8e5 on windows setup with 3 IMAP accounts (same provider : [OVH](https://getmailspring.com/setup/access-ovh-net-via-imap-smtp)) which used to work perfectly fine. I now have a connection error, the log is below :

```
----------IMAP----------
* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=LOGIN] Dovecot on host 115 ready
```

Their SSL certificate looks fine : https://www.sslshopper.com/ssl-checker.html#hostname=ssl0.ovh.net. It actually expires in 357 days which makes me think it has just been renewed 8 days ago which might be the cause of the issue.

Also there seem to be no DNS problem : `nslookup` =>
```
Non-authoritative answer:
Name:   ssl0.ovh.net
Address: 193.70.18.144
```

Interestingly Mailspring on Ubuntu (the exact same version) can still connect to those accounts perfectly fine, so the obvious conclusion would be that something have changed on my computer, however I can't seem to know what.

I already tried to rebuild the cache and also to reinstall Mailspring after deleting C:\Users\<Your User>\AppData\Roaming\Mailspring and C:\Users\<Your User>\AppData\Local\Mailspring but then I still cannot add the account (`Dovecot on host 121 ready`).

edit : it seems similar to #62 :

>  I can use it on Ubuntu 18.10 but not on Windows

**Comment by bengotow** [comment] 2019-05-26 20:38
Hey @ydixt,

Thanks for reporting this—it looks like the ovh certificate is trusted on my Mac, but if your Windows machine has a different set of "trusted root certificates" installed, it may not believe that the OVH certificate is valid. You may want to try installing updates on your Windows machine if there are any available. I'll fire up a Windows VM in a bit and see if I can reproduce this!

**Comment by didrip** [comment] 2019-08-15 18:11
I still encounter the same problem on another machine running Windows (10 Home 1809) for another account (imap.mailbox.org). Again if I check "Allow insecure SSL" it works fine so it is not a credentials issue.

The interesting part is I have the exact same setup on 2 different computers (same Windows version, Mailspring v1.6.3-134a0e55 and same connection settings) and only one of them is showing this error.

The other IMAP account to a different mail server works fine (on both computers). So this is likely not not problem with Mailspring but it is still good to have it there in case anyone encounters the same issue.

**Comment by didrip** [comment] 2019-08-15 18:13
I believe this is a DNS issue on my side as the server addresses that cause problem resolve to IPv6 first whereas the address that don't lead to error resolve only to IPv4 (`nslookup server.domain.com`).

I already have a DNS/IPv6 problem on LAN so this might be related.

**Comment by eikaramba** [comment] 2020-01-26 17:32
i have the same problem with mailbox.org if i enter imap.mailbox.org for imap server i get a certificate failure. i'm just following the settings on https://kb.mailbox.org/display/MBOKB/E-Mail-Einrichtung+-+allgemein

```
----------IMAP----------
* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE UIDPLUS AUTH=PLAIN AUTH=LOGIN] Dovecot ready.
```

**Comment by CodeMouse92** [comment] 2021-02-18 00:57
It appears that this issue has been resolved (apparently, a user-side DNS error), so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

@eikaramba Your problem would probably be unrelated to @didrip's, given the cause of his. Please open a new Sync Issue on Discourse if you're still having that problem, and include all information requested by the template.

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-18 00:57 UTC
Labels: audit, needs-reproduction, windows
