### ISSUE TITLE
Bug: Horizontal swipe not working Fedora 32, logitech K400+

### ISSUE THREAD

**Issue by meelash** [Foundry376/Mailspring#2126] opened 2020-08-22 03:06 UTC
**Describe the bug**
On Fedora 32, I have the wireless logitech K400+ keyboard with built-in trackpad. Horizontal scrolling with two-fingers works in other apps, for example, firefox. In Mailspring, if I make the window smaller, for example, in a message, I can scroll horizontally. But swiping in the message list does absolutely nothing (no archiving or snoozing).

**To Reproduce**
Open mailspring.
Swipe left and right on message in the list.

**Expected behavior**
Expect swipe left to snooze, swipe right to archive.

**Setup: (please complete the following information):**
 - OS: Fedora
 - OS Version 32
 - Mailspring Version: 1.7.8

**Comment by CodeMouse92** [comment] 2021-03-03 02:30
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/horizontal-swipe-not-working-fedora-32-logitech-k400/948

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@meelash: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-03 02:30 UTC
Labels: audit, bug
