### ISSUE TITLE
Libsecret not installed (SNAP on KDE Neon)

### ISSUE THREAD

**Issue by DT-Newman** [Foundry376/Mailspring#713] opened 2018-02-20 17:40 UTC
##### What operating system are you using?
KDE Neon

##### What version of Mailspring are you using?
Snap (1.1.4)

When opening I get the following error and mailspring does not start:

"Mailspring could not store you password securely. Make sure you have `libsecret` installed and a keyring is present. For more information, visit http://support.getmailspring,com/hc/en-us/articles/115001875571 "

**Comment by DT-Newman** [comment] 2018-04-15 21:33
The above fix by @kbknapp worked.

**Comment by heoft** [comment] 2019-06-16 17:41
Thank you very much to @kbknapp It works perfectly.

**Comment by Lvaskz** [comment] 2019-10-22 18:45
> 
> 
> `$ sudo apt install gnome-keyring` fixes this

That is cool, but maybe this dependency should be by default in mailspring snap. Not all normal users know report this kind of stuff, if they do not know what to do, it will be frustrating and they will be uninstalling the app because "it is not working" 

What do you think?

**Comment by Lvaskz** [comment] 2019-10-22 18:50
or maybe warning text in some where indicating " you need to use this command: sudo apt install gnome-keyring, if you don't have it in your system"

**Comment by thiagosfsilva** [comment] 2019-11-08 18:22
Got here after having the same problem. Isn't the whole purpose of Snaps making sure that all dependencies are pre-packaged? Also, if I install it from the AUR (running Manjaro KDE), I need to enter my gnome-keyring master password every time I log on, which doesn't make sense **particularly as I am not using Gnome Desktop**. This feels like a very sloppy implementation, there should be a proper way to store passwords securely without depending on a package from a specific desktop environment.

**Comment by funkypitt** [comment] 2019-11-18 11:36
I agree with thiagofsilva, it's sloppy: 1) snaps should have all dependencies packages (supposedly) and 2) a snap should work regardless of the DE chosen by the user. Surely there is another option?

**Comment by funkypitt** [comment] 2019-11-18 20:54
We can't blame them for ignoring the feedback once the issue has been closed. Technically, it should not have been closed since the issue was not fixed and still happens as of now.

**Comment by sarthak247** [comment] 2019-12-17 20:07
As mentioned by @thiagosfsilva , installing `gnome-keyring` on a Plasma based Desktop Environment just doesn't make sense. This is a lousy fix and there could have been better fixes like why not make mailspring use `KDE Wallet` instead for keyring management? Also, like he mentioned, one has to enter the password of gnome-keyring at every login which was just not worth it. 

Also, @funkypitt is right. This issue shouldn't have been closed in the first place so I will re-open another issue addressing the same

**Comment by exapsy** [comment] 2020-04-02 02:16
Why is this issue closed? The "solution" literally puts the weight of the fix on the users and not mailspring. And its done with the assumption that users are technical enough, to search for it on google, go on Github issues on this specific issue, read the correct solution and then type it on terminal. So, you're literally limiting mailspring's user audience and also prove that you dont care enough for the rest of it to even consider the issue unsolved.

And besides that, `gnome-keyring` requires you to enter the password literally everytime you open it unless you install it on Gnome itself. So the supposed long-term solution itself is not even sufficient to make mailspring user-friendly.

Solving the issue ASAP is a completely another story, we could even contribute to solve it ourselves. But marking it as closed just shows that you dont care for a solution to be found at all, which is just a bad way to show that you care for your audience and its issues.

**Comment by Grawl** [comment] 2020-04-27 10:36
I think it's closed because there is more than 800 opened issues at this time

**Comment by kaolpr** [comment] 2020-04-28 06:12
@Grawl Sorry, but this in not an argument. One issue more is an increase in number of 0,12%, whereas having it closed just makes part of community feel ignored.

**Comment by funkypitt** [comment] 2020-04-28 07:39
After much searching, I switched to Geary as a flatpak which is beautiful, 100% free and integrates seemlessly with Protonmail bridge.

**Comment by Grawl** [comment] 2020-04-29 03:48
Geary doesn’t have “unread” filter and “all mailboxes” folder

**Comment by funkypitt** [comment] 2020-04-30 09:08
@Grawl you are right. 
Unread filter is in the pipeline for version 3.38: https://wiki.gnome.org/Apps/Geary/ReleasePlanning
Unified mailbox is not, although it is in demand: https://gitlab.gnome.org/GNOME/geary/issues/53

**Comment by Grawl** [comment] 2020-04-30 09:17
They work slow https://gitlab.gnome.org/GNOME/geary/-/issues/85#note_557607

**Comment by AirCly** [comment] 2020-04-30 12:44
Dovete installare questi:

libgnome-keyring

**Comment by saywebsolutions** [comment] 2020-05-20 03:14
Also happens on Kubuntu (probably obviously). This issue should be opened back up

**Comment by drom98** [comment] 2020-06-01 13:11
Having the same problem with KDE Neon and Kubuntu 20.04.

**Comment by dmytro-shchurov** [comment] 2020-06-07 14:40
I din't want to use snaps at all. But Mailspring was a reason. And guess what? After the first click on the icon I've got the error which is two years old, and nobody is going to fix it. 
The only way I see is to create a new one every month until someone fix...

**Comment by farverio** [comment] 2020-08-15 23:31
same issue on kde neon 20.04. do not believe this issue should be closed as installing gnome keyring is a workaround specific to a DE

**Comment by ynavott** [comment] 2020-08-28 11:59
Same issue on Manjaro KDE. I have been a Mailspring user for a long time (both Windows and Linux) but only recently switched to KDE, and this is just disappointing.

**Comment by yousefamar** [comment] 2020-09-11 19:38
I did a bunch of research to compare mail clients and finally settled on Mailspring (I don't use a DE, just bspwm as a WM). I was even ready to pay to get some of the pro features. This issue, its age, and the response to it, has convinced me to go with a different client. I say this only so that the devs can be aware that something this silly is costing them sales.

**Comment by dmytro-shchurov** [comment] 2020-09-11 19:44
> I don't use a DE, just bspwm as a WM

The same thing is with i3. Even worse: high CPU load happens without any result occurs after literally each restart with 100% confirmation. 
If I add gtk password manager to trusted ones, Mailspring is ok, the other applications do not get passwords. So, I have to use it untrusted entering passwords manually every time.

**Comment by Stapleton** [comment] 2020-11-09 21:55
> Same issue on Manjaro KDE. I have been a Mailspring user for a long time (both Windows and Linux) but only recently switched to KDE, and this is just disappointing.

I just installed Manjaro Xfce last night and am encountering this dumb issue as I write this. Mailspring needs to see how many people are switching just because of this. Since I have to install misc packages on a 1 day old install just to use my mail client, I am gonna be switching. If you're gonna make an application crossplatform, actually make it true crossplatform or dont, because this is not true crossplatform. My fuckin distro should **not** matter with a snap.

**Comment by saywebsolutions** [comment] 2020-11-20 19:54
@DT-Newman can you fix this please, thank you

**Comment by DT-Newman** [comment] 2020-11-21 01:59
The cause of this issue seems to be that the secret management library used by mailspring (keytar) depends on libsecret... which KDE does not support when first installed.

The solutions to this problem would seem to be one of the following:

1. Prompt or document that the user must install gnome-keyring (or something else that supports libsecret)
2. Change key management library to one that supports kwallet, or one that can be self-contained within a snap
3. Update keytar to support kwallet
4. Update kwallet/KDE to support libsecret

In hindsight I probably shouldn't have closed this issue, as I agree with @Lvaskz that in theory a snap should be self contained.

Personally there is very little incentive for me to spend time trying to fix this issue as I rarley nowadays use desktop linux or a desktop mail client.

**Comment by binodmalaka** [comment] 2020-12-05 16:16
Thanks a lot , it worked ❤️

**Comment by CodeMouse92** [comment] 2021-01-28 03:14
Hi everyone,

Rest assured, this issue *does* matter to us. @DT-Newman was both the one to originally post it, and to close it, so that further caused it to slide under the radar. It was reopened November 2020, as you'll notice above, and I've marked it to be looked into.

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/libsecret-not-installed-snapcraft/333

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. **Rest assured, this doesn't mean the issue is being discarded or ignored.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 03:14 UTC
Labels: audit
