### ISSUE TITLE
Changed subject is not visible any where

### ISSUE THREAD

**Issue by patelom** [Foundry376/Mailspring#895] opened 2018-05-26 07:47 UTC
##### Are there any related issues?

https://github.com/Foundry376/Mailspring/issues/894
Solving the referred issue will solve this issue as well
##### What operating system are you using?
MacOS v10.13.4

##### What version of Mailspring are you using?
Mailspring v1.2.1

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No. I checked with could of them.

#####  Reference Image
<img width="1440" alt="screen shot 2018-05-26 at 1 14 55 pm 2" src="https://user-images.githubusercontent.com/5392699/40573943-19228ca6-60e7-11e8-8608-1daef7363f60.png">

#####  Issue 1
Consider that in my Mailspring, I am logged in with abc@mailspring.com. There is another email id, gmail@gmail.com. I do not use mailspring for gmail@gmail.com.

1. Now gmail@gmail.com sent an email to abc@mailspring.com.
2. abc@mailspring.com replied back.
3. **gmail@gmail.com replied back on the same thread but changed the subject**
4. **abc@mailspring.com replied back on the last email and again changed the subject.**

In the above case mentioned, even if gmail@gmail.com changed the subject, Mailspring is showing the email in the same thread. **There is no place where i can see the changed subject of the email. On the top, you only show the subject of the first email.** 

**Lot of time, certain information is only mentioned within the subject**

#####  Suggested change

If you solve this issue, https://github.com/Foundry376/Mailspring/issues/894, you will eventually solve this issue

**Comment by patelom** [comment] 2018-06-28 09:31
Any updates on this @bengotow ? Gmail has thread level subject, but subject of each email is also accessible. In Mailspring, we there is no way to see email level subject line.
<img width="1131" alt="screen shot 2018-06-28 at 2 53 31 pm" src="https://user-images.githubusercontent.com/5392699/42026167-1137eec0-7ae4-11e8-8d6c-0e13d8726da1.png">

**Comment by deckar01** [comment] 2020-02-13 18:43
There is some application state inconsistency here also. If mailspring is running as the emails arrive, the subject will match first email. If mailspring wasn't running, then syncs a new thread, mailspring will use the subject of the last email in the thread. The subject chosen persists between app restarts, but can differ between clients on different machines based on if the client was running when the emails arrived.

Side note: I missed an important email yesterday related to this behavior. The thread title of the original email was a generic error email sent to several people automatically (which we get a fair amount of). When my boss replied to me on that email thread telling me to look into it, the title never changed to `RE: ...` and the sender just changed from `errorbot@domain.com` to `errorbot@mydomain.com, Chri...`.

**Comment by CodeMouse92** [comment] 2021-02-15 23:24
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/changed-subject-is-not-visible-any-where/642

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@patelom @deckar01: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-15 23:24 UTC
Labels: audit
