### ISSUE TITLE
Only the first reply is quoted correctly

### ISSUE THREAD

**Issue by tgrgin** [Foundry376/Mailspring#1768] opened 2020-01-13 17:35 UTC
##### Are there any related issues?
No
...

##### What operating system are you using?
Ubuntu 18.04.3
...

##### What version of Mailspring are you using?
1.7.2
--

**Bug?**
Yep.
##### Is this an email sync or connection issue?
No
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No.
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Nothing particular about the issue.
...

--

**Feature Request?**
No
##### Does this feature exist in another mail client or tool you use?
Yes.
...

Send a longer mail with several paragraphs divided by empty lines to someone.
Receive their response where they answer something for each of your original paragraphs.
Try replying to them by opening empty lines below their responses.
Only the first response will have correct quoting level (i.e. 2 indents for your original paragraph, 1 indent for their response, 0 indent for the text you are currently typing). Every other response you enter will have 0 indent for previous text in discussion.

Darn, quoting levels just don't work! This is basic thing and messes up my discussions with colleagues. Goodbye Mailspring.
![Mailspring-quote-level-problem](https://user-images.githubusercontent.com/28588634/72278071-858c0700-3633-11ea-949b-bcf6ea509d06.png)

**Comment by CodeMouse92** [comment] 2021-02-11 19:15
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/quoted-text-not-folded/570

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@tgrgin: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-11 19:15 UTC
Labels: audit
