### ISSUE TITLE
Blurry fonts in some messages and application elements

### ISSUE THREAD

**Issue by kbchurch** [Foundry376/Mailspring#1119] opened 2018-10-09 14:55 UTC
Some emails, and even parts of the app, display fonts blurry. Seems it's the Sans Serif font and perhaps when it's in bold.

##### Are there any related issues?

Not that I have seen
...

##### What operating system are you using?

Windows 10 Build 18252

##### What version of Mailspring are you using?

1.42

--

**Bug?**

##### Is this an email sync or connection issue?

No

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Not that I can tell

##### Is the issue reproducible with a particular attachment, message, signature, etc?

![screenshot 24](https://user-images.githubusercontent.com/11573224/46677579-ea46ef00-cbb0-11e8-91be-c32bdf2bb338.png)

![screenshot 26](https://user-images.githubusercontent.com/11573224/46677886-6c371800-cbb1-11e8-9393-323e18809702.png)

With the second one, the titles of "Theme and Style" and "Scaling" are blurry, as if a double exposure horizontally.

Anyone have an idea of what's going on here?

**Comment by alxtr1bal** [comment] 2018-10-10 08:15
Same behavior, same windows version. But i don't think it's related, as i was seeing this in the former insider build.

**Comment by bengotow** [comment] 2018-10-16 09:58
Whoa. I haven't seen this before, that is some SUPER terrible looking text. Almost so bad it couldn't just be a font issue.

EDIT: It looks like this has been seen in VSCode and also upstream in Electron:
https://github.com/Microsoft/vscode/issues/51789
https://github.com/electron/electron/issues/13646

It seems like the fix is to go into the NVIDIA control panel and disable "FXAA" (https://github.com/Microsoft/vscode/issues/51789#issuecomment-416868789) until a more permanent fix is found. That's wild... hopefully we can fix this upstream soon.

**Comment by alxtr1bal** [comment] 2018-10-16 10:31
FXAA is already disabled here.

**Comment by kbchurch** [comment] 2018-10-16 14:29
AMD gpu here. I've not seen it in other apps yet either. I can still use Mailstring to cull emails down, but reading them can be hit or miss.

**Comment by GeorgeHahn** [comment] 2018-10-31 04:12
I'm seeing the same issue - Windows 10 Build 18267 on Mailspring 1.5.1

For context, this only seems to apply to text in some places - there's lots of text that renders without any problems.

No problems:
![image](https://user-images.githubusercontent.com/502747/47765485-180be900-dcc2-11e8-80c0-e320b13e6ea6.png)

Email body:
![image](https://user-images.githubusercontent.com/502747/47765497-26f29b80-dcc2-11e8-8d3d-0588bccc4b7f.png)

Appears to be related to the font:
![image](https://user-images.githubusercontent.com/502747/47765559-6de09100-dcc2-11e8-8a14-eb626a5a35c6.png)

Remove font-family property:
![image](https://user-images.githubusercontent.com/502747/47765562-75079f00-dcc2-11e8-8ddb-045a3907f4d8.png)

Elsewhere:
![image](https://user-images.githubusercontent.com/502747/47765662-eba49c80-dcc2-11e8-9dda-db7ca7ef1b4c.png)

Removed font-family from header (h1-h6) style:
![image](https://user-images.githubusercontent.com/502747/47765686-09720180-dcc3-11e8-8f10-10f73704a332.png)

**Comment by mjoppich** [comment] 2018-11-14 21:30
I can confirm that this issue persists on Windows Build 18277 as shown by @GeorgeHahn  .

**Comment by CodeMouse92** [comment] 2021-02-18 23:43
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/interface-gets-blurry/89

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed** 2021-02-25 01:51 UTC
Labels: bug, migrated
