### ISSUE TITLE
[Feature request] <Create new rule from address> in the context menu

### ISSUE THREAD

**Issue by Andrewsudarikov** [Foundry376/Mailspring#83] opened 2017-10-08 03:43 UTC
Mailspring supports automatic label sorting rules but access to them is somewhat inconvenient. 
It would be much handier if there was a context menu item to create a rule from received emails in the inbox with automatically filled in. 

This would greatly help people ho get 50+ emails a day from different sources and manual sorting into folders is just too big a task.

**Comment by QuantumMecha** [comment] 2018-08-23 10:48
This is the only thing that I feel is missing from Mailspring. 

Additionally, It would be great if this worked when multiple emails from different address are selected too.

**Comment by cobraBJ** [comment] 2018-11-13 09:54
Is this feature status still pending?  
Creating rules is very inconvenient at present , please develop this feature to allow users creating rules from mails directly ,just like Outlook . 
Thanks a lot ~

**Comment by Bugsbane** [comment] 2019-03-26 02:54
I agree that this would be a great feature, however what I love in Thunderbird is that it's not limited to just the sender. You can right click on an email subject and choose to create a mail rule from that. You can right click on the date of an email and choose to create a mail rule from that. You can right click on the starred status and choose to create a mail rule from that etc.

It's much more flexible than just creating a rule from the sender, and the interface is elegant.

**Comment by amandabee** [comment] 2020-11-05 20:36
I would even be happy if I could have my inbox and rules open at the same time. Then I could at least copy and paste the correct search terms from my inbox or search result.

**Comment by CodeMouse92** [comment] 2021-01-29 21:19
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/create-new-rule-from-address-in-the-context-menu/385

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@Andrewsudarikov @QuantumMecha @Bugsbane: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-29 21:19 UTC
Labels: audit, enhancement
