### ISSUE TITLE
Quit  doesn't completely close application

### ISSUE THREAD

**Issue by krasi-georgiev** [Foundry376/Mailspring#1488] opened 2019-05-06 12:23 UTC
Ubuntu

1.6.1-aceed8e5

When exiting via Quit or ctrl+q the application continues to run in the background and doesn't quit.

**Comment by bengotow** [comment] 2019-05-26 19:17
Hey! Could you try launching Mailspring via the command line and then see if you get an exception of some sort when you choose Quit / Exit from the menu? I don't think we've seen this one before!

**Comment by krasi-georgiev** [comment] 2019-05-27 10:12
![Screenshot_20190527_131154](https://user-images.githubusercontent.com/8903888/58413255-08e6f100-8081-11e9-828e-c6d4df8260a0.png)


no error on exit and if you look at the screenshot after exiting there are 3 main processes left to run in the background.

**Comment by krasi-georgiev** [comment] 2019-06-04 08:06
ping

**Comment by krasi-georgiev** [comment] 2020-08-31 18:15
still an issue

**Comment by CodeMouse92** [comment] 2021-01-28 04:16
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/exit-on-x-button-with-no-minimize-to-tray/207/6

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 04:16 UTC
Labels: audit, bug, linux, needs-reproduction
