### ISSUE TITLE
[Bug] Send later only works when Mailspring is open

### ISSUE THREAD

**Issue by palefire19** [Foundry376/Mailspring#334] opened 2017-11-11 16:55 UTC
##### What operating system are you using?
MacOS 10.12.6

##### What version of Mailspring are you using?
1.0.8

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail maybe?

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Steps to reproduce:
- Compose a new email
- Send later for a few minutes from now
- Quit Mailspring
- Email does not go out during the send later time if Mailspring is not open

**Comment by JunnanZ** [comment] 2017-11-12 06:15
I had a similar situation. I sent later an email, put my laptop in sleep, and opened again after the set time. Mailspring seemed to have some trouble deciding when to send that email. The desired behavior should be sending the email right now if the time has already passed, but it was actually sent way later.

**Comment by bengotow** [comment] 2017-11-12 18:52
Hey! This is correct—right now, features like snooze and send later rely on Mailspring being open because the app doesn't send your email credentials to the cloud. We've got the infrastructure to support running the "send later" from Mailspring's servers, but when it was a feature in Nylas Mail there was a lot of feedback from users that they didn't want their email passwords being stored in the cloud to power those features, so it was removed for Mailspring 1.0. Definitely hoping to bring it back as an opt-in soon so you can choose the behavior you want!

**Comment by gitbobbed** [comment] 2017-11-13 02:12
On this particular issue (and before I go filing new issues), can I ask what the expected behavior would be at the moment for people who use Mailspring on multiple computers?

For instance, I have Mailspring connected to the same e-mail account(s) on three computers. If I snooze a message on one of them, and not use that computer when that message was supposed to be resurfaced (but keep using Mailspring in my other computers), that message is not going to pop back, right?

(Asking because I can think of ways through which that could be achieved through the Mailspring ID alone without uploading any e-mail credentials  - or any PII for that matter - to the cloud, so don't know if that has been implemented already).

**Comment by palefire19** [comment] 2017-11-13 06:43
I like the idea of making it an option. For me, send later is almost always used so that something goes out when the computer is asleep (and when I'm asleep), so the feature loses a fair amount of its power if it only sends once I'm back at my computer.

**Comment by ykguler** [comment] 2017-12-18 22:28
For me send later doesn't work at all, circle loader just keeps on rolling..

**Comment by rdddyEB** [comment] 2018-10-23 19:19
What is the latest on this issue -- does Mailspring still have to be open for items to send later? And how does that relate to using different computers at different times -- does the one it was written on have to be open or can any copy of the program be open? I find this functionality potentially quite useful but its implementation is still quite confusing to me.

**Comment by Kaos-Industries** [comment] 2020-05-18 06:55
Seems this is STILL an occurring issue over three years later, with still no option to send later without leaving your computer on all night. This is the second serious problem I've discovered in Mailspring's UX in days. I'd be willing to look past it if Mailspring was free, but the "Send later" feature and others like it is costing me $8 a month, so this is quite frankly appalling.

**Comment by CodeMouse92** [comment] 2021-01-29 23:21
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/server-side-send-later/391

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-29 23:21 UTC
Labels: audit, product-direction
