### ISSUE TITLE
Unread filter not showing all unread messages from inbox

### ISSUE THREAD

**Issue by nemm** [Foundry376/Mailspring#1143] opened 2018-10-18 05:48 UTC
In my inbox there are 4 unread messages (notifications from redmine) that are not visible in unread filter. As you can see in the video below there should be 10 unread messages shown with this filter. Those notifications are missing.

(sorry for my English)

OS: Windows 10
Version: 1.4.2-f587b7b7

[https://www.youtube.com/watch?v=EdfPRdoikwg](https://www.youtube.com/watch?v=EdfPRdoikwg)

**Comment by J-tt** [comment] 2018-11-10 03:39
Bump,
I'm experiencing the same issue, Windows 10, I've got 8 unread emails that I cannot seem to get rid of.

**Comment by kode54** [comment] 2019-01-01 22:02
Bump,
I have two unread messages on Arch Linux, and they only started appearing with 1.5.4. They don't appear anywhere in the listing, and when I log into Gmail's web site, they don't appear there, either.

**Comment by sitefinitysteve** [comment] 2019-04-23 16:43
I'm plagued by this as well

**Comment by CodeMouse92** [comment] 2021-02-16 01:33
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/unread-filter-not-showing-all-unread-messages-from-inbox/646

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@nemm @kode54 @J-tt: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-16 01:33 UTC
Labels: audit
