### ISSUE TITLE
Feature Request: Dismiss connection issues dialogue.

### ISSUE THREAD

**Issue by omaregb** [Foundry376/Mailspring#2122] opened 2020-08-18 15:16 UTC
Some of my email accounts require 2 factor authentication, but I don't always want to use them. Yet, if I don't authenticate, the pop-up saying "one or more accounts are having connection issues" is persistently there.

It would be nice to have a way to dismiss this dialogue, as it is quite distracting.

**Comment by CodeMouse92** [comment] 2021-03-03 02:15
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/dismiss-connection-issues-dialogue/945

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@omaregb: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-03 02:15 UTC
Labels: audit, enhancement
