### ISSUE TITLE
[Feature requests] Add an option to synchronize your mail account between computers

### ISSUE THREAD

**Issue by ShiiroSan** [Foundry376/Mailspring#1210] opened 2018-11-02 08:18 UTC
Hello, 

I've many computer, and it could be useful to have an option to synchronize my mail account with every computer I own. This would also offer the ability to easily recover installed account when setting up a new computer with mailspring.

**Comment by bengotow** [comment] 2018-11-03 16:00
Hey @ShiiroSan — this is a great idea. I know in the past we've avoided this because people don't want to sync their passwords to the cloud, but maybe we could sync everything but the password and allow you to type it in again once.

**Comment by CodeMouse92** [comment] 2021-01-28 03:38
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/sync-templates-signatures-accounts-etc-accross-multiple-devices/265/8

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 03:38 UTC
Labels: audit, enhancement
