### ISSUE TITLE
Bug: Fatal error when syncing IMAP

### ISSUE THREAD

**Issue by BrunoSpy** [Foundry376/Mailspring#2139] opened 2020-09-08 12:49 UTC
**Describe the bug**
Mailsync can't finish sync of IMAP account : stuck at 1%.

**To Reproduce**
21470 [2020-09-08 14:45:04.291] [main] [info] ------------- Starting Sync (********) ---------------
21470 [2020-09-08 14:45:04.300] [metadata] [info] Metadata delta stream starting...
21470 [2020-09-08 14:45:08.300] [background] [info] Marking all folders as `busy`
21470 [2020-09-08 14:45:08.310] [background] [info] Syncing folder list...
21470 [2020-09-08 14:45:08.817] [background] [info] Syncing folder list...
21470 [2020-09-08 14:45:08.928] [background] [info] syncFolderUIDRange for INBOX, UIDs: 1 - 109986, Heavy: false
21470 [2020-09-08 14:45:09.171] [background] [info] - remote=4500, local=0
21470 [2020-09-08 14:45:09.237] [background] [info] - Fetching full headers for 4500 (of 4500 needed)
21470 [2020-09-08 14:45:09.278] [foreground] [info] syncFolderUIDRange for INBOX, UIDs: 110591 - 110740, Heavy: false
21470 [2020-09-08 14:45:09.390] [foreground] [info] - remote=101, local=101
21470 [2020-09-08 14:45:09.403] [foreground] [info] Idling on folder INBOX
21470 [2020-09-08 14:45:09.434] [background] [critical] 
***
*** Mailspring Sync 
*** An exception occurred during program execution: 
*** {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID (heavy)","key":"ErrorFetch","retryable":true,"what":"std::exception"}
***

21470 [2020-09-08 14:45:09.435] [background] [critical] *** Stack trace (line numbers are approximate):
*** ??:?        SyncWorker::syncFolderUIDRange(Folder&, mailcore::Range, bool, vector*)
*** ??:?        SyncWorker::syncNow()
*** ??:?        runBackgroundSyncWorker()
*** main.cpp:?  main::{lambda()#3}::operator()() const
*** main.cpp:?  _Bind_simple::operator()()
*** main.cpp:?  thread::_Impl::_M_run()
*** thread.o:?  execute_native_thread_routine()

**Setup: (please complete the following information):**
 - OS: Arch Linux
 - Mailspring Version: latest 1.7.8

**Additional context** 
Tried to fully delete Mailspring and reinstall, clear et reconstruct cache... doesn't help : same error over and over.

**Comment by CodeMouse92** [comment] 2021-02-01 18:16
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one already on Discourse:

https://community.getmailspring.com/t/syncfolderuidrange-errorconnection-on-one-of-the-folders/412

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-01 18:16 UTC
Labels: audit, bug
