### ISSUE TITLE
When a keyboard shortcut is modified, I cannot add alternative shortcut

### ISSUE THREAD

**Issue by tukusejssirs** [Foundry376/Mailspring#1529] opened 2019-06-18 17:38 UTC
##### Are there any related issues?

I have not found any.

##### What operating system are you using?

CentOS 7

##### What version of Mailspring are you using?

v1.6.1 and v1.6.2

**Bug?**

I’d say: yes, it is a bug. :)

##### Is this an email sync or connection issue?

No.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

It is not connected with anything else but Mailspring settings and its keyboard shortcuts.

#### Problem description

When one edits the keyboard shortcuts in Mailspring settings, they cannot add alternative keyboard shortcuts (at least I could not find a way). Take for example the ‘Move to newer/older conversation": by default, it is set to ‘k’ or ‘up’ and ‘j’ or ‘down’, respectively. Now, I wanted to switch the ‘j’ with ‘k’, so I changed it, however, I lost the ‘up/down’ shortcut.

There might be a way to input the alternative shortcut, but I could not find a way. Still, I suggest to add separate, let’s say, text box (like in Gmail settings) for each keyboard settings (i.e. there would be two boxes per each setting).

**Comment by tukusejssirs** [comment] 2020-02-14 13:42
I have tried to add the following lines into `keymap.json`, but the new shortcuts does not work (the old one are not overriden by these).

```json
"core:previous-item": ["j", "up"],
"core:next-item": ["k", "down"],
"core:select-up": ["shift+j", "shift+up"],
"core:select-down": ["shift+k", "shift+down"],
```

And I have found out that for example <kbd>Alt</kbd>+<kbd>Shift</kbd>+`anything` (`alt+shift` nor `shift+alt`) cannot be assigned as a shortcurt.

Note that I have edited `~/.config/Mailspring/keymap.json` file.

**Comment by CodeMouse92** [comment] 2021-02-11 23:06
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/when-a-keyboard-shortcut-is-modified-i-cannot-add-alternative-shortcut/579

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-11 23:06 UTC
Labels: audit, enhancement
