### ISSUE TITLE
Bug: Snooze label date format is ambiguous 

### ISSUE THREAD

**Issue by pandaiolo** [Foundry376/Mailspring#2141] opened 2020-09-11 11:56 UTC
**Describe the bug**

The Snooze label date format leads to ambiguous display in at least two cases:
1. Hour is displayed without minutes so it really looks like it is a year
2. Year is not displayed even if snoozing beyond year's end

**To Reproduce**

Steps to reproduce the 1st failing use case:
1. Snooze an email
2. Type `13 dec at 22h` or any plain hours (without minutes, such as 1:00, 2:00, etc)
3. Mail will be visibly snoozed to the following date: `Dec, 13 22`, which seems like it is 2022/12/13 date

Steps to reproduce the 2nd failing use case:
1. Snooze an email
2. Type `13 dec 2022`
3. Mail will be visibly snoozed to the following date: `Dec, 13 12`, which seems like it is 2012/12/13 date

_Note: when not specifying any hour, it sets the snooze time at 12 o'clock, like above... so the impact is significant because it is the default behaviour_

**Expected behavior**

- Do not display hours/minutes if they were not specified
- Always display hours AND minutes to lift any ambiguity 
- Make it smart to display the year as well, if snoozed beyond this year's end

The expected label for above ambiguous use cases would be: 
- `Dec, 13 22:00` 
- `Dec, 13 2022` 

**Screenshots**

<img width="174" alt="Screenshot 2020-09-11 at 12 44 15" src="https://user-images.githubusercontent.com/1933404/92922184-4f568f80-f42d-11ea-9ceb-921cd576830d.png">

(first snooze above is actually in 2022, but not the second one)

**Setup: (please complete the following information):**
 - OS: Mac OS Catalina
 - OS Version: 10.15.6
 - Mailspring Version: 1.7.8

**Comment by CodeMouse92** [comment] 2021-03-03 03:02
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/snooze-label-date-format-is-ambiguous/952

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@pandaiolo: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-03 03:02 UTC
Labels: audit, bug
