### ISSUE TITLE
New message icon showing after refreshing, but there's no new mail

### ISSUE THREAD

**Issue by mtxr** [Foundry376/Mailspring#1463] opened 2019-04-10 16:45 UTC
##### Are there any related issues?

Didn't find any. But has a few tray problems

##### What operating system are you using?

Fedora 29

##### What version of Mailspring are you using?

1.6.1

**Bug?**

##### Is this an email sync or connection issue?

Don't know

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No.

**Comment by cept73** [comment] 2019-04-19 06:10
Same on Kubutnu 18.10. Mailspring 1.6.1

**Comment by triptec** [comment] 2019-05-08 06:19
Reset cache in settings reset it for me

**Comment by techtickcn** [comment] 2019-09-06 08:54
Same on Kubutnu 18.04 lts. Mailspring 1.6.3

**Comment by CodeMouse92** [comment] 2021-02-18 01:55
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/unread-count-still-on-without-unread-messages/350

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-18 01:55 UTC
Labels: audit
