### ISSUE TITLE
[Feature request] Allow jumping to labels like Gmail does using G + L, then type the label name.

### ISSUE THREAD

**Issue by Kredns** [Foundry376/Mailspring#347] opened 2017-11-16 16:17 UTC
##### What operating system are you using?
Fedora 27

##### What version of Mailspring are you using?
1.08

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
GMail, but it may be useful on other email accounts as well.

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
This is available in the gmail WebUI and makes it so that I never have to use my mouse while checking my emails. 

You press the G key, then the L key (which I've always assumed stands for goto label) and then start typing the label name. When you hit enter Gmail takes you to that label. This would be a nice feature to have.

**Comment by bengotow** [comment] 2017-11-16 16:26
Hey! Ahh we should definitely add this. Some sort of "jump bar" would be really cool. Right now in keyboard shortcuts you can configure a few "Go To's", but just for the standard locations:

<img width="478" alt="image" src="https://user-images.githubusercontent.com/1037212/32902663-48412a7c-caf3-11e7-9196-28413a08a368.png">

**Comment by Kredns** [comment] 2017-11-16 16:36
I'm already using those shortcuts and they are nice. They allow me to do about 90% of what I need to on a daily basis. I can use the mouse for other labels, but yeah I think this would be nice to have. 

I'm going to clone the repo and see if I can't work on this over the weekend.

**Comment by CodeMouse92** [comment] 2021-02-20 03:26
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/allow-jumping-to-labels-like-gmail-does-using-g-l-then-type-the-label-name/714

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@Kredns: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-20 03:26 UTC
Labels: audit, enhancement, good first issue
