### ISSUE TITLE
Check for updates banner is annoying when using a third-party distribution that lags behind releases

### ISSUE THREAD

**Issue by KristerV** [Foundry376/Mailspring#1229] opened 2018-11-12 07:33 UTC
Are there any related issues? **no**
What operating system are you using? **Arch Linux**
**Feature Request?**

I would like to either disable checking for updates or just hide the notification.

![image](https://user-images.githubusercontent.com/2750622/48332779-b3f00a00-e65d-11e8-884a-cf67c040ed8c.png)

I'm on Arch Linux and the AUR repo is kept up to date pretty well. I am not going to download the app manually and I don't want to update my computer every time MailSpring says so. I have a once-a-month update schedule.

This notification hides needed info and it's color takes my attention away - super annoying and not useful.

**Comment by bengotow** [comment] 2018-11-22 00:10
Hey! Sorry for the delay—please use the Snapcraft release if you can! It autoupdates and doesn't display the notifications. It's great someone is maintaining an AUR repo but it's not us. I'll see if maybe we can take it over or publish an official AUR package in the future!

**Comment by zaen323** [comment] 2019-02-27 01:51
Having the same annoyance as well, I would really just like an option in the settings menu to disable the banner. Or an "x" button to hide the banner for a period of time, although not ideal.

**Comment by nelai1** [comment] 2019-03-15 13:13
using the snap on ubuntu, still seeing this annoying banner

**Comment by jnylen** [comment] 2019-03-18 17:54
@bengotow Hi,
I'm the one that created the aur repo in the beginning and are collabing on it again.

Is there a safe way to disable the update notification? Such as setting the updateAvailable = false in the update-notification file? Just making sure.

**Comment by marxistvegan** [comment] 2019-03-19 13:59
Same issue in the Solus Project (https://getsol.us) the notification is very annoying and will get updated on a weekly basis so being able to turn off that notification would be greatly appreciated.

**Comment by friday** [comment] 2019-03-20 15:02
I found a hacky way to disable it, which requires `asar`:

From the path app.asar is in:
```sh
asar extract app.asar app
sed -i 's/updater.getState()/0/g' app/internal_packages/notifications/lib/items/update-notification.js
asar pack app app.asar
rm -rf app
```

I'm not sure it's safe, but it worked for me. The result will be larger than the original `app.asar` since the original build step [excludes some patterns](https://github.com/Foundry376/Mailspring/blob/149b389508f59ef382c21900fc7b45aa5599caad/app/build/tasks/package-task.js#L133-L151). If someone is ambitious enough, it should be possible to ignore these form the cli too, or possibly rebuild only this with gulp. :/

**Comment by Stefan538871** [comment] 2020-04-07 15:08
@bengotow Hi,
I know this issue started 2018 and the last comment was march 2019.
I just want to mention that I use fedora31 and apparently the rpmfusion repo is behind aswell.

Since you already mentioned snap, would it be possible to distribute this app as flatpak too?
Or as someone already mentioned an option in the settings menu to disable auto updates.
Aside from that, great email client :)

**Comment by KristerV** [comment] 2020-04-11 11:13
@Stefan538871 that is called thread hijacking. Also this thread is stale, so closing.

**Comment by friday** [comment] 2020-04-11 12:05
Why @KristerV? Others want to keep track of the development too and invested time in finding this issue, subscribing. commenting etc.

**Comment by KristerV** [comment] 2020-04-11 16:05
oh, well kudos for replying fast, sure I'll reopen it then. Thought since the last comment was over a year ago..

**Comment by CodeMouse92** [comment] 2021-02-10 00:53
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/check-for-updates-banner-is-annoying-when-using-a-third-party-distribution-that-lags-behind-releases/542

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@KristerV @jnylen @marxistvegan @friday: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-10 00:53 UTC
Labels: audit, linux
