### ISSUE TITLE
Encountered an error while syncing...

### ISSUE THREAD

**Issue by maxoodf** [Foundry376/Mailspring#994] opened 2018-07-23 16:59 UTC
MacOS 10.13.6 (17G65)
Mailspring 1.3.0
IMAP (dovecot)

I receive "Encountered an error while syncing" error about every one minute with the following log records:

```
21348 [2018-07-23 19:44:33.072] [main] [info] Identity created at 1532250877 - using ID Schema 1
21348 [2018-07-23 19:44:33.074] [main] [info] ------------- Starting Sync ([hidden]) ---------------
21348 [2018-07-23 19:44:33.098] [background] [info] Marking all folders as 'busy'
21348 [2018-07-23 19:44:33.099] [metadata] [info] Metadata delta stream starting...
21348 [2018-07-23 19:44:33.101] [background] [info] Syncing folder list...
21348 [2018-07-23 19:44:33.849] [background] [info] Syncing folder list...
21348 [2018-07-23 19:44:33.994] [background] [info] syncFolderChangesViaCondstore - INBOX: modseq 73360 to 73360, uidnext 45627 to 45627
21348 [2018-07-23 19:44:34.139] [background] [info] syncFolderChangesViaCondstore - Sent: modseq 3171 to 3171, uidnext 9881 to 9881
21348 [2018-07-23 19:44:34.257] [background] [info] syncFolderChangesViaCondstore - Drafts: modseq 2039 to 2039, uidnext 1972 to 1972
21348 [2018-07-23 19:44:34.375] [background] [info] syncFolderChangesViaCondstore - Trash: modseq 15962 to 15962, uidnext 201275 to 201275
21348 [2018-07-23 19:44:34.567] [foreground] [info] [local-c086bd6a-a1e7] Running ChangeFolderTask performRemote:
21348 [2018-07-23 19:44:34.739] [background] [info] syncFolderUIDRange for spam, UIDs: 2017514 - 2018264, Heavy: true
21348 [2018-07-23 19:44:35.970] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID","key":"ErrorParse","retryable":true,"what":"std::exception"}
21348 [2018-07-23 19:44:38.819] [foreground] [critical]  *** Stack trace (line numbers are approximate):
 *** in mailsync     mailimap_unstrict_char_parse
 *** in mailsync     _applyFolderMoveInIMAPFolder(mailcore::IMAPSession*, mailcore::String*, mailcore::IndexSet*, __1::vector, nlohmann::basic_json&)
 *** in mailsync     TaskProcessor::performRemoteChangeOnMessages(Task*, void (*)(mailcore::IMAPSession*, mailcore::String*, mailcore::IndexSet*, __1::vector, nlohmann::basic_json&))
 *** in mailsync     TaskProcessor::performRemote(Task*)
 *** in mailsync     SyncWorker::idleCycleIteration()
 *** in mailsync     runForegroundSyncWorker()
 *** in mailsync     runBackgroundSyncWorker()::$_0::operator()() const
 *** in mailsync     void* __1::__thread_proxy(void*)
 *** 0x7fff5cdbb661  _pthread_body
 *** 0x7fff5cdbb50d  _pthread_body
 *** 0x7fff5cdbabf9  thread_start
 ***
```

**Comment by maxoodf** [comment] 2018-07-23 17:06
I can not understand, is it the official (getmailspring.com) or forked repository? I can not find 1.3.0 branch here... Any way, this issue is related to the binary package downloaded from getmailspring.com.

**Comment by bengotow** [comment] 2018-08-02 20:07
Hey! There should be a 1.3.0 tag not a branch. It seems like Mailspring is having trouble with a folder name, which is pretty odd. Do you know what folder you tried to move things in to that might be causing this? That'd help narrow it down quite a bit.

**Comment by maxoodf** [comment] 2018-08-09 08:51
Hi! I've reinstalled Mailspring and can not reproduce this bug. I can suppose that it was related to a removed mail folder on my server side...

**Comment by blinderjay** [comment] 2018-11-17 17:06
I encountered same problem while i try to sync my xxx@163.com , It seemed that 163 has some invalidly named mail folder which can not be deleted(system folder), here is the log message:
```
8894 [2018-11-18 00:56:35.463] [main] [info] Identity created at 1532921585 - using ID Schema 1
8894 [2018-11-18 00:56:35.465] [main] [info] ------------- Starting Sync (blinderjay@163.com) ---------------
8894 [2018-11-18 00:56:35.469] [background] [info] Marking all folders as `busy`
8894 [2018-11-18 00:56:35.469] [metadata] [info] Metadata delta stream starting...
8894 [2018-11-18 00:56:35.470] [background] [info] Syncing folder list...
8894 [2018-11-18 00:56:36.323] [background] [error] Could not create Mailspring container folder: Mailspring. ErrorNonExistantFolder
8894 [2018-11-18 00:56:36.406] [background] [error] Could not create required Mailspring folder: Mailspring/Snoozed. ErrorNonExistantFolder
8894 [2018-11-18 00:56:36.409] [background] [info] Syncing folder list...
8894 [2018-11-18 00:56:36.576] [background] [error] Could not create Mailspring container folder: Mailspring. ErrorNonExistantFolder
8894 [2018-11-18 00:56:36.649] [background] [error] Could not create required Mailspring folder: Mailspring/Snoozed. ErrorNonExistantFolder
8894 [2018-11-18 00:56:36.720] [background] [info] syncFolderUIDRange for INBOX, UIDs: 1 - 4294967296, Heavy: false
8894 [2018-11-18 00:56:36.822] [background] [critical] 
 ***
 *** Mailspring GenericException occurred during program execution: 
 *** {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID","key":"ErrorNonExistantFolder","retryable":false,"what":"std::exception"}
 ***

8894 [2018-11-18 00:56:36.822] [background] [critical]  *** Stack trace:
 ***   SyncWorker::syncFolderUIDRange(Folder&, mailcore::Range, bool, vector*)
 ***   SyncWorker::syncNow()
 ***   runBackgroundSyncWorker()
 ***   clone
 ***
```

**Comment by NewtMa** [comment] 2019-07-13 08:13
@blinderjay I've gt the same problem with my @126.com and @163.com. 你解决了没有?

**Comment by knimer** [comment] 2020-04-13 06:05
Hello,

The same issue!

Mailspring 1.7.2 - Solus 4.1
IMAP account

Mail Sync File includes:

`4339 [2020-04-13 09:54:53.992] [main] [info] Identity created at 1552382207 - using ID Schema 1
4339 [2020-04-13 09:54:53.996] [main] [info] ------------- Starting Sync (knimer@baitmahsir-pharma.com) ---------------
4339 [2020-04-13 09:54:54.004] [metadata] [info] Metadata delta stream starting...
4339 [2020-04-13 09:54:57.004] [background] [info] Marking all folders as `busy`
4339 [2020-04-13 09:54:57.011] [background] [info] Syncing folder list...
4339 [2020-04-13 09:54:59.493] [background] [info] Syncing folder list...
4339 [2020-04-13 09:55:00.115] [background] [info] syncFolderChangesViaCondstore - INBOX: modseq 31 to 31, uidnext 16 to 16
4339 [2020-04-13 09:55:00.323] [background] [info] syncFolderChangesViaCondstore - INBOX.Sent: modseq 3 to 3, uidnext 2 to 2
4339 [2020-04-13 09:55:00.531] [background] [info] syncFolderChangesViaCondstore - INBOX.Drafts: modseq 1 to 1, uidnext 1 to 1
4339 [2020-04-13 09:55:00.740] [background] [info] syncFolderChangesViaCondstore - INBOX.Archive: modseq 1 to 1, uidnext 1 to 1
4339 [2020-04-13 09:55:00.949] [background] [info] syncFolderChangesViaCondstore - INBOX.Trash: modseq 2 to 2, uidnext 2 to 2
4339 [2020-04-13 09:55:01.165] [background] [info] syncFolderChangesViaCondstore - INBOX.spam: modseq 1 to 1, uidnext 1 to 1
4339 [2020-04-13 09:55:01.378] [background] [info] syncFolderChangesViaCondstore - INBOX.Mailspring: modseq 1 to 1, uidnext 1 to 1
4339 [2020-04-13 09:55:01.378] [foreground] [info] syncFolderChangesViaCondstore - INBOX: modseq 31 to 31, uidnext 16 to 16
4339 [2020-04-13 09:55:01.382] [foreground] [info] Idling on folder INBOX
4339 [2020-04-13 09:55:01.785] [background] [info] syncFolderChangesViaCondstore - INBOX.Mailspring.Snoozed: modseq 1 to 1, uidnext 1 to 1
4339 [2020-04-13 09:55:01.788] [background] [info] Sync loop deleting unlinked messages with phase 2.
4339 [2020-04-13 09:55:01.788] [background] [info] Sync loop complete.
4339 [2020-04-13 09:55:09.000] [metadataExpiration] [info] Scanning for expired metadata
4339 [2020-04-13 09:55:09.001] [metadataExpiration] [info] -- Will wake for next expiration in 7200sec
4339 [2020-04-13 09:55:15.630] [calContacts] [critical] 
 ***
 *** An exception occurred during program execution: 
 *** (unknown exception details)
 ***

4339 [2020-04-13 09:55:15.646] [calContacts] [critical]  *** Stack trace (line numbers are approximate):
 *** (unknown)  clone
 ***
`

**Comment by CodeMouse92** [comment] 2021-01-30 00:33
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/the-eternal-sync-bug/334

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-30 00:33 UTC
Labels: audit, bug, needs-reproduction
