### ISSUE TITLE
Feature request: delete earlier messages

### ISSUE THREAD

**Issue by phamhung77** [Foundry376/Mailspring#1028] opened 2018-08-15 14:30 UTC
Currently, all messages with the same subject will be merged in one thread. If I click to delete button, Mailspring will delete the whole thread. 

If there is a separate delete, reply, forward... button in each message, it would be much easier.

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?
Yes, at least Mail Mac has it. I haven't checked other software yet.

**Comment by pablorq** [comment] 2019-10-24 07:22
Same feature request: to delete messages individually.

**Comment by CodeMouse92** [comment] 2021-02-11 23:33
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue is very similar to one already migrated to Discourse:

https://community.getmailspring.com/t/move-or-delete-a-single-message-in-a-thread/320

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@phamhung77: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-11 23:33 UTC
Labels: audit
