### ISSUE TITLE
While forwarding an email with a long email thread, the send button appears way too down and difficult to find

### ISSUE THREAD

**Issue by patelom** [Foundry376/Mailspring#897] opened 2018-05-26 13:12 UTC
##### What operating system are you using?
MacOS

##### What version of Mailspring are you using?
1.2.1
--
##### Issue?
I have an email thread with multiple long emails. While I try to forward that email, the send button comes way down. Sometimes its difficult find the send button.
 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5392699/40576455-5cc85256-6114-11e8-9fe6-981c260f62de.gif)

##### Does this feature exist in another mail client or tool you use?
Yes, Gmail. It shows concise view while forwarding the email. Send button is very much accessible.

**Comment by patelom** [comment] 2018-06-28 10:11
@bengotow Any update on this one ?

**Comment by dublav** [comment] 2018-08-13 18:16
+1 for this request

**Comment by vitaliel** [comment] 2018-11-29 10:10
+1

**Comment by florianb** [comment] 2020-01-08 09:06
:bellhop_bell: 

This issue is pretty annoying - my first thought was the send-button has disappeared.

**Comment by CodeMouse92** [comment] 2021-02-18 23:14
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/style-send-button-tool-bar-with-fixed-positioning/577

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-18 23:14 UTC
Labels: audit
