### ISSUE TITLE
Dock icon badges missing and no notifications on macOS Catalina

### ISSUE THREAD

**Issue by sampotts** [Foundry376/Mailspring#1624] opened 2019-08-30 04:37 UTC
##### Are there any related issues?
None that I can see. 

##### What operating system are you using?

macOS Catalina Beta 7 19A546d but I noticed it effected all previous betas too 

##### What version of Mailspring are you using?

Version 1.6.3 (1.6.3)

---

# Bug

The email unread count is missing from the badge, even though the option is enabled and there are unread emails. Also there are no notifications for mail received. 

##### Is this an email sync or connection issue?

Nope. 

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Nope. 

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Any message.

**Comment by sampotts** [comment] 2019-09-01 10:40
This may be helpful. Apparently the process has changed for Catalina... https://developer.apple.com/documentation/devicemanagement/notifications/notificationsettingsitem

**Comment by perteraul** [comment] 2019-09-06 19:31
Can confirm this - @bengotow, is there anything that we can do on our side?

**Comment by sampotts** [comment] 2019-09-23 23:56
They seem to be back for me on beta 9 👍 

![image](https://user-images.githubusercontent.com/719092/65470986-c0193a80-deb0-11e9-8451-6e3f6ece9ed8.png)

Don't have a notification to show but they also seem to show up ok.

**Comment by bengotow** [comment] 2019-10-09 02:46
Hey! This may be related to #1467 and fixed in the next release. Will do some testing and see!

**Comment by perteraul** [comment] 2019-10-14 10:56
thanks @bengotow! any update on when the next release will be shipped?

**Closed** 2019-10-22 15:45 UTC
Labels: bug, done-pending-release

**Comment by perteraul** [comment] 2019-10-23 10:43
That works, thanks for the update! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AndreaCardiota** [comment] 2021-02-11 10:50
Just installed it on Big Sur and it doesn't show me badges for unread mail. Was doing the same with the Spark app. How do I fix it?

**Comment by CodeMouse92** [comment] 2021-02-11 17:27
@AndreaCardiota If the problem is occurring with both Mailspring and Spark, then it probably isn't a bug on our end.

---

It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team
