### ISSUE TITLE
How can I send an email to a gmail group of email addresses?

### ISSUE THREAD

**Issue by indaleto** [Foundry376/Mailspring#451] opened 2017-12-18 17:06 UTC
##### What operating system are you using?
Ubuntu 17.10

##### What version of Mailspring are you using?
1.0.10

##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Don't know.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Yes: Just create a gmail group of contacts, put some addresses inside and try to email to that specific group

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Yes

**Comment by bengotow** [comment] 2017-12-18 23:24
Hey! Thanks for filing this—Mailspring doesn't currently support Gmail address book sync, so you aren't able to access your Gmail Contact Groups from the app. This is definitely coming though.

**Comment by indaleto** [comment] 2017-12-18 23:43
Can you tell when will this option come out?

**Comment by aaylnx** [comment] 2018-01-11 17:42
I would also love to know when this is coming.  Thanks!

**Comment by rovingrambler** [comment] 2018-10-11 14:29
I would love this too.

**Comment by inventortechie** [comment] 2018-10-11 14:50
I'm wondering what the latest update on this might be since the heads up from the Dec 18, 2017 comment above. ;-)

**Comment by shawnkhall** [comment] 2019-01-15 18:32
this missing feature just kept me from being able to recommend this instead of Outlook. :(

**Comment by RasheedAZ** [comment] 2019-09-09 10:30
Any update on this? Could be a deal breaker for many potential users :(

**Comment by CodeMouse92** [comment] 2021-02-24 18:43
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/gmail-group-support/763

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@indaleto: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-24 18:43 UTC
Labels: audit, enhancement
