### ISSUE TITLE
Archive hotkey not working in All Mail folder

### ISSUE THREAD

**Issue by leggomyinfo** [Foundry376/Mailspring#1720] opened 2019-11-22 05:44 UTC
macOS 10.15.1
Mailspring 1.7.2

If I have opened an email in the All Mail folder with an inbox tag and then click the hotkey for archive ("e"), the inbox tag should be removed. Currently, nothing happens.

**Comment by bengotow** [comment] 2019-12-02 16:22
Hey! Ahh yes this seems like a bug—I think the email won't disappear (since you're already looking at the archive essentially if this is a Gmail account), but the inbox tag should definitely be removed.

**Comment by vincic** [comment] 2019-12-09 09:33
This applies to all none 'inbox' folders when you have a gmail account. In gmail archiving always removes the current viewed tag.

**Comment by CodeMouse92** [comment] 2021-02-19 01:04
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/archive-hotkey-not-working-in-all-mail-folder/706

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@leggomyinfo @vincic: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-19 01:04 UTC
Labels: audit, bug
