### ISSUE TITLE
Duplicate mails being sent

### ISSUE THREAD

**Issue by ignispider** [Foundry376/Mailspring#1279] opened 2018-12-21 20:36 UTC
This issue is known by many people and I'm not going to describe it.
I have mailspring 1.3.5 on Debian 9. Even sending an email for a single address 2 is being sent.
I don't understand how I problem like this persist for so long. We are treated like spam, flooding someone else's inbox.

The only fix I can see now is changing my email client.

**Comment by Yonezpt** [comment] 2018-12-26 20:06
This just happened to me, I never noticed it before, but it is true it is sending the same email twice. Same version but on Win7x64.

This is a problematic bug and like you said it is causing issues on servers that have strict rules for spam blocking, causing my email to be blacklisted.

I cannot use this client any longer to send emails until this troublesome bug is fixed.

**Comment by Adyel** [comment] 2019-01-06 07:17
The same thing happened to me multiple time. It's really annoying when you are sending an important mail and it gets sent twice.

**Comment by JKAnderson409** [comment] 2019-05-10 15:49
It seems that this may be a problem with the feature to delay sending an email. I have turned off this feature and am no longer having the problem with mail sent from an Outlook account. Unfortunately this is turned on by default.

**Comment by mthomos** [comment] 2019-12-12 12:06
Issue still exists, using Gmail and Outlook accounts

**Comment by mthomos** [comment] 2019-12-17 21:37
@bengotow issue still exists when replying to a mail. Can you acknowledge the issue ?

**Comment by fireedo** [comment] 2020-01-05 03:55
happend today, so the problem still exists.
Replying an email will send multiple email to receiver.

**Comment by cherrot** [comment] 2020-02-23 14:26
Maybe this duplicate to #1086.  Anyway, neither is assigned :disappointed:

**Comment by CharlesCossette** [comment] 2020-03-20 14:50
Same issue.

Ubuntu 18.04
Mailspring 1.7.4-d54ff730

**Comment by Deyjandi** [comment] 2020-07-13 15:36
I can confirm this too. Its so annoying and seeing the issue exists since 2018 is at least depressing...

**Comment by AntGeorge** [comment] 2020-09-15 11:45
I can also confirm this in ubuntu 20.04, mailspring version 1.7.8-13635bcf

**Comment by givemeamug** [comment] 2020-09-25 15:19
Can also confirm this happening on Mac OS. Running the latest version of everything and when I reply to a single person, it goes out twice, when I reply to 1 person and another on cc it's being sent 3 times!!!!! It's not just copies in my Sent folder, I tested it with another email of mine and the recipients get the duplicates too. I'm on the Pro plan and this is extremely frustrating because I spammed 1 recruiter like hell

**Comment by CodeMouse92** [comment] 2021-01-29 22:28
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/duplication-of-sent-mail/275

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-29 22:28 UTC
Labels: audit
