### ISSUE TITLE
xdg-email is not working with attachments  

### ISSUE THREAD

**Issue by ltiber** [Foundry376/Mailspring#1804] opened 2020-02-21 17:52 UTC
I use the cmd `xdg-email --attach myfile.jpg`
to create a new empty mail with the file attached myfile.jpg. But unfortunately the file is not attached in the new message dialogbox. 
Other options of  `xdg-email` like 
`--body , --subject or address(es)` are working fine.
It seems that the problem happens only with `--attach `option whereas it is supported by geary or thunderbird  

 
- OS: Ubuntu 18.04
- Mailspring Version: 1.7.2-4522b259

**Comment by bengotow** [comment] 2020-02-24 21:14
Hey @ltiber — can you try passing a full file path instead of a relative one? 

Edit: it looks like the source code to xdg-email just adds `&attach=path` to a mailto URL it hands to the app. This isn't part of the mailto URL spec, but we can probably make Mailspring support that option in the future so this works.

**Comment by ltiber** [comment] 2020-02-25 10:51
Absolute paths run the same. It would be really nice if Mailspring support this feature in a new version. Any workaround? I use it in my software to share photos via Email.

**Comment by tlindig** [comment] 2020-12-31 12:06
have same problem on Linux Mint 20 with xdg-email 1.1.3 and Thunderbird 68.10.0
(Kernel: 5.8.0-33-generic x86_64 bits: 64; Desktop: Cinnamon 4.6.7; Distro: Linux Mint 20 Ulyana; base: Ubuntu 20.04 focal)

That works, attachment is in the opened e-mail window:
``` sh
thunderbird -compose attachment="file:///$HOME/.bash_history"
```

but this open only a e-mail window without the attachment:
``` sh
xdg-email --attach $HOME/.bash_history
```

**Comment by CodeMouse92** [comment] 2021-02-02 03:20
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/attachment-from-right-click-in-file-explorer-command-line/373

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-02 03:20 UTC
Labels: audit, bug, linux
