### ISSUE TITLE
Bug: Removing only account results in Mailspring closing instantly

### ISSUE THREAD

**Issue by samtuke** [Foundry376/Mailspring#1854] opened 2020-03-11 13:08 UTC
**Describe the bug**
Removing the only mail account so far added in Mailspring causes it to close / crash instantly. The account I was removing was the one following the process described in https://github.com/Foundry376/Mailspring/issues/1855 ; theoretically that could have impacted this instant close behaviour.

**To Reproduce**

1. Add 1 account
2. Go to preferences and remove it
3. See Mailspring close instantly, unexpectedly

**Expected behavior**
The account is removed and I can immediately add another one

**Setup: (please complete the following information):**
 - OS: Fedora 31
 - OS Version [e.g. 14]
 - Mailspring Version: ex: 1.7.2 (using that due to https://github.com/Foundry376/Mailspring/issues/1841)

**Comment by CodeMouse92** [comment] 2021-02-12 19:48
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/removing-only-account-results-in-mailspring-closing-instantly/587

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@samtuke: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-12 19:48 UTC
Labels: audit, bug
