### ISSUE TITLE
Exchange account does not sync received mail

### ISSUE THREAD

**Issue by nicobonne** [Foundry376/Mailspring#1122] opened 2018-10-10 09:02 UTC
##### Are there any related issues?

Somehow #684, for the buggy folder sync.

##### What operating system are you using?

Ubuntu 18.04

##### What version of Mailspring are you using?

1.4.2, snap package
--

**Exchange account does not work properly. Received mail does not sync unless I close the app and re-open it. Clicking on "sync new mail now" does nothing. I noticed that the folders scanning and caching never ends, no matter how long I leave the app running. I experienced this issue in Ubuntu 16.04 as well. I also have a Gmail account that works great.**

##### Is this an email sync or connection issue?

Sync issue, log file right after "Sync New Mail Now" attached.
[mailsync-0d62ba71.zip](https://github.com/Foundry376/Mailspring/files/2463920/mailsync-0d62ba71.zip)

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Exchange

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Not sure how to reproduce it, I had the same issue under Ubuntu 16.04.

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

...

**Comment by CodeMouse92** [comment] 2021-02-05 00:35
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be a duplicate of one we've already migrated to Discourse:

https://community.getmailspring.com/t/institutional-office365-not-working/48

Please consider joining that community and continuing the discussion there.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-05 00:35 UTC
Labels: audit
