### ISSUE TITLE
[Feature Request] Support the Services Menu on macOS

### ISSUE THREAD

**Issue by iandol** [Foundry376/Mailspring#1428] opened 2019-03-22 12:29 UTC
The macOS Services menu enables scripts, tools and other applications to share useful services across the OS. Mailspring does not have a Services menu in the Context menu, and it is inactive in the Application menu. Electron does support the Services menu as I see that Atom has the Services menu enabled and functional:

![Screenshot 2019-03-22 at 20 20 46](https://user-images.githubusercontent.com/153905/54822880-fb0f9b00-4ce0-11e9-9477-4f5e55737b6d.png)

I'm not a JS developer, but I see Electron offers the following advice:

https://electronjs.org/docs/api/menu#notes-on-macos-application-menu 

##### Are there any related issues?

No

##### What operating system are you using?

macOS

##### What version of Mailspring are you using?

1.6.0

##### Does this feature exist in another mail client or tool you use?

Yes, Services menu works in almost all macOS applications and certainly Apple Mail, Airmail etc.

**Comment by bengotow** [comment] 2019-03-23 16:59
Hey! Thanks for filing this - this is actually pretty odd... it seems the menu is supposed to "just work", but it's broken for me as well. I'll see if I can figure this out! If anyone else has ideas or knows of other Electron apps where it works / doesn't work, that might help narrow it down as well.

**Comment by CodeMouse92** [comment] 2021-02-25 23:33
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

@iandol: Can you please confirm that this is still broken with 1.8.0, and if so, open a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-25 23:33 UTC
Labels: audit, enhancement
