### ISSUE TITLE
When replying, changing the subject does not create a new thread

### ISSUE THREAD

**Issue by patelom** [Foundry376/Mailspring#894] opened 2018-05-26 07:42 UTC
##### Are there any related issues?

https://github.com/Foundry376/Mailspring/issues/193

##### What operating system are you using?
MacOS v10.13.4

##### What version of Mailspring are you using?
Mailspring v1.2.1

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No. I checked with could of them.

#####  Reference Image
<img width="1440" alt="screen shot 2018-05-26 at 12 44 48 pm" src="https://user-images.githubusercontent.com/5392699/40573785-45cd63b4-60e4-11e8-8df5-f6ddbcbc38cf.png">

#####  Issue
Consider that in my Mailspring, I am logged in with abc@mailspring.com. There is another email id, gmail@gmail.com. I do not use mailspring for gmail@gmail.com.

1. Now gmail@gmail.com sent an email to abc@mailspring.com.
2. abc@mailspring.com replied back.
3. **gmail@gmail.com replied back on the same thread but changed the subject. Now this should appear as a new thread inside my Mailspring app.** It appears in the same thread. This is a common behavious obervered across every other email clients including Gmail. **Changing the subject can be considered as a begining of the new thread.**
4. **abc@mailspring.com replied back on the last email and again changed the subject. Now this should appear as a new thread in my sent. This is shown in the same thread.**

#####  Suggested change @bengotow 
As most of the users are used to Gmail, please observe how the threading works in Gmail. This might be just one issue I highlighted, but there can be many more. As I find I will keep raising tickets here.

*For this issue, on replying if someone is changing the subject, please create a new thread*

**Comment by patelom** [comment] 2018-05-26 07:58
The similar thing happens while **forwarding an email**. If I got an email, I changed the subject and forwarded it to someone. **There is no way to see the subject of the forwarded email.**

Reference Screen Shot
<img width="1440" alt="screen shot 2018-05-26 at 1 27 08 pm" src="https://user-images.githubusercontent.com/5392699/40574028-a0cc4cd6-60e8-11e8-926c-48baf6c557c0.png">

**Comment by bengotow** [comment] 2018-05-30 20:28
Hey! Thanks for reporting this—you're correct, Mailspring will never break the thread when creating a reply / forward. I actually didn't think Gmail did either when I originally wrote this a couple years ago, but I was able to reproduce your scenario and choosing "Edit Subject" and changing the subject even slightly within Gmail creates a new thread.

This should be fairly straightforward to fix—I'll see what I can do.

Do let me know if you find other ways Mailspring is different. Gmail may be a bit of a moving target—I could have sworn this was correct—but I'd definitely like to emulate the webmail behavior when possible.

**Comment by patelom** [comment] 2018-06-25 07:39
@bengotow would love to know if this would be something you are planning to fix by the next release? And have you had any thoughts on the Search UI?
 Thanks.

**Comment by bengotow** [comment] 2018-07-14 20:35
Hey! I'm actually wrapping up the next release right now and it includes a totally overhauled search bar that exposes all the of the available query options (and adds a few more). I'm still working on the reply threading, but I hope to have that fixed in the release after this one.

**Comment by patelom** [comment] 2018-07-18 10:35
Much thanks @bengotow ! The searching experience has become much better now. Looking forward to the reply to threading fix!

**Comment by karannshah** [comment] 2018-09-03 13:55
@bengotow thanks for Mailspring. Wanted to check if this issue will be fixed soon. It's creating a hiccup because when I am forwarding the same email to different recipients via different emails its still grouping them all into the same thread. And that is making tracking conversation with all the different recipients difficult.

**Comment by CodeMouse92** [comment] 2021-02-15 23:19
It appears that there has been no activity on this issue for some time, so we will close it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-15 23:19 UTC
Labels: audit, bug
