### ISSUE TITLE
[Feature Request] Add github or other URL into signature creator

### ISSUE THREAD

**Issue by aprather51** [Foundry376/Mailspring#1490] opened 2019-05-07 16:04 UTC
After 1.6.0 update/fix signature creator include url to facebook, linkedin, and twitter which is great. But unfortunately, not everyone own all, fb, linkedin, or twitter accounts including me.

Perhaps, signature creator could give more flexibility by adding "other URL" input and have user to pick up icon from there i.e. github, dribbble, youTube, reddit, pintrest and etc...

This would be HUGE beneficial, thanks in advance.

**Comment by bengotow** [comment] 2019-05-26 19:28
Hey! This is a great idea—I think the icons we need are small enough that you might be able to allow someone to type in a "social URL" and then resolve it's favicon by scanning default locations on that site, like facebook.com/favicon.ico.

**Comment by Tasty213** [comment] 2019-07-25 19:41
I agree this sounds like a good feature, whereabouts is the signature creation .ts file?

**Comment by michaelaye** [comment] 2020-06-19 03:45
Yes please/ it would add even more use to the prettiest signature creator i know. (and i know a lot of email clients).

**Comment by CodeMouse92** [comment] 2021-02-25 23:42
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/add-github-or-other-url-into-signature-creator/806

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@aprather51 @Tasty213 @michaelaye: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-25 23:42 UTC
Labels: audit, enhancement, good first issue
