### ISSUE TITLE
CSS background images appear inverted in the dark theme and look bad

### ISSUE THREAD

**Issue by Lyptik** [Foundry376/Mailspring#1191] opened 2018-10-29 11:01 UTC
spec : win10
mailspring : 1.5.1-da141eaf with dark theme

I think I always had this problem, just reporting it now.

The screenshot speaks for itself, I think the colors are inversed when we are in the dark theme for photos inside mail.

Best,

![image](https://user-images.githubusercontent.com/5172593/47645764-39f65600-db72-11e8-8339-870805a43ceb.png)

**Comment by bengotow** [comment] 2019-03-17 18:15
Hey! Right now, Mailspring inverts the entire iframe so that the majority of emails display white-on-black instead of black-on-white and are easier on the eyes when you're in dark mode. Then it inverts `<img>` tags, etc. AGAIN to ensure they're the original colors. Unfortunately, if the emails use CSS `background-image` to display images instead of img tags, they're inverted as shown above.

We actually turned this off a while back and everyone complained because having giant white blocks for each email sort of ruins dark mode. I think for now we'll leave this in place and hopefully we can find a better solution soon.

**Comment by CodeMouse92** [comment] 2021-02-17 23:23
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/dont-invert-images-with-dark-theme/536

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-17 23:23 UTC
Labels: audit, product-direction
