### ISSUE TITLE
Unread count still on without unread messages

### ISSUE THREAD

**Issue by Ivluengo** [Foundry376/Mailspring#711] opened 2018-02-20 06:58 UTC
##### What operating system are you using?
... Windows 10

##### What version of Mailspring are you using?
...
1.1.4-22d9f20d
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
... No I don't.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
... I don't know. I have only one account with google in mailspring.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Since a few days ago I don't know why some messages (not all of them and I don't know which ones exactly) are waiting in the unread tab and are being showed in the unread count in spite of I already have ridden them!!

![mailspring](https://user-images.githubusercontent.com/10440026/36410854-49a32292-1613-11e8-9795-07cae89fcd4a.JPG)

In the image you can see the inbox. The count tells me there are 4 unread messages but there are not more emails unread.  Here you have otherimage with the unread tab selected.

![mailspring 2](https://user-images.githubusercontent.com/10440026/36410885-729f0fa8-1613-11e8-82bf-216912cc431a.JPG)

As you can see, 4 messages are appearing in this tab and all of them are already ridden.  What do you think it can be happening?  Thanks a  lot!!

Ivan

**Comment by pateljj04** [comment] 2018-02-26 19:37
I am having the same issue, Messages that are read are still showing under unread. I have checked and all the message in the thread are read messages, but they still show up under unread.

**Comment by sam-lucas** [comment] 2018-02-26 21:21
Same here on Ubuntu 16.04. I am able to temporarily resolve the issue by marking ALL my mail as unread and then re-marking it as read, but the issue will eventually return. If I perform this action on my mail in chunks the number will decrement gradually, which seems to imply it is particular messages causing this bug and not just a random number.

**Comment by joaquinrulin** [comment] 2018-05-03 17:44
it happens to me when a new email comes to a selected thread

**Comment by webberwang** [comment] 2018-06-23 04:30
Still happening

**Comment by abdoul-Karim** [comment] 2018-12-19 11:23
Still happening to me too. version 1.5.3.

**Comment by DianaNites** [comment] 2018-12-24 06:46
I'm having the same issue and it's infuriating. Every time I check, theres nothing, and then it brings itself back, so now theres no way to know if I actually have new messages or not.

**Comment by croahs** [comment] 2019-01-12 20:36
Same issue still here. 

Workaround is currently to go to "Unread". There will be a read e-mail there.

On this e-mail do this: 
Right click, Mark as Unread
Right click, Mark as Read.

This will remove it. But you will have to do this several times every day to keep all of them away.

**Comment by sitefinitysteve** [comment] 2019-05-06 13:40
I have another workaround

Preferences->Accounts->(Account in question)->Rebuild Cache

Seems to clear it for me, but annoying nonetheless

**Comment by ransagy** [comment] 2019-05-10 11:53
I've had a similar issue for a while, But for me it's restricted solely to the "Important" label/folder of Gmail. Only there some of my email are continuously flagged as unread (just by the icon, no actual unread mail under that label/folder). Clearing the cache "works", But somewhat inconviniant, especially if this happens again the next time a mail comes in and is considered "Important".

**Comment by zachschrock** [comment] 2019-10-07 18:30
I am still getting this pretty frequently off and on. Pretty annoying, any help would be appreciated.

Mailspring (1.6.3-134a0e55)

Mac OS 10.14 (18A391)

**Comment by benwbooth** [comment] 2019-12-28 04:48
I also get this issue on the latest Mailspring (1.7.2) on both macOS mojave and Windows 10. I'm using a Gmail account.

**Comment by Venryx** [comment] 2020-05-11 23:50
I'm still getting this issue sometimes, in v1.7.6, on Windows 10. (for unread messages, which I then read, remaining in the "Unread" section, even after restarts of the program)

**Comment by benwbooth** [comment] 2020-07-09 18:08
I run mailspring both on Windows and macOS, and still get this issue. It's really annoying. Any idea when this will be fixed?

**Comment by zachschrock** [comment] 2020-07-09 18:13
> I run mailspring both on Windows and macOS, and still get this issue. It's really annoying. Any idea when this will be fixed?

What version are you on? This was fixed for me awhile ago.I'm currently on Version 1.7.8 (1.7.8) — you may need to reset your cache — Preferences > Local Data Reset Cache (lower left)

**Comment by benwbooth** [comment] 2020-07-10 18:50
Actually, I checked and it looks like the problem is finally fixed. Thanks!

**Comment by benwbooth** [comment] 2020-07-13 15:23
I just had this happen again on version 1.7.8:
![image](https://user-images.githubusercontent.com/75972/87322102-de086800-c4e1-11ea-87bb-609cdcf182bb.png)

Notice how both mails in the unread section are un-bolded (already read), but still show up in the unread section. After marking as Unread, then marking as Read, then the messages are gone from the Unread section

**Comment by stefanedberg** [comment] 2020-11-09 07:16
I'm having the exact same problem and marking unread and then marking as read seem to resolve the issue. 
Mailspring 1.7.8
macOS 10.15.7

**Comment by triptec** [comment] 2021-01-08 07:56
@stefanedberg LOL, and for everyone else yeah I've got this problem with:
Mailspring 1.7.8-13635bcf
Ubuntu 20.10

**Comment by danielwangksu** [comment] 2021-01-10 04:13
> @stefanedberg LOL, and for everyone else yeah I've got this problem with:
> Mailspring 1.7.8-13635bcf
> Ubuntu 20.10

Can confirm Ubuntu 20.04 Mailspring 1.7.8-13635bcf

**Comment by CodeMouse92** [comment] 2021-01-28 18:37
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/unread-count-still-on-without-unread-messages/350

Please consider joining that community and continuing the discussion there!

@lvluengo: if you join and reply to the issue, the moderators can make an effort to reassign your migrated posts to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 18:37 UTC
Labels: audit
