### ISSUE TITLE
[Feature Request] Windows Titlebar & Dark Mode

### ISSUE THREAD

**Issue by thejustinwalsh** [Foundry376/Mailspring#1638] opened 2019-09-19 17:27 UTC
When using dark mode in windows the titlebar remains white. Seems like linux builds get all kinds of appearance options. I would love to see  soimething similar on windows and suggest something like https://github.com/sidneys/electron-titlebar-windows since my understanding is that without going frameless this isn't solvable in electron on Windows.

##### Are there any related issues?
https://github.com/Foundry376/Mailspring/issues/142
...

##### What operating system are you using?
Windows 10
...

##### What version of Mailspring are you using?
1.6.3
...

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?
Every electron app ever made.
...

**Comment by wayoutware** [comment] 2019-10-14 18:29
the only way for them to do this, would be to render the titlebar inside the client itself (rather than using the one provided by the windows DWM). [however, you can make the default window decorations black, if you would like.](https://www.onmsft.com/how-to/how-to-get-dark-theme-title-bars-in-windows-10-without-changing-your-accent-colour) as a workaround.

**Comment by CodeMouse92** [comment] 2021-02-11 22:21
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/consistent-theming-on-windows/58

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-11 22:21 UTC
Labels: enhancement, migrated

**Comment by bengotow** [comment] 2026-04-19 21:10
Good news — Mailspring 1.20.0 (April 2026) added an "Automatic" theme (now the default) that follows your operating system's light/dark mode setting. It also adds system accent color support. You should no longer need to manually switch themes when your OS changes modes. Let us know if you still see any areas that don't respond correctly.
