### ISSUE TITLE
Bug: Mailspring crashes on start since today

### ISSUE THREAD

**Issue by zaolin** [Foundry376/Mailspring#2203] opened 2020-11-16 11:13 UTC
**Describe the bug**
Start the mailspring app, crashes few minutes later with a libsecret error. Worked 1 year long until today. Now I get the following messages from a terminal start

Running database migrations
App load time: 241ms

{"error":null}
Manual update check (updates.getmailspring.com/check/linux/x64/1.7.8-13635bcf/b5560017-eee4-49ca-bb4e-04b89de5f920/stable) returned 204
{ [Error: Zeitüberschreitung wurde erreicht] message: 'Zeitüberschreitung wurde erreicht' } { pluginIds: [] }

**To Reproduce**
See above

**Expected behavior**
Mailspring starts and does not crash

**Setup: (please complete the following information):**
 - OS: Gentoo Linux
 - Mailspring Version:  1.7.8

**Comment by CodeMouse92** [comment] 2021-02-15 21:36
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

@zaolin: Can you please confirm that this is still broken with 1.8.0, and if so, open a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

This might be related, but I'm not certain: https://community.getmailspring.com/t/libsecret-not-installed-snapcraft/333

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-15 21:36 UTC
Labels: audit, bug
