### ISSUE TITLE
Show unread count / badge in the Windows 10 tray

### ISSUE THREAD

**Issue by ilmonteux** [Foundry376/Mailspring#446] opened 2017-12-17 01:44 UTC
##### Are there any related issues?

...

##### What operating system are you using?
windows 10

##### What version of Mailspring are you using?
1.0.10-d250d253

--

**Bug?**

The unread email count badge does not seem to work in Windows 10 (turned on in Preferences > General > Notifications > Show badge on the app icon --> "Show unread count"). Tried to change the preferences and quit/relaunch Mailspring multiple times to no result. Is this supposed to work in Windows 10?  The default Mail app has working badge. 

![image](https://user-images.githubusercontent.com/34525889/34075840-0f7a5de2-e288-11e7-9281-93b8f6b74eec.png)

##### Do you have any third-party plugins installed? If so, which ones?
no

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by cloudbarracuda12** [comment] 2017-12-24 11:16
yeah, and startmenu live tile would be great!

**Comment by bengotow** [comment] 2018-02-06 20:12
Hey! That option is actually just for macOS, but I'll see if we can make this work on Windows 10. We might need to see if we can get support added to Electron.

**Comment by smashingx1** [comment] 2019-01-16 17:51
The icon also doesn't show any unread messages count on Linux :/

**Comment by Spidersouris** [comment] 2019-06-29 06:44
Any news about that?

**Comment by sajjadalis** [comment] 2020-01-20 07:53
Hello,

I have just moved from Mailbird Pro (Windows 10) and this is the only thing bugging me. There is no unread count on tray icon in Windows 10 (and Ubuntu). https://github.com/Foundry376/Mailspring/issues/420

Any update on this?

**Comment by deviant-studio** [comment] 2020-11-24 15:18
guys, please implement this feature

**Comment by CodeMouse92** [comment] 2021-02-24 18:41
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/show-unread-count-badge-in-the-windows-10-tray/762

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@ilmonteux: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-24 18:41 UTC
Labels: audit, enhancement, windows
