### ISSUE TITLE
Cant launch the program

### ISSUE THREAD

**Issue by mortenanakin** [Foundry376/Mailspring#2375] opened 2022-03-09 21:34 UTC
Hi! From today I cant launch the program.

![image](https://user-images.githubusercontent.com/52761884/157540069-4ef304c6-3e1d-4395-9580-eb838a7b80d6.png)

**Comment by RoySRC** [comment] 2022-03-09 22:14
Do not update to `1.10.0`, this release seems to have a bug. Revert to the older version by going to `%LocalAppData%/Mailspring` and deleting the folder `app-1.10.0`. Do not attempt to reinstall an older version as this will not solve the issue. The error will persist regardless of the version if `app-1.10.0` folder is not deleted.

**Comment by Predeactor** [comment] 2022-03-09 22:28
Hey, this is a duplicate of #2373, it might be interesting to close this issue in favor of the already opened one
In any case, you can check out my little guide on how to fix Mailspring 1.10.0 here: https://community.getmailspring.com/t/database-error-and-unable-to-launch-app-after-installing-v1-10-0/4063/11?u=predeactor

**Comment by mortenanakin** [comment] 2022-03-09 23:10
Deleting the folder app-1.10.0 and now the program wont launch, the window with the error doesnt appear anymore. But the program still wont launching xD

**Comment by Predeactor** [comment] 2022-03-09 23:24
@mortenanakin Have you tried [this post](https://community.getmailspring.com/t/error-with-the-local-database-during-update/4179/9) too?

**Comment by Phylu** [comment] 2022-03-10 06:33
Closing this one as duplicate.

**Closed by Phylu** 2022-03-10 06:33 UTC
