### ISSUE TITLE
Bug: empty trash is not working

### ISSUE THREAD

**Issue by chenhao1umbc** [Foundry376/Mailspring#1997] opened 2020-05-21 12:15 UTC
**Describe the bug**
When I deleted a draft email reply to a certain email, there is a new trash email generated. But when I hit empty trash, the trash did not go away.

**To Reproduce**
1. Go to any received email, scroll to the bottom
2. Click on 'write a reply'
3. click 'delete' icon
4. go to trash folder
5. click empty trash now.... nothing happened

**Expected behavior**
trash folder should be empty

**Screenshots**
![image](https://user-images.githubusercontent.com/25485451/82558065-e7590200-9b3a-11ea-9d6d-1c7369fc61f3.png)

**Setup: (please complete the following information):**
 - OS: Window 10 home
 - OS Version Build 18363
 - Mailspring Version: 1.7.7

**Comment by asparc** [comment] 2020-05-25 14:07
Can confirm. Deleted empty drafts appear as empty threads in the trash bin and these empty cannot be removed from there (unless you rebuild all cache...). 

When you drag these empty threads back into the inbox, completely random things start happening (e.g. other recent emails from the inbox suddenly disappear from the inbox and pop up in the trash; or other recent emails from the inbox turn into empty threads, causing data loss). So: don't drag the empty threads from the trash into the inbox!

**Comment by chenhao1umbc** [comment] 2020-06-03 21:40
Is anybody address this issue?

**Comment by valentt** [comment] 2020-06-14 21:49
It looks like single developer that is working on this can't handle the load. There was a team but it looks like they split...

**Comment by CodeMouse92** [comment] 2021-01-18 21:08
Thank you for reporting this. 2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/empty-trash-not-working/81

Please consider joining that community and continuing the discussion there! Bonus: @chenhao1umbc and @asparc, if you join and reply to the issue, the moderators can make an effort to reassign your migrated posts to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-18 21:08 UTC
Labels: audit, bug
