### ISSUE TITLE
quoted text not folded

### ISSUE THREAD

**Issue by didrip** [Foundry376/Mailspring#919] opened 2018-06-05 08:54 UTC
Mailspring v1.2.2
Ubuntu 18.04

Some emails do not have their quoted text (previous emails below signature) folded (3 dots buttons).

It happens when there is an unquoted element in the email below the quoted text, ex an image.

Jon Doe wrote on 24/06 :
> Hi Jack
>
> John.
>
> Jack Reacher wrote on 23/06 :
>> Hi John !
>>
>> Jack Reacher.
>> developer ~~@github~~ @microsoft

![JackReacherLogo](https://1.img-dpreview.com/files/p/TC1x1S40~avatars/4932338053/1/avatar.jpg)

**Comment by lephuongbg** [comment] 2020-10-03 23:52
I'm meeting this problem also and it is very annoying when it happens. Some enterprise mail servers automatically add confidential note to every email sending outside, and that note is put outside the quote. It really becomes a chore to scroll through the length of all the thread per each email, just to get to the email's text part.

**Comment by CodeMouse92** [comment] 2021-02-11 18:39
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've migrated to Discourse:

https://community.getmailspring.com/t/improve-threading-behavior-when-moving-messages/569

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Comment by CodeMouse92** [comment] 2021-02-11 19:15
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/quoted-text-not-folded/570

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@didrip @lephuongbg: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-11 19:15 UTC
Labels: audit
