### ISSUE TITLE
Select all mail in a folder does not work in Linux

### ISSUE THREAD

**Issue by erik-alatest** [Foundry376/Mailspring#682] opened 2018-02-14 08:28 UTC
##### What operating system are you using?
Ubuntu 17.10 (Artful Aardvark)

##### What version of Mailspring are you using?
1.1.3-27

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
GSuite (gmail for business)

##### Is the issue reproducible with a particular attachment, message, signature, etc?

1. Select a message in any folder
2. Press Ctrl-A ... nothing happens
3. Use the menu `Edit`>`Select all` ... nothing happens
4. To remedy: select the first message, hold shift, select the last message

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by gmagic** [comment] 2018-02-14 11:35
Confirm this.
Fedora 27, Gnome Shell

**Comment by fcastilloec** [comment] 2018-03-01 23:02
I'm using Ubuntu 16.04 with Mailspring 1.1.4 and this bug is only half there.
If I select a folder and then do `Ctrl-A` all messages are selected, same goes if click on one message and then do `Ctrl-A`.
The problem is with using the menu `Edit > Select all` then nothing gets selected, which is weird because even the menu tells you about the keyboard shortcut which does work.
@erik-alatest and @gmagic have you updated to 1.1.4? Do you have the same behavior as I do?

**Comment by irissoftworks** [comment] 2018-03-31 11:14
+1 herem, I can confirm this is also happening on Ubuntu 17.10

**Comment by sp0rk** [comment] 2018-04-04 14:50
+1 not working on Ubuntu 16.04
Tested ctrl+a having selected a message, a folder or clicking a message
edit > select All not working either

**Comment by fcastilloec** [comment] 2018-04-04 16:10
I can confirm that this bug is still present in the last version `v1.2.1`

**Comment by omarenm** [comment] 2018-06-11 17:47
I have this same issue, Crtl+A doesn't work on any folder/label it doesn't work from the Edit menu and doesn't work even if i click on a message inside the folder.

I'm using Mailspring 1.2.2 and Ubuntu 18.04

**Comment by krupenja** [comment] 2018-07-18 18:26
Also reproducible on macOS 10.13.5.

**Comment by saadin** [comment] 2018-08-07 05:44
I can confirm this too. Both `Ctrl-A` and `Edit > Select All` not working.
Ubuntu 18.04
Gnome 3.28.2
Mailsprint 1.3.0

**Comment by fromanm1** [comment] 2018-08-12 05:58
same here, CTRL+A doesn't work at all.

CentOS Linux release 7.5.1804
GNOME Shell 3.25.4
mailspring 1.4.0-549b7968

**Comment by tpavicic** [comment] 2018-09-09 10:29
Same issue

Ubuntu 18.04.1 LTS
GNOME 3.28.2
Mailspring 1.4.2

**Comment by hrmzaqa** [comment] 2019-02-19 12:50
Same issue
Fedora 29
Mate 1.20.4
Mailspring 1.5.6

**Comment by najamsk** [comment] 2019-04-08 06:05
wow this issue persisted from 2018. i have manjaro and ctrl+A key combination and select all from menu both not working.

**Comment by andreyfedoseev** [comment] 2019-07-04 09:19
Same here.

Ubuntu 19.04
Mailspring 1.6.3

Doing "Select All" from "Edit" menu does not work either. "Select Unread" and "Select Read" work fine.

**Comment by endrureza** [comment] 2019-12-05 04:30
Well, this problem still persist. The only thing that works for me is to set shortcut. Go to **Edit > Preferences > Shortcuts**. 

On **Selection Section**, Define select all conversations to **ctrl + a**. that's all. Select all is working by doing that shortcut.

**Comment by kaluk1321** [comment] 2020-08-21 01:19
> Well, this problem still persists. The only thing that works for me is to set shortcut. Go to **Edit > Preferences > Shortcuts**.
> 
> On **Selection Section**, Define select all conversations to **ctrl + a** / anything that suits your preference. that's all. Select all is working by doing that shortcut.

Not only Ctrl + A for select all was disabled but all Ctrl commands were replaced with a star( * ). So i had to remap those as well, they are right below the select all command so it should be easy to find.

**Comment by karthikiyengar** [comment] 2020-09-04 18:49
I can also confirm that this is an issue.
NixOS 20.03, XMonad, Mailspring 1.7.8-13635bcf

**Comment by AurevoirXavier** [comment] 2020-10-19 03:45
OS: Arch Linux 
Kernel: x86_64 Linux 5.8.14-arch1-1
DE: KDE 5.75.0 / Plasma 5.20.0

Still got this in 2020-10-19.

**Comment by makmorningstar** [comment] 2020-12-30 08:36
OS: Arch Linux x86_64
Host: 20217 Lenovo IdeaPad Y510P
Kernel: 5.9.14-arch1-1
WM: i3
DE: gnome
Mailspring version: 1.7.8-13635bcf

Neither selecting "Select All" from edit menu nor Ctrl+A works.

**Comment by CodeMouse92** [comment] 2021-02-04 18:46
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/select-all-messages/171

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-04 18:46 UTC
Labels: audit
