### ISSUE TITLE
Width of folders / message list resetting (Windows)

### ISSUE THREAD

**Issue by igoramadas** [Foundry376/Mailspring#510] opened 2018-01-07 20:16 UTC
Hi there,

sometimes when I start Mailspring it resets the width of the panes. I am using the vertical panes mode (left folders, middle message list, right message contents).

I suppose it should save the layout so adding that as a bug.

Windows client on Windows 10.

**Comment by bengotow** [comment] 2018-01-11 23:45
Hey! Thanks for filing this - this /should/ have been fixed in 1.0.12 by this commit (8e7a63d1fe1dce7f0ea0d63df0e78bdc9363a47f) but maybe it didn't resolve the issue fully. Can you check that you're running 1.0.12?

**Comment by igoramadas** [comment] 2018-01-12 14:41
Yep running on 1.0.12. It doesn't happen all the time, but I still could not figure out what triggers the reset :-(

**Comment by PauloPeres** [comment] 2018-01-17 11:37
I have the same problem. Looks like it's all the time i re-start the PC.
Mailspring(1.0.12) running on Windows 10

**Comment by LuckeyBertl** [comment] 2018-02-05 10:37
I also have this problem. After restarting the PC all panels are in default widths and all account folders are expanded.
Issue appeared on v1.0.12 and it is still on v1.1.2 running on Linux Mint 18.2 Cinnamon 64-bit.

**Comment by CodeMouse92** [comment] 2021-01-30 01:13
It appears that there has been no activity on this issue for some time, so we will close it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-30 01:13 UTC
Labels: audit, needs-reproduction
