### ISSUE TITLE
Add support for Grammarly / grammar check

### ISSUE THREAD

**Issue by walkafwalka** [Foundry376/Mailspring#1402] opened 2019-03-01 18:33 UTC
**Feature Request?**

Add support for grammar check or integration with a popular grammar checker such as ~~Grammarly~~ LanguageTool.

Edit: Replaced Grammarly with LanguageTool.

**Comment by walkafwalka** [comment] 2019-03-01 18:34
> Grammarly doesn't support integration with Apple Mail, the Airmail app, or Mozilla Thunderbird. 

See https://support.grammarly.com/hc/en-us/articles/115000271852-How-can-I-check-my-emails-with-Grammarly-

**Comment by arkraft** [comment] 2019-03-04 12:48
Grammarly does not have a module which could be used here, it only has a browser extension and extension for office. I found the same request for slack and they had the same answer. Only solution for using it is to write emails in the browser using this extension.

**Comment by walkafwalka** [comment] 2019-03-04 19:09
@arkraft After researching (not heavily) alternatives, I could not find any open-source options. There are options such as https://www.grammarbot.io though.

**Comment by arkraft** [comment] 2019-03-05 08:26
I doubt people would want their emails sent to an online service, i personally would not use that if i knew it's done online.

**Comment by walkafwalka** [comment] 2019-03-05 08:35
If it were a third-party, I imagine it would be in the form of an installable plugin, not necessarily part core project. Grammarly has millions of daily users and collects ["all text, documents, or other content or information uploaded, entered, or otherwise transmitted"](https://www.grammarly.com/privacy-policy).

There are open-source grammar checkers such OpenOffice's grammary checker, [Lingucomponent](https://www.openoffice.org/lingucomponent/grammar.html).

**Comment by bengotow** [comment] 2019-03-16 19:25
Hey folks! Yeah we looked at trying to use Grammarly or a similar service, but it'd involve us sending your text to a third party on the internet as you compose messages, which I think would be too much of a privacy concern for many folks. It'd be a cool add-on someday, but I don't think we'll ever include it out-of-the-box. Thanks!

**Comment by k4ch0** [comment] 2019-10-24 21:11
+1 on this feature!!

**Comment by it2911** [comment] 2020-01-15 00:58
I need this feature.

**Comment by Metlearm** [comment] 2020-01-15 19:24
This would be a great feature to have! It would really speed up productivity whilst making everything more professional.

**Comment by aigoncharov** [comment] 2020-05-10 17:33
There's a great self-hosted open-source alternative to Gramarly - https://languagetool.org/. It would be great to have a plugin that integrates with it.

**Comment by raisty** [comment] 2020-05-31 11:55
> I doubt people would want their emails sent to an online service, i personally would not use that if i knew it's done online.

There is no big difference between copy&paste text to 3rd party service and install a plug-in.

In any case, I will prefer a self-hosted instance like languagetool.org mentioned before.

**Comment by felixcheruiyot** [comment] 2020-06-29 12:18
Any progress on this?  This is the only feature I'm missing and very important for me, especially that English is not my first language.

**Comment by walkafwalka** [comment] 2020-07-02 20:11
@raisty If copying and pasting to a third-party service is no big difference than installing a plugin, then this issue would be pointless because you can already run LanguageTool locally and copy and paste your email to it.

That being said, at the time, I had not heard of LanguageTool at the time and have long since switched to LanguageTool. I agree that an integration with LanguageTool would be better, but it should still allow users to easily use the LanguageTool servers.

By requiring a user to run the server locally, you are increasing the barrier to entry which will be a turn-off to a lot of users and may not be worth the development time.

**Comment by raisty** [comment] 2020-07-03 16:13
IMHO Mailspring still uses service for registering an account - which is totally ok - because I think somebody need keep development alive.
Still, it is the best multiplatform mail client.

I am emphasizing the fact, that the person who chooses to register an account - should have more "cloud" services like a translation tool, etc. This will increase your income as well. I don't mind pay you if you will integrate it.

BUT! In any case, you should offer mail client without any registration and remind what they can get with subscribing.

Probably I am not the only one who is thinking about forking it and remove any connection with external service.

In the end, it is just your decision and time will show if it was good.

TL;TR

Maybe you can integrate grammar tool in your service.

**Comment by CodeMouse92** [comment] 2021-01-28 02:51
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. Learn more about the changes here.

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/grammar-check-tool-integration/329

Please consider joining that community and continuing the discussion there! Votes on the feature suggestion on Discourse will increase the likelihood we implement this.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 02:51 UTC
Labels: audit, product-direction
