### ISSUE TITLE
Draft emails not saved on server

### ISSUE THREAD

**Issue by jpbaril** [Foundry376/Mailspring#728] opened 2018-02-26 20:27 UTC
##### Are there any related issues?

Maybe related to https://github.com/Foundry376/Mailspring/issues/43

##### What operating system are you using?
Ubuntu Linux 17.10

##### What version of Mailspring are you using?
1.1.4

**Bug?**
Yes

##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
It sure does.

----------------------------------------------

Drafts are automatically saved in Mailspring but they don't seem to be saved on the email server.

If I begin to write an email and then close the composition window, the email appears in the Draft folder. Just to be sure I then also close Mailspring.

If I go in another email client (Imap webmail, GMail webmail, K-9 Mail on Android, Evolution on Linux) and look at the Draft folder, my email is not there.

If I open Mailsring, my email appears in Mailspring's draft folder. (But still not in any other client)

**Comment by fcastilloec** [comment] 2018-03-01 22:54
I have the same problem. Drafts are not synced back to the email server. I'm using an IMAP account.
I double checked that the folder for Drafts was properly selected in the settings, which it was, but the problem is still there.
I tried forcing "Sync New Mail Now" to try to get those drafts back into the server but nothing...

I'm also using Ubuntu, but version 16.04. I have only tested this with IMAP, so no idea if it's related to the protocol, or this issue is found on all providers.

**Comment by dweremeichik** [comment] 2018-03-10 06:59
I believe that this has been the the behavior since N1 (arguably shouldn't be).

Also, Mailspring does not respect other applications drafts either, it treats them as normal messages.

**Comment by rukmal** [comment] 2018-04-06 07:26
+1

I verify that this issue persists with an IMAP account as well.

Mailspring Version: 1.2.1
OS Version: macOS High Sierra 10.13.4

**Comment by markojurkovic** [comment] 2018-06-13 22:59
+1, I can also confirm the issue with both of my Gmail accounts. I'm running Mailspring 1.2.2 on Ubuntu 18.04.

**Comment by danbob** [comment] 2018-10-05 14:30
+1
IMAP accounts from two different providers, using Mailspring 1.4.2 on Arch and macOS.

**Comment by stouf** [comment] 2019-07-26 02:06
Same thing here with Mailspring 1.6.3 running on Mac OS 10.14.6 with GMail accounts (IMAP).

**Comment by arturtr** [comment] 2019-08-06 02:53
+1

**Comment by rdecharette** [comment] 2019-09-23 14:19
+1 with Ubuntu 18.04 and Mailspring 1.6.3-134a0e55.
Issues are on both private IMAP account, and GMail IMAP account.

Details: if an email is saved in the IMAP/drafts folder by another IMAP application (e.g. zimbra, other IMAP client), then the drafts folder is synced server>mailspring which automatically erase any local mailspring drafts.

**Comment by fede-boinc** [comment] 2020-05-02 12:36
Same problem on both Ubuntu 19.10 and Ubuntu 20.04 LTS with mailspring 1.7.6 installed from .deb package and not snap

**Comment by CodeMouse92** [comment] 2021-02-03 19:45
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/disappearing-emails-desync/428

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

P.S. Duplicate of #304

**Closed by CodeMouse92** 2021-02-03 19:45 UTC
Labels: audit
