### ISSUE TITLE
Bug: Threads with one mail moved to trash are not found when using the search bar

### ISSUE THREAD

**Issue by simroux** [Foundry376/Mailspring#2050] opened 2020-06-10 15:56 UTC
**Describe the bug**
I had issues with some emails not showing up in my search results. After trying out a few things, here's what I believe is happening: if I delete one email from a thread (e.g. a draft email that I eventually doesn't send), then the whole thread is flagged as "in trash". It still shows up in my inbox, but is not found when searching, unless I specify "in:Trash". Not that the email I'm searching for has never been in the trash, it's only another email from the same thread that was sent to trash, and seems to affect the whole thread.
Note: This is using Mailspring 1.7.8-13635bcf on Ubuntu 20.04

**To Reproduce**
1. Go to an email thread in your inbox
2. Try searching this email using the search bar: should work
3. Delete one of the emails in the thread, either from e.g. the gmail site, or start a reply, wait for it to be saved as draft, then delete it
4. Try searching the same thread using the same email as before, it shouldn't work anymore
5. Try the same search with "in:Trash": you should find the thread back (although the thread itself shows up in the Inbox).

**Expected behavior**
I would expect the thread to still show up in the search results even if one of the emails along the thread was put into trash. Actually, I would expect it to be returned unless all emails in the thread are marked "trash" and/or "spam".

**Setup: (please complete the following information):**
 - OS: Ubuntu
 - OS Version: 20.04
 - Mailspring Version:  Mailspring 1.7.8-13635bcf

**Comment by CodeMouse92** [comment] 2021-03-02 02:34
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/threads-with-one-mail-moved-to-trash-are-not-found-when-using-the-search-bar/915

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@simroux: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 02:34 UTC
Labels: audit, bug
