### ISSUE TITLE
Bug: Cannot connect to mails account since last update

### ISSUE THREAD

**Issue by Meunsy** [Foundry376/Mailspring#1920] opened 2020-04-19 09:45 UTC
In switched to 1.7.5 today, but since then none of my accounts can connect.
I get the following message: "Mailspring cannot authenticate with xxxx@yyyy.com. Password or authentication may have been changed".

Or course, none of my password were changed in the meantime. I tried to remove all my accounts and add them again, which works in the current session. 
But if I stop Mailspring and open it again, the same issue happens, which make it unusable.

**To Reproduce**
1. Update to 1.7.5
2. Open Mailspring, you can an error message on the bottom left corner "Several of your accounts have problems"
3.Try to reconnect (which in my case, simply doesn't do anything)

**Expected behavior**
Reconnect my mail accounts.

**Setup: (please complete the following information):**
 - OS: Manjaro Linux
 - Mailspring Version: 1.7.5

**Comment by skrive** [comment] 2020-04-20 08:52
I experienced this initially, but I removed everything to do with Mailspring on my disk (cache folder, settings folder etc.) and reinstalled and now everything seems to be working great.

Try deleting the Mailspring folder in .config and try again.

**Comment by BigDon55** [comment] 2020-04-21 12:16
OK, I have found the issue and how to resolve it, at least it worked for me.

1 - Close Mailspring down.
2 - Go to ~/.config/Mailspring in File Manager
3 - Inside are 4 files, 3 are lock files. Delete them. The other file is SingletonCookie. Delete it.
4 - Close File Manager and relaunce Mailspring. Problem resolved.
5 -  No need to delete the entire .config folder and re-setup your accounts.

-DON-

**Comment by bengotow** [comment] 2020-04-22 15:32
Hey folks—thanks for reporting this. Could you try going to Developer > Show Mailsync Logs in Mailspring's menu? That'll reveal a folder that contains the mailsync-***.log files. If you could look at the bottom of those and see if there are any stack traces / errors, that will help narrow this down a lot.

**Comment by pyeguy** [comment] 2020-04-23 21:17
I'm also having this behaviour since last update and opened another issue #1933 (sorry!).

here are some stack traces in the various logs with a few surrounding lines:

```
18116 [2020-04-16 11:35:46.019] [main] [info] [local-f28530e3-9364] Running DestroyDraftTask performLocal:
18116 [2020-04-16 11:35:46.020] [main] [info] -- Hiding / detatching drafts while they're deleted...
18116 [2020-04-16 11:35:46.047] [main] [critical]  *** Stack trace:
 ***   RaiseException
 ***   _CxxThrowException
 ***   RtlGetAppContainerNamedObjectPath
 ***   RtlGetAppContainerNamedObjectPath
 ***

19648 [2020-04-16 11:35:46.334] [main] [info] Identity created at 1532397112 - using ID Schema 1
```
and a different flavor in a different log file:

```
4052 [2020-03-08 20:06:57.294] [main] [info] Waking all workers...
4052 [2020-03-08 20:06:57.294] [background] [info] Marking all folders as `busy`
4052 [2020-03-08 20:06:57.294] [metadata] [info] Metadata delta stream starting...
4052 [2020-03-08 20:06:57.302] [background] [info] Syncing folder list...
4052 [2020-03-08 20:06:57.489] [foreground] [critical]  *** Stack trace:
 ***   RtlConstructCrossVmEventPath
 ***   RtlFreeHeap
 ***   free
 ***   CRYPTO_free
 ***   ?connect@IMAPSession@mailcore@@UAEXPAW4ErrorCode@2@@Z
 ***   ?connectIfNeeded@IMAPSession@mailcore@@UAEXPAW4ErrorCode@2@@Z
 ***   ?loginIfNeeded@IMAPSession@mailcore@@UAEXPAW4ErrorCode@2@@Z
 ***   ?fetchAllFolders@IMAPSession@mailcore@@UAEPAVArray@2@PAW4ErrorCode@2@@Z
 ***   _o_iswdigit
 ***   RtlGetAppContainerNamedObjectPath
 ***   RtlGetAppContainerNamedObjectPath
 ***

4052 [2020-03-08 20:06:57.489] [background] [critical]  *** Stack trace:
 ***   RtlConstructCrossVmEventPath
 ***   RtlFreeHeap
 ***   free
 ***   CRYPTO_free
 ***   ?connect@IMAPSession@mailcore@@UAEXPAW4ErrorCode@2@@Z
 ***   ?connectIfNeeded@IMAPSession@mailcore@@UAEXPAW4ErrorCode@2@@Z
 ***   ?loginIfNeeded@IMAPSession@mailcore@@UAEXPAW4ErrorCode@2@@Z
 ***   ?fetchAllFolders@IMAPSession@mailcore@@UAEPAVArray@2@PAW4ErrorCode@2@@Z
 ***   _o_iswdigit
 ***   RtlGetAppContainerNamedObjectPath
 ***   RtlGetAppContainerNamedObjectPath
 ***

27900 [2020-03-08 20:06:57.948] [main] [info] Identity created at 1532397112 - using ID Schema 1
```

**Comment by Meunsy** [comment] 2020-04-26 09:07
> OK, I have found the issue and how to resolve it, at least it worked for me.
> 
> 1 - Close Mailspring down.
> 2 - Go to ~/.config/Mailspring in File Manager
> 3 - Inside are 4 files, 3 are lock files. Delete them. The other file is SingletonCookie. Delete it.
> 4 - Close File Manager and relaunce Mailspring. Problem resolved.
> 5 - No need to delete the entire .config folder and re-setup your accounts.
> 
> -DON-

Hi !

It did work after completely removing ~/.config/Mailspring, but for sure I needed to re-add all my mail accounts.

Everything fine so far, but I hope that I won't get the same issue with the next update...

**Comment by valentt** [comment] 2020-12-16 11:12
Check my bug: https://github.com/Foundry376/Mailspring/issues/2231

This is a dead project and dead product unfortunately, and we need to find an alternative. Any suggestions?

**Comment by CodeMouse92** [comment] 2021-01-18 21:28
It appears that this issue has been resolved, so I'll be closing it. If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-18 21:28 UTC
Labels: audit, bug

**Comment by galvari** [comment] 2021-05-18 10:49
> Hey folks—thanks for reporting this. Could you try going to Developer > Show Mailsync Logs in Mailspring's menu? That'll reveal a folder that contains the mailsync-***.log files. If you could look at the bottom of those and see if there are any stack traces / errors, that will help narrow this down a lot.

-------

I have a similar issue with my Institution mail. After I changed the password, I need to re-authenticate every time I restart mailspring (I already tried to reinstall).

I've just checked the log file at the bottom and found this error:

*** 
*** Mailspring Sync 
*** An exception occurred during program execution: 
*** {"debuginfo":"https://www.googleapis.com/oauth2/v4/token RETURNED {\n  \"error\": \"invalid_grant\",\n  \"error_description\": \"Bad Request\"\n}","key":"Invalid Response Code: 400","retryable":false,"what":"Unknown exception"}
***
