### ISSUE TITLE
Feature Request: Move Highlighter to current screen after mass delete

### ISSUE THREAD

**Issue by maxtimbo** [Foundry376/Mailspring#1989] opened 2020-05-16 15:23 UTC
**Is your feature request related to a problem? Please describe.**
Sometimes when I delete many, many emails, I lose the highlighter. I very often use my keyboard only, so I have to press up or down in order to find the highlighter.

**Describe the solution you'd like**
Never let the highlighter leave go below or above what is on screen.

**Describe alternatives you've considered**
None

**Additional context**
This is the highlighter, btw. Not sure what it's actually called....
![image](https://user-images.githubusercontent.com/8702833/82123461-8d85c000-9767-11ea-9620-fe16dce18c7f.png)

**Comment by CodeMouse92** [comment] 2021-03-01 23:48
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/move-highlighter-to-current-screen-after-mass-delete/896

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@maxtimbo: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-01 23:48 UTC
Labels: audit, enhancement
