### ISSUE TITLE
Bug: Important markers keep visible despite being disabled

### ISSUE THREAD

**Issue by retroriff** [Foundry376/Mailspring#2248] opened 2021-01-05 13:06 UTC
All my Gmail accounts have the Important markers disabled. Despite I have unchecked "Show Gmail-style important markers" from my Mailspring Settings, they are still shown.

Version 1.7.8 (1.7.8) on macOS Catalina

**Comment by CodeMouse92** [comment] 2021-01-22 18:23
Thank you for reporting this.

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

**@retroriff To help with this, since the issue is still fairly fresh, could you please start a new Thread in the appropriate category on our [Discourse](https://community.getmailspring.com)?** It would really help! (Additionally, some screenshots would be extremely helpful.)

Meanwhile, we're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-22 18:23 UTC
Labels: audit, bug
