### ISSUE TITLE
[Feature Request] Add option to not run in the background or disable notifications when closed

### ISSUE THREAD

**Issue by psivesely** [Foundry376/Mailspring#1567] opened 2019-07-08 20:29 UTC
**Feature Request?**

When I close MailSpring, I don't want to be distracted by emails. It would be nice to have the option to have close mean all processes are killed (after being allowed to finish w/ some reasonable timeout). I understand this could interfere with, e.g., delayed sending of a message, but so can disconnecting from wifi or closing my laptop lid. Alternatively, if closing MailSpring means just disabling notifications, I'd be equally happy with that as long as the background process uses minimal RAM and CPU.

I don't want to simply turn off notifications, because sometimes I'm waiting for a message, and in that case would rather be able to continue working and have the message "come to me" rather than having to check for it periodically.

If you have a suggestion for how to make things work with MailSpring's existing feature set, I'm all ears :smiley_cat: 

##### Does this feature exist in another mail client or tool you use?

Default behavior in Thunderbird.

**Comment by CodeMouse92** [comment] 2021-01-28 04:13
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/exit-on-x-button-with-no-minimize-to-tray/207/6

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 04:13 UTC
Labels: audit, enhancement
