### ISSUE TITLE
[Feature request] Add Gmail Categories

### ISSUE THREAD

**Issue by hadifarnoud** [Foundry376/Mailspring#439] opened 2017-12-15 07:58 UTC
I get a lot of emails. The only issue I have with Mailspring is not supporting [Gmail Categories](https://support.google.com/mail/answer/3094499?hl=en-GB&p=inboxtabs&visit_id=1-636489213842181232-206834662&rd=2)

I'm torn between Mailspring and Ploymail. Polymail doesn't have plugin support and Mailspring is hard to use due to large number of emails I get.

Please add category support. this is very important to many users and probably one of most important reasons people go back go Gmail web client.

**Comment by bengotow** [comment] 2017-12-18 23:20
Hey! Thanks for reporting this - unfortunately Gmail doesn't provide an API for it's tabs / categories (Promotions, etc.) It'd definitely be a nice feature to have - I sometimes go back to the Gmail UI to quickly clear all of my "Promotions" tab, but we'll have to wait for them to expose it via IMAP.

**Comment by Adoah** [comment] 2018-04-30 00:42
@bengotow I've been trying to crack this problem for a little while now, but I just can't seem to get the understanding of the program in order to fix it myself. 
I think you might find this useful for implementing the gmail tabs/categories system. 
https://developers.google.com/gmail/api/guides/labels

**Comment by hadifarnoud** [comment] 2018-05-13 05:59
they are just special labels I think. super useful to clean up the inbox

**Comment by leebickmtu** [comment] 2018-08-26 04:35
https://developers.google.com/gmail/imap/imap-extensions#access_to_gmail_labels_x-gm-labels

The above link explains that they are simply an extension to the IMAP standard, and implemented with similar API to IMAP folders. Should be possible to add to Mailspring and I would certainly love to see it supported.

**Comment by halfer53** [comment] 2019-10-17 05:59
Any update on this issue, I would really love to see that get done

**Comment by omaregb** [comment] 2019-10-23 00:06
you can set up a filter in gmail settings that attaches the label. 
If the email matches category:primary you can set the filter to attach the label "primary". Then create the label in mailspring and it works perfectly. 
It also works for category:updates, category:social and so on

**Comment by BryanWall** [comment] 2020-01-30 19:24
Airmail is able to do this, so it is possible. It looks for Category = Promotions or Category = Social. I don't know which API or field they are getting those from, but they are definitely available from Gmail via IMAP somehow.

**Comment by shenghan97** [comment] 2020-04-10 07:30
+1 Definitely want to see this! It's really useful. Looking forward to the implementation!

**Comment by jasonlyle88** [comment] 2020-05-06 23:54
Would also love to see this feature!

**Comment by CodeMouse92** [comment] 2021-01-29 23:59
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/gmail-categories-support/393

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@hadifarnoud @mononen @leebickmtu @omaregb @BryanWall : if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-29 23:59 UTC
Labels: audit
