### ISSUE TITLE
email display problem with the theme DARK

### ISSUE THREAD

**Issue by franco27** [Foundry376/Mailspring#612] opened 2018-02-01 12:07 UTC
Mailspring 112 - Windows 10 x64

with the theme installed at the installation, named DARK I had a display problem with the mail Newletter Netflix.

See the screenshots:
With DARK
![theme dark](https://user-images.githubusercontent.com/31793920/35677637-be0bcb10-0750-11e8-824d-631795ac4aa8.png)

With theme by default
![theme par defaut 2018-02-01_11-40-13](https://user-images.githubusercontent.com/31793920/35677664-d5bbf17c-0750-11e8-8cc7-7a42a4391a62.png)

**Comment by bengotow** [comment] 2018-02-03 06:53
Hey! So we used to invert images in the dark mode to make them more readable, but disabled it after some negative feedback. In this case, it'd cause the "DAMNATION" image to render properly since the words would be black, but would cause the image with the field / grass to be inverted and super ugly.

I think that it's probably best to leave the behavior as-is. Mailspring does it's best to invert solid colors in the email so they're not white and painful to read against dark mode, but doesn't alter the color of static images in the message, so things like logos and pictures of people are still the "right colors". 

This does produce some bad results, like this message from Mint:

<img width="632" alt="image" src="https://user-images.githubusercontent.com/1037212/35763947-cc0560b6-086b-11e8-8df3-76cca92c218f.png">

Maybe we can make this an option? Or we could stop inverting emails at all - though it'd cause all HTML emails to render with white backgrounds, which would be a bit of a bummer...

**Comment by Ansem93** [comment] 2018-03-01 11:28
In my opinion images should not have inverted coloros. If someone send a white image than we will handle it.

This is how I see the latest netflix email:
![immagine](https://user-images.githubusercontent.com/6626218/36842346-b4f7b4ec-1d4b-11e8-9d39-9950c57c24db.png)

**Comment by giedriusStan** [comment] 2018-03-14 14:19
I also think images should not have inverted colors, half on my emails look super weird. My vote goes for having an option to disabling it

**Comment by rob1998** [comment] 2018-06-01 14:53
+1 for that option

**Comment by StevenSeiden** [comment] 2018-12-15 02:43
<img width="766" alt="image picture" src="https://user-images.githubusercontent.com/29214251/50038174-db315280-ffe0-11e8-9ab9-7388343f018d.png">
Certain email messages also look bad when just the background is changed.

**Comment by sitefinitysteve** [comment] 2019-03-08 15:19
> I also think images should not have inverted colors, half on my emails look super weird. My vote goes for having an option to disabling it

They should be what the sender intended. I can internally deal with any inconsistencies based on my theme choice, but I would rather not have important things like that changed.

Loving the client though

**Comment by robclancy** [comment] 2020-06-02 22:34
This is still an issue? I just tried the dark theme and didn't expect it to completely butcher the emails.

**Comment by lp35** [comment] 2020-12-08 22:34
Same issue here

**Comment by CodeMouse92** [comment] 2021-02-09 23:24
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/dont-invert-images-with-dark-theme/536

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@franco27 @Ansem93 @ghost @sitefinitysteve @maxpareschi: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-09 23:24 UTC
Labels: audit, product-direction
