### ISSUE TITLE
Move emails and folders between accounts

### ISSUE THREAD

**Issue by neddy** [Foundry376/Mailspring#580] opened 2018-01-26 06:18 UTC
It would be great if we could copy emails (and folders of emails) between accounts in Mailspring. Sometimes I have emails come into one of my accounts that I need to move to another email account, I still need to open up Apple Mail to do this. 

Cheers,
Ned

**Comment by GwenaelGabard** [comment] 2018-02-05 13:42
Same here. It is a really important feature for me as well.

**Comment by map7** [comment] 2018-03-19 22:30
This feature is what I'm waiting for before we swap the company over. Currently we use Thunderbird to do this but it isn't perfect.

**Comment by jbonlinea** [comment] 2018-05-24 17:16
yes same for me here ! 
it's a deal breaker !

**Comment by quadrifolia** [comment] 2018-09-21 10:52
same for me, it’s a deal breaker!

**Comment by awunder** [comment] 2018-11-26 10:38
Hello mailspring,

first of all, i **LOVE** mailspring.. i felt in love as soon as i installed and opened it. though there's this one thing i miss which is to move emails from a folder of account a to another folder of account b.

i often receive emails which i want to archive in another account's folder structure but seem unable to do so.. that also prevents me from using mail rules as those seem to offer only folders from the selected account.

so, please make it possible to choose from other accounts folders in the mail rules setting as well as move emails from one account to another.

thanks a lot,
Andreas

**Comment by knireis** [comment] 2019-02-08 10:23
+1

**Comment by gaydenko** [comment] 2020-04-18 08:48
I'm the next treating the issue as an absolute show stopper.

**Comment by nzmuzzer** [comment] 2020-06-24 09:21
I'm loving Mailspring but after a few months of use I'm finding I'm getting an overloaded inbox because I cannot move emails to appropriate account/folder. It's becoming unusable now with so many categorised emails, which is a real shame, other than this issue it's a really nice app.

**Comment by CodeMouse92** [comment] 2021-01-28 01:20
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/move-emails-between-accounts/244

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed** 2021-01-28 02:09 UTC
Labels: migrated, product-direction
