### ISSUE TITLE
Emails Disappear From Inbox (icloud)

### ISSUE THREAD

**Issue by jkikke** [Foundry376/Mailspring#1095] opened 2018-09-26 19:28 UTC
Some messages from my inbox go missing after a while. They can be found from webmail and other clients and they are not in starred or other folders. Only a few of the newest ones are shown and others are missing.

##### Are there any related issues?

Possibly  #304 

##### What operating system are you using?

Ubuntu 18.04.1

##### What version of Mailspring are you using?

1.4.2-f587b7b7

##### Is this an email sync or connection issue?

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

I'm using only icloud atm.

[mailsync_log.zip](https://github.com/Foundry376/Mailspring/files/2421249/mailsync_log.zip)

**Comment by CodeMouse92** [comment] 2021-02-02 02:41
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/disappearing-emails-desync/428

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-02 02:41 UTC
Labels: audit
