### ISSUE TITLE
Mailspring lags alot when an email has many threads/reply history in it

### ISSUE THREAD

**Issue by GAPP99** [Foundry376/Mailspring#720] opened 2018-02-23 11:02 UTC
##### Are there any related issues?

...

##### What operating system are you using?
Windows 10 64x

##### What version of Mailspring are you using?
1.1.4-22d9f20d

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
None

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Yeah, any time a thread gets higher than like 25-30 replies, it will be very slow.

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by MyGovDoug** [comment] 2018-02-28 21:37
I also see this issue. I often have to force quit the app and restart because it locks up. 

I'm using this on a Mac.

**Comment by enoversum** [comment] 2018-03-08 09:14
This has been there since early days of Nylas Mail and does still occur.

**Comment by farfromrefug** [comment] 2018-06-20 11:38
Please look at this one. makes the app unusable.

**Comment by Carve** [comment] 2018-06-21 21:34
Still have this issue, had to revert to my previous client for the time being.. Please FIX!

**Comment by GAPP99** [comment] 2018-06-21 22:01
Same here. I upgraded to Pro subscription, but have had to revert to alternate client, because it completely freezes my computer. Had the same problem with Nylas too.

I urge you to take a look at it @bengotow

**Comment by enoversum** [comment] 2018-06-22 08:01
It seems some really nagging bugs like this one just found their permanent home in Mailspring. Even though I loved some features of Mailspring, I finally jumped off to Newton as a cross-platform, well-maintained e-mail client.

**Comment by GAPP99** [comment] 2018-06-22 08:08
Thanks for the suggestions, @enoversum. Will check it out.

**Comment by GAPP99** [comment] 2018-06-28 15:48
Alright, considering that the developers have not even bothered to respond to a critical issue like this, I'm going to assume that there's simply not enough resources to maintain Mailspring anymore.

Care to elaborate, @bengotow ?

**Comment by sommarnatt** [comment] 2018-07-19 20:50
Same issue on Ubuntu 18.04 and not really that many "fancy ui" clients to choose from on Linux.
Started to lag constantly from around 25+ replies in a thread and locks up the client totally. After restarting the client it sometimes lets you type a few characters or some lines until it locks up again.

Will switch to some other client, this makes it unusable.

**Comment by alxtr1bal** [comment] 2018-10-09 04:59
Same issue, windows 10.

**Comment by ysBach** [comment] 2018-10-24 09:14
Same here. Scanning gmail never ends (Mac OS X 10.14).....
I quit using Mailspring due to this issue.

**Comment by TeamKinetic** [comment] 2018-10-25 10:40
same here...along with the NIL issue for names in email addresses with the latest release I will have to move client..Mailspring is almost brilliant

**Comment by GAPP99** [comment] 2018-10-25 10:42
Please do update on which email client you're moving to. Cause, to be frank, I haven't yet found anything as simple to use as Mailspring, with also the read receipts, etc.

**Comment by enoversum** [comment] 2018-10-25 11:17
I did move on to Newton, which got closed down sadly. Now I stuck with Missive, which is more geared towards teams, but still works solo as well.

**Comment by TeamKinetic** [comment] 2018-10-25 11:31
EM is decent (http://emclient.com) and thunderbird with the latest skins and threaded conversations is good too.

**Comment by BhavKhatri** [comment] 2018-10-26 14:39
I'm having the same problem on Windows 10. With 20+ messages in a thread composing an email becomes interminably slow!

**Comment by GAPP99** [comment] 2018-11-24 16:48
> EM is decent (http://emclient.com) and thunderbird with the latest skins and threaded conversations is good too.

Do any of these have read receipts? That's an incredibly important feature for me. I could not see if they had it available in the two you listed.

**Comment by GAPP99** [comment] 2018-11-24 16:49
> I did move on to Newton, which got closed down sadly. Now I stuck with Missive, which is more geared towards teams, but still works solo as well.

Thank you for your recommendation, @enoversum. I'll give it a try.

**Comment by Melissa-Kay** [comment] 2018-12-07 21:36
I'm having the same issue... and I'm at the point I can't use this client anymore. I love mailspring and was contemplating upgrading until I started running into this issue. Now I have to switch to something else. Anytime a thread is >10 emails.. it starts lagging quite a bit. When it hits 20, I can't reply to a thread and have to use gmail in the browser. Testing out EM for now.

**Comment by eduardohenriquearnold** [comment] 2019-01-11 10:23
Same issue, and quite annoying too. Anyone knows the cause?

**Comment by harrync** [comment] 2019-01-11 16:00
Joining the queue on this, latest snap MS on Ubuntu/KDE plasma 5. Is totally unusable with threaded emails, opening emails can take minutes or outright crashes the app

**Comment by jord-bh** [comment] 2019-01-11 16:53
Also hitting this problem on arch linux since forever.

**Comment by BhavKhatri** [comment] 2019-01-11 20:48
I've given up and uninstalled Mailspring. I also had the problem both on Windows and Linux.

**Comment by monkeydri** [comment] 2019-02-08 02:58
Same problem on Ubuntu since... as far as I can remember. Really annoying as it forces me to create a new thread otherwise every time I try to reply a very long thread 9 times on 10 it freezes.

**Comment by mikolajzieba** [comment] 2019-02-12 06:54
The same here. Long thread is when it has ~ 10-15 replies, and it starts to lag more and more on each new reply, making client unusable at some stage.

**Comment by sanjeev2010** [comment] 2019-03-25 16:06
Is there any update on this? I'm having the same issue on a Mac, currently upgraded to Pro but might need to switch clients too!

**Comment by GAPP99** [comment] 2019-03-30 20:03
> Is there any update on this? I'm having the same issue on a Mac, currently upgraded to Pro but might need to switch clients too!

You should move on. That's what everyone else has. It's a shame, because Nylas/Mailspring is by far the best client I've used when it's actually working like it's suppose to.

**Comment by sanjeev2010** [comment] 2019-03-30 20:44
I reached out to support about this. No response.  Time to move on I guess. Any alternative recommendations?

Best wishes

Sanjeev

Sanjeev Bhadresa
E: sanjeev.bhadresa@gmail.com
P: (607) 342-8325
W: www.linkedin.com/in/sanjeevbhadresa<http://www.linkedin.com/in/sanjeevbhadresa>

________________________________

**Comment by enoversum** [comment] 2019-03-31 20:22
Yes. If you're working in a team, the comparably costly, but constantly improving Missive worked very well for me. For single-user work, the resurrected Newton Mail client is doing it for me again. Even though the latter give me bugs now and then, they're actively supporting their client and always reply to help.

**Comment by LoneWolfHT** [comment] 2019-04-02 01:41
I also have this problem

**Comment by ronilaukkarinen** [comment] 2019-04-02 10:15
I have seen this a lot lately. TIL makes it easier when you disable automatic loading of images in the threads.

**Comment by mamantoha** [comment] 2019-04-08 16:36
I also have this problem. Disabling spell checking helps a lot. But anyway, when I press Ctrl+A and delete text, the client is freeze for a few seconds.
<img width="655" alt="Screenshot_20190408_193158" src="https://user-images.githubusercontent.com/61285/55741254-8012e800-5a35-11e9-9481-69ceb89ebb49.png">

**Comment by scottybo** [comment] 2019-04-25 15:32
Echoing this sentiment - seems to happen when the mail threads are long

**Comment by jmaybe** [comment] 2019-06-09 03:03
I truly hope this can get resolved at some point as it is the one email client I can use on all (Linux, Mac, and Windows) of my work machines. However, I cannot continue using the app when it comes to a screeching halt when replying to long threads (which happens all too often).

**Comment by BhavKhatri** [comment] 2019-06-09 10:19
I think the developers have packed up shop or don't give a monkeys! I think there is a better chance of us in the UK coming together to agree on what to do with Brexit!!

**Comment by Jesterjke** [comment] 2019-07-05 18:04
@bengotow it's been a year since this issue was opened, man, you need to address it or at least give us an update. This is a critical issue (for me at least): after ~15 messages it start to lag and after around 30 it just stops responding completely when I try to reply.

**Comment by fiskhest** [comment] 2019-10-15 13:28
@bengotow Is there anything we can do to help troubleshoot this issue?

**Comment by QuakeString** [comment] 2019-10-16 14:42
> @bengotow Is there anything we can do to help troubleshoot this issue?

My mailsping freeze and ask to force close when I'm tying to reply a long tailed email.
Its take too long time to bring the reply form after pressing replyall. 
Practically I've to open gmail web and reply it, its really annoying when I'm paying for Pro version. 
Kindly fix it. I'm using it on Manjaro KDE

**Comment by BigLeagueChewie** [comment] 2020-01-07 14:37
Just adding another tally for this issue. Recently discovered Mailspring after trying just about everything else and thought I had found the solution. Was ready to pay for the premium features, but this performance issue is a deal breaker. 

Hopefully it can be fixed soon and I can come to back what seems like a very solid email tool otherwise. 

Happy to provide any information to help troubleshoot as well.

**Comment by paulux84** [comment] 2020-01-15 10:39
Same for me. My experience isn't good with mailspring and i must switch to thunderbird for this issue.
I have a lot of email with really long thread and for me is unusable

**Comment by solatis** [comment] 2020-02-12 08:46
I'm a paying user and having severe lags as described here. Often the interface is completely unusable for large threads, which are (afaik) very common in corporate settings. For an email client which positions itself as fast, this is pretty bad.

**Comment by RomanSytnyk** [comment] 2020-10-02 10:11
I have the same. Interface freezing is even on the mail list

**Comment by drholera** [comment] 2020-11-12 07:56
I have the same. Threat with 35+ letters can't be opened at all, the app is totally frozen. Ubuntu 20.04.

**Comment by Kesiunas** [comment] 2021-01-22 12:43
Same problem for me. Sometime even when the thread doesn't have much letters but is replied separately (it shows two same named threads separately) the one with less letters freezes a lot.

**Comment by CodeMouse92** [comment] 2021-01-22 18:20
Thank you for reporting this. Mailspring is historically maintained by one developer, in addition to his full-time job, and the backlog of issues — which also include questions, plenty of duplicates, and wishlist-level feature requests ­— has often been a stumbling block to ongoing development. I just joined as the Volunteer Community Manager to help mitigate that and set priorities in terms of bug fixes and feature development.

We are now in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/significant-lag-on-large-threads/183

Please consider joining that community and continuing the discussion there!

We're locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. In fact, I'm *not* closing it (unlike most migrated issues), since it strikes me as an important near-term fix.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-22 18:20 UTC
Labels: audit, performance
