### ISSUE TITLE
Bug: Cleanup Error - Mailspring was unable to reset the local cache. Error: disk I/O error

### ISSUE THREAD

**Issue by edwardsaunders7** [Foundry376/Mailspring#2202] opened 2020-11-14 13:00 UTC
**Describe the bug**
Gmail account will not sync. Attempts to re authenticate do not make any difference. Attempts to Rebuild Cache presents with "Cleanup Error - Mailspring was unable to reset the local cache. Error: disk I/O error"

**To Reproduce**
1. Go to Edit > Preferences
2. Click on Accounts
3. Click on the account, and try to rebuild cache

**Expected behavior**
Cache should clear

**Screenshots**

![Screenshot_20201114_125432](https://user-images.githubusercontent.com/51308267/99147452-ef70a500-2678-11eb-9ebb-27b4288bc049.png)

**Setup: (please complete the following information):**
 - OS: [Manjaro Linux]
 - OS Version [5.8.18-1]
 - Mailspring Version: ex: 1.7.8-13635bcf

**Comment by CodeMouse92** [comment] 2021-01-28 16:26
I cannot replicate this on Ubuntu 20.04 and Mailspring 1.8.0. The disk I/O error actually makes me suspect a hardware issue, although that would have become evident by now (two months later) if it were the problem.

@edwardsaunders7: Can you please confirm that this is still broken with 1.8.0, and if so, open a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 16:26 UTC
Labels: audit, bug
