### ISSUE TITLE
Absent attachments not detected in French when using "joindre"

### ISSUE THREAD

**Issue by EcksD33** [Foundry376/Mailspring#1218] opened 2018-11-05 23:42 UTC
Hi. When writing emails in French which include attachments, it is very common to use the verb "joindre" instead of "attacher". At the moment, using the latter (or any of its variant) but forgetting to attach anything results in a warning when trying to send the email, as expected.

However, doing the same but using any variant of the former is completely disregarded. This is most unfortunate because French speakers tend to use the phrase "ci-joint" (as in "attached") more often than "attaché".

##### Are there any related issues?
Couldn't find any (open or closed).

##### What operating system are you using?
Linux and Windows.

##### What version of Mailspring are you using?
1.5.2-31660462

**Comment by bengotow** [comment] 2018-11-22 00:13
Hey! Thanks for pointing this out—if anyone is interested in fixing this, I think it'd be a great starter issue! You can see the existing code for this if you search the codebase for `validateDraftForSending`. We might just want to check for a few more phrases to catch `ci-joint`.

**Comment by CodeMouse92** [comment] 2021-02-25 22:44
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/absent-attachments-not-detected-in-french-when-using-joindre/796

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@EcksD33: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-25 22:44 UTC
Labels: audit, composer, enhancement, good first issue
