### ISSUE TITLE
problem with local email database

### ISSUE THREAD

**Issue by TeoMorabito** [Foundry376/Mailspring#2373] opened 2022-03-09 04:53 UTC
I tried updating to 1.10 and get stuck in a loop with the following error message
Tried uninstalling and deleting the folder shown in the error message and it keeps coming back.
![Screenshot 2022-03-09 155057](https://user-images.githubusercontent.com/29008340/157375320-fe6556df-39e5-4847-b9aa-b2ce3acdcea8.png)

**Comment by zzamizz** [comment] 2022-03-09 04:54
Same https://community.getmailspring.com/t/mailspring-wont-open-after-update-1-10-0/4143

**Comment by Marvin-1802** [comment] 2022-03-09 04:56
I have the same problem.  I tried uninstall and reinstall.  Problem persists.  
Have deleted.  Hope you are able to correct this soon.

**Comment by XaniMander** [comment] 2022-03-09 04:57
same, what a coincidence I found this literally just now from google

**Comment by dixls** [comment] 2022-03-09 05:00
I was getting this too, on win11, I was able to launch the old version from this folder for now
(https://user-images.githubusercontent.com/527440/157375984-f4ff9a7e-0259-46d1-9753-f431ab4c739e.png)

**Comment by dirtmaxim** [comment] 2022-03-09 05:03
The same for me.

**Comment by frayien** [comment] 2022-03-09 05:03
Same here, quite curious of what happened for all of us to have the same issue at the same time right now... 
I reverted to an older version with no issue (fortunately I still had an old installer on my computer)

**Comment by TeoMorabito** [comment] 2022-03-09 05:05
> Same here, quite curious of what happened for all of us to have the same issue at the same time right now... I reverted to an older version with no issue (fortunately I still had an old installer on my computer)

i'm guessing we all tried to update when the update notification for 1.10 showed up

**Comment by frayien** [comment] 2022-03-09 05:08
> i'm guessing we all tried to update when the update notification for 1.10 showed up

Fair, fells odd no one updated or installed manually since the update was released, 8 days ago, and acknowledged the issue.

**Comment by extant1** [comment] 2022-03-09 05:10
Same for me on Win 11 (21H2 22000.527)

https://github.com/Foundry376/Mailspring/releases

Reverting to 1.9.2 restored the app.

**Comment by Marvin-1802** [comment] 2022-03-09 05:15
Why did they push the update if they already knew it had a problem?

**Comment by NicholasBottone** [comment] 2022-03-09 05:16
I had the same issue on Windows 10 after upgrading. Even purging the database and clean installing caused the issue to happen again. Will be downgrading in the meantime.

**Comment by CDzungx** [comment] 2022-03-09 05:29
Same issue, fully removed and re-install but still that problem.

**Comment by yretenai** [comment] 2022-03-09 05:33
> Why did they push the update if they already knew it had a problem?

Clearly they didn't test it on a windows machine, only macOS.

**Comment by Phylu** [comment] 2022-03-09 05:34
Thanks for reporting this. I will take a look and try to resolve this as fast as possible.

Please try to keep this issue clean by not posting "I have this issue too" comments, but only use it to add further information regarding the cause of the issue such as log files.

**Comment by frayien** [comment] 2022-03-09 05:51
Had a quick look at the commits,
https://github.com/Foundry376/Mailspring/commit/445546f9edb862d60961db8836305507aaa105a5
bumps sqlite version, perhaps this is what breaks it ? 
I am not familiar with the project, I tried to clone it to test but I fail to build it.

**Comment by lukefiji** [comment] 2022-03-09 05:56
Likewise here

**Comment by mmmwatchasay** [comment] 2022-03-09 06:57
> add further information regarding the cause of the issue such as log files.

Hi, I'm not sure which logs are relevant but I'll upload some if they can be useful

[mailsync-8f43f2bf.log](https://github.com/Foundry376/Mailspring/files/8212360/mailsync-8f43f2bf.log)
[mailsync-f67fb34f.log](https://github.com/Foundry376/Mailspring/files/8212361/mailsync-f67fb34f.log)
[mailsync-3baaf1c1.log](https://github.com/Foundry376/Mailspring/files/8212362/mailsync-3baaf1c1.log)

**Comment by rktic** [comment] 2022-03-09 07:03
> Thanks for reporting this. I will take a look and try to resolve this as fast as possible.
> 
> Please try to keep this issue clean by not posting "I have this issue too" comments, but only use it to add further information regarding the cause of the issue such as log files.

Question:

What's the windows background service called that keeps Mailspring alive? For now, getting out of the recurring pop-up feedback loop would help.

**Comment by frayien** [comment] 2022-03-09 07:13
>For now, getting out of the recurring pop-up feedback loop would help.

I kept killing it in the task manager and it finally died after the third or fourth time.

**Comment by deltapath-eric** [comment] 2022-03-09 07:41
Same for me on Windows 11 (21H2 22000.527)

https://github.com/Foundry376/Mailspring/releases

Reverting to 1.9.2 restored the app.

**Comment by shiipou** [comment] 2022-03-09 07:46
Idem 
![image](https://user-images.githubusercontent.com/38187238/157395711-2fbab22f-eb27-43e0-ad2b-e9fde2c7e024.png)

**Comment by MauriceNimma** [comment] 2022-03-09 08:04
Same issue here.
Is the an instruction how to revert back to 1.9.2?

**Comment by shiipou** [comment] 2022-03-09 08:13
@MauriceNimma you just have to download the old installer from here : https://github.com/Foundry376/Mailspring/releases/tag/1.9.2

**Comment by pxnt** [comment] 2022-03-09 08:18
> Question:
> 
> What's the windows background service called that keeps Mailspring alive? For now, getting out of the recurring pop-up feedback loop would help.

For me, killing the Mailspring process when the popup is open did the job.

**Comment by primski** [comment] 2022-03-09 08:21
achievement unlocked


break production database for thousands ( millions??) of users

**Comment by shiipou** [comment] 2022-03-09 08:24
@primski your data is safe if you didn't delete it manually. This update just make it incompatible with old database I think.
If you switch back to old version you recover everything.

**Comment by TuralAsgar** [comment] 2022-03-09 09:01
Same here. 

I reinstalled, deleted the folder, reinstalled it again. It doesn't work.

**Comment by HoWol76** [comment] 2022-03-09 09:09
I managed to download an older version here: https://github.com/Foundry376/Mailspring/releases/tag/1.9.2

This version works, now I have to ignore the update message ;)

**Comment by Archiware** [comment] 2022-03-09 09:40
As far as I'm aware, there have been problems with better_sqlite3 when cross compiling. I suggest that maybe, for the past releases, no upgrade of better_sqlite3 meant no new compilation and therefore no error, whereas the upgrade now lead to a new compilation that now causes that.

Has the release been cross compiled or natively on Windows? If the former is the case, probably just give compiling from Windows a try.

**Comment by akramrana** [comment] 2022-03-09 10:36
same, what a coincidence I found this literally just now from google

**Comment by AlessandroFasse** [comment] 2022-03-09 11:04
I have the same issue on two windows machines. I am really looking forward to use mailspring again. The best mail client I have ever used :)

**Comment by hermannleboss** [comment] 2022-03-09 11:34
Stop mailspring
Remove the folder `app-1.10.0` in `C:\Users\user\AppData\Local\Mailspring`
And restart your OS

**Comment by reactivedigital** [comment] 2022-03-09 11:38
I am having the same issue on windows 10 as well with 1.10 version. I reinstalled 1.9.2. until the issue has resoved.

**Comment by Dani-sw** [comment] 2022-03-09 11:40
Same for me on W7......but you guys tested this update before release it?! i Try on w7 and w10 and same error.....where you tried thi update to not show this error?

**Comment by hermannleboss** [comment] 2022-03-09 11:41
> I am having the same issue on windows 10 as well with 1.10 version. I reinstalled 1.9.2. until the issue has resoved.

Look in your user folder `..\AppData\Local\Mailspring`

**Comment by Dani-sw** [comment] 2022-03-09 11:44
> > I am having the same issue on windows 10 as well with 1.10 version. I reinstalled 1.9.2. until the issue has resoved.
> 
> Look in your user folder `..\AppData\Local\Mailspring` And remove this folder `app-1.10.0`

yes but before kill every process mailsping.exe from task manager or it will be impossible remove the 1.10 folder. Do that for remove mailspring loop message windows too.

**Comment by hermannleboss** [comment] 2022-03-09 11:51
> > > I am having the same issue on windows 10 as well with 1.10 version. I reinstalled 1.9.2. until the issue has resoved.
> > 
> > 
> > Look in your user folder `..\AppData\Local\Mailspring` And remove this folder `app-1.10.0`
> 
> yes but before kill every process mailsping.exe from task manager or it will be impossible remove the 1.10 folder. Do that for remove mailspring loop message windows too.

Yer right. 
It's why in my first intervention i asked to Stop mail spring. 
But it seems that there is another process i can't found. 
So you can juste restart your computer in case you have no other choice

**Comment by PeraDev7** [comment] 2022-03-09 12:21
Also delete the MailSpring folder from `Roaming ` folder

**Comment by bowihowi4u** [comment] 2022-03-09 12:34
Another question: Is there a way to prevent updates?

**Comment by primski** [comment] 2022-03-09 12:41
i trust if i skip this update (and by skip i mean already upgraded) and wait until the next one, the problem will be solved?

**Comment by nicolas-oliveira** [comment] 2022-03-09 13:43
Same errors here. Downgrade to 1.9.2 in windows 11 fix the problem for now. When they will fix this incompatibility?

**Comment by josiasmat** [comment] 2022-03-09 14:28
This issue was first reported 9 hours ago. And it is apparently happening to all Windows users who accept to update the application. Lay users won't know how to handle this strange message loop. So I think you guys should have suspended the offering of this update already until a fix is released.

**Comment by CountZeroOr** [comment] 2022-03-09 14:46
Especially since it keeps re-downloading the update since there's no way to disable or postpone updates in the software.

**Comment by bowihowi4u** [comment] 2022-03-09 14:50
> 

Rename "Update.exe" (stored in ...\AppData\Local\Mailspring) to "Update.exe_" or anything else :) to prevent running in the same issue again and again.

**Comment by Niko-Kk** [comment] 2022-03-09 15:06
Having the same problem here ^^

**Comment by AndrewCarvalho** [comment] 2022-03-09 15:32
Same here. Ran Mailspring.exe from command line with --mode=migrate as per an old post and got this stack trace, if it's helpful. 

[Mailspring-StackTrace.txt](https://github.com/Foundry376/Mailspring/files/8215931/Mailspring-StackTrace.txt)

**Comment by arslancharyev31** [comment] 2022-03-09 16:30
Even if you roll back to the old version, Mailspring will still forcibly install the latest broken update upon next program launch via default launcher. You have to keep launching the executable directly from the `app-1.9.2` folder to bypass the forced update. Great product design 👏

**Comment by i-zanis** [comment] 2022-03-09 17:13
I have this issue after upgrading.
I have uninstalled the application a few times and deleted the local storage. 

All the attempts haven't yielded any good result.

**Comment by evaristorivi** [comment] 2022-03-09 17:37
Same bug. I return to 1-9-2

**Comment by michalzembron** [comment] 2022-03-09 17:39
> This issue was first reported 9 hours ago. And it is apparently happening to all Windows users who accept to update the application. Lay users won't know how to handle this strange message loop. So I think you guys should have suspended the offering of this update already until a fix is released.

Even better, on their official bug report forum, there are several submissions from 8 days ago about this update on Windows. 8 days without any dev noticing it? wow

**Comment by Niko-Kk** [comment] 2022-03-09 17:47
I wonder how many people have paid for mailspring to have this kind of a
response, or fatal flaw not uncovered. Things like this, along with very
little refining that I've seen over the years, leads me to potentially stop
my subscription.

**Comment by vdisp** [comment] 2022-03-09 19:34
For me, Windows must have did an update, since my computer was restarted in the AM, and Mailspring must have updated automatically.  So, yes having the same issue.

Downloaded the old version:
https://github.com/Foundry376/Mailspring/releases/tag/1.9.2

Reinstalled and seems to have fixed the issue for now.

**Comment by carterxx** [comment] 2022-03-09 19:42
Same issue. I am also having this same issue. Unable to bypass error loop - had to entirely uninstall application. Deleted folders mentioned in error, and checked for registry issues. Only way to get app functioning again was to reinstall using a previous install .exe, as most current install .exe from website results in same issue.

**Comment by Marvin-1802** [comment] 2022-03-09 22:04
I reinstalled ver. 1.9.2 but when I restart my PC Mailspring updates automatically.  I have to delete the updated app and reinstall 1.9.2 so this is only a temp fix.  Hopefully they correct the issues with the update soon!

**Comment by Predeactor** [comment] 2022-03-09 22:26
Hello everyone, I'm quite late into the party here, but I've personally made a little guide on how to rollback Mailspring to 1.9.2 the correct way!
Hopefully this will help everyone here
https://community.getmailspring.com/t/database-error-and-unable-to-launch-app-after-installing-v1-10-0/4063/11?u=predeactor
I hope this will clear everyone's bad time into this little mess 😄

**Comment by theamazingaustin** [comment] 2022-03-09 23:06
Following the suggestions above to delete the 1.10.0 folder (and reinstall 1.9.2 in my instance) resolved the issue for me. I'll just ignore the update prompt for now.

**Comment by Marvin-1802** [comment] 2022-03-10 02:44
Very Frustrating . . . . Too bad there isn't a way to turn off the automatic update in the preferences/settings.  Every time the app restarts after it has been installed it updates to the new version: 1.10.0 and I have to start over again.

**Comment by Andychud** [comment] 2022-03-10 05:40
Windows 11 here and exactly the same issue. Until this is fixed, I just disabled Mailspring from my starting automatically and changed my taskbar shortcut to previous version C:\Users\XXXX\AppData\Local\Mailspring\app-1.9.2\mailspring.exe

**Comment by ali2077** [comment] 2022-03-10 07:34
I also got this error message with weird Chinese characters and thought I was hit with a malware attack. what's happening to this app, really?

**Comment by omiazad** [comment] 2022-03-10 09:00
I have the same issue. Installed older version and working fine.

**Comment by anwar3606** [comment] 2022-03-10 09:31
I can bypass this error by placing the win32 build of better_sqlite3 inside  \app-1.9.2\resources\app.asar.unpacked\node_modules\better-sqlite3\build\Release

But this raises another error saying NODE_MODULE_VERSION missmatch.  
It expects version 97 but I can't find better_sqlite3 build for 97. In their release page they only have build for version 98,
Does anyone have any idea how to build it for v97 ?

**Comment by KHulena** [comment] 2022-03-10 10:34
I have the same issue and like others I re-installed the prior version which works but as soon as I close it auto updates and I am back in the loop.  Is there any way to prevent this auto update?  Or create a restore point so it's easy to go back to a prior version?

**Comment by Jean-luc57** [comment] 2022-03-10 10:54
In C:\Users\"yourusername"\AppData\Local\Mailspring I renamed Update.exe to Update.exe.old

**Comment by githrdw** [comment] 2022-03-10 11:46
> I can bypass this error by placing the win32 build of better_sqlite3 inside \app-1.10.0\resources\app.asar.unpacked\node_modules\better-sqlite3\build\Release
> 
> But this raises another error saying NODE_MODULE_VERSION missmatch. It expects version 97 but I can't find better_sqlite3 build for 97. In their release page they only have build for version 98, Does anyone have any idea how to build it for v97 ?

@anwar3606 I got it working by cloning `better-sqlite3` and running the following;
```npx --no-install prebuild -r electron -t 14.2.1 --include-regex 'better_sqlite3.node$' --arch ia32```

Then Mailspring 'starts' with other module errors that seems to be Win32-phobic, fixing `keytar` will be the next step :/

**Comment by Marvin-1802** [comment] 2022-03-10 12:38
> In C:\Users\"your_user_name"\AppData\Local\Mailspring\ I renamed Update.exe to Update.exe.old This prevents updating when closing

@Jean-luc57 Thanks for this, it solved the viscous cycle :)

**Comment by working-name** [comment] 2022-03-10 15:36
I have long awaited the day where the decision to automatically update the application without a way to disable such terrible behavior would bite you in the ass. There you go, "smart" developer (whoever implemented that), you're missing an ass cheek now. Hope you learned from it.

**Comment by tfont** [comment] 2022-03-10 15:42
Also got this today when updating (coming from the default notification through Mailspring). After this failure, I decided to directly download a new installation executable from the official website, and ran as administrator, and STILL the same problem.

I could imagine that anyone who updates directly from the notification will face this corruption and fail to run the application from there.

As a programmer, this is a HUGE bug, and I am absolutely sure that Mailspring will lose a fair amount of users from this.

**Comment by working-name** [comment] 2022-03-10 15:46
@tfont there's no way to stop the auto update from the UI, no off switch anywhere. You hit dismiss on the update, but the next time mailspring starts (reboot, logout, crash, user quit from sys tray) it'll be the updated version unless you find update.exe and rename it.

**Comment by tfont** [comment] 2022-03-10 15:50
@working-name unfortunately it's a pretty bad bug! from reading the comments it's an incompatibility issue with a newer version of SQLite. Seems like the Mailspring team didn't test on a Windows 😂😂

The good news is, if they update a hotfix quick enough to roll back the version, they won't lose as many users! The average windows user won't understand this loop and will simply uninstall and never use the app again.

**Comment by resiva** [comment] 2022-03-10 16:11
*************[ Solved ]********************

This is how you can survive this 1.10 update. btw noob here.

uninstall mailspring.

delete the items inside this folder 
C:\Users\XXXX\AppData\Local\Mailspring 

{XXXX- Username}

download the Mailspring v.1.9.2 here : https://github.com/Foundry376/Mailspring/releases/download/1.9.2/MailspringSetup.exe

and install the same.

open and sign up and add just 1 account.

close the Mailspring app in the Task Manager to shut it completely.

go to C:\Users\XXXX\AppData\Local\Mailspring 

Find the file "Update.exe"

rename the file into "Update.exe.old"

go to this folder
 
C:\Users\XXXX\AppData\Local\Mailspring\app-1.9.2

find and right click on the file "mailspring.exe" and Click " Send to - Desktop (create Shortcut)"

come to desktop and find the "mailspring - Shortcut".

Use only that shortcut file to open the Mailspring from hereafter.

If error occurs repeat from step one.

Hope this Helps!

**Comment by bliet** [comment] 2022-03-10 16:46
Same here. And even if I kill the process via Task Manager, the message is shown again... in a loop.
Bye bye mailspring.

**Comment by resiva** [comment] 2022-03-10 16:52
> Same here. And even if I kill the process via Task Manager, the message is shown again... in a loop. Bye bye mailspring.

Leave the loop in the background and continue the step from Renaming Update.exe.old file.

Hope this helps.

**Comment by KHulena** [comment] 2022-03-10 16:59
I am no techy, but I opened the file location C>programData>xxxx>mailspring
and in this file there was the sneaky update file which has the bug, along
side old app 1.9.2 and I deleted this bug file and renamed the
update.exe.old.

Fingers crossed I have shut down and restarted twice and it is still working

K

**Comment by Marvin-1802** [comment] 2022-03-10 23:19
Hope they release a fix soon!  I'm hoping that it corrects this current problem along with several other bugs that make me crazy.

Does anyone know how to turn off _conversation_ view?  
I don't like _conversation_ view and can't see a way to turn it off.

**Comment by shiipou** [comment] 2022-03-11 07:44
> Hope they release a fix soon! Hope it corrects this current problem along with several other bugs that make me crazy.
> 
> Does anyone know how to turn off _conversation_ view? I don't like _conversation_ view and can't see a way to turn it off.

Sorry @Marvin-1802 : https://community.getmailspring.com/t/disable-threading-conversation-view/290/2

**Comment by steffenu** [comment] 2022-03-11 07:49
Already started testing some alternatives .... like emclient ...
pretty major  that I have to come to github to find a solution ....

**Comment by aliyazdi75** [comment] 2022-03-11 08:12
We are on the third day and still, nothing happened. I don't quite understand why don't you use the revert button on GitHub and think about a solution later?
![image](https://user-images.githubusercontent.com/20153831/157828195-ecbeea20-b082-498d-a711-dca4d8ea8992.png)

**Comment by patricioriba** [comment] 2022-03-11 08:58
Hola me funcionaba perfectamente hasta que lo actualice y me sale este error lo he desistalado y he vuelto a instalar la version anterior y funciona todo en win10
atentamente Patrick

**Comment by primski** [comment] 2022-03-11 09:23
stari ti vidš da je to angleški thread? 

> Hola me funcionaba perfectamente hasta que lo actualice y me sale este error lo he desistalado y he vuelto a instalar la version anterior y funciona todo en win10 atentamente Patrick

**Comment by githrdw** [comment] 2022-03-11 10:14
I got it working by manually building some packages (the way I described [here](https://github.com/Foundry376/Mailspring/issues/2373#issuecomment-1063969902)).

You can [download](https://github.com/Foundry376/Mailspring/files/8231008/node_modules.zip) and unpack my prebuilt packages in here:
`%LOCALAPPDATA%\Mailspring\app-1.10.0\resources\app.asar.unpacked\node_modules`

(replace folders `better-sqlite3`, `cld`, `keytar` and `windows-quiet-hours`)

https://github.com/Foundry376/Mailspring/files/8231008/node_modules.zip

**Comment by rajwanur** [comment] 2022-03-11 11:11
> I got it working by manually building some packages (the way I described [here](https://github.com/Foundry376/Mailspring/issues/2373#issuecomment-1063969902)).
> 
> You can [download](https://github.com/Foundry376/Mailspring/files/8231008/node_modules.zip) and unpack my prebuilt packages in here: `%LOCALAPPDATA%\Mailspring\app-1.10.0\resources\app.asar.unpacked\node_modules`
> 
> (replace folders `better-sqlite3`, `cld`, `keytar` and `windows-quiet-hours`)
> 
> https://github.com/Foundry376/Mailspring/files/8231008/node_modules.zip

Cheers, I can confirm that this method solve the issue. Thanks @githrdw

**Comment by DrBones** [comment] 2022-03-11 12:52
Thank you @githrdw !

The prebuild node packages worked for me too, and now 1.10.0 (or a Frankenstein version of if) runs with the 1.9.2 data. Also it doesn't automatically update anymore or present the update hint.

Nice Workaround!

**Comment by kevinjaygonz** [comment] 2022-03-11 15:23
> I got it working by manually building some packages (the way I described [here](https://github.com/Foundry376/Mailspring/issues/2373#issuecomment-1063969902)).
> 
> You can [download](https://github.com/Foundry376/Mailspring/files/8231008/node_modules.zip) and unpack my prebuilt packages in here: `%LOCALAPPDATA%\Mailspring\app-1.10.0\resources\app.asar.unpacked\node_modules`
> 
> (replace folders `better-sqlite3`, `cld`, `keytar` and `windows-quiet-hours`)
> 
> https://github.com/Foundry376/Mailspring/files/8231008/node_modules.zip

Confirm works !!!! Thanks

**Comment by Darthagnon** [comment] 2022-03-11 19:05
I had the same bug; was very worried when I saw the chinese characters (where on earth are those from? CCP doing pull requests?
![mailspring_3PUPEyNEcy](https://user-images.githubusercontent.com/20792748/157934702-a823d278-4b38-44ab-a643-d1a70a22ded9.png)
)

Mailspring uses [Squirrel](https://github.com/Squirrel/Squirrel.Windows) autoupdate on Windows, for the unavoidable updating. imo a very bad design decision. Also used by [Fork](https://fork.dev/). As many of you have already found out, rename/delete the updater exe and you'll be fine.

**Comment by working-name** [comment] 2022-03-11 21:21
> We are on the third day and still, nothing happened. I don't quite understand why don't you use the revert button on GitHub and think about a solution later? ![image](https://user-images.githubusercontent.com/20153831/157828195-ecbeea20-b082-498d-a711-dca4d8ea8992.png)

Because that requires common sense.

**Comment by Marvin-1802** [comment] 2022-03-11 21:47
Wow!  I'm sure happy that this is a free service, there's no way I would pay for $8/month for pro now with this sort of response.

Looking at Mailbird again, which I've used before and was happy with, but a little pricey.  
There is Twobird, pretty good, but only for Gmail and Outlook. 
 And there is Bluemail and EM Client too, but I think EM is overly complex for most personal user applications.

**Comment by working-name** [comment] 2022-03-11 21:48
> Wow! I'm sure happy that this is a free service, there's no way I would pay $8/month for pro now with this sort of response.
> 
> Looking at Mailbird again, which I've used before and was happy with, but a little pricey. There is Twobird, pretty good, but only for Gmail and Outlook. And there is Bluemail and EM Client too, but I think EM is overly complex for most personal user applications.

Postbox might potentially be a significant alternative - not open source, not free.

**Comment by Predeactor** [comment] 2022-03-11 21:49
@githrdw May I mention your solution/fix into [my post](https://community.getmailspring.com/t/database-error-and-unable-to-launch-app-after-installing-v1-10-0/4063/11?u=predeactor)? Or do you think it would be a bad idea to do so?

**Comment by githrdw** [comment] 2022-03-11 22:16
@Predeactor of course! 
Only thing is that this fix is somewhat temporary, so an upcoming update or re-install will remove these files.

**Comment by githrdw** [comment] 2022-03-11 22:36
@Darthagnon My assumption is that the title in the message box is not rendered properly.
Electron 14.2.1 is using Chromium it's `base::UTF8ToUTF16` to convert the app title to a default title. In the Chromium docs however, there is this statement:

```
// These convert between UTF-8, -16, and -32 strings. They are potentially slow,
// so avoid unnecessary conversions. The low-level versions return a boolean
// indicating whether the conversion was 100% valid. In this case, it will still
// do the best it can and put the result in the output buffer. The versions that
// return strings ignore this error and just return the best conversion
// possible.
```

So I guess it is a bug in Electron resulting in this Chinese-looking string because UTF8 to UTF16 went wrong.
I understand your reaction but I think this has nothing to do with China.
Your second statement about Squirrel and auto-updating is something I agree with, it is bad behaviour to update automatically and use outdated updater-frameworks.

Some traces I followed:
**Mailspring error generator we all have seen in it's full glory**
https://github.com/Foundry376/Mailspring/blob/3be72eee5c10a43f6fb9924ab1e9a33bb0f5216e/app/src/browser/application.ts#L287

**Electron 14.4 dialog src**
https://github.com/electron/electron/blob/8f487aa2cfe2a613a53b6b3552d7da3a374041da/atom/browser/ui/message_box_win.cc#L100

**Chromium src**
https://chromium.googlesource.com/chromium/src/+/HEAD/base/strings/utf_string_conversions.h

**Comment by bengotow** [comment] 2022-03-11 23:00
Hey folks! Thanks for the reports of this issue, we're looking in to it and will ship an update as soon as possible. It sounds like everyone is on Windows, but are all of you also using Windows 32-bit? I've been looking into this for hours and I think that our CI service provider moved to 64-bit machines and it caused our native node modules to implicitly build for 64-bit as well.

👍 for 32-bit, 👎 for 64-bit

**Comment by spartanhooah** [comment] 2022-03-11 23:10
Glad to finally get a response, but I'm switching to Blue Mail. It has a built-in calendar, which I like.

**Comment by githrdw** [comment] 2022-03-11 23:13
@bengotow Looks like Mailspring is running as a 32-bit app. 
I am using Windows 11 21H2 (must be 64-bit because there is no 32-bit version of Win 11 ;)
![image](https://user-images.githubusercontent.com/1455140/157986643-333defbc-3365-4c0d-93e2-72b021074653.png)

**Comment by vdisp** [comment] 2022-03-11 23:28
64bit Windows 10 here, however, MailSpring is running as a 32bit app as noted above.

**Comment by bengotow** [comment] 2022-03-11 23:31
Hey folks, thanks for the updates - could you give this version of Mailspring a spin? I believe it will resolve the issue and we can ship a patch:

https://mailspring-builds.s3.amazonaws.com/client/5cf60d4b/win32/MailspringSetup.exe

Thanks for your patience and help tracking this one down!

**Comment by AhoyLemon** [comment] 2022-03-11 23:32
Amazon says Access Denied.

**Comment by githrdw** [comment] 2022-03-11 23:34
@bengotow I think Mailspring for Windows is built 32-bit because of this setting:
https://github.com/Foundry376/Mailspring/blob/5a9d59dfacc871e35a8a3657cf1c68d3ac26e6f6/app/build/tasks/package-task.js#L135

Don't know why, bet there is a good cause.

**Comment by bengotow** [comment] 2022-03-11 23:37
> Amazon says Access Denied.

Sorry @AhoyLemon - I pasted incorrectly and edited the post above - here's the link!

https://mailspring-builds.s3.amazonaws.com/client/5cf60d4b/win-ia32/MailspringSetup.exe

I think you're right @githrdw - I think we've been shipping a Win32 binary to avoid having to ship separate 64-bit and 32-bit versions (and because Windows runtime support is *excellent* and since we don't need 64-bit data types or tons of RAM, 32-bit is just fine). 

So far, I think the issue was that the AppVeyor machine quietly became 64-bit when we upgraded our build process for Electron 14, and anything that wasn't explicitly specifying "ia32" was getting "x64" all the sudden. It looks like our SQLite and other native binaries were 64-bit, even though Electron and the rest of the app was expecting them to be 32-bit.

**Comment by githrdw** [comment] 2022-03-11 23:43
@bengotow I can imagine very well, but I am curious about your testing process.
Maybe in the future to have some kind of beta release for these kinds of major changes that you can test? Or to which we can subscribe, like a beta channel.
Pretty common with paid products.

**Comment by AhoyLemon** [comment] 2022-03-11 23:46
Hmmmm, nope. Just bringing up a blank Electron screen 

![image](https://user-images.githubusercontent.com/3413200/157991269-913cd809-3746-45ad-9f75-e22655cc4499.png)

log file attached.
[-1647042379709.log](https://github.com/Foundry376/Mailspring/files/8236502/-1647042379709.log)

**Comment by githrdw** [comment] 2022-03-12 00:24
Hehe this is good material for "Seconds before disaster".
Works like a charm now 👍

**Comment by kstorbakken** [comment] 2022-03-12 01:25
> Thanks for the notes @githrdw! I did look at the package list, but I think all the binaries should be fixed at once, if the build configuration is correct.
> 
> It looks like AppVeyor had a second cache of node modules that needed to be cleared so it'd rebuild from scratch. I wiped that and had it re-run the build (creating all the node modules again from scratch for 32-bit), and I believe this build should do it: https://mailspring-builds.s3.amazonaws.com/client/5cf60d4b/win-ia32-rebuild/MailspringSetup.exe
> 
> Sorry for the hassle with all this. I tested the Electron 14 upgrade on Windows last month when we were reviewing + merging the PR, but my primary work laptop is an M1 Mac now and won't launch my Windows VM. I made the mistake of not testing the final build going out the door on Windows and just assuming the green light from Appveyor + the PR testing was good enough. I think the issue was that when I reviewed the PR (on an old Windows laptop at the office), I was building the app locally and compiled all the native modules correctly.
> 
> Going to get the old windows laptop now, but I think that link above will do it! 🙏

Ran this as well and can confirm it's running great now. Thanks for looking into this.

**Comment by 1093i3511** [comment] 2022-03-12 03:32
> Ran this as well and can confirm it's running great now. Thanks for looking into this.

Same here as well. Fixed it. But in the end, It's 32bit. Which I'ld to replace with 64 bit.

Additionally, It's no fun at all that heading of the currently opened mail. Is added as an suffix to the related task. 

![whut](https://user-images.githubusercontent.com/597697/158002019-575f3b0e-3da7-4499-b29c-51f0343b5f59.JPG)

Therefore::  Do I really have to create an isolated linux VM solely for eMail hiding the eMail heading of the latest mail I recieved ? Lile the UI, but mailspring isn't that responsive as an 32bit application. That`s outdated. Attaching the name of the currently opened eMail to the systems task. Is simply a no go to me. 

Miss the good old days of dial up internet. It was certainly more secure in terms of privacy at least. There was no firmware name of the phone transmitted to the reciepient.

**Comment by Quentinover** [comment] 2022-03-12 12:43
Thank you for the quick intervention!

**Comment by AhoyLemon** [comment] 2022-03-12 14:43
Resolved for me as well.  Thanks @bengotow

**Comment by carterxx** [comment] 2022-03-12 16:42
> Thanks for the notes @githrdw! I did look at the package list, but I think all the binaries should be fixed at once, if the build configuration is correct.
> 
> It looks like AppVeyor had a second cache of node modules that needed to be cleared so it'd rebuild from scratch. I wiped that and had it re-run the build (creating all the node modules again from scratch for 32-bit), and I believe this build should do it: https://mailspring-builds.s3.amazonaws.com/client/5cf60d4b/win-ia32-rebuild/MailspringSetup.exe
> 
> Sorry for the hassle with all this. I tested the Electron 14 upgrade on Windows last month when we were reviewing + merging the PR, but my primary work laptop is an M1 Mac now and won't launch my Windows VM. I made the mistake of not testing the final build going out the door on Windows and just assuming the green light from Appveyor + the PR testing was good enough. I think the issue was that when I reviewed the PR (on an old Windows laptop at the office), I was building the app locally and compiled all the native modules correctly.
> 
> Going to get the old windows laptop now, but I think that link above will do it! 🙏

Can we confirm this build is working? Reinstalling, deleting old directories in AppData and renaming update.exe to .exe.old is not a huge task, but seeing as I've had to do it a few times now, I'd like to be sure. If it has been fixed, has this build been pushed to the main download link on the Mailspring page?

**Comment by adam-huganir** [comment] 2022-03-12 17:11
> I got it working by manually building some packages (the way I described [here](https://github.com/Foundry376/Mailspring/issues/2373#issuecomment-1063969902)).
> 
> You can [download](https://github.com/Foundry376/Mailspring/files/8231008/node_modules.zip) and unpack my prebuilt packages in here: `%LOCALAPPDATA%\Mailspring\app-1.10.0\resources\app.asar.unpacked\node_modules`
> 
> (replace folders `better-sqlite3`, `cld`, `keytar` and `windows-quiet-hours`)
> 
> https://github.com/Foundry376/Mailspring/files/8231008/node_modules.zip

thank you! worked like a charm

**Comment by bengotow** [comment] 2022-03-12 18:00
Hey folks! Thanks for your patience and help tracking this down - I've published the Mailspring v1.10.1 update this morning and it'll resolve the issue launching the app.

The app's auto-updater is running in the broken version, so if you launch Mailspring and see the `sqlite is not a Win32 application` error, you can wait a few minutes on that screen while the update downloads, and then force quit / log out + log back in to continue with the fixed version of Mailspring. (Unfortunately clicking "Ok" in the dialog opens the same version and not the updated version of the app.)

You can also download the latest version from https://getmailspring.com/download and run MailspringSetup.exe to get the new version.

I'm looking into Electron changes we can make so that the Windows autoupdater is less aggressive, and I sincerely apologize for any lost time and work caused by this update. If you're a Mailspring Pro user, feel free to email me at ben@foundry376.com and I'll credit your account for the quarter as thank-you for using Mailspring.

On the plus side, the Electron 14 update brought a lot of bug fixes, performance, and security updates to Mailspring's core and will make it easier for us to stay on top of improvements to the Electron platform going forward. Good things ahead!

**Comment by shiipou** [comment] 2022-03-12 18:16
> pp.)
> 
> You can also downlo

This update 10 is good, thanks no more freeze on my mail client.

**Comment by LoneWolfHT** [comment] 2022-03-13 16:28
Seems to work after the latest update

**Comment by vdisp** [comment] 2022-03-14 21:12
Now working after downloading and installing latest version from:
https://getmailspring.com/download (1.10.1x)

**Comment by shiipou** [comment] 2022-03-15 07:47
@Phylu I think this issue can be closed now.
Thanks for your work.

**Closed** 2022-03-15 16:36 UTC
Labels: bug, windows

**Comment by BenjaminHoegh** [comment] 2022-08-27 17:26
1.10 also give me this issue on MacOS 10.11.6 and ask me to rebuild it but I doesn't work

**Comment by KHulena** [comment] 2022-10-11 08:00
Thanks, I will see how this goes

Cheers kaye
