### ISSUE TITLE
Attachments (PDF) not always sending

### ISSUE THREAD

**Issue by dale76uk** [Foundry376/Mailspring#955] opened 2018-06-27 15:36 UTC
##### Are there any related issues?

...

##### What operating system are you using?
UBUNTU 18

##### What version of Mailspring are you using?
1.2.2

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
None

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Random, seems to send if I CC myself in the email
--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by franciscaconcha** [comment] 2018-06-28 15:56
I am having the same problem on Ubuntu 18.04 with Mailspring v1.2.2. So far it seems to be random which files get attached and which don't. It has happened for PDFs and images in various formats.

**Comment by dale76uk** [comment] 2018-07-01 12:03
It never fails though if you Cc another person in the email

**Comment by evcastelani** [comment] 2018-07-11 19:56
The same problem here with Ubuntu Mate 16.04 and Mailspring 1.2.2.

**Comment by cedewey** [comment] 2018-07-19 18:52
I am having the same issue on OSX 10.13.2 , Mailspring 1.3.0

**Comment by paulocoghi** [comment] 2018-07-25 15:31
Same issue here with PDFs attached on **v1.3.0**, using Ubuntu Mate 16.04.

**Comment by dale76uk** [comment] 2018-08-16 21:39
great news, updated to 1.4.1 and so far it seems to be fixed.  Subsequently, I've even upgraded to the Pro version. :-)

**Comment by joancarballo** [comment] 2018-12-14 12:50
Same issue on Windows 10 "The server cannot connect" only when I attach a PDF file.

**Comment by wallaceerick** [comment] 2019-02-20 15:48
Same issue on Windows 10.

**Comment by jjlankinen** [comment] 2019-05-15 06:16
Same issue here. Does not happen every time and very hard to predict when attachments might get left behind.

Mailspring version 1.6.1 and using Manjaro 18.0.4

**Comment by montoyah** [comment] 2019-10-31 21:19
Any improvements on this issue?

**Comment by CodeMouse92** [comment] 2021-02-09 23:03
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

Can anyone confirm that this is still broken with 1.8.0, and if so, open a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-09 23:03 UTC
Labels: audit
