### ISSUE TITLE
[Feature Request] "Move to..." menu with last locations... 

### ISSUE THREAD

**Issue by muradm** [Foundry376/Mailspring#1180] opened 2018-10-26 19:43 UTC
##### What version of Mailspring are you using? - 1.5.0

**Feature Request?**

##### Does this feature exist in another mail client or tool you use? - Yes

Both Outlook and Outlook Web Access has very nice feature, in the list of emails, right click on e-mail popup menu, where there is `Move to >` menu item. When it is selected, contents of it is like:
```
Recent Folder 1
Recent Folder 2
.
.
.
Recent Folder 10
Move to other folder...
```
Very productive feature for use with mouse, when away from keyboard, or lazy to press it. There are also a number of disadvantages in MS's implementation which can be considered straight away:
* Folder names are not prefixed with e-mail account they relate to, so if you have more than one account in Outlook and there is a folder name like `Accounting` in both accounts, from sub-menu above, you see:
```
Accounting
Accounting
.
.
.
Move to other folder...
```
So it is impossible to distinguish to which account folder message will be moved. This can be solved by prefixing for example `Account Name - Folder`. Also account may have an abbreviation letter assigned to it, so that folder name in multi-account can be displayed as `A - Folder`, `B - Folder` etc.

* Number of recent folders is not configurable in MS's implementation.

For now, I'm cleaning my mailboxes in Outlook / Web Access, because of this feature is missing.

**Comment by bengotow** [comment] 2018-11-03 17:43
Hey! This seems like a great feature and it’s definitely something we could add. I don’t think Mailspring currently tracks the folders you move mail in to to build a recent list, but it shouldn’t be too hard to add.

**Comment by CodeMouse92** [comment] 2021-02-25 21:12
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/move-to-menu-with-last-locations/795

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@muradm: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-25 21:12 UTC
Labels: audit, enhancement
