### ISSUE TITLE
Feature Request: Password changed successfully should be green

### ISSUE THREAD

**Issue by thraizz** [Foundry376/Mailspring#2096] opened 2020-07-17 10:36 UTC
**Is your feature request related to a problem? Please describe.**
When the user changes his/her password, the dialog providing feedback is currently a red info box, no matter what message is being displayed.

**Describe the solution you'd like**
- When a link has been sent for resetting the password, the dialog should be something neutral, blue e.g.
- When the password has been updated, the dialog should be green, signaling the user the success of the action.

**Additional context**
Screenshot (also note the width has been autoset and is too wide, but doesnt bother really):
![IMG_0979](https://user-images.githubusercontent.com/30572790/87777513-e803d100-c829-11ea-9672-3c14a8c75bfc.PNG)

If I find time this weekend I'll fork and submit a PR for this.

Anyway, really great app, thank you very much for it :heart:

**Comment by CodeMouse92** [comment] 2021-03-02 18:53
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/password-changed-successfully-should-be-green/935

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@thraizz: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 18:53 UTC
Labels: audit, enhancement
