### ISSUE TITLE
Language problem

### ISSUE THREAD

**Issue by serhattsnmz** [Foundry376/Mailspring#1159] opened 2018-10-24 11:38 UTC
Hey, 

My app language has been changed after upgrading 1.5.0 and I want to change it to back English. 
I couldn't find where could I change back. 

Any suggestion?

**Comment by phamhung77** [comment] 2018-10-24 12:12
You can read here https://github.com/Foundry376/Mailspring/blob/master/LOCALIZATION.md

**Comment by SimonVanacco** [comment] 2018-10-24 21:28
It seems to be impossible to choose mailspring locale "easily" in the Settings Menu. 
Maybe this could be added for the next release as it can be considered a pretty important feature?

**Comment by serhattsnmz** [comment] 2018-10-26 17:30
> You can read here https://github.com/Foundry376/Mailspring/blob/master/LOCALIZATION.md

I've read, but I still couldn't make permanent change on Windows. 
It would be more easily to change it on Settings Menu as @SimonVanacco said.

**Comment by CodeMouse92** [comment] 2021-02-18 23:08
It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-18 23:08 UTC
Labels: audit
