### ISSUE TITLE
Remove the subscription advertisement when you have more than 4 email accounts

### ISSUE THREAD

**Issue by deanpress** [Foundry376/Mailspring#1393] opened 2019-02-28 17:09 UTC
There's a virtually constant notification asking you to subscribe if you have more than 4 email accounts. It's a bit intrusive and distracting. When I had the free version I git cloned the repo just so I could remove that notification. The UX would be better (and personally I'd be more inclined to consider upgrading if I hadn't already) if the UX of the free version doesn't contain advertisements for the subscription model.

**Comment by bengotow** [comment] 2019-03-16 20:10
Hey thanks for filing this! Of course the UX would be better if there wasn't an ad - most of the internet would be nicer without ads. But then I'd be doing contract work right now instead of working on open source. ;-) 

Super awesome you cloned it and removed the banner! Maybe the annoyance factor will get more folks into open source. Jokes aside though I agree it's probably overkill. That banner was inserted ages ago and we never ran any sort of A/B tests to see if it really made a difference. I'll see if we can tone it down a bit, I don't imagine the impact would be too great.

**Comment by deanpress** [comment] 2019-03-18 14:39
@bengotow It's probably fine for the light theme, but the light notification is an eye-sore on the dark theme 😄 

As for conversions; I upgraded due to the fantastic tracking/scheduling features. That trial expiring made it an easy purchase.

**Comment by CodeMouse92** [comment] 2021-01-28 03:04
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/remove-the-subscription-advertisement-when-you-have-more-than-4-email-accounts/332

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@deanpress: if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 03:04 UTC
Labels: audit, product-direction
