### ISSUE TITLE
Draft created from Gmail and modified in MailSpring are sent with the wrong content

### ISSUE THREAD

**Issue by nchevobbe** [Foundry376/Mailspring#1306] opened 2019-01-07 22:48 UTC
**Steps to reproduce:**

1. Create a draft from Gmail
1. Type "a" in it, and save it
1. Open the email in MailSprint and edit it to "b"
1. Send it

**Actual result:**

The sent email is "a", instead of "b"

---

That's really bad. I just lost an entire evening re-writing a finely crafted, very-important email.

**Comment by bengotow** [comment] 2019-06-17 05:44
Hey @nchevobbe —thanks for reporting this. I was able to reproduce this today and figured out what was going on this evening. It looks like a race condition could cause the app to send the "last saved" version of the draft rather than the current version of the draft, which is pretty bad. Will be fixed in the next release! Sorry for the hassle.

**Comment by bengotow** [comment] 2019-07-04 13:55
Hey folks! This should be addressed in the latest release (1.6.3) that shipped earlier this week. The app should auto-update on it's own, or you can grab the new version from the releases page: https://github.com/Foundry376/Mailspring/releases/. Thanks for filing this - enjoy the update!

**Closed by bengotow** 2019-07-04 13:55 UTC
Labels: done-pending-release
