### ISSUE TITLE
No progressbar or alert or file attachment upload

### ISSUE THREAD

**Issue by ayanb1991** [Foundry376/Mailspring#793] opened 2018-03-30 08:29 UTC
##### What operating system are you using?
Linux Mint 18.3 64Bit KDE

##### What version of Mailspring are you using?
1.1.5.5834c99f

**Bug?**
When uploading files as attachment, no progress bar is shown. Even there are no alerts to clarify that if my attachments are uploaded or not. Sometimes recipient is receiving the mail without the attachment I uploaded.
##### Do you have any third-party plugins installed? If so, which ones?
No third-party plugins.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Have not checked. Currently using 1and1 as provider.

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Please add a progress bar for file attachments.

**Comment by JulienAllard** [comment] 2018-04-04 13:46
Same problem here with Linux 18.2 64Bits Cinnamon. I'm actually with version 1.1.5 but had the same issue with 1.1.4 and the one before. I'm a Pro user.

**My workaround:**
When composing a message with attachment, I go in the Draft folder to see the auto saved message that I'm actually composing. When the attachment will be uploaded, a paper clip icon will appear next to the message in Draft.

It is annoying though to always have to check that. Sometime the attachment will never join so I have to remove it from the message and put it back.

**Comment by geccentric** [comment] 2018-04-05 03:53
I experience same issue with mac client. Sometimes recipients shoot back an email saying no attachment. Problem has been happening for a while. Right now I am using  1.2.1.7e7447b6. 

The problem is interesting because I always explicitly indicate an attachment in email text, and if I forgot to choose an attachment before sending, Mailspring will always give a nice reminder. No attachment problems occur without such reminder (since i definitely chose an attachment).

**Comment by chemicalkosek** [comment] 2018-04-09 13:55
I can confirm this bug. Ubuntu 16.04 64bit. Mailspring 1.2.1-5f094887

**Comment by JulienAllard** [comment] 2018-04-11 14:40
**NEW WORKAROUND!**
I found a way to immediately to include attachments to my messages. You need to have at least two e-mail registered in mailspring.

1. Compose your message + join your attachments
2. Say you want to send your message from e-mail # 1, in the composition window, change the "From" section to e-mail # 2.
3. Change it back to e-mail # 1.
4. Bam! You can now send it

The e-mail # 2 is really just to add a second choice to choose from in the composition window. I assume that by changing it, it triggers a draft message refresh in mailspring that will also take into account the attachments.
![screenshot from 2018-04-11 10-38-25](https://user-images.githubusercontent.com/36508687/38623854-b31ab20c-3d74-11e8-9700-452516fceb39.png)

**Comment by CodeMouse92** [comment] 2021-02-18 23:27
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/attached-files-not-sent/468

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@ayanb1991: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-18 23:27 UTC
Labels: audit, needs-reproduction
