### ISSUE TITLE
Unable to add home.pl IMAP account - parsing error.

### ISSUE THREAD

**Issue by ldziubek** [Foundry376/Mailspring#1795] opened 2020-02-14 16:04 UTC
There used to be a problem syncing home.pl accounts (issue #967), which was solved. However, I encountered another error last week. I tried to send an e-mail from my account using a slightly unstable network connection. The mail spent over an hour in the Draft folder and Mailspring kept showing the "Sending message" indicator, and couldn't synchronize the account, and same thing happened if I restarted the app. I decided to remove the account and add it again, since it had sometimes helped with some issues in the past. However, now I'm unable to add the account at all - I get the Parsing error (IMAP) message. I'm using Mailspring 1.7.2-5422b259 on Fedora 31. Log attached below. Interesting fact: I can add the account without any hiccups to Thunderbird and Evolution, and I can add it to Geary, but there it fails to sync.

```
----------IMAP----------
* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN] Dovecot ready.
1 LOGIN "leszek@dziubek.biz.pl" *********
1 OK [CAPABILITY IMAP4rev1 LITERAL+ CHILDREN I18NLEVEL=1 IDLE SORT SORT=DISPLAY UIDPLUS UNSELECT QUOTA MOVE WITHIN LIST-EXTENDED LIST-STATUS SPECIAL-USE XLIST STARTTLS] Completed
2 LIST "" ""
* LIST (\Noselect) "." ""
2 OK Completed
3 XLIST "" "*"
* XLIST (\HasNoChildren \) "." "Argos"
* XLIST (\HasNoChildren \Draft) "." "DRAFTS"
* XLIST (\HasNoChildren \) "." "Euron"
* XLIST (\HasNoChildren \) "." "Gambit"
* XLIST (\HasNoChildren \Inbox) "." "INBOX"
* XLIST (\HasNoChildren \) "." "Inne"
* XLIST (\HasNoChildren \) "." "Ksi&ARk-gowo&AVsBBw-"
* XLIST (\HasNoChildren \) "." "Lionbridge"
* XLIST (\HasNoChildren \) "." "Locaria"
* XLIST (\HasNoChildren \) "." "Proz"
* XLIST (\HasNoChildren \) "." "SDL"
* XLIST (\HasNoChildren \Sent) "." "SENT"
* XLIST (\HasNoChildren \Spam) "." "SPAM"
* XLIST (\HasNoChildren \) "." "Sopoltrad"
* XLIST (\HasNoChildren \Trash) "." "TRASH"
* XLIST (\HasNoChildren \) "." "Test"
* XLIST (\HasNoChildren \) "." "confirmed-ham"
* XLIST (\HasNoChildren \) "." "confirmed-spam"
3 OK Completed
XLIST (\HasNoChildren \) "." "Argos"
```

**Comment by ldziubek** [comment] 2020-02-14 16:13
I'm not sure if this will be of any help, but I'll also attach logs from Geary:

```
Account identifier: account_01
Account provider: GEARY_SERVICE_PROVIDER_OTHER
Service type: GEARY_PROTOCOL_IMAP
Service host: serwer1913971.home.pl
Error type: GearyImapError 2
Message: a003 xlist: Connection channels closed

Back trace:
 * unknown
 * unknown
 * unknown
 * unknown
 * g_closure_invoke
 * g_signal_handler_disconnect
 * g_signal_emit_valist
 * g_signal_emit
 * unknown
 * g_subprocess_communicate_utf8
 * g_task_attach_source
 * unknown
 * g_subprocess_communicate_utf8
 * g_task_attach_source
 * unknown
 * g_subprocess_communicate_utf8
 * g_task_attach_source
 * unknown
 * g_subprocess_communicate_utf8
 * g_task_attach_source
 * unknown
 * g_subprocess_communicate_utf8
 * g_task_attach_source
 * unknown
 * g_subprocess_communicate_utf8
 * g_task_attach_source
 * unknown
 * g_subprocess_communicate_utf8
 * g_task_attach_source
 * unknown
 * g_subprocess_communicate_utf8
 * g_task_attach_source
 * unknown
 * g_subprocess_communicate_utf8
 * g_task_attach_source
 * unknown
 * unknown
 * g_list_sort_with_data
 * g_main_context_dispatch
 * g_main_context_dispatch
 * g_main_context_iteration
 * g_application_run
 * unknown
 * __libc_start_main
 * unknown

```
[Geary Problem Report - 2020-02-14 17:11:29.txt](https://github.com/Foundry376/Mailspring/files/4205359/Geary.Problem.Report.-.2020-02-14.17.11.29.txt)

**Comment by PanchoKce** [comment] 2020-02-15 08:58
Same here. Imap error with home.pl
`----------IMAP----------
* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN] Dovecot ready.
1 LOGIN "xxx@xxx" *********
1 OK [CAPABILITY IMAP4rev1 LITERAL+ CHILDREN I18NLEVEL=1 IDLE SORT SORT=DISPLAY UIDPLUS UNSELECT QUOTA MOVE WITHIN LIST-EXTENDED LIST-STATUS SPECIAL-USE XLIST STARTTLS] Completed
2 LIST "" ""
* LIST (\Noselect) "." ""
2 OK Completed
3 XLIST "" "*"
* XLIST (\HasNoChildren \Draft) "." "DRAFTS"
* XLIST (\HasNoChildren \Inbox) "." "INBOX"
* XLIST (\HasChildren \) "." "Mailspring"
* XLIST (\HasNoChildren \) "." "Mailspring.Snoozed"
* XLIST (\HasNoChildren \Sent) "." "SENT"
* XLIST (\HasNoChildren \Spam) "." "SPAM"
* XLIST (\HasNoChildren \Trash) "." "TRASH"
* XLIST (\HasNoChildren \) "." "confirmed-ham"
* XLIST (\HasNoChildren \) "." "confirmed-spam"
3 OK Completed
XLIST (\HasChildren \) "." "Mailspring"`

Any solution for this?

**Comment by bengotow** [comment] 2020-02-17 02:14
Hey folks! Thanks for filing this—the log excerpts you've provided all have this sort of pattern, where one of the XLIST response lines is arriving AFTER the `OK Completed` message:

```
* XLIST (\HasNoChildren \) "." "confirmed-spam"
3 OK Completed
XLIST (\HasNoChildren \) "." "Argos"
```

I'm not sure why that's the case - it seems like the home.pl server is sending back items after it's said that it's finished, which is an IMAP error. Thunderbird might just ignore those folders (Argos in this example), instead of complaining - hard to say. I'm afraid I don't have any suggestions - we can try to make Mailspring less strict in parsing these responses, but we use an open-source library to read/write IMAP commands so it's not part of this immediate project.

**Comment by PanchoKce** [comment] 2020-02-17 07:54
> Hey folks! Thanks for filing this—the log excerpts you've provided all have this sort of pattern, where one of the XLIST response lines is arriving AFTER the `OK Completed` message:
> 
> ```
> * XLIST (\HasNoChildren \) "." "confirmed-spam"
> 3 OK Completed
> XLIST (\HasNoChildren \) "." "Argos"
> ```
> 
> I'm not sure why that's the case - it seems like the home.pl server is sending back items after it's said that it's finished, which is an IMAP error. Thunderbird might just ignore those folders (Argos in this example), instead of complaining - hard to say. I'm afraid I don't have any suggestions - we can try to make Mailspring less strict in parsing these responses, but we use an open-source library to read/write IMAP commands so it's not part of this immediate project.

Hi @bengotow. All my accounts at home.pl just stop working. Can't use it with mailspring.
Do you think we can do anything to make the mail work again?

**Comment by meron1122** [comment] 2020-02-19 12:38
+1

**Comment by RafalKrych** [comment] 2020-02-24 14:31
Hello. Exactly same problem for me. Waiting for fix.

----------IMAP----------
* OK [CAPABILITY IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE LITERAL+ AUTH=PLAIN] Dovecot ready.
1 LOGIN "ralph@hot.pl" *********
1 OK [CAPABILITY IMAP4rev1 LITERAL+ CHILDREN I18NLEVEL=1 IDLE SORT SORT=DISPLAY UIDPLUS UNSELECT QUOTA MOVE WITHIN LIST-EXTENDED LIST-STATUS SPECIAL-USE XLIST STARTTLS] Completed
2 LIST "" ""
* LIST (\Noselect) "." ""
2 OK Completed
3 XLIST "" "*"
* XLIST (\HasNoChildren \Draft) "." "DRAFTS"
* XLIST (\HasNoChildren \Inbox) "." "INBOX"
* XLIST (\HasChildren \) "." "Mailspring"
* XLIST (\HasNoChildren \) "." "Mailspring.Snoozed"
* XLIST (\HasNoChildren \Sent) "." "SENT"
* XLIST (\HasNoChildren \Spam) "." "SPAM"
* XLIST (\HasNoChildren \) "." "Spambox"
* XLIST (\HasNoChildren \Trash) "." "TRASH"
* XLIST (\HasNoChildren \) "." "Trash"
* XLIST (\HasNoChildren \) "." "Unwanted"
* XLIST (\HasNoChildren \) "." "confirmed-ham"
* XLIST (\HasNoChildren \) "." "confirmed-spam"
3 OK Completed
XLIST (\HasChildren \) "." "Mailspring"

**Comment by pawel-wlodarski** [comment] 2020-04-03 09:59
In version 1.7.4 still not work :(

**Comment by T3sT3ro** [comment] 2020-04-10 20:45
same, have to stick to thunderbird (eww...) utill it's fixed.

**Comment by ldziubek** [comment] 2020-05-02 16:47
@PanchoKce @meron1122 @RafalKrych  @pawel-wlodarski @T3sT3ro If you'd still like to see this problem fixed, the best chance may be to write a message to home.pl tech support, providing description of the problem and link to this issue thread. The problem is actually caused by incorrect IMAP configuration on the home.pl end, it can be worked around, but they should still fix it. I have sent them a message, if more people complain about this, they may do something about it.

**Comment by PanchoKce** [comment] 2020-05-02 16:53
Yes, it still doesn't work, completely preventing the use of Mailspring ... and home.pl is one of the largest hosting company in Poland - they won't be interested either ... as I know them.

**Comment by PanchoKce** [comment] 2020-05-02 16:55
but the weird thing is that mailspring worked perfectly for several months ... up to a point ... :(

**Comment by ldziubek** [comment] 2020-05-02 17:03
I know, it was the same for me - home.pl changed something in their configuration. I don't hold much hope that they will respond to my message, if they get a number of complaints, they may eventually fix it. It's definitely not just a Mailspring issue, I had the same problem with Geary and their dev actually managed to prepare a working branch for me today, they will probably include a fix in a future release - but as I mentioned, it is just a workaround allowing the client to ignore a faulty response from server.

**Comment by PanchoKce** [comment] 2020-05-02 17:08
Sad truth, mailspring is the best email client I've ever used

**Comment by RafalKrych** [comment] 2020-05-02 17:44
I gave up with checking home.pl due to this error. I just switched to Gmail account as a main one, so I simply created redirection from home.pl e-mail to gmail. This solved this issue for me.

**Comment by FilipCEZOS** [comment] 2020-05-28 07:17
Reported this problem to home and finally they have admitted that their current platform Idea is "not supported" by springmail/spark.
They proposed to change my account to dovecot, which should fix this issue (no changes on my side), so i guess they will not be fixing it on all accounts by default anytime soon.

Anyone who still has this issue should contact home support directly to fix it.

**Comment by tosziro** [comment] 2021-01-11 08:29
Still broken. :-(

**Comment by okkindel** [comment] 2021-01-26 10:32
+1

**Comment by CodeMouse92** [comment] 2021-01-26 19:50
Since this appears to be entirely on `home.pl` to solve, and not on us, I'm closing this task.

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/unable-to-add-home-pl-imap-account-parsing-error/270

Please consider joining that community and continuing the discussion there!

@ldziubek @PanchoKce @FilipCEZOS: if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

We're locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-26 19:50 UTC
Labels: audit, mailserver-incompatibility
