### ISSUE TITLE
Feature Request: Specify a different service (OpenStreetMap, Bing Maps, etc) for sidebar address / location links

### ISSUE THREAD

**Issue by MalteKiefer** [Foundry376/Mailspring#1799] opened 2020-02-16 04:39 UTC
Good morning,

is it possible to integrate OpenStreetMap into Mailspring?
Or a possibility in the settings, to select on which map provider the location of the contact should be opened?

Thanks

**Comment by bengotow** [comment] 2020-02-16 16:36
Hey! Editing the description to make it easier for folks to find this and +1. I think this would be cool but want to confirm enough folks would be interested for a configuration option to be worth the overhead. Cheers!

**Comment by MalteKiefer** [comment] 2020-02-16 16:44
Thank you

**Comment by CodeMouse92** [comment] 2021-02-26 18:59
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/specify-a-different-service-openstreetmap-bing-maps-etc-for-sidebar-address-location-links/839

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@MalteKiefer: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-26 18:59 UTC
Labels: audit, enhancement
