### ISSUE TITLE
Super + Arrow shortcut does not resize the window (snap to right/left)

### ISSUE THREAD

**Issue by tholop** [Foundry376/Mailspring#1643] opened 2019-09-25 19:17 UTC
On Ubuntu 18.04 with Gnome desktop, I am usually able to snap windows&mdash;i.e. resize them to half the screen&mdash;on the left or on the right of my screen by using the `Super` + `RightArrow` and `Super` + `LeftArrow` shortcuts. 

However, Mailspring does not respond to these shortcuts (version 1.6.3). This is my only application that does not behave correctly to `Super` + `RightArrow` shortcut, and it is annoying when I want to quickly resize my window to write an email while reading another document.

**Comment by bengotow** [comment] 2019-10-09 02:45
Hey! Thanks for reporting this - do you remember if you installed Mailspring via Snapcraft or from the raw .deb file? Could you try running another app using snapcraft and seeing if the behavior exists there as well? I'm surprised this isn't working!

**Comment by tholop** [comment] 2019-10-09 02:55
Thanks for your reply!

I installed Mailspring via Snapcraft. On other snaps I don't have this issue.

I have the same problem on a different computer, which is also running a Gnome desktop on Ubuntu.

Interestingly, when I click on "Popout thread" to open a thread in another window, the new window responds well to the `Super` + `LeftArrow` shortcut. As a result, this bug is not too annoying because I can just pop out my email when I want to use it in split screen.

**Comment by greenisagoodcolor** [comment] 2020-05-25 15:52
Hello - I built this from AUR. Same problem in XFCE/arch. Interestingly the maximize minimize with super key works. As well as the super left and right work to snap to half size in the pop-out, just not the main screen. Also too, the default opening size is quite weird...

**Comment by greenisagoodcolor** [comment] 2020-07-18 14:47
Same problem for me arch/xfce4 installed from AUR. Interestingly - window up (horizontal upper halfscreen) and window down (horizontal lower halfscreen) work.

Doesn't work - Title left, right, upper right, upper left, lower right, lower left.

Makes its so much harder to use :(

**Comment by greenisagoodcolor** [comment] 2020-07-29 20:02
I suspect it may be due to mailspring having a forced width, if the width is greater than half of the scrreen size, perhaps that is causing the issue?

**Comment by greenisagoodcolor** [comment] 2020-07-30 16:38
Confirmed the snap issue is due to forced window sizes - if the pixels on screen are less than 1/2*mailsprings minimum horizontal length, then it won't snap.

This has to do with the forced side horizontal nature of the inboxes, which cannot go less horizontal than a fixed width. I suspect that if that could change, then it would snap o nall screens.

**Comment by greenisagoodcolor** [comment] 2020-07-30 16:39
@bengotow Confirmed the snap issue is due to forced window sizes - if the pixels on screen are less than 1/2*mailsprings minimum horizontal length, then it won't snap.

This has to do with the forced side horizontal nature of the inboxes, which cannot go less horizontal than a fixed width. I suspect that if that could change, then it would snap o nall screens.

**Comment by greenisagoodcolor** [comment] 2020-08-16 19:38
Just flagging this - can anyone point me to where the requirement for a certain window size in the app? If we removed that requirement, snapping would be enabled to on monitors with DPI < 1/2 the required size.

**Comment by patrickaldis** [comment] 2020-11-03 09:24
I can reproduce this. Is there any update?

**Comment by pascalbe-dev** [comment] 2021-01-17 09:46
I can reproduce this as well and it would be awesome if this was fixed 👍🏼

**Comment by CodeMouse92** [comment] 2021-01-18 18:37
This appears to be resolved here:

https://community.getmailspring.com/t/mailspring-doesnt-respect-ubuntu-window-placement/77/2

Please consider joining that community and continuing the discussion there!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

If the above link doesn't resolve the problem, please create a new Feature Suggestion thread on Discourse: https://community.getmailspring.com/c/features/12

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-18 18:37 UTC
Labels: audit, bug, linux, needs-reproduction
