### ISSUE TITLE
sent emails showing with "1969" date on GoDaddy IMAP 

### ISSUE THREAD

**Issue by bayareacoder** [Foundry376/Mailspring#1019] opened 2018-08-13 07:17 UTC
##### What operating system are you using?

OS X High Sierra 10.13.6

##### What version of Mailspring are you using?

1.4.0

**Bug?**
Yes. Reported before and also reported as fixed before but still seen. Emails sent from GoDaddy Workspace Email IMAP account show a Dec 31 1969 date. For some reason these emails also do not show up in Sent Items (other bug I filed) but in Inbox, and are thus messing up completely the conversation thread due to the wrong date. 
Both issues are very annoying because it makes it difficult to find sent emails which you want to find to see the open tracking.
Seems in need of a fix after being reported for months...

##### Is this an email sync or connection issue?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Yes likely GoDaddy IMAP

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Yes

**Comment by nanohard** [comment] 2018-08-22 17:33
Sounds like `UnixTime - 1second`. Everyone knows the universe was created on January 1, 1970.

**Comment by pagsball** [comment] 2020-07-27 18:22
This happens with GoDaddy. I can temporarily fix it by refreshing the caches in the accounts tab of settings but it is a very troublesome bug.

**Comment by CodeMouse92** [comment] 2021-02-05 00:02
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/sent-date-always-showing-1969-or-1970/471

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-05 00:02 UTC
Labels: audit
