### ISSUE TITLE
Compose in $EDITOR

### ISSUE THREAD

**Issue by sQVe** [Foundry376/Mailspring#1239] opened 2018-11-23 10:09 UTC
Cheers for all the work put into this application. I'm surprised how much you have managed to improve background resource management compared to Nylas Mail.

Over to my question... Would it be possible to compose mails in $EDITOR? I'm a avid Vim user and feel that I'm missing my key bindings a bit too much. Just having the option to add a button to open in $EDITOR would be enough really.

**Comment by bengotow** [comment] 2018-11-25 06:54
Hey! Ahh this would be super cool. I wonder if you could rig up a script of some sort to enable this? You couldn't really start in Mailspring and open VIM, but you could potentially pipe vim output into a new Mailspring email like this:

```
quickmail() (  trap 'rm ~/temp$$' exit; vim ~/temp$$ >/dev/tty; mailspring "mailto:?subject=Untitled&body=$(cat ~/temp$$ | xxd -plain | tr -d '\n' | sed 's/\(..\)/%\1/g' )")

quickmail
```

Then when you run the quickmail command, it runs vim in your terminal session and captures the output to a temp file. It then pipes the temp file in, url-encodes the contents using `xdd` and places that encoded body in a `mailto:` URL that opens in Mailspring. Might be a good workflow for you?

**Comment by sQVe** [comment] 2018-11-25 08:58
@bengotow That would work really well for me. Even better would be a hotkey / button to open current composed Mailspring text, but I understand if that is a bit harder to implement.

Qutebrowser handles this quite nicely. Focus a input field and press Ctrl + E and it opens Vim externally. Whenever I write to the file that qutebrowser opened in Vim the browser input is updated.

**Comment by CodeMouse92** [comment] 2021-02-25 23:00
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/compose-in-external-editor-tool/798

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@sQVe: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-25 23:00 UTC
Labels: audit, enhancement, linux
