### ISSUE TITLE
Drafts are lost

### ISSUE THREAD

**Issue by robert-winkler** [Foundry376/Mailspring#1234] opened 2018-11-16 13:29 UTC
Hi,

If sending a mail fails, the Draft is visible, but cannot be opened. 

PS.: unfortunately the mailspring contact does not answer, even if I am a subscribed user.

**Comment by RasheedAZ** [comment] 2019-10-26 05:46
I've experienced the same issue. Part of the message preview is visible but draft can neither be opened nor is it saved in Gmail.

**Comment by CodeMouse92** [comment] 2021-02-03 19:42
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/disappearing-emails-desync/428

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

P.S. Duplicate of #304

**Closed by CodeMouse92** 2021-02-03 19:42 UTC
Labels: audit
