### ISSUE TITLE
Email Triage

### ISSUE THREAD

**Issue by GammaGames** [Foundry376/Mailspring#1695] opened 2019-10-31 17:51 UTC
I think an email triage feature would be a nice feature to have available. The ideas is that all general emails come into the main inbox, and are then filtered to either FYI or Action types. Each would have a different colored tag to easily differentiate between types, and you can also easily view them by category (including uncategorized). This helps keep your main inbox empty, while letting you easily filter your important emails from the unimportant.

Instead of tagging emails and filtering the view, an alternate solution could be to allow users to choose which folders are visible under the account on the left sidebar. You could easily create a "FYI" and "TODO" folder, but if you have many other folders it is really messy. Being able to hide default folders (I don't need archive, junk mail, drafts, etc) and pin custom folders with icons to the top.

##### Does this feature exist in another mail client or tool you use?

Hiri has this email feature and it works very well. Hiri has stopped development though, so I moved to Mailspring. Here is what they say about the features (which are optional in their client):
![image](https://user-images.githubusercontent.com/7832163/67970692-05780880-fbd1-11e9-982b-24ea24e7d293.png)

**Comment by CodeMouse92** [comment] 2021-02-08 19:13
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/email-triage-feature/496

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

OP: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-08 19:13 UTC
Labels: audit
