### ISSUE TITLE
Bug: Office 365 unable to add a new account

### ISSUE THREAD

**Issue by OmarMorando** [Foundry376/Mailspring#2206] opened 2020-11-20 15:10 UTC
**Describe the bug**
Office 365 unable to add a new account.

**To Reproduce**
1. Go to 'Connect an email account'
2. Click on 'Office 365'
3. Enter username and password
4. See error "Authentication Error - Check your username and password. (IMAP)"

**Setup:**
 - OS: Kubuntu 20.04
 - Mailspring Version: 1.7.8 with Pro subscription

**Comment by Gilligan759** [comment] 2020-11-23 21:45
Yep, I have the same issue. 
I contacted support, but they haven't responded for over 2 weeks :/

**Comment by divinetouch** [comment] 2020-12-03 18:14
Are you using 2-step verification for your Office 365 account? If you do then you have to generate an app password and use that instead of your regular password.

Here is a link that explains how to generate and use an app password: https://support.microsoft.com/en-us/account-billing/using-app-passwords-with-apps-that-don-t-support-two-step-verification-5896ed9b-4263-e681-128a-a6f2979a7944

**Comment by CodeMouse92** [comment] 2021-01-21 15:29
Thank you for your patience on this issue! I know it's frustrating when you cannot connect to your email with Mailspring.

2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be a duplicate of one we've already migrated to Discourse:

https://community.getmailspring.com/t/institutional-office365-not-working/48

Please consider joining that community and continuing the discussion there.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-21 15:29 UTC
Labels: audit, bug
