### ISSUE TITLE
[Feature Request] Allow SMTP connections without authentication

### ISSUE THREAD

**Issue by timvdalen** [Foundry376/Mailspring#76] opened 2017-10-07 15:03 UTC
Please allow SMTP connections without authentication.

In Holland, it's quite common for consumer ISPs to block all traffic on commonly used SMTP servers.
ISPs require you to use their SMTP server to send email.

If you have your own email setup (or anything not offered by your ISP) you will not have an account with them, so authenticated requests are not possible.

Currently, the onboarding wizard isn't allowing me to try to connect to the server without offering authentication details.

##### Are there any related issues?

#23 

##### What operating system are you using?
Windows 8.1

##### What version of Mailspring are you using?
I can't finish onboarding so I can't check but I'm assuming latest.

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Yes, Thunderbird.

**Comment by bengotow** [comment] 2017-10-07 23:51
Hey! Thanks for filing this and providing your use case. I /think/ we should be able to add this pretty easily so I'll take a crack at it soon.

**Comment by bengotow** [comment] 2017-10-10 19:31
(Fixed in e4d61462edf086e64a309a36321ef9bcfc8f464f, will ship later today!)

**Comment by timvdalen** [comment] 2017-10-11 12:49
Just tested it, getting the following error now when I try to submit:

```
Waiting for Account JSON:

{"error":"Account is missing required fields:smtp_*"}
```

**Comment by bengotow** [comment] 2017-11-02 18:37
Hey! Thanks - just checked and it looks like this has been fixed as well.Cheers!

**Closed by bengotow** 2017-11-02 18:37 UTC
Labels: done-pending-release, enhancement

**Comment by timvdalen** [comment] 2017-11-02 19:26
I now get "Account is missing required fields:smtp configuration" whenever I attempt to connect an account.

**Comment by bengotow** [comment] 2017-12-22 18:42
Hey folks—looks like a regression caused the username field to still be required. Will be fixed in the next release.

**Comment by timvdalen** [comment] 2018-03-04 11:05
Figured I'd give this one more try:

The input validation is weird now:
* you _have_ to give a custom port number, selecting from the dropdown is invalid input (probably an unrelated issue).
* you _have_ to select "Allow insecure SSL" for both the IMAP and SMTP servers, otherwise the form isn't valid
* you have to fill in a username and password and then remove them, otherwise the form isn't valid on the first try with the fields empty

Trying to connect to the server results in:

```
******************************************************************************************SMTP******************************************************************************************


mailsmtp Last Error Code: 25

mailsmtp Last Error Location: 7
```
