### ISSUE TITLE
Archive Office365

### ISSUE THREAD

**Issue by BenjaVR** [Foundry376/Mailspring#194] opened 2017-10-18 04:00 UTC
I've added 2 Gmail accounts, and 2 Office365 accounts. With the Office365 ones I can't archive mails, only delete them. Gmail mails can be archived without any problem.

Is this normal behaviour? A limitation from Microsoft? Or is something wrong here?

**Comment by JunnanZ** [comment] 2017-10-18 07:24
I don't know yours but my Office 365 account doesn't have the "archive" action.

**Comment by agesome** [comment] 2017-10-18 08:07
I can archive emails for an Office365 account (same as web UI), but not for a plain IMAP one, even though both have an archive folder.

Suggestion: explicitly configure an archive folder in folder preferences to enable such an option?

**Comment by bengotow** [comment] 2017-10-19 01:12
Hey! This is a duplicate of #185 but I'm gonna leave this here so we don't get more duplicates :-) This will be in the next release—just need to do some more testing.

**Closed** 2017-11-28 22:56 UTC
Labels: enhancement
