### ISSUE TITLE
Feature request: RSS reader

### ISSUE THREAD

**Issue by majkinetor** [Foundry376/Mailspring#1789] opened 2020-01-30 09:01 UTC
Mail clients typicaly support RSS reading (Outlook, Thunderbird etc.). It would be nice to support it.

**Comment by bengotow** [comment] 2020-02-15 19:58
Hey thanks for reporting this! I wonder if there's an open source / gpl licensed RSS reader that we could incorporate - I think RSS usage is declining (which is really disheartening, I can't believe they pulled support from Firefox this month) but it's a fairly simple protocol and wouldn't add that much weight to the app I think.

**Comment by majkinetor** [comment] 2020-02-15 21:41
Making basic RSS reader is probably trivial and could be done within an hour.
More advanced stuff like regex filters etc may require some time. I will take a look around.

RSS will always be there IMO, usuage may decline, but its most simple protocol to get up to date..

**Comment by CodeMouse92** [comment] 2021-02-26 18:54
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/rss-feed-reader-for-mailspring/837

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@majkinetor: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-26 18:54 UTC
Labels: audit, enhancement
