### ISSUE TITLE
[Feature Request] Adaptive junk filtering

### ISSUE THREAD

**Issue by mhatvan** [Foundry376/Mailspring#1765] opened 2020-01-11 17:16 UTC
##### Description

Today, I was wondering if the "Mark as Spam" button in Mailspring actually offers me any advantage over the "Move to Trash" button. What does "Mark as Spam" do in the background? It would be cool to not have to care about incoming junk/spam emails and make it learn the pattern of emails that the user deletes right away, so that they can get moved into spam/trash folders automatically.

##### Does this feature exist in another mail client or tool you use?

Yes, in Mozilla Thunderbird and I loved it for its accuracy. A link to an explanation can be found here: https://wiki.mozilla.org/Thunderbird:Help_Documentation:Dealing_with_Junk_E-mail#Adaptive_Filtering

**Comment by bengotow** [comment] 2020-02-17 00:26
Hey! Mailspring's "Mark as Spam" option just moves the thread to your defined "spam" folder. I think that on Gmail and a few other providers the underlying mail server scans these emails and creates a model for blocking further spam, but older IMAP servers don't do anything at all.

I don't think we'll invest much time in client-side spam / junk filtering in the future. Thunderbird's client-side filtering was pretty good and we looked at pulling it or another open source project into Mailspring to do spam handling, but it'd be technically complicated because they require a lot of structured data and need to be deeply integrated into the app (to prevent things like notifications about spam emails.) It also turns out the majority of our users are connecting to mail services that perform spam filtering on their own (Fastmail, Gmail, etc.) at the mail server. Filtering server-side is much better because the volume of training data is so much higher and services can coordinate to track and identify trends.

**Comment by mhatvan** [comment] 2020-02-17 20:44
Thanks for this thorough explanation, totally understand ;)

**Comment by CodeMouse92** [comment] 2021-02-26 18:44
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/adaptive-junk-filtering/834

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@mhatvan: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-26 18:44 UTC
Labels: question
