### ISSUE TITLE
Mailspring for Apple Sillicon Macs

### ISSUE THREAD

**Issue by nicocossiom** [Foundry376/Mailspring#2228] opened 2020-12-15 15:27 UTC
**Is your feature request related to a problem? Please describe.**
Recompile the app for apple sillicon macs for better battery life

**Describe the solution you'd like**
Since the app is based on electron an React, for what I have researched it would not be too hard to recompile the app so it can be native on apple's new chips, hence, getting the performance and battery gains that come with them. 

**Describe alternatives you've considered**
None, just make it compatible pleeeeaseeee, I don't want to use Apple Mail it suckss

**Additional context**
I might be wrong here and it might not be as easy, or the app might have been updated already. If that's the case. sorry hahah I am a first year CS student so I don't know too much about this stuff yet. 
Anyway, this is the best email client and I will still use it in the rest of my devices, just a pity that I won't use it on my MacBook since it drains more battery than necessary

**Comment by CodeMouse92** [comment] 2021-02-03 22:00
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mailspring-for-apple-sillicon-macs/451

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@nicocossiom: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them. **We may also be able to use your help with this in the near future.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-03 22:00 UTC
Labels: audit, enhancement
