### ISSUE TITLE
Bug: CardDAV/Google Contacts, no embedded photos showing

### ISSUE THREAD

**Issue by Darthagnon** [Foundry376/Mailspring#1981] opened 2020-05-12 21:16 UTC
**Describe the bug**
Currently tested on Google contacts - my Gmail contacts all have embedded photos. Some of them have text notes/descriptions. Neither their photos, nor their descriptions appear.

**To Reproduce**
1. Add a Gmail account with detailed contacts (notes, profile pictures, many other fields)
2. Open Mailspring >>Menu >> Window >> Contacts
3. Detailed fields are not displayed

**Expected behavior**
Detailed fields should be displayed.

**Screenshots**

**Setup: (please complete the following information):**
 - OS: Win10 v1709
 - Mailspring Version: 1.7.6

**Comment by CodeMouse92** [comment] 2021-02-23 22:14
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/carddav-google-contacts-details-and-photos/747

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@Darthagnon: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-23 22:14 UTC
Labels: audit, bug
