### ISSUE TITLE
Recognise Common Nicknames/Titles for Recipient

### ISSUE THREAD

**Issue by flanagansteve** [Foundry376/Mailspring#1694] opened 2019-10-31 03:09 UTC
Loving Mailspring so far! One suggestion: Mailspring flags emails beginning with "Hi XXX" being sent to recipients whose name is not exactly XXX. This can make for incorrect flags in two common cases:
- For nicknames - ie, emailing Joseph Shmoseph, at josephshmoseph@gmail.com, but greeting him with "Hi Joe"
- For titles - greeting Joseph from above with "Hi Professor" if he teaches my class.

This change seems straightforward to an outsider like me, but if this idea has been discussed before and is unworkable, let me know.

**Comment by bengotow** [comment] 2020-04-16 06:07
Ahh that would be really cool! I think that the "incorrect recipient name" warning is a little rough around the edges. Now that we support contact management we might be able to do a better job of this soon since we could save other acceptable titles to the contact card. Going to tie this to our contacts feature for tracking!

**Comment by CodeMouse92** [comment] 2021-02-15 21:12
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/recognise-common-nicknames-titles-for-recipient/631

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@flanagansteve: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-15 21:12 UTC
Labels: audit, contacts
