### ISSUE TITLE
[Bug] "No Recipient" error on email send. Email shows in drafts, but is empty on draft open.

### ISSUE THREAD

**Issue by deanpress** [Foundry376/Mailspring#1604] opened 2019-08-06 14:21 UTC
Sometimes when I try to send an email, I get a "No recipient" error and the mail is reset to only containing my signature. If I check Drafts, I can see the drafted mail body there, but when I open it it's the same empty body.

##### Are there any related issues?

...

##### What operating system are you using?

Windows 10

##### What version of Mailspring are you using?

1.7.2

--

**Comment by RasheedAZ** [comment] 2019-10-26 05:50
I've had the same issue many times. I can see the preview of the message's begging but draft is completely empty when I open it. Not even the title or recipient is saved :(

Also on Windows 10 but using Mailspring 1.7.2

**Comment by deanpress** [comment] 2019-11-21 15:00
This issue still persists. It's a huge bug as large emails can get lost entirely and I have to rewrite them. This is happening on a daily basis.

At this point I either have to make a habit out of writing my emails in a separate program, or switch email clients entirely.

**Comment by MonoTovarisj** [comment] 2020-02-05 15:24
I can confirm this bug, very annoying, is there any way to recover the email in the draft folder?

**Comment by RasheedAZ** [comment] 2020-03-30 01:55
Just had this again in 1.74 :(  This is a really breaking bug as carefully thought up email drafts gets lost and inaccessible...

**Comment by RasheedAZ** [comment] 2020-03-30 01:56
> 
> 
> This issue still persists (also on 1.7.2 at this point). It's a huge bug as large emails can get lost entirely and I have to rewrite them. This is happening on a daily basis.
> 
> At this point I either have to make a habit out of writing my emails in a separate program, or switch email clients entirely.

Hey deanpress what did you do? Write in notepad or something, then copy paste in Mailspring?

Or switched to another email client?

**Comment by CodeMouse92** [comment] 2021-02-18 01:15
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/no-recipient-error-on-email-send-email-shows-in-drafts-but-is-empty-on-draft-open/687/1

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@RasheedAZ @deanpress: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-18 01:15 UTC
Labels: audit
