### ISSUE TITLE
Yandex SSL not trusted

### ISSUE THREAD

**Issue by owner** [Foundry376/Mailspring#1323] opened 2019-01-14 21:41 UTC
Ver.: latest
Internet connection: working

Error log:

```
{"account":null,"error":"ErrorCertificate","error_service":"imap","log":"----------IMAP----------\n* OK Yandex IMAP4rev1 at imap2p.mail.yandex.net:993 ready to talk with ::ffff:******:449, 2019-Jan-15 00:38:47, kcUQpkLZ0Gk1\r\n"}Verification failed:
X509_verify_cert_error_string:
unable to get local issuer certificateX509_get_subject_name:
countryName               = PL
organizationName          = Unizeto Technologies S.A.
organizationalUnitName    = Certum Certification Authority
commonName                = Certum Trusted Network CA

```

**Comment by bengotow** [comment] 2019-02-05 05:59
Hey! Thanks for reporting this - Is this on linux? It may be that you need to add this certificate to your system trust chain (unfortunately at this time there's not a great way to get Mailspring to do that...) For the meantime, you may want to connect your Yandex account using the IMAP / SMTP option from the "Add Account" screen and choose "Allow Insecure SSL".

**Comment by owner** [comment] 2019-02-05 13:00
Its on Windows 10 x64 (October 2018 Update).

With "Insecure SSL" - does work too,

**Comment by CodeMouse92** [comment] 2021-02-03 00:37
Duplicate of #214

**Closed by CodeMouse92** 2021-02-03 00:37 UTC
Labels: audit, mailserver-incompatibility
