### ISSUE TITLE
Can we please have the option to hide the left hand pane ie the account and folders pane ?

### ISSUE THREAD

**Issue by Chaupeter** [Foundry376/Mailspring#924] opened 2018-06-12 01:13 UTC
##### Are there any related issues?

...

##### What operating system are you using?
...Windows 10 Build 17686

##### What version of Mailspring are you using?
...The latest variant of 1.2.2

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...No plugins

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...The isn't and issue just a feature request

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...N/A

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...Yes most

**Comment by rykr** [comment] 2018-06-12 02:17
Yes, please.  +1000

**Comment by ploum** [comment] 2018-11-08 09:32
Adding my vote to this issue. This would make Mailspring a lot easier and distraction free for "normal use".

**Comment by bergmul** [comment] 2020-02-25 10:55
+1: I just googled on how to do it because I assumed it was possible like in any other mail program. Then I arrived here.

**Comment by bdombro** [comment] 2020-04-19 13:44
+1: Most email clients allow this now and I would <3 <3 <3 it!

**Comment by chensun-hep** [comment] 2020-06-18 11:06
+1 would love to have this feature given that everyone even Microsoft mail has it

**Comment by anunes** [comment] 2020-11-29 14:55
Last comment was on Jun 18. It is the end of Nov and still no change guess they not changing.

**Comment by CodeMouse92** [comment] 2021-02-18 01:24
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/hide-show-compact-left-panel-account-folders-pane/688

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-18 01:24 UTC
Labels: audit
