### ISSUE TITLE
[Feature Request] User Enable/Disable Action Buttons

### ISSUE THREAD

**Issue by Richyread** [Foundry376/Mailspring#997] opened 2018-07-25 21:56 UTC
**Feature Request?**

In the current version of the client [1.3.0] 3 quick actions icons are displayed when hovering over an email within main list view.

![image](https://user-images.githubusercontent.com/7470850/43229467-bd812678-905c-11e8-9f87-1f5275eb76b7.png)

Would it be possible to allow for users to select which actions are enabled/disabled on these buttons?

For example, I prefer to 'star'/flag emails that I want to come back to over a 'snooze' function and 'move to folder' rather than 'archive' function. These commands/functions are already available within the detail window of Mailspring, so it would be great if users could simply be given an option as to what quick actions they'd like to see on the main list view.

I think three most used commands is probably a good fit, so just an option within settings to select/tick/mark/choose which 3 commands users would prefer to see would be ideal.

Richy.

**Comment by bengotow** [comment] 2018-08-02 19:54
Hey! This would be a great feature to add I think. We've been looking to make the swipe actions (on touch screens and on macOS) customizable, and I think being able to customize these quick actions would be nice to add at the same time. Would be a good starter issue for someone looking to get involved as well!

**Comment by Richyread** [comment] 2018-08-03 10:34
Wow - I'm really pleased that you think it's something to take forward....but I'm also a little embarrassed to admit that the 'open-source' flag hadn't registered with me that I could actually contribute to the project too! 😳 

Having always wanted to work on something like this - where better to start than with my own suggestion....challenge accepted! :blush:

**Comment by CodeMouse92** [comment] 2021-02-03 18:14
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/customizable-swipe-button-actions/444

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-03 18:14 UTC
Labels: audit, enhancement, good first issue
