### ISSUE TITLE
Labeling an email can sometimes label other emails

### ISSUE THREAD

**Issue by victortrac** [Foundry376/Mailspring#941] opened 2018-06-18 23:27 UTC
It seems like sometimes when I label an email thread (I use the `l` shortcut), another email thread also gets applied with the same label.  I have noticed that this happens quite frequently, but haven't noticed a pattern, so I often don't notice until much later when the emails seem completely wrong.

With the last occurence, I noticed exactly what happened:
* I responded to an email, the second newest
* I navigated down a couple of email threads (using `j`, if that matters)
* I responded to the last email in the 2nd thread (using `r`)
* I labeled the 2nd thread using `l`
* I noticed that both the 2nd thread and the 1st thread (second newest email) got applied the same label

##### What operating system are you using?
Linux, Gnome-shell 3.28.2-1

##### What version of Mailspring are you using?
1.2.2-1

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail (maybe others?)

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Not sure.

**Comment by victortrac** [comment] 2018-07-05 21:58
I just managed to reproduce this again and noticed what happened:

1.  I apply a label to an email (using `l` -> selecting a lable)
2.  I archive that email using `e` shortcut
3.  Immediately I selected another email 
4.  Both emails got labeled and archived.

I believe step 3 happened before Mailspring finished with step 1 and 2, and Mailspring applied actions from the first email to the 2nd email when thing synchronized.

**Comment by andjosh** [comment] 2019-08-08 13:44
Bump. I see this happening as well.

**Comment by jurjens** [comment] 2019-10-11 08:23
+1 here as well...

**Comment by CodeMouse92** [comment] 2021-02-12 23:39
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/labeling-an-email-can-sometimes-label-other-emails/598

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@victortrac @jurjens: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-12 23:39 UTC
Labels: audit
