### ISSUE TITLE
Mailspring freezes when email conversions exceed 70+ emails

### ISSUE THREAD

**Issue by GAPP99** [Foundry376/Mailspring#914] opened 2018-06-04 11:03 UTC
Hey guys. First off thanks for an awesome software, I'm a pro user, and quite happy with some of the features you're providing. That said, there is a few things that is very annoying. :-)

##### What operating system are you using?
Windows 10 x64

##### What version of Mailspring are you using?
1.2.2

--

**Bug?**
Every time a email conversion gets above 70+ emails, it's almost impossible to even open the email and much harder to actually write an email. It freezes inside those emails or just restarts Mailspring and the email shows up with a red "in editing" icon.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Nah, it's with any email provider.

Looking forward to hearing from you, as it's something that's been going on for the last few months. I upgraded to Pro hoping that it'd go away for some reason.

**Comment by CodeMouse92** [comment] 2021-02-03 02:41
Thank you for reporting this. 2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/mailspring-has-high-cpu-usage/87

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-03 02:41 UTC
Labels: audit
