### ISSUE TITLE
The whole client freezes when there are connection issues

### ISSUE THREAD

**Issue by JuhG** [Foundry376/Mailspring#1147] opened 2018-10-19 10:08 UTC
##### What operating system are you using?

Both Windows and Mac.

##### What version of Mailspring are you using?

Latest.

##### Is this an email sync or connection issue?

Connection issue.

When my internet is gone, the whole client just freezes and everything becomes unclickable.
When I can finally open a label for example, it shows a gray background and nothing else.
This happened multiple times on both operating systems.

Shouldn't it show the already downloaded emails?

**Comment by majkinetor** [comment] 2020-01-19 10:32
I have it at least couple of times per day.

**Comment by CodeMouse92** [comment] 2021-02-13 00:26
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/the-whole-client-freezes-when-there-are-connection-issues/602

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@JuhG @majkinetor: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-13 00:26 UTC
Labels: audit
