### ISSUE TITLE
Feature Request:  “Reply all“ Popups before replying to multiple people 

### ISSUE THREAD

**Issue by shenghan97** [Foundry376/Mailspring#2040] opened 2020-06-03 19:53 UTC
**Is your feature request related to a problem? Please describe.**
I’ve got an recruitment email sent to me with multiple recipients.  I intended to reply to the sender but didn’t notice that all the other recipients were automatically added to my reply. It is a very embarrassing moment. 

**Describe the solution you'd like**

I suggest that if there are multiple recipients in the original email, there should be a pop up or drop down to ask if they want to reply all or just the sender after the user pressing the reply button. Email client like Spark has this feature:
![C4BF1748-AD2A-4CA4-86FF-8402112E3FA7](https://user-images.githubusercontent.com/8342250/83682752-5c541f00-a5b2-11ea-9771-11065f919226.jpeg)

Thanks!!

**Describe alternatives you've considered**

**Additional context**
Add any other context or screenshots about the feature request here. If this feature exists in another email product or tool you use (eg: Thunderbird), be sure to describe their implementation and/or include screenshots!

**Comment by CodeMouse92** [comment] 2021-03-02 02:18
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/reply-all-popups-before-replying-to-multiple-people/912

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@shenghan97: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 02:18 UTC
Labels: audit, enhancement
