### ISSUE TITLE
HIGH CPU USAGE

### ISSUE THREAD

**Issue by maborak** [Foundry376/Mailspring#1344] opened 2019-01-29 16:03 UTC
The CPU is always 80% used only by Mailspring  (Intel Core i9-7920X X-Series )

All i have is 3 email accounts.

```
/bin/bash /snap/mailspring/309/usr/share/mailspring/resources/app.asar.unpacked/mailsync --mode sync --info MYMAIL1
/bin/bash /snap/mailspring/309/usr/share/mailspring/resources/app.asar.unpacked/mailsync --mode sync --info MYMAIL2
/bin/bash /snap/mailspring/309/usr/share/mailspring/resources/app.asar.unpacked/mailsync --mode sync --info MYMAIL3
```

Maybe the problem is because each account has around 139.000 emails?

This is a problem because the sync  is running i background and cannot control it ( just kill the process) not doing a good usage of IMAP IDLE.

Any idea or future patch to solve this problem?

thank you.

**Comment by bengotow** [comment] 2019-02-05 05:08
Hey! Mailspring will run quietly (via IMAP IDLE) once it's completed a scan of your mailboxes for search. Before it starts idling on the mailbox, it fetches headers + subject lines for every message in your mailbox. It usually goes pretty quickly, but with 139,000 emails and a slowish IMAP server, it could take 6+ hours. The UI in the bottom left of the app should let you know when it's done and is idling.

Sorry for the hassle! If you keep seeing this CPU usage after ~24 hours of Mailspring running let me know - looking at the Mailsync logs (from the developer menu) will show any errors it's encountering and we can see if it's stuck in a loop of some sort (maybe? haven't seen that happen in a while...)

**Comment by wonx** [comment] 2019-05-03 11:15
I am also experimenting this problem. Mailspring always uses one CPU core to the 100%, draining the battery of my laptop (I cannot have it opened in the background). I have three google accounts and one outlook account. Sometimes it stops for a while, but after a few minutes or hours, starts again. 

I've been experiencing this for a few months now, so I don't think it's just a matter of waiting a few hours.

**Comment by jolars** [comment] 2019-05-11 14:06
I am getting this as well but only occasionally.

**Comment by andersonjw2021** [comment] 2019-05-13 17:51
I am also experiencing a rather high CPU usage that forces my laptop to heat up tremendously. In my case, it's only noticed when connected to wi-fi. For context, the bottom UI states "Syncing your mailbox..."; however, all folders are filled green and there is one instance that states at the top, "Applying labels... (1)" that does not change count if this helps.

**Comment by flantel** [comment] 2019-05-31 19:04
Yes, I really like Mailspring but the CPU usage is a problem.

**Comment by Galaxy0419** [comment] 2019-06-10 04:59
Same problem with the lastest version on Arch with GNOME.  Even there no mails in inbox.  CPU usage is still high.

**Comment by deanroker123** [comment] 2019-06-12 20:53
I have this issue, but only when I am replying to an email as I type it gets slower and slower. CPU goes to 100%, when I stop it goes back to normal. its the Mailspring Default process.

**Comment by valentt** [comment] 2019-06-25 06:51
I have same Gmail inbox over IMAP and it also causes all 4 cores to go full 100% for few minutes when checking new messages. IMAP must be optimised in order for this mail client to be considered a pro (paid) and not a hobby (free) app.

**Comment by pablocal** [comment] 2019-08-15 12:03
Same problem here. I had to uninstall because the CPU usage (and overheating) was a real problem.

**Comment by Kabouik** [comment] 2019-09-11 20:52
Same here with Solus. CPU gets to 100% when sending an email or during synchronizations, and still high CPU use even when Mailpile does not seem to be doing anything.

**Comment by meriops** [comment] 2019-10-15 13:44
Same thing here with an ms exchange account via davmail on a linux box. Mailspring also causes davmail to have a high CPU usage, as if it was constantly fetching / sending mails or something. And, it's probably related, "scanning messages" shows for all folders and has not progressed beyond 6% for the Archive folder since I installed mailspring a couple weeks ago...

**Comment by saidaspen** [comment] 2019-10-22 04:14
Here it maxes out one core  for  a couple of minutes. Then it goes down for a minute and then right back up to 90% again. But, its not constant. It does drop off, at least for a little bit, every now and then.

**Comment by awunder** [comment] 2019-11-19 21:09
same issue here..

![Selection_239](https://user-images.githubusercontent.com/13486613/69186629-d88b8700-0ae6-11ea-83b6-7a4a4e2a7778.png)

gnome with latest mailspring

**Comment by jerm** [comment] 2020-01-17 00:58
Feeling this, too. Mailspring normally runs at 25-30% on my i7 mbp and routinely jumps up to 100% for minutes at a time.

Recent experiments while traveling shows that shutting down Mailspring is a quick hack to double my battery life.

Happy to help debug this if i can.

FWIW I run 7 mailboxes, a couple of them pretty old. All gmail/google apps. A several GB of email in some, but a couple are nearly empty.

**Comment by dmytro-shchurov** [comment] 2020-06-10 06:37
Just after a booting of a computer, Mailspring went crazy.
![image](https://user-images.githubusercontent.com/772293/84233924-9746dd00-aaf3-11ea-8719-825ae6133d95.png)
It's like a random generator decided to check for an email.
By the way, one of two Google's inboxes contained few new unread messages at that moment, but I didn't see them in the client. May be this high load relates to unsuccessful attempts to read an inbox.
I understand that no logs means no solution, but may be such info will help.
After I quit from the app and restarted it, everything was fine, and new messages were downloaded.
```
Kernel: 5.6.15-1-MANJARO x86_64 bits: 64 Desktop: KDE Plasma 5.18.5 Distro: Manjaro Linux 
```

**Comment by yorikvanhavre** [comment] 2020-09-18 10:56
I met this issue too, and it seems pretty much caused by mailspring gathering large quantities of emails from the net. When I added my different mailboxes, some pretty large with many years of emails, several threads popped up (named "main", would be cool to have more significant names ;) ) that did together eat up quite a lot of CPU (70 or 80%). After a couple of hours, all emails got imported, all the extra threads finished, leaving mailspring running only one thread that consumes a totally normal amount of resources (2% CPU). So this seems mostly like a "first launch" issue

**Comment by complyue** [comment] 2020-09-21 07:00
I just installed Mailspring as Thunderbird stopped working for me, I really like Mailspring, but met this issue too. I'm considering uninstalling it if this can't be solved in a month or so. 

I think there can be a lot of people switching to Mailspring with huge amount of legacy messages in their account. I guess the Pro users Mailspring Pro is targeting, may have developed good habit of archiving historic messages to relieve the scanner/indexer, making this issue of less priority for the team, it's pity but I can understand.

I do software engineering myself, but just a light email user, so hesitate to make contribution improving this issue. With uneducated guess, I think there may be spin-locks somewhere in scanning messages over IMAP, hope it helps a tiny bit.

**Comment by sendittokeith** [comment] 2020-10-24 05:07
Came back nearly a year later thinking this would be resolved :-(

**Comment by dmytro-shchurov** [comment] 2020-10-24 08:29
For all concerned.
In my case this problem has gone in some weird way. First I installed KDE and tried Mailspring there (with all possible tricks to solve it). Then i3 (but I doubt this somehow relates). Then I wanted to try Materia Shell and installed GNOME. GNOME didn't satisfy me, and I got back to i3 ... and the problem had gone!
This is only a speculation, but I think this is a workaround: install GNOME first, then your desired DE, and Mailspring. For me it worked in Manjaro.

PS Sorry for reddit-like post.

**Comment by CodeMouse92** [comment] 2021-01-18 22:32
Thank you for reporting this. 2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mailspring-has-high-cpu-usage/87

Please consider joining that community and continuing the discussion there! Bonus: if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Comment by CodeMouse92** [comment] 2021-01-18 22:33
Duplicate of #2218

**Closed by CodeMouse92** 2021-01-18 22:32 UTC
Labels: audit, needs-reproduction, performance
