### ISSUE TITLE
[Feature Request] Finer notification control

### ISSUE THREAD

**Issue by gitbobbed** [Foundry376/Mailspring#332] opened 2017-11-10 18:52 UTC
Would be nice to have the option to only have toasts/banners appear in the notification area if I get new e-mail (and not every time one of my recipients opens a message).

**Feature Request?**
Not sure this applies since other e-mail clients don't offer the same functionality...

**Comment by oxysoft** [comment] 2018-01-23 14:02
+1 I'm surprised this isn't in already. Toast notifications should be a big priority.

**Comment by CodeMouse92** [comment] 2021-02-11 22:13
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/finer-notification-control/573

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@gitbobbed: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-11 22:13 UTC
Labels: audit, enhancement
