### ISSUE TITLE
Bug: Mailspring does not refresh when switching to it after a while

### ISSUE THREAD

**Issue by dmocek** [Foundry376/Mailspring#2149] opened 2020-09-18 18:13 UTC
**Describe the bug**
It looks like there's a refresh problem deleting messages if I switch to Mailspring after a while.  I've only tested this with one account.  If I switch to Mailspring after using other apps for a while and select and delete messages, the UI does no refresh and show the messages as having been deleted.  I need to select another mailbox and com back to the Inbox to get it to refresh. Once I do this, things are back to normal.  If I then select a message and delete it, Mailspring removes the message and refreshes properly.

**To Reproduce**
1. Run Mailspring.
2. Switch to other apps and come back to Mailspring after a while (I don't know exactly how long, but for me it's typically quite a while like an hour or a few hours).
3. Select one or more messages to delete them using the delete key.  You'll get the pop-up stating the messages have been archived, but the screen remains the same.  All of the "deleted" messages still display and are selected.

**Expected behavior**
When I delete messages, the list of messages should always refresh, showing the messages as removed.

**Screenshots**

**Setup: (please complete the following information):**
 - OS:Ubuntu Linux
 - OS Version:  v20.04 LTS
 - Mailspring Version: 1.7.8

**Additional context** 
Add any other context about the problem here. If this issue is related to a particular account or email service, be sure to mention it so this report is actionable!

**Comment by CodeMouse92** [comment] 2021-03-03 03:06
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mailspring-does-not-refresh-when-switching-to-it-after-a-while/953

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@dmocek: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-03 03:06 UTC
Labels: audit, bug
