### ISSUE TITLE
Replied message disappears when responding

### ISSUE THREAD

**Issue by victorvanr** [Foundry376/Mailspring#1952] opened 2020-04-29 07:30 UTC
Hi there, 

When I respond to a message in a thread (on panel view), the content of the replied message disappears. Anyone else has this issue and is there a possibility to repair this? 

Thanks, 

Victor

**Comment by CodeMouse92** [comment] 2021-02-12 21:33
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/replied-message-disappears-when-responding/592

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@victorvanr: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-12 21:33 UTC
Labels: audit
