### ISSUE TITLE
Sent emails showing Jan 1 1970 date on GoDaddy IMAP

### ISSUE THREAD

**Issue by vishnumaiea** [Foundry376/Mailspring#1665] opened 2019-10-15 09:16 UTC
##### Are there any related issues?

Yes - https://github.com/Foundry376/Mailspring/issues/1019

##### What operating system are you using?

Windows 10 Version 10.0.18362 Build 18362

##### What version of Mailspring are you using?
(eg: 1.6.3 or 1.7.0 - this is shown in Mailspring's main menu.)

1.7.1

**Bug?**

Yes

##### Is this an email sync or connection issue?

No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Yes probably with GoDaddy IMAP configuration

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Yes. Tested this multiple times and problem persists.

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

Not a feature request.

**Screenshot?**

![image](https://user-images.githubusercontent.com/10383395/66818176-8b9e1900-ef5a-11e9-8270-7cf2c5a194aa.png)

**Comment by dev8546** [comment] 2020-06-18 07:39
Hello Team, I am also facing the same issue. It is really annoying as thread of the email get messed up. Any idea when we are going to fix and release this one.

**Comment by dev8546** [comment] 2020-06-18 07:40
Mine version is 1.7.8 which seems to be the latest one and still this bug is persisting. Is there any workaround for this? Any help will work. Our email is also hosted with the Godaddy

**Comment by pagsball** [comment] 2020-08-03 17:43
As a workaround, I "rebuild cache" multiple times every day. It's in Preferences > Accounts > At the bottom, the "Rebuild Cache" button.

Obviously I would prefer the bug be fixed, but this workaround at least makes messages show up in the right place when I'm searching.

**Comment by CodeMouse92** [comment] 2021-02-05 00:02
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/sent-date-always-showing-1969-or-1970/471

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-05 00:02 UTC
Labels: audit
