### ISSUE TITLE
[Feature Request] Apply mail rules to another account

### ISSUE THREAD

**Issue by QuantumMecha** [Foundry376/Mailspring#1040] opened 2018-08-23 11:24 UTC
I would like to be able to apply my mail rules from one email account to another account.

It would be nice if I could select which accounts the rules can be applied to, or if I could copy the mail rules to another account.

Alternatively, if rule creation was made easier (#83 for example) this could be worked around.

**Comment by jocksdev** [comment] 2018-09-05 12:34
Duplicate of #1043

**Comment by CodeMouse92** [comment] 2021-01-29 21:25
Thank you for reporting this. 2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/create-new-rule-from-address-in-the-context-menu/385/3

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-29 21:25 UTC
Labels: audit
