### ISSUE TITLE
Bug: I can't get the CSS from the Labels Menu 

### ISSUE THREAD

**Issue by phackwer** [Foundry376/Mailspring#2003] opened 2020-05-21 20:50 UTC
**Describe the bug**
When I open the inspector and try to get the CSS classes from the Labels menu that are on a popover div, content is removed from body. I can't finish my theme!

**To Reproduce**
1. Open inspector
2. Click the labels menu
3. try to see the content of mailpopover to get the CSS
4. content is gone as menu is removed from dom tree.

**Expected behavior**
Where is the CSS documentation?!

**Additional context** 
I just want to finish my pitch black DarkKnight theme that you can see here:
https://github.com/phackwer/DarkKnight-Mailspring-theme

Obs: I know the .less file could be better, I just want it to work.

**Comment by CodeMouse92** [comment] 2021-02-23 17:53
Sorry for the delay in response! 2020 brought development to a grinding halt. It's restarted again.

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/i-cant-get-the-css-from-the-labels-menu/740

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@phackwer: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-23 17:53 UTC
Labels: audit, bug
