### ISSUE TITLE
Drafts folder non-functional

### ISSUE THREAD

**Issue by palefire19** [Foundry376/Mailspring#590] opened 2018-01-29 14:02 UTC
##### What operating system are you using?
MacOS 10.13.2

##### What version of Mailspring are you using?
1.1.1

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Doubt it

##### Is the issue reproducible with a particular attachment, message, signature, etc?

The drafts folder has become essentially non functional since 1.1.1 or 1.1.0

This seems to consistently reproduce it for me:
- Open up Mailspring
- Go to the drafts folder (often this first time I get "No Messages" even though I definitely have drafts)
- Go to another folder
- Go to the drafts folder again - totally blank screen comes up, crashes Mailspring

**Comment by palefire19** [comment] 2018-01-29 14:04
Seems possibly related to #587

**Comment by bengotow** [comment] 2018-01-29 15:42
Hey folks—I've been able to reproduce this, will get this patched ASAP. Looks like it's related to the move to Electron 1.8.

**Comment by palefire19** [comment] 2018-01-29 16:08
Thanks so much @bengotow !!

**Comment by bengotow** [comment] 2018-01-29 20:35
Hey folks—the fix for this has been shipped in 1.1.2. The app will auto-update in the next few hours, or you can download the new version directly from https://getmailspring.com/download. Enjoy!

**Closed by bengotow** 2018-01-29 20:35 UTC
Labels: bug, done-pending-release
