### ISSUE TITLE
Loading individual mail is slow / doesn't load

### ISSUE THREAD

**Issue by samtuke** [Foundry376/Mailspring#1606] opened 2019-08-08 11:43 UTC
Loading the email body in the right hand pane is very slow or doesn't load at all. The loading animation repeats on loop. Thunderbird loads the messages usually instantly, or within a few seconds, for the same mail and the same email account.

##### What operating system are you using?

Fedora 30

##### What version of Mailspring are you using?

1.6.3

**Comment by CodeMouse92** [comment] 2021-02-08 20:27
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/mailspring-has-high-cpu-usage/87

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-08 20:27 UTC
Labels: audit
