### ISSUE TITLE
[Feature Request] Quick Unsubscribe from Lists

### ISSUE THREAD

**Issue by pgebheim** [Foundry376/Mailspring#1501] opened 2019-05-17 02:38 UTC
Hello!

I looked and didn't find a feature for this in mailspring, but its something that exists in other email tools (e.g. Outlook Mobile).

Could mailspring off a "Quick Unsubscribe" for emails which contain an unsubscribe url included in their headers? A quick action for this common thing makes maintaining a sane mailbox much easier.

##### Does this feature exist in another mail client or tool you use?
Yes! Outlook on Android (at least) has this. Sparkmail, Windows Mail app, etc do not however.
...

**Comment by bengotow** [comment] 2019-05-26 20:32
Hey! This is a great idea and something we're hoping to do soon. There's been a bit of work on it in the past (as an external plugin), but we're revisiting the implementation of that to tie it into the client more closely. (The plugin version came with some performance downsides because it had to request additional headers from the mail server for each email in your mailbox.) Stay tuned!

**Comment by pgebheim** [comment] 2019-05-26 20:43
Great!

I was thinking of doing it in a plug-in myself but it wasn't obvious that the headers existed so I didn't keep digging.

Good to hear!

Paul

________________________________

**Comment by ted-gould** [comment] 2019-06-27 15:24
I think this would be a cool feature, noting that it got praise in the NYTimes article on Superhuman.

https://www.nytimes.com/2019/06/27/technology/superhuman-email.html

Going through the article, seems like the only feature Mailspring is missing, except the price tag :wink:

**Comment by ponyesteves** [comment] 2020-06-03 17:39
Hi @bengotow, do you have an estimated date on this release? 

thanks

**Comment by pgebheim** [comment] 2020-06-03 19:13
I'm assuming this hasn't been scheduled yet with no activity on this ticket.

**Comment by valentt** [comment] 2020-12-16 11:12
Check my bug: https://github.com/Foundry376/Mailspring/issues/2231

This is a dead project and dead product unfortunately, and we need to find an alternative. Any suggestions?

**Comment by CodeMouse92** [comment] 2021-01-18 21:48
2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/quick-unsubscribe-from-lists/84

Please consider joining that community and continuing the discussion there!

Bonus: @pgebheim @ted-gould if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-18 21:48 UTC
Labels: audit, enhancement
