### ISSUE TITLE
Bug: cannot open email.

### ISSUE THREAD

**Issue by queglay** [Foundry376/Mailspring#1824] opened 2020-02-27 20:18 UTC
**Describe the bug**
upon opening an email, it never displays the email message.  After this it will not display any messages in the inbox.

**To Reproduce**
1. open up an email.

**Expected behavior**
The email should open.

**Screenshots**
![Screenshot from 2020-02-28 06-45-01](https://user-images.githubusercontent.com/4046493/75483139-1d805d00-59f6-11ea-922c-4671faf26134.png)

**Setup: (please complete the following information):**
 - CentOS
 - CentOS 7 
 - Mailspring Version: 1.7.2

**Comment by CodeMouse92** [comment] 2021-02-23 17:47
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/invisible-empty-blank-email-message/739

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@queglay: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-23 17:47 UTC
Labels: audit, bug
