### ISSUE TITLE
Undoing a move from Gmail Inbox > Trash moves the message to All Mail, not Inbox

### ISSUE THREAD

**Issue by palefire19** [Foundry376/Mailspring#491] opened 2017-12-29 15:48 UTC
##### Are there any related issues?

...

##### What operating system are you using?
MacOS 10.13.2

##### What version of Mailspring are you using?
1.0.12

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Doubt it

##### Is the issue reproducible with a particular attachment, message, signature, etc?

I can reproduce this behavior with 100% consistency; curious if others can as well.
1. Go to your inbox
2. Select an email and delete it
3. Then hit "Undo". Expected behavior is obviously that the email would leave the trash folder and return to the Inbox. Instead it seems to return only to the All Mail folder, but not the Inbox.

Some more minor things cropping up, but still weird and potentially clues as to what's going wrong:
1. When deleting an email from the Inbox, the email now shows up in the trash, it still has the "Inbox" label <i>in the trash</i>, which seems odd.
2. When moving an email from All Mail to the Inbox, Mailspring's message for you is "Moved to All Mail, Unarchived". It should just say "Unarchived" or "Moved to Inbox"

**Comment by bengotow** [comment] 2017-12-29 17:22
Hey! Thanks for reporting this - will take a look. Minor thing #1 is actually standard Gmail behavior, but the rest of this definitely sounds incorrect.

**Comment by palefire19** [comment] 2017-12-29 18:41
Ah okay, thanks that's a helpful clarification. So it seems like the major issue then is the undoing of a delete from the inbox.

**Comment by bengotow** [comment] 2018-01-04 18:51
I've been able to reproduce this. It looks like Mailspring says "move this back from Trash to All Mail and don't change the labels", which /should/ keep the Inbox label on there, but Gmail automatically removes the inbox label (I think they do this so clients can "archive" messages by moving them from Inbox to All Mail via IMAP.)

Will see if I can fix this in an update.

**Comment by CodeMouse92** [comment] 2021-02-03 00:33
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. Learn more about the changes here.

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/disappearing-emails-desync/428

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-03 00:33 UTC
Labels: bug
