### ISSUE TITLE
[Regression] Dragging an email onto a folder no longer moves / labels it

### ISSUE THREAD

**Issue by palefire19** [Foundry376/Mailspring#586] opened 2018-01-29 08:10 UTC
##### What operating system are you using?
10.12.3

##### What version of Mailspring are you using?
1.1.1

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Doubt it

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Before 1.1.1 (or maybe 1.1.0?), you could label or move an email by dragging it onto the desired folder. This no longer works at least on Mac.

**Comment by timdorr** [comment] 2018-01-29 15:35
I can confirm this regression. I've had to switch to using the menu icon and setting a custom keyboard shortcut (⇧⌘M in my case).

**Comment by bengotow** [comment] 2018-01-29 15:56
Hey! Thanks - taking a look at this now, I'll get this fixed in the next release. (Which actually should be very soon because #590 is serious.)

**Comment by bengotow** [comment] 2018-01-29 20:20
Hey folks—the fix for this has been shipped in 1.1.2, thanks for reporting it. The app will auto-update in the next few hours, or you can download the new version directly from https://getmailspring.com/download. Enjoy!

**Closed by bengotow** 2018-01-29 20:20 UTC
Labels: done-pending-release
