### ISSUE TITLE
Problem with writing korean.

### ISSUE THREAD

**Issue by hajinhoe** [Foundry376/Mailspring#1489] opened 2019-05-07 13:13 UTC
##### Are there any related issues?

...

##### What operating system are you using?
Linux/Ubuntu 19.04
...

##### What version of Mailspring are you using?
1.6.1-aceed8e5
...

--

**Bug?**
There is a problem combining Korean letters in mail text editor.

Example)

normal : 메일스프링 메일스프링

in mailspring : 메ㄹ스프리ㅇ 메F스링

I tested it by iBus-hangul and nimf. not IM problem.

##### Is this an email sync or connection issue?
No

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?
No

...

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

...

**Comment by CodeMouse92** [comment] 2021-02-10 21:45
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/problem-with-writing-korean/560

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@hajinhoe: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-10 21:45 UTC
Labels: audit, bug, intl, linux
