### ISSUE TITLE
Sync Error

### ISSUE THREAD

**Issue by jeremyjaybaker** [Foundry376/Mailspring#1965] opened 2020-05-04 21:06 UTC
Hello, I've been having problems syncing my work email for the past 8+ months. I haven't really looked into it until recently since I'm not a frequent email user, but when I did I got very ambiguous exception details in the attached log. Anyone have any advice? The weird thing is is that I can receive email for about 10 mins at a time, then I get a sync error. Once I tell it try to again, it will work again for ~10 minutes or so then give me another sync error.

[1and1error.log](https://github.com/Foundry376/Mailspring/files/4577465/1and1error.log)

**Comment by CodeMouse92** [comment] 2021-01-28 03:22
Hi @jeremyjaybaker,

2020 prevented much development work on Mailspring, but rest assured, development has resumed! We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

Can you please confirm that this is still broken with 1.8.0, and if so, open a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 03:22 UTC
Labels: audit
