### ISSUE TITLE
Linux "Several of your accounts are having issues"

### ISSUE THREAD

**Issue by vincenzopalazzo** [Foundry376/Mailspring#1469] opened 2019-04-19 08:01 UTC
##### Are there any related issues?

...

##### What operating system are you using?

Linux mint 19

##### What version of Mailspring are you using?

1.6.1

**Bug?**

##### Is this an email sync or connection issue?

Even if I re-login to my client after a while, this error appears

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?

![Selection_003](https://user-images.githubusercontent.com/17150045/56414158-05926580-628a-11e9-9f0f-c6a810282ce8.png)
![Selection_004](https://user-images.githubusercontent.com/17150045/56418718-14801480-6298-11e9-9753-062d71ae28db.png)

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

...

**Comment by aia832003** [comment] 2019-04-24 12:31
I'm still seeing this on Fedora 29 as well.

**Comment by corck** [comment] 2019-04-25 07:29
#1407 pretty annoying bug, probably switching clients because of that.

**Comment by vincenzopalazzo** [comment] 2019-04-25 07:55
@corck Let's wait for sure they will have a solution in the next updates.

**Comment by codebudo** [comment] 2019-05-04 03:58
+1. Same issue on Ubuntu 18.10.

**Comment by swissbuechi** [comment] 2019-05-07 20:51
Same issue on 1.6.1 (Ubuntu 19.04)

**Comment by duvh93** [comment] 2019-05-07 23:10
same issue on Manjaro

**Comment by GraOrigin** [comment] 2019-05-30 10:50
same issue with Mailspring 1.6.1 on (UniX) macOS 10.14.5 ...

**Comment by EMachado88** [comment] 2019-06-26 17:36
Same inssue on 1.6.2, Ubuntu 18.04

**Comment by al2me6** [comment] 2019-06-28 11:57
Seems related to #1407. 

Affected on Kubuntu 18.10 and Manjaro Linux with Mailspring 1.6.2.

**Comment by bengotow** [comment] 2020-04-17 14:18
Hey folks, thanks for reporting this issue—sorry I've been quiet on this one. When you launch Mailspring, does it complain about being unable to securely store your passwords? On Linux this can happen if you have no keyring / libsecret package installed and it can also happen if you dismiss the "Please unlock your keychain" password prompt the system shows when you launch the app. Cheers!

**Comment by vincenzopalazzo** [comment] 2020-04-17 15:19
Hi @bengotow,

Thanks for the answer, I'm not able to reproduce this problem but I remember that this issue was caused when I use a different network from my usually mail.

**Comment by CodeMouse92** [comment] 2021-02-01 19:29
It appears that this issue has been resolved, so we are closing it. If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-01 19:29 UTC
Labels: audit, linux
