### ISSUE TITLE
Bug: Font issue. Some characters are displayed as "?"

### ISSUE THREAD

**Issue by perarg** [Foundry376/Mailspring#1959] opened 2020-05-02 11:54 UTC
**Describe the bug**
Font issue in some Greek characters. 

**To Reproduce**
There are no specific steps that can reproduce the issue. Just receiving emails from specific servers and the display is problematic.

**Expected behavior**
Just displaying correctly all text.

**Screenshots**
Here is the problematic character display in MailSpring
![font_issue-MailSpring](https://user-images.githubusercontent.com/1533511/80863151-f9a1f780-8c82-11ea-8b46-409b2ed67730.png)

Here is the same emails how they are displayed in Mail.app in macOS
![font_issue-MailApp](https://user-images.githubusercontent.com/1533511/80863409-bc3e6980-8c84-11ea-9c44-ca2058d4ace7.png)

**Setup: (please complete the following information):**
 - OS: macOS (but tested the same in Ubuntu, too)
 - OS Version: 10.13.6
 - Mailspring Version: 1.7.6

**Additional context** 
It seems that the problem is character encoding of the servers which sending the emails. I noticed that the same problematic characters that missing from these specific emails, they are present in other emails from other servers.
But in default Mail application of macOS, all the emails are displayed correctly, so something here is happening either the font support or encoding

**Comment by CodeMouse92** [comment] 2021-03-01 22:46
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/font-issue-some-characters-are-displayed-as/891

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@perarg: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-01 22:46 UTC
Labels: audit, bug
