### ISSUE TITLE
[Feature Request] Different Star flag options

### ISSUE THREAD

**Issue by danjkim21** [Foundry376/Mailspring#1754] opened 2020-01-03 14:06 UTC
Are there any related issues?
No
...

What operating system are you using?
Windows 10
...

What version of Mailspring are you using?
1.7.2
--

Bug?
Is this an email sync or connection issue?
N/A
...

 Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
N/A
...

Is the issue reproducible with a particular attachment, message, signature, etc?
N/A
...
--

**Feature Request?**
An option to choose different color star flag options. Would it be possible to include functionality similar to Gmail in which you can cycle through different color/icon options on clicking the star button? Even just different colors (i.e. red, green, blue) would be a great addition to Mailspring's functionality for me and for those who need more visual distinction for flagging mail.

Thanks! 

Does this feature exist in another mail client or tool you use?
Gmail

![Untitled](https://user-images.githubusercontent.com/29828039/71727309-d2880600-2e07-11ea-82b0-5af742a43001.png)

...

**Comment by alpelectronics** [comment] 2020-06-08 19:58
This feature would really be perfect.

**Comment by CodeMouse92** [comment] 2021-02-26 18:35
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/different-star-flag-options/832

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@danjkim21: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-26 18:35 UTC
Labels: audit, enhancement
