### ISSUE TITLE
Automatic spell check not working as expected

### ISSUE THREAD

**Issue by iuvbio** [Foundry376/Mailspring#825] opened 2018-04-11 19:26 UTC
##### Are there any related issues?
Not that I know of

##### What operating system are you using?
elementary OS 0.4.1 Loki

##### What version of Mailspring are you using?
1.2.1

##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
![mailspring_issue_1](https://user-images.githubusercontent.com/13389526/38638008-255c0d86-3dcd-11e8-89aa-2e4373fd34c1.jpeg)

##### Description
Mailspring spellcheck seems to automatically recognise the language after a few words, as it says in the settings, but it still marks some of the first words as incorrect, although they aren't. When right-clicking on a word, the same word is the first in the suggestions. The read underscoring disappears when either right- or left-clicking on the word, but reappears again after clicking somewhere else. The issue doesn't seem to depend on the language, I can confirm it for English and German.

**Comment by TheBigFatTony** [comment] 2018-04-16 06:46
Same problem here, on:
Fedora 27
Languages tested: English, German, French
Mailspring 1.2.1
No third-party plugins
Only tested on Gmail

**Comment by vgribov** [comment] 2020-04-24 08:04
Have the same issue with German.
Ubuntu 18.04.1
Mailspring 1.7.6
Gmail account

**Comment by CodeMouse92** [comment] 2021-02-16 00:36
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/automatic-spell-check-not-working-as-expected/643/2

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@iuvbio @TheBigFatTony @vgribov: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-16 00:36 UTC
Labels: audit
