### ISSUE TITLE
Sync to much in delay

### ISSUE THREAD

**Issue by caygri** [Foundry376/Mailspring#2190] opened 2020-10-31 11:45 UTC
#1876 ### What is the behavior you're seeing?
Delay receive email on pc with mailsping after hours, even if I update and update again!

##### What email provider (Gmail, Exchange, etc.) are you trying to use?
Zoho Mail Business

##### What operating system are you using?
Windows 10

##### What version of Mailspring are you using?
1.7.8

(eg: 1.6.3 or 1.7.0 - this is shown in Mailspring's main menu.)

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Happen for all message.

**Comment by CodeMouse92** [comment] 2021-02-12 21:42
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue may be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/the-eternal-sync-bug/334

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-12 21:42 UTC
Labels: audit, mailserver-incompatibility, needs-reproduction
