### ISSUE TITLE
Update 1.7.4-d54ff730  keeps re-applying

### ISSUE THREAD

**Issue by Stemnetuk** [Foundry376/Mailspring#1877] opened 2020-03-29 09:37 UTC
I have been offered update 1.7.4-d54ff730 which has been applied many time successfully. But it keeps coming up again on launch of mailspring.
This has been happening for nearly 2 months now.

**Comment by Stemnetuk** [comment] 2020-03-30 16:03
I applied this update and it has since come back as another update required. Mine did have the correct version no but has dropped back to 1.7.2.45226259

**Comment by bengotow** [comment] 2020-04-16 01:22
Hey @Stemnetuk  thanks for reporting this. I think this was caused by a problem we had with the github tag when rolling out the 1.7.4 release. Let's keep an eye on this and make sure it doesn't happen with 1.7.5 tomorrow.

**Comment by Stemnetuk** [comment] 2020-04-22 21:28
Hi, Same happening with update 1.75a9767d710.   Kind regardsR Shah   From: Ben GotowSent: Thursday, April 16, 2020 2:22 AMTo: Foundry376/MailspringCc: Stemnetuk; MentionSubject: Re: [Foundry376/Mailspring] Update 1.7.4-d54ff730 keeps re-applying (#1877) Hey @Stemnetuk thanks for reporting this. I think this was caused by a problem we had with the github tag when rolling out the 1.7.4 release. Let's keep an eye on this and make sure it doesn't happen with 1.7.5 tomorrow.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by bengotow** [comment] 2020-04-22 22:20
Hey thanks for reporting that its' still broken for you—are you running on Windows? I'll see if I can reproduce this. We just pushed up 1.7.6 but I imagine that will get stuck as well..

**Comment by CodeMouse92** [comment] 2021-02-02 23:20
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

@Stemnetuk: Can you please confirm that this is still broken with 1.8.0, and if so, open a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-02 23:20 UTC
Labels: audit, done-pending-release
