### ISSUE TITLE
Bug: Cant send any email with file included

### ISSUE THREAD

**Issue by skobanev** [Foundry376/Mailspring#2075] opened 2020-06-29 12:40 UTC
I cant send any email with file included.
Any emails without file - are sending without any problem.
Mailspring tells me that it cant connect to specified address and port/
I use internet email server and local server too.

Mailspring version 1.7.8-13635bcf

3908 [2020-06-29 14:35:19.667] [foreground] [info] - Sending draft F9A416A7-01DE-4A51-8AC1-7E5E770DB385@getmailspring.com
3908 [2020-06-29 14:35:19.667] [foreground] [info] -- Identified `sent` folder: &BB4EQgQ,BEAEMAQyBDsENQQ9BD0ESwQ1-
3908 [2020-06-29 14:35:19.680] [foreground] [info] -- Sending a single message body to all recipients:
3908 [2020-06-29 14:35:19.735] [foreground] [info] -X An SMTP error occurred: ErrorConnection LibEtPan code: MAILSMTP_NO_ERROR
3908 [2020-06-29 14:35:20.185] [foreground] [error] [local-3e00198b-43a9] -- Failed ({"debuginfo":"ErrorConnection","key":"send-failed","retryable":false,"what":"Unknown exception"}). Changing status to `complete`

**Comment by CodeMouse92** [comment] 2021-03-02 03:35
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one already on Discourse:

https://community.getmailspring.com/t/cannot-send-mail-connection-error-unable-to-connect-to-the-server-new-to-1-8-0/440

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@skobanev: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 03:35 UTC
Labels: audit, bug
