### ISSUE TITLE
Mailspring doesn't quit gracefully on Gnome logout

### ISSUE THREAD

**Issue by gitbobbed** [Foundry376/Mailspring#1946] opened 2020-04-27 19:39 UTC
**Describe the bug**
If mailspring is open and I log out of Gnome, instead of closing normally like all other apps, it crashes instead of quitting. 

**To Reproduce**
1. Have mailspring open
2. Click on menu bar -> power menu -> log out
4. Mailspring will freeze and the system will issue an error message that it can't quit the app (the famous 'Close' of 'Wait for app' message. If I don't click 'Close' soon enough, the system becomes increasingly unresponsive and the only way to get out of it is to press ctrl + alt + F1/F2 etc. (in which case gdm pops up) and restart from there (logging back doesn't solve the issue).  

**Expected behavior**
Mailbird quits and the system logs out.

**Screenshots**
https://photos.app.goo.gl/jYQKR5BMgGR3XAZ39

(sorry for the piss-poor quality of the video, I'm in a dark room and screen recorders are no use because they stop recording the moment I click on log out).

**Setup: (please complete the following information):**
 - OS: [Ubuntu]
 - OS Version [20.04]
 - Mailspring Version: ex: 1.7.6-e94bb759

More system specs:
OS: Ubuntu 20.04 LTS x86_64 
Host: X570 AORUS PRO -CF 
Kernel: 5.4.0-26-generic 
Packages: 1824 (dpkg), 5 (flatpak), 9 (snap) 
Shell: bash 5.0.16 
Resolution: 3440x1440 
DE: GNOME 
WM: Mutter 
WM Theme: Adwaita 
Theme: Ant-master [GTK2/3] 
Icons: Flat-Remix-Blue-Light [GTK2/3] 
Terminal: gnome-terminal 
CPU: AMD Ryzen 5 3600 (12) @ 3.600GHz 
GPU: AMD ATI Radeon 5700 XT 
Memory: 2837MiB / 32126MiB 

**Additional context** 
Mailspring is the only app that does this. Tested both snap and .deb versions, same problem.

**Comment by GGimenez96** [comment] 2020-08-08 02:00
Same issue here. It only happens when logging out. It doesn't happen when shutting down directly.

* OS: Ubuntu 20.4.1 LTS
* Mailspring version: 1.7.8-13635bcf (snap)

**Comment by senorLobito** [comment] 2020-08-26 23:34
> Same issue here. It only happens when logging out. It doesn't happen when shutting down directly.
> 
> * OS: Ubuntu 20.4.1 LTS
> * Mailspring version: 1.7.8-13635bcf (snap)

Havig same configuration, confirming issue.

**Comment by allanvb** [comment] 2020-12-13 23:02
Any updates here ? This issue already exists on dec. 2020

**Comment by ualich** [comment] 2021-02-14 14:34
As of feb. 2021 this issue still exists.

OS: Ubuntu 20.04
Mailspring: v1.8.0-8983dca2

**Comment by arg1998** [comment] 2021-02-15 19:34
I'm on Ubuntu 20.04 too with Mailspring version 1.8.0 having the exact same issue.

**Comment by CodeMouse92** [comment] 2021-02-15 21:26
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mailspring-doesnt-quit-gracefully-on-gnome-logout/632

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@gitbobbed @GGimenez96 @senorLobito @ualich @arg1998: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-15 21:26 UTC
Labels: audit, bug
