### ISSUE TITLE
Potential Sync Bug: Client syncs forever without progress - Debian/Linux

### ISSUE THREAD

**Issue by jackbillstrom** [Foundry376/Mailspring#1971] opened 2020-05-07 09:03 UTC
**Describe the bug**
My accounts won't sync if my internet connection drops, if I resume my laptop after e.g sharing WiFi from my phone the client always need a restart.  

**To Reproduce**
1. Initial stating client
2. Computer loses internet connection for let's say 15 minutes
3. Opening Client
4. Mailspring are syncimng

**Expected behavior**

**Screenshots**

**Setup: (please complete the following information):**
 - OS: Ubuntu 
 - OS Version 18.04
 - Mailspring Version: ex: 1.7.6-e94bb759 

**Additional context** 
Was the same on 19.04, 19.10 and 20.04

**Comment by jsf15** [comment] 2020-05-07 11:01
Same problem here on 20.04

**Comment by CodeMouse92** [comment] 2021-01-28 03:29
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/the-eternal-sync-bug/334

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 03:29 UTC
Labels: audit, bug
