### ISSUE TITLE
Bug: Images shown briefly when opening email in separate window

### ISSUE THREAD

**Issue by guillaumedavidphd** [Foundry376/Mailspring#2086] opened 2020-07-09 16:58 UTC
**Describe the bug**
I have the "Automatically load images in viewed messages" unchecked in Preferences. So when I click on an email the images are not shown. However if I double click on an email to open it in a separate window the images are downloaded and shown briefly before disappearing.

**To Reproduce**
1. Disable "Automatically load images in viewed messages".
2. Go to 'Inbox'.
3. Single click on an email that has images and see them not loading (correct behavior).
4. Double click on the same email to open it in a separate window and see the images being displayed briefly.

**Expected behavior**
The images should not be loaded and shown until the user clicks "Show Images" when the email is opened in a separate window.

**Setup: (please complete the following information):**
 - OS: Ubuntu
 - OS Version: 19.10
 - Mailspring Version: ex: 1.7.8-13635bcf

**Comment by CodeMouse92** [comment] 2021-03-02 18:47
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/images-shown-briefly-when-opening-email-in-separate-window/933

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@guillaumedavidphd: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 18:47 UTC
Labels: audit, bug
