### ISSUE TITLE
Fastmail Alias Usability Improvement

### ISSUE THREAD

**Issue by slinkymanbyday** [Foundry376/Mailspring#1356] opened 2019-02-08 02:25 UTC
I like how easy it is to add aliases in Mailspring, however the below would make aliases much more useful for the way I use them.

Fastmail allows me to receive mail to <anything>@<anything>.mydomain.com . However when I reply to an email from xxx@yyy.mydomain.com, unless I have that alias set up explicitly, the email will be sent from my default send address. It would be great if I could reply and mailspring would  set up the alias automatically depending on which email address received the email. 

I imagine this would be the same case for GMail with username+anything@gmail.com. 

EDIT: alternatively, have the from address editable when sending an email instead of forcing an alias to exist.

**Comment by bengotow** [comment] 2019-02-11 01:05
This seems like a great idea. I think it should be safe to allow you to send from the email address the email was sent to on most providers. I'll do a bit of testing and see 👍

**Comment by CodeMouse92** [comment] 2021-02-25 23:06
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/reply-to-headers/507

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-25 23:06 UTC
Labels: audit, enhancement
