### ISSUE TITLE
Bug: Select multiple mails and hit the "delete selection" button deletes only first mail

### ISSUE THREAD

**Issue by pinkerltm** [Foundry376/Mailspring#2053] opened 2020-06-12 06:36 UTC
When I select multiple mails in my inbox and then the Button "Delete selection" the mails are just unselected and nothing happens.

If I hit the `Del` Button on my keyboard the selection is deleted as it should

Mailspring 1.7.8-13635bcf 
Outlook/Exchange Account

**Comment by CodeMouse92** [comment] 2021-03-02 02:41
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

@pinkerltm: Can you please confirm that this is still broken with 1.8.0, and if so, open a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information (and your OS info!) to do it. You're welcome to include a link back to this issue for more context.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 02:41 UTC
Labels: audit, bug
