### ISSUE TITLE
Tearing issue with the snap version.

### ISSUE THREAD

**Issue by laichiaheng** [Foundry376/Mailspring#1714] opened 2019-11-18 11:18 UTC
##### Are there any related issues?
Tearing when scrolling down the page

...

##### What operating system are you using?
Manjaro Linux
...

##### What version of Mailspring are you using?
(eg: 1.6.3 or 1.7.0 - this is shown in Mailspring's main menu.)
1.7.2
--

**Bug?**

##### Is this an email sync or connection issue?
No

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?
No

...

--

**Feature Request?**
No
##### Does this feature exist in another mail client or tool you use?

...

**Comment by CodeMouse92** [comment] 2021-02-02 23:26
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

@laichiaheng (or anyone else): Can you please confirm that this is still broken with 1.8.0, and if so, open a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-02 23:26 UTC
Labels: audit, linux, snapcraft
