### ISSUE TITLE
CANNOT sync with regular email provider via IMAP and SMTP

### ISSUE THREAD

**Issue by kongxiao0532** [Foundry376/Mailspring#769] opened 2018-03-19 12:32 UTC
##### What operating system are you using?
Ubuntu 16.04.3 

##### What version of Mailspring are you using?
Mailspring 1.1.5-5834c99f

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
nope

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
nope

##### Is the issue reproducible with a particular attachment, message, signature, etc?
I cannot set up the account!

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
No

### Description

mail provider: mail.163.com
smtp server: smtp.163.com with SSL
imap server: imap.163.com with SSL

Server address and port number are set according to the guidance provided by mail.163.com/

This line of sentences were shown after setting up the account.
"Mailspring encountered errors syncing this account. Crash reports have been sent to the Mailspring team and we'll work to fix these errors in the next release. Try Reconnecting."

### Error Log
>7667 [2018-03-19 20:21:06.255] [main] [info] ------------- Starting Sync (**************@163.com) ---------------
7667 [2018-03-19 20:21:06.258] [metadata] [info] Metadata delta stream starting...
7667 [2018-03-19 20:21:06.258] [background] [info] Marking all folders as `busy`
7667 [2018-03-19 20:21:06.259] [background] [info] Syncing folder list...
7667 [2018-03-19 20:21:07.302] [background] [error] Could not create Mailspring container folder: Mailspring. ErrorNonExistantFolder
7667 [2018-03-19 20:21:07.493] [background] [error] Could not create required Mailspring folder: Mailspring/Snoozed. ErrorNonExistantFolder
7667 [2018-03-19 20:21:07.494] [background] [info] Syncing folder list...
7667 [2018-03-19 20:21:07.710] [background] [error] Could not create Mailspring container folder: Mailspring. ErrorNonExistantFolder
7667 [2018-03-19 20:21:07.720] [background] [error] Could not create required Mailspring folder: Mailspring/Snoozed. ErrorNonExistantFolder
7667 [2018-03-19 20:21:07.910] [background] [info] syncFolderUIDRange for INBOX, UIDs: 1 - 4294967296, Heavy: false
7667 [2018-03-19 20:21:07.931] [foreground] [info] Connection does not support idling. Locking until more to do...
7667 [2018-03-19 20:21:07.940] [background] [critical] 
 ***
 >*** Mailspring GenericException occurred during program execution: 
 *** {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID","key":"ErrorNonExistantFolder","retryable":false,"what":"std::exception"}
 ***

>7667 [2018-03-19 20:21:07.940] [background] [critical]  *** Stack trace (line numbers are approximate):
 *** ??:?     SyncWorker::syncFolderUIDRange(Folder&, mailcore::Range, bool, vector*)
 *** ??:?     SyncWorker::syncNow()
 *** ??:?     runBackgroundSyncWorker()
 *** (unknown)  clone
 ***

>7687 [2018-03-19 20:21:08.070] [main] [info] Identity created at 1521428184 - using ID Schema 1
7687 [2018-03-19 20:21:08.072] [main] [info] ------------- Starting Sync (kongxiao0532@163.com) ---------------
7687 [2018-03-19 20:21:08.074] [background] [info] Marking all folders as `busy`
7687 [2018-03-19 20:21:08.074] [metadata] [info] Metadata delta stream starting...
7687 [2018-03-19 20:21:08.075] [background] [info] Syncing folder list...
7687 [2018-03-19 20:21:08.573] [background] [error] Could not create Mailspring container folder: Mailspring. ErrorNonExistantFolder
7687 [2018-03-19 20:21:08.734] [background] [error] Could not create required Mailspring folder: Mailspring/Snoozed. ErrorNonExistantFolder
7687 [2018-03-19 20:21:08.736] [background] [info] Syncing folder list...
7687 [2018-03-19 20:21:08.749] [background] [error] Could not create Mailspring container folder: Mailspring. ErrorNonExistantFolder
7687 [2018-03-19 20:21:08.756] [background] [error] Could not create required Mailspring folder: Mailspring/Snoozed. ErrorNonExistantFolder
7687 [2018-03-19 20:21:08.781] [background] [info] syncFolderUIDRange for INBOX, UIDs: 1 - 4294967296, Heavy: false
7687 [2018-03-19 20:21:08.963] [background] [critical] 
 ***
 >*** Mailspring GenericException occurred during program execution: 
 *** {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID","key":"ErrorNonExistantFolder","retryable":false,"what":"std::exception"}
 ***

>7687 [2018-03-19 20:21:08.963] [background] [critical]  *** Stack trace (line numbers are approximate):
 *** ??:?     SyncWorker::syncFolderUIDRange(Folder&, mailcore::Range, bool, vector*)
 *** ??:?     SyncWorker::syncNow()
 *** ??:?     runBackgroundSyncWorker()
 *** (unknown)  clone
 ***

**Comment by bengotow** [comment] 2018-03-19 20:39
Hey! Haven't seen this one before - it looks like Mailspring is unable to create a `Mailspring` folder with a `Snoozed` subfolder in your IMAP account. Can you try creating those folders manually? If that works, we can add that to the setup process.

**Comment by kongxiao0532** [comment] 2018-03-20 07:32
Sorry but where should this folder be created? I'm kinda new to linux, thanks.

**Comment by louisgrasset** [comment] 2018-03-26 11:40
Hi there, a temporary fix is to setting up your email account without SSL, then when it's done, go to account settings and add SSL features.

**Comment by kongxiao0532** [comment] 2018-03-30 03:57
Thanks. But whenever i create a new IMAP account, it will automatically use SSL to connect. How can I change that?

**Comment by arturtr** [comment] 2018-05-04 10:36
Has the same error on connecting to Google

**Comment by arturtr** [comment] 2018-05-04 10:47
Google sent me an email about getting access to a less secure app.
Can you update security options for communicating with google it common security way?

**Comment by bengotow** [comment] 2019-02-23 07:41
Hey folks—thanks for reporting this. I believe this will be fixed in 1.5.7 by the fixes we've put in place for home.pl. Stay tuned. 👍

**Closed** 2019-03-18 18:21 UTC
Labels: done-pending-release, mailserver-incompatibility, needs-reproduction

**Comment by sighingnow** [comment] 2019-04-07 15:57
Hi @bengotow,

Do you confirm that the fix for this issue has already been included in the latest release? I still suffers this issue with mailspring 1.6.1 when sync 163 email:

```
3967 [2019-04-07 23:45:22.815] [main] [info] Identity created at 1553407604 - using ID Schema 1
3967 [2019-04-07 23:45:22.816] [main] [info] ------------- Starting Sync (xxxxxx@163.com) ---------------
3967 [2019-04-07 23:45:22.819] [background] [info] Marking all folders as `busy`
3967 [2019-04-07 23:45:22.819] [metadata] [info] Metadata delta stream starting...
3967 [2019-04-07 23:45:22.821] [background] [info] Syncing folder list...
3967 [2019-04-07 23:45:22.904] [background] [error] Could not create required Mailspring folder: Mailspring/Snoozed. ErrorNonExistantFolder
3967 [2019-04-07 23:45:22.907] [background] [info] Syncing folder list...
3967 [2019-04-07 23:45:22.913] [background] [error] Could not create required Mailspring folder: Mailspring/Snoozed. ErrorNonExistantFolder
3967 [2019-04-07 23:45:22.919] [background] [info] syncFolderUIDRange for INBOX, UIDs: 1 - 4294967296, Heavy: false
3967 [2019-04-07 23:45:22.942] [background] [critical] 
 ***
 *** Mailspring GenericException occurred during program execution: 
 *** {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID","key":"ErrorNonExistantFolder","retryable":false,"what":"std::exception"}
 ***

3967 [2019-04-07 23:45:22.942] [background] [critical]  *** Stack trace (line numbers are approximate):
 *** ??:?     SyncWorker::syncFolderUIDRange(Folder&, mailcore::Range, bool, vector*)
 *** ??:?     SyncWorker::syncNow()
 *** ??:?     runBackgroundSyncWorker()
 *** (unknown)  clone
 ***
```

**Comment by sighingnow** [comment] 2019-04-07 15:59
The problem seems to be that nested folder is not supported by 126/163 email, but mailspring are trying to create such subfolder. Is there any way that user can specify the snoozed folder in settings?

Thanks in advance!

**Comment by miuzel** [comment] 2019-05-18 10:48
> a

Encountering the same problem in email.qq.com. Nested folders are not supported. I cannot create the folder manually. This brokes not only the snoozing feature but also the whole syncing process of the account.

**Comment by staick** [comment] 2019-06-01 04:57
I cannot use the 163.com,fix it please

**Comment by gbcbooks** [comment] 2020-11-11 03:26
having the same issue here , my version is  1.7.8-13635bcf

**Comment by CodeMouse92** [comment] 2021-02-10 22:16
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/cannot-sync-126-163-mails-because-setting-up-snooze-subfolder-in-mail-folders-is-not-allowed/562

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@kongxiao0532 @sighingnow @miuzel @gbcbooks : if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team
