### ISSUE TITLE
Institutional Office365 not working

### ISSUE THREAD

**Issue by nvsitr** [Foundry376/Mailspring#2245] opened 2020-12-30 03:51 UTC
##### What is the behavior you're seeing?
Whenever I try to connect using mailspring, my institutional e-mail doesn't authenticate. So far I've tried as many options as there are online (including multiple different DavMail configs). No 2-fac auth enabled.

##### What email provider (Gmail, Exchange, etc.) are you trying to use?
MS Outlook Exchange.

##### What operating system are you using?
Ubuntu 20.04 Focal Fossa.

##### What version of Mailspring are you using?
1.7.8

##### Is the issue reproducible with a particular attachment, message, signature, etc?
LOG

----------IMAP----------
connect <mailcore::IMAPSession:0x7fffc7838df0>
* OK The Microsoft Exchange IMAP4 service is ready. [QwBIADIAUABSADEANABDAEEAMAAwADAANwAuAG4AYQBtAHAAcgBkADEANAAuAHAAcgBvAGQALgBvAHUAdABsAG8AbwBrAC4AYwBvAG0A]
ssl connect outlook.office365.com 993 2
OpenSSL version: OpenSSL 1.1.0f  25 May 2017
1 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
1 OK CAPABILITY completed.
connect ok
login
2 LOGIN "username@domain.edu" "####"
2 NO LOGIN failed.

---------------------------

**Comment by hkorsvoll** [comment] 2021-01-04 09:21
Hi, I have the same problem. I have two-factor authentication on my office365 account. But I have set up an App password for the Mailspring client.
I get the same log-transcript as @nvsitr. I also notice that I don't see any failed login attempts under recent activity on the Microsoft account page: https://mysignins.microsoft.com/
It would be really great to have proper two-factor authentication in Mail spring. I really love this mail client, but at the moment I am not able to use it for my office365 account. As soon as I get the account authenticated, I will buy the pro version of Mailspring.

**Comment by BekirZahit** [comment] 2021-01-07 07:50
Hi,
I have a similar problem. My institution doesn't allow us to use IMAP/POP, so I couldn't connect Office 365. It would be perfect if the web interface of office 365 will work for account set up in the next versions.

**Comment by humanolaranja** [comment] 2021-01-14 11:13
Same problem here

**Comment by hkorsvoll** [comment] 2021-01-14 12:46
Created bug report on [https://community.getmailspring.com/t/institutional-office365-not-working/48](https://community.getmailspring.com/t/institutional-office365-not-working/48)

**Comment by CodeMouse92** [comment] 2021-01-17 03:41
Thanks for helping us with the migration, @hkorsvoll!

For everyone else: we are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please check out the conversation on Discourse. The link is provided in the comments above ^^^.

**Closed by CodeMouse92** 2021-01-17 03:41 UTC
Labels: audit, mailserver-incompatibility, needs-reproduction
