### ISSUE TITLE
[Feature Request] Use both labels and folders

### ISSUE THREAD

**Issue by d33pcode** [Foundry376/Mailspring#1320] opened 2019-01-11 15:44 UTC
It would be nice to have the option to create _both_ labels and folders, for providers that support this feature.

**OS:** Fedora 28

**Mailspring version:** 1.5.5-b7939d38

**Comment by CodeMouse92** [comment] 2021-02-10 21:22
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/support-for-imap-flags-aka-labels/540

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-10 21:22 UTC
Labels: audit
