### ISSUE TITLE
[Feature] Allow moving individual emails

### ISSUE THREAD

**Issue by jpbaril** [Foundry376/Mailspring#730] opened 2018-02-26 22:02 UTC
##### Are there any related issues?

Did not find any.

##### What operating system are you using?
Ubuntu Linux 17.10

##### What version of Mailspring are you using?
1.1.4

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Yes and no. IMAP use folders whereas Gmail logic is labels.

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Yes

----------------------

I often want to move to a specific folder one individual email from a thread. For that, in other mail clients, I select that one particular email from the thread and click on the move button.

In Mailspring, the "Move to folder" button (and "Apply labels" for Gmail accounts) moves/applies-labels-to the whole thread. UI tweaks should be done to let users move/apply-label-to one individual email. 

I also created another related issue that is specific for Gmail accounts: https://github.com/Foundry376/Mailspring/issues/729

**Comment by CodeMouse92** [comment] 2021-02-05 01:11
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/move-or-delete-a-single-message-in-a-thread/320

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@jpbaril: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-05 01:11 UTC
Labels: audit, enhancement, product-direction
