### ISSUE TITLE
[Feature Request] Mail storage settings (download number of days, all mail, etc.)

### ISSUE THREAD

**Issue by HaoZeke** [Foundry376/Mailspring#473] opened 2017-12-23 20:19 UTC
##### Are there any related issues?
Nope

##### What operating system are you using?
Archlinux

##### What version of Mailspring are you using?
1.0.11-ea4b20af

**Bug?**
Not really

##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Nope

#### Details

I can't seem to figure out where the settings are for downloading all mail.
Also how is the storage calculated? Shouldn't there be a download last 100days of mail or all mail or something somewhere?

**Comment by bengotow** [comment] 2017-12-28 16:50
Hey! Right now, Mailspring fetches the headers for all your mail and the message bodies and attachments for the last three months of mail (except for Spam and Trash). This will definitely be configurable in the future. Just to help plan the configuration options, are you looking to store more of your mail or less?

**Comment by HaoZeke** [comment] 2017-12-29 15:47
I generally go for more, atleast on my desktop PC where I run thunderbird, I grab every mail available..

**Comment by sgsinclair** [comment] 2018-03-03 19:43
+1 I'd love to be able to configure storage and know that I have a full archive of messages for when I'm offline and also that searches are including all message bodies (in addition to all headers, which I believe is already the case).

**Comment by jotaf98** [comment] 2018-06-27 18:58
Second the "Store all e-mail" feature. The fact is that, for some e-mail servers (e.g. work), you cannot depend on having access to it forever (e.g. you change jobs).

Backing up all e-mails in a simple, transferable format locally would be ideal, otherwise you risk loss of data in the future.

**Comment by hyviquel** [comment] 2018-08-23 09:29
+1 for storing all emails, I often use my laptop without internet access and there is a lot of information/documents stored in my mailbox.

**Comment by L0drik** [comment] 2019-02-20 14:43
+ 1, would love to have this feature as well

**Comment by jibasig** [comment] 2019-03-25 10:48
+1 for this feature

**Comment by lonewolf1870** [comment] 2019-04-27 23:16
+1
is it still the case that only the last 3 months are fully stored locally?
is it documented somewhere?

**Comment by qrooel** [comment] 2019-05-29 11:37
+1

**Comment by Danish22** [comment] 2019-08-29 14:21
+1

**Comment by rubidiumRydberg** [comment] 2020-05-31 16:22
+1

**Comment by 00Asgaroth00** [comment] 2020-08-07 09:17
+1

**Comment by nirvaat** [comment] 2020-09-11 07:55
This is very much needed. Actually this is the only reason which prevents me from using Mailspring as me default email cleint.

**Comment by lewis206** [comment] 2020-09-29 16:26
+1 That would be amazing. Why is it not coming yet?

**Comment by bjohnny-user** [comment] 2021-01-22 01:02
+1 now i use thunderbird, mailspring and outlook to. This function is so important!!

**Comment by CodeMouse92** [comment] 2021-01-22 02:03
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mail-storage-settings-download-number-of-days-all-mail-etc/170

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-22 02:03 UTC
Labels: audit, enhancement
