### ISSUE TITLE
Mails doesn't move to trash when viewing a filter / search query

### ISSUE THREAD

**Issue by gmagic** [Foundry376/Mailspring#594] opened 2018-01-30 10:59 UTC
##### Are there any related issues?

Didn't find/

##### What operating system are you using?
Fedora 27

##### What version of Mailspring are you using?
1.1.2

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
I don't have any third-party plugins installed.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I don't know, cuz have 3 different mail providers.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
When i have mails filtered in "All mails" or "Inbox" of any account and try to delete mail from list by pressing "Delete" button Mailspring shows me "Moved to All mails". If i click "Trash" icon, it says "Moved to trash" but nothing really happens. The same from context menu "Trash".

**Comment by sathiz1993** [comment] 2018-02-07 05:30
+1

**Comment by WanderingRaven** [comment] 2018-03-25 13:15
+1
Operating System: Windows 8.1
Mailspring Version: 1.1.5-5834c99f

**Comment by CodeMouse92** [comment] 2021-02-18 23:37
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/deleting-a-message-while-viewing-a-search-query-does-not-remove-it-from-view/576

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-18 23:37 UTC
Labels: audit, bug
