### ISSUE TITLE
iCloud (CardDAV) contacts not syncing

### ISSUE THREAD

**Issue by ersan** [Foundry376/Mailspring#1760] opened 2020-01-06 17:18 UTC
I have an iCloud account added and Mailspring doesn't seem to be able to see its contacts, running 1.7.2 - are there extra steps I'm missing somewhere?  It works for Google accounts.

https://i.imgur.com/N3qeouK.png

**Comment by CodeMouse92** [comment] 2021-02-12 20:58
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/icloud-carddav-contacts-not-syncing/591

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@ersan: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-12 20:58 UTC
Labels: audit, contacts
