### ISSUE TITLE
[Feature Request] Show avatar/profile icon on inbox

### ISSUE THREAD

**Issue by Laikar** [Foundry376/Mailspring#1715] opened 2019-11-19 17:06 UTC
##### Are there any related issues?
#213 exists, but its 2 years old and didn't seem like it got much attention

##### What operating system are you using?

Windows 10 1909

##### What version of Mailspring are you using?
1.7.2-4522b259

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

Yes, [bluemail](https://bluemail.me/) 
Take a look a [this](https://bluemail.me/img/desktop/BlueMail-Windows-PC-Desktop.png) for an example

**Comment by CodeMouse92** [comment] 2021-02-08 19:09
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We've migrated the linked issue to Discourse:

https://community.getmailspring.com/t/avatar-profile-icon-on-inbox/494

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-08 19:09 UTC
Labels: audit
