### ISSUE TITLE
Screenshot Mode Doesn't Hide Email Contents

### ISSUE THREAD

**Issue by Modelmat** [Foundry376/Mailspring#1044] opened 2018-08-26 10:19 UTC
##### Are there any related issues?
Nope

...

##### What operating system are you using?
Linux, Manjaro
...

##### What version of Mailspring are you using?
1.4.2-https://github.com/Foundry376/Mailspring/commit/f587b7b728830dae59e9faa7e39a769890fd8e63
...

--

**Bug?**

##### Is this an email sync or connection issue?
No

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Doesn't matter

...
--

When pressing toggle screenshot mode, it does not hide the email contents.

![image](https://user-images.githubusercontent.com/25718989/44627203-0a0db500-a96d-11e8-8714-7b6e97868910.png)

**Comment by bengotow** [comment] 2018-09-17 19:09
Who would want to hide such a wonderful email! Just kidding :-) This is definitely a bug. I'll see if this would be an easy fix, I think we may just need to inject the font into the iframes as well as into the theme.

**Comment by CodeMouse92** [comment] 2021-01-28 03:44
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/screenshot-mode-doesnt-hide-email-contents/336

Please consider joining that community and continuing the discussion there!

@Modelmat: if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 03:44 UTC
Labels: audit, bug
