### ISSUE TITLE
office 365 mail not syncing

### ISSUE THREAD

**Issue by 512DuncanL** [Foundry376/Mailspring#2117] opened 2020-08-09 03:33 UTC
##### What is the behavior you're seeing?

mail is not showing up

##### What email provider (Gmail, Exchange, etc.) are you trying to use?

office 365 mail

##### What operating system are you using?

macOS Mojave 10.14.5

##### What version of Mailspring are you using?

1.7.8

**Comment by CodeMouse92** [comment] 2021-02-12 22:16
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/institutional-office365-not-working/48

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-12 22:16 UTC
Labels: audit, bug, mailserver-incompatibility, needs-reproduction
