### ISSUE TITLE
Unable to install on Ubuntu 16.04: Package libsecret-1-dev is not installed

### ISSUE THREAD

**Issue by thinkwalnut** [Foundry376/Mailspring#293] opened 2017-11-02 08:32 UTC
Total newbie to Linux here,

So i just downloaded mailspring-1.0.7-amd64.deb

and i tried to install via Software install but nothing happens,

So i tried to install via terminal `**sudo dpkg -i mailspring-1.0.7-amd64.deb**`

It gave following error:

```
Selecting previously unselected package mailspring.
(Reading database ... 329215 files and directories currently installed.)
Preparing to unpack mailspring-1.0.7-amd64.deb ...
Unpacking mailspring (1.0.7) ...
dpkg: dependency problems prevent configuration of mailspring:
 mailspring depends on libsecret-1-dev; however:
  Package libsecret-1-dev is not installed.

dpkg: error processing package mailspring (--install):
 dependency problems - leaving unconfigured
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5.1) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160824-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mime-support (3.59ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Errors were encountered while processing:
 mailspring

```
I also did `**sudo apt-get install -f**`
It gave following output:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following packages will be REMOVED:
  mailspring
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 280 MB disk space will be freed.
Do you want to continue? [Y/n] Y
(Reading database ... 329463 files and directories currently installed.)
Removing mailspring (1.0.7) ...
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu5.1) ...
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20160824-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for mime-support (3.59ubuntu1) ...
And I am still unable to install it please help
```

**Comment by lamarios** [comment] 2017-11-02 09:18
Can you give it a try with gdebi ? It's a tool that will find and install the required dependencies for a .deb package.

```
sudo apt install gdebi
sudo gdebi mailspring-1.0.7-amd64.deb
```

**Comment by thinkwalnut** [comment] 2017-11-02 09:20
```
sudo gdebi mailspring-1.0.7-amd64.deb
Reading package lists... Done
Building dependency tree        
Reading state information... Done
Reading state information... Done
This package is uninstallable
Cannot install 'libsecret-1-dev'

```

**Comment by lamarios** [comment] 2017-11-02 09:21
Which desktop environment are you using ?

**Comment by thinkwalnut** [comment] 2017-11-02 09:36
I am Ubuntu 16.04 LTS so i guess Unity by default.. i am total newbie to all this..

**sudo apt-get install libsecret-1-dev**

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libsecret-1-dev : Depends: libglib2.0-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```

**Comment by knireis** [comment] 2017-11-02 10:31
i use linux mint (cinnamon desktop) which is based on ubuntu 16.04 and mailspring installed without issues

**Comment by oserban** [comment] 2017-11-04 17:00
@bengotow this is a bit weird because the deb package has a dev dependency

**Comment by oserban** [comment] 2017-11-04 17:04
@thinkwalnut you should be able to install libsecret-1-dev manually and try again to install the mailspring package.

```bash
sudo apt install libsecret-1-dev
```

then **dpkg -i mailspring.deb** should be enough

**Comment by bengotow** [comment] 2017-11-04 19:48
Hey folks! Yeah... it's definitely strange is requires libsecret-1-dev. I think we originally tried specifying the dependency as `libsecret-1-0`, but folks reported it wasn't working. I didn't realize that `dpkg` wouldn't automatically resolve and install the dependency though...

**Comment by bengotow** [comment] 2017-11-07 00:40
(Related https://github.com/Foundry376/Mailspring/issues/216) - if anyone with more linux background knows which of these two is correct, I'd appreciate it! The part of Mailspring that needs this is the https://github.com/atom/node-keytar module.

**Comment by oserban** [comment] 2017-11-08 07:40
It's a keytar issue, see: https://github.com/atom/node-keytar#on-linux
Other people are reporting the same problem in Nylas: https://github.com/atom/node-keytar/issues/73

**Comment by oserban** [comment] 2017-11-08 07:48
Regarding the automatic dependency resolution, dpkg does not do this on Ubuntu/Debian. It's a known fact. So much so, that [everybody](https://unix.stackexchange.com/a/159114) does a:
```bash
sudo apt-get install -f
```
after a dpkg install. 

A least known method to install on Ubuntu/Debian is with apt (not apt-get):

```bash
sudo apt install ./package.deb
```

This will automatically try to resolve dependencies. 

**Note:** The apt install method requires either a relative path or full path. It does not work with the package name (in current folder). If you do provide the name of the deb without the path, it will try to install the package from the remote repositories instead of the deb file.

@bengotow Can you please add this to the Ubuntu/Debian install tutorials. I can write a cleaner version if needed. Also, most Linux projects provide an install guide on the download page if the install requires more than double click on the downloaded file.

**Comment by bengotow** [comment] 2017-11-09 17:29
Hey! Ahh that’s great info - it looks like the Snap package will be
shipping next Tuesday and I believe this won’t be a problem once we’re usig
that install method, but I’ll double check and see.

**Comment by curtisgibby** [comment] 2017-12-19 05:40
I'm still seeing this when trying to install the latest 1.0.11 .deb file on Linux Mint 18.3. Is there any workaround?

```
sudo apt install ./mailspring-1.0.11-amd64.deb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'mailspring' instead of './mailspring-1.0.11-amd64.deb'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
mailspring : Depends: libsecret-1-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by oserban** [comment] 2017-12-19 06:06
sudo apt-get install -f
After you installed the package with dpkg. This will install all dependencies of a previously failed package.

See above for more details

**Comment by curtisgibby** [comment] 2017-12-19 20:03
the `install -f` doesn't seem to do anything different -- it asks if I want to *remove* mailspring, not fix the dependency problems.

```
$ sudo dpkg -i ./mailspring-1.0.11-amd64.deb 
Selecting previously unselected package mailspring.
(Reading database ... 243024 files and directories currently installed.)
Preparing to unpack ./mailspring-1.0.11-amd64.deb ...
Unpacking mailspring (1.0.11) ...
dpkg: dependency problems prevent configuration of mailspring:
 mailspring depends on libsecret-1-dev; however:
  Package libsecret-1-dev is not installed.

dpkg: error processing package mailspring (--install):
 dependency problems - leaving unconfigured
Processing triggers for hicolor-icon-theme (0.15-0ubuntu1) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for desktop-file-utils (0.22+linuxmint1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Errors were encountered while processing:
 mailspring

$ sudo apt-get install -f
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following packages will be REMOVED:
  mailspring
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 280 MB disk space will be freed.
Do you want to continue? [Y/n] n
Abort.
```

**Comment by oserban** [comment] 2017-12-19 20:09
That is incredibly weird, as my suggestion is pretty much standard practice in Ubuntu.

Anyway, you can install the package manually. It should fix the problem:

```bash
sudo apt install libsecret-1-dev
```

**Comment by curtisgibby** [comment] 2017-12-19 21:34
```
$ sudo apt install libsecret-1-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 libsecret-1-dev : Depends: libglib2.0-dev but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
```

Then when I run the suggested `apt-get -f install`, it gives me the same error as above. :disappointed:

**Comment by oserban** [comment] 2017-12-20 12:59
In that case, I think that library is not packed properly into your Linux Mint distribution.

Everything I posted here works well on Ubuntu, so you may need to ask this question to the Mint community.

**Comment by curtisgibby** [comment] 2017-12-21 18:31
I just reinstalled my OS (due to unrelated issues), and I'm now able to get mailspring to install without any issues. Thanks for the troubleshooting help.

**Comment by dhruvdutt** [comment] 2018-03-26 18:03
```
sudo apt install libsecret-1-dev
```
Fixed it. I'm on Ubuntu 16.04 KDE

**Comment by victorbasset** [comment] 2019-04-19 09:14
```zsh
sudo apt install libpcre3=2:8.39-12
sudo gdebi mailspring-1.6.1-amd64.deb
```
Works for me :)

**Comment by mohsenSy** [comment] 2020-05-01 05:38
Hi, I have the same issue on Ubuntu 20.04, mailspring is installed and words correctly however every time I want to update my packages it complains that mailspring package is not configured properly
```
The following packages have unmet dependencies:
 mailspring : Depends: libsecret-1-dev but it is not installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
```

If I try with `apt --fix-broken install` it just removes mailspring.

And if I try to install `libsecret-1-dev` manually I get this error

```
The following packages have unmet dependencies:
 libsecret-1-dev : Depends: libglib2.0-dev (>= 2.44.0) but it is not going to be installed
```

Does anyone has a solution for this?

**Comment by dptole** [comment] 2020-12-11 00:09
So... **I'm not trying to install Mailspring** but protonmail-bridge on my ubuntu 16.04 and the same error occurs

```
dan@dan:~/lab/proton-bridge$ sudo apt install libsecret-1-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libsecret-1-dev : Depends: libglib2.0-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

If I try to install the dependencies manually (which I think shouldn't be necessary) no progress is made, of course.

```
dan@dan:~/lab/proton-bridge$ sudo apt install libsecret-1-dev libglib2.0-dev zlib1g zlib1g-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
zlib1g is already the newest version (1:1.2.8.dfsg-2ubuntu4.1).
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libglib2.0-dev : Depends: libglib2.0-0 (= 2.48.0-1ubuntu4) but 2.48.2-0ubuntu4.3 is to be installed
                  Depends: libglib2.0-bin (= 2.48.0-1ubuntu4)
 zlib1g-dev : Depends: zlib1g (= 1:1.2.8.dfsg-2ubuntu4) but 1:1.2.8.dfsg-2ubuntu4.1 is to be installed
E: Unable to correct problems, you have held broken packages.
```

I can rarely solve these kinds of problems and I don't want to spend god knows how many days upgrading stuff that is working fine so that they will stop working, as it always happens.

**Comment by CodeMouse92** [comment] 2021-01-28 18:20
It appears that this issue has been resolved — there are a number of users who have been able to install Mailspring 1.8.0 on Ubuntu 20.04 (latest LTS) — so we are closing it. If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 18:20 UTC
Labels: audit, linux, snapcraft
