### ISSUE TITLE
Request: "Send Now" Button on the "Sending Soon" Alert

### ISSUE THREAD

**Issue by johnyradio** [Foundry376/Mailspring#1379] opened 2019-02-20 21:47 UTC
When the delay is enabled, you get a "Sending Soon" popup. 
It has an "Undo" button. 
Please add a "Send Now" button. 

thx!

**Comment by ilovecats516** [comment] 2019-02-23 17:17
Yes, I would like that too!

**Comment by bengotow** [comment] 2019-03-16 20:40
Ahh this is a great idea 👍  I'll see if we can get this in to a future release.

**Comment by johnyradio** [comment] 2019-03-16 20:44
Alternately, add a "send now" option to the send button (which currently
has send, and send+archive).

**Comment by djfredalert** [comment] 2019-11-22 00:12
+1 for the feature

Not necessarily advocating this particular approach, but worth considering Gmail's: there's a little X within the pop-up; by clicking it and dismissing it, the email is sent.

**Comment by CodeMouse92** [comment] 2021-02-25 23:28
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/send-now-button-on-the-sending-soon-alert/802

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@johnyradio @leggomyinfo: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-25 23:28 UTC
Labels: audit, enhancement, product-direction
