### ISSUE TITLE
Ctrl+A "select all" in composer not working

### ISSUE THREAD

**Issue by benkuper** [Foundry376/Mailspring#823] opened 2018-04-10 20:44 UTC
##### What operating system are you using?
Windows 10 x64

##### What version of Mailspring are you using?
1.2.1

##### Description

When composing a mail, doing Ctrl+A should select all (like standard text editor) but it just put the cursor back to the top.
It looks like a confusion between Command+A and Ctrl+A : Ctrl+A shortcut on Mac has this behavior of placing the cursor to the top, but the Ctrl+A in windows and linux should actually be the same as Mac's Command+A and not Ctrl+A

I suspect this issue : https://github.com/Foundry376/Mailspring/issues/682 is related as well

**Comment by eliocamp** [comment] 2018-05-09 17:57
Can confirm this issue on elementary OS loki (based on Ubuntu 16.04)

**Comment by CodeMouse92** [comment] 2021-02-11 23:42
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/improve-select-all-behavior/172

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-11 23:42 UTC
Labels: audit
