### ISSUE TITLE
Syncing IMAP accounts continuously use the CPU

### ISSUE THREAD

**Issue by Plaristote** [Foundry376/Mailspring#435] opened 2017-12-13 15:02 UTC
##### Are there any related issues?
No.

##### What operating system are you using?
Archlinux (built from AUR)

##### What version of Mailspring are you using?
1.0.10-d250-d253

--
##### Do you have any third-party plugins installed? If so, which ones?
None.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
IMAP, using a Gandi mail account.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Is this question relevant, considering it seems to be a syncing issue ? Should I be looking for something specific ?

--
##### What's happening ?
The `main` process that seems related with syncing one of my IMAP accounts eats up a lot of CPU.
The command that launched that process is:
`/usr/share/mailspring/resources/app.asar.unpacked/mailsync.bin --mode sync`.
Nothing in the logs but the periodic "Manual update check". I'm currently "solving" the issue by sending SIGSTOP to the process, and unstop it to manually check my mails. The process does respond to SIGINT properly.

And the syncing does work : I sent myself an email to confirm it. It just eats an entire CPU for a couple of seconds on very short intervals.

**Comment by bengotow** [comment] 2017-12-14 19:26
Hmm—this is interesting. Do you have more than one account linked to Mailspring? If so, is it just one of the mailsync processes that is using a lot of CPU, or both? I think this is probably an issue specific to the content of your mailbox, but it's hard to say. For clients that don't support CONDSTORE and QRESYNC, we poll the "top" of the mailbox every two minutes to look for changes, but it typically only takes a second or so and CPU usage shouldn't be that extreme.

Are you seeing CPU use more frequently than every two minutes, or just a large period of high CPU every two minutes? On macOS I'd ask for an Instruments profile of the process to dig in to this a bit further, not sure if there's something equivalent on Linux.

**Comment by Plaristote** [comment] 2017-12-15 16:29
I do have several accounts, and this only apply to one of them. The good news is, the mailbox that causes issues is relatively empty, so it shouldn't be too hard to find what causes the problem, if it comes from the mailbox content.

What I see is short periods of high CPU usage (between 2 and 6 seconds), all separated by an interval of a couple of seconds. Comparatively, the same process, for the mailbox that works nicely, has a very similar period of high CPU usage, but separated by an interval of a minute.

As for the profiling, I think Callgrind might be what we're looking for. I see that I should be able to launch the mailsync process with Callgrind, once I've found out what arguments need to be passed to have it watch the proper mailbox. 

This is what I've tried:
```
export LD_LIBRARY_PATH=/usr/share/mailspring/resources/app.asar.unpacked
export CONFIG_DIR=$HOME/.config/Mailspring
export IDENTITY_SERVER=https://id.getmailspring.com

/usr/share/mailspring/resources/app.asar.unpacked/mailsync.bin \
  --identity IDENTITY_ID \
  --mode sync \
  --account ACCOUNT_ID \
  --orphan --verbose
```
I found IDENTITY_ID and ACCOUNT_ID in $CONFIG_DIR/config.json. I assumed I had to pick the id field for the only identity that was there, and for the account corresponding to the faulty mailbox.
However, running this command just prints the usage help and exits.

**Comment by OptogeneticsandNeuralEngineeringCore** [comment] 2018-01-02 21:43
I just installed Mailspring (new user) on Linux Mint (18.3) and set up syncing to office365. It drove all 4 of my processors to 100% (continuous). I let it do that for 10 min (maybe it needed to figure itself out, hey...?) and then quit Mailspring, and they dropped to their normal well below 10%. Seems like a similar experience to OP? Don't know what other info to post.

**Comment by tuomastik** [comment] 2018-01-04 15:18
I just encountered the same issue with Ubuntu 17.10, Mailspring 1.0.12-cf081332 and 4 mailboxes. Ended up killing the process.

**Comment by saildata** [comment] 2018-01-05 23:17
**Actual:** I'm also seeing this issue, where after selecting `Quit` from the mail program exits the program, but leaves two processes running: ```mailsync.bin``` from ```/usr/share/mailspring/resources/app.asar.unpacked/mailsync.bin``` The only known workaround is to kill the process(s) as mentioned above. That seems like a hack that users should not have to use.

**Expected** The program fully exits when I select `Quit`. It's not a matter of system resources (in my case), rather it's a matter of respecting what was requested by the user.

**Comment by dmeijboom** [comment] 2018-01-24 08:53
I have two imap accounts linked but even with one the CPU usage is very high, all the time. I'm running Archlinux and installed mailspring from the AUR. It's completely unusable since it slows down my entire system. Too bad because mailspring looks very promising.

**Comment by pat-s** [comment] 2018-01-24 22:25
Kubuntu 16.04, Mailspring 1.1.0

When running, my CPU runs at 50% (4 Cores, i5-8th). 
After quitting mailspring, my CPU usage is around 10-15%.

Similar behavior also in  =< 1.0.12 

The "syncing mailbox" info button is always there. Maybe its stuck at syncing? Happy to provide some logs.

**Comment by cdanielian** [comment] 2018-02-27 20:27
Similar problem for me.  Elementary OS Loki. Mailspring 1.1.4

One of the processors runs at 100% most of the time.  In general the CPU usage is quite large when Mailspring is open or running in background, all driven by same file: /usr/share/mailspring/resources/app.asar.unpacked/mailsync.bin

Memory usage is not out of the ordinary. 

The high CPU causes battery drain very quickly, and eventually the computer becomes unresponsive after about 10mins.  Unresponsive only happens if Mailspring application is physically open, high CPU and battery drain happen when the actual application is closed but it is running in background (ie, the icon is in the alert bar at the top of screen).   If I quit Mailspring altogether then the CPU usage goes back to normal.

Happy to send through any log files if that would help (though need direction as to where to get them!).

**Comment by timjefferies** [comment] 2018-03-01 09:20
I'm having this issue - it's killing my battery. Also on arch here.

Here is a bash script I made to kill mailspring after 5 minutes. It's the only way I can make the app usable at this point.

`# Spawn a child process:
(mailspring) & pid=$!
# in the background, sleep for 10 secs then kill that process
(sleep 300 && kill -9 $pid) &
`

**Comment by sikand** [comment] 2018-05-15 21:39
I'm having the same issue on OpenSuse 42.3

**Comment by oliverbienert** [comment] 2018-07-29 20:19
Having the same issue, Ubuntu 18.04, 4 accounts, high cpu usage on a GMX account.

**Comment by sviatco** [comment] 2018-08-13 04:56
Having the same issue here on Arch with two different systems. While on desktop it's largely unnoticeable being overcompensated through hardware, on a laptop (xps 9370) as soon as I launch Mailspring the fans immediately kick in and the CPU reached 70C and then gets cooled down to 65C, while the normal operating temperatures are around 45C. The load remains sustained until I quit the process.

**Comment by pat-s** [comment] 2018-08-13 06:51
Having exact the same problem running arch on my laptop.

**Comment by kode54** [comment] 2018-10-10 04:41
I’m having the same issue on Kubuntu 18.04.1 with Mailspring 1.4.2, and five accounts: two GMail (one of them G Suite), one iCloud, one Yahoo, and a generic IMAP account. It’s been pegging a core of my 3770 (4c8t), causing a load average of 0.97 while it’s at the lock screen and I’m on my tablet.

**Comment by nfaivre** [comment] 2018-10-15 07:36
Same same on Ubuntu 18.04 and Mailspring 1.4.2, one gmail and two generic Imap.

**Comment by lillemets** [comment] 2018-10-23 08:10
Mailspring 1.4.2 is also unusable on my Arch Linux system due to high CPU use. I'm using one Gmail and one IMAP account.

**Comment by estiens** [comment] 2018-10-24 02:58
Same here with Ubuntu 18.04 and Mailspring 1.5.0 -- added one gmail account and mailsync.bin processes are keeping CPU pegged at 75-100% and fans on full blast. I'll leave overnight to see if it is just initial sync...

**Comment by renanss** [comment] 2018-10-25 19:31
same here on Ubuntu 16.04. Mailspring 1.5.0
![image](https://user-images.githubusercontent.com/13458004/47525327-585b0980-d873-11e8-9dfd-a998f403fbf4.png)

**Comment by asifamod** [comment] 2018-11-05 18:06
Hi there

I'm having the same issue on Ubuntu, any fixes for this?

**Comment by estiens** [comment] 2018-11-05 22:02
FYI, my issue resolved itself on Ubuntu after about 1 week of syncing. Now mailspring uses appropriate CPU when open, but it definitely pegged a CPU at 100%+ while syncing a large mailbox initially.

**Comment by renanss** [comment] 2018-11-06 12:53
The problem solved itself.

**Comment by Bergg** [comment] 2018-11-12 09:22
Not solved here (Fedora29) with 1.5.2 main is still using a very high level of cpu.

**Comment by frigaut** [comment] 2018-11-17 05:58
Same here. main using 100% on one core. I have large mailboxes, so will let it go syncing for some days. Hopefully eventually it will quiet down.

**Comment by frigaut** [comment] 2018-11-18 10:09
Seems to be solved. It appears I had several local config. One in .config/Mailspring, another under .config/Mailspring-dev, and even another under the old Nylas-N1 (also under .config). I don't know if or why other configs interacted, but deleting the config directories and restarting from scratch seems to have solved the CPU issue. So far so good.

**Comment by Bergg** [comment] 2018-11-18 16:38
thanks @frigaut that solved it for me too. My .config had similar objects and I got rid of them - that did the trick.

**Comment by wonx** [comment] 2019-01-11 15:57
Same (or similar) issue here. One of the 4 cores is always at 100%, even when Mailspring is minimized at the tray, which is draining the battery...

**Comment by cpacchierotti** [comment] 2019-02-07 17:31
I am experiencing a similar issue. When it happens (~20 times per day), Mailspring is stuck in "Syncing your mailbox''. If I close it and reopen it, it stops.

```
4331 [2019-02-07 18:25:29.786] [background] [info] Sync loop complete.
4331 [2019-02-07 18:27:29.787] [background] [info] Syncing folder list...
4331 [2019-02-07 18:27:29.834] [background] [info] syncFolderChangesViaCondstore - INBOX: modseq 66702 to 66702, uidnext 46517 to 46517
4331 [2019-02-07 18:27:30.161] [background] [info] syncFolderChangesViaCondstore - Sent: modseq 66704 to 66704, uidnext 46519 to 46519
4331 [2019-02-07 18:27:30.430] [background] [info] syncFolderChangesViaCondstore - Drafts: modseq 65342 to 65342, uidnext 10277 to 10277
4331 [2019-02-07 18:27:30.710] [background] [info] syncFolderChangesViaCondstore - Archive: modseq 66704 to 66704, uidnext 46518 to 46518
4331 [2019-02-07 18:27:30.987] [background] [info] syncFolderChangesViaCondstore - Trash: modseq 66691 to 66691, uidnext 46516 to 46516
4331 [2019-02-07 18:27:30.996] [background] [info] syncFolderChangesViaCondstore - Junk: modseq 66288 to 66288, uidnext 46314 to 46314
4331 [2019-02-07 18:27:31.005] [background] [info] syncFolderChangesViaCondstore - Mailspring: modseq 52160 to 52160, uidnext 30554 to 30554
4331 [2019-02-07 18:27:31.281] [background] [info] syncFolderChangesViaCondstore - Mailspring/Snoozed: modseq 52163 to 52163, uidnext 30556 to 30556
4331 [2019-02-07 18:27:31.551] [background] [info] Sync loop deleting unlinked messages with phase 1.
4331 [2019-02-07 18:27:31.552] [background] [info] Sync loop complete.
4331 [2019-02-07 18:29:31.552] [background] [info] Syncing folder list...
4331 [2019-02-07 18:29:31.604] [background] [info] syncFolderChangesViaCondstore - INBOX: modseq 66702 to 66702, uidnext 46517 to 46517
4331 [2019-02-07 18:29:31.837] [background] [info] syncFolderChangesViaCondstore - Sent: modseq 66704 to 66704, uidnext 46519 to 46519
4331 [2019-02-07 18:29:32.039] [background] [info] syncFolderChangesViaCondstore - Drafts: modseq 65342 to 65342, uidnext 10277 to 10277
4331 [2019-02-07 18:29:32.248] [background] [info] syncFolderChangesViaCondstore - Archive: modseq 66704 to 66704, uidnext 46518 to 46518
4331 [2019-02-07 18:29:32.447] [background] [info] syncFolderChangesViaCondstore - Trash: modseq 66691 to 66691, uidnext 46516 to 46516
4331 [2019-02-07 18:29:32.456] [background] [info] syncFolderChangesViaCondstore - Junk: modseq 66288 to 66288, uidnext 46314 to 46314
4331 [2019-02-07 18:29:32.465] [background] [info] syncFolderChangesViaCondstore - Mailspring: modseq 52160 to 52160, uidnext 30554 to 30554
4331 [2019-02-07 18:29:32.658] [background] [info] syncFolderChangesViaCondstore - Mailspring/Snoozed: modseq 52163 to 52163, uidnext 30556 to 30556
4331 [2019-02-07 18:29:32.843] [background] [info] Sync loop deleting unlinked messages with phase 2.
4331 [2019-02-07 18:29:32.844] [background] [info] Sync loop complete.
```

**Comment by cpacchierotti** [comment] 2019-02-11 17:09
I am able to reproduce this problem easily. Mailspring goes on and on with the following

```
26350 [2019-02-11 18:04:20.390] [background] [info] Syncing folder list...
26350 [2019-02-11 18:04:20.412] [background] [info] syncFolderChangesViaCondstore - INBOX: modseq 67496 to 67496, uidnext 46852 to 46852
26350 [2019-02-11 18:04:20.712] [background] [info] syncFolderChangesViaCondstore - Sent: modseq 67486 to 67486, uidnext 46850 to 46850
26350 [2019-02-11 18:04:20.952] [background] [info] syncFolderChangesViaCondstore - Drafts: modseq 65342 to 65342, uidnext 10277 to 10277
26350 [2019-02-11 18:04:21.206] [background] [info] syncFolderChangesViaCondstore - Archive: modseq 67494 to 67494, uidnext 46855 to 46855
26350 [2019-02-11 18:04:23.755] [background] [info] syncFolderChangesViaCondstore - Trash: modseq 67365 to 67365, uidnext 46768 to 46768
26350 [2019-02-11 18:04:23.764] [background] [info] syncFolderChangesViaCondstore - Junk: modseq 67240 to 67240, uidnext 46745 to 46745
26350 [2019-02-11 18:04:23.773] [background] [info] syncFolderChangesViaCondstore - Archives: modseq 67222 to 67222, uidnext 46738 to 46738
26350 [2019-02-11 18:04:24.008] [background] [info] syncFolderChangesViaCondstore - Mailspring: modseq 52160 to 52160, uidnext 30554 to 30554
26350 [2019-02-11 18:04:24.281] [background] [info] syncFolderChangesViaCondstore - Mailspring/Snoozed: modseq 52163 to 52163, uidnext 30556 to 30556
26350 [2019-02-11 18:04:24.581] [background] [info] Sync loop deleting unlinked messages with phase 2.
26350 [2019-02-11 18:04:24.581] [background] [info] Sync loop complete.
26350 [2019-02-11 18:04:24.582] [background] [info] Syncing folder list...
26350 [2019-02-11 18:04:24.604] [background] [info] syncFolderChangesViaCondstore - INBOX: modseq 67496 to 67496, uidnext 46852 to 46852
26350 [2019-02-11 18:04:24.888] [background] [info] syncFolderChangesViaCondstore - Sent: modseq 67486 to 67486, uidnext 46850 to 46850
26350 [2019-02-11 18:04:25.297] [background] [info] syncFolderChangesViaCondstore - Drafts: modseq 65342 to 65342, uidnext 10277 to 10277
26350 [2019-02-11 18:04:25.610] [background] [info] syncFolderChangesViaCondstore - Archive: modseq 67494 to 67494, uidnext 46855 to 46855
26350 [2019-02-11 18:04:27.631] [background] [info] syncFolderChangesViaCondstore - Trash: modseq 67365 to 67365, uidnext 46768 to 46768
26350 [2019-02-11 18:04:27.641] [background] [info] syncFolderChangesViaCondstore - Junk: modseq 67240 to 67240, uidnext 46745 to 46745
26350 [2019-02-11 18:04:27.650] [background] [info] syncFolderChangesViaCondstore - Archives: modseq 67222 to 67222, uidnext 46738 to 46738
26350 [2019-02-11 18:04:27.925] [background] [info] syncFolderChangesViaCondstore - Mailspring: modseq 52160 to 52160, uidnext 30554 to 30554
26350 [2019-02-11 18:04:28.258] [background] [info] syncFolderChangesViaCondstore - Mailspring/Snoozed: modseq 52163 to 52163, uidnext 30556 to 30556
26350 [2019-02-11 18:04:28.576] [background] [info] Sync loop deleting unlinked messages with phase 1.
26350 [2019-02-11 18:04:28.577] [background] [info] Sync loop complete.
26350 [2019-02-11 18:04:28.577] [background] [info] Syncing folder list...
26350 [2019-02-11 18:04:28.600] [background] [info] syncFolderChangesViaCondstore - INBOX: modseq 67496 to 67496, uidnext 46852 to 46852
26350 [2019-02-11 18:04:28.948] [background] [info] syncFolderChangesViaCondstore - Sent: modseq 67486 to 67486, uidnext 46850 to 46850
26350 [2019-02-11 18:04:29.296] [background] [info] syncFolderChangesViaCondstore - Drafts: modseq 65342 to 65342, uidnext 10277 to 10277
26350 [2019-02-11 18:04:29.593] [background] [info] syncFolderChangesViaCondstore - Archive: modseq 67494 to 67494, uidnext 46855 to 46855
26350 [2019-02-11 18:04:29.900] [background] [info] syncFolderChangesViaCondstore - Trash: modseq 67365 to 67365, uidnext 46768 to 46768
26350 [2019-02-11 18:04:29.909] [background] [info] syncFolderChangesViaCondstore - Junk: modseq 67240 to 67240, uidnext 46745 to 46745
26350 [2019-02-11 18:04:29.918] [background] [info] syncFolderChangesViaCondstore - Archives: modseq 67222 to 67222, uidnext 46738 to 46738
26350 [2019-02-11 18:04:30.181] [background] [info] syncFolderChangesViaCondstore - Mailspring: modseq 52160 to 52160, uidnext 30554 to 30554
26350 [2019-02-11 18:04:30.372] [background] [info] syncFolderChangesViaCondstore - Mailspring/Snoozed: modseq 52163 to 52163, uidnext 30556 to 30556
26350 [2019-02-11 18:04:30.571] [background] [info] Sync loop deleting unlinked messages with phase 2.
26350 [2019-02-11 18:04:30.572] [background] [info] Sync loop complete.
```

![image](https://user-images.githubusercontent.com/16774343/52580109-f75a4000-2e27-11e9-996e-dd2326c35149.png)

This constantly uses 30% of the CPU.

**Comment by cpacchierotti** [comment] 2019-03-06 10:04
This problem is still present in Mailspring 1.5.7.

**Comment by cagnulein** [comment] 2019-05-04 04:20
I have also the same issue with 1.6.1 on Ubuntu

**Comment by tiguchi** [comment] 2019-05-31 20:55
Just ran into that issue on Ubuntu 18.04. Mailspring kept 2 CPU cores constantly busy at 100%

**Comment by wonx** [comment] 2019-08-23 00:01
I have added my email accounts one by one to make sure it's indeed an IMAP issue. 4 gmail accounts, no problem. The moment I add one hotmail account, the scanning for emails never ends, even affecting other accounts that were working normally up to that point.

Are there any news about a possible fix?

**Comment by drjimmie1976** [comment] 2019-11-12 15:27
Repeatable for me on Debian 10. With Mailspring open all 4 cores continuously occupied at around 35 - 40%

![resources-mailspring-shutdown](https://user-images.githubusercontent.com/4533473/68684650-c0ed5500-0560-11ea-84a1-ec12b7af2619.png)

![mailspring-processes-mailspring-open](https://user-images.githubusercontent.com/4533473/68684731-e24e4100-0560-11ea-8128-9558fa322a44.png)

Shutting Mailspring gets back to service as usual, fans shut off within 5s.

**Comment by Tanneguy** [comment] 2020-01-28 08:31
Same issue on Ubuntu 19.04
I can't believe there is still no explanation about this behaviour

**Comment by 404NotFoundv2** [comment] 2020-02-08 11:30
Similiar issue here on fedora 31. It just eats my battery on my laptop.

**Comment by sj64** [comment] 2020-05-24 07:12
Just encountered this after update yesterday to 1.7.7. All 4 imap accounts continuously using 13%/14% cpu EACH, fans on full. Killing pids for mailsync processes is a pita workaround.

**Comment by TadielloM** [comment] 2020-09-18 07:46
Same problem here on Manjaro with KDE. Multiple accounts.
For each account I have this process running occupying 15% of CPU (intel core i7)
```/usr/share/mailspring/resources/app.asar.unpacked/mailsync.bin --mode sync --info mail@domain.com```

**Comment by squinterodlr** [comment] 2020-11-09 09:16
Same problem with Kubuntu 20.04, two google accounts and one IMAP. There's a 50/50 chance that when I start mailspring, three main processes will start and hog all the CPU usage and the client is stuck at "checking for mail". Killing the processes manually solves it.

**Comment by CodeMouse92** [comment] 2021-01-28 03:28
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/the-eternal-sync-bug/334

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 03:28 UTC
Labels: audit, linux, needs-reproduction
