### ISSUE TITLE
Stuck on 'scanning messages... \ loading messages...'

### ISSUE THREAD

**Issue by TristanK27** [Foundry376/Mailspring#2082] opened 2020-07-06 11:25 UTC
##### What is the behavior you're seeing?
Mailspring not syncing mail for 1 office365 account. All other accounts work fine, even other office365 accounts.
##### What email provider (Gmail, Exchange, etc.) are you trying to use?
Exchange
##### What operating system are you using?
Windows 10 version 2004
##### What version of Mailspring are you using?
1.7.8

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Only this 1 office365 account. Worked fine yesterday but stopped working today after reboot. Tried reinstalling, still not working.
Log:
```
12804 [2020-07-06 12:57:37.044] [background] [info] --sleeping
8284 [2020-07-06 12:59:41.963] [main] [info] Identity created at 1585499282 - using ID Schema 1
8284 [2020-07-06 12:59:41.964] [main] [info] ------------- Starting Sync (yesthisismymail@mail.uni.edu) ---------------
8284 [2020-07-06 12:59:41.979] [metadata] [info] Metadata delta stream starting...
8284 [2020-07-06 12:59:43.992] [background] [info] Marking all folders as `busy`
8284 [2020-07-06 12:59:43.993] [background] [info] Syncing folder list...
8284 [2020-07-06 12:59:44.634] [background] [info] Syncing folder list...
8284 [2020-07-06 12:59:45.016] [foreground] [info] Connection does not support idling. Locking until more to do...
8284 [2020-07-06 12:59:48.044] [background] [info] syncFolderUIDRange for INBOX, UIDs: 15755 - 16505, Heavy: true
8284 [2020-07-06 12:59:56.978] [metadataExpiration] [info] Scanning for expired metadata
8284 [2020-07-06 12:59:56.978] [metadataExpiration] [info] -- Will wake for next expiration in 7200sec
8284 [2020-07-06 13:00:16.933] [background] [critical] 
***
*** Mailspring Sync 
*** An exception occurred during program execution: 
*** {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID","key":"ErrorParse","retryable":true,"what":"Unknown exception"}
***

8284 [2020-07-06 13:00:16.933] [background] [info] --sleeping
8284 [2020-07-06 13:02:16.936] [background] [info] Syncing folder list...
8284 [2020-07-06 13:02:19.751] [background] [info] syncFolderUIDRange for INBOX, UIDs: 15755 - 16505, Heavy: true
8284 [2020-07-06 13:02:50.516] [background] [critical] 
***
*** Mailspring Sync 
*** An exception occurred during program execution: 
*** {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID","key":"ErrorParse","retryable":true,"what":"Unknown exception"}
***

8284 [2020-07-06 13:02:50.516] [background] [critical] *** Stack trace (line numbers are approximate):
*** 699  SyncWorker::syncFolderUIDRange()
*** 343  SyncWorker::syncNow()
*** 202  runBackgroundSyncWorker()
*** 686  ::operator()
*** 210  _Pad::_Call_func()
```
The part that keeps repeating:
![image](https://user-images.githubusercontent.com/20356336/86588209-96d32200-bf8b-11ea-8d8e-96bfbac7e571.png)

**Comment by CodeMouse92** [comment] 2021-01-28 03:33
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/the-eternal-sync-bug/334

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 03:33 UTC
Labels: audit, bug, mailserver-incompatibility, needs-reproduction
