### ISSUE TITLE
Bug: high power draw as a result of mailspring using the GPU while on background on linux

### ISSUE THREAD

**Issue by omaregb** [Foundry376/Mailspring#2143] opened 2020-09-15 21:24 UTC
**Describe the bug**
I have a laptop with discrete nvidia graphics switched off, though it is known that it will turn back on as a result of some apps trying to use it. Normally, Mailspring behaves well, with no significant power draw, however, if I suspend the laptop and then resume, mailspring will try to use the GPU based on what is shown in powertop. Power draw will increase by about 15W and GPU usage will go to 100%, significantly reducing battery life. Closing mailspring from the tray and launching it again brings the power draw back down, and the GPU will also go off.

**To Reproduce**
This is in a laptop with a Geforce GTX 1060 mobile (max-Q), while having the GPU disabled by optimus-manager in Manjaro.
1. Open Mailspring
2. Suspend
3. Resume
4. See power draw increase and GPU usage jump (despite it being "disabled")
5. Completely close Manjaro
6. See power Draw come back down.

**Expected behavior**
The power draw before and after suspend should remain the same.

**Setup: (please complete the following information):**
 - OS: Manjaro KDE
 - Mailspring Version: 1.7.8-13635bcf

**Comment by CodeMouse92** [comment] 2021-03-02 18:11
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/mailspring-has-high-cpu-usage/87

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 18:11 UTC
Labels: audit, bug
