### ISSUE TITLE
Support ARM

### ISSUE THREAD

**Issue by LeandroStanger** [Foundry376/Mailspring#1144] opened 2018-10-18 12:49 UTC

**Comment by bengotow** [comment] 2018-11-03 22:02
Hey! I’ll see if we can do this in the future. I /think/ we should be able to compile the C++ portion of Mailspring for ARM. I’m not sure about Electron but I’ll see.

**Comment by samhotchkiss** [comment] 2019-12-05 07:05
With the release of the Surface Pro X, it'd be great to see this on the Windows side, as well.  Any word on this, @bengotow ?

**Comment by pyeguy** [comment] 2019-12-17 18:36
Mailspring Pro X user here, would be great to see this as well! Right now it's functional but can be very laggy at times. Rumor has it Google has a Chrome for Windows ARM release completed and is expected sometime in early 2020 which will hopefully coincide w/ an Electron for WIndows ARM

**Comment by CodeMouse92** [comment] 2021-02-25 21:07
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/support-arm-architecture-windows/794

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-25 21:07 UTC
Labels: audit, enhancement, linux
