### ISSUE TITLE
Coping email between IMAP accounts

### ISSUE THREAD

**Issue by jbonlinea** [Foundry376/Mailspring#886] opened 2018-05-23 07:37 UTC
Hi, thank's for this great app

##### What operating system are you using?
debian stretch

##### What version of Mailspring are you using?
1.2.1

**Feature Request?**

I'm having more than one email account, all in IMAP.

I was used to use Apple Mail as a clien app, and could copy-paste email from one account to the other "naturally" as is they were on the same accound.
for instance with two gmail account,
account1 has labels A/B/C
account2 has labels D/E/F

I could mark any mail from accoun1 with the label E, in exactly the same way as I would mark it with label B.

if an email was marked with a label from it's own account, it was automatically archived on this account

if an email was mark with a label from an other account, it was copied to the second account, marked and achived, and also deleted from the first one.

This is what I would like to achieve with mailspring.

Is there any way to achieve this, or close to this with mailspring

Thank's

##### Does this feature exist in another mail client or tool you use?

yes, in apple mail app

**Comment by CodeMouse92** [comment] 2021-02-24 18:56
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/move-emails-and-folders-between-accounts/244

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-24 18:56 UTC
Labels: audit, enhancement, product-direction
