### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by dcts** [Foundry376/Mailspring#2130] opened 2020-08-25 20:26 UTC
**Is your feature request related to a problem? Please describe.**
I love the queries to search your inbox, but would be awesome if the date format could be more resillient (intelligent).

**Describe the solution you'd like**
I would love to have a string evaluation function that supports a lot of date formats, for example:
```
- "20 aug 2020" => detect as 2020-08-20
- "July 2020" => detect as 2020-07-01 (when in the before query)
- "July 2020" => detect as 2020-07-31 (when in the after query)
- "2020" => detect as 2020-12-31 (when in the after query) 
- "2020" => detect as 2020-01-01 (when in the before query) 
- "2020/08/01" => detect as 2020-08-01 (already working)
- "12.8.2020" => detect as 2020-08-01
``` 

These are just suggestions. I think the community should discuss and add all different kinds of date formats that should be supported, then we could define tests and write a function that satisfy all the specified formats. 

I would love to help with that. Let me know if this would be something that the community would like to see and I can provide a sample code.

**Comment by CodeMouse92** [comment] 2021-03-03 02:32
@dcts I think a PR for this would be very well received! Apologies for the delay. 2020 brought development to a screeching halt, but we've resumed.

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/intelligent-adaptive-dates-in-search/949

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@dcts: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-03 02:32 UTC
Labels: audit, enhancement
