### ISSUE TITLE
The new template / email composer does not allow editing the contents of HTML tables

### ISSUE THREAD

**Issue by nul0m** [Foundry376/Mailspring#585] opened 2018-01-26 18:17 UTC
I'm unable to use templates created using "edit as html" feature in the older version of Mailspring. In particular, I have a table which I cannot modify -- neither in Template Manager nor when inserted in the new mail.

in fact the same happens with the signatures. i cannot modify signatures in the mail.

##### Are there any related issues?

didn't find

##### What operating system are you using?
Ubuntu 16.04.3 LTS 64-bit

##### What version of Mailspring are you using?
1.1.0-7563b09d (auto updated from snap)

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
no

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
no, it's the application issue

##### Is the issue reproducible with a particular attachment, message, signature, etc?

i can reproduce it with all my templates

**Comment by bengotow** [comment] 2018-01-27 20:27
Hey! Thanks for reporting this @nul0m — In 1.1.0, the composer text editor was switched out for a new one (built on SlateJS) that made it easier to add new features like font size and color, and will enable more things to be added in the next couple releases. The one big drawback of the change is that content inside `<table>` tags needs to be locked in the editor to preserve it's exact appearance, because Slate doesn't support all of the styles / features of tables and would break some of them.

I'll see if I can find a good solution to this in the next update - we can probably allow editing inside tables and other custom HTML without Slate's shortcuts / rich text tools.

**Comment by nul0m** [comment] 2018-01-27 20:45
thanks @bengotow, will revert my snap to the 1.0.12 before then

**Comment by Xin6Zhou** [comment] 2018-04-29 02:44
hi,  @bengotow

Just interested at the progress.

the feature of editable tables in composer is essential for me, because our team uses the email embedded table to collect important task information. I roll back to 1.0.12 now. 

thanks.

**Comment by sergiodieguez** [comment] 2018-05-17 08:12
essential for us too.

thanks.

**Comment by RavenKong** [comment] 2018-06-05 04:32
Yes please bring back the ability to edit tables, I fall back to 1.0.12 until newer release fixes this issue.
Thanks!

**Comment by nul0m** [comment] 2019-07-19 10:04
hey, @bengotow any update on this one? as far as I can see [here](https://www.slatejs.org/#/tables) SlateJS does support tables editing. any chance you could utilize that?

**Comment by estebansanti** [comment] 2019-10-25 22:13
@bengotow

We 👏🏽Need 👏🏽This

**Comment by coreders** [comment] 2020-09-25 08:58
Hi, 
Still no progress on this issue ?

**Comment by o4dev** [comment] 2020-11-19 06:01
How is there STILL no progress on this? To me the templates are useless without! How are you meant to have templates you can't fill with content! Please let me know if this is being worked on else I will fork and try to fix it myself. 

MailSpring is incredible and I am thankful to every contributor. This seems like a key feature that we need this feature thou.

**Comment by CodeMouse92** [comment] 2021-02-16 23:58
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/the-new-template-email-composer-does-not-allow-editing-the-contents-of-html-tables/654

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@nul0m: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

@o4dev To my knowledge, no one is working on this right now — an avalanche of higher priority tasks are in the way — so you're welcome to take it on. Please post on the Discourse topic if you decide to work on it. We'd appreciate the help!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-16 23:58 UTC
Labels: audit, composer
