### ISSUE TITLE
Mailspring should preview small TIFF images along with JPEG, GIF, etc.

### ISSUE THREAD

**Issue by ggirelli** [Foundry376/Mailspring#1117] opened 2018-10-08 12:52 UTC
##### Are there any related issues?

Kind-of similar to this: https://github.com/Foundry376/Mailspring/issues/262
But different... :)

##### What operating system are you using?

Ubuntu 18.04

##### What version of Mailspring are you using?

v1.4.2.f587b7b7

--

**Bug:** inline tiff images (don't make me start on why someone would ever want to include tiff images as inliners, as I do not get it either) are not showed in mailspring, while they are properly showed on the Gmail web interface. The email HTML contains the proper `<img />` tag with the proper file address (see below). I tried to access the location and the file indeed is there, it's just not showed. I quickly tested inline `png` images and those work properly. Any clues?

```html
<img id="F87091C9-31F5-43C7-8972-0101521C8967" src="file:///home/gire/snap/mailspring/common/files/ru/ew/ruewre9uvxfwvsqmikxb7hmcceweazoucyhuhq82y/1 - Faktura-2.tiff" style="max-width: 100vw;">
```

##### Is this an email sync or connection issue?

No.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Not sure, I have only Gmail accounts though so I cannot test it on other ones.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Yes, it is.

**Comment by bengotow** [comment] 2018-10-16 06:28
Hey! Thanks for reporting this—I think there are a couple things going on here. Mailspring doesn't preview TIFF images right now, and also doesn't preview images that are larger than 5MB (because they can make the app use a lot of memory.)

I think it'd be fairly safe to allow <5MB tiff files to be previewed along with JPEG, GIF, etc. If anyone wants to take a look, I think this might be a good starter issue! There's a utility function called `shouldDisplayAsImage` that determines whether Mailspring treats an attachment as an image or a file, I think the change could go in there.

**Comment by LonghornRach** [comment] 2018-10-17 15:45
I can take a look at this

**Comment by adriancodesailors** [comment] 2019-05-16 07:37
I know this is quite old but browser natively do not support TIFF files - we'd have to convert it using some library to canvas and display it from there (either generate temp file with thumbnail which sounds like a major refactor to me or display the encoded imagedata in img tag).

Is it really worth it? Do you want to continue with this? If yes - in which way? @bengotow

**Comment by lashus** [comment] 2019-05-16 07:38
I know this is quite old but browser natively do not support TIFF files - we'd have to convert it using some library to canvas and display it from there (either generate temp file with thumbnail which sounds like a major refactor to me or display the encoded imagedata in img tag).

Is it really worth it? Do you want to continue with this? If yes - in which way? @bengotow

**Comment by CodeMouse92** [comment] 2021-02-25 01:36
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mailspring-should-preview-small-tiff-images-along-with-jpeg-gif-etc/783

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@ggirelli @lashus: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-25 01:36 UTC
Labels: audit, enhancement, good first issue
