### ISSUE TITLE
Allow searching in the "Show Original" window

### ISSUE THREAD

**Issue by jerm** [Foundry376/Mailspring#907] opened 2018-06-01 00:54 UTC
Please add, or no longer suppress, the ability to do a find/search in the "Show Original" window.

**Comment by bengotow** [comment] 2018-07-08 07:38
It looks like this is possible, but the default UI isn't available (that tiny overlay with the text field and up/down arrows) so I'd need to roll something. I think this would apply to the print window as well though, so I'll see what I can do! https://electronjs.org/docs/all#contentsfindinpagetext-options

**Comment by CodeMouse92** [comment] 2021-02-20 02:55
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/allow-searching-in-the-show-original-window/709

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@jerm: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-20 02:55 UTC
Labels: audit, enhancement
