### ISSUE TITLE
Multiple copies of email in sent folder.

### ISSUE THREAD

**Issue by debabratadas-zz** [Foundry376/Mailspring#151] opened 2017-10-13 13:30 UTC
##### What operating system are you using?
Ubuntu 16.10

##### What version of Mailspring are you using?
1.0.4-e604c991

##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Hotmail (Not sure, cause used Hotmail only in which this issue is present. It may be also reproducible in other email provider also).

##### Bug:
On sending email, there are multiple (mostly 2, but sometime 3) copies of email present in "Sent" folder. 
This also get reflected in webmail also, so email is not just in app sent folder but gets synced in actual. It works correctly in Thunderbird, so issue can't be at email provider side.

**Comment by icf20** [comment] 2017-10-14 06:17
Check with the server/service providers by default many of them put a copy on the folder and then your mail client put another

**Comment by debabratadas** [comment] 2017-10-14 06:31
In **Thunderbird** following setting prevents this:
1. Go to **Tools** on Thunderbird.
2. Click on **Account settings** and select your account name.
3. Go to **Copies and Folders**.
4. Uncheck the option which says “**Place a copy in**.”

I think we need similar option in **Mailspring** app.

**Comment by ricardovsilva** [comment] 2018-01-05 16:23
Is there someone looking at that?

**Comment by jsburckhardt** [comment] 2018-02-22 10:08
Same boat here... I send an email and the receiver gets 5. 
I'm using Hotmail and I set it up through IMAP/SMTP.

**Comment by easternbluebird** [comment] 2018-03-21 08:05
I am using bcc per default to have threaded view of all conversations for other mail clients (can I tell mailspring to use only mails in the inbox for the thread, not in the sent folder?).

**Comment by debabratadas** [comment] 2018-07-24 07:02
Is there someone looking at this? This issue prevents me from using this software as receivers gets email multiple times.

**Comment by jordantshaw** [comment] 2018-09-04 20:53
Same issue, also using outlook on Ubuntu 18.  Is this being fixed?

**Comment by coryrose1** [comment] 2018-09-29 11:27
Same issue as well on OSX, sent work email to multiple contacts multiple times, really can't use this software until I know that won't occur again.

**Comment by Bezuki-sf** [comment] 2018-10-12 19:00
Same issue Win 10, starting 10/09/2018.  Cannot resolve with various settings.  Clients going nuts with receiving so many copies of mail.  Stopped using. 

**No response** from Mailspring as of yet.

**Comment by m7rcelo** [comment] 2018-12-14 12:02
Same here. Still waiting.

**Comment by ShiveshM** [comment] 2019-08-06 15:03
Still seeing the same issue, v1.6.3 on Ubuntu 18.04.

**Comment by saravanabalagi** [comment] 2019-08-10 23:54
I have it as well, 
v1.6.3
Windows 10 & Ubuntu 18.04

**Comment by CodeMouse92** [comment] 2021-01-29 21:27
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/duplication-of-sent-mail/275

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-29 21:27 UTC
Labels: audit
