### ISSUE TITLE
Add keyboard shortcut for "next/previous message in current thread"

### ISSUE THREAD

**Issue by vlcinsky** [Foundry376/Mailspring#1566] opened 2019-07-08 12:41 UTC
Mailspring version: `1.6.3-136a0e55` on Debian Buster

**Feature Request**

Gmail has shortcuts for next/previous message in current thread (`p` and `n`)

Current version of Mailspring only allows to:
- goto next and previous thread
- search in current thread

It would be great to have next/previous message in current thread as a keyboard shortcut in Mailspring too (as keyboard shortcuts contribute to productivity in general).

**Comment by david-sitsky** [comment] 2020-06-01 23:48
This would be extremely useful as I often have to navigate long email threads with large bodies and it is a painful process right now.

**Comment by CodeMouse92** [comment] 2021-02-26 17:06
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/add-keyboard-shortcut-for-next-previous-message-in-current-thread/825

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@vlcinsky @david-sitsky: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-26 17:06 UTC
Labels: audit, enhancement
