### ISSUE TITLE
office365: High CPU Usage

### ISSUE THREAD

**Issue by muradm** [Foundry376/Mailspring#1177] opened 2018-10-26 13:26 UTC
##### Are there any related issues?

Yes, there are related issues from beginning of the year. Most are closed at version 1.1.3.

##### OS: Arch Linux + Gnome, Version: 1.5.0-92ed66b8

**Bug**

Constantly high CPU usage:

![image](https://user-images.githubusercontent.com/2050575/47569307-5319bf80-d944-11e8-955b-ca700ec6554a.png)

Have to periodically use mailspring, because my laptop get too hot.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Could be related to Office365 connector. It keeps fetching old folders over and over again.

**Comment by ericnewton76** [comment] 2018-11-12 23:59
I have imap account into Gmail and a private server, seeing high cpu usage at rest as well

**Comment by bLuka** [comment] 2019-01-17 12:13
Three accounts, one Gmail and two Office365.

A process called `mailsync.bin`, one by email account, sometimes showing up 100% of CPU usage on Gentoo GNU/Linux for a short time.

The Mailspring main process (`opt/mailspring/mailspring --type=gpu-process ...`) is constantly using 20%/30% of CPU.

Some other mailspring processes (`/opt/mailspring/mailspring --background`, and `Mailspring default             ox --js-flags=--harmony ...`) are using 10% CPU each.

**Comment by aethralis** [comment] 2019-03-28 12:37
Also affected by similar bug (Gmail + office365). Ubuntu, sometimes the cpu usage goes to 100% and the fan is constantly spinning.

**Comment by bLuka** [comment] 2019-03-28 13:47
I'm thinking about leaving Mailspring for this bug and some others (crashes, visual glitches, …), but having a mail client using more than 1GiB of RAM sometimes, and too much CPU ressources is a bit of a pain on a laptop…

In top of that, absence of support is really hard to stand when you see about 700 of opened issues, and no trace of discussion with the maintainer.

**Comment by CodeMouse92** [comment] 2021-01-18 22:31
Thank you for reporting this. 2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mailspring-has-high-cpu-usage/87

Please consider joining that community and continuing the discussion there! Bonus: if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-18 22:31 UTC
Labels: audit

**Comment by CodeMouse92** [comment] 2021-01-18 22:33
Duplicate of #2218
