### ISSUE TITLE
Markdown support on compose

### ISSUE THREAD

**Issue by bnvt** [Foundry376/Mailspring#891] opened 2018-05-24 08:28 UTC
As per [issue #19](https://github.com/Foundry376/Mailspring/issues/19), markdown is supported for composing emails since v 1.1.0.
I haven't been able to find any documentation on the feature, though.
No markdown code is rendered when composing email, and I'm unsure if this is some feature I need to explicitly enable to use it. I'm unsure if markdown code is rendered when the mail is sent, or I'm supposed to render it by some command before sending.

**Comment by mclang** [comment] 2018-05-24 12:05
I found out about the (partial?) markdown support when I entered command text between back-tick ('`') characters, where the text between back-ticks were suddenly converted into fixed space font. I tried to use two sets of three back-ticks to enter bigger code block, but that didn't work, so I don't know what works and what not.

But I still would like to have plain text support.

**Comment by bnvt** [comment] 2018-05-24 12:41
Well, thanks to your tip I managed to get some italic and bold markdown rendered; just start a text block with a back-tick, ('`'), then your '*' and '**' will get auto expanded to italic and bold. But this seems to work randomly and often gets the text editor locked down (All this in OSX).
Seems that this markdown support is still in a very early stage of development.

**Comment by mitten** [comment] 2018-07-18 23:32
How do I turn this "feature" off? I don't want to use Markdown, I just want to type regular text. 

The specific problem I'm having is that typing "- Laura" turns into "• Laura" with an indent, as if I'm starting a list.

How do I make it stop doing that?

**Comment by mclang** [comment] 2018-08-09 11:37
I think that annoying feature is older than markdown support... But I might be wrong.

**Comment by ASeatonSpatial** [comment] 2019-07-31 09:02
I also want to turn this feature off, but I can't seem to find a way to do that.  

I frequently send emails with code snippets or maths where I use * to indicate multiplication.  It's very annoying it gets rendered to italics and the *'s disappear.

**Comment by ubuntudroid** [comment] 2020-06-20 15:58
@mitten @ASeatonSpatial Late on this one, but did you guys try to switch off *Enable rich text and advanced editor features* in the **Composing** section in the **General** tab of settings? This could do what you want. :)

**Comment by CodeMouse92** [comment] 2021-02-18 22:44
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/markdown-support-in-composer/322

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-18 22:44 UTC
Labels: audit
