### ISSUE TITLE
Bug: vanishing text when replying to an email

### ISSUE THREAD

**Issue by asparc** [Foundry376/Mailspring#2020] opened 2020-05-25 23:18 UTC
When replying to a message while the option "Display conversations in descending chronological order" is ENABLED in Preferences, the text of the message you are replying to will vanish as soon as the reply is sent. Reopening the message restores the text, so it is just a cosmetic problem, but it can be quite annoying.

**Setup: (please complete the following information):**
 - OS: Ubuntu 20.04
 - Mailspring Version: 1.7.8

**Comment by CodeMouse92** [comment] 2021-03-02 00:40
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/vanishing-text-when-replying-to-an-email/904

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@asparc: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 00:40 UTC
Labels: audit, bug
