### ISSUE TITLE
Folder Sync with Office 365 is Buggy

### ISSUE THREAD

**Issue by seesemichaelj** [Foundry376/Mailspring#684] opened 2018-02-14 17:41 UTC
If I mark an email as archived in Mailspring (with the archive folder set to Archive), the email doesn't show up as archived in Outlook Android. If I move an email from the Archive folder to the Inbox from Outlook, Mailspring doesn't show the email in the Inbox. When Mailspring tries to get fresh emails, I see the email appear in the inbox for a second before it disappears.

I'm not sure how reproducible these issues are; the first didn't seem very reproducible but the second was more so. I'll update after I get more info.

##### Are there any related issues?
I couldn't find any.

##### What operating system are you using?
Elementary OS 0.4.1 Loki

##### What version of Mailspring are you using?
1.1.3

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Office 365

##### Is the issue reproducible with a particular attachment, message, signature, etc?
N/A

**Comment by bengotow** [comment] 2018-02-14 21:59
Hmm this one is interesting–I have an Office365 account I use for testing, I'll see if I'm able to reproduce this. Next time you notice this happen, can you look in the mailsync log file and see if there are any errors?

**Comment by ReedMerrill** [comment] 2020-05-20 16:33
I have a related issue. A folder on my Office 365 account with rules to move emails from certain contacts doesn't sync to mailspring. Has this issue been resolved yet?

**Comment by CodeMouse92** [comment] 2021-02-02 02:44
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/disappearing-emails-desync/428

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-02 02:44 UTC
Labels: audit, needs-reproduction
