### ISSUE TITLE
Reply-To Headers

### ISSUE THREAD

**Issue by himynameisphil** [Foundry376/Mailspring#1666] opened 2019-10-15 10:33 UTC
Mailspring doesn't seem to respect the reply-to headers.

**Comment by Webbeh** [comment] 2019-10-17 18:41
Hey there.

Just to let you know that I have the same issue here, From: and Reply-to: headers giving different addresses, and the From: address is used in the To: header of a reply.

This is not correct and the Reply-To address should be used over the From address, every time it is given, according to [RFC822](https://tools.ietf.org/html/rfc822#section-4.4.4) (section 4.4.4).
Quoting :

>             o   If the "Reply-To" field exists, then the reply  should
>                 go to the addresses indicated in that field and not to
>                 the address(es) indicated in the "From" field.

Some reasons as to why it is this way are given in section 4.4.3 of the same RFC. 

Literally every other email client does it correctly...

Please change this behaviour to respect the RFC.

**Comment by nickreiner** [comment] 2019-11-18 03:26
I'm having the same issue. Mailspring doesn't respect the Reply-To field when the reply-to is an email from one of your accounts

**Comment by CodeMouse92** [comment] 2021-02-08 21:23
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/reply-to-headers/507

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@Webbeh: I used *your* bug summary, as it was the most detailed. If you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-08 21:23 UTC
Labels: audit, needs-reproduction
