### ISSUE TITLE
Hotmail emails shows and disappears 

### ISSUE THREAD

**Issue by dlj2019** [Foundry376/Mailspring#1415] opened 2019-03-12 01:42 UTC
##### Are there any related issues?

...

##### What operating system are you using?

...

##### What version of Mailspring are you using?

...

--

**Bug?**

##### Is this an email sync or connection issue?

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

...

**Comment by cpacchierotti** [comment] 2019-03-12 15:08
Probably similar to #304. Please check your logs to confirm that this is the same bug.

**Comment by dlj2019** [comment] 2019-03-12 19:15
I am running on KDE Neon 18.04

**Comment by cpacchierotti** [comment] 2019-03-12 19:24
Please compare your Mailspring logs (~/.config/Mailspring/mailsync-*.log) with those of #304, as soon as this happens. If they are similar, please report your experience on #304.

**Comment by CodeMouse92** [comment] 2021-02-02 02:41
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/disappearing-emails-desync/428

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-02 02:41 UTC
Labels: audit
