### ISSUE TITLE
Dynamic SHORTCODE or variable insertion possible in signature? 

### ISSUE THREAD

**Issue by ReessKennedy** [Foundry376/Mailspring#1355] opened 2019-02-06 20:27 UTC
New Mailspring user here on a Mac and using it with Gmail. 

**ISSUE:** Is there a method to use something like {{recipient_email}} or [email] in the HTML signature and have Mailspring insert the recipients email before sending? 

This would allow me to insert my own custom tracking code with the other open source tool I use for tracking. Thanks for the help ... or any ideas!

**Comment by CodeMouse92** [comment] 2021-02-10 23:35
Duplicate of #174

**Closed by CodeMouse92** 2021-02-10 23:35 UTC
Labels: audit
