### ISSUE TITLE
Mailspring opens on system start when option is turned off

### ISSUE THREAD

**Issue by JKAnderson409** [Foundry376/Mailspring#1493] opened 2019-05-10 15:17 UTC
##### What operating system are you using?

MacOS Mojave 10.14.4

##### What version of Mailspring are you using?

1.6.1

**Bug?**

##### Is the issue reproducible with a particular attachment, message, signature, etc?

To reproduce:

Install Mailspring on MacOS Mojave 10.14.4, uncheck preference "Launch on system start" and restart the OS.

**Comment by bengotow** [comment] 2019-05-26 19:44
Hey! Thanks for reporting this—when you check/uncheck the box, Mailspring creates and removes `~/Library/LaunchAgents/com.mailspring.plist`. It looks like right now there's no user feedback if that fails for some reason. It also looks like if you go to System Preferences and configure Mailspring to launch at start from the Users & Groups preference pane under Login Items, that creates a /separate/ preference in another locaiton which could separately launch Mailspring even if you unchecked the box within the app.

This is a bit of a mess—I'll see if we can revisit this and clean up the MacOS implementation to do the same thing as adding the app as a "Login Item" in system preferences. In the meantime, I'll make the app present an error message if removing it's LaunchAgent plist fails. You may be having a permissions issue of some sort and it's just not letting you know it's unable to delete that file.

Thanks!

**Comment by Darthagnon** [comment] 2020-03-29 13:06
I've noticed the same problem on Windows - setting Mailspring to not open on boot, and it resets the option and does so anyway.

**Comment by maneandrea** [comment] 2020-04-08 11:44
On Ubuntu 18.04 LTS I get a similar issue, which perhaps is related. If I un-check the box "Launch on system start", then I close the settings (or I go to another tab) and go back to the "General" tab, I see that the check was put back in.

Note: This is on Mailspring 1.7.4

**Comment by Darthagnon** [comment] 2020-04-09 13:31
> On Ubuntu 18.04 LTS I get a similar issue, which perhaps is related. If I un-check the box "Launch on system start", then I close the settings (or I go to another tab) and go back to the "General" tab, I see that the check was put back in.
> 
> Note: This is on Mailspring 1.7.4

Exactly what happens on Windows. Good that someone else can confirm it; I wasn't 100% sure, since I was using some configuration mods.

**Comment by playforvoices1** [comment] 2020-04-16 16:13
The same problem appears here on Windows 10 and elementaryOS  (Ubuntu 18.04 LTS). I uncheck the option, leave the tab, go back to it and it's checked again. 

I use on both machines the version 1.7.4

**Comment by Darthagnon** [comment] 2020-05-12 21:03
Update: v1.7.6 - Mailspring still always keeps "Use Mailspring as default mail client" and "Launch on system start" checked. Please, could the checkboxes clear and stay cleared when we click on them?

**Comment by Darthagnon** [comment] 2020-05-25 12:22
Update: v1.7.8 - Bug still present. I tested, and #2010 notices it too.

**Comment by CodeMouse92** [comment] 2021-02-17 00:49
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/i-cant-uncheck-run-on-startup/208

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-17 00:49 UTC
Labels: audit, bug, good first issue, macos
