### ISSUE TITLE
Bug: Word documents are forwarded as empty

### ISSUE THREAD

**Issue by ondrej-petr** [Foundry376/Mailspring#2061] opened 2020-06-20 11:16 UTC
**Describe the bug**
When I forward mail with Word document (.doc), file is sent as empty (with 0 size).

**To Reproduce**
1. Receive mail with Word doc attachement.
2. Forward this mail
3. Check the outsent mail

**Expected behavior**
Word document should stay as it is

**Screenshots**
![image](https://user-images.githubusercontent.com/9945232/85200463-f082ed80-b2f7-11ea-9bf7-fc9f9790b947.png)

**Setup: (please complete the following information):**
 - OS: Windows
 - 10 (19040.330)
 - Mailspring Version: ex: 1.7.8

**Additional context**

**Comment by CodeMouse92** [comment] 2021-03-02 03:01
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/word-documents-are-forwarded-as-empty/919

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@ondrej-petr: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 03:01 UTC
Labels: audit, bug
