### ISSUE TITLE
[Feature request] Add an option to hide default labels

### ISSUE THREAD

**Issue by igor-krupenja** [Foundry376/Mailspring#987] opened 2018-07-19 14:11 UTC
##### Are there any related issues?

No.

##### What operating system are you using?
macOS 10.13.6

##### What version of Mailspring are you using?
1.3.0

**Feature Request?**

Would be great to have an option to hide some of the default labels under All Accounts:
![image](https://user-images.githubusercontent.com/26354715/42947537-328e6c28-8b76-11e8-84f3-2579fd45984c.png)
For instance, Reminders, Snoozed and All Mail.

##### Does this feature exist in another mail client or tool you use?
On macOS this is definitely implemented in Spark, I think also in Airmail.

**Comment by CodeMouse92** [comment] 2021-02-04 23:13
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/left-pane-hide-show-folders/469

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

OP: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-04 23:13 UTC
Labels: audit
