### ISSUE TITLE
Bug: MailSpring cannot be installed on Centos8+ or RHEL 8+

### ISSUE THREAD

**Issue by lambdaknight** [Foundry376/Mailspring#2125] opened 2020-08-21 16:21 UTC
**Describe the bug**
MailSpring cannot be installed on Centos8+ or RHEL 8+ due to broken dependency.

**To Reproduce**

    1. Download mailspring (*.rpm)

    2. Try to install on Centos8+ or RHEL 8+

**Expected behavior**
The installation runs smoothly

**Screenshots**
Not required. Log:

```
Error: 
 Problem: conflicting requests
  - nothing provides libappindicator needed by mailspring-1.7.8-0.1.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

**Setup: (please complete the following information):**

    * OS: Centos and RHEL

    * OS Version 8+

    * Mailspring Version: 1.7.4

**Possible bug fix**
In file ./app/build/resources/linux/redhat/mailspring.spec.in

```
%ifarch i386 i486 i586 i686
Requires: lsb-core-noarch, libXss.so.1, libsecret-1.so.0, ca-certificates
%if 0%{?rhel} >= 8
Requires: libappindicator-gtk3
%else
Requires: libappindicator
%endif
%else
Requires: lsb-core-noarch, libXss.so.1()(64bit), libsecret-1.so.0()(64bit), ca-certificates
%if 0%{?rhel} == 8
Requires: libappindicator-gtk3
%else
Requires: libappindicator
%endif
%endif
```

Note: I just copied this bug report from #1870 and included @dillonforrest 's suggestion from that bug after it was closed since it seems like it might have escaped your notice. Specifically, it looks like the >= operator didn't work, but the == apparently does work.

**Comment by CodeMouse92** [comment] 2021-03-03 02:22
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mailspring-cannot-be-installed-on-centos8-or-rhel-8/947

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@lambdaknight: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-03 02:22 UTC
Labels: audit, bug
