### ISSUE TITLE
How to uninstall a theme?

### ISSUE THREAD

**Issue by akraminakib** [Foundry376/Mailspring#518] opened 2018-01-10 21:43 UTC
Hey I just started trying out Mailspring for my Macbook and love it! Only issue for me is that after I installed a custom theme, I've decided not to go with that theme and wanted to uninstall it. There's currently no button to uninstall a certain theme. Is there a specific folder path that the installed themes are in so I can delete it?

**Comment by dweremeichik** [comment] 2018-01-11 19:01
According to the Starter Theme template docs, for a Mac, the theme should be located here: `~/Library/Application Support/Mailspring/packages/THEME_NAME`.

**Comment by akraminakib** [comment] 2018-01-11 21:25
@dweremeichik Thank you! Maybe a feature where users can do it through the app itself would make it a bit less confusing.

**Comment by dweremeichik** [comment] 2018-01-11 23:24
@akraminakib I think your correct, it might be worth reopening this so that it can be tracked.

**Comment by cyranowebdev** [comment] 2020-08-30 23:24
Hi there. Found this issue opened while trying to figure out how to remove a theme I installed for Mailspring.
I'm using Elementary OS Hera, and found the themes folders.
I erased the one I wanted to remove, but now the option remains in the theme picker in the app, while its folder is no more. Not exactly what I wanted, of course.

**Comment by CodeMouse92** [comment] 2021-01-30 01:01
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/plugin-theme-catalog/318

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-30 01:01 UTC
Labels: audit
