### ISSUE TITLE
Email Tag answer problem

### ISSUE THREAD

**Issue by sinnlosername** [Foundry376/Mailspring#1005] opened 2018-08-03 21:52 UTC
##### Are there any related issues?
Couldn't find one

##### What operating system are you using?
Windows

##### What version of Mailspring are you using?
1.3.0

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### The problem
I got an email using imap in mailspring. Let's call it test@example.com. My mail provider is modern, so they support email tags. This means if I send an email to test+tag@example.com it will be delivered to test@example.com. This works fine, but if I try to answer the mail it will answer to the wrong mail. 

For example: I send a mail from abc@gmail.com to test+tag@example.com. If I click on the "answer" button it should answer to abc@gmail.com, but for me it answers to test+tag@example.com (to myself).

A picture of the bug:
 ![Bug](https://png.sx/i3Dv)

**Comment by bengotow** [comment] 2018-09-17 19:38
Hey! This is a good catch - I don't think we have test coverage for this scenario at the moment. I'll see if I can get this fixed in an upcoming release. I think this is happening because Mailspring can't figure out which of the recipients is "you".

**Comment by CodeMouse92** [comment] 2021-02-19 00:07
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/reply-to-headers/507

@sinnlosername: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-19 00:07 UTC
Labels: audit, bug, composer
