### ISSUE TITLE
unexpected mailsync error occurred

### ISSUE THREAD

**Issue by amarbreddy** [Foundry376/Mailspring#353] opened 2017-11-20 02:39 UTC
I got the error message while adding my google account. After signing into gmail account , I get the following message .

An unexpected mailsync error occurred (134). Try again.

Please let me know what could be causing this issue.

I am using ubuntu 17.10 as an OS

**Comment by DmitryLoki** [comment] 2017-11-24 00:28
Confirm this bug. Ubuntu 16.10, MS 1.0.8

**Comment by bengotow** [comment] 2017-11-25 20:53
Hey! Thanks for reporting this—it sounds like a message in your mailbox is crashing the sync worker. I'm working on some additional error reporting that should make this much easier to track down and fix. Stay tuned—

**Comment by robertsheacole** [comment] 2017-12-15 04:41
Having the same problem here! Any resolution to this?

**Comment by jessykate** [comment] 2018-01-17 07:50
I'm also having this issue on Linux, Ubuntu 17.04, when trying to connect a G Suite email account. Firefox default browser, and I installed via the .deb.

**Comment by Skylled** [comment] 2018-01-22 20:34
I can reproduce this on a G Suite account with no emails.

**Comment by ThinkDigitalRepair** [comment] 2018-02-10 22:32
I'm having this issue trying to sync a bluehost email account. Trying to find the logs for the snap app on Ubuntu

**Comment by ShravanTata** [comment] 2018-02-12 14:58
I have the same error. Any solutions?

**Comment by robertsheacole** [comment] 2018-02-12 20:15
hrm...no answer...I'm done wasting my time with this app.

**Comment by ShravanTata** [comment] 2018-02-13 13:22
Well, fair enough! I think I have wasted a fair amount of time on it too.

**Comment by jdavidbakr** [comment] 2018-02-14 02:40
Same issue here, "View Log" does nothing.

**Comment by fcastilloec** [comment] 2018-02-14 19:58
Installed mailsync for the first time on Ubuntu 16.04 using `snap`, when setting up my account using IMAP I get this error. I tried setting up on Virtualbox running Ubuntu 17.04 and there was no problem there

**Comment by pahofmann** [comment] 2018-02-15 20:44
Installed via snap on 16.04, too and get the same error when adding an IMAP account (not gmail) 

> An unexpected mailsync error occurred (134)View Log

If there is any input I can provide just let me know.

**Comment by martinjurco** [comment] 2018-02-22 12:40
Ubuntu 17.10

When installing the app via .deb package downloaded from project website I get the same error - An unexpected mailsync error occurred (134). 
+
when trying to sync it after installing it via Ubuntu Software I get an error: "Could not reach https://id.getmailspring.com/onboarding?
utm_medium=N1&utm_source=0nboarding Page&N1_version=1.1.4-
22d9f20d&client_edition=basic. The host name could not be
resolved.

Try Again"

**Comment by roboto-cloud** [comment] 2018-03-03 20:05
same issue here:

Log:
```

Waiting for Account JSON:

Waiting for Identity JSON:
info: Identity created at 1509539227 - using ID Schema 0
critical: 
 ***
 *** A JSON exception occurred during program execution: 
 *** [json.exception.type_error.302] type must be string, but is null
 ***

critical: 
 ***
 *** A JSON exception occurred during program execution: 
 *** [json.exception.type_error.302] type must be string, but is null
 ***

critical:  *** Stack trace (line numbers are approximate):
 *** ??:?  void nlohmann::detail::from_json(nlohmann::basic_json const&, nlohmann::basic_json::string_t&)
 *** ??:?  decltype ((from_json({parm#1}, {parm#2})),((void)())) nlohmann::detail::from_json_fn::call(nlohmann::basic_json const&, string&, nlohmann::detail::priority_tag) const
 *** ??:?  void nlohmann::detail::from_json_fn::operator()(nlohmann::basic_json const&, string&) const
 *** ??:?  void nlohmann::adl_serializer::from_json(nlohmann::basic_json const&, string&)
 *** ??:?  string nlohmann::basic_json::get() const
 *** ??:?  Account::IMAPSecurity()
 *** ??:?  MailUtils::configureSessionForAccount(mailcore::IMAPSession&, shared_ptr)
 *** ??:?  runTestAuth(shared_ptr)
 *** ??:?  main
 ***

critical:  *** Stack trace (line numbers are approximate):
 *** ??:?  void nlohmann::detail::from_json(nlohmann::basic_json const&, nlohmann::basic_json::string_t&)
 *** ??:?  decltype ((from_json({parm#1}, {parm#2})),((void)())) nlohmann::detail::from_json_fn::call(nlohmann::basic_json const&, string&, nlohmann::detail::priority_tag) const
 *** ??:?  void nlohmann::detail::from_json_fn::operator()(nlohmann::basic_json const&, string&) const
 *** ??:?  void nlohmann::adl_serializer::from_json(nlohmann::basic_json const&, string&)
 *** ??:?  string nlohmann::basic_json::get() const
 *** ??:?  Account::IMAPSecurity()
 *** ??:?  MailUtils::configureSessionForAccount(mailcore::IMAPSession&, shared_ptr)
 *** ??:?  runTestAuth(shared_ptr)
 *** ??:?  main
 ***

/usr/share/mailspring/resources/app.asar.unpacked/mailsync: line 4: 13483 Aborted                 SASL_PATH="$(dirname $(realpath $0))" LD_LIBRARY_PATH="$(dirname $(realpath $0));$LD_LIBRARY_PATH" "$(dirname $0)/mailsync.bin" "$@"
```

**Comment by itesk8** [comment] 2018-03-04 15:36
Waiting for Account JSON:

Waiting for Identity JSON:
info: Identity created at 1515027538 - using ID Schema 0


 ***
 *** A fatal error occurred during program execution.
 *** No details were provided about the error.
 ***
CREATE PROCESS FAIL: 
addr2line.exe -f -i -C -s -p -e "C:\Users\loihx\AppData\Local\Mailspring\app-1.1.4\resources\app.asar.unpacked\mailsync" 75FE08C2 5BB245A5 0088FC83 0088BEC0 008CA01C 008AE99B 008B8E8C 008BBACA 009D0B3C 73F08654 77054A77 77054A47
critical:  *** Stack trace:
 ***   RaiseException
 ***   CxxThrowException
 ***   RtlGetAppContainerNamedObjectPath
 ***   RtlGetAppContainerNamedObjectPath
 ***


critical:  *** Stack trace:
 ***   RaiseException
 ***   CxxThrowException
 ***   RtlGetAppContainerNamedObjectPath
 ***   RtlGetAppContainerNamedObjectPath
 ***

**Comment by fangpianqi** [comment] 2018-09-28 10:57
> Confirm this bug. I'm using Ubuntu 18.04 with GNOME.

same here.

**Comment by IMEVER** [comment] 2018-11-27 02:01
Same error with MailSpring 1.1.5 on Deepin Linux

**Comment by DanielRios549** [comment] 2019-02-21 11:42
Same here, it is not fixed 3 months later

**Comment by emersonvolkov** [comment] 2019-09-11 08:42
```sudo vim /etc/resolv.conf``` 

Add this 2 lines on top 

nameserver 8.8.8.8
nameserver 8.8.4.4

and try again.

**Comment by CodeMouse92** [comment] 2021-01-29 23:37
Duplicate of #397

**Closed by CodeMouse92** 2021-01-29 23:37 UTC
Labels: audit, needs-reproduction

**Comment by CodeMouse92** [comment] 2021-02-02 01:25
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/gmail-mailsync-134/422

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team
