### ISSUE TITLE
Returning archived messages 

### ISSUE THREAD

**Issue by dtokarczyk** [Foundry376/Mailspring#1589] opened 2019-07-25 12:15 UTC
**##### What operating system are you using?**
Ubuntu 19.04
**##### What version of Mailspring are you using?**
1.6.3.134a0e55
**##### Is this an email sync or connection issue?**
It is manage messages issue IMAP/SMTP option. 
**##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?**
Yes, the issue occurs only in SMTP/IMAP option. Precisely - home.pl, you resolved issues about connect with this provider #967 
**##### Is the issue reproducible with a particular attachment, message, signature, etc?**
I observe that when I adding a message to snooze, and that returns and then I want to add a message to archive, message return to inbox after some time. 

Edit:
Sometimes I observe that messages show in the inbox and fast hide (after sync). Another time, the same messages stay in inbox and I have to them to archive.

**Comment by CodeMouse92** [comment] 2021-02-08 21:15
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/disappearing-emails-desync/428

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-08 21:15 UTC
Labels: audit
