### ISSUE TITLE
[BUG] iCloud cannot sync even with app-specific password

### ISSUE THREAD

**Issue by yasithmilinda** [Foundry376/Mailspring#1491] opened 2019-05-07 22:15 UTC
## Issue
I've been trying to add my iCloud account to Mailspring in three different computers, all with app-specific passwords as advised in issues raised previously. However, i still could not get Mailspring to fetch my messages. The progress shows that it is syncing, but it does not go beyond 0%

## System Configuration
* OS - Ubuntu 19.04
* Mailspring - v1.6.1-aceed8e5
* Network - Stable and works fine for other tasks
* Account - iCloud

## Related Logs
```
26252 [2019-04-24 17:19:45.976] [main] [info] ------------- Starting Sync (****@icloud.com) ---------------
26252 [2019-04-24 17:19:45.982] [background] [info] Marking all folders as `busy`
26252 [2019-04-24 17:19:45.982] [background] [info] Syncing folder list...
26252 [2019-04-24 17:19:46.102] [metadata] [info] Metadata delta stream starting...
...
26252 [2019-04-24 20:32:08.945] [background] [info] Syncing folder list...
26252 [2019-04-24 20:32:09.966] [background] [info] syncFolderUIDRange for INBOX, UIDs: 1 - 2895, Heavy: true
26252 [2019-04-24 20:32:11.305] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID","key":"ErrorParse","retryable":true,"what":"std::exception"}
26252 [2019-04-24 20:34:03.334] [metadata] [info] Metadata delta stream closed.
26252 [2019-04-24 20:34:03.340] [metadata] [critical] 
 ***
 *** A JSON exception occurred during program execution: 
 *** [json.exception.type_error.316] invalid UTF-8 byte at index 0: 0xF8
 ***

26252 [2019-04-24 20:34:03.343] [metadata] [critical]  *** Stack trace:
 ***   clone
 ***
```

**Comment by yasithmilinda** [comment] 2019-05-07 22:20
I'm convinced that this error is due to 
```
[json.exception.type_error.316] invalid UTF-8 byte at index 0: 0xF8
```

any workaround for this?

**Comment by bengotow** [comment] 2019-05-26 19:31
Whoa! This is an interesting one - thanks for reporting it. It looks like that `[metadata]` error may actually be unrelated—it sounds like Mailspring is unable to connect to id.getmailspring.com to sync the metadata (snooze dates, send later times, etc.) that we sync to our servers to enable those features across installs. I think that the line above that is actually the interesting bit:

```

26252 [2019-04-24 20:32:11.305] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID","key":"ErrorParse","retryable":true,"what":"std::exception"}
```

Unfortunately that doesn't give many clues. I'll see if we can improve the error reporting in this particular case in the next release. If we can make it print the exact message or data range it's fetching, I think that'd help narrow this down.

**Comment by yasithmilinda** [comment] 2019-05-27 02:27
@bengotow You're welcome! Yes if you could update this thread when the error reporting is improved, I could attach the updated logs if the issue still persists.

**Comment by kadmonj** [comment] 2019-08-29 06:23
I have a similar problem with synching gmail.
os: Ubuntu 19.04
mailspring version: 1.6.3-134a0e55
gmail account.

The UI shows an error:

> Encountered error while syncing....

from the logs:
```
17136 [2019-08-28 23:08:22.367] [metadata] [critical]  *** Stack trace:
 ***   clone
 ***

17178 [2019-08-28 23:08:22.482] [main] [info] Identity created at 1566958133 - using ID Schema 1
17178 [2019-08-28 23:08:22.484] [main] [info] ------------- Starting Sync (kadmonj@gmail.com) ---------------
17178 [2019-08-28 23:08:22.486] [background] [info] Fetching XOAuth2 access token from Gmail for e3489d72
17178 [2019-08-28 23:08:22.487] [metadata] [info] Metadata delta stream starting...
17178 [2019-08-28 23:08:22.653] [background] [info] Marking all folders as `busy`
17178 [2019-08-28 23:08:22.655] [background] [info] Syncing folder list...
17178 [2019-08-28 23:08:23.990] [background] [info] Syncing folder list...
17178 [2019-08-28 23:08:24.387] [background] [info] syncFolderUIDRange for [Gmail]/All Mail, UIDs: 140832 - 143386, Heavy: false
17178 [2019-08-28 23:08:25.162] [background] [info] - remote=400, local=400
17178 [2019-08-28 23:08:25.442] [background] [info] syncFolderUIDRange for [Gmail]/Trash, UIDs: 1 - 45737, Heavy: false
17178 [2019-08-28 23:08:25.858] [background] [info] - remote=8, local=8
17178 [2019-08-28 23:08:25.860] [background] [info] Sync loop deleting unlinked messages with phase 2.
17178 [2019-08-28 23:08:25.894] [background] [info] Sync loop complete.
17178 [2019-08-28 23:08:26.331] [foreground] [info] syncFolderChangesViaCondstore - [Gmail]/All Mail: modseq 8049841 to 8049841, uidnext 143386 to 143386
17178 [2019-08-28 23:08:26.426] [foreground] [info] Idling on folder [Gmail]/All Mail
17178 [2019-08-28 23:08:37.489] [metadataExpiration] [info] Scanning for expired metadata
17178 [2019-08-28 23:08:37.489] [metadataExpiration] [info] -- Will wake for next expiration in 7200sec
17178 [2019-08-28 23:08:42.488] [metadata] [info] Metadata delta stream timed out.
17178 [2019-08-28 23:08:42.510] [metadata] [critical] 
 ***
 *** A JSON exception occurred during program execution: 
 *** [json.exception.type_error.316] invalid UTF-8 byte at index 0: 0xF8
 ***
```

Any updates or a solution for that?

**Comment by erodriguezv** [comment] 2019-09-17 16:55
I have the same issue: icloud with app specific password stuck at 0%.
I tried a manualt SMTP, IMAP config and I got the same resutlts.
OS: Linux Manjaro, GNOME.
Mailspring installed with snap.
Looks like the same error:
Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID","key":"ErrorParse","retryable":true,"what":"std::exception"}


Logs:
8741 [2019-09-17 11:36:14.524] [main] [info] Identity created at 1559805020 - using ID Schema 1
8741 [2019-09-17 11:36:14.526] [main] [info] ------------- Starting Sync (*********@me.com) ---------------
8741 [2019-09-17 11:36:14.528] [background] [info] Marking all folders as `busy`
8741 [2019-09-17 11:36:14.528] [background] [info] Syncing folder list...
8741 [2019-09-17 11:36:16.385] [background] [info] Syncing folder list...
8741 [2019-09-17 11:36:16.885] [background] [info] syncFolderUIDRange for INBOX, UIDs: 2884 - 3634, Heavy: true
8741 [2019-09-17 11:36:17.170] [metadata] [info] Metadata delta stream starting...
8741 [2019-09-17 11:36:18.056] [foreground] [info] Idling on folder INBOX
8741 [2019-09-17 11:36:19.237] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID","key":"ErrorParse","retryable":true,"what":"std::exception"}
8741 [2019-09-17 11:36:29.531] [metadataExpiration] [info] Scanning for expired metadata
8741 [2019-09-17 11:36:29.531] [metadataExpiration] [info] -- Will wake for next expiration in 7200sec
8741 [2019-09-17 11:38:19.237] [background] [info] Syncing folder list...
8741 [2019-09-17 11:38:21.250] [background] [info] syncFolderUIDRange for INBOX, UIDs: 2884 - 3634, Heavy: true
8741 [2019-09-17 11:38:23.686] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID","key":"ErrorParse","retryable":true,"what":"std::exception"}
8741 [2019-09-17 11:40:23.686] [background] [info] Syncing folder list...
8741 [2019-09-17 11:40:25.776] [background] [info] syncFolderUIDRange for INBOX, UIDs: 2884 - 3634, Heavy: true
8741 [2019-09-17 11:40:27.540] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID","key":"ErrorParse","retryable":true,"what":"std::exception"}
8741 [2019-09-17 11:42:27.540] [background] [info] Syncing folder list...
8741 [2019-09-17 11:42:29.734] [background] [info] syncFolderUIDRange for INBOX, UIDs: 2884 - 3634, Heavy: true
8741 [2019-09-17 11:42:31.621] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID","key":"ErrorParse","retryable":true,"what":"std::exception"}
8741 [2019-09-17 11:44:31.622] [background] [info] Syncing folder list...
8741 [2019-09-17 11:44:33.684] [background] [info] syncFolderUIDRange for INBOX, UIDs: 2884 - 3634, Heavy: true
8741 [2019-09-17 11:44:35.590] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID","key":"ErrorParse","retryable":true,"what":"std::exception"}
8741 [2019-09-17 11:46:35.591] [background] [info] Syncing folder list...
8741 [2019-09-17 11:46:37.696] [background] [info] syncFolderUIDRange for INBOX, UIDs: 2884 - 3634, Heavy: true
8741 [2019-09-17 11:46:39.576] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID","key":"ErrorParse","retryable":true,"what":"std::exception"}
8741 [2019-09-17 11:48:39.577] [background] [info] Syncing folder list...
8741 [2019-09-17 11:48:41.521] [background] [info] syncFolderUIDRange for INBOX, UIDs: 2884 - 3634, Heavy: true
8741 [2019-09-17 11:48:43.439] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID","key":"ErrorParse","retryable":true,"what":"std::exception"}

**Comment by bengotow** [comment] 2019-10-09 03:38
Hey folks - just a quick heads up that the `invalid UTF-8 byte at index 0: 0xF8` issue will be fixed in the next release.

**Closed** 2019-10-22 15:46 UTC
Labels: bug, done-pending-release

**Comment by ronnievv82** [comment] 2020-12-10 16:20
This is an issue that I am having with my main iCloud account. Are there any workarounds? It was working then stopped a few days ago.

**Comment by DkGr** [comment] 2021-04-23 08:43
Still have this issue... (MailSpring 1.9.1 on Windows 10)

**Comment by CodeMouse92** [comment] 2021-04-23 18:47
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

@DkGr: Can you please open a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team
