### ISSUE TITLE
[Feature Request] Allow emails to be signed with a certificate / private key

### ISSUE THREAD

**Issue by icf20** [Foundry376/Mailspring#28] opened 2017-10-04 22:34 UTC
hello i am interested in this feature ( nylas dint have  it) that allow to sign email with a government issues certificate signed by a root certificate(like this one https://www.sede.fnmt.gob.es/descargas/certificados-raiz-de-la-fnmt) for business representative.

are there any plans for something like this ?

**Comment by bengotow** [comment] 2017-10-05 06:02
Hey @icf20 — I actually hadn't heard of this but I think this would be a great feature.

Could you do me a favor and (if you can), send me an example of a signed email to `ben@foundry376.com`? That will help me understand exactly what the end result should look like and I can investigate adding it in the future.

Also, does the government or business provide any sort of tutorial or instructions for setting this up in your current client? I'd also be interested in seeing that, since I'd want to make Mailspring consistent with what you're already doing. Thanks!

**Comment by buildersbrewery** [comment] 2017-10-05 23:11
Looking at <https://www.nylas.com/blog/pgp/> Nylas used to support PGP, but Mailspring keeps adding these to the `config.json` any time I change a line:

```json
    "disabledPackages": [
        "message-view-on-github",
        "personal-level-indicators",
        "phishing-detection",
        "nylas-private-salesforce",
        "github-contact-card",
        "keybase",
        "composer-markdown",
        "composer-scheduler",
        "composer-mail-merge",
        "send-and-archive",
        "main-calendar"
      ]
```

**Comment by icf20** [comment] 2017-10-06 21:32
@bengotow  try the official repo https://github.com/ctt-gob-es

**Comment by jacboy** [comment] 2018-04-24 06:59
@bengotow Any news on this?

**Comment by beowuff** [comment] 2018-07-21 21:50
I also need pki S/MIME signing, which is what I think this request is about. I'd love to move off of Thunderbird, but this is a must have feature. :/

**Comment by victor-casas-sm** [comment] 2018-11-14 18:14
Pretty unuseful a email client without digital sign inserting capacity!

**Comment by beowuff** [comment] 2018-11-14 21:42
I've actually moved on from Thunderbird to kmail. Yep. Even kmail supports both pgp and pki certificate signing.

**Comment by cjpabloL** [comment] 2019-02-06 11:45
same here, I can't move from thunderbird without this feature.

**Comment by n-salvi** [comment] 2019-04-01 06:49
any progress on this?

**Comment by soumyajyotih** [comment] 2019-04-19 10:23
Any progress on the "digital signing" feature. Otherwise not worth it for me moving from thunderbird, or even pay for the pro features.

**Comment by albertonoys** [comment] 2019-07-05 13:56
This feature is the only one that keeps me from moving away from Thunderbird. Any news?

**Comment by agopu** [comment] 2020-02-17 15:25
This is the only feature that keeps me from using Mailspring for my email client needs. Please consider implementing this even if there's a nominal fee! Thanks!

**Comment by IngwiePhoenix** [comment] 2020-12-14 14:46
Would love this feature too! Interested in setting up my own email hosting off my own domain and adding signing and encryption to my emails to improve trust to my messages. :)

**Comment by CodeMouse92** [comment] 2021-01-18 21:41
Hey everyone,

This is something both @bengotow and I would love to see, but **we really need some members of the community to step up and help us implement this!**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/pgp-encryption-gpg-support-keybase/83

Please consider joining that community and continuing the discussion there!
We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-18 21:41 UTC
Labels: audit, enhancement
