### ISSUE TITLE
Feature Request: Tasks in calendar

### ISSUE THREAD

**Issue by GrigoriyMikhalkin** [Foundry376/Mailspring#1821] opened 2020-02-27 08:32 UTC
Hi! Is there plans to integrate Google Tasks into Calendar?

In Google Calendar web app, there's nice feature -- it displays tasks assigned for the day in it's header, like this:

![tasks](https://user-images.githubusercontent.com/3637857/75425933-b363ab80-5954-11ea-8913-206e6b72753a.png)

I'm very much missing that in Mailspring Calendar)

**Comment by CodeMouse92** [comment] 2021-02-26 20:48
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/task-support-in-calendar/844

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@GrigoriyMikhalkin: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-26 20:48 UTC
Labels: audit, enhancement
