### ISSUE TITLE
Composer uses up to 100% CPU with active spell checking

### ISSUE THREAD

**Issue by kakra** [Foundry376/Mailspring#1161] opened 2018-10-24 12:25 UTC
##### Are there any related issues?

I only found one issue about strange cursor movement in version 1.1.

##### What operating system are you using?

Gentoo Linux

##### What version of Mailspring are you using?

1.5.0

--

**Bug?**

##### Is this an email sync or connection issue?

Not a connection issue. Actually, this is symmetric 1 gbit/s here.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

This is not specific to some account type but I discovered it while using an O365 account.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

This issue becomes visible as the typed text becomes longer. After composing up to one or two pages worth of text, the composer uses more and more CPU resulting in very sluggish curcor movement and mouse navigation with this window, choking every few characters over multiple seconds. The rest of the system behaves normally. Only one core is used, the remaining CPU cores stay mostly idle. This also affects responsiveness of the Mailspring main window then but this is less visible.

**Comment by CodeMouse92** [comment] 2021-02-03 18:19
Duplicate of #927

**Closed by CodeMouse92** 2021-02-03 18:19 UTC
Labels: audit
