### ISSUE TITLE
[Feature Request] Make making subfolders more intuitive

### ISSUE THREAD

**Issue by psivesely** [Foundry376/Mailspring#1574] opened 2019-07-13 00:50 UTC
I had to look up how to create a new subfolder. Basic actions like this could be made more intuitive, so that they do not require looking up. Adding it under the right click menu when clicking on an existing folder seems like an intuitive solution, but I'm no UX designer.

**Comment by CodeMouse92** [comment] 2021-02-03 17:46
Thank you for reporting this. 2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/improve-folder-management/443

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-03 17:46 UTC
Labels: audit, enhancement
