### ISSUE TITLE
Snap auto startup

### ISSUE THREAD

**Issue by DanielRios549** [Foundry376/Mailspring#848] opened 2018-05-06 18:31 UTC
I have just installed snap version of Mailspring, and there is no option to "Launch on system startup", but, snap creates a symlink on /snap/bin/mailspring, which makes the same as /usr/bin/mailspring, that is, it opens the software. The option to auto start, can simply execute mailspring command , or even mailspring --background one, to auto start with the system.

OBS: This is specifically for snap version, the .deb version starts normally with the system (it has the option to make this under preferences).

**Comment by geddawi** [comment] 2019-06-27 12:39
June 2019, this has not been resolved. Any workarounds? Having the system execute `mailspring -background` still opens the GUI client

**Comment by DanielRios549** [comment] 2019-06-30 00:41
I think that if you copy the desktop file and place it in ~/.config/autostart, Mailspring will start automatically, but I end up using .deb version because it does not has this bug the theme bug that all snap apps have

**Comment by dastorm** [comment] 2020-01-08 21:08
Having the system execute `bash -c "mailspring -b"` at startup works for me with the snap version

**Comment by CodeMouse92** [comment] 2021-02-09 22:51
Based on the above, it appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-09 22:51 UTC
Labels: audit, bug, snapcraft
