### ISSUE TITLE
Feature Request: Option to view message without background theme

### ISSUE THREAD

**Issue by trylaarsdam** [Foundry376/Mailspring#2145] opened 2020-09-17 13:57 UTC
**Is your feature request related to a problem? Please describe.**
I've been getting more messages that when using dark theme are partially unreadable because of the dark theme in mailspring. Some messages (see screenshots at the bottom) are auto-formatted OK, but it'd still be nice for newsletters and other messages to have the default formatting.

**Describe the solution you'd like**
What would be great is if there was a way to view a message with a standard white background instead of the one in the theme, maybe in this drop down next to the reply button at the top of the email.
![image](https://user-images.githubusercontent.com/50586094/93480847-89a7ad00-f8c3-11ea-9130-bb92130f2d45.png)

**Describe alternatives you've considered**
My way around this issue has just been to change themes temporally. 

**Additional context**
Here's an example of what I mean:
**Standard/light theme**
![image](https://user-images.githubusercontent.com/50586094/93480964-aa700280-f8c3-11ea-97ce-f1ca223159e5.png)
**Dark theme**
![image](https://user-images.githubusercontent.com/50586094/93481027-bbb90f00-f8c3-11ea-83bc-bb68167453fc.png)

**Comment by CodeMouse92** [comment] 2021-03-03 02:37
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/dark-theme-on-message-optional-poor-text-rendering-in-dark-theme/886

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-03 02:37 UTC
Labels: audit, enhancement
