### ISSUE TITLE
Sync error with a Fastmail account

### ISSUE THREAD

**Issue by ay4** [Foundry376/Mailspring#2147] opened 2020-09-18 13:43 UTC
Hi, 

For several versions now I'm experiencing the same bug. Currently I am using Mailspring 1.7.8 and MacOS 10.14.6. 

When I add a Fastmail account, the first several syncs go well after which there's a recurrent sync error. I can fix it only if I delete the Fastmail account and then connect it again. Here is the error log:

Mailspring Version: 1.7.8-13635bcf
Platform: darwin
Account State: sync_error
Account Provider: fastmail
IMAP Server: imap.fastmail.com
SMTP Server: smtp.fastmail.com
--------------------------------------------
6198 [2020-09-18 16:34:53.677] [background] [info] syncFolderChangesViaCondstore - Drafts: modseq 725123 to 725123, uidnext 2705 to 2705
6198 [2020-09-18 16:34:53.810] [background] [info] syncFolderUIDRange for Archive, UIDs: 15986 - 20986, Heavy: true
6198 [2020-09-18 16:34:54.684] [foreground] [info] syncFolderChangesViaCondstore - INBOX: modseq 728123 to 728123, uidnext 7334 to 7334
6198 [2020-09-18 16:34:54.684] [foreground] [info] Idling on folder INBOX
6198 [2020-09-18 16:34:55.122] [background] [info] - remote=5001, local=4003
6198 [2020-09-18 16:34:55.279] [background] [critical] 
***
*** Mailspring Sync 
*** A JSON exception occurred during program execution: 
*** [json.exception.type_error.316] invalid UTF-8 byte at index 1: 0xBF
***

6198 [2020-09-18 16:34:55.897] [background] [critical] *** Stack trace (line numbers are approximate):
*** in mailsync  exceptions::logCurrentExceptionWithStackTrace()
*** in mailsync  runBackgroundSyncWorker()
*** in mailsync  main::$_6::operator()() const
*** in mailsync  void* __thread_proxy(void*)
*** in mailsync  thread_start()
***

6201 [2020-09-18 16:34:59.268] [main] [info] Identity created at 1536593504 - using ID Schema 1
6201 [2020-09-18 16:34:59.269] [main] [info] ------------- Starting Sync (dima@fastmail.co.uk) ---------------
6201 [2020-09-18 16:34:59.279] [metadata] [info] Metadata delta stream starting...
6201 [2020-09-18 16:35:03.282] [background] [info] Marking all folders as `busy`
6201 [2020-09-18 16:35:03.287] [background] [info] Syncing folder list...
6201 [2020-09-18 16:35:05.171] [background] [info] Syncing folder list...
6201 [2020-09-18 16:35:05.438] [background] [info] syncFolderChangesViaCondstore - INBOX: modseq 728123 to 728123, uidnext 7334 to 7334
6201 [2020-09-18 16:35:05.574] [background] [info] syncFolderChangesViaCondstore - Sent: modseq 726492 to 726492, uidnext 23368 to 23368
6201 [2020-09-18 16:35:05.719] [background] [info] syncFolderChangesViaCondstore - Drafts: modseq 725123 to 725123, uidnext 2705 to 2705
6201 [2020-09-18 16:35:05.848] [background] [info] syncFolderUIDRange for Archive, UIDs: 15986 - 20986, Heavy: true
6201 [2020-09-18 16:35:06.472] [foreground] [info] syncFolderChangesViaCondstore - INBOX: modseq 728123 to 728123, uidnext 7334 to 7334
6201 [2020-09-18 16:35:06.472] [foreground] [info] Idling on folder INBOX
6201 [2020-09-18 16:35:07.050] [background] [info] - remote=5001, local=4003
6201 [2020-09-18 16:35:07.202] [background] [critical] 
***
*** Mailspring Sync 
*** A JSON exception occurred during program execution: 
*** [json.exception.type_error.316] invalid UTF-8 byte at index 1: 0xBF
***

6201 [2020-09-18 16:35:07.436] [background] [critical] *** Stack trace (line numbers are approximate):
*** in mailsync  exceptions::logCurrentExceptionWithStackTrace()
*** in mailsync  runBackgroundSyncWorker()
*** in mailsync  main::$_6::operator()() const
*** in mailsync  void* __thread_proxy(void*)
*** in mailsync  thread_start()
***

**Comment by ay4** [comment] 2020-10-06 09:08
Just to add something here: if Mailspring is relaunched, the first sync (or maybe several) go fine; but after a minute a two the abovementioned error starts to show up

**Comment by CodeMouse92** [comment] 2021-01-28 04:10
Thank you for reporting this. 2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/sync-error-with-a-fastmail-account/337

Please consider joining that community and continuing the discussion there!

@ay4: if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 04:10 UTC
Labels: audit, bug
