### ISSUE TITLE
Unable to connect to Yandex mail

### ISSUE THREAD

**Issue by vbitner87** [Foundry376/Mailspring#712] opened 2018-02-20 10:07 UTC
Mail connection is described here:
https://yandex.com/support/mail/mail-clients.html

Mailspring error is the following:
Account is missing required fields:imap_allow_insecure_ssl

The error occurs during account set up.

**Comment by matthieujoossen** [comment] 2018-02-24 12:29
Same problem with 1and1 server.

I am using Ubuntu 17.10 and mailspring snap app.
My account set up is ok (I'm using it with mailspring with another computer)

![mailspring_error](https://user-images.githubusercontent.com/6122330/36630429-8e915314-1966-11e8-83b3-a217bf277f3c.png)

**Comment by bengotow** [comment] 2018-02-26 19:55
Hey - thanks for filing this, I'll see if I can reproduce this and let you know if I narrow it down.

**Comment by bengotow** [comment] 2018-02-26 20:00
Hey folks—can you confirm you're using the latest version of Mailspring (1.1.4)? I was able to go through account setup with a yandex test account without seeing that error and I'm not sure how it could be possible looking at the code. This was an issue with an older release though.

**Comment by Dudo1985** [comment] 2018-02-26 20:49
Hello, I've same situation (last version of mailspring, 1.1.4) using a custom impa/smtp settings
![schermata del 2018-02-26 21-49-36](https://user-images.githubusercontent.com/5710734/36694539-fa5cf632-1b3e-11e8-951e-097cafe08210.png)

**Comment by Dudo1985** [comment] 2018-02-26 20:53
Further this, if I try to connect, I got this:

An unexpected mailsync error occurred (134)

this is the error log


Waiting for Account JSON:

Waiting for Identity JSON:
info: Identity created at 1514557442 - using ID Schema 0
critical: 
 ***
 *** A JSON exception occurred during program execution: 
 *** [json.exception.type_error.302] type must be string, but is null
 ***

critical: 
 ***
 *** A JSON exception occurred during program execution: 
 *** [json.exception.type_error.302] type must be string, but is null
 ***

critical:  *** Stack trace (line numbers are approximate):
 *** ??:?  void nlohmann::detail::from_json(nlohmann::basic_json const&, nlohmann::basic_json::string_t&)
 *** ??:?  decltype ((from_json({parm#1}, {parm#2})),((void)())) nlohmann::detail::from_json_fn::call(nlohmann::basic_json const&, string&, nlohmann::detail::priority_tag) const
 *** ??:?  void nlohmann::detail::from_json_fn::operator()(nlohmann::basic_json const&, string&) const
 *** ??:?  void nlohmann::adl_serializer::from_json(nlohmann::basic_json const&, string&)
 *** ??:?  string nlohmann::basic_json::get() const
 *** ??:?  Account::IMAPSecurity()
 *** ??:?  MailUtils::configureSessionForAccount(mailcore::IMAPSession&, shared_ptr)
 *** ??:?  runTestAuth(shared_ptr)
 *** ??:?  main
 ***

critical:  *** Stack trace (line numbers are approximate):
 *** ??:?  void nlohmann::detail::from_json(nlohmann::basic_json const&, nlohmann::basic_json::string_t&)
 *** ??:?  decltype ((from_json({parm#1}, {parm#2})),((void)())) nlohmann::detail::from_json_fn::call(nlohmann::basic_json const&, string&, nlohmann::detail::priority_tag) const
 *** ??:?  void nlohmann::detail::from_json_fn::operator()(nlohmann::basic_json const&, string&) const
 *** ??:?  void nlohmann::adl_serializer::from_json(nlohmann::basic_json const&, string&)
 *** ??:?  string nlohmann::basic_json::get() const
 *** ??:?  Account::IMAPSecurity()
 *** ??:?  MailUtils::configureSessionForAccount(mailcore::IMAPSession&, shared_ptr)
 *** ??:?  runTestAuth(shared_ptr)
 *** ??:?  main
 ***

/usr/share/mailspring/resources/app.asar.unpacked/mailsync: line 4:  3671 Aborted                 (core dumped) SASL_PATH="$(dirname $(realpath $0))" LD_LIBRARY_PATH="$(dirname $(realpath $0));$LD_LIBRARY_PATH" "$(dirname $0)/mailsync.bin" "$@"

**Comment by vbitner87** [comment] 2018-02-27 17:48
https://github.com/Foundry376/Mailspring/issues/712#issuecomment-368630638

Mailsping version is 1.1.4

Small workaround:
- check "Allow insecure SSL" in both sections
- press button "connect account"
- uncheck  "Allow insecure SSL"

After that the original error disappears. However another one occurs:
___An unexpected mailsync error occurred (134)___

![image](https://user-images.githubusercontent.com/3747439/36745048-6dc7c870-1bff-11e8-92bd-56b8786887c9.png)


```
Waiting for Account JSON:

Waiting for Identity JSON:
info: Identity created at 1518966295 - using ID Schema 1
critical: 
 ***
 *** A JSON exception occurred during program execution: 
 *** [json.exception.type_error.302] type must be string, but is null
 ***

critical: 
 ***
 *** A JSON exception occurred during program execution: 
 *** [json.exception.type_error.302] type must be string, but is null
 ***

critical:  *** Stack trace (line numbers are approximate):
 *** ??:?  void nlohmann::detail::from_json(nlohmann::basic_json const&, nlohmann::basic_json::string_t&)
 *** ??:?  decltype ((from_json({parm#1}, {parm#2})),((void)())) nlohmann::detail::from_json_fn::call(nlohmann::basic_json const&, string&, nlohmann::detail::priority_tag) const
 *** ??:?  void nlohmann::detail::from_json_fn::operator()(nlohmann::basic_json const&, string&) const
 *** ??:?  void nlohmann::adl_serializer::from_json(nlohmann::basic_json const&, string&)
 *** ??:?  string nlohmann::basic_json::get() const
 *** ??:?  Account::SMTPSecurity()
 *** ??:?  MailUtils::configureSessionForAccount(mailcore::SMTPSession&, shared_ptr)
 *** ??:?  runTestAuth(shared_ptr)
 *** ??:?  main
 ***

critical:  *** Stack trace (line numbers are approximate):
 *** ??:?  void nlohmann::detail::from_json(nlohmann::basic_json const&, nlohmann::basic_json::string_t&)
 *** ??:?  decltype ((from_json({parm#1}, {parm#2})),((void)())) nlohmann::detail::from_json_fn::call(nlohmann::basic_json const&, string&, nlohmann::detail::priority_tag) const
 *** ??:?  void nlohmann::detail::from_json_fn::operator()(nlohmann::basic_json const&, string&) const
 *** ??:?  void nlohmann::adl_serializer::from_json(nlohmann::basic_json const&, string&)
 *** ??:?  string nlohmann::basic_json::get() const
 *** ??:?  Account::SMTPSecurity()
 *** ??:?  MailUtils::configureSessionForAccount(mailcore::SMTPSession&, shared_ptr)
 *** ??:?  runTestAuth(shared_ptr)
 *** ??:?  main
 ***

/usr/share/mailspring/resources/app.asar.unpacked/mailsync: line 4: 28984 Aborted                 (core dumped) SASL_PATH="$(dirname $(realpath $0))" LD_LIBRARY_PATH="$(dirname $(realpath $0));$LD_LIBRARY_PATH" "$(dirname $0)/mailsync.bin" "$@"
```

**Comment by visagegod** [comment] 2018-02-28 10:25
Getting the same exact error as described by vbitner87 with 'zoho.eu' account.

**Comment by aditiapratama** [comment] 2018-03-01 11:02
I got the same error as @vbitner87

**Comment by roboto-cloud** [comment] 2018-03-01 21:02
Here the same error...

own SMTP IMAP server

**Comment by Donald3d** [comment] 2018-03-04 19:06
Same problem here

**Comment by joaofar** [comment] 2018-03-05 01:06
Me also

**Comment by Donald3d** [comment] 2018-03-05 04:30
I noticed using an unsecure option from webmail client setup of my domain worked fine , the problem is with secure connections

**Comment by jaccoh** [comment] 2018-03-05 14:00
same issue here.. using the snap most recent version of mailspring.. super annoying

**Comment by visagegod** [comment] 2018-03-06 09:38
Is this only an issue for mac users?

**Comment by jaccoh** [comment] 2018-03-06 09:47
I had it using snap/Ubuntu

**Comment by roboto-cloud** [comment] 2018-03-06 09:56
debian

**Comment by joaofar** [comment] 2018-03-06 13:00
windows here

**Comment by flavioballabeni** [comment] 2018-03-06 15:10
Ubuntu Trusty

**Comment by CookedApps** [comment] 2018-03-06 22:41
Windows 10 and Linux Mint

**Comment by roboto-cloud** [comment] 2018-03-08 21:48
with the last version
**1.1.5-5834c99f**
it's work on:
**Linux deb 4.14.0-3-amd64 #1 SMP Debian 4.14.17-1 (2018-02-14) x86_64 GNU/Linux**

**Comment by ovgeorge** [comment] 2018-09-25 19:47
Same problem on Mac with 1.4.2 version. In syncs only inbox.

**Comment by Kriger** [comment] 2019-12-30 00:15
Hi guys! I think I've found a solution to the problem: to get access to yandex mail with your custom domain you must use **app passwords** (in russian: пароли приложений). Just create new app password and enter it in the password field. In any case, it helped me

**Comment by gui-com-pt** [comment] 2020-09-16 07:31
> Hi guys! I think I've found a solution to the problem: to get access to yandex mail with your custom domain you must use **app passwords** (in russian: пароли приложений). Just create new app password and enter it in the password field. In any case, it helped me

You can also authenticate using the Portal Password (your regular password) without setting up the App Password. Go to **Mail → All settings → Email clients** and enable **Portal password** at **IMAP authorization method**.

**Comment by CodeMouse92** [comment] 2021-01-28 18:18
It appears that this issue has been resolved, so we are closing it. If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 18:18 UTC
Labels: audit, needs-reproduction
