### ISSUE TITLE
performance hit using Cinnamon DT/Ubuntu 16.04

### ISSUE THREAD

**Issue by ghost** [Foundry376/Mailspring#771] opened 2018-03-19 20:42 UTC
Haven't seen anything posted about this yet so, here you go...

I just changed my desktop over from gnome to cinnamon (2.8.6) under Ubuntu 16.04.04.

I noticed a significant change in overall system responsiveness under Cinnamon than I did with Gnome so looking closer at the process table, I see that Mailspring (1.1.5) is consuming a lot of cycles when at-rest and in a steady-state. 

This is a dev laptop and runs a lot of stuffs so I'm used to having my sys-load up over 1, but never over 3 like I am getting with the combination of the new desktop and Mailspring.  (I switched b/c Gnome just wasn't being that stable...)

I'm including a few htop screenies showing:
13.23.33:  no mailspring (system at-rest)
13.24.58:  mailspring started, idling
13.25.49:  maiilspring being used; sent an email

What's interesting to note is the interaction with Cinnamon - as I write this, Cinnamon is parked at around 10-13% of CPU utilization.

Once I start interacting (switch desktops, raising apps, etc.) it rises to about 19%...

After starting Mailspring and allowing Mailspring to settle, CPU use of Cinnamon has jumped to about 40% of CPU while Mailspring is consuming collectively about 43%.

After using Mailspring (switch emails, compose and send), Cinnamon maintains at around 40% and Mailspring maintains around 43%.

But overall system load is up to 3.3 nearly tripling.

Again, wasn't seeing these CPU/System levels at all under Gnome DT.  This is my first day running Cinnamon and I've had to stop Mailspring (opening occasionally before completely closing again) in order to enjoy normal levels of machine performance.

I've since stopped-started Mailspring many times, keeping an eye each time of resource consumption and Mailspring appears to be consistent in terms of amount of resources consumed also, leaving me to wonder, what's strange about the Cinnamon desktop that's causing both processes to spike...

Anyway, hope this is of some use...

--mike

 
![screenshot from 2018-03-19 13-25-49](https://user-images.githubusercontent.com/798582/37621035-14461b04-2b7b-11e8-9919-cd0708e01b78.png)
![screenshot from 2018-03-19 13-24-58](https://user-images.githubusercontent.com/798582/37621036-147c3112-2b7b-11e8-8e82-5fa139de584c.png)
![screenshot from 2018-03-19 13-23-33](https://user-images.githubusercontent.com/798582/37621037-149b7bf8-2b7b-11e8-8055-f00949ecdfb8.png)

**Comment by bengotow** [comment] 2018-03-19 20:49
Hmm thanks for the detailed writeup - this is definitely interesting. I wonder if Slack / VSCode / other Electron apps are displaying the same behavior? Another possibility is that something like updating the tray icon is very, very expensive in cinnamon, but it's hard to imagine it taking that much CPU...

**Comment by mshallop** [comment] 2018-03-19 22:22
I'm also running slack desktop - it's a staple for work so it's always active...without Mailspring running, slack appears a couple times as shown in the screenie...
![screenshot from 2018-03-19 15-22-31](https://user-images.githubusercontent.com/798582/37625500-5d5f37ae-2b89-11e8-8658-e9afb04fc343.png)

**Comment by mshallop** [comment] 2018-03-22 15:25
fwiw - I'm also seeing the same behavior in KDE.  This is a screenie from my desktop this morning -- the system's been idle all night...

![mailspring3](https://user-images.githubusercontent.com/798582/37779758-6b4dd4ce-2daa-11e8-911d-f4974ffb2c9b.png)

**Comment by CodeMouse92** [comment] 2021-03-02 18:07
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/mailspring-has-high-cpu-usage/87

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 18:07 UTC
Labels: linux, needs-reproduction
