### ISSUE TITLE
Feature Request:  Add squares to "select all" on page and option to do same when searching.

### ISSUE THREAD

**Issue by famewolf** [Foundry376/Mailspring#2174] opened 2020-10-21 17:29 UTC
Gmail currently allows you to select a top checkbox which either checks all the emails on page or unchecks them depending on their current state.  Additionally when filtering based on a search and you use that checkbox gmail gives you the option to "select all mail which matches" allowing you to do mass deletes of things like deal alerts, promotional emails etc which can build up over time.   I'd like to be able to do it in mailspring and not have to go to gmail web to accomplish it.

![image](https://user-images.githubusercontent.com/4558832/96755975-65972a00-13a1-11eb-8732-2677cd3f5801.png)

**Comment by CodeMouse92** [comment] 2021-03-03 03:27
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/add-squares-to-select-all-on-page-and-option-to-do-same-when-searching/960

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@famewolf: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-03 03:27 UTC
Labels: audit, enhancement
