### ISSUE TITLE
Bug: Chinese Inputer not compatible

### ISSUE THREAD

**Issue by Ariczh** [Foundry376/Mailspring#1984] opened 2020-05-14 04:38 UTC
**Describe the bug**
While Inputing Chinese with a high speed by Microsoft Pinyin Inputer, the last letter will cover front. It usually reproduce in reply mail.

**To Reproduce**
1. Open a mail
2. Click on reply
3. Switch to Microsoft Pinyin Inputer (Pre-Installed in windows 10)
3. Input a few words with high speed. (etc. dameixingchuanpuwang)
4. See error.

**Expected behavior**
Some of inputted words be covered with last input word.

**Screenshots**
![screensnap](https://www.dage1st.com/download/pics/all.gif)

**Setup: (please complete the following information):**
 - OS: Microsoft Windows 10 Pro
 - OS Version 1903(18362.720)
 - Mailspring Version: ex: 1.7.6

**Additional context** 
inputed this Issue in a poor english. LOL.

**Comment by CodeMouse92** [comment] 2021-02-23 22:06
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/chinese-inputer-not-compatible/745

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@Ariczh: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-23 22:06 UTC
Labels: audit, bug
