### ISSUE TITLE
[Feature Request] Sync / Export / Import Settings

### ISSUE THREAD

**Issue by Steppschuh** [Foundry376/Mailspring#1043] opened 2018-08-24 14:04 UTC
I'm looking for a new mail client as Newton is shutting down. One of the key features for me was that I didn't need to setup my accounts (including Gmail, Exchange and IMAP - 9 in total) on all my devices (which change often).

I would like to be able to export settings, including the following, to a file (e.g. JSON) and import it on a different device:

- Preferences
- Accounts
- Rules
- Signatures
- Templates

**Comment by jocksdev** [comment] 2018-09-05 12:16
+1

**Comment by Southclaws** [comment] 2018-09-08 08:41
Just installed on my other laptop and was very surprised to not simply load up all my mail accounts and settings. Would love to see this feature added to make it truly a cross-platform solution.

**Comment by joshtwo** [comment] 2019-01-26 04:49
I wrote well over a hundred rules for one of my email accounts on Mailspring before buying a new laptop, and I was shocked to realize none of my accounts or settings were attached to my Mailspring account when I installed it on here. I'm shocked that this wasn't part of the reason we had a Mailspring account in the first place.

**Comment by belgacea** [comment] 2019-05-03 14:59
Still no news about this ? Does anyone know if it's planned already ? 
This is a major feature..

**Comment by sn3h** [comment] 2019-05-16 18:59
+1

**Comment by covelus** [comment] 2019-05-31 08:32
My suggestion: if you could do it in the way that it can be automated (as through a BASH and PowerShell script, callable from Ansible), much better.

My use case (which is uncommon, but I guess not that weird):

Using mainly with Cloud tools and Ansible, I need to do:
1. From 1 single Virtual Machine template (as Ubuntu Linux Desktop or Windows), I need to deploy several VMs for training workshops, which include several generic but **different** student users.
2. after the VMs are deployed, I automatically deploy software, including email clients **for different mail accounts** (not the same, that would be easy just including in the template VM), and configure them. 
3. Issue: I could not find the way to auto-configure these several different email clients (we are not using auto-discovery e-mail servers, as Exchange). 
4. I am testing moving Mainspring config files (easy doable with Ansible), but not very successful.

What I would need is to **be able to export an email client account profile, even manually, and then be able to import it automatically using Ansible**. 
A case: running a script to import it (BASH/Powershell, depending on the system).
A related but independent Mailspring tool to import could be useful, or running Mailspring a first time with some configuration-import parameter.

After that, I could even develop an Ansible module for Mailspring, which probably would make your tool more attractive for advanced users/sysadmins.

Thank you very much

**Comment by FancyBanana** [comment] 2019-06-03 19:19
Any news on this feature? I have windows and linux installations and it's a pain in the ass to sync settings between them.

**Comment by jtguzman** [comment] 2019-06-04 21:14
I bought a subscription just because it seemed it would sync email preferences between my computers.
It seems this is not possible. Is there any config file that could be copied?

**Comment by pavel-the-best** [comment] 2019-07-31 10:37
Seems like mailspring id is only used to collect our personal data.

**Comment by jizongFox** [comment] 2019-09-28 14:46
I hope this feature can be added soon.

**Comment by MarcBollmann** [comment] 2020-01-31 19:38
This would be awesome or some kind of Account syncing.

**Comment by tukusejssirs** [comment] 2020-03-01 17:10
A workaround on Linux: I always back up the `~/.config/Mailspring` folder (with the exception of the folders below) on a machine where I have everything configured, install Mailspring on another machine, restore the above-mentioned folder and run Mailspring – everything is set up the way it was on the other machine.
- `Mailspring/GPUCache/`;
- `Mailspring/edgehill.db*`;
- `Mailspring/files/`;
- `Mailspring/Local Storage/`;
- `Mailspring/Singleton*`;
- `Mailspring/SS`;
- `mailsync-*.log*`;
- `saved-telemetry-pings/`.

**Comment by kinduff** [comment] 2020-04-12 19:32
Well this sucks, what's the point of forcing a Mailspring account if this is not a feature?

**Comment by campfred** [comment] 2020-04-12 19:37
Damm. I thought it was used for settings sync. That's a bummer. It would have been THE alternative email client. :/

**Comment by vasanthdeveloper** [comment] 2020-05-24 12:41
And it is really rude that no one from the official developers is interested in even having a conversation about this issue. :unamused:

**Comment by gaui** [comment] 2020-07-15 14:46
Shocking this is not a feature. :disappointed:

**Comment by gaui** [comment] 2020-07-15 14:58
I did the following...

 ```bash
cd ~/snap/mailspring/common
sftp 192.168.1.13
sftp> cd ~/snap/mailspring/common
get -R .
```

**Comment by samtuke** [comment] 2020-08-27 15:47
Also missing this feature

**Comment by CodeMouse92** [comment] 2021-01-28 01:25
Thank you for your patience. This has been under consideration for a while, but Mailspring is primarily the independent work of one developer (who has a full time job besides). GitHub Issues has always been a bit full — often of edge-case bug reports, wishlist feature requests, and questions — making it difficult to find and respond to specific things with limited development time.

On top of that, 2020 prevented much development work on Mailspring, but rest assured, development has resumed!

This feature is once again under consideration, although there are quite a few bigger fish to fry first!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/sync-templates-signatures-accounts-etc-accross-multiple-devices/265

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 01:25 UTC
Labels: audit
