### ISSUE TITLE
Can't print to PDF

### ISSUE THREAD

**Issue by lucaspon** [Foundry376/Mailspring#1027] opened 2018-08-14 13:49 UTC
##### Are there any related issues?

No

##### What operating system are you using?

Windows 10

##### What version of Mailspring are you using?

1.4.1 - b1028ad4

--

**Bug?**

Can't print e-mails do PDF using microsoft print to PDF.
It asks for a file name but, upon clicking "Save", the dialog just disappears and no file is generated.

##### Is this an email sync or connection issue?

No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No

--

**Comment by qnox81** [comment] 2018-09-28 11:04
I second this issue - same situation in my 1.4.2 release.

**Comment by iaz3** [comment] 2018-10-22 22:58
As of the latest update i was able to print an email, so this may have been fixed, or a coincidence.(The last version worked intermittently before breaking entirely, so it may be a fluke that it worked)

**Comment by TeamKinetic** [comment] 2018-11-15 09:33
Windows 10 same here..no bytes sent to either the PDF file generator or print spool

1.5.2

**Comment by bengotow** [comment] 2018-12-30 00:59
Hey folks—thanks for reporting this. Mailspring 1.5.4 shipped earlier today and should address this issue. It turned out to be a combination of things - an Electron-level printing bug and also empty print jobs caused by Mailspring closing the window immediately after the print dialog was closed. In addition to fixing these, 1.5.4 adds a new "Save as PDF" option beside the "Print" option in the print window, making it easy to export emails as well. Enjoy!

**Closed by bengotow** 2018-12-30 00:59 UTC
Labels: done-pending-release, windows

**Comment by macrophone** [comment] 2022-01-11 13:00
Hi. Still affected by this bug : 
The "Save as PDF" button open a dialog window, once "Save" is clicked, the dialog closes and no pdf file is generated. 
Mailspring 1.9.2, snap package, Linux Debian 11

**Comment by Phylu** [comment] 2022-01-11 21:10
@macrophone Please check, if this is the following issue: https://community.getmailspring.com/t/pdf-printing-broken/1750/12

We do not track bugs at GitHub anymore, but on the Mailspring Community Discourse instead.
