### ISSUE TITLE
Delete and archive message shortcuts

### ISSUE THREAD

**Issue by mat-m** [Foundry376/Mailspring#1763] opened 2020-01-09 22:44 UTC
##### Are there any related issues?

Nothing matches

##### What operating system are you using?

Linux Mint 19.3

##### What version of Mailspring are you using?

1.7.2

------

**Bug?**

Here is my keymap.json (custom from Outlook defaults)

```
{
  "application:new-message": "c",
  "core:archive-item": "y",
  "core:remove-and-previous": "backspace",
  "core:remove-and-next": "del",
  "core:star-item": "ins",
  "core:remove-from-view": "y"
}
```

`backspace` and `del`   have no effect to delete the message and move the cursor (`del` worked when used for `core:archive-item` as default).

Did I misinterpret the commands ?
Can anyone reproduce ?

**Comment by CodeMouse92** [comment] 2021-02-12 21:34
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/delete-and-archive-message-shortcuts/593

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@mat-m: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-12 21:34 UTC
Labels: audit
