### ISSUE TITLE
IMAP/SMTP account not receiving emails after upgrading to 1.0.11

### ISSUE THREAD

**Issue by alechko** [Foundry376/Mailspring#475] opened 2017-12-24 06:14 UTC
##### What operating system are you using?
debian jessie

##### What version of Mailspring are you using?
1.0.11

--

**Bug?**
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
zoho mail

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Screenshots provided with comparison between thunderbird and mailspring with the same inbox of the same account.
![image](https://user-images.githubusercontent.com/1391846/34324608-eaf2c6dc-e870-11e7-9e17-9ee139eb3d6c.png)
![image](https://user-images.githubusercontent.com/1391846/34324609-f1dbe348-e870-11e7-9fb4-1a450f114877.png)

--
Mailsync log
```
10364 [2017-12-24 06:12:07.976] [background] [info] Syncing folder list...
10364 [2017-12-24 06:12:08.413] [background] [info] syncFolderUIDRange - (INBOX, UIDs: 1 - 0, Heavy: false)
10364 [2017-12-24 06:12:08.853] [background] [error] syncFolderUIDRange - Fetching full headers for 4
10364 [2017-12-24 06:12:09.066] [background] [info] 🔸 Updating message 25=328 with subject: No Subject
10364 [2017-12-24 06:12:09.069] [background] [info] 🔸 Updating message 328=327 with subject: No Subject
10364 [2017-12-24 06:12:09.071] [background] [info] 🔸 Updating message 327=326 with subject: No Subject
10364 [2017-12-24 06:12:09.073] [background] [info] 🔸 Updating message 326=325 with subject: No Subject
10364 [2017-12-24 06:12:09.291] [background] [info] syncFolderUIDRange - (Sent, UIDs: 1 - 0, Heavy: false)
10364 [2017-12-24 06:12:09.720] [background] [error] syncFolderUIDRange - Fetching full headers for 20
10364 [2017-12-24 06:12:09.933] [background] [info] 🔸 Updating message 325=62 with subject: No Subject
10364 [2017-12-24 06:12:09.935] [background] [info] 🔸 Updating message 62=60 with subject: No Subject
10364 [2017-12-24 06:12:09.937] [background] [info] 🔸 Updating message 60=56 with subject: No Subject
10364 [2017-12-24 06:12:09.939] [background] [info] 🔸 Updating message 56=50 with subject: No Subject
10364 [2017-12-24 06:12:10.142] [background] [info] 🔸 Updating message 50=48 with subject: No Subject
10364 [2017-12-24 06:12:10.184] [background] [info] 🔸 Updating message 48=44 with subject: No Subject
10364 [2017-12-24 06:12:10.186] [background] [info] 🔸 Updating message 44=42 with subject: No Subject
10364 [2017-12-24 06:12:10.188] [background] [info] 🔸 Updating message 42=40 with subject: No Subject
10364 [2017-12-24 06:12:10.190] [background] [info] 🔸 Updating message 40=38 with subject: No Subject
10364 [2017-12-24 06:12:10.191] [background] [info] 🔸 Updating message 38=36 with subject: No Subject
10364 [2017-12-24 06:12:10.193] [background] [info] 🔸 Updating message 36=34 with subject: No Subject
10364 [2017-12-24 06:12:10.195] [background] [info] 🔸 Updating message 34=32 with subject: No Subject
10364 [2017-12-24 06:12:10.196] [background] [info] 🔸 Updating message 32=30 with subject: No Subject
10364 [2017-12-24 06:12:10.198] [background] [info] 🔸 Updating message 30=28 with subject: No Subject
10364 [2017-12-24 06:12:10.199] [background] [info] 🔸 Updating message 28=24 with subject: No Subject
10364 [2017-12-24 06:12:10.200] [background] [info] 🔸 Updating message 24=22 with subject: No Subject
10364 [2017-12-24 06:12:10.202] [background] [info] 🔸 Updating message 22=14 with subject: No Subject
10364 [2017-12-24 06:12:10.203] [background] [info] 🔸 Updating message 14=11 with subject: No Subject
10364 [2017-12-24 06:12:10.205] [background] [info] 🔸 Updating message 11=9 with subject: No Subject
10364 [2017-12-24 06:12:10.206] [background] [info] 🔸 Updating message 9=7 with subject: No Subject
10364 [2017-12-24 06:12:10.421] [background] [info] syncFolderUIDRange - (Drafts, UIDs: 1 - 0, Heavy: false)
10364 [2017-12-24 06:12:11.059] [background] [info] syncFolderUIDRange - (Archives, UIDs: 1 - 0, Heavy: false)
10364 [2017-12-24 06:12:11.708] [background] [info] syncFolderUIDRange - (Trash, UIDs: 1 - 0, Heavy: false)
10364 [2017-12-24 06:12:12.135] [background] [error] syncFolderUIDRange - Fetching full headers for 1
10364 [2017-12-24 06:12:12.346] [background] [info] 🔸 Updating message 7=59 with subject: No Subject
10364 [2017-12-24 06:12:12.561] [background] [info] syncFolderUIDRange - (Spam, UIDs: 1 - 0, Heavy: false)
10364 [2017-12-24 06:12:12.987] [background] [error] syncFolderUIDRange - Fetching full headers for 1
10364 [2017-12-24 06:12:13.199] [background] [info] 🔸 Updating message 59=25 with subject: No Subject
10364 [2017-12-24 06:12:13.415] [background] [info] syncFolderUIDRange - (Templates, UIDs: 1 - 0, Heavy: false)
10364 [2017-12-24 06:12:14.056] [background] [info] syncFolderUIDRange - (Archives/2017, UIDs: 1 - 0, Heavy: false)
10364 [2017-12-24 06:12:14.697] [background] [info] syncFolderUIDRange - (SF Community, UIDs: 1 - 0, Heavy: false)
10364 [2017-12-24 06:12:15.341] [background] [info] syncFolderUIDRange - (Code Scans, UIDs: 1 - 0, Heavy: false)
10364 [2017-12-24 06:12:15.983] [background] [info] syncFolderUIDRange - (Billing, UIDs: 1 - 0, Heavy: false)
10364 [2017-12-24 06:12:16.623] [background] [info] syncFolderUIDRange - ([Mailspring], UIDs: 1 - 0, Heavy: false)
10364 [2017-12-24 06:12:17.262] [background] [info] syncFolderUIDRange - ([Mailspring]/Snoozed, UIDs: 1 - 0, Heavy: false)
10364 [2017-12-24 06:12:17.768] [background] [info] Sync loop deleting unlinked messages with phase 1.
10364 [2017-12-24 06:12:17.769] [background] [info] Sync loop complete.
```

**Comment by sinnlosername** [comment] 2017-12-26 22:52
Same for me

**Comment by nhf-zaki** [comment] 2017-12-27 10:24
same issue happened while using zoho mail

**Comment by snqlby** [comment] 2017-12-27 10:33
I had the same problem twice last week. I just clear mail cache and it works fine.

**Comment by nhf-zaki** [comment] 2017-12-27 20:14
every time I have to clear mail cache to get new mails. what should be the way around to fix this?

**Comment by sinnlosername** [comment] 2017-12-28 04:50
I've got an old version of mailspring 1.0.6 from the 27.10.17. If you want, I can share it to you, so you'll be able to use Mailspring until it's fixed.

**Comment by nhf-zaki** [comment] 2017-12-28 04:56
@sinnlosername Please share the older version 1.0.6. Thanks in advance.

**Comment by sinnlosername** [comment] 2017-12-28 05:10
There you go. https://nofile.io/f/76nmnFmn7zD/MailspringSetup.exe
The password is: a7fe19c1

**Comment by nhf-zaki** [comment] 2017-12-28 07:26
@sinnlosername Its very unfortunate, I am using ubuntu 16.04. 
If any one has the 1.0.6 version for linux (deb), please share.

**Comment by sinnlosername** [comment] 2017-12-28 16:08
Oh sorry, didn't see it. Sadly, I haven't got it for ubuntu. I also wrote a support email, lets hope they'll fix it soon.

**Comment by bengotow** [comment] 2017-12-28 16:46
Hey folks! Sorry for the hassle, this will be fixed in 1.0.12 which will go out later today. It looks like this was a very subtle regression in 1.0.11 that got through testing. Looking to see if we can improve static analysis so this won't happen again.

**Comment by alechko** [comment] 2018-01-02 10:11
@bengotow tested in 1.0.12 and looks like the issue is fixed, thanks!

**Comment by jasonmarkperez** [comment] 2018-01-17 19:24
I am running in 1.0.12 but I am seeing this issue.

**Comment by bengotow** [comment] 2018-02-09 20:22
Hey folks—version `1.1.3` shipped a few days ago and included the fix for this issue. In some scenarios, Mailspring could get backlogged by enough backend changes that it tried to create IMAP commands that were so large they would never complete successfully. 

You should have received the update automatically, but if not you can download it directly from getmailspring.com/download. Enjoy! Gonna go ahead and close this.

**Closed by bengotow** 2018-02-09 20:22 UTC
Labels: bug, done-pending-release
