### ISSUE TITLE
Bug:  Fastmail & Contacts Not Showint/Editable

### ISSUE THREAD

**Issue by kwa11ace** [Foundry376/Mailspring#2048] opened 2020-06-09 06:28 UTC
**Describe the bug**
Have the free version of Mailspring and have connected to my Fastmail account.  The email side is no problem but on the contacts (Settings → Window → Contacts)  I can neither see any of my created contacts nor the contact groups.  All I do see are the contacts stripped from the emails Mailspring has downloaded.  I also cannot not create a new contact nor edit the contacts Mailspring has stripped.

Mailspring 1.7.8-13635bcf - Windows 10 64b

**Expected behavior**
I also added a GMail account and all the contacts features worked as you would expect.

**Comment by CodeMouse92** [comment] 2021-03-02 02:30
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/editable-contacts-from-imap-email-addresses/752

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 02:30 UTC
Labels: audit, bug
