### ISSUE TITLE
how to Change Icons Tray ?

### ISSUE THREAD

**Issue by HaxorGaruda** [Foundry376/Mailspring#1444] opened 2019-03-31 07:48 UTC
##### What operating system are you using?
Parrot Os debian testing based
...

##### What version of Mailspring are you using?
1.6.0
...

How to Change Icon Tray mailspring manualy ? on my Parrot Os debian based is to big ,  thanks ....

![mailspring-jembut](https://user-images.githubusercontent.com/5996055/55286283-df348500-53c3-11e9-8894-ff306239ac17.png)

**Comment by bengotow** [comment] 2019-05-26 23:47
Hey! There's not currently a way to do this, but it'd be a great thing for someone to tackle and I'd love a pull request for improvements here. We've tried for years to find a single icon that will work for everyone on Linux, but the trays and how they scale images is inconsistent. I think allowing people to override the image (or creating a lookup table of linux distro <> image) would be a good next step.

@arkraft recently contributed some great Linux theme utils to the project so maybe that'd be a good starting point: https://github.com/Foundry376/Mailspring/blob/master/app/src/linux-theme-utils.ts#L318.

**Comment by CodeMouse92** [comment] 2021-02-20 03:50
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/allow-theme-override-of-system-tray-icon/537

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-20 03:50 UTC
Labels: audit, enhancement, good first issue, linux
