### ISSUE TITLE
Bug: Windows outside of Mailspring does not show any text on Buttons

### ISSUE THREAD

**Issue by zickzackzuck** [Foundry376/Mailspring#2112] opened 2020-08-04 08:09 UTC
**Describe the bug**
If I try to change the Theme, or try to print a Mail, the Dialogue from Ubuntu is not shown properly: There is no text on the Buttons

**To Reproduce**
1. Go to 'Theme'
2. Click 'Install Theme'

**Expected behavior**
The Windows should be like normal.

**Screenshots**
Putted some Screenshots into the Post
![Bildschirmfoto-20200804093518-965x438](https://user-images.githubusercontent.com/45263585/89269610-63db8700-d63a-11ea-8d59-bff51d4515fd.png)
![Bildschirmfoto-20200804093349-675x133](https://user-images.githubusercontent.com/45263585/89269616-64741d80-d63a-11ea-9987-330ea27c2d90.png)

**Setup: (please complete the following information):**
 - OS: Ubuntu
 - OS Version 18.04
 - Mailspring Version: ex: 1.7.8 installed via snap

**Additional context** 
In the Terminal mailspring gives these Errors, looks like this is a snap-issue?:
`robert@robert-desktop:~$ mailspring
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Running database migrations
App load time: 230ms

{"error":null}

(mailspring:27033): Pango-WARNING **: failed to create cairo scaled font, expect ugly output. the offending font is 'Ubuntu 11'

(mailspring:27033): Pango-WARNING **: font_face status is: file not found

(mailspring:27033): Pango-WARNING **: scaled_font status is: file not found

(mailspring:27033): Pango-WARNING **: shaping failure, expect ugly output. shape-engine='PangoFcShapeEngine', font='Ubuntu 11', text='Home'

(mailspring:27033): Pango-WARNING **: failed to create cairo scaled font, expect ugly output. the offending font is 'Ubuntu 11'

(mailspring:27033): Pango-WARNING **: font_face status is: file not found

(mailspring:27033): Pango-WARNING **: scaled_font status is: file not found

(mailspring:27033): Pango-WARNING **: failed to create cairo scaled font, expect ugly output. the offending font is 'Ubuntu Bold 11'

(mailspring:27033): Pango-WARNING **: font_face status is: file not found

(mailspring:27033): Pango-WARNING **: scaled_font status is: file not found

(mailspring:27033): Pango-WARNING **: shaping failure, expect ugly output. shape-engine='PangoFcShapeEngine', font='Ubuntu Bold 11', text='On This Computer'

(mailspring:27033): Pango-WARNING **: failed to create cairo scaled font, expect ugly output. the offending font is 'Ubuntu Bold 15.83984375'

(mailspring:27033): Pango-WARNING **: font_face status is: file not found

(mailspring:27033): Pango-WARNING **: scaled_font status is: file not found

(mailspring:27033): Pango-WARNING **: shaping failure, expect ugly output. shape-engine='PangoFcShapeEngine', font='Ubuntu Bold 15.83984375', text='No results found'

(mailspring:27033): Pango-WARNING **: failed to create cairo scaled font, expect ugly output. the offending font is 'Ubuntu Bold 11'

(mailspring:27033): Pango-WARNING **: font_face status is: file not found

(mailspring:27033): Pango-WARNING **: scaled_font status is: file not found
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
`

**Comment by zickzackzuck** [comment] 2020-08-05 18:52
Anyone Reading this here?

**Comment by bengotow** [comment] 2020-08-16 23:19
Hey @zickzackzuck yep this seems like a Snap / Ubuntu configuration issue, can you try this? Because we're looking for the standard "Ubuntu 11" font it seems like the app may be unable to read any fonts:

```
1. open terminal
2. su -
3. chmod -Rf 777 /usr/share/fonts/*
4. Tada! Everything should be fixed now! 
```

**Comment by zickzackzuck** [comment] 2020-08-18 20:30
I tried this: 

This happens: 

`robert@robert-desktop:~$ su -
Passwort: 
su: Legitimierungsfehler
robert@robert-desktop:~$ 
`

If I do then a 
`sudo chmod -Rf 777 /usr/share/fonts/*`

the bug still exists.

**Comment by zickzackzuck** [comment] 2020-08-26 08:02
Still doesn't work.

**Comment by CodeMouse92** [comment] 2021-03-02 21:51
@zickzackzuck It seems that Snap has been causing all sorts of problems for Mailspring, so we're looking on adding Flatpak support instead.

https://community.getmailspring.com/t/flatpak-distribution-on-linux/68

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 21:51 UTC
Labels: audit, bug, linux
