### ISSUE TITLE
Bug: Drag and drop 2 images together only add 1 attached image 

### ISSUE THREAD

**Issue by keithyipkw** [Foundry376/Mailspring#2055] opened 2020-06-14 09:55 UTC
**Describe the bug**
When composing a new email, dragging and dropping 2 images together only adds 1 attached image. Dragging and dropping the missing image multiple times randomly add it.

**To Reproduce**

1. Click "Compose new message"
1. In File Explorer, select 2 images
1. Drag them onto the message composer
1. Drop
1. Only 1 image is added
1. Drag the missing image onto the message composer
1. Repeat until the image is added

**Expected behavior**
The 2 images are added in the first drag and drop

**Setup: (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - Mailspring Version: 1.7.8

**Comment by CodeMouse92** [comment] 2021-03-02 02:45
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/drag-and-drop-2-images-together-only-add-1-attached-image/916

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@keithyipkw: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 02:45 UTC
Labels: audit, bug
