### ISSUE TITLE
[Feature Request] Ability to reply from different account.  

### ISSUE THREAD

**Issue by neddy** [Foundry376/Mailspring#581] opened 2018-01-26 06:34 UTC
Sometimes I get emails into one account that I would like to be able to reply to with another account.

Cheers,
Ned

**Comment by gmagic** [comment] 2018-02-02 14:36
Support such feature request!

Important for me.

**Comment by aulbricht** [comment] 2018-12-04 02:31
Yes please. +1

**Comment by CarlosRebolledoA** [comment] 2018-12-04 11:16
+1

**Comment by bergmul** [comment] 2019-10-20 01:27
+1

**Comment by didrip** [comment] 2019-10-24 12:46
Any update on this ? Makes it really hard to use a work email address on one account when all emails are redirected to one account.

**Comment by samtuke** [comment] 2020-03-16 14:59
+1. Have to use Geary for certain types of replies until this is supported.

**Comment by lindsaymasten** [comment] 2020-04-17 20:11
+1 adding my voice to the choir. This is an important feature. (Right now I'm having to switch to Edison to make certain replies and that's not ideal because I need read receipts for work reasons.)

**Comment by alexpan1996** [comment] 2020-06-03 08:51
+ yes please!

**Comment by tomas-dostal** [comment] 2020-09-14 10:42
+1 
I used Gmail before and this was a feature I used very often. Now when I switched to Mailspring I miss this feature a lot.

**Comment by CodeMouse92** [comment] 2021-01-27 01:34
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/ability-to-reply-from-different-account/294

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@neddy: if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-27 01:34 UTC
Labels: audit, enhancement
