### ISSUE TITLE
Feature request: tor hidden service imap/pop3/smtp

### ISSUE THREAD

**Issue by theoden8** [Foundry376/Mailspring#1777] opened 2020-01-20 02:11 UTC
As a mailspring user, I appreciate how the software allows for flexible account set up, various customizations, and even third-party VPN/Tor routing, using external software (orbot-like), which is quite enough for me to be content with its functionality on everyday use.

You may know that email providers such as protonmail, cock.li and numerous others, including more private and self-hosted ones, set up tor hidden services to "provide more anonymity". I wonder if, perhaps, email hosts that support a hidden service could be set up in some way. Maybe, a PAC plugin will suffice. I'm not familiar with the code, just a thought.

It fails to authenthicate **.onion** IMAP service when I run it through TOR with proxifier on Windows 10, and produces no error log but its title:

```
----------IMAP----------
```

**Comment by bengotow** [comment] 2020-02-15 19:01
Hey @theoden8 — thanks for proposing this! Mailspring doesn't support system proxies, but I think that you /should/ be able to route your IMAP / SMTP traffic through a VPN, bastion host, or other router by mapping `localhost:PORT` to your VPN, with instructions for the VPN to forward the traffic to `destination:OTHER_PORT` and then pointing Mailspring to localhost.

I'm not familiar with the privacy options offered by other mail providers - if we can figure this out it'd be cool to provide instructions in our knowledge base. I tried for a while to add ProtonMail Bridge support, but it turns out they implemented their own IMAP service that runs on your local machine (rather than just forwarding traffic through a VPN to a standard IMAP server), and their implementation wasn't formatting it's IMAP responses quite right.

**Comment by CodeMouse92** [comment] 2021-02-26 18:52
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/add-proxy-support/185

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@theoden8: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-26 18:52 UTC
Labels: enhancement, interesting, migrated
