### ISSUE TITLE
How to run Mailspring on Gentoo?

### ISSUE THREAD

**Issue by BlueManCZ** [Foundry376/Mailspring#1613] opened 2019-08-13 09:22 UTC
Hello,

I have a question rather than a problem. I read the [paragraph](https://github.com/Foundry376/Mailspring/blob/master/ROADMAP.md#why-is-mailsync-closed-source) where you mention how hard is compilation of Mailspring and it sounds like you suggest not to try at all.

But I have for example **Gentoo**, where I can't install .deb or .rpm packages and not even snap (don't have systemd).

What do you suggest me to do, when I want to use Mailspring?

Thank you in advance.

**Comment by bengotow** [comment] 2019-10-08 21:33
Hey! Thanks for filing this—at this time there's not much help I can offer. I think that your best bet may be trying to unpack the RPM and place the files in the correct locations. (The contents of the RPM - the actual Mailspring binary - should work fine once it's installed I /think/). That said I don't imagine anyone has tested with Gentoo before! I'm going to leave this issue open in case other folks come by with the same question.

**Comment by BlueManCZ** [comment] 2020-03-25 14:54
I created ebuild to get Mailspring working on Gentoo, based on .deb extraction, and it works fine. But I get this warning during installation:

![Snímek z 2020-03-25 15-50-13](https://user-images.githubusercontent.com/17854950/77549616-58b86380-6eb0-11ea-8637-ad63e847b73f.png)

Do you link `libcrypto.so.1.0.0` in these libraries? And why this version? I have only `libcrypto.so.1.1` in my system provided by `openssl:1.1.1d-r3` package.

**Comment by paul** [comment] 2020-03-26 21:27
I just happened to run into this with the released rpm on Fedora 31. They provide `libcrypto.so.1.1` and `libcrypto.so.1.0.2`, but the .so files in Mailspring depend on `libcrypto.so.1.0.0`:

```
$ ldd /usr/share/mailspring/resources/app.asar.unpacked/libntlm.so
	linux-vdso.so.1 (0x00007ffd06175000)
	libcrypto.so.1.0.0 => not found
	libc.so.6 => /lib64/libc.so.6 (0x00007f8eb6817000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f8eb6c08000)
```

There's a `compat-openssl10-devel` that provides `libcrypto.so.1.0.0`, but its incompatible with the "normal" openssl-devel package, are replacing that will probably break lots of other things.

```
$ sudo dnf install compat-openssl10-devel
Last metadata expiration check: 2:21:44 ago on Thu 26 Mar 2020 01:04:26 PM MDT.
Error:
 Problem: problem with installed package openssl-devel-1:1.1.1d-2.fc31.x86_64
  - package compat-openssl10-devel-1:1.0.2o-8.fc31.i686 conflicts with openssl-devel provided by openssl-devel-1:1.1.1d-2.fc31.x86_64
  - conflicting requests
  - package compat-openssl10-devel-1:1.0.2o-8.fc31.x86_64 conflicts with openssl-devel provided by openssl-devel-1:1.1.1d-2.fc31.x86_64
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages)
```

**Comment by paul** [comment] 2020-03-27 16:32
Quick update: I installed the `compat-openssl10-devel` package, and manually set up a symlink for `libcrypto.so.1.0.0` to the `libcrypto.so.1.0.2o` file that package provides, but that just gives a different error:

```
Mar 27 10:26:31 ava.home mailsync.bin[279578]: unable to dlopen /usr/share/mailspring/resources/app.asar.unpacked/libdigestmd5.so: /lib64/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by /usr/share/mailspring/resources/app.asar.unpacked/libdigestmd5.so)
Mar 27 10:26:31 ava.home mailsync.bin[279578]: unable to dlopen /usr/share/mailspring/resources/app.asar.unpacked/libntlm.so: /lib64/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by /usr/share/mailspring/resources/app.asar.unpacked/libntlm.so)
Mar 27 10:26:31 ava.home mailsync.bin[279578]: unable to dlopen /usr/share/mailspring/resources/app.asar.unpacked/libscram.so: /lib64/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by /usr/share/mailspring/resources/app.asar.unpacked/libscram.so)
```

It seems the Mailspring RPM won't work on recent versions of Fedora (I'm using 31 currently, this was working on 30). I also tried the snap, but it just hangs when trying to add the first account during the setup wizard.

**Comment by BlueManCZ** [comment] 2020-03-27 17:11
@paul And when you extract .rpm package and simply run `./mailspring` inside the `usr/share/mailspring/` directory? Does it work?

**Comment by paul** [comment] 2020-03-27 17:23
@BlueManCZ nope, same error:

```
unable to dlopen /home/rando/Downloads/mailspring/usr/share/mailspring/resources/app.asar.unpacked/libdigestmd5.so: /lib64/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by /home/rando/Downloads/mailspring/usr/share/mailspring/resources/app.asar.unpacked/libdigestmd5.so)
```

Looks like the oldest version of openssl I can get on Fedora 31 without it being a giant pain is `1.0.2o`. 

When I run `./mailspring` in the console, it also prints out:

```
Fontconfig warning: "/usr/share/fontconfig/conf.avail/05-reset-dirs-sample.conf", line 6: unknown element "reset-dirs"
Running database migrations
App load time: 122ms

{"error":null}
Manual update check (updates.getmailspring.com/check/linux/x64/1.7.4-d54ff730/fc5b9ea1-4a8f-4fe3-9fc5-b5743a4681d6/stable) returned 204
{ TypeError: Cannot read property 'emailAddress' of undefined
    at _AccountStore.addAccount (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/flux/stores/account-store.ts:223:18)
    at OnboardingStore._onFinishAndAddAccount (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib/onboarding-store.ts:129:20)
    at EventEmitter.eventHandler (/home/rando/Downloads/mailspring/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:36:22)
    at EventEmitter.emit (/home/rando/Downloads/mailspring/usr/share/mailspring/resources/app.asar/node_modules/eventemitter3/index.js:72:35)
    at Function.trigger (/home/rando/Downloads/mailspring/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:52:26)
    at Object.functor [as finishAndAddAccount] (/home/rando/Downloads/mailspring/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/createAction.js:32:56)
    at onboarding_helpers_1.finalizeAndValidateAccount.then.validated (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib/decorators/create-page-for-form.tsx:170:29)
  message: 'Cannot read property \'emailAddress\' of undefined' } { pluginIds: [ 'onboarding' ] }
```

But I imagine that `undefined` is just coming from the libcrypto errors preventing the fastmail connection in the first place.

**Comment by BlueManCZ** [comment] 2020-03-27 17:27
Yea, I noticed you edited your first comment, so I deleted mine. Developers should say something about it. I would probably have the same problem as you, but I can't test it with Fastmail. I have only Gmail and IMAP accounts.

**Comment by BlueManCZ** [comment] 2020-03-27 17:32
Maybe you can create a new issue for this. This is from 13 Aug 2019, I don't know if they still watch it.

**Comment by paul** [comment] 2020-03-27 17:46
Actually, this may just be a total red herring. I downloaded the openssl-1.0.0 source, compiled it by hand, copied the `/lib64/libcrypto.so.1.0.0` in place manually, so now `ldd` finds it, but I still can't add the fastmail account. No libcrypto errors in the logs any more, but I still get the `undefined` error in the console.

```
message: 'Cannot read property \'emailAddress\' of undefined' } { pluginIds: [ 'onboarding' ] }
```

So maybe this is a different problem.

**Comment by BlueManCZ** [comment] 2020-03-27 17:56
You are right. It looks like a different problem, unrelated to libcrypto.

**Comment by paul** [comment] 2020-03-27 18:16
I can't add a generic IMAP one, either. I was able to surgically extract the credentials from libsecret and the account json from the config from an old backup, and its happily syncing the emails now. Must just be a bug in the wizard, I'll open a separate issue.

**Comment by CodeMouse92** [comment] 2021-02-09 23:26
Based on the above. it appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-09 23:26 UTC
Labels: audit, linux
