### ISSUE TITLE
Reading pane crashes when scrolling up using arrows

### ISSUE THREAD

**Issue by thertz** [Foundry376/Mailspring#950] opened 2018-06-24 22:03 UTC
When writing a response to an email if I mistakenly use the up arrow, the reading pane crashes with the following Error:

Error: Failed to execute 'setStart' on 'Range': The offset 4294967295 is larger than the node's length (1).
    at findDOMRange (/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/utils/find-dom-range.js:37:5)
    at Content._this.updateSelection (/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/content.js:154:46)
    at Content._this.componentDidMount (/usr/share/mailspring/resources/app.asar/node_modules/slate-react/lib/components/content.js:113:13)
    at commitLifeCycles (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:149:193)
    at b (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:158:229)
    at m (/usr/share/mailspring/resources/app.asar/node_modules/react-dom/cjs/react-dom.production.min.js:169:217)
    at w (/usr/share/mailspring/

##### Are there any related issues?

...

##### What operating system are you using?
...

##### What version of Mailspring are you using?
...

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment] 2018-07-08 07:08
Hey thanks for reporting this — this seems to be happening quite a bit and I'm trying to create a case that allows me to reproduce it reliably. I'll let you know if I can track it down.

**Comment by phamhung77** [comment] 2018-08-22 05:00
I am facing this too with the latest Mailspring on Mac High Sierra. Searching issues show that this bug exists for a while already. Any ETA for fixing please?

**Comment by cr1st1p** [comment] 2018-11-26 12:46
I'm facing this problem too :-(
Note that that offset (4294967295) seems to be -1 interpreted as a no-sign number (positive). 

Is there a way to recover from that error?

**Comment by thertz** [comment] 2018-11-26 12:52
Hi,
I use the reload command from the developer menu (not sure this is the name,  not in front of my laptop)

**Comment by cr1st1p** [comment] 2018-11-26 12:57
@thertz  thank you for the tip.

**Comment by bengotow** [comment] 2019-03-26 15:48
Note: this is related to #921

**Comment by bengotow** [comment] 2019-07-04 13:55
Hey folks! This should be addressed in the latest release (1.6.3) that shipped earlier this week. The app should auto-update on it's own, or you can grab the new version from the releases page: https://github.com/Foundry376/Mailspring/releases/. Thanks for filing this - enjoy the update!

**Closed by bengotow** 2019-07-04 13:55 UTC
Labels: bug, composer, done-pending-release
