### ISSUE TITLE
Bug:  Sophos Endpoint is detecting mailspring as a generic threat

### ISSUE THREAD

**Issue by Shadi** [Foundry376/Mailspring#1802] opened 2020-02-19 08:35 UTC
I have Sophos Endpoint installed and it keeps giving me warnings about mailspring, the warning text:

**Active threat C2/Generic-A detected**

the file that it is giving me warnings about is:
Mailspring Helper.app/Contents/MacOS/Mailspring Helper

**Setup: (please complete the following information):**
 - OS: macOS
 - OS Version: 10.15.3 (19D76)
 - Mailspring Version: 1.7.2 (1.7.2)

**Comment by CodeMouse92** [comment] 2021-02-16 18:33
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/sophos-premium-version-mailspring-freezes/600/1

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-16 18:33 UTC
Labels: audit, bug
