### ISSUE TITLE
Adding a label to an email adds that label to emails directly above or below it.

### ISSUE THREAD

**Issue by rachilli** [Foundry376/Mailspring#1725] opened 2019-11-29 10:12 UTC
##### Are there any related issues?

This issues seems to be similar: https://github.com/Foundry376/Mailspring/issues/941

Essentially, I use Mailspring because I like its speed, but sometimes things seem a little slow - for example, I love to move emails to separate folders or label them (and have them automatically move out of the inbox) by pressing v. But, sometimes, when I press v + then want to move to a folder beginning with "a", Mailspring isn't quick enough and it starts to reply-all instead.

In this case, though, I am sometimes moving through my inbox quite quickly - filing away emails that aren't needed in there any more. I'm assuming it could be to do with the speed again, but I'm finding that I often have emails popping back in my inbox that are labelled incorrectly. This seems to happen when I label or move one email by pressing v, and it seems to apply it to the emails either directly before or after it (sometimes both) in the inbox.

##### What operating system are you using?

Windows 10, latest version of 1909. But this has been happening since I started using Mailspring on-and-off last year (2018).

##### What version of Mailspring are you using?
(eg: 1.6.3 or 1.7.0 - this is shown in Mailspring's main menu.)

1.7.2-4522b259

--

**Bug?**

##### Is this an email sync or connection issue?
I don't think so, no.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

I use Google Suite, and don't know if this is relevant or to do with that!

##### Is the issue reproducible with a particular attachment, message, signature, etc?

This is one example - these two emails were to the same person, with two separate threads. However, I added the top tag to a different email, and it then automatically applied it to this one below it. https://share.getcloudapp.com/E0uE5GLg

**Comment by rachilli** [comment] 2019-11-29 10:25
Just to add to this, it's _literally_ just happened again. I searched for a particular email, then labelled it/moved it in my "Support Tickets" folder. I then go back to my inbox and the top email in the inbox has that label too, despite me not adding it myself: https://share.getcloudapp.com/RBuX555O

**Comment by bengotow** [comment] 2019-11-30 18:48
Hey! Thanks for reporting this - will see if I can reproduce this today. I think you're right that this may be speed related, but it's definitely an odd one.

**Comment by rachilli** [comment] 2019-12-04 09:57
No worries! If there's anything I can do or pass along do let me know. :)

**Comment by CodeMouse92** [comment] 2021-02-12 23:38
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/labeling-an-email-can-sometimes-label-other-emails/598

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@rachilli: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-12 23:38 UTC
Labels: audit
