### ISSUE TITLE
Mailspring incorrectly grouping emails by ignoring brackets in subject lines

### ISSUE THREAD

**Issue by v0wels** [Foundry376/Mailspring#954] opened 2018-06-25 12:40 UTC
##### Are there any related issues?
This is the same issue as my original Nylas Mail issue from Mar 2017. https://github.com/nylas/nylas-mail/issues/3309

##### What operating system are you using?
10.12.6

##### What version of Mailspring are you using?
1.2.2

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Tested with Gmail.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
It seems to only happen with emails generated by Basecamp Classic.

https://cloud.githubusercontent.com/assets/5385895/23512294/1fe90040-ff2e-11e6-93bd-1a568377de23.jpg

My team uses Basecamp Classic as our project management software, and as the title says, if two message has the same message title, they get grouped together as one email. When messages get sent, they follow the format of [Job Name] Message Title, meaning that if I get two emails like this:

[Acme Co Website Development] Project Overview
[Initech Edits Q1 2017] Project Overview
[Globex Banner Design] Project Overview

They'd both be grouped into the same thread. This is a big issue, because we re-use message titles all the time (as you can see, the thread attached has 44 different emails in it).

The other strange thing is, there's no rhyme or reason as to which emails get grouped with what. There's another "Project Overview" thread in my inbox a few lines down that contains another 3 completely different Basecamp threads.

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Again, only in Nylas Mail.

**Comment by bengotow** [comment] 2018-07-08 07:15
Hey—thanks for reporting this, this is pretty whacky but I've been able to reproduce it by sending a Gmail account two emails titled `[Project A] System Overview` and `[Project B] System Overview`. Unfortunately, for Gmail accounts Mailspring and Nylas Mail actually delegate threading completely to Gmail. It provides "thread IDs" for each message, and we just use those to do the collapsing without any additional logic. It looks like Gmail is threading those messages in their web UI too:

<img width="800" alt="image" src="https://user-images.githubusercontent.com/1037212/42417626-8f3be778-8254-11e8-91f4-88a151ee86ae.png">

I think that this is probably one of those unfortunate scenarios where Gmail probably changed it's behavior at some point, and Basecamp may need to change the subject lines. 😞

**Comment by bengotow** [comment] 2018-07-08 07:15
Gonna close this as resolved since there's not too much we can do without separating Mailspring's threading from Gmail's threading, and I'm afraid that'd introduce a lot more problems!

**Closed by bengotow** 2018-07-08 07:15 UTC
