### ISSUE TITLE
Feature Request: Filters based on dates

### ISSUE THREAD

**Issue by ted-gould** [Foundry376/Mailspring#2085] opened 2020-07-08 21:41 UTC
**Is your feature request related to a problem? Please describe.**

Like most folks I get a bunch of notification emails that are useful, but generally only for a limited amount of time. For instance, I get the USPS Informed Delivery emails daily about what is in my mailbox. These are useful for a day or two, but I don't care for them after then. I'd generally like them to be trashed after that.

**Describe the solution you'd like**

My thoughts are that an additional type of rule could be added to the mail filters. For instance "Older than: One week" which would then apply the rule. It isn't an automatic solution, but provides the feature to power users.

**Describe alternatives you've considered**

* Many mail clients (i.e. GMail) are going to try and auto-classify emails into groups. It would be interesting to have a group of emails and be able to set policies for that group. This is clearly more complex as the group is non-trivial. But if the grouping could be made simple, it would be probably a feature that could elevate to being usable by a more general audience.
* Provide a delayed delete feature while browsing email. For instance, Shift+Delete, which would delete the email in a specified number of days. Feels hidden to me, but perhaps it could be surfaced in a more intuitive way.

**Comment by CodeMouse92** [comment] 2021-03-02 18:44
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mail-rule-filters-based-on-dates/932

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@ted-gould: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 18:44 UTC
Labels: audit, enhancement
