### ISSUE TITLE
[Feature Request] Search: Find emails by date?

### ISSUE THREAD

**Issue by ghost** [Foundry376/Mailspring#88] opened 2017-10-08 16:00 UTC
Is it possible to search for emails by date? For instance, i'm trying to display all emails that I received in 2016.

##### What operating system are you using?

Ubuntu 16.04 LTS

##### What version of Mailspring are you using?

1.02

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?

Yes.

Thank you

**Comment by bengotow** [comment] 2017-10-08 16:40
Hey! I don't believe you can do this yet, but it shouldn't be too hard to add in an update.

**Comment by DannyGlover** [comment] 2017-10-08 17:53
Awesome, thanks for adding this as a feature request. It would be extremely useful.

**Comment by cucumbur** [comment] 2018-04-03 19:28
http://it.fitnyc.edu/2014/05/23/gmail-tip-filter-mail-older-than-a-certain-date/
Here is the relevant gmail syntax. Can confirm it doesnt work currently

**Comment by DarkSmile92** [comment] 2018-10-12 14:11
I searched for a solution and can confirm that gmail search works. For a date range (event a day), use:
before:"2018/08/30" and after:"2018/08/01"

**Comment by CodeMouse92** [comment] 2021-02-04 23:19
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/custom-email-sorting/470

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-04 23:19 UTC
Labels: enhancement
