### ISSUE TITLE
Several of your accounts are having issues - and doesn't retry

### ISSUE THREAD

**Issue by krasi-georgiev** [Foundry376/Mailspring#1407] opened 2019-03-05 08:34 UTC
Fedora 27

##### What version of Mailspring are you using?
1.5.7

**Bug?**

Since upgrading to 1.5.7 after restoring my laptop from sleep mailspring doesnt retry to sync the mails. If I click "Check Again" manually it all syncs fine. But the problem is that it doesn't auto retry after a certain period of time on its own. With the previous versions when it looses internet or after resuming the laptop it would auto reconnect and sync all mail without the need to click that button manually.

[Mailspring.zip](https://github.com/Foundry376/Mailspring/files/2929930/Mailspring.zip)

**Comment by pburney** [comment] 2019-03-09 12:40
I am also having this issue on Ubuntu 18.0.4.1, Mailspring 1.5.7-2057ca30

**Comment by Al2Me6** [comment] 2019-03-19 01:53
Can confirm; also occurs on Ubuntu 18.10, Mailspring 1.5.7.

**Comment by corck** [comment] 2019-03-30 07:43
Same for me: Manjaro, Mailspring 1.6.0-10f5c95c

**Comment by MuTaTeD** [comment] 2019-04-03 04:28
Same for me
Mailspring: 1.6.0-10f5c95c
Kubuntu (Ubuntu 18.04.2 LTS)

**Comment by krasi-georgiev** [comment] 2019-04-25 07:03
ping to the maintainers.

**Comment by al2me6** [comment] 2019-06-28 11:55
Has there been any updates to this issue?

**Comment by awunder** [comment] 2019-07-08 16:52
fwiw, i also have this issue with v1.6.3.134a0e55 but only after a couple of hours after reboot.. it works fine in the morning and issues start after maybe 6hours.. 

it doesnt help to close and reopen it, i have to reboot and then it works again, for a couple hours.

Andreas

**Comment by awunder** [comment] 2019-07-09 08:54
fwiw i just found in the logs a:

> 10874 [2019-07-09 04:35:47.151] [main] [info] Identity created at 1561632118 - using ID Schema 1
> 10874 [2019-07-09 04:35:47.154] [main] [info] ------------- Starting Sync (mail@example.com) ---------------
> 10874 [2019-07-09 04:35:47.156] [background] [info] Marking all folders as `busy`
> 10874 [2019-07-09 04:35:47.157] [metadata] [info] Metadata delta stream starting...
> 10874 [2019-07-09 04:35:47.158] [background] [info] Syncing folder list...
> 10874 [2019-07-09 04:35:47.614] [background] [info] Syncing folder list...
> 10874 [2019-07-09 04:35:47.783] [background] [info] syncFolderChangesViaCondstore - INBOX: modseq 57033 to 57033, uidnext 55534 to 55534
> 10874 [2019-07-09 04:35:47.957] [background] [info] syncFolderChangesViaCondstore - Sent: modseq 1254 to 1254, uidnext 1201 to 1201
> 10874 [2019-07-09 04:35:48.006] [background] [info] syncFolderChangesViaCondstore - Drafts: modseq 25 to 25, uidnext 9 to 9
> 10874 [2019-07-09 04:35:48.041] [foreground] [info] syncFolderChangesViaCondstore - INBOX: modseq 57033 to 57033, uidnext 55534 to 55534
> 10874 [2019-07-09 04:35:48.048] [background] [info] syncFolderChangesViaCondstore - Trash: modseq 18 to 18, uidnext 8 to 8
> 10874 [2019-07-09 04:35:48.091] [background] [info] syncFolderChangesViaCondstore - Junk: modseq 500 to 500, uidnext 425 to 425
> 10874 [2019-07-09 04:35:48.133] [background] [info] syncFolderChangesViaCondstore - Mailspring: modseq 1 to 1, uidnext 1 to 1
> 10874 [2019-07-09 04:35:48.163] [foreground] [info] Idling on folder INBOX
> 10874 [2019-07-09 04:35:48.183] [background] [info] syncFolderChangesViaCondstore - Mailspring/Snoozed: modseq 1 to 1, uidnext 1 to 1
> 10874 [2019-07-09 04:35:48.227] [background] [info] syncFolderChangesViaCondstore - INBOX/Folder: modseq 6503 to 6503, uidnext 6503 to 6503
> 10874 [2019-07-09 04:35:48.235] [background] [info] Sync loop deleting unlinked messages with phase 2.
> 10874 [2019-07-09 04:35:48.254] [background] [info] Sync loop complete.
> 10874 [2019-07-09 04:36:02.155] [metadataExpiration] [info] Scanning for expired metadata
> 10874 [2019-07-09 04:36:02.155] [metadataExpiration] [info] -- Will wake for next expiration in 7200sec
> 10874 [2019-07-09 04:36:06.867] [metadata] [info] Metadata delta stream closed.
> 10874 [2019-07-09 04:36:06.908] [metadata] [critical] 
>  ***
>  *** A JSON exception occurred during program execution: 
>  *** [json.exception.type_error.316] invalid UTF-8 byte at index 0: 0x90
>  ***
> 
> 10874 [2019-07-09 04:36:06.935] [metadata] [critical]  *** Stack trace (line numbers are approximate):
>  *** (unknown)  clone
>  ***

maybe that helps..

thanks,
Andreas

**Comment by husaam-adel** [comment] 2019-07-15 10:10
Happening with me too on Windows. Lock my laptop often during the day, will sometimes not re-sync when I come back to the laptop. Need to quit the application and restart for it to pick up again

**Comment by oohjhu** [comment] 2019-07-18 19:09
I installed Mailspring on my Linux Mint 19.1 system, added a few accounts...Gmail, Outlook, and yahoo. Every one of them is experiencing syncing issues. Almost as soon as I launch the app, message pops up saying "several of my accounts are having syncing issues." It's essentially unusable. Is anyone doing something abou this?

**Comment by codermjb** [comment] 2019-08-20 15:57
I have the same issue on Debian 9 and Debian 10 with the latest version of Mailspring 1.6.3: https://gyazo.com/85308f70a3e9122a28002b09fce83c69

For me, the issue is my computer goes to sleep. And when I wake it up, Mailspring doesn't reconnect. If I click "check again" from the bottom left corner of the sidebar, it reconnects and email starts to come in.

The issue for me, when I resume work at my computer, I don't get new emails because it's stuck on "try reconnecting". Until I reconnect pressing the check again button.

**Comment by crispincorky** [comment] 2019-09-07 08:53
Similar here. If my Mac or PC go to sleep I have to clear the cache to get the email to reconnect. Using 4  imap accounts.

**Comment by crispincorky** [comment] 2019-09-07 08:54
Love the app though. If this can be fixed, think I'll sign up for pro!

**Comment by bengotow** [comment] 2019-10-09 03:40
Hey folks - just a quick heads up that the `invalid UTF-8 byte at index 0` bug will be fixed in the next release this week. This turned out to be a tricky one and the app doesn't retry the connection because the error is actually thrown within the error handling logic for the sync worker. Stay tuned!

**Comment by zenfulcoder** [comment] 2019-10-15 15:38
I am still having this issue in 1.7.1. Did the fix make it over? To be able to add more than 1 Gmail account.

**Comment by lucianoratamero** [comment] 2019-10-31 17:04
@zenfulcoder , I tried that, to no avail :(
thanks for the suggestion, though!

mine was a clean install, btw, so it seems to be an issue with mailspring itself.

**Comment by ryanerwin** [comment] 2020-02-19 02:23
I'm getting this same error with Mailspring... Leaving my computer on over night, when I return to it, this "Several of your accounts are having issues" error is shown... If I choose "check again" everything works fine... Just wish MailSpring could automatically "check again" after a 1-5 minute timeout on that box so that my mail stays synced up...

![image](https://user-images.githubusercontent.com/2156415/74795687-2cca2100-52f9-11ea-9986-d609d2bb82fe.png)

**Comment by bengotow** [comment] 2020-04-22 22:13
Hey folks! Thanks for reporting this. If you get a chance, could you download the latest version of Mailspring (1.7.6), let it fail, and then click the new "Show Error Logs..." button in the Preferences > Accounts tab? That tails the logs for technical details and attaches other information like your platform and IMAP host and we can track this down!

**Comment by astavonin** [comment] 2020-05-05 12:49
@bengotow , I feel I have a similar issue. On one of my accounts, Mailspring pops up a message "Encountered an error while syncing" and do nothing till I press the "Try Again" button. I observe this behaviour on Ubuntu 18.04 + Mailspring 1.7.6. Should I create a new defect?

**Comment by krasi-georgiev** [comment] 2020-08-31 18:15
fixed

**Closed** 2020-10-27 09:42 UTC
Labels: bug, done-pending-release
