### ISSUE TITLE
Imap issues: deleted messages are not (really) deleted

### ISSUE THREAD

**Issue by davduf** [Foundry376/Mailspring#335] opened 2017-11-12 17:38 UTC
Since the last version, everything is much better but... the deleted messages.

When I delete a message or mark it as spam/junk, the message goes right to the trash... BUT if i use another  email client, the deleted messages are back again in my INBOX (in the other email client). It seems that Mailspring don't send the right signal to my IMAP account

##### Are there any related issues?
I don't see.

##### What operating system are you using?
Linux Fedora 26

##### What version of Mailspring are you using?
1-0- 8
...

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
IMAP

Thank you a million !
David

**Comment by bengotow** [comment] 2017-11-12 18:49
Hey! Can you open the Mailspring data folder (at `~/.config/Mailspring` on Linux) and see if there are any errors near the bottom of the mailsync-***.log file for your account? It sounds like the syncback is failing for some reason, but it's hard to say why offhand. Check and make sure that if you go to Preferences > Folders, the correct folder is shown as your trash.

**Comment by davduf** [comment] 2017-11-12 19:47
DEAR BEN,

Thank you!

Here some lines from my log...
Do you see something wrong?

Keep up the GREAT job !

11313 [2017-11-12 20:38:11.665] [background] [info] Syncing folder list...
11313 [2017-11-12 20:38:11.858] [background] [info] syncFolderChangesViaCondstore - INBOX: highestmodseq changed, requesting changes...
11313 [2017-11-12 20:38:11.918] [background] [info] - Building queries for range 323413-323418
11313 [2017-11-12 20:38:11.918] [background] [info] Unlinking messages WHERE remoteFolderId = ? AND remoteUID IN (?,?,?,?,?) no longer present in remote range.
11313 [2017-11-12 20:38:11.950] [background] [info] -- Unlinking "Essai de te joindre" (Z2iDCvHTcwUGD6HcXay75fk7bBpbCBcH1oLKaPYLM)
11313 [2017-11-12 20:38:11.957] [background] [info] -- Unlinking "Soccer Manager 2018 vient de sortir" (qdVSi2F3sPqUd7xtjTv4P9CJs7WETBVW3JEbcVV4o)
11313 [2017-11-12 20:38:11.960] [background] [info] -- Unlinking "test" (9GsaSj5y8QBLgRo5RXzhXyKPQWBTBFrRJ3mkwgxH6)
11313 [2017-11-12 20:38:11.964] [background] [info] -- Unlinking "test" (cULPRP6YNH3rUBdf9U8p1a1NgJ9drxBmkp8x3xcW7)
11313 [2017-11-12 20:38:11.967] [background] [info] -- Unlinking "RE: Re: Essai de te joindre" (2FKBekAMCkg5tNNdHzmN9RSfGJNSrZPgAcmKtGGJp)
11313 [2017-11-12 20:38:12.022] [background] [info] syncFolderChangesViaCondstore - INBOX.Sent Messages: highestmodseq, uidnext match, no changes.
11313 [2017-11-12 20:38:12.065] [background] [info] syncFolderChangesViaCondstore - INBOX.Brouillons: highestmodseq, uidnext match, no changes.
11313 [2017-11-12 20:38:12.107] [background] [info] syncFolderChangesViaCondstore - INBOX.Archive: highestmodseq, uidnext match, no changes.
11313 [2017-11-12 20:38:12.151] [background] [info] syncFolderChangesViaCondstore - INBOX.Trash: highestmodseq changed, requesting changes...
11313 [2017-11-12 20:38:12.244] [background] [warning] Ignoring changes to [D*] Objet acheté #476126474 (PARIS GENE BULLARD 53 Rue Pigalle), more recent data is available 1510515492 < 1510601676
11313 [2017-11-12 20:38:12.245] [background] [info] 🔸� Updating message 4294967294=1604 with subject: Essai de te joindre
11313 [2017-11-12 20:38:12.247] [background] [info] 🔸� Updating message 4294967294=1605 with subject: RE: Re: Essai de te joindre
11313 [2017-11-12 20:38:12.249] [background] [warning] Ignoring changes to test, more recent data is available 1510515492 < 1510596077
11313 [2017-11-12 20:38:12.250] [background] [warning] Ignoring changes to test, more recent data is available 1510515492 < 1510596077
11313 [2017-11-12 20:38:12.250] [background] [warning] Ignoring changes to Soccer Manager 2018 vient de sortir, more recent data is available 1510515492 < 1510595038

11313 [2017-11-12 20:38:15.493] [background] [info] Sync loop deleting unlinked messages with phase 2.
11313 [2017-11-12 20:38:15.501] [background] [info] Sync loop complete.
11313 [2017-11-12 20:38:28.977] [main] [info] [local-8d581c11-6119] Running ExpungeAllInFolderTask performLocal:
11313 [2017-11-12 20:38:28.978] [main] [info] [local-8d581c11-6119] -- Succeeded. Changing status to `remote`
11313 [2017-11-12 20:38:29.316] [foreground] [info] Idle exited with code 0
11313 [2017-11-12 20:38:29.317] [foreground] [info] [local-8d581c11-6119] Running ExpungeAllInFolderTask performRemote:
11313 [2017-11-12 20:38:29.417] [foreground] [info] -- Expunged INBOX.Trash
11313 [2017-11-12 20:38:29.477] [foreground] [info] -- Deleted 2 local messages
11313 [2017-11-12 20:38:29.778] [foreground] [info] [local-8d581c11-6119] -- Succeeded. Changing status to `complete`
11313 [2017-11-12 20:38:29.781] [foreground] [info] Idling on folder INBOX
11313 [2017-11-12 20:38:38.083] [foreground] [info] Idle exited with code 0
11313 [2017-11-12 20:38:38.084] [foreground] [info] Idling on folder INBOX
11313 [2017-11-12 20:39:07.282] [foreground] [info] Idle exited with code 0
11313 [2017-11-12 20:39:07.283] [foreground] [info] Idling on folder INBOX
11313 [2017-11-12 20:39:37.452] [foreground] [info] Idle exited with code 0
11313 [2017-11-12 20:39:37.452] [foreground] [info] Idling on folder INBOX
11313 [2017-11-12 20:40:07.682] [foreground] [info] Idle exited with code 0
11313 [2017-11-12 20:40:07.683] [foreground] [info] Idling on folder INBOX
11313 [2017-11-12 20:40:15.503] [background] [info] Syncing folder list...

13 [2017-11-12 20:42:21.895] [background] [info] Sync loop complete.
11313 [2017-11-12 20:42:33.212] [main] [info] [local-5c9d478f-1c5b] Running SyncbackDraftTask performLocal:
11313 [2017-11-12 20:42:33.226] [main] [info] [local-5c9d478f-1c5b] -- Succeeded. Changing status to `remote`
11313 [2017-11-12 20:42:33.563] [foreground] [info] Idle exited with code 0
11313 [2017-11-12 20:42:33.565] [foreground] [info] [local-5c9d478f-1c5b] Running SyncbackDraftTask performRemote:
11313 [2017-11-12 20:42:33.565] [foreground] [info] [local-5c9d478f-1c5b] -- Succeeded. Changing status to `complete`
11313 [2017-11-12 20:42:33.566] [foreground] [info] Idling on folder INBOX
11313 [2017-11-12 20:42:37.810] [foreground] [info] Idle exited with code 0
11313 [2017-11-12 20:42:37.811] [foreground] [info] Idling on folder INBOX
11313 [2017-11-12 20:42:55.328] [main] [info] [local-30292072-c14c] Running SyncbackDraftTask performLocal:
11313 [2017-11-12 20:42:55.338] [main] [info] [local-30292072-c14c] -- Succeeded. Changing status to `remote`
11313 [2017-11-12 20:42:55.679] [foreground] [info] Idle exited with code 0
11313 [2017-11-12 20:42:55.681] [foreground] [info] [local-30292072-c14c] Running SyncbackDraftTask performRemote:
11313 [2017-11-12 20:42:55.682] [foreground] [info] [local-30292072-c14c] -- Succeeded. Changing status to `complete`
11313 [2017-11-12 20:42:55.684] [foreground] [info] Idling on folder INBOX
11313 [2017-11-12 20:43:07.753] [foreground] [info] Idle exited with code 0
11313 [2017-11-12 20:43:07.754] [foreground] [info] Idling on folder INBOX
11313 [2017-11-12 20:43:32.072] [main] [info] [local-4d32d062-bb40] Running SyncbackDraftTask performLocal:
11313 [2017-11-12 20:43:32.087] [main] [info] [local-4d32d062-bb40] -- Succeeded. Changing status to `remote`
11313 [2017-11-12 20:43:32.430] [foreground] [info] Idle exited with code 0
11313 [2017-11-12 20:43:32.432] [foreground] [info] [local-4d32d062-bb40] Running SyncbackDraftTask performRemote:
11313 [2017-11-12 20:43:32.432] [foreground] [info] [local-4d32d062-bb40] -- Succeeded. Changing status to `complete`
11313 [2017-11-12 20:43:32.434] [foreground] [info] Idling on folder INBOX
11313 [2017-11-12 20:43:37.705] [foreground] [info] Idle exited with code 0
11313 [2017-11-12 20:43:37.706] [foreground] [info] Idling on folder INBOX
11313 [2017-11-12 20:44:08.220] [foreground] [info] Idle exited with code 0
11313 [2017-11-12 20:44:08.221] [foreground] [info] Idling on folder INBOX
11313 [2017-11-12 20:44:21.895] [background] [info] Syncing folder list...

11313 [2017-11-12 20:46:27.989] [background] [info] Sync loop deleting unlinked messages with phase 2.
11313 [2017-11-12 20:46:27.999] [background] [info] Sync loop complete.
11313 [2017-11-12 20:46:37.395] [foreground] [info] Idle exited with code 0
11313 [2017-11-12 20:46:37.396] [foreground] [info] Idling on folder INBOX
11313 [2017-11-12 20:46:40.146] [metadata] [info] Metadata delta stream closed.
11313 [2017-11-12 20:46:40.153] [metadata] [info] Metadata delta stream starting...
11313 [2017-11-12 20:46:49.485] [main] [info] [local-0402f263-871c] Running SyncbackDraftTask performLocal:
11313 [2017-11-12 20:46:49.489] [main] [info] [local-0402f263-871c] -- Succeeded. Changing status to `remote`
11313 [2017-11-12 20:46:49.858] [foreground] [info] Idle exited with code 0
11313 [2017-11-12 20:46:49.861] [foreground] [info] [local-0402f263-871c] Running SyncbackDraftTask performRemote:
11313 [2017-11-12 20:46:49.861] [foreground] [info] [local-0402f263-871c] -- Succeeded. Changing status to `complete`
11313 [2017-11-12 20:46:49.864] [foreground] [info] Idling on folder INBOX

**Comment by davduf** [comment] 2017-11-13 21:33
Dear Ben,

Juts to let you know: I delete all my files and folders of Mailspring and start from scratch again, just to see. oups: problems are still there... :-)

Thank you agaon for any idea / help !

**Comment by khman95** [comment] 2017-11-14 23:44
I have two installations on Linux having the same problem for both archive and delete. Also IMAP (Cambridge Hermes). I also have no error message in log file. I am also running 1.0.8

**Comment by davduf** [comment] 2017-11-21 22:57
Dear Ben,

After a fresh install of FEDORA 27 + fresh install of MailSpring, same problems... :-(
Any chance you have time to take a look ?
Thank you again for the great job !

**Comment by davduf** [comment] 2017-11-26 00:20
Any improvement for you @khman95 ?

**Comment by khman95** [comment] 2017-11-26 01:03
@davduf No same issue.

**Comment by davduf** [comment] 2017-12-05 15:45
Same issue with 1.0.9
I am sorry :-)

**Comment by sveinburne** [comment] 2017-12-05 16:11
I notice an interesting subtlety: 
Let's say I have a selection of 30 mails. If I click `SUPPR`, a notification message pops and says "30 threads moved to All Mails". However if I right click on any mail and select "Trash", the popup mentions "30 threads moved to Bin".

**Comment by maxlevesque** [comment] 2017-12-10 13:33
Same issue with 1.0.9 here. Don't know if it has any consequence, but I paid for a premium account.

**Comment by bengotow** [comment] 2017-12-11 20:28
Hey folks, thanks for the reports, this is really interesting and it might be related to #428. 

Can you try opening Mailspring's Preferences and going to `Folders`? There's a section there for each account and it shows which folders Mailspring is using for Archive and Trash. It sounds like Mailspring may be moving your mail to the wrong Trash folder, which doesn't work.

<img width="680" alt="image" src="https://user-images.githubusercontent.com/1037212/33852231-94e3836e-de6e-11e7-9097-f321d1605bb4.png">

Try clicking the dropdown beside Trash and see if you see any other trash folder listed there. Switching to that one may resolve the issue.

I'm going to do some more research and see if there are any other scenarios in which this can happen.

**Comment by maxlevesque** [comment] 2017-12-11 20:48
Hey there,
The folders look fine to me, and changing INBOX.Trash to anything with relevent name does not solve the problem. Thanks anyway for digging in !

![screenshot from 2017-12-11 21-47-55](https://user-images.githubusercontent.com/1818339/33853083-fccef370-debc-11e7-8c0e-f7b0dbf2001c.png)

**Comment by bengotow** [comment] 2017-12-12 02:02
Hey folks—I think we've figured this out in #364. Mailspring required the IMAP `MOVE` extension to actually place messages in the trash, archive, etc. and it seems a fair number of providers still don't support that extension. In 1.0.11, we'll fall back to the very old school approach of `COPY, STORE, DELETE`.  It's a bit slower but should ensure that deleting / archiving messages works absolutely everywhere.

Sorry for the hassle—I'm going to continue testing the fix but 1.0.11 should ship in a couple days.

**Comment by bengotow** [comment] 2017-12-18 23:15
Hey folks - this has shipped in 1.0.11. The app will download the update automatically, but you can get it directly here: https://www.getmailspring.com/download. Gonna go ahead and close this—if you continue to have trouble after the update, let me know and I'll re-open it!

**Closed by bengotow** 2017-12-18 23:15 UTC
Labels: bug, done-pending-release, mailserver-incompatibility, needs-reproduction

**Comment by khman95** [comment] 2017-12-20 02:32
I can confirm that the issue is solved for me, thanks for the work!
