### ISSUE TITLE
Bug: Error typing email

### ISSUE THREAD

**Issue by aletc1** [Foundry376/Mailspring#2073] opened 2020-06-26 07:29 UTC
**Describe the bug**
When typing, sometimes, the keyboard hangs, doesn't write, and you cannot move the cursor. Also get the error in the screenshot section. If you close and reopen the app, the issue disappear, and the written text is there but in other location, not where the cursor was.

**To Reproduce**
It is random, but it is not a one-time thing. It happened to me a lot. Usually when changing the language with the keyboard to Spanish, and when putting accents in the works like á é í, etc. To create the accent a key combination is used (`and the letter). Also, it always happened when reply, not when you write a new email.

**Expected behavior**
Write an email reply without issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/14905652/85831329-6c64b600-b78e-11ea-9acc-dee7affd53a2.png)
![image](https://user-images.githubusercontent.com/14905652/85832168-dc277080-b78f-11ea-8bc2-790aa09728d7.png)

**Setup: (please complete the following information):**
 - OS: macOS
 - OS Version 10.15.5
 - Mailspring Version: 1.7.8 (1.7.8)

**Additional context** 
Writing an email with Mailspring starts to bothers me, since this issue is appearing more often.

**Comment by CodeMouse92** [comment] 2021-03-02 03:30
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/error-typing-email/923

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@aletc1: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 03:30 UTC
Labels: audit, bug
