### ISSUE TITLE
mailspring doesnt show new messages in task tray icon.

### ISSUE THREAD

**Issue by sniperfull** [Foundry376/Mailspring#692] opened 2018-02-15 15:41 UTC
im on windows 10 and i have the notifications turned on, but it doesnt always display new messages... sometimes i have received many emails but they dont show up as new messages in the task tray. im on the latest version of mailspring.

**Comment by CodeMouse92** [comment] 2021-01-30 02:10
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/badge-doesnt-always-appear-on-app-indicator-when-receiving-new-mail/392

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-30 02:10 UTC
Labels: audit
