### ISSUE TITLE
Bug: Messages are sent twice with an Outlook account

### ISSUE THREAD

**Issue by RustBeard** [Foundry376/Mailspring#2148] opened 2020-09-18 14:39 UTC
**Describe the bug**
When I send messages via Mailspring, where I have an account with outlook.com attached, I see two messages sent. I have it every time. 
I also have a gmail.com account connected and there are no such problems. 

**To Reproduce**
1. Click on the 'compose new message' icon.
2. Send a message to any e-mail address. It is important that you do this from a connected account with an outlook.com or hotmail.com ending. 
3. Check this message in the 'sent' folder (or in the inbox thread if you replying).
4. You will see the two same messages. 

**Expected behavior**
When I send one message, I would like to send it only once and see it as one in the sent box. 

**Screenshots**
![Screenshot-2020-09-18-163238](https://user-images.githubusercontent.com/13813117/93610485-69fcab80-f9cd-11ea-8bec-6ce884f53d76.jpg)

**Setup: (please complete the following information):**
 - OS: Windows 10
 - OS Version 10.0.18363 Build 18363
 - Mailspring Version: ex: 1.7.8-13635bcf

**Comment by arabsight** [comment] 2020-09-19 11:09
I've been having this for a long time, I thought it was by design, lol

**Comment by Dobeb96** [comment] 2020-09-21 17:51
Same here, pasting a screenshot where three emails are visible in my Mailspring.

This email was sent to two recipients (both in "to", not "cc"). I confirmed with one of the recipients that he has received my email only once, which is comforting, but still it makes me wonder if there are some recipients that indeed get duplicated emails.

I'm using Linux, email was sent from an Outlook account. This screenshot is from April so it might be using older Mailspring version, but I also have sent an email today, and it was also duplicated - and this time it was on Mailspring 1.7.2

![mailspring_bug](https://user-images.githubusercontent.com/18633831/93801748-c0beeb00-fc42-11ea-9786-4c0f3cfbfe5d.png)

**Comment by mishabhi** [comment] 2020-09-24 04:10
> **Describe the bug**
> When I send messages via Mailspring, where I have an account with outlook.com attached, I see two messages sent. I have it every time.
> I also have a gmail.com account connected and there are no such problems.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
>     1. Click on the 'compose new message' icon.
> 
>     2. Send a message to any e-mail address. It is important that you do this from a connected account with an outlook.com or hotmail.com ending.
> 
>     3. Check this message in the 'sent' folder (or in the inbox thread if you replying).
> 
>     4. You will see the two same messages.
> 
> 
> **Expected behavior**
> When I send one message, I would like to send it only once and see it as one in the sent box.
> 
> **Screenshots**
> ![Screenshot-2020-09-18-163238](https://user-images.githubusercontent.com/13813117/93610485-69fcab80-f9cd-11ea-8bec-6ce884f53d76.jpg)
> 
> **Setup: (please complete the following information):**
> 
>     * OS: Windows 10
> 
>     * OS Version 10.0.18363 Build 18363
> 
>     * Mailspring Version: ex: 1.7.8-13635bcf

yes I am also facing same issue.

**Comment by ItsNewe** [comment] 2021-01-06 13:39
Still experiencing this issue in 2021. Arch Linux, Mailsprint 1.7.8-13635bcf
I've sadly had to put Mailspring to the side because of this issue :(

**Comment by CodeMouse92** [comment] 2021-01-29 22:29
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/duplication-of-sent-mail/275

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-29 22:29 UTC
Labels: audit, bug
