### ISSUE TITLE
Encounters error while syncing accounts after updating to Ubuntu 20.04

### ISSUE THREAD

**Issue by lewis-m** [Foundry376/Mailspring#2121] opened 2020-08-17 13:54 UTC
##### What is the behavior you're seeing?
Mail not syncing for any accounts, going into preferences gives this detailed error message (for gmail, but analogously for other accounts):

Mailspring Version: 1.7.8-13635bcf
Platform: linux
Account State: sync_error
Account Provider: gmail
IMAP Server: imap.gmail.com
SMTP Server: smtp.gmail.com
--------------------------------------------
18383 [2020-08-15 23:16:29.380] [background] [info] - Updating message 71zqkev3QmC3EphtQFbTprivRHL9PMo3TpELjkHZM
18383 [2020-08-15 23:16:29.380] [background] [info] -- UID (882 to 669)
18383 [2020-08-15 23:16:29.380] [background] [info] -- XGMLabels (["[Imap]/Sent"] to ["\\Sent"])
18383 [2020-08-15 23:16:29.383] [background] [info] - Updating message CZb1pYSjjjPcVfwm62njhyxrKiLgXYzmu6Dr3oKh9
18383 [2020-08-15 23:16:29.383] [background] [info] -- UID (668 to 667)
18383 [2020-08-15 23:16:29.383] [background] [info] -- XGMLabels (["[Imap]/Sent"] to ["\\Sent"])
18383 [2020-08-15 23:16:29.626] [background] [info] syncFolderUIDRange for [Gmail]/Bin, UIDs: 1 - 0, Heavy: false
18383 [2020-08-15 23:16:29.888] [background] [info] - remote=20, local=20
18383 [2020-08-15 23:16:30.012] [background] [info] syncFolderUIDRange for [Gmail]/Spam, UIDs: 1 - 0, Heavy: false
18383 [2020-08-15 23:16:30.272] [background] [info] - remote=7, local=7
18383 [2020-08-15 23:16:30.273] [background] [info] Sync loop deleting unlinked messages with phase 1.
18383 [2020-08-15 23:16:30.275] [background] [info] Sync loop complete.
18383 [2020-08-15 23:16:58.404] [metadata] [info] Metadata delta stream closed.
18383 [2020-08-15 23:16:58.411] [metadata] [info] Metadata delta stream starting...
18383 [2020-08-15 23:18:30.276] [background] [info] Syncing folder list...
18383 [2020-08-15 23:18:30.563] [background] [info] syncFolderUIDRange for [Gmail]/All Mail, UIDs: 9748 - 10332, Heavy: false
18383 [2020-08-15 23:18:30.993] [background] [info] - remote=400, local=400
18383 [2020-08-15 23:18:31.179] [background] [info] syncFolderUIDRange for [Gmail]/Bin, UIDs: 1 - 1136, Heavy: false
18383 [2020-08-15 23:18:31.587] [background] [info] - remote=20, local=20
18383 [2020-08-15 23:18:31.714] [background] [info] syncFolderUIDRange for [Gmail]/Spam, UIDs: 1 - 599, Heavy: false
18383 [2020-08-15 23:18:32.016] [background] [info] - remote=7, local=7
18383 [2020-08-15 23:18:32.017] [background] [info] Sync loop deleting unlinked messages with phase 2.
18383 [2020-08-15 23:18:32.022] [background] [info] Sync loop complete.
18383 [2020-08-15 23:20:32.023] [background] [info] Syncing folder list...
18383 [2020-08-15 23:20:36.769] [background] [info] syncFolderUIDRange for [Gmail]/All Mail, UIDs: 9748 - 10332, Heavy: false
18383 [2020-08-15 23:20:37.180] [background] [info] - remote=400, local=400
18383 [2020-08-15 23:20:37.321] [background] [info] syncFolderUIDRange for [Gmail]/Bin, UIDs: 1 - 1136, Heavy: false
18383 [2020-08-15 23:20:37.747] [background] [info] - remote=20, local=20
18383 [2020-08-15 23:20:37.952] [background] [info] syncFolderUIDRange for [Gmail]/Spam, UIDs: 1 - 599, Heavy: false
18383 [2020-08-15 23:20:38.362] [background] [info] - remote=7, local=7
18383 [2020-08-15 23:20:38.364] [background] [info] Sync loop deleting unlinked messages with phase 1.
18383 [2020-08-15 23:20:38.368] [background] [info] Sync loop complete.

##### What email provider (Gmail, Exchange, etc.) are you trying to use?
Issue with Gmail, Outlook, and custom IMAP

##### What operating system are you using?
Ubuntu 20.04.1 LTS. Problem is occurring since updating from Ubuntu 18

##### What version of Mailspring are you using?
1.7.8-13635bcf
(eg: 1.6.3 or 1.7.0 - this is shown in Mailspring's main menu.)

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Error occurs while syncing. Cannot start new message or receive emails. Issue occurs for all accounts.

**Comment by lewis-m** [comment] 2020-08-18 12:06
This is now working again, I don't know why. I had tried restarting my computer before, which did not resolve it, but it worked after I started my computer this morning without doing anything else. I can also add that the mail accounts did work in another mail app (Thunderbird) throughout. I am not sure if this closes the issue?

**Comment by CodeMouse92** [comment] 2021-02-01 18:27
Actually, I think this is related to an ongoing issue, which we've already migrated to our new Discourse:

https://community.getmailspring.com/t/syncfolderuidrange-errorconnection-on-one-of-the-folders/412

Please consider joining that community and continuing the discussion there!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38). We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

**Closed by CodeMouse92** 2021-02-01 18:27 UTC
Labels: audit, bug, mailserver-incompatibility, needs-reproduction
