### ISSUE TITLE
More than half of a message being composed got suddenly deleted, and cannot be restored

### ISSUE THREAD

**Issue by kerabromsmu** [Foundry376/Mailspring#851] opened 2018-05-07 10:12 UTC
I was composing a rather long e-mail (maybe 50 lines of text and an image), and suddenly more than half of the entered text and image was gone. Actually, it suddenly fell back to some old state, before much of the text was edited. This happened while I was moving the cursor around in the text. Pressing Ctrl+Z or Ctrl+Shift+Z had no effect, more than half of the message was just gone beyond restoring. Restarting Mailspring didn't help either.

##### Are there any related issues?
Couldn't find any

##### What operating system are you using?
Linux Mint 18.3, kernel 4.15.0-15-generic

##### What version of Mailspring are you using?
1.2.1-7e7447b6

--

**Bug?**
Most certainly.

##### Do you have any third-party plugins installed? If so, which ones?
None installed

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I use one.com as the e-mail provider. No idea if this is specific to provider.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Apparently, this is more probable to happen if there is an image or images pasted into the message text, and you run the text cursor through the position of the image with arrow keys. The other hypothesis is this is more probable when you have bullet points in your message, and you run the cursor beyond the last of the first bullet point in the list.

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Haven't seen such a "feature" since maybe the 90s in any other mail client. Better remove this "feature".

**Comment by lnpalmer** [comment] 2018-05-08 13:50
+1! This happened to me twice before I realized that cursor movement was involved, and the whole message was deleted, augh

**Comment by dialed** [comment] 2018-05-16 02:22
This happens quite often to me too. Not sure if it matters but I have noticed it while typing work emails the most which are office365.

**Comment by kleinschmidt** [comment] 2018-08-22 19:29
Same here (Arch linux, Mailspring 1.4.2).  Most recently triggered when I pressed ctrl-D to forward delete one character.  the cursor jumped to the To: field and half the message was deleted.

**Comment by remokon** [comment] 2018-10-05 12:47
It happened to me as well in Ubuntu 18.04 several times, and it was extremely frustrating. 
I am temporarily switching back to gmail, I cannot imagine losing 20 minutes of work again like today. Twice.  :disappointed:

**Comment by BinaryPaean** [comment] 2020-02-21 19:50
I've seen this (or what seems like this) on Windows 10 / Mailspring 1.7.2-

**Comment by CodeMouse92** [comment] 2021-02-11 00:01
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/more-than-half-of-a-message-being-composed-got-suddenly-deleted-and-cannot-be-restored/564

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@kerabromsmu: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-11 00:01 UTC
Labels: audit
