### ISSUE TITLE
Synchronize inbox settings in the cloud

### ISSUE THREAD

**Issue by brunofin** [Foundry376/Mailspring#796] opened 2018-04-03 17:21 UTC
For those who own multiple computers or have to dual-boot, since we already have to create an account and login to use Mailspring, it would be game-changing to have all settings synchronized across installations, including:

* All inbox configured;
* Individual signatures;
* Templates;
* User settings.

These could be a Pro features and I would happily subscribe to have it.

Regards.

**Comment by jcrben** [comment] 2018-06-17 15:49
Are settings configurable via a file that I can commit to my dotfiles?

**Comment by CodeMouse92** [comment] 2021-02-05 01:12
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/sync-templates-signatures-accounts-etc-accross-multiple-devices/265

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-05 01:12 UTC
Labels: audit
