### ISSUE TITLE
Occupying GPU memory when minimized (Linux)

### ISSUE THREAD

**Issue by PowerSnail** [Foundry376/Mailspring#1484] opened 2019-05-03 19:21 UTC
##### Are there any related issues?

I don't think there is a similar issue.

##### What operating system are you using?

Linux (ubuntu 19.04)

##### What version of Mailspring are you using?

16.1

--

**Bug?**

##### Is this an email sync or connection issue?

No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Not Applicable.

--

Mailspring, when minimized to tray icon, still occupy a significant amount of GPU memory. Since there is nothing to render, is this necessary?

Here are some screenshots: 

fig1: Mailspring open
![b](https://user-images.githubusercontent.com/7428673/57160390-a1f25700-6db6-11e9-90aa-dc08581130d9.png)

fig2: Mailspring minimized to tray icon

![c](https://user-images.githubusercontent.com/7428673/57160399-a7e83800-6db6-11e9-83ae-ddfe1b37b4fe.png)

fig3: Mailspring quit

![d](https://user-images.githubusercontent.com/7428673/57160400-aa4a9200-6db6-11e9-81ab-27c35655aee4.png)

As you can see, if we include the extra memory put on xorg process, Mailspring takes 200+ MB GPU memory even when there is nothing to render.

Thank you for this application.

**Comment by bengotow** [comment] 2019-05-26 19:23
Hey! Thanks for reporting this — this is super interesting, actually. Right now, minimizing Mailspring is roughly equivalent to opening a window in Chrome and minimizing it (under the hood, Mailspring uses Electron + Chromium). I think that doing this really should free the GPU memory, but Chromium probably keeps the underlying page resources intact.

I'll see if we can improve this in the future—we'd probably need to close, rather than minimize, the Electron window (which would come with some downsides - the window takes 500ms+ to load, so showing the window again would be slower), to fully release the graphics memory, but I'll check.

**Comment by PowerSnail** [comment] 2019-06-25 02:20
@bengotow 
I propose a workaround that is pretty simple: have an option to close Mailspring (instead of to tray) when click (X) button. It solves the memory problem, with a trade-off for slower start time.

I'm using the latest Gnome now which does even have a tray anyway. I think this is the case for Elementary OS as well. As a result, minimizing to system tray is not really meaningful on these desktops. 

I personally find that the start time of Mailspring to be okay. It is not instant, but well within my tolerance. The difference between opening Mailspring and restoring from tray is quite small. 

Thanks.

**Comment by CodeMouse92** [comment] 2021-02-16 01:24
@PowerSnail Is this still a problem in 1.8.0? If so, please open a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

Meanwhile, **is this perhaps a problem specific to the Snap? That seems to have significant overhead compared to the native package.** If you create the bug report, please include that detail. (I cannot reproduce this on Mailspring 1.8.0 and Ubuntu 20.04, but I'm using the native package.

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-16 01:24 UTC
Labels: audit, linux, performance
