### ISSUE TITLE
Annoying "are you sure" warnings

### ISSUE THREAD

**Issue by intradesign** [Foundry376/Mailspring#709] opened 2018-02-19 16:55 UTC
Hi, there is always a "are you sure" warning popping up when I just want to send an email to "Chris". Is this because of the "Hi Chris," in the email bosy or something else?
Is it possible to completely disable a warning like this?

Thanks and best regards, Timo

**Comment by RomanKlopsch** [comment] 2018-02-25 14:31
As far as i know there is currently no option to disable confirmation dialogues but i agree to you , that there should be one

**Comment by CodeMouse92** [comment] 2021-02-15 21:08
Duplicate of #1201

**Closed by CodeMouse92** 2021-02-15 21:08 UTC
Labels: audit
