### ISSUE TITLE
Bug: incorrect email content being rendered

### ISSUE THREAD

**Issue by nthfloor** [Foundry376/Mailspring#2066] opened 2020-06-23 15:11 UTC
**Describe the bug**
I am using MailSpring (v1.7.8) on MacOS and have it linked up to 3 gmail accounts. I have recently started to experience a bug where the wrong email gets rendered when I click on a separate email. Often the incorrect email that gets rendered is an email I have viewed recently and trashed.

**To Reproduce**

I am unable consistently reproduce this, but these are the steps I followed to experience the issue:

1. Ensure you have 3 gmail accounts loaded into Mailspring (not sure if this is related to the issue or not)
2. Delete/trash a recently received email
3. Wait a while
4. Send a new email to this same email account
5. Open the new email
6. Sometimes, you'll see the recently trashed email rendered instead of the new email content
7. This issue then persists with this particular email, by consistently rendering the wrong email content even after I restart Mailspring
8. Issue goes away when I reset the cache

**Expected behavior**
I am expecting that the correct email content gets rendered when I click on an email

**Screenshots**
nothing relevant atm

**Setup: (please complete the following information):**
 - OS: macOS
 - OS Version 10.15.4
 - Mailspring Version: ex: 1.7.8 (found in the app's menu)

**Additional context** 
I have 3 gmail accounts

**Comment by CodeMouse92** [comment] 2021-03-02 03:13
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/incorrect-email-content-being-rendered/920

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@nthfloor: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 03:13 UTC
Labels: audit, bug
