### ISSUE TITLE
Simple MAPI Support

### ISSUE THREAD

**Issue by michel-cote** [Foundry376/Mailspring#1947] opened 2020-04-28 06:30 UTC
For proper setting of Mailspring as a the default email client for Windows, the email client is required to support Simple-MAPI.   

As the current version does not, so emailing does NOT work from Windows File Explorer (ie. Send to...email recipient), and from all other Windows programs that provide a "Send as email attachment".

This applies to all Windows versions (7, 8.x, 10)

This may seem like an old technology (which it is), but many new printers that have a scan-to-email function in their software tools, requires a MAPI complaint default mail client.

**Comment by CodeMouse92** [comment] 2021-02-27 03:48
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/simple-mapi-support/862

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@michel-cote: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-27 03:48 UTC
Labels: audit, enhancement
