### ISSUE TITLE
[Feature Request] Option to show attachments at the top of email

### ISSUE THREAD

**Issue by readsquirrel** [Foundry376/Mailspring#738] opened 2018-03-02 16:21 UTC
##### Are there any related issues?
No
...

##### What operating system are you using?
MacOS 10.13.3

##### What version of Mailspring are you using?
1.1.4

--

**Feature Request?**
It would be very helpful to have the option to see documents that were attached to a received email below the header but above the message itself rather than at the bottom of the email.

##### Does this feature exist in another mail client or tool you use?
The current behavior of Mailspring is the same as (and the reason why I don't use) Apple Mail. Attachments are important for my workflow, and making sure that I don't miss an attached document is one of the most important features of a mail program. Outlook shows attachments below the email information and above the message body as I am suggesting. Another useful implementation that I've seen is Postbox shows them in the sidebar. Either works great.

Thank you for considering!

**Comment by bengotow** [comment] 2018-03-06 23:48
Hey! I actually haven't seen this before but it seems like a great idea. I imagine we'd want to make the display of attachments a bit "narrower" than it currently is when they're shown at the bottom of the message, but I like it.

**Comment by readsquirrel** [comment] 2018-03-07 14:24
That's great news. Narrow/smaller styling makes sense, but there's less of a need to see the small preview at the top, I think. Thank you!

**Comment by enoversum** [comment] 2018-03-08 09:12
The problem with the current way is that it sometimes takes literally ages of scrolling when you have loooong messages (or those that fail to cut out previous messages, hence show the whole bloody conversation in a long towel). Showing attachments at the top in a neat and compact way would be quite helpful, @bengotow 😉 .

**Comment by Nisgrak** [comment] 2021-01-12 10:09
@bengotow Any updates on this?

**Comment by CodeMouse92** [comment] 2021-02-24 22:16
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/option-to-show-attachments-at-the-top-of-email/772

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@readsquirrel @enoversum: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-24 22:16 UTC
Labels: audit, enhancement
