### ISSUE TITLE
AUR package [Results in SSL errors]

### ISSUE THREAD

**Issue by b0o** [Foundry376/Mailspring#13] opened 2017-10-04 03:48 UTC
It would be great to have an AUR package for Mailspring. 

I tried to get it running manually by cloning the repo, running running `npm install` and `npm start` but keep getting errors like the following:

![2017-10-03-20-45-25](https://user-images.githubusercontent.com/21299126/31159148-d97ebfd0-a87b-11e7-94e0-4d95234d120a.png)

I tried finding/installing the correct package providing the noted libraries, but had trouble finding the right versions of most of them.

**Comment by ConorIA** [comment] 2017-10-04 03:50
That would be `icu52` from the AUR, I think.

**Comment by b0o** [comment] 2017-10-04 04:05
@ConorIA 

Thanks! The icu52 package solved that error, but now I'm getting this:

`libcurl.so.4: version `CURL_OPENSSL_3' not found`

Searching for that error, I found this thread: https://bbs.archlinux.org/viewtopic.php?id=187871

If that's correct, Mailspring is requiring an old version of libcurl? I'd rather not have to install an old version just for one application to work. For some other libraries I've installed (like libtidy and libctemplate), I couldn't find the exact same version, so I tried to just symlink Mailspring's expected version to the closest version I could find, just to see if I could get things to work at all.

I'm curious to know if you're able to get Mailspring running on Arch?

**Comment by bengotow** [comment] 2017-10-04 05:34
Hey! How do you guys feel about snapcraft.io? The current plan is to release a single "containerized" Snap package for all linux distros, because it makes things easy for developers and supports autoupdate (which is fairly challenging to do across distros on Linux). I've been talking with a few folks at Canonical and the Snap should be ready by the end of the week.

Also working on that libicuuc issue—I've changed the app to statically link against most of it's library dependencies, and for the handful left (like libicuuc), I'm hoping to package them into the app so you don't need to install them separately (total, they're only ~3MB)

**Comment by el-psycho** [comment] 2017-10-04 05:55
I'd prefer a flatpak http://flatpak.org/ since I'm not an Ubuntu user (I'm on Fedora). I know a snap technically should work too. I dont know what the status for snaps vs flatpaks is today, which is easier, more popular, etc. but I think flatpaks are available in more distributions than Ubuntu's snaps.

**Comment by ktw** [comment] 2017-10-04 06:04
A snap would be great for us Solus users.

**Comment by faasie** [comment] 2017-10-04 12:46
Personally, I'd lean more towards flatpak...but that's ONLY because I'm more familiar with it. Though, it looks like Snap is pretty widely available.

Install docs indicate:

- Arch Linux
- Debian
- Fedora
- Gentoo
- OpenEmbedded/Yocto
- openSUSE
- OpenWrt
- Solus
- Ubuntu

*shrug* I'm just looking forward to getting it installed!

**Comment by Aletheia-Lothlorien** [comment] 2017-10-04 13:12
And/or would [AppImage](https://appimage.org/) meet your needs? I've had great success with them as a user on different systems, though I've never developed for it.

Can't wait for this!

**Comment by ConorIA** [comment] 2017-10-04 13:40
AppImage is nice for those who don't want the extra overhead. It doesn't check off @bengotow's autoupdate requirement though. I'd personally just prefer a .Deb for someone on the AUR to tear open and package up nice and clean for Arch(-derivs).

**Comment by Aletheia-Lothlorien** [comment] 2017-10-04 13:57
@ConorIA Very true. The AppImage devs say that is by design (offer pre-packaged apps and let users decide where to install, whether to update, etc.). I seem to have glossed over that requirement. Thanks. And I, too, would prefer an AUR package.

**Comment by ConorIA** [comment] 2017-10-04 23:01
Ok. Prototype PKGBUILD for you: https://gist.github.com/ConorIA/b8c7c3ef6d70902dff169afbbbff7d2b
Build with `makepkg`.

I do not plan to submit this to the AUR until there is clarity over whether or not @bengotow will continue to provide `.deb`s or just snaps. There is also a nasty shared library workaround that is probably not allowed for AUR standards (see the end of the PKGBUILD). Please comment on the gist if depends should be added and/or removed. Let's also not annoy @bengotow about bugs/issues unless we're sure they are in Mailspring and not in this PKGBUILD.

**Comment by b0o** [comment] 2017-10-04 23:14
@ConorIA 

You're a badass. That worked PKGBUILD flawlessly, thank you!

**Comment by ConorIA** [comment] 2017-10-04 23:22
@b0o, just make sure you have `gnome-keyring` installed. I got my depend wrong!
Also, I'm gettting SSL errors trying to add accounts! :cry:

**Comment by b0o** [comment] 2017-10-04 23:24
@ConorIA Yeah, I'm getting those SSL errors as well. For now I checked the 'insecure stmp/imap' boxes.

**Comment by Aletheia-Lothlorien** [comment] 2017-10-05 00:14
@ConorIA Thank you so much! Much appreciated. Getting those SSL errors as well, but until I investigate further I'm following @b0o's lead in allowing insecure connections. Thanks.

**Comment by step21** [comment] 2017-10-05 23:41
+1 for deb or snap. Flatpak might work too but please no AppImage. It is just like one big blob lying around randomly in your filesystem, that even hast be made executable manually ^^ (I'm also fine with just running it from the github source, if I can tell it where the sync engine is)

**Comment by kolletzki** [comment] 2017-10-06 17:40
FYI: Somebody has created an AUR package: https://aur.archlinux.org/packages/mailspring/
Sadly, I'm getting SSL errors as well :confused:

**Comment by bengotow** [comment] 2017-10-08 16:46
Hey folks! Please do not replace libsasl2.so with a different version - you'll get SSL errors, certificate problems authenticating with SMTP, etc., or it just won't run at all. The .deb package should contain the correct version of libsasl2 already alongside the `mailsync.bin` file!

**Comment by ConorIA** [comment] 2017-10-09 01:23
@bengotow, if we don't link `libsasl2.so.2`, Mailspring complains about the missing library and doesn't launch. I've [tried](https://gist.github.com/ConorIA/b8c7c3ef6d70902dff169afbbbff7d2b) linking to `/usr/share/mailspring/resources/app.asar.unpacked/libsasl2.so.2`, but this didn't solve the issue either. I guess I'm *really* looking forward to the snap! 😛 Thanks for your work on Mailspring!

**Comment by bengotow** [comment] 2017-10-10 19:25
Hey folks—the `libsasl2` should be fixed in the next release. It'll definitely be nice to have the Snap build, but in 1.0.3 (coming later today) it should at least be possible to build a working AUR!

**Comment by dmeijboom** [comment] 2017-10-11 07:31
I think this issue can be closed. The AUR package is working just fine with the 1.0.3 release. :)

**Comment by JunnanZ** [comment] 2017-10-11 09:37
I'm using the newest AUR package and I got this error:

> Waiting for Account JSON:
> Waiting for Identity JSON:
> {"error":"Identity is missing required fields."}

Just this, nothing else. Anybody knows why?

**Comment by rezhajulio** [comment] 2017-10-11 10:43
I have the same problem like @JunnanZ with AUR package

**Comment by jGleitz** [comment] 2017-10-11 11:31
I have the same problem as @JunnanZ but with the .deb package (version 1.0.3 on Ubuntu 17.04).

**Comment by ZakharH** [comment] 2017-10-11 11:35
I also have the same problem. Not sure if we should create a separate issue or piggyback on the end of this one though

**Comment by jGleitz** [comment] 2017-10-11 11:42
@ZakharH you are right; we should create a new issue as this is apparently not specific to the AUR package. See #123.

**Closed** 2017-11-02 18:35 UTC
Labels: done-pending-release, linux
