### ISSUE TITLE
[Feature Request] Mark folder as read/unread

### ISSUE THREAD

**Issue by fakeid30** [Foundry376/Mailspring#159] opened 2017-10-14 07:28 UTC
**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Thunderbird 
...

**Comment by rovingrambler** [comment] 2017-10-31 12:26
I'm looking for mark all in folder as read too.

**Comment by rafrsr** [comment] 2017-11-07 00:30
I'm too, it's a very helpful feature 👍

**Comment by vnpnlz** [comment] 2017-11-09 08:15
I'm waiting for this feature too!

**Comment by AndreaBarghigiani** [comment] 2018-01-08 08:40
I am wondering, it is possible to select all emails in the account inside the unread folder and mark them as read? 

I've been syncing an email account where previously forwarded all the messages and now I have thousands of emails that need to be read.

**Comment by raqua** [comment] 2018-02-08 13:41
+1 on this.

**Comment by Harlock123** [comment] 2018-02-28 15:50
+1

Its a shame to have to boot up another app just to clean up a set of folders with those annoying unread messages  (Mostly crap ads for various wonder drugs and male enhancement)

**Comment by readsquirrel** [comment] 2018-03-02 16:26
This would be a good time saver. +1

**Comment by ramy-ahmed** [comment] 2018-03-21 08:29
+1 saving time.

**Comment by alejdg** [comment] 2018-04-09 15:53
+1

**Comment by alejdg** [comment] 2018-04-09 16:10
I'm using a workaround to mark all as read due to a limit on how much you can select using the "select all" command (200 messages). 

- Search for "is: unread"
- ^A to select all the messages (more than 200 messages will be selected)
- Click mark as read

**Comment by Harlock123** [comment] 2018-04-09 16:41
Except Crappy CTRL A does not work on LINUX... It does nothing when you lave your list of messages narrowed down to the unread ones in the message list.... (Between the Mailbox folders panel and the preview panel)

Select ALL from the menu does not do so either, only the first one clicked on is actually selected...
You can CTRL and Click to select more than one message... and right mouse button to Mark as Read or Unread depending...

**Comment by alejdg** [comment] 2018-04-10 17:40
@Harlock123 I'm using Linux (Ubuntu Bionic) as well and it works perfectly. Maybe you could try and check your shortcuts. If everything is configured right and the problem persist try filing a bug.

**Comment by SBKubric** [comment] 2018-05-05 03:27
Find a hack to do it more properly: i have a gmail set of shortcuts, so if i press '*' and then 'u' it selects 200 unread messages.

**Comment by sclarkso** [comment] 2018-05-28 23:00
I would like this feature as well.  I get several hundred alert emails overnight, and it would be nice to be able to mark them all as read.

**Comment by lucaspon** [comment] 2018-09-04 02:43
Yes!! Pls add this :) 👍

**Comment by ChristopherBare** [comment] 2018-12-10 04:13
Can I reopen this feature request? This is essential for how I use a mail app.

**Comment by CristalT** [comment] 2019-01-08 22:38
+1 !!

**Comment by matthiasmengel** [comment] 2019-06-03 11:40
+1

**Comment by leoalvs** [comment] 2019-06-04 02:02
+1

**Comment by fredrik84** [comment] 2019-06-10 08:07
+1

**Comment by ibgoldbergs** [comment] 2019-07-24 13:18
+1

**Comment by pentacore** [comment] 2019-07-31 09:50
Why is this still not a thing? +1

**Comment by MatthewScholefield** [comment] 2019-09-17 21:17
@rafaelbecks Ctrl + A only selects all messages in the view. If you have more than around 50 messages in a folder, it only selects the top part of them.

**Comment by nizmogtr** [comment] 2019-10-06 00:19
+1

**Comment by hubris-kubrick** [comment] 2019-10-06 17:20
+1
I need this too

**Comment by MaximOrlovsky** [comment] 2019-11-11 07:08
+1 vote for this feature

**Comment by markoshorro** [comment] 2019-12-11 21:27
+1, I really need this too

**Comment by SayonB** [comment] 2020-01-07 01:18
For people still looking this up, there's a workaround involving rules.

1. Click preferences > Mail Rules
2. Select the account you want to mark as read
3. Create new rule
4. Select the criteria

- From
- Matches Expression
- .*

5. Perform these actions > mark as read
6. At the bottom, press "Process entire inbox"
7. Wait for the inbox to process
8. Delete the rule so all future emails don't get marked as read immediately

Explanation: .* is the regular expression that matches everything, so everything will be selected.

**Comment by kurai021** [comment] 2020-04-03 19:29
+1

**Comment by Kenney-G** [comment] 2020-05-06 14:00
If all it needs is a regex and a drop down to run the function what's the hold up?

**Comment by mpaccione** [comment] 2020-07-02 20:08
Look can we just get this feature implemented I just started using mailspring and naturally I have like 35,000 unread emails and its not great.

I would greatly appreciate, please and thank you.

**Comment by jerinpetergeorge** [comment] 2020-08-11 13:09
> Found a hack to do it more properly: i have a gmail set of shortcuts, so if i press '*' and then 'u' it selects 200 unread messages.

Perfect !!! @SBKubric 

Step 1: `*` + `u`  (to select unread mails)
Step 2: `Shift` + `I`  (to mark as read)

**Comment by CodeMouse92** [comment] 2021-01-28 01:12
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

<<LINK>>

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 01:12 UTC
Labels: audit, enhancement
