### ISSUE TITLE
Additional minor composer bug: copying links

### ISSUE THREAD

**Issue by palefire19** [Foundry376/Mailspring#592] opened 2018-01-30 08:33 UTC
##### Are there any related issues?

Don't think so

##### What operating system are you using?
10.13.2

##### What version of Mailspring are you using?
1.1.2

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Doubt it - composer-related

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Copying text with a link in it seems to break consistently:
1. Find an existing in your inbox with a link in it
2. Copy the text containing that link (note I don't mean right-click to copy link address, I mean actually copying the email body)
3. Start a new email
4. Paste in what you copied
5. For me, I consistently get the text that used to have the link showing up as blue, but no longer actually having a hyperlink

**Comment by bengotow** [comment] 2018-02-03 07:18
Hey! I've been able to reproduce this - this is definitely annoying, especially because it's still highlighted as blue which makes you think it worked. Thankfully it should be an easy fix - stay tuned!

**Comment by bengotow** [comment] 2018-02-09 20:24
Hey folks—version `1.1.3` shipped a few days ago and included the fix for this issue. You should have received the update automatically, but if not you can download it directly from getmailspring.com/download. Enjoy! Gonna go ahead and close this.

**Closed by bengotow** 2018-02-09 20:24 UTC
Labels: bug, composer, done-pending-release
