### ISSUE TITLE
Keeps running after quitting

### ISSUE THREAD

**Issue by HaoZeke** [Foundry376/Mailspring#472] opened 2017-12-23 16:38 UTC
##### Are there any related issues?

No.

##### What operating system are you using?
ArchLinux

##### What version of Mailspring are you using?
1.0.11-ea4b20af

**Bug? Yes**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?
No

##### Details

After quitting the app with the GUI interface I notice that a bunch of spawned processes do not shut down.

This is especially irksome for me as I keep my mail on a fuse-mounted disk which cannot be unmounted without manually killing all these zombie processes.

The attached screenshot will clarify the processes.
![screenshot from 2017-12-23 22-07-50](https://user-images.githubusercontent.com/4336207/34321113-bc042c14-e82d-11e7-9e78-ca9afcc323ae.png)

**Comment by bengotow** [comment] 2017-12-23 17:06
Hey! Thanks for reporting this - the processes should stop ~30 seconds after the app exits... I guess they're staying alive indefinitely on your machine and this isn't temporary?

Looking at the code, it seems like this could happen if the system doesn't "close" the communication stream between the app and the sync process. I'll see if I can reproduce this.

**Comment by HaoZeke** [comment] 2017-12-23 19:07
Some of them do eventually shut down after around 10-12 minutes, but atleast 3 (in my case) seem to persist beyond that...

**Comment by NeroVanbiervliet** [comment] 2018-01-12 07:25
Same issue over here on ubuntu 17.10. Version 1.0.12-cf081332

**Comment by victortrac** [comment] 2018-04-04 15:43
Same issue here on Archlinux. This has been happening on all versions, up to the latest 1.2.1 release today.

**Comment by hunnsdon** [comment] 2018-04-21 10:34
I'm having the same issue with Windows 7.

Also app seems to crash regularly and then processes stay open.

**Comment by stargazer** [comment] 2019-02-20 06:55
Same issue on Ubuntu `18.04.1`, with Mailspring version `1.5.6-4cb1851b`

**Comment by snjvm** [comment] 2020-03-13 23:25
Same issue on Ubuntu 18.04.3, with Mailspring version 1.7.4-d54ff730

**Comment by CodeMouse92** [comment] 2021-01-28 02:39
Thank you for reporting this. 2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/exit-on-x-button-with-no-minimize-to-tray/207

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 02:39 UTC
Labels: audit, linux, needs-reproduction
