### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by naxiand** [Foundry376/Mailspring#1873] opened 2020-03-23 22:01 UTC
**To Reproduce**
1. Go to 'https://snapcraft.io/install/mailspring/manjaro#install'

Although it works with Gmail accounts with IMAP I get a success message but nothing happens. Account is not shown

**Setup: (please complete the following information):**
Operating System: Manjaro Linux 
KDE Plasma Version: 5.18.3
KDE Frameworks Version: 5.67.0
Qt Version: 5.14.1
Kernel Version: 5.4.24-1-MANJARO
Mailspring: 1.7.4 d54ff730

**Comment by zhengyi-yang** [comment] 2020-03-24 02:20
I have the same issue on Ubuntu. i have added different accounts but none of them are shown.

**Comment by Lubell** [comment] 2020-03-24 09:07
Seems to be a duplicate of #1857

**Comment by bengotow** [comment] 2020-04-16 01:23
Hey folks! Yep—this is a pretty nasty bug and will be fixed in the upcoming release tomorrow, thanks for your patience, I'm really sorry it's taken me so long to push the fix out.

**Comment by bengotow** [comment] 2020-04-22 22:14
Hey folks, thanks for reporting this. Happy to say this has been resolved in 1.7.6 which shipped this afternoon. 🚀  The app should auto-update, but if it doesn't you can also grab the new release from GitHub's Releases tab or from https://getmailspring.com/download. Thanks for your patience and help tracking this down, enjoy the update!

**Closed by bengotow** 2020-04-22 22:14 UTC
Labels: bug, done-pending-release
