### ISSUE TITLE
Feature Request: Allow option to undo "show all images from this sender"

### ISSUE THREAD

**Issue by harshitgarg22** [Foundry376/Mailspring#2067] opened 2020-06-23 20:09 UTC
**Is your feature request related to a problem? Please describe.**
I mistakenly clicked on `Always show all images from this sender`.

**Describe the solution you'd like**
It'd be nice to have an option that allows you to undo the white-listing of specific senders.

**Describe alternatives you've considered**
None? I'm not aware of any.

**Additional context**
None.

**Comment by CodeMouse92** [comment] 2021-03-02 03:15
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/allow-option-to-undo-show-all-images-from-this-sender/921

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@harshitgarg22: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 03:15 UTC
Labels: audit, enhancement
