### ISSUE TITLE
Features Request: Customizeable Swipe Actions

### ISSUE THREAD

**Issue by fanvyr** [Foundry376/Mailspring#1938] opened 2020-04-25 12:15 UTC
Like in other Mail apps:
- half / full swipe
- customize the swipe actions

Like
delete, move, snooze, reply, forward, archive, ...

**Comment by bengotow** [comment] 2020-04-26 06:57
Related: #760, #997

**Comment by CodeMouse92** [comment] 2021-02-03 18:14
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/customizable-swipe-button-actions/444

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-03 18:14 UTC
Labels: audit, enhancement
