### ISSUE TITLE
Feature Request: Allow opening of the client by double-clicking (or single-clicking) the systray icon in Linux. 

### ISSUE THREAD

**Issue by gardotd426** [Foundry376/Mailspring#1969] opened 2020-05-06 06:17 UTC
**Is your feature request related to a problem? Please describe.**
Regardless of operating system, it's a pretty universal feature to be able to open applications by double or single-clicking their icon in the system tray. However, with Mailspring on Linux, this doesn't work. In order to get the app to restore, I have to right-click on the systray icon, and click "restore." This is maddening, especially with the muscle-memory of every other app and systray item being activated by a single or double left-click. 

**Describe the solution you'd like**
To be able to restore the desktop application on Linux by just clicking or double clicking on the systray icon, or at LEAST include the option in the Preferences menu. 

**Describe alternatives you've considered**
None that I'm aware of. 

**Additional context**
Like I said, this is a thing in essentially every other app I've ever heard of that has a system tray icon. Mailspring is the only app I've ever used, on Linux or Windows, that doesn't allow for this. 

Also, I'm just curious, is there any way to donate to this project? It's fantastic to have such a professional-grade open-source desktop email client on Linux, but I am not really able to pay 8 dollars a month for a subscription, but I WOULD like to be able to make a one-time donation from time to time, but can't find anywhere to do that.

**Comment by CodeMouse92** [comment] 2021-02-16 01:20
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/double-single-click-on-tray-icon-doesnt-open-app/37

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-16 01:20 UTC
Labels: audit, enhancement
