### ISSUE TITLE
Feature request: save an email in eml format

### ISSUE THREAD

**Issue by phamhung77** [Foundry376/Mailspring#1012] opened 2018-08-10 09:54 UTC
##### Does this feature exist in another mail client or tool you use?
Yes, Mac Mail.

##### Why need this feature?
Sometimes I receive spam messages and would like to save those spam in EML format, so I can upload to our antispam filters for training them.

**Comment by bengotow** [comment] 2018-08-15 02:05
Hey! Thanks for reporting this—I think we may be able to add this in the near future. The app internally works with the RCF 2822 format, we just need to allow it to be exported.

**Comment by dibley1973** [comment] 2018-11-30 09:09
I'd also like to see this issue as I often need to attach email to other media as reference material or evidence.

**Comment by rsmsha** [comment] 2019-02-14 23:54
Any updates?

**Comment by invokemethod** [comment] 2019-04-26 17:12
i actually installed mail spring today, and the lack of this feature quickly made me uninstall and go back to thunderbird

**Comment by kte608** [comment] 2019-10-11 18:44
Yes. Me too. I cannot use it properly without eml export.

**Comment by requestsandinquiries** [comment] 2020-10-29 13:29
+1 for .eml support.

Tried Mailspring out. Slick interface, no .eml support. https://github.com/Foundry376/Mailspring/issues/264 Dev: "Why should a desktop email client open the most common email formats? Closed." Ok, got it. Unfortunately, very little value for any email-based workflow without .eml support. Uninstalling.

**Comment by CodeMouse92** [comment] 2021-01-28 02:01
This feature suggestion is being revisited.

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/gh-issue-migration-canned-message/39

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 02:01 UTC
Labels: audit, enhancement

**Comment by bengotow** [comment] 2026-04-19 21:07
Hi! Just wanted to let you know this was implemented in Mailspring 1.20.0 (The April 18, 2026 release). You can now right-click any message or thread to save it as an .eml file, and right-click any folder in the sidebar to export the entire folder. You can also forward a message as an .eml attachment. Hope this helps! 🎉
