### ISSUE TITLE
Contacts: Specify custom CardDAV service

### ISSUE THREAD

**Issue by Tamriel** [Foundry376/Mailspring#1668] opened 2019-10-15 20:17 UTC
##### What version of Mailspring are you using?
1.7.1

**Feature Request?**
I would like to use my ownCloud CardDAV service for the contacts, but don't find a place where to enter its URL and credentials.

**Comment by bengotow** [comment] 2019-10-16 15:04
Hey! There isn't a way to do this currently, but we'll probably add it when the full calendar launches later this year. In the meantime, if your CardDAV server and your IMAP server share username / password settings, you can tell Mailspring where your CardDAV server is using the `SRV` record standard. If your email address is `me@example.com`, edit your DNS records for `example.com` and add a SRV record (`_carddavs._tcp.example.com` => `your carddav server domain`). That will actually allow Mailspring and (almost) all other CardDav apps to find your server without further configuration! The same exists for `_caldavs._tcp.example.com` for calendar.

**Comment by tvercaut** [comment] 2019-10-19 15:19
Not sure if this warrants a separate feature request but additionally, the following two related features would be nice:

1) Be able to fetch contacts from a gmail account even if the the gmail account is not being used for emails in Mailspring

2) Be able to fetch contacts from Mac OS X built in `Contacts` app. Note that this option is available in Thunderbird's Address Book where one can find the `Mac OS X Address Book`

**Comment by kirkbeard** [comment] 2019-10-28 01:08
> 2. Be able to fetch contacts from Mac OS X built in Contacts app. Note that this option is available in Thunderbird's Address Book where one can find the Mac OS X Address Book

I'd like to request this as well. I can understand other users would like built-in contact/calendar features for Mailspring, but I only use it as a dedicated mail app. I'd prefer all contacts to come from the macOS Contacts app. At the moment (for me at least), email autocompletion is a complete mess in Mailspring, and I'm constantly double-checking that Mailspring isn't going to send an email to a random person I received an email from 7 years ago.

**Comment by f512** [comment] 2020-02-27 12:57
Hi !
I tried to configure a custom CardDAV, but I didn't manage to make it work.

> if your CardDAV server and your IMAP server share username / password settings
Check

>edit your DNS records for `example.com` and add a SRV record (`_carddavs._tcp.example.com` => `your carddav server domain`)
Check

> That will actually allow Mailspring and (almost) all other CardDav apps to find your server without further configuration
It didn't work. Nothing happend.
I tried to delete my mail account in Mailspring and recreate it, but nothing.
Is there a way to be sure Mailspring tried to fetch the `SRV` value ? A way to force the refresh ? A way to get the error (if there is an error)

Thanks !

**Comment by EugenMayer** [comment] 2020-06-17 08:01
This is my personal deal-breaker for Mailspring. I have several email accounts and several addressbooks, some hosted on mailbox.org, some on our zimbra and some on my own carddav server ( synology ).

Not being able to add them all like i do in evolution does block mailspring for me entirely.

**Comment by hawkette** [comment] 2020-07-08 03:45
Is this still happening? Would love CalDav/CardDav support

" but we'll probably add it when the full calendar launches later this year" was posted about 9 months ago.

Right now using MineTime and it's a bit clunky...

**Comment by pinglekoder** [comment] 2020-10-21 09:40
Not having carddav is also a dealbreaker for me.
I would like to have a "closed" system within my own network, not sharing the data with any Alphabetical company.

**Comment by CodeMouse92** [comment] 2021-02-09 22:39
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/contacts-specify-custom-carddav-service/531

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@Tamriel: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-09 22:39 UTC
Labels: audit, calendar, contacts, enhancement, product-direction
