### ISSUE TITLE
multi-factor-authentication-mfa

### ISSUE THREAD

**Issue by vtraida** [Foundry376/Mailspring#1277] opened 2018-12-20 11:50 UTC
account creation issue - office365
office 365 + multi-factor-authentication-mfa (https://duo.com/product/multi-factor-authentication-mfa)
receiving error

Authentication Error - Check your username and password. (IMAP)View Log----------IMAP----------* OK The Microsoft Exchange IMAP4 service is ready. [QQBNADYAUAAxADkAMwBDAEEAMAAxADAAMAAuAEUAVQBSAFAAMQA5ADMALgBQAFIATwBEAC4ATwBVAFQATABPAE8ASwAuAEMATwBNAA==]1 CAPABILITY* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+1 OK CAPABILITY completed.2 LOGIN "vadym_traida@___.com" "*********"2 NO LOGIN failed.

i need approve on my mobile device, but window is not showed is it possible to show this window?

![duo1](https://user-images.githubusercontent.com/32762226/50283319-37232d80-045e-11e9-8d6b-9b8b23962e84.png)
![duo2](https://user-images.githubusercontent.com/32762226/50283331-3f7b6880-045e-11e9-9597-b64a95d8a236.png)

**Comment by pablo-esteban-serrano** [comment] 2019-03-03 02:48
I'm seeing the same issue as soon as I setup MFA using the microsoft authenticator app, whether using the 6 digit 30 second codes or the app approval response. other clients work fine.

**Comment by CodeMouse92** [comment] 2021-01-18 19:20
Thank you for your patience on this issue! I know it's frustrating when you cannot connect to your email with Mailspring.

2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be a duplicate of one we've already migrated to Discourse:

https://community.getmailspring.com/t/institutional-office365-not-working/48

Please consider joining that community and continuing the discussion there.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-18 19:20 UTC
Labels: audit
