### ISSUE TITLE
Feature Request: To ask confirmation questions when deleting accounts

### ISSUE THREAD

**Issue by MalteKiefer** [Foundry376/Mailspring#1812] opened 2020-02-25 05:30 UTC
Today my son came without intention to the mouse, which was just on the minus sign in the account overview.
The account was deleted without further inquiry. It would be good if a dialog comes up again and asks if you really want to delete the account.

**Comment by CodeMouse92** [comment] 2021-02-26 19:00
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/to-ask-confirmation-questions-when-deleting-accounts/840

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@MalteKiefer: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-26 19:00 UTC
Labels: audit, enhancement
