### ISSUE TITLE
Mouse cursor is different from my desktop cursor theme

### ISSUE THREAD

**Issue by migmolrod** [Foundry376/Mailspring#422] opened 2017-12-11 02:07 UTC
##### What operating system are you using?
Ubuntu 16.04 (installed server edition, then added gnome desktop with `tasksel`)

##### What version of Mailspring are you using?
1.0.10-d250d253

**Bug?**
Mouse cursor is different from what I selected in Tweak Tool (Breeze-Snow), as if it was hardcoded in Mailspring. It happened me in a couple apps but they were using mono and I could actually fix those (like they used some kind of fallback default, and changing that default to my cursor theme). Can't do the same here apparently.
Since Mailspring is styled through CSS, can it be that the cursors are stored somewhere and I can overwrite them or something?

**Comment by bengotow** [comment] 2017-12-11 18:37
Are you using the Snapcraft release of Mailspring? I think this is a known issue they're working to fix.

**Comment by migmolrod** [comment] 2017-12-12 17:21
Oh, ok. It is actually Snapcraft version, yes. Where can I track that issue? I've looked for this bug but couldn't find anything, that's why I opened this.

**Comment by Ads20000** [comment] 2018-01-05 19:13
@migmolrod keep an eye on [this thread](https://forum.snapcraft.io/t/use-the-system-gtk-theme/496/), [this post](https://forum.snapcraft.io/t/use-the-system-gtk-theme/496/21) implies that the mouse theme is included in that thread's issue

**Comment by grg2rsr** [comment] 2018-02-03 09:24
Hi have the same problem (use snapcraft version too, 1.1.2). The mouse cursor is different in Mailspring window. More serious than a different color is the different size: I am using a hidpi screen, gnome scaling factor 2 (gnome-shell 3.26.2). Cursor is tiny hovering over mailspring ...

**Comment by brown121407** [comment] 2019-03-16 09:55
Any updates on this? I really like Mailspring but the cursor is just too small and it's extremely annoying.

![mail](https://user-images.githubusercontent.com/24657667/54473573-4ce88a80-47e2-11e9-9454-e4a371071b44.png)

**Comment by mssngr** [comment] 2019-03-17 20:57
Same here. With a HiDPI display, the cursor is almost unusable.

**Comment by mokafolio** [comment] 2019-07-13 18:09
This is still an issue. I am on ubuntu 18.10, same thing happened on 18.04. I installed mailspring through snap and I am on version 1.6.3-134a0e55 .

**Comment by x6herbius** [comment] 2019-10-22 12:42
Tiny mouse cursor is an issue for me too, on Ubuntu MATE 19.04. Just trying the application today, but disappointed to find the issue has been around since 2017.

**Comment by chanchansir** [comment] 2020-01-14 11:18
Got the same problem Zorin OS 15 running of Yoga 920 in 4K screen too. Really annoying and hope this can be resolved. A great mail client. Don't wanna use Thunderbird or Evolution.

**Comment by bliles** [comment] 2020-01-20 20:45
It looks like it might be as simple as setting the XCURSOR_PATH env var in the mailspring snap:
https://github.com/ubuntu/snapcraft-desktop-helpers/commit/4008601d

**Comment by tty2** [comment] 2020-12-19 07:18
Still exists if install using snapcraft.

**Comment by congard** [comment] 2021-01-16 20:34
> Still exists if install using snapcraft.

+

**Comment by CodeMouse92** [comment] 2021-01-17 02:40
Hi everyone!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mouse-cursor-different-from-desktop-cursor-theme/56/1

Please consider joining that community and continuing the discussion there! Bonus: if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-17 02:40 UTC
Labels: audit, bug, linux, not-yet-possible, snapcraft
