### ISSUE TITLE
Missing message (Gsuite account). Other clients show this message.

### ISSUE THREAD

**Issue by sikand** [Foundry376/Mailspring#1313] opened 2019-01-09 19:51 UTC
##### Are there any related issues?

...

##### What operating system are you using?
OpenSuse 42.3

...

##### What version of Mailspring are you using?
1.5.5
...

--

**Bug?**

##### Is this an email sync or connection issue?

Possibly

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Possibly
...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

...

I received a message that shows up on gmai/android etc. but doesn't show up on my Mailspring client.

**Comment by CodeMouse92** [comment] 2021-02-02 02:50
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/disappearing-emails-desync/428

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

P.S. Duplicate of #304

**Closed by CodeMouse92** 2021-02-02 02:50 UTC
Labels: audit
