### ISSUE TITLE
Snap package does not allow browsing or attaching from shared drives in Linux

### ISSUE THREAD

**Issue by timgoodwin123** [Foundry376/Mailspring#1074] opened 2018-09-16 12:06 UTC
Using Mailspring 1.4.2 on KDE Neon User Edition. The Snap install sandbox does not allow me to browse or attach files from my shared drives, automatically mounted on boot at /shared
Drives do not show when browsing, and if attachments are dragged to Mailspring the error 'file not found or insufficient permissions' is displayed. This makes the Snap install unusable for me. The problem does not occur with the .deb install - browsing and attachments are fine.

**Comment by bengotow** [comment] 2018-09-17 18:08
Hey! I'm not sure, but there might be an additional snapcraft permission we need to add here.

**Comment by Lin-Buo-Ren** [comment] 2019-01-05 02:36
Hello, currently snapd only allow regular file access from `/mnt`, `/media`, and `/run/media`, you may want to consider to move the mount point under these directories after connecting the `removable-media` interface.

**Comment by timgoodwin123** [comment] 2019-01-05 12:15
The drive I am trying to access is not removable media but a separate internal hard drive on which I have /home mounted. This enables me to re-install the OS without affecting all the files in /home
As Snap does not allow access to this drive, I can't attach any documents in /home to mail, rendering the Snap version of Mailspring useless to me. I'm currently using the .deb file.

Tim Goodwin
Actor, Presenter, Geek

timgoo@gmail.com (mailto:timgoo@gmail.com)
http://www.timgoodwin.co.uk

**Comment by Lin-Buo-Ren** [comment] 2019-01-05 15:14
@timgoodwin123 Note that the access of files in /home is granted via the `home` interface.  The `removable-media` interface name is misleading as it simply allows access to `/mnt` and `*/media`, if you move the /shared mount point under `/mnt/shared` or /media/shared` the files in the /shared file system should be accessible by Mailspring.

**Comment by CodeMouse92** [comment] 2021-02-10 20:47
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/cannot-attach-files-stored-in-ntfs-partition-with-snap-version/557

@timgoodwin123 @Lin-Buo-Ren: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

P.S. Duplicate of #749

**Closed by CodeMouse92** 2021-02-10 20:47 UTC
Labels: audit, bug, linux, snapcraft
