### ISSUE TITLE
Feature Request: Add more than 20 Accounts

### ISSUE THREAD

**Issue by theburningsoul** [Foundry376/Mailspring#2030] opened 2020-05-28 16:34 UTC
Is there a way to add more accounts than the windows limit of 15 or 17 ? I am looking to add like 20 accounts or so

All of the accounts are Gsuites 

Please help

**Comment by CodeMouse92** [comment] 2021-02-12 19:54
To my knowledge, there is no limit to the number of accounts that you can add to Mailspring.

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

**In order to properly address this issue, we require the additional information requested by the issue template. Please start a new Thread in the Bug Reports category on our [Discourse](https://community.getmailspring.com) so we can properly evaluate and discuss this issue.**

Meanwhile, we're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-12 19:54 UTC
Labels: audit, enhancement
