### ISSUE TITLE
Bug: Cannot connect to organization office 365 

### ISSUE THREAD

**Issue by Sraw** [Foundry376/Mailspring#2091] opened 2020-07-14 15:37 UTC
**Setup: (please complete the following information):**
 - OS: Linux Mint 20
 - Mailspring Version: 1.7.8

**Additional context** 
I just cannot find a way to connect the organization office 365. Please fix this as it totally prevents me to use.

**Comment by drkostas** [comment] 2020-07-27 10:28
@Sraw I have the same problem. I found an open [issue](https://github.com/Foundry376/Mailspring/issues/1118) from 2018 that describes the same problem. #1118

**Comment by Sraw** [comment] 2020-07-27 19:50
@drkostas So you see, nobody cares about this issue, just leave it as it is. NOT EVEN A RESPONSE.

**Comment by e0lithic** [comment] 2020-09-16 04:12
Recently, office 365 has introduced the "security defaults" which says `If you've enabled security defaults in your organization, SMTP AUTH is already disabled in Exchange Online` and most organizations do use it .As such the following needs to be enabled at the org level.

**Use the Microsoft 365 admin center to enable or disable SMTP AUTH on specific mailboxes**
1. Open the [Microsoft 365 admin center](https://admin.microsoft.com/) and go to **Users** > **Active users**.
2. Select the user, and in the flyout that appears, click **Mail**.
3. In the **Email apps** section, click **Manage email apps**.
4. Verify the **Authenticated SMTP** setting: unchecked = disabled, checked = enabled.
When you're finished, click **Save changes**.

This is an excerpt from the following [page](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/authenticated-client-smtp-submission).

On a side note , @bengotow maybe this section can be added in the office 365 setup page.

Thanks

**Comment by hsheikhali** [comment] 2021-01-17 17:38
Id like to point out that end users generally don't have the luxury of asking their IT team to tweak the security settings for their O365...

I'm confused as to why mailspring doesn't look into Oauth based authentication? Maybe it might me a huge effort i am not aware of but asking us to get IT to change security permissions isn't realistic.

**Comment by CodeMouse92** [comment] 2021-01-18 18:41
Thank you for your patience on this issue! I know it's frustrating when you cannot connect to your email with Mailspring.

2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be a duplicate of one we've already migrated to Discourse:

https://community.getmailspring.com/t/institutional-office365-not-working/48/2

Please consider joining that community and continuing the discussion there.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-18 18:41 UTC
Labels: audit, bug
