### ISSUE TITLE
Unable to search with gmail label

### ISSUE THREAD

**Issue by studgeek** [Foundry376/Mailspring#394] opened 2017-12-04 15:49 UTC
I am unable to search mail with multiple labels. I just get "No search results available". Doing the same search in Gmail returns lots of results. I have tried the following (not "qf" and "@0" are both labels).

From inbox (so all mail):
in:sent - works
in:inbox AND in:sent - works
in:inbox AND in:unread - works
in:qf - "No search results available"
in:@0 - "No search results available"
in:inbox AND in:qf - "No search results available"

From "qf" folder:
sunday - works
in:sent - works
in:qf - "No search results available"
in:inbox - "No search results available"

As additional context, my goal/need is to search for mails in the inbox that are labeled with a particular label (e.g. "in:inbox AND in:qf", "in:inbox AND in:@0". This meets a similar need as Google Inbox provides with clustering - being able to see the inbox emails related to a particular subject all together.

##### Are there any related issues?
#184 could be related, but I am seeing "No search results available" rather than it never returning.

##### What operating system are you using?
macOS 10.12.6 (16G1036)

##### What version of Mailspring are you using?
Version 1.0.9 (1.0.9)

--

**Bug**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Possibly, it has to do with Gmail labels

##### Is the issue reproducible with a particular attachment, message, signature, etc?

--

##### Does this feature exist in another mail client or tool you use?
Yes - Gmail, Airmail

**Comment by bengotow** [comment] 2017-12-06 21:17
Hey! I've been able to reproduce this and it looks like we're not properly indexing Gmail labels for this sort of query. Will get this fixed in the next release.

**Comment by bengotow** [comment] 2017-12-08 02:30
Hey! The fix for this has shipped in `1.0.10` - thanks for the detailed report.

To see the fix after upgrading, you'll need to rebuild Mailspring's search index. This happens automatically, but pretty infrequently. To trigger a rebuild manually, go to Preferences > General and click "Reset Email Cache" at the very bottom. Mailspring will re-fetch and re-index your mail.

**Closed by bengotow** 2017-12-08 02:30 UTC
Labels: done-pending-release
