### ISSUE TITLE
Mail lost when sending

### ISSUE THREAD

**Issue by radu-b** [Foundry376/Mailspring#1107] opened 2018-10-01 16:38 UTC
##### What operating system are you using?

Ubuntu 18.04

##### What version of Mailspring are you using?

1.4.2-f587b7b7

--

**Bug?**

##### Is this an email sync or connection issue?

It's possible, but there is an UI side as well.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Only tried Gmail.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Seems to happen randomly.

--

This happened about three times over the course of a few weeks. When sending, the undo counter (15s in this case) finishes, there is the usual UI indication of the sending in progress and then an error message is shown, with a text like "Failed to send e-mail". 

The original message is not sent (I've checked the GMail sent folder online) and it cannot be recovered - for instance from Drafts. There is a message in Drafts with the respective subject and a summary line that looks like the sent message however it cannot be opened correctly - an empty message editor is shown. The GMail Drafts folder does not contain the message at all.

As a warning sign, I noticed in two of the cases that the editor behaved strangely when writing the email. Some formatting was used in these cases (monspaced font in one and bullets in the other), and there were some editing glitches: for instance a word was deleted completely out of the blue, or a few items on the bullet list just vanished. Subsequently sending these e-mails failed as described.

**Comment by barbrick** [comment] 2018-10-12 14:38
I have the same issue.

**What operating system are you using?**
macOS High Sierra 10.13.6 (17G65)

**What version of Mailspring are you using?**
1.4.2-f587b7b7

Using Google Apps accounts, some emails go through, others don't, I haven't noticed a pattern. The undo send countdown goes all the way down then I get an alert with something along the lines of "Failed to send message: undefined". If it happens again I'll update with the full error message.

I haven't noticed the message behaving strangely while writing the message but I'll keep an eye out for it.

Like above, the unsent message will appear in drafts with the message preview, subject, recipients, etc. but once opened it's a blank message, no recipients, message, subject, and also it will be set to the default account rather than the account the message was sent from.

**Comment by radu-b** [comment] 2018-10-12 14:43
The issue happened with a Google Apps account for me too - did not realize it before.

**Comment by ToRvaLDz** [comment] 2018-10-12 20:36
Same here

**Comment by radu-b** [comment] 2018-10-18 12:56
It just happened again, without any formatting problems. I've opened the developer tools and the log contains a bunch of SyncbackDraftTask objects followed by a SendDraftTask. 

The SyncbackDraftTask objects contain the correct details of the message (except there's no body field), but the SendDraftTask seems to be mixed up: it has a different account id, the sender is the default account (not the one I used in the draft), the subject is empty and the body is just <br>.

In other messages that are sent correctly, SendDraftTask contains the correct information for the sent message.

**Comment by barbrick** [comment] 2018-10-23 14:43
Happened yesterday and again today, the message in the error alert popup was "Sorry, Mailspring was unable to deliver the message: undefined."

Here is a snippet from the logs:

```
59616 [2018-10-23 11:37:35.575] [main] [info] [local-62709687-1c09] Running SendDraftTask performLocal:
59616 [2018-10-23 11:37:35.576] [main] [info] [local-62709687-1c09] -- Succeeded. Changing status to `remote`
59616 [2018-10-23 11:37:35.946] [foreground] [info] Idle exited with code 0
59616 [2018-10-23 11:37:36.032] [foreground] [info] [local-62709687-1c09] Running SendDraftTask performRemote:
59616 [2018-10-23 11:37:36.034] [foreground] [info] - Sending draft 1540304986.local-887a7095-7585-v1.5.0-92ed66b8@getmailspring.com
59616 [2018-10-23 11:37:36.034] [foreground] [info] -- Identified `sent` folder: [Gmail]/Sent Mail
59616 [2018-10-23 11:37:36.042] [foreground] [info] -- Sending a single message body to all recipients:
59616 [2018-10-23 11:37:36.044] [foreground] [info] -X An SMTP error occurred: ErrorNoRecipient LibEtPan code: 0
59616 [2018-10-23 11:37:36.563] [foreground] [error] [local-62709687-1c09] -- Failed ({"debuginfo":"ErrorNoRecipient","key":"send-failed","retryable":false,"what":"std::exception"}). Changing status to `complete`
59616 [2018-10-23 11:37:36.631] [foreground] [info] syncFolderChangesViaCondstore - [Gmail]/All Mail: modseq 11340466 to 11340466, uidnext 129791 to 129791
```

**Comment by radu-b** [comment] 2018-10-24 13:51
@barbrick Do you use the default undo timeout, or a larger one like me (15s)?

**Comment by barbrick** [comment] 2018-10-24 14:00
@radu-b Good catch, I also use the 15 second timeout. I wonder if that's related? I'll set it back to 5s for the time being, unfortunately, the issue has been sporadic so it will be hard to tell if that makes a difference.

**Comment by KristerV** [comment] 2018-11-09 14:30
I've got 5sec delay, not sure if it's default or not. Arch Linux. Non-gmail address (custom domain).

![image](https://user-images.githubusercontent.com/2750622/48267789-e4f0f480-e43b-11e8-84af-916855eab0dc.png)

Not being able to send is a problem, but losing the email is critical.

**Comment by GAPP99** [comment] 2018-11-24 16:38
This happens to me as well. What I've found is that the email actually gets sent, but Mailspring just glitches a lot, so the email is moved around between the "Deleted folder" and the "Sent folder".

**Comment by gitsper** [comment] 2018-11-27 16:25
I'd like to echo everything in this thread -- I get the same type of logs, same error message, same deal with the timer expiring before getting the error, also with gmail, etc. I'd like to add that for whatever reason I don't get this problem when replying to emails. It only happens when clicking the "compose" button and sending an email from the compose window. Maybe someone can confirm this?

**Comment by KristerV** [comment] 2018-11-28 08:37
yeah it's definitely in compose, as in writing an email from scratch.

**Comment by bengotow** [comment] 2018-12-06 07:48
Hey folks—thanks for reporting this. I'm looking in to this and I'll see if I can reproduce it reliably. When you're composing emails and this happens, do you remember if you choose a "From:" address in the composer? It sounds like Mailspring might be waiting the 15 seconds, going to send the draft, and discovering that it's sending through Account A with the "From" address of Account B.

**Comment by KristerV** [comment] 2018-12-07 07:36
I change the "From" often, so could be that.

k

**Comment by ToRvaLDz** [comment] 2018-12-07 10:07
I'm sure it happens when changing the From address, I need to check if it happens without changing it.

> Hey folks—thanks for reporting this. I'm looking in to this and I'll see if I can reproduce it reliably. When you're composing emails and this happens, do you remember if you choose a "From:" address in the composer? It sounds like Mailspring might be waiting the 15 seconds, going to send the draft, and discovering that it's sending through Account A with the "From" address of Account B.

**Comment by EtoileFilante** [comment] 2018-12-07 10:48
Same here

**Comment by gitsper** [comment] 2018-12-14 14:58
> Hey folks—thanks for reporting this. I'm looking in to this and I'll see if I can reproduce it reliably. When you're composing emails and this happens, do you remember if you choose a "From:" address in the composer? It sounds like Mailspring might be waiting the 15 seconds, going to send the draft, and discovering that it's sending through Account A with the "From" address of Account B.

Since reading this comment, I have been composing new mail by first selecting the inbox of the account  I want to send from. Then when I click the send button, the "from" address in the composer window is populated with the address that I want. I have not had any errors sending mail in this way, so it seems your assessment is spot on!

**Comment by rafacapa** [comment] 2019-05-14 09:40
> I'm sure it happens when changing the From address, I need to check if it happens without changing it.
> 
> > Hey folks—thanks for reporting this. I'm looking in to this and I'll see if I can reproduce it reliably. When you're composing emails and this happens, do you remember if you choose a "From:" address in the composer? It sounds like Mailspring might be waiting the 15 seconds, going to send the draft, and discovering that it's sending through Account A with the "From" address of Account B.

It happened to me without changing the from field but having set 15 secs to undo send in the timer settings option.

**Comment by Galvanize87** [comment] 2019-10-03 09:34
Oh my god, after a long message is the second time this happens to me. I can see the message on the Drafts in front of the Subject until the first paragraph. When open the message there is nothing there.
So annoying! 1 year and still not fixed.

**Comment by ljwolf** [comment] 2019-11-08 11:56
I am also having this error with an Office365 account.

**Comment by leonelvsc** [comment] 2020-05-02 12:47
Same here with an IMAP account, if i have configured 2 sending accounts, not just lost the email but also when changing the sender the new email disappears.

One account has a predefined BCC.

Just a shame, it's an email client ! the only thing that needs to works allways isnt not working

**Comment by justinsolms** [comment] 2020-11-11 11:47
Using Ubuntu 20.04 some emails are being lost my being moved to trash, why?

**Comment by CodeMouse92** [comment] 2021-01-22 00:04
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mail-lost-when-sending/169

Please consider joining that community and continuing the discussion there!

@radu-b, @barbrick: if you join and reply to the issue, the moderators can make an effort to reassign your post to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-22 00:04 UTC
Labels: audit
