### ISSUE TITLE
[Feature Request] Vertically stacked messages pane / reading pane ala Mail.app

### ISSUE THREAD

**Issue by Weuxel** [Foundry376/Mailspring#116] opened 2017-10-11 05:41 UTC
##### Are there any related issues?
Did not find any.

##### What operating system are you using?
macos

##### What version of Mailspring are you using?
1.0.3

--
##### Does this feature exist in another mail client or tool you use?
Yes

Please provide a reading pane below the messages pane.
A reading pane beside the messages pane wastes a lot of space. Space below the messages is mostly empty while the reading pane is left to small. At the same time message subjects are cut.

**Comment by bengotow** [comment] 2017-10-11 18:00
(Graphic just for reference)

![image](https://user-images.githubusercontent.com/1037212/31457992-6c676034-ae73-11e7-86c1-ae831882471f.png)

**Comment by mattlyons0** [comment] 2017-10-25 10:23
I'm working on a PR for this, got it mostly done but needs some polish. 
https://github.com/mattlyons0/Mailspring/tree/verticalStack

Here's a preview of what it looks like:
![](https://i.imgur.com/iucV4os.png)

When paired with #251's ability to disable max width limit it will look even better.

**Comment by alpha-beta-soup** [comment] 2019-06-27 09:11
This would also make it possible to use the app on a vertical monitor. At the moment it's very difficult to read some emails on a vertical screen, and the window cannot be maximised. (Fedora 29.)

**Comment by TheSHEEEP** [comment] 2019-08-02 11:36
Yes, please! The way the split is now makes both the email list and the email content itself look really messed up.

**Comment by lilgreggy** [comment] 2020-05-12 21:19
Is there any progress on this? I intermittently tried switching to Mailspring, but it's rather unusable for me with the Reading Pane as my email is dedicated to a vertical screen.

**Comment by xxxxxxxboy** [comment] 2020-07-27 07:10
PLEASE someone work on this.. Horizontal preview pane is a must in the modern world.
Hope to see this soon.

**Comment by r0073rr0r** [comment] 2020-09-15 09:12
any news? please we need this 👍

**Comment by Phylu** [comment] 2020-12-28 02:52
I started working on this based on the code by @mattlyons0
Unfortunately, I am not yet satisfied as the reading pane so far is spanning the whole bottom area, but I would prefer it to only span the middle area between the left and right sidebar. I will need to figure out how to proceed from here.

![Bildschirmfoto von 2020-12-28 03-48-25](https://user-images.githubusercontent.com/587332/103186258-1947f900-48c0-11eb-821d-ae34e8b56aeb.png)

**Comment by CodeMouse92** [comment] 2021-01-21 01:18
I'm locking this, but not closing or migrating it, as it is in progress with #2243.

**Comment by CodeMouse92** [comment] 2021-01-26 22:07
Duplicate of #420
Duplicate of #153

**Closed** 2021-03-26 15:15 UTC
Labels: Hacktoberfest, enhancement, good first issue
