### ISSUE TITLE
Bug: 

### ISSUE THREAD

**Issue by wulfalpha** [Foundry376/Mailspring#1950] opened 2020-04-29 03:37 UTC
**Describe the bug**
A clear and concise description of what the bug is. Does it happen with all email accounts, or only a particular account and/or email message?
It happens on all accounts but not all at the same time.
Sync erro ha
[mailsync-e7658785.log](https://github.com/Foundry376/Mailspring/files/4549681/mailsync-e7658785.log)

Mailspring Version: 1.7.6-e94bb759
Platform: linux
Account State: sync_error
Account Provider: icloud
IMAP Server: imap.mail.me.com
SMTP Server: smtp.mail.me.com
--------------------------------------------
19109 [2020-04-28 21:21:02.230] [metadataExpiration] [info] Scanning for expired metadata
19109 [2020-04-28 21:21:02.230] [metadataExpiration] [info] -- Will wake for next expiration in 7200sec
19109 [2020-04-28 21:22:53.162] [background] [info] Syncing folder list...
19109 [2020-04-28 21:23:03.280] [background] [critical] 
 ***
 *** A C++ exception occurred during program execution: 
 *** database is locked
 ***

19109 [2020-04-28 21:23:03.289] [background] [critical]  *** Stack trace:
 ***   clone
 ***

19418 [2020-04-28 21:23:09.210] [main] [info] Identity created at 1512098976 - using ID Schema 0
19418 [2020-04-28 21:23:09.277] [main] [info] ------------- Starting Sync (********@******.***) ---------------
19418 [2020-04-28 21:23:09.333] [metadata] [info] Metadata delta stream starting...
19418 [2020-04-28 21:23:13.289] [background] [info] Marking all folders as `busy`
19418 [2020-04-28 21:23:23.308] [background] [critical] 
 ***
 *** A C++ exception occurred during program execution: 
 *** database is locked
 ***

19418 [2020-04-28 21:23:23.316] [background] [critical]  *** Stack trace:
 ***   clone
 ***

19465 [2020-04-28 21:23:23.588] [main] [info] Identity created at 1512098976 - using ID Schema 0
19465 [2020-04-28 21:23:23.592] [main] [info] ------------- Starting Sync (********@******.***) ---------------
19465 [2020-04-28 21:23:23.605] [metadata] [info] Metadata delta stream starting...
19465 [2020-04-28 21:23:27.604] [background] [info] Marking all folders as `busy`
19465 [2020-04-28 21:23:37.624] [background] [critical] 
 ***
 *** A C++ exception occurred during program execution: 
 *** database is locked
 ***

19465 [2020-04-28 21:23:37.632] [background] [critical]  *** Stack trace:
 ***   clone
 ***

19512 [2020-04-28 21:23:37.878] [main] [info] Identity created at 1512098976 - using ID Schema 0
19512 [2020-04-28 21:23:37.881] [main] [info] ------------- Starting Sync (********@******.*** ---------------
19512 [2020-04-28 21:23:37.893] [metadata] [info] Metadata delta stream starting...
19512 [2020-04-28 21:23:41.892] [background] [info] Marking all folders as `busy`
19512 [2020-04-28 21:23:51.911] [background] [critical] 
 ***
 *** A C++ exception occurred during program execution: 
 *** database is locked
 ***

19512 [2020-04-28 21:23:51.922] [background] [critical]  *** Stack trace:
 ***   clone
 ***

19560 [2020-04-28 21:23:52.165] [main] [info] Identity created at 1512098976 - using ID Schema 0
19560 [2020-04-28 21:23:52.168] [main] [info] ------------- Starting Sync (*********@******.***) ---------------
19560 [2020-04-28 21:23:52.179] [metadata] [info] Metadata delta stream starting...
19560 [2020-04-28 21:23:56.178] [background] [info] Marking all folders as `busy`
19560 [2020-04-28 21:24:06.198] [background] [critical] 
 ***
 *** A C++ exception occurred during program execution: 
 *** database is locked
 ***

19560 [2020-04-28 21:24:06.207] [background] [critical]  *** Stack trace:
 ***   clone
 ***

**To Reproduce**
1. Open Mailspring.
Sync errors happen repeatedly. Log is posted above. Full log is attached.

**Expected behavior**
I expected mailspring to not have sync errors

**Screenshots**

**Setup: (please complete the following information):**
 - OS: Feren OS
 - OS Version (Ubuntu) 18.04
 - Mailspring Version: ex: 1.7.6

**Additional context** 
Add any other context about the problem here. If this issue is related to a particular account or email service, be sure to mention it so this report is actionable!
I deleted the LOCK file but that didn't help. As it is the snap version mailspring is not in the .config folder

**Comment by fferraro87** [comment] 2020-05-15 16:49
I've same problem on ubuntu 20.04 and the same mailspring version

**Comment by BarryHelfrich** [comment] 2021-01-05 10:52
I have the same issue on 1.7.8

**Comment by CodeMouse92** [comment] 2021-02-01 19:23
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/database-is-locked/420

Please consider joining that community and continuing the discussion there!

@tristanlins: I've migrated your comments particularly, as they point to the version where this first appears. If you join and reply to the issue, the moderators can make an effort to reassign that post to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-01 19:23 UTC
Labels: audit, bug
