### ISSUE TITLE
Add account successfully but not showing in the list ubuntu 18.10

### ISSUE THREAD

**Issue by wuyuanyi135** [Foundry376/Mailspring#1248] opened 2018-11-27 16:07 UTC
Hello,
I am new to mailspring. I have two email account (gmail and office 365). Mailspring only displays the one I added in the starting up wizard. The account I added afterwards will not be in the account list, even though the dialog showed "successfully added the account".

I tried to uninstall mailspring and start with another email. The issue persists. The second account did not show up.

##### Are there any related issues?
Not found

##### What operating system are you using?

```
$ uname -a
Linux wuyuanyi-workstation 4.18.0-11-generic #12-Ubuntu SMP Tue Oct 23 19:22:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic
```
##### What version of Mailspring are you using?

mailspring-1.5.3

**Bug?**
Yes

##### Is this an email sync or connection issue?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
It occurs to all providers

##### Is the issue reproducible with a particular attachment, message, signature, etc?
N/A

**Comment by bengotow** [comment] 2018-12-19 07:35
Hey! Thanks for reporting this - if you go to the Preferences > Accounts screen in Mailspring, do you see your second account? It sounds like Mailspring may not be able to connect to your mailbox and is still trying to fetch the list of folders. (Once it has the folders, the account will appear throughout the app.)

**Comment by wuyuanyi135** [comment] 2018-12-19 19:52
@bengotow 
Hi. Thanks for your response. No, I tried all the versions I could get (apt, snap, release from gh, build from source) none of them have the second account. 

I checked the log but it seems adding account was not recorded. Was this intended behavior?

```
21024 [2018-12-19 14:50:06.613] [main] [info] Identity created at 1543350298 - using ID Schema 1
21024 [2018-12-19 14:50:06.616] [main] [info] ------------- Starting Sync (***HIDDEN***) ---------------
21024 [2018-12-19 14:50:06.620] [metadata] [info] Metadata delta stream starting...
21024 [2018-12-19 14:50:06.620] [background] [info] Marking all folders as `busy`
21024 [2018-12-19 14:50:06.630] [background] [info] Syncing folder list...
21024 [2018-12-19 14:50:07.107] [background] [info] Syncing folder list...
21024 [2018-12-19 14:50:07.568] [foreground] [info] syncFolderUIDRange for INBOX, UIDs: 47039 - 47324, Heavy: false
21024 [2018-12-19 14:50:07.796] [foreground] [info] - remote=101, local=101
21024 [2018-12-19 14:50:07.821] [foreground] [info] Idling on folder INBOX
21024 [2018-12-19 14:50:08.180] [background] [info] Sync loop deleting unlinked messages with phase 2.
21024 [2018-12-19 14:50:08.186] [background] [info] Sync loop complete.
21024 [2018-12-19 14:50:21.619] [metadataExpiration] [info] Scanning for expired metadata
21024 [2018-12-19 14:50:21.619] [metadataExpiration] [info] -- Will wake for next expiration in 7200sec
```

**Comment by wuyuanyi135** [comment] 2018-12-19 19:53
@bengotow I did not go through the source code. Could you give me some idea which logging file should I look into or is there any file/db that holds the added account for me to check into?

**Comment by wuyuanyi135** [comment] 2019-01-15 20:08
Is this issue reproducible? @bengotow

**Comment by StevenMapes** [comment] 2019-02-22 09:28
It's even worse for me on Linux Mint 18.3 and Mailspring 1.5.6 as you can add the first account but then when you click to add any others it launches a window but it doesn't actually render anything so you can't even start the flow of adding a second account

**Comment by frischnetz** [comment] 2019-09-05 16:37
I can confirm this bug on Ubuntu 19.04 with Mailspring 1.6.3. I can only ever setup one account. The second one gets forgotten immediately, no matter which account I add first, the second one never turns up anywhere.

**Comment by rcozzolino** [comment] 2020-02-28 15:17
Has this ever been resolved? I was able to add 2 gmail accounts, but NOTHING else. Shows the "Adding account", then nada. Running Ubuntu 19.1 and latest version of mailspring.

**Comment by StevenMapes** [comment] 2020-02-28 15:25
I have seven working on Kubuntu 18.04 with the snapd package so 1..7.4

**Comment by rcozzolino** [comment] 2020-02-28 16:15
I have a feeling it is totally on my end regarding keys, but not 100% sure. Office365 hits, finds account, says its adding ... then nothing. Basic mail accounts set up manually do the same.

**Comment by lukewarlow** [comment] 2020-02-29 16:57
I'm on Zorin OS 15.2 with version 1.7.4 installed from .deb download, and I have the same issue have added my first account, but any others I try to add say successfully setup but don't show in the main interface or the accounts section in settings.

**Comment by fabricio-garcia** [comment] 2020-03-02 02:30
Just like @lukewarlow I'm on Zorin 15.2 (fresh install), installed Mailspring from a .deb and I was only able to add one account and for the others Mailspring says they were added successfully without showing them.

**Comment by protopoloji** [comment] 2020-03-02 08:32
Hi, On elementary OS Hera and issue the is same here.I couldn't add secondary account.

**Comment by mscroggi** [comment] 2020-03-02 13:32
Linux Mint 19.3  Having the same problem..  I tried to add an IMAP account.. once I click the connect account button.. the frame goes all white and hangs..    I figured out I could add a gmail account successfully .. and if I do that first, when I add my IMAP account, it continues and says it is added successfully.  but the account never shows up anywhere.  

I started mailspring in the terminal window and it is logging this - 

mailspring
Running database migrations
App load time: 213ms

{"error":null}
Manual update check (updates.getmailspring.com/check/linux/x64/1.7.4-d54ff730/f94f3510-4fb8-4fdf-a93e-e57c98f6039a/stable) returned 204
{ TypeError: Cannot read property 'emailAddress' of undefined
    at _AccountStore.addAccount (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/src/flux/stores/account-store.ts:223:18)
    at OnboardingStore._onFinishAndAddAccount (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib/onboarding-store.ts:129:20)
    at EventEmitter.eventHandler (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:36:22)
    at EventEmitter.emit (/usr/share/mailspring/resources/app.asar/node_modules/eventemitter3/index.js:72:35)
    at Function.trigger (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/PublisherMethods.js:52:26)
    at Object.functor [as finishAndAddAccount] (/usr/share/mailspring/resources/app.asar/node_modules/reflux/src/createAction.js:32:56)
    at onboarding_helpers_1.finalizeAndValidateAccount.then.validated (file:///tmp/nylas-build/electron-packager/linux-x64/mailspring-linux-x64/resources/app/internal_packages/onboarding/lib/decorators/create-page-for-form.tsx:170:29)

**Comment by fabricio-garcia** [comment] 2020-03-03 03:21
**Quick workaround**: I uninstalled Mailspring and removed any configuration files either from ~/.config or ~/.local. Then I downloaded a .deb containing the release 1.7.2 from [here](https://github.com/Foundry376/Mailspring/releases). I was able to add all my accounts without any problem and then upgraded to 1.7.4

**Comment by rcozzolino** [comment] 2020-03-03 03:23
I did the same thing and all worked well. 1.74 is a terribly broken version.

**Comment by saravanabalagi** [comment] 2020-03-03 18:54
Doesn't work on Ubuntu 18.04  - 1.7.4

**Comment by DrAlgernopKrieger** [comment] 2020-03-06 13:57
> Linux Mint 19.3
> Mailspring 1.7.4 from snap package.. Same behavior using deb file
> 
> Having the same problem.. I tried to add an IMAP account.. once I click the connect account button.. the frame goes all white and hangs.. I figured out I could add a gmail account successfully .. and if I do that first, when I add my IMAP account, it continues and says it is added successfully. but the account never shows up anywhere.

Exactly the same thing happens to me. However, installing 1.7.2 as described above works.

**Comment by rcozzolino** [comment] 2020-03-06 14:48
Has anyone tried to upgrade after accounts are set? I am officially afraid to, but curious.

**Comment by StevenMapes** [comment] 2020-03-06 14:51
I had the problem on Mint and Kubuntu but I fixed the kubuntu version by removing the apt version and installing the snapd package and since then it's been working fine with multiple accounts whilst staying up to date

**Comment by DrAlgernopKrieger** [comment] 2020-03-06 14:56
> Has anyone tried to upgrade after accounts are set? I am officially afraid to, but curious.

You will anyway get into trouble if you want to add another account later on.

**Comment by ImranR98** [comment] 2020-03-11 22:42
Same issue for me on Pop!_OS 19.10. Using 1.7.2 fixes it and the accounts still work after updating to 1.7.4. Hopefully this is fixed soon.

**Comment by redburn1994** [comment] 2020-03-12 20:54
Same here. Fresh mailspring 1.7.4, both installed from website and from snapd, on fresh linux mint 19.3 installed. Thing is that two days ago I had linux 19.2 and some older version of mailspring and everything worked well.

**Comment by andreideak** [comment] 2020-03-12 21:46
I was unable as well to add any other accounts - but I was able to add Gmail accounts, with the 1.7.4 build. 
I have the mailboxes for my domain, for which I use IMAP - configuration successful, account never showing up in the list.

Tried on Windows 10 1909 -> same issue with the IMAP configuration
1.7.4 on Ubuntu 18.04 -> same issue with IMAP account
1.7.2 on Ubuntu 18.04 -> works without any issues. 

Thanks @fabricio-garcia for pointing to the repository for 1.7.2, good ideea.
We'll wait for the next 1.7.x update. :-)

**Comment by pkhural** [comment] 2020-03-13 09:25
Same issue for me on Fedora 5.5.8-200.fc31.x86_64, installing 1.72 resolved the issue and i was able to add 2 accounts

**Comment by mlgoodson** [comment] 2020-03-17 14:23
Same issue usign 1.74 on Ubuntu 19.10.  I can add google accounts, but not any other (Outllook.com, generic smtp account) .  The add process goes without generating an obvious error, but it does not show up in the account list (I have less than 4 accounts) or in the config file in the snap directory.  It doe not matter if I add the other accounts first on a fresh install.

**Comment by stanclarke-jr** [comment] 2020-03-18 14:01
> > Linux Mint 19.3
> > Mailspring 1.7.4 from snap package.. Same behavior using deb file
> > Having the same problem.. I tried to add an IMAP account.. once I click the connect account button.. the frame goes all white and hangs.. I figured out I could add a gmail account successfully .. and if I do that first, when I add my IMAP account, it continues and says it is added successfully. but the account never shows up anywhere.
> 
> Exactly the same thing happens to me. However, installing 1.7.2 as described above works.

Same issue on Kali 5.4 and Mailspring 1.7.4. Installing 1.7.2 worked for my system as well.

**Comment by mlgoodson** [comment] 2020-03-19 03:46
I can confirm that if you remove 1.7.4 and install 1.7.2, you can add accounts.  You can then upgrade to. 1.7.4 and the accounts are still there and usable, so a bit of a work-around.  I suspect (don't know) that it has something to do with getting a client authentication established with accounts other than gmail.  I should mention that the install/upgrade I did was with the .deb packages not the snap (I just didn't try it).

**Comment by Shootify** [comment] 2020-03-19 20:13
happening to me right now, it doesnt show others accounts after successfully added.

**Comment by stanclarke-jr** [comment] 2020-03-19 20:31
> I can confirm that if you remove 1.7.4 and install 1.7.2, you can add accounts. You can then upgrade to. 1.7.4 and the accounts are still there and usable, so a bit of a work-around. I suspect (don't know) that it has something to do with getting a client authentication established with accounts other than gmail. I should mention that the install/upgrade I did was with the .deb packages not the snap (I just didn't try it).

Was also able to upgrade and keep accounts.

**Comment by wuyuanyi135** [comment] 2020-03-20 12:50
Update: I have upgrade my Ubuntu to 19 and this problem is gone so cannot provide more information.

**Comment by RemyyB** [comment] 2020-03-21 19:48
I'm on Windows 10 with Mailspring 1.7.4-d54ff730 and I have the same problem, I can add mails via Gmail etc. but SMTP & Imap isn't working, it says the email account is added but then the window closes and nothing happens.

**Comment by andrejberg** [comment] 2020-03-23 11:23
Same here with Ubuntu 18 5.3.0-28-generic. Version 1.7.2 works. 1.7.4 even breaks if I add a custom IMAP account as the first one.

**Comment by AdaLollA** [comment] 2020-03-23 12:23
I'm on Windows 10 with Mailspring 1.7.4-d54ff730. Same problem: i can go through the entire input section and configure the new accounts (tried several different mail accounts) and get a "success message" at the end of the process. However the accounts are never actually added it seems. They do not show up in the account section of the preferences, nor in the navigation bar in the main ui.

**Comment by marcwieland95** [comment] 2020-03-28 12:17
Same for me on macOS. Version 1.7.4 and only on IMAP accounts

**Comment by IamNaN** [comment] 2020-03-28 17:10
No joy for me either. I'm on Debian 18.04.3 LTS, Linux 5.3.0-42, GTK 3.22.30 (Elementary 5.1.2). It sounds like I picked the exact wrong moment to try out a new desktop. :man_facepalming: I'm going to  try downgrading if possible.

**Comment by ravigehlot** [comment] 2020-03-29 18:20
On my system, Mailspring adds up to 5 accounts in total. An attempt to add an additional account does not add it, even though, the new account seems to successfully "connect". I briefly looked at Mailspring's log files looking for any reference to the additional account. There was no log entry that I could find. There were log files for the accounts that were successfully added.

Some info on my system:

Linux Ubuntu version: 19.10 (eoan)
Kernel version: 5.3.0-42-generic
X.Org version: 1.20.5
Window Manager: Ubuntu GNOME
MailSpring version: 1.7.4-d54ff730

Also, removing(pressing on the delete keystroke) email threads by keystrokes does not seem to be working on my system. I have to manually click on the trash icon. This might rather be reported as a bug instead. I am just not sure yet if this warrants a bug report. Thanks in advance!

Kindest Regards,
Ravi.

**Comment by ccodestaff** [comment] 2020-03-30 16:30
Same here, I can add the account successfully using IMAP/SMTP accounts but for some reason I can't find it. Experienced with macOS, Windows and Linux Mint.

Currently I'm using:
Windows 10
![imagem](https://user-images.githubusercontent.com/33130229/77937132-ccd97980-72ab-11ea-9729-904ed557fcaf.png)

Kind regards,
Marcelo Coelho

**Comment by dprn** [comment] 2020-04-01 09:28
Same here, fresh mailspring install. I can add gmail accounts without any problem, but the custom IMAP one does not show on the account lists (even though it is supposedly added succesfully).

Currently using Windows

**Comment by 7Kronos** [comment] 2020-04-02 14:59
Same here, on Arch Linux version 1.7.4

**Comment by eporedieis** [comment] 2020-04-03 17:22
Same here, using Mailspring 1.7.4 on Mac OS X 10.15.1

**Comment by GiannisKout** [comment] 2020-04-04 19:40
I have the same problem with Mailspring 1.7.4 on Ubuntu 18.04. It doesn't actually adds any other account except gmail...

**Comment by Michael-Schaer** [comment] 2020-04-04 19:59
Windows 10 can confirm the issue. Failing to add a second account with GMX & Yahoo.

**Comment by RemyyB** [comment] 2020-04-05 17:18
Can people stop saying they have the same issue, it's clearly not OS related and common so adding "I have the same issue" is quite useless now. :)

**Comment by mlgoodson** [comment] 2020-04-05 19:48
I agree with RemyyB.  As I have mentioned in my prevision comment, a workaround is:
completely uninstalling 1.7.4 and then installing [1.7.2,](https://github.com/Foundry376/Mailspring/releases/tag/1.7.2). This version makes it so you can add accounts. You can then upgrade to. 1.7.4 and the accounts are still there and usable.

I have also submitted a support request to tell the developers about this issue and point them to this thread. Hopefully the next version will sort this out.  

Cheers.

**Comment by marvinjuette** [comment] 2020-04-09 19:32
I updated to 1.7.5 beta and it also works there! :)

**Comment by tpaixao** [comment] 2020-04-13 23:35
> I updated to 1.7.5 beta and it also works there! :)

How did you install the beta version? I am using snap. Is it possible to upgrade when using the snap version?

**Comment by marvinjuette** [comment] 2020-04-13 23:37
I used this command to install 1.7.5: `sudo snap install mailspring --edge`

**Comment by tpaixao** [comment] 2020-04-13 23:44
Thanks! that worked.

**Comment by gugacavalieri** [comment] 2020-04-22 11:35
`1.7.5` is already available in the snap stable repository.

Updated by running: `snap refresh mailspring` :)

**Comment by siucdude** [comment] 2021-01-28 07:52
I have Ubuntu 20.10 and running 1.8 and i can confirm that this still is a bug... I can't add any second account.. Also people recommend to install 1.7.2 first, problem is in Ubuntu 20.10 the python package changed and we can't install old version..

**Comment by CodeMouse92** [comment] 2021-01-28 15:59
Hi all,

2020 prevented much development work on Mailspring, but rest assured, development has resumed! We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

@siucdude: Since this is still broken with 1.8.0, would you be willing to open a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 15:59 UTC
Labels: audit, bug, needs-reproduction
