### ISSUE TITLE
Avoid corruption of config.json on unexpected shutdown

### ISSUE THREAD

**Issue by brandondube** [Foundry376/Mailspring#463] opened 2017-12-20 19:39 UTC
Unexpected shutdowns (e.g. OS crash) will cause config.json to become corrupted.  I believe this is because Mailspring keeps it open for R/W axis, so it becomes corrupted if Mailspring doesn't shut down properly.

The client should behave in a way that is robust against this issue.

**Comment by ElectricCookie** [comment] 2017-12-24 01:19
This happened to me too after windows crashed!

**Comment by shaunidiot** [comment] 2018-03-23 02:45
Any updates on this? I'm having this problem as well and the error persists after
1. Restarting of MailSpring and the PC itself.
2. Reinstalling with removal all folders on MailSpring from AppData/Local and AppData/Roaming.

Multiple copies of `config.json.local-<some unique id>.bak` is getting replicated in MailSpring folder in AppData/Roaming.

I've tried copying the data from `config.json`, deleting the file itself, then pasting the content into a new `config.json` file but problem still persists.

**Comment by M1n15ter** [comment] 2018-04-10 00:31
Ive got the same problem. Ive tried reinstalling it, but doesnt make any difference. I dont believe that the beginning of it was a crash or anything. In fact I cannot determine what kicked it off. I love the programme but this is just annoying. 
Any movemnet on a solution for this yet?

**Comment by ccc5vd** [comment] 2018-06-19 07:01
Adding my +1 here. Believe it is the same issue as what occurred in Nylas Mail, see thread [here](https://github.com/nylas/nylas-mail/issues/2518). It looks like they developed a fix in Nylas 0.4.51, but that it reoccurred in a later release, and has popped back up here. Hopefully this means it's an easy fix?!

**Using the bug report template:**

Are there any related issues?
No.

What operating system are you using?
Windows 10.0.17134 Build 17134

What version of Mailspring are you using?
1.2.2

Bug?
Told that Mailspring failed to load config.json due to unexpected token, meaning I have to completely redo my config, adding new accounts, updating signature, etc. This is the third time this has happened in the last week, 2 of the three were related to a crash/unexpected shutdown, one was during normal conditions.

Do you have any third-party plugins installed?
No.

Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail, but not sure that's related.

Is the issue reproducible with a particular attachment, message, signature, etc?
Just launching Mailspring

Absolutely love all the features of Mailspring and would love to upgrade to pro, but this could be a dealbreaker if not fixed--it's a huge pain to have to reload all my accounts each time!

**Comment by robert-winkler** [comment] 2018-10-22 12:04
+1 just happened to me (due to an unexpected update of Windows?). 
I just subscribed to the Pro Version..

**Comment by ElectricCookie** [comment] 2018-10-23 16:17
Mailspring should simply make backups of config.json before changing. Always reinstalling profiles whenever windows feels like bricking something is pretty painful.

**Comment by Bobbycharlton1** [comment] 2019-02-22 14:27
i am having this issue constantly.  my laptop will sometimes be off over night when I open it in the morning, for reasons I do not know.  but every time it does, I get the config.json error on start and I have to re-configure mailspring every time.

**Comment by lopugit** [comment] 2019-03-21 03:21
bump

**Comment by JustSid** [comment] 2019-03-21 17:47
This happens so regularly to me that I'm unfortunately going to switch away from Mailspring. It's great when it works, but I don't want to set it up from scratch every few weeks. It's very frustrating and sure, I could make a backup of a good config.json somewhere, but I don't want to hand hold applications.

**Comment by sandsou** [comment] 2019-06-29 12:50
I am also fed up with this issue. Setting up the app from ground whenever my computer crashes is simply troubling enough to defeat the purpose of convenience of using MailSpring at the first place.

**Comment by timersys** [comment] 2019-07-25 14:56
same, I already started over twice. Won't do it again

**Comment by paulocoghi** [comment] 2020-02-11 12:38
Unfortunately, same here. I reconfigured Mailspring twice after the error on a Windows PC from a customer. And the error is repeating.

**Comment by desyatnik** [comment] 2020-02-18 09:21
Same issue here after sudden shutdown (windows 10). I'm not going to dump Mailspring, since it's the only email client I found (tried them all more or less) that plays nicely with multiple email accounts, however a fix would be great.

**Comment by JustSid** [comment] 2020-02-18 09:29
@desyatnik I was in the same boat when I ditched Mailspring last year. I'm still subscribed to the issue and shocked that this is still a problem, so I'm hoping to be able to give you a suggestion for an alternative: eM Client. It's not free and it only works on Windows and macOS. But if that's okay for you, it's an absolutely fantastic mail client. And it doesn't corrupt its own config when it doesn't cleanly exit :P

**Comment by desyatnik** [comment] 2020-02-18 09:43
@JustSid Hey Sidney, thanks for the suggestion! 
I was so happy when I discovered an email client that knows how to do unified inbox (looking at you Outlook) and search across several email accounts, but this issue is weird and kind of unpromising bearing in mind that it was open more than 2 years ago. 
I'm still willing to give Mailspring another chance, but will keep an eye on other options and definitely check out this eM Client.
Thanks again!

**Comment by ElectricCookie** [comment] 2020-02-18 19:44
Switched to em too and now to stock mail on the Mac. I loved mailspring but 1 setup every month was too much.

**Comment by ibrahimhajjaj** [comment] 2020-03-02 08:54
Switched to em too, res setup every week is too much!

**Comment by Cantfirmed** [comment] 2020-05-11 17:35
How can this still not be fixed? This is a major issue.

**Comment by PavelHonza** [comment] 2020-09-10 11:58
Fuck! Few hours setting of all for nothing. Finish with mailspring......

**Comment by paulocoghi** [comment] 2020-09-10 12:50
It seems this issue is related to the ones mentioned by @ccc5vd. This happened before on Nylas, detailed [here](https://github.com/nylas/nylas-mail/issues/2518) and the fix was reviewed by @bengotow .

If this is a regression from Nylas, propagated to Mailspring, maybe we already have the solution.

**Comment by ashtez** [comment] 2020-11-27 14:37
Yes, Windows just bluescreened me, and then Mailspring greets me with this error. Always a pleasure.

**Comment by CodeMouse92** [comment] 2021-01-29 21:48
Hi all,

Thanks for reporting this! It probably got buried in the backlog, but I've marked it for inclusion on the new roadmap.

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/regression-avoid-corruption-of-config-json-on-unexpected-shutdown/386

Please consider joining that community and continuing the discussion there!

@brandondube @paulocoghi : if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-29 21:48 UTC
Labels: audit, windows
