### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by odinian** [Foundry376/Mailspring#2244] opened 2020-12-29 20:28 UTC
**Is your feature request related to a problem? Please describe.**
Using MailSpring 1.78 on Windows 10. How can I show the Menu Bar?

**Describe the solution you'd like**
I would like a preference to always show the menu bar.

**Describe alternatives you've considered**
Thunderbird

Seems like there used to be a menu bar, then an option to hide it, and now there is no option to show it. I'm new to Windows (coming from Mac), and the lack of menu bars in Windows apps is really annoying.

**Comment by CodeMouse92** [comment] 2021-01-18 23:30
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/option-to-show-menu-bar-on-windows/91

Please consider joining that community and continuing the discussion there! Bonus: if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-18 23:30 UTC
Labels: audit, enhancement
