### ISSUE TITLE
Management Of Contacts

### ISSUE THREAD

**Issue by matyhaty** [Foundry376/Mailspring#1895] opened 2020-04-09 08:31 UTC
When composing emails and entering into the To, CC and BCC fields Mailspring autocompletes.

However the emails that come up are often old, or dead.
Where is mailspring getting these emails from?
Is there a way I can manage these.

Quote often this happens:

Billy Jean @ oldcompany.com
Billy Jean @ amothercompany.com
Billy Jean @ Currentcompany.com

So to actually get to Billy's latst email address I have to click on the third auto suggest, and sometimes I might accidentally choose the wrong one.

Ive listed this as a bug, as its a crucial issue (as its using bad data), but might end up as something else.

**Comment by bengotow** [comment] 2020-04-16 15:28
Hey @matyhaty! Thanks for reporting this. Mailspring finds contacts in your sent mail and offers them as suggestions by default. You can disable this feature by going to Window > Contacts, clicking "Found in Mail" and disabling it here:

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/1037212/79475085-d7468380-7fcc-11ea-8d1a-c74ab67c5c6d.png">

I'll see if we can link to the contacts window in a few more places so this is easier to find. It's also worth mentioning that with it turned off, Mailspring will only offer suggestions if it supports your account's address book (currently Google, O365, Yahoo, and iCloud only I believe.)

**Comment by matyhaty** [comment] 2020-04-17 06:42
@bengotow 
Thanks for the feedback
I can see that option, the main problem is that contacts are not coming over from Google.

Ive ensure im on latest version, Windows.
I have removed the account and re-added
retsarted and all that stuff
Ensured that there are contacts in the Gmail Contact part

But my contact remains empty

Any suggestions (im making the assumption that the contacts sync between mailspring and gmail of course!)

**Comment by renguer0** [comment] 2020-10-19 17:19
I have the same problem. I'm using Mailspring with an owned domain and I can't use groups to send e-mails.

Thanks for your time!

**Comment by CodeMouse92** [comment] 2021-02-27 02:53
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/management-of-contacts/851

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@matyhaty @renguer0: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-27 02:53 UTC
Labels: audit, bug, contacts
