### ISSUE TITLE
Feature Request: go back to email list after archiving

### ISSUE THREAD

**Issue by ghuba** [Foundry376/Mailspring#2057] opened 2020-06-18 18:15 UTC
**Is your feature request related to a problem? Please describe.**

After archiving an email, the next or previous email in the inbox is shown.

**Describe the solution you'd like**

I would like to have the option of archiving without opening any email afterward (just returning to the list of emails in the inbox).

**Describe alternatives you've considered**

I could not find a way to do this.

**Additional context**
None

**Comment by CodeMouse92** [comment] 2021-03-02 02:50
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/customize-auto-advance-behavior-upon-archive-delete/493/3

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@ghuba: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 02:50 UTC
Labels: audit, enhancement
