### ISSUE TITLE
Snoozing emails errors out

### ISSUE THREAD

**Issue by makrandgupta** [Foundry376/Mailspring#1427] opened 2019-03-20 23:16 UTC
##### Are there any related issues?

None that I can find

##### What operating system are you using?
Windows 10

##### What version of Mailspring are you using?
1.6.0-10f5c95c
--

**Bug?**

##### Is this an email sync or connection issue?

Neither. It's relating to the sync 

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

When hitting the snooze button, it errors out with:
```
Cannot read property `snooze` of undefined
```
This happens on a fresh install on Windows.
Here's a GIF:
![20bce88e-2275-4148-a969-f9e20a6c93e9](https://user-images.githubusercontent.com/9060170/54725217-a46d5a00-4b44-11e9-8661-14b12ef99cf0.gif)

**Comment by CodeMouse92** [comment] 2021-01-30 00:30
Hi all,

2020 prevented much development work on Mailspring, but rest assured, development has resumed! We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

@makrandgupta: Can you please confirm that this is still broken with 1.8.0, and if so, open a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-30 00:30 UTC
Labels: audit
