### ISSUE TITLE
[Feature Request] Additional 'Default' Notification Actions

### ISSUE THREAD

**Issue by Richyread** [Foundry376/Mailspring#371] opened 2017-11-27 17:34 UTC
The current banner/alert provides the option to view the message only, please could you consider adding [Delete Msg] [Archive Msg] [Close/Dismiss] as additional selection options?

Note - this is a request for reusing the existing _default_ functionality: I appreciate that allowing for _Customised/User defined_ notification actions is a separate ball game completely! :-)

If implemented, when combined with the request for enabling/disabling notifications per account, it would substantially cut down on interruptions/notification overload for users with multiple accounts and allow for improved workflow.

E.g.
- Sales email slips through SPAM filter >> Quick Delete
- Read receipt from colleague >> Quick Archive

Etc.  
Richy.

**Comment by applesea2** [comment] 2018-01-06 17:46
Please add this! This is already a feature in the default mail client for Windows 10 and is extremely useful

**Comment by CodeMouse92** [comment] 2021-02-20 03:37
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/additional-default-notification-actions/716

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@Richyread @applesea2 @jerm: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-20 03:37 UTC
Labels: audit, enhancement
