### ISSUE TITLE
[Feature Request] Multiple Profiles

### ISSUE THREAD

**Issue by Modelmat** [Foundry376/Mailspring#163] opened 2017-10-15 01:07 UTC
**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
In Outlook
...

Would it be possible to support multiple profiles, just like Outlook? It would be useful.

**Comment by bengotow** [comment] 2017-10-15 07:34
Can you elaborate on what a profile is? Mailspring supports multiple accounts, with accounts having different signatures, etc.

**Comment by Modelmat** [comment] 2017-10-15 07:37
A Profile is an item higher up the tier eg:
`-Home
---foo@home.com
---bar@home.com
-Work
---foo@work.com
---bar@work.com` 

This allows me to open a set of accounts (like in All Accounts) that is JUST work, or JUST home, while still seeing more than one at once.

**Comment by lxalln** [comment] 2017-11-13 20:59
I'd find this feature very useful to.
I'm now involved in managing a sports club, and have access to the club email account. This account gets a tonne of emails, and just gets in the way of my combined inbox.

I've love to be able to stick it in a different folder and only check it when I needed to.

**Comment by artsgirl** [comment] 2019-02-18 13:30
+1 to this

I would even be happy if it was just a matter of being able to split out the unified inboxes. For example, a "work" unified inbox and a "personal" one, and then assign specific addresses into each one. I'm managing about 10 email addresses, and right now it's either see all emails at once or look at one individual account at a time.

**Comment by CodeMouse92** [comment] 2021-01-29 21:38
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be best covered by another feature suggestion already on our Discourse:

https://community.getmailspring.com/t/disable-selective-unified-inbox/136

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-29 21:38 UTC
Labels: audit, enhancement
