### ISSUE TITLE
Blank area instead of message previews

### ISSUE THREAD

**Issue by Draghmar** [Foundry376/Mailspring#1055] opened 2018-08-31 10:26 UTC
##### Are there any related issues?
I couldn't find any.

##### What operating system are you using?
Windows 10 64bit

##### What version of Mailspring are you using?
1.4.2

--

**Bug?**
I'm not entirely sure if it's because of this but when I have conversation selected and new e-mail appears it won't be set as read even if click anywhere on the preview and what's more important - some older messages are blank. Selecting any other thread and then again this one will fix the blank part and marking as read as well. Take a look at the screenshot to get the idea:
![mailspring-error](https://user-images.githubusercontent.com/275348/44907538-8bbc6480-ad18-11e8-8fda-ee1e49cb0a62.jpg)

##### Is this an email sync or connection issue?
Nope.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I don't know - I'm using Gmail.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
I didn't found any other pattern then one described above.

**Comment by CodeMouse92** [comment] 2021-02-02 02:15
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/many-emails-appear-white-empty/426/2

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-02 02:15 UTC
Labels: audit
