### ISSUE TITLE
Bug: Can't reply to email chains

### ISSUE THREAD

**Issue by ZeeshanSultan** [Foundry376/Mailspring#1930] opened 2020-04-22 22:29 UTC
**Describe the bug**
I synced the client using IMAP. I can send emails but can't reply to certain emails and the application gives the error of server being inaccessible. I have tried to send another new email at that very second and it worked. the issue is reproduced when I try to hit send on that same error-prone email multiple times 

**To Reproduce**
1. Replying to email chains synced via IMAP
2. See error

**Expected behavior**
Email was supposed to be sent but got this error instead

**Screenshots**
![image](https://user-images.githubusercontent.com/8667667/80039860-4151b200-8512-11ea-80f7-2126348fb1f2.png)

**Setup: (please complete the following information):**
 - OS: Windows
 - OS Version: 10
 - Mailspring Version: 1.7.6

**Comment by bengotow** [comment] 2020-04-22 23:03
Wow I think this is a new one! What email provider are you using? I think that the "Connection Error" is probably a bit of a red herring and your SMTP gateway is seeing something it doesn't like in the outbound message and terminating the connection. Maybe very strict spam rules or something?

**Comment by ZeeshanSultan** [comment] 2020-04-22 23:25
I am using, cPanel with the pre-configured mail server on my own VPS. Just sent the same mail from webmail (Horde) and it sent just fine so I am confident if there was any spam rule it would've been triggered. In fact, the client sent other emails just fine. Only some particular ones get this error.

As a side note: Until we have a stable release we can actually have a debug log option enabled for the client.

**Comment by ZeeshanSultan** [comment] 2020-04-22 23:56
Turned on debug flags, it lost all my mails and preferences but after resyncing sent the same mail. And voila It has been sent.

**Comment by CodeMouse92** [comment] 2021-02-27 03:43
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/cant-reply-to-email-chains/860

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@ZeeshanSultan: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-27 03:43 UTC
Labels: audit, bug
