### ISSUE TITLE
Unable to Compose Email

### ISSUE THREAD

**Issue by mavogaro** [Foundry376/Mailspring#584] opened 2018-01-26 15:30 UTC
When composing a new email, after about the 3rd word, the words disappear and the cursor goes back to the front of the sentence.
Running Ubuntu 17.10
Mailspring version:1.1.0-7563b09d
No plugins installed
Happens with all email accounts

**Comment by justindoran** [comment] 2018-01-26 17:46
I'm having a similar problem in MacOS, and it sounds related to #578. For me, the problem is created when I type a single-quote character ('). Going back to the Inbox and opening the draft in composer again frees it back up. It's intermittent: occasionally the single-quote won't cause the problem, but usually it does.

OS: MacOS High Sierra 10.13.2 (17C205)
Mailspring: 1.1.0 (1.1.0)
No plugins. Relatively standard settings.
Probably relevant: I'm using U.S.-International keyboard setting (the one that uses single-quotes to transform standard into accented characters)

**Comment by victortrac** [comment] 2018-01-27 17:26
I have a similar issue on Linux. I pop out a reply window to a thread, scroll up to the thread, and start typing in the new window. Every few seconds the thread scrolls down the composer there, which seems almost sync'd to what I typed in the new window. This is annoying in itself since I can't see  the email that I was trying to reference in my reply.  But worse is that sometimes the composer in the new window wipes away recent changes and puts the cursor at the beginning of my reply.

**Comment by bengotow** [comment] 2018-01-27 20:19
Hey! Thanks for the reports folks - I was able to reproduce this issue and it'll be fixed in the next release by c711a0c1b06e9a87ed2c9f31340ff999ca6745f5. Going to fast-track the release and it should be out in the next 24 hours. Stay tuned—

**Comment by bengotow** [comment] 2018-01-29 20:20
Hey folks—the fix for this has been shipped in 1.1.2. The app will auto-update in the next few hours, or you can download the new version directly from https://getmailspring.com/download. Enjoy! If you run into this in the new version (there's a small chance it wasn't the same issue as in c711a0c), please file a new issue and we can triage it separately.

**Closed by bengotow** 2018-01-29 20:20 UTC
Labels: bug, composer, done-pending-release

**Comment by vipranarayan14** [comment] 2020-04-19 10:42
I have the same problem in the popout composer.

In the popout composer, after some writing, some of the recent few words disappear and the cursor goes back to the start of the email.

Even in the normal composer the cursor often goes to the start of the email.

I noticed this happens whenever the "Syncing your mailbox..." message appears in the sidebar.

Setup:
- OS: macOS
- OS Version: 10.15.4
- Mailspring Version: 1.7.5
