### ISSUE TITLE
Bug: Largest font choice still not large enough

### ISSUE THREAD

**Issue by famewolf** [Foundry376/Mailspring#2178] opened 2020-10-23 03:20 UTC
Ok this is obviously an issue with my older eyes which need larger text nowadays to read.  I have the aA menu cranked all the way up to the largest size and it's still about 2 levels smaller than I really like.  Can the range be bumped up a few levels?

**Comment by CodeMouse92** [comment] 2021-03-03 03:32
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/largest-font-choice-still-not-large-enough/962

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@famewolf: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-03 03:32 UTC
Labels: audit, bug
