### ISSUE TITLE
Feature request: Move messages between mailboxes

### ISSUE THREAD

**Issue by koenpunt** [Foundry376/Mailspring#733] opened 2018-02-27 13:53 UTC
When I receive a mail from someone on my private address which is actually about business, I used to move the thread from one account to the other using Apple Mail. 

Mailspring currently doesn't support this, so whenever this now happens I still have to use Apple Mail to move the mail.

It would be great if Mailspring would support this too.

#### Are there any related issues?

No

#### What operating system are you using?

macOS

#### What version of Mailspring are you using?

Version 1.1.4 (1.1.4)

#### Does this feature exist in another mail client or tool you use?

Yes, Apple Mail

**Comment by bengotow** [comment] 2018-03-06 23:37
Duplicate of #580

**Closed by bengotow** 2018-03-06 23:37 UTC

**Comment by koenpunt** [comment] 2018-03-06 23:59
Turns out my search-fu isn’t that good.. or github issue search isn’t.. but at least I’m not the only one wanting this feature :)
