### ISSUE TITLE
Always one new mail notification

### ISSUE THREAD

**Issue by xoned1** [Foundry376/Mailspring#1570] opened 2019-07-10 16:11 UTC
I'm currently facing the bug, that regardsless of what i'm doing, there is always one new mail notification shown. It's happening only for one account but it never disappears.
I've checked `is:unread` but nothing is shown either. 

* OS: Windows 10
* Mailspring: 1.6.3-134a0e55
* Provider: Googlemail.

* No connection/sync issues.
* Other client: No

Edit: I forgot to mention that i mean the notification on the left side beside the Inbox

**Comment by TK42DAN** [comment] 2019-07-18 20:40
While mine isn't always there, on Mac, I have perhaps a similar issue. On Mac, the menu bar icon says I have mail, so I go, read and process the mail, literally get to inbox zero, the notification goes dark, and then about 30-60 seconds later I look up and the menu bar icon is blue again. I go back and there is never any new mail. Once I view the client again, the notification goes dark again and stays dark until I actually get some mail. Not a huge problem--not as annoying as what xoned1 is talking about--but still frustrating, especially for the OCD'ers among us. :)

**Comment by Tomschi** [comment] 2019-08-05 05:59
Can confirm the issue. Every time i change the focus to another application, the mail icon turns blue after some time. But there is no new mail in the inbox.

**Comment by EvanTsiatsios** [comment] 2019-09-07 20:45
While this is not a solution, I figured out if you go to Preferences->Accounts->Rebuild Cache, it removes the notification. Just in case someone is getting really annoyed and stumbles upon this.

**Comment by Funeoz** [comment] 2019-10-28 13:43
Same problem here : Kubuntu 19.10 / Mailspring 1.7.2-4522b259

**Comment by CodeMouse92** [comment] 2021-01-28 18:41
Thank you for reporting this. 2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/unread-count-still-on-without-unread-messages/350

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 18:41 UTC
Labels: audit
