### ISSUE TITLE
[Feature Request] Better account folder management

### ISSUE THREAD

**Issue by mirkoschubert** [Foundry376/Mailspring#1197] opened 2018-10-29 18:55 UTC
I use Mailspring for a while now and recommend it occasionally to friends. Today I recommended, installed and configured Mailspring for a friend on Windows 10. He has very specific archiving methods in multiple accounts with multiple folder and subfolder structures. So I stumbled upon an issue, that should be addressed and fixed:

Unlike me, many users archive their emails not in the dedicated archiving feature, but in an own subfolder structure. Yes, there is a way to handle extra folders per account, but it's not possible to **create subfolders** in the account or **move folders** into another folder. It's also not possible to move folders with multiple emails **from one account to another**. Not to mention that I didn't find any **local storage**, so that some emails (or folders with emails) don't appear at the mail server anymore.

This should be fixed, since almost every other email client provides such features.

##### Are there any related issues?

I didn't find anything, but to be fair, I didn't search very long...

##### What operating system are you using?

Windows 10, MacOS Mojave - I think, it's not dependent on the OS

##### What version of Mailspring are you using?

1.5.1

--

It's a little bit of both - a bug and a feature request. 😏 

**Bug?**

##### Is this an email sync or connection issue?

No.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

It's reproducible for everyone. I tested it on Windows and macOS.

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

The feature exists in supposedly every email client. I know it for sure for Apple Mail, Airmail, Windows Mail, Mozilla Thunderbird, Microsoft Outlook (+Express)

**Comment by CodeMouse92** [comment] 2021-02-03 17:39
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/creating-subfolders-clarify-interface/443

This issue also relates to another migrated feature request:

https://community.getmailspring.com/t/move-emails-and-folders-between-accounts/244

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestions on Discourse will increase the likelihood we implement this.**

@mirkoschubert: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-03 17:39 UTC
Labels: audit
