### ISSUE TITLE
[Feature Request] Keep the next email unread after archiving

### ISSUE THREAD

**Issue by paulgaumer** [Foundry376/Mailspring#1502] opened 2019-05-18 13:20 UTC
**Feature Request?**
I have been loving Mailspring so far but this feature would improve the UX quite a lot.

As for now, everytime I archive a message from the inbox, Mailspring moves to the next or previous unread message, marking it read straight away. Having the option to keep it unread until user action (click, archive...) would be awesome.

##### Does this feature exist in another mail client or tool you use?
Airmail does it
...

**Comment by bengotow** [comment] 2019-05-26 21:35
Hey @paulgaumer — thanks for reporting this, this seems like a great idea. I'll see if we can add this as an option soon. Right now you can choose to "Mark as read after..." a number of seconds, but it seems like we need a new option in that dropdown that is "upon action".

**Comment by FXschwartz** [comment] 2019-06-23 20:27
Hey @bengotow - Looking to get into contributing to Mailspring and would like to give this a try. As a first timer can you point me into the right direction on where the mail preferences live in the code base?

**Comment by paulgaumer** [comment] 2019-09-03 08:36
Hi there! Just a follow up on this issue to see if @bengotow or @FXschwartz had time to look at it? I'd love to help but I'm not sure where to start.

**Comment by CodeMouse92** [comment] 2021-02-08 18:50
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/keep-the-next-email-unread-after-archiving/492

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@paulgaumer, @FXschwartz: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-08 18:50 UTC
Labels: audit, enhancement, good first issue
