### ISSUE TITLE
sync_error v 1.7.2

### ISSUE THREAD

**Issue by enrico-guida** [Foundry376/Mailspring#1792] opened 2020-02-06 08:08 UTC
Hi, I keep experiencing sync error.
After synchronizing the account again, I re-download the emails and after a few minutes the error occurs again.

In config.json I found:

`"aliases": [],
        "syncState": "sync_error",
        "syncError": {
          "code": null,
          "error": {
            "stack": "Error: nullhttps://osiris.rockethosting.it/:1: parser error : Opening and ending tag mismatch: META line 1 and head\n\"><META HTTP-EQUIV=\"refresh\" CONTENT=\"0;URL=/cgi-sys/defaultwebpage.cgi\"></head>\n                                                                               ^\nhttps://osiris.rockethosting.it/:1: parser error : Opening and ending tag mismatch: META line 1 and html\n\"refresh\" CONTENT=\"0;URL=/cgi-sys/defaultwebpage.cgi\"></head><body></body></html\n                                                                               ^\nhttps://osiris.rockethosting.it/:2: parser error : Premature end of data in tag head line 1\nhttps://osiris.rockethosting.it/:2: parser error : Premature end of data in tag html line 1\n34676 [2020-02-06 08:53:17.353] [calContacts] [critical] \n ***\n *** An exception occurred during program execution: \n *** (unknown exception details)\n ***\n\n34676 [2020-02-06 08:53:17.877] [calContacts] [critical]  *** Stack trace (line numbers are approximate):\n *** in mailsync     DavXML::DavXML(__1::string, __1::string)\n *** in mailsync     DAVWorker::performXMLRequest(__1::string, __1::string, __1::string)\n *** in mailsync     DAVWorker::resolveAddressBook()\n *** in mailsync     DAVWorker::runContacts()\n *** in mailsync     DAVWorker::run()\n *** in mailsync     runCalContactsSyncWorker()\n *** in mailsync     main::$_7::operator()() const\n *** in mailsync     void* __1::__thread_proxy(void*)\n *** 0x7fff8c73799d  _pthread_body\n *** 0x7fff8c73791a  _pthread_body\n *** 0x7fff8c735351  thread_start\n ***\n\nlibc++abi.dylib: terminate_handler unexpectedly threw an exception\n\n    at ChildProcess.onStreamCloseOrExit (file:///var/folders/bb/n7t3rs157850byt_jfdcq9k80000gn/T/nylas-build/electron-packager/darwin-x64/Mailspring-darwin-x64/Electron.app/Contents/Resources/app/src/mailsync-process.ts:289:17)\n    at ChildProcess.emit (events.js:182:13)\n    at ChildProcess.EventEmitter.emit (domain.js:442:20)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)",
            "message": "nullhttps://osiris.rockethosting.it/:1: parser error : Opening and ending tag mismatch: META line 1 and head\n\"><META HTTP-EQUIV=\"refresh\" CONTENT=\"0;URL=/cgi-sys/defaultwebpage.cgi\"></head>\n                                                                               ^\nhttps://osiris.rockethosting.it/:1: parser error : Opening and ending tag mismatch: META line 1 and html\n\"refresh\" CONTENT=\"0;URL=/cgi-sys/defaultwebpage.cgi\"></head><body></body></html\n                                                                               ^\nhttps://osiris.rockethosting.it/:2: parser error : Premature end of data in tag head line 1\nhttps://osiris.rockethosting.it/:2: parser error : Premature end of data in tag html line 1\n34676 [2020-02-06 08:53:17.353] [calContacts] [critical] \n ***\n *** An exception occurred during program execution: \n *** (unknown exception details)\n ***\n\n34676 [2020-02-06 08:53:17.877] [calContacts] [critical]  *** Stack trace (line numbers are approximate):\n *** in mailsync     DavXML::DavXML(__1::string, __1::string)\n *** in mailsync     DAVWorker::performXMLRequest(__1::string, __1::string, __1::string)\n *** in mailsync     DAVWorker::resolveAddressBook()\n *** in mailsync     DAVWorker::runContacts()\n *** in mailsync     DAVWorker::run()\n *** in mailsync     runCalContactsSyncWorker()\n *** in mailsync     main::$_7::operator()() const\n *** in mailsync     void* __1::__thread_proxy(void*)\n *** 0x7fff8c73799d  _pthread_body\n *** 0x7fff8c73791a  _pthread_body\n *** 0x7fff8c735351  thread_start\n ***\n\nlibc++abi.dylib: terminate_handler unexpectedly threw an exception\n"
          },
          "signal": "SIGABRT"
        },
        "__cls": "Account"`

are you aware of this bug?

Thank You

**Comment by d3vCr0w** [comment] 2020-02-10 14:48
I'm also experiencing Sync issues, whenever I try to compose a new email, I get a message saying: "Mailspring is unable to syna my@email.com", "In order to perform actions on this mailbox you need to resolve the sync issue. Visit Preferences > Accounts for more information."

**Comment by enrico-guida** [comment] 2020-02-11 07:52
yes the same. then I reconfigure the email, download the new email and shortly after the error occurs again. this thing starts to be annoying!

**Comment by enrico-guida** [comment] 2020-02-12 12:55
small update:
before updating the setting of the mail connections (for the umpteenth time), I started the rebuilding of the cache ... now it is 2 hours that is not giving problems.
I wish I had solved it this way.
I keep you updated

**Comment by jrodd96** [comment] 2020-02-12 14:54
I too am suddenly experiencing sync errors with all three of my Gmail accounts on Mailspring after previously having no issues at all for several months of use.

I have tried re-authenticating, but even though it appears successful the mailboxes will still refuse to sync.

Here is the error:
`Mailspring is unable to sync ***@gmail.com`
`In order to perform actions on this mailbox, you need to resolve the sync issue. Visit Preferences > Accounts for more information.`

l have also tried rebuilding the cache, but this error appears whenever that is attempted:
`Cleanup Error`
`Mailspring was unable to reset the local cache. Error: Account is missing required fields:imap_password or refresh_token`

Mailspring Version:     1.7.2
OS:                             Pop! OS 19.10
PC:                              Dell Inspiron 5579

**Comment by enrico-guida** [comment] 2020-02-13 07:35
Compared to my last post yesterday, I confirm that even when rebuilding the cache the error occurs again

**Comment by sebastian1130** [comment] 2020-02-13 12:58
The same over here, same configuration in 3 different email clients, and only Mailspring fails with the same error: Mailspring is unable to sync ***@gmail.com.

No solution, it seems.

**Comment by SebasVelez34** [comment] 2020-02-13 18:34
I'm also experiencing Sync issues, whenever I try to compose a new email, I get a message saying: "Mailspring is unable to sync my@email.com", "In order to perform actions on this mailbox you need to resolve the sync issue. Visit Preferences > Accounts for more information."

**Comment by enrico-guida** [comment] 2020-02-28 07:52
no response from the team,
thank you, Mailspring Team!

**Comment by xplreitr** [comment] 2020-03-09 17:11
I am also experiencing syncing errors

The logs report
```
6992 [2020-03-09 10:33:07.779] [background] [info] Sync loop deleting unlinked messages with phase 2.
6992 [2020-03-09 10:33:07.782] [background] [info] Sync loop complete.
6992 [2020-03-09 10:33:11.408] [metadataExpiration] [info] Scanning for expired metadata
6992 [2020-03-09 10:33:11.409] [metadataExpiration] [info] -- Will wake for next expiration in 7200sec
6992 [2020-03-09 10:33:16.281] [calContacts] [critical]  *** Stack trace:
 ***   raise
 ***   abort
 ***   terminate
 ***   _is_exception_typeof
 ***   _is_exception_typeof
 ***   RtlInterlockedCompareExchange64
 ***   RtlInterlockedCompareExchange64
 ***   KiUserExceptionDispatcher
 ***   _CxxThrowException
 ***
```
- mailspring version = 1.7.4-d54ff730 
- Windows 10 v1809
- connecting via imap with inmotionhosting.com

**Comment by CodeMouse92** [comment] 2021-02-02 02:33
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/the-eternal-sync-bug/334

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-02 02:33 UTC
Labels: audit
