### ISSUE TITLE
Attachments not downloading - Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by billytcl** [Foundry376/Mailspring#6] opened 2017-10-03 18:18 UTC
##### Are there any related issues?

...

##### What operating system are you using?
Windows 10

##### What version of Mailspring are you using?
v1.0.0-20839f9b

--

**Bug?**
Cannot download any attachments. Gives an error - "Check your network connection and try again. Error: ENOENT: no such file or directory, open [FILE NAME, APPDATA LOCATION]

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Have only tried in Gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?

![image](https://user-images.githubusercontent.com/10386511/31141498-72425074-a82c-11e7-8f05-136e95c6a28f.png)

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment] 2017-10-03 20:10
Hey @billytcl thanks for reporting this—trying to reproduce it on Windows now.

**Comment by bengotow** [comment] 2017-10-03 20:54
This will be fixed in the next update—turns out there was a bug in mailcore2 that was preventing Mailspring from creating new files on Windows! Stay tuned—

**Comment by bengotow** [comment] 2017-10-04 19:23
Version 1.0.1 started shipping a few minutes ago, so this should be fixed now. Let me know if you still see this after updating!

**Closed by bengotow** 2017-10-04 19:23 UTC
Labels: done-pending-release

**Comment by elCanarioVidal** [comment] 2017-10-17 16:27
Hi Guys

I have the last update, but this error still happens
Some help?
