### ISSUE TITLE
Quick way for temporary disable / enable accounts

### ISSUE THREAD

**Issue by MurzNN** [Foundry376/Mailspring#1271] opened 2018-12-17 08:27 UTC
When user use multiple email accounts, sometime it need to temporary hide some of them (eg when go to vacation - hide work email). Will be good to have option to temporary disable account, without deleting.

**Comment by CodeMouse92** [comment] 2021-02-03 17:28
Duplicate of #1739

**Closed by CodeMouse92** 2021-02-03 17:28 UTC
Labels: audit
