### ISSUE TITLE
Having a way to export/copy/backup emails

### ISSUE THREAD

**Issue by sebastian-code** [Foundry376/Mailspring#1368] opened 2019-02-13 18:54 UTC
It would be nice to be able to export/copy/backup emails as `.eml` and `.mbox` files or any compatible format; being able to use local (or remote) folders so users can free server space in those cases where they have inbox size restrictions.

Are there any plans to work in this somehow or are there any existing solution people use without an additional email client?

##### Are there any related issues?

Yes, directly related to these request are the issues #264  #1012 and mildly related is #1109 

##### What operating system are you using?

Ubuntu Linux 18.04

##### What version of Mailspring are you using?

1.5.6

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

Yes, I'm aware this feature is available at least in MS Outlook, Thunderbird and Evolution, perhaps there are other email clients where the user is able to do it.

**Comment by lski** [comment] 2019-03-19 19:20
To expand on the clients that also do this feature is "em Client" and I also would appreciate this feature.

**Comment by Hope2Code** [comment] 2019-06-15 13:02
PLEASE add this?

Have a look at Em-Client (as noted above by Iski). It manages too import EVERYTHING + keep local copies. M$ only, unfortunately, but it is miles above their awful Outlook in every way. If Mailspring could do what Em-C does, it would immediately become the hottest client for sure!

**Comment by mrvik** [comment] 2019-12-27 16:50
Atm you could copy `.config/Mailspring` to backup config and IDK if mail folders too. But an official way to export mail to a standard format is needed.

**Comment by Azertooth** [comment] 2020-01-08 14:47
> PLEASE add this?
> 
> Have a look at Em-Client (as noted above by Iski). It manages to import EVERYTHING + keep local copies. M$ only, unfortunately, but it is miles above their awful Outlook in every way. If Mailspring could do what Em-C does, it would immediately become the hottest client for sure!

i'm exactly in that position: using emclient on windows and altough i want to switch so badly to mailspring, this is a core feature for me so until they implement it i can't get along

**Comment by franapoli** [comment] 2020-10-05 11:30
Here's my use case.
I have tons of emails from an account that is not active anymore (I changed job). I thought I could export them from Mailspring and store them away. Instead, I'm stuck with a disabled account that I can not delete and a corresponding error message that I can not fix. Any help would be highly appreciated.

**Comment by CodeMouse92** [comment] 2021-01-28 01:59
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/export-copy-backup-emails/325

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@sebastian-code, @Hope2Code, @Azertooth, @franapoli: if you join and reply to the issue, the moderators can make an effort to reassign your migrated post to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 01:59 UTC
Labels: audit
