### ISSUE TITLE
Bug: Hebrew writing

### ISSUE THREAD

**Issue by XDavidT** [Foundry376/Mailspring#2171] opened 2020-10-20 08:59 UTC
I'm using Mailspring using snap store, and getting all the updates.
But it has a lot of problems when writing Hebrew, since we use RTL, in other apps, when we change to English in Heb sentence, it's change the specific word's/sentence to LTR, and the Heb is keep RTL.
Here is example of my problem: https://i.imgur.com/34GDQex.jpg
It's also happen in my signature, when I'm trying to have separate one to use Heb, it's also use LTR..

**Comment by CodeMouse92** [comment] 2021-02-19 01:12
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/arrow-keys-move-to-the-opposite-direction-when-composing-rtl/704

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-19 01:12 UTC
Labels: audit, bug
