### ISSUE TITLE
Feature Request: More control of threads

### ISSUE THREAD

**Issue by Jonassenher** [Foundry376/Mailspring#2193] opened 2020-11-05 10:44 UTC
**Is your feature request related to a problem? Please describe.**
I found than many of my email threads are split into multiple threads in Mailspring. This happens when it doesn't recognize them as one thread. As when I send an email "\<subject\>", and someone replies in Norwegian, so the answer's subject is "SV:\<subject\>" (instead of "Re:\<subject\>" as it would have been in English). Or, when they are assigning a case-number or something so that the subject of the reply is "\<casenumber\>:\<subject\>".

**Describe the solution you'd like**
I would like an option to choose all emails to be grouped to one thread if their subject is the same after the last colon. In general, I would have liked many more options to choose how Mailspring decides how it groups emails together in threads. I never like to trust the technology blindly.

**Describe alternatives you've considered**
For now, I can't find any solution to this other than looking for another email client.

**Additional context**
Under you can see an example where multiple email threads are split into multiple threads. "Pause?" is split into two, "Teknisk problem (...)" is also split into three, etc.

![Screenshot_20201105_114021](https://user-images.githubusercontent.com/28196005/98230806-e0447580-1f5b-11eb-9a0d-79822e83da23.png)

**Comment by CodeMouse92** [comment] 2021-02-17 02:04
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/more-control-of-threads/657

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@Jonassenher: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-17 02:04 UTC
Labels: audit, enhancement
