### ISSUE TITLE
RTL in bullet points

### ISSUE THREAD

**Issue by desyatnik** [Foundry376/Mailspring#1788] opened 2020-01-29 08:56 UTC
Hi there,
First off, thank you for a great product - it's a joy to use!
Now to the issue at hand. I haven't found an option to create bullet points with RTL content, i.e. when you add bullet points the text remains on the left (please see the screenshot attached.

##### Are there any related issues?

Haven't found any.

...

##### What operating system are you using?
Windows 10
...

##### What version of Mailspring are you using?
(eg: 1.6.3 or 1.7.0 - this is shown in Mailspring's main menu.)
1.7.2
--
![Annotation 2020-01-29 105524](https://user-images.githubusercontent.com/34752947/73341754-f2371080-4285-11ea-8eea-c55859971a27.png)

**Comment by desyatnik** [comment] 2020-01-29 09:02
BTW, this is how they do it in Outlook - a simple toggle that switches the whole message to RTL or backwards. Just a thought.
![Annotation 2020-01-29 105945](https://user-images.githubusercontent.com/34752947/73342205-c1a3a680-4286-11ea-9256-3f14406c4ecd.png)

**Comment by bengotow** [comment] 2020-02-15 19:51
Oh hey this is super interesting, thanks for reporting! I hadn't thought about RTL lists. I think that this /should/ be easy to fix by doing this (https://stackoverflow.com/a/21952230). Will see what we can do!

**Comment by bengotow** [comment] 2020-02-15 19:55
Hey! I tried switching the app into arabic and it seems to be working, but in this language the entire UI (navigation, sidebars, etc.) is flipped RTL. What interface language / composer language are you using?

<img width="912" alt="image" src="https://user-images.githubusercontent.com/1037212/74594337-dd36dd00-4ffa-11ea-9297-bac8a0c51b25.png">

**Comment by desyatnik** [comment] 2020-02-16 15:00
Hey, thanks for the reply!
Yeah, I prefer all my interfaces to be in English, but do require to write emails in Hebrew on regular basis. So that could be the reason why I've stumbled upon this issue.
Any chance you could think of an RTL switch similar to Outlook?
Although I do understand that my use case is probably quite esoteric, so no pressure here.
In the meantime, I found out that copying a pre-made RTL list onto a Mailspring's message pane works just fine as a workaround, i.e. the formatting is kept.

**Comment by CodeMouse92** [comment] 2021-02-12 20:49
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/rtl-in-bullet-points/589

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@desertdisk: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-12 20:49 UTC
Labels: audit
