### ISSUE TITLE
Feature Request: Customize swipe actions

### ISSUE THREAD

**Issue by ZachariahRosenberg** [Foundry376/Mailspring#2185] opened 2020-10-26 22:07 UTC
**Is your feature request related to a problem? Please describe.**

Swipe actions are great for reacting quickly to a large list of emails without having to open each one. It would be nice to be able to customize what the swipe action does, for instance:

- Delete
- Archive
- Mark as read/unread
- Star
- Snooze

**Describe the solution you'd like**

Add a menu in the preferences pane that allows a user to customize swipe right/left actions

**Additional context**
This is how spark handles it:

<img width="619" alt="Screen Shot 2020-10-26 at 6 05 02 PM" src="https://user-images.githubusercontent.com/6923376/97233844-0cbafd80-17b6-11eb-9b28-9f42c22de340.png">

**Comment by CodeMouse92** [comment] 2021-02-03 18:14
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/customizable-swipe-button-actions/444

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-03 18:14 UTC
Labels: audit, enhancement
