### ISSUE TITLE
[Feature Request] Custom sorting of emails

### ISSUE THREAD

**Issue by redlac** [Foundry376/Mailspring#361] opened 2017-11-24 18:08 UTC
I would like to be able to sort the inbox by Subject, From, and Date. This is in the Thunderbird email client.

**Comment by bengotow** [comment] 2017-12-02 06:40
(Related: #88 find by date) We'll probably add these at some point, but it's tricky to do in a threaded conversation view, which is the only option currently. We'd need to build a flat message list first and then make sortable columns. (What does it mean to sort by "From" if the conversation has four people? Does Date show the first message date, or most recent message date? Etc...)

**Comment by studgeek** [comment] 2017-12-04 16:01
Other apps: Airmail has this by lots of fields. Unibox has group by sender.

I think sorting by thread is quite possible and would be better than sorting by individual message.  I believe threads could be sorted a follows:
Date - by date of the most recent email (this is how Gmail does it).
Subject - by  original email subject (which should align pretty closely with the rest of them)
From - by original sender

**Comment by jdavidbakr** [comment] 2018-02-19 14:37
I just want to be able to sort with oldest messages on top instead of newest on top.  Is that possible now?

**Comment by markkuit** [comment] 2018-02-28 23:03
Interested in this as well. Any chance?

**Comment by simonb01** [comment] 2018-03-21 15:16
I am interested in this functionality as well as the ability to add custom groupings, etc, group by date, sender, etc.

**Comment by viraf** [comment] 2018-03-23 18:04
I would prefer group by sender aka like Unibox

**Comment by studgeek** [comment] 2018-03-24 16:28
viraf, That sounds like a separate request (grouping)? Maybe add it and link to it from here?

**Comment by WanderingRaven** [comment] 2018-03-25 13:52
+1 for these options as well.  I know the implementation in the code is a little more complicated to build, but this is pretty standard in most email applications.

**Comment by stmcginnis** [comment] 2018-03-30 17:44
I've often used sorting by size in other clients to be able to figure out which old emails were eating up so much space. I would find that very useful in Mailspring.

**Comment by Disane87** [comment] 2018-04-13 12:29
I use sorting/grouoing within outlook for date. All dates are grouped: today, yesterday, this week and so on:

![image](https://user-images.githubusercontent.com/956158/38734769-0db50d62-3f27-11e8-8959-c2e514ab293b.png)

It would be great, if this would be a feature.

**Comment by TeamKinetic** [comment] 2018-07-27 10:03
Even basic sorting is a must for any email app (date, from, attachments etc).

Other clients (Thunderbird, outlook) that support threaded conversations explode the threads when sorting and then revert to threaded when viewing normally so I guess thats the way to go.

Any idea when this is pencilled in for development..?

**Comment by studgeek** [comment] 2018-08-02 14:50
Don't write out sorting threads. Sorting by thread works fine some thread level aspects like subject and date (last email). It could even sort by last sender.

**Comment by columbian-chris** [comment] 2019-02-12 16:25
This really seriously is a feature that should be implemented. It's nearly unusable for me without it.

**Comment by jonathonbarton** [comment] 2019-03-27 16:17
Mailspring is the first mail client I've used that doesn't have the ability to sort emails. For cryin' out loud, even [PINE ](https://en.wikipedia.org/wiki/Pine_(email_client)) (now 26 years old) has the **-sort _order_** command which includes arrival, date, subject, orderedsubj, thread, from, size, score, to, cc, and reverse.

**Comment by jlomoglio** [comment] 2019-04-30 20:41
The fact that newest message threads appear at the bottom of the message view is HORRIBLE - VERY BAD UX. So when I have 72 threads, I am forced to scroll to the bottom simple shows that your development team is clueless and that makes Mailspring one of the WORST mail clients on the planet!!!

Its time to put a stop to BAD SOFTWARE!!!

**Comment by TheSHEEEP** [comment] 2019-08-02 11:27
I'm also pretty baffled that I can't just sort my emails... I prefer newer emails at the bottom instead of the top.

**Comment by nurikabe** [comment] 2020-11-08 16:13
Was about to pay for a subscription but definitely need sorting.  Going to try Evolution.

**Comment by CodeMouse92** [comment] 2021-02-04 23:19
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/custom-email-sorting/470

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-04 23:19 UTC
Labels: audit, enhancement
