### ISSUE TITLE
Mailspring shows wrong Subject

### ISSUE THREAD

**Issue by falko-strenzke** [Foundry376/Mailspring#2108] opened 2020-07-30 15:12 UTC
$ mailspring --version
1.7.8-13635bcf

$ uname -a
Linux fsx1tablet 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux

The following Email (mail addresses removed) is shown with Subject "test-from-" in Mailspring

MIME-Version: 1.0
Date: Thu, 30 Jul 2020 17:01:22 +0200
Message-ID: <CA+y-Ona1uvNvjtxe7QjneBrwNwkp=6dfZ-i5KE0DjbsXxjR2vg@mail.gmail.com>
Subject: test-from-webclient
From: XXX
To: XXX
Content-Type: multipart/alternative; boundary="0000000000001dfd4b05aba9f29c"

--0000000000001dfd4b05aba9f29c
Content-Type: text/plain; charset="UTF-8"

--0000000000001dfd4b05aba9f29c
Content-Type: text/html; charset="UTF-8"

<div dir="ltr"><br></div>

--0000000000001dfd4b05aba9f29c--

**Comment by falko-strenzke** [comment] 2020-07-30 15:15
+1

**Comment by falko-strenzke** [comment] 2020-07-30 15:52
And
`Subject: abc-def-ghi`
is shown as empty subject

**Comment by bengotow** [comment] 2020-08-16 23:40
Hey thanks for reporting this! Could you attach screenshot of where you're seeing the subject line? I'm guessing this is actually a text truncation issue in the front-end rather than a sync problem. (It seems like Mailspring might be wrapping the text at the `-` characters?) Could you also verify that it happens with the stock theme if you're using one of the custom ones? Cheers!

**Comment by jfredrickson** [comment] 2020-10-09 16:19
I'm seeing this, too, but only in emails from me to myself. There may be some kind of race condition because it will often, but not always, occur. I only have Gmail so I have not tested this with other email providers.

Steps:

1. Use a different client (e.g., Gmail mobile app or Gmail website) to begin composing an email to yourself.
2. In the subject line, type: 12345678
3. Backspace over half of the numbers until the subject line reads: 1234
4. Type the last four numbers again until the subject line reads: 12345678
5. Send

At this point, Mailspring will receive the new email from you to yourself, but the subject line in the Mailspring UI (both in the inbox and the message view) will likely (but not always) say 1234 instead of 12345678. Displaying the original message shows the correct subject, 12345678.

**Comment by jfredrickson** [comment] 2020-10-09 16:35
The more I look at it, the more it seems like some kind of syncing issue due to Mailspring somehow getting confused about me sending email to myself with Gmail constantly syncing my draft updates to the server.

I followed my reproduction steps above using the Gmail web interface. This time, I didn't get "1234" but simply "No subject". This is what my Mailspring inbox looked like after I sent the email:

![screenshot-20201009-102637](https://user-images.githubusercontent.com/171487/95608757-d726be00-0a1a-11eb-8cbe-6cf004b7fd0d.png)

Interestingly, there are a bunch of draft emails in the thread.

![screenshot-20201009-102653](https://user-images.githubusercontent.com/171487/95608762-d9891800-0a1a-11eb-8755-e46cf59a23e3.png)

**Comment by Reiszecke** [comment] 2021-02-02 10:35
I am seeing the same behavior with an email very similar in content that I have sent to two different people. One person replied but it shows the subject line of the other conversation.

It MAY have to do with the pattern matching done to group emails into conversations. I have posted a bug report but haven't gotten a reply. I have specifically said that I'm sure I could fix this by myself but again, I need someone to tell me where that matching logic sits as it appears to be undocumented.

https://community.getmailspring.com/t/unified-inbox-doesnt-group-conversations-with-the-same-sender-across-mailboxes/380

![image](https://user-images.githubusercontent.com/11237541/106587776-5308c100-654a-11eb-9cbc-5aaefc1800e4.png)

**Comment by CodeMouse92** [comment] 2021-02-15 23:11
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mailspring-shows-wrong-subject/640

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@falko-strenzke @jfredrickson: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-15 23:11 UTC
Labels: audit, bug, needs-reproduction
