### ISSUE TITLE
[Feature Request] Ability to change name of the attachment file

### ISSUE THREAD

**Issue by GP-S** [Foundry376/Mailspring#342] opened 2017-11-15 13:39 UTC
It could be cool to let the user change the name of the attached file while redacting message.

##### Are there any related issues?
AFAIK no

##### What operating system are you using?

ArchLinux
##### What version of Mailspring are you using?
1.0.8

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?

Thunderbird,

**Comment by bengotow** [comment] 2017-11-25 20:50
Wow you can do this in Thunderbird? Man that thing has so many features. I think this would be a cool one for someone to tackle - maybe we could make it so that hovering over the attachment's name showed a little edit pen icon, and clicking that let you change it?

This UI is rendered by `AttachmentItem` in this file: https://github.com/Foundry376/Mailspring/blob/master/app/src/components/attachment-items.jsx#L97. That'd probably be a good place to start! (Note: that file contains a bunch of react components that haven't been broken into separate files yet because they're only used elsewhere in the file. A few of the smaller ones are "function-style" React Components which can be a bit confusing.)

<img width="393" alt="image" src="https://user-images.githubusercontent.com/1037212/33234604-5cd0b5b4-d22a-11e7-8cf5-4c51aa5f64fa.png">

**Comment by GP-S** [comment] 2017-11-27 01:44
> Wow you can do this in Thunderbird?

Yep. But you have to right click on the attachment to see the feature option. It may explain why there is not much people aware of this one (which is tremendously useful when you get used to it). 

For what it worth I like the idea of the pen appearing when hovering the name :)

**Comment by AlexandreRozier** [comment] 2019-10-31 10:20
Hi! Thanks for this amazing software :smile:  Do you have any plans concerning this feature? It's definitely useful.

**Comment by NateGrobe** [comment] 2020-07-14 18:09
Hi! I'm new to open source and was thinking of working on this issue. Is that ok?

**Comment by CodeMouse92** [comment] 2021-02-20 03:43
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/ability-to-change-name-of-the-attachment-file/717

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@GP-S: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-20 03:43 UTC
Labels: audit, enhancement, good first issue
