### ISSUE TITLE
Feature Request: "Reply To" as a filter/rule option

### ISSUE THREAD

**Issue by amandabee** [Foundry376/Mailspring#2195] opened 2020-11-05 20:28 UTC
**Is your feature request related to a problem? Please describe.**
I like to filter my newsletters into a "news" folder. One of the clearest indicators that a message is a newsletter is a "reply-to" address `@inbound.mailchimpapp.net` and using `"Recipient" / "Matches expression" / "*@inbound.mailchimpapp.net"` doesn't catch those. 

**Describe the solution you'd like**

I would like an option in the mail rules pull down to create a rule based on the "reply to " address.

**Comment by CodeMouse92** [comment] 2021-03-03 03:43
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/reply-to-as-a-filter-rule-option/967

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-03 03:43 UTC
Labels: audit, enhancement
