### ISSUE TITLE
Bug: appmenu-gtk-module

### ISSUE THREAD

**Issue by Dedsecproject** [Foundry376/Mailspring#2191] opened 2020-11-03 18:34 UTC
MailSpring is failing to run. when I check the CLI this is what it returns as the error.

Failed to load module "appmenu-gtk-module".

when ran as SUDO the error is different:
"mkdir: cannot create directory '/run/user/0': Permission denied"

**To Reproduce**
Can't reproduce steps since started failing ever since I've updated to Pop_Os version 20.10. currently running kernel 5.8.0-7625

**Expected behavior**
I wanted the software to run and open up my email accounts.

**Screenshots**
![image](https://user-images.githubusercontent.com/24379933/98026429-1d342f00-1dd9-11eb-8db2-73d361a32452.png)

**Setup**
 - OS: [Linux - Pop_Os]
 - OS Version [20.10]
 - Mailspring Version: 1.7.8

**Additional context** 
MailSpring is installed in my system through snapd NOT flathub

**Comment by Dedsecproject** [comment] 2020-11-03 18:36
:+1:

**Comment by nprestel** [comment] 2020-11-06 15:31
+1 experiencing the same issue after updating Pop_OS

**Comment by torbenal** [comment] 2020-11-10 10:29
> +1 experiencing the same issue after updating Pop_OS

Same here

**Comment by CodeMouse92** [comment] 2021-03-03 03:39
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/appmenu-gtk-module/965

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@Dedsecproject @nprestel @torbenal: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-03 03:39 UTC
Labels: audit, bug
