### ISSUE TITLE
Bug: mailspring + virtualdesktopa areas in windows 10 will sooner or later place mailspring on coordinates outside of any area.

### ISSUE THREAD

**Issue by tosvfl** [Foundry376/Mailspring#2183] opened 2020-10-26 12:54 UTC
Running mailspring in windows 10 using multiple desktop areas (just like Mac and Linux have had forever and appeared in windows at version 10) does not work well with mailspring. What happens is mailspring looses its position in the virtual desktop space. You can zoom out so that you can see all desktops and windows on them and see mailspring in one of the desktops, but when zooming out to normal size again mailspring goes away and does not appear on any virtual desktop area. The only way to solve this is the reboot the windows machine. After that it works for a short while until it happens again and you have to reboot again. This is really annoying. Otherwise i really like mailspring and would really like to use it, but I cannot simply keep restarting my windows machine over and over, and I cannot **not** use multiple desktop areas, it becomes too messy. 

I'm not sure what Mailspring is written in, but being a developer myself, but working with Java I made a personal java desktop app and decided to store and remember window coordinares and restore those on start. That gave the same behavior as mailspring i showning! Coordinates seem to keep changeing and what was at one time on a screen is after a while off any screen area. I removed the window coordinate saving that that seemed to fix the problem for my gui app.  

Reproduce by using multiple desktop areas in windows 10 and run mailspring in one of them. Then switch desktop areas back and forth and choose other appps and then back to mailspring again back and forth. Sooner or later mailspring swill be invisible on all desktop areas but can be seen when zooming out to the complete desktop areas view.

**Comment by CodeMouse92** [comment] 2021-03-03 03:35
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mailspring-virtualdesktopa-areas-in-windows-10-will-sooner-or-later-place-mailspring-on-coordinates-outside-of-any-area/964

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@tosvfl: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-03 03:35 UTC
Labels: bug, migrated
