### ISSUE TITLE
Contact avatar not showing

### ISSUE THREAD

**Issue by cabaracus** [Foundry376/Mailspring#1036] opened 2018-08-20 17:58 UTC
##### Are there any related issues?

N/A

##### What operating system are you using?

mac OS 10.13.6

##### What version of Mailspring are you using?

1.4.2

--

**Bug?**

##### Is this an email sync or connection issue?

No

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

<img width="194" alt="screen shot 2018-08-20 at 1 47 21 pm" src="https://user-images.githubusercontent.com/42551226/44357738-d7515180-a480-11e8-8137-c9f0f2e6982a.png">

##### Does this feature exist in another mail client or tool you use?

Yes. Airmail and Polymail have no issues with showing contact avatars. 
...

**Comment by CodeMouse92** [comment] 2021-02-25 01:32
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/contact-avatars/782

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-25 01:32 UTC
Labels: audit, enhancement
