### ISSUE TITLE
Issues with Mailspring snap on Kubuntu 18.04

### ISSUE THREAD

**Issue by etrigan63** [Foundry376/Mailspring#942] opened 2018-06-19 06:47 UTC
##### Are there any related issues?

...

##### What operating system are you using?
...
Kubuntu 18.04
##### What version of Mailspring are you using?
...
1.2.2 from snap
--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
...
no plugins
##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
...
This is a snap install issue
##### Is the issue reproducible with a particular attachment, message, signature, etc?

...
After I install Mailspring from the snap store, Clicking on the icon does nothing. Running it from the command line via `snap run mailspring` reveals that the `gnome-keyring` has not been installed (why would it on KDE?) and that the `.config` folder is missing from `/home/user/snap/mainspring/common`. Both are easily fixed from the command line, but shouldn't the snap do that in the first place? Also couldn't the app detect whether `gnome-keyring` or `kde-wallet` is installed and use the appropriate one?
-- 

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by Al2Me6** [comment] 2018-06-19 18:04
I've found the solution to the problem. It wants the GNOME keyring manager Seahorse to be installed, so just do `sudo apt-get install seahorse` and it will work.

**Comment by etrigan63** [comment] 2018-06-19 18:16
Someone suggested installing `seahorse`. What is the difference between `seahorse` and just installing `gnome-keyring`?

**Comment by bengotow** [comment] 2018-07-08 07:03
Hey! Ahh man that's really interesting... It looks like there's not a mainline snapd release for Kubuntu, I wonder if Snapcraft itself is just buggy on Kubuntu? 😕 I think something like gnome-keyring or kde-wallet should have been installed as a core dependency of snapd itself. Maybe when you install it on Kubuntu, it doesn't automatically bring those dependencies with it?

It might be a good idea to post this on the Snapcraft forum (http://forum.snapcraft.io/) those folks are actually super knowledgeable. It might be something wrong with the Mailspring snap, but this feels like it should work.

**Comment by Inmer** [comment] 2018-07-13 00:05
I am having the very same issue, using Kubuntu 18.04 as well

**Comment by endrift** [comment] 2018-07-26 17:14
Same issue with 1.3.0. Installing `gnome-keyring` didn't fix it though.

**Comment by Inmer** [comment] 2018-07-26 17:16
did you restart the pc?

**Comment by endrift** [comment] 2018-07-26 17:20
Yes. For reference: deb version works fine.

**Comment by Inmer** [comment] 2018-07-26 17:22
I tried the deb package before Installing gnome-keyring, and same issue. Happy to hear that it finally worked for you @endrift

**Comment by Lin-Buo-Ren** [comment] 2019-01-05 09:57
Not reproduced on ezgo 14(a fork based on Kubuntu 18.04), can anyone still reproduce this problem in Kubuntu?

For `gnome-keyring` try to connect the snap to the `password-manager-service` interface via `snap connect mailspring:password-manager-service`

**Comment by academay** [comment] 2020-10-15 15:55
@Lin-Buo-Ren  I'm not using snap, just the plain deb package + KDE  

I have KDE plasma 18, kubuntu 20. 



This issue is more than 2 years old, and I've never seen Mailspring working.

**Comment by CodeMouse92** [comment] 2021-02-03 22:29
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/libsecret-not-installed-snapcraft/333

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-03 22:29 UTC
Labels: audit, snapcraft
