### ISSUE TITLE
Your Mailspring ID is missing required fields - you may need to reset Mailspring.

### ISSUE THREAD

**Issue by andrewbetron** [Foundry376/Mailspring#2133] opened 2020-09-02 02:54 UTC
##### What is the behavior you're seeing?
Frequently when mailspring starts after logging in/starting my PC. And i need to reset mailspring. Adding my accounts back everytime.
##### What email provider (Gmail, Exchange, etc.) are you trying to use?
Gmail and IMAP
##### What operating system are you using?
Windows 10 Version 2004
Build 19041.450
##### What version of Mailspring are you using?
1.7.8-13635bcf
##### Is the issue reproducible with a particular attachment, message, signature, etc?
No

**Comment by CodeMouse92** [comment] 2021-02-12 22:14
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/frequent-your-mailspring-id-is-missing-required-fields/596

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@andrewbetron: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-12 22:14 UTC
Labels: audit, mailserver-incompatibility, needs-reproduction
