### ISSUE TITLE
Bug: Wrong recipient when replying emails send to an alias

### ISSUE THREAD

**Issue by keithyipkw** [Foundry376/Mailspring#2124] opened 2020-08-20 12:41 UTC
**Describe the bug**

I have set up my main G Suite email a@main.com with an alias domain a@alias.com in MailSpring. Clicking the reply button for an email sent to a@alias.com opens a new composer. The recipient is a@alias.com instead of the original sender.

**To Reproduce**
1. Add a@main.com
1. Add a@alias.com as an alias in MailSpring
1. User b@sender.com to send an email to a@alias.com
1. Click the reply button

**Expected behavior**
The recipient is b@sender.com

**Actual behavior**
The recipient is a@alias.com

**Setup: (please complete the following information):**
 - OS: Windows
 - OS Version 10
 - Mailspring Version: ex: 1.7.8

**Additional context** 
The recipient in the original email is a@main.com which is wrong. After expanding the detail, it becomes a@alias.com. It should be #874.

The sender in the replying email is a@alias.com which is correct.

**Comment by CodeMouse92** [comment] 2021-02-08 21:36
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/wrong-recipient-when-replying-emails-send-to-an-alias/508

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@keithyipkw: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-08 21:36 UTC
Labels: audit, bug
