### ISSUE TITLE
Feature Request: Calendar Support

### ISSUE THREAD

**Issue by ZakharyH** [Foundry376/Mailspring#199] opened 2017-10-18 14:28 UTC
Integrate calendar support, as well as syncing with web calendars such as google calendar

**Comment by Shickmo** [comment] 2017-10-18 18:33
If there could be support for Office 365 Business account calendars as well this would be a serious advantage over the conversation.

**Comment by applesea2** [comment] 2017-10-22 06:54
Please add this. Its a must to be have calendar integration built into a mail client or it defeats the purpose of having one

**Comment by t3mujin** [comment] 2017-10-24 13:32
I'm backing this one also, it's a deal breaker for me. I'm not saying a full calendar support, it would be nice though ;) , but better handling on incoming event requests would be great!

**Comment by Thrakius** [comment] 2017-11-25 20:45
It would be the all in one solution if we would be able to sync calendars.  Love the client so far though.

**Comment by theurso** [comment] 2017-12-05 13:24
Agreed - w/out calendar support this is hard to switch to for business use.

**Comment by bensullivan2002** [comment] 2017-12-06 10:56
Absolutely love this mail client but, as above, it **needs** to have calendar integration for business use.

**Comment by mannp** [comment] 2017-12-07 09:53
CalDAV support would be great to allow syncing with my nextcloud instance.

**Comment by MirkoLedda** [comment] 2017-12-13 18:45
I second a calendar integration as well.

**Comment by h4d3z** [comment] 2017-12-20 10:19
Would also love (and really need) a calender integration.
If it could sync with google that would be excellent.

**Comment by kdupreez** [comment] 2018-01-04 15:25
+1 more for google calendar sync.

**Comment by mchilson** [comment] 2018-01-04 21:47
Ditto here! Love the client. Just needs calendar integration.

**Comment by applesea2** [comment] 2018-01-06 17:51
I'd recommend pulling Google/Outlook/etc calendars based on the account from the web and integrating events with the emails

**Comment by sathisz** [comment] 2018-01-08 05:14
+1

**Comment by alechko** [comment] 2018-01-16 05:57
love mailspring, best email client I've used under linux, must have calendar support to be proper replacement to others.

**Comment by khaks01** [comment] 2018-01-16 10:58
Mailspring is outstanding experience on Ubuntu, good UI and functional. Missing my calendars badly here. Add gmail/ outlook calendar sync/ integration.

**Comment by scothost** [comment] 2018-01-22 14:41
Mail client looks great and connects to my Microsoft account. Unfortunately it does not have Office365 support only office outlook support so I installed it based on misrepresented claims of its ability. As with most Office365 users no calendar support is a showstopper. ... Shame - had to go to all the trouble of signing up for a mailspring account only to find no calendar - uninstalled after 5 mins - perhaps ill try again in a year or 2

**Comment by SAShapeShifter** [comment] 2018-01-25 03:11
Hi, Its a far nicer client than Thunderbird for my Linux computer, but CalDAV support would be required as I use it for business use, I cant open up two programs to handle invites or send invites. 
But when done wil be amazing

**Comment by Pierrotws** [comment] 2018-02-07 10:01
+1, this is really needed for day-to-day use. I'm rollbacking to thunderbird until invitations are supported

**Comment by ricardovsilva** [comment] 2018-02-08 16:08
Is there someone looking at this? If answer is negative, can someone point me a point to start? I can start coding that feature, I will be glad if someone with UX expertise draw some sketchs.

**Comment by tvieiragoncalves** [comment] 2018-02-09 16:37
+1

**Comment by FDiskas** [comment] 2018-02-12 15:32
And add support to VCALENDAR (Microsoft Exchange Server 2010) attachments in mails for events.
example file looks like
```
BEGIN:VCALENDAR
METHOD:CANCEL
PRODID:Microsoft Exchange Server 2010
VERSION:2.0
BEGIN:VTIMEZONE
TZID:W. Europe Standard Time
BEGIN:STANDARD
DTSTART:16010101T030000
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=10
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010101T020000
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
...
SUMMARY;LANGUAGE=de-DE:Abgesagt: Daily Standup Team
DTSTART;TZID=W. Europe Standard Time:20180117T104500
DTEND;TZID=W. Europe Standard Time:20180117T110000
UID:***
RECURRENCE-ID;TZID=W. Europe Standard Time:20180117T104500
CLASS:PUBLIC
PRIORITY:1
DTSTAMP:20180117T083122Z
TRANSP:OPAQUE
STATUS:CANCELLED
SEQUENCE:19
LOCATION;LANGUAGE=de-DE:Raum Team
X-MICROSOFT-CDO-APPT-SEQUENCE:19
X-MICROSOFT-CDO-OWNERAPPTID:1405982689
X-MICROSOFT-CDO-BUSYSTATUS:FREE
X-MICROSOFT-CDO-INTENDEDSTATUS:FREE
X-MICROSOFT-CDO-ALLDAYEVENT:FALSE
X-MICROSOFT-CDO-IMPORTANCE:2
X-MICROSOFT-CDO-INSTTYPE:3
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT
END:VCALENDAR
```

**Comment by rsramesh** [comment] 2018-02-14 21:43
+1 for calendar support, atleast syncing with google calendar.

**Comment by dwuttke90** [comment] 2018-02-14 21:44
+1 and outlook.com ;)

**Comment by ricardovsilva** [comment] 2018-02-15 13:37
@everyone Please, don't spam this thread with "+1" messages. Github added capability to add reaction to prevent that.

**Comment by ZakharH** [comment] 2018-02-15 14:02
@ricardosilva +1 ;)

**Comment by AndreasJacobsen** [comment] 2018-02-16 16:50
Calendar would be super, you could make office 365 calendar only for pro users, a great way to make money. I can't really switch out Thunderbird for Mailspring now due to lack of calendar support. But will as soon as you provide calendar support :)

**Comment by theurso** [comment] 2018-03-01 13:58
Any update on calendar support being added?

**Comment by fried-eggz** [comment] 2018-03-05 09:22
Apparently Calendar support is [listed in the roadmap as a Long Term Focus](https://github.com/Foundry376/Mailspring/blob/master/ROADMAP.md#long-term).

The roadmap is apparently "based on popular GitHub issues". Personally I would love to see Calendar support as a Near Term focus.

**Comment by chefboyct** [comment] 2018-03-22 14:20
I was looking at changing from Thunderbird to Mailspring. Thunderbird in Linux can be a bit unstable and resource hungry! But without calendar support? How can one actually use it on the daily basis for business purpose? I mean, I struggle to migrate from Office 365 and was juggling in between Evolution and Thunderbird and now I was hoping to move to Mailspring. If it has no calendar support, then it is simply not going to work

**Comment by rolandbreedveld** [comment] 2018-04-06 08:15
I like mailspring for mail, but without calendar functionality its not usable for me.
so please add it.

**Comment by tarican** [comment] 2018-04-06 11:41
+1

**Comment by feliarana** [comment] 2018-04-09 22:30
+1

**Comment by kassanunda** [comment] 2018-04-12 23:39
+1

**Comment by FDiskas** [comment] 2018-04-17 09:00
Hey, please stop adding +1 comments. Just hit subscribe button or if you want to be in the list of all others - hit the like button on first comment. Thanks :rewind:

**Comment by scazzy** [comment] 2018-04-30 13:07
I can see calendar in their code. guess it's coming :)

**Comment by MateuszKubuszok** [comment] 2018-05-02 11:16
I am not so sure - Nylas Mail also had "working calendar" in the code, but if I understand correctly it was just for handling calendar invites. Actual calendar never appeared (except for a plugin that never worked for me). I guess, that they have to implement quite a lot of corner-case'y logic in order to just display it right, not to mention managing events. There is a reason by Sunrise Calendar was, such a hit and why there are no good replacement to this date.

**Comment by fbroqued** [comment] 2018-05-07 14:32
+1

**Comment by nymusicman** [comment] 2018-05-10 18:38
Same. Absolutely need calendar support.

**Comment by FDiskas** [comment] 2018-05-14 16:51
and sync with google calendar and so on :) :tada:

**Comment by canavaroski90** [comment] 2018-05-24 12:50
What is the challenge? What makes G-Calender sync is that hard?

**Comment by Samsonait** [comment] 2018-05-29 17:09
+1 for this great mailing app..

But.. Calendar, and exchange integration? Would be a big + for me.

Where is the donation link? so we can back this great app. And motivate the team behind this app for makign a calendar plugin (outlook and gmail) and exchange support.

**Comment by jcrben** [comment] 2018-06-17 15:36
> Where is the donation link? so we can back this great app

To support future development and get cool features, you could get a pro subscription https://getmailspring.com/pro

**Comment by Holer90** [comment] 2018-07-09 22:55
+1

**Comment by Pierrotws** [comment] 2018-07-10 11:50
This is the most commented (so probably the most wanted) feature request for this project.

Lot of us are showing that we are ready to pay pro sub for this features (myself included)
Some have also proposed their help if Mailspring Team intend to put this feature in the opensource codebase.

But, 9 months after, still no information given by Mailspring... 

For those who still need to read vcalendar attachment, there is a little script found on github that may help :
https://github.com/hangyan/Code/blob/master/perl/vcal.pl

**Comment by jotaf98** [comment] 2018-07-17 12:02
I think that the point is that most of us get event invites by e-mail.

This doesn't mean that Mailspring has to show and manage a full calendar.

For me, a much simpler and sufficient solution would be to have the option to "send to calendar" (scrape an event from the e-mail and add it to a cloud-based calendar, e.g. Google Calendar).

Me (and probably others) already manage their calendars with outside software/web interfaces, so just sending them there would work well. (Not to trivialize the effort in implementation, just saying that no UI other than a menu option is needed.)

**Comment by MateuszKubuszok** [comment] 2018-07-17 14:33
Could it be implemented as a plugin? This way community could deliver some extra functionalities (even in Thunderbird calendar is a set of plugins).

**Comment by wedza** [comment] 2018-08-16 17:39
As said by a lot of people, a nice Calendar feature will great to compete with other clients. More and more people are leaving proprietary software, and for the moment, the only usable calendar app on windows is Thunderbird.

Even if we talk about proprietary calendar clients, even the default Calendar app on Windows 10 doesn't officially support iCal.

Also, If Mailspring brings iCal support, a nice addition will be the ability to edit tasks by iCal (Thunderbird does it). It's the only way to sync tasks between devices without using GAFAM services. And as far as I know, there's no client (except Thunderbird) that let us do that on Windows or MacOs (but [a ton](https://f-droid.org/en/packages/org.dmfs.tasks/) on [Android](https://f-droid.org/en/packages/org.tasks/)).

**Comment by hhue13** [comment] 2018-09-04 08:07
+1 for the request to implement calendar functionality in Mailspring. Mail client function is really great but without calendar of limited use for business purposes

**Comment by ScoutsOut** [comment] 2018-09-21 17:05
Here's another +1 for Calendar support.

**Comment by AlejoJauregui** [comment] 2018-09-30 22:56
I'm totally agree. It's one of principal functions that have other clients. Please, think in this petition, we're many that wanted.

**Comment by nineyards** [comment] 2018-10-03 08:39
@bengotow @Foundry376 So guys, what do you say? Given the amount of interest this thread has gotten and the voices raised for this feature it might be time to move calendar support from long term to short term on the roadmap. Any thoughts on this?

**Comment by mietzen** [comment] 2018-10-17 08:48
+1

**Comment by Samuel3** [comment] 2018-10-23 18:05
+1

**Comment by FDiskas** [comment] 2018-10-23 18:49
:recycle: looks like this will be never implemented or somehow reacted. Unsubscribing. :ox:

**Comment by Samuel3** [comment] 2018-10-23 18:52
I think you are poorly right. I wanted to try to write a plugin but this nearly impossible.

**Comment by tonyjbutler** [comment] 2018-10-24 16:43
+1

**Comment by Ansem93** [comment] 2018-11-08 09:51
I really hope that even a basic calendar will be implemented! It's the biggest feature this client is missing

**Comment by sudhirdhumal289** [comment] 2018-11-14 16:17
I usually get the mail from GoToMeeting as we use it as a daily driver, but looks like I can not add / view the meeting details in Mailspring.

Really expect this.

I'm falling back to thunderbird - it requires timezone setting change to view the proper meeting invite time but I guess I have to keep using it.

**Comment by prouth** [comment] 2018-11-18 17:20
+1

**Comment by ipolevoy** [comment] 2018-12-07 18:16
It is crucial for me to use it as well. If implemented I will switch to a paid version immediately and can even pay a bonus - let me know.

**Comment by nineyards** [comment] 2019-01-06 14:03
@bengotow @Foundry376 Please respond in some way. It doesnt cost much to at least comment on this matter...

**Comment by wedza** [comment] 2019-01-06 19:57
> 
> 
> @bengotow @Foundry376 Please respond in some way. It doesnt cost much to at least comment on this matter...

Calendar is planned for Summer 2019 in [the roadmap](https://github.com/Foundry376/Mailspring/blob/master/ROADMAP.md) :)

**Comment by bengotow** [comment] 2019-01-06 22:00
Hey folks! Sorry I've been silent on this one—I could have sworn I'd commented already but it must have been somewhere else.

There was actually a prototype of a calendar in Mailspring back in 2015 when it was Nylas Mail. It turned out to be a huge undertaking and the team decided to cut it to focus on polishing the core email experience. The idea was that it was better to have a great email app than a sorta-buggy email+calendar app.

I've stood by that for the last few years, and in 2018 all of the new features and bug fixes were aimed at improving the email experience. I think the app is in a great spot as a mail client now. On the email front, I'm hoping to add support for IMAP virtual folders and email signing, and also continue performance improvements to the composer, but I think things are stable enough that we can revisit the calendar feature.

I'll probably start development of a CalDAV sync worker this spring. I think we can ship a beta of a calendar shortly thereafter since some of the core calendar UI actually exists already. (Though React has changed a bit since 2015... hopefully it's alright). Calendar is one of those infinite-effort projects, and I think we'll have to carefully scope what Mailspring supports out of the gate. (Shared calendars, room reservations, travel time notifications, etc. add a lot of complexity). To focus efforts, I'll almost definitely start with a whitelist of supported CalDAV servers (Gmail + O365 at first) and expand the list as we verify those super-popular implementations work well.

Hope that helps! The ability to RSVP to iCal events from within email messages will definitely be one of the first features we tackle, hopefully that helps address the biggest pain point soon.

**Comment by AlejoJauregui** [comment] 2019-01-06 22:06
Sounds grate if you can give us a Beta version of this calendar. I'm expecting this since I install Mailspring on my machine. So please @bengotow add to the roadmap, will be awesome have this feature.

**Comment by 13pixlar** [comment] 2019-01-06 23:07
@bengotow That is absolutely awesome news! I think you are right to focus on core calendar functionality first and incrementaly add new features. Great news!

**Comment by Modelmat** [comment] 2019-01-06 23:15
Since we're getting CalDAV, on the related side, can we plan to add contacts too? As much as there are other alternatives, this would definitely be good to have too.

**Comment by joshbmartin** [comment] 2019-01-23 18:34
Super pumped about this. I was worried with all the comments I'd be visiting a dead thread. 17 days ago! WOOHOO. You'll have peoples wallets open as well as their legs when you start pushing out beta for this!

**Comment by frigaut** [comment] 2019-02-07 11:04
Just keeping this thread alive. Yes, this would be awesome. Not saying "this is a deal breaker for me", but it's definitely annoying not to have at least partial support.

**Comment by h4d3z** [comment] 2019-02-07 12:16
really would love to see this happen soon

**Comment by cpacchierotti** [comment] 2019-02-07 12:53
Although very interesting and useful, I agree with @bengotow that it is important to have - first - a good email client. There are still several blocking issues to be addressed before moving on.

**Comment by a-sevin** [comment] 2019-02-27 15:47
It's really an main feature that keeps me from switching to mailspring

**Comment by easit** [comment] 2019-03-21 15:03
Calendar functions for standalone Exchange and/or O365 are a must; without it the tool is quite useless for professional business use :(

**Comment by cotej** [comment] 2019-03-22 16:45
+1
Currently stuck with Evolution (even though I despise it) for its Exchange calendar support... would love to be able to switch to Mailspring.

**Comment by dataacumen** [comment] 2019-03-31 21:51
Calendar support would make this my go to. Without it, the app has little value.

**Comment by porterbayne** [comment] 2019-04-09 15:55
I am switching mail programs without this feature.  I missed a calendar invite, and have been opening G Suite in my browser to accept invites.

**Comment by sandeep-pareek** [comment] 2019-04-10 06:33
Any workaround for using Calendar invites? Cannot even see the invite properly as it shows a VCARD as an unnamed attachment. Considering my Linux environment, this client is much better than Thunderbird. So, I am ready for any workarounds regarding Calendar.

**Comment by k4ch0** [comment] 2019-04-18 22:02
Waiting on the beta!!

**Comment by Ross-Byrne** [comment] 2019-04-24 10:50
+1 for calender support.

**Comment by kevvvvyp** [comment] 2019-04-25 22:30
Looking forward to the beta!

**Comment by tracker1** [comment] 2019-04-26 16:52
Not to pile on the me too conversations... but definitely a must have for me... tried against my work's Office 365 (Exchange) account, and not having the Calendar is a definite deal breaker for me as well.  I know that office/exchange/o365 consists of proprietary protocols, but integration for contacts and calendar support are absolutely critical for what I would consider the majority of office users.

Even my personal email accounts (one on outlook.com, another on gmail) get a lot of use with calendar integration... without it, it's too painful to use.  It looks like caldav support is coming, and that's great.  Will probably give it another look in a few months give or take.  I really want to see some alternatives succeed, given than my home system is currently mac and switching to linux later in the year, I'd rather not be stuck with a web interface if I can avoid it.

**Comment by lonewolf1870** [comment] 2019-04-27 20:18
First, thanks a lot for the app. I'd rate Mailspring the best mail app I tried on the Mac so far, but I really miss a support to invitations (plus LDAP support and quick-look of attachments, I have to say :-) )

As a Mac user, my wish list for this is:
- capability to automatically answer to invitations
- add events to the Mac calendar app (which has iCloud, Google, etc.).
So, maybe you don't need to write a full calendar app, as long as you can use external tools - but I don't know the situations for other platforms.

On the mac, I've noticed 3 ways of dealing with it:
- some apps relies completely on the calendar app, as the standard Mac Mail. Maybe easier implementation, but not ideal
- Thunderbird has its own calendar, to which the user can connect shared calendars (iCloud, Google, etc). Maximum flexibility, but not user friendly (especially for iCloud)
- best app so far in the respect is Spark by Readdle: if you can, give it a try. It has its own well designed calendar, answer to invitation, and a nice & modern design. Then it has many flows in other areas...

**Comment by synsa** [comment] 2019-04-29 22:25
I agree with @lonewolf1870.

Love the app and recommend it to everyone that I can. Would love to make Mailspring the standard instead of thunderbird/outlook at my company, but sadly, the one thing preventing me from moving fully to Mailspring is the lack of calendar/ldap support at this time.

I'd offer to help with the implementation, but I'm not acquainted with React all that well. Vue, yes, React nope :(.

**Comment by scchearn** [comment] 2019-05-09 11:47
+1 for Office365 calendar support. [Hiri](https://www.hiri.com/) mail has a great O365 implementation, although it is too slow for my liking, Mailspring FTW!

**Comment by GuiltyNL** [comment] 2019-05-25 11:00
What is the current status on this one?

**Comment by Giorgiofox** [comment] 2019-05-29 20:35
Agree! Wait for that

**Comment by danielfm123** [comment] 2019-06-14 00:49
yeah calendar pleaaaase :P

**Comment by couling** [comment] 2019-06-18 12:40
Ultimately I **NEED** to be able to click accept on an invite and have it appear in may calendar.

**Comment by SpineEyE** [comment] 2019-06-18 12:42
whine somewhere else or code it yourself or pay someone to do it or use Thunderbird or Microsoft Office. Why do people need to spam this issue? I just want to stay up to date with its implementation. This is not facebook.

**Comment by couling** [comment] 2019-06-18 12:52
@SpineEyE You are not obliged to receive updates on this thread.  I suggest you investigate your github settings more thoroughly to turn this off.  Crying that you are getting spammed by people asking for a vital piece of functionality is just an exercise in futility.

**Comment by SpineEyE** [comment] 2019-06-18 12:58
Instead of trying to appear intelligent by showing off your English language skills, read the [contribution](https://github.com/Foundry376/Mailspring/blob/master/CONTRIBUTING.md#filing-an-issue) guidelines to this repository. Let me quote that for you in case you don't understand:

>  If someone has already requested the feature you have in mind, upvote it using the "Add Reaction" feature - our team often sorts issues to find the most upvoted ones.

Also you might note that this issue has been getting spammed every couple of days since October 2017.

**Comment by Corey-Hunt** [comment] 2019-07-09 15:52
If it's anything like our dev teams (or really any software company I've worked with) the number of adds on an enhancement request ups the priority. So I'm adding my +1 to it and you can just deal with it spiny

**Comment by Corey-Hunt** [comment] 2019-07-09 16:33
> > If someone has already requested the feature you have in mind, upvote it using the "Add Reaction" feature - our team often sorts issues to find the most upvoted ones.
> 

Where is this?

**Comment by danielfm123** [comment] 2019-07-17 11:41
untill calendar is ready, im stuck with evolution

**Comment by Sparsa** [comment] 2019-07-24 12:10
Waiting for the calendar support :D

**Comment by danielfm123** [comment] 2019-07-25 22:46
meanwhile im using evolution, is quite good :)

**Comment by nolddor** [comment] 2019-08-03 17:08
Upvoted!

**Comment by d3vCr0w** [comment] 2019-09-18 20:44
This feature would be really useful, definitely a nice addition to MailSpring

**Comment by rjrodriguezalvarez97** [comment] 2019-11-06 15:36
Hope to see it soon!

**Comment by faithisgood** [comment] 2019-11-13 14:18
I have seen "calendar" coming soon for quite a while, can anyone give an update on the ETA of the calendar?  How much longer if at all?

**Comment by wedza** [comment] 2019-11-13 14:26
Hi @faithisgood ! It seems like the preview of the Calendar is already here under the "Developpement" menu, and already supports Google Calendar. In the issue #1668, @bengotow said that the full calendar will be launched "later this year".

![image](https://user-images.githubusercontent.com/20335741/68772208-b3e86880-0629-11ea-9a9e-f1092e17185c.png)

**Comment by faithisgood** [comment] 2019-11-13 15:01
> 
> 
> Hi @faithisgood ! It seems like the preview of the Calendar is already here under the "Developpement" menu, and already supports Google Calendar. In the issue #1668, @bengotow said that the full calendar will be launched "later this year".
> 
> ![image](https://user-images.githubusercontent.com/20335741/68772208-b3e86880-0629-11ea-9a9e-f1092e17185c.png)

Yes, I have seen that for many months now, my question is when it might be working? and available for use....originally I saw it say that it was due to launch earlier in the year, then it now says later this year and later is like next month so just kinda wanted an eta is all...thanks for response...

**Comment by osphost** [comment] 2020-01-08 02:32
+1

**Comment by thblckjkr** [comment] 2020-01-10 04:54
The **Late this year** now means late 2020?

**Comment by robdam1001** [comment] 2020-01-12 17:03
Love Mailspring BUT I am unable to use it due to no integrated calendar.  Back to Mailbird for me.

**Comment by lukasbradley** [comment] 2020-02-21 11:40
I would subscribe right now if it had calendar support.  It's a must.

**Comment by thaihoangminh** [comment] 2020-02-25 04:22
+1, Would like to see this implemented soon

**Comment by paroque28** [comment] 2020-03-12 22:43
What is the status of this?

**Comment by JamesClonk** [comment] 2020-03-13 14:27
Calendar support is the only thing that currently keeps me from switching to Mailspring, would love to be able to do that though.

**Comment by PrijaveRazne** [comment] 2020-03-18 08:55
I really miss calendar.
I enjoy using Mailspring for email and then use thunderbird to sync my calendar which is on exchange and accessible by using DavMail.

Any info on when the calendar will be available in Mailspring?

**Comment by SargeKhan** [comment] 2020-03-19 10:27
Hey guys, do you need support in the development of the calendar? How can we help pushing this feature faster?

**Comment by mstites** [comment] 2020-04-05 03:29
I would love to see calendar added to mailspring! I already love the client and use the paid version accordingly - the calendar is the thing I miss the most.

What is the progress on this?

**Comment by perfecto25** [comment] 2020-05-19 14:53
looks like its coming soon (v 1.7.6)

![image](https://user-images.githubusercontent.com/10224886/82341683-bce23a00-99be-11ea-9b8f-b846fa12a226.png)

**Comment by faithisgood** [comment] 2020-05-19 17:37
I have actually seen this before like over a year ago, same comment, Calendar is launching later this year!  Is there anything you have seen that confirms with that specific update v 1.7.6 that indicates the calendar would be available?  Just curious, using other software until Mailspring get this added.

**Comment by GeigerJ2** [comment] 2020-06-19 07:31
Any updates on this issue? Love using Mailspring, but it makes one's organization a bit clunky having to rely on different software for the calendar. Maybe it's possible to release a preliminary version in which at least manual adding of events is supported? I suppose this should be fairly straightforward to implement. This feature is dearly awaited.

**Comment by chgradl** [comment] 2020-07-07 17:48
Same here. I love mailspring but can't use it for my business since so much of my emails are related to calendar events.
I doubt I'm the only one who would be happy to sign up for the Pro-version if a calendar was available.

**Comment by DasJott** [comment] 2020-07-22 12:37
Can't believe this request is active for 3 years now. The message still states "...later this year...", which is a little uncool.
Many people even want to help to integrate. What's the big problem?

I would also love to kick Thunderbird for using this modern looking application!

**Comment by 13pixlar** [comment] 2020-07-22 14:35
@bengotow see above. Any news?

**Comment by mbaev** [comment] 2020-08-11 18:53
I'm looking forward to this feature! I'll pay for the subscription when it released!

**Comment by lukasbradley** [comment] 2020-08-14 10:23
Unsubscribing to this thread.  Not going to wait anymore.

**Comment by asm0dey** [comment] 2020-08-14 10:34
@lukasbradley what are you migrating to?

**Comment by tracker1** [comment] 2020-08-20 23:59
@asm0dey  can't speak for above, but I've been using a combination of Outlook on Windows, and an electron wrapper for outlook web on Linux/Mac.  I've also been using a bit of Thunderbird for some secondary emails and Gmail web and/or an electron wrapper for that.

Would love it all in one box, but no one box does a very good job of it.

**Comment by estebanjosealva** [comment] 2020-08-27 13:32
I think most of us understand that this kind of development takes time. But 3 years? Either something is very wrong, or developing the calendar functionality for Mailspring is incredibly difficult. In either case, a little bit more explanation from Mailspring devs would be appreciated. Heck, I'd even pay for the premium plan if this proves to be the solution we were all waiting for.

**Comment by tracker1** [comment] 2020-09-07 20:53
To expand on @estebanjosealva not sure if the app model supports it, but if it were a paid extension, I'd be willing to go that route for this.

**Comment by F1nny** [comment] 2020-10-02 20:59
Has anyone seen any word/update/note on this from the team in the past year+? 

Major bummer as LOVE Mailspring - it's beautiful and exactly what we need with a current-gen email client, especially in the linux community, but the lack of this support has been a major blocker for most. Would bring in a ton of $$ for the project for business users going pro. 

Hell at this point I think if could setup a sponsor a feature sort of thing, a lot of us would pay/donate to get this feature moving again ASAP :disappointed: Maybe doable with github sponsors @Foundry376 ? :crossed_fingers: 

There's also plenty of us in the community who would be willing to help and develop this feature too - the trick is, I'm not sure if the calendar support needs to be handled within the sync engine, which case that's out as an option since closed source :frowning_face: - 
**Anyone know if that's the case or not?**

**Comment by 13pixlar** [comment] 2020-11-16 14:48
> Has anyone seen any word/update/note on this from the team in the past year+?
> 
> Major bummer as LOVE Mailspring - it's beautiful and exactly what we need with a current-gen email client, especially in the linux community, but the lack of this support has been a major blocker for most. Would bring in a ton of $$ for the project for business users going pro.
> 
> Hell at this point I think if could setup a sponsor a feature sort of thing, a lot of us would pay/donate to get this feature moving again ASAP disappointed Maybe doable with github sponsors @Foundry376 ? crossed_fingers
> 
> There's also plenty of us in the community who would be willing to help and develop this feature too - the trick is, I'm not sure if the calendar support needs to be handled within the sync engine, which case that's out as an option since closed source frowning_face -
> **Anyone know if that's the case or not?**

@bengotow @Foundry376 Please respond in some way. Are donations or collaboration a way to move this forward?

**Comment by vaibhavjain3** [comment] 2020-11-17 05:33
Such a waste of time. Request is just getting delayed from 3 years.
Migrating now from Mailspring to Mailbird.

**Comment by rohit901** [comment] 2020-11-19 12:59
Any updates on this? would love this feature.

**Comment by eibrunorodrigues** [comment] 2020-11-19 13:20
@rohit901 unfortunately the project seems abandoned.

**Comment by rohit901** [comment] 2020-11-19 13:22
@eibrunorodrigues you mean mailspring project itself has been abandoned or only the calendar support? I'm on Manjaro and I would want desktop notification of my google calendar events, do you know how can i achieve that?

**Comment by eibrunorodrigues** [comment] 2020-11-19 13:34
@rohit901 The project itself. But taking a good look at the pull request history, I think the owner of this project is only reviewing pull requests. So to achieve the calendar I think we may need to create a pull request. I'm going to take a look later and maybe continue this issue. I too really want the calendar support (not only for Google but for Office 365 as well)

**Comment by ostenning** [comment] 2020-11-19 13:36
What would be great is an answer from the project owner. Any kind of feedback regarding this would be appreciated. I have literally been following this thread for 2 years and seen nothing from it.

**Comment by eibrunorodrigues** [comment] 2020-11-19 13:39
@ostenning Yep! I send him an email. Let's see if he responds. But following other threads, It looks like he's not responding.

**Comment by sgdavis1** [comment] 2020-11-19 14:26
As soon as this is added I am going to switch. Wish I could help in some way but I doubt I could make a meaningful contribution...

**Comment by aigoncharov** [comment] 2020-11-19 14:40
For Ubuntu users, you can add your Google (or other accounts) to your system (see https://wiki.gnome.org/Projects/GnomeOnlineAccounts). Then all your calendars will show up in the built-in local calendar.
As to accepting the invites, I use Google calendar, which sends any invite as rich HTML where you can click on the accept button to add it online.

**Comment by rohit901** [comment] 2020-11-19 14:42
@aigoncharov any work around for manjaro users? i had been doing the same in Ubuntu but switched to manjaro recently.

**Comment by eibrunorodrigues** [comment] 2020-11-19 15:21
@aigoncharov I'm using Office 365 which is not very supported for invites on email clients. Only Evolution has this support, and it is not a very good application.

**Comment by aigoncharov** [comment] 2020-11-19 15:46
@rohit901 @eibrunorodrigues sorry, I am unaware of workarounds for you. I have just shared what works for me.

**Comment by ostenning** [comment] 2020-11-19 15:48
I think using wine and a windows based email client could be a working solution. Defeats the point though

**Comment by valentt** [comment] 2020-12-16 11:10
Check my bug: https://github.com/Foundry376/Mailspring/issues/2231

This is a dead project and dead product unfortunately, and we need to find an alternative. Any suggestions?

**Comment by RedKage** [comment] 2020-12-16 12:18
> This is a dead project and dead product unfortunately, and we need to find an alternative. Any suggestions?

I have been using "eM Client" https://www.emclient.com/?lang=en for a few years now.
It's the total opposite in terms of philosophy, it's closed source, and paid. Quite expensive as well
Managed to get 2 lifetime licenses a few years back during a promotion. Maybe a black friday or something.

But this covers all my needs, with a somewhat functional calendar, multiple emails account support, webdav account, contact account, etc.

I used to use Thunderbird+Lightning, but with a dozen email accounts, each of them existing for at least decade without deleting any emails.... it was so slow that it crashed. Not sure if the inbox format has changed or not in Thunderbird since then, but I had to stop using it because of that. Couldn't handle gigabytes of emails properly.

**Comment by CodeMouse92** [comment] 2021-01-18 21:54
**This task is underway.**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/calendar-support/85

Please consider joining that community and continuing the discussion there!

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed** 2021-02-02 02:52 UTC
Labels: calendar, enhancement, migrated
