### ISSUE TITLE
Can't authenticate Office 365 account

### ISSUE THREAD

**Issue by duoi** [Foundry376/Mailspring#1536] opened 2019-06-21 02:22 UTC
##### Are there any related issues?

...

##### What operating system are you using?

MacOS Mojave, same thing happens on Ubuntu 18.04

##### What version of Mailspring are you using?

Version 1.6.2 (1.6.2) but this has been ongoing for about three months. I'm a paid user if that affects the version.

--

**Bug?**

##### Is this an email sync or connection issue?

Perhaps?

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

Exchange/Office 365

##### Is the issue reproducible with a particular attachment, message, signature, etc?

...

--

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?

No

---

logs:

```
----------IMAP----------
* OK The Microsoft Exchange IMAP4 service is ready. [TQBFADIAUABSADAAMQBDAEEAMAAyADIANwAuAGEAdQBzAHAAcgBkADAAMQAuAHAAcgBvAGQALgBvAHUAdABsAG8AbwBrAC4AYwBvAG0A]
1 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
1 OK CAPABILITY completed.
2 LOGIN "me@work.com" *********
2 NO LOGIN failed.
```

This is using an app password and my normal password.

**Comment by lucian303** [comment] 2019-07-05 23:46
Same here on Ubuntu 18.04.I was able to log in initially and sync/download all my messages. Now it won't authenticate anymore. I've looked into creating an app password as suggested in some of the other issues, but that is not an option since our accounts do not use 2FA. That simply cannot be the solution. If there are other solutions to try, I'm more than willing to but at this point, it seems Office365 / IMAP functionality is in alpha and doesn't work. I'm 100% sure my credentials are correct. 

----------IMAP----------
* OK The Microsoft Exchange IMAP4 service is ready. [TQBXAEgAUABSADEAOABDAEEAMAAwADMANQAuAG4AYQBtAHAAcgBkADEAOAAuAHAAcgBvAGQALgBvAHUAdABsAG8AbwBrAC4AYwBvAG0A]
1 CAPABILITY
* CAPABILITY IMAP4 IMAP4rev1 AUTH=PLAIN AUTH=XOAUTH2 SASL-IR UIDPLUS ID UNSELECT CHILDREN IDLE NAMESPACE LITERAL+
1 OK CAPABILITY completed.
2 LOGIN "email@mywork.com" "*********"
2 NO LOGIN failed.

**Comment by duoi** [comment] 2019-07-11 23:45
@lucian303 I've tried using an app password but still no luck.

**Comment by linuxiaobai** [comment] 2020-03-08 01:52
I have encountered the same issue from last month.

**Comment by CodeMouse92** [comment] 2021-01-28 04:06
Thank you for your patience on this issue! I know it's frustrating when you cannot connect to your email with Mailspring.

2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be a duplicate of one we've already migrated to Discourse:

https://community.getmailspring.com/t/institutional-office365-not-working/48

Please consider joining that community and continuing the discussion there.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 04:06 UTC
Labels: audit
