### ISSUE TITLE
[Bug] Zendesk Auto Reply Email Content Formatting Issue - Paragraph tags with no margin/padding

### ISSUE THREAD

**Issue by ghost** [Foundry376/Mailspring#1633] opened 2019-09-13 01:49 UTC
Hi,

It seems the &nbsp of Zendesk's email auto-reply is removed on the formatting when viewing it with Mailspring.

Please see attachment below for reference.

**On Mailspring**
![image](https://user-images.githubusercontent.com/44415788/64832351-32199600-d60c-11e9-8cb3-677bea4c533f.png)

**On Gmail**
![image](https://user-images.githubusercontent.com/44415788/64832386-5a08f980-d60c-11e9-9083-1888826c3746.png)

**Comment by bengotow** [comment] 2020-02-17 16:15
Hey! It looks like Mailspring's display of these emails was impacted by this change a while back to improve support for outlook messages: https://github.com/Foundry376/Mailspring/commit/1794025eec8abe04f5ec2fa77cfe1451c0d323da which uses paragraph tags more like `<br>` tags. Will see if anything can be done about this.

**Comment by CodeMouse92** [comment] 2021-03-02 18:33
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/zendesk-auto-reply-email-content-formatting-issue-paragraph-tags-with-no-margin-padding/929

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 18:33 UTC
Labels: audit, bug
