### ISSUE TITLE
Feature Request: Smart prediction of destination folder when moving messages

### ISSUE THREAD

**Issue by zeigerpuppy** [Foundry376/Mailspring#2207] opened 2020-11-25 14:49 UTC
When filing messages in folders, it would be useful for Mailspring to suggest the most likely folder(s) based on the message content.
This could work in a similar way to the [Mailhub](http://www.dervishsoftware.com/) plugin for OS X Mail.

**Describe the solution you'd like**
when selecting the "Move to" menu, the first results (3 would be sufficient) would display the predicted folders that best match the message content.  This prediction would be based on two data sets:
1. indexed message statistics
2. previous actions of moving messages

**Additional context**
Mailhub allows using a key combination to bring up a contextual menu of folders for filing a message (or group of selected messages).  The program keeps an index of matches and does a good job of predicting where messages should be filed based on content.  This saves a lot of time for users who file their messages.

**Possible extension:**

To make this feature even better, it could be possible to add a tag in the folder mail list view with the suggested filing location for each mail.  Then the user could just click on the tag if they are happy with the filing location suggested (this would reduce the steps even further in moving messages to their appropriate folders).

**Comment by CodeMouse92** [comment] 2021-03-03 03:45
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/smart-prediction-of-destination-folder-when-moving-messages/968

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@zeigerpuppy: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-03 03:45 UTC
Labels: audit, enhancement
