### ISSUE TITLE
Cannot run via snap on Fedora or Ubuntu

### ISSUE THREAD

**Issue by cyplo** [Foundry376/Mailspring#933] opened 2018-06-14 08:06 UTC
Heya ! 

Thank you for the software it looks cool !
I tried running via snap on Fedora and it seems that Mailspring has troubles starting there.

It hangs and does not start, here's the full commandline log:
```
snap run mailspring
/snap/mailspring/216/bin/desktop-launch: line 177: /home/cyryl/snap/mailspring/common/.config/user-dirs.dirs: No such file or directory
cp: cannot create regular file '/home/cyryl/snap/mailspring/common/.config/': Not a directory
/snap/mailspring/216/bin/desktop-launch: line 180: /home/cyryl/snap/mailspring/common/.config/user-dirs.dirs.md5sum: No such file or directory
/snap/mailspring/216/bin/desktop-launch: line 180: /home/cyryl/snap/mailspring/common/.config/user-dirs.locale.md5sum: No such file or directory
Gtk-Message: Failed to load module "pk-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Running database migrations
App load time: 10633ms

Running Setup
{"error":null}
TypeError: _electron.app.isInApplicationsFolder is not a function
    at moveToApplications (/src/browser/move-to-applications.es6:4:11)
    at Application.oneTimeMoveToApplications (/src/browser/application.es6:174:5)
    at Application.start (/src/browser/application.es6:88:16)
    at <anonymous> Promise {
  <rejected> TypeError: _electron.app.isInApplicationsFolder is not a function
    at moveToApplications (/src/browser/move-to-applications.es6:4:11)
    at Application.oneTimeMoveToApplications (/src/browser/application.es6:174:5)
    at Application.start (/src/browser/application.es6:88:16)
    at <anonymous> }

```

version info:
```
commands:
  - mailspring
snap-id:   0TyNxgP6wEM3nTXzymtc1wOnvl2P6Iij
tracking:  stable
refreshed: 2018-05-24T20:12:17+01:00
installed:   1.2.2 (216) 164MB -
channels:                
```

let me know if you'd need any more info ! thanks again !

**Comment by gvinaccia** [comment] 2018-06-18 17:33
I have the same issue, but on ubuntu xenial

**Comment by rvsandeep** [comment] 2018-06-27 18:42
I have the same issue on ubuntu 18.04

**Comment by synsa** [comment] 2018-06-29 02:36
I get the same error after installing mailspring.

```
$ mailspring
/snap/mailspring/216/bin/desktop-launch: line 177: /home/slang/snap/mailspring/common/.config/user-dirs.dirs: No such file or directory
cp: cannot create regular file '/home/slang/snap/mailspring/common/.config/': Not a directory
/snap/mailspring/216/bin/desktop-launch: line 180: /home/slang/snap/mailspring/common/.config/user-dirs.dirs.md5sum: No such file or directory
/snap/mailspring/216/bin/desktop-launch: line 180: /home/slang/snap/mailspring/common/.config/user-dirs.locale.md5sum: No such file or directory
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "canberra-gtk-module"
Running database migrations
App load time: 1451ms

Running Setup
{"error":null}
TypeError: _electron.app.isInApplicationsFolder is not a function
    at moveToApplications (/src/browser/move-to-applications.es6:4:11)
    at Application.oneTimeMoveToApplications (/src/browser/application.es6:174:5)
    at Application.start (/src/browser/application.es6:88:16)
    at <anonymous> Promise {
  <rejected> TypeError: _electron.app.isInApplicationsFolder is not a function
    at moveToApplications (/src/browser/move-to-applications.es6:4:11)
    at Application.oneTimeMoveToApplications (/src/browser/application.es6:174:5)
    at Application.start (/src/browser/application.es6:88:16)
    at <anonymous> }
```

*Version Info*:

```
$ snap --version
snap    2.33
snapd   2.33
series  16
ubuntu  18.04
kernel  4.15.0-23-generic
```

```
$ snap info mailspring
commands:
  - mailspring
snap-id:      0TyNxgP6wEM3nTXzymtc1wOnvl2P6Iij
tracking:     stable
refresh-date: today at 18:51 PDT
channels:                      
  stable:    1.2.2 (216) 164MB -
  candidate: 1.2.2 (216) 164MB -
  beta:      1.2.2 (216) 164MB -
  edge:      1.2.3 (218) 165MB -
installed:   1.2.2 (216) 164MB -
```

It appears that it has issues creating the .config directory within /snap/mailspring/common/

Generating the .config directory manually removed the error regarding the .config directory. However, it still errored out with the following:
```
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Running database migrations
App load time: 3317ms

Running Setup
{"error":null}
TypeError: _electron.app.isInApplicationsFolder is not a function
    at moveToApplications (/src/browser/move-to-applications.es6:4:11)
    at Application.oneTimeMoveToApplications (/src/browser/application.es6:174:5)
    at Application.start (/src/browser/application.es6:88:16)
    at <anonymous> Promise {
  <rejected> TypeError: _electron.app.isInApplicationsFolder is not a function
    at moveToApplications (/src/browser/move-to-applications.es6:4:11)
    at Application.oneTimeMoveToApplications (/src/browser/application.es6:174:5)
    at Application.start (/src/browser/application.es6:88:16)
    at <anonymous> }
```
After waiting for 30 seconds I ctrl-C'd it and tried again with the following error in output:
```
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Running database migrations
App load time: 207ms

{"error":null}
Failed to generate minidump.Segmentation fault (core dumped)
```

After removing mailspring and then reinstalling; I was able to get it to load for me by running `mailspring` in the terminal. With the following output:
```
/snap/mailspring/216/bin/desktop-launch: line 177: /home/slang/snap/mailspring/common/.config/user-dirs.dirs: No such file or directory
cp: cannot create regular file '/home/slang/snap/mailspring/common/.config/': Not a directory
/snap/mailspring/216/bin/desktop-launch: line 180: /home/slang/snap/mailspring/common/.config/user-dirs.dirs.md5sum: No such file or directory
/snap/mailspring/216/bin/desktop-launch: line 180: /home/slang/snap/mailspring/common/.config/user-dirs.locale.md5sum: No such file or directory
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "canberra-gtk-module"
Running database migrations
App load time: 206ms

{"error":null}
{ Error: DraftEditingSession::ensureCorrectAccount - you can only send drafts from a configured account.
    at DraftEditingSession.ensureCorrectAccount (/src/flux/stores/draft-editing-session.es6:325:13)
    at DraftStore._onSendDraft (/src/flux/stores/draft-store.es6:402:19)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  message: 'DraftEditingSession::ensureCorrectAccount - you can only send drafts from a configured account.' } { pluginIds: [] }
```
After setting up my account and closing out of Mailspring, I attempted to start the app via the desktop icon, with no such luck.

The only way it loads now is if I start the client via the terminal. Though it still provides the same output as above regarding the missing .config directory.

```
/snap/mailspring/216/bin/desktop-launch: line 177: /home/slang/snap/mailspring/common/.config/user-dirs.dirs: No such file or directory
cp: cannot create regular file '/home/slang/snap/mailspring/common/.config/': Not a directory
/snap/mailspring/216/bin/desktop-launch: line 180: /home/slang/snap/mailspring/common/.config/user-dirs.dirs.md5sum: No such file or directory
/snap/mailspring/216/bin/desktop-launch: line 180: /home/slang/snap/mailspring/common/.config/user-dirs.locale.md5sum: No such file or directory
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "canberra-gtk-module"
Running database migrations
App load time: 215ms

{"error":null}
```
Hopefully this information helps in solving this issue regarding the snap version.

**Comment by synsa** [comment] 2018-06-29 02:37
I get the same error after installing mailspring.

```
$ mailspring
/snap/mailspring/216/bin/desktop-launch: line 177: /home/slang/snap/mailspring/common/.config/user-dirs.dirs: No such file or directory
cp: cannot create regular file '/home/slang/snap/mailspring/common/.config/': Not a directory
/snap/mailspring/216/bin/desktop-launch: line 180: /home/slang/snap/mailspring/common/.config/user-dirs.dirs.md5sum: No such file or directory
/snap/mailspring/216/bin/desktop-launch: line 180: /home/slang/snap/mailspring/common/.config/user-dirs.locale.md5sum: No such file or directory
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "canberra-gtk-module"
Running database migrations
App load time: 1451ms

Running Setup
{"error":null}
TypeError: _electron.app.isInApplicationsFolder is not a function
    at moveToApplications (/src/browser/move-to-applications.es6:4:11)
    at Application.oneTimeMoveToApplications (/src/browser/application.es6:174:5)
    at Application.start (/src/browser/application.es6:88:16)
    at <anonymous> Promise {
  <rejected> TypeError: _electron.app.isInApplicationsFolder is not a function
    at moveToApplications (/src/browser/move-to-applications.es6:4:11)
    at Application.oneTimeMoveToApplications (/src/browser/application.es6:174:5)
    at Application.start (/src/browser/application.es6:88:16)
    at <anonymous> }
```

*Version Info*:

```
$ snap --version
snap    2.33
snapd   2.33
series  16
ubuntu  18.04
kernel  4.15.0-23-generic
```

```
$ snap info mailspring
commands:
  - mailspring
snap-id:      0TyNxgP6wEM3nTXzymtc1wOnvl2P6Iij
tracking:     stable
refresh-date: today at 18:51 PDT
channels:                      
  stable:    1.2.2 (216) 164MB -
  candidate: 1.2.2 (216) 164MB -
  beta:      1.2.2 (216) 164MB -
  edge:      1.2.3 (218) 165MB -
installed:   1.2.2 (216) 164MB -
```

It appears that it has issues creating the .config directory within /snap/mailspring/common/

Generating the .config directory manually removed the error regarding the .config directory. However, it still errored out with the following:
```
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Running database migrations
App load time: 3317ms

Running Setup
{"error":null}
TypeError: _electron.app.isInApplicationsFolder is not a function
    at moveToApplications (/src/browser/move-to-applications.es6:4:11)
    at Application.oneTimeMoveToApplications (/src/browser/application.es6:174:5)
    at Application.start (/src/browser/application.es6:88:16)
    at <anonymous> Promise {
  <rejected> TypeError: _electron.app.isInApplicationsFolder is not a function
    at moveToApplications (/src/browser/move-to-applications.es6:4:11)
    at Application.oneTimeMoveToApplications (/src/browser/application.es6:174:5)
    at Application.start (/src/browser/application.es6:88:16)
    at <anonymous> }
```
After waiting for 30 seconds I ctrl-C'd it and tried again with the following error in output:
```
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Running database migrations
App load time: 207ms

{"error":null}
Failed to generate minidump.Segmentation fault (core dumped)
```

After removing mailspring and then reinstalling; I was able to get it to load for me by running `mailspring` in the terminal. With the following output:
```
/snap/mailspring/216/bin/desktop-launch: line 177: /home/slang/snap/mailspring/common/.config/user-dirs.dirs: No such file or directory
cp: cannot create regular file '/home/slang/snap/mailspring/common/.config/': Not a directory
/snap/mailspring/216/bin/desktop-launch: line 180: /home/slang/snap/mailspring/common/.config/user-dirs.dirs.md5sum: No such file or directory
/snap/mailspring/216/bin/desktop-launch: line 180: /home/slang/snap/mailspring/common/.config/user-dirs.locale.md5sum: No such file or directory
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "canberra-gtk-module"
Running database migrations
App load time: 206ms

{"error":null}
{ Error: DraftEditingSession::ensureCorrectAccount - you can only send drafts from a configured account.
    at DraftEditingSession.ensureCorrectAccount (/src/flux/stores/draft-editing-session.es6:325:13)
    at DraftStore._onSendDraft (/src/flux/stores/draft-store.es6:402:19)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  message: 'DraftEditingSession::ensureCorrectAccount - you can only send drafts from a configured account.' } { pluginIds: [] }
```
After setting up my account and closing out of Mailspring, I attempted to start the app via the desktop icon, with no such luck.

The only way it loads now is if I start the client via the terminal. Though it still provides the same output as above regarding the missing .config directory.

```
/snap/mailspring/216/bin/desktop-launch: line 177: /home/slang/snap/mailspring/common/.config/user-dirs.dirs: No such file or directory
cp: cannot create regular file '/home/slang/snap/mailspring/common/.config/': Not a directory
/snap/mailspring/216/bin/desktop-launch: line 180: /home/slang/snap/mailspring/common/.config/user-dirs.dirs.md5sum: No such file or directory
/snap/mailspring/216/bin/desktop-launch: line 180: /home/slang/snap/mailspring/common/.config/user-dirs.locale.md5sum: No such file or directory
Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "canberra-gtk-module"
Running database migrations
App load time: 215ms

{"error":null}
```
Hopefully this information helps in solving this issue regarding the snap version.

**Comment by illia-v** [comment] 2018-07-12 14:22
There is the same issue with the Snap package on Ubuntu Budgie.

**Comment by sudame** [comment] 2018-07-18 14:13
I had same issue on my Ubuntu 18.04, but in latest version on snap, I can install and run mail spring.
I don't know why it succeeded, so this is just a report, sorry.

**Comment by PascalNoisette** [comment] 2018-07-27 18:17
Hi, the reference to Fedora in the title of this issue should be remove to draw more attention. This is not exclusive to this distribution I also have the same here on ubuntu 17.10.
I tried the snap because he was advertised by [ubuntu](https://twitter.com/ubuntu/status/1020953621985406976) as enterprise class app.

**Comment by fsevenm** [comment] 2018-07-30 12:44
I have the same issue, this is what i got
`fsevenm@fsevenm:~$ snap run mailspring
/snap/mailspring/239/bin/desktop-launch: line 183: /home/fsevenm/snap/mailspring/common/.config/user-dirs.dirs: No such file or directory
cp: cannot create regular file '/home/fsevenm/snap/mailspring/common/.config/': Not a directory
/snap/mailspring/239/bin/desktop-launch: line 186: /home/fsevenm/snap/mailspring/common/.config/user-dirs.dirs.md5sum: No such file or directory
/snap/mailspring/239/bin/desktop-launch: line 186: /home/fsevenm/snap/mailspring/common/.config/user-dirs.locale.md5sum: No such file or directory`

Hope someone can give any solutions.

**Comment by CodeMouse92** [comment] 2021-02-01 20:43
It appears that this issue has been resolved, so we are closing it. If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-01 20:43 UTC
Labels: audit
