### ISSUE TITLE
Bug: Attachments are not displayed for some emails

### ISSUE THREAD

**Issue by teejee2008** [Foundry376/Mailspring#1922] opened 2020-04-20 15:40 UTC
**Describe the bug**
Attachments are not displayed for some emails.

**To Reproduce**
1. Open any email that has an attachment
2. Email does not display attachments anywhere (in reading pane, in list, or after opening the email in new window)

**Expected behavior**
Email should show attachment

**Screenshots**

This email has a 3 MB attachment but doesn't show it anywhere.

![image](https://user-images.githubusercontent.com/12488854/79770002-6f849580-834a-11ea-899d-2789209a26b5.png)

![image](https://user-images.githubusercontent.com/12488854/79770104-9642cc00-834a-11ea-8bfb-2de3a4dbe9d1.png)

![image](https://user-images.githubusercontent.com/12488854/79770272-d144ff80-834a-11ea-8c53-0f1626b076ec.png)

**Setup: (please complete the following information):**
 - OS: Ubuntu 18.04 
 - OS Version: 18.04 with all updates installed
 - Mailspring Version: 1.7.5

**Additional context** 

- It appears to be random as some emails display attachments but others don't. 

- The issue seems to have started with a recent update as it didn't occur before. 

- Tried doing a fresh install of Mailspring on another system (tried both the DEB and Snap versions) and they exhibit the same problem.

**Comment by bengotow** [comment] 2020-04-22 23:17
Hey @teejee2008 — thanks for reporting this! I don't think I've seen this happen before. I appreciate you dong a second install on another system, that rules out the app being unable to write to the filesystem to save files, etc.

Could you try opening that email in Mailspring, and then clicking in the whitespace to the left of the Reply button?

<img width="356" alt="image" src="https://user-images.githubusercontent.com/1037212/80042629-2ad13980-84c5-11ea-9e24-c9f70b3fd2ff.png">


There's a small hidden menu there with an option to "Show Original". If you click that, it'll open the RFC2822 message (the raw MIME from your mail server).

Inside there, you should see a structure something like this:

```
Content-Type: multipart/related; boundary="000000000000b0e5ba05a3e7e21e"

--000000000000b0e5ba05a3e7e21e
Content-Type: multipart/alternative; boundary="000000000000b0e5b705a3e7e21d"

--000000000000b0e5b705a3e7e21d
Content-Type: text/plain; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

<possible plaintext version of email>

--000000000000b0e5b705a3e7e21d
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

<possible HTML version of email>

--000000000000b0e5b705a3e7e21d--
--000000000000b0e5ba05a3e7e21e
Content-Type: image/png; name="image.png"
Content-Disposition: attachment; filename="image.png"
Content-Transfer-Encoding: base64
X-Attachment-Id: ii_k9bu89js0
Content-ID: <ii_k9bu89js0>

<attachment content>
```

If you could post the general shape you see in your email that'll help me narrow this down and create a test case to reproduce it. It'd be super helpful if you could send me the entire text of that raw MIME message to ben@foundry376.com, but I understand the backup in this screenshot might be sensitive data so that's fine!

**Comment by bengotow** [comment] 2020-04-22 23:20
Ahh one more question—is there any chance this attachment is a plain text file? We recently added support for plaintext message viewing / replying in Mailspring, and it's possible that the app now thinks the plaintext is a separate "version" of the message body, not an attachment. I haven't seen that happen, but if this didn't occur until recently there's actually a pretty narrow set of things that could cause it.

**Comment by teejee2008** [comment] 2020-04-23 04:29
I have emailed you the raw data. The raw data shows the attachment in the message.

The attachment is a TAR+XZ archive 3 MB in size.  I have other emails with similar attachments that display properly.

**Comment by CodeMouse92** [comment] 2021-02-27 03:27
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/attachments-are-not-displayed-for-some-emails/857

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@teejee2008: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-27 03:27 UTC
Labels: audit, bug
