### ISSUE TITLE
Mailspring not syncing with private IMAP server (Apache James)

### ISSUE THREAD

**Issue by jessepeng** [Foundry376/Mailspring#1479] opened 2019-04-27 13:00 UTC
##### Are there any related issues?

Difficult to say since the logs are not very detailed.

##### What operating system are you using?

Ubuntu 18.04.2 LTS

##### What version of Mailspring are you using?

1.6.1-aceed8e5

--

**Bug?**

##### Is this an email sync or connection issue?

Yes, it's an email sync issue. Email syncing works fine the first time the account is added but stops working after a while. I'm using a Let's Encrypt SSL certificate that I frequently have to exchange (since it's only valid for 3 months). I don't know if this has something to do with the issue, but maybe this information helps. The logs show no exception details:

`2944 [2019-04-27 14:45:43.993] [foreground] [info] syncFolderChangesViaCondstore - INBOX: modseq 7444 to 7976, uidnext 2347 to 2513
2944 [2019-04-27 14:45:44.037] [foreground] [info] Encountered exception: {"debuginfo":"syncFolderChangesViaCondstore - syncMessagesByUID","key":"ErrorFetch","retryable":true,"what":"std::exception"}
2944 [2019-04-27 14:45:44.037] [foreground] [info] --sleeping
2944 [2019-04-27 14:45:49.136] [background] [info] Syncing folder list...
2944 [2019-04-27 14:45:49.250] [background] [info] syncFolderUIDRange for INBOX, UIDs: 1 - 1597, Heavy: true
2944 [2019-04-27 14:45:50.094] [background] [info] - remote=538, local=533
2944 [2019-04-27 14:45:50.124] [background] [info] - Updating message HD5P8GeFTseVXFSiuH9edMVetuzMk5PRZEp3teaFR
2944 [2019-04-27 14:45:50.124] [background] [info] -- UID (194 to 199)
2944 [2019-04-27 14:45:50.153] [background] [info] - Updating message HD5P8GeFTseVXFSiuH9edMVetuzMk5PRZEp3teaFR
2944 [2019-04-27 14:45:50.153] [background] [info] -- UID (199 to 198)
2944 [2019-04-27 14:45:50.180] [background] [info] - Updating message HD5P8GeFTseVXFSiuH9edMVetuzMk5PRZEp3teaFR
2944 [2019-04-27 14:45:50.180] [background] [info] -- UID (198 to 197)
2944 [2019-04-27 14:45:50.209] [background] [info] - Updating message HD5P8GeFTseVXFSiuH9edMVetuzMk5PRZEp3teaFR
2944 [2019-04-27 14:45:50.209] [background] [info] -- UID (197 to 196)
2944 [2019-04-27 14:45:50.235] [background] [info] - Updating message HD5P8GeFTseVXFSiuH9edMVetuzMk5PRZEp3teaFR
2944 [2019-04-27 14:45:50.235] [background] [info] -- UID (196 to 195)
2944 [2019-04-27 14:45:50.249] [background] [info] syncFolderChangesViaCondstore - INBOX: modseq 7444 to 7976, uidnext 2347 to 2513
2944 [2019-04-27 14:45:50.290] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderChangesViaCondstore - syncMessagesByUID","key":"ErrorFetch","retryable":true,"what":"std::exception"}`

Detailed logs are attached. [mailspring-log.zip](https://github.com/Foundry376/Mailspring/files/3123894/mailspring-log.zip)

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

It's a private email server running on Apache James 3.0. All other mail providers work normally.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No, unfortunately not.

**Comment by CodeMouse92** [comment] 2021-02-10 23:34
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

@jessepeng: Can you please confirm that this is still broken with 1.8.0, and if so, open a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-10 23:34 UTC
Labels: audit
