### ISSUE TITLE
Bug: Update.exe not removed from system on uninstall [Windows]

### ISSUE THREAD

**Issue by dweremeichik** [Foundry376/Mailspring#2213] opened 2020-11-28 23:08 UTC
**Describe the bug**
[Windows 10] Update.exe not removed from system/startup on uninstall.
**To Reproduce**
1. Uninstall Mailspring.
2. Open task manager
3. Click startup
4. Update.exe is still present (it exists under AppData\Local\Mailspring)

**Expected behavior**
The updater should be removed when mailspring is removed.

**Setup:**
 - OS: Windows 10
 - Mailspring Version:  unsure - updater metadata says file version1.7.9.0 (mailspring was removed months ago).

**Additional context** 
Removed mailspring months ago and came across the updater in my startup today.

**Comment by CodeMouse92** [comment] 2021-02-23 22:55
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/update-exe-not-removed-from-system-on-uninstall-windows/754

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@dweremeichik: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-23 22:55 UTC
Labels: audit, bug
