### ISSUE TITLE
When I input Japanese, the sentence disappears during the input.

### ISSUE THREAD

**Issue by kometchtech** [Foundry376/Mailspring#1531] opened 2019-06-19 12:16 UTC
##### What operating system are you using?

Windows 10 1903 [10.0.18362.175]

##### What version of Mailspring are you using?

1.6.2

**Bug?**

When I input Japanese, the sentence disappears during the input.
I attach a screen shot, but I am not certain at the time of character input, and the character I entered in the middle disappears even though I did not delete it.

I tried changing the input speed, but I did not improve the symptoms.
It also suspects Mailspring or base electron, as no problems have occurred with other applications.

![mailspring](https://user-images.githubusercontent.com/5137077/59764510-e38f8080-92d6-11e9-9589-fcd1c4e21a30.gif)

There was no problem with English input.

**Comment by bengotow** [comment] 2019-07-01 04:04
Hey @kometchtech thanks for reporting this—I'm looking in to this ASAP! Will see what's going on.

**Comment by bengotow** [comment] 2019-07-01 04:27
Ok—I've tried a bunch of things, and here's what seems to happen:

- When you start typing, Mailspring enters text composition mode with the dropdown.

- When you press enter to confirm your typing and advance the text cursor, it works fine. (I think?) 

- When you press TAB to control the composition dropdown (on the mac), it transfers keyboard focus to the To field and inserts the text suggestion there instead. (BAD)

- When you click something to blur the composition dropdown and save your current composition, Mailspring enters a weird state where the text is still there but is not selectable. If you type another phrase, the text is overwritten (BAD)

Does that cover your scenario? I can't quite tell in the GIF how you are exiting / confirming the text when it disappears.

Unfortunately, I think these problems are probably upstream in the Slate text editor. It looks like there are quite a few known problems that the maintainers are merging in to https://github.com/ianstormtaylor/slate/issues/2368. I will debug exactly what is happening, especially with the focus issue, and see if I can fix that on our side.

I'm very sorry but I don't think this will be fixed in time for the 1.6.3 release tomorrow. There are a few other important bug fixes I want to get out, but I'll make sure to investigate this early this week.

**Comment by bengotow** [comment] 2019-07-01 16:32
Hey @kometchtech, it looks like this works a bit better in the Slate examples (https://www.slatejs.org/#/rich-text) so I'm trying to narrow this down more and see what's going on. Maybe there is something we can do today.

**Comment by bengotow** [comment] 2019-07-01 17:19
It turns out that that this issue may be specific to our text editor and Chrome-based browsers. (When I posted above I was using Firefox!) I filed a bug with at least one behavior I observed: https://github.com/ianstormtaylor/slate/issues/2906.

It looks like we may be able to patch around this though, looking to see now.

**Comment by kometchtech** [comment] 2019-07-02 00:05
It seems that you responded in 1.6.3, but when I checked it at hand, I did not improve it.
The phenomenon of disappearing of the character which I entered by myself before I decide Kanji conversion reappears.

**Comment by bengotow** [comment] 2019-07-04 13:59
Hey @kometchtech ahh interesting! Thank you for the extra detail. I'll see if I can get that to happen. I didn't realize that in your GIF, the panel was closing on it's own.

**Comment by bengotow** [comment] 2019-07-05 05:49
Hey @kometchtech — I set up my Windows VM to test this and I was able to reproduce exactly what you see, even after the fixes in 1.6.3. It looks like the IME input is conceptually similar on Windows, but Chrome emits different events. It's quite broken, will see if I can fix this!

**Comment by kometchtech** [comment] 2019-07-05 05:54
Thank you for your patient investigation.
I do not know about this part systemically, but please contact me if there is any need.

**Comment by kevinphys** [comment] 2019-11-18 10:37
Hi @bengotow, this happened in 1.7.2 as well.
I have the issue on both Windows 10 and Ubuntu 18.04, typing within tradition Chinese zhuyin input.

Changing input speed doesn't improve the undetermined words disappearing.

But, the funny thing I found is that if I switch laptop mode from "efficiency" to "performance" with built-in device manager. The incidence of disappearing words reduces significantly, though it would still happen somehow.


![Peek 2019-11-18 18-22](https://user-images.githubusercontent.com/8801187/69044874-b20b1480-0a30-11ea-833e-14731ad17d58.gif)

**Comment by takedakn** [comment] 2019-12-22 10:21
I'm facing the same issue.

Environment:
Mailspring: 1.7.2-4522b259 (electron 4.2.2)
OS: Windows 10
IME: Google Japanese Input

Expected behaviror:
 1. Enable Japanese IME in mail compose screen.
 2. Type keys to input (e.g. furuikeyakawazutobikomumizunooto) then underlined and unfinalized hiragana characters are shown  (e.g. ___ ふるいけやかわずとびこむみずのおと ___ ).
 3. Press enter then input charcters are finalized (e.g. ふるいけやかわずとびこむみずのおと).

Actual behaviror:
 1. Enable Japanese IME in mail compose screen.
 2. Type keys to input, but sometimes all input charcters are cleared.
    * type: furuikeyakawazutobi, shown ___ ふるいけやかわずとび ___
    * (suddenly input characters are cleared)
    * keep typing remaining characters: komumizunooto, shown ___ こむみずのおと ___
    * (press enter)
    * only こむみずのおと part is finalized.

The timing of sudden clear is difficult to expect, but it's easy to reproduce when I type long unfinalized sentense. This should be a critical issue for Japanese or Chinese writers.

I'm happy to do addional testing if nessesary.

**Comment by hieuxlu** [comment] 2020-02-28 16:10
I also have problem with Vietnamese Input on Ubuntu Linux, so this is not limited to Windows. @bengotow If you can point me where can I start investigating this bug in the source code, I could give a helping hand.

**Comment by jacobgoodo** [comment] 2020-07-17 05:25
![Typing Japanese in Mailspring on Windows not functioning as it should.](https://my-existence-is-an.enormous.fail/ACSqYXf.gif)

The exact same is happening to me, and this doesn't happen anywhere else. I really love this email client, but I may switch soon due to this - it makes typing in Japanese impossible.

**Comment by CodeMouse92** [comment] 2021-02-09 23:16
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/when-i-input-japanese-the-sentence-disappears-during-the-input/535

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@kometchtech @kevinphys @takedakn @hieuxlu @norenTM: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-09 23:16 UTC
Labels: audit, bug, composer, done-pending-release
