### ISSUE TITLE
Bug: Select All doesn't work from search results

### ISSUE THREAD

**Issue by sergeystoma** [Foundry376/Mailspring#1807] opened 2020-02-24 02:01 UTC
After searching, Select All doesn't work to select all found emails at once, either through Edit -> Select All menu or Cmd-A key.

Interestingly, Select All Read/Unread/Starred/Unstarred actions work as expected.

 - OS: macOS Catalina
 - Mailspring Version: 1.7.2

**Comment by CodeMouse92** [comment] 2021-02-04 18:46
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/select-all-messages/171

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-04 18:46 UTC
Labels: audit, bug
