### ISSUE TITLE
[Feature Request] Add an option to create global mail rules

### ISSUE THREAD

**Issue by tigerstrikemedia** [Foundry376/Mailspring#1209] opened 2018-10-31 23:28 UTC
##### What operating system are you using?
Manjaro KDE

##### What version of Mailspring are you using?
1.5.1-2

**Feature Request?**
There should be an option in the mail rules to create global rules. Currently there is only the option for individual mail accounts.

##### Does this feature exist in another mail client or tool you use?
Yes
...

**Comment by bengotow** [comment] 2018-11-03 16:59
This would definitely be nice. I think the range of actions might be a bit more limited (since Mailspring doesn't move mail between accounts, you couldn't create a rule to add a Gmail label to all messages matching a phrase across all accounts, for example). Will see if this can add this the next time mail rules are revisited!

**Comment by CodeMouse92** [comment] 2021-02-11 22:28
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/add-an-option-to-create-global-mail-rules/575

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@tigerstrikemedia @jenschurchill: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-11 22:28 UTC
Labels: audit, enhancement
