### ISSUE TITLE
Make link and read tracking disabled by default

### ISSUE THREAD

**Issue by zowber** [Foundry376/Mailspring#244] opened 2017-10-24 16:29 UTC
I just sent my first email with Mailspring and was found it uncomfortable to see that link and read tracking was enabled by default on my fresh install (via Arch AUR).

I believe that tracking should be disabled by default and an made an opt-in feature.

**Comment by bengotow** [comment] 2017-10-24 20:54
Hey!  Thanks for the feedback—the reason these are enabled by default is because they're the reason a lot of sales and business-oriented folks download and use Mailspring in the first place (and then pay for Mailspring Pro!) I agree it's not for everyone, but I can't afford to obscure them by default and risk lowering the Pro conversion rate among folks that think it's the most useful bizdev/sales feature ever. (They're the reason I can afford to maintain Mailspring all day long!)

That said, I'm working on updates to the onboarding flow and I think it's likely we could add a checkbox in there that says something along the lines of "I'm not interested in trying out Mailspring Pro features" so you can hide this stuff more easily.

**Comment by zowber** [comment] 2017-10-25 08:52
I hear your point loud and clear. If the pro subs pay for the development I agree it should be your focus to nudge users in the direction you mention.

I think perhaps the drive I felt to raise this issue was more of a knee-jerk reaction to seeing the program work by default in a way that I feel doesn't respect or empower me as a user nor respect the people I chose to send mail to. I really don't want to know if recipients have opened/read my messages, and don't feel it's right to be tracking them without their explicit knowledge of what is happening.

However I do fully support your idea that these settings and the ability to opt in/out could be presented in a clear way during on-boarding and would thus hand choice and power back to the user. I.e., presenting all the default authoring options, explaining what they do and what their benefits may be, and allowing setting of those options before any mail has been sent or received. That would certainly resolve my issue, at least in the case of new installs.

**Comment by slhck** [comment] 2017-11-07 12:38
> I think perhaps the drive I felt to raise this issue was more of a knee-jerk reaction to seeing the program work by default in a way that I feel doesn't respect or empower me as a user nor respect the people I chose to send mail to. I really don't want to know if recipients have opened/read my messages, and don't feel it's right to be tracking them without their explicit knowledge of what is happening.

Just want to chime in and second your opinion. I wasn't aware of the tracking being applied by default (let alone that it was a feature) and was almost about to uninstall Mailspring immediately after not being able to find a global setting to disable it. I've only later learned from another GitHub issue that it's possible to turn it off in the options below the mail, which I assume few first-time users explore if they just want to go on with working on their mail.

I fully understand that this project operates between being free, open source software and being a product that you would like to sell, but being transparent to your users (and potential customers) about which (somewhat) privacy-invasive options are applied by default would go a long way in increasing trust and reputation for your software.

That said, thanks for the great piece of software!

**Comment by SimonEnsemble** [comment] 2017-11-20 02:43
+10, I came to this page just before I was about to uninstall Mailspring because I can't figure out how to disable link tracking. It is indeed embarrassing if you sent an email with link tracking.

**Comment by hardfire** [comment] 2017-12-21 11:17
Maybe its just me, but I couldn't find a way to disable the tracking for all newly composed emails. I don't mind the initial default with tracking enabled. An option to disable it later would be great.
Thank you for this great piece of software btw.

**Comment by tenkabuto** [comment] 2018-06-04 21:30
On a different track, please make the tooltip for these buttons tell users whether the feature is currently enabled or not. The icons for them were blue, and when I hovered over them the tooltip said "Disable Open Tracking", and yet I still misinterpreted them as suggesting that these features were disabled until I click on them.

**Comment by infosisio** [comment] 2018-10-20 14:46
@MichelChouinard I agree. Such an option would be tremendously useful.

**Comment by krupenja** [comment] 2019-02-05 14:47
Personally, I do not mind that tracking is on by default. What bothers me is that there is no global setting to it this off. I find the feature less than ethically sound and a potential invasion of privacy of e-mail recipients. Turning it off for every e-mail is time-consuming and somewhat frustrating as you have to keep the thing in mind constantly.

This is such a pity considering that Mailspring is an amazing e-mail client in general with some killer features like the perfect dark theme.

**Comment by infosisio** [comment] 2019-02-05 14:48
@krupenja I completely agree.

**Comment by afritzler** [comment] 2019-08-23 06:42
There should definitely be a global setting to turn of tracking since it is a violation of GDPR.

**Comment by ForNeVeR** [comment] 2019-11-16 06:29
I wasn't able to find an option to disable the mail tracking. How does it work, and how do I disable it?

As a business user currently evaluating whether to pay for Pro account or not, I am very concerned if Mailspring inserts some sort of tracking scripts/pixels (or whatever) to my messages and I cannot disable it!

**Comment by ForNeVeR** [comment] 2019-11-16 06:34
Okay, looks like I've found it. To disable read and link tracking, one have to make sure these icons aren't highlighted in the Compose Message window:
![image](https://user-images.githubusercontent.com/92793/68989204-9a3b6100-0875-11ea-9e2f-946010937206.png)

Mailspring seems to remember their state between restarts, so, if you disable them once and don't touch them since, they'll stay disabled. Seems good?

But it would really be nice to have a settings checkbox to completely disable these (and hide the buttons from the UI), even if enabled by default.

**Comment by Frenzie** [comment] 2019-11-16 06:34
I don't think there's anything in the global settings (but there should be, see https://github.com/Foundry376/Mailspring/issues/244#issuecomment-385516273), just in the mail compose window. Also the way the icons work is rather unclear (cf. https://github.com/Foundry376/Mailspring/issues/244#issuecomment-394506226).

![Screenshot_2019-11-16_07-30-46](https://user-images.githubusercontent.com/202757/68989193-21bbac80-0843-11ea-968e-e5d3333c7ffe.png)

But yeah, the first time I tried this app and sent an e-mail to my wife it suddenly popped up a notification that she'd clicked on a link… super creepy!

**Comment by CodeMouse92** [comment] 2021-01-28 01:31
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/make-link-and-read-tracking-disabled-by-default/321/2

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@zowber @slhck : if you join and reply to the issue, the moderators can make an effort to reassign your migrated posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 01:31 UTC
Labels: audit, product-direction
