### ISSUE TITLE
[Feature Request] Add Draft Versioning

### ISSUE THREAD

**Issue by ReillyBrogan** [Foundry376/Mailspring#1478] opened 2019-04-27 01:31 UTC
##### What operating system are you using?
Linux

##### What version of Mailspring are you using?
1.6.1

**Feature Request?**

##### Does this feature exist in another mail client or tool you use?
Could we add the ability to enable periodic snapshots of draft emails as they are being written? I just had Mailspring crash while I was finishing up a very long email and when it came back up Mailspring had overwritten my long email with a blank draft. If we had a versioning system as a simple backup it would have been possible to roll the draft back a few minute to a pre-crash state instead of having to rewrite the email and losing hours of work (lesson learned, I'll write long emails in something with better crash recovery like LibreOffice Writer).

**Comment by bengotow** [comment] 2019-05-26 23:31
Ahhh man I'm so sorry this happened. Mailspring does periodically save your draft as you work, but right now it only keeps the most recent copy.

I think the underlying crashing issue will be fixed in the next release when we switch to a newer version of the SlateJS text editor. There are only one or two more things I have to fix to be able to ship that, and I'll try to knock it out tomorrow so we can start testing.

Sorry again for the hassle. If the new version of the text editor doesn't resolve the issue we can definitely make it autosave versions or perhaps just keep the text/html of your draft on disk somewhere.

**Comment by RasheedAZ** [comment] 2020-03-30 02:01
Hi Ben. Hope you all are well and safe. I wanted to ask whether your autosave or keeping text of draft on disk idea was implemented?

Thanks.

**Comment by CodeMouse92** [comment] 2021-02-19 01:01
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/add-draft-versioning/705

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@ReillyBrogan: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-19 01:01 UTC
Labels: audit, bug, composer
