### ISSUE TITLE
[Feature request] Text expansion of abbreviations

### ISSUE THREAD

**Issue by mimavox** [Foundry376/Mailspring#1673] opened 2019-10-18 09:23 UTC
**Feature Request**
As a user, I would like to be able to enter short abbreviations for common email closings and have them expand to full phrases. Preferably, these abbreviations/phrases would be editable so I could edit/add/remove them according to my preferences.

##### Does this feature exist in another mail client or tool you use?
* On MacOS, this is a system-wide feature that works in Apple Mail. For example, in Swedish, I'm able to close my email with "mvh" and have this abbreviation automatically expand to "Med vänliga hälsningar" which is a common email closing in Sweden. This expansion takes place instantenously, as soon as the abbreviation is detected. This doesn't work in Mailspring however (perhaps because it being an Electron app?)
* On Linux, I have yet to found a working software that replicates this functionality.
...

**Comment by bengotow** [comment] 2019-10-22 02:35
Hey! That's interesting—I'm surprised the default expansions don't work on macOS. It looks like it is an Electron thing, but we can potentially get the default behavior with the help of https://github.com/CharlieHess/electron-text-substitutions/ (at least on mac.),but it's implemented in a bit of a heavyweight way we'd need to retool for the composer. Will see if this can happen soon!

**Comment by CodeMouse92** [comment] 2021-02-26 17:25
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we already migrated to Discourse:

https://community.getmailspring.com/t/osx-text-replacement-support/599

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@mimavox: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-26 17:25 UTC
Labels: audit, composer, enhancement
