### ISSUE TITLE
Feature Request: Global Mail Folders/Labels

### ISSUE THREAD

**Issue by amadrzyk** [Foundry376/Mailspring#1902] opened 2020-04-13 21:08 UTC
**Is your feature request related to a problem? Please describe.**
I often get 20+ emails a day, and found it super overwhelming to the point where my inbox could easily reach 500+ unreads. I've stared leveraging inbox rules and they've helped a **ton**. However, I have several accounts linked, and often labels are repeated across accounts.

**Describe the solution you'd like**
One solution I think would be great is a **global** collection of labels that could be applied to every account in Mailspring. This would mean that when a global label is created it is synced with each account, and mail rules would also be able to be applied globally to all incoming mail.

**Describe alternatives you've considered**
The alternative is the current solution, where labels are kept across different accounts. I use this feature and like it, but I spend most of my time in the "unified" view (and many others probably do as well), so it would be great to have a "unified" label view as well.

**Comment by CodeMouse92** [comment] 2021-02-27 02:55
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/global-mail-folders-labels/852

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@amadrzyk: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-27 02:55 UTC
Labels: audit, enhancement
