### ISSUE TITLE
Doesn't work with Magnet App anymore.

### ISSUE THREAD

**Issue by gregorian-iterable** [Foundry376/Mailspring#1302] opened 2019-01-04 18:33 UTC
##### Are there any related issues?

None that I could find.

##### What operating system are you using?

macOS - 10.14.1 (18B75)

##### What version of Mailspring are you using?

Version 1.5.5 (1.5.5)
--

**Bug?**

##### Is this an email sync or connection issue?

Not sync or connection related. 

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No

##### Is the issue reproducible with a particular attachment, message, signature, etc?

![screen shot 2019-01-04 at 10 10 38 am](https://user-images.githubusercontent.com/34252625/50704197-6368ad80-100b-11e9-99ba-dec3b7991ed2.png)

I like snapping my app windows with the Magnet app. MailSpring is the only app that can no longer snap or orient, see screenshot above. All of the options are greyed out whereas the other apps are still able to snap correctly.

**Comment by midgethoen** [comment] 2019-01-21 10:57
I have the same issue.. 
It might also be useful to note that this is the only electron based app that I have  that suffers from this issue, so it seems to be something Mailspring specific

**Comment by Ancillas** [comment] 2019-01-29 17:34
I use Mailsprint 1.5.5 and Magnet 2.4.2 on MacOS Mojave 10.14.2 and I cannot reproduce this issue.  I use my keyboard shortcut Ctrl+Option+Arrow to snap Mailspring to either side of my screen without issue.

**Comment by midgethoen** [comment] 2019-02-01 17:11
> I use Mailspring 1.5.5 and Magnet 2.4.2 on MacOS Mojave 10.14.2

im using mailspring 1.5.5, magnet 2.4.1 on osx 10.14.2 (18C54)

**Comment by midgethoen** [comment] 2019-02-01 17:13
upgrading magnet 2.4.2 does not fix it for me

**Comment by alechp** [comment] 2020-03-29 16:33
![Screen Shot 2020-03-29 at 9 33 07 AM](https://user-images.githubusercontent.com/3058939/77854646-4e43e580-71a0-11ea-9347-f0f5cb29b56d.png)

Running latest version. Confirmed Magnet App doesn't work with MailSpring.

**Comment by lopugit** [comment] 2020-06-22 06:52
yeah hasn't worked for a while :'(

**Comment by CodeMouse92** [comment] 2021-02-18 02:05
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/doesnt-work-with-magnet-app-anymore/689

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@gregorian-iterable @midgethoen @Ancillas @alechp: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-18 02:05 UTC
Labels: audit
