### ISSUE TITLE
Feature request: Gnome Online Accounts integration

### ISSUE THREAD

**Issue by luispabon** [Foundry376/Mailspring#466] opened 2017-12-21 10:46 UTC
##### What operating system are you using?
Ubuntu 17.10 / Gnome 3.26

##### What version of Mailspring are you using?
1.0.10 / .deb

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
Evolution

The Gnome desktop already has an online accounts section where different accounts can be set up for email, calendar, files etc and manages authentication. Evolution integrates with this to provide pre-configured mailboxes and calendars per account.

It would be great if Mailspring could also tap into this system to auto configure itself.

**Comment by bengotow** [comment] 2017-12-27 17:54
Hey! If anyone knows more about this and could write the code to retrieve the account information and passwords from Gnome, I think this would be a really cool feature. It'd probably be best to wrap the retrieval into a node module that could be used in other projects as well.

**Comment by fiws** [comment] 2018-01-09 10:27
No C++ developer but did some digging:

* [GOA API](https://developer.gnome.org/goa/stable/)
 
Looks like there are 2 ways to implement this:

A: use the [GoaClient](https://developer.gnome.org/goa/stable/GoaClient.html) – native module
B: Use the [d-bus API](https://developer.gnome.org/goa/stable/ref-dbus.html) with this node module: https://github.com/Shouqun/node-dbus – pure js implementation

**Comment by PascalBe07** [comment] 2019-06-05 04:25
Any Update on this lately? This would be a very cool feature.

**Comment by CodeMouse92** [comment] 2021-02-20 03:57
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/gnome-online-accounts-integration/718

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@luispabon @fiws: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-20 03:57 UTC
Labels: audit, enhancement, good first issue, linux
