### ISSUE TITLE
Bug: Cannot Compose Mail

### ISSUE THREAD

**Issue by ckkibet** [Foundry376/Mailspring#2035] opened 2020-05-30 19:06 UTC
**Describe the bug**
Sometimes when I launch MailSpring, I cannot compose mail. However, shortcuts work pretty well as pressing C launches the compose window. However, trying to type into that window does not write/display anything on the screen. 

**Setup: (please complete the following information):**
 - OS: Fedora
 - OS Version 32 (Workstation Edition)
 - Mailspring Version: 1.7.6

**Comment by skonsoft** [comment] 2020-06-02 07:23
Hello,

I have exactly the same problem. I can not compose email. It looks like mailspring does not recognize the keyboard. **Only mouse is working !!**

Can you fix this issue ASAP pease !

**I can not work !!!!**

OS: Ubuntu 20.04 LTS
Mailspring: 1.7.8-13635bcf

Regards.

**Comment by skonsoft** [comment] 2020-06-04 12:27
Any news ??

**Comment by skonsoft** [comment] 2020-06-08 11:32
After some tries, after installing hplip drivers, i got this problem:

**(mailspring:8263): IBUS-WARNING **: Unable to connect to ibus: Could not connect: Connection refused**

Here is the complete log:
```

Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Running database migrations
App load time: 307ms

{"error":null}

(mailspring:8718): IBUS-WARNING **: Unable to connect to ibus: Could not connect: Connection refused

(mailspring:8718): IBUS-WARNING **: Events queue growing too big, will start to drop.

(mailspring:8718): IBUS-WARNING **: Events queue growing too big, will start to drop.

(mailspring:8718): IBUS-WARNING **: Events queue growing too big, will start to drop.

(mailspring:8718): IBUS-WARNING **: Events queue growing too big, will start to drop.

(mailspring:8718): IBUS-WARNING **: Events queue growing too big, will start to drop.

(mailspring:8718): IBUS-WARNING **: Events queue growing too big, will start to drop.

(mailspring:8718): IBUS-WARNING **: Events queue growing too big, will start to drop.

(mailspring:8718): IBUS-WARNING **: Events queue growing too big, will start to drop.
```

This happens each time i install the hplip driver that you can found it here:

[https://developers.hp.com/hp-linux-imaging-and-printing/gethplip](https://developers.hp.com/hp-linux-imaging-and-printing/gethplip)

Tip: Perhaps there is a conflicted version of python as it' used by hplip and mailspring. Mailspring should use the snap python version and not the system's one. Here is a list of all installed pythons:
```
Python 3.7.7
/snap/core18/1705/usr/bin/python3.6: Python 3.6.9
/snap/core18/1705/usr/bin/python3.6m: Python 3.6.9
/snap/core18/1754/usr/bin/python3.6: Python 3.6.9
/snap/core18/1754/usr/bin/python3.6m: Python 3.6.9
/snap/core/9066/usr/bin/python3.5: Python 3.5.2
/snap/core/9066/usr/bin/python3.5m: Python 3.5.2
/snap/core/9289/usr/bin/python3.5: Python 3.5.2
/snap/core/9289/usr/bin/python3.5m: Python 3.5.2
/snap/gnome-3-28-1804/116/usr/bin/python3.6: Python 3.6.9
/snap/gnome-3-28-1804/116/usr/bin/python3.6m: Python 3.6.9
/snap/gnome-3-28-1804/128/usr/bin/python3.6: Python 3.6.9
/snap/gnome-3-28-1804/128/usr/bin/python3.6m: Python 3.6.9
/snap/gnome-3-34-1804/33/usr/bin/python3.6: Python 3.6.9
/snap/gnome-3-34-1804/33/usr/bin/python3.6m: Python 3.6.9
/snap/gnome-3-34-1804/36/usr/bin/python3.6: Python 3.6.9
/snap/gnome-3-34-1804/36/usr/bin/python3.6m: Python 3.6.9
/snap/inkscape/7601/usr/bin/python3.6: Python 3.6.9
/snap/inkscape/7601/usr/bin/python3.6m: Python 3.6.9
/snap/inkscape/7627/usr/bin/python3.6: Python 3.6.9
/snap/inkscape/7627/usr/bin/python3.6m: Python 3.6.9
/snap/mailspring/482/usr/bin/python2.7: Python 2.7.12
/snap/mailspring/488/usr/bin/python2.7: Python 2.7.12

```

**Comment by Dahaniel** [comment] 2020-07-27 14:21
Same here, keyboard commands seem to work but I cannot type text anywhere in mailspring (compose or search field).
I am using 1.7.8-13635bcf on Ubuntu 20.04.

Interestingly this behavior started after I used a new printer for the first time, using it with the auto-installed driver. Could that relate to hplip as reported above?

**Comment by CodeMouse92** [comment] 2021-03-02 00:52
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/cannot-compose-mail/909

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@ckkibet @Dahaniel: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-02 00:52 UTC
Labels: audit, bug
