### ISSUE TITLE
Mails are not sent before relaunch of Mailspring

### ISSUE THREAD

**Issue by ploum** [Foundry376/Mailspring#366] opened 2017-11-27 10:14 UTC
Quite often, it seems that mails are not sent before a relaunch of Mailspring. The little "currently sending" spinner keeps turning and turning infinitely.

##### What operating system are you using?
OSX

##### What version of Mailspring are you using?
1.0.8-5a…

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

In-house exchange server accessed through IMAP and SMTP

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Didn't find why it happens. Seems to happen mostly when the laptop lost the connection then get it back. Mailspring seems to not get it back.

--

**Comment by palefire19** [comment] 2017-11-27 12:05
I think this is related / the same as my #336 and #348. Emails getting stuck without sending. Restarting Mailspring seems to reliably get them to go out.

**Comment by ploum** [comment] 2017-11-27 16:59
might be a duplicate of #336 indeed. I've disabled undo send to see how it works.

**Comment by kaleidoscopique** [comment] 2017-12-11 20:48
Same here. I'm using OS/X, and I tried different e-mail providers (Zoho and GSuite), same result. Keep me in touch if I can help with more details or some logs.

**Comment by gottlike** [comment] 2017-12-12 13:55
Same here.. always happens after I put the laptop to sleep.

**Comment by ploum** [comment] 2017-12-14 11:44
I now have a mail that refuses to be sent, even after multiple stop/restart of Mailspring

**Comment by gottlike** [comment] 2017-12-15 09:43
@bengotow This is the one bug that is preventing me from recommending Mailspring to my friends (plus the calendar feature request), as this makes the app really flaky (I can never be sure that mail is sent and have to check the drafts folder). I'd like to be able to trust my mail client to reliably take care of the most basic email functions. It'd be great if you can at least give a quick feedback to confirm this is on your radar.

**Comment by kaleidoscopique** [comment] 2017-12-15 10:28
Same as @gottlike ... I was very mad at Zoho Mail because I thought there was a major issue with their SMTP servers. So I paid an annual plan @ Google Suit to solve this issue... which was in fact related to Mailspring.

I do not want to complain about a free software, but I guess a lot of Mailspring's users will be in trouble because of this bug (I spent 3 days without sending any e-mail... my clients were not happy at all).

Good luck to fix it btw, I really hope this is on your radar too.

**Comment by overclockedllama** [comment] 2018-02-11 15:38
same! but it was only happening with my google account, so i removed it and re-added it and that seemed to fix the problem :D

**Comment by AGraphicDesigner** [comment] 2018-10-24 18:55
I've had the same problem, but only with my private email hosting account, my gmail works fine. I've tried removing and re-adding the account several times, but the problem still persists.

**Comment by wonx** [comment] 2019-08-05 13:52
I still have the same problem, and it happens quite often (maybe half of the emails I send). Moreover, the interface feels sluggish and letters take some time to appear. Sometimes the email is sent the next time I start mailspring, but sometimes it is not even in the outbox (it remains as a draft).

More often than not, one of the CPU cores is always at 100% while mailspring is open. 

I have 3 gmail and 1 hotmail accounts configured in it.

**Comment by matthiasheuser** [comment] 2021-01-15 09:01
Still happening. I confirm: "currently sending" spinner keeps turning and turning infinitely.
What operating system are you using? Fedora 33
What version of Mailspring are you using? 1.7.8-13635bcf
No plugins, happens with Gmail
In parralel I have the issue [#156](https://github.com/Foundry376/Mailspring/issues/158). That might be linked?
I also had undo send enabled. I saw that Palefire19 suggested in bug #336 that it might be linked. Testing if it works now. 

ploum speculated: "Didn't find why it happens. Seems to happen mostly when the laptop lost the connection then get it back. Mailspring seems to not get it back."
He might be right.
Speculating myself: A connection error (in my case that happens after every sleep (laptop) since Wifi takes some time to reconnect) messes up the authentification process and thereby the sync and send functions (I continue to receive mal, though).

**Comment by CodeMouse92** [comment] 2021-01-17 03:52
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mail-getting-stuck-in-outbox/60/1

Please consider joining that community and continuing the discussion there! Bonus: if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

@matthiasheuser, I particularly migrated your comment above, as it's a recent and insightful confirmation of this bug.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-17 03:52 UTC
Labels: audit
