### ISSUE TITLE
Cant print any emails using any print driver

### ISSUE THREAD

**Issue by TeamKinetic** [Foundry376/Mailspring#1236] opened 2018-11-19 16:02 UTC
1.5.2 Windows 10

Opens the printer spool but doesnt send any bytes. Same for PDF printing or indeed any of the available printers. Pretty critical issue id say.

Previous issue closed for 1.4.2 but not reopened.

**Comment by bengotow** [comment] 2018-11-22 00:08
Hey! Thanks for reporting this—this is really odd... it looks like Electron has had a lot of trouble with printing in recent releases. I just looked through their recent changelogs and it says "Fixed printing related bugs on Windows. #15402" in the 3.0.7 release. I'm going to upgrade Mailspring to that version and see if we can get this fixed!

**Comment by mnylen** [comment] 2018-11-26 04:36
Likely related: https://github.com/Foundry376/Mailspring/issues/1027

**Comment by bengotow** [comment] 2018-12-30 00:59
Hey folks—thanks for reporting this. Mailspring 1.5.4 shipped earlier today and should address this issue. It turned out to be a combination of things - an Electron-level printing bug and also empty print jobs caused by Mailspring closing the window immediately after the print dialog was closed. In addition to fixing these, 1.5.4 adds a new "Save as PDF" option beside the "Print" option in the print window, making it easy to export emails as well. Enjoy!

**Closed by bengotow** 2018-12-30 00:59 UTC
Labels: done-pending-release, windows
