### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by ksdfg** [Foundry376/Mailspring#2222] opened 2020-12-09 20:16 UTC
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/43273771/101681692-8f5afc00-3a88-11eb-83a5-447d23e5d7cd.png)
The system-tray icon for mailspring is quite different to the ones from my icon theme, and this inconsistency is quite frustrating.

**Describe the solution you'd like**
I would like to be able to override the tray icons from a generalised location like `/usr/share/icons/hicolor/scalable/status` so I can properly employ my icon theme in the system-tray as well.

**Describe alternatives you've considered**
I have tried to unpack app.asar, change the icons and pack it again, but whenever I did this the repacked app.asar was ~5mb while the original is ~130mb. Whenever I tried running mailspring it would give `app not found` error.

**Comment by CodeMouse92** [comment] 2021-01-26 22:13
@Phylu All yours.

**Comment by CodeMouse92** [comment] 2021-02-09 23:28
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/allow-theme-override-of-system-tray-icon/537

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@ksdfg: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-09 23:28 UTC
Labels: audit, enhancement
