### ISSUE TITLE
Bug: Adding G Suite account results in auth loop

### ISSUE THREAD

**Issue by nedludd** [Foundry376/Mailspring#1829] opened 2020-02-28 16:28 UTC
Adding G Suite account results in auth loop

**To Reproduce**
1. Click "Add Account"
2. Click on 'Gmail or G Suite"
3. Go to the browser and select the account.  Accept the permissions.
4. Control goes back to Mailspring.  Get the popup "Sign into Google in your browser".
5. If you paste the suggested link, you get the same popup

**Screenshots**
![mailspring](https://user-images.githubusercontent.com/17875/75566237-57b12500-5a1d-11ea-9b62-10fd39b12368.png)

**Setup:**
 - OS: Arch Linux
 - OS Version: Latest
 - Mailspring Version: 1.7.4 via snap (also happened with 1.7.2 via pacman)

**Additional context** 
This is an older free G Suite account.
Nothing is logged.  Even in debug mode.

**Comment by nedludd** [comment] 2020-02-28 16:39
On MacOS with the same account I get the following:

<img width="627" alt="Mailspring" src="https://user-images.githubusercontent.com/17875/75567094-f2f6ca00-5a1e-11ea-9134-b3cf8f7a2999.png">

**Comment by petertriho** [comment] 2020-03-02 05:10
Have the same issue on macos with both gmail and gsuite accounts. Fetching emails seems to work fine but sending emails also comes up with the same error.


```
Using Mailcore Template: {
  "servers": {
    "imap": [
      {
        "port": 993,
        "hostname": "imap.gmail.com",
        "ssl": true
      }
    ],
    "smtp": [
      {
        "port": 587,
        "hostname": "smtp.gmail.com",
        "starttls": true
      },
      {
        "port": 465,
        "hostname": "smtp.gmail.com",
        "ssl": true
      },
      {
        "port": 25,
        "hostname": "smtp.gmail.com",
        "starttls": true
      }
    ]
  },
  "mx-match": [
    "aspmx2\\.googlemail\\.com",
    "aspmx\\.l\\.google\\.com",
    "aspmx3\\.googlemail\\.com",
    "alt1\\.aspmx\\.l\\.google\\.com",
    "alt2\\.aspmx\\.l\\.google\\.com",
    "alt1\\.gmail-smtp-in\\.l\\.google\\.com",
    "alt2\\.gmail-smtp-in\\.l\\.google\\.com",
    "alt3\\.gmail-smtp-in\\.l\\.google\\.com",
    "alt4\\.gmail-smtp-in\\.l\\.google\\.com",
    "gmail-smtp-in\\.l\\.google\\.com"
  ],
  "domain-match": [
    "googlemail\\.com",
    "gmail\\.com"
  ],
  "mailboxes": {
    "sentmail": "[Gmail]/Sent Mail",
    "allmail": "[Gmail]/All Mail",
    "starred": "[Gmail]/Starred",
    "trash": "[Gmail]/Trash",
    "drafts": "[Gmail]/Drafts",
    "spam": "[Gmail]/Spam",
    "important": "[Gmail]/Important"
  }
}
/Applications/Mailspring.app/Contents/Resources/app.asar/src/error-logger.js:101 Error: Connection Error - Unable to connect to the server / port you provided. (SMTP)
    at ChildProcess._proc.on.code (mailsync-process.ts:221)
    at ChildProcess.emit (events.js:182)
    at ChildProcess.EventEmitter.emit (domain.js:442)
    at maybeClose (internal/child_process.js:962)
    at Socket.stream.socket.on (internal/child_process.js:381)
    at Socket.emit (events.js:182)
    at Socket.EventEmitter.emit (domain.js:442)
    at Pipe._handle.close (net.js:606) Object
```

**Comment by nedludd** [comment] 2020-03-03 14:01
I don't think that's the same thing.  I don't even get logs just a loop to the auth stuff.

**Comment by nedludd** [comment] 2020-03-03 14:05
Ran it like this:

```
mailspring --dev --log-file /tmp/mailspring.log
```
That file is not even created.  Even when I don't try to add an account.

**Comment by petertriho** [comment] 2020-03-05 00:18
Nevermind, looks like it was a network issue for me. Switched to another network and it is working fine now.

**Comment by CodeMouse92** [comment] 2021-02-01 21:09
Thank you for reporting this. 2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/cannot-connect-to-gmail-from-behind-vpn/421

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-01 21:09 UTC
Labels: audit, bug
