### ISSUE TITLE
How do i get the tray icon to show new mail on KDE ?

### ISSUE THREAD

**Issue by JackDinn** [Foundry376/Mailspring#1042] opened 2018-08-24 10:01 UTC
iv installed mailspring but there is no tray indication. There is a tray icon but it does not change or mark when i have unread mail... but i do get sound and **sometimes** a pop-up notifier but thats about it. I do have zenity installed and i have python2-libappindicator installed (i could not find libappindicator1 )

![screenshot_20180824_105256](https://user-images.githubusercontent.com/5557560/44578689-2e5e6b80-a78c-11e8-8405-7356eeefb107.png)

Kernel: 4.18.3-1-MANJARO x86_64 bits: 64 compiler: gcc v: 8.2.0 
Desktop: KDE Plasma 5.13.4 Distro: Manjaro Linux

**Comment by JackDinn** [comment] 2018-08-24 15:11
I have since found out that it only works if MS is minimized and not closed to tray and that the blue dot is so small i can not see it without using Kmag and also i get the blue dot appear on every sync regardless of if i have new mail or not.

**Comment by varlesh** [comment] 2018-11-25 02:53
I confirm this, new mail notification tray icon show only if Mailspring minimized.
- Mailspring 1.5.2
- KDE Neon (Ubuntu 18.04)
- Plasma 5.14.3

@JackDinn For better rendering try run program with Unity Environment option:
`XDG_CURRENT_DESKTOP=Unity mailspring`

**Comment by JoshKisb** [comment] 2018-12-26 21:03
Yes facing same issue on Kubuntu 18.04 
I would prefer to close MS and let the tray icon notify whenever a new message arrives

**Comment by vanushwashere** [comment] 2019-05-02 14:15
Yeah, same issue on latest KDE Neon,
Icon in notification area gets blueish only when Mailspring window is open or minimised

**Comment by allopislozano** [comment] 2019-08-20 15:43
For me I don't even see a correct icon, just a generic question mark and the correct MS icon is not shown

**Comment by doman18** [comment] 2020-04-28 09:13
I confirm this as well and want to add that other electron app with notifications (Franz) works fine all the way. When you minimize window, close it (but not app entirely)  or is opened in foreground or background - it always shows red dot on tray icon when something new comes.
Mailspring only works when its minimized. When it is closed or opened then tray icon does not change the color to blue

Mailspring 1.7.6
Kubuptu 18.04
KDE Plasma: 5.12.9
KDE Framworks: 5.44.0
Qt: 5.9.5

**Comment by kamiszczu** [comment] 2020-11-28 00:11
I confirm, same issue on latest KDE Neon.
Additionally icon is not in style kde.

![image](https://user-images.githubusercontent.com/5055672/100489750-92fc9380-3116-11eb-9145-cbebbcd6f3b1.png)

**Comment by CodeMouse92** [comment] 2021-02-18 22:46
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/badge-doesnt-always-appear-on-app-indicator-when-receiving-new-mail/392

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-18 22:46 UTC
Labels: audit, linux
