### ISSUE TITLE
[Feature Request] temporary disable/enable an account

### ISSUE THREAD

**Issue by mhadidg** [Foundry376/Mailspring#1739] opened 2019-12-13 09:34 UTC
Sometimes our private company mail server goes down during maintenance for a day or maybe days. At that unfortunate time, Mailspring attempts repeatedly to connect to a mail server that will never be available!

Well, I have two problems with this:
- the error message that came out when I open the app is absolutely annoying; and
- the background job that attempts to connect is a pointless waste of resources.

To stop the error messages from showing up, I have to delete the account and reconnect it later. It would be much easier If I have the **option to disable the account** through Preferences -> Accounts tab.

**Comment by CodeMouse92** [comment] 2021-02-03 17:29
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/temporary-disable-enable-account/442

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@mhadidg: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-03 17:29 UTC
Labels: enhancement, migrated
