### ISSUE TITLE
Bug: Signature is not added in plain text drafts

### ISSUE THREAD

**Issue by aigoncharov** [Foundry376/Mailspring#1904] opened 2020-04-15 18:56 UTC
**Describe the bug**
Signature is not added automatically if I create a new email or reply. If switch accounts back and forth, it is added.

**To Reproduce**
1. Create at least two accounts
2. Create a signature for both of them
3. Compose a new email
4. There's no signature
5. Switch from account A to account B
6. Switch back
7. Signature appears as plain HTML. Moreover, it's not complete

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/12794628/79376998-b269f600-7f63-11ea-8190-062d6e95ddeb.png)

**Setup: (please complete the following information):**
 - OS: Ubuntu
 - OS Version: 19.10
 - Mailspring Version: 1.7.5-94c69708

**Comment by bengotow** [comment] 2020-04-16 05:19
Hey @aigoncharov — thanks for reporting this! It looks like you're using the new plaintext composer that was shipped in 1.7.4. We're still working on signature support in plaintext mode (and actually it shouldn't be inserting those HTML fragments either), and I'll see if we can get this into 1.7.6!

**Comment by aigoncharov** [comment] 2020-04-16 06:18
Hi @bengotow ! Is there a way to switch back to the HTML composer? The plain text one opens for me by default.

**Comment by dubst3pp4** [comment] 2020-06-04 14:48
@bengotow Any news on signature support in plain text mails? This is the missing feature that keeps me away from using this great mail client...

**Comment by CodeMouse92** [comment] 2021-02-27 02:57
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/plain-text-mode-signatures/751

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-27 02:57 UTC
Labels: audit, bug, product-direction
