### ISSUE TITLE
Mouse back/forward buttons do nothing

### ISSUE THREAD

**Issue by Raytar** [Foundry376/Mailspring#210] opened 2017-10-19 19:13 UTC
The back / forward buttons on my mouse do nothing as far as I can tell. For example, when viewing an email and clicking on the back button on my mouse, I would expect to be taken back to the inbox. Instead, nothing happens.

##### What operating system are you using?
Ubuntu 17.10

##### What version of Mailspring are you using?
1.0.5

##### Do you have any third-party plugins installed? If so, which ones?
No.

**Comment by bengotow** [comment] 2017-10-20 06:46
Hmm can you open the Developer Tools in Mailspring (from the Developer menu), go to the console and type `document.addEventListener('keyup', (e) => console.log(e.keyCode))`? Then switch focus back to the Mailspring window and hit the back / forward buttons on the keyboard and let me know what keycodes are in the console.

You can probably map the back/forward "key press" events from your mouse in the keyboard shortcuts panel in Preferences > Keymaps (click a mapping to change it) but I'm curious to know if we can add them by default.

**Comment by Raytar** [comment] 2017-10-20 16:56
Not sure what you mean about the keyboard, but I did some looking around and it seems that electron doesn't recognize the forward/back buttons on linux. (see [electron#6996](https://github.com/electron/electron/issues/6996)). However, also found a module that can be used instead: [mouse-forward-back](https://github.com/jostrander/mouse-forward-back)

**Comment by kvnxiao** [comment] 2017-10-28 06:00
I'm getting the same behaviour. However, with `document.addEventListener('keyup', (e) => console.log(e.keyCode))`, I am getting key codes `18` and `37` when pressing the back button on my mouse for example (equivalent to `ALT` + `Left Arrow`) but it does nothing. Where can I add custom key mappings for back and forth panel navigation? There doesn't seem to exist an option in `Preferences -> Keymaps` for this...

**Comment by jGleitz** [comment] 2017-10-28 10:14
<kbd>Alt</kbd>+<kbd>→</kbd> and <kbd>Alt</kbd>+<kbd>←</kbd> are very common keyboard shortcuts, supported by Chrome, Firefox and a lot of file browsers. So can we consider adding them to the default keymap?

**Comment by CodeMouse92** [comment] 2021-02-24 18:36
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mouse-back-forward-buttons/761

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@Raytar @kvnxiao @jGleitz: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-24 18:36 UTC
Labels: audit, enhancement, good first issue, needs-reproduction
