### ISSUE TITLE
Email list view stuck on loading animation - Release 1.7.0

### ISSUE THREAD

**Issue by karpawich** [Foundry376/Mailspring#1659] opened 2019-10-14 17:08 UTC
**TEMPORARY FIX:** Click "Drafts" on the Sidebar, and then click back to inbox or another conversations view

---

After updating to Release 1.7.0, the email list view on Mailspring can get stuck on the loading animation:

![Screenshot (11)](https://user-images.githubusercontent.com/34974152/66769400-0d227800-ee83-11e9-958a-f192b73e0efc.png)

**What operating system are you using?**

Windows 10

**What version of Mailspring are you using?**

1.7.0

**Comment by Lyptik** [comment] 2019-10-14 17:13
Hello There,
Same, whenever I click I have the same problem after the last update (win10 as well). I don't have any mail that I can access.

It's stuck right away when starting the software

**Comment by karpawich** [comment] 2019-10-14 17:14
@Lyptik Have you tried the temporary fix listed at the top of the Issue? That should resolve it.

**Comment by lecooliver** [comment] 2019-10-14 17:14
+1

**Comment by adefee** [comment] 2019-10-14 17:15
Happens to me across all email accounts and panes - can't access anything (Inbox, Sent, etc). Also Win10 and latest (v1.70-65435390). @karpawich temp workaround also seems to work, but have to do it everytime I want to check for new mail/see new messages.

**Comment by josiasmat** [comment] 2019-10-14 17:22
Happening to me too.

**Comment by kevinphys** [comment] 2019-10-14 17:35
+1

**Comment by herreraemanuel** [comment] 2019-10-14 17:41
Hi.
Same issue here.
Even with my microsoft account

**Comment by GamerMedic** [comment] 2019-10-14 17:46
I'm also having the same issue. The temporary fix works but it's very inconvenient.

**Comment by chung5829** [comment] 2019-10-14 17:52
Having issues with all my 4 gmail accounts. Fix it!!!

**Comment by RemyyB** [comment] 2019-10-14 18:14
Same issue for all my accounts (even SMTP accounts) :(

**Comment by RemyyB** [comment] 2019-10-14 18:15
`Tasks must have an accountId. Check your instance of ChangeStarredTask.
    at MailsyncBridge._onQueueTask (mailsync-bridge.ts:351)
    at EventEmitter.eventHandler (C:\Users\remyb\AppData\Local\Mailspring\app-1.7.0\resources\app.asar\node_modules\reflux\src\PublisherMethods.js:36)
    at EventEmitter.emit (C:\Users\remyb\AppData\Local\Mailspring\app-1.7.0\resources\app.asar\node_modules\eventemitter3\index.js:93)
    at Function.trigger (C:\Users\remyb\AppData\Local\Mailspring\app-1.7.0\resources\app.asar\node_modules\reflux\src\PublisherMethods.js:52)
    at Object.functor [as queueTask] (C:\Users\remyb\AppData\Local\Mailspring\app-1.7.0\resources\app.asar\node_modules\reflux\src\createAction.js:32)
    at click (thread-list-context-menu.ts:238)
    at CallbacksRegistry.apply (C:\Users\remyb\AppData\Local\Mailspring\app-1.7.0\resources\electron.asar\renderer\callbacks-registry.js:47)
    at handleMessage (C:\Users\remyb\AppData\Local\Mailspring\app-1.7.0\resources\electron.asar\renderer\api\remote.js:285)
    at EventEmitter.ipcRenderer.on.args (C:\Users\remyb\AppData\Local\Mailspring\app-1.7.0\resources\electron.asar\renderer\api\remote.js:275)
    at EventEmitter.emit (events.js:182)
    at EventEmitter.emit (domain.js:442)
    at EventEmitter.topLevelDomainCallback (domain.js:121) Object`

**Comment by wayoutware** [comment] 2019-10-14 18:24
happening to me on windows 10, too
![image](https://user-images.githubusercontent.com/48106340/66773944-e4e84880-ee85-11e9-8749-bf8102fff38e.png)

**Comment by RemyyB** [comment] 2019-10-14 18:27
> happening to me on windows 10, too
> ![image](https://user-images.githubusercontent.com/48106340/66773944-e4e84880-ee85-11e9-8749-bf8102fff38e.png)


Sorry for offtopic but what's that theme? :)

**Comment by Lyptik** [comment] 2019-10-14 18:32
I confirm that the temporary fix works on my setup

**Comment by lvtz** [comment] 2019-10-14 19:04
+1 same issue here... temporary fix also works for me, win 10, mailspring ver 1.7.0

**Comment by bengotow** [comment] 2019-10-14 20:00
Hey folks! just want to thank everyone for filing this - it looks like this is a timing issue in Mailspring's JavaScript that only happens on Windows, which is really surprising and allowed it to skip through the release testing. (At this time I've been able to reproduce it and the fix is in 9c763dac, but I still haven't gotten it to happen on Mac or Linux). I'm planning to ship the fixes for this and #1660 in a patch today because this is a fairly critical bug. Stay tuned!

**Comment by bengotow** [comment] 2019-10-14 20:43
Hey folks—just a heads up that the fix for this has shipped in 1.7.1. Decided to push it out along with the fix for #1660 because there have been quite a few reports of this happening via Twitter and our support channel. 

The app should auto-update in an hour or two, or you can choose "Check for Updates" from the menu or visit https://github.com/Foundry376/Mailspring/releases/tag/1.7.1 to get it now. Thanks - sorry for the hassle on this one!

**Closed** 2019-10-15 16:26 UTC
Labels: bug, done-pending-release
