### ISSUE TITLE
Mailspring's trash has items that aren't in Gmail's trash and that I never deleted

### ISSUE THREAD

**Issue by palefire19** [Foundry376/Mailspring#224] opened 2017-10-21 06:34 UTC
##### Are there any related issues?

...

##### What operating system are you using?
Mac OS 10.12.6

##### What version of Mailspring are you using?
1.0.6

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail

##### Is the issue reproducible with a particular attachment, message, signature, etc?

Mailspring's trash has many more items than the trash folder on Gmail, including numerous items that I definitely never deleted.

--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?
...

**Comment by bengotow** [comment] 2017-10-21 07:17
Hmm you've also been having issues with the badge counter right and duplicate copies of messages in the inbox right? Something is definitely up with your account, but it might be hard to reproduce this. We may need to wait for more reports first.

**Comment by palefire19** [comment] 2017-10-21 07:30
One hypothesis is that I generally have pretty slow internet - I live in East Africa. I've noticed that Mailspring's sync issues seem to pop up more frequently when my internet is particularly bad. Just a guess though.

**Comment by rafrsr** [comment] 2017-10-21 14:07
I guess this may be related to #220, I have the same issue with emails that I have never deleted and persist in trash even if I empty it.  My Internet connection is not the best either.

**Comment by pepgubau** [comment] 2019-07-25 06:32
It happens all the time. Trash on Mailspring shows emails that were never deleted and are not in the Trash folder / Label in Gmail. Only option is to clear cache and resync.

Version 1.5.6 (July 2019) - On Mac - Gmail account

**Comment by CodeMouse92** [comment] 2021-01-30 01:12
Hi all,

2020 prevented much development work on Mailspring, but rest assured, development has resumed! We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

@pepgubau (or someone else): Can you please confirm that this is still broken with 1.8.0, and if so, open a new Bug Report on our [Discourse](https://community.getmailspring.com)? We want to be able to address this, but we need up-to-date diagnostic information to do it. You're welcome to include a link back to this issue for more context.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-30 01:12 UTC
Labels: audit, needs-reproduction
