### ISSUE TITLE
Feature Request Mail Rules on Read

### ISSUE THREAD

**Issue by joaomaridalho** [Foundry376/Mailspring#977] opened 2018-07-13 14:13 UTC
Hey,

Can you add the ability to apply a mail rule only when a message is read?

Best Regards,
João Maridalho

**Comment by Bugsbane** [comment] 2019-03-26 02:49
I would love the option to have emails be deleted if not starred, or archived if they are starred once an email is read.

The one caveat is that I wouldn't want it to happen until I navigated away from the specific email. Obviously having an email that you're in the middle of reading, be deleted and disappear as you're reading it would not be a good user experience.

So yes, a rule condition that said "When read" would be awesome, as long as it only processed after navigating away from emails.

**Comment by CodeMouse92** [comment] 2021-02-11 22:25
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mail-rules-on-read/574

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@Bugsbane: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-11 22:25 UTC
Labels: audit
