### ISSUE TITLE
Empty emails

### ISSUE THREAD

**Issue by murakami-marco** [Foundry376/Mailspring#1112] opened 2018-10-05 16:09 UTC
##### Are there any related issues?
Not found

##### What operating system are you using?
KDE Neon 18.04 - Plasma 5.13.5
...

##### What version of Mailspring are you using?
1.4.2
...

--

**Bug?**

Mailspring shows emtpy received emails despite they are not. I'm been using Mailspring like for 2 years, more o less, and this issue was present since then but it seems it's only on plain text emails.

![image](https://user-images.githubusercontent.com/823462/46545102-01bd6980-c88b-11e8-9917-30aab7c23215.png)

![screenshot_20181005_105534](https://user-images.githubusercontent.com/823462/46546379-780f9b00-c88e-11e8-9724-75226fca40e4.png)
...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
I'm using Gmail but i don't know if this issue is presente with other provider
...

**Comment by CodeMouse92** [comment] 2021-02-03 18:28
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/many-emails-appear-white-empty/426

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-03 18:28 UTC
Labels: audit
