### ISSUE TITLE
Bug: mailsync freezes under some proxy.

### ISSUE THREAD

**Issue by Ushio-Cheng** [Foundry376/Mailspring#2249] opened 2021-01-05 22:23 UTC
**Describe the bug**
When this problem appears, mailspring client gives "One or more accounts are having Connection Issues" and refuse to refresh.
When try to Re-Auth since a lot of connection issue can be solved by Re-Auth, it gives an error "mailsync: null".
mailsync would have only one active connection, while I have 5 email account.
At this point, restarting MailSpring client or even killall mailsync would not help.

**To Reproduce**
I have configured my network as following:
I am using surge 4 on MacOS and are using proxies.
I have multiple proxy nodes (most are provided by a company and thus shared) and are setup as Load Balance Group in Surge.
After running for about 1-2 days, MailSpring client would not refresh. This have happen to be >5 times so there is a problem.

**Setup**
 - MacOS Cataline
 - 10.15.7 build 19H2
 - Mailspring 1.7.8 installed from homebrew cask

**Current workaround** 
- Turn off wifi to force mailsync connection to fail and then it somehow would work.
- I have setup some rules to let mailsync use a single proxy node that I own (i.e. <5 users) instead of load balanced group, this seems to solve the problem. My rationale is that some proxy node maybe messing with SOCKS connection, perhaps due to port assignment.

**If no bugs can be found in code**
Please at least provide a easy way to forcefully restart mailsync, even though command line.

**Comment by CodeMouse92** [comment] 2021-01-18 23:27
Thank you for reporting this!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mailsync-freezes-under-some-proxy/90

Please consider joining that community and continuing the discussion there! Bonus: if you join and reply to the issue, the moderators can make an effort to reassign the post to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-18 23:27 UTC
Labels: audit, bug
