### ISSUE TITLE
Disabling or fixing "not addressed to recipient warning"

### ISSUE THREAD

**Issue by gottlike** [Foundry376/Mailspring#381] opened 2017-11-30 12:07 UTC
##### Are there any related issues?
Nope

##### What operating system are you using?
Mac OS

##### What version of Mailspring are you using?
1.0.8

**Feature Request**
##### Does this feature exist in another mail client or tool you use?
Kind of, yes.

--

Mailspring keeps asking me if I really want to address the person as "XYZ", because her mail name is different. Obviously for some people you don't use their name, but their nickname. This is pretty annoying after a while. Either Mailspring should remember this as a valid name or I should be able to disable this feature in the settings.

Related spec: https://github.com/Foundry376/Mailspring/blob/7e81c3154e70f0b4336f7184031a7a0068151ad0/app/internal_packages/composer/specs/composer-view-spec.cjsx#L219

**Comment by we3geeks** [comment] 2017-11-30 12:46
+1

I have seen similar behavior if I forward an email that contains "Dear so-and-so" to someone with an email address that doesn't look like it would belong to someone named "so-and-so". For example, if I get an email from a local sports organization with the body of the message starting "Dear Parents" and I forward that message to someone else with a name-based email (e.g., john.doe@gmail.com).

**Comment by bengotow** [comment] 2017-12-02 06:16
Hey! I've actually had some problems with this feature as well. When I email folks via Zendesk, the email is addressed to Zendesk but I still want to reference the recipient by name. It /has/ saved me a couple times when copy-pasting the same response to people though.

I'm not sure how best to improve on the logic here. The existing logic is in `validateDraftForSending`: https://github.com/Foundry376/Mailspring/blame/master/app/src/flux/stores/draft-editing-session.es6#L213. Will see if we can collect a few more use cases - it might just need to be removed if we can't make it work more often.

**Comment by we3geeks** [comment] 2017-12-02 14:20
I do like the intent of the feature and I don't bump into it very often. Part of what confused me initially was simply how terse the warning itself was -- it wasn't obvious to me what it was complaining about (which is why this issue got my eye). So, perhaps a slightly more verbose warning would have helped my initial confusion? 

That said, I think mine is a slightly different use case (forwarding vs sending or replying), and I think it is further narrowed to the case when I forward a message and don't put something ahead of the salutation in the original message? In that context, it seems quite likely that the contact(s) to whom I am forwarding the message will be different than the salutation in original.

@bengotow I agree with the "collect more use cases" approach at this point.

**Comment by sdyson** [comment] 2018-01-04 09:56
This fix does not seem to have fixed the problem originally reported relating to nicknames. For example, I just emailed someone named 'Daniel' and I got a warning because I addressed them as 'Dan'. I appreciate the warning the first time, but to have to confirm this every time is quite annoying.

**Comment by antbowling** [comment] 2018-01-21 11:54
+1 for not being clear enough, the warning I received reads as follows:

"Send addressed to a name that doesn't appear to be a recipient ("leo")?"

The wording here made me think it was an issue with the To: email address. The error could've done with saying 'You started your email with the line: "Hi Leo", but it doesn't look like you're sending to anyone called "Leo".'

The warning also printed "leo" in lowercase even though I typed "Leo", which led to further confusion.

Nice feature though (which I don't think was in Nylas?) for preventing accidental sends

**Comment by escursionista** [comment] 2018-07-30 13:13
+1 Send addressed to a name that doesn't appear to be a recipient ("mr")? 
When answering to an email to Dear Mr. X

**Comment by alpha-beta-soup** [comment] 2019-03-05 01:45
I seem to get this warning for everyone in my organisation, since our emails are `{lastname}{firstinitial}@{domain}`, yet I address them by their actual name when I compose a message. Mailspring is however able to display their actual name in the profile panel, which matches what I use in the body of the email. Would be nice to disable this or at least improve the match to consider any accessible profile information rather than just the email address string itself (which very often isn't a name you use in interpersonal communication).

**Comment by blancmatter** [comment] 2020-01-21 16:51
+1 This check should be an optional feature that can be turned disabled. Its annoying.

**Comment by CodeMouse92** [comment] 2021-01-29 23:43
Causally looking through the code, I think this feature was removed, so I'm closing this issue. If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-29 23:43 UTC
Labels: audit, product-direction
