### ISSUE TITLE
Can we have an option to mark all messages in the account till now as historical thus skip scanning of them?

### ISSUE THREAD

**Issue by complyue** [Foundry376/Mailspring#2182] opened 2020-10-26 05:41 UTC
**Is your feature request related to a problem? Please describe.**

It has been weeks, but seems it's faithless for Mailspring to finish scanning my icloud.com account's mail boxes. I'd been leaving the main window open over nights, but no obvious progress at all.

There're tens of thousands of historic messages there, and obviously Apple can be throttling the connection.

**Describe the solution you'd like**

I just want an option from the client menu or somewhere, to tell Mailspring to skip scanning all those historic messages, and only process whatsoever come from then on.

**Describe alternatives you've considered**

I thought mark all my mails as archived may help it, but I don't want to do so unless absolutely necessary.

**Additional context**

No

**Comment by CodeMouse92** [comment] 2021-03-03 03:33
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/can-we-have-an-option-to-mark-all-messages-in-the-account-till-now-as-historical-thus-skip-scanning-of-them/963

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@complyue: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-03 03:33 UTC
Labels: audit, enhancement
