### ISSUE TITLE
Button and other UI images broken.

### ISSUE THREAD

**Issue by hughstimson** [Foundry376/Mailspring#1366] opened 2019-02-12 17:24 UTC
I installed the latest version for Windows 10 x64.

All (or almost all) icons in the buttons and other UI are missing.

The only exception seems to be the "quick reply" "translate" and "disable tracking" icons in the mail compose window.

Screenshot:

![missing_buttons](https://user-images.githubusercontent.com/518248/52654924-e7824080-2ea7-11e9-8315-e6bab45b2a7f.png)

##### Are there any related issues?

No related issues found.

##### What operating system are you using?

Windows 10.

##### What version of Mailspring are you using?

Latest installer (can't easily check version because settings button image is missing).

##### Is this an email sync or connection issue?

No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

No.

**Comment by bengotow** [comment] 2019-03-29 22:09
Hey! This is suuuuper odd. Thanks for reporting this. I'm going to see if we can find any other reports that will help narrow this down.

**Comment by hughstimson** [comment] 2019-03-29 22:30
OK. FYI I tried installing a slightly more recent version on an entirely different machine, also Windows 10, with the same result.

Could it be remote image resources getting blocked by our firewall, or something like that? I haven't seen that behaviour in any other application/website/etc tho.

**Comment by NaungYeOo** [comment] 2019-11-14 07:51
I'm in the same issue. Is there any solution for this case?

**Comment by hughstimson** [comment] 2019-11-14 18:01
I've noticed that I have display issues with several Electron-based apps. 

Some work fine: GitHub Desktop, Visual Studio Code, Slack. 

Some display completely blank: Microsoft Teams, Signal, Keybase, Wavebox. 

And a couple of them display but with a few missing UI elements: Mailspring, Station. 

@NaungYeOo have you tried running any of the above apps? Do you have the same issues with them? Or is it specific to Mailspring for you?

**Comment by hughstimson** [comment] 2019-12-02 22:46
It looks like this was caused by the presence of a # symbol in my username. Mailspring (and other Electron based apps) stores program files in the user AppData directory. I guess the application can't access some of those files when there's a special character in the file path.

It doesn't mess up all Electron apps, just some. Maybe there's a fix that can be implemented in Mailspring?

As a workaround I had to switch to a new profile name.

**Comment by bengotow** [comment] 2020-04-17 05:21
Turns out this is very easily reproduced, even on macOS by doing this:
<img width="223" alt="image" src="https://user-images.githubusercontent.com/1037212/79534859-62f9f780-8041-11ea-8924-c3a6b9ad05f5.png">

**Comment by bengotow** [comment] 2020-04-22 22:13
Hey folks, thanks for reporting this. Happy to say this has been resolved in 1.7.6 which shipped this afternoon. 🚀  The app should auto-update, but if it doesn't you can also grab the new release from GitHub's Releases tab or from https://getmailspring.com/download. Thanks for your patience and help tracking this down, enjoy the update!

**Closed by bengotow** 2020-04-22 22:13 UTC
Labels: done-pending-release
