### ISSUE TITLE
During sending Emails the attached files are EMPTY

### ISSUE THREAD

**Issue by donmoskeyra** [Foundry376/Mailspring#370] opened 2017-11-27 16:44 UTC
##### Are there any related issues?
No.

##### What operating system are you using?
Windows 10

##### What version of Mailspring are you using?
1.0.8

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
No.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No.

##### Is the issue reproducible with a particular attachment, message, signature, etc?
Mailspring has an issue some cases when sending attached files, the emails goes with attached file EMPTY.

![mailspring-attached-issue](https://user-images.githubusercontent.com/24660356/33277489-d798c98e-d37f-11e7-93fc-199be8bcfb24.png)

**Comment by bengotow** [comment] 2017-11-28 23:11
Hey! Thanks for reporting this - I haven't been able to reproduce this one yet. Can you check your email on the web or on mobile and see if the attachment is really missing? I think this could be a display bug.

**Comment by bengotow** [comment] 2017-12-12 03:34
Hey! I've been able to fix this. Looks like it happens when the title of the file contains characters that are not safe on old versions of Windows (they work fine on Windows 7 forward, but Mailspring is still mangling the file data.) Will ship the fix in the next release—

**Comment by bengotow** [comment] 2017-12-18 23:16
Hey folks - this has shipped in 1.0.11. The app will download the update automatically, but you can get it directly here: https://www.getmailspring.com/download. Gonna go ahead and close this—if you continue to have trouble after the update, let me know and I'll re-open it!

**Closed by bengotow** 2017-12-18 23:16 UTC
Labels: done-pending-release, needs-reproduction

**Comment by donmoskeyra** [comment] 2017-12-19 15:54
Thanks @bengotow!
