### ISSUE TITLE
Empty Archive in gmail account

### ISSUE THREAD

**Issue by eliocamp** [Foundry376/Mailspring#1255] opened 2018-12-03 13:53 UTC
##### Are there any related issues?

Not that I've found.

...

##### What operating system are you using?

elementary OS 5 (Ubuntu 18.04) and elementary OS 0.4.1 (Ubuntu 16.04)

...

##### What version of Mailspring are you using?

1.5.3-420ce003 (but also present on previous verions)

...

--

**Bug?**

Mailspring shows the "No message" icon on my gmail archive even though there are lot's of messages. I've tried rebuilding the cache, but no luck. 

[mailsync-925a928c.log](https://github.com/Foundry376/Mailspring/files/2639652/mailsync-925a928c.log)

[mailsync-e2935a22.log](https://github.com/Foundry376/Mailspring/files/2639653/mailsync-e2935a22.log)

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

gmail

...

**Comment by stouf** [comment] 2019-08-06 00:57
I am experimenting the same issue. Some details I could add in my case: I have three GMail accounts configured in Mailspring and out of the three only one of them is affected by this. The only difference I can see between the three accounts is that the affected one has its language set to Japanese whereas the two others have their language set to English. As a consequence, for the two English accounts, all the emails are archived into a `All mail` label whereas it's a `すべてのメール` ("All mail" in Japanese) label for the Japanese account. I don't know if it matters.
Another thing I noticed: if I click on the unified `Archive` folder in Mailspring, I can see archived emails from the three accounts, including the Japanese account.

@eliocamp Are there similarities with the above on your side?

**Comment by eliocamp** [comment] 2019-08-06 02:53
Not really. My gmail is in regular ol' english. :man_shrugging:

**Comment by stouf** [comment] 2019-08-06 03:51
Hmm, nevermind then 😅

**Comment by CodeMouse92** [comment] 2021-02-18 23:19
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/disappearing-emails-desync/428

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-18 23:19 UTC
Labels: audit
