### ISSUE TITLE
[Bug] Any open compose windows close when another email sent

### ISSUE THREAD

**Issue by faasie** [Foundry376/Mailspring#351] opened 2017-11-17 19:57 UTC
##### Are there any related issues?

Not that I can find.

##### What operating system are you using?
OpenSUSE Linux 

##### What version of Mailspring are you using?
1.0.8

--

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
None.

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No.

##### Is the issue reproducible with a particular attachment, message, signature, etc?

1. Compose a message and send.
2. Immediately open another compose window and start typing (or not)
3. When 5 second "Undo Send" goes by, opened compose window will automatically close
4. Closed message is available in Drafts so all is not lost.

*shrug* It's more annoying than earth shattering. 👍

**Comment by palefire19** [comment] 2017-11-18 06:42
+1 on MacOS

**Comment by bengotow** [comment] 2017-11-25 20:39
Whoa this is a good one! I've been able to reproduce on my end and I'll see if we can get it fixed.

**Comment by palefire19** [comment] 2017-11-27 12:58
@bengotow Another related one - although I'm having a hard time consistently reproducing it. When I send an email, sometimes the top-most email in my inbox (if it is unread) will get archived. Seems sort of similar.

**Comment by bengotow** [comment] 2017-11-28 23:10
Hey! This should be fixed in the next release - turns out we were "processing" the undo-send action in both windows. Good catch!

**Comment by faasie** [comment] 2017-11-29 13:26
Thanks, @bengotow. Appreciate all the work and Mailspring is getting better and better!

**Comment by bengotow** [comment] 2017-12-02 06:49
This has shipped in 1.0.9. Cheers!

**Closed by bengotow** 2017-12-02 06:49 UTC
Labels: bug, done-pending-release
