### ISSUE TITLE
Email count not showing up on the badge

### ISSUE THREAD

**Issue by anshuman73** [Foundry376/Mailspring#892] opened 2018-05-25 09:14 UTC
##### Are there any related issues?

...

##### What operating system are you using?

Ubuntu 18.04

##### What version of Mailspring are you using?

Version 1.2.1-7e7447b6
--

**Bug**

No email count shows up in the icon/badge. I have "show Total count" selected and zenity installed, yet no count shows up on the badge.

##### Do you have any third-party plugins installed? If so, which ones?
Yes, I'm using the gnome extension "Dash to Panel" (https://extensions.gnome.org/extension/1160/dash-to-panel/)

**Comment by domenico-ruggiano** [comment] 2018-08-29 11:42
I'm having this issue too, Mailspring version 1.4.2, Ubuntu 18.04

**Comment by CodeMouse92** [comment] 2021-02-13 00:37
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/icon-badge-on-ubuntu/186

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-13 00:37 UTC
Labels: audit
