### ISSUE TITLE
Enhancement: Special case sender information sidebar for mailing list services

### ISSUE THREAD

**Issue by heliostatic** [Foundry376/Mailspring#1588] opened 2019-07-23 11:22 UTC
##### What operating system are you using?

macOS 10.14.5

##### What version of Mailspring are you using?

1.6.3

--

**Feature Request?**

In the "Sender Information" sidebar, it would be nice to special case mailing list services like Substack -- currently, the company info is about Substack, but it could be about the mailing list sender themself (although obviously not easy to get from Clearbit/etc).

<img width="267" alt="Screen Shot 2019-07-23 at 7 16 14 AM" src="https://user-images.githubusercontent.com/70898/61708443-ce18d680-ad1a-11e9-9c9e-255ba5eb5c2a.png">

**Comment by bengotow** [comment] 2019-10-22 05:26
Hey! Ahh that's a really cool idea - I think that we could probably parse some of the standard mailing list header formats and pull out the actual sender.

**Comment by CodeMouse92** [comment] 2021-02-26 17:09
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/special-case-sender-information-sidebar-for-mailing-list-services/826

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-26 17:09 UTC
Labels: audit, enhancement
