### ISSUE TITLE
Mailspring creates many copies of a draft when editing a draft in Google Inbox or Gmail. 

### ISSUE THREAD

**Issue by punshs** [Foundry376/Mailspring#579] opened 2018-01-26 04:06 UTC
##### Are there any related issues?

Not that I can see.

##### What operating system are you using?
Ubuntu 17.10
Gnome-Shell

##### What version of Mailspring are you using?
1.1.0-7563b09d
non-snap version

**Bug?**
Anytime I receive an email and open a draft in Mailspring and then proceed to edit that draft in Google Inbox or Gmail, Mailspring starts to generate many separate draft copies of the email being composed in Gmail or Inbox. Each draft seems to be a snapshot the draft in Gmail or Inbox at various stages. It can generate nearly a hundred drafts for long emails.

##### Do you have any third-party plugins installed? If so, which ones?
None

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
Gmail and Google Inbox

**Comment by bengotow** [comment] 2018-01-29 16:08
Hey! Thanks for reporting this — this is definitely a bug. IMAP is really gross and there's actually no way to "update" a draft, so it needs to delete and re-create the draft with different text. It sounds like the "delete" part of that operation is failing. Stay tuned—

**Comment by iainheng** [comment] 2018-05-31 04:02
I am having the same issue with browser Gmail and Android Gmail. This bug is very crucial as it will generate a lot of redundant drafts in Mailspring which we need to delete it one by one.

Hopefully to see a fix for this.

**Comment by da-am** [comment] 2018-06-20 21:51
Seeing this on Fedora 28 as well with Mailspring v 1.2.2.

**Comment by sabatesduran** [comment] 2018-07-04 13:12
Seeing this on Ubuntu 17.10 with Mailspring 1.2.2

**Comment by arcwright** [comment] 2018-07-30 06:07
Still getting this error on Linux Mint 18.3 (Sylvia) with Mailspring v1.3.0

**Comment by fromanm1** [comment] 2018-08-17 16:12
same issue

centos 7 7.5.1804
mailspring mailspring-1.4.2

**Comment by gotamist** [comment] 2018-11-30 17:14
Same issue on Ubuntu 18.04

**Comment by brianleejackson** [comment] 2019-01-22 05:47
Same here, on Mojave 10.14.2. @coagmano We are also sharing a G suite account and this is why it's happening. Unfortunately, I might have to move to a different client because of this bug.

**Comment by Birssan** [comment] 2019-01-30 09:50
Same issue here...

**Comment by Dudo1985** [comment] 2019-01-30 21:49
Same issue on both Windows and Linux

**Comment by xclabit** [comment] 2019-02-28 12:46
Still experiencing the same issue on Windows using Mailspring (1.5.7-2057ca30). Consistently happens when I start writing drafts on my work computer using OSX's Mail.app (Office 365 mail).

**Comment by tdzienniak** [comment] 2019-05-07 07:28
Still the same issue with Mailspring 1.6.1 on Ubuntu. Is there any chance that it will be fixed anytime soon?

**Comment by brianleejackson** [comment] 2019-05-07 20:04
Ya I loved Mailspring, but this one bug made it impossible to use. Using a different solution now. 
I would return in a heartbeat if it was ever fixed.

**Comment by Dudo1985** [comment] 2019-06-01 10:49
Any update on this?

Is pretty frustating.

**Comment by abezukor** [comment] 2019-06-04 23:03
Having the Issue on Pop OS 19.4 with both G Suite and Gmail Accounts.

**Comment by youngwoo-yoon** [comment] 2020-06-23 10:46
Still the same problem on version 1.7.8 (windows)

**Comment by CodeMouse92** [comment] 2021-02-09 21:37
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mailspring-creates-many-copies-of-a-draft-when-editing-a-draft-in-google-inbox-or-gmail/526

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@punshs: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-09 21:37 UTC
Labels: audit, bug
