### ISSUE TITLE
Mailspring does not start when open through icon/error when starting via terminal: cannot perform readlinkat() on the mount namespace file descriptor of the init process: Permission denied 

### ISSUE THREAD

**Issue by goldsteal** [Foundry376/Mailspring#962] opened 2018-07-01 13:28 UTC
When I try to open Mailspring (installed as snap) nothing happens. Trying to open it via the terminal gives me the following error: 

`env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/mailspring_mailspring.desktop /snap/bin/mailspring %U
cannot perform readlinkat() on the mount namespace file descriptor of the init process: Permission denied` 

**System Info**
**OS / _Kernel_:** Linux Mint 18.3/ _4.18.0-041800rc2-generic_
**CPU:** Intel Core i7-5820K 
**GPU:**  AMD R9 380X
**Mainboard / _Bios_:** Asus X99-DELUXE / _3802_

Also tested with:
**Mainboard / _Bios_:** Asus X99-DELUXE / _3902_

**Comment by bengotow** [comment] 2018-07-08 06:41
Hey! Thanks for reporting this - can you see if there are any updates available to snapd for Linux Mint? This may actually be a snapd issue.

**Comment by markstos** [comment] 2018-08-08 14:52
I got the same error when trying to run the unrelated `ec2-consistent-snapshot` snap on Ubuntu 14.04. 

So yeah, it does like the error is snap-related.

**Comment by markstos** [comment] 2018-08-14 13:12
This error is also also being discussed on the Snapcraft forum: https://forum.snapcraft.io/t/cannot-perform-readlinkat-on-the-mount-namespace-file-descriptor-of-the-init-process-permission-denied/6743 

I'm not sure if the root cause is the same or not.

**Comment by mikehhhhhhh** [comment] 2018-08-16 20:45
I also get the same error with 18.04 and 4.18
```cannot perform readlinkat() on the mount namespace file descriptor of the init process: Permission denied```

**Comment by bengotow** [comment] 2020-04-16 06:25
Hey folks—it's been a few years and I believe this has been fixed in more recent versions of Electron and/or snapcraft. Feel free to bump this or re-open a new issue if you run in to this again.

**Closed by bengotow** 2020-04-16 06:25 UTC
Labels: linux, snapcraft
