### ISSUE TITLE
Bug: No signatures in plain-text mode

### ISSUE THREAD

**Issue by bliss1985** [Foundry376/Mailspring#1865] opened 2020-03-17 07:08 UTC
**Describe the bug**
When you switch to plain-text mode you're not able to use any singatures. 

**To Reproduce**
Just switch to plain-text mode and try send an e-mail

**Comment by bliss1985** [comment] 2020-03-26 23:59
Anyone?

**Comment by BhavKhatri** [comment] 2020-04-03 15:34
I have the issue that I can't seem to choose whether my reply is plain text or html - currently it randomly decides whether to give me a html reply, which is my set default.

When it is plain text, yes I do lose my signature. 

Sent a request to zendesk, but as with all requests I've sent them over the years regarding mailspring it has been completely ignored!!!

**Comment by CodeMouse92** [comment] 2021-02-23 22:47
@BhavKhatri Just a heads up, the Zendesk is unmaintainable by the one regular contributor, Ben. You're not being "ignored" - there's just literally no way to find occasional legitimate inquiry in the 22K tickets, almost all of which are either spam or things that should only go to the GitHub. (And no, Mailspring Pro has never offered "premium support" — there's no way for Ben to provide that without stopping all development work indefinitely and just answering tickets all day every day forever.)

What's further, 2020 brought development to a grinding halt. *It has resumed!* We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

And yes, we're shutting down the Zendesk very soon, in favor of Discourse.

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/plain-text-mode-signatures/751

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@bliss1985 @BhavKhatri: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-23 22:47 UTC
Labels: audit, bug
