### ISSUE TITLE
Bug: Search is not working

### ISSUE THREAD

**Issue by simroux** [Foundry376/Mailspring#1945] opened 2020-04-27 15:30 UTC
**Describe the bug**
Some of the most recent emails do not seem to be included in the search / are not retrieved via text search

**To Reproduce**
1. Receive an email
2. Search by the sender name / email of this recent email
3. The most recent email is not found, but some older ones are
Note: this seems to be somewhat random, i.e. it works in most cases, but only sometimes is the search failing. Can't seem to find a good reason/pattern explaining the failures

**Expected behavior**
The email should be retrieved

**Setup: (please complete the following information):**
 - Ubuntu 19.10
 - Mailspring Version: 1.7.6-e94bb759

**Additional context** 
Seems similar and could be related to issue https://github.com/Foundry376/Mailspring/issues/731

**Comment by ondrej-petr** [comment] 2020-04-29 08:32
I can confirm this behaviour.

Windows 10
Mailspring 1.7.6-e94bb759

inbox list:
![image](https://user-images.githubusercontent.com/9945232/80575635-314f3c00-8a04-11ea-8172-ddb081b015f3.png)

search by subject:
![image](https://user-images.githubusercontent.com/9945232/80575742-5348be80-8a04-11ea-8500-a3fedf3528ec.png)

search by sender:
![image](https://user-images.githubusercontent.com/9945232/80575588-21375c80-8a04-11ea-87e3-04b81f41b1b2.png)

**Comment by reshadde** [comment] 2020-04-30 13:45
Same issue here on ubuntu 20.04.
Also inputs on new mail are not working for me.

**Comment by ondrej-petr** [comment] 2020-04-30 16:35
Reseting cache (Preferences ->button on the bottom) solved my problem. But it is not the best solution in my opinion.

**Comment by simroux** [comment] 2020-04-30 19:35
Worked for me too, thanks ! Agreed that this is not the best solution though, is the underlying issue is a "corrupted" cache, ideally the software would have a way to detect it, and then either force cache rebuild or suggest it to the user, so I'm leaving the bug open for now

**Comment by marcvk** [comment] 2020-05-09 08:37
I can confirm the bug. Search started working after resetting cache as suggested above.

**Comment by woook** [comment] 2020-06-05 13:39
I can also confirm.

**Comment by iojw** [comment] 2020-07-05 09:55
Same issue here on Windows 10, Mailspring version 1.7.8-13635bcf - search started working again after resetting the cache.

**Comment by CodeMouse92** [comment] 2021-02-27 03:54
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/search-is-not-working/863

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@simroux @ondrej-petr @reshadde @marcvk @iojw: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-27 03:54 UTC
Labels: audit, bug
