### ISSUE TITLE
[BUG] Copied text from the previous message to reply area will be black in black theme

### ISSUE THREAD

**Issue by a2nt** [Foundry376/Mailspring#743] opened 2018-03-07 16:34 UTC
Copied text from the previous message to reply area will be black in black theme:
![screenshot from 2018-03-07 23-33-13](https://user-images.githubusercontent.com/672794/37104705-48b870d0-2225-11e8-8bd0-66bd1f4b487a.png)
After typing "Fixed" it's still black, but it will became white after sending.

**Comment by CodeMouse92** [comment] 2021-02-03 18:47
Duplicate of #1928

**Closed by CodeMouse92** 2021-02-03 18:47 UTC
Labels: audit

**Comment by CodeMouse92** [comment] 2021-02-03 18:59
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/dark-text-using-dark-themes/448

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team
