### ISSUE TITLE
[Feature Request] Sync New Mail Button in Toolbar

### ISSUE THREAD

**Issue by algkmn** [Foundry376/Mailspring#1558] opened 2019-07-03 06:28 UTC
Example: https://i.vgy.me/EaRhMO.jpg

Adding a "sync new mail" button after the "compose new email" button would be nice.

**Comment by dtokarczyk** [comment] 2019-07-03 13:46
For the same effect you can push F5, I don't know if you know.

**Comment by algkmn** [comment] 2019-07-03 14:01
Yeap, I already know that. But that's not the point.

**Comment by bengotow** [comment] 2019-07-04 13:44
Hey! Thanks for filing this! Honestly, we probably won't implement this because for (almost all) mail providers, Mailspring holds an IMAP IDLE connection open to your mail server and the app is notified of mailbox changes, so choosing "Sync New Mail" doesn't ~really~ make a difference in most scenarios. (It does kick off a forced resync of all your folders, but typically the new mail would have arrived in the same amount of time without any user action.)

We will be putting a calendar icon up there soon though! 🙌

**Comment by c-bandy** [comment] 2019-07-11 07:39
Pressing the refresh button makes my brain happy, even if it doesn't technically do anything. Having it not there would feel wrong, as every other email client has one.

**Comment by CodeMouse92** [comment] 2021-02-26 17:03
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/sync-new-mail-button-in-toolbar/824

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@algkmn @dtokarczyk @c-bandy: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-26 17:03 UTC
Labels: audit, enhancement, product-direction
