### ISSUE TITLE
Clicking older e-mail in conversation and using shortcode to reply creates reply on latest message

### ISSUE THREAD

**Issue by enoversum** [Foundry376/Mailspring#562] opened 2018-01-24 14:05 UTC
I believe this behaviour transferred from the original Nylas mail client to Mailspring.
I would like to be able to reply to an older e-mail in a conversation by clicking on it and using one of the reply shortcuts (A/R) to actually reply to that specific e-mail. This is useful if the conversation spread out to two separate threads with two participants, and you want to follow up on an e-mail with one of the earlier participants in the thread instead of who you wrote to last time around. 
So far, no matter what e-mail in a conversation you open and click on, when you hit the reply shortcuts, a reply to the most recent e-mail and their participants is being created.

**Comment by bengotow** [comment] 2018-01-29 07:25
Hey! Yeah this is a longstanding issue actually—there's no concept of a "selected message" within the conversation, so keyboard shortcuts always impact the latest message. I'll see if I can fix this soon.

**Comment by enoversum** [comment] 2018-01-29 07:46
Hi @bengotow , thanks for letting me know 😄 ! Would love get this corrected at some place in time 😉 . Though knowing you already did a very good job getting Mailspring up and working (a lot better than its ancestor)!

**Comment by CodeMouse92** [comment] 2021-02-24 22:00
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue looks like one we've already migrated to Discourse:

https://community.getmailspring.com/t/focused-message/710

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@enoversum: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-24 22:00 UTC
Labels: audit, enhancement
