### ISSUE TITLE
[Feature Suggestion] Allow 'Mark as Read then Arhive' as a swipe option

### ISSUE THREAD

**Issue by PowerSnail** [Foundry376/Mailspring#760] opened 2018-03-14 04:01 UTC
I suggest that Mailspring could add a 'Read & Archive' action. 

It is useful when swiping away emails, which upon looking at their title, you know you don't have to read them. Directly archiving such emails scatters unread and unimportant entries in the archive box. It is not very hard to clean them, but it would be nice if the mail client handles this automatically.

Thank you!

##### Are there any related issues?

I did not find any.

##### What operating system are you using?

Windows 10

##### What version of Mailspring are you using?

1.1.4
--

**Feature Request?**
##### Does this feature exist in another mail client or tool you use?

Yes, Outlook on Android (probably on iOS as well) has the feature.

**Comment by CodeMouse92** [comment] 2021-02-03 18:14
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/customizable-swipe-button-actions/444

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-03 18:14 UTC
Labels: audit
