### ISSUE TITLE
Bug: mail ordering

### ISSUE THREAD

**Issue by GrigoriyMikhalkin** [Foundry376/Mailspring#2123] opened 2020-08-19 16:55 UTC
**Describe the bug**
There's problem with mail ordering, looks like something off with handling timezones -- as you can see in attached picture, there's two of my messages and it looks like i sent second right after first, but actual order was like: my first message, response, my second message. My guess is that problem is in timezone, as person and i are in different ones, and my time was 2 hours earlier.

P.S. Gmail web client ordering mails correctly.

**Screenshots**
![ordering_bug](https://user-images.githubusercontent.com/3637857/90663590-26861480-e24a-11ea-8cc7-bf9c004b6c1a.png)

**Setup: (please complete the following information):**
 - OS: Ubuntu
 - OS Version 20.04
 - Mailspring Version: ex: 1.7.8-13635bcf

**Comment by CodeMouse92** [comment] 2021-03-03 02:18
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mail-ordering/946

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@GrigoriyMikhalkin: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-03-03 02:18 UTC
Labels: audit, bug
