### ISSUE TITLE
Mailspring display 2 unread messages in the inbox but I already read everything

### ISSUE THREAD

**Issue by rafrsr** [Foundry376/Mailspring#247] opened 2017-10-25 02:39 UTC
##### Are there any related issues?
no

##### What operating system are you using?
Ubuntu 17.10

##### What version of Mailspring are you using?
1.0.6

**Bug?**
##### Do you have any third-party plugins installed? If so, which ones?
no

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
no

---

Mailspring are showing 2 unread mails in the inbox, but all messages appear as read. When I go to unread messages folder, can see 2 messages but are already read and marked as read, I try to mark as unread and open again but nothing happen, the message is read but the badge still showing [2]. The webmail and other clients display 0 unread messages. Only clearing the cache resolve this issue, but is annoying because  happen frequently.

**Comment by rafrsr** [comment] 2017-10-26 15:23
Apparently this problem happens with some rules that I have, move some messages to specific folder and mark them as read.  The message appears as read, but the unread badge are not updated.

**Comment by rafrsr** [comment] 2017-10-31 13:51
Digging into this issue I can see that happens not only with automatic tasks, but also happens when I mark some emails as unread manually.

For example, I have some mails in my INBOX (Gmail), after mark some email as unread can see the following logs:

`mailsync-xxxx.log:`
```
3551 [2017-10-31 09:30:08.212] [foreground] [info] [local-2dd29259-1454] Running ChangeUnreadTask performRemote:
3551 [2017-10-31 09:30:08.754] [foreground] [info] [local-2dd29259-1454] -- Succeeded. Changing status to `complete`
3551 [2017-10-31 09:30:09.002] [foreground] [info] syncFolderChangesViaCondstore - [Gmail]/All Mail: highestmodseq changed, requesting changes...
3551 [2017-10-31 09:30:09.287] [foreground] [info] 🔸 Updating message 61491=61491 with subject:  Email subject ......
3551 [2017-10-31 09:30:09.291] [foreground] [info] Idling on folder [Gmail]/All Mail
```
And the email is marked as unread with success, and appear as unread in MailSpring and Gmail, in this case all works as expected, then when the email is read, is marked as read in Gmail and MailSpring , at this point all ok.

Now trying the same task with another email in the same account but from another sender:

`mailsync-xxxx.log:`
```
3551 [2017-10-31 09:23:48.198] [foreground] [info] [local-87d8fcd7-eafc] Running ChangeUnreadTask performRemote:
3551 [2017-10-31 09:23:48.453] [foreground] [info] [local-87d8fcd7-eafc] -- Succeeded. Changing status to `complete`
3551 [2017-10-31 09:23:48.715] [foreground] [info] syncFolderChangesViaCondstore - [Gmail]/All Mail: highestmodseq, uidnext match, no changes.
3551 [2017-10-31 09:23:48.719] [foreground] [info] Idling on folder [Gmail]/All Mail
```
When manually mark the email as `unread` the above lines appear in the log file, the email is never marked as unread in Mailspring, but it's marked in Gmail as unread, and the Inbox folder in MailSpring display the badge: (1) unread mail.

From here, MailSpring will always keep showing the badge of there are unread emails in the Inbox, even if you no longer have unread emails. Only clearing the cache resolve this issue, but is annoying because happen frequently.

**Comment by oxysoft** [comment] 2017-11-30 16:47
Can't add much more to this but I also have the same problem on Windows 10 with the latest release.

**Comment by andrew-collins-at-cre8ive** [comment] 2018-01-08 06:28
I also have this issue on OSX 10.10.5

**Comment by bengotow** [comment] 2018-02-03 17:38
Hey folks—I think this was fixed in 1.1.0 by fe2170c65f9cdce7bec6a1f69b02e28e9557f746. If anyone sees this on a newer version can you post and let me know? Otherwise I'll close this in a bit.

**Comment by backendr** [comment] 2018-02-05 08:51
Im on version `1.1.2` and still have this issue.

For me there are 2 short term workarounds:
+ Click on `Unread Emails` and delete them from there. :(
+ `preferences > Accounts > Select Account > Rebuild Cache`

Doesn't seem to be any specific email or account. I have no email rules and only the default folders.

**Comment by TheRoarkster** [comment] 2018-02-11 16:54
On version 1.1.2, same issue.  No rules.

**Comment by enx1998** [comment] 2018-07-15 10:33
On version 1.2.2 there is the same issue. Rebuilding cache resetted the unread number. 
Would be great if this issue were definitely solved.

**Comment by Geotig** [comment] 2018-07-18 20:06
In version 1.3.0 if the cache was created with the previous version it still shows the persistent "1 new message" mail count. I will report back if the issue appears again.

**Comment by byroncoetsee** [comment] 2018-07-31 23:38
1.3.0 still showing 2 unread but nothing in the unread folder. Rebuilt cache and no change 😢

**Comment by ulgens** [comment] 2018-08-11 21:54
On 1.4.0, this issue still exists.

**Comment by grinsted** [comment] 2018-08-24 19:11
the unread count very quickly is wrong. You can rebuild the cache to correct it temporarily (very short term). 

There are many issues here on github reporting this bug - . (Stilll buggy in 1.4.2)

**Comment by 90yukke** [comment] 2018-12-04 15:38
1.5.3 - Issue still exists.

**Comment by nfaivre** [comment] 2019-01-14 09:06
Same here, Version 1.5.5-b7939d38 on Ubuntu 18.04.

**Comment by ASAPHAANING** [comment] 2019-02-08 14:13
1.5.5-b7939d38 

Same issue, 2 unread unless rebuilding cache.

4.14.94-1-MANJARO

**Comment by ksbg** [comment] 2019-03-05 01:56
Same problem on 1.5.7-20157ca30

**Comment by F0x06** [comment] 2019-03-11 10:44
Same problem on 1.5.7-20157ca30

**Comment by mustafacansevinc** [comment] 2019-04-24 06:45
Same problem on 1.6.1-aceed8e5 on Ubuntu 18.04

**Comment by rtud** [comment] 2019-04-27 19:04
I second that for 1.6.1-aceed8e5 on Ubuntu 18.04.

**Comment by vanushwashere** [comment] 2019-05-08 21:14
Same problem for 1.6.1-aceed8e5 on latest KDE Neon based on Ubuntu 18.04
Opening `Unread` and deleting one already read message solved the issue

**Comment by whywaitwebs** [comment] 2019-05-08 23:48
Issue exists on Windows 10. Darn, thought I finally found a usable mail client.

**Comment by Chrismarsh** [comment] 2019-05-27 16:47
Same issue on macos and fedora

**Comment by DCzajkowski** [comment] 2019-06-21 20:12
Same problem here on MacOS Mojave.

**Comment by scacinto** [comment] 2019-07-19 16:09
**Same problem:**

Mailspring Version: 1.6.2-278bf219
Operating System: KDE neon 5.16
KDE Plasma Version: 5.16.3
KDE Frameworks Version: 5.60.0
Qt Version: 5.12.3
Kernel Version: 4.15.0-52-lowlatency
OS Type: 64-bit
Processors: 12 × Intel® Xeon® E-2176M CPU @ 2.70GHz
Memory: 15.5 GiB of RAM

**Comment by DCzajkowski** [comment] 2019-08-09 11:14
To solve this for me is to click on whatever email, `cmd+a` to select all, click "mark as unread" and click "mark as read".

**Comment by Nashluffy** [comment] 2019-09-25 18:05
Still an issue running on Ubuntu 18.04

**Comment by martin-cod** [comment] 2019-11-18 09:25
I am still running into the same issue. 
MacOS High Sierra
MailSpring 1.7.2

Some emails are not marked as Read. I use the same solution provided by @DCzajkowski 

> To solve this for me is to click on whatever email, cmd+a to select all, click "mark as unread" and click "mark as read".

**Comment by vanquang9387** [comment] 2019-12-20 08:24
I got same issue with version 1.7.2 on Windows 10.

**Comment by Acid-miuipolskapl** [comment] 2020-02-06 14:08
1.7.2
Kubuntu 18.04.
Same problem with mails count. Rebuilding cache doesn't help. It clears mails count for a second and then its back again. Very annoying. 
I will not buy the program (because I can buy Pro version) without fixing this bug.

**Comment by cherrot** [comment] 2020-02-23 12:42
In my case, the unread number came from Gmail IMAP. After mark all the mails of every gmail "tag" as read. Unread number on `mailspring` disappeared.

**Comment by Acid-miuipolskapl** [comment] 2020-02-24 07:07
I have 4 IMAP accounts. Only 1 is gmail. Rest are my own domain. The problem exists on every account. And even then sometimes when I read the email and then go to another account and go back my previously read email is again unreaded. Seems developers doesnt care about this problem as this git issues is full of users complaints.

**Comment by MonoTovarisj** [comment] 2020-02-26 13:59
1.7.4 Problem still persist.

It happens for me when I read emails in gmail, when I get to mailspring it still think it's new in the counter but in the inbox mail list it looks read.

**Comment by Raketemensch** [comment] 2020-05-11 19:32
Still happening in 1.7.6 on Mojave. The Unread filter has zero emails, but II still have a basge telling me there are 2 unread emails.

**Comment by doman18** [comment] 2020-05-28 07:32
Mailspring 1.7.6, Kubuntu 18.04 - the same situation. I already have 5 mails which keep coming back. It happens only on Exchange but probably because recently im using it much more than the other accounts. 
Im in the middle of mail-client search for my needs (trying them one by one) so this bug is major factor to try another one

**Comment by Raketemensch** [comment] 2020-05-29 13:47
I think it may be related to threaded messages. It's been happening on my work client for ages, and it just happened on my personal laptop for the first time, and it was definitely on a threaded message.

**Comment by corpsee** [comment] 2020-11-11 02:39
Still present in version 1.7.8-13635bcf.

**Comment by Raketemensch** [comment] 2020-11-25 22:00
This is an outrageously annoying bug that is over 3 years old.

What's weird is that if you do a search of:

is:"unread" in:"Inbox"

...then it finds nothing. It would be nice if the UI would use the same mechanism.

**Comment by egordorichev** [comment] 2021-01-07 08:01
Yes, it is very annoying, has anyone found a workaround yet?

**Comment by CodeMouse92** [comment] 2021-01-28 18:36
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/unread-count-still-on-without-unread-messages/350

Please consider joining that community and continuing the discussion there!

@rafrsr @DCzajkowski @Raketemensch: if you join and reply to the issue, the moderators can make an effort to reassign your migrated posts to you, so you get the credit for it.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-28 18:36 UTC
Labels: audit
