### ISSUE TITLE
mailto: links don't work on Linux

### ISSUE THREAD

**Issue by panta82** [Foundry376/Mailspring#903] opened 2018-05-29 07:19 UTC
When clicking on any `mailto:` link (with or without subject), MailSpring opens up and then I get this error:

![image](https://user-images.githubusercontent.com/4291324/40643618-06f6e90a-6321-11e8-9309-ef9a8e717ea1.png)

Links work fine when I switch my default mail app to Thunderbird (so it's not an issue with system configuration).

--------

##### Are there any related issues?

This one seem similar, but not quite the same:
https://github.com/Foundry376/Mailspring/issues/877

##### What operating system are you using?
Debian 9.4 XFCE

##### What version of Mailspring are you using?
`1.2.1`

##### Do you have any third-party plugins installed? If so, which ones?
No

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?
No

**Comment by allanbreyes** [comment] 2018-05-30 21:56
This _seems_ orthogonal to #877 (cc: @bengotow); looks like something breaks between the OS and Mailspring hand-off. @panta82 do you by chance have this installed from a snap? If so, can you try it with a native installation?

**Comment by panta82** [comment] 2018-06-01 07:13
@allanbreyes I have installed from a deb package, not snap.

I have just updated to `mailspring-1.2.2-amd64.deb`, and the problem is still there.

**Comment by vagos06** [comment] 2018-06-29 09:12
I've had the same problem and after some digging I found that XFCE calls `/usr/lib/x86_64-linux-gnu/xfce4/exo-1/exo-compose-mail-1` (or `/usr/lib/i386-linux-gnu/xfce4/exo-1/exo-compose-mail-1` for 32-bit systems) to handle mailto links
[helper.zip](https://github.com/Foundry376/Mailspring/files/2148703/helper.zip)

. Its syntax is `exo-compose-mail-1 <style> <binary> <mailto>`, with `<style>` being `mozilla`, `mozilla-remote`, `evolution`, `kmail`, `sylpheed`, `balsa` or `mutt`, as defined in the file source: [https://www.apt-browse.org/browse/debian/wheezy/main/i386/libexo-1-0/0.6.2-5/file/usr/lib/i386-linux-gnu/xfce4/exo-1/exo-compose-mail-1](url).
Now, in order for XFCE to recognize an app as a valid e-mail client, it must have a helper file at `/usr/share/xfce4/helpers/` or `~/.local/share/xfce4/helpers/` (with filename `custom-<appname>.desktop` for the latter). This file essentially sets the arguments to call with `exo-compose-mail-1`. I have found that  Mailspring works ok with style set to `evolution` (I've only encountered one input/output error and the message window opened anyway) - I'm attaching the helper file for `~/.local/share/xfce4/helpers/`.

From the looks of it, the devs could fix this problem by having the app add a custom helper file with the appropriate style to match the mailto syntax Mailspring expects.

**Comment by andreshg112** [comment] 2018-08-06 16:30
@vagos06 , I did what you said but It doesn't work.
![image](https://user-images.githubusercontent.com/15859884/43728874-03a14ed6-996c-11e8-896d-ce7bb9a24604.png)

![image](https://user-images.githubusercontent.com/15859884/43728885-10331a4e-996c-11e8-8596-cf5dac50bf6f.png)

Do I have to restart something?

**Comment by andreshg112** [comment] 2018-08-06 16:35
I copy your file content into /home/andreshg112/.local/share/xfce4/helpers/custom-MailReader.desktop
Now, It opens the New mail window but I still got the error.
![image](https://user-images.githubusercontent.com/15859884/43729090-ca355452-996c-11e8-8d0c-b237d786f4f3.png)

**Comment by vagos06** [comment] 2018-08-09 18:35
That's what I'm getting too. My best guess is that mainspring does not return the value `exo-compose` expects, therefore throws this error.

**Comment by andreshg112** [comment] 2018-08-09 19:18
I just noticed something: This doesn't work when the explorer is in the second workspace, and sometimes it doesn't work with Chrome.

**Comment by minhducsun2002** [comment] 2018-12-30 02:43
Same issue as above. I'm on `Debian GNU/Linux buster/sid` with Mailspring `1.5.3-420ce003`.

**Comment by lucas-gautier** [comment] 2019-07-06 18:56
I believe this has been fixed as of Mailspring 1.6.3-134a0e55 which was installed from the downloaded .deb package; had too many issues with the snap installer. Running PopOS 18.04 LTS here.

If you are using Google Chrome/Chromium, you need to remove mailto: from the site handlers settings so Chrome doesn't eat the links.
## To Remove Mailto links from Chrome
1.  Follow this settings chain:  `Settings -> Site Settings -> Handlers`
2.  Remove mailto/Gmail from the email section

Mailto links should now open directly from chrome. Test it!  [didyoufixit@yeahyoudid.com](mailto:didyoufixit@yeahyoudid.com)

**Comment by panta82** [comment] 2019-07-17 08:27
@lucas-gautier , I can't get it to work in Chrome, but at least it now works from Firefox.

**Comment by CodeMouse92** [comment] 2021-02-09 23:02
It appears that this issue has been resolved, so we are closing it. **If the problem occurs again, please create a new thread in the appropriate category on our [Discourse](https://community.getmailspring.com).**

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

We hope to see you there soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-09 23:02 UTC
Labels: audit
