### ISSUE TITLE
Bug: `mailspring --background` and `mailspring --background=true` launch the GUI

### ISSUE THREAD

**Issue by doronbehar** [Foundry376/Mailspring#2152] opened 2020-09-23 07:32 UTC
**Describe the bug**

If no `mailspring` process is alive, I expect `mailspring --background` or `mailspring --background=true` to not start a new GUI instance. I expect these commands to be suitable for an `~/.config/autostart/mailspring.desktop` file. Is there a different way mailspring was intended to be launch in the background? 

**To Reproduce**

Run `mailspring --background` or `mailspring --background=true` when no `mailspring process is alive.

**Expected behavior**

No GUI is launched, and mailspring is running in the background.

**Setup: (please complete the following information):**
 - OS: NixOS
 - OS Version: [nixos-unstable](https://github.com/NixOS/nixpkgs/commit/1179840f9a88b8a548f4b11d1a03aa25a790c379)
 - Mailspring Version: 1.7.8

**Comment by CodeMouse92** [comment] 2021-01-28 16:29
Duplicate of #153

**Closed by CodeMouse92** 2021-01-28 16:29 UTC
Labels: audit, bug
