### ISSUE TITLE
Select/Switch Email Account when forwarding/answering email

### ISSUE THREAD

**Issue by eikaramba** [Foundry376/Mailspring#1474] opened 2019-04-24 01:10 UTC
Currently i cannot change the account FROM with the email is send by when i forward or answer an email. it is always selecting the account the email was initially retrieved. That is unfornately a showstopper, as you especially want to forward emails from another email maybe than the one it was send to (e.g. different private and business email accounts)

##### What version of Mailspring are you using?
1.6.1

##### Does this feature exist in another mail client or tool you use?
Postbox, Outlook, i think everyone supports that

**Comment by sasokess** [comment] 2019-05-08 22:04
I completely agree that this feature should be there!
Whenever i need to do that, I open Mac's Mail app to do it!  Which is not something I should do after paying them for premium subscription!

**Comment by bengotow** [comment] 2019-05-26 23:20
Hey folks! Thanks for reporting this, this is great feedback. I think that we've put off doing this in the past because when you change the account you're replying from, it results in the new message being placed in a separate email thread (it "breaks" the current conversation), but in scenarios where you actually want to move the conversation to another account that's probably fine. I'll see if we can do this in an upcoming release soon.

**Comment by karimpb** [comment] 2019-06-12 17:35
I strongly support this request. I'm about to quit mailspring because of the lack of this feature (present in most of other email clients), please add this soon. Best

**Comment by pgebheim** [comment] 2019-10-24 03:15
Heya,

Just noticed this feature still isn't there -- @bengotow Do you have any update on making this happen?

**Comment by pgebheim** [comment] 2019-10-24 13:54
Yeah I have a half dozen email accounts. I commonly need to forward receipts to expensify with the sender being a certain account.

I always jump to Outlook to do that one task -- usually on my phone.

**Comment by nenewapete** [comment] 2020-03-02 10:05
I have the same issue. I need to forward mails from a certain account. is it in the roadmap?

**Comment by Dahaniel** [comment] 2020-07-08 10:02
I strongly support this request. I regularly have to forward information to a mailinglist and I have to use a different account that is registered with the list.

**Comment by CodeMouse92** [comment] 2021-02-17 00:48
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/settings-select-switch-email-account-when-forwarding-answering-email/655

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@eikaramba @pgebheim @Dahaniel: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-17 00:48 UTC
Labels: audit, composer, enhancement
