### ISSUE TITLE
Can't sync emails from Outlook / Microsoft Exchange / Office 365 Exchange

### ISSUE THREAD

**Issue by davond** [Foundry376/Mailspring#1708] opened 2019-11-13 10:57 UTC
Hi,
I've issue with syncing emails from outlook exchange server. Synchronization begins, but never ends and new emails aren't showing up. I tried newest version - 1.7.2, also older verson 1.6.3., but same issue. Some idea or help? Thanks

APP version: 1.7.2 / 1.6.3
OS: Ubuntu 18.04.3 TLS

[![mailspring-issue.png](https://i.postimg.cc/mD0vgyMp/mailspring-issue.png)](https://postimg.cc/8JmKyWZL)

```
13022 [2019-11-13 10:56:29.630] [main] [info] Identity created at 1571127896 - using ID Schema 1
13022 [2019-11-13 10:56:29.632] [main] [info] ------------- Starting Sync (###@###.com) ---------------
13022 [2019-11-13 10:56:29.634] [background] [info] Marking all folders as `busy`
13022 [2019-11-13 10:56:29.634] [background] [info] Syncing folder list...
13022 [2019-11-13 10:56:30.272] [background] [info] Syncing folder list...
13022 [2019-11-13 10:56:30.358] [background] [info] syncFolderUIDRange for INBOX, UIDs: 44079 - 44829, Heavy: true
13022 [2019-11-13 10:56:30.762] [foreground] [info] Idling on folder INBOX
13022 [2019-11-13 10:56:30.979] [metadata] [info] Received metadata V1 for (message - k99wRxzJB2NvBpnfV8wTFtxwioKRCfXWuSczHE6Gk)
13022 [2019-11-13 10:56:30.979] [metadata] [info]  -- Local model is not present. Saving to waiting table.
13022 [2019-11-13 10:56:30.980] [metadata] [info] Received metadata V10 for (message - k99wRxzJB2NvBpnfV8wTFtxwioKRCfXWuSczHE6Gk)
13022 [2019-11-13 10:56:30.980] [metadata] [info]  -- Local model is not present. Saving to waiting table.
13022 [2019-11-13 10:56:30.981] [metadata] [info] Received metadata V1 for (message - k99wRxzJB2NvBpnfV8wTFtxwioKRCfXWuSczHE6Gk)
13022 [2019-11-13 10:56:30.981] [metadata] [info]  -- Local model is not present. Saving to waiting table.
13022 [2019-11-13 10:56:30.982] [metadata] [info] Metadata delta stream starting...
13022 [2019-11-13 10:56:32.357] [background] [info] - remote=205, local=0
13022 [2019-11-13 10:56:32.852] [background] [info] syncFolderUIDRange for INBOX, UIDs: 44079 - 44829, Heavy: false
13022 [2019-11-13 10:56:32.906] [background] [info] - remote=205, local=205
13022 [2019-11-13 10:56:36.870] [background] [info] syncFolderUIDRange for Odeslan&AOE- po&AWE-ta, UIDs: 1 - 1820, Heavy: true
13022 [2019-11-13 10:56:40.050] [background] [info] - remote=512, local=0
13022 [2019-11-13 10:56:40.158] [background] [info] - Updating message JfSfiBAtdyJkpwd9UUm2XUbedDMSBRFoTmanfqu5W
13022 [2019-11-13 10:56:40.158] [background] [info] -- UID (44406 to 1778)
13022 [2019-11-13 10:56:40.158] [background] [info] -- FolderID (ZYdBz7TJ5LcXybmswh3m5V5TQzMB9moAtcARt1bDn to TuCxsUeAyMXjqmfmkoDUCNG4k7hKvJ9XkLdreHoWz)
13022 [2019-11-13 10:56:40.173] [background] [info] - Updating message WDuzSDVX85oCZ8ZvYWB6RaiiaytrkMeWG824HwJKJ
13022 [2019-11-13 10:56:40.173] [background] [info] -- UID (1766 to 1765)
13022 [2019-11-13 10:56:40.180] [background] [info] - Updating message GYWuPqRbzj6yGVARzmFYpkZDuyc9LC9Eo3TZxaCQ1
13022 [2019-11-13 10:56:40.180] [background] [info] -- UID (1762 to 1760)
13022 [2019-11-13 10:56:40.185] [background] [info] - Updating message cuGEc3H8BPaA3pe6CH5XpiCY3gTwsE7Xfn3yZbQor
13022 [2019-11-13 10:56:40.185] [background] [info] -- UID (1756 to 1755)
13022 [2019-11-13 10:56:40.189] [background] [info] - Updating message J5MjmycRdAs9wKb7SjAjoab8aQLPxRYSZWpA7gNqf
13022 [2019-11-13 10:56:40.189] [background] [info] -- UID (1751 to 1750)
13022 [2019-11-13 10:56:40.193] [background] [info] - Updating message BN1YXHrSfee5GtqZssf7QTVkHgX1FJcCDST1NJiu2
13022 [2019-11-13 10:56:40.193] [background] [info] -- UID (1747 to 1745)
13022 [2019-11-13 10:56:40.197] [background] [info] -- Attaching waiting metadata for link-tracking
13022 [2019-11-13 10:56:40.197] [background] [info] -- Attaching waiting metadata for open-tracking
13022 [2019-11-13 10:56:40.197] [background] [info] -- Attaching waiting metadata for send-later
13022 [2019-11-13 10:56:40.200] [background] [info] - Updating message k99wRxzJB2NvBpnfV8wTFtxwioKRCfXWuSczHE6Gk
13022 [2019-11-13 10:56:40.200] [background] [info] -- UID (1740 to 1736)
13022 [2019-11-13 10:56:42.334] [background] [info] syncFolderUIDRange for Odeslan&AOE- po&AWE-ta, UIDs: 725 - 1820, Heavy: false
13022 [2019-11-13 10:56:42.389] [background] [info] - remote=406, local=400
13022 [2019-11-13 10:56:42.394] [background] [info] - Fetching full headers for 6 (of 6 needed)
13022 [2019-11-13 10:56:42.496] [background] [info] - Updating message WDuzSDVX85oCZ8ZvYWB6RaiiaytrkMeWG824HwJKJ
13022 [2019-11-13 10:56:42.496] [background] [info] -- UID (1765 to 1766)
13022 [2019-11-13 10:56:42.513] [background] [info] - Updating message GYWuPqRbzj6yGVARzmFYpkZDuyc9LC9Eo3TZxaCQ1
13022 [2019-11-13 10:56:42.513] [background] [info] -- UID (1760 to 1762)
13022 [2019-11-13 10:56:42.524] [background] [info] - Updating message cuGEc3H8BPaA3pe6CH5XpiCY3gTwsE7Xfn3yZbQor
13022 [2019-11-13 10:56:42.524] [background] [info] -- UID (1755 to 1756)
13022 [2019-11-13 10:56:42.530] [background] [info] - Updating message J5MjmycRdAs9wKb7SjAjoab8aQLPxRYSZWpA7gNqf
13022 [2019-11-13 10:56:42.530] [background] [info] -- UID (1750 to 1751)
13022 [2019-11-13 10:56:42.536] [background] [info] - Updating message BN1YXHrSfee5GtqZssf7QTVkHgX1FJcCDST1NJiu2
13022 [2019-11-13 10:56:42.536] [background] [info] -- UID (1745 to 1747)
13022 [2019-11-13 10:56:42.541] [background] [info] - Updating message k99wRxzJB2NvBpnfV8wTFtxwioKRCfXWuSczHE6Gk
13022 [2019-11-13 10:56:42.541] [background] [info] -- UID (1736 to 1740)
13022 [2019-11-13 10:56:44.633] [metadataExpiration] [info] Scanning for expired metadata
13022 [2019-11-13 10:56:44.634] [metadataExpiration] [info] -- Will wake for next expiration in 7200sec
13022 [2019-11-13 10:56:46.602] [background] [info] Cleaning local cache and updating stats
13022 [2019-11-13 10:56:46.603] [background] [info] -- 0 message bodies deleted from local cache.
13022 [2019-11-13 10:56:46.641] [background] [info] syncFolderUIDRange for Koncepty, UIDs: 1 - 4430, Heavy: true
13022 [2019-11-13 10:56:46.750] [background] [info] - remote=0, local=0
13022 [2019-11-13 10:56:46.751] [background] [info] syncFolderUIDRange for Koncepty, UIDs: 1 - 4430, Heavy: false
13022 [2019-11-13 10:56:46.786] [background] [info] - remote=0, local=0
13022 [2019-11-13 10:56:46.787] [background] [info] Cleaning local cache and updating stats
13022 [2019-11-13 10:56:46.789] [background] [info] -- 0 message bodies deleted from local cache.
13022 [2019-11-13 10:56:46.839] [background] [info] syncFolderUIDRange for Odstran&ARs-n&AOE- po&AWE-ta, UIDs: 1 - 26878, Heavy: false
13022 [2019-11-13 10:56:46.958] [background] [info] - remote=698, local=0
13022 [2019-11-13 10:56:46.961] [background] [info] - Fetching full headers for 698 (of 698 needed)
13022 [2019-11-13 10:56:53.023] [background] [info] syncFolderUIDRange for Odstran&ARs-n&AOE- po&AWE-ta, UIDs: 26100 - 26878, Heavy: false
13022 [2019-11-13 10:56:53.077] [background] [info] - remote=400, local=400
13022 [2019-11-13 10:56:53.078] [background] [info] Cleaning local cache and updating stats
13022 [2019-11-13 10:56:53.079] [background] [info] -- 0 message bodies deleted from local cache.
13022 [2019-11-13 10:56:53.124] [background] [info] syncFolderUIDRange for Nevy&AX4A4Q-dan&AOE- po&AWE-ta, UIDs: 109118 - 109868, Heavy: true
13022 [2019-11-13 10:56:56.835] [background] [info] - remote=648, local=0
13022 [2019-11-13 10:56:59.905] [background] [info] syncFolderUIDRange for Nevy&AX4A4Q-dan&AOE- po&AWE-ta, UIDs: 109393 - 109868, Heavy: false
13022 [2019-11-13 10:56:59.988] [background] [info] - remote=400, local=400
13022 [2019-11-13 10:57:00.026] [background] [info] syncFolderUIDRange for &ANo-lohy, UIDs: 1 - 1, Heavy: false
13022 [2019-11-13 10:57:00.100] [background] [info] - remote=0, local=0
13022 [2019-11-13 10:57:00.100] [background] [info] Cleaning local cache and updating stats
13022 [2019-11-13 10:57:00.102] [background] [info] -- 0 message bodies deleted from local cache.
13022 [2019-11-13 10:57:00.141] [background] [info] syncFolderUIDRange for Archivovat, UIDs: 1 - 2, Heavy: true
13022 [2019-11-13 10:57:00.216] [background] [info] - remote=0, local=0
13022 [2019-11-13 10:57:00.216] [background] [info] syncFolderUIDRange for Archivovat, UIDs: 1 - 2, Heavy: false
13022 [2019-11-13 10:57:00.250] [background] [info] - remote=0, local=0
13022 [2019-11-13 10:57:00.250] [background] [info] Cleaning local cache and updating stats
13022 [2019-11-13 10:57:00.252] [background] [info] -- 0 message bodies deleted from local cache.
13022 [2019-11-13 10:57:00.293] [background] [info] syncFolderUIDRange for Probl&AOk-my se synchronizac&AO0-/Selh&AOE-n&AO0- serveru, UIDs: 1 - 1, Heavy: false
13022 [2019-11-13 10:57:00.367] [background] [info] - remote=0, local=0
13022 [2019-11-13 10:57:00.368] [background] [info] Cleaning local cache and updating stats
13022 [2019-11-13 10:57:00.370] [background] [info] -- 0 message bodies deleted from local cache.
13022 [2019-11-13 10:57:00.410] [background] [info] syncFolderUIDRange for Probl&AOk-my se synchronizac&AO0-/M&AO0-stn&AO0- selh&AOE-n&AO0-, UIDs: 1 - 1, Heavy: false
13022 [2019-11-13 10:57:00.484] [background] [info] - remote=0, local=0
13022 [2019-11-13 10:57:00.486] [background] [info] Cleaning local cache and updating stats
13022 [2019-11-13 10:57:00.492] [background] [info] -- 0 message bodies deleted from local cache.
13022 [2019-11-13 10:57:00.547] [background] [info] syncFolderUIDRange for Probl&AOk-my se synchronizac&AO0-/Konflikty, UIDs: 1 - 49, Heavy: true
13022 [2019-11-13 10:57:00.624] [background] [info] - remote=0, local=0
13022 [2019-11-13 10:57:00.625] [background] [info] syncFolderUIDRange for Probl&AOk-my se synchronizac&AO0-/Konflikty, UIDs: 1 - 49, Heavy: false
13022 [2019-11-13 10:57:00.659] [background] [info] - remote=0, local=0
13022 [2019-11-13 10:57:00.660] [background] [info] Cleaning local cache and updating stats
13022 [2019-11-13 10:57:00.666] [background] [info] -- 0 message bodies deleted from local cache.
13022 [2019-11-13 10:57:00.714] [background] [info] syncFolderUIDRange for Probl&AOk-my se synchronizac&AO0-, UIDs: 1 - 1, Heavy: false
13022 [2019-11-13 10:57:00.789] [background] [info] - remote=0, local=0
13022 [2019-11-13 10:57:00.790] [background] [info] Cleaning local cache and updating stats
13022 [2019-11-13 10:57:00.793] [background] [info] -- 0 message bodies deleted from local cache.
13022 [2019-11-13 10:57:00.841] [background] [info] syncFolderUIDRange for Pozn&AOE-mky, UIDs: 1 - 1, Heavy: false
13022 [2019-11-13 10:57:00.917] [background] [info] - remote=0, local=0
13022 [2019-11-13 10:57:00.918] [background] [info] Cleaning local cache and updating stats
13022 [2019-11-13 10:57:00.920] [background] [info] -- 0 message bodies deleted from local cache.
13022 [2019-11-13 10:57:00.962] [background] [info] syncFolderUIDRange for Odchoz&AO0- po&AWE-ta, UIDs: 1 - 19, Heavy: true
13022 [2019-11-13 10:57:01.039] [background] [info] - remote=0, local=0
13022 [2019-11-13 10:57:01.040] [background] [info] syncFolderUIDRange for Odchoz&AO0- po&AWE-ta, UIDs: 1 - 19, Heavy: false
13022 [2019-11-13 10:57:01.077] [background] [info] - remote=0, local=0
13022 [2019-11-13 10:57:01.079] [background] [info] Cleaning local cache and updating stats
13022 [2019-11-13 10:57:01.084] [background] [info] -- 0 message bodies deleted from local cache.
13022 [2019-11-13 10:57:01.135] [background] [info] syncFolderUIDRange for Odb&ARs-ry RSS, UIDs: 1 - 1, Heavy: false
13022 [2019-11-13 10:57:01.209] [background] [info] - remote=0, local=0
13022 [2019-11-13 10:57:01.210] [background] [info] Cleaning local cache and updating stats
13022 [2019-11-13 10:57:01.212] [background] [info] -- 0 message bodies deleted from local cache.
13022 [2019-11-13 10:57:01.255] [background] [info] syncFolderUIDRange for Mailspring/Snoozed, UIDs: 1 - 1, Heavy: false
13022 [2019-11-13 10:57:01.330] [background] [info] - remote=0, local=0
13022 [2019-11-13 10:57:01.331] [background] [info] Cleaning local cache and updating stats
13022 [2019-11-13 10:57:01.333] [background] [info] -- 0 message bodies deleted from local cache.
13022 [2019-11-13 10:57:01.378] [background] [info] syncFolderUIDRange for Mailspring, UIDs: 1 - 1, Heavy: false
13022 [2019-11-13 10:57:01.454] [background] [info] - remote=0, local=0
13022 [2019-11-13 10:57:01.455] [background] [info] Cleaning local cache and updating stats
13022 [2019-11-13 10:57:01.457] [background] [info] -- 0 message bodies deleted from local cache.
13022 [2019-11-13 10:57:01.501] [background] [info] syncFolderUIDRange for Kontakty, UIDs: 1 - 7, Heavy: true
13022 [2019-11-13 10:57:01.642] [background] [info] - remote=1, local=0
13022 [2019-11-13 10:57:01.648] [background] [info] syncFolderUIDRange for Kontakty, UIDs: 1 - 7, Heavy: false
13022 [2019-11-13 10:57:01.739] [background] [info] - remote=1, local=1
13022 [2019-11-13 10:57:01.843] [background] [info] Cleaning local cache and updating stats
13022 [2019-11-13 10:57:01.846] [background] [info] -- 0 message bodies deleted from local cache.
13022 [2019-11-13 10:57:01.888] [background] [info] syncFolderUIDRange for Kalend&AOEBWQ-/Narozeniny, UIDs: 1 - 1, Heavy: false
13022 [2019-11-13 10:57:02.496] [background] [info] - remote=0, local=0
13022 [2019-11-13 10:57:02.498] [background] [info] Cleaning local cache and updating stats
13022 [2019-11-13 10:57:02.504] [background] [info] -- 0 message bodies deleted from local cache.
13022 [2019-11-13 10:57:02.559] [background] [info] syncFolderUIDRange for Kalend&AOEBWQ-, UIDs: 1 - 2189, Heavy: true
13022 [2019-11-13 10:57:03.023] [background] [info] - remote=80, local=0
13022 [2019-11-13 10:57:03.346] [background] [info] syncFolderUIDRange for Kalend&AOEBWQ-, UIDs: 1 - 2189, Heavy: false
13022 [2019-11-13 10:57:03.383] [background] [info] - remote=80, local=80
13022 [2019-11-13 10:57:04.288] [background] [info] Cleaning local cache and updating stats
13022 [2019-11-13 10:57:04.292] [background] [info] -- 0 message bodies deleted from local cache.
13022 [2019-11-13 10:57:04.335] [background] [info] syncFolderUIDRange for Infected Items, UIDs: 1 - 1, Heavy: false
13022 [2019-11-13 10:57:04.413] [background] [info] - remote=0, local=0
13022 [2019-11-13 10:57:04.415] [background] [info] Cleaning local cache and updating stats
13022 [2019-11-13 10:57:04.420] [background] [info] -- 0 message bodies deleted from local cache.
13022 [2019-11-13 10:57:04.466] [background] [info] syncFolderUIDRange for Historie konverzace, UIDs: 1 - 3, Heavy: true
13022 [2019-11-13 10:57:04.606] [background] [info] - remote=1, local=0
13022 [2019-11-13 10:57:04.624] [background] [info] syncFolderUIDRange for Historie konverzace, UIDs: 1 - 3, Heavy: false
13022 [2019-11-13 10:57:04.718] [background] [info] - remote=1, local=1
13022 [2019-11-13 10:57:04.718] [background] [info] Cleaning local cache and updating stats
13022 [2019-11-13 10:57:04.720] [background] [info] -- 0 message bodies deleted from local cache.
13022 [2019-11-13 10:57:04.760] [background] [info] syncFolderUIDRange for Den&AO0-k, UIDs: 1 - 1, Heavy: false
13022 [2019-11-13 10:57:04.834] [background] [info] - remote=0, local=0
13022 [2019-11-13 10:57:04.835] [background] [info] Cleaning local cache and updating stats
13022 [2019-11-13 10:57:04.836] [background] [info] -- 0 message bodies deleted from local cache.
13022 [2019-11-13 10:57:04.839] [background] [info] Sync loop deleting unlinked messages with phase 2.
13022 [2019-11-13 10:57:04.841] [background] [info] Sync loop complete.
13022 [2019-11-13 10:57:04.841] [background] [info] Syncing folder list...
13022 [2019-11-13 10:57:04.924] [background] [info] syncFolderUIDRange for INBOX, UIDs: 1 - 44079, Heavy: false
13022 [2019-11-13 10:57:05.152] [background] [info] - remote=3934, local=1
13022 [2019-11-13 10:57:05.210] [background] [info] - Fetching full headers for 3933 (of 3933 needed)
13022 [2019-11-13 10:57:05.271] [background] [info] Sleeping after exception: {"debuginfo":"syncFolderUIDRange - fetchMessagesByUID (heavy)","key":"ErrorFetch","retryable":true,"what":"std::exception"}
```

**Comment by mbrihed** [comment] 2019-11-14 04:31
I have a similar issue. I use DavMail and Mailspring has been synchronizing my emails for 3 weeks and it never stops. I dont even see a progress on percentage.

I would love to see EWS suport so I could remove Davmail and have native Office 365 support through EWS instead. The calendar I use (Minetime) uses it and works perfectly.

**Comment by xtrasimplicity** [comment] 2019-12-11 20:35
I'm having the same issue and would also like to be able to remove Davmail and use Mailspring + O365 natively.

Is there any particular reason this hasn't been developed? Is it just a case of a lack of resourcing?
If so, would the core team be open to a PR with this implemented? @bengotow @emorikawa

**Comment by nalin29** [comment] 2019-12-26 15:59
same issue anyone have a workaround

**Comment by bengotow** [comment] 2020-02-15 20:30
Hey folks—thanks for filing this! I'd really like to support Exchange / EWS in the future and if there's an external OSS project or a PR that adds it we'd definitely accept it! We originally held off because Exchange is a very different beast than IMAP / SMTP and likely to be a major project, and also because it seemed like Microsoft was on track to add IMAP support to all Office 365 offerings.

If you use Office 365 "for Home", or "Office 365 Business" (NOT Business Essentials or Business Premium) you actually can connect Mailspring directly to your Office 365 account from the "Add an Account" screen since those Office 365 tiers don't come with Exchange and it uses IMAP instead. (If you visit the "Compare Plans" page, you can see at the bottom which types of accounts list "Exchange" as a service: https://products.office.com/en-us/compare-all-microsoft-office-products?activetab=tab:primaryr2)

I'm stil hoping that Microsoft adds support for IMAP to their Exchange email offering, but it seems like it's not a priority for them. After I wrap up the calendar feature this summer I'll take a look and see if we can add native Exchange support so you don't have to try proxying through DAVMail.

Also as a sidenote, I think the reason that DAVMail is not working is because the same email message appears in multiple "IMAP Folders" because Exchange tags / labels are mapped to IMAP folders. If DAVMail allows you to limit sync to just the core Exchange folders I think that will work reliably!

**Comment by BrunoSpy** [comment] 2020-11-24 11:09
As more and more organizations are switching to MS365, the need for an implementation of EWS is very high. I hope you will find the time and resources to add the feature in the future.

**Comment by CodeMouse92** [comment] 2021-01-30 00:43
Thank you for your patience on this issue! I know it's frustrating when you cannot connect to your email with Mailspring.

2020 prevented much development work on Mailspring, but rest assured, development has resumed!

We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be a duplicate of one we've already migrated to Discourse:

https://community.getmailspring.com/t/institutional-office365-not-working/48

Please consider joining that community and continuing the discussion there.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-01-30 00:43 UTC
Labels: audit, enhancement, mailserver-incompatibility, product-direction
