### ISSUE TITLE
Shows e-mail content blank

### ISSUE THREAD

**Issue by konrei** [Foundry376/Mailspring#1341] opened 2019-01-28 11:48 UTC
##### Are there any related issues?

I searched but I only found one issue that is similiar to mine: [#1055](https://github.com/Foundry376/Mailspring/issues/1055)
...

##### What operating system are you using?

**kernel**: 4.19.0-1-amd64 x86_64 **bits**: 64 **compiler**: gcc **v**: 6.3.0 **Desktop**: Xfce 4.12.3 **Distro**: MX-18_x64 Continuum Dec 20 2018 **base**: Debian GNU/Linux 9 (stretch) 

...

##### What version of Mailspring are you using?

1.5.5

...

--

**Bug?**

##### Is this an email sync or connection issue?

No

...

##### Is the issue related to a specific email provider (Gmail, Exchange, etc.)?

No

...

##### Is the issue reproducible with a particular attachment, message, signature, etc?

![screenshot](https://user-images.githubusercontent.com/32584232/51834635-f5628e00-230b-11e9-8d31-ba94f9f15a98.jpg)

...

**Comment by bengotow** [comment] 2019-02-05 05:57
Hey! Thanks for reporting this - do you see this on all your email, or just this message?

**Comment by wheldrak3** [comment] 2019-02-06 14:34
Actually, I'm seeing this randomly. Some messages appears like this, some messages do not. 

I quite liked the design and the features of Mailspring. Without a doubt, the best e-mail client yet. I hope these bugs are going to be fixed and we'll have a great program at the end. 

Thank you :)

**Comment by CodeMouse92** [comment] 2021-02-02 02:07
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/many-emails-appear-white-empty/426/2

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored. Please consider joining the Discourse community and continuing the discussion there.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-02 02:07 UTC
Labels: audit
