### ISSUE TITLE
Bug: The mailspring program does not support RTL languages

### ISSUE THREAD

**Issue by RezaSh13** [Foundry376/Mailspring#2043] opened 2020-06-06 09:52 UTC
The mailspring program does not support RTL languages such as Persian or Arabic
And if possible, use the vazir font for Persian

https://github.com/rastikerdar/vazir-font

![2020-06-06_14-04](https://user-images.githubusercontent.com/22277992/83941379-142a3c00-a800-11ea-8c0f-db675d17bf52.png)

![image](https://user-images.githubusercontent.com/22277992/83941439-80a53b00-a800-11ea-8076-b556c4994b42.png)

**Comment by CodeMouse92** [comment] 2021-02-23 21:38
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/rtl-problem-in-the-subject-section/741

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@RezaSh13: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-23 21:38 UTC
Labels: audit, bug
