### ISSUE TITLE
Mail rules is slow

### ISSUE THREAD

**Issue by psivesely** [Foundry376/Mailspring#1551] opened 2019-06-28 08:19 UTC
##### What operating system are you using?
 
Debian 10

##### What version of Mailspring are you using?

1.6.2

**Feature Request?**

I just tested a single mail rule which moves messages with a certain string in the subject from my inbox to a special folder. It processed my inbox at about 100 messages/second, which is not unbearable, but you could be doing much better. I presume if the rule was for the message body it could be worse. I think an improvement of at least one order of magnitude, if not two, should be possible. Maybe integrating something like Lucene or Xapian could give a lot of performance benefits for mail rules and general search as well.

**Comment by bengotow** [comment] 2019-07-01 00:38
Hey! Yeah, I hear you—right now all mail rules run with the message bodies loaded, which is why it's so slow. (And why it operates so slowly when new mail arrives.) I think that if we only allowed rules based on headers it'd be much much faster. I'll take a look and see if there are any quick wins though. I think that we also intentionally throttle how fast they run to ensure the app is still usable while they're processing, but that may not be super necessary since a few other major changes have been made in the last few years.

**Comment by CodeMouse92** [comment] 2021-02-26 16:53
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mail-rules-is-slow/820

Please consider joining that community and continuing the discussion there! **Votes on the feature suggestion on Discourse will increase the likelihood we implement this.**

@psivesely: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-26 16:53 UTC
Labels: audit, enhancement
