### ISSUE TITLE
Mailspring will reset its window size after restart.

### ISSUE THREAD

**Issue by krehak** [Foundry376/Mailspring#1582] opened 2019-07-18 19:35 UTC
##### Are there any related issues?

I haven't found anything.

##### What operating system are you using?

Windows 10

##### What version of Mailspring are you using?

1.6.3

--

**Bug?**

Start software, maximize window (or just set bigger size), close it, restart PC, start it and Mailspring has its defaults size.

**Comment by patrickaldis** [comment] 2019-11-23 10:31
Have exactly the same problem. When the os loads it fills the screen, becomes rather frustrating.

OS - Windows 10
Mailspring Ver - 1.7.2

**Comment by Kaos-Industries** [comment] 2020-05-17 22:40
This shouldn't still be an issue. When needing to send more than 50 emails, maximising the window before composing each individual email is a ridiculous time hog, and it's not what I'm paying $8 a month for.

**Comment by GrangeBeach** [comment] 2020-06-24 09:28
same here for me in windows 10 - is there no workaround ?

**Comment by tstizzle** [comment] 2021-02-09 17:53
same problem.

**Comment by CodeMouse92** [comment] 2021-02-09 20:57
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

As part of this, we've migrated this issue to Discourse:

https://community.getmailspring.com/t/mailspring-will-reset-its-window-size-after-restart/524

Please consider joining that community and continuing the discussion there! **Votes on the issue on Discourse will help raise its priority in our planning.**

@krehak: if you join and reply to the issue, the moderators can make an effort to reassign your posts to you, so you get the credit for them.

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-09 20:57 UTC
Labels: audit
