### ISSUE TITLE
Bug: Files not being attached to any emails. Blank window is displayed when 'preview' is clicked on.

### ISSUE THREAD

**Issue by leckyneil** [Foundry376/Mailspring#2044] opened 2020-06-06 16:27 UTC
**Describe the bug**
A clear and concise description of what the bug is. Does it happen with all email accounts, or only a particular account and/or email message?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Setup: (please complete the following information):**
 - OS: [e.g. macOS, Fedora Linux]
 - OS Version [e.g. 14]
 - Mailspring Version: ex: 1.6.2 (found in the app's menu)

**Additional context** 
Add any other context about the problem here. If this issue is related to a particular account or email service, be sure to mention it so this report is actionable!

**Comment by CodeMouse92** [comment] 2021-02-04 23:09
We are in the process of migrating issues to Discourse, which can better facilitate discussion and discovery, and so GitHub Issues can focus on issues that are confirmed and slated for resolution in the near term. [Learn more about the changes here.](https://community.getmailspring.com/t/mailspring-community-transition/38)

This issue appears to be related to one we've already migrated to Discourse:

https://community.getmailspring.com/t/attached-files-not-sent/468

We're closing and locking the issue here as part of this migration. Rest assured, this doesn't mean the issue is being discarded or ignored.

Please consider joining the Discourse community and continuing the discussion there. **Votes on the issue on Discourse will help raise its priority in our planning.**

We hope to see you on Discourse soon!

-The Mailspring Team

**Closed by CodeMouse92** 2021-02-04 23:09 UTC
Labels: audit, bug
